### PR TITLE
Improve argument escaping when running external commands for non-literals

### PR DESCRIPTION
**Pull request by CBenoit**
Quotes were not added even when argument contained parenthesis.

A quick way to test is the following oneliner:

> echo "test()" | ^echo $it

Without this fix, the following error is reported:
```
sh: -c: line 0: syntax error near unexpected token `('
sh: -c: line 0: `echo test()'
```

Were we expect "test()" to be printed.

### CODE REVIEW

**Comment by CBenoit** [comment]
Regarding my last commit. It addresses the following:

# Characters causing unexpected EOF

```
echo "ab'cd" | ^echo $it
```

> sh: -c: line 0: unexpected EOF while looking for matching `''

```
echo `ab"cd` | ^echo $it
```

> sh: -c: line 0: unexpected EOF while looking for matching `"'

```
echo "ab(cd" | ^echo $it
```

> sh: -c: line 0: syntax error near unexpected token `('

# Unexpected glob interpretation

Assume you have folders "ab\*cd" and "abxcd".
You expect to list content of "ab*cd" only with
```
^ls "ab*cd"
```
However, both will be listed with
```
echo "ab*cd" | ^ls $it
```
> 'ab*cd':
> somefile.txt
>
> abxcd:
> otherfile.txt

Similar issues might be caused with `?`, `[` and `\`.

# Missing quotes

Assume you have a folder named `"abcd"` (in zsh you just have to enter `mkdir \"abcd\"`).
You can't list content using
```
echo `"abcd"` | ^ls $it
```
> ls: cannot access 'abcd': No such file or directory

You can list using built-in `ls` of course:
```
ls `"abcd"`
```

Same goes for a file or a folder name `'abcd'`.

We can add `\` before any `'` and `"` to fix this.

# How to solve this

- `(`, `'` and glob patterns are escaped by surrounding with `"`.
- `"` are escaped by adding `\` before

I believe this can safely be applied to any non-literal argument unconditionally.

On the other hand, literal arguments are fine the way they are interpreted right now, so this shouldn't be applied to literals.

```
^ls ab*cd
```

> 'ab*cd':
> somefile.txt
>
> abxcd:
> otherfile.txt


# Last remark

Maybe it would be better to make `evaluate_baseline_expr` returns `(Value, bool)` with the bool indicating that the arg is a literal, so that we don't need to match twice. However, I didn't quite like the fact that one can't know what the boolean is supposed to mean without looking a the code or documentation. Alternatively a struct can be used instead. Anyway for now it matches twice.

Please, let me know what you think about this.

**Comment by jonathandturner** [comment]
Looks like you're hitting some clippy lints:

```
error: explicit lifetimes given in parameter types where they could be elided (or replaced with `'_` if needed by type declaration)
   --> crates\nu-cli\src\commands\classified\external.rs:518:1
    |
518 | fn escape_double_quotes<'a>(argument: &'a str) -> Cow<'a, str> {
    | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |
    = note: `-D clippy::needless-lifetimes` implied by `-D warnings`
```

You can check these locally with `cargo clippy --all --features=extra`

**Comment by CBenoit** [comment]
Woops. I fixed this and clean up history.

**Comment by jonathandturner** [comment]
Looks good!

**Pull request merged**
