### PR TITLE
Fix path_contains_hidden_folder

### PR DESCRIPTION
**Pull request by nibon7**
# Description

No need to convert `Path` to `&str` and the convention may return None if `Path` contains non-UTF-8 strings.

# Tests

Make sure you've done the following:

- [ ] Add tests that cover your changes, either in the command examples, the crate/tests folder, or in the /tests folder.
- [ ] Try to think about corner cases and various ways how your changes could break. Cover them with tests.
- [ ] If adding tests is not possible, please document in the PR body a minimal example with steps on how to reproduce so one can verify your change works.

Make sure you've run and fixed any issues with these commands:

- [x] `cargo fmt --all -- --check` to check standard code formatting (`cargo fmt --all` applies these changes)
- [x] `cargo clippy --workspace --features=extra -- -D warnings -D clippy::unwrap_used -A clippy::needless_collect` to check that you're using the standard code style
- [x] `cargo test --workspace --features=extra` to check that all the tests pass

### CODE REVIEW

**Comment by onthebridgetonowhere** [comment]
Maybe we should add some extra tests here, or do we already have tests for this?

**Comment by nibon7** [comment]
> Maybe we should add some extra tests here, or do we already have tests for this?

`ls` itself will not panic since it just ignore non-UTF-8 filenames
https://github.com/nushell/nushell/blob/2cffff0c1bd8e155d1718702f25e5f99c2f4ff74/crates/nu-glob/src/lib.rs#L419-L432

```
/home/nibon7/demo/non_utf8_names〉ls                                                                                                               07/29/2022 05:38:09 PM
warning: get non-utf8 filename "/home/nibon7/demo/non_utf8_names/./\u{7}Đ\xBC", ignored.
warning: get non-utf8 filename "/home/nibon7/demo/non_utf8_names/./\u{18}\u{f}\xC9\u{f}", ignored.
warning: get non-utf8 filename "/home/nibon7/demo/non_utf8_names/./1\u{16}s\xD0", ignored.
warning: get non-utf8 filename "/home/nibon7/demo/non_utf8_names/./4z\xF5\xC3", ignored.
warning: get non-utf8 filename "/home/nibon7/demo/non_utf8_names/./{\xE19\xDA", ignored.
warning: get non-utf8 filename "/home/nibon7/demo/non_utf8_names/./\x958\u{18}^", ignored.
warning: get non-utf8 filename "/home/nibon7/demo/non_utf8_names/./\xE8\xF3\xCAo", ignored.
warning: get non-utf8 filename "/home/nibon7/demo/non_utf8_names/./\xEE\xF8\xF1}", ignored.
warning: get non-utf8 filename "/home/nibon7/demo/non_utf8_names/./\xF9\xD5x\xD7", ignored.
Error:
  × No matches found for ./*
  help: no matches found
```

But test function `path_contains_hidden_folder` standalone, it panics.
```diff
diff --git a/crates/nu-command/src/filesystem/ls.rs b/crates/nu-command/src/filesystem/ls.rs
index a3ac0eed4..bc988ba46 100644
--- a/crates/nu-command/src/filesystem/ls.rs
+++ b/crates/nu-command/src/filesystem/ls.rs
@@ -505,6 +505,23 @@ fn path_contains_hidden_folder(path: &Path, folders: &[PathBuf]) -> bool {
     false
 }

+#[cfg(test)]
+#[cfg(unix)]
+#[test]
+fn test_path_contains_hidden_folder() {
+    use self::path_contains_hidden_folder;
+    use std::ffi::OsStr;
+    use std::os::unix::ffi::OsStrExt;
+    use std::path::Path;
+
+    let v: [u8; 4] = [0, 159, 146, 150];
+    let s = OsStr::from_bytes(&v);
+    let path = Path::new(s);
+    let paths = vec![path.to_owned()];
+
+    assert!(path_contains_hidden_folder(&path, &paths));
+}
+
 #[cfg(unix)]
 use std::os::unix::fs::FileTypeExt;
 use std::path::Path;
```

**Comment by onthebridgetonowhere** [comment]
Awesome, thanks for the extra test!

**Comment by fdncred** [comment]
thanks

**Comment by bobhy** [comment]
@nibon7, sorry for the late question.  The test you added in this PR is now failing in my local repo, on the `main` branch, so not due to my own code changes.  Can you offer any suggestions for me debugging this?

```
> git log
commit c925537c48ffa2bd927dd33f30af462483fea657 (HEAD -> main, upstream/main, upstream/HEAD)
Author: Stefan Holderbach <sholderbach@users.noreply.github.com>
Date:   Wed Oct 11 21:28:18 2023 +0200

> cargo test --package nu-command
 . . .
failures:

---- commands::ls::list_directory_contains_invalid_utf8 stdout ----
thread 'commands::ls::list_directory_contains_invalid_utf8' panicked at 'failed to create directory: Os { code: 84, kind: Uncategorized, message: "Invalid or incomplete multibyte or wide character" }', crates/nu-command/tests/commands/ls.rs:619:43
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace


failures:
    commands::ls::list_directory_contains_invalid_utf8

test result: FAILED. 1227 passed; 1 failed; 21 ignored; 0 measured; 0 filtered out; finished in 5.83s

error: test failed, to rerun pass `-p nu-command --test main`
```

It doesn't fail in CI, I think because these package tests are not run.
Could it have something to do with newer rust toolchain?

**Pull request merged**
