### PR TITLE
nu-cli: added tests for file completions

### PR DESCRIPTION
**Pull request by herlon214**
# Description

Adding tests for file completions in order to have consistency while we're adding new completions. I will write more tests for the others soon.

Let me know if there's any other use case I should add into this file completions tests.

# Tests

Make sure you've run and fixed any issues with these commands:

- [X] `cargo fmt --all -- --check` to check standard code formatting (`cargo fmt --all` applies these changes)
- [X] `cargo clippy --all --all-features -- -D warnings -D clippy::unwrap_used -A clippy::needless_collect` to check that you're using the standard code style
- [x] `cargo build; cargo test --all --all-features` to check that all the tests pass

### CODE REVIEW

**Comment by herlon214** [comment]
hmmm, interesting, the CI shouldn't fail... probably something to do with the sorting

```
     Running tests/test_completions.rs (target/debug/deps/test_completions-2b7554d3972bf701)

running 1 test
test file_completions ... ok

test result: ok. 1 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.01s
```

i will take a look

**Comment by herlon214** [comment]
I needed to add that extra ascending sort before levenshtein, otherwise the results were coming in some sort of random order.

I know it's not ideal, I would like to hear your suggestions.

**Comment by herlon214** [comment]
Waiting on https://github.com/nushell/nushell/pull/5228 because that makes some good changes in order to have predictable results.

**Comment by jntrnr** [comment]
I think it's fine to sort twice for now. We don't often have giant lists of completions, so for the common case I think most people won't notice.

Thanks for getting us going on completion tests!

**Pull request merged**
