### PR TITLE
Fix `$in` in blocks given to `any` and `all`

### LINKED ISSUE #6917: `any` and `all` do not set $in correctly
### Describe the bug

It's known that the block iteration construct `each` sets the $in value on each loop, saving you the necessity of creating a variable for it using `|e|` notation. However, `any` and `all` do not do this.

### How to reproduce

```
〉[1 2 3] | each { print ($in | describe) }
int
int
int
〉[1 2 3] | any { print ($in | describe) }
nothing
nothing
nothing
false
〉[1 2 3] | all { print ($in | describe) }
nothing
false
```
As you can see, $in in the second and third examples is set to `null` incorrectly.

### Expected behavior

I expect $in to be the item being passed in to the block.

### Screenshots

_No response_

### Configuration

| key                | value                                           |
| ------------------ | ----------------------------------------------- |
| version            | 0.70.1                                          |
| branch             | edited-messages                                 |
| commit_hash        | a4edd88425ade5f3fae2bfb3e93700589e45ce61        |
| build_os           | windows-x86_64                                  |
| build_target       | x86_64-pc-windows-msvc                          |
| rust_version       | rustc 1.63.0 (4b91a6ea7 2022-08-08)             |
| rust_channel       | 1.63.0-x86_64-pc-windows-msvc                   |
| cargo_version      | cargo 1.63.0 (fd9c4297c 2022-07-01)             |
| pkg_version        | 0.70.1                                          |
| build_time         | 2022-10-23 15:18:10 +10:00                      |
| build_rust_channel | debug                                           |
| features           | database, dataframe, default, trash, which, zip |
| installed_plugins  |                                                 |

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by webbedspace**
# Description

Closes #6917. A fix of a couple of lines.

# Tests

Make sure you've done the following:

- [x] Add tests that cover your changes, either in the command examples, the crate/tests folder, or in the /tests folder.
- [x] Try to think about corner cases and various ways how your changes could break. Cover them with tests.
- [x] If adding tests is not possible, please document in the PR body a minimal example with steps on how to reproduce so one can verify your change works.

Make sure you've run and fixed any issues with these commands:

- [x] `cargo fmt --all -- --check` to check standard code formatting (`cargo fmt --all` applies these changes)
- [x] `cargo clippy --workspace --features=extra -- -D warnings -D clippy::unwrap_used -A clippy::needless_collect` to check that you're using the standard code style
- [x] `cargo test --workspace --features=extra` to check that all the tests pass

# Documentation

- [x] If your PR touches a user-facing nushell feature then make sure that there is an entry in the documentation (https://github.com/nushell/nushell.github.io) for the feature, and update it if necessary.

### CODE REVIEW

**Comment by rgwood** [comment]
Thanks for this PR.

I'm not 100% confident _why_ this change works, I need to dig into the mechanics of `$in` a little more. Will aim to do that today, but if any other Nu developers are familiar with this area please jump in.

**Comment by rgwood** [comment]
OK, most of this makes sense to me now. We take the value and pass it into the evaluated block as input, sounds good. 👍 

But I'm uncertain about the stack bits:

```rust
let orig_env_vars = stack.env_vars.clone();
let orig_env_hidden = stack.env_hidden.clone();
...
stack.with_env(&orig_env_vars, &orig_env_hidden);
```

It seems like you're taking the environment variables from the stack, cloning them, and then adding them to the stack again. I might be missing something; what's the purpose of that?

**Comment by webbedspace** [comment]
Those were something I added from `each`'s implementation that seemed like it might be necessary. In practice, though, I can't see any difference, so I'll remove them.

**Comment by webbedspace** [comment]
Actually, I've figured out the purpose of those lines now. This is the output when the lines are present:
```
C:\Coding\nushell〉[1 2 3] | any { print $env.PWD | cd '~' | false }
C:\Coding\nushell
C:\Coding\nushell
C:\Coding\nushell
```
This is the output when the lines are absent:
```
C:\Coding\nushell〉[1 2 3] | any { print $env.PWD | cd '~' | false }
C:\Coding\nushell
C:\Users\Leon
C:\Users\Leon
```
In short, the lines create a new Env for each iteration, and changes to things like the CWD don't carry over.

`each` uses the former behaviour, so I assume that's the intended behaviour.

**Comment by rgwood** [comment]
Ah, that makes sense. Yeah I agree that changes to the env vars probably shouldn't carry over.

**Pull request merged**
