### PR TITLE
Add human, precision commands

### PR DESCRIPTION
**Pull request by bailey-layzer**
Addresses #2033 

There could be a bit more testing on behaviors in different locales, but I wasn't sure how to proceed since possible values for `LC_NUMERIC` will depend on the system. `examples_work_as_expected` for human may fail depending on the system. I've left another TODO in human.rs about num-format requiring Clang 3.9+ on Windows - I couldn't figure out if this was already required (and what to do if it's not).

### CODE REVIEW

**Comment by jonathandturner** [comment]
It's cool to see work going into nicer number support. Having better precision is going to be great.

I was a little confused by the name `human` as a command. Can you say a bit more about that?

**Comment by fdncred** [comment]
@jonathandturner `df -h`, `du -h` in those regular *nix command the `-h` is for `human readable`, as found in `man` - typically this is expressed with `1K, 243M, 2G` but it can also be expressed with the number separator like `1,000,000`.

**Comment by bailey-layzer** [comment]
Yeah, the name came from @fdncred's suggestion to implement the --human flag. Summarize seems like it could work well as an option under a unified command - just trying to think of something clearer than `print` given `format` already does something else.

**Comment by jonathandturner** [comment]
@bailey-layzer - we're interested, if you're still interested in working on it.

**Comment by jonathandturner** [comment]
@bailey-layzer - to your question, I think @fdncred was suggesting we have commands that can do the formatting, and then you could call those commands from `format`.

We tend to add commands, and then refine over time as we get more experience with using them.

**Comment by bailey-layzer** [comment]
@jonathandturner that makes sense. Sorry for the mess - I made a new pull request to fix my git history in case the platform issues take a bit of time.

**Pull request closed without merging**
