### PR TITLE
add support for Vim motions in `explore`

### PR DESCRIPTION
**Pull request by amtoine**
related to
- https://github.com/nushell/nushell/issues/7819

# Description
this PR does not quite address https://github.com/nushell/nushell/issues/7819 because it does not implement configurable keybindings for `explore` but rather only adds support for Vim-like motions *out of the box*.

# User-Facing Changes
in *view* and *cursor* modes,
- `h`, `j`, `k` and `l` give standard Qwerty-based Vim motions
- `g` and `G` go to the top and the end respectively
- `u` and `d` scroll up and down

> **Note**
> the bindings do not support the use of modifiers for now, so it's not `c-u` and `c-d` which scroll pages but rather `u` and `d`

# Tests + Formatting

# After Submitting

### CODE REVIEW

**Comment by sholderbach** [comment]
There is nothing stopping you technically from using `key.modifiers` in a match guard right?

**Comment by fdncred** [comment]
If it's important that we support ctrl+u and ctrl+d, we could remove this part https://github.com/nushell/nushell/blob/af82eeca72707b56476e335cb624df8864ff68c5/crates/nu-explore/src/pager/mod.rs#L744-L748

**Comment by amtoine** [comment]
@fdncred 
- 765c00bc5 should disable `ctrl + d` for quitting
- 990704c75 should allow `ctrld + u` and `ctrl + d` to page up and down

:yum:

**Comment by fdncred** [comment]
I added breaking change since ctrl+d doesn't exit. I think we should move forward with this to see if we can live without ctrl+d. Although, in my mind, having vim motions pushes explore even _more_ in the modal direction that we're trying to get away from. Whatev.

**Pull request merged**
