### PR TITLE
Adds mimalloc as default feature.

### PR DESCRIPTION
**Pull request by FilipAndersson245**
# Description

This PR makes `mimalloc` the default allocator, it has been the default on the nightly builds of nushell now for a couple of months and the performance improvements are quite nice, measuring upwards of 30% faster startup time on Windows, and a bit smaller on Linux, https://github.com/nushell/nushell/pull/9415

# User-Facing Changes

# Tests + Formatting

# After Submitting

### CODE REVIEW

**Comment by amtoine** [comment]
@fdncred
i think you are our *mimalloc* expert, right? :yum:

**Comment by fdncred** [comment]
@amtoine I'm not expert but I run nushell exclusively with extra,dataframe,mimalloc features on Windows, MacOS, and Ubuntu. I've had no issues whatsoever related to it. I'd be for making this default, but I have a suspicion that @jntrnr would be against it. JT said a while back that we should improve performance in other ways first. I could be wrong.

**Comment by ChrisDenton** [comment]
The default Windows allocator is slow but perhaps even more troubling is that all allocations are synchronized across thread. This can negate many of the perf advantages of multithreading unless you're very careful with every alloc/dealloc. Which is why I'd make the case for switching now. The patterns used to optimize around the Windows allocator may be very different to other allocators.

This is all imho, of course.

**Comment by fdncred** [comment]
Let's go!

**Pull request merged**
