### PR TITLE
update reedline

### PR DESCRIPTION
**Pull request by maxomatic458**
update to support the latest reedline changes from https://github.com/nushell/reedline/pull/696

### CODE REVIEW

**Comment by fdncred** [comment]
can you also do a `cargo update -p reedline` so the cargo.lock file is updated to the latest reedline main commit?

**Comment by maxomatic458** [comment]
i've ran that already

**Comment by fdncred** [comment]
oops, sorry. i missed that.

**Comment by fdncred** [comment]
Thanks so much @maxomatic458. We really appreciate your help!

**Pull request merged**
