### PR TITLE
nu-cli/completions: support record for custom completion

### PR DESCRIPTION
**Pull request by herlon214**
# Description

This PR adds support for returning a `Record { value: "", description: "" }` for custom completions.

Fix https://github.com/nushell/nushell/issues/5291

[asciicast](https://asciinema.org/a/R3OBqJO2b6mzYgFGMLpQq8EyC)

# Tests

Make sure you've run and fixed any issues with these commands:

- [X] `cargo fmt --all -- --check` to check standard code formatting (`cargo fmt --all` applies these changes)
- [X] `cargo clippy --all --all-features -- -D warnings -D clippy::unwrap_used -A clippy::needless_collect` to check that you're using the standard code style
- [X] `cargo build; cargo test --all --all-features` to check that all the tests pass

### CODE REVIEW

**Comment by fdncred** [comment]
nice!

**Comment by elferherrera** [comment]
Very nice

**Comment by herlon214** [comment]
@elferherrera the description is actually optional, if no `value` is provided it should keep the default one (empty).
For the comment in the extern I'm not sure, never dealt with that comment parsing logic (yet 😅 )

**Comment by fdncred** [comment]
let's go!

**Pull request merged**
