### PR TITLE
Change `cd` and `pwd` to use logical path by default

### PR DESCRIPTION
**Pull request by YizhePKU**
# Description

Change the behavior of `cd` and `pwd` to use logical paths by default. A switch is added to both commands to force the use of physical paths.

```nu
mkdir /tmp/foo
ln -s /tmp/foo /tmp/foo_link

cd /tmp/foo_link
pwd                  # /tmp/foo_link
pwd -P               # /tmp/foo

cd -P /tmp/foo_link
pwd                  # /tmp/foo
```

Fixes issue #2175.

# User-Facing Changes
The default behavior of `cd` and `pwd` changes, also they both gained a switch `--physical` or `-P`.

# Tests + Formatting

Test cases for `cd` are updated to reflect the new behavior. No test cases exist for `pwd`, but it's simple enough that it shouldn't be necessary.

# After Submitting

I'm not sure how much this will break things. Judging from the comments from #2175, it shouldn't break too much.

Is there any documentation that needs updating?

### CODE REVIEW

**Comment by sholderbach** [comment]
If we change `PWD` we will need to vet our internal path expansions, that for now could assume it, if any operation we are doing with them depends on an absolute physical path.

**Comment by YizhePKU** [comment]
I spent over an hour trying to analyze the "reverse call stack" of PWD. Most operations that act on PWD later canonicalize the path again, so the change has no effect on them. I've found a few more interesting behaviors:

* The auto-cd feature seems to behave inconsistently when the target is a symlink
* Plugins now receive new PWD values from engine calls

Also, I discovered some unrelated issues during investigation:
* `rm ~` protection can be worked around by using symlinks
* `load-env { PWD: foo }` doesn't work, but `{ PWD: foo } | load-env` does
* There're seven different APIs for retriving PWD (!)
* `env::current_dir_str()` reads PWD from the stack while `env::current_dir_str_const()` reads PWD from the working set, which makes no sense to me

Here are the seven APIs I was talking about:
* `EngineState::get_cwd()` (unused)
* `EngineState::current_work_dir()`
* `StateWorkingSet::get_cwd()`
* `env::current_dir_str()`
* `env::current_dir_str_const()`
* `env::current_dir()`
* `env::current_dir_const()`

I probably missed something in my analysis due to the sheer complexity of everything (I didn't even look at the standard library, which can use `$env.PWD`). I feel like the technical debt is starting to take its toll...

**Comment by sholderbach** [comment]
Thanks for the in-depth investigation!

- good to know that most operations take care of canoncialization.
- The `rm` check and `load-env` `PWD` protections should certainly be fixed
- There may be an intended restriction for `const` evaluation. But @kubouch is probably our expert there which value should be read there.
- simplifying the number of env var related helpers is certainly desirable, as long as we cover all the necessary semantics properly.
- Related but not immediately relevant: We should probably lint against free use of the `std::env` functions with a `clippy.toml` and `disallowed-methods` as we have distinct environment semantics and the engine should manage the transfer into the system state.

**Comment by YizhePKU** [comment]
> There may be an intended restriction for const evaluation. But @kubouch is probably our expert there which value should be read there.

I'm particularly interested in the purpose of `Stack`. From its documentation, it seems that `Stack` gradually lost its purpose during development. Maybe it's possible to refactor it away?

**Comment by kubouch** [comment]
> env::current_dir_str() reads PWD from the stack while env::current_dir_str_const() reads PWD from the working set, which makes no sense to me

The const variant is for const eval context, the stack is used in normal runtime. If we could reduce the number of cwd-fetching APIs, it would be great. The ones from EngineState should probably be removed as it can be error-prone fetching stuff from the permanent state disregarding the eval context (either Stack or StateWorkingSet).

The reason for the `_str` variants is just API convenience. Otherwise, the EngineState/StateWorkingSet methods likely exist to be used in the parser which doesn't (or shouldn't) have the engine dependency. We could e.g. move the `env::current_dir()` and friends to `nu-protocol` and get rid of all the EngineState/StateWorkingSet methods

> I'm particularly interested in the purpose of Stack. From its documentation, it seems that Stack gradually lost its purpose during development. Maybe it's possible to refactor it away?

Stack is necessary to hold runtime values of variables and env variables.

> Related but not immediately relevant: We should probably lint against free use of the std::env functions with a clippy.toml and disallowed-methods as we have distinct environment semantics and the engine should manage the transfer into the system state.

+1

Otherwise, I'm good with this, it's quite annoying to always cd into the fully resolved path. To me, it seems that `$env.PWD` will always be an absolute path, but sometimes without resolved symlinks. If we make sure that we canonicalize everywhere where we use cwd, I'm fine merging this. For example, we could change `env::current_dir()` etc. to always canonicalize.

If someone insists on the old behavior, they can do `alias cd = cd -P`.

**Comment by kubouch** [comment]
I'm still slightly worried about `$env.PWD` not being a canonicalized path which was always assumed throughout the code and functions like `env::current_dir()` rely on it. On the other hand, the path should always be absolute, just sometimes with unresolved symlinks, so maybe it would be fine. One solution I'm thinking, just to be on the safe side, is to make sure `env::current_dir()` and friends return canonicalized physical path so that we do not change the assumption. We could e.g. maintain `$env.PHYSICAL_PWD` that would be queried instead of `$env.PWD`.

I'm just being extra cautious around it, as the current directory is one of the most important things to get right.

**Comment by YizhePKU** [comment]
How about this: we change `$env.PWD` to no longer be a canonicalized path, but keep the current behavior of `env::current_dir()`, by canonicalizing `$env.PWD` within `env::current_dir()`. Then we mark `env::current_dir()` as deprecated, and gradually migrate to a new API that returns non-canonicalized path instead.

This way we get a smooth transition process: we can check all usages of `env::current_dir()` one by one to make sure nothing break. As a bonus, this also eliminates the "too many APIs" problem.

**Comment by kubouch** [comment]
Yes, I agree, but is there a need for a new API returning potentially unresolved paths? We could make `env::current_dir()` (and all the current dir helpers) to always return a resolved physical path and only add the new API if there is an actual need for it.

It should probably be done via https://doc.rust-lang.org/std/fs/fn.read_link.html. The `$env.PWD` should already be absolute, the only step missing is resolving the symlink.

**Comment by YizhePKU** [comment]
> Is there a need for a new API returning potentially unresolved paths?

Yes. We want `cd` to use logical path, and we can't do that without an API that returns potentially unresolved paths.

> We could make `env::current_dir()` (and all the current dir helpers) to always return a resolved physical path and only add the new API if there is an actual need for it.

`env::current_dir()` will always return a resolved physical path. However, once we have an API that returns potentially unresolved paths, `env::current_dir()` and friends should become much less relavant. From my investigations, most usages of `env::current_dir()` don't care if the path is resolved or not.

Additionally, `env::current_dir()` will be slower than the new API. Since `$env.PWD` will be an unresolved path and presumably we don't want to store two `PWD`, we have to canonicalize everytime `env::current_dir()` is called.

> It should probably be done via https://doc.rust-lang.org/std/fs/fn.read_link.html.

I don't think that works. `read_link()` only works on the symbolic link itself, not a path that contains symbolic links in its components. For example, if `/tmp/link` points to a directory `/tmp/foo`, then we can use `read_link()` on `/tmp/link` but not `/tmp/link/bar`.

**Comment by kubouch** [comment]
> Yes. We want `cd` and `pwd` to use logical path, and we can't do that without an API that returns potentially unresolved paths.

This is currently done inside the `cd` command in your PR. But having an API for that would be nice.

> From my investigations, most usages of `env::current_dir()` don't care if the path is resolved or not.

Yeah, we need to make sure about that. If that's the case, we can just use the new API.

> I think the correct answer is still `fs::canonicalize()`.

Makes sense. Let's use that, then, but there should be a check or assert that makes sure that we're canonicalizing an absolute path. It would probably be best to wrap it into `nu_path::resolve_symlinks(path)` or similar to avoid littering freestanding `canonicalize()` around the codebase.

So yeah, your plan sounds good. I'll mark it as a draft to avoid accidental merge.

**Comment by tesujimath** [comment]
Thanks for this PR @YizhePKU  :heart_eyes: 

FYI I started a discussion in #12628 about canonicalize in general (which I am surprised GitHub didn't automatically link).  I think there's more work to be done in this whole area.  I like what you're doing here and in #12603.

**Comment by kubouch** [comment]
I think this PR needs to be landed after https://github.com/nushell/nushell/pull/12603 and use the new cwd API from that PR, right?

**Comment by YizhePKU** [comment]
> I think this PR needs to be landed after https://github.com/nushell/nushell/pull/12603 and use the new cwd API from that PR, right?

That is correct. I'll rework this PR after the new API is available.

**Comment by YizhePKU** [comment]
I'm supposed to update this PR to use the new PWD API, but I accidentally put that part in my last PR instead. Whoops!

So now this PR can be merged as is. It only contains updated test and the `-P` switches, because the behavior was already changed in the last PR.

**Comment by fdncred** [comment]
lol, thanks.

**Pull request closed without merging**
