### PR TITLE
overhaul shell_integration to enable individual control over ansi escape sequences

### LINKED ISSUE #11301: Enable only specific shell_integration features
### Related problem

_No response_

### Describe the solution you'd like

As discussed in the Discord server:

```nu
shell_integration: {
  OSC7: true
  OSC8: true
  OSC2: true
  VSCODE: true
...
}
```

Maybe use readable names instead of the codenames as well?

### Describe alternatives you've considered

_No response_

### Additional context and details

To not be a breaking change and for ease of use, setting shell_integration to true or false would toggle all settings, and giving a record would toggle those specific features, if a features is omitted from that record it would default to false.

### PR DESCRIPTION
**Pull request by fdncred**
# Description

This PR overhauls the shell_integration system by allowing individual control over which ansi escape sequences are used. As we continue to broaden our support for more ansi escape sequences, we can't really have an all-or-nothing strategy. Some ansi escapes cause problems in certain operating systems or terminals. We should allow the user to choose which escapes they want.

TODO:
* Gather feedback
* Should osc7, osc9_9 and osc633p be mutually exclusive?
* Is the naming convention for these settings too nerdy osc2, osc7, etc?

closes #11301

# User-Facing Changes
shell_integration is no longer a boolean value. This is what is supported in the default_config.nu
```nushell
  shell_integration: {
    # osc2 abbreviates the path if in the home_dir, sets the tab/window title, shows the running command in the tab/window title
    osc2: true
    # osc7 is a way to communicate the path to the terminal, this is helpful for spawning new tabs in the same directory
    osc7: true
    # osc8 is also implemented as the deprecated setting ls.show_clickable_links, it shows clickable links in ls output if your terminal supports it
    osc8: true
    # osc9_9 is from ConEmu and is starting to get wider support. It's similar to osc7 in that it communicates the path to the terminal
    osc9_9: false
    # osc133 is several escapes invented by Final Term which include the supported ones below.
    # 133;A - Mark prompt start
    # 133;B - Mark prompt end
    # 133;C - Mark pre-execution
    # 133;D;exit - Mark execution finished with exit code
    # This is used to enable terminals to know where the prompt is, the command is, where the command finishes, and where the output of the command is
    osc133: true
    # osc633 is closely related to osc133 but only exists in visual studio code (vscode) and supports their shell integration features
    # 633;A - Mark prompt start
    # 633;B - Mark prompt end
    # 633;C - Mark pre-execution
    # 633;D;exit - Mark execution finished with exit code
    # 633;E - NOT IMPLEMENTED - Explicitly set the command line with an optional nonce
    # 633;P;Cwd=<path> - Mark the current working directory and communicate it to the terminal
    # and also helps with the run recent menu in vscode
    osc633: true
    # reset_application_mode is escape \x1b[?1l and was added to help ssh work better
    reset_application_mode: true
  }
```

# Tests + Formatting

# After Submitting

### CODE REVIEW

**Comment by rgwood** [comment]
Thanks for this one Darren.

**Comment by rgwood** [comment]
With this PR, confirmed that `osc633` is causing issues on Windows WezTerm (on every keypress, most of the screen scrolls up).

**Comment by fdncred** [comment]
I don't see osc633 being sent with escape-artist, but I do see other problems. Thanks!

**Comment by fdncred** [comment]
I did that but it was sending 133 not 633, so that was a bug. I also found some logic issues that I'm trying to fix now. I'm building release to test with escape-artist. :)

**Comment by dedebenui** [comment]
> shell_integration is no longer a boolean value.

Any reason to make this a breaking change? Would it not have been possible to interpret `shell_integration = true` as `shell_integration = <default table>`, as @RGBCube mentioned in #11301? Additionally, if the defaults change in future versions, no action would be required from the user.

**Comment by fdncred** [comment]
yup, that would've been possible. I didn't think of it.

**Comment by eliax1996** [comment]
Adding a comment here for noobs like me that didn't knew how to apply the suggested tip;
1. Run `config nu`, this will open the `nu` config file with the default editor (in my `wsl` instance the referenced file its `/home/${USERNAME}/.config/nushell/config.nu`, obtained by running `echo $nu.config-path`)
2. Insert the following in the config file:
```
$env.config = {
  shell_integration: {
    osc133: false
  }
}
```
This is an override of the [default file](https://github.com/nushell/nushell/blob/e2d0514bb57ae0b071631d880acbcb695858f67c/crates/nu-utils/src/sample_config/default_config.nu#L236C5-L263C6)
3. Reload the config by running `source $nu.config-path`

**Comment by sholderbach** [comment]
Since `0.101.0` the recommended line would be just

```nushell
$env.config.shell_integration.osc133 = false
```

(The config error recovery will recover the rest of the record values, but its both terser and more realistic in that it just sets the value you care about and doesn't imply clearing the other keys, which doesn't occurr)

**Pull request merged**
