### PR TITLE
Add Argument::span() and Call::arguments_span()

### PR DESCRIPTION
**Pull request by drbrain**
# Description

These make it easy to make a Span that covers an entire argument and the span of all arguments in a Call.

Call::arguments_span() is useful for errors where a command may accept arguments or the pipeline, but not both.

Argument::span() is useful for errors where an arguments is incompatible with one or more other arguments.

In particular, I wish to use this to create an error for an implementation of #9563 that either allows arguments to set limits:

```nushell
limits set RLIMIT_NOFILE --soft 255 --hard 1024
```

Or pipeline:

```nushell
{name: RLIMIT_NOFILE, soft: 255} | limits set
```

But not both:

```
❯ [{name: RLIMIT_NOFILE, soft: 255, hard: 1024}] | limits set AS --soft 5 --hard 5
Error: nu::shell::incompatible_parameters

  × Incompatible parameters.
   ╭─[source:1:1]
 1 │ [{name: RLIMIT_NOFILE, soft: 255, hard: 1024}] | limits set AS --soft 5 --hard 5
   · ───────────────────────┬──────────────────────              ──────────┬─────────
   ·                        │                                              ╰── or arguments, not both
   ·                        ╰── Supply either pipeline
   ╰────
```

# User-Facing Changes

Only nushell Command API changes

# Tests + Formatting

- :green_circle: `toolkit fmt`
- :green_circle: `toolkit clippy`
- :green_circle: `toolkit test`
- :green_circle: `toolkit test stdlib`

# After Submitting

N/A

### CODE REVIEW

**Comment by drbrain** [comment]
Force-pushed with a rewrite to `Call::arguments_span()` that avoids `unwrap()`.

Somehow `toolkit check pr` has not been running `cargo clippy` the same way as CI

**Comment by sholderbach** [comment]
Love the idea of some clean convenience helpers here!

**Comment by drbrain** [comment]
Is there any objection to merging this?

**Review by sholderbach — APPROVED** [review]
Looks good to me! Now familiar with the used types and things going on here.

I think we need to tweak the span computation in short flag parsing in the `parse_internal_call` logic but that is not a new issue with this PR.

**Pull request merged**
