### PR TITLE
WIP/ Checkout to new `tabled`

### PR DESCRIPTION
**Pull request by zhiburt**
Hello,

This PR must make tables faster while not break anything.

I was pointing out a few times that there were areas where `tabled` clearly could do a better job.
I did have some progress, so I wanted to show it to you so maybe you could make tests.

for example running `1..100000` (#5972) gives me `262`

cc: @fdncred

### CODE REVIEW

**Comment by fdncred** [comment]
wow, this is a lot of changes. we have a release coming up on 8/16. hopefully there's enough time to test this and publish your crate by then.

**Comment by fdncred** [comment]
@zhiburt can you rebase this on main? i want to see if the new lscolors breaks anything and i don't see it updated in your cargo.toml files

**Comment by fdncred** [comment]
Some windows testing of `1..100000`. We know windows to be much slower than Linux or Mac.
|Terminal|This PR Time|Previous Version Time|
|-|-|-|
|Windows Terminal 1.14.1963.0|5095ms|2540ms|
|WSL2 0.65.3.0|4532ms|1339ms|
|WezTerm 20220807-113146-c2fee766|5461ms|2825ms|
|Alacritty 0.10.1|17835ms|9208ms|8992ms|

**Comment by fdncred** [comment]
Sure. Here are the results with `cargo r --features=extra --release`. Looks better for some reason but not quite as good as `1040`. There's really no file io with that test so I'm not sure what could be affecting the difference between your test and mine.

|Terminal|This PR Time|
|-|-|
|Windows Terminal 1.14.1963.0|1705ms|
|WSL2 0.65.3.0|1495ms|
|WezTerm 20220807-113146-c2fee766|2331ms|
|Alacritty 0.10.1|5567ms|

**Comment by zhiburt** [comment]
So what do you think about the numbers.
They're kind of unclear right?

> not quite as good as 1040

As we know theme and color of it certainly affects it (mine was rounded + purple borders).
CPU I think too but I think mine is not very big performer (Laptop with CPU: 11th Gen Intel i7-11850H (16) @ 4.800GHz)

**Comment by fdncred** [comment]
> They're kind of unclear right? I mean it gets worse in some of your tests as well as my benchmarks.

I think the results look good to me, better in most cases.

> As we know theme and color of it certainly affects it (mine was rounded + purple borders).

Oh ya, you're right. Mine was rounded too but different color borders.

> CPU I think too but I think mine is not very big performer (Laptop with CPU: 11th Gen Intel i7-11850H (16) @ 4.800GHz)

Mine is a laptop as well. Here's my CPU, Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz   2.30 GHz, 32GB ram, NVidia Quadro RTX 4000 video card. So, mine should be pretty fast.

**Comment by fdncred** [comment]
@zhiburt We'd probably be ok landing this today if you had a published version. If not, that's fine, our next release is 8/16, so we'd probably wait until after that one. I really just don't want to cram a new thing in right before the release. It sometimes makes for problems after the release.

**Comment by zhiburt** [comment]
Seems like fixed a single line table benchmark.
Though multiline one still worse... (I even tested small unsafe block (in regard of self referencing structs), which in my mind must be very effective but it only made an increase  `~8%`).

image

**Comment by zhiburt** [comment]
Maybe it's worth to do some set of runs once again what do you @fdncred think?

**Comment by fdncred** [comment]
I'll try windows tomorrow but here's my Mac.

|Terminal|This PR Time|
|-|-|
|iterm2|2146ms|
|kitty|437ms|
|tabby|635ms|
|wezterm|315ms|
|warp|309ms|
|alacritty|247ms|
|terminal.app|509ms|

**Comment by fdncred** [comment]
I keep forgetting to test this on Windows. Is this PR just waiting for me?

**Comment by zhiburt** [comment]
> I keep forgetting to test this on Windows. Is this PR just waiting for me?

In some sense, but not exactly.
We'd need to verify that it better to justify its move otherwise it could stay not changed (maybe).
PS: wrapping performance must be improved too. (can be tested when data has bigger width than termwidth), could be nice to check it.

I have few TODOs in `tabled` and because of this it's ~1-2 week (I hope) from publishing to crates.io.
Therefore I kind of think there's not point to hurry here, right?

**Comment by fdncred** [comment]
ok. just tag me if you're waiting on me. I don't want to be a bottleneck to the process.

**Comment by fdncred** [comment]
Here's the latest for Windows

|Terminal|Last Test|This PR Time|
|-|-|-|
|Windows Terminal 1.14.1963.0|1705ms|1402ms|
|WSL2 0.65.3.0|1495ms|1262ms|
|WezTerm 20220807-113146-c2fee766|2331ms|1811ms|
|Alacritty 0.10.1|5567ms|5531ms|

**Comment by fdncred** [comment]
@zhiburt We have a release on Sept 6th. Do you think this is close to ready or should we just plan on landing it sometime after the next release?

**Comment by zhiburt** [comment]
Hi there,

Actually the main logic is already merged to master.
But there are some TODOs before the release, I would do it on next on if everything goes well.

**Comment by zhiburt** [comment]
I've added the `expand` view, but it's still WIP.

```shell
# collapsed mode
sys | table -c

# general mode
sys | table -e
```

It doesn't has any width limit logic.
Which is possible to do but...............not easy.

**Comment by zhiburt** [comment]
Also #6443 must be fixed here already

**Comment by fdncred** [comment]
> So what do you think about this table --expand and table --collapse?

I did `sys | table -e` and it hung and never finished.

> I would like to notice about it, that it's currently doesn't recognize footer/header, custom alignment of data and there's no proper width control.

I absolutely love the idea of `--expand` and `--collapse` but considering the hang I just experienced and the awkwardness of not having header/footer/alignment/width control maybe we should pull them from this PR until they're ready, as to not hold up the rest of the fixes. What do you think?

**Comment by zhiburt** [comment]
> I did sys | table -e and it hung and never finished.

Good catch.

Interesting.
I've found an issue.
It's actually a performance issue, caused by many spaces (`' '`) in the string.
We split the string by spaces and if there's many spaces.... seems like bad things happen....

I'll try to do something about it.

```nu
ls | table -e
```

> the awkwardness of not having header/footer/alignment/width control

- Header
    We have header.
- Footer
    I guess it shouldn't be hard to do just add a copy of a header as a last row into `json::Array`.
- Alignment
   Requires some work in `tabled` which possible but not sure how it would look like.
- Width
  It is working...... But probably not as you would like....
  I mean we just cut the whole thing which is make no sense.
  As I see it ideally we would need to remove some part of the table.
  But it's not quite an easy task I believe.

image

**Comment by fdncred** [comment]
`infintely slow` sounds bad - haha!

Ideally, with `| table -e` we'd have all nested tables expanded. However, the way it's working now is a bit weird. Example:
```
╭───────┬───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╮
│ cpu   │ ╭───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╮ │
│       │ │ ╭──────┬──────────────────────────────────────────────────────────────────────────────────╮                               │ │
│       │ │ │ name │ ╭───────┬──────────────────────────────────────────────────────────────────────╮ │                               │ │
│       │ │ │      │ │ brand │ ╭──────┬───────────────────────────────────────────────────────────╮ │ │                               │ │
│       │ │ │      │ │       │ │ freq │ ╭───────────┬───────────────────────────────────────────╮ │ │ │                               │ │
│       │ │ │      │ │       │ │      │ │ cpu_usage │ ╭──────────────┬────────────────────────╮ │ │ │ │                               │ │
│       │ │ │      │ │       │ │      │ │           │ │ load_average │ ╭───────────┬────────╮ │ │ │ │ │                               │ │
│       │ │ │      │ │       │ │      │ │           │ │              │ │ vendor_id │  freq  │ │ │ │ │ │                               │ │
│       │ │ │      │ │       │ │      │ │           │ │              │ ╰───────────┴────────╯ │ │ │ │ │                               │ │
│       │ │ │      │ │       │ │      │ │           │ ╰──────────────┴────────────────────────╯ │ │ │ │                               │ │
│       │ │ │      │ │       │ │      │ ╰───────────┴───────────────────────────────────────────╯ │ │ │                               │ │
│       │ │ │      │ │       │ ╰──────┴───────────────────────────────────────────────────────────╯ │ │                               │ │
│       │ │ │      │ ╰───────┴──────────────────────────────────────────────────────────────────────╯ │                               │ │
│       │ │ ╰──────┴──────────────────────────────────────────────────────────────────────────────────╯                               │ │
│       │ │ ╭───────┬──────────────────────────────────────────────────────────────────────────────────────────────────────────────╮  │ │
│       │ │ │ CPU 1 │ ╭──────────────────────────────────────────┬───────────────────────────────────────────────────────────────╮ │  │ │
│       │ │ │       │ │ Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz │ ╭───┬───────────────────────────────────────────────────────╮ │ │  │ │
│       │ │ │       │ │                                          │ │ 0 │ ╭───┬───────────────────────────────────────────────╮ │ │ │  │ │
│       │ │ │       │ │                                          │ │   │ │ 0 │ ╭──────────────────┬────────────────────────╮ │ │ │ │  │ │
│       │ │ │       │ │                                          │ │   │ │   │ │ 0.00, 0.00, 0.00 │ ╭──────────────┬─────╮ │ │ │ │ │  │ │
│       │ │ │       │ │                                          │ │   │ │   │ │                  │ │ GenuineIntel │  8  │ │ │ │ │ │  │ │
│       │ │ │       │ │                                          │ │   │ │   │ │                  │ ╰──────────────┴─────╯ │ │ │ │ │  │ │
│       │ │ │       │ │                                          │ │   │ │   │ ╰──────────────────┴────────────────────────╯ │ │ │ │  │ │
│       │ │ │       │ │                                          │ │   │ ╰───┴───────────────────────────────────────────────╯ │ │ │  │ │
│       │ │ │       │ │                                          │ ╰───┴───────────────────────────────────────────────────────╯ │ │  │ │
│       │ │ │       │ ╰──────────────────────────────────────────┴───────────────────────────────────────────────────────────────╯ │  │ │
│       │ │ ╰───────┴──────────────────────────────────────────────────────────────────────────────────────────────────────────────╯  │ │
```
There's really no need for these rectangles within rectangles within rectangles. Ideally, we'd have a table nested within a cell. Something like this:
```
╭───────┬────────────────────────────────────────────────────────────────────────────────────────────────────────────────╮
│ cpu   │╭────┬────────┬──────────────────────────────────────────┬──────┬───────────┬──────────────────┬──────────────╮ │
│       ││  # │  name  │                  brand                   │ freq │ cpu_usage │   load_average   │  vendor_id   │ │
│       │├────┼────────┼──────────────────────────────────────────┼──────┼───────────┼──────────────────┼──────────────┤ │
│       ││  0 │ CPU 1  │ Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz │    8 │      0.00 │ 0.00, 0.00, 0.00 │ GenuineIntel │ │
│       ││  1 │ CPU 2  │ Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz │    8 │      0.00 │ 0.00, 0.00, 0.00 │ GenuineIntel │ │
│       ││  2 │ CPU 3  │ Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz │    8 │      0.00 │ 0.00, 0.00, 0.00 │ GenuineIntel │ │
│       ││  3 │ CPU 4  │ Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz │    8 │      0.00 │ 0.00, 0.00, 0.00 │ GenuineIntel │ │
│       ││  4 │ CPU 5  │ Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz │    8 │      0.00 │ 0.00, 0.00, 0.00 │ GenuineIntel │ │
│       ││  5 │ CPU 6  │ Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz │    8 │      0.00 │ 0.00, 0.00, 0.00 │ GenuineIntel │ │
│       ││  6 │ CPU 7  │ Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz │    8 │      0.00 │ 0.00, 0.00, 0.00 │ GenuineIntel │ │
│       ││  7 │ CPU 8  │ Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz │    8 │      0.00 │ 0.00, 0.00, 0.00 │ GenuineIntel │ │
│       ││  8 │ CPU 9  │ Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz │    8 │      0.00 │ 0.00, 0.00, 0.00 │ GenuineIntel │ │
│       ││  9 │ CPU 10 │ Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz │    8 │      0.00 │ 0.00, 0.00, 0.00 │ GenuineIntel │ │
│       ││ 10 │ CPU 11 │ Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz │    8 │      0.00 │ 0.00, 0.00, 0.00 │ GenuineIntel │ │
│       ││ 11 │ CPU 12 │ Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz │    8 │      0.00 │ 0.00, 0.00, 0.00 │ GenuineIntel │ │
│       ││ 12 │ CPU 13 │ Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz │    8 │      0.00 │ 0.00, 0.00, 0.00 │ GenuineIntel │ │
│       ││ 13 │ CPU 14 │ Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz │    8 │      0.00 │ 0.00, 0.00, 0.00 │ GenuineIntel │ │
│       ││ 14 │ CPU 15 │ Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz │    8 │      0.00 │ 0.00, 0.00, 0.00 │ GenuineIntel │ │
│       ││ 15 │ CPU 16 │ Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz │    8 │      0.00 │ 0.00, 0.00, 0.00 │ GenuineIntel │ │
│       │├────┼────────┼──────────────────────────────────────────┼──────┼───────────┼──────────────────┼──────────────┤ │
│       ││  # │  name  │                  brand                   │ freq │ cpu_usage │   load_average   │  vendor_id   │ │
│       │╰────┴────────┴──────────────────────────────────────────┴──────┴───────────┴──────────────────┴──────────────╯ │
```
maybe without the footer?

**Comment by zhiburt** [comment]
> infintely slow sounds bad - haha!

:disappointed_relieved: 
must be fixed.

Also added footer for the main table.

image

> There's really no need for these rectangles within rectangles within rectangles. Ideally, we'd have a table nested within a cell. Something like this:

Interesting

**Comment by fdncred** [comment]
that collapsed table is looking better, although i don't really understand why the columns do not align.

on that table with the new footer and non-aligned columns, can you still do `ls | table -c | where name =~ '(?i)read'`? I'm guessing not because it kind of seems like columns are kind of lost.

**Comment by fdncred** [comment]
I"m getting the footer now but I'm still missing the |- and -| characters
image

**Comment by zhiburt** [comment]
> that collapsed table is looking better, although i don't really understand why the columns do not align.

I've already told you a few times :)
It's because we represent the table as a json array.
And elements inside array doesn't align with others.

It could be fixed if we would have a map of maps, but it implies that there would be no duplicate keys, which is not true.

> I didn't came up with good analogue schemes to do the job better than that :disappointed:
> 
> ```
> [
>   { "name": { "brand": { "cpu_usage": ... } } },
>   { "CPU 1": { "Inte(R) ...": { "0": ... } } },
>   { "CPU 1": { "Inte(R) ...": { "0": ... } } },
> ]
> ```



> on that table with the new footer and non-aligned columns, can you still do ls | table -c | where name =~ '(?i)read'? I'm guessing not because it kind of seems like columns are kind of lost.

You're correct, we can't.
As well if you would do just `ls | table | where name =~ '(?i)read'`

> I"m getting the footer now but I'm still missing the |- and -| characters

They are not missed.
Just change the theme to `thin` for example.

________

Here we go

image

**Comment by zhiburt** [comment]
With sessions

image

**Comment by fdncred** [comment]
WOW! that looks great!!!!! good job.

regarding `sessions` - One way to address this is to have a parameter that states how deeply it should try to expand. so `table -e -n 1` would only try to expand 1 level deep but `-n 2` would do 2 levels deep. Generally, I think sessions is a table within a cell but a little different too. I wouldn't find it bad if it looked like `(sys).host.sessions` (the top part). In a perfect world it might look like the flattened output on the bottom.
image

**Comment by zhiburt** [comment]
I've addressed a flatten and deep control.

```nu
sys | table --expand --expand-deep=3 --flatten --flatten-separator=", "
```

image

> Generally, I think sessions is a table within a cell but a little different too. I wouldn't find it bad if it looked like (sys).host.sessions (the top part). In a perfect world it might look like the flattened output on the bottom.

I am not sure how flatten suppose to work.

I've just make it so if it's a simple array we return a string instead a table.

**Comment by fdncred** [comment]
wow! that looks great!

**Comment by zhiburt** [comment]
Added a width control.

```nu
sys | table --expand -w 50
```

image

Not everything is well tested though and may require refactoring.

**Comment by fdncred** [comment]
very cool!

**Comment by fdncred** [comment]
I'm loving this part
Screen Shot 2022-09-30 at 7 50 53 PM

**Comment by fdncred** [comment]
I think determining the width my not be working right. I make my font smaller and I can do `term size` and get 214 columns and and 62 rows. Then I do `nu | table --expand` and it only takes up 1/2 the terminal width.

This is `$nu.scope | table --expand`
Screen Shot 2022-09-30 at 7 58 51 PM

I'm still loving it though.

**Comment by zhiburt** [comment]
> I think determining the width my not be working right. I make my font smaller and I can do term size and get 214 columns and and 62 rows. Then I do nu | table --expand and it only takes up 1/2 the terminal width.

Yes it's because the next columns are very big.
I think ideally we would need to truncate the inner table first.

image

Question: How to show empty list?

**Comment by IwateKyle** [comment]
Per request, I'm re-posting the following image to this thread.  

Where there are long entries in a table (I've only tested this with directory listings) some of the listings get circularly recycled somehow.  

image

**Comment by zhiburt** [comment]
@IwateKyle interesting.....

Thanks you for report.

I was think it was suppose to be OK :disappointed:

**Comment by fdncred** [comment]
> How to show empty list?

I'm fine with `(list 0 items)` for now. It's not too annoying, is it?

**Comment by zhiburt** [comment]
> I'm fine with (list 0 items) for now. It's not too annoying, is it?

Yes, It's kind of "unnatural" when we do expand

**Comment by fdncred** [comment]
> Yes, It's kind of "unnatural" to see it when we do expand

I'm fine with changing it in expand to an the empty item emoji, or other suggestion you have.

**Comment by zhiburt** [comment]
> I'm fine with changing it in expand to an the empty item emoji, or other suggestion you have.

Like this? (maybe not perfect emojie)

image

**Comment by fdncred** [comment]
> Like this? (maybe not perfect emojie)
> Maybe the old one is better actually.

LOL. Yes, I think the old one is better.

**Comment by zhiburt** [comment]
@IwateKyle I bet you've run it on `main` branch ?:)

@fdncred could you verify these bugs are fixed?
#6553 #6443
And could we merge it if they're fixed?

now

image

was

image

**Comment by fdncred** [comment]
#6553 = yes, fixed.
#6443 = yes, fixed.
#6592 = yes, fixed.

ok, let's land it.

**Comment by fdncred** [comment]
@zhiburt it would be awesome if you could fit in writing some announcement documentation here for the new features enabled with this PR https://github.com/nushell/nushell.github.io/pull/614 - if you don't have time, that's ok.

**Comment by IwateKyle** [comment]
@zhiburt  - sorry, actually I ran it directly from a binary install.  I will pull and build and get back with an update.

**Pull request merged**
