### PR TITLE
Fish-like completions for nested directories

### LINKED ISSUE #5683: Autocomplete paths properly
### Related problem

The new releases of nu with engine-q doesn't  handle directory commands as conveniently as previous version like 0.41.  

For example, using version 0.41.0 to handle a directory called `FooBar` , on Ubuntu 20.04

1.  Using autocomplete adds a `./` prefix when you press tab to autocomplete  `Foo` into full directory name `FooBar` but when using version 0.60+ only the `FooBar` full name is autocompleted with no `./` added prefix thereby on pressing enter an error occurs since nushell thinks it's executing a binary
```sh
Error: nu::shell::external_command (link)

  × External command
   ╭─[entry #2:1:1]
 1 │ FooBar/
   · ────────┬────────
   ·         ╰── can't run executable
   ╰────
  help: Permission denied (os error 13)
```

2. Version before engine-q like 0.41.0 are able to understand what constitutes a directory so just typing `FooBar` or `FooBar/` nushell will switch to the directory but on version `0.60+` this will return an error since it thinks binary execution is happening
```sh
Error: nu::shell::external_command (link)

  × External command
   ╭─[entry #3:1:1]
 1 │ FooBar
   · ────────┬───────
   ·         ╰── can't run executable
   ╰────
  help: No such file or directory (os error 2)

```

### Describe the solution you'd like

With new versions of nushell, reintroduce this convenience like:
1. Add a `./` prefix on autocompleting a directory 
2. Nushell should be able to detect a directory and switch to it on pressing enter even if the directory name does not have a `./` prefix or `/` suffix on the directory name

### Describe alternatives you've considered

_No response_

### Additional context and details

_No response_

### PR DESCRIPTION
**Pull request by lavafroth**
# Description

This PR allows tab completion for nested directories while only specifying a part of the directory names. To illustrate this, if I type `tar/de/inc` and hit tab, it autocompletes to `./target/debug/incremental`.

# User-Facing Changes

Nested paths can be tab completed by typing lesser characters.

# Tests + Formatting

Tests cases are added.

# After Submitting

### CODE REVIEW

**Comment by lavafroth** [comment]
[Here's a preview](https://github.com/nushell/nushell/assets/107522312/b6c533b0-b993-45a6-9558-d4c7af759440)

**Comment by fdncred** [comment]
This looks cool! Thanks!

**Comment by lavafroth** [comment]
Update: I changed the functions a lot, making sure to conform to the engine_state for each completer (which I previously ignored). Also, I remove the prefix with the pathdiff crate to make relative paths like `../some/thi/n/g` stay relative. I would love to hear everyone's feedback on this. Thanks!

**Comment by fdncred** [comment]
Have you tested it on Windows? I'm hoping it works there too.

**Comment by lavafroth** [comment]
Actually, I haven't tested it on Windows yet. I'll need to setup a VM.

**Comment by lavafroth** [comment]
Yep, it works fine with spaces. I checked that manually. Also the cargo tests cover that.

**Comment by fdncred** [comment]
I just tested on Windows and it works as long as the slashes point left like regular windows slashes. Maybe it's just me, that's great, but I tend to cd /a/b/c/d even on Windows.

### Complete paths from root c:\ or \
I'm not sure if it doesn't work with spaces in file names or if it just doesn't like what I'm doing.
```
cd \pro\a\a<tab>
cd c:\pro\a\a<tab>
```
both go to the same folder `c:\program files\adobe\adobe acrobat reader dc`
### Complete c:\temp as c:\t
here's another weird one
```
cd \t<tab>
```
completes to `cd src\tests\`
```
cd c:\t<tab>`
```
returns no records found

### In the root
```
cd pro\a\a<tab>
```
no records found

**Comment by fdncred** [comment]
One more test. Just a regular folder with a space in it with a folder in it seems to work on windows.
image

**Comment by fdncred** [comment]
I'm retesting because some system I use carapace. So just to be verbose, this is on my Lenovo on Win11 launched with `cargo r -- -n --no-std-lib`

1. `cd cr\nu-c\s\b<tab>` - Works! expands to `crates\nu-command\src\bytes\`
2. `cr\nu-c\s\b<tab>` - Works! expands to `crates\nu-command\src\bytes\`
3. `cd pro\a\a<tab>` - Works!
image
4. `pro\a\a<tab>` - Works! same image as above
5. `cd t\set<tab>` - works!
image
6. `cd \t\set<tab>` - does not work
image
7. `cd c:\t\set<tab>` - does not work
8. `cd c:/t/set<tab>` - does not work

So, what I see right now on Windows 11 is drive names don't work like `C:` or `D:`.

**Comment by lavafroth** [comment]
Can we utilize some property of the engine state to get the current drive?

**Comment by lavafroth** [comment]
I added support for drive letters like `c:` with an optional slash like `c:/` or `c:\`. I also added support for `/` as the system root. However, since we have been using platform specific slashes everywhere else, `/wind/sys` won't autocomplete but `/w\sys` will. We can change this behavior if wanted.

**Comment by fdncred** [comment]
My preference would be for all these to "just work"
* `c:/blah/<tab>`
* `c:\blah\<tab>`
* `c:\blah/<tab>`
* `\w\sys<tab>`
* `/w/sys<tab>`
* `/w\sys<tab>`
* `\w/sys<tab>`

Basically, any slash direction with tab should work. I'm also fine with homogenizing the slashes so if you were to do something weird like `\a/b\c/d\e/f<tab>` it would do `\a\b\c\d\e\f` or `/a/b/c/d/e/f`.

I'm interested to see what others think.

**Comment by fdncred** [comment]
BTW, just let me say that is an epic PR. One of the biggest complaints we have is about completions not working the way people expect them to. This PR won't fix 100% of people's complaints, but man, it goes a long way to making our path completions better. Thanks so much for investing your time into nushell. ❤️

**Comment by jntrnr** [comment]
I think we should support the slash direction that's native for that platform for the first version of this change. If people want to it to be more flexible than that, we can improve it further later. 

Technically the other slash direction is valid as a filename, for example I can do `touch \` on my mac and get a file, so being conservative at first is probably a better place to start from.

**Comment by lavafroth** [comment]
Alright, I have implemented the slash homogenization. I also made sure to keep `~` and `..` relative. I've tried to make the code concise albeit there's still quite some room for improvement. Tell me what you folks think!

**Comment by lavafroth** [comment]
Bare string manipulations have been tedious, so I rewrote quite a bit of the code to use `std::path::Components`. The code has much less overhead now, I don't have to perform error prone checks for `..`, `~` or a drive letter from the partial string itself. The slashes also get homogenized as a by-product of using components. Finally, the binary size is way smaller that previous iterations of the PR.

**Comment by fdncred** [comment]
I'm happy to see the CI green. I fought with it yesterday because macos kept puking. 

I'm wondering if there's a way to add tests? If this works the way we want it to, we'd like to preserve that functionality and protect it from inadvertent changes breaking it. One way to do that is with some tests.

**Comment by lavafroth** [comment]
Yes, I'll be adding tests for this shortly. In the meanitme, you might want to try it out, see if it feels natural.

**Comment by fdncred** [comment]
I've tested it. I love it. ❤️ Everything that failed before on Windows is working great!

**Comment by lavafroth** [comment]
Whoops, typo checker thinks a file's prefix is a typo. I'll fix it.

**Comment by lavafroth** [comment]
Let me know if there's anything else I have to do before this gets merged!

**Review by fdncred — APPROVED** [review]
I like it and I'm ready to land it. Let's see if there are differing opinions.

**Comment by jntrnr** [comment]
+1 from me too. Let's do it.

**Comment by AucaCoyan** [comment]
I saw this new feature in the last 0.86 release, I've been looking forward for this in a long time! Thanks @lavafroth ❤️

**Pull request merged**
