### PR TITLE
Correct line folding in `from ics`/`from vcf`

### PR DESCRIPTION
**Pull request by joergsch**
# Description
Potential fix for #10398

# User-Facing Changes

# Tests + Formatting

# After Submitting

### CODE REVIEW

**Review by sholderbach — COMMENTED** [review]
Thanks for tackling this!

Would you mind adding a Reference to the relevant RFC: 
https://datatracker.ietf.org/doc/html/rfc5545#section-3.1
https://datatracker.ietf.org/doc/html/rfc6350#section-3.2

For tests we have https://github.com/nushell/nushell/blob/main/tests/plugins/formats/ics.rs

**Review by amtoine — COMMENTED** [review]
(just making the test request more vivible :wink: feel free to dismiss this for me once some tests have been added :relieved: )

**Review by amtoine — CHANGES_REQUESTED** [review]
(just making the test request more vivible :wink: feel free to dismiss this for me once some tests have been added :relieved: )

**Comment by joergsch** [comment]
Added test functions, optimized input_string building

**Review by sholderbach — APPROVED** [review]
Thanks for the tests especially the one including a desired space!

**Pull request merged**
