### PR TITLE
explore: remove `:config`, `:show-config`, `:tweak` commands

### PR DESCRIPTION
**Pull request by rgwood**
More trimming of underused `explore` functionality.

The `explore` command has subcommands that can be run like `:config` or `:try` or whatnot. This PR removes the `:config`, `:show-config`, and `:tweak` commands which are all for viewing+modifying config.

These are interesting commands and they were cool experiments, but ultimately I don't think they fit with our plans for a simplified `explore`. They'd need a lot more polish if we want to keep them and I don't think we do. Happy to discuss if I've missed a good reason to keep these.

cc @fdncred

### CODE REVIEW

**Comment by fdncred** [comment]
Before landing this PR, let's resolve the comments in the Discord thread. I think it's great to remove most config points, but I'm not sure it's good to remove all of them.

Just to reiterate, these were the config points (in the first paragraph) that I was concerned with.

I think hiding the cursor should be the default. I'm also fine with removing some config items. I agree that all colors should map from your current theme. Having said that, What colors will you use for `table.selected_cell`, `table.selected_column`, `table.selected_row`, `status_bar_background` and `status_bar_text`? These are probably all the config points I still care about. It'll be good to know how you map these colors. I'm not sure our theme supports them but maybe you'll find something that works. I'm on the fence whether `table.selected_column` should be a thing, it just depends on how navigation is changed.

I also think `try.reactive` should be an option in the `:try` feature, wherever that ends up. I was talking about a cool feature in the meeting. This is it. start `explore`, type `:tweak try.reactive true` then type `:try` and in this mode, the try functionality runs your command when you pause typing. It makes exploring commands fast. I'm also fine with `:try` being in a separate tool. I'm not fine with losing `:try` altogether though. Hopefully we can keep it separate somewhere.

**Comment by rgwood** [comment]
@fdncred just to make sure we’re on the same page, this PR doesn’t remove any config items yet; `explore` config is still editable in `config.nu`.

**Review by fdncred — APPROVED** [review]
> @fdncred just to make sure we’re on the same page, this PR doesn’t remove any config items yet; `explore` config should still be editable in `config.nu`.

Right, this just removes the explore interface to change config, try the config with tweak, or show the config with config-show. I overlooked that. Thanks for pointing it out.

My comments will be valid on the PR where you're removing them. :)

Once the CI is green, I'm good with landing this PR to remove these components.

**Comment by fdncred** [comment]
+2 / -1010 😃

**Comment by zhiburt** [comment]
Just noticed that `:config` is gone....

I was thinking about configuration of a `hexdump` grid via it ...........

Am I correct that it was the only way to configure things?

**Comment by rgwood** [comment]
You should be able to edit config.nu. Or, if you want to update config while Nu is running: https://www.nushell.sh/book/configuration.html#configuring-env-config

**Comment by fdncred** [comment]
@zhiburt yup, you're right that the `:config` you wrote was removed. we were and are still trying to slim down explore and also still want to remove the vim-like modes. So, there is no way to modify the config in real time while you're in explore anymore. what `hexdump` config were you thinking of adding? i assume maybe to enable coloring or not. you should feel free to add a config item to config.nu for it.

**Pull request merged**
