### PR TITLE
Prevents duplicate fields in `transpose -r`

### LINKED ISSUE #5837: `transpose -r` allows creating duplicate record fields
### Describe the bug

With certain inputs, `transpose -r` allows creating records using duplicate fields. Duplicate fields in records can cause confusing interactions.
A similar issue was occuring [with `merge`](https://github.com/nushell/nushell/issues/5282) in the past.

### How to reproduce

1. `[[key value]; [foo 1] [foo 2]] | transpose -r | debug`

### Expected behavior

The resulting record should only contain `foo` once.

### Screenshots

image

image

### Configuration

| key                | value                                           |
| ------------------ | ----------------------------------------------- |
| version            | 0.63.1                                          |
| branch             |                                                 |
| commit_hash        | 5bae7e56ef0990312a7becf8280b2f06899db6ad        |
| build_os           | linux-x86_64                                    |
| build_target       | x86_64-unknown-linux-gnu                        |
| rust_version       | rustc 1.60.0 (7737e0b5c 2022-04-04)             |
| rust_channel       | stable-x86_64-unknown-linux-gnu                 |
| cargo_version      | cargo 1.60.0 (d1fd9fe 2022-03-01)               |
| pkg_version        | 0.63.1                                          |
| build_time         | 2022-06-09 11:11:11 +02:00                      |
| build_rust_channel | release                                         |
| features           | database, dataframe, default, trash, which, zip |
| installed_plugins  |                                                 |

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by merelymyself**
# Description

Fixes #5837. Might need input, right now it just drops all excess values under an identical column name, which `merge` does as well in a similar situation.

# Tests

Make sure you've done the following:

- [x] Add tests that cover your changes, either in the command examples, the crate/tests folder, or in the /tests folder.
- [x] Try to think about corner cases and various ways how your changes could break. Cover them with tests.
- [x] If adding tests is not possible, please document in the PR body a minimal example with steps on how to reproduce so one can verify your change works.

Make sure you've run and fixed any issues with these commands:

- [x] `cargo fmt --all -- --check` to check standard code formatting (`cargo fmt --all` applies these changes)
- [x] `cargo clippy --workspace --features=extra -- -D warnings -D clippy::unwrap_used -A clippy::needless_collect` to check that you're using the standard code style
- [x] `cargo test --workspace --features=extra` to check that all the tests pass

### CODE REVIEW

**Comment by WindSoilder** [comment]
Thanks for your PR, the code looks clear :-)  Just my two cents:

Refer to the original issue's [comment](https://github.com/nushell/nushell/issues/5837#issuecomment-1160750673): 
> For the realworld task where I actually ran into this problem I'd actually like to retain all the occurences of the field, e.g. by collecting all the occurences of that field into an array, however, I'd consider that out of scope for this issue.

Unlike `merge`, which has semantic about overwriting the existing value.

I'd consider adding one more argument (Something like `--keep`?) to control the bebavior about duplicate value if `-r` is provided:
1. `--keep all`, we can collect all the occurences of that field into a list
2. `--keep first`(which is what you are doing in the pr), only need the first value.
3. `--keep last`, only need the last value.

It's just my personal thought, I'm curious about others idea too :-)

**Comment by merelymyself** [comment]
@WindSoilder, that's a great idea! I was thinking this could just be added to -r as itself, but that might constitute a breaking change. If not, then which do you think should be used by default?

**Comment by fdncred** [comment]
maybe default should be what it does now but `--keep` overrides those defaults?

**Comment by WindSoilder** [comment]
I would vote for keep last element by default;  So it's consistent with the following:
```
> {a: 3, a: 4}
╭───┬───╮
│ a │ 4 │
╰───┴───╯
```

**Comment by elferherrera** [comment]
I would suggest to make the flags as
```
--keep-last (-l)
--keep-all (-a)
```
Being the default keep first. Otherwise the flag expects a string and that is open to accept anything, creating another flag check

**Comment by merelymyself** [comment]
@fdncred I think so.

**Pull request merged**
