### PR TITLE
Always populate config record during startup

### PR DESCRIPTION
**Pull request by NotTheDr01ds**
# Description

As a bit of a follow-on to #13802 and #14249, this (pretty much a "one-line" change) really does *always* populate the `$env.config` record with the `nu-protocol::config` defaults during startup.  This means that an `$env.config` record is value (with defaults) even during:

* `nu -n` to suppress loading of config files
* `nu -c <commandstring>`
* `nu <script>`

# User-Facing Changes

There should be no case in which there isn't a valid `$env.config`.

* Before:

  ```nushell
  nu -c "$env.config"
  # -> Error
  ```

* After:

  ```nushell
  nu -c "$env.config"
  # -> Default $env.config record
  ```

Startup time impact is negligible (17.072µs from `perf!` on my system) - Seems well worth it.

# Tests + Formatting

Added tests for several `-n -c` cases.

- :green_circle: `toolkit fmt`
- :green_circle: `toolkit clippy`
- :green_circle: `toolkit test`
- :green_circle: `toolkit test stdlib`

# After Submitting

Config chapter update still in progress.

### CODE REVIEW

**Review by IanManske — APPROVED** [review]
Nice! Thanks for all the tests as well.

**Comment by WindSoilder** [comment]
Actually I'm a little confused.
Because when using `nu -n`, it starts with no config file and no env file, so what's the meaning of `$env.config`?

**Comment by NotTheDr01ds** [comment]
> Actually I'm a little confused. When using `nu -n`, it starts with no config file and no env file, so what's the meaning of `$env.config`?

It represents all of the internal defaults from [`nu-protocol::config`](https://github.com/nushell/nushell/tree/main/crates/nu-protocol/src/config).

**Review by WindSoilder — APPROVED** [review]
Thanks!  I get the idea behind it.  LGTM

**Pull request merged**
