### PR TITLE
Add feedback to cp

### PR DESCRIPTION
**Pull request by Kangaxx-0**
# Description

 - Add feedback to command `cp`
 - Add wildcard command example to `cp`

image
image

# Tests

Make sure you've run and fixed any issues with these commands:

- [x] `cargo fmt --all -- --check` to check standard code formatting (`cargo fmt --all` applies these changes)
- [x] `cargo clippy --all --all-features -- -D warnings -D clippy::unwrap_used -A clippy::needless_collect` to check that you're using the standard code style
- [x] `cargo build; cargo test --all --all-features` to check that all the tests pass

### CODE REVIEW

**Comment by hustcer** [comment]
Maybe we can add a `--verbose / -v` flag to show the feedback, and output nothing by default just as `cp` in bash ?

**Comment by Kangaxx-0** [comment]
> Maybe we can add a `--verbose / -v` flag to show the feedback, and output nothing by default just as `cp` in bash ?

I got what you meant - But the thing is - Right now, commands like `mv` and `rm`, they do show the feedback by default, do we want to keep the consistency ?

**Comment by hustcer** [comment]
I don't think we should keep the consistency, as `cp` feedback is less important than `rm`. It's just my personal view, How do you think? @fdncred

**Comment by fdncred** [comment]
I think they all should be consistent and they all should use `-v/--verbose` to display what's happened.

**Comment by hustcer** [comment]
> I think they all should be consistent and they all should use -v/--verbose to display what's happened.

currently `mv` and `rm` use `-q, --quiet` to suppress feedback, they don't have `-v / --verbose` options

**Comment by fdncred** [comment]
ok, to be consistent, let's make it `-q, --quiet`

**Comment by fdncred** [comment]
either way is fine with me, just pick one and be consistent. LOL. :)

**Comment by Kangaxx-0** [comment]
@hustcer @fdncred Is it ok to get this one completed, then having a refactoring PR to change the default behavior to not show feedback unless user specifies `-v`? It seems like a bigger change anyway

Thoughts?

**Comment by hustcer** [comment]
> @hustcer @fdncred Is it ok to get this one completed, then having a refactoring PR to change the default behavior to not show feedback unless user specifies `-v`? It seems like a bigger change anyway
> 
> Thoughts?

Fine with me. BTW, It's more acceptable to use `-q` if we don't show the files  inside it and only show the directory itself been copied while copying a directory recursively. Can we hide the child items been copied inside the directory?

**Comment by fdncred** [comment]
I'm fine with doing it in multiple parts.

**Comment by hustcer** [comment]
@Kangaxx-0 I will add `-v, --verbose` for `mv` and `rm`, you can go on with `cp` later

**Comment by fdncred** [comment]
@Kangaxx-0 I actually like your output of files/child files in a list, it just needs to be shown if `-v` or `--verbose` is used. Do you want to work on that here or do you want to land this PR and work on that next?

**Comment by Kangaxx-0** [comment]
> @Kangaxx-0 I actually like your output of files/child files in a list, it just needs to be shown if `-v` or `--verbose` is used. Do you want to work on that here or do you want to land this PR and work on that next?

I need to get my team's sprint planning done today and tomorrow, then jump back to this pr and send a new iteration to add verbose parameter

**Comment by jmoore34** [comment]
Personally I kind of like the idea of having output by default, and opting in to silent mode (or piping into `ignore`) when desired, for a couple reasons:

* Narrower gulf of evaluation -- a user (and in particular, a novice user) doesn't have to guess (or check with `ls`) whether the files were deleted. Checking to see whether the command was successful is especially troublesome in a large directory, or when you `rm` or `cp` files outside the current directory.

* Globs: whenever using globs (e.g. `rm *.rs`), it's nice to be shown by default the files you acted on, so that if you forgot to supply a -v flag or `ls *.rs` beforehand, you can still catch mistakes (or, you can rm without stressing whether you unknowingly deleted a file you weren't supposed to, which I think is a sane default).

**Comment by fdncred** [comment]
maybe we need a config point to allow quiet or verbose by default, across commands?

**Comment by jmoore34** [comment]
Perhaps, though a workaround might be to have users who prefer silent mode create aliases, e.g.:

```
alias rm-noisy = rm
alias rm = rm --silent
alias mv-noisy = mv
alias mv = mv --silent
```

That way it's opt-in, and novice users get the benefit of the feedback by default.

**Comment by Kangaxx-0** [comment]
@fdncred @hustcer 

This is what I have locally, does it look good?

- Default with verbose = `false`
image

- Specify `- v`
image

**Comment by fdncred** [comment]
@Kangaxx-0 yes, it looks good to me. Thanks for working on this.

**Pull request merged**
