### PR TITLE
Fix unsupported type message for some math related commands

### PR DESCRIPTION
**Pull request by hustcer**
# Description

Fix unsupported type message of some math related commands

Before:
```
$> '-2' | math abs
Error: nu::shell::unsupported_input (link)

  × Unsupported input
   ╭─[entry #6:1:1]
 1 │ '-2' | math abs
   ·        ────┬───
   ·            ╰── Only numerical values are supported not supported
   ╰────
```

After:

```
$> '-2' | math abs
Error: nu::shell::unsupported_input (link)

  × Unsupported input
   ╭─[entry #11:1:1]
 1 │ '-2' | math abs
   ·        ────┬───
   ·            ╰── Only numerical values are supported, input type: String not supported
   ╰────
```
# Tests

Make sure you've run and fixed any issues with these commands:

- [x] `cargo fmt --all -- --check` to check standard code formatting (`cargo fmt --all` applies these changes)
- [x] `cargo clippy --all --all-features -- -D warnings -D clippy::unwrap_used -A clippy::needless_collect` to check that you're using the standard code style
- [x] `cargo build; cargo test --all --all-features` to check that all the tests pass

### CODE REVIEW

**Comment by hustcer** [comment]
Maybe we should change `UnsupportedInput(String, #[label("{0} not supported")] Span)`  to `UnsupportedInput(String, #[label("{0}")] Span),` ?

**Comment by jntrnr** [comment]
@hustcer - your suggestion for changing the error form for `UnsupportedInput` sounds good

**Comment by hustcer** [comment]
> @hustcer - your suggestion for changing the error form for `UnsupportedInput` sounds good

Okay, I will check all the `UnsupportedInput` messages and update this pr later.

**Comment by hustcer** [comment]
@jntrnr I think it's ready now

**Comment by jntrnr** [comment]
looks good!

**Pull request merged**
