### PR TITLE
mention `do` in `complete` command's doc

### PR DESCRIPTION
**Pull request by WindSoilder**
# Description

Closes: #7841

# User-Facing Changes

new complete doc:
```
Complete the external piped in, collecting outputs and exit code

To collect stderr messages and exit_code, external piped in need to wrapped with `do`

Usage:
  > complete

Flags:
  -h, --help - Display the help message for this command

Signatures:
  <any> | complete -> <record>

Examples:
  Run the external completion
  > ^external arg1 | complete

  Run external completion, collects stderr and exit_code
  > do { ^external arg1 } | complete
```

# Tests + Formatting

Don't forget to add tests that cover your changes.

Make sure you've run and fixed any issues with these commands:

- `cargo fmt --all -- --check` to check standard code formatting (`cargo fmt --all` applies these changes)
- `cargo clippy --workspace -- -D warnings -D clippy::unwrap_used -A clippy::needless_collect` to check that you're using the standard code style
- `cargo test --workspace` to check that all tests pass

# After Submitting

If your PR had any user-facing changes, update [the documentation](https://github.com/nushell/nushell.github.io) after the PR is merged, if necessary. This will help us keep the docs up to date.

### CODE REVIEW

**Comment by fdncred** [comment]
I think the text here is misleading but after our recent conversation I'm not sure I fully understand. I'm thinking that the descriptions should be changed from this:
```rust
Example {
    description: "Run the external completion",
    example: "^external arg1 | complete",
    result: None,
},
Example {
    description: "Run external completion, collects stderr and exit_code",
    example: "do { ^external arg1 } | complete",
    result: None,
},
```
to this:
```rust
Example {
    description: "Run the external command to completion, capturing stdout and exit_code",
    example: "^external arg1 | complete",
    result: None,
},
Example {
    description: "Run external command to completion, capturing, stdout, stderr and exit_code",
    example: "do { ^external arg1 } | complete",
    result: None,
},
```
Do you think those changes are correct? I tested with`^ls | complete` and `do { ^ls } | complete`

**Comment by WindSoilder** [comment]
Thanks for the update, I think these changes are correct.

**Comment by fdncred** [comment]
@WindSoilder I made some more changes to the usage/extra_usage. Do you think those are still correct with how the command works?

**Comment by WindSoilder** [comment]
Yeah, It's correct

**Comment by fdncred** [comment]
Thanks!

**Pull request merged**
