### PR TITLE
`ls` improvement: Handle illegal filenames better on Windows

### PR DESCRIPTION
**Pull request by rgwood**
[Windows doesn't like some file names that are valid on *nix](https://learn.microsoft.com/en-us/windows/win32/fileio/naming-a-file). This is a problem because files with these names _can_ be created in tools like MinGW bash, but then attempts to work with those files often fail unless a special ["verbatim" file path](https://users.rust-lang.org/t/understanding-windows-paths/58583/2) prefixed with `\\?\` is used.

I've updated `ls` to convert file paths to their verbatim form before looking up metadata. This fixes the most common scenario users run into, but eventually we should update other filesystem commands too.

### Before

image

### After

image

Related issues: https://github.com/nushell/nushell/issues/7869 https://github.com/nushell/nushell/issues/8364 https://github.com/nushell/nushell/issues/7345

### CODE REVIEW

**Comment by rgwood** [comment]
@ChrisDenton 

I used [the `verbatim` crate](https://lib.rs/crates/verbatim) to convert paths to their verbatim form. Seems to work OK but are you aware of any better crates or approaches?

**Comment by ChrisDenton** [comment]
Hm, the number of `unimplemented!` calls in the `verbatim` crate has me slightly concerned.

If you give me a sec I can extend omnipath to add the necessary function. Honestly it's mainly just copy/pasting similar code I wrote for the Rust standard library.

**Comment by rgwood** [comment]
> If you give me a sec I can extend omnipath to add the necessary function.

That would be great! There's no rush on this, I'll wait until you have time to update omnipath.

**Comment by rgwood** [comment]
@ChrisDenton I'm trying out `omnipath` v0.1.4 but am having some trouble with these kinds of illegal filenames. For example:

```rust
let path = Path::new(r"C:\Users\reill\scratch\illegal\NUL");
let path = path.to_verbatim().unwrap();
dbg!(&path);
```
prints this:
```
[src\main.rs:12] &verbatim = "\\\\?\\NUL"
```

That NUL file exists on disk; I would expect that `to_verbatim()` call to return `\\?\C:\Users\reill\scratch\illegal\NUL` (or fail)

**Comment by rgwood** [comment]
@ChrisDenton One more test case: files with a name that ends in `.`

On v0.1.5, `C:\bad.txt.` is being converted to `\\?\C:\bad.txt` (the trailing `.` gets dropped).

**Comment by fdncred** [comment]
I'm looking forward to landing this. Nice work. Are we still waiting for a newer version of omnipath?

**Comment by rgwood** [comment]
Yep! I'll put this one in draft for now, will revisit it when omnipath is updated

**Comment by ChrisDenton** [comment]
Sorry for the delay! I had to think about the API I wanted for this and got nervous about it for the general use case. Rust's std had a lot of problems with verbatim paths not working how people expected. My idea now is for a `to_verbatim_exact` function with all the right health warnings. I.e. it's for when you're sure the path is exactly the one you want, no pesky changes at all. Such as when the path originates from the OS.

**Comment by fdncred** [comment]
Whatever happened to this @rgwood? Run out of steam or upstream blockers?

**Comment by rgwood** [comment]
Waiting on a new version of Omnipath: https://github.com/ChrisDenton/omnipath

**Comment by ChrisDenton** [comment]
That's on me, I've admittedly been distracted lately. I've pushed an update to omnipath that adds `to_verbatim_exact`. Which should do as it says. (I still want to update the original function but I do need to think about API considerations and add more test cases).

I'll get it published to crates.io once I've had a bit of time to confirm it's working ok.

**Comment by ChrisDenton** [comment]
[Published](https://docs.rs/omnipath/latest/omnipath/windows/trait.WinPathExt.html#tymethod.to_verbatim_exact),

**Comment by rgwood** [comment]
Awesome, thanks! I'll pick this up again soon.

**Comment by rgwood** [comment]
I’m not sure when I’ll get back to this, sorry. If anyone else wants to pick it up, feel free.

**Pull request closed without merging**
