### PR TITLE
Fix ps command CPU usage on Apple Silicon M1 macs. #4142

### PR DESCRIPTION
**Pull request by obaudys**
# Description

The cpu user and system times returned by libproc are not in
nanoseconds; they are in mach ticks units.  This is not documented very
well.  The convert from mach ticks to ns, the kernel provides a timebase
info function and datatype:

(https://developer.apple.com/documentation/driverkit/3433733-mach_timebase_info)

The commit makes the PS command work for me.

 
image

 
# Tests

Existing tests should cover this just fine.  However it would be good to get confirmation from someone with an Intel mac to see if ps output makes sense.

### CODE REVIEW

**Comment by fdncred** [comment]
oh wow. it's so nice to have cpu utilization again. thanks so much for this. now, if we can only fix the virtual memory, why oh why is everything ~400-~500GB? it's not like that in activity monitor. I wonder if it's the same sort of thing?

**Comment by obaudys** [comment]
>  if we can only fix the virtual memory, why oh why is everything ~400-~500GB?

As far as I can see,  the data for virtual memory size is populated by the C  library function `proc_pidinfo`, which is a wrapper around a syscall [`__proc_info`](https://opensource.apple.com/source/xnu/xnu-2782.1.97/libsyscall/wrappers/libproc/libproc.c.auto.html).  So, I'll say it is accurate,  and the native `/bin/ps` utility's "rss" field matches nushell's "mem":

image

Funnily enough my Google Chrome worker processes have 1.5TB mapped into their address space, apparently. Both nushell and `/bin/ps` agree on this.

Activity Monitor does not seem to report the the rss field unless you enable the "Real Mem" column,  and I have no idea how it actually calculates the "Memory" column: 

image

**Comment by fdncred** [comment]
@obaudys When I compared activity monitor to nushell's `ps` command earlier this morning. The virtual memory was way off, but maybe I was looking at the wrong column. All I saw was 95% (or greater) of my processes were using over 400GB of virtual memory. I'll take a closer look later this afternoon like you suggest. Thanks for the info.

**Comment by rgwood** [comment]
Thanks @obaudys! Really appreciate these kinds of platform-specific fixes :)

**Pull request merged**
