### PR TITLE
Add ulimit command

### LINKED ISSUE #9563: Add ulimit
### Related problem

Posix shells all have to have something like `ulimit` built in somehow in order to change their limits from the shell in a way that persists. It does me no good to use the system ulimit (typicall at /usr/bin/ulimit) from nushell as that does not change nushell's limits nor any of its child process limits.

### Describe the solution you'd like

On posix systems there should be a built in for getrlimit and setrlimit libc functions. This would allow me to at least write my own ulimit

### Describe alternatives you've considered

Ideally, nushell would maintain its own ulimit implementation that worked something like bash's ulimit rather than just providing raw primitives.

### Additional context and details

Right now if I have to change my ulimits I have to go into bash first, and then change it, and then if I still want to use nushell I have to invoke nushell form there.

### PR DESCRIPTION
**Pull request by nibon7**
# Description
This PR adds `ulimit` command to Nushell. 

Closes #9563

# User-Facing Changes
```
/data/source/nushell> ulimit -a                                                                                                  
╭─────────────────────────────────────────────────────────────────┬───────────╮
│ Maximum size of core files created                         (-c) │ unlimited │
│ Maximum size of a process's data segment                   (-d) │ unlimited │
│ Controls of maximum nice priority                          (-e) │ 0         │
│ Maximum size of files created by the shell                 (-f) │ unlimited │
│ Maximum number of pending signals                          (-i) │ 55273     │
│ Maximum size that may be locked into memory                (-l) │ 8.0 MiB   │
│ Maximum resident set size                                  (-m) │ unlimited │
│ Maximum number of open file descriptors                    (-n) │ 1024      │
│ Maximum bytes in POSIX message queues                      (-q) │ 800.0 KiB │
│ Maximum realtime scheduling priority                       (-r) │ 0         │
│ Maximum stack size                                         (-s) │ 8.0 MiB   │
│ Maximum amount of CPU time in seconds                      (-t) │ unlimited │
│ Maximum number of processes available to the current user  (-u) │ 55273     │
│ Maximum amount of virtual memory available to each process (-v) │ unlimited │
│ Maximum number of file locks                               (-x) │ unlimited │
│ Maximum contiguous realtime CPU time                       (-y) │ unlimited │
╰─────────────────────────────────────────────────────────────────┴───────────╯
/data/source/nushell> ulimit -s                                                                                                
╭─────────────────────────────────────────────────────────────────┬─────────╮
│ Maximum stack size                                         (-s) │ 8.0 MiB │
╰─────────────────────────────────────────────────────────────────┴─────────╯
/data/source/nushell> ulimit -s 102400                                                                                           
/data/source/nushell> ulimit -s                                                                                                    
╭─────────────────────────────────────────────────────────────────┬───────────╮
│ Maximum stack size                                         (-s) │ 100.0 KiB │
╰─────────────────────────────────────────────────────────────────┴───────────╯
/data/source/nushell> ulimit                                                                                                      
╭─────────────────────────────────────────────────────────────────┬───────────╮
│ Maximum size of files created by the shell                 (-f) │ unlimited │
╰─────────────────────────────────────────────────────────────────┴───────────╯
/data/source/nushell>                     
```

# Tests + Formatting
- [x] add `commands::ulimit::limit_nice`
- [x] add `commands::ulimit::invalid_limit`
- [x] add `commands::ulimit::limit_set_and_get`
- [x] `cargo fmt --all -- --check` to check standard code formatting (`cargo fmt --all` applies these changes)
- [x] `cargo clippy --workspace -- -D warnings -D clippy::unwrap_used` to check that you're using the standard code style
- [x] `cargo test --workspace` to check that all tests pass (on Windows make sure to [enable developer mode](https://learn.microsoft.com/en-us/windows/apps/get-started/developer-mode-features-and-debugging))
- [x] `cargo run -- -c "use std testing; testing run-tests --path crates/nu-std"` to run the tests for the standard library

### CODE REVIEW

**Comment by nibon7** [comment]
I'll try the plugin system, thanks! :)

**Comment by fdncred** [comment]
@nibon7 let me know if you run into any issues or come by the `#plugins` channel on discord.

**Comment by nibon7** [comment]
It's quite easy to convert to plugin, but I found that `ulimit` can't be implemented as plugin, seems plugin system calls the plugin as child process and the limits set by the `ulimit` plugin does not apply to nushell itself and its child processes.

**Comment by fdncred** [comment]
> seems nushell calls the plugin as child process

This is true, nushell will launch the plugin executable and then communicate with it on stdout. I had no idea that it was required to be run from the nushell process. Not sure where we go from here.

**Comment by nibon7** [comment]
Hi @fdncred, I found some platform dependent features, I'm wondering if there's any chance that this `uilimit` feature could be accepted.

https://github.com/nushell/nushell/blob/94b27267fd2ba47b170389e5baf1650b3fadea0c/crates/nu-command/src/default_context.rs#L149-L150

**Comment by fdncred** [comment]
Yup, I wrote that one and CAD97 cleaned it up. It's windows specific because the windows registry doesn't exist on any other platform. You could argue similarly for ulimit, which you are. :) 

This decision is up to the @nushell/core-team. I'd vote against it just because I don't think it's a super important command, but I could be wrong.

**Comment by nibon7** [comment]
Thanks for your explanation, I'm just curious :)

**Comment by fermuch** [comment]
Hello! I've just stumbled upon this problem and found it weird there is no ulimit command. As @nibon7 explained, this need to be executed from the shell process for it to work.

I would also like to point out most (all?) other UNIX shell implement it:

* BASH
* SH
* Fish
* ZSH
* BusyBox

**Comment by fdncred** [comment]
@nibon7 I'm fine with you reopening this PR while waiting for the @nushell/core-team to respond here.

@fermuch We have to focus on more than just those shells you mention. Nushell tries very hard to be completely cross platform. I'm not convinced this is a shell thing anyway. It looks more like an OS level command. I don't think it's nushell's place to control any of this. Please correct me if I'm wrong.

**Comment by stormasm** [comment]
>> I'd vote against it just because I don't think it's a super important command, but I could be wrong.

After reviewing the documentation on the details of this command I agree with @fdncred that this command
should NOT be part of nushell --- but instead one can use the ulimit command that is already builtin to the particular
operating system the user is using...

**Comment by bakaq** [comment]
@stormasm, please read the explanation at https://github.com/nushell/nushell/issues/9563#issuecomment-1614927270. As I understand, this is a command that could probably only be implemented in nushell itself, because it needs to change the state of it's child processes.

Maybe the command itself could be implemented as a plugin, but as I understand it the plugin would have to communicate how the limits actually change to the main nushell process, which would still need to implement this functionality anyway (probably with platform specific code) since the main nushell process is the one that spawns programs as childs and therefore needs to know what limits it should give them.

There are many usecases for this command. As @JakeSiFive said in the explanation above, it is needed in some systems to get coredumps at all. My usecase is to set the maximum virtual memory of a program very low so I can test how it deals with out of memory errors.

On the other hand, I think that we could maybe do a better implementation of this feature of changing limits of child processes than how `ulimit` works in other shells. This command is stateful, and one of the best parts of nushell is how it's scoping works. Maybe we could have the limits in a environment variable, so that we could stuff like this:

```nu
{
    # Run a program with ~10MB of virtual memory
    ulimit -v 10000
    example
}
# Run it again without the limit
example
```

**Comment by stormasm** [comment]
@nibon7 the core team met today and we decided to go ahead and land your ulimit command PR.

One of our initial concerns with the command is that its not cross platform but we are willing to make an exception for this command based on the feedback from @bakaq as well as @JakeSiFive.

Plus it will enhance our Linux user base with an extra command that will come in handy for a subset of our user base.

However, since no one on the core team has a lot of experience with how the command works we were wondering if long term you ( @nibon7 ) would mind making sure the command continues to work and if in the future issues arise with how the command works or developers have questions with how to use it etc that you wouldn't mind taking on that responsibility.

The reason we are requesting that up front is because we need to make sure if we land your PR that someone knows and understands in depth how it works as well as being able to support it for our user base long term.

That is one of our main concerns about the ulimit command.

Let us know what you think about this proposal...

FYI @IanManske was on the core team call today as well and also said they would help out as well...

Thanks for your work on this command and we look forward to having this in the code base.

**Comment by stormasm** [comment]
Going ahead and reopening the PR

**Comment by fdncred** [comment]
Thanks. We decided we'd land this today as a *nix command only, if we can get people to maintain it.

**Comment by nibon7** [comment]
Thanks all. @fdncred  @fermuch @stormasm @bakaq @JakeSiFive.
I'll create another one later, since my `main` branch has been force-pushed :)

**Comment by fdncred** [comment]
Thanks @nibon7. We appreciate your patience to figure this out.

**Comment by stormasm** [comment]
@nibon7 thank you 😄

**Pull request closed without merging**
