### PR TITLE
Bye bye upx sorry

### PR DESCRIPTION
**Pull request by fdncred**
remove stripping too

### CODE REVIEW

**Comment by ajeetdsouza** [comment]
Why did we remove stripping?

**Comment by fdncred** [comment]
> Why did we remove stripping?

Because the git action we were using did ups and stripping and seemed to provide no option to turn off only upx. I'd personally like to use stripping again so if you have an action that does it on all 3 platforms (linux, Mac, windows) let me know. I'd happily accept a PR for this on Nushell and engine-q.

**Comment by ajeetdsouza** [comment]
Cargo is adding support for binary stripping soon: https://github.com/rust-lang/cargo/pull/10088

Once it's merged, we won't need an action at all.

**Comment by fdncred** [comment]
oh, that will be nice. I look forward to that. Looks like it's in 1.58  stable so it should be soon-ish.

**Pull request merged**
