### PR TITLE
Made a change to completion resolution order

### PR DESCRIPTION
**Pull request by PurityLake**
# Description

Relates to issue: #5437 

The change to the code is that instead of matching for a file, a catchall is used, then it tests using a `CommandCompletion` object, if there are no completions found *then* a it tests for a file.

This is a suggested fix, I am open to hear other implementations, perhaps one where `process_completion` isn't called twice.

# Tests

Make sure you've run and fixed any issues with these commands:

- [x] `cargo fmt --all -- --check` to check standard code formatting (`cargo fmt --all` applies these changes)
- [x] `cargo clippy --all --all-features -- -D warnings -D clippy::unwrap_used -A clippy::needless_collect` to check that you're using the standard code style
- [x] `cargo build; cargo test --all --all-features` to check that all the tests pass

### CODE REVIEW

**Comment by PurityLake** [comment]
Made some changes, removing file path finding in the command completer so it is relegated to the actual file completer

**Comment by jntrnr** [comment]
It's a bit difficult to review with so much mostly just being commented out.

Instead, can you remove the code that needs to be removed and explain what steps you're doing?

It would also be helpful to have a short explanation (or gif) of the before and after. Completions are notoriously tricky, so being able to see the differences also helps review.

**Comment by PurityLake** [comment]
@jntrnr will do

Ok so here is what is shown prior to the fix:

completion-broke

Despite checkout being a completion that should be there.

Here is it fixed:

completion-fixed

**Comment by herlon214** [comment]
@PurityLake could you test some other completions, just to see if that didn't broke them?

I'm raising some PRs with tests for completions, that might be a great help in the future.

**Comment by PurityLake** [comment]
@herlon214

Screenshot from 2022-05-08 23-07-52

Screenshot from 2022-05-08 23-07-33

Screenshot from 2022-05-08 23-07-09

Screenshot from 2022-05-08 23-10-29

Added some commands to `$nu.config_path` and seems run rather well

Here are the entries I made in my config file:

```
export extern "cargo build" [
  --package
  --workspace
  -- all
  --lib
  --bin
  --bins
]


export extern "cargo check" [
  --lib
  --bins
  --example
  --examples
  --test
]


export extern "svn checkout" [

]


export extern "svn update" [

]

export extern "svn commit" [

]
```

**Comment by herlon214** [comment]
Thanks @PurityLake.

Can we told this PR a bit, until https://github.com/nushell/nushell/pull/5460 and https://github.com/nushell/nushell/pull/5474 get merged, so we can have a bit more confidence?

**Comment by PurityLake** [comment]
> Can we told this PR a bit, until #5460 and #5474 get merged, so we can have a bit more confidence?

No worries, always better safe than sorry

**Comment by herlon214** [comment]
@PurityLake those two PRs got merged. Could you fix the conflicts and check the tests?
I did some refractor in the tests as well to split them into different files.

**Comment by PurityLake** [comment]
@herlon214 awesome, just fixed up everything and all tests seem to pass

**Comment by PurityLake** [comment]
@herlon214 Weirdly enough needed a merge conflict again

**Comment by fdncred** [comment]
@herlon214 @PurityLake are we ready to land this one or are you still working on it?

**Comment by PurityLake** [comment]
@fdncred I believe it is ready to go

**Comment by fdncred** [comment]
thanks

**Pull request merged**
