### PR TITLE
feat(xdg_state)!: support xdg_state dir on unix

### PR DESCRIPTION
**Pull request by Decodetalkers**
# Description

support xdg_state dir, put history file in here

reference to the pr 

https://github.com/xdg-rs/dirs/pull/43

elvish and nvim has already put history file in it

# User-Facing Changes

# Tests + Formatting

# After Submitting

### CODE REVIEW

**Comment by Decodetalkers** [comment]
After history file will be in `~/.local/state`, if  the environment ${XDG_STATE_HOME} is not setted

**Review by amtoine — APPROVED** [review]
i personnally like these changes:
- they work on linux, i've just tested
- they won't break anything on windows

:ok_hand: 

the only thing is that i believe this is a breaking change in the sense that users on linux will loose their histories at first :thinking: 

however, if we give them something like the following script, the transition should be fine :relieved: 
```nushell
def "history migrate" [] {
    use std log

    if $nu.os-info == windows {
        log info "history location did not change on windows => nothing to do"
        return
    }

    let history_files = $nu.default-config-dir | path join "history*"
    let new_history_dir = $env.XDG_STATE_HOME?
        | default ($nu.home-path | path join ".local" "state")
        | path join "nushell"

    mv $history_files $new_history_dir

    log info "history has been migrated successfully!"
}
```

thanks @Decodetalkers :blush:

**Comment by Decodetalkers** [comment]
Ok.

**Comment by Decodetalkers** [comment]
> i personnally like these changes:
> 
>     * they work on linux, i've just tested
> 
>     * they shouldn't break anything on windows
> 
> 
> ok_hand
> 
> the only thing is that i believe this is a breaking change in the sense that users on linux will loose their histories at first thinking
> 
> however, if we give them something like the following script, the transition should be fine relieved
> 
> ```nushell
> def "history migrate" [] {
>     use std log
> 
>     if $nu.os-info == windows {
>         log info "history location did not change on windows => nothing to do"
>         return
>     }
> 
>     let history_files = $nu.default-config-dir | path join "history*"
>     let new_history_dir = $env.XDG_STATE_HOME?
>         | default ($nu.home-path | path join ".local" "state")
>         | path join "nushell"
> 
>     mv $history_files $new_history_dir
> 
>     log info "history has been migrated successfully!"
> }
> ```
> 
> thanks @Decodetalkers blush

put it in default_env.nu or default_config.nu?

**Comment by fdncred** [comment]
I don't like this because it's hacking around dirs-next, nor do I support it. We should just figure out https://github.com/nushell/nushell/pull/8682 and use it. I could live with this suggestion https://github.com/nushell/nushell/pull/8682#issuecomment-1574939674 which emphasizes my number 2 point.

**Comment by amtoine** [comment]
> put it in default_env.nu or default_config.nu?
>
i think we could just put this script in the next release note, it's just a temporary measure imo :yum:

**Comment by Decodetalkers** [comment]
then can we use https://github.com/dirs-dev/dirs-rs this instead? seem we just use home , config, it seems the same @fdncred

**Comment by fdncred** [comment]
> then can we use https://github.com/dirs-dev/dirs-rs this instead? seem we just use home , config, it seems the same @fdncred

This crate doesn't seem to fix the problem we're trying to solve.
```
dirs::config_dir();
// Lin: Some(/home/alice/.config)
// Win: Some(C:\Users\Alice\AppData\Roaming)
// Mac: Some(/Users/Alice/Library/Application Support)
```

**Comment by Decodetalkers** [comment]
> > then can we use https://github.com/dirs-dev/dirs-rs this instead? seem we just use home , config, it seems the same @fdncred
> 
> This crate doesn't seem to fix the problem we're trying to solve.
> 
> ```
> dirs::config_dir();
> // Lin: Some(/home/alice/.config)
> // Win: Some(C:\Users\Alice\AppData\Roaming)
> // Mac: Some(/Users/Alice/Library/Application Support)
> ```

https://github.com/dirs-dev/directories-rs what about this one? it is the same as dir-next

**Comment by fdncred** [comment]
closing in favor of #8682

**Pull request closed without merging**
