### PR TITLE
Adding two Dockerfiles to deploy to Docker Hub with CircleCI

### PR DESCRIPTION
**Pull request by vsoch**
As discussed in https://github.com/nushell/nushell/pull/429, this PR will add a Circle configuration and two Dockerfiles to deploy the following containers to Docker Hub:

 - nushell/nu-base: is the rust slim base with all of the code added, and a release built, and the nu binary added to /usr/local/bin. The container is heftier in that it has all of the source code / dependencies. It builds from docker/Dockerfile.nu-base
 - nushell/nu is a multistage build that does nothing other than grab the nu binary from /usr/local/bin, with the same rust base. It should be somewhat smaller, although not tiny because I couldn't find a (rust maintained) busybox or similar image.

For the CircleCI config, we of course will need to test everything, but to setup we would want:
 - the repository connected to CircleCI
 - the settings updated to build on forked pull requests, to have workflows enabled, and to cancel redundant builds (this is my preference, you don't have to but it saves resources)
 - DOCKER_LOGIN and DOCKER_PASSWORD saved to encrypted CircleCI secrets. It can be any Docker Hub user that has push access to the repository.

For this first go at a configuration, the following should happen (needs to be tested of course!):
 - a build is triggered for nu-base, followed by nu, on any pull request (any branch other than master)
 - on official tags (releases) a version tag and "latest" are deployed
 - on merge to master, a "devel" tag is deployed
 - a nightly build is done, with tag "nightly"

Some questions I am wondering about:
 - I haven't ever tried a requires section for an orb, so we'll have to see how that works!
 - did I build and install correctly? For example I only grabbed the nu binary and didn't touch any of the plugins / libraries. Where should those go? If there is a procedure for doing it with some prefix, can we add that to the Makefile?
 - is there any way to cache / speed up the build/install? It's really really slow. :)

Signed-off-by: Vanessa Sochat <vsochat@stanford.edu>

### CODE REVIEW

**Comment by wycats** [comment]
I'm working on this

**Comment by vsoch** [comment]
Alrighty - but note that the configurations need testing! Please let me know if you want any help.

**Comment by wycats** [comment]
@vsoch I don't use CircleCI much and would be happy to hand this off to you, but I don't know how to do that!

**Comment by wycats** [comment]
@vsoch I don't use CircleCI much and would be happy to hand this off to you, but I don't know how to do that!

**Comment by vsoch** [comment]
The idea with the PR was that you could connect the repository to CircleCI, and then I would keep updating it until everything was in working order. I can debug and do most of what is needed without any special permission just via pull request.

**Comment by wycats** [comment]
Sounds great! I've connected the repo, and wouldn't mind giving you perms so you could iterate without special help from me. Are you on Discord?

**Comment by vsoch** [comment]
In my original note https://github.com/nushell/nushell/pull/500#issue-311586975 I listed the settings you would want to check after connecting it, mainly building on forked pull requests, enabling workflows, and auto-cancelling redundant builds.  You can normally login to CircleCI with GitHub, go to the dashboard, https://circleci.com/dashboard and then add projects based on the organization. If you don't see the organization, there should be a link to take you directly to GitHub settings to authorize.

**Comment by vsoch** [comment]
yes I'm newly on Discord! How do I find you?

**Comment by vsoch** [comment]
Just joined the channel from the README link. :)

**Comment by wycats** [comment]
@vsoch I made a #ci channel to coordinate

**Pull request merged**
