### PR TITLE
Change install context of windows terminal profile to `per-user`

### PR DESCRIPTION
**Pull request by wolimst**
# Description

Change installation context of the windows terminal profile to `per-user` from `per-system`.

This change is made because installation validation fails in winget ci while executing custom action to replace the installation path of `nu.exe` and `nu.ico` in the windows terminal profile file.

Refer discussions in #5812 and https://github.com/microsoft/winget-pkgs/pull/106977

- Installation path of the windows terminal profile is changed as below:
  - from: `C:\ProgramData\Microsoft\Windows Terminal\Fragments\nu\nu.json`
  - to: `C:\Users\<user>\AppData\Local\Microsoft\Windows Terminal\Fragments\nu\nu.json`
- Custom action to replace the installation path of `nu.exe` and `nu.ico` in the json file will be executed without privilege escalation

This change is expected to eliminate the validation failure in winget ci (need to wait until next release to be sure about it), however, it creates some inconsistency in installation context.

- The windows terminal profile is installed in `per-user` context, other files / PATH env variable are installed in `per-system` context.
- Building the installer shows a warning about this: `warning LGHT1076 : ICE91: The file 'WindowsTerminalProfileFile' will be installed to the per user directory 'WindowsTerminalProfileAppFolder' that doesn't vary based on ALLUSERS value. This file won't be copied to each user's profile even if a per machine installation is desired.`
  which means: WT profile will be installed only for the user that executed the installer and it won't be installed for other users in the system. However, the installer is configured to use `per-system` context, therefore, other files (such as nushell binary `nu.exe`) will be installed for all users.

It might be better if we provide options for installation context (`per-user` or `per-system`) as requested in #5927 in the future, if that doesn't cause problems in winget ci.

# User-Facing Changes

- Installation path of windows terminal profile will be changed as above.
- Windows Terminal profile will be installed only for the user that installed nushell as stated above. The profile should be manually added for other users if needed.

# Tests + Formatting

No test is added since this change is related to installation process in Windows and does not contain source code changes.

Following checks are done manually.

### Environment

- OS: Windows 11 Pro 22H2
- Built the installer by referring `.github/workflows/release-pkg.nu` script

### Checks

- Install: WT profile should be created in `C:\Users\<user>\AppData\Local\Microsoft\Windows Terminal\Fragments\nu\nu.json` and it should contain correct path for `nu.exe` and `nu.ico`.
  - [x] Install (WT profile feature enabled)
  - [x] Install (WT profile enabled) -> Manually remove the WT profile file -> Re-run the installer and Repair

- Uninstall: WT profile should be removed.
  - [x] Install (WT profile enabled) -> Uninstall
  - [x] Install (WT profile enabled) -> Re-run the installer and Modify (WT profile disabled)

# After Submitting

No relevant documentation to update.

### CODE REVIEW

**Comment by fdncred** [comment]
I'm so greatly appreciative of you and your work on this. Thanks so much! I'm hoping this fixes the issue.

> It might be better if we provide options for installation context (per-user or per-system) as requested in https://github.com/nushell/nushell/issues/5927

I'd be ok with this in the future as long as our winget_pkgs submissions knows to use the -user one and it works.

**Comment by fdncred** [comment]
We're getting close to a release. Let's land this and see if it works.

**Comment by fdncred** [comment]
Welp, it failed but for a different reason. I'm not sure what's going on. It didn't even get submitted to the winget repo.
https://github.com/nushell/nushell/actions/runs/5226501091/jobs/9437222070

**Comment by wolimst** [comment]
I don't have much knowledge about the tool (winget-releaser github action), but looking at the error message and comparing it to [the previous job from v0.80](https://github.com/nushell/nushell/actions/runs/4998011060/jobs/8952987321), it looks like the number of installer urls is causing the problem.

```
# v0.81
Executing command: java -jar komac.jar update --id 'Nushell.Nushell' --version 0.81.0 --urls 'https://github.com/nushell/nushell/releases/download/0.81.0/nu-0.81.0-aarch64-pc-windows-msvc.msi,https://github.com/nushell/nushell/releases/download/0.81.0/nu-0.81.0-x86_64-pc-windows-msvc.msi' --submit
  The number of unique installer urls is greater than the number of previous manifest urls

# v0.80
Executing command: java -jar komac.jar update --id 'Nushell.Nushell' --version 0.80.0 --urls 'https://github.com/nushell/nushell/releases/download/0.80.0/nu-0.80.0-x86_64-pc-windows-msvc.msi' --submit
```

**Comment by fdncred** [comment]
Good catch. I wonder where that's coming from?

**Comment by fdncred** [comment]
I think @sitiom helped with that CI change. Maybe they can help?

**Comment by wolimst** [comment]
Sorry it didn't work.

> You could add the "requiresElevation" for the machine scope and "prohibitsElevation" for the user scope (as long as no UAC is required).

I think what they are suggesting is related to the winget manifest, not directly related to the installer msi.

From [Winget Manifest Schema for `installer.yaml`](https://github.com/microsoft/winget-pkgs/blob/master/doc/manifest/schema/1.5.0/installer.md):
>
> ElevationRequirement - Indicator for elevation requirements when installing or upgrading packages.
> Optional Field
> 
> This key represents which scope a package is required to be executed under. Some packages require user level execution while others require administrative level execution.
> 
> elevationRequired - Must be run from a shell that is running in an administrative context (e.g - Admin user using powershell/terminal/cmd with "Run as Administrator")
> elevationProhibited - Must be run from a shell that is not running in an administrative context
> elevatesSelf - If called from a non-administrative context, will request elevation. If called from an administrative context, may or may not request elevation.

[`installer.yaml` manifest for nushell](https://github.com/microsoft/winget-pkgs/blob/6cb364f790b5d98555c0be407eedded16e56721d/manifests/n/Nushell/Nushell/0.81.0/Nushell.Nushell.installer.yaml) do not contain `ElevationRequirement` field currently, so I think we should try adding the field as suggested.

About the value for `ElevationRequirement`, I think we should use `requiresElevation` for now (until nushell support user context installation), since the binaries such as `nu.exe` and PATH env variable are installed in system scope, and also `Scope: machine` is specified in [`installer.yaml` manifest for nushell](https://github.com/microsoft/winget-pkgs/blob/6cb364f790b5d98555c0be407eedded16e56721d/manifests/n/Nushell/Nushell/0.81.0/Nushell.Nushell.installer.yaml).

**Comment by fdncred** [comment]
oh, ok. Is this `requiresElevation` setting, is that something you can do a PR for us to use next release?

**Comment by wolimst** [comment]
I think we are using the ci tools ([Winget Releaser](https://github.com/vedantmgoyal2009/winget-releaser) and [Komac](https://github.com/russellbanks/Komac)) for submitting winget PR, is that right?

I don't have much knowledge about those tools, but I think the winget manifest is automatically generated by Komac. If Komac supports `ElevationRequirement`, then we might update the ci script.
If it is not supported, maybe we can manually create a PR just like the current release (v0.81)?

Best if we can get some help from the contributors who helped with the winget submission ci.

**Comment by fdncred** [comment]
> I think we are using the ci tools ([Winget Releaser](https://github.com/vedantmgoyal2009/winget-releaser) and [Komac](https://github.com/russellbanks/Komac)) for submitting winget PR, is that right?

Yup, I think that's right. It happened here https://github.com/nushell/nushell/pull/8070

@sitiom any ideas about this `ElevationRequirement`?

**Comment by sitiom** [comment]
> maybe we can manually create a PR just like the current release

Yes, any changes to the manifest would require a manual PR. Winget Releaser is just used for auto-updating the manifest.

Also, it seems like the installer is failing to install again in a Sandbox?
image

You might want to resolve this first, as this may be connected to the Winget issue. Related: https://github.com/nushell/nushell/pull/8070#issuecomment-1441888310

**Comment by fdncred** [comment]
> Also, it seems like the installer is failing to install again in a Sandbox?

Thanks. Good tip about the sandbox but I have no clue how to resolve that at all. Manually rerunning the CI routines to generate a new MSI, like I did in the prior comment, isn't really an option.

We have to figure this out one way or the other.

**Comment by wolimst** [comment]
Thanks for the info! I was able to reproduce the failure in a sandbox. The error message in the installation log is same with that one of the winget moderator found in their ci system.

```
CAQuietExec:  Error 0xc0000135: Failed in ExecCommon method
CustomAction ReplacePathsInWindowsTerminalProfile returned actual error code 1603 (note this may not be 100% accurate if translation happened inside sandbox)
Action ended 18:49:40: InstallFinalize. Return value 3.
```

I don't know it for sure, but maybe they are running the ci in a sandbox. So, resolving this might solve the issue we are having in the winget ci. I'll look into this further when I have some free time.

@fdncred From https://github.com/nushell/nushell/pull/8070#issuecomment-1441888310, it seems like the manually created installer had no install error. Can you share any detail when you manually re-created the installer?

**Comment by fdncred** [comment]
> Thanks for the info! I was able to reproduce the failure in a sandbox. 

That's great news! Yup, 1603 is that same error code.

> So, resolving this might solve the issue we are having in the winget ci. I'll look into this further when I have some free time.

Oh, that's awesome news. I hope you can find time and figure out exactly what is going on and how to fix it. That would be a huge win and relief to me!

> Can you share any details when you manually re-created the installer?

Sure, but it's a non-trivial manual task, so much so that I tried to document it to match my Windows system here https://github.com/nushell/nushell/blob/7d301c76d37129152c5c7fffbebb85d25c60899b/.github/workflows/release-pkg.nu#L9-L40.
There's no doubt that you'll have to change the paths and such to make it work for you but I tried to list the requirements and exactly how to set all the variables it needs. I usually just end copy copy-n-pasting and running these lines one-by-one.

**Comment by wolimst** [comment]
I think I found the cause of the problem, and after all, it seems like neither windows terminal profile feature nor permission issue are not the main cause. (TLDR is at the bottom of the comment.)

---

Currently, an installer created by [github actions ci for release](https://github.com/nushell/nushell/blob/64319ad90f72e3d67685c9d11ce808d7475c55db/.github/workflows/release.yml) fails to install in a windows sandbox instance, with 1603 error code when executing custom action for windows terminal profile feature.

I was able to install without an error by changing the installer to ignore the result of the wt profile feature and recreated it from the release ci.

But at this point, executing `nu.exe` failed with an error `The code execution cannot proceed because VCRUNTIME140.dll was not found`, which means which means the installer did not contain statically linked MSVC runtime and `nu.exe` couldn't find MSVC runtime for dynamic linking.

It looks like this error is the cause of the installation failure on wt profile feature, since it executes nushell to update the wt profile configuration.

On the other hand, an installer that is manually created by a user does not have this problem. Looking here and there, I found that nushell is already statically linking the MSVC runtime as below.

https://github.com/nushell/nushell/blob/64319ad90f72e3d67685c9d11ce808d7475c55db/.cargo/config.toml#L1-L4

However, these build configurations are abandoned on the ci, because `RUSTFLAGS` env variable has the priority which was set by default as `RUSTFLAGS="-D warnings"` by [actions-rust-lang/setup-rust-toolchain](https://github.com/actions-rust-lang/setup-rust-toolchain/). They have documentation about this behavior in their [README](https://github.com/actions-rust-lang/setup-rust-toolchain/#rustflags).

https://github.com/nushell/nushell/blob/64319ad90f72e3d67685c9d11ce808d7475c55db/.github/workflows/release.yml#L73-L74

By removing the `RUSTFLAGS` env variable, the build configurations above are properly used on the ci, and I was able to install nushell without an error in a windows sandbox instance.

Finally, looking at [the history of PRs for winget submission](https://github.com/microsoft/winget-pkgs/issues?q=nushell.nushell), I found that the verification failure is occurring since v0.73 ([winget PR](https://github.com/microsoft/winget-pkgs/pull/91926)). The wt profile feature was added in v0.65 ([release note](https://www.nushell.sh/blog/2022-07-05-nushell-0_65.html), [winget PR](https://github.com/microsoft/winget-pkgs/pull/76026)) and had no problem on the verification until v0.73. On the other hand, nushell started using `actions-rust-lang/setup-rust-toolchain` on the release ci (#7315) since v0.73 ([release note](https://www.nushell.sh/blog/2022-12-20-nushell-0.73.html)). The timing matches to the start of the winget verification error, which backs up my theory about the cause of the winget verification failure.

---

TLDR:

1. `actions-rust-lang/setup-rust-toolchain` on the nushell's release workflow sets `RUSTFLAGS="-D warnings"` env variable by default, which makes `rustflags` configuration to statically link MSVC runtime ignored. Therefore, an installer automatically created by the release workflow do not contain statically linked MSVC runtime.
2. When installing windows terminal profile feature, nushell is used to update paths. However, executing nushell ends up an error because MSVC runtime is not statically linked and there is no pre-installed one in a sandbox instance for dynamic linking.
3. The timing when the winget verification error started matches with the timing when `actions-rust-lang/setup-rust-toolchain` was added to the release workflow (i.e. when statically linked MSVC runtime started being excluded from the installer), so it seems like it is the cause of the winget verification failure.

**Comment by wolimst** [comment]
So, I think I'll make a PR to remove `RUSTFLAGS` env variable on the release ci. If the winget verification failure is indeed connected to the installation failure in a windows sandbox instance described above, then I think it will fix the problem.

Also, if its ok, I would like to revert the changes made by this PR (that changed install context of wt profile to per-user) back to per-system, since the installer is based on per-system installation and having different installation context among the features creates unnecessary inconsistency.

@fdncred Does this sound good to you?

**Comment by fdncred** [comment]
First of all, wow, big wow! I'm so impressed and thankful that you were able to figure out exactly what is going on. Thank you so much!

> Does this sound good to you?

Yes, it does. I'm excited to see it work.

**Comment by wolimst** [comment]
Thanks. Happy to help! I just created two PRs discussed in the previous comments. I'm hopeful that it will finally resolve the issue in winget PRs since it looks quite promising, but let's wait for the next release to see if it works..!

**Comment by sitiom** [comment]
Seems like its fixed now 🎉: https://github.com/microsoft/winget-pkgs/pull/110786

**Comment by fdncred** [comment]
great work here! our winget create pr action failed for some reason, but after the winget pr got created, it was totally successful! i'm just not sure how the pr got created.

**Comment by fdncred** [comment]
Welp, winget is broke again. I just went through and all the `target_rustflags: ''` seem to be set. No idea what's going on now. Thinking of removing the windows terminal fragment maybe.

**Comment by fdncred** [comment]
Thanks @wolimst. You can see here where i checked for `target_rustflags: ''`. apparently that was the wrong thing to check for 🤣

**Comment by fdncred** [comment]
@wolimst Any time to help diagnose our latest winget + sandbox failures? I have two suspicions:
1. Same old one, UAC is required to write to system level folder, thinking of switching to user level folder.
2. I'm not convinced our guid is calculated correctly in our nu.json WT fragment file as per https://learn.microsoft.com/en-us/windows/terminal/json-fragment-extensions.
3. I've checked the with rustflags and I think they're all still set right.

Any help here would be greatly appreciated.

**Comment by wolimst** [comment]
@fdncred Hi! Is the issue resolved? Looks like the validation in the winget PR is merged after the hash for the msi file is updated.

**Comment by fdncred** [comment]
Hey @wolimst Thanks for checking in. This is resolved for now. Check out PR to see what I did to get it to pass the winget-pkgs validation. https://github.com/nushell/nushell/pull/12720. It wasn't a hash issue.

**Pull request merged**
