### PR TITLE
Allow 'url join' to print username without password

### PR DESCRIPTION
**Pull request by richardwesthaver**
# Description
Fixes: https://github.com/nushell/nushell/issues/11677

# User-Facing Changes

# Tests + Formatting

```
'https://example.com' | url parse | update scheme ssh | upda
te username user | url join
# => ssh://user@example.com/
'https://example.com' | url parse | update scheme ssh | upda
te password hackme | url join
# => ssh://example.com/
'https://example.com' | url parse | update scheme ssh | update username user | update password hackme | url join
# => ssh://user:hackme@example.com/
```
# After Submitting

### CODE REVIEW

**Comment by AucaCoyan** [comment]
I peeped into your solution and I found very clever the use of `match (&self.username, &self.password) {}` with `Option`s 😄 .
You are great!

**Review by fdncred — APPROVED** [review]
Nice change. Looks good, Thanks!

**Comment by fdncred** [comment]
@richardwesthaver Looks like some tests may need to be updated or added to get the CI green.

**Comment by richardwesthaver** [comment]
@fdncred whoops I should have ran before commit, my b! I'll update the test case in a few

**Comment by fdncred** [comment]
Thanks!

**Pull request merged**
