### PR TITLE
Split blocks and closures

### PR DESCRIPTION
**Pull request by jntrnr**
# Description

This splits the concept of a "block" into two things: closures and blocks.

A **closure** is a first-class function. For example:

```
let x = {|y| $y + 100}
```

A closure can capture variables in scope if necessary, hence the name "closure" from the ability to "close" over variables. A closure has a signature that describes how it can be called, placed between pipes. Eg) `{|| 3 + 4}`

A **block** is not a first-class value. Instead, it represents a block of code that will be immediately evaluated by the command it is passed to. Blocks do not have a signature and while they may refer to variables outside of themselves, they do not close over these variables.

```
if true {
  print "hello"
}
```

Reasons for the split:
* This will allow for more easily describing `break` and `return`
* This will allow for access to mutable variables in the immediate scope in the case of blocks. It will also allow us to prevent the mutation of variables in closures, which would cause unsafe sharing issues.
* Makes the use of both more predictable in how they will function at runtime

This change is a step towards the above but not all of the above are yet available. Instead, this change lays the groundwork for the above by doing the split of the closure/block concepts.

# Major Changes

This will be a breaking change for consumers of SyntaxShapes or Types.

# Tests + Formatting

Make sure you've done the following, if applicable:

- Add tests that cover your changes (either in the command examples, the crate/tests folder, or in the /tests folder)
  - Try to think about corner cases and various ways how your changes could break. Cover those in the tests

Make sure you've run and fixed any issues with these commands:

- `cargo fmt --all -- --check` to check standard code formatting (`cargo fmt --all` applies these changes)
- `cargo clippy --workspace --features=extra -- -D warnings -D clippy::unwrap_used -A clippy::needless_collect` to check that you're using the standard code style
- `cargo test --workspace --features=extra` to check that all tests pass

# After Submitting

* Help us keep the docs up to date: If your PR affects the user experience of Nushell (adding/removing a command, changing an input/output type, etc.), make sure the changes are reflected in the documentation (https://github.com/nushell/nushell.github.io) after the PR is merged.

### CODE REVIEW

**Comment by rgwood** [comment]
Nice! This feels like a big step forward, thanks for making it happen.

**Comment by webbedspace** [comment]
Quick question: are `def` bodies blocks or closures? I assume blocks, but then again, wouldn't they close over the arguments and inputs? Ah, but if they are closures, then they'd need `||` at the start, right?

**Comment by jntrnr** [comment]
@webbedspace - there are a couple cases that are closures but don't quite look like it. Right now that's `for` and `def`.

**Comment by kubouch** [comment]
One comment: What happens if a variable is defined inside a block?
```
if true {
    let x = 4
}
```
Quickly looking at the code, it seems to me it would be defined also in the parent scope.

**Comment by jntrnr** [comment]
@kubouch - it fails to typecheck

```
C:\Source\nushell〉if true { let x = 100 }; $x
Error: nu::parser::variable_not_found (link)

  × Variable not found.
   ╭─[entry #1:1:1]
 1 │ if true { let x = 100 }; $x
   ·                          ─┬
   ·                           ╰── variable not found
   ╰────
   ```

**Pull request merged**
