### PR TITLE
Make only_buffer_difference: true work

### LINKED ISSUE #8091: completion_menu crashes if `only_buffer_difference` is `true`
### Describe the bug

If I do `cd <tab>` it returns nothing, and then if I hit `c` it panics like this:
``` 
cd thread 'main' panicked at 'insertion index (is 3) should be <= len (is 1)', library/alloc/src/vec/mod.rs:1445:13 FOUND
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrack
```

I narrowed this down to this completion_menu in my config. Note it's matches the default_config.nu except the colors are different and `only_buffer_difference` is `true` here and `false` in the default_config.nu.
```
  {
    name: completion_menu
    only_buffer_difference: true
    marker: $"(char -u 1f4ce) "
    type: {
      layout: columnar
      columns: 4
      col_width: 20   # Optional value. If missing all the screen width is used to calculate column width
      col_padding: 2
    }
    style: {
      text: { fg: "#33ff00" }
      selected_text: { fg: "#0c0c0c" bg: "#33ff00" attr: b}
      description_text: yellow
    }
  }
```

if `only_buffer_difference: true` it crashes. If it's `false` it does not crash.

This is fernando's documentation for that menu option.
```
only_buffer_difference: true # Search is done on the text written after activating the menu
```

### How to reproduce

See above

### Expected behavior

Even if `only_buffer_difference` is supposed to be `false` and I have it set to `true` it shouldn't panic. I've had this value set to `true` for (probably) years. So, I'm guessing that this is a recent regression.

### Screenshots

_No response_

### Configuration

|key|value|
|-|-|
|version|0.75.1|
|branch|main|
|commit_hash|ade7bde813218ed599552731266eea844766b9cc|
|build_os|macos-aarch64|
|build_target|aarch64-apple-darwin|
|rust_version|rustc 1.66.1 (90743e729 2023-01-10)|
|rust_channel|1.66.1-aarch64-apple-darwin|
|cargo_version|cargo 1.66.1 (ad779e08b 2023-01-10)|
|pkg_version|0.75.1|
|build_time|2023-02-16 05:37:23 -06:00|
|build_rust_channel|release|
|features|database, dataframe, default, trash, which, zip|
|installed_plugins|custom-value generate, custom-value generate2, custom-value update, from eml, from ics, from ini, from parquet, from plist, from vcf, gstat, hist, inc, nu-example-1, nu-example-2, nu-example-3, periodic-table, plot, pnet, query, query json, query web, query xml, regex, xyplot|

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by ysthakur**
# Description

This PR is for fixing #8091 (making `only_buffer_difference: true` work). Relies on https://github.com/nushell/reedline/pull/695.

Here's a recording of how it looks:

[asciicast](https://asciinema.org/a/J5iTgVdgrcm8vYvgLWDbHMqvE)

I'm not sure what it's supposed to look like, having never experienced the original behavior, so if someone who knows could try out this branch, that'd be cool. Just a note, you'll have to change the Reedline dependency to `reedline = { git = "https://github.com/ysthakur/reedline.git", branch = "fix-nu-8091" }`.

# User-Facing Changes

# Tests + Formatting

I haven't tested the changes to `src/ide.rs` and `nu-lsp/src/lib.rs`.

# After Submitting

I'm temporarily using my branch on the [other PR](https://github.com/nushell/reedline/pull/695) for the Reedline dependency in Cargo.toml. Once that PR's merged, I can make Cargo.toml use `nushell/reedline.git` again

### CODE REVIEW

**Comment by fdncred** [comment]
That's a lot of changes to the cargo.lock file. Did you just update reedline?

**Comment by ysthakur** [comment]
@fdncred Whoops, deleted the lock file at some point while trying to figure out why cargo was saying the reedline patch was unused, didn't realize that meant everything woulf get upgraded. Should be fixed now

**Comment by fdncred** [comment]
I can't merger it from my phone. It says, "Head branch was modified" and doesn't allow squash and merger. Does that mean you need to rebase?

**Comment by ysthakur** [comment]
Huh, weird, I'll try rebasing

**Comment by fdncred** [comment]
Looks like it finally worked.

**Pull request merged**
