### PR TITLE
change default keybinding in default config

### PR DESCRIPTION
**Pull request by WindSoilder**
# Description

Introduce new keybinding `ctrl-y` in default, I use it heavily with `ctrl-k`...

And move var menu from `ctrl-y` to `alt-o`, the `alt-o` comes from [pycharm navigate to symbol](https://www.jetbrains.com/pycharm/guide/tips/navigate-to-symbol/), which is using `Alt-Cmd-O in macOS`

`alt-o` looks similar to it, so I chose `alt-o`

# Tests

Make sure you've done the following:

- [ ] Add tests that cover your changes, either in the command examples, the crate/tests folder, or in the /tests folder.
- [ ] Try to think about corner cases and various ways how your changes could break. Cover them with tests.
- [ ] If adding tests is not possible, please document in the PR body a minimal example with steps on how to reproduce so one can verify your change works.

Make sure you've run and fixed any issues with these commands:

- [x] `cargo fmt --all -- --check` to check standard code formatting (`cargo fmt --all` applies these changes)
- [X] `cargo clippy --workspace --features=extra -- -D warnings -D clippy::unwrap_used -A clippy::needless_collect` to check that you're using the standard code style
- [x] `cargo test --workspace --features=extra` to check that all the tests pass

### CODE REVIEW

**Comment by stormasm** [comment]
@WindSoilder I believe on a mac keyboard 

the Alt key is = 

Shift-Option

I tried it a few times and it seems pretty simple to hit on my keyboard...

curious to see what @fdncred thinks about introducing the Alt key as we don't currently use it for any 

default keybinding commands,

but if people like it --- it will open the door for other Alt key commands in the future...

**Comment by fdncred** [comment]
I use iterm2 on my Mac and I have it setup so I can do option-o like alt-o without issue. I'm fine with it.

**Comment by WindSoilder** [comment]
Oh... I never though about `alt` in `mac` keyboard, in different terminal, `alt` may need extra setup(like iterm2, alacritty) to make it works property.  

I'm not sure if `alt` introduces not frendly usage on mac.

**Comment by fdncred** [comment]
It's probably fine.

**Comment by stormasm** [comment]
Unfortunately it does not appear to be working on my mac and I use the standard out of the box terminal

Monterey Terminal.app Version 2.12 (443)

So we might not be able to use this binding...

**Comment by stormasm** [comment]
just curious @fdncred can you fire up the standard terminal I am using on your mac and see if it works for you ?

**Comment by stormasm** [comment]
For simplicity for now I think I would stick with either the 

**modifier: Shift**
**modifier: Ctrl** 

which is the way we currently have the default keybindings...

We can leave the ALT keys etc... to people's custom bindings....

And then we don't have to worry about all of the keyboard issues / international keyboards etc....

I think all keyboards and platforms have shift and control by default.

Just my 2 cents 😄

**Comment by WindSoilder** [comment]
I've tested in mac terminal, it works fine for me, but we need to have extra setup: `Use Option as Meta key`, as the following screenshot, enable this should make `alt` on mac work as expected.

图片

**Comment by fdncred** [comment]
@stormasm, After making the change that @WindSoilder suggests alt-o works fine in terminal.app. We also cannot use ctrl-o as it's already used. Check `keybindings default`.

**Comment by stormasm** [comment]
@fdncred @WindSoilder 

ok we are good !   we can now start using the ALT modifier for future key bindings.... 

I tested 

**modifier : alt**

based on making the config change recommended above in the terminal preferences window....

Thank you both for helping me out here with this particular issue 😄

**Comment by fdncred** [comment]
thanks

**Comment by stormasm** [comment]
@WindSoilder @fdncred just updated to latest code base and deleted config.nu so that it could get the latest version and it works great !!

glad to know now that we can use ALT on the mac

great job...
in tracking this down...

**Pull request merged**
