### PR TITLE
Add `detailed` flag for `describe`

### PR DESCRIPTION
**Pull request by gaetschwartz**
- Add `detailed` flag for `describe`

- Improve detailed describe and better format when running examples.

# Rationale

For now, neither `describe` nor any of the `debug` commands provide an easy and structured way of inspecting the data's type and more. This flag provides a structured way of getting such information. Allows also to avoid the rather hacky solution 
```nu
$in | describe | str replace --regex '<.*' ''
```

# User-facing changes

Adds a new flag to ``describe`.

### CODE REVIEW

**Comment by fdncred** [comment]
This is kind of interesting because it's somewhere between the `describe` command and the `debug` commands. One thing that didn't seem to work for me was printing `metadata`.

I believe there should be pipeline metadata attached to this command.
```nushell
ls | describe -d
```
just like if you had done
```nushell
ls | metadata
```

**Comment by fdncred** [comment]
I'm guessing that it's because you're using `_,_` in `PipelineData::ListStream(_, _)`? or you could just get it at the beginning for all like `input.metadata()` and pass it on through. That's where I'd start.

**Comment by fdncred** [comment]
Thanks

**Comment by fdncred** [comment]
For some reason this broke main where it won't compile now. Not quite sure how CI passed but it can't compile.

**Comment by amtoine** [comment]
> For some reason this broke main where it won't compile now. Not quite sure how CI passed but it can't compile.
>
i can reproduce :+1:

**Comment by amtoine** [comment]
@fdncred
as you can see, the CI in the PR passed but the CI on `main` did not.
i think this can happen when a commit that are landed in the meantime introduces a bug when the new PR lands as well :thinking:

**Comment by fdncred** [comment]
I have it about fixed now. Just texting/checking it.

**Comment by fdncred** [comment]
Just found that `detailed -d` doesn't work on `sys`. I'm guessing that's because it's a LazyRecord, but I think it should handle that and produce some type of output. What do you think @gaetschwartz?

**Comment by gaetschwartz** [comment]
I went through the code and overlooked a part, sending a pr soon 😳

**Comment by gaetschwartz** [comment]
#10836

**Pull request merged**
