### PR TITLE
Implement PWD recovery

### PR DESCRIPTION
**Pull request by YizhePKU**
This PR has two parts. The first part is the addition of the `Stack::set_pwd()` API. It strips trailing slashes from paths for convenience, but will reject otherwise bad paths, leaving PWD in a good state. This should reduce the impact of faulty code incorrectly trying to set PWD. (https://github.com/nushell/nushell/pull/12760#issuecomment-2095393012)

The second part is implementing a PWD recovery mechanism. PWD can become bad even when we did nothing wrong. For example, Unix allows you to remove any directory when another process might still be using it, which means PWD can just "disappear" under our nose. This PR makes it possible to use `cd` to reset PWD into a good state. Here's a demonstration:

```sh
mkdir /tmp/foo
cd /tmp/foo

# delete "/tmp/foo" in a subshell, because Nushell is smart and refuse to delete PWD
nu -c 'cd /; rm -r /tmp/foo'

ls          # Error:   × $env.PWD points to a non-existent directory
            # help: Use `cd` to reset $env.PWD into a good state

cd /
pwd         # prints /
```

Also, auto-cd should be working again.

### CODE REVIEW

**Comment by fdncred** [comment]
Could you add a test with autocd as well so we can test that functionality? One of the reasons it's failing now is because we must not have had a good test for it.

**Comment by WindSoilder** [comment]
It should fix: https://github.com/nushell/nushell/issues/8072

**Comment by YizhePKU** [comment]
Testing auto-cd is tricky, because the `nu!` macro and friends invoke Nushell with `-c`, so auto-cd doesn't work. I'll figure something out.

**Comment by fdncred** [comment]
We understand that our test-harness is not perfect. We'd gladly accept PRs to that as well. Just sharing information and off-topic, but one thing we've talked about for a while is having some type of vte/pseudotty where we can very precisely run things and look at returns including ansi escapes. Reilly started this project as a quick prototype https://github.com/rgwood/pty-driver.

**Comment by WindSoilder** [comment]
Maybe you can `nu_repl_code` to test auto-cd?

**Comment by sholderbach** [comment]
Would unit-testing `do_auto_cd` suffice as a stop gap measure or is there more special logic to provide it with `cwd` that would go untested that way?

**Comment by YizhePKU** [comment]
> Maybe you can use nu_repl_code to test auto-cd?

I looked at the source code of the `nu_repl` test binary, and it seems it just re-implements some of the REPL functionality without ever invoking `nu-cli`. Specifically, it doesn't seem to support auto-cd. I wonder what its original purpose was?

> Would unit-testing do_auto_cd suffice as a stop gap measure or is there more special logic to provide it with cwd that would go untested that way?

Since auto-cd is REPL specific, I think some kind of behavior testing would be more effective, like emulating an entire TTY and observe interactions. Though if we can't do that, unit testing is certainly better than nothing.

**Comment by fdncred** [comment]
It would be good to land this sooner rather than later so maybe just unit test for now.

**Comment by WindSoilder** [comment]
> I wonder what its original purpose was?

There are some issues that only happened in repl, I guess that's the reason to use `nu_repl` to test such case

**Comment by YizhePKU** [comment]
I've add some unit tests on `parse_operation` and `do_auto_cd`. It's not the same as the real REPL interactions, but it should be good enough.

Some issues I found during testing:

* `foo/` doesn't work on Windows, only `foo\`. Should we allow `foo/` to work on Windows as well?
* auto-cd works with backticks only. Is that intentional? Also I think backticks are under-documented in general.

**Comment by fdncred** [comment]
> Should we allow foo/ to work on Windows as well?

My preference would be for either `foo\` or `foo/` to work on Windows.

> auto-cd works with backticks only.

Backticks should only be involved if there is a space in the folder like "Program Files", otherwise backticks shouldn't be needed. They're not needed on macos. I can just type `crates/` and it cds just fine.

> Also I think backticks are under-documented in general.

Agreed

In general, fully documenting backtick quotes would be great, but that's for another issue where we can collab all the things that backtick quotes do.

**Comment by YizhePKU** [comment]
Are we OK with merging this?

**Comment by fdncred** [comment]
It looks like we're saving `foo\` vs `foo/` for later PRs, which I'm fine with. But what about your comment of autocd only working with backticks, that should not be the case.

**Comment by YizhePKU** [comment]
> But what about your comment of autocd only working with backticks, that should not be the case.

That's a miscommunication on my part. What I actually meant was "auto-cd works with either unquoted strings or backticks, but not with other types of quotes". This has always been the expected behavior, so there's no problem here. Typing `crates/` works just fine.

**Comment by fdncred** [comment]
Thanks @YizhePKU. We appreciate your continued help!

**Comment by rgwood** [comment]
Yes, @YizhePKU thank you for continuing to make this functionality better!

**Pull request merged**
