### PR TITLE
Switch the parser to stop using Strings instead of Spans to represent quoted strings

### LINKED ISSUE #1456: Nushell can't handle escaped " on echo
**Describe the bug**
I tried to run this simple command and it failed `echo "\"foo\""`

**To Reproduce**
`echo "\"foo\""`

**Expected behavior**
it should echo `"foo"`

**Configuration (please complete the following information):**
 - OS: osx
 - Version 0.10
 - all features enabled

```
❯ echo "\"foo\""
error: Parse Error
- shell:1:14
1 | echo "\"foo\""
  |
```

### PR DESCRIPTION
**Pull request by Sosthene-Guedon**
This replaces the PR #1520.
Since the first PR was way too big, this one is smaller and only deals with double quoted strings.

This PR changes the parser to use copied strings from the original input instead of a span. This allows the implementation of escaping in double quoted strings. This fixes #1456. Now `echo "fo\"o"` doesn't fail and displays `fo"o`. Slashes can also be escaped `echo "foo\\"` displays `foo\`.

This fix applies to any command using double quoted string.

### CODE REVIEW

**Comment by Sosthene-Guedon** [comment]
It might be worth discussing how we should deal with some escape sequences.
Do we want the parser to interpret "\t" as a tab (and do the same for other escape sequences like \n etc... or do we want to let the command handle that and pass it the 2 char "\t" string?
It seems bash does it the second way.

**Comment by jonathandturner** [comment]
@Sosthene-Guedon - a few things.  One, sorry it's taking so long. I/we have been busy working on a new parser. I've tried to incorporate some of the stuff that came up in discussions with your work into it, so that it's easier to add formatters and escaping in the future.  You can see more here: https://github.com/nushell/nushell/pull/1554.  

As for what escaping should look like, I think one idea we should explore is something that's easier for beginners to understand.  For things like `\r` and `\n` you have to know how programming languages do it, and what each thing means.

One approach we could take is to add a few terms you could use.  Like `"this is a {tab}"` where `{tab}` would get replaced with a tab character.

It's a little longer to type but a little easier to read, also.

**Comment by jonathandturner** [comment]
Just to add also, I'm happy to work with you to help adapt your work for the new parser or to see if we can extend the parser with some of the ideas you wanted to make sure it was capable of.

**Comment by Sosthene-Guedon** [comment]
I took a look at the new parser and it doesn't seem that any of the code from this PR is usable in the new parser.

Also it seems that the new parser already copies strings so implementing escape sequences shouldn't be hard. I'll make a PR for that.

**Pull request closed without merging**
