### PR TITLE
Add environment engine calls for plugins

### PR DESCRIPTION
**Pull request by devyn**
# Description

This adds three engine calls: `GetEnvVar`, `GetEnvVars`, for getting environment variables from the plugin command context, and `GetCurrentDir` for getting the current working directory.

Plugins are now launched in the directory of their executable to try to make improper use of the current directory without first setting it more obvious. Plugins previously launched in whatever the current directory of the engine was at the time the plugin command was run, but switching to persistent plugins broke this, because they stay in whatever directory they launched in initially.

This also fixes the `gstat` plugin to use `get_current_dir()` to determine its repo location, which was directly affected by this problem.

# User-Facing Changes
- Adds new engine calls (`GetEnvVar`, `GetEnvVars`, `GetCurrentDir`)
- Runs plugins in a different directory from before, in order to catch bugs
- Plugins will have to use the new engine calls if they do filesystem stuff to work properly

# Tests + Formatting
- :green_circle: `toolkit fmt`
- :green_circle: `toolkit clippy`
- :green_circle: `toolkit test`
- :green_circle: `toolkit test stdlib`

# After Submitting
- [ ] Document the working directory behavior on plugin launch
- [ ] Document the new engine calls + response type (`ValueMap`)

### CODE REVIEW

**Comment by fdncred** [comment]
Thanks @devyn. 

I'd like @kubouch to sign off on this because we have to be very careful about how we get and set env vars. Part of it may be ok since you're calling into `stack.get_env_var()`. But some may not be. I'm not sure the `current_dir()` and `set_current_dir()` are ok since we have `nu_engine::env::current_dir(engine_state, stack)`.

**Comment by devyn** [comment]
We could do a separate engine call if you'd rather. I just copied the same logic in `nu_engine::env::current_dir` over to the plugin side, but I guess that would be best if that logic changes.

**Comment by devyn** [comment]
Actually, let's just do that. I'll fix it. I'd rather have correct behavior going into the future than fewer engine calls, and it will be better to ensure other language plugins do the right thing too.

**Comment by devyn** [comment]
That's done now. Specifically calling `nu_engine::env::current_dir_str` instead

@fdncred 

The calls to `std::env::set_current_dir` should be fine, because `EngineInterface` is only used in plugin code, and that's where we want the current directory to reflect the engine one.

**Comment by devyn** [comment]
I'm slightly bummed that plugins will have to carefully manage the current directory in order to do filesystem stuff correctly, but I guess that's no different than any code in the engine.

This should finally be correct - I'm not suggesting anyone do `std::env::set_current_dir` anymore, and `gstat` as an example just joins to what it gets from `engine.get_current_dir()` to determine the repo path. I also cleaned up some of that logic anyway.

**Comment by fdncred** [comment]
Thanks all. Let's move forward with this now.

**Pull request merged**
