### PR TITLE
Make 'each' implicitly filter out nothings

### LINKED ISSUE #4341: prints blank rows when else loop is commented out
I'm puzzled because I've had to remove all my `(char nl)` commands in an effort to stop double printing new lines. I'm also getting extra new lines on a loop iteration that I'm not sure where they're coming from. with this snippet below it's as if the else loop is just printing a new line and nothing else when it's commented out. when it's not commented out, it prints as it should.

```
let param_missing_in_eq = ($eq_param | to json | str length)
if $param_missing_in_eq == 2 {
    $"missing: command [($cmd)] exists but parameter [($param_name)] is missing in eq"
} 
# else {
#     $"found: command [($cmd)] found param type [($x.parameter_type)]"
# }
```

_Originally posted by @fdncred in https://github.com/nushell/engine-q/issues/739#issuecomment-1013540683_

### PR DESCRIPTION
**Pull request by jntrnr**
# Description

Like the change for #4536, this makes a similar change for `each`

fixes #4341 
  
# Tests

Make sure you've run and fixed any issues with these commands:

- [x] `cargo fmt --all -- --check` to check standard code formatting (`cargo fmt --all` applies these changes)
- [x] `cargo clippy --all --all-features -- -D warnings -D clippy::unwrap_used -A clippy::needless_collect` to check that you're using the standard code style
- [x] `cargo build; cargo test --all --all-features` to check that all the tests pass

### CODE REVIEW

**Comment by jntrnr** [comment]
Switching to draft and pinging @andrasio. I *think* this might have repercussions we don't want, where someone might want to default `$nothing` to some value, but they won't be able to because we've already filtered them out.

**Comment by andrasio** [comment]
so I believe we should have another command called `map`

`map` should preserve nothings (current behavior of `each`).

`each` on the other hand should be thought of (like `for`) side effecting constructs instead and they should return the same stream of values that come from the input no matter what.

I think we've always had `each` working as if it were `map` because for each value coming in it applies and returns the value coming out of the block.

Making `each` and `for` filter out `$nothing` values implicitly does not feel correct.

**Comment by jntrnr** [comment]
@andrasio - originally, we had talked about having `map` as it's closer to what other functional languages do. Soon after though, we switched away from just using functional programming terminology, hoping to find command names that fit a bit better with a broader audience.

Need to think about this one. It would definitely break all the scripts, so if we want to go this way, we should do it soon.

**Comment by jntrnr** [comment]
@andrasio - going to land, but I think we should watch to make sure we have the right default. You may be right and we might need to flip the default around, or explore adding another type of iterating command.

**Comment by fdncred** [comment]
love this change :)

**Comment by andrasio** [comment]
@jntrnr Agreed. We did talk about it and `each` landed instead. The main reason was naming (and it felt a little odd to me since `each` behaves exactly like `map` and coming myself with a mental model of a programming language (errrrr Ruby) where `each` and `map` exists... well).

Our `each` behaves exactly like `map` in FP languages. With this change, `each` will be like a `flat-map` instead (because it continues to transform each value)

**Pull request merged**
