### PR TITLE
fix: add missing crates to `Cargo.toml`

### PR DESCRIPTION
**Pull request by MangoIV**
# Description

Hi, as mentioned in #8155, some packages in the `crates` directory are not mentioned in the workspace, perhaps they should be added.

# User-Facing Changes

- none

# Tests + Formatting

Don't forget to add tests that cover your changes.

Make sure you've run and fixed any issues with these commands:

- [x] `cargo fmt --all -- --check` to check standard code formatting (`cargo fmt --all` applies these changes)
- [x] `cargo clippy --workspace -- -D warnings -D clippy::unwrap_used -A clippy::needless_collect` to check that you're using the standard code style
- [x] `cargo test --workspace` to check that all tests pass

# After Submitting

- n/a

### CODE REVIEW

**Comment by MangoIV** [comment]
if any nix users is searching this repo: https://git.sr.ht/~mangoiv/nu-shell.nix/tree , here you go.

**Comment by stormasm** [comment]
I am pretty sure we don't want to add extra stuff into our Cargo.toml file if it is not needed in the build...
We are trying to keep things as small as possible...
So the reason they are not referenced is because they are not needed.
I am closing this PR.
If someone else has a good reason to add extra stuff in we can re-open this PR.

**Comment by MangoIV** [comment]
I can perhaps go through which ones are needed exactly.

**Comment by sholderbach** [comment]
I am gonna reopen it out of curiosity if the coverage changes drastically (somehow the upload failed for this run). Have to read up on cargo's documentation what the implications for the subcrates are depending on their mention there.

**Comment by MangoIV** [comment]
It’s a bit weird, perhaps I should’ve asked before; are there parts of this repo that should not check/ work? Because there’s actually a bunch of tests that fail…

**Comment by MangoIV** [comment]
Maybe it’s simply due to the nix environment, though, I’ll have to compile without nix once I get home…

**Comment by sholderbach** [comment]
Mhh in the CI the tests were passing but uploading the `lcov.info` or its metadata failed.

**Comment by MangoIV** [comment]
Ah perhaps my failures happened because I didn’t build with the ci profile…

**Comment by sholderbach** [comment]
According to https://doc.rust-lang.org/cargo/reference/workspaces.html#the-members-and-exclude-fields the crates we explicitly depend on in the dependencies of nu and are specified with a relative path will also be `workspace.members`, so it should only affect the plugins explicitly.

**Comment by MangoIV** [comment]
Cargo so smart, amazing

**Comment by MangoIV** [comment]
Without source cleaning, it works. I’ll close this. Thank you for your time and please excuse the fuzz. I wasn’t aware that cargo is so smort

**Comment by sholderbach** [comment]
Thanks for playing attention to the details and giving it a shot!

**Comment by stormasm** [comment]
@MangoIV Thank you as well !  Glad to have you helping us figure all of this stuff out 👍

**Comment by MangoIV** [comment]
> Thank you as well ! Glad to have you helping us figure all of this stuff out

What's with the irony? @.@

**Comment by stormasm** [comment]
@MangoIV no irony --- I was just being honest in a more global sense of nushell ---- 

we have lots of hard problems to solve and when people like yourself are in there looking at our code making valuable suggestions that is important.  We don't always get it right sometimes but that doesn't matter...  Its about learning along the way....

**Comment by MangoIV** [comment]
Thank you. Good that i could - perhaps indirectly - be helpful. And please excuse the false accusation.

**Pull request closed without merging**
