### PR TITLE
Add support for the `ps` command on FreeBSD, NetBSD, and OpenBSD

### LINKED ISSUE #6862: Freebsd, only "ls" shows a table.
### Question

With the exception of "ls" all commands show no table.
"ps" does not show a table
"zfs list" does not show a table
Even "zfs list | table -n 1" does not show a table.

This does not look like a new shell but an improved "ls". Or did i missed something.

### Additional context and details

_No response_

### PR DESCRIPTION
**Pull request by devyn**
# Description

I feel like it's a little sad that BSDs get to enjoy almost everything other than the `ps` command, and there are some tests that rely on this command, so I figured it would be fun to patch that and make it work.

The different BSDs have diverged from each other somewhat, but generally have a similar enough API for reading process information via `sysctl()`, with some slightly different args.

This supports FreeBSD with the `freebsd` module, and NetBSD and OpenBSD with the `netbsd` module. OpenBSD is a fork of NetBSD and the interface has some minor differences but many things are the same.

I had wanted to try to support DragonFlyBSD too, but their Rust version in the latest release is only 1.72.0, which is too old for me to want to try to compile rustc up to 1.77.2... but I will revisit this whenever they do update it. Dragonfly is a fork of FreeBSD, so it's likely to be more or less the same - I just don't want to enable it without testing it.

Fixes #6862 (partially, we probably won't be adding `zfs list`)

# User-Facing Changes
`ps` added for FreeBSD, NetBSD, and OpenBSD.

# Tests + Formatting
The CI doesn't run tests for BSDs, so I'm not entirely sure if everything was already passing before. (Frankly, it's unlikely.) But nothing appears to be broken.

# After Submitting
- [ ] release notes?
- [ ] DragonflyBSD, whenever they do update Rust to something close enough for me to try it

### CODE REVIEW

**Comment by fdncred** [comment]
I'm happy for this and it actually shows one-way nushell has evolved by people working on parts that they find fun in. I've changed the windows part a few times. Sophia has changed the linux parts a few times. We've both changed the macos parts a few times, all in the name of fun.

At some point, it would be nice to unite all these parts, so the readout is identically supported across os's. I haven't looked but as I recall, there are some things implemented around here that aren't the same in every os, like additional columns and such.

Good work! Keep it up!

**Comment by devyn** [comment]
> I haven't looked but as I recall, there are some things implemented around here that aren't the same in every os, like additional columns and such.

Yeah, that's true. One big improvement I think would be to have the process information implement a trait rather than just being a convention. That would make it easier to be sure about what should be there, and errors about incorrect or missing functionality at compile time would be better.

As far as the extra columns go, I think it's a good thing that there are some more OS-specific things exposed - process management is very OS specific, and we have a nice set of universal columns that are pretty standardized for portable scripts to use. I would actually like to see some more things exposed on Unixes, like process group ID for example, in the long form.

**Comment by devyn** [comment]
Environment is something we could probably support elsewhere. It's possible to configure the Linux kernel to not allow other processes to read environment variables, though, I think, and I'm not sure if macOS allows it or not

Still, this works for me on Linux, so I'm guessing it is usually allowed there:

```nushell
open /proc/<pid>/environ | split row "\u{0}" | parse "{key}={value}"
```

**Comment by devyn** [comment]
This is ready now.

- @0323pin, would you mind checking this out for me on NetBSD? I also found out that the `mimalloc` feature does work if you set `CC=clang` while building, it just doesn't like GCC.
- @yurivict or @nibon7, I saw you were both active in #11373, so if you're able to give me your thoughts about this on FreeBSD I would really appreciate that. No pressure though.

**Comment by 0323pin** [comment]
@devyn 🚀 
Awesome! Sure, I'll test this. Although, I won't get to my laptop before tomorrow.

**Comment by 0323pin** [comment]
Alright, so here we go 😄 ...

`ps` works flawlessly now, thank you!

2024-05-20-094028_1366x768_scrot

As for enabling `mimalloc` by default, I'm a bit more concerned.
I had to build using no default features, features = plugin which-support trash-support sqlite
NetBSD uses gcc as the default compiler and it does indeed fail to build when `mimalloc` is enabled.

**Comment by devyn** [comment]
Great! Yeah, unfortunately it doesn't seem to work with GCC. If it hasn't been reported already I will, but I'm not entirely sure if it's a GCC bug or a mimalloc bug

**Comment by 0323pin** [comment]
Thank you!

**Pull request merged**
