### PR TITLE
Add two further path cmds - type and exists

### PR DESCRIPTION
**Pull request by mattyhall**
Sorry for splitting this up over two PRs (the other being #2255) - just thought of these two extra commands that could be helpful today :)

### CODE REVIEW

**Comment by jonathandturner** [comment]
@mattyhall - realized what was causing the failure. In examples, you can only access a small subset of commands. This was preventing the example with `path expand` to work

**Comment by jonathandturner** [comment]
Looks good!

**Comment by fdncred** [comment]
@mattyhall What am I doing wrong here. Trying to play with your new `path` commands.
image

**Comment by mattyhall** [comment]
Away from my dev machine atm but I think it is because ls gives you a table (_with multiple columns_). You need to do something like:
`ls | first | get name | path type`
or
`ls | first | path type name`

**Comment by fdncred** [comment]
Great! Thanks for the help. All the `path` commands seem to work like you suggested except `basename`. I'm doing `ls *.toml | each { path basename name }`

**Comment by mattyhall** [comment]
No worries. That does seem to work for me:
```
/home/matt/Documents/Programming/Rust/nushell> ls *.toml | each { path basename name }
───┬───────────────┬──────┬────────┬──────────────
 # │ name          │ type │ size   │ modified
───┼───────────────┼──────┼────────┼──────────────
 0 │ Cargo.toml    │ File │ 5.6 KB │ 21 hours ago
 1 │ Makefile.toml │ File │  449 B │ 5 days ago
 2 │ features.toml │ File │  632 B │ 5 days ago
 3 │ rustfmt.toml  │ File │   16 B │ 5 days ago
───┴───────────────┴──────┴────────┴──────────────
/home/mjh/Documents/Programming/Rust/nushell>
```

For reference, bash:
```
/home/matt/Documents/Programming/Rust/nushell> for file in `ls *.toml`; do echo $(basename $file); done
Cargo.toml
features.toml
Makefile.toml
rustfmt.toml
```

What were you expecting in this case?

**Comment by fdncred** [comment]
Thanks @mattyhall for the examples. I guess this just comes down to my understanding of how `basename` works. I've always used it in shell scripts to represent the filename without the extension. Maybe this is why C# has a property called `FilenameWithoutExtension`. LOL. 

So, if `basename` is working the way it should, and it appears, based on your examples, it is, then maybe we need another command for filename without extension. Either that or allow `basename` to take parameters so one could do something like `ls *.toml | each { path basename name --ext ".toml" }`.

BTW - I'm not saying you need to write that change (but you can if you want). I'm just testing my understanding based on what you've said and looking for your opinion.

**Comment by jonathandturner** [comment]
Not sure if there is an official name for that part. I see that Rust calls it "file stem"

https://doc.rust-lang.org/std/path/struct.Path.html

**Comment by fdncred** [comment]
I'm good with `file_stem`. I'm not sure that communicates `filename_without_extension` as well, but i'm good with idiomatic rust names.

**Pull request merged**
