### PR TITLE
Fix issue with head on separation lines

### LINKED ISSUE #13287: tables with header_on_separator set to true and columns with spaces could appear truncated when they aren't actually
### Describe the bug

I noticed what may be a bug in `header_on_separator` functionality that makes me not want to use it by default until the bug is fixed. Here's the bug. When columns are truncated, meaning there are more columns than the width of the terminal, columns with spaces in them get truncated too.

Example:
```nushell
❯ open -r test.csv
Supplier No,Supplier Name,Supplier Address 1,Supplier Address 2,Supplier Address 3/Town
nushell,nushell,nushell,nushell,nushell
```

On a narrow terminal (notice that every column appears to be "Supplier ")
```nushell
❯ open test.csv
╭─#─┬─Supplier  ─┬─Supplier  ─┬─Supplier  ─┬─Supplier   ─┬─...─╮
│ 0 │ nushell    │ nushell    │ nushell    │ nushell     │ ... │
╰───┴────────────┴────────────┴────────────┴─────────────┴─────╯
❯ $env.config.table.header_on_separator = false 3
❯ open test.csv
╭───┬────────────┬────────────┬────────────┬─────────────┬─────╮
│ # │ Supplier   │ Supplier   │ Supplier   │ Supplier    │ ... │
│   │ No         │ Name       │ Address 1  │ Address 2   │     │
├───┼────────────┼────────────┼────────────┼─────────────┼─────┤
│ 0 │ nushell    │ nushell    │ nushell    │ nushell     │ ... │
╰───┴────────────┴────────────┴────────────┴─────────────┴─────╯
```
On a wider terminal
```nushell
❯ $env.config.table.header_on_separator = true
❯ open test.csv
╭─#─┬Supplier No┬Supplier Name┬Supplier Address 1┬Supplier Address 2┬Supplier Address 3/Town╮
│ 0 │ nushell   │ nushell     │ nushell          │ nushell          │ nushell               │
╰───┴───────────┴─────────────┴──────────────────┴──────────────────┴───────────────────────╯
```

### How to reproduce

See above

### Expected behavior

I'm thinking that we should not allow columns with spaces in them to be truncated this way. We should just fill the width of the screen with the full column header text until there isn't enough room and just `...` the rest of the columns.

### Screenshots

_No response_

### Configuration

|key|value|
|-|-|
|version|0.95.1|
|major|0|
|minor|95|
|patch|1|
|branch|main|
|commit_hash|0d060aeae85ac53baf89f776bc236f7dad0ba3cf|
|build_os|windows-x86_64|
|build_target|x86_64-pc-windows-msvc|
|rust_version|rustc 1.77.2 (25ef9e3d8 2024-04-09)|
|rust_channel|1.77.2-x86_64-pc-windows-msvc|
|cargo_version|cargo 1.77.2 (e52e36006 2024-03-26)|
|build_time|2024-07-02 07:40:33 -05:00|
|build_rust_channel|release|
|allocator|mimalloc|
|features|default, sqlite, system-clipboard, trash|
|installed_plugins|formats 0.95.1, gstat 0.95.1, inc 0.95.1, jwalk 0.5.0, polars 0.95.1, query 0.95.1, stress_internals 0.95.1|

### Additional context

/cc @zhiburt Is this something you have time to work on? Ping me with questions if you have them.

### PR DESCRIPTION
**Pull request by zhiburt**
Hi there,

Seems to work

Though I haven't done a lot of testing.

image
image
image
image
image

close #13287
cc: @fdncred 

PS: Yessssss I do remember about emojie issue..... :disappointed:

### CODE REVIEW

**Comment by zhiburt** [comment]
ok seems like tested enough

**Comment by fdncred** [comment]
Thanks @zhiburt. I think this is a good start but it may not be quite right yet.

This PR
image

Before this PR
image

With header_on_separator = false
image

I think we want to show the entire header all on one line, without truncating. Without showing it all, it's hard to tell what it is. I'm wondering if it would be better to at least give an indication that the header was truncated like "Supplier..."? @rgwood Do you have an opinion on these two options?
1. have the truncation `...` symbol on the headers
2. just the entire header, even though it's wider than the data

**Comment by zhiburt** [comment]
could you @fdncred check it now?

**Comment by fdncred** [comment]
@zhiburt it does the same thing. I get "Supplier N", "Supplier N", "Supplier A", "Supplier A", "Supplier T"

**Comment by zhiburt** [comment]
OK; seems like I got it.

cc: @fdncred 

image
image
image

**Comment by zhiburt** [comment]
ahhhhh not yet I've found some issues...

**Comment by zhiburt** [comment]
OK; seems OK;

cc: @fdncred 

image

**Comment by fdncred** [comment]
Looks good. Thanks for all your work!

**Pull request merged**
