### PR TITLE
Fix SIGTTIN handling

### PR DESCRIPTION
**Pull request by IanManske**
# Description
Due to a typo? in the [reference](https://www.gnu.org/software/libc/manual/html_node/Initializing-the-Shell.html) used to implement SIGTTIN handling, nushell will crash when being sent to the background from within another shell.

For example, currently in bash:
```bash
$ nu -n &
[1] 176058
$ ERROR: failed to SIGTTIN ourselves

[1]+  Exit 1                  nu -n
$
```

Now fixed:
```bash
$ nu -n &
[1] 178788
$ jobs
[1]+  Stopped                 nu -n
$
```

For further reference, this is how [fish](https://github.com/fish-shell/fish-shell/blob/493cbeb84c9146341790ef563434d47f3b4e0fa5/src/reader.cpp#L2571) does it.

# User-Facing Changes
Bug fix only -- users should now be able to send nushell to the background.

### CODE REVIEW

**Comment by WindSoilder** [comment]
Thanks!  I think it'd allow users to debug in vscode, I remember @fdncred faced the issue before, it's really annoying

**Comment by fdncred** [comment]
Ya, and @sholderbach too. He has an issue open on it somewhere I think. It would be nice if it fixed that problem too.

**Comment by jntrnr** [comment]
Thanks!

**Comment by sholderbach** [comment]
This somehow causes the test binaries to stop: Launching the latest `main` (`53ae03bd`) with `cargo test --workspace` from bash in WSL2/Ubuntu.

```
test tests::test_cell_path::record_with_nested_list_column_failure ... ok
test tests::test_cell_path::list_row_optional_access_succeeds ... ok
test tests::test_conditionals::if_cond ... ok
test tests::test_commandline::commandline_test_replace ... ok
test tests::test_converters::to_json_escaped ... ok
test tests::test_converters::from_json_2 ... ok
test tests::test_converters::to_json_raw_flag_2 ... ok
test tests::test_converters::to_json_raw_flag_3 ... ok
test tests::test_converters::to_json_raw_flag_1 ... ok
test tests::test_custom_commands::allow_missing_optional_params ... ok
test tests::test_custom_commands::custom_rest_var ... ok

[1]+  Stopped                 cargo test --workspace
```

And after reviving things with `fg` things seem to stall again.
```
test tests::test_stdlib::library_loaded ... ok

test result: ok. 503 passed; 0 failed; 4 ignored; 0 measured; 0 filtered out; finished in 245.55s

     Running tests/main.rs (target/debug/deps/main-a563851cb5fe7f80)

running 438 tests
test const_::const_list ... ok
test const_::const_in_scope ... ok
test const_::const_string ... ok
test const_::const_datetime ... ok
test const_::const_table ... ok
test const_::const_int ... ok
test const_::const_nothing ... ok
test eval::source_file_relative_to_file ... ok
test const_::const_record ... ok
test const_::const_binary ... ok

[1]+  Stopped                 cargo test --workspace
```

**Comment by IanManske** [comment]
Yep, sorry about that!
Looking over the reference linked above, I don't think we should even be running `take_control()` if `interactive` if false.
It seems like previously `killpg` either did nothing or was erroring, but since interactive was false, no errors were being thrown.

**Pull request merged**
