### PR TITLE
truly flexible csv/tsv parsing

### LINKED ISSUE #14398: Support setting column names in advance using flags for `from csv` / `from tsv`
### Related problem

The Nushell cookbook presents an external completer using the fish shell.

https://www.nushell.sh/cookbook/external_completers.html

```nushell
let fish_completer = {|spans|
    fish --command $'complete "--do-complete=($spans | str join " ")"'
    | $"value(char tab)description(char newline)" + $in
    | from tsv --flexible --no-infer
}
```

This part has always bugged me:

> `$"value(char tab)description(char newline)" + $in`

Not only it's inefficient since it'll be creating a whole new potentially large string via string concatenation just to give columns their names, but also I don't find it semantically clean.

One of the main appeals of Nushell is being able to avoid the awkward string operations that the traditional shells and tools have been doing and instead work with real, strongly typed data rather than formatted strings. In that sense, prepending the header row with string concatenation before parsing the tsv feels like a band-aid fix rather than a real solution.

### Describe the solution you'd like

I suggest a new flag `--columns {col1} {col2} ...` to name to columns in advance.
This flag will imply `--noheaders` and remove the need for prepending the header row.

```nushell
fish --command $'complete "--do-complete=($spans | str join " ")"'
| from tsv --flexible --no-infer --columns value description
```

### Describe alternatives you've considered

Currently, it is possible to parse the tsv headerless with `--noheaders` and later name them with `rename`.

```nushell
fish --command $'complete "--do-complete=($spans | str join " ")"'
| from tsv --flexible --no-infer --noheaders
| rename value description
```

But according to the cookbook, this method has an edge case it cannot cover.

> if the first line of the input doesn't have a second column the parser will skip that column for all the input

### Additional context and details

_No response_

### PR DESCRIPTION
**Pull request by Bahex**
- fixes #14398

I will properly fill out this PR and fix any tests that might break when I have the time, this was a quick fix.

# Description

This PR makes `from csv` and `from tsv`, with the `--flexible` flag, stop dropping extra/unexpected columns.

# User-Facing Changes

`$text`'s contents
```csv
value
1,aaa
2,bbb
3
4,ddd
5,eee,extra
```

Old behavior
```nushell
> $text | from csv --flexible --noheaders 
╭─#─┬─column0─╮
│ 0 │ value   │
│ 1 │       1 │
│ 2 │       2 │
│ 3 │       3 │
│ 4 │       4 │
│ 5 │       5 │
╰─#─┴─column0─╯
```

New behavior
```nushell
> $text | from csv --flexible --noheaders 
╭─#─┬─column0─┬─column1─┬─column2─╮
│ 0 │ value   │   ❎    │   ❎    │
│ 1 │       1 │ aaa     │   ❎    │
│ 2 │       2 │ bbb     │   ❎    │
│ 3 │       3 │   ❎    │   ❎    │
│ 4 │       4 │ ddd     │   ❎    │
│ 5 │       5 │ eee     │ extra   │
╰─#─┴─column0─┴─column1─┴─column2─╯
```

- The first line in a csv (or tsv) document no longer limits the number of columns
- Missing values in columns are longer automatically filled with `null` with this change, as a later row can introduce new columns. **BREAKING CHANGE**

  Because missing columns are different from empty columns, operations on possibly missing columns will have to use optional access syntax e.g. `get foo` => `get foo?`
  
# Tests + Formatting
Added examples that run as tests and adjusted existing tests to confirm the new behavior.

# After Submitting

Update the workaround with fish completer mentioned [here](https://www.nushell.sh/cookbook/external_completers.html#fish-completer)

### CODE REVIEW

**Comment by fdncred** [comment]
I've read the linked issue, but I'd also like to see an example and some tests that demonstrate how/why this is useful.

**Comment by WieeRd** [comment]
@fdncred You mean that the use case presented in #14398 is nearly enough to justify adding this feature, or just that this PR and the added contents (e.g. the --help output) needs more documentations?

**Comment by sholderbach** [comment]
For the examples we show in the release notes or the specific command documentation we prefer examples without additional needed context (e.g. the fish completions in #14398)

I have to admit that I can't gather quickly what changes here based on just the diff (or which part of the issue discussion manifested here). So a before and after behavior on a particular input or edge case can be helpful to see how this is a breaking change.

**Comment by Bahex** [comment]
I'll add examples and tests tomorrow, in the mean time this how the behavior changes:

`$text`'s contents
```csv
value
1,aaa
2,bbb
3
4,ddd
5,eee,extra
```

Old behavior
```nushell
> $text | from csv --flexible --noheaders 
╭─#─┬─column0─╮
│ 0 │ value   │
│ 1 │       1 │
│ 2 │       2 │
│ 3 │       3 │
│ 4 │       4 │
│ 5 │       5 │
╰─#─┴─column0─╯
```

New behavior
```nushell
> $text | from csv --flexible --noheaders 
╭─#─┬─column0─┬─column1─┬─column2─╮
│ 0 │ value   │   ❎    │   ❎    │
│ 1 │       1 │ aaa     │   ❎    │
│ 2 │       2 │ bbb     │   ❎    │
│ 3 │       3 │   ❎    │   ❎    │
│ 4 │       4 │ ddd     │   ❎    │
│ 5 │       5 │ eee     │ extra   │
╰─#─┴─column0─┴─column1─┴─column2─╯
```

- The first line in a csv(or tsv) document no longer limits the number of columns
- Missing values can no longer automatically filled with `null` with this change, as a later row can introduce new columns.

**Comment by fdncred** [comment]
That helps me understand much better @Bahex. Thanks! Looking forward to landing after you add tests/examples to ensure the behavior doesn't change by accident.

**Comment by fdncred** [comment]
Seems reasonable. Thanks.

**Comment by WieeRd** [comment]
Nicely done!

**Pull request merged**
