### PR TITLE
Implement passthrough for benchmark

### LINKED ISSUE #2577: Add passthrough mode to benchmark
**Is your feature request related to a problem? Please describe.**
Sometimes, I would like to benchmark a specific part of a pipeline.
The current `benchmark` command throws the original output of the block away.
I would like to add a mode `-p, --passthrough` that would print the benchmark results to stdout and pass the result structured data through:
`echo 1..5000 | benchmark -p { sleep 500ms } | math sum`

**Describe the solution you'd like**
A new argument for `benchmark` that causes it to print to stdout instead and pass through the block's structured data.

**Describe alternatives you've considered**
The benchmark could not support this functionality.

**Additional context**
The benchmark command in #2571 has a feature gate for advanced stats (user time, system time, idle time), the output would change slightly based on that feature flag (default on) if that PR is merged.

### PR DESCRIPTION
**Pull request by radekvit**
Closes #2577 if this feature is wanted.

Add a new option -p,--passthrough to benchmark.
With this option, the benchmark command prints its results to stdout and passes the block's output to the next command in the pipeline.

### CODE REVIEW

**Comment by jonathandturner** [comment]
I wonder - does it make sense to pass through the duration with the value instead of printing to stdout?

When we do `each --numbered` right now, we make a new output that has the number and the data as two parts. We could do something similar here where we output the duration and the data as two parts of a table.

**Comment by radekvit** [comment]
> I wonder - does it make sense to pass through the duration with the value instead of printing to stdout?
> 
> When we do `each --numbered` right now, we make a new output that has the number and the data as two parts. We could do something similar here where we output the duration and the data as two parts of a table.

@jonathandturner I think it would be clunky.

I imagine if I want to benchmark a part of a pipeline, with -p I want to work with the original output.
If we gave a table as an output, people would have to write `benchmark { something } | get output` every time.

I think that another switch could enable what you're suggesting, and it may be nice to have once `nu` has variables and/or scripting. I can't figure out what to name that switch, though.

**Comment by radekvit** [comment]
I added a block for --passthrough.

The benchmark data will be sent there instead of stdout.
Additionally, `-p {}` will automatically translate into `-p {autoview}` in `benchmark`.

**Comment by jonathandturner** [comment]
Look good

**Pull request merged**
