### PR TITLE
Add completion options for custom completions

### PR DESCRIPTION
**Pull request by wingertge**
# Description

This adds the ability for custom completions to return a record that modifies completion filtering and sorting. The old behaviour of returning a list still works and if any options are empty they default to the current behaviour (case-sensitive, positional and sorted). I tested all iterations of the new feature and all old code paths and everything works as intended or as before respectively.

# Example Usage

```
def my-completion [] {
    { completions: [a d c b], options: { sort: $false, case_sensitive: $true, positional: $true } }
}
```

# Tests

Make sure you've run and fixed any issues with these commands:

- [x] `cargo fmt --all -- --check` to check standard code formatting (`cargo fmt --all` applies these changes)
- [x] `cargo clippy --all --all-features -- -D warnings -D clippy::unwrap_used -A clippy::needless_collect` to check that you're using the standard code style
- [x] `cargo build; cargo test --all --all-features` to check that all the tests pass

### CODE REVIEW

**Comment by jntrnr** [comment]
Tagging @elferherrera to give a look - he's been working around completion logic for a while and might have some thoughts

**Comment by elferherrera** [comment]
I'm a bit lost, what else can we do with the record?

**Comment by wingertge** [comment]
Right now the record sets sorting, case sensitivity in filtering and whether to match only at the start or anywhere in the completion string. It could easily be expanded in the future though in case that's necessary. Now that I'm looking at it again I'd probably refactor it to put all settings in an `options` field for clarity. It works just like `$config`, any fields inside it will override the defaults if set.

**Comment by jntrnr** [comment]
Oh, that's a good point - I think the user might want to say "all completions should be fuzzy" or "all completions should be case-insensitive"

Are there completions that would want their own settings, or should we make everything come from `$config`?

**Comment by wingertge** [comment]
There is definitely a difference between completions. Maybe adding a config option to set the defaults would be nice too, but I don't want fuzzy matching in paths for example or in an "enum" (like scope in `winget`, it's either `machine` or `user`). The usecases for fuzzy search are more for when the completion options are complex names or something like that. `winget install` is a great example because the completions are based on `winget search` which does use fuzzy search if you use it directly. So this is definitely something that should be switched on a per completion basis I think.

**Comment by elferherrera** [comment]
How do you suggest we pass those parameters to the completer?

**Comment by wingertge** [comment]
I've already done the per completion options. The filtering and sorting was all done in `completion_helper` in `completions.rs`. The reedline completer doesn't do any of that so it doesn't need to know about it. As for how global configuration options are usually passed I haven't looked into it.

**Review by elferherrera — APPROVED** [review]

**Comment by wingertge** [comment]
Done

**Comment by fdncred** [comment]
+1 to landing this. i think we can continue tweaking it as we need to. i'm curious about global defaults but that shouldn't stop us from landing this, i don't think.

**Comment by jntrnr** [comment]
Sounds good. Thanks @wingertge !

**Pull request merged**
