### PR TITLE
Remove uses of nightly Rust, switch compiler to beta

### LINKED ISSUE #362: Target stable Rust
Right now nushell seems to require Rust nightly. But this hampers adoption, for example linux distros can't include it this way. It would be great if eventually, nushell would work on Rust stable.

futures-async-stream unrelated nightly features:

- [x] #367
- [x] type_name #371
- [x] option_flattening #468
- [x] try_trait #520
- [x] crate_visibility_modifier #526 , https://github.com/Hoverbear/getset/pull/28 , #561
- [x] bind_by_move_pattern_guards #521 
- [x] specialization #531, #569 , #579
- [x] in_band_lifetimes #527
- [x] https://github.com/wycats/language-reporting https://github.com/wycats/language-reporting/pull/7

futures-async-stream related nightly features:

- [ ] proc_macro_hygiene https://github.com/nushell/nushell/pull/724
- [ ] generators https://github.com/nushell/nushell/pull/724
- [ ] https://github.com/taiki-e/futures-async-stream https://github.com/nushell/nushell/pull/724

### PR DESCRIPTION
**Pull request by est31**
This removes the last remaining dependencies on nightly Rust and switches the pinned nightly to the beta toolchain. Once 1.39.0 is released, the pin can be removed.

Closes #362

### CODE REVIEW

**Comment by jonathandturner** [comment]
@est31 wow! That's awesome!

**Comment by est31** [comment]
Hmmm I just now discovered that language-reporting uses nightly Rust... will have to file a PR for language-reporting before this is ready for merging.

**Comment by jonathandturner** [comment]
cc @wycats about language-reporting using nightly

**Comment by est31** [comment]
The PR has been filed: https://github.com/wycats/language-reporting/pull/7

I have also updated this PR to use it.

**Comment by wycats** [comment]
I merged language-reporting

**Pull request merged**
