### PR TITLE
allow lists to have type annotations

### LINKED ISSUE #8109: `list` type annotations do not allow default values and specifying generic type
hello there :wave: :yum: 

### Describe the bug

Related to the second part of what i'm saying in #7699, the other first part is being addressed in #7699 :ok_hand:

i'm having trouble making the type annotations of compound types work as i expect
> **Note**
> here i take the example of `list`s, which is a simple compound type

i've got two main issues, as stated in the title of this issue :yum: 
- default `list` values do not allow a function definition to compile
- i can not give the generic type of `list<T>` to a signature

### 1. the original simple error with default values
define the following function
```bash
def foo [my_list: list = ["default value"]] {
  $my_list
}
```
and get the error
```bash
Error: nu::parser::assignment_mismatch (link)

  × Default value wrong type
   ╭─[entry #30:1:1]
 1 │ def foo [my_list: list = ["default value"]] {
   ·                          ────────┬────────
   ·                                  ╰── default value not list<any>
 2 │   $my_list
   ╰────
```

#### 2.1. no default value
```bash
def foo [my_list: list = []] {
  $my_list
}
```
and
```bash
> foo [1, 2, 3]
╭───┬───╮
│ 0 │ 1 │
│ 1 │ 2 │
│ 2 │ 3 │
╰───┴───╯
```

#### 2.2. complete the annotation
```bash
def foo [my_list: list<string> = ["a default string"]] {
  $my_list
}
```
gives
```
Error: nu::parser::unknown_type (link)

  × Unknown type.
   ╭─[entry #39:1:1]
 1 │ def foo [my_list: list<string> = ["a default string"]] {
   ·                   ──────┬─────
   ·                         ╰── unknown type
 2 │   $my_list
   ╰────
```

### 1. give default values
```bash
def foo [my_list: list = ["a default string"]] {
  $my_list
}
```
or even
```bash
def foo [my_list: list<any> = ["a default string"]] {
  $my_list
}
```
would give
```bash
> foo
╭───┬──────────────────╮
│ 0 │ a default string │
╰───┴──────────────────╯
> foo ["another string"]
╭───┬────────────────╮
│ 0 │ another string │
╰───┴────────────────╯
> foo [1234]
╭───┬──────╮
│ 0 │ 1234 │
╰───┴──────╯
```

### 2. generic type annotations
we could even restrict the type with `<T>`
```bash
def foo [my_list: list<string> = ["a default string"]] {
  $my_list
}
```
would result in
```bash
> foo
╭───┬──────────────────╮
│ 0 │ a default string │
╰───┴──────────────────╯
> foo ["another string"]
╭───┬────────────────╮
│ 0 │ another string │
╰───┴────────────────╯
```
but the following would give an error like
```bash
> foo [1234]
Error: nu::parser::type_mismatch (link)

  × Type mismatch.
   ╭─[entry #15:1:1]
 1 │ foo [1234]
   ·     ───┬──
   ·        ╰── expected List(String), found List(Int)
   ╰────
```

### Screenshots

_No response_

### Configuration

| key                | value                                    |
| ------------------ | ---------------------------------------- |
| version            | 0.75.1                                   |
| branch             |                                          |
| commit_hash        | 66398fbf77d03a6c7fd231da157f410d0446132e |
| build_os           | linux-x86_64                             |
| build_target       | x86_64-unknown-linux-gnu                 |
| rust_version       | rustc 1.66.1 (90743e729 2023-01-10)      |
| rust_channel       | 1.66.1-x86_64-unknown-linux-gnu          |
| cargo_version      | cargo 1.66.1 (ad779e08b 2023-01-10)      |
| pkg_version        | 0.75.1                                   |
| build_time         | 2023-02-18 11:04:21 +01:00               |
| build_rust_channel | release                                  |
| features           | database, default, trash, which, zip     |
| installed_plugins  | gstat                                    |

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by 1Kinoti**
this pr refines #8270 and closes #8109

# description
examples:

the original syntax is okay
```nu
def okay [nums: list] {}         # the type of list will be list<any>
```

empty annotations are allowed in any variation
the last two may be caught by a future formatter, 
but do not affect `nu` code currently
```nu
def okay [nums: list<>] {}       # okay

def okay [nums: list<     >] {}  # weird but also okay

def okay [nums: list<
>] {}                            # also weird but okay
```

types are allowed (See [notes](#notes) below)
```nu
def okay [nums: list<int>] {}    # `test [a b c]` will throw an error 

def okay [nums: list< int > {}   # any amount of space within the angle brackets is okay

def err [nums: list <int>] {}    # this is not okay, `nums` and `<int>` will be parsed as
                                 # two separate params, 
```

nested annotations are allowed in many variations
```nu
def okay [items: list<list<int>>] {}

def okay [items: list<list>] {}
```

any unterminated annotation is caught
```nu
Error: nu::parser::unexpected_eof

  × Unexpected end of code.
   ╭─[source:1:1]
 1 │ def err [nums: list<int] {}
   ·                       ▲
   ·                       ╰── expected closing >
   ╰────
```

unknown types are flagged
```nu
Error: nu::parser::unknown_type

  × Unknown type.
   ╭─[source:1:1]
 1 │ def err [nums: list<str>] {}
   ·                     ─┬─
   ·                      ╰── unknown type
   ╰────

Error: nu::parser::unknown_type

  × Unknown type.
   ╭─[source:1:1]
 1 │ def err [nums: list<int, string>] {}
   ·                    ─────┬─────
   ·                          ╰── unknown type
   ╰────
```

# notes
the error message for mismatched types in not as intuitive
```nu
Error: nu::parser::parse_mismatch

  × Parse mismatch during operation.
   ╭─[source:1:1]
 1 │ def err [nums: list<int>] {}; err [a b c]
   ·                                    ┬
   ·                                    ╰── expected int
   ╰────
```
it should be something like this
```nu
Error: nu::parser::parse_mismatch

  × Parse mismatch during operation.
   ╭─[source:1:1]
 1 │ def err [nums: list<int>] {}; err [a b c]
   ·                                    ──┬──
   ·                                      ╰── expected list<int>
   ╰────
```
this is currently not implemented

### CODE REVIEW

**Review by sholderbach — COMMENTED** [review]
Nice! Looks like you figured a relatively straightforward patch. And great to see all the tests!

**Comment by amtoine** [comment]
very nice :ok_hand

**Comment by Sygmei** [comment]
Will this feature be ported to `record` type as well ?

**Review by sholderbach — APPROVED** [review]
I checked that the lexing changes don't conflict with the new match syntax. So let's merge this as the changes look good and well covered.
Thanks for tackling that @1Kinoti

**Comment by fdncred** [comment]
> thanks! is it okay if i now tackle records and tables?

I'm anxious to see what that looks like and I'm excited to try this out more. Good work @1Kinoti!

**Comment by fdncred** [comment]
@1Kinoti Here's something I stumbled upon while testing this.

Given this custom command:
```
> def foo [my_list: list<string> = ['val1' 'val2']] {
  $my_list
}
> foo
╭───┬──────╮
│ 0 │ val1 │
│ 1 │ val2 │
╰───┴──────╯
> foo [1 2 3]
╭───┬───╮
│ 0 │ 1 │
│ 1 │ 2 │
│ 2 │ 3 │
╰───┴───╯
```
I expected the last example to produce and error because I defined `$my_list` as a `list<string>`. Any ideas?

**Comment by amtoine** [comment]
@fdncred 
agree :+1: 

especially since
```bash
def foo [x: list<int> = [1 2 3]] { print $x }
```
works as expected.

**Pull request merged**
