### PR TITLE
Fix build warnings & add CI

### PR DESCRIPTION
**Pull request by max-sixty**
I don't know the practices in this project so please lmk if this is reasonable

### CODE REVIEW

**Comment by jonathandturner** [comment]
@max-sixty - thanks for the PR! It will be good to fix these warnings.

For now, on Azure Pipelines we're experimenting with only building the default build to help with build times.  We have another build which is run nightly (on Circle CI I believe?) that just got turned on that will test all the features.

A couple options:

We could turn the error-on-warning flag for one of the platforms (maybe the fastest one, which I think is macOS). Or, we could see if we could add it to the nightly build.

**Comment by max-sixty** [comment]
Great—as you wish re the options. 

Out of interest, do you have tests that only run on `--all-features`? Do you ever merge code that fails those? (possible I'm misunderstanding something basic about how that works...)

**Comment by jonathandturner** [comment]
@max-sixty we currently don't have tests for the optional features but it's definitely something we should add

**Comment by max-sixty** [comment]
> @max-sixty we currently don't have tests for the optional features but it's definitely something we should add

Once they're added, will you need `--all-features` anyway?

**Comment by wycats** [comment]
@jonathandturner Could we parallelize the tests by feature? I don't like the idea of merging code to master that doesn't work, only to find it out the next day and having to do a revert or hotfix.

**Comment by jonathandturner** [comment]
@wycats could you say more? Tests are run in parallel by default in Rust, though I'm not sure what you mean by "by feature".

**Comment by jonathandturner** [comment]
@wycats one idea would be to do an all-features test run on one of the platforms (like macOS, since it's fastest) rather than doing it on all 3. The build will take the same amount of time, but we'll have some coverage for the optional features.

**Comment by jonathandturner** [comment]
Since we're seeing breakage from not testing all features, the approach in this PR is seeming like the important part.

We can work on build times, but correctness is the more important foundation to start from.

**Pull request merged**
