### PR TITLE
rename the types with spaces in them to use `-`

### PR DESCRIPTION
**Pull request by amtoine**
# Description
before this PR,
```nushell
> $.a.b | describe
cell path
```
which feels inconsistent with the `cell-path` type annotation, like in
```nushell
> def foo [x: cell-path] { $x | describe }; foo $.a.b
cell path
```

this PR changes the name of the "cell path" type from `cell path` to `cell-path`

# User-Facing Changes
`cell path` is now `cell-path` in the output of `describe`.
this might be a breaking change in some scripts.

same goes with
- `list stream` -> `list-stream`
- `match pattern` -> `match-pattern`

# Tests + Formatting
- :green_circle: `toolkit fmt`
- :green_circle: `toolkit clippy`
- :black_circle: `toolkit test`
- :black_circle: `toolkit test stdlib`

this PR adds a new `cell_path_type` test to make sure it stays equal to `cell-path` in the future.

# After Submitting

### CODE REVIEW

**Comment by fdncred** [comment]
If we're going to rename `cell path`, maybe we should make all two-word types hyphenated?

**Comment by amtoine** [comment]
> If we're going to rename `cell path`, maybe we should make all two-word types hyphenated?
>
yeah this would make sense :+1: 

i see `match pattern` and `list stream` in `ty.rs`, but i'm not sure if it's possible to encounter them, is it? :open_mouth:

**Comment by fdncred** [comment]
> i'm not sure if it's possible to encounter them, is it?

I don't know but that's not an excuse to not be consistent with our naming, imo.

**Comment by amtoine** [comment]
> I don't know but that's not an excuse to not be consistent with our naming, imo.
>
done in e1e0e333e :+1:

**Review by sholderbach — APPROVED** [review]
Sounds good to me. Not sure if we ever encounter `list-stream` in the wild as `describe seems to map that differently if I recall.

**Comment by fdncred** [comment]
I just noticed this. While we're in here changing cell-path, there are a few other places that have `cellpath`. So, can we just fix those too? If you search for "cellpath" you'll see what I'm talking about. Maybe all these should be `cell-path` too?

**Comment by jntrnr** [comment]
will they be matching what the parser uses for the shape/type names?

**Comment by fdncred** [comment]
@jntrnr `parse_shape_name()` uses `cell-path` right now and yet in `impl Display for SyntaxShape` we return `cellpath`. It's also called `cellpath` in the config settings.

Something good to do is to search for `cellpath`, `cell path`, and `cell-path` (and the other ones that are changed here) and see where we're using these. We should try and be consistent as much as possible.

**Comment by amtoine** [comment]
oh wow @fdncred, thanks for the very good catches :clap: :clap: 

do you feel this is ready now? :blush:

**Comment by fdncred** [comment]
close enough i think

**Pull request merged**
