### PR TITLE
Add commit hash to version command

### PR DESCRIPTION
**Pull request by coolshaurya**

### CODE REVIEW

**Comment by coolshaurya** [comment]
This is failing due to an unwrap 
image

The unwrap is okay here because the `OUT_DIR` is guaranteed to exist by cargo - https://doc.rust-lang.org/cargo/reference/environment-variables.html#environment-variables-cargo-sets-for-build-scripts

A possible workaround to this is to use `.unwrap_or_else(|| unreachable!())`

**Comment by jonathandturner** [comment]
@coolshaurya instead of `.unwrap` use `.expect` and pass in a message about why this should never fail.

**Comment by jonathandturner** [comment]
Looks good - thanks!

**Comment by jonathandturner** [comment]
We might need to implement this one differently. Just tried to release nu-plugin-textview, which depends on nu-cli. nu-cli published okay, but I got this error with publishing nu-plugin-textview:

```
error: failed to run custom build command for `nu-cli v0.18.0`

Caused by:
  process didn't exit successfully: `/home/jonathan/Source/nushell/target/package/nu_plugin_textview-0.18.0/target/debug/build/nu-cli-29c1b26389b2852e/build-script-build` (exit code: 1)
--- stderr
Error: GitError(Error { code: -3, klass: 6, message: "could not find repository from \'/home/jonathan/.cargo/registry/src/github.com-1ecc6299db9ec823/nu-cli-0.18.0\'" })

warning: build failed, waiting for other jobs to finish...
error: failed to verify package tarball
```

I'll revert this PR to see if that fixes the issue. If so, we can re-implement this differently. Would still like to have this feature.

**Pull request merged**
