### PR TITLE
Rename `random decimal` to `random float`

### PR DESCRIPTION
**Pull request by sholderbach**
# Description
Similar to #9979

# User-Facing Changes
`random decimal` will now raise a warning and can be removed in an
upcoming release.

New command is named `random float`

# Tests + Formatting
Tests updated and improved.

### CODE REVIEW

**Review by fdncred — APPROVED** [review]
Thanks!

**Comment by jntrnr** [comment]
We'll also need to update `describe` I think? I was poking around and there are still a few places in the code we call things "decimal" instead of "float"

**Comment by amtoine** [comment]
good job with the deprecation message :ok_hand:

**Comment by sholderbach** [comment]
> We'll also need to update `describe` I think? I was poking around and there are still a few places in the code we call things "decimal" instead of "float"

- [x] `describe`/`Type::to_string()` is fine
- [ ] Parser accepts both `decimal` and `float`...
- [ ] to define `SyntaxShape::Decimal`
- [x] `StyleComputer` to map in the config uses the type name so `float`

**Pull request merged**
