### PR TITLE
allow complex types in return types

### PR DESCRIPTION
**Pull request by 1Kinoti**
# description

this pr fixes #9702 

- [x] syntax
- [ ] type checking

### CODE REVIEW

**Comment by sholderbach** [comment]
What are the missing parts here?

We should make sure the already landed type-checking improvements don't limit us for the release on Tuesday, but my basic reading of #9702 was that this is not yet critical as it only affects potential added stringency for custom commands?

**Comment by 1Kinoti** [comment]
i have fixed the syntax issue in the first commit, however, #9702 [isn't](https://github.com/nushell/nushell/issues/9702#issuecomment-1637021314) completely fixed.

**Comment by amtoine** [comment]
i tried the following on this branch
```nushell
def foo []: nothing -> record<foo: string> {
    {foo: "bar"}
}
let res: table<foo: string> = foo
```

## before
```nushell
Error: nu::parser::unclosed_delimiter

  × Unclosed delimiter.
   ╭─[entry #15:1:1]
 1 │ def foo []: nothing -> record<foo: string> {
   ·                        ─────┬─────
   ·                             ╰── unclosed >
 2 │     {foo: "bar"}
   ╰────
```

## after
```nushell
Error: nu::parser::unclosed_delimiter

  × Unclosed delimiter.
   ╭─[entry #2:3:1]
 3 │ }
 4 │ let res: table<foo: string> = foo
   ·          ─────┬────
   ·               ╰── unclosed >
   ╰────
```

so the command parses now :partying_face:


can't wait to see the rest :star_struck:

**Comment by fdncred** [comment]
@1Kinoti Are you able to finish this up or are you still having a hard time finding the time?

**Pull request closed without merging**
