### PR TITLE
First pass at updating all documentation formatting and cleaning up output of examples

### PR DESCRIPTION
**Pull request by JosephTLyons**
Let me start off by saying that there are a lot of changes here.  I passed over all the documentation (every `.md` file) 3 separate times (although there is so much to go over that I wouldn't doubt I still somehow missed stuff).  Here is a list of what all I did and what I might've skipped:

- I used [markdownlint](https://marketplace.visualstudio.com/items?itemName=DavidAnson.vscode-markdownlint) as my main tool to format all of the markdown files.  I would say that I corrected 95 percent or more of the lint warnings emitted from this package, however, there were a few files that had cases where I didn't know of a good way to resolve the issue, and let it slide (I’ll probably correct these in future PRs).  Mostly what I corrected was:
    - spacing between headers
    - spacing between blocks of code
    - marking blocks of code with whatever tag needed to allow them to be syntax highlighted, splitting up multiple examples into separate code blocks
    - fixing headers that jumped from `#` to `###` randomly, 
    - and other small things.

- If I saw that there were examples that had output that came from evidently older versions of nushell, I reran them and updated the output.  I wasn't able to rerun all of the examples, as a good chunk of the commands load data into the table from data files that I do not own or possess, so I skipped those (sort of stinks because I would've loved to update all to get the same output across all documentation).

- Some older documentation had examples that showed the full path of where the command was ran, including the user’s name, where newer commands seem to just show `>` and omit anything before it.  I went ahead and followed the second form and took out the user-specific paths of where commands were ran, except in the cases where the path was relevant to the command.

- I corrected a few typos here and there, fixed places where example commands we're entirely omitted.

### CODE REVIEW

**Comment by fdncred** [comment]
Love the attention to detail. This makes my OCD very calm. :) Thanks!

**Comment by JosephTLyons** [comment]
Thanks @fdncred, I'm actually plagued by OCD and the fact I wasn't able to update everything bothers me (lol).  I'm thinking about suggesting that all example files used in examples be placed in a folder in the repo so that documentation can be updated easier for commands that use files.

**Comment by fdncred** [comment]
There is definitely some re-organization that could help. A `samples` folder would be great IMHO. I'd also love for the code to be restructured so that compiling is faster and there aren't any extra binaries being generated, but that's over my pay grade. :)

**Comment by JosephTLyons** [comment]
> There is definitely some re-organization that could help. A `samples` folder would be great IMHO. I'd also love for the code to be restructured so that compiling is faster and there aren't any extra binaries being generated, but that's over my pay grade. :)

Another absolutely crazy wish of mine would be that somehow the documentation examples could be created dynamically, like some sort of thing running nu and capturing its output and putting it in the code blocks in the md file.  Examples would always be up to date and it would be more obvious if something was broken in the examples.

**Comment by jonathandturner** [comment]
Looks great! Thanks for putting this together

**Pull request merged**
