### PR TITLE
fix: preserve path when completing intermediate directory

### LINKED ISSUE #10766: Directory completion doesn't work when triggering inside a command
### Describe the bug

Dir completion overrides the command contents after the cursor.

### How to reproduce

1. type a command with file path
2. try to change the prefix of the path with directory completion

### Expected behavior

nu's directory completion should behave as bash, preserve `src/lib.rs`

### Screenshots

https://github.com/nushell/nushell/assets/35686186/323824e0-26a3-4f83-b889-bf5afdc75497

https://github.com/nushell/nushell/assets/35686186/e0be818f-eda2-4ead-9baa-770c90979d57

### Configuration

| key                | value                                       |
| ------------------ | ------------------------------------------- |
| version            | 0.84.0                                      |
| branch             |                                             |
| commit_hash        |                                             |
| build_os           | linux-x86_64                                |
| build_target       | x86_64-unknown-linux-gnu                    |
| rust_version       | rustc 1.74.0-nightly (8142a319e 2023-09-13) |
| rust_channel       | nightly-x86_64-unknown-linux-gnu            |
| cargo_version      | cargo 1.74.0-nightly (2fc85d15a 2023-09-09) |
| build_time         | 2023-09-19 11:35:09 +08:00                  |
| build_rust_channel | release                                     |
| allocator          | standard                                    |
| features           | default, sqlite, trash, which, zip          |
| installed_plugins  |                                             |

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by lavafroth**
- fixes #10766

# Description

If the partial supplied to the completion function is shorter than the span, the cursor is in between the path, we are trying to complete an intermediate directory. In such a case we:
- only suggest directory names
- don't append the slash since it is already present
- only complete the path till the component the cursor is on

# User-Facing Changes

Intermediate directories can be completed without erasing the rest of the path.

# Tests + Formatting

# After Submitting

### CODE REVIEW

**Comment by fdncred** [comment]
nice work! 
you probably had no idea what you were getting into when you filed your first PR to help with completions. LOL. I hope you don't mind too much working on this stuff with us.

**Comment by lavafroth** [comment]
Always here to help! 😄

**Comment by lavafroth** [comment]
I tried the same command and at the same location, works fine for me. I'm wondering if it's because of the cursor.

**Comment by lavafroth** [comment]
Update: I tried your cursor shape. I'm unable to reproduce your error. This might still have something to do with the cursor. Whenever I get the span value from the working set, it includes the cursor character. So when I convert the span value to a lossy string, it inserts an 'a' at the cursor's position that I have to skip over manually. Is there a way to get the span value without including the cursor's unicode character?

**Comment by fdncred** [comment]
I just tried with the standard "marker", which is `marker: "| "` and it didn't make any difference.

**Comment by fdncred** [comment]
This PR works on WSL/Ubuntu though. So, it's definitely a windows thing as far as I can tell.

**Comment by fdncred** [comment]
With the latest push, in Windows, I can now complete with `rg test crates/nu-command/src/b<tab>` but not `rg test .\crates\nu-command\src\b<tab>` and neither will complete with other parameters at the end then moving the cursor to src/_ and hitting tab.

**Comment by lavafroth** [comment]
I updated the code to not use range indices for strings and instead use the chars method for each rune. I figured, using ranges might not have removed the cursor's unicode code point completely. Unfortunately, I can't test this on Windows since I'm not home.

**Comment by fdncred** [comment]
same with the latest commit

**Comment by lavafroth** [comment]
I accidentally set the criteria for completing intermediate directories to only when there was something between the cursor and the end of the current path component, which resulted in the completions failing on linux too. This should hopefully fix that and the unicode problem.

**Comment by fdncred** [comment]
Still not working on Windows. `rg test .\crates\nu-com<tab>` doesn't even work but `rg test ./crates/nu-com<tab>` works in Windows. Neither work with `-F --no-ignore` at the end.

**Comment by lavafroth** [comment]
Do the trailing flags get wiped on Windows?

**Comment by fdncred** [comment]
> Do the trailing flags get wiped on Windows?

I just get NO RECORDS FOUND, like on the screenshot above.

**Comment by lavafroth** [comment]
Guess this has to wait while I get hands on a Windows box, sorry.

**Comment by amtoine** [comment]
pinging you @fdncred as maybe the last commit will fix this on Windows :crossed_fingers: 

do we have a way to add a test for this behaviour on Windows? :innocent:

**Comment by fdncred** [comment]
@amtoine I tested it when the commit was added. It still doesn't work.

**Comment by amtoine** [comment]
@lavafroth
i'll mark this PR as DRAFT until we have a fix for Windows :relieved: 

feel free to mark back as ready when you get confirmation it works on Windows :wink:

**Comment by lavafroth** [comment]
Sure thing.

**Comment by lavafroth** [comment]
Okay, it appears that the bug only occurs in Windows Terminal. If we use something like conhost or Fluent terminal, the completions work as intended. It'd be great if someone else could verify this.

**Comment by fdncred** [comment]
Tested in:

### Windows Terminal
rg test ./crates/nu-command/src/b<tab> -F --no-ignore => Fails to complete
rg test .\crates\nu-command\src\b<tab>                => Fails to complete
rg test ./crates/nu-command/src/b<tab>                => Completes

### Rio
rg test ./crates/nu-command/src/b<tab> -F --no-ignore => Fails to complete
rg test .\crates\nu-command\src\b<tab>                => Fails to complete
rg test ./crates/nu-command/src/b<tab>                => Completes

### WezTerm
rg test ./crates/nu-command/src/b<tab> -F --no-ignore => Fails to complete
rg test .\crates\nu-command\src\b<tab>                => Fails to complete
rg test ./crates/nu-command/src/b<tab>                => Completes

### Alacritty
rg test ./crates/nu-command/src/b<tab> -F --no-ignore => Fails to complete
rg test .\crates\nu-command\src\b<tab>                => Fails to complete
rg test ./crates/nu-command/src/b<tab>                => Completes

### Tabby
rg test ./crates/nu-command/src/b<tab> -F --no-ignore => Fails to complete
rg test .\crates\nu-command\src\b<tab>                => Fails to complete
rg test ./crates/nu-command/src/b<tab>                => Completes

### Contour
rg test ./crates/nu-command/src/b<tab> -F --no-ignore => Fails to complete
rg test .\crates\nu-command\src\b<tab>                => Fails to complete
rg test ./crates/nu-command/src/b<tab>                => Completes


I'm running out of Windows terminals to test. Seems like they all work the same.

**Comment by lavafroth** [comment]
I tested this in Windows Terminal today and it works with the default config. Maybe the problem only gets triggered by your config?

**Comment by fdncred** [comment]
Indeed, it could be my config. Lemme see.

**Comment by fdncred** [comment]
hmmm, this is with default config. Seems a little fickle. This doesn't work.
image

```
rg test crates/nu-commands/src/b<tab> -F --Ignore
```
This works
```
rg test crates\nu-command\src\b<tab> -F --Ignore
```
So, maybe the forward slash is breaking it?

**Comment by fdncred** [comment]
But with my config `rg test .\cra<tab>` doesn't work. I'm so confused.

**Comment by fdncred** [comment]
Ugh, I figured it out. Even though I had my `$env.config.completions.external.completer` set to `null` I was sourcing another file that re-enabled it. This would've been easy to check on day 1 like this.
```
❯ $env.config.completions | table -e
╭──────────────┬────────────────────────────╮
│case_sensitive│false                       │
│quick         │true                        │
│partial       │true                        │
│algorithm     │prefix                      │
│              │╭───────────┬──────────────╮│
│external      ││enable     │true          ││
│              ││max_results│10            ││
│              ││completer  │<Closure 2447>││
│              │╰───────────┴──────────────╯│
╰──────────────┴────────────────────────────╯
```
My sincerest apologies @lavafroth ❤️ 

This PR seems to work as expected now, no thanks to me! 😭

**Review by fdncred — APPROVED** [review]
I'm an idiot sometimes. Enough said.

Note to self, when testing PRs, it's always good to make sure your personal configuration isn't influencing the change. Sometimes it's hard to see like this one since I had a setting disabled to test this PR but another file I was sourcing re-enabled it. Ugh!

**Comment by fdncred** [comment]
@lavafroth Is there anything you want to un-re-change since I was providing false information during testing? Or are you good to go with this PR the way it is?

**Comment by lavafroth** [comment]
Since the logic is the same for both the file and the directory completions, I'll extract the code into its own function. Also, it is probably safer to count the runes when parsing the path as UTF-8, so I'll keep that.

**Comment by fdncred** [comment]
ok, ping me here when you're ready again. I'll do a quick test and hopefully land it.

**Comment by lavafroth** [comment]
Alright, should be all good now.

**Comment by fdncred** [comment]
This is working great! I can't break it. Thanks for sticking with us. We appreciate your help!

Let's go!

**Comment by lavafroth** [comment]
Correct me if I'm wrong but if I couple the current iteration of nu with `carapace`, the completions return `NO RECORDS FOUND` like you mentioned. However, I think I have figured out a way to have consistent completions with an external completer. Should I open another PR?

**Comment by fdncred** [comment]
I think that would be helpful. I know some people use carapace and that's where I was getting all the issues. People definitely use external completers. I see the fish completer used quite a bit.

**Pull request merged**
