### PR TITLE
Replace git current_branch to shadow-rs branch

### PR DESCRIPTION
**Pull request by baoyachi**
## update
* `branch()` method built in **shadow-rs**,it can get current branch variable. So not need rewrite again with this function.
* So,it's not use `git2` crates, could remove `git2` dependencies

### CODE REVIEW

**Comment by baoyachi** [comment]
It's seems to shoule add `feature` with shadow-rs,that  can fixed in wasm.

**Comment by fdncred** [comment]
Cool, less dependencies! :) I think it would be nice to have `is_debug` and `tag` in there too eventually. I'll have to look at adding them. You've been adding some nice features to `shadow-rs`!

**Comment by baoyachi** [comment]
@fdncred I just add feature with shadow-rs `git2` features option:[https://github.com/baoyachi/shadow-rs/blob/master/Cargo.toml](https://github.com/baoyachi/shadow-rs/blob/master/Cargo.toml).

And then config in `nu-cli`,`nu-command`. But when i run `./sample/wasm`,but build error. It's seem's `shadow-rs` `default-features = false` not work?, 
Could your help me see this problem.

**Comment by baoyachi** [comment]
It' seem everything Ok. 🦀

**Comment by jonathandturner** [comment]
Looks good!

**Pull request merged**
