### PR TITLE
Dependency: use tracing and tracing subscriber instead of simplelog and log

### PR DESCRIPTION
**Pull request by WindSoilder**
# Description

# User-Facing Changes

There are two different things:
1. `--log-level mixed` is no longer supported, because `tracing_subscriber` doesn't support it.
2. the log format is a little bit different:
* **Prev**: ﻿2023-06-25 08:26:56.411 AM [INFO ] nu_utils::utils: perf: crates/nu-cli/src/repl.rs:445:13 update_prompt took 162.725128ms
* **After**: ﻿2023-06-25T08:27:25.780427Z  INFO nu_utils::utils: crates/nu-utils/src/utils.rs:76: perf: crates/nu-cli/src/repl.rs:445:13 update_prompt took 144.284107ms

But yeah, I think it's fine for me.

**Edit**: new version, don't show line number and file name in subscriber.
图片

The core logic lays in `setup_logger` in `src/logger.rs`
# Tests + Formatting

# After Submitting

### CODE REVIEW

**Comment by jntrnr** [comment]
can you say more about the advantages of the new system?

**Comment by WindSoilder** [comment]
Yeah, I'll from @kubouch 's message in discord directly

> One thing we could do is move from the log crate to tracing which would give us the option to use the excellent https://github.com/wolfpld/tracy profiler thanks to https://github.com/nagisa/rust_tracy_client . The instrumenting profiler gives you more fine-grained resolution than sampling profiler and also manual tracing can have less noise information as you can choose to drill only into one area that interests you.

Actually I haven't play with tracy yet, but migrating to tracing is the first step.

**Comment by fdncred** [comment]
That's pretty verbose for the info log. I'm wondering if we should tweak the format a bit. I found this [crate](https://github.com/isgasho/pretty_tracing_subscriber/blob/master/src/lib.rs#L82) that shows how to have a custom format.

Also, I'm wondering if this tracing will work with superluminal profiling?

**Comment by WindSoilder** [comment]
> That's pretty verbose for the info log.
Thanks, that's a good catch!  
图片
I've updated relative code to disable file and line number in subscriber

**Comment by kubouch** [comment]
@fdncred This crate supports superluminal profiling https://github.com/aclysma/profiling . It seems to wrap the tracing crate.

**Comment by fdncred** [comment]
since we haven't been able to produce any tracing examples/demos, i'm thinking we should think about closing this. i'm not sure it's worth it at this point.

**Comment by kubouch** [comment]
I used this PR to produce Tracy traces. Instead of `trace!` macros we'd need to use `trace_span!` and distribute them better to provide more useful information. I currently don't have the bandwidth to finish this, though.

**Comment by WindSoilder** [comment]
Closing this for now because it's not our target torward 1.0

**Comment by fdncred** [comment]
Let's not forget this because I still believe tracing like this can be helpful when using superluminal, Tracy, or other gui programs that show tracing events. I don't think the normal logging crate helps in the same way.

**Pull request closed without merging**
