### PR TITLE
Dependency update: update notify version to v5

### PR DESCRIPTION
**Pull request by WindSoilder**
# Description

Relative: #8060

While investigating, I found we need to update notify, which is a good step to remove some duplicate dependencies.

As title, here are some goods and bads after updating:

## Good
keep dependency up to date, and remove duplidate dependency(cfg-if, winapi) in Cargo.lock.

## Bad
Introduce some breaking changes:
After updating to notify v5, I found that we have to remove `Rename` events.  

But I've testing under notify v4, and it doesn't work good if we running the following command on MacOS:
```
touch a
mv a b
```
It fires file create event, but no file rename event.  So `rename` event is not really reliable, so I think it's ok for us to remove `Rename` events.

The reason to remove `--debounce-ms` flag:
It's not provided by defualt file watcher, we can use [PollWatcher](https://docs.rs/notify/latest/notify/poll/struct.PollWatcher.html), but it scans filesystem, which is really expensive.  So I just remove the flag.

# User-Facing Changes

1. `--debounce-ms` flag is removed
2. no longer watch `Rename` event.

# Tests + Formatting

Don't forget to add tests that cover your changes.

Make sure you've run and fixed any issues with these commands:

- `cargo fmt --all -- --check` to check standard code formatting (`cargo fmt --all` applies these changes)
- `cargo clippy --workspace -- -D warnings -D clippy::unwrap_used -A clippy::needless_collect` to check that you're using the standard code style
- `cargo test --workspace` to check that all tests pass

# After Submitting

If your PR had any user-facing changes, update [the documentation](https://github.com/nushell/nushell.github.io) after the PR is merged, if necessary. This will help us keep the docs up to date.

### CODE REVIEW

**Comment by sholderbach** [comment]
Thanks for giving this one a go.

@rgwood noticed some of the problems with the changed functionality of `notify` a while back.

(also his comment recently https://github.com/nushell/nushell/pull/7977#issuecomment-1427238762)

The upgrade docs refer to an additional crate to do debouncing but not sure if this fully captures the edge cases we need to handle
https://github.com/notify-rs/notify/blob/main/UPGRADING_V4_TO_V5.md

**Comment by WindSoilder** [comment]
It's a pity that current debouncing only returns Any and AnyContinuous event: https://docs.rs/notify-debouncer-mini/0.2.1/notify_debouncer_mini/enum.DebouncedEventKind.html

And I don't think it'll be changed in the forseen future :-(

**Comment by rgwood** [comment]
I guess we could write our own debouncer if needed. Doesn't need to be fancy, could be something like:

1. Incoming events get put in a queue.
2. Every X milliseconds, we read the whole queue and deduplicate events before processing them

I'm OK merging this PR and doing the debouncer work separately. Might be best to wait until after the release though.

**Comment by sholderbach** [comment]
Should we land this with this release or hold off?

**Comment by WindSoilder** [comment]
I think we can merging with release and see how it works

**Comment by rgwood** [comment]
I think we should wait until after the release to merge this.

**Comment by rgwood** [comment]
Let's merge this once the conflict is resolved.

**Comment by rgwood** [comment]
I'm having trouble with `watch` on Windows after this. For some reason it won't pick up changes to `.rs` files.

If I run `watch . { |a, f| print $f }` in a Rust project folder, then change `src\main.rs` and save the file, it gives me events for lots of files but *not* `main.rs`. Weird.

```
C:\Users\reill\source\bitline〉watch . { |a, f| print $f }                                                                                                                                                                                                                  02/28/2023 11:07:23 AMNow watching files at "C:\\Users\\reill\\source\\bitline". Press ctrl+c to abort.
C:\Users\reill\source\bitline\target\debug\.fingerprint\bitline-961c4e97b4d28930\output-bin-bitline
C:\Users\reill\source\bitline\target\debug\.fingerprint\bitline-3416813bbb94a996\output-test-bin-bitline
C:\Users\reill\source\bitline\target\debug\incremental\bitline-3jcl4qz7lpem2\s-ginvyutv8y-tis3pa.lock
C:\Users\reill\source\bitline\target\debug\incremental\bitline-3jcl4qz7lpem2\s-ginvyutv8y-tis3pa-working
C:\Users\reill\source\bitline\target\debug\incremental\bitline-38jupfy1kjztq\s-ginvyutvkc-1p7k82u.lock
C:\Users\reill\source\bitline\target\debug\incremental\bitline-38jupfy1kjztq\s-ginvyutvkc-1p7k82u-working
C:\Users\reill\source\bitline\target\debug\incremental\bitline-3jcl4qz7lpem2\s-ginvyutv8y-tis3pa-working\dep-graph.bin
C:\Users\reill\source\bitline\target\debug\incremental\bitline-38jupfy1kjztq\s-ginvyutvkc-1p7k82u-working\dep-graph.bin
C:\Users\reill\source\bitline\target\debug\incremental\bitline-3jcl4qz7lpem2\s-ginvyutv8y-tis3pa-working\query-cache.bin
C:\Users\reill\source\bitline\target\debug\incremental\bitline-38jupfy1kjztq\s-ginvyutvkc-1p7k82u-working\query-cache.bin
C:\Users\reill\source\bitline\target\debug\incremental\bitline-3jcl4qz7lpem2\s-ginvyutv8y-tis3pa-working\work-products.bin
C:\Users\reill\source\bitline\target\debug\incremental\bitline-38jupfy1kjztq\s-ginvyutvkc-1p7k82u-working\work-products.bin
C:\Users\reill\source\bitline\target\debug\.fingerprint\bitline-961c4e97b4d28930\output-bin-bitline
C:\Users\reill\source\bitline\target\debug\.fingerprint\bitline-3416813bbb94a996\output-test-bin-bitline
C:\Users\reill\source\bitline\target\debug\incremental\bitline-38jupfy1kjztq\s-ginvyutvkc-1p7k82u-working\dep-graph.part.bin
C:\Users\reill\source\bitline\target\debug\incremental\bitline-3jcl4qz7lpem2\s-ginvyutv8y-tis3pa-working\dep-graph.part.bin
C:\Users\reill\source\bitline\target\debug\deps\rmetabkSlw1
C:\Users\reill\source\bitline\target\debug\deps\rmetabkSlw1\lib.rmeta
C:\Users\reill\source\bitline\target\debug\deps\libbitline-3416813bbb94a996.rmeta
C:\Users\reill\source\bitline\target\debug\deps\rmetabkSlw1\lib.rmeta
C:\Users\reill\source\bitline\target\debug\deps\libbitline-3416813bbb94a996.rmeta
C:\Users\reill\source\bitline\target\debug\deps\rm-0
C:\Users\reill\source\bitline\target\debug\deps\rmeta37H6Up
C:\Users\reill\source\bitline\target\debug\deps\rmeta37H6Up\lib.rmeta
C:\Users\reill\source\bitline\target\debug\deps\libbitline-961c4e97b4d28930.rmeta
C:\Users\reill\source\bitline\target\debug\deps\rmeta37H6Up\lib.rmeta
C:\Users\reill\source\bitline\target\debug\deps\libbitline-961c4e97b4d28930.rmeta
C:\Users\reill\source\bitline\target\debug\deps\rm-0
C:\Users\reill\source\bitline\target\debug\incremental\bitline-38jupfy1kjztq\s-ginvyutvkc-1p7k82u-working\query-cache.bin
C:\Users\reill\source\bitline\target\debug\incremental\bitline-38jupfy1kjztq\s-ginvyutvkc-1p7k82u-working\query-cache.bin
C:\Users\reill\source\bitline\target\debug\incremental\bitline-38jupfy1kjztq\s-ginvyutvkc-1p7k82u-working\dep-graph.bin
C:\Users\reill\source\bitline\target\debug\incremental\bitline-3jcl4qz7lpem2\s-ginvyutv8y-tis3pa-working\query-cache.bin
C:\Users\reill\source\bitline\target\debug\incremental\bitline-3jcl4qz7lpem2\s-ginvyutv8y-tis3pa-working\query-cache.bin
C:\Users\reill\source\bitline\target\debug\incremental\bitline-38jupfy1kjztq\s-ginvyutvkc-1p7k82u-working\work-products.bin
C:\Users\reill\source\bitline\target\debug\incremental\bitline-38jupfy1kjztq\s-ginvyutvkc-1p7k82u-working\work-products.bin
C:\Users\reill\source\bitline\target\debug\incremental\bitline-3jcl4qz7lpem2\s-ginvyutv8y-tis3pa-working\dep-graph.bin
C:\Users\reill\source\bitline\target\debug\incremental\bitline-38jupfy1kjztq\s-ginvypq4ju-1g8nihp-3tp0vv6stggcl\dep-graph.bin
C:\Users\reill\source\bitline\target\debug\incremental\bitline-38jupfy1kjztq\s-ginvypq4ju-1g8nihp-3tp0vv6stggcl\query-cache.bin
C:\Users\reill\source\bitline\target\debug\incremental\bitline-38jupfy1kjztq\s-ginvypq4ju-1g8nihp-3tp0vv6stggcl\work-products.bin
C:\Users\reill\source\bitline\target\debug\incremental\bitline-38jupfy1kjztq\s-ginvypq4ju-1g8nihp-3tp0vv6stggcl
C:\Users\reill\source\bitline\target\debug\incremental\bitline-38jupfy1kjztq\s-ginvypq4ju-1g8nihp.lock
C:\Users\reill\source\bitline\target\debug\incremental\bitline-3jcl4qz7lpem2\s-ginvyutv8y-tis3pa-working\work-products.bin
C:\Users\reill\source\bitline\target\debug\incremental\bitline-3jcl4qz7lpem2\s-ginvyutv8y-tis3pa-working\work-products.bin
C:\Users\reill\source\bitline\target\debug\incremental\bitline-3jcl4qz7lpem2\s-ginvypq4bq-17r5ljn-ox7d0dh6lvs5\dep-graph.bin
C:\Users\reill\source\bitline\target\debug\incremental\bitline-3jcl4qz7lpem2\s-ginvypq4bq-17r5ljn-ox7d0dh6lvs5\query-cache.bin
C:\Users\reill\source\bitline\target\debug\incremental\bitline-3jcl4qz7lpem2\s-ginvypq4bq-17r5ljn-ox7d0dh6lvs5\work-products.bin
C:\Users\reill\source\bitline\target\debug\incremental\bitline-3jcl4qz7lpem2\s-ginvypq4bq-17r5ljn-ox7d0dh6lvs5
C:\Users\reill\source\bitline\target\debug\incremental\bitline-3jcl4qz7lpem2\s-ginvypq4bq-17r5ljn.lock
C:\Users\reill\source\bitline\.git\fsmonitor--daemon\cookies\13996-142
C:\Users\reill\source\bitline\.git\fsmonitor--daemon\cookies\13996-142
```

**Comment by rgwood** [comment]
^might be related: https://github.com/notify-rs/notify/issues/422

**Comment by rgwood** [comment]
I've bisected and confirmed that this PR breaks `watch` for `*.rs` files when I'm working on a Rust project in VS Code in Windows.

I'll try to put together a minimal repro for the `notify` people, but I think we should revert this for now :(

**Comment by rgwood** [comment]
OK, there are a few problems going on here.

1. We only handle [`ModifyKind::Data`](https://docs.rs/notify/latest/notify/event/enum.ModifyKind.html), but on Windows a change to a Rust file in VS Code is reported as `ModifyKind::Any`: https://github.com/nushell/nushell/blob/27d798270b2051e850f1b2ee3fa118d9992b8ea4/crates/nu-command/src/filesystem/watch.rs#L201
2. If we fix the `watch` code to handle `ModifyKind::Any` too, a single `ctrl+s` save is reported as _3_ `ModifyKind::Any` events:
image

I think we need to either:
1. Revert this PR
2. Fix the `ModifyKind` handling _and_ add debouncing
    1. Without debouncing, `watch` is going to be unusable for common use cases like "run `cargo test` every time I save a file"

**Comment by WindSoilder** [comment]
Hmm...I'd like to tried 2nd option, it's not likely to have debouncing in notify in forseen future :-(  And it's not really good to use old version if we can work around this

**Comment by WindSoilder** [comment]
Yeah, I think so, I'll try this(or next) weekend

**Pull request merged**
