### PR TITLE
update to shadow-rs 0.5. make use easy 

### PR DESCRIPTION
**Pull request by baoyachi**

### CODE REVIEW

**Comment by jonathandturner** [comment]
Hi - thanks for the PR!

I was looking through the error, and I wonder if the fix you did is compatible with webassembly. Looks like it's pulling in some changes that don't work with the webassembly build.

**Comment by baoyachi** [comment]
> Hi - thanks for the PR!
> 
> I was looking through the error, and I wonder if the fix you did is compatible with webassembly. Looks like it's pulling in some changes that don't work with the webassembly build.

look this link:https://github.com/alexcrichton/ssh2-rs/issues/207

**Comment by baoyachi** [comment]
@jonathandturner It's seems everything is ok.

**Comment by jonathandturner** [comment]
Thanks!

**Pull request merged**
