### PR TITLE
 Path Enhancement Project #2: parse, join and split

### PR DESCRIPTION
**Pull request by kubouch**
First PR about representing paths as structured data. For more broad picture, motivation and examples, see #3219.

List of changes:
- [x] : Add `path parse`: Splits a path into a table with `parent`, `stem` and `extension`. On Windows, there is an additional `prefix` column (see Rust's [Prefix](https://doc.rust-lang.org/std/path/enum.Prefix.html)). On non-Windows, the prefix is always empty, so it's pointless to have the column.
- [x] : Remove `filestem` and `extension` subcommands as these can be retrieved from the table
- [x] : Add option to easily extract complex extensions (e.g., `.tar.gz`) or ignore the extension (e.g., `conf.d` directory)
- [x] : Modify `path join` command to convert the path table back into a full path (i.e., reverse the effect of `path parse`)
- [x] : Modify remaining `path` subcommands to accept rows with `parent`, `stem` or `extension` columns.
- [x] : Add `path split` command that splits path by separator

To fix:
- [x] : Broken column path with named flags (passing column path causes `Expected Tagged, found column path`; solution: `rest` arg needs to be always first)
- [x] : Inconsistent split behavior with and without column path (`ls | path split name | get name` vs `ls | get name | path split`)
- [x] : Windows bugs
- [x] : `path join` panic when there is empty stream

We lose the following functionality:
- prefix/suffix flags of `path filestem`

Additional TODO list:
- [x] : craft error messages
- [x] : usages
- [x] : examples (especially of the removed features, such as changing extension)
- [x] : tests
- [x] : rebase
- [x] : clippy
- [x] : fmt

Comments:
- Misplaced errors (`echo home/viking/spam.txt | path parse | update extension 0.9 | path join`)
  * should be probably treated more generally
- Hand-waving `/` vs `\` in Windows tests (Windows seems to accept both `\` and `/` as a separator)

### CODE REVIEW

**Comment by andrasio** [comment]
@kubouch Left a [comment](https://github.com/nushell/nushell/issues/3219#issuecomment-812905506).

**Comment by kubouch** [comment]
All the basic commands are now done. I made `path join` to be implicit, so now all `path` subcommands understand the output of `path parse` and `path split`. It's pretty cool since the `path join` is now basically a noop :-D (it still has the append feature).

The output of `path split` is a table which you need to `flatten` to see the components (for example `echo /home/viking/spam.txt | path split` outputs `[table 4 rows]`). It seems weird at first, but I found it to be the most consistent solution. Now, the path subcommands always operate on every value of the input stream. If `path split` unrolled the table and we wanted to `path join` them back, `path join` would be in a conflict: should it collect the table values or apply `path join` on each value as the rest of the subcommands? There might be a way around this, I just couldn't find it right now.

There is one issue that needs to be solved: 
```shell
❯ ls | first 2 | path expand name | get name | path split
   0   [table 7 rows]
   1   [table 7 rows]
   
❯ ls | first 2 | path expand name | path split name | get name
    0   /
    1   home
    2   kubouch
    3   git
    4   forks
    5   nushell
    6   CODE_OF_CONDUCT.md
    7   /
    8   home
    9   kubouch
   10   git
   11   forks
   12   nushell
   13   CONTRIBUTING.md
```
Seems like using column path somehow steps into the resulting table. Or the `get` recursively steps into into the tables. However, it should ideally output the same result as in the first case.

**Comment by kubouch** [comment]
I modified the `path join` and `path split` commands to behave more like `str collect` and `slpit row`:

* `path join` will attempt to join the input list instead of requiring a table
* `path split` will directly output an output stream of split parts instead of wrapping it into a table

This should match better what a user would expect, IMO. The above applies when not operating by column path. Swapping table values by column path is still supported the same way as before. 

Here are some examples:
```
❯ def ls3 [ ] { ls | first 3 | path expand name }

❯ ls3
  #                          name                          type     size       modified
───────────────────────────────────────────────────────────────────────────────────────────
  0   /home/kubouch/git/forks/nushell/CODE_OF_CONDUCT.md   File     3.4 KB   6 months ago
  1   /home/kubouch/git/forks/nushell/CONTRIBUTING.md      File     1.7 KB   1 week ago
  2   /home/kubouch/git/forks/nushell/Cargo.lock           File   164.7 KB   3 days ago

❯ ls3 | path parse name
  #              name               type     size       modified
────────────────────────────────────────────────────────────────────
  0   [row parent stem extension]   File     3.4 KB   6 months ago
  1   [row parent stem extension]   File     1.7 KB   1 week ago
  2   [row parent stem extension]   File   164.7 KB   3 days ago

❯ ls3 | path parse name | get name
  #               parent                     stem         extension
─────────────────────────────────────────────────────────────────────
  0   /home/kubouch/git/forks/nushell   CODE_OF_CONDUCT   md
  1   /home/kubouch/git/forks/nushell   CONTRIBUTING      md
  2   /home/kubouch/git/forks/nushell   Cargo             lock

❯ ls3 | path split name
  #        name        type     size       modified
───────────────────────────────────────────────────────
  0   [table 7 rows]   File     3.4 KB   6 months ago
  1   [table 7 rows]   File     1.7 KB   1 week ago
  2   [table 7 rows]   File   164.7 KB   3 days ago

❯ ls3 | path split name | get name
   0   /
   1   home
   2   kubouch
   3   git
   4   forks
   5   nushell
   6   CODE_OF_CONDUCT.md
   7   /
   8   home
   9   kubouch
  10   git
  11   forks
  12   nushell
  13   CONTRIBUTING.md
  14   /
  15   home
  16   kubouch
  17   git
  18   forks
  19   nushell
  20   Cargo.lock

❯ ls3 | path split name | each { echo $it.name | path join }
  0   /home/kubouch/git/forks/nushell/CODE_OF_CONDUCT.md
  1   /home/kubouch/git/forks/nushell/CONTRIBUTING.md
  2   /home/kubouch/git/forks/nushell/Cargo.lock

❯ ls3 | get name | path parse | select stem extension | path join
  0   CODE_OF_CONDUCT.md
  1   CONTRIBUTING.md
  2   Cargo.lock

❯ ls3 | get name | path parse | update parent { path split | first 3 | path join } | path join
  0   /home/kubouch/CODE_OF_CONDUCT.md
  1   /home/kubouch/CONTRIBUTING.md
  2   /home/kubouch/Cargo.lock
```

So far, I like the result. It still needs some refactoring and there might still be some edge cases, but I would propose this functionality as final.

**Comment by jonathandturner** [comment]
Lots of cool stuff in this one!

**Pull request merged**
