### PR TITLE
Add auto-cd for directories not starting with ., ./, ../, etc, #8222

### PR DESCRIPTION
**Pull request by ryand67**
# Description

#8222 

Add functionality for auto-cd on paths that don't start with ., ./, ../, ~.

# User-Facing Changes

Before:
```
/home/rdevenney〉Documents/Postman/                                                                                                                     02/28/2023 01:11:41 PM
Error: nu::shell::external_command

  × External command failed
   ╭─[entry #3:1:1]
 1 │ Documents/Postman/
   · ─────────┬────────
   ·          ╰── can't run executable
   ╰────
  help: Permission denied (os error 13)

/home/rdevenney〉                                                                                                                                       02/28/2023 01:11:45 PM

```

After:
```
/home/rdevenney〉Documents/Postman/                                                                                                                     02/28/2023 01:10:36 PM
/home/rdevenney/Documents/Postman〉                                                                                                                     02/28/2023 01:10:48 PM
```

# Tests + Formatting

Don't forget to add tests that cover your changes.

Make sure you've run and fixed any issues with these commands:

- `cargo fmt --all -- --check` to check standard code formatting (`cargo fmt --all` applies these changes)
- `cargo clippy --workspace -- -D warnings -D clippy::unwrap_used -A clippy::needless_collect` to check that you're using the standard code style
- `cargo test --workspace` to check that all tests pass

# After Submitting

If your PR had any user-facing changes, update [the documentation](https://github.com/nushell/nushell.github.io) after the PR is merged, if necessary. This will help us keep the docs up to date.

### CODE REVIEW

**Review by sholderbach — CHANGES_REQUESTED** [review]
Mhh, that doesn't cut it yet in our context as it will `cd` as soon as there is a directory overriding any command.

```
~> mkdir help
~> help
~/help>
```

Would you mind investigating what is up with the `#[ignore]` tests around the auto-cd feature? Would be great if we could keep this covered, especially with complications like that.

**Comment by ryand67** [comment]
Ahh very true, that’s what I get for trying to get this done during my
lunch break. Yes I can investigate that!

**Comment by ryand67** [comment]
@sholderbach Is there a best practice for gathering all available commands to compare against? Was thinking maybe a completer with an empty input but wanted to check to see if I was too off base.

**Comment by kubouch** [comment]
You can check the `help commands` implementation for tips how to query commands.

However, I'm not sure we want to support full autocd? The checks there are likely for a reason, otherwise just `Path::new(&orig).is_dir()` would be enough (the other checks are redundant with your PR). Maybe more core team members could say if/how they want autocd.

**Comment by ryand67** [comment]
Ok perfect, I'll look into that and have it up ASAP so more core members can look into it. Thanks!

**Comment by kubouch** [comment]
We chatted about it and the response seemed lukewarm. The fact that instead of running a command you would enter a directory (or the other way) can make autocd unpredictable. One solution would be to prepend `./` in front of files/directories when tab-completing them and then it would be supported by autocd.

Maybe longer paths with `/` in them could support autocd (command names shouldn't have `/` in them), but doing autocd on any bare word seems a bit too much to me.

**Comment by jntrnr** [comment]
We used to have this functionality, but we removed it because it can be very confusing if you do not expect it. We saw a few different kinds of "footguns" as @sholderbach points out.

While I don't want to go this direction, one that I think that would be very beneficial would be to fix the completions, so that they put the `./` or `.\` in front for you, allowing the auto-cd to do its work.

**Comment by fdncred** [comment]
Seems like we're not going to accept this. Closing for now.

**Pull request closed without merging**
