### PR TITLE
add in the nu-cmd-extra tests to the CI

### PR DESCRIPTION
**Pull request by stormasm**
See if the CI passes with the nu-cmd-extra tests...

### CODE REVIEW

**Comment by amtoine** [comment]
@stormasm 
in the CI, `cargo clippy` and `cargo test` run with the `--workspace` option.
with the investigation i conducted in [#9425](https://github.com/nushell/nushell/pull/9425#discussion_r1228437973), i suspect the `--features` option and thus maybe this `style` field in the PR is useless :thinking: 

it looks to me like, as this is passed through the `MATRIX_FLAGS` variable, it's like running `--features ...` with `--workspace`, which i suspect does absolutely nothing more than `--workspace` alone :thinking:

**Comment by stormasm** [comment]
@amtoine unfortunately I am clueless about the CI and just got it working as I followed the model of how dataframe works...

If you feel like experimenting more with the configuration of the CI file go for it...

Best folks to ask on the CI are probably @rgwood and possibly @sholderbach who may know as well...

I am happy we finally got the nu-cmd-extra tests in there...

If there is more tweaking to be done to make the file simpler I am all for it 😄

**Comment by sholderbach** [comment]
@amtoine this is not a product of the `--features` being overriden by `--workspace` but rather due to the general cratification. 
Previously the feature gating completely removed modules and tests inside the `nu-command` crate. Now they are separate crates that on their own are fully valid and don't have feature gates. Thus workspace will pull them in to compile, lint, and test separately. The final product `nu` will still reflect the feature setting.

Furthermore potentially all the feature requirements they have for upstream crates may get unified with the mainline crates. 

We could look into feature gating the crates themselves internally in some form as well as making their dependencies optional. (the optional dependencies themselves are a good thing in my view!)
May be worth a bit of research if there are some additional workarounds for workspaces in the community. (Instead of just `#[cfg(...)]`ing the whole `lib.rs`)

**Comment by amtoine** [comment]
yup, it's not about the final `nu` binary which is definitely feature-gated :ok_hand: 

it's about `cargo clippy` and `cargo test` :thinking: 
i'm conducting tests to see their behaviour but i think the `--workspace` option overrides `--features` and thus we would be able to simplify the CI quite a bit :yum: 

i'll come back shortly :relieved:

**Comment by sholderbach** [comment]
It doesn't *override* features. Those features are simply not present/relevant in `nu-cmd-extra`/`nu-cmd-dataframe`

From a test as you run perspective it is a bit unfortunate as it seems that the `nu!` tests get the same binary with a level of available features.

I don't worry about `cargo clippy` in my books it is a good thing that we don't have to deal with the added complication that it is feature/cfg aware. There is a bunch of unlinted code that pops up in only certain configs at the moment.

**Comment by amtoine** [comment]
when defining the following command
```bash
def test [case: int] {
    let options = [
        "-D" "warnings"
        "-D" "clippy::unwrap_used"
        "-A" "clippy::needless_collect"
    ]

    match $case {
        0 => { cargo clippy --workspace -- $options },
        1 => { cargo clippy --workspace --features "" -- $options },
        2 => { cargo clippy --workspace --features default -- $options },
        3 => { cargo clippy --workspace --features extra -- $options },
        4 => { cargo clippy --workspace --features dataframe -- $options },
        5 => { cargo clippy --workspace --features dataframe,extra -- $options },
        6 => { cargo clippy -- $options },
        7 => { cargo clippy --features "" -- $options },
        8 => { cargo clippy --features default -- $options },
        9 => { cargo clippy --features extra -- $options },
        10 => { cargo clippy --features dataframe -- $options },
        11 => { cargo clippy --features dataframe,extra -- $options },
        _ => { error make --unspanned {msg: $"unknown case ($case)"} },
    }
}
```
i.e. basically all the scenarii, with and without `--workspace`.

now if i apply a patch with one clippy error in `extra` and another one in `dataframe`, i get the following results:
| case | --workspace | --features      | extra              | dataframe          |
| ---- | ----------- | --------------- | ------------------ | ------------------ |
| 0    | true        | none            | :x:                | :x:                |
| 1    | true        | ""              | :x:                | :x:                |
| 2    | true        | default         | :x:                | :x:                |
| 3    | true        | extra           | :x:                | :x:                |
| 4    | true        | dataframe       | :x:                | :x:                |
| 5    | true        | dataframe,extra | :x:                | :x:                |
| 6    | false       | none            | :heavy_check_mark: | :heavy_check_mark: |
| 7    | false       | ""              | :heavy_check_mark: | :heavy_check_mark: |
| 8    | false       | default         | :heavy_check_mark: | :heavy_check_mark: |
| 9    | false       | extra           | :x:                | :heavy_check_mark: |
| 10   | false       | dataframe       | :heavy_check_mark: | :x:                |
| 11   | false       | dataframe,extra | :x:                | :x:                |

## conclusion
i think the `--workspace` option overrides `--features` and, as we want to test all features in the CI, we can probably get rid of the `--features` option and simplify the jobs :yum:

**Comment by sholderbach** [comment]
You draw the wrong conclusion from the observation in a technical sense of how it works. It doesn't override `features` it makes the crates visible to `cargo clippy`/`cargo test`.

The reason why one should test a feature matrix is not primarily that we want to compile/lint less for speed but rather that there could be unforeseen problems only arising thanks to `#[cfg(feature = "...")]` logic or incompatibilites through other feature-gated crates.

**Comment by amtoine** [comment]
mm i do not understand here...

above, when `--workspace` is triggered, regardless of the `--features` option, we always get *Clippy* errors on all the features :thinking: 
i do not see the point of having `--features` when we already have `--workspace`, because the `extra` and `dataframe` are part of the workspace!

**Pull request merged**
