### PR TITLE
Add or update examples for some commands

### PR DESCRIPTION
**Pull request by hustcer**
# Description

Add or update examples for some commands
  
# Tests

Make sure you've run and fixed any issues with these commands:

- [x] `cargo fmt --all -- --check` to check standard code formatting (`cargo fmt --all` applies these changes)
- [x] `cargo clippy --all --all-features -- -D warnings -D clippy::unwrap_used -A clippy::needless_collect` to check that you're using the standard code style
- [x] `cargo build; cargo test --all --all-features` to check that all the tests pass

### CODE REVIEW

**Comment by hustcer** [comment]
Update issue: https://github.com/nushell/nushell/issues/4518

**Comment by fdncred** [comment]
I added a couple comments. This is great though! Thanks for working so hard on this. We generally want to avoid `None` results as much as possible, but as you've seen, sometimes you have to have a `None` result.

**Comment by fdncred** [comment]
> That's because `cargo test --all --all-features` won't check the result. LOL

Exactly! We want as many of these examples to run through cargo test as possible to ensure that we don't break things. Thanks for understanding!

**Comment by hustcer** [comment]
@fdncred I have checked all the examples, the output result will be different on different machine, How to handle these situations?

**Comment by fdncred** [comment]
@hustcer I think the only ones that need to be changed are the ones I mentioned.

**Comment by fdncred** [comment]
you may need to refresh the issue. But here's a screenshot.
Screen Shot 2022-02-18 at 6 23 22 AM

**Comment by hustcer** [comment]
> you may need to refresh the issue.

It's very strange, I cleared the cache and refreshed the issue, but could not see any comments.

**Comment by hustcer** [comment]
@fdncred BTW， `let x = if $false { -1 } else { 1 }` has no result, and it's `if $false { -1 } else { 1 }` who has a result. And the `alias` result is the same. I don't think they have results. Feel free to update it, I will follow you next time

**Comment by hustcer** [comment]
I mean 1 is the result of `if $false { -1 } else { 1 }` not `let x = if $false { -1 } else { 1 }`
and `$scope.aliases | where alias == ll | get expansion` is nu code, not rust code
And the previous let examples' results are `None` too:
```rust
            Example {
                description: "Set a variable to a value",
                example: "let x = 10",
                result: None,
            },
            Example {
                description: "Set a variable to the result of an expression",
                example: "let x = 10 + 100",
                result: None,
            },
```

**Pull request merged**
