### PR TITLE
Respect non-zero exit code in subexpressions and blocks

### PR DESCRIPTION
**Pull request by sophiajt**
# Description

This PR changes the way we handled non-zero exit codes to be and early exit between `foo; bar`. If `foo` in the example has a non-zero exit code, `bar` wouldn't be run.

This also affects subexpressions.

Note: this breaks some tests, so we'll want to think through a) if we want this approach, b) how do we easily want to say "continue if there is an error" in the same way bash differentiates between `;` and `&&`.

# User-Facing Changes

This would be a breaking change, as both interactive and scripts could work differently in the presence of non-zero exit codes.

# Tests + Formatting

# After Submitting

### CODE REVIEW

**Comment by WindSoilder** [comment]
Thanks @jntrnr, I really like the change, it's much better than my attempt :-D

**Comment by WindSoilder** [comment]
It will fix #7690

**Review by WindSoilder — APPROVED** [review]
I believe it works fine after some redirection fixes and we disabled pipeline echo in https://github.com/nushell/nushell/pull/8292

I've been bothered for a long time, thanks for the fix!

**Comment by amtoine** [comment]
@WindSoilder 
i just tried
```nushell
(^false; "hello,world!")
```
on this PR and, even though it correctly does not print the string, it does not return the exit code of `1` from `^false`, is that expected?

**Pull request merged**
