### PR TITLE
Command: Add `config env/nu --default` to print defaults

### LINKED ISSUE #5436: Display/query default config even when not present in config file
### Related problem

I'm trying out `nu` and I started using it in `0.61.0`. `0.62.0` came out and changed several things in how the config is supposed to be written. There was no warning, no indication, nothing about it when launching `nu`.

What's more, since the default config is written entirely in `config.nu`, if it evolves upstream it won't be updated for me, leading to potential confusion very quickly when i don't experience the changes noted in the changelog.

Finally, I think there is no way to display/query the full configuration that is active while running `nu` and it makes for a poor UX since I can't discover settings I would like to modify and such.

### Describe the solution you'd like

A `nu config` subcommand that would:

- output a normal table when given no arguments or `--table`
- output a runnable `nu` script when given `--script` so that it can be tried out in isolation

### Do nothing

Possible, still horrible UX. I don't want to have to follow `nu` updates very closely just to update the *default* config.

### Give a warning like `starship` does on update

Better, but starship configs are quite stable and no runnable scripts but a single `toml` file. `nu`'s default configuration changes often, and in non-backward compatible ways.

### Rewrite the `config/env.nu` files on update

This would delete all custom configurations, obviously not feasible. Renaming the old file and sourcing it in the new one is problematic too, since if sourced at the start the new defaults could override configuration changed by the user and if sourced at the end the old defaults could override the new ones, which is not better.

### Additional context and details

_No response_

### PR DESCRIPTION
**Pull request by poliorcetics**
# Description

Closes #5436

When I opened this issue more than a year ago, I mainly wanted the following capacity: easily access the full env and have the hability to update it when a new version of `nushell` comes out.

With this PR I can now do the following:

```nu
source-env ~/.config/nushell/defaults/env.nu
source     ~/.config/nushell/defaults/config.nu

# Update nushell default config & env file (run this after a version update)
def update-defaults [] {
    config env --default | save -f ~/.config/nushell/defaults/env.nu
    config nu  --default | save -f ~/.config/nushell/defaults/config.nu
}
```

Which is more than enough for me. Along with `nushell` respecting the XDG spec on macOS (`dirs-next` should be banned for CLI tools on macOS), this should be one of the last hurdle before fully switching for me!

# User-Facing Changes

Two new switches to existing commands:

```nu
config env --default # Print the default env embedded at compile time in the binary
config nu  --default # Print the default config embedded at compile time in the binary
```

# Tests + Formatting

- Added a test for the output of `config env --default`
- Added a test for the output of `config nu --default`

# After Submitting

Are the docs for commands generated automatically or do I need to make a PR there too ? It's no problem if so, just point me at instructions if there are any :)

### CODE REVIEW

**Comment by poliorcetics** [comment]
Note: I'm note sure if the last commit is worth it ? Since `source` and `source-env` only work with a file, `source (config default nu)` won't work so I'm sure how the const form could be useful. It's two lines of code though, so I'm not too worried about maintainability 😅

**Comment by fdncred** [comment]
First of all, thanks for this! I think this type of feature will make nushell better. :heart:

I'm wondering if we should reduce some of the boilerplate and just have 1 `config default` command that takes a parameter of `env` if you want the env.nu and no parameters if you want the config.nu. Also, it would be good to have `login` and `plugin` parameters to see the login.nu and plugin.nu files.

IMO, the default output should be a structured output like a record or a table, like when you type `$env.config` but I can see the value of having a `--text` parameter too.

I'm anxious to hear what others think.

**Comment by poliorcetics** [comment]
> Also, it would be good to have login and plugin parameters to see the login.nu and plugin.nu files.

Didn't even know they existed ! I'll add them

**Comment by poliorcetics** [comment]
> Also, it would be good to have login and plugin parameters to see the login.nu and plugin.nu files.

There are not such defaults in `nu` ?

**Comment by poliorcetics** [comment]
> I'm wondering if we should reduce some of the boilerplate and just have 1 config default command that takes a parameter of env if you want the env.nu and no parameters if you want the config.nu

That's not the precedent that has been set with `config nu` and `config env`

**Comment by poliorcetics** [comment]
> IMO, the default output should be a structured output like a record or a table, like when you type `$env.config` but I can see the value of having a `--text` parameter too.

I'm unsure how to achieve this since to evaluate to a record/table, context is needed and that context may have changed a lot between the shell starting and the call to `config default ...`

Also, I'm unsure in which situation `config default nu` should output a record, it not's something I have wanted at all, the only feature I missed was being able to generate the defaults locally to have my own `config/env.nu` importing them and modifying just what I wanted

**Comment by fdncred** [comment]
I'm just guessing that the CI failure on Windows may be because Windows may have `\r\n` and not just `\n`.

**Review by amtoine — COMMENTED** [review]
i think this is a great idea, thanks @poliorcetics :pray: 

> **Note**
> one could also write a command to pull the files from the Nushell repo
> ```nushell
> def update-default-config [] {
>     let revision = (version).commit_hash? | default (version).version
> 
>     let default_config = $"https://raw.githubusercontent.com/nushell/nushell/($revision)/crates/nu-utils/src/sample_config/default_config.nu"
>     let default_env = $"https://raw.githubusercontent.com/nushell/nushell/($revision)/crates/nu-utils/src/sample_config/default_env.nu"
> 
>     http get $default_config | save --force $nu.config-path
>     http get $default_env | save --force $nu.env-path
> }
> ```

**Comment by poliorcetics** [comment]
Yes I thought about it and I have something like this locally (didn't think about using `version` since I only run this very close to updates of nushell so haven't had troubles with `blob/main/` yet), but it has some (small) problems: it doesn't work with local development builds and it asks for more internet downloads when the data is already present locally in the binary, which I always find a little sad

@fdncred In preparation for a future where `config default nu` gives a structured output, I could add a `--text` flag to `config default env/nu` to make it behave as it does in this MR currently while leaving room for future improvements, would that be ok ?

**Comment by fdncred** [comment]
What about `config env --default` and `config nu --default` to dump to a text output? I'm really just looking for less code to maintain.

I'm not sure what adding a --text parameter would do in this PR since it already produces text.

**Comment by poliorcetics** [comment]
You mentioned having `config default nu` output a structured record, but if that's unnecessary at the moment, then yes `config env/nu --default` is enough and I can do it quickly

**Comment by poliorcetics** [comment]
Made the change and modified the MR title and description to reflect the new MR state

**Review by fdncred — APPROVED** [review]
I'm good with these changes. Thanks!

**Comment by fdncred** [comment]
let's move forward with this and see if anyone complains. 😆 Thanks for working with us!

**Pull request merged**
