### PR TITLE
Remove `yr` and `mon`

### LINKED ISSUE #3253: Remove the `yr` and `mon` units
**Describe the bug**
The `yr` and `mon` units don't really make sense. Making `1yr` equal 365 days and `1mon` equal to 30 days feels not very helpful and even potentially error-prone if people thing that the duration understands the context (some years are more than 365 days, some months have different than 30 days).

**To Reproduce**
1. `echo 1yr`
2. `echo 1mon`
3.

**Expected behavior**
These units shouldn't exist. We should remove both from Nushell.

### PR DESCRIPTION
**Pull request by mhmdanas**
Fixes #3253.

### CODE REVIEW

**Comment by mhmdanas** [comment]
Anybody know why the test fails? It doesn't look related to my changes on first glance.

**Comment by kubouch** [comment]
If you click through the failure details, it shows the `format_conversions::html::test_html_color_where_flag_dark_false` test is failing. It seems like it somehow relies on having `yr` or `mon` units in the table. When you copy-paste the left and right side of the error, as shown in the error message, into a text editor, and search for "yr" and "mon, you'll see that the right side contains "mon", while the left one doesn't. So the test somehow relies on having the removed "mon" unit.

**Comment by mhmdanas** [comment]
@kubouch thanks for the help!

**Comment by jonathandturner** [comment]
Looks good!

**Pull request merged**
