### PR TITLE
compute directory sizes from contained files and directories

### PR DESCRIPTION
**Pull request by Amanita-muscaria**
resolves: https://github.com/nushell/nushell/issues/1242

`ls --full` will now show the total directory size as computed from all the contained files and folders recursively.

This has been the only time in my career where a recursive function was actually a good idea.

### CODE REVIEW

**Comment by jonathandturner** [comment]
I like it.

I wonder if this should go behind a new flag. Maybe `--total` to get directory totals. You might want to do `full` to get the extra information but not want to wait for the full totals (especially for big directories)

**Comment by Amanita-muscaria** [comment]
I thought about that but I'd have to change the function declaration for each shell and only the filesystem shell actually needs this.

**Comment by thegedge** [comment]
Sorry, I asked this question in the issue not realizing we already had a PR out:

> One question I'd like to first ask: would it make more sense for us to build a du alternative instead of baking this into ls? More generally, should we take the UNIX philosophy with our tools and try to keep their complexity down by making them do one thing well?

I was wondering what we thought about those questions, since I think it sets a precedent that I want to make sure is the right one 🙂

**Comment by Amanita-muscaria** [comment]
Personally, I don't mind either way. I can add a different command to do this just as easily as I've added it to `ls`.

**Comment by jonathandturner** [comment]
Sure, let's do it that way. @Amanita-muscaria - your point about adding it to all the shells is a good one. Want to take @thegedge's idea and turn this into a new `du` command?

**Comment by andrasio** [comment]
Agree with all points stated. Thank you!!!

**Comment by Amanita-muscaria** [comment]
Ya, I can do that.

**Comment by jonathandturner** [comment]
Looks good!

**Pull request merged**
