### PR TITLE
Adds rustls compile time feature flag

### PR DESCRIPTION
**Pull request by fnordpig**
# Description
Adds a rustls compile time feature flag.  I do this by also adding a native-tls feature flag that's enabled by default, and using cfg-if to pick out the rustls feature flag integration.  This would make it easy to swap which is the default in the future, enabling people to explicitly use native-tls today and safely inherit that if we were to switch at some point to rustls.  Default features can not currently be predicated against (there's a nightly feature in development to allow this, but isn't available today.

# User-Facing Changes
All user facing behaviors are the same.

# Tests + Formatting
Ran tests and formatting.

- :green_circle: `toolkit fmt`
- :green_circle: `toolkit clippy`
- :green_circle: `toolkit test`
- :green_circle: `toolkit test stdlib`
- 
# After Submitting

### CODE REVIEW

**Comment by fnordpig** [comment]
Let me know if there are any concerns.  I'm traveling in SE Asia right now so turn around times might be slow.  I wasn't really able to find a way to feature flag things neatly that had a reasonable glide path for any eventual default changes that allowed for no-op default changing and preserving behavior for native-tls dependent users other than this.  Rustls  maintainers also really don't like the idea of accepting invalid certificates so there's no simple API for doing so, hence requiring a special pass through verifier.  If we wanted to tighten up some aspects and not just be a rubber stamp LMK, but this is what postgresql rust integration is doing.

**Comment by fnordpig** [comment]
Any thoughts?

**Comment by sholderbach** [comment]
Thanks for working on this!

We are all currently a bit busy with the hotfixes for the type system. (we want to get this out the door before we think about landing new changes)

I like the option through the feature flag so we can proof out if rustls works on all platforms we ship to, and have the option for package maintainers to still link to openssl.
At the same time each new feature flag needs a level of testing (and also a clippy pass as that is also going through conditional compilation!). So we should make sure we get this into CI properly: At some point tested on every platform in all configs. Not sure if the "all on all" is necessary for the PR-level checks, we could expand our nightly CI work to have a nightly check run as well.

**Comment by fnordpig** [comment]
> I have no idea if the  `NoCertificateVerification` struct is a problem, but I personally don't like how you handled the conditional compilation. Rust is already very capable of differentiating what feature you want without a new dependency. Just use `#[cfg(all(feature = "rustls", not(feature = "native-tls"))]` and vice versa.  `#cfg[all(feature = "rustls", feature = "native-tls")]` and `#cfg[all(not(feature = "rustls"), not(feature = "native-tls"))]` can then be used for your `compile_error!`

From discord @Piepmatz

**Comment by cptpiepmatz** [comment]
@fnordpig it was me 😅

**Comment by piepmatz** [comment]
@fnordpig, I guess you tagged the wrong guy here ;)

**Comment by amtoine** [comment]
@fnordpig 
it looks like `http_client` is not a thing in `network::http:client` :open_mouth: 
do you have some time to look into it? :innocent:

**Comment by fnordpig** [comment]
Yes I'll be revising this soonish. Still traveling

**Comment by fnordpig** [comment]
> @fnordpig 
> 
> it looks like `http_client` is not a thing in `network::http:client` :open_mouth: 
> 
> do you have some time to look into it? :innocent: 

Sure!  But I'm not sure what you mean - I've not been at a computer and haven't merged, had the file changed?  If so that's fine I will retrofit to whatever is there now.

**Comment by amtoine** [comment]
> Yes I'll be revising this soonish. Still traveling
>
no worries, when you have time, if any :wink: 

> Sure! But I'm not sure what you mean - I've not been at a computer and haven't merged, had the file changed? If so that's fine I will retrofit to whatever is there now.
>
if you look at the [failing CI job](https://github.com/nushell/nushell/actions/runs/5655058861/job/15319381264?pr=9798), we get the following error
```
error[E0432]: unresolved import `crate::network::http::client::http_client`
Error:  --> crates/nu-command/src/network/http/put.rs:9:5
  |
9 |     http_client, http_parse_url, request_add_authorization_header, request_add_custom_headers,
  |     ^^^^^^^^^^^ no `http_client` in `network::http::client`
```

**Comment by fnordpig** [comment]
> > Yes I'll be revising this soonish. Still traveling
> 
> no worries, when you have time, if any 😉
> 
> > Sure! But I'm not sure what you mean - I've not been at a computer and haven't merged, had the file changed? If so that's fine I will retrofit to whatever is there now.
> 
> if you look at the [failing CI job](https://github.com/nushell/nushell/actions/runs/5655058861/job/15319381264?pr=9798), we get the following error
> 
> ```
> error[E0432]: unresolved import `crate::network::http::client::http_client`
> Error:  --> crates/nu-command/src/network/http/put.rs:9:5
>   |
> 9 |     http_client, http_parse_url, request_add_authorization_header, request_add_custom_headers,
>   |     ^^^^^^^^^^^ no `http_client` in `network::http::client`
> ```

Ah the issue is this:

```
error: Either feature native_tls or rustls features must be specified.
Error:   --> crates/nu-command/src/network/http/client.rs:93:9
   |
93 |         compile_error!("Either feature native_tls or rustls features must be specified.");
   |         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

So: either I need to add a --feature nativetls or need to make nativetls implicit as before - any preference?  I added the nativetls feature to make it clearer what's going on and easier to in the future swap the default to rustls.

**Comment by fnordpig** [comment]
Merged origin/main.  Still not sure what to do with the virtualenv that's failing - I don't think there's any technical risk with adding ''--features native-tls'' to make it pass, but I don't know if the lack of feature flags is necessary for some reason.

**Comment by fnordpig** [comment]
Hi! Sorry I was on an extended trip and just got back, sorry for letting this languish.  I'm going to amend the virtualenv to pick nativetls rather than no defaults and resubmit.  If anyone has any reason that it must have absolutely no feature flags, LMK and I'll try to figure out a way forward.

**Comment by sholderbach** [comment]
Thanks for your persistence on this!

> Merged origin/main. Still not sure what to do with the virtualenv that's failing - I don't think there's any technical risk with adding `--features native-tls` to make it pass, but I don't know if the lack of feature flags is necessary for some reason.

This sounds fine, I think the disabling of features is just used to cheap out on compile time. (In theory you could also build with `rustls` if this compiles faster with `--no-default-features` 🤔 )

**Comment by fnordpig** [comment]
For some reason I have to exclude rustls from the windows testing - it fails in a seemingly unrelated test:
``` rust
#[cfg(windows)]
#[test]
fn can_run_batch_files_without_cmd_extension() {
    use nu_test_support::fs::Stub::FileWithContent;
    Playground::setup(
        "run a Windows batch file without specifying the extension",
        |dirs, sandbox| {
            sandbox.with_files(vec![FileWithContent(
                "foo.cmd",
                r#"
                @echo off
                echo Hello World
            "#,
            )]);

            let actual = nu!(cwd: dirs.test(), pipeline("foo"));
            assert!(actual.out.contains("Hello World"));
        },
    );
}
```

However all tests pass at this point.  I will keep digging into the windows test, I have a non-dev windows machine at home I can try to figure out what's going on, but I really only use windows for games so am not particularly adept!

**Comment by cptpiepmatz** [comment]
I cloned this PR on my Windows machine and have no issues with the tests, maybe you need to run them with elevated privileges.

**Comment by fnordpig** [comment]
Weird, I'll reenable them so we can more easily see the CI error

**Comment by fnordpig** [comment]
@cptpiepmatz check the test failures - make any sense to you?

**Comment by sholderbach** [comment]
Wth is going on with this test?!

**Comment by fnordpig** [comment]
Ok figured it out, got my gaming machine set up and tested. The which-support feature is required for windows to pass all tests. I added all the default flags to the rustls test to be sure behavior is as expected, except no native-tls.

Please let me know if there's any further feedback!!

**Review by sholderbach — APPROVED** [review]
I am supportive of adding this option. Your code looks good to me, and great that you figured out the problem on Windows.

Unfortunate state with cargo that the feature additivity breaks for stuff like this where you need to introduce an explicit `compile_error!` to get things working. 

The only quality of life improvement for `cargo build --no-default-features` I could think of would be to completely remove the http commands when just having default features but maybe I am thinking around too many corners.

**Comment by fnordpig** [comment]
Sweet!  Anyone with merge rights willing to close this out?  Thanks!

**Comment by stormasm** [comment]
We had our core team meeting today and discussed your PR at length.

Unfortunately we are not going to be able to land your PR.

We have a lot of priorities ahead of us prior to our 1.0 release and
we discussed the pros and cons of supporting 
[rustls](https://crates.io/crates/rustls) at this time and we are not
able to do it...

However, we would be willing to have a link on our
[awesome-nu](https://github.com/nushell/awesome-nu) website talking about
how folks can install rustls based on the work you have done.

There are several options of how you could move forward with a fairly simple
install of rustls.

### Option One

One way would be to publish out a new crate.  Something like *nu-cmd-rustls*
and then folks who wanted to use it could add a line of code in here to
their main.rs

https://github.com/nushell/nushell/blob/main/src/main.rs#L41

You could then link in your crate here with one line of code

```rust
let engine_state = nu_cmd_rustls::add_rustls_context(engine_state);
```

You could change the name of the http command to something similar but
different.  This way no changes would need to be made to the nu-command
crate and the new crate would have a slightly different named http command.

So basically take this command infrastructure

https://github.com/nushell/nushell/tree/main/crates/nu-command/src/network/http

and change the name of the http command and everything would work.

If you decide to publish out the crate.  You could publish out the crate from your
account and then reference it from the top level Cargo.toml.

If you are interested in going down this route let me know and I could
advise you on a way forward.  I have done this with other code integrations
so I am familiar with the issues involved in making this happen.

That is why I am the person who is responding to your PR :)

### Option Two

You could also just do a drop in replacement of your currently written code
including : crates/nu-cmd-rustls/src/network/http/client.rs

and then modify the Cargo.toml files accordingly.

### Option Three

You could also consider doing a nushell plugin...

If you have further questions about this reach out to me on discord.
You can send me a private message to @stormichael on discord

**Comment by stormasm** [comment]
See my above comment.  I am closing this PR.

**Pull request closed without merging**
