### PR TITLE
nu-explore/ A few things

### PR DESCRIPTION
**Pull request by zhiburt**
ref #7332

### CODE REVIEW

**Comment by fdncred** [comment]
wow, lots of stuff here to try. thanks @zhiburt!!

**Comment by fdncred** [comment]
Quite a few things are addressed here. Definitely quite a few steps in the right direction here. I've marked off the ones seem complete-ish in #7332. There's a few that I don't quite understand how to make work yet.

- I see you have a record mode now. Thanks! We'll have to play with it for a while to see if we need a `:record` command or not. One idea is to be able to transform the data from :table to :record to :expand, etc. but that doesn't seem possible yet.
- I see we have a `:table` mode now, although I'm not sure I understand how it works. Same idea as above, to be able to switch modes and transform the data. Like if I do `open cargo.toml | explore` it opens is record more correctly. But then if I type `:table`, it just puts a 1 2 column on it. I expected that doing `:table` here would take the keys and make them columns.
- Make `enter` have the same behavior as `i` I think is a good idea to make it less vim-like. Thanks. Let's see what others think of it.
- `:preview` renamed to `:expand` - Thanks
- using `tab` in `:try` mode is a wonderful thing - It seems so much more intuitive to me. Thanks!
- I see the help in the status bar. checked off!
- And fixed some general bug, good work!!

Do you have any questions? 
Do you want to continue adding to this PR - or would you rather land this and make another PR to try and address the other things?

**Comment by fdncred** [comment]
I'd probably be willing to land this PR, and continue iterating, if I could understand the `:help` changes better.

**Comment by zhiburt** [comment]
> One idea is to be able to transform the data from :table to :record to :expand, etc. but that doesn't seem possible yet.

I it's possible I believe.

> I see we have a :table mode now, although I'm not sure I understand how it works.

So it's not a mode.

To be crystal clear it's output would be the same as if you would run `:nu` with no arguments.

> Like if I do open cargo.toml | explore it opens is record more correctly. But then if I type :table, it just puts a 1 2 column on it. I expected that doing :table here would take the keys and make them columns.

What happens is exactly what you've described.
When we run `explore` we see it's a record so we hide the columns and press `<t>`.

and these 1 2 you see is hidden columns.

> if I could understand the :help changes better.

But what you don't understand?

**Comment by zhiburt** [comment]
I've just changed a bit its columns by moving shortcuts to the commands

download (17)

**Comment by fdncred** [comment]
> But what you don't understand?

Ok, I see now. I think we just want to see them all on one screen without having to traverse to `[table 6 rows]` and hit enter.

**Comment by zhiburt** [comment]
> Ok, I see now. I think we just want to see them all on one screen without having to traverse to [table 6 rows] and hit enter.

So why we had that screen cause I was not sure where to highlight search support.

But I've take a look at vim help and they show just a text by default.
So did I.

download (18)

**Comment by fdncred** [comment]
> Close this window:  Use "<Esc>".

I can't get that to work. I type `explore`, read the help text, hit `esc` and nothing happens.

**Comment by zhiburt** [comment]
> I can't get that to work. I type `explore`, read the help text, hit `esc` and nothing happens.

Well someone just bad in a documentation :)

I assume you opened it right from `explore`.
If you would do `ls | explore`, `:help`, `<Esc>` it would exit.

Remember we discussed some time ago that there are cases were we don't keep track of screens.
So they when we hit `<Esc>` we don't get back to them but rather skip them.
These are welcome screen, `:try` and `:help` I believe.

**Comment by rgwood** [comment]
> PS: Not sure whether you've noticed but code I've written so far got not a lot of comments 😅 😥

Sorry about that; I've been busy with other stuff and haven't had much time to devote to reviewing your code reviews. I'll try to spend some more time looking at it but can't make any promises.

I do think `explore` is really cool, thanks for making it!

**Comment by fdncred** [comment]
> PS: Not sure whether you've noticed but code I've written so far got not a lot of comments

Ya, we'd love more comments but that can come as nu-explore matures.

> I assume you opened it right from explore.

yes.

> Remember we discussed some time ago that there are cases were we don't want to get back to some screens.

Yes, I remember that conversation, but also, I think the team still wants `esc` to quit out once you're at the "root" view.

**Comment by fdncred** [comment]
@zhiburt I think "record mode" may still need a little polish. Try this:
1. `$nu | explore`
2. We're in record mode, great! (It may be nice to have maybe a little padding at the top, but we can continue to discuss that)
3. Hit enter, then select scope's `{record 5 fields}` and hit enter. It looks like this, which is a little confusing. 
Screenshot 2022-12-04 at 7 24 10 PM
I'm thinking that since it's a record, it should look like this (which i did by hitting `t`)
Screenshot 2022-12-04 at 7 25 27 PM
So, I think the rule of thumb is that when the data is a nushell `record` it should look like this transposed view.

**Comment by zhiburt** [comment]
> I'm thinking that since it's a record, it should look like this (which i did by hitting `t`)

Fixed.

> Yes, I remember that conversation, but also, I think the team still wants esc to quit out once you're at the "root" view.

Added a config option so if it's set it will be the case. (`exit_esc`)

Also renamed some other options so now config looks like this.

```nu
{
  status_bar: { bg: '#FFF9C1', fg: '#1D1F21' }
  command_bar: { fg: '#C4C9C6', bg: '#223311' }
  highlight: { bg: 'yellow', fg: 'black' }

  exit_esc: true,

  status_info: { bg: "yellow", fg: "blue" }
  status_warn: { bg: "yellow", fg: "blue" }
  status_error: { bg: "yellow", fg: "blue" }

  table_split_line: { fg: '#ff00f0', attr: "b" }
  table_cursor: true
  table_selected_column: 'blue'
  table_selected_row: { fg: 'yellow', bg: '#C1C2A3' }
  table_selected_cell: { fg: 'white', bg: '#777777' }
  table_line_shift: false,
  table_line_index: false,
  table_line_head_top: false,
  table_line_head_bottom: false,
}
```

**Comment by fdncred** [comment]
Thanks for another round of changes! This thing keeps getting better and better.

- I think record detection is working much better, but I think we would like to have it without the `1 2` type columns.
- `esc` is working much better. thanks! I definitely like the idea of a config option for this. good idea!
- I like your renamed settings, seems much more intuitive!
- the `tweek` command is a good idea. can you change the spelling to `tweak`?
- I can't get `try_border_color` to change colors either with `:tweek try_border_color '{ fg: green }'` or by changing the config file.

**Comment by zhiburt** [comment]
Took me longer than I was thinking to do this subtle change, but now we have a different config once again.

```nu
{                                                                                                                                                                            12/05/2022 09:24:16 PM
      status_bar: { bg: '#FFF9C1', fg: '#1D1F21' }
      command_bar: { fg: '#C4C9C6', bg: '#223311' }
      highlight: { bg: 'yellow', fg: 'black' }

      exit_esc: true
 
      status: {
        info: { bg: "yellow", fg: "blue" }
        warn: { bg: "yellow", fg: "blue" }
        error: { bg: "yellow", fg: "blue" }
      }

      table: {
        show_index: true
        show_head: true

        split_line: { fg: '#ff00f0', attr: "b" }

        cursor: true
        selected_column: 'blue'
        selected_row: { fg: 'yellow', bg: '#C1C2A3' }
        selected_cell: { fg: 'white', bg: '#777777' }

        line_shift: false
        line_index: false
        line_head_top: false
        line_head_bottom: false
      }

      try: {
        border_color: 'red',
        highlighted_color: 'blue'
      }
}
```

> I think record detection is working much better, but I think we would like to have it without the 1 2 type columns.

Yep I kind of back down a bit here ....
As you can do now `:tweak table show_head false` and it won't be shown any more.

> I can't get try_border_color to change colors either with :tweek try_border_color '{ fg: green }' or by changing the config file.

It must work.
Though I've noticed that we can't do it like this `{fg: red}` you should do  just  `'red'`.

> Note for anyone else testing. I noticed some performance issues until I built in release mode. Perf issues in debug mode aren't a concern at this point.
> 
> This is one such sequence that is slow in debug mode. (1) $nu | explore (2) :e - it takes several seconds in debug mode and about a second in release mode.

So interesting.
It actually must be approximately the same as general `table -e` call. (which also slow but if there's some difference that might be an issue then?)

**Review by zhiburt — COMMENTED** [review]
I did not notice, good catch.

**Comment by fdncred** [comment]
> Took me longer than I was thinking to do this subtle change, but now we have a different config once again.

LOL. Sorry it's being so difficult. I'm still having problems with it. Maybe I'm doing something wrong. I have this in my config
image

When I launch `$nu | explore` and then do `:try` the borders are white vs red, which is in the config.
image

If I do `:tweak try border_color red` it works and changes the color. Seems like it would be more intuitive to make this `:tweak try.border_color red` but I'm fine with the way it is now.

> As you can do now :tweak table show_head false.

Oh, I see. Then that's fine. We can make the default `show_head: false` because that's what others want to see. Oh, btw - show_head false in the config doesn't work either. I'm beginning to thing the config isn't being read correctly.

**Comment by zhiburt** [comment]
> Oh, I see. Then that's fine. We can make the default show_head: false because that's what others want to see. Oh, btw - show_head false in the config doesn't work either. I'm beginning to thing the config isn't being read correctly.

To be a candor I didn't tested config,
I've used `let-env`

**Comment by fdncred** [comment]
> To be a candor I didn't tested config,
> I've tested it by let-env

That's what I'm here for. To help test. :)

> It would make all :tables being with no column headers. Therefore ls | explore would also be with not header.

We don't want all tables to be without headers. We just want a different view with records than with tables. I was thinking it would be easier to say that if it's a record, don't have a header and if it's a table, show the header. But, if it's easier to have an entirely separate view too, we can do that too. We're open to other ideas. We just want to be able to show records and tables similarly to the way nushell shows each of them.

**Comment by zhiburt** [comment]
Followed your suggestion with a path `:tweak table.line_head_bottom false` usage.

Added an ability to move column headers around.
(To address special record treatment).

download (20)

**Comment by fdncred** [comment]
oh wow, that table.orientation thing looks cool. gonna play a bit now. :)

**Comment by fdncred** [comment]
ok, this new handling of tables and records is great! good work. I'd like to land this but there are two things not working yet.
1. The config settings in config.nu seem to be ignored
2. `esc` doesn't seem to quit now. i tried `sys | explore` then hit `esc`. Then in another session I tried `sys | explore`, then `:tweak exit_esc true`, and then hit `esc` and it didn't quit.

if we can get these 2 things working. i think we can land this and talk about the other things in #7332

**Comment by zhiburt** [comment]
> The config settings in config.nu seem to be ignored

Works for me just verified

> esc doesn't seem to quit now

Indeed it was a case.
Fixed.

_____

Added a few more config settings:

`table.padding_column_left    <u16>`
`table.padding_column_right  <u16>`
`table.padding_index_left        <u16>`
`table.padding_index_right     <u16>`

`try.reactive <bool>` (I might got it wrong but is it what [@yingzhu146](https://github.com/yingzhu146) was talking about?)

`help_banner <bool>` (proposed by [@remmycat](https://github.com/remmycat))

**Comment by zhiburt** [comment]
> I'm not sure if i have some error in it or what, but the try.border_color is definitely not red.

Not sure neither

It works for me on linux when the config is placed in `$nu.config-path`.

_________________________

For a few days I was kind of chasing around 1 idea. (obviously not that original)

download (22)

All though after this change code quality quite a bit dropped down :disappointed: 

it's a bit unstable so far.
(while rending the gif found 1 panic :sweat_smile: )

PS: Is there a way to serialize to a `nu` format?

**Comment by fdncred** [comment]
I think I figured out my configuration issue. But now I'm getting this when I type `:try` after `$nu | explore`.
```
:trythread 'main' panicked at 'Trying to access position outside the buffer: x=161, y=7, area=Rect { x: 0, y: 0, width: 156, height: 47 }', /Users/fdncred/.cargo/registry/src/github.com-1ecc6299db9ec823/tui-0.19.0/src/buffer.rs:208:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

And, oh wow! that `:config` thing is rad!

> PS: Is there a way to serialize to a nu format?

You can try ` | to nuon` but there are some things that don't serialize to nuon I think, like maybe blocks and closures.

**Comment by rgwood** [comment]
That `:config` feature is promising :)

**Comment by fdncred** [comment]
I agree that `:try` mode in particular is quite a bit more unstable now.
Screenshot 2022-12-08 at 6 34 36 AM

**Comment by zhiburt** [comment]
Must be better now I believe;

Let me now of any issues.

**Comment by zhiburt** [comment]
Just wanna highlight the idea behind `:config`.
Is that you can make a config and then `copy & paste` it into your own config.

Still not copy pastable but almost.

download (24)

**Comment by fdncred** [comment]
Just tried going thought `:config` and changing a bunch of settings. Then did `:config-show` and when I did `:nu to nuon` I got this
image

**Comment by zhiburt** [comment]
> Just tried going thought `:config` and changing a bunch of settings. Then did `:config-show` and when I did `:nu to nuon` I got this

😥 

Could you run it with `RUST_BACKTRACE=1`?

**Comment by fdncred** [comment]
> Could you run it with RUST_BACKTRACE=1?

i can't break it now. LOL

**Comment by zhiburt** [comment]
Hi @fdncred, have you found that issue since?

I tend to believe I've just finished refactorings.

**Comment by fdncred** [comment]
@zhiburt does it cache the settings somewhere? Notice my config at the left and `:config-show` at the right. all the padding items are 10 (which are my old settings) but i have changed that and can't get it to display how they're set.
image

**Comment by fdncred** [comment]
I've also got into a weird mode with `:nu $nu` where I can't use the arrow keys.

1. :nu $nu
2. hit enter
3. arrow down to scope's {record 5 fields}
4. hit enter
5. it draws the next record view right but the cursor is already in cursor/interact mode and i cannot move it up or down with the arrow keys. if i hit escape it unselects the column, then i hit enter again, and the column is selected but i cannot use the arrow keys.

**Comment by zhiburt** [comment]
> Does it cache the settings somewhere

Sort of.
It just keep it in memory it just keep it in memory.

Initially the idea was that we tweak it by `:config` and then call `:config-show` then `:nu to nuon` and copy & paste it on our own.

**Comment by fdncred** [comment]
> It just keeps it in memory.

No, I meant between sessions. So, it's getting that value from somewhere, I just don't know where.

**Comment by zhiburt** [comment]
> I've also got into a weird mode with :nu $nu where I can't use the arrow keys.

Must be fixed.

> No, I meant between sessions. So, it's getting that value from somewhere, I just don't know where.

In case you update your config by hand and check `config-show` afterwards I don't think it will recognize the change.
Right?

**Comment by fdncred** [comment]
> Right?

Right. I don't expect it to re-read after I've changed it and explore was already open, but if I open it again, it should see the values. That's what wasn't working. Things seem to be working fine now.

**Comment by fdncred** [comment]
I think I'm ready to land this one @zhiburt. How do you feel about it?

**Comment by fdncred** [comment]
@zhiburt I just saw one thing that needs to be added. The default_config.nu needs to be updated with the explore default configurations. Can you please add those?

**Comment by zhiburt** [comment]
> The default_config.nu needs to be updated with the explore default configurations

So I've update it though didn't check even for syntax mistakes... :disappointed: 
And it might not totally correspond to some default values set in code. (though it likely should just didn't verified it as I said alreadt)

**Comment by fdncred** [comment]
> Look it breaks somethings

@zhiburt I edited the config part. I think these errors are because quotes are not required except for around hex colors like `#00FF00`

**Comment by zhiburt** [comment]
@fdncred

**Comment by rgwood** [comment]
Nice job @zhiburt!

I'm taking a closer look at `explore` now. I would like to cut down on the number of configuration options if possible; I think that it would be good to ship with fewer configuration options, at least until `explore` is more mature and we know how people will use it. Some questions:

1. Is it OK if I remove the `exit_esc` config? I would like it to always be true. But maybe vim users feel differently?
2. Is it OK if I remove the 4 `padding_*` settings? I don't think these will be commonly modified
3. Do you think we need the `show_cursor` and `turn_on_cursor_mode` settings?

There are also a lot of color settings - I wonder if we can cut down on the number of those, maybe by combining some or by inheriting settings from the general Nushell config. I'll try to look into that

**Comment by zhiburt** [comment]
> I would like to cut down on the number of configuration options if possible;

You can remove all the options from the config and it will use the set defaults.
So we can just remove them from sample configuration file.

> Do you think we need the `show_cursor` and `turn_on_cursor_mode` settings?

`show_cursor` yes
`turn_on_cursor_mode` it's not related to a configuration.

**Comment by rgwood** [comment]
> So we can just remove them from sample configuration file.

They still show up in `:config` and we still need to test with multiple values though. I think 32 configuration options is too many:

image

**Comment by fdncred** [comment]
@zhiburt you've done exactly what we asked for, thank you for that! please don't be mad with us asking for change after change. we're just so happy with this that we want our users to have the absolute perfect user experience. people see explore and it blows their minds, then they come back and say, "what if it did this" or "what if it did that", which is an excellent response. anything that cause this much interest is a great feature to have. so, thanks for that.

after thinking about this a bit more, i like most of @rgwood's points. here's the main one that i resonate with. when launching explore, the user shouldn't have "color-shock", meaning they should see colors that they've already configured nushell with and not be shocked with other colors that they don't know where they came from. there may be room for a few more since explore implements things that nushell by itself does not. so, what that means, is we want to be able to use nushell's existing colors everywhere possible.

as an example, here's what my `ls` output looks like.
Screenshot 2022-12-17 at 2 59 33 PM
so, 
- the lines in explore should be these colors.
- the headers in table and record mode should be the same colors as the `ls` output header.
- the datatypes like filesize, dates, filenames, ints, decimals, etc, should be the same color as i have configured

so, every place we can use an existing nushell color, we can remove that explore color config setting. What do you think about this?

**Comment by rgwood** [comment]
> @zhiburt you've done exactly what we asked for, thank you for that!

Agreed, `explore` is very cool 👍

**Pull request merged**
