### PR TITLE
resolving external highlight should take current PATH into account

### PR DESCRIPTION
**Pull request by crides**
# Description

When resolving external commands, the current `PATH` was not taken into account. 

# User-Facing Changes

# Tests + Formatting

# After Submitting

### CODE REVIEW

**Comment by fdncred** [comment]
I don't really understand what this is doing different. Can you post a before and after screenshot?

I already have executables that are in the current directory highlighted as found. Yellow is my found color and this src folder isn't in my path.
image

**Comment by crides** [comment]
The problem is with modifying the PATH. Previously any custom modifications will not show up until you do a nested shell of some kind

**Comment by fdncred** [comment]
> The problem is with modifying the PATH. Previously any custom modifications will not show up until you do a nested shell of some kind

I'm sorry but I'm not following what you mean. Do you have an example that shows what you're describing?

**Comment by fdncred** [comment]
Here's a simple thing I'm trying to do. Use a shell script to call bash's version of `ps` then redirect it to nushell's stdin.
```nushell
❯ open cpu.sh
#!/usr/bin/env bash

ps | nu --stdin -c ' | detect columns'
```
That script gets highlighted as external found with `./cpu.sh` as long as I've done `chmod +x cpu.sh` on it.

**Comment by crides** [comment]
not sure where you got the cwd from, but try any executable that's not in the system default PATH, e.g. `~/.local/bin`, `~/.cargo/bin`

**Comment by fdncred** [comment]
You can see thst `/home/fdncred/src/forks` is not in my path.
image

However, neither `ghostty` nor `lvim` show up as found.
image

Why do you think this is happening like this? (gonna try your PR to see if it fixes this)

**Comment by fdncred** [comment]
Looks like it finds them with your PR. Nice work and thanks for taking the time to explain it to me!
image

**Pull request merged**
