### PR TITLE
make `date format` supports locale

### PR DESCRIPTION
**Pull request by WindSoilder**
# Description
The idea comes from discord message: https://discord.com/channels/601130461678272522/614593951969574961/1007130690472640632

> is it expected that nu seems to completely ignore locale settings? like even for things like date format '%c' which should be in the system locale

I think this is useful to myself, so I'm trying to implement it.

As title, fix `%x`, `%X`, `%c` behavior to make them works more friendly.

Quickly reference for %x, %X, %c:
```
╭───┬───────────────┬──────────────────────────┬─────────────────────────────────────────────────────────╮
│ # │ Specification │         Example          │                       Description                       │
├───┼───────────────┼──────────────────────────┼─────────────────────────────────────────────────────────┤
│ 0 │ %x            │ 08/12/22                 │ Locale's date representation (e.g., 12/31/99).          │
│ 1 │ %X            │ 23:16:17                 │ Locale's time representation (e.g., 23:13:48).          │
│ 2 │ %c            │ Fri Aug 12 23:16:17 2022 │ Locale's date and time (e.g., Thu Mar 3 23:05:25 2005). │
╰───┴───────────────┴──────────────────────────┴─────────────────────────────────────────────────────────╯
```

## Notes
~1. Actually I have no idea how to add tests to test for the behavior, because we can't make any assume about locale in CI machine.~ (It's resolved, thanks for the https://github.com/nushell/nushell/pull/6085)
~2. I'm failed to get a short flag for `--locale`, because `-l` is used.~

# Tests

Make sure you've done the following:

- [ ] Add tests that cover your changes, either in the command examples, the crate/tests folder, or in the /tests folder.
- [ ] Try to think about corner cases and various ways how your changes could break. Cover them with tests.
- [ ] If adding tests is not possible, please document in the PR body a minimal example with steps on how to reproduce so one can verify your change works.

Make sure you've run and fixed any issues with these commands:

- [X] `cargo fmt --all -- --check` to check standard code formatting (`cargo fmt --all` applies these changes)
- [X] `cargo clippy --workspace --features=extra -- -D warnings -D clippy::unwrap_used -A clippy::needless_collect` to check that you're using the standard code style
- [X] `cargo test --workspace --features=extra` to check that all the tests pass

### CODE REVIEW

**Comment by fdncred** [comment]
Forgive me @WindSoilder but I'm testing this an missing the point.
image

Is nothing changing for me because the default is en-US and that's where I live?

**Comment by x3rAx** [comment]
> Actually I have no idea how to add tests to test for the behavior, because we can't make any assume about locale in CI machine.

That will be possible when PR https://github.com/nushell/nushell/pull/6085 is merged. We then have the ability to call the `nu!` macro with a `locale: "..."` option. The only requirement for this to work is that the code you want to test uses `nu_utils::get_system_locale()` to get the system locale.

But if I interpret the description of `%x`, `%X` and `%c` correctly, it should already respect the system locale and ICD rather fix that than adding another flag, that seems redundant to me.

**Comment by WindSoilder** [comment]
> Is nothing changing for me because the default is en-US and that's where I live?

Yeah, I think that's the reason, if you change `LANG` variable, something will be different.

> That will be possible when PR https://github.com/nushell/nushell/pull/6085 is merged. We then have the ability to call the nu! macro with a locale: "..." option. The only requirement for this to work is that the code you want to test uses nu_utils::get_system_locale() to get the system locale.
But if I interpret the description of %x, %X and %c correctly, it should already respect the system locale and I'd rather fix that than adding another flag, that seems redundant to me.

Thanks for your input, I think that's a good idea, we can just do it without introducing extra `--local` flag, which only affects `%x`, `%X`, `%c`

**Comment by WindSoilder** [comment]
I need some time to work on it, mark as draft for now

**Comment by fdncred** [comment]
thanks

**Pull request merged**
