### PR TITLE
don't allow `save` command to save both stdout and stderr to the same file

### PR DESCRIPTION
**Pull request by WindSoilder**
# Description
It's not a good idea to save `stdout` and `stderr` to the same file from `save` command directly.

Because it saves `stdout` and `stderr` in different thread, which leads to in-consistent output.  As replace, we can use `o+e` redirection to fix the issue

# User-Facing Changes
```
❯ do -i { "aa" } | save foo.txt -e foo.txt
Error:   × input and stderr input to same file
   ╭─[entry #3:1:1]
 1 │ do -i { "aa" } | save foo.txt -e foo.txt
   ·                                  ───┬───
   ·                                     ╰── can't save both input and stderr input to the same file
   ╰────
  help: you should use `o+e> file` instead
```

# Tests + Formatting

# After Submitting

### CODE REVIEW

**Comment by amtoine** [comment]
@WindSoilder
this *ratatouille* typo issue should have been addressed in bdb09a9a00cf559a036073ef306aefa04787ac1b, could you try to merge again the `main` branch in here to see if the CI passes again? :yum: 

maybe we'll have to ping a few other PRs if that's the way to make the CI green again :open_mouth:

**Comment by WindSoilder** [comment]
@amtoine Thank you for typo fixing!

**Review by amtoine — APPROVED** [review]
looks good to me and sensible, thanks @WindSoilder :blush:

**Comment by amtoine** [comment]
> @amtoine Thank you for typo fixing!
>
:blush: 

yeah the CI was a bit capricious these days :eyes: :laughing:

**Pull request merged**
