### PR TITLE
adds a `config reset` command

### PR DESCRIPTION
**Pull request by merelymyself**
# Description

Related to #6041. I'll admit this isn't the cleanest solution (because now the default_config can't be found in docs/!), but this should definitely allow the package to be published. 

# Tests

Make sure you've done the following:

- [ ] Add tests that cover your changes, either in the command examples, the crate/tests folder, or in the /tests folder.
- [ ] Try to think about corner cases and various ways how your changes could break. Cover them with tests.
- [ ] If adding tests is not possible, please document in the PR body a minimal example with steps on how to reproduce so one can verify your change works.

Make sure you've run and fixed any issues with these commands:

- [ ] `cargo fmt --all -- --check` to check standard code formatting (`cargo fmt --all` applies these changes)
- [ ] `cargo clippy --workspace --features=extra -- -D warnings -D clippy::unwrap_used -A clippy::needless_collect` to check that you're using the standard code style
- [ ] `cargo test --workspace --features=extra` to check that all the tests pass

### CODE REVIEW

**Comment by fdncred** [comment]
I'm not a fan of duplicating the default config files.

**Comment by merelymyself** [comment]
Nor am I, really. Random thought, but do you think it's possible to move the config files fully into nu_command or some other crate? Or does there have to be a copy in `docs/`?

**Comment by fdncred** [comment]
I have two thoughts.

1. Do you not think my suggestion in your original PR would work?
2. I'm not opposed to moving the sample_config folder to nu-command, as long as all our code can reach it from there upon publishing.

I'm not really sure how publishing works but I know it has a `--dry-run` flag that we can perhaps test out any changes with.

**Comment by merelymyself** [comment]
@fdncred -
1. I did try your suggestion at first, but what the env variable registered as was the nu-command crate root, i.e. `nushell/crates/nu-command/`, so the same issue still applied.
2. I'm hoping this should just work, but I'll also try to find more potential points where this can break things.

**Comment by fdncred** [comment]
ok, sounds good. thanks for jumping on this so fast.

**Comment by fdncred** [comment]
@jntrnr How do you propose we test this?

**Comment by nibon7** [comment]
I think this PR may be useful for #6160.

**Comment by merelymyself** [comment]
For what it's worth, I set the `Cargo.toml`s to the last available dependencies on crates.io and tried publishing with `--dry-run`. There were no errors in compilation until the newly added functions were called, which don't exist in the current `0.66.0` dependencies. I can't be fully certain there will be no errors when actually publishing it, but it seems fairly unlikely to me.

**Pull request merged**
