### PR TITLE
`str collect` => `str join`

### PR DESCRIPTION
**Pull request by dandavison**
In a recent [Discord thread](https://discord.com/channels/601130461678272522/615329862395101194/1017764714316582933) in `#design-discussion` it was suggested that `str join` would be a better name than `str collect`, and this met with quite a lot of agreement. Motivations include it being a more intuitive name to the average user, and consistency with `path join`.

This PR:
- Introduces `str join` with the same behavior as `str collect` had
- Replaces all occurrences of `str collect` with `str join` (except for in the `str_/collect.rs` file itself)
- ~~Deprecates `str collect` (i.e. it becomes an error, but prints out the deprecation message pointing to `str join`.~~ **UPDATE**: Nope, it turned out that Python virtualenv activation calls `str collect`!

```
~ 〉["a" "b"] | str join
ab
~ 〉["a" "b"] | str join "-"
a-b
```

(Reviewers: the global-find-and-replace commit is separated from the others so it might be easier to look at individual commits.)

- [x] Documentation PR: https://github.com/nushell/nushell.github.io/pull/602

# Tests
- [x] Changed `str collect` to `str join` in all tests. `str join` now has all the coverage `str collect` had and `str collect` has no coverage. 

# Checklist
Make sure you've run and fixed any issues with these commands:

- [x] `cargo fmt --all -- --check` to check standard code formatting (`cargo fmt --all` applies these changes)
- [x] `cargo clippy --workspace --features=extra -- -D warnings -D clippy::unwrap_used -A clippy::needless_collect` to check that you're using the standard code style
- [x] `cargo test --workspace --features=extra` to check that all the tests pass

### CODE REVIEW

**Comment by dandavison** [comment]
The test failure is genuine: nu's `str collect` is called in Python virtualenv activation: https://github.com/pypa/virtualenv/blob/b85542c31ca8afcff317e618da434f59fa06d122/src/virtualenv/activation/nushell/activate.nu#L43

That may mean, if we still want to do this, we should not actually disable `str collect` for now, but:

1. Introduce `str join` as an alias
2. Change the docs to use `str join` everywhere
3. Document that `str collect` is deprecated
4. Remove `str collect` at some point in the future when versions of virtualenv that refer to it are considered old.

**Comment by rgwood** [comment]
This is a great first PR, thanks!

I'm not very familiar with the failing virtualenv tests. IIRC @kubouch is the virtualenv expert; if you need any help he might be the person to ask.

**Comment by dandavison** [comment]
Right! I think credit due to @kubouch for putting the Python virtualenv test in place and preventing me from creating a pretty bad experience for users of nu and python.

I've updated this PR to revert the final commit that got rid of `str collect` (i.e. via `nu_protocol::ShellError::DeprecatedCommand`).

So, if you want to accept this PR, then nu will have both `str collect` and `str join`, but the `str` help will tell users that they should prefer `join`. But no worries if you don't want to go this route!

```
nushell/nushell str-join 〉str --help
...
Subcommands:
...
  str collect - 'str collect' is deprecated. Please use 'str join' instead.
...
  str join - Concatenate multiple strings into a single string, with an optional separator between each
```

**Comment by stormasm** [comment]
@dandavison @kubouch is out of town this weekend so when he gets back probably early next week he can advise us more on this point...

thank you for submitting the PR so quickly... 😄

**Comment by CBenoit** [comment]
Nice :+1: 
`collect` in Rust is doing something different so I was unsure of what `str collect` did until I read the documentation.

**Comment by stormasm** [comment]
@CBenoit thank you a fine point and yet another reason that the word "join" IMHO is probably a much better choice of words...

**Comment by kubouch** [comment]
I like `str join` instead of `str collect`. And I think it's a good practice to keep both commands working at first as it gives us a time to port virtualenv and other integrations. We can open a new PR right after the release that removes `str collect`.

**Pull request merged**
