### PR TITLE
Rework output formatting / colorization of `ls` and `find`

### PR DESCRIPTION
**Pull request by panicbit**
# Description

Context: https://github.com/nushell/nushell/issues/6315

This PR adds a mechanism for commands to optionally format list stream values for presentation to the user.
`ls` and `find` (partially) have been ported to this new mechanism.
The reason for this change is that `find` previously added colorization by modifying the pipe stream, making subsequent processing difficult, as can be seen in https://github.com/nushell/nushell/pull/6220.
Furthermore, hardcoding colorization for specific commands using metadata (like it has been done for `ls`) is not very flexible, does not scale well, and requires the logic for formatting to be in the wrong place (i.e. the `table` viewer).

As a byproduct, this PR also fixes [some bugs in `find`](https://github.com/nushell/nushell/issues/6315#issuecomment-1214371993).

# Tests

```
[[name]; ["hello"] ["world"] ["foo"] ["bar"]] | each {$in} | find ll | get 0.name | into binary
```
Should print the same as
```
"hello" | into binary
```
i.e. there shouldn't be any ansi escapes included in the binary string.

Old output (bad):
grafik

New output (good):
grafik

(The `each {$in}` is just there to turn the table into a list stream internally. `find` only highlights list streams properly atm.)

Additionally, the output of
```
[[name]; ["hello"] ["world"] ["foo"] ["bar"]] | each {$in} | find ll
```
should still be colorized:
grafik

Make sure you've done the following:

- [ ] Add tests that cover your changes, either in the command examples, the crate/tests folder, or in the /tests folder.
- [ ] Try to think about corner cases and various ways how your changes could break. Cover them with tests.
- [x] If adding tests is not possible, please document in the PR body a minimal example with steps on how to reproduce so one can verify your change works.

Make sure you've run and fixed any issues with these commands:

- [x] `cargo fmt --all -- --check` to check standard code formatting (`cargo fmt --all` applies these changes)
- [x] `cargo clippy --workspace --features=extra -- -D warnings -D clippy::unwrap_used -A clippy::needless_collect` to check that you're using the standard code style
- [x] `cargo test --workspace --features=extra` to check that all the tests pass
    - there is a failing test, but it was already failing before:
    ```
    ---- conversions::into::string::test::test_examples stdout ----
    input: 5 | into string -d 3
    result: String { val: "5,000", span: Span { start: 4, end: 15 } }
    done: 893.601µs
    thread 'conversions::into::string::test::test_examples' panicked at 'the example result is different to expected value: String { val: "5,000", span: Span { start: 4, end: 15 } } != String { val: "5.000", span: Span { start: 0, end: 0 } }', crates/nu-command/src/example_test.rs:139:25
    note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
    ```

### CODE REVIEW

**Comment by fdncred** [comment]
nice work @panicbit. so appreciate you working on this. we're pretty close to a release 8/16 so we may wait to land this until after it. thanks.

**Comment by panicbit** [comment]
It will need some follow-up PRs after this anyway to fully remove ansi escapes from `find` and also to remove stripping of ansi codes from the filesystem commands. :+1:

**Comment by andrasio** [comment]
I'd feel more comfortable if you can do the PR with the ability for commands to format their list stream values for presentation.

Then in other separate PRs using them for improving the 'find' command and the like.

**Comment by panicbit** [comment]
I'll split this PR then

**Comment by andrasio** [comment]
Thank you! @panicbit Yes. I'd be nice a PR per command after this general abstraction one.

**Comment by fdncred** [comment]
@panicbit Since we have default ls_colors if use_ls_colors is true, I'm wondering if we can construct some tests with these commands. What do you think?

**Comment by panicbit** [comment]
@fdncred I have no idea, but I'll look into it

**Comment by panicbit** [comment]
Here's the PR for just the new formatting mechanism: https://github.com/nushell/nushell/pull/6325

**Comment by panicbit** [comment]
Closing this in favor of the new PRs

**Pull request closed without merging**
