### PR TITLE
Parameter defaults to `$nu.scope.commands`

### PR DESCRIPTION
**Pull request by bobhy**
Show parameter defaults in scope command signature, where they're available for display by help.
per #8928.

# Description

Adds field `parameter_default` to `$nu.scope.command.signatures`. 
Populates with defaults for optional positionals.
WIP: waiting for #8940, then can also populate default for named flags.
Does not populate default for rest positionals; though these have a default field in signature, parser disallows specifying in the `def`.

```
〉def t1 [a:int b?:float=1.23 ...rrr:string --flag1:string --flag2:float=4.56] {true}
〉$nu.scope.commands | where name == 't1' | get signatures.0.any | reject short_flag description custom_completion
╭───┬────────────────┬────────────────┬──────────────┬─────────────┬───────────────────╮
│ # │ parameter_name │ parameter_type │ syntax_shape │ is_optional │ parameter_default │
├───┼────────────────┼────────────────┼──────────────┼─────────────┼───────────────────┤
│ 0 │                │ input          │ any          │ false       │                   │
│ 1 │ a              │ positional     │ int          │ false       │                   │
│ 2 │ b              │ positional     │ number       │ true        │              1.23 │
│ 3 │ rrr            │ rest           │ string       │ true        │                   │
│ 4 │ flag1          │ named          │ string       │ true        │                   │
│ 5 │ flag2          │ named          │ decimal      │ true        │                   │
│ 6 │                │ output         │ any          │ false       │                   │
╰───┴────────────────┴────────────────┴──────────────┴─────────────┴───────────────────╯

```
# User-Facing Changes

New field in `$nu.scope.commands.signatures`, should only break scripts that had an exhaustive list of the signature fields.

# Tests + Formatting

# After Submitting

### CODE REVIEW

**Comment by bobhy** [comment]
Help shows default value for optional positionals, using nu-highlight (woo-hoo!).  Shows whether a named flag has a default, but shows placeholder 'coming soon' as the value, pending update to type of those defaults from @MariaSolOs .

**Comment by amtoine** [comment]
looks there are a bunch of commits that do not belong to this PR, doesn't it? :thinking:

**Comment by bobhy** [comment]
Defaults are now captured in `$nu.scope.commands` and are displayed (with highlighting) in builtin help.
However, both plugins and help_completer invoke functions from core builtin help but don't have the context to support highlighting (or even standard `Type::Value.into_string` in the case of plugins).  I made the minimal changes necessary to compile and pass tests for the mainline scenario.  
Ready for review with those caveats.

**Comment by MariaSolOs** [comment]
> looks there are a bunch of commits that do not belong to this PR, doesn't it? 🤔

Yeah, I think a rebase here would be cleaner.

**Comment by bobhy** [comment]
I was having some problems with my local repo, am rebuilding everything now.  Moving back to draft status in the meantime...

**Comment by bobhy** [comment]
I do not know how to rescue this PR.  Closing this one, reopened as #9104

**Pull request closed without merging**
