### PR TITLE
Path Command Enhancement Project

### PR DESCRIPTION
**Pull request by kubouch**
# Description

The aim of this PR is to add a couple of options enhancing the capabilities of the `path` subcommands. More specifically, it makes it easier to mass-rename files and their locations without an excessive use of `build-string` chains. I found both nu and traditional Unix tools (such as dirname or basename) too verbose when I was encoding and moving tens of thousands images in tens of different folders all over the place.

# Changes

## path basename
- [x]  Add `--replace <string>` option to replace the basename instead of returning it
  - (e.g., `echo foo/bar/baz.txt | path basename -r spam.md` would return `foo/bar/spam.md`)
- [x] Examples

## path dirname
- [x] Add `-n <int>` option to specify how many levels up to return
  - (e.g., `echo foo/bar/baz.txt | path dirname -n 2` would return `foo`)
- [x]  Add `--replace <string>` option to replace the dir instead of returning it (respecting the `-n` option)
  - (e.g., `echo foo/bar/baz.txt | path dirname -n 2 -r eggs` would return `eggs`)
- [x] Examples
- [x] Handle num_levels < 0 properly -- current message is good enough

## path extension
- [x]  Add `--replace <string>` option to replace the extension instead of returning it
  - (e.g., `echo test.txt | path extension -r md` would return `test.md`)
- [x] Examples

## path filestem
- [x]  Add `--replace <string>` option to replace the filestem instead of returning it
  - (e.g., `echo foo/bar/baz.txt | path basename -r spam` would return `foo/bar/spam.txt`)
- [x] Add an option to spell out the suffix literally to cover cases like `.tar.gz`
- [x] Add an option to spell out the prefix literally to cover cases like `out_<whatever>`
- [x] Examples
- [x] Review for possible cleanup 

## misc
- [x] Add integration tests to cover edge cases
- [x] Go through descriptions and examples and make sure they're consistent
- [x] Replace `...args: optionally operate by path` with `...args: optionally operate by column path` in subcommands desctiprions
- [x] Fix failing tests on Windows
  - solution: generate different set of examples on Windows
- [x] Fix broken expand on Windows -- the command is a bit problematic but I'll leave that for further discussion/PR
- [x] Return path from subcommands when appropriate (e.g., expand, --replace options)

### CODE REVIEW

**Comment by fdncred** [comment]
These sounds cool! Thanks!

**Comment by jonathandturner** [comment]
Seconded! I like these

**Comment by kubouch** [comment]
Alright, path handling turned out to be a little rabbit hole. The commands mostly respect the `std::path`'s way of resolving paths which is not very intuitive at times (for example, `.` is automatically resolved while `..` is not). Also, there are some limitations in the `path expand` command: most notably, the `~` resolves as home only with `/` separator but not `\` which can lead to strange bugs.

I think the path handling would deserve some consistency revamp so it behaves the same way on all platforms but I'll leave it for a further discussion / PR.

**Comment by jonathandturner** [comment]
This is great, thanks for putting it together!

**Comment by jonathandturner** [comment]
and agreed, we'll want to circle back and improve the path handling a bit more. We can do that in a future PR and land this one, as I think these improvements stand on their own.

**Pull request merged**
