### PR TITLE
Remove use of ExtractType in deserialize_any

### PR DESCRIPTION
**Pull request by est31**
This removes use of the ExtractType trait from the deserialize_any function by changing the code to never call it. The ultimate goal is to remove use of specialization.

ExtractType and its use of specialization exists to allow deserialization of cli arguments. For each command, there is a struct with some members and serde's Deserialize trait is being derived. This is the argument struct for the mv command:

```Rust
#[derive(Deserialize)]
pub struct MoveArgs {
    pub src: Tagged<PathBuf>,
    pub dst: Tagged<PathBuf>,
}
```

The cli arguments input by an user are being converted from a `CallInfo` struct to that command-specific struct using `ConfigDeserializer`. The only uses of the `ExtractType` trait in the codebase are in its `Deserializer` implementation where they help avoiding having to use serde beyond iterating over the fields of the command-specific structs: any field of a cli param is expected to be readable from a `Tagged<Value>`.

In order to reduce usage of `ExtractType`, this PR brings more data into format understandable by serde.

The command  `rg "\(Deserialize\)][^}]*\}" -U src/commands/*` provides a list of command-param-structs that we have to handle. The field types can be extracted using `rg "\(Deserialize\)][^}]*\}" -U src/commands/* | rg ": .*: " | sed 's/^.*: //' | sort | uniq`:
```
bool,
Option<Tagged<PathBuf>>,
Option<Tagged<String>>,
Option<(Tagged<String>, Tagged<Value>)>,
Tagged<bool>,
Tagged<i64>,
Tagged<PathBuf>,
Tagged<String>,
value::Block,
Vec<Tagged<PathBuf>>,
Vec<Tagged<String>>,
```
Previously, all these types were parsed from `Tagged<Value>` instances using the `ExtractType` trait. Now, serde with its outside-to-inside model is being used to handle the logic to deserialize Vec<>, bool, Option<>, tuples, but we still defer to `ExtractType` when something is encountered that doesn't fit into the serde data model like Tagged or Block. Handling these via serde as well is still possible and subject of future PRs.

Useful commands for testing:
```
open tests/fixtures/formats/sample.bson | pick _id root // tests vec
config --set [specialization false] // tests Option containing a tuple
```

cc #362

### CODE REVIEW

**Comment by wycats** [comment]
@est31 Honestly, you know serde better than I do. Thanks for this work and all of your work getting us on stable!

**Comment by androbtech** [comment]
`config --set [specialization false] // tests Option containing a tuple`

Thoughts on #627 ? @est31

**Comment by est31** [comment]
@androbtech yeah this is likely a regression caused by this PR. Sorry for the inconvenience! Will try to get a fix done by tomorrow.

**Comment by est31** [comment]
Hmmm nevermind, it wasn't this PR but #579.

**Pull request merged**
