### PR TITLE
str-expand: update bracoxide to v0.1.2, fixes #9913

### LINKED ISSUE #9913: str-expand bug: bracoxide ignores single dots.
### Describe the bug
```
╭───┬─────────────────────────────────────────────╮
│ 0 │ ~/Downloads/archlinux-..20230801-x86_64.iso │
│ 1 │ ~/Downloads/Win10_22H2_French_x64v1.iso     │
╰───┴─────────────────────────────────────────────╯
```
### How to reproduce

1. `'~/Downloads/{archlinux-2023.08.01-x86_64,Win10_22H2_French_x64v1}.iso' | str expand`

### Expected behavior

```
╭───┬─────────────────────────────────────────────╮
│ 0 │ ~/Downloads/archlinux-2023.08.01-x86_64.iso │
│ 1 │ ~/Downloads/Win10_22H2_French_x64v1.iso     │
╰───┴─────────────────────────────────────────────╯
```

### Screenshots

_No response_

### Configuration

| key                | value                                                            |
| ------------------ | ---------------------------------------------------------------- |
| version            | 0.83.0                                                           |
| branch             | makepkg                                                          |
| commit_hash        | a33b5fe6ce97b5e9fe8a774c13e783ed65c1b591                         |
| build_os           | linux-x86_64                                                     |
| build_target       | x86_64-unknown-linux-gnu                                         |
| rust_version       | rustc 1.71.0 (8ede3aae2 2023-07-12) (Arch Linux rust 1:1.71.0-1) |
| cargo_version      | cargo 1.71.0                                                     |
| build_time         | 2023-07-26 01:10:19 +00:00                                       |
| build_rust_channel | release                                                          |
| allocator          | standard                                                         |
| features           | dataframe, default, extra, sqlite, trash, which, zip             |
| installed_plugins  |                                                                  |

### Additional context

The problem is pretty basic. Should not take long. I'm working on it now.

### PR DESCRIPTION
**Pull request by atahabaki**
Fixes: #9913 

Changes:

- updated crate bracoxide from v0.1.1 to v0.1.2

### CODE REVIEW

**Review by amtoine — DISMISSED** [review]
simple enough change :yum: 


could you add a few tests to make sure the behaviour stays correct in the future?

for instance with commands and outputs from https://github.com/nushell/nushell/issues/9913#issuecomment-1665268254

**Comment by atahabaki** [comment]
I don't think it'll ever fail again, unless `bracoxide` crate's version is less than `0.1.2`. I added test cases to `bracoxide`.

Anyways, i added test cases. I'm not exactly sure, I've written them in the right fashion.

**Review by amtoine — COMMENTED** [review]
i've run the following commands
```nushell
cargo run -- -n -c '("{a.b.c,d}" | str expand) == [a.b.c, d]'
cargo run -- -n -c '("{1.2.3,a}" | str expand) == [1.2.3, a]'
cargo run -- -n -c '("{a-1.2,b}" | str expand) == [a-1.2, b]'
```
on the tip of the current `main` branch and then on the tip of this PR branch.

i get
```
true
false
false
```
and then
```
true
true
true
```

so the first does not capture the changes in this PR but the two others will :partying_face: 

i think we can leave these examples :relieved:

**Review by sholderbach — APPROVED** [review]
Thanks for the thorough testing!

**Pull request merged**
