### PR TITLE
Allow duration to be added to date

### LINKED ISSUE #14294: Can add duration to date, but not date to duration
### Describe the bug

Best just reproduced:

### How to reproduce

```nushell
(date now) + 1hr
# => Sat, 9 Nov 2024 23:44:39 -0500 (in an hour)
1hr + (date now)
# => Error: addition is not supported between duration and date
```

### Expected behavior

Commutative property of addition to hold true:

(A + B) == (B + A)

### Configuration

| key                | value                                    |
| ------------------ | ---------------------------------------- |
| version            | 0.99.2                                   |
| major              | 0                                        |
| minor              | 99                                       |
| patch              | 2                                        |
| branch             |                                          |
| commit_hash        | d6944b348fa508b7fb7ff7c7614a9d0860e9a109 |
| build_os           | linux-x86_64                             |
| build_target       | x86_64-unknown-linux-gnu                 |
| rust_version       | rustc 1.80.1 (3f5fd8dd4 2024-08-06)      |
| rust_channel       | 1.80.1-x86_64-unknown-linux-gnu          |
| cargo_version      | cargo 1.80.1 (376290515 2024-07-16)      |
| build_time         | 2024-11-03 07:47:12 -05:00               |
| build_rust_channel | release                                  |
| allocator          | mimalloc                                 |
| features           | default, sqlite, trash                   |
| installed_plugins  |                                          |

### PR DESCRIPTION
**Pull request by NotTheDr01ds**
# Description

Fixes #14294 - Turned out to be a whole lot easier than I expected, but please double-check me on this, since it's an area I haven't been in before.

# User-Facing Changes

Allow date to be added to a duration type.

# Tests + Formatting

Tests added:

* Duration + Date is allowed
* Duration - Date is not allowed

- :green_circle: `toolkit fmt`
- :green_circle: `toolkit clippy`
- :green_circle: `toolkit test`
- :green_circle: `toolkit test stdlib`

# After Submitting

N/A

### CODE REVIEW

**Comment by fdncred** [comment]
I think that seems correct. Is there any reason why we shouldn't allow this?

**Comment by NotTheDr01ds** [comment]
I'm going to add tests before I bring it out of draft, but I'd like to fix the `into datetime` tests first.  It's not just one that's failing.

**Comment by fdncred** [comment]
Feel free to add it to the [agenda](https://hackmd.io/o-cND1eKS0aK57vuY2yKQQ)

**Comment by IanManske** [comment]
> @fdncred I've added tests and brought this out of draft. Maybe we ask on Wednesday's call if anyone can remember whether or not this was intentionally disallowed originally?

Seems like an oversight, I don't see why it shouldn't be allowed. Thanks for the catch and PR.

**Pull request merged**
