### PR TITLE
chore: rename uid to user column in ls --long

### PR DESCRIPTION
**Pull request by Mehrbod2002**
Fixes: #9389

### CODE REVIEW

**Comment by amtoine** [comment]
fix simple enough :ok_hand: :yum: 

you might have some tests involving the old name to fix :wink:

**Review by amtoine — APPROVED** [review]
thanks @Mehrbod2002, this looks great :ok_hand:

**Comment by sholderbach** [comment]
Thanks @Mehrbod2002! Would you mind adding a sentence on the change in the breaking changes section of the release notes? https://github.com/nushell/nushell.github.io/pull/945

**Comment by Mehrbod2002** [comment]
@sholderbach Done .

**Comment by sholderbach** [comment]
Thanks!

**Pull request merged**
