### PR TITLE
Add host env to scope at creation and not before every parsing/evaluation...

### LINKED ISSUE #2981: let-env can't shadow environment variables
**Describe the bug**
Currently, if you use `let-env`, you can create new environment variables but can't seem to override existing environment variables.

**To Reproduce**
```
> let-env CC = clang
> echo $nu.env.CC
gcc
```

**Expected behavior**
I should be able to shadow the environment variables in the current environment.

**Configuration (please complete the following information):**

Run `version | pivot` and paste the output to show OS, features, etc.

```
────┬────────────────────┬──────────────────────────────────────────────────────────────────────────────────────────────────────
 #  │      Column0       │                                               Column1                                                
────┼────────────────────┼──────────────────────────────────────────────────────────────────────────────────────────────────────
  0 │ version            │ 0.26.0                                                                                               
  1 │ branch             │ main                                                                                                 
  2 │ short_commit       │ b1e1dab4                                                                                             
  3 │ commit_hash        │ b1e1dab4cb86d477d226a92480e95f9513055702                                                             
  4 │ commit_date        │ 2021-01-27 07:42:34                                                                                  
  5 │ build_os           │ linux-x86_64                                                                                         
  6 │ rust_version       │ rustc 1.49.0                                                                                         
  7 │ rust_channel       │ stable-x86_64-unknown-linux-gnu (default)                                                            
  8 │ cargo_version      │ cargo 1.49.0                                                                                         
  9 │ pkg_version        │ 0.26.0                                                                                               
 10 │ build_time         │ 2021-01-27 18:19:31                                                                                  
 11 │ build_rust_channel │ release                                                                                              
 12 │ features           │ clipboard-cli, ctrlc, default, directories, dirs, ichwh, ptree, rustyline, term, trash, uuid, which, 
    │                    │ zip                                                                                                  
────┴────────────────────┴──────────────────────────────────────────────────────────────────────────────────────────────────────
```

### PR DESCRIPTION
**Pull request by LhKipp**
Fix #2981

Now it is working as expected.

Example:

```shell
> echo $NUTESTGLOBAL #In fish shell
Hello
> cat test.nu
echo $nu.env.NUTESTGLOBAL
> cargo run #Switch to nushell
Welcome to Nushell 0.26.1 (type 'help' for more info)
> echo $nu.env.NUTESTGLOBAL
Hello
> nu test.nu
Hello
> let-env NUTESTGLOBAL = World
> echo $nu.env.NUTESTGLOBAL
World
> nu test.nu
World
```

### CODE REVIEW

**Comment by LhKipp** [comment]
This PR currently fails at a test, testing the correct behaviour of the ".nu-env" feature living in the directory nu-cli/src/env/*.
Here is a tldr of ".nu-env":

**What env/* is doing**
env/* provides functionality to read and apply variables from a config file located in a directory. Furthermoe the config file can contain a exitscript which gets executed on directory leave. The normal flow of execution is as follows:
1. The user enters a directory with a local config file
2. Nu checks whether the config file is trusted. If it isn't, stop
3. env/* adds the variables from the config file and a exitscript, which is executed when leaving the directory
4. When the user leaves the directory, env/* removes the added variables and executes the exitscript

**How env/* is doing it**
env/* was written before Scope and ScopeFrame was introduced. env/* is managing adding and removing of variables solely on the information of CWD into the environment via `std::env::set_var` directly.

(Security side-note: A file can be marked as trusted by using the command `autoenv trust`. `autoenv trust` computes a hash of the config file and stores a tuple (config-file-path, config-file-hash) in an unencrypted plain text file. I have no clue about security, but I think this solves the problem of the user downloading someone malicious configs (e.G. as part of an open-source-project) into a directory and the user cding into this directory. However if the attacker can manipulate the file with (path, hash) tuples, the method is insecure (but if this happens the user is in trouble anyways I guess). A more secure way (but harder to setup), would be to store a digital signature for each local config file)

**How I think it can improve**
The new logic should leverage Scope and ScopeFrame. It could be as follows:
1. The user enters a directory with a local config file            (Same as before)
2. Nu checks whether the config file is trusted. If it isn't, stop (Same as before)
3. A new ScopeFrame with a marker value of CWD is entered.
4. The config.nu file is sourced. All aliases, defs, variables get added.
5. When the directory is left, the ScopeFrame with marker value of the old CWD is dropped.

(I am not yet sure how the exitscript functionality can be made available to the user. We could add a command like
```shell
# Execute <block> when the current scope is dropped
on-scope-drop <block>
```
)

As soon as env/* would use the new method, I am sure, the test would work.

**Comment by jonathandturner** [comment]
Tagging @wycats, who has also been thinking about autoenv

**Comment by LhKipp** [comment]
#3041 is related

**Comment by wycats** [comment]
@LhKipp my biggest concern with this approach, if I understand it correctly, has to do with callbacks in scripts (and the potential for  long-lived first-class functions). We want to make sure that we don't end up with a mechanism that is so defined by dynamic scope that it would be difficult to lexically scope any part of the mechanism in the future.

Another way to put it is: should the $nu.env (and any future features that are scoped via mechanisms like autoenv) be based on the cwd, or should it be based on the directory that the script is located inside of?

**Comment by LhKipp** [comment]
@wycats Thanks for the feedback.
Are you referring to the following?

> * The user enters a directory with a local config file            (Same as before)
> 
> * Nu checks whether the config file is trusted. If it isn't, stop (Same as before)
> 
> * A new ScopeFrame with a marker value of CWD is entered.
> 
> * The config.nu file is sourced. All aliases, defs, variables get added.
> 
> * When the directory is left, the ScopeFrame with marker value of the old CWD is dropped.

I don't see that much of a difference to what is happening right now.

I think `autoenv` should be purely a feature when navigating interactively in the cli. It should not be triggered by scripts, as it makes reasoning (as you explained) way to complicated. If a script wants to use environment variable defined in a config file, the script should source / import the config file explicitly.

If you are talking about the mistake I made in this PR, where I cloned a scope, instead of allocating a new: It's fixed :)

**Comment by wycats** [comment]
> I think autoenv should be purely a feature when navigating interactively in the cli.

@LhKipp that makes a lot of sense, and should go into our discussion (and hopefully conclusion) about the differences between scripts and the REPL.

**Comment by LhKipp** [comment]
Merged if #3041 gets accepted

**Pull request closed without merging**
