### PR TITLE
Changes release build opt-level

### PR DESCRIPTION
**Pull request by FilipAndersson245**
# Description

I have done some testing with the current performance on Nushell, I have used Nushell to compare som different `opt-level` strategies and I think we should change to the standard `opt-level=3` instead of the current `opt-level='s'`. Changing to 3 would as it seems give roughly **5-8%** better performance. Interestingly is that in most tests `opt-level=2` performed a tiny bit better, I'm unsure if this was due to noise in the setup or something else as `3` enables more optimizations. I think it's wasteful to leave CPU cycles on the table. 

Here are the differences in 
## compile time
dev: 2m 12s,
1:   4m 51s,
2:   5m 11s
3:   5m 12s
's'  4m 25s
'z'  4m 06s

## binary sizes
image

Each runtime test where run 150 times, and had a warmup of 10.
## 1. math_function
| Command | Mean [ms] | Min [ms] | Max [ms] | Relative |
|:---|---:|---:|---:|---:|
| `./nu-1.exe -c "source math_function.nu"` | 330.8 ± 17.3 | 322.1 | 391.4 | 1.00 ± 0.07 |
| `./nu-2.exe -c "source math_function.nu"` | 329.6 ± 15.3 | 321.9 | 391.4 | 1.00 |
| `./nu-3.exe -c "source math_function.nu"` | 338.4 ± 14.3 | 330.7 | 397.0 | 1.03 ± 0.06 |
| `./nu-s.exe -c "source math_function.nu"` | 360.0 ± 21.3 | 346.0 | 413.6 | 1.09 ± 0.08 |
| `./nu-z.exe -c "source math_function.nu"` | 381.0 ± 23.4 | 364.7 | 469.3 | 1.16 ± 0.09 |

```nu
let alist = for i in 1..100000 { random decimal (-10)..10 }

let _ = ($alist | math abs | math sqrt)
let _ = ($alist | math avg)
let _ = ($alist | math ceil)
let _ = ($alist | math floor)
let _ = ($alist | math max)
let _ = ($alist | math median)
let _ = ($alist | math min)
let _ = ($alist | math mode)
let _ = ($alist | math product)
let _ = ($alist | math round)
let _ = ($alist | math stddev)
let _ = ($alist | math sum)
let _ = ($alist | math variance)

let alist = 0
let _ = 0
```

## 2. source for_and_each
| Command | Mean [ms] | Min [ms] | Max [ms] | Relative |
|:---|---:|---:|---:|---:|
| `./nu-1.exe -c "source for_and_each.nu"` | 934.2 ± 49.7 | 878.8 | 1120.1 | 1.02 ± 0.07 |
| `./nu-2.exe -c "source for_and_each.nu"` | 919.4 ± 33.8 | 885.3 | 1014.0 | 1.00 |
| `./nu-3.exe -c "source for_and_each.nu"` | 926.0 ± 42.9 | 883.9 | 1113.5 | 1.01 ± 0.06 |
| `./nu-s.exe -c "source for_and_each.nu"` | 1004.0 ± 22.7 | 971.3 | 1095.7 | 1.09 ± 0.05 |
| `./nu-z.exe -c "source for_and_each.nu"` | 1131.3 ± 63.3 | 1075.1 | 1460.6 | 1.23 ± 0.08 |

```nu
let _ = (for i in 0..10 {
    (for j in 0..25 {
        ((0..500) | each {|k|
            echo $"($i)-($j)-($k)"
        } | reduce {|it, acc| $it + $acc })
    } | reduce {|it, acc| $it + $acc })
} | reduce {|it, acc| $it + $acc })

let _ = (for i in 0..10 {
    (for j in 0..25 {
        ((0..500) | par-each {|k|
            echo $"($i)-($j)-($k)"
        } | reduce {|it, acc| $it + $acc })
    } | reduce {|it, acc| $it + $acc })
} | reduce {|it, acc| $it + $acc })

let _ = 0
```
## 3. parsing large json / others
| Command | Mean [ms] | Min [ms] | Max [ms] | Relative |
|:---|---:|---:|---:|---:|
| `./nu-1.exe -c "source parse_large_json.nu"` | 80.0 ± 0.4 | 79.2 | 82.4 | 1.01 ± 0.01 |
| `./nu-2.exe -c "source parse_large_json.nu"` | 80.0 ± 0.4 | 79.3 | 83.1 | 1.01 ± 0.01 |
| `./nu-3.exe -c "source parse_large_json.nu"` | 79.4 ± 0.4 | 78.2 | 81.9 | 1.00 |
| `./nu-s.exe -c "source parse_large_json.nu"` | 83.1 ± 0.4 | 82.4 | 85.0 | 1.05 ± 0.01 |
| `./nu-z.exe -c "source parse_large_json.nu"` | 86.8 ± 0.4 | 86.1 | 89.0 | 1.09 ± 0.01 |

```nu

let r = (0..250 | each {|_| random uuid })
let r2 = (0..1000 | flatten )
let data = {(random uuid): { (random uuid): $r}, (random uuid): {(random uuid): { (random uuid): $r2}, (random uuid): {(random uuid): { (random uuid): $r}, (random uuid): {(random uuid): { (random uuid): $r}, (random uuid): {(random uuid): { (random uuid): $r2}, (random uuid): {(random uuid): { (random uuid): $r}, (random uuid): {(random uuid): { (random uuid): $r}, (random uuid): {(random uuid): { (random uuid): $r2}, (random uuid): {(random uuid): { (random uuid): $r}, (random uuid): {(random uuid): { (random uuid): $r2}, (random uuid): $r}}}}}}}}}}

let _ = ($data | to csv  | from csv)
let _ = ($data | to html)
let _ = ($data | to json | from json)
let _ = ($data | to md)
let _ = ($data | to nuon | from nuon)
let _ = ($data | to text)
let _ = ($data | to toml)
let _ = ($data | to tsv)
let _ = ($data | to yaml | from yaml)

let data = 0
let _ = 0
```

## 4. bench_math_expr

| Command | Mean [ms] | Min [ms] | Max [ms] | Relative |
|:---|---:|---:|---:|---:|
| `./nu-1.exe -c "source math_expr.nu"` | 338.2 ± 29.9 | 310.7 | 499.4 | 1.03 ± 0.13 |
| `./nu-2.exe -c "source math_expr.nu"` | 327.9 ± 28.6 | 310.4 | 501.7 | 1.00 |
| `./nu-3.exe -c "source math_expr.nu"` | 332.9 ± 25.2 | 310.0 | 447.0 | 1.02 ± 0.12 |
| `./nu-s.exe -c "source math_expr.nu"` | 355.2 ± 18.5 | 340.8 | 449.9 | 1.08 ± 0.11 |
| `./nu-z.exe -c "source math_expr.nu"` | 404.3 ± 19.6 | 387.9 | 524.5 | 1.23 ± 0.12 |

I don't post the code here (not to get too bloated), but it is a really long math expression with multiple `*/+-` (roughly 128960 characters long.)

# Tests + Formatting

Make sure you've done the following, if applicable:

- Add tests that cover your changes (either in the command examples, the crate/tests folder, or in the /tests folder)
  - Try to think about corner cases and various ways how your changes could break. Cover those in the tests

Make sure you've run and fixed any issues with these commands:

- `cargo fmt --all -- --check` to check standard code formatting (`cargo fmt --all` applies these changes)
- `cargo clippy --workspace --features=extra -- -D warnings -D clippy::unwrap_used -A clippy::needless_collect` to check that you're using the standard code style
- `cargo test --workspace --features=extra` to check that all tests pass

# User-Facing Changes

If you're making changes that will affect the user experience of Nushell (ex: adding/removing a command, changing an input/output type, adding a new flag):

- Get another regular contributor to review the PR before merging
- Make sure that there is an entry in the documentation (https://github.com/nushell/nushell.github.io) for the feature, and update it if necessary

### CODE REVIEW

**Comment by FilipAndersson245** [comment]
I did a minor test on startup time also and this gave a very minor victory for the non `opt-level=s` builds by about **3.5-3%**
I'm unsure why the variance was so much higher for the `s` build.
| Command | Mean [ms] | Min [ms] | Max [ms] | Relative |
|:---|---:|---:|---:|---:|
| `./nu-1.exe -c ""` | 30.0 ± 0.6 | 28.9 | 31.5 | 1.00 |
| `./nu-2.exe -c ""` | 30.0 ± 0.7 | 29.0 | 35.9 | 1.00 ± 0.03 |
| `./nu-3.exe -c ""` | 30.4 ± 1.3 | 29.1 | 41.0 | 1.01 ± 0.05 |
| `./nu-s.exe -c ""` | 31.0 ± 7.1 | 28.9 | 112.8 | 1.03 ± 0.24 |
| `./nu-z.exe -c ""` | 31.0 ± 0.6 | 29.9 | 34.0 | 1.03 ± 0.03 |

**Comment by rgwood** [comment]
Thanks for the very detailed PR description.

Personally, I care a lot about compile times and binary size. I'm not in favour of regressing on both for faster performance; I think the conclusion from [your last issue on this topic](https://github.com/nushell/nushell/issues/5076) still stands.

Also, am I correct in thinking that those numbers are without any features enabled? `dataframes` is a really big feature and likely to change the binary size+compile time numbers.

**Comment by FilipAndersson245** [comment]
These are without any extra features added.

**Comment by rgwood** [comment]
> Edit: This would only affect release builds, as dev builds will be the same, if compile time is the mayor problem we may enable this only for the CI releases.

Compile times in CI matter a lot, because our CI runs on slow free GitHub machines. This also affects local release builds, which I do often.

But even if compile times weren't an issue, the binary size regression (which we don't fully understand, since the builds weren't run with `features=extra`) is concerning.

**Comment by sholderbach** [comment]
Thanks for the in-depth measurements and providing benchmark code!
I disagree with the conclusion that `opt-level = 3` is a sweet spot if you only care about the best runtime performance.
On most benchmarks `opt-level = 2` was slightly better or had better worse case performance than `3`.
It really high lights that optimization levels aren't just a magical "make the code go fast" buttons.
Doing more inlining or elaborate code gen can lead to more instruction cache misses (may explain the worse case performance) also the larger binary simply takes longer to load into memory on startup which matters if you use `nu` as a script runner.

Optimization is always a trade off and can depend on the code at hand and the workload as well as the platform/architecture. I was kind of surprised that `3` was also struggling with the tight loop math problems that in theory is a feast for optimizations. In interactive use, lower latency matters as well and there the cost of calls might be lower than the icache misses caused by long inlined blocks of code.

**Comment by rgwood** [comment]
Closing this as I believe the conclusions from [the previous issue](https://github.com/nushell/nushell/issues/5076) are still valid.

**Pull request closed without merging**
