### PR TITLE
Parse timestamps as UTC by default

### PR DESCRIPTION
**Pull request by rgwood**
# What?

This change allows for Unix timestamps to be parsed as UTC by default. Previously this would fail:

```
〉1614434140 | into datetime
Error: nu::shell::unsupported_input (link)

  × Unsupported input
   ╭─[entry #5:1:1]
 1 │ 1614434140 | into datetime
   ·              ──────┬──────
   ·                    ╰── Received integer input but timezone not specified. Did you forget to specify a timezone?
   ╰────
```

Now it works:

```
〉1614434140 | into datetime
Sat, 27 Feb 2021 13:55:40 +0000 (a year ago)
```

# Why?

UTC is more or less the de facto standard timezone. And Unix timestamps are defined relative to a UTC point in time. I think that people will want UTC more often than not when converting Unix timestamps (I do, anyway).

# Tests

Make sure you've run and fixed any issues with these commands:

- [x] `cargo fmt --all -- --check` to check standard code formatting (`cargo fmt --all` applies these changes)
- [x] `cargo clippy --all --all-features -- -D warnings -D clippy::unwrap_used -A clippy::needless_collect` to check that you're using the standard code style
- [x] `cargo build; cargo test --all --all-features` to check that all the tests pass

### CODE REVIEW

**Comment by rgwood** [comment]
Actually, let's hold off on merging this; I forgot to update examples.

**Comment by rgwood** [comment]
Made some improvements to the flags and examples.

**Comment by fdncred** [comment]
you're on a roll today. ready to land this @rgwood ?

**Comment by rgwood** [comment]
@fdncred Yup this one's good to go thanks!

**Pull request merged**
