### PR TITLE
feat: add search terms to date

### PR DESCRIPTION
**Pull request by babalolajnr**
# Description
This PR is relevant to [#5093](https://github.com/nushell/nushell/issues/5093.)
Added search terms to `date` category 

# Tests

Make sure you've run and fixed any issues with these commands:

- [x] `cargo fmt --all -- --check` to check standard code formatting (`cargo fmt --all` applies these changes)
- [x] `cargo clippy --all --all-features -- -D warnings -D clippy::unwrap_used -A clippy::needless_collect` to check that you're using the standard code style
- [x] `cargo build; cargo test --all --all-features` to check that all the tests pass

### CODE REVIEW

**Comment by fdncred** [comment]
nice! thanks for adding these. it looks like ci is complaining about the format though. maybe try running `cargo fmt --all` and see if that fixes it.

**Comment by babalolajnr** [comment]
Okay .Will try that

**Comment by babalolajnr** [comment]
So. I also added search terms to filesystem category and it looks like the commits are also part of this pull request. I don't understand how that happened. Anything I can do to fix that?

**Comment by fdncred** [comment]
It looks like maybe the problem is that you're editing code in the main branch. typically people will do something like `git checkout -b some_branch_name` and then do edits there, then use that branch to make a PR. This way, you can work on many different things at once. That's my guess as to why they're all in this PR.

Either way, it's fine to have both sets of commits here since they're all search terms.

**Comment by babalolajnr** [comment]
Oh, my bad. Totally my fault. Thanks for the info

**Comment by fdncred** [comment]
cool. thanks!

**Pull request merged**
