### PR TITLE
Add shift +  navigation functionality through reedline

### LINKED ISSUE #1171: shift + navigation should highlight
**Is your feature request related to a problem? Please describe.**

Sort of, this is more of a "I'm used to this behavior from other shells."

I was psyched when I saw control left / control right move by words in nu 0.8. I tend to use this in cooperation with shift in order to higlight and delete things, but holding shift does not do this. In fact, it doesn't with arrow keys either.

**Describe the solution you'd like**

It would be cool if I could hold shift to select a portion of the command.

**Describe alternatives you've considered**

Maybe this isn't the way nu wants to be used, or there's some better way of doing this I'm not used to.

### PR DESCRIPTION
**Pull request by Tastaturtaste**
This PR should close #1171

# Description

This PR introduces the capability to select text using the existing move.. `EditCommand`s of `reedline`. Those commands are extended with an optional parameter specifying if text should be selected while navigating. This enables a workflow familiar from a wide variety of text editors, where holding `shift` while navigating selects all text between the initial cursor position when pressing `shift` and the current cursor position.

Before this PR can be merged the [sibling PR for reedline](https://github.com/nushell/reedline/pull/689) has to land first.

# User-Facing Changes
## Additional `EditCommand`s
1. `SelectAll`
2. `CutSelection`
3. `CopySelection`
## New optional parameter on existing `EditCommand`s
All `EditCommand`s of `EditType` `MoveCursor` have a new optional parameter named `select` of type `bool`. If this parameter is not set by a user it is treated as false, which corresponds to their behavior up to now.

I am relatively new to `nushell` and as such may not know of existing behavior that might change through this PR. However, I believe there should be none. I come to this conclusion because
1. Existing commands are extended only with an *optional* additional parameter, users who currently use these EditCommands keep their existing behavior if they don't use it.
2. A few new commands are introduced which were previously not valid.
3. The default keybindings specified in `default_config.nu` are untouched.

# Tests + Formatting
Tests for the new optional parameter for the move commands are included to make sure that they truly are optional and an unused optional parameter conforms to the previous behavior.

### CODE REVIEW

**Comment by Tastaturtaste** [comment]
Note that the functionality is partly not available by default because the keybindings are used for something else already:
1. `Ctrl + C` is used for `cancel_command`, so copying doesn't work out of the box
2. `Ctrl + X` is used for `next_page_menu`, so cutting also doesn't work out of the box
3. `Ctrl + A` is used for `move_to_line_start`, so select_all doesn't work by default

All of these defaults can, of course, be overridden. 
One oddity I stumbled upon is that `nushell` in general does not set default keybindings apart from those defined by reedline in code, but specifies them all in the `config.nu` file. However, the function `add_menu_keybindings` is an exception to this rule and adds 7 hardcoded default keybindings. These keybindings are then *also* again set in `config.nu` by default. Is there a reason for this? I would think it would be less surprising and error prone if there was a single place for them to be specified.

**Comment by fdncred** [comment]
I think what we need to do is come up with some key bindings that will work without conflicting with other key combinations. maybe ...
- ctrl-shift-c (copy) 
- ctrl-shift-v (paste)
- ctrl-shift-x (cut)
- ctrl-shift-a (select all)
- etc ...

Then put these in the default_config.nu in this PR. Then if people want to reassign them in their config.nu, they can.

**Comment by Tastaturtaste** [comment]
> I think what we need to do is come up with some key bindings that will work without conflicting with other key combinations. maybe ...
> 
>     * ctrl-shift-c (copy)
> 
>     * ctrl-shift-v (paste)
> 
>     * ctrl-shift-x (cut)
> 
>     * ctrl-shift-a (select all)
> 
>     * etc ...
> 
> 
> Then put these in the default_config.nu in this PR. Then if people want to reassign them in their config.nu, they can.

Sounds good to me, I will do that with your suggested key combinations. If anyone has a better idea for free combinations please mention them.

> It also looks like there are some security concerns in the ci that may affect the reedline PR as well.

Yeah, because of `reedline`s dependency on the [clipboard](https://crates.io/crates/clipboard) crate, which is pulled in because of the `system_clipboard` feature I enabled in this PR. The root cause is an old version of the [xcb](https://crates.io/crates/xcb) crate. Since `clipboard` is unmaintained, it probably won't get a new version with the fixed `xcb` dependency. 

There are two popular alternatives to `clipboard`, both forks of it:
1. [copypasta](https://crates.io/crates/copypasta)
2. [arboard](https://crates.io/crates/arboard)

Both have over a million downloads and had their last release in the last 3 months. 
I could try to transition `reedline` from `clipboard` to one of those two if you want.

**Comment by fdncred** [comment]
It would be wonderful to replace clipboard with something. Note the concern here https://github.com/nushell/reedline/pull/606. So, if we could do it with minimal dependency increase it would be wonderful. If there is no other option than to increase dependencies, I'm sure we'll go for that. I hate to put another PR on your plate but thanks so much for offering. We truly appreciate your help!

**Comment by fdncred** [comment]
@Tastaturtaste I just tested this out with the new keybindings. It seems to work great with the exception of select_all. They keybinding works but it selects everything in the terminal windows, including all the backbuffer. Is that what it's supposed to do? I thought it would just select the entire command line.

**Comment by fdncred** [comment]
indeed, i was testing in windows terminal. i just remaped the wt select-all to ctrl-alt-shift-a and that did the trick. thanks for figuring this out. i hadn't considered that wt was using the keybinding!

now, to figure out these ci issues.

**Comment by Tastaturtaste** [comment]
Ok, so on windows all tests are working fine for me. In wsl linux I got multiple fails for the `nu` crate alone, though:
```
failures:
    tests::test_config_path::test_alternate_config_path
    tests::test_config_path::test_default_config_path
    tests::test_custom_commands::deprecated_boolean_flag
    tests::test_custom_commands::infinite_recursion_does_not_panic
    tests::test_custom_commands::override_table_eval_file
    tests::test_spread::deprecate_implicit_spread_for_externals
    tests::test_spread::spread_external_args
    tests::test_spread::spread_non_list_args
```
Mostly with the following error message:
```
---- tests::test_spread::spread_external_args stdout ----
thread 'tests::test_spread::spread_external_args' panicked at /home/<user>/dev/nushell/crates/nu-test-support/src/macros.rs:233:9:
Couldn't canonicalize dummy binaries path /home/<user>/dev/nushell/target/debug: Os { code: 2, kind: NotFound, message: "No such file or directory" }
```
I don't know yet what is going on, on first glance these tests have nothing to do with the changes I made or the new clipboard crate. Since I am not that knowledgeable with linux specifics, if someone can help out here that would be much appreciated.

I also get those test fails on main. I expect this has something to do with wsl specifically.

**Comment by Tastaturtaste** [comment]
The backtrace for the error in the CLI:
```
--- STDERR:              nu-cli repl::are_session_ids_in_sync ---
thread 'repl::are_session_ids_in_sync' panicked at /home/joshua/.cargo/git/checkouts/reedline-e42026a78d91c510/2f3eb3e/src/core_editor/clip_buffer.rs:92:37:
called `Result::unwrap()` on an `Err` value: Unknown { .. } - "Unknown error while interacting with the clipboard: X11 server connection timed out because it was unreachable"
stack backtrace:
   0: rust_begin_unwind
             at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/std/src/panicking.rs:595:5
   1: core::panicking::panic_fmt
             at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/core/src/panicking.rs:67:14
   2: core::result::unwrap_failed
             at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/core/src/result.rs:1652:5
   3: core::result::Result<T,E>::unwrap
             at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/core/src/result.rs:1077:23
   4: reedline::core_editor::clip_buffer::system_clipboard::SystemClipboard::new
             at /home/joshua/.cargo/git/checkouts/reedline-e42026a78d91c510/2f3eb3e/src/core_editor/clip_buffer.rs:92:22
   5: reedline::core_editor::clip_buffer::get_default_clipboard
             at /home/joshua/.cargo/git/checkouts/reedline-e42026a78d91c510/2f3eb3e/src/core_editor/clip_buffer.rs:63:5
   6: <reedline::core_editor::editor::Editor as core::default::Default>::default
             at /home/joshua/.cargo/git/checkouts/reedline-e42026a78d91c510/2f3eb3e/src/core_editor/editor.rs:21:34
   7: reedline::engine::Reedline::create
             at /home/joshua/.cargo/git/checkouts/reedline-e42026a78d91c510/2f3eb3e/src/engine.rs:198:21
   8: nu_cli::repl::are_session_ids_in_sync
             at ./src/repl.rs:844:23
   9: nu_cli::repl::are_session_ids_in_sync::{{closure}}
             at ./src/repl.rs:838:30
  10: core::ops::function::FnOnce::call_once
             at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/core/src/ops/function.rs:250:5
  11: core::ops::function::FnOnce::call_once
             at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/core/src/ops/function.rs:250:5
```

Seems to be some problem with X11 server timing out.

**Comment by Tastaturtaste** [comment]
I am unable to reproduce the test failure for `repl::are_session_ids_in_sync` deterministically. I had some test fails that I can't reproduce anymore. I didn't change any code. Could it be that it really is just a flaky system behaviour we can't really influence from the application? In that case a practical solution would maybe involve trying to get the clipboard with N retries. I think I saw that approach somewhere already while looking for the clipboard replacement.

Also, the test `repl::glob` seems to hang for me in wsl. I don't know what the expected runtime for that test should be, but I waited well over two minutes for it before terminating.

**Comment by fdncred** [comment]
I'm guessing there are two ways forward for the clipboard thing.
1. retry x amount of times, like you suggested.
2. use another clipboard library and hope it works.

**Comment by fdncred** [comment]
i'm going to re-run the failed ci jobs too and see what happens.

**Comment by fdncred** [comment]
This is becoming a bigger problem now because i can't compile nushell because of these error messages.
```
error[E0533]: expected value, found struct variant `EditCommand::MoveToStart`
   --> crates/nu-cli/src/reedline_config.rs:864:26
    |
864 |         "movetostart" => EditCommand::MoveToStart,
    |                          ^^^^^^^^^^^^^^^^^^^^^^^^ not a value

error[E0533]: expected value, found struct variant `EditCommand::MoveToLineStart`
   --> crates/nu-cli/src/reedline_config.rs:865:30
    |
865 |         "movetolinestart" => EditCommand::MoveToLineStart,
    |                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^ not a value

error[E0533]: expected value, found struct variant `EditCommand::MoveToEnd`
   --> crates/nu-cli/src/reedline_config.rs:866:24
    |
866 |         "movetoend" => EditCommand::MoveToEnd,
    |                        ^^^^^^^^^^^^^^^^^^^^^^ not a value
... and more
```

**Comment by fdncred** [comment]
we have a very limited amount of time to fix this issue, otherwise i'm going to have to revert the reedline PR and we can work on it there and here to get the clipboard stuff sorted.

**Comment by Tastaturtaste** [comment]
Yeah, that's what I feared. Sorry for the inconvenience.
I will try the retry approach today. I will get to it at ~ 1800 UTC I think.

**Comment by Tastaturtaste** [comment]
> Yeah, that's what I feared. Sorry for the inconvenience. I will try the retry approach today. I will get to it at ~ 1800 UTC I think.

Sadly life gets in the way and I won't be able to tackle this today. Sorry.

**Comment by Tastaturtaste** [comment]
I think the problem really is the CI which runs in headless mode, in combination with the clipboard, which expects an x11 server to be available. I found multiple similar problems people had with github actions and X11 where the required x11 dependency is missing: 
- https://en.sfml-dev.org/forums/index.php?topic=28295.0
- https://stackoverflow.com/questions/63125480/running-a-gui-application-on-a-ci-service-without-x11
- https://github.com/go-gl/glfw/issues/129
- https://github.com/fyne-io/fyne/issues/3115

Also [the x11rb crate](https://crates.io/crates/x11rb/0.12.0), which is the dependency `arboard` uses for its linux implementation, states in its readme: 
> The interaction with libxcb via XCBConnection requires at least libxcb 1.12.

This didn't come up in the reedline PR, because the `system_clipboard` feature is not tested in CI. I modified the ci of reedline to run the CI with the system_clipboard feature and with that I get the same error: https://github.com/Tastaturtaste/reedline/actions/runs/7588891933/job/20672377555

Assuming this is the case, it would now be necessary to find a way to enable x11 in github actions. I don't know how this would work, as I haven't done much with github actions before. So if someone could figure this out for me I would be grateful. My naive first guess would be to run `sudo apt get libxcb` as a step before running the tests, but that wouldn't work for windows.

**Comment by fdncred** [comment]
@Tastaturtaste can you try this out on your personal reedline ci

```
- name: Install xmllint
  run: sudo apt-get install -y libxml2-utils
```
just replace libxml2-utils with whatever you need.

That is taken from here
https://stackoverflow.com/questions/57982945/how-to-apt-get-install-in-a-github-actions-workflow

but this is the gh reference
https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners/customizing-github-hosted-runners

**Comment by Tastaturtaste** [comment]
I tried some things and I think I was able to install things on linux, but I can't get it to work. 
I looked at the CI of arboard itself and found this:
> [# No Linux test for now as it just fails due to not having a desktop environment.](https://github.com/1Password/arboard/blob/a648570ce9c8d7051546f93df4b06cd6e82e9e01/.github/workflows/test.yml#L57)

And [the CI from copypasta also doesn't test on linux](https://github.com/alacritty/copypasta/blob/54699fb3d9435ac86fbc0ebb18d3e8ae3665b7be/.github/workflows/ci.yml). Since the two biggest clipboard crates themselves with combined over 4 million downloads can't get CI testing on linux gh action to work, I don't think it's possible to get any clipboard crate to work in a linux github action environment with reasonable effort.

As I see it this leaves us with three options:

1. Don't merge this PR
2. Merge this PR, enable the clipboard feature behind a default feature flag, and disable this feature for CI tests on linux
3. Merge this PR but without the clipboard feature enabled

I think option 2 would give the most benefit for most people, but as the creator of this PR I am also of course biased. Option 3 would still provide some benefits, like bulk deleting selected text or copy and paste inside nushell itself, but the usability is seriously hampered. Obviously I am not a fan of option 1 :)

I would propose to go with option 2 after local testing by interested parties.

**Comment by fdncred** [comment]
I'm fine with number 2 and ignoring the tests for clipboard for now. if you want to make those changes, we'll land this. thanks for your hard work and research.

**Comment by Tastaturtaste** [comment]
Currently my build fails because of [this recent PR](https://github.com/nushell/reedline/pull/696). Once that is resolved everything should be fine. [Here is a CI run for basically the same branch](https://github.com/Tastaturtaste/nushell/actions/runs/7590603899), with only few adjustments to be able to run the CI and based on an older version of reedline.

**Comment by fdncred** [comment]
> Once that is resolved  ...

What's the plan to resolve it?

**Comment by Tastaturtaste** [comment]
I don't know, you tell me. That change has nothing to do with this PR and the failure happens in a file completely untouched by this PR. 

The mentioned PR adds a new trait method which is not yet implemented in nushell/main. The reason it doesn't fail on main as is is just that it doesn't pull in the newest version of reedline. Running `cargo update` on the main branch breaks the build in the same way. So unless you want me to manually edit the Cargo.lock file or take on another PR to fix this I don't see what I could do here to resolve it.

**Comment by Tastaturtaste** [comment]
I just manually resolved the reedline dependency in the `Cargo.lock` file so work around the breaking change on reedline/master introduced by adding the `set_cursor_pos` associated function to the `Menu` trait with PR https://github.com/nushell/reedline/pull/696#issue-2064487553. This allows merging this PR without waiting for nushell to catch up to reedline/master.

**Comment by fdncred** [comment]
Thanks for working on this @Tastaturtaste. We appreciate it. This may get us over the hump, and I've contacted the author of the ide menu to see what they can do to help and get us on the latest main of reedline.

**Comment by Tastaturtaste** [comment]
The difference very likely stems from the fact that selection by keyboard is implemented in nushell while the selection by mouse happens separately by the OS/Terminal. If you select text with the mouse you won't be able to use the associated keybindings in nushell, though copy/paste may still work with support from the terminal itself.

Yeah, the color should be configurable. It shouldn't be to hard to implement, I just wanted to avoid scope creep for the MVP.

**Comment by Tastaturtaste** [comment]
There sure is a way if you are able and willing to contribute the code :) 

Maybe I will have some time in the next few weeks to implement it myself, but honestly that's not a big priority for me at the moment.

**Pull request merged**
