### PR TITLE
FIX: filter the `std help ...` by name, usage and search terms

### PR DESCRIPTION
**Pull request by amtoine**
Should close on of the points in
- https://github.com/nushell/nushell/issues/8813

# Description
this PR uses the new `--columns` option for `find` to filter the results of the `std help` commands on the `usage`, `name` and `search_terms` columns.

# User-Facing Changes
the `--find` option of `std help` commands should match more closely the built-in `help` commands output.

# Tests + Formatting
- :green_circle: `toolkit fmt`
- :green_circle: `toolkit clippy`
- :black_circle: `toolkit test`
- :black_circle: `toolkit test stdlib`

# After Submitting
```
$nothing
```

### CODE REVIEW

**Comment by amtoine** [comment]
that should be a bit better with the last commit @fdncred :yum:

**Comment by fdncred** [comment]
> that should be a bit better with the last commit @fdncred 😋

That latest commit helps but `std help modules -f blah` doesn't output a table at all

**Comment by amtoine** [comment]
> That latest commit helps but `std help modules -f blah` doesn't output a table at all
>
yes, it's an issue that had been there since the beginning of these commands :eyes: 

can i save that for after this lands? :yum: [

**Review by fdncred — APPROVED** [review]
These changes work and we can land this on the promise that the other issues will be fixed in subsequent PR(s).

**Pull request merged**
