### PR TITLE
bump to 0.81

### PR DESCRIPTION
**Pull request by jntrnr**
# Description

# User-Facing Changes

# Tests + Formatting

# After Submitting

### CODE REVIEW

**Comment by fdncred** [comment]
FYI - Stefan had some checklist items here if it's helpful https://github.com/nushell/nushell/pull/9369

**Comment by jntrnr** [comment]
@fdncred - lets hope it works as-in. Unfortunately, I've only got time/energy to just do a normal release.

**Comment by fdncred** [comment]
@jntrnr I'm good with whatever, just didn't know if you were following that we added nu-cmd-extra crate. Nor do I know if it's in the release scripts yet.

**Comment by jntrnr** [comment]
@fdncred - yeah just grabbed the latest release script

**Comment by sholderbach** [comment]
One thing for next time, I added a `# version = 0.xx.y` comment at the top of the `default_{config,env}.nu` files for tracking/troubleshooting and have been updating with the version bump PRs.

**Pull request merged**
