### PR TITLE
Unify glob behavior on `open`, `rm`, `cp-old`, `mv`, `umv`, `cp` and `du` commands

### PR DESCRIPTION
**Pull request by WindSoilder**
# Description
This pr is a follow up to [#11569](https://github.com/nushell/nushell/pull/11569#issuecomment-1902279587)
> Revert the logic in https://github.com/nushell/nushell/pull/10694 and apply the logic in this pr to mv, cp, rv will require a larger change, I need to think how to achieve the bahavior

And sorry @bobhy for reverting some of your changes.

This pr is going to unify glob behavior on the given commands:
* open
* rm
* cp-old
* mv
* umv
* cp
* du

So they have the same behavior to `ls`, which is:
If given parameter is quoted by single quote(`'`) or double quote(`"`), don't auto-expand the glob pattern.  If not quoted, auto-expand the glob pattern.

Fixes: #9558  Fixes: #10211 Fixes: #9310 Fixes: #10364 

# TODO
But there is one thing remains: if we give a variable to the command, it will always auto-expand the glob pattern, e.g:
```nushell
let path = "a[123]b"
rm $path
```
I don't think it's expected.  But I also think user might want to auto-expand the glob pattern in variables.

So I'll introduce a new command called `glob escape`, then if user doesn't want to auto-expand the glob pattern, he can just do this: `rm ($path | glob escape)`

# User-Facing Changes

# Tests + Formatting
Done

# After Submitting

## NOTE
This pr changes the semantic of `GlobPattern`, before this pr, it will `expand path` after evaluated, this makes `nu_engine::glob_from` have no chance to glob things right if a path contains glob pattern.

e.g:  [#9310 ](https://github.com/nushell/nushell/issues/9310#issuecomment-1886824030)  #10211

I think changing the semantic is fine, because it makes glob works if path contains something like '*'.

It maybe a breaking change if a custom command's argument are annotated by `: glob`.

### CODE REVIEW

**Comment by kubouch** [comment]
This is awesome! For me, the exact semantics are not as important as the fact that the behavior is _unified_, meaning that if we need to reconsider the globbing behavior at some point, we'd change it in one place instead of 10.

`glob escape` sounds good as well as a way to escape globbing. We could even land just the unification and leave `glob escape` to a separate PR.

**Comment by bobhy** [comment]
Hmmm,
We're trying to solve a problem here that traditional shells could never
solve, but this particular solution doesn't feel right.

In a traditional shell, the commands don't glob and rely on the shell to
expand globs.  The shell itself makes no attempt to be aware of the
particular command it's expanding, it just expands whatever unescaped glob
characters it sees.  And we've all internalized the peculiarities: we
accept, for example, that, in bash, `cp *` could be a perfectly legit
command (but would be hard pressed to name the new file that is created).

Nu already handles the `cp` example in a more natural way.  The Nu `cp`
command insists on at least 2 arguments and just knows that the last
argument is a single path, not a glob.

But now we have a new situation where we want to suppress expanding a glob
appearing *anywhere* in the (input arguments of the) command line.  It's
not just the last argument.  As I say, this is not a situation we have
experience with, and our experience from traditional shells doesn't give us
a model, so we have to be careful what we innovate.

I think it's a mistake to use quotes to suppress globbing.  We already want
to use quotes as the natural way to specify paths containing spaces or
other characters special for the parsing of the command line, like
whitespace and `;`.

I wish Nu allowed named parameters to be positional, so we could have
(command-specific) syntax like:
```
cp able --noglob bak*er charlie
```
Where the `--noglob` named param could appear anywhere in the argument list
and apply to just that argument. That feels like a very natural way to
specify special handling for the argument.

As it is right now though, you could support this as the *first and only*
input argument to the file system commands, e.g `cp --noglob able charlie`.
I actually feel that's good enough -- dealing with files whose names
contain glob characters should be rare and the commands for dealing with
them can be a bit limited.  It's OK (with me) if the user has to review the
command help when dealing with them.

But if you wanted to provide full generality, I'd suggest some convention
other than quoting, perhaps protocol-ish syntax?
```
cp able noglob://bak*er charlie
```
This would be specific to arguments of type "path" only.

**Comment by fdncred** [comment]
I thought double/single quoting was the standard way of telling any shell "this is a string. don't mess with it"?

**Comment by WindSoilder** [comment]
>  The Nu `cp` command insists on at least 2 arguments and just knows that the last argument is a single path, not a glob.

Actually it remains the same, the last argument is still a single path.

I think something like: `cp able noglob://bak*er charlie` required user types too much things, `cp able "bak*er" charlie` is more readable.  Maybe it's more comfortable to users from other shells?
After reading relative issues, I think quoting something to say "this is just a string, no need to escape it" is natural.

**Comment by kubouch** [comment]
As I mentioned, the main value of this PR is the unification of globbing across commands. If we need to change how globbing works, this PR makes it easier to do by changing it only in one place. I'd vote for landing this.

**Comment by fdncred** [comment]
I'm fine with landing it too, 
- main needs to be merged, since we removed cp-old. 
- `touch "[a] b.c"` works, but ``` rm `[a] b.c` ``` does not work (maybe fix and add a test) (windows)
- `rm '[a] b.c'` and `rm "[a] b.c"` work fine (windows)
- perhaps `touch` should be added (could be another pr)
- perhaps `ls` should be added (could be another pr)
- `touch "\u{1b}[31mnushell\u{1b}[0m"` works but then you see a red nushell that you don't know how to remove. (real use case someone had) (ubuntu)
- `rm "\u{1b}[31mnushell\u{1b}[0m"` doesn't work (ubuntu)
- i can only see the odd file in zsh as `''$'\033''[31mnushell'$'\033''[0m'` and `rm $'\033'\[31mnushell$'\033'\[0m` got rid of it
- string interpolation seems to work. here's my test
```nushell
touch 1.txt
let a = '1'
rm $"($a).txt"
```

**Comment by WindSoilder** [comment]
> touch "[a] b.c" works, but rm `[a] b.c` does not work (maybe fix and add a test) (windows)

It shouldn't work, because we treated backtick quoted as a bare word.

> touch "\u{1b}[31mnushell\u{1b}[0m" works but then you see a red nushell that you don't know how to remove. (real use case someone had) (ubuntu)
For such file, it's because we auto strip ansi string, maybe we need to find a way to fix such issue

**Comment by fdncred** [comment]
> It shouldn't work, because we treated backtick quoted as a bare word.

I am thinking it probably should because backticks are what we use with paths with spaces in them. I think that's why backticks work in this situation, because there is a space in the filename.

> For such file, it's because we auto strip ansi string, maybe we need to find a way to fix such issue

I think this is a special issue that could be handled in a separate PR but it's interesting to me that other shells do not just create a folder literally, the encode the escape from `\u{1b}` to `'$'\033''` before trying to create a file with "bad" characters.

**Comment by WindSoilder** [comment]
> I am thinking it probably should because backticks are what we use with paths with spaces in them. I think that's why backticks work in this situation, because there is a space in the filename.

Maybe we can discuss it in next meeting :-) 

> other shells do not just create a folder literally, the encode the escape from \u{1b} to '$'\033'' before trying to create a file with "bad" characters.

That's interesting, maybe we can fix it in that direction, like modify `mkdir` command.  And keep in mind on `touch` command while we are adding it to nushell.

**Comment by fdncred** [comment]
> That's interesting, maybe we can fix it in that direction, like modify mkdir command. And keep in mind on touch command while we are adding it to nushell.

ya, i think the fix needs to be like what you're saying. we intercept escapes and encode them somehow before trying to create a file.


I just texted this again and rm with backticks works like i thought it did. maybe i did something different yesterday?
```nushell
❯ touch "[a] b.c"  
❯ rm `[a] b.c`
```

**Comment by fdncred** [comment]
I rediscoverd my old PR https://github.com/nushell/nushell/pull/9956 with raw string literals. I wonder if something like that would help here?

**Comment by WindSoilder** [comment]
> I just texted this again and rm with backticks works like i thought it should. maybe i did something different yesterday?
❯ touch "[a] b.c"  
❯ rm `[a] b.c`

It doesn't work fine on my machine:
```
❯ touch "[a] b c"
❯ rm `[a] b c`
Error:   × File(s) not found
   ╭─[entry #5:1:1]
 1 │ rm `[a] b c`
   ·    ────┬────
   ·        ╰── File(s) not found
   ╰────
```

> I rediscoverd my old PR https://github.com/nushell/nushell/pull/9956 with raw string literals. I wonder if something like that would help here?

Hmm...TBH I'm not really sure

**Comment by fdncred** [comment]
> It doesn't work fine on my machine:

I'm on windows on the latest main. Not sure that matters.

**Comment by WindSoilder** [comment]
Oh, you mentioned latest main, yeah it works because of Bob's pr, it check the existence of a file before globbing it

**Comment by WindSoilder** [comment]
Let's merge and try it:-)

**Comment by kubouch** [comment]
Yeah, I agree, we can iterate on the glob semantic in separate PRs. Now it's at least uniform.

To me, `...` also seems like a bare word and thus should be glob-expanded.

**Comment by matklad** [comment]
Drive by comment, but I was reading the last changelog, and

> So I'll introduce a new command called glob escape, then if user doesn't want to auto-expand the glob pattern, he can just do this: rm ($path | glob escape)

Feels **very** surprising.

It seems to me that this behavior is very error prone? `rm $file` looks like it removes a single file. What’s more, it *works* as if it removes only a single file most of the time, so the user won’t learn about mistakes in their mental model until the day the file is named `*`.

To put it in other way, I posit that with the current semantics:

* most arguments should be using `| str glob-escape`
* almost none will be

Is there any way to make it work the opposite way? Such that `rm $file` is never a glob, and `rm ($file | str glob)` is?

Note: although I feel very strongly about the isssue, my level of confidence here is low, I might be misunderstanding something about nu which makes this pattern not as problematic as it seems.

**Comment by bobhy** [comment]
In supporting globbin of `rm` arguments, nushell is just following the lead
of traditional shells (both linux and windows).  Technically it could work
the other way, but then nu would be odd man out.

It is a valid concern that `rm *` might do more than you expected, and that
you might not realize it till later.
Perhaps nushell `rm` should integrate with the "trash" mechanism on the
underlying platform?

**Comment by matklad** [comment]
> In supporting globbin of `rm` arguments, nushell is just following the lead of traditional shells

Indeed, and my understanding is that this behavior is a confirmed footgun in those shells. 

For example shellcheck lints against unquoted variables:

https://www.shellcheck.net/wiki/SC2086

So, for a shell language which isn’t trying to be compatible with POSIX shell, I’d expect a different, safer semantics by default.

**Comment by 71** [comment]
IMHO, this change breaks the principle of least astonishment. Considering the three following snippets:

1. ```nu
   let a = "a?c"
   rm $a
   ```

2. ```nu
   rm a?c
   ```

3. ```nu
   rm "a?c"
   ```

The first two are equivalent, but the last one isn't. I would expect (looking strictly at quotes) that the 1st and 3rd statement are equivalent, but instead they behave differently. Given a variable `a`, now the way to achieve the same behavior as 3. is:

4. ```
   let a = "a?c"
   rm ($a | str glob-escape)
   ```

Which looks very differently from 3.

----

Nu seems to pride itself in approaching things differently. Notably, given a string with spaces like

```nu
let a = "-rm ."
```

Then this command is safe to execute and will delete a file named `-rm .`, since `$a` is a single string:

```nu
rm $a
```

However, this assumption that using a variable to execute a command is safe is now broken following this change; additional arguments/flags will not be given to `rm` (a strength of Nushell), but `$a` will _still_ be expanded.

----

> Perhaps nushell `rm` should integrate with the "trash" mechanism on the underlying platform?

IMO this doesn't solve it. `mv` and other such commands will still move (and potentially overwrite) items, which doesn't involve the system trash.

**Comment by bobhy** [comment]
@matklad How should the safer semantics work in practice?
If Nu does *not* glob `rm` arguments, how should the knowledgeable and careful user actually delete multiple files?
``` 
> rm a.txt b.txt c.txt                            # works, but is typo-prone and tedious

> ls *.txt | rm                                       # nope, rm doesn't accept pipeline input
Error: nu::parser::missing_positional

  × Missing required positional argument.
   ╭─[entry #9:1:1]
 1 │ ls *.txt | rm
   ╰────
  help: Usage: rm {flags} <filename> ...(rest) . Use `--help` for more information.

> ls *.txt | each  {|x| rm $x.name}         # works, is nushell - normative, but intuitive?  
╭────────────╮                                 # And what is this 'empty list' result?
│ empty list │
╰────────────╯
```

The rest of the world seems to have decided that the best balance between "convenience" and "safety" here is to allow globbing but to enable wastebasket or similarly named mechanism to recover from mistakes.

Building on this, I just discovered that `rm --trash` is a thing, and actually does work on linux.  Perhaps it should be the default?

**Comment by matklad** [comment]
@bobhy I personally find the behavior of fish shell quite reasonable:

```
15:52:45|~/tmp
λ touch '*' 'a.txt' 'b.txt' 'c.txt' && rm * && eza

15:52:56|~/tmp
λ touch '*' 'a.txt' 'b.txt' 'c.txt' && rm '*' && eza
a.txt  b.txt  c.txt

15:52:59|~/tmp
λ touch '*' 'a.txt' 'b.txt' 'c.txt' && FILE='*' rm $FILE && eza
a.txt  b.txt  c.txt

15:53:06|~/tmp
λ touch '*' 'a.txt' 'b.txt' 'c.txt' && FILE='*' eval rm $FILE && eza
```

**Comment by fdncred** [comment]
Numbering and labeling these to reference them. Let me know if I interpreted them wrong.
1. globbing *, removes everything
2. non-globbing, looking for literal '*', removes nothing
3. non-globbing, since it's a variable, I guess? removes nothing
4. still non-globbing, but uses eval to turn it into a glob, I guess? removes everything

**Comment by matklad** [comment]
Yup, that's correct, just "removes nothing" -> "removes only the file whose name is literally '*'":

```
λ touch '*' 'a.txt' 'b.txt' 'c.txt'  && eza
*  a.txt  b.txt  c.txt
* ```

**Comment by CAD97** [comment]
> If Nu does not glob rm arguments, how should the knowledgeable and careful user actually delete multiple files?

The spread operator could be made to work, e.g. `glob *.txt | rm ...$in`. It doesn't currently because `rm` has a required positional argument and the spread operator only spread into rest arguments (or other list contexts).

> the behavior of fish shell

A principled interpretation of the behavior would be to consistently distinguish between "bareword string" and "quoted string" shapes (the `any` shape preserving the distinction), treating the content of "quoted strings" as final, applying the same rules to all shapes that impact semantics (at least `glob` and `path`).

The most directly equivalent constructs written in Nu would be (checked means expands glob):

- [X] `ls *`
- [ ] `ls '*'` ([0.90 feature](https://www.nushell.sh/blog/2024-02-06-nushell_0_90_0.html#breaking-change-handling-globs)
- [X] `with-env [FILE *] { ls $env.FILE }`
- [X] `with-env [FILE *] { ^$nu.current-exe -c $'ls ($env.FILE)' }` (little a `eval`, as a treat)

Nu-specific fun:

- [X] `ls ('*')`
- [X] `'*' | ls $in`
- [X] `def f [file] { ls $file }; f '*'`
- [ ] `def f [file: glob] { ls $file }; f '*'` (syntax shape changes semantics)
- [X] `def f [file: glob] { ls $file }; f ('*')` (but not through other constructs)

**Comment by WindSoilder** [comment]
Thank you for all feedback!

I can try to adjust the behavior when we meet variables

**Comment by CAD97** [comment]
Maybe look at how `path` is handled: a syntax shape of `path` will expand barewords but not strings (quoted, expression, or variable). It would mean flipping from "use `str escape-glob` to 

My crazy-concept idea would be for a `...pattern: glob` shape to expand bareword globs directly, with everything else interacting with it as just `...pattern: path`. That is, writing `ls *.nu` would be translated by the syntax shape into the equivalent of `ls ...(glob '*.nu')`. (It would probably want lazy/deferred expansion support as an optimization, though.)

**Pull request merged**
