### PR TITLE
Set Up Config in LSP Mode

### PR DESCRIPTION
**Pull request by schrieveslaach**
# Description

When starting the LSP server, the configuration file and environment file are used to configure the LSP engine unless --no-config-file is provided.

This PR provides an improvement that is related to #10794 

CC: @fdncred

### CODE REVIEW

**Comment by schrieveslaach** [comment]
@fdncred, I was wondering if you wait a little with merging because I reviewed the changes here and I was wondering if we should implement [`workspace/configuration`](https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#workspace_configuration) too with this PR. A client could provide an option to load or not to load the configuration for config folder.

What do you think?

**Comment by fdncred** [comment]
I'd be good with landing this one and then doing the workspace/configuration in a separate one. I haven't tried this one out but looking at the code, it seems like it may do what I'm talking about. Then we can tweak on that in a separate PR. How's that sound?

**Comment by schrieveslaach** [comment]
Sounds great.

**Comment by fdncred** [comment]
I still get the same diagnostic errors after this change but I'm not sure why. Trying to think of another way to test this. 🤔

**Comment by fdncred** [comment]
If I do `nu -c '$env.NU_LIB_DIRS' --lsp` I get 'variable not found' errors pointing to $nu, which seems weird to me. Maybe in lsp mode, there isn't a fully startup of nushell with all the bells and whistles?

**Comment by schrieveslaach** [comment]
@fdncred, I tried your commands on my Linux machine and they work just fine. If I remember correctly, you are on Windows, right? Could you try the version after rebase?

Maybe, I refactor the code so that it runs after initializing the LSP.

**Comment by fdncred** [comment]
I get this on MacOS. I can try Windows on Monday.
image

image

**Comment by schrieveslaach** [comment]
Ah, I think the LSP start was in the wrong spot. And I have no usage of `$nu` in `env.nu`. Can you give it another try?

**Comment by fdncred** [comment]
Seems to be working better because I don't have any red squigglies now. I'm not sure how to see what the lsp has configured for `$env.NU_LIB_DIRS` but I guess it must be reading my config/env files.
image

Before, these `use` lines would have diagnostic errors.

**Comment by fdncred** [comment]
Let me know if there's anything else you want to add, otherwise I'll land this.

**Comment by schrieveslaach** [comment]
I will create another PR that will add `workspaca/configuration`.

**Comment by fdncred** [comment]
ok, thanks.

**Pull request merged**
