### PR TITLE
Fix missing invocation errors

### LINKED ISSUE #1810: Invocation doesn't properly return errors
**Describe the bug**
Argument invocation is swallowing errors it should bubble up to the user.

**To Reproduce**
1. If there isn't a `foo` command available, it should error to call it in an invocation
2. Eg) `echo $(foo)`
3. 

**Expected behavior**
Errors like the above should be show to the user.
**Configuration (please complete the following information):**
 - OS (e.g. Windows): Linux
 - Nu version (you can use the `version` command to find out): 0.14.1
 - Optional features (if any):

### PR DESCRIPTION
**Pull request by cjpearce**
Tests and fixes missing errors from argument invocation.

With this being my first issue for the project, any advice about the fix is welcome.

Fixes #1810

### CODE REVIEW

**Comment by thegedge** [comment]
> With this being my first issue for the project, any advice about the fix is welcome.

Looks good, and you even added a test. No advice to give 🙂

**Comment by thegedge** [comment]
Verified this works 👍

**Comment by thegedge** [comment]
Nice work! 🎉

**Comment by jonathandturner** [comment]
Thank you!

**Pull request merged**
