### PR TITLE
Lex whitespace in input-output types.

### LINKED ISSUE #12264: Multiple output types can't be formatted across multiple lines
### Describe the bug

Multiple output types can't be formatted across multiple lines.

### How to reproduce

```nu
def demo [--verbose]: [
  nothing -> nothing
  nothing -> string
] {
  print demoing
  if $verbose {
    'done'
  }
}
```

### Expected behavior

Parse instead of:

```
Error: nu::parser::unknown_type

  × Unknown type.
   ╭─[entry #1:1:24]
 1 │ def demo [--verbose]: [
   ·                        ┬
   ·                        ╰── unknown type
 2 │   nothing -> nothing
 3 │   nothing -> string
   ╰────
```

### Screenshots

_No response_

### Configuration

| key                | value                                                |
| ------------------ | ---------------------------------------------------- |
| version            | 0.91.0                                               |
| branch             |                                                      |
| commit_hash        |                                                      |
| build_os           | macos-x86_64                                         |
| build_target       | x86_64-apple-darwin                                  |
| rust_version       | rustc 1.76.0 (07dca489a 2024-02-04) (Homebrew)       |
| cargo_version      | cargo 1.76.0                                         |
| build_time         | 2024-03-05 20:28:40 +00:00                           |
| build_rust_channel | release                                              |
| allocator          | mimalloc                                             |
| features           | dataframe, default, extra, sqlite, trash, which, zip |
| installed_plugins  | nu_plugin_explore                                    |

### Additional context

I haven't tried it but my suspicion is this line:

https://github.com/nushell/nushell/blob/cc8f2b6419daa7c5c55fb8ca0ef257fc76be6674/crates/nu-parser/src/parser.rs#L3057

... needs `&[b'\n', b'\r', b',']` as `additional_whitespace`.

### PR DESCRIPTION
**Pull request by texastoland**
# Description

Fixes #12264.

# User-Facing Changes

Multiple input-output types can break across lines like command params.

# Tests + Formatting

✅ E2E parser tests

# After Submitting

### CODE REVIEW

**Comment by sholderbach** [comment]
Regarding tests:

@1Kinoti put some unit tests for `lex_signature` in `/crates/nu-parser/tests/test_lex.rs`
https://github.com/nushell/nushell/blob/9444020f269903c017c6fce4b1d8a6688cac73ad/crates/nu-parser/tests/test_lex.rs#L25-L117
Maybe worth adding your changes here as well for the local testing.


Note that you should probably use `run_test` over the `nu!` macro (because the latter removes newlines and runs the commands with `nu -c` instead of moving them into a that gets executed)

Syntax focussed tests, currently don't seem to have an obvious place:

Best option among:

https://github.com/nushell/nushell/blob/9444020f269903c017c6fce4b1d8a6688cac73ad/src/tests/test_parser.rs#L659-L720

or

https://github.com/nushell/nushell/blob/9444020f269903c017c6fce4b1d8a6688cac73ad/src/tests/test_custom_commands.rs#L229-L242

**Comment by texastoland** [comment]
Thanks I'll add 1 of each now 🙏🏼

**Comment by texastoland** [comment]
> unit tests for `lex_signature` in `/crates/nu-parser/tests/test_lex.rs`

The issue with these is the tests are only testing themselves. The `lex_signatures` arguments are implementation details of parser methods. I'll try refactoring them. Perhaps inline functions?

> Best option among:

Thanks I'll add 1 here too 🙏🏼

**Comment by sholderbach** [comment]
Hot take: As we still want to refactor large parts of the parser or migrate to the architecture tried out in https://github.com/sophiajt/new-nu-parser I don't think we should spend too much effort on unstable parser unit-tests.

If you something in mind to make `lex_signature` more robust in terms of its arguments... PR welcome 😄

**Comment by texastoland** [comment]
> migrate to the architecture tried out in [sophiajt/new-nu-parser](https://github.com/sophiajt/new-nu-parser)

Good call I'm looking forward to that! I'll just include the latter test then.

**Comment by texastoland** [comment]
> Syntax focussed tests, currently don't seem to have an obvious place:

Added ✅

**Comment by sholderbach** [comment]
Mhh not sure what it tries to parse when I give it linebreaks between the type arrow/ type

grafik

**Comment by texastoland** [comment]
Yeah I saw other bugs but didn't consider fixing them. For example this works in release:

```nushell
def demo []: nothing -> nothing] {}
```

It's why I was hesitant to touch it before. It has a kind of lex-parse-lex structure and keeps text around instead of an AST. I can easily fix the 1 above. I'll look into what you found now 🕵🏼‍♂️

The XY problem this solves is IO types quickly become long due to lack of nullable /union/alias/generic types. Imagine a command that expects list or table input or not depending on a flag. It returns a record or not depending on another flag. If typed correctly (I ended up using `any` for now) it was:

```nushell
...: [
  list<path> -> record<old: path new: path>
  table<name: path> -> record<old: path new: path>
  nothing -> record<old: path new: path>
  list<path> -> nothing
  table<name: path> -> nothing
  nothing -> nothign
]
``

**Comment by texastoland** [comment]
@sholderbach PS I fixed that rendering bug in Starship prompt if you update the script!

**Comment by texastoland** [comment]
> @sholderbach The issue is the space here:

This is a preexisting issue and the scope is bigger than I expected. I left a question in #design-discussion and will open a separate PR for:

- Unbalanced bracket error in IO types
- Flexible spacing around type annotations

**Comment by texastoland** [comment]
Can this drop now?

**Pull request merged**
