### PR TITLE
Adjust permissions using `umask` in `mkdir`

### LINKED ISSUE #12161: Access permissions are different for external `mkdir` and nushell's `mkdir`
### Describe the bug

Access permissions are different for external `mkdir` and nushell's `mkdir`. Nushell's `mkdir` is more lenient.
If this is what you intended, feel free to close this issue without worrying about me.

### How to reproduce

1. `mkdir foo`
2. `^mkdir bar`
3. `^ls -lah --color`

### Expected behavior

Create a directory with the same access permission as the external `mkdir` using nushell's `mkdir`.

### Screenshots

image

### Configuration

| key                | value                                                            |
| ------------------ | ---------------------------------------------------------------- |
| version            | 0.91.0                                                           |
| branch             | makepkg                                                          |
| commit_hash        | 3016d7a64ccb2c2eac9f735f6144fc896ea724a5                         |
| build_os           | linux-x86_64                                                     |
| build_target       | x86_64-unknown-linux-gnu                                         |
| rust_version       | rustc 1.76.0 (07dca489a 2024-02-04) (Arch Linux rust 1:1.76.0-1) |
| cargo_version      | cargo 1.76.0                                                     |
| build_time         | 2024-03-06 05:55:14 +00:00                                       |
| build_rust_channel | release                                                          |
| allocator          | mimalloc                                                         |
| features           | dataframe, default, extra, sqlite, trash, which, zip             |
| installed_plugins  |                                                                  |

### Additional context

Maybe related to #12007, #10785

### PR DESCRIPTION
**Pull request by sarubo**
# Description

With this change, `mkdir` mirrors coreutils works. Closes #12161

I referred to the implementation of `mkdir` in uutils/coreutils. I add `uucore` required for implementation to dependencies. Since `uucore` is already included in dependencies of `uu_mkdir`, I don't think there will be any additional dependencies.

# User-Facing Changes

- Directories are created according to `umask` except for Windows.

# Tests + Formatting

I add `mkdir` test considering permissions. The test assumes that the default `umask` is `022`.

# After Submitting

### CODE REVIEW

**Comment by fdncred** [comment]
Looks like your `stat` test is failing. I'm not a huge fan of using externals like this if we don't have to because, as you can see, other operating systems may perform differently. This is why we have several testbin commands. I'm not sure we have one for permissions though. Is there another way around this while still testing it?

**Comment by ysthakur** [comment]
Perhaps you could run just the `mkdir` command in Nushell and then use the `std::fs::metadata` function from Rust to check the permissions?

**Comment by sarubo** [comment]
Thank you for letting me know. I'll try implementing it.

**Comment by fdncred** [comment]
Thanks!

**Pull request merged**
