### PR TITLE
to-json and to-toml output with pretty formatter in default

### PR DESCRIPTION
**Pull request by yjhmelody**
Maybe a new `to-json-pretty` is needed?

### CODE REVIEW

**Comment by jonathandturner** [comment]
I'd add a flag onto `to-json` and `to-toml` so you could call `to-json --pretty` or `to-toml --pretty`

**Comment by jonathandturner** [comment]
You can see examples of adding flags in other commands, like `from-json`

**Comment by yjhmelody** [comment]
@jonathandturner ok! should I close it?

**Comment by jonathandturner** [comment]
@yjhmelody - you can, or you can change it to use flags

**Pull request closed without merging**
