### PR TITLE
refactor html module

### PR DESCRIPTION
**Pull request by pinjeff**
# Description
Previously html 228_themes.json was loaded from a zip file which required the [zip](https://crates.io/crates/zip) crate to extract, this PR just load the json directly and removes the zip crate from the dependencies, this also reduces compile time because we don’t have to build bzip2 (see Cargo.lock)

# Tests

Make sure you've run and fixed any issues with these commands:

- [x] `cargo fmt --all -- --check` to check standard code formatting (`cargo fmt --all` applies these changes)
- [x] `cargo clippy --all --all-features -- -D warnings -D clippy::unwrap_used -A clippy::needless_collect` to check that you're using the standard code style
- [x] `cargo build; cargo test --all --all-features` to check that all the tests pass

### CODE REVIEW

**Comment by fdncred** [comment]
cool. fwiw, when I added the zipped themes, nushell was very large so adding a large json file without compressing it was an impact. that's why I zipped it. now that we're smaller again, it's probably ok to have it without zipping. however, I'd like to know the before and after bin size before landing this.

**Comment by rgwood** [comment]
Nice, this is an awesome first commit. bzip's the 3rd-slowest unit in `cargo build --timings` for me (Windows laptop), so assuming this doesn't regress file size too much it would be a nice win.

**Comment by rgwood** [comment]
`228_themes.json` is 22kb zipped, 130kb unzipped.

**Comment by pinjeff** [comment]
I did some testing on my machine (Windows) to measure the final binary size:
zip file (15,894,016 bytes)
json (15,987,712 bytes)(~94kb larger than zip)
minify json (15,945,728 bytes)(~52kb larger than zip)

we could save 42kb by just minifying the json

**Comment by fdncred** [comment]
if I understand correctly, it seems like we're adding about ~52k to the final binary if we minify the json. That seems reasonable to be considering the boost in compile times. @pinjeff can you make sure the json is minified in your pr?

**Comment by pinjeff** [comment]
I already did that

**Comment by fdncred** [comment]
let's do it. thanks for your effort!

**Pull request merged**
