### PR TITLE
Glob: don't allow implicit casting between glob and string

### PR DESCRIPTION
**Pull request by WindSoilder**
# Description
As title, currently on latest main, nushell confused user if it allows implicit casting between glob and string:
```nushell
let x = "*.txt"
def glob-test [g: glob] { open $g } 
glob-test $x
```
It always expand the glob although `$x` is defined as a string.
This pr implements a solution from @kubouch :
> We could make it really strict and disallow all autocasting between globs and strings because that's what's causing the "magic" confusion. Then, modify all builtins that accept globs to accept oneof(glob, string) and the rules would be that globs always expand and strings never expand

# User-Facing Changes
After this pr, user needs to use `into glob` to invoke `glob-test`, if user pass a string variable:
```nushell
let x = "*.txt"
def glob-test [g: glob] { open $g } 
glob-test ($x | into glob)
```
Or else nushell will return an error.
```
 3 │ glob-test $x
   ·           ─┬
   ·            ╰── can't convert string to glob
```

# Tests + Formatting
Done

# After Submitting
Nan

### CODE REVIEW

**Comment by fdncred** [comment]
nice idea @kubouch and great use of `oneof` @WindSoilder. maybe we should call our next release "The Glob Release" since there were so many glob changes. 🤣

**Comment by kubouch** [comment]
Seems good. Does https://github.com/nushell/nushell/pull/11946 need to be merged as well?

**Comment by WindSoilder** [comment]
They are independent. But yeah, #11946 is ready to review too :)

**Comment by fdncred** [comment]
If this PR and the other one are ready, we need to land these PRs if they're going to make it into the next release. It's getting close to freeze time and we only have a few extra days to test right now.

**Pull request merged**
