### PR TITLE
Added new flag '--all/-a' for Ls, also refactor some code

### LINKED ISSUE #1460: Visibility flags for Ls
**Is your feature request related to a problem? Please describe.**
Running `ls` on `$HOME` can output a lot of rows since a lot of dotfiles and hidden folders reside there. 

**Describe the solution you'd like**
Adding a new flag for `ls`, it would be named `--all/-a` just as its native counterpart on Linux. This flag will show all entries, even the hidden ones and `.` and `..`. Also adding `--almost-all` could be good, this flag will show everything just as `--all` but `.` and `..`.

**Describe alternatives you've considered**
Currently, it's possible to achieve this behavior using pipelines, taking the **"Nu way"**. For example, to emulate the absence of the hypothetical `--all` flag we can do this:

```
ls -s | match name "^[^\.]+$"
```

In my opinion, this is just good, but also it seems to be tedious for the end-user, which may or not be experienced with regular expressions.

**Additional context**
Specifically talking about the design of Nu, which one should be the preferred way to accomplish this? As suggested in [#739](https://github.com/nushell/nushell/issues/739#issuecomment-536657661) may be aliases could handle this, but how?

### PR DESCRIPTION
**Pull request by quebin31**
Closes #1460. 

- Added flag '--all/-a'
- Some clean up on code for `ls` on FilesystemShell

### CODE REVIEW

**Comment by jonathandturner** [comment]
Looks like some clippy warnings. We run clippy on all the code, so you might want to install clippy (I *think* it's `rustup component add clippy` these days) and then run `cargo clean && cargo clippy --all --features=stable`

**Comment by quebin31** [comment]
> Looks like some clippy warnings. We run clippy on all the code, so you might want to install clippy (I _think_ it's `rustup component add clippy` these days) and then run `cargo clean && cargo clippy --all --features=stable`

Yeah, but it's failing on `nu-macros` and I didn't touch any code there.

**Comment by quebin31** [comment]
I've fixed the external errors that were preventing clippy to success.

**Comment by jonathandturner** [comment]
Looks good!

**Pull request merged**
