### PR TITLE
precedence of 'not' operator was '0'

### PR DESCRIPTION
**Pull request by sdderal**
# Description

# User-Facing Changes

# Tests + Formatting

# After Submitting

### CODE REVIEW

**Comment by fdncred** [comment]
We discussed this recently in a team meeting and decided to change it. I'm not sure what it should be changed to though. Thanks for submitting this.

**Comment by kubouch** [comment]
The `not` operator has a wrong precedence and should be changed. The issue can be demonstrated by
```
> (not false) and false
false
> not false and false
true
```

This PR only changes the precedence in a help message, I'm not sure if it fixes the actual problem just changing it in this file. It might require changing it in the parser as well. It would be good to also add a test demonstrating the fix (e.g., the snippet I pasted above).

**Comment by kubouch** [comment]
Possible fix: https://github.com/nushell/nushell/pull/11672

**Comment by fdncred** [comment]
I tested that PR and it seems good to me. I'm closing this one in favor of it. Since `not` isn't really an operator, I'm not sure what to use for the value in `help operators` though.

**Pull request closed without merging**
