### PR TITLE
Add `math exp` command (issue #8661)

### PR DESCRIPTION
**Pull request by lesves**
# Description
I copied the `math ln` command and replaced the relevant parts to implement `math exp`.

# User-Facing Changes

The `math exp` command was added. Now one can do `[1, 2, 3] | math exp` to get e to the power of these numbers.

# Tests + Formatting
I only wrote example tests, same as for `math ln`, which also does not have special tests. I have ran into an issue with the tests but it seems completely unrelated (see #8687)

# After Submitting

This PR was done in order to make the documentation complete, so I'm not adding any documentation except `math ln`.

### CODE REVIEW

**Comment by amtoine** [comment]
just for reference, this is already implemented in the `nu_scripts`.
> see [`math exp`](https://github.com/nushell/nu_scripts/blob/7b6fa05907b3fc1f7b63b1a02653d04582a6d0ab/maths/math_functions.nu#L161-L164)

not that this PR is not legit to land :yum: 
but maybe we should not forget to remove the `math exp` from the `nu_scripts` :wink:

**Review by sholderbach — APPROVED** [review]
Thanks! Looks all good to me

**Comment by amtoine** [comment]
@lesves do you want to remove `math exp` from the `nu_scripts`? :yum:

**Comment by lesves** [comment]
> @lesves do you want to remove `math exp` from the `nu_scripts`? 😋

Uh-huh, thanks... I will put another PR there:)

**Pull request merged**
