### PR TITLE
Add --ignore-errors flag to where

### PR DESCRIPTION
**Pull request by NotLebedev**
# Description

Added `--ignore-errors` flag for `where`. With this flag `where` treats error in row condition or closure as `false` and does not include row in result:

image

image

# User-Facing Changes
New `--ignore-errors` flag for `where` command

# Tests + Formatting

Don't forget to add tests that cover your changes.

Make sure you've run and fixed any issues with these commands:

- `cargo fmt --all -- --check` to check standard code formatting (`cargo fmt --all` applies these changes)
- `cargo clippy --workspace -- -D warnings -D clippy::unwrap_used -A clippy::needless_collect` to check that you're using the standard code style
- `cargo test --workspace` to check that all tests pass

# After Submitting

If your PR had any user-facing changes, update [the documentation](https://github.com/nushell/nushell.github.io) after the PR is merged, if necessary. This will help us keep the docs up to date.

### CODE REVIEW

**Comment by NotLebedev** [comment]
I do not think that this error is correct:
`The example `[{a: 1} {a: 2} {b: 3}] | where --ignore-errors a > 1` demonstrates a transformation of type List(Any) -> Table([("a", Int)]). However, this does not match the declared signature: [(List(Any), List(Any)), (Table([]), Table([]))]. For this command, `vectorizes_over_list` is false and `operates_on_cell_paths()` is false.`
This example does indeed match `(List(Any), List(Any))` signature because table is just a special case of list?

**Comment by fdncred** [comment]
> [{a: 1} {a: 2} {b: 3}]

I thought this was referred to as a `Table` vs a `List` in this context. I could be wrong. I'd look at other examples and see what they say.

**Comment by kubouch** [comment]
I don't think we need a new flag, you can do, e.g., `where {|x| try { $x.a > 1 } catch { false } }`

**Comment by sholderbach** [comment]
I think you can try https://docs.rs/nu-protocol/latest/nu_protocol/struct.Signature.html#method.allow_variants_without_examples I believe this disables some of the checking of the types. Our table type inference is messy.

**Comment by NotLebedev** [comment]
> I don't think we need a new flag, you can do, e.g., `where {|x| try { $x.a > 1 } catch { false } }`

I think this is a bit too lengthy. In this case this goes from `where a > 1` to `where {|x| try { $x.a > 1 } catch { false } }` which is 4 times longer!
Also if `get` has this flag, than I think `where` deserves it as well

**Comment by rgwood** [comment]
> Also if `get` has this flag, than I think `where` deserves it as well

I _think_ the `-i` flag on `get` is something we want to get rid of eventually. There have been [a few attempts](https://github.com/nushell/nushell/pull/7540) to add a `?` modifier to cell paths that would effectively ignore missing data; if we can implement that I'm not sure we'll need `-i` anymore.

**Comment by NotLebedev** [comment]
I think 

> > Also if `get` has this flag, than I think `where` deserves it as well
> 
> I _think_ the `-i` flag on `get` is something we want to get rid of eventually. There have been [a few attempts](https://github.com/nushell/nushell/pull/7540) to add a `?` modifier to cell paths that would effectively ignore missing data; if we can implement that I'm not sure we'll need `-i` anymore.

I don't have any strong feelings about this change. Currently this is useful, but the `?` PR that did not make the cut is a much better idea. You are free to delete this PR.

**Pull request closed without merging**
