### PR TITLE
require variable names to follow additional restrictions

### PR DESCRIPTION
**Pull request by jntrnr**
# Description

Require that variables don't include operators in them. This should allow us to be a bit more friendly with expression parsing in the future.

# Tests

Make sure you've done the following:

- [x] Add tests that cover your changes, either in the command examples, the crate/tests folder, or in the /tests folder.
- [ ] Try to think about corner cases and various ways how your changes could break. Cover them with tests.
- [ ] If adding tests is not possible, please document in the PR body a minimal example with steps on how to reproduce so one can verify your change works.

Make sure you've run and fixed any issues with these commands:

- [x] `cargo fmt --all -- --check` to check standard code formatting (`cargo fmt --all` applies these changes)
- [x] `cargo clippy --workspace --features=extra -- -D warnings -D clippy::unwrap_used -A clippy::needless_collect` to check that you're using the standard code style
- [x] `cargo test --workspace --features=extra` to check that all the tests pass

### CODE REVIEW

**Comment by jjpe** [comment]
I just ran across this.
Does this mean that commands defined with `def` also cannot have `-` in their name?
If they cannot, what happens to commands like `par-each`?
If they can, isn't that inconsistent between locals and command names?

**Comment by sietse** [comment]
Heya @jntrnr 

> This should allow us to be a bit more friendly with expression parsing in the future.

Could you elaborate on this a bit?

Previously, Nu made the following tradeoff:
- Pro: allow easy-to-type hyphens in variable names
- Con: when writing arithmetic, you have to put spaces around the minus (`2-3` gets parsed as a string)
- Con: when writing arithmetic, you can't use the unary minus with a variable (`-$three` gets parsed as a string. `-3` is fine)

Am I correct in guessing that the tradeoff this PR wants to enable / move towards is something like this?
- Con: Require harder-to-type underscores in variable names (hyphens will be parsed as minus operators)
- Pro: In arithmetic, you can write minuses without surrounding spaces
- Pro: In arithmetic, you can use the unary minus with varnames as well as number

I agree that the current parsing situation for unary minuses needs to be improved. Forbidding variable names that start with `-` would be enough allow this.

However, the tradeoff "you can type variable-names-without-hitting-shift, although for arithmetic minus you have to hit spacebar" is very nice to me, and I always felt it was a very user-friendly design choice. Especially in a shell, variable names are a LOT more common than arithmetic.

Would I be correct in thinking that the [Nushell Discord](https://discord.gg/NtAbbGn) is the right place to raise this question?

**Comment by sietse** [comment]
In case it is helpful, I've made a table of various expressions involving the hyphen-minus, and their behaviour in various Nu shells.

In the table below, assume `let six = 6` and `let gzip_flags = "xzvf"`

| Expression                          | Nu <= 0.66               | Nu = 0.67                | Intended future?  | remarks                                      |
| ----------                          | ----------               | ---------                | -------           | -------                                      |
| == variable names ==                |                          |                          |                   |                                              |
| `let hello-word = "Welcome!"`       | ✅ok                     | ❌invalid varname        | ❌invalid varname |                                              |
| `let 4-1 = "Section 4 paragraph 1"` | ✅ok                     | ❌invalid varname        | ❌invalid varname |                                              |
| `let -x = "dash x"`                 | ✅ok                     | ❌invalid varname        | ❌invalid varname |                                              |
| == subtraction ==                   |                          |                          |                   |                                              |
| `let four_minus_one = 4 - 1`        | ✅3                      | ✅3                      | ✅3               |                                              |
| `let four_minus_one = 4-1`          | ❌Unknown command 4-1    | ❌Unknown command 4-1    | ✅3               |                                              |
| `let one_minus_six = 1-$six`        | ❌Unknown command 1-$six | ❌Unknown command 1-$six | ✅-5              |                                              |
| `let six_minus_one = $six-1`        | ❌Unknown varname six-1  | ❌Unknown varname six-1  | ✅5               |
| == unary minus ==                   |                          |                          |                   |                                              |
| `let minus_one = -1`                | ✅-1                     | ✅-1                     | ✅-1              |                                              |
| `let minus_six = -$six`             | ❔"-$six"                | ❔"-$six"                | ✅-3              |                                              |
| `let flags = -$gzip_flags`          | ✅"-xzvf"                | ✅"-xzvf"                | ❔❔❔            | Will minus-before-stringvar error in future? |
| `let minus_six = (0 - $six)`        | ✅-6                     | ✅-6                     | ✅-6              | current workaround for `-$six`               |

**Comment by ehawman** [comment]
So I am attempting to create a custom function that staples [`sharkdp/fd`](https://github.com/sharkdp/fd) onto `rm`.

I couldn't find how to iterate over args so I set out to hard-code each of `fd`'s boolean flags into my script. After banging my head on the [Variables and Subexpressions](https://www.nushell.sh/book/variables_and_subexpressions.html) page for a good while, which *explicitly* uses a hyphenated variable name as a correct example, I stumbled onto this.

So firstly I recognize that this is an extreme edge case and I could almost certainly be doing this in a cleaner way (suggestions welcome, btw).

Secondly I'm putting this here since I believe it's relevant enough to this change that it at least belongs in the discussion (although I'm more than happy to start a new issue if y'all think that's more appropriate.

Thirdly, is there a way for me to maintain parity with `fd`'s flags without breaking everything else?

My hard-coded nonsense is:

``` nush
#!/usr/bin/env nush

def fdrm [
    pattern: string
    --hidden (-H): string           #Search hidden files and directories
    --no-ignore (-I): string        #Do not respect .(git|fd)ignore files
    --case-sensitive (-s): string   #Case-sensitive search (default: smart case)
    --ignore-case (-i): string      #Case-insensitive search (default: smart case)
    --glob (-g): string             #Glob-based search (default: regular expression)
    --absolute-path (-a): string    #Show absolute instead of relative paths
    --list-details (-l): string     #Use a long listing format with file metadata
    --follow (-L): string           #Follow symbolic links
    --full-path (-p): string        #Search full abs. path (default: filename only)
    --version (-V): string          #Prints version information
] {
    if $hidden {
        let pattern = ($pattern | append " --hidden")
    }
    if $no-ignore {
        let pattern = ($pattern | append " --no-ignore")
    }
    if $case-sensitive {
        let pattern = ($pattern | append " --case-sensitive")
    }
    if $ignore-case {
        let pattern = ($pattern | append " --ignore-case")
    }
    if $glob {
        let pattern = ($pattern | append " --glob")
    }
    if $absolute-path {
        let pattern = ($pattern | append " --absolute-path")
    }
    if $list-details {
        let pattern = ($pattern | append " --list-details")
    }
    if $follow {
        let pattern = ($pattern | append " --follow")
    }
    if $full-path {
        let pattern = ($pattern | append " --full-path")
    }
    if $help {
        let pattern = ($pattern | append " --help")
    }
    if $version {
        let pattern = ($pattern | append " --version")
    }
    
    echo $pattern
    #fd $pattern | split row \n | each {|it| rm $it --verbose --interactive} | flatten
}
```

I've tried 
``` nush
def fdrm [
    ...flags: string
] {
    for $flag in $flags {
        let pattern = ($pattern | append $" ($flag)")
    }
    echo $pattern
    #fd $pattern | split row \n | each {|it| rm $it --verbose --interactive} | flatten
}
```

But it doesn't like taking strings with hyphens that aren't actually flags.

Am I SOL?

**Comment by hyiltiz** [comment]
The doc page [0] still refers to `let my-value = 4`; I liked having dash and spaces in my command names, and really hope we could allowlist a few "operators" to show up in variable/function names. A few of those that could be useful: `-!?`, such as `describe-model`, `push-changes!`, `any? is-empty`.

[0] https://www.nushell.sh/book/variables_and_subexpressions.html

**Pull request merged**
