### PR TITLE
Plugin: from_mp4 and UntaggedValue::duration fix

### PR DESCRIPTION
**Pull request by reaganmcf**
This patch introduces a new plugin for reading the metadata from mp4 files. `from mp4` shows a table of metadata including track information, timescale, bitrate, etc.

It also includes a fix for UntaggedValue::duration, which now gets serialized correctly.

### Screenshot
from_mp4 example

### Todo
- [x] Get very rudimentary implementation done
- [x] Finish implementing all of the metadata fields
- [x] Fix `UntaggedValue::duration(mp4.duration())` resulting in crashes
- [x] Cleanup code and tidy up

### CODE REVIEW

**Comment by jonathandturner** [comment]
I know it's still a draft, but figured I'd mention. We check cargo clippy on each PR. You can try it locally with: `cargo clippy --all --features=extra`

**Comment by reaganmcf** [comment]
@jonathandturner Yea that's what I expected from all the failures. I usually fix all the clippy warnings right before I squash all my commits 👍🏻

**Comment by fdncred** [comment]
@reaganmcf Totally not required but it would be cool to see a screenshot in this PR. _Sometimes_ PRs make it to our release blog and screenshots look cool there.

**Comment by reaganmcf** [comment]
I can add it 😀

**Comment by jonathandturner** [comment]
Looks great. Thanks!

And thanks for fixing that serialization bug

**Pull request merged**
