### PR TITLE
add `math min` and `math max` to `bench` command

### PR DESCRIPTION
**Pull request by fdncred**
# Description

This PR adds min and max to the bench command.
```nushell
❯ use std bench
❯ bench { dply -c 'parquet("./data.parquet") | group_by(year) | summarize(count = n(), sum = sum(geo_count)) | show()' | complete | null } --rounds 100 --verbose
100 / 100
╭───────┬───────────────────╮
│ mean  │ 71ms 358µs 850ns  │
│ min   │ 66ms 457µs 583ns  │
│ max   │ 120ms 338µs 167ns │
│ std   │ 6ms 553µs 949ns   │
│ times │ [list 100 items]  │
╰───────┴───────────────────╯
```

# User-Facing Changes

# Tests + Formatting

# After Submitting

### CODE REVIEW

**Comment by maxim-uvarov** [comment]
I'm not sure why `into int | into float` is there. Maybe it is historical artifact that isn't necessary animore

```nu
timeit { do $code } | into int | into float
```

Without it we can get rid of `from ns`

```nu
mean: ($times | math avg | from ns)
```

**Comment by amtoine** [comment]
@maxim-uvarov 
`into int` is to convert the `duration` given by `timeit` to the corresponding number of nanoseconds and `into float` is here to help the `math stddev` not overflow :open_mouth:

**Comment by maxim-uvarov** [comment]
@amtoine got it, thanks

**Comment by fdncred** [comment]
@amtoine are you good with these additions? I think min and max are pretty helpful here.

**Comment by amtoine** [comment]
> @amtoine are you good with these additions? I think min and max are pretty helpful here.
>
yup, it's fine because `mean` and `std` are already there :+1: 

to have my full opinion, i think i would have only selected `times` if i were to write this command again nowadays, letting the user compute statistics at will :rofl: 
because, this begs the question: _why not add the `math median`, `math variance` or even compute the MAD indicator_? :wink:

**Comment by fdncred** [comment]
true. let's move ahead with this. it's just software, we can change it if we want later.

**Pull request merged**
