### PR TITLE
reenable `let-env`

### PR DESCRIPTION
**Pull request by amtoine**
related to
- https://github.com/nushell/nushell/pull/9574

# Description
just in case we need to reenable `let-env` for the patch release, this PR should revert https://github.com/nushell/nushell/pull/9574 so that we can do it quickly.

# User-Facing Changes
### before
```nushell
> let-env foo = "foo"; print $env.FOO
Error: nu::shell::deprecated_command

× Deprecated command let-env
╭─[entry #3:1:1]
1 │ let-env foo = "foo"; print $env.FOO
· ───┬───
·    ╰── 'let-env' is deprecated. Please use '$env.<environment variable> = ...' instead.
╰────
```
```nushell
> $env.BAR = "bar"; print $env.BAR
bar
```

### after
```nushell
> let-env FOO = "foo"; print $env.FOO
foo
```
```nushell
> $env.BAR = "bar"; print $env.BAR
bar
```

# Tests + Formatting
- :green_circle: `toolkit fmt`
- :green_circle: `toolkit clippy`
- :black_circle: `toolkit test`
- :black_circle: `toolkit test stdlib`

# After Submitting

### CODE REVIEW

**Comment by hustcer** [comment]
I personally prefer the new syntax

**Comment by amtoine** [comment]
> I personally prefer the new syntax, I don't think it's a good idea to reenable it
>
agree :+1:

**Comment by sholderbach** [comment]
This is purely as a mitigation for #9812. Thanks for preparing it @amtoine

**Comment by sholderbach** [comment]
As `starship` as the main remaining integration is now released we can skip this step https://github.com/starship/starship/issues/5338

**Comment by CarterLi** [comment]
Do we still support zoxide?

```
    ╭─[C:\Users\zhang\.zoxide.nu:8:1]
  8 │ # Initialize hook to add new entries to the database.
  9 │ if (not ($env | default false __zoxide_hooked | get __zoxide_hooked)) {
    · ─┬
    ·  ╰── expected def, def-env, extern, alias, use, module, export or export-env keyword
 10 │   let-env __zoxide_hooked = true
    ╰────
```

**Pull request closed without merging**
