### PR TITLE
Add CustomValue support to plugins

### PR DESCRIPTION
**Pull request by Mathspy**
# Description

See https://github.com/nushell/nushell/pull/6070#issuecomment-1193234554 for up to date status

Builds on top of https://github.com/nushell/nushell/pull/6064 and https://github.com/nushell/nushell/pull/6065 an initial vision of how support for CustomValues could be achieved in plugins
~~This is not complete and I am currently stuck on something that might require some shuffling of responsibility so I decided to make this draft PR to ask firstly if this direction makes sense, and if yes how can I resolve the following issue:~~

~~This PR adds a new variant to `PipelineData`: `PluginData`, the variant is meant to hold an opaque blob of data passed from a plugin, it's currently implemented as a `serde_json::Value` for the sake of debugging but switching over to `Vec<u8>` ought to be simple.~~
~~The idea behind adding the new variant is that the engine has two things it can potentially do with a bunch of `PluginData`:~~
1) ~~It can send it back to the plugin in a pipeline chain i.e: `custom-plugin abc | custom-plugin xyz` where the call to `xyz` would get back the exact `CustomValue` it passed to the engine~~
2) ~~It can _collapse_ the value if it needs to display it or pass it to a non-plugin. Collapsing is done by calling the plugin and asking it to return back a non-`CustomValue`~~

~~Sending back is easy and already added in this PR (though not fully tested yet). Meanwhile the value collapsing plugin infrastructure is already in place but _calling_ that infrastructure is proving to be tricky, because the places where it needs to be called are `PipelineData` methods; `PipelineData` is defined in `nu-protocol` which is depended upon by `nu-plugin`, so we can't depend on `nu-plugin` from `nu-protocol` because that would cause a cyclic dependency 😞 ~~

~~Not sure what direction to go from here, or if this direction is a bad idea in first place. Theoretically if one were to merge `nu-protocol` and `nu-plugin` this ought to work, but I don't think that's very reasonable and I would need the team's approval. Maybe there's something much easier that I am missing, please do point it out if so!~~

cc @elferherrera

### CODE REVIEW

**Comment by elferherrera** [comment]
I'm wondering if instead of creating an extra PipelineData we use a Value::Custom to store the binary information.

**Comment by Mathspy** [comment]
> I'm wondering if instead of creating an extra PipelineData we use a Value::Custom to store the binary information.

Hmmm I thought about that, we would need a way of distinguishing CustomValues that can be handled by the engine itself and one’s that have to be sent to the plugins nonetheless, though. And we’d still need a way to call the plugin from nu-protocol when collapsing the custom variables

**Comment by elferherrera** [comment]
I think plugins will be the only ones that can have access to this PluginData custom value. When receiving the data from the plugin the deserialiser puts the data directly in a custom value and store it until it is sent to another plugin. Each plugin will know how to deal with it

**Comment by fdncred** [comment]
@elferherrera @Mathspy This isn't too old yet, but was wondering if we're still working on this?

**Comment by elferherrera** [comment]
@fdncred Yeap. We are still working on it

**Comment by Mathspy** [comment]
This is now ready to go! There are a couple of open questions still and some interesting thoughts I had while working on this PR

# Open questions
- What format should we use to handle serializing structs to Vec<u8>? It needs to be schemaless if we want to keep the same user experience for plugin authors. Currently I picked bincode since it's the most popular choice in the ecosystem for this but it's by no means my favorite, it tends to handle errors poorly.
- When calling `plugin-1 | plugin-2` or when calling `open-db file.db | plugin`, in both cases we have a `CustomValue` that the next thing in the pipeline can't handle and we will send it over and wait for a `"plugin failed to decode Xyz"` errors. This is not ideal, should we collapse (AKA turn into base value, sorry I invented the word collapse lol) the `CustomValue`s before sending them to something we know can't handle them?
  The only issue I see with this is if the ecosystem grows and 2 plugins are relying on a shared library that defines a `CustomValue`, they _could_ communicate together if we keep the current implementation so long as they are using compatible versions of that shared library. This however means that plugins and the main engine's `CustomValue`s will often need some kind of "collapse" command so that people can call that manually when they are trying to send the collapsed value of the next thing in the pipeline instead of a `CustomValue` that the thing can't handle

# Interesting thoughts

After working on this for a while I realized this PR is by no means incompatible with the idea in https://github.com/nushell/nushell/pull/6077. If a plugin wants to send a binary blob to the engine, it totally could! We currently _could_ just `impl CustomValue for PluginData` and basically get this for the cost of an extra serialization and deserialization! A plugin could even define its own `Blob` CustomValue and not use our `PluginData` type at all (Still has to be pay the extra serialization cost however)
If we care about the serialization cost we could do a neat trick of storing a special byte at the beginning of the `Vec<u8>` if it's a `PluginData` that doesn't need further serialization or a different special byte if it's a `CustomValue` that needs further serialization (and error if the first byte is anything else). THE POWER OF RAW BYTES!

The gist of the matter is, plugins are capable of sending and receiving `Vec<u8>`s now. `serve_plugin` is the one doing all the `CustomValue` shenanigans that's involving bincode into the equation, in another language (like Python) the `serve_plugin` can just send and receive `Vec<u8>`s without any magic and error if `CallInfo` is `::CollapseCustomValue`. And of course we can have a `serve_plugin_without_custom_values` in Rust that does the same thing! The current magical `serve_plugin` doesn't even have to be part of `nu_plugin` crate at all!
I don't personally have a use case for sending and receiving blob-like `Vec<u8>`s from a plugin hence why I didn't do any of that and just kept `serve_plugin` with all its newly found magic and didn't `impl CustomValue for PluginData`. I totally don't mind keeping the default `serve_plugin` simple and creating my own `serve_plugin_with_magic` from my own plugins though!

**Comment by elferherrera** [comment]
Thanks a lot for this effort. 

If I understand correctly your are using bincode to serialise and deserialise PluginData, which is only a Vec<u8> and a span. If you don't store the span, do you still need bincode? 
And also, why do you need to span in the data?

**Comment by Mathspy** [comment]
> If I understand correctly your are using bincode to serialise and deserialise PluginData

To be more precise, `bincode` is being used to serialize and deserialize `CustomValue`s to `Vec<u8>`, the deserialization requires that the plugin uses `typetag` and mark their `impl CustomValue` with it

> If you don't store the span, do you still need bincode?

Would still be needed, `bincode` is needed _only_ for the current `CustomValue` magic. There _are_ other ways to support `CustomValue`s like creating a new `PluginCustomValue` trait for use by plugins which has the exact same required methods but also requires two extra `serialize(&self) -> Vec<u8>` and `deserialize(data: Vec<u8>) -> Self` (or maybe it just requires `CustomValue + Read + Write`). But then we'd probably need a `PluginValue` that has `Value::CustomValue<dyn PluginCustomValue>` instead of `dyn CustomValue`
There are _many_ ways to go about how `serve_plugin` treats `Value::CustomValue`, the simplest `serve_plugin` could just error if `dyn CustomValue` is anything but `PluginData`! The neat thing about current implementation is it's able to reuse the exact same types and even traits as the main engine and all it requires from plugin authors is to put `#[typetag::serde]` on top of their `impl CustomValue` and they will just work!

I am mostly storing the Span because all the other datatypes store ones and pass it back to the engine 🤷‍♀️ I understand what `Span`s are used for (errors) but I don't actually understand when are we supposed to preserve them and when do they become no longer relevant and we can drop them.

**Comment by Mathspy** [comment]
Here's a quick draft of a `plugin_serve` that moves the responsibility of deserialization and serialization to the plugin at the cost of no longer being able to define `CustomValue`s inside of plugins, requires no modification to any code besides `plugin_serve` itself!

```rs
#[derive(Debug, Serialize, Deserialize)]
struct Bytes(Vec<u8>);

#[typetag::serde]
impl CustomValue for Bytes {
    fn clone_value(&self, span: Span) -> Value {
        Value::CustomValue {
            val: Box::new(Self(self.0.clone())),
            span,
        }
    }

    fn value_string(&self) -> String {
        self.typetag_name().to_string()
    }

    fn to_base_value(&self, span: Span) -> Result<Value, ShellError> {
        unimplemented!("bytes can't be converted to base value")
    }

    fn as_any(&self) -> &dyn std::any::Any {
        self
    }
}

pub fn serve_plugin_without_generic_custom_value_support<F>(
    plugin: &mut impl Plugin,
    encoder: impl PluginEncoder,
    collapser: F,
) where
    F: Fn(Vec<u8>, Span) -> Result<Value, ShellError>,
{
    let mut stdin_buf = BufReader::with_capacity(OUTPUT_BUFFER_SIZE, std::io::stdin());
    let plugin_call = encoder.decode_call(&mut stdin_buf);

    match plugin_call {
        Err(err) => {
            let response = PluginResponse::Error(err.into());
            encoder
                .encode_response(&response, &mut std::io::stdout())
                .expect("Error encoding response");
        }
        Ok(plugin_call) => {
            match plugin_call {
                // Sending the signature back to nushell to create the declaration definition
                PluginCall::Signature => {
                    let response = PluginResponse::Signature(plugin.signature());
                    encoder
                        .encode_response(&response, &mut std::io::stdout())
                        .expect("Error encoding response");
                }
                PluginCall::CallInfo(call_info) => {
                    let input = match call_info.input {
                        CallInput::Value(value) => value,
                        // Instead of turning CallInput::Data into a CustomValue defined inside of
                        // the plugin we turn it into Vec<u8>, we will leave the plugin to deal
                        // with it as it pleases
                        CallInput::Data(plugin_data) => Value::CustomValue {
                            val: Box::new(Bytes(plugin_data.data)),
                            span: plugin_data.span,
                        },
                    };

                    let value = plugin.run(&call_info.name, &call_info.call, &input);

                    let response = match value {
                        Ok(Value::CustomValue { val, span }) => {
                            // Once we have a CustomValue from a plugin response, we will make sure
                            // that it's a Vec<u8> because that's the only CustomValue our plugin
                            // is allowed to return
                            match val.as_any().downcast_ref::<Bytes>() {
                                Some(Bytes(data)) => PluginResponse::PluginData(
                                    "Bytes".to_string(),
                                    PluginData {
                                        data: data.clone(),
                                        span,
                                    },
                                ),
                                None => panic!("CustomValue that's not bytes"),
                            }
                        }
                        Ok(value) => PluginResponse::Value(Box::new(value)),
                        Err(err) => PluginResponse::Error(err),
                    };
                    encoder
                        .encode_response(&response, &mut std::io::stdout())
                        .expect("Error encoding response");
                }
                PluginCall::CollapseCustomValue(plugin_data) => {
                    // When we receive a request to collapse a value, we just pass it wholesale
                    // to the plugin to deal with, a plugin can define a collapser as
                    // |_, span| Value::String { val: "<MyPluginData>".to_string(), span }
                    // this way it acts how you envision PluginData custom value to act
                    //
                    // Another plugin meanwhile could deserialize the Vec<u8> and give some kind
                    // of real value
                    let response = collapser(plugin_data.data, plugin_data.span)
                        .map(Box::new)
                        .map_err(LabeledError::from)
                        .map_or_else(PluginResponse::Error, PluginResponse::Value);

                    encoder
                        .encode_response(&response, &mut std::io::stdout())
                        .expect("Error encoding response");
                }
            }
        }
    }
}
```

**Comment by fdncred** [comment]
> at the cost of no longer being able to define CustomValues inside of plugins

don't we want to be able to define CustomValues in plugins?

**Comment by Mathspy** [comment]
I do! I want to be able to define my own `CustomValue`s in plugins. And that’s what this PR does, see the nu_plugin_custom_value for an example of that in action!

But to achieve that a key component is some way of turning `CustomValue` into a `Vec<u8>` and back again, this is where bincode or any other Serde-powered byte-producing schema-less format is needed for.
The above example demonstrates that the main engine does not actually care about how plugins generate or handle Vec<u8> and that in another language (like Python, or even Rust if a plugin doesn’t care about CustomValues but wants to send and receive binary blobs) where you can’t implement CustomValue, you still have access to sending and receiving bytes that you can do anything you want with! I am not much of a Pythonista myself but I think `struct.pack()` could be used

**Comment by Mathspy** [comment]
> Or are you saying that this is a new feature that allows one to do things a little different _IF_ they want to do it that way?

Pretty much, yes. To be more specific I am saying the default `serve_plugin` could be the one I wrote in the comment above, this removes the dependency on `bincode`, we could then have `serve_plugin_with_custom_values` that does what the one in the current code does and hide it behind a `custom_values` feature which brings in the `bincode` dependency

We could even have
```rs
pub fn serve_plugin_with_custom_values<S, D>(
    plugin: &mut impl Plugin,
    encoder: impl PluginEncoder,
    serialize: S,
    deserialize: D,
) where
    S: Fn(&Box<dyn CustomValue>) -> Result<Vec<u8>, ShellError>,
    D: Fn(&[u8]) -> Result<Box<dyn CustomValue>, ShellError>,
```

If we want to leave the choice of the `CustomValue -> Vet<u8>` format to the users!

And the users _can_ make their own `serve_plugin`s as well! I just don't know what the team thinks is a good default, I don't mind any default personally because I can always make my own `serve_plugin` that behaves in the specific way I want

**Comment by elferherrera** [comment]
Im kind of inclined on leaving the serialisation to the plugin creator. That way they could have more flexibility on the whole process.

I'll check the PR more carefully later tonight but it already looks amazing

**Comment by Mathspy** [comment]
> Im kind of inclined on leaving the serialisation to the plugin creator. That way they could have more flexibility on the whole process.

Yep I agree that makes sense, feel free to give me signatures and desired behavior for the default `serve_plugins` and I will update them acorrdingly! Maybe the default serve_plugin can error on all CustomValues and we can have another one with the signature in my last comment?

> I'll check the PR more carefully later tonight but it already looks amazing

Thank you ❤️

**Comment by elferherrera** [comment]
It all looks good. I think we cannot scape the bincode dependency so let's leave it for the time being. I left a comment about sending any CustomValue to a plugin. I think we should allow this, but if you have identified a use case for it we can leave it

**Pull request merged**
