### PR TITLE
Make sum plugin as internal command.

### PR DESCRIPTION
**Pull request by andrasio**

### CODE REVIEW

**Comment by thegedge** [comment]
When do we go plugin versus internal? Not sure if we've answered that question anywhere? I don't think we have, because I'm pretty sure I've seen others ask this question and I couldn't get an answer for them 🙂

**Comment by jonathandturner** [comment]
@thegedge - good question! I was leaning towards "if it's generally useful, let's make it a command", but definitely wondering what other people think

**Comment by thegedge** [comment]
> "if it's generally useful, let's make it a command"

My only problem is that "useful" is very subjective. For example, it's likely that there will be someone who uses `ps` regularly, far more than they use `sum`. That person would consider `ps` more useful than `sum` 🙂

I'd love for this decision to have low cognitive overhead, so if we had guidelines that were a little more objective, that would be 💯.

**Comment by jonathandturner** [comment]
Yeah, +1 from me.

The only reasons `ps` isn't built in is for portability and it requires async/await, and we didn't have a good way to do the latter until more recently.  We could make it a command behind a feature flag.

**Pull request merged**
