### PR TITLE
Use PWD if present to set path on startup

### LINKED ISSUE #2649: New terminal opens always in home directory when called from Tilix
**Describe the bug**
When a terminal is open to some directory in Tilix and I open a new one, bash and zsh will open it in the same directory as the previous terminal, but after setting Nushell as the default it always opens in home directory.

**To Reproduce**
1. Install tilix
2. Set nushell as the default shell with `chsh`
3. Open terminal in tilix
4. Navigate to some directory
5. Call New Terminal (`ctrl+shift+a` in my case)

**Expected behavior**
New terminal opens in the same directory as the previous one.

**Configuration (please complete the following information):**
 - OS (e.g. Windows): Ubuntu 20.04
 - Nu version (you can use the `version` command to find out): 0.20

### PR DESCRIPTION
**Pull request by zbraniecki**
Attempt to fix #2649.

### CODE REVIEW

**Comment by jonathandturner** [comment]
Seems good. You'll need to run through `cargo fmt` to pass the formatting check, but otherwise looks okay.

**Comment by jonathandturner** [comment]
@zbraniecki  - are you still interested in working on this?

**Comment by zbraniecki** [comment]
I don't think this patch fixes #2649 fully. Do you think its worth landing even if partial?

**Comment by jonathandturner** [comment]
@zbraniecki - I think it might be better to land a full fix for this one, as it seems it should be fix-able.

There's an environment syncer that we use to handle environment variables that come into Nushell from outside. I wonder if we should update that and use the environment that it produces.

Happy to help mentor a fix if you're interested.

**Comment by zbraniecki** [comment]
I failed to find a way to achieve the experience and I think we should fix it once we understand how. I'm also not very available to tinker with that for the next month or so, so I'd prefer if someone took it over from me.
If that won't happen I may look at it the next time I get frustrated and have cycles :)

**Comment by ilius** [comment]
I think this probably should be fixed in `tilix`.

**Comment by ilius** [comment]
https://dlang.org/library/std/process/execute.html
There is a workDir argument!

**Comment by jonathandturner** [comment]
Going ahead and closing as this is now out of date with the current codebase.

**Comment by vadixidav** [comment]
> I think this probably should be fixed in `tilix`.
> 
> LXTerminal and xfce4-terminal also work, from bash to nu, and sh to nu!
> 
> I think the terminal should set the current directly when running / forking the shell.
> 
> I'm not familiar with D language.
> But Python has such feature when running a process: subprocess.Popen has cwd argument.

I noted this in the issue as well, but it isn't clear if just fixing it in `tilix` is the right solution. Gnome also uses PWD to indicate where to open when starting a terminal in a particular directly from the file manager. It may be that this is an unspoken standard that exists, which other shells are using.

**Pull request closed without merging**
