### PR TITLE
run Nushell with the default config files in the CI

### PR DESCRIPTION
**Pull request by amtoine**
# :warning: WIP => this PR will be rebased when done

related to
- https://github.com/nushell/nushell/pull/10038
- https://github.com/nushell/nushell/pull/10052

# Description
the CI did not catch the breaking change from https://github.com/nushell/nushell/pull/10038, which is a problem.

this PR aims at adding the default config files to the CI to catch issues with it.

## :warning: WIP
for now i just want to run the CI and see if it fails.
because this PR is based on a commit **before** the fix of https://github.com/nushell/nushell/pull/10052, it should fail.

# User-Facing Changes

# Tests + Formatting
for now, the test is running in the `std-lib-and-python-virtualenv` job, to reuse the `cargo install`.

# After Submitting

### CODE REVIEW

**Comment by amtoine** [comment]
"blah blah WIP, it's a WIP do not merge" => @amtoine please make this a draft already!! :laughing:

**Comment by amtoine** [comment]
closing this as it's been there for a while...
feel free to reopen and build upon :relieved:

**Comment by sholderbach** [comment]
What kept this one in the draft stage? Would be great to have something like this! Very possible that it got under the rug due to failing CI on the PR?

**Comment by amtoine** [comment]
@sholderbach 
to be honest i don't remember at all :open_mouth:

**Pull request closed without merging**
