### PR TITLE
Fix drop nth bug

### PR DESCRIPTION
**Pull request by onthebridgetonowhere**
# Description

This should fix the `drop nth bug` and close the issue #5260 

# Tests

Make sure you've run and fixed any issues with these commands:

- [x] `cargo fmt --all -- --check` to check standard code formatting (`cargo fmt --all` applies these changes)
- [x] `cargo clippy --all --all-features -- -D warnings -D clippy::unwrap_used -A clippy::needless_collect` to check that you're using the standard code style
- [x] `cargo build; cargo test --all --all-features` to check that all the tests pass

### CODE REVIEW

**Comment by onthebridgetonowhere** [comment]
I am not sure if `drop` is supposed to work only on list, range, and tables. Should `drop nth` work on streams?

**Comment by elferherrera** [comment]
What would be an example of working with a stream?

**Comment by onthebridgetonowhere** [comment]
> What would be an example of working with a stream?

I am not familiar with streams, so I honestly do not know. From my basic understanding, this would not really work with streams?

I was just thinking that I changed quite a bit from the original implementation. Particularly, now there are specific checks for the input to be of  `List` and `Range` types, thus making it throw an error if the input is not one of those two types.

Would you do something different? I am not 100% if cloning the input part to figure out the input's size - Line 121 and 122 -- in the Range pattern matching code is the right way.

**Comment by elferherrera** [comment]
I also dont think that it could work with streams, but probably JT could comment on that

**Comment by jntrnr** [comment]
If we do the `into_value` step, it'll collect the stream into a single value. For really long/infinite streams, that'd be a problem.

I think we'd need something similar to what was there before, with a new iterator that will handle the skipping but otherwise passes values through. Actually, we may want to match on the input, and see what type of thing it is at the top level. If it's a List or Stream, we could apply the `skip nth` logic.

**Comment by onthebridgetonowhere** [comment]
thanks @jntrnr I will try to rewrite it asap.

**Comment by fdncred** [comment]
@onthebridgetonowhere any update on this?

**Comment by onthebridgetonowhere** [comment]
@fdncred struggling to find time to work on it. I'll try it out tonight or in the weekend! Thanks for the patience. If you have a fix already, feel free to go ahead and push it upstream!!

**Comment by onthebridgetonowhere** [comment]
@jntrnr I rewrote some parts of the code and added checks for different types of Values. I do not know how the streams work, so I need some direction there. We cannot consume all the stream, but should the first "x" elements be consumed so to know which ones to drop, where X is the given drop range? (e.g., drop nth 1..5, X=5; or drop nth 1 0 4 3, X=4).

**Comment by onthebridgetonowhere** [comment]
I changed the code again as I think I found a more elegant way to check if an upper bound is given or not. Essentially, we only care when there is no upper bound given, and that semantically means that we only take the first X elements, and drop the rest, where X is the lower bound range given from input. 

@stormasm - would you mind taking a look at the code? I remember you ported the initial version of `drop nth`. 
@fdncred  - I think this should be ready now, though I'd appreciate another pair of eyes on it. 

Thanks for patiently waiting for this fix.

**Comment by stormasm** [comment]
LGTM Thanks for hanging in there and getting this working ! 😄

**Pull request merged**
