### PR TITLE
fix: ✨ "saner" default for mv

### LINKED ISSUE #6747: `mv -f` switch highly desired, so as to not overwrite files by default
### Related problem

_No response_

### Describe the solution you'd like

Basically, `mv` in this shell currently seems to act like `mv -f` in other shells, which seems unusually dangerous for a program intended to be interacted with by humans. Basically, I think the `-f` (`--force`) switch should be added to `mv` for cases of overwriting.

Here's an example of something I was writing that would rename a bunch of images to just sequential numbers. See if you can spot the massive data loss problem that a `-f` switch would probably have prevented.
```
ls | sort-by modified | get name | each -n {|e| mv $e.item ($e.index + 1 | into string | $in + '.jpg' )};
```

### Describe alternatives you've considered

_No response_

### Additional context and details

_No response_

### PR DESCRIPTION
**Pull request by melMass**
# Description

fixes #6747

As highlighted in the issue, the default behavior of nu currently
is to overwrite the destination file without notice.
This is not a "standard" expectation users that want this behavior
can create a dedicated alias.

# Tests

Make sure you've done the following:

- [x] I did not find any tests for mv ~~Add tests that cover your changes, either in the command examples, the crate/tests folder, or in the /tests folder.~~
- [x] Try to think about corner cases and various ways how your changes could break. Cover them with tests.
- [x] If adding tests is not possible, please document in the PR body a minimal example with steps on how to reproduce so one can verify your change works.

Make sure you've run and fixed any issues with these commands:

- [x] `cargo fmt --all -- --check` to check standard code formatting (`cargo fmt --all` applies these changes)
- [x] `cargo clippy --workspace --features=extra -- -D warnings -D clippy::unwrap_used -A clippy::needless_collect` to check that you're using the standard code style
- [x] `cargo test --workspace --features=extra` to check that all the tests pass

# Documentation
Yes, see nushell/nushell.github.io/pull/648
- [x] If your PR touches a user-facing nushell feature then make sure that there is an entry in the documentation (https://github.com/nushell/nushell.github.io) for the feature, and update it if necessary.

### CODE REVIEW

**Comment by melMass** [comment]
Oops the CI did catch errors, not sure why I did not see those tests locally my bad
image

**Comment by melMass** [comment]
Im not sure why but locally I can't get to trigger those errors, looking closer into it it seems to silently fail

image

image

**Comment by webbedspace** [comment]
>I did not find any tests for mv

Uhhhhhh… shouldn't this sentence be extremely alarming?

I'd at least add one test for just the new `-f`, even if it means committing a whole new file.

**Comment by rgwood** [comment]
Thank you! Looks good to me, I agree that this is much safer+saner behaviour than before.

If you have time, would you mind documenting this breaking change in the blog post/release notes for the upcoming v0.71 release? https://github.com/nushell/nushell.github.io/pull/647

**Comment by rgwood** [comment]
I think we generally like this change but it might be good to add some more tests. @sholderbach had some ideas/requests for testing, @sholderbach do you mind elaborating here?

**Comment by webbedspace** [comment]
I just had a thought… maybe not in this PR, but do you think you could add a similar flag for `save` when it doesn't have `-a`? I looked up the zsh `NOCLOBBER` setting, and not only does it protect `mv`, but also piping to a file (Nushell equivalent being `save`).

**Comment by melMass** [comment]
Nice! @rgwood , yes I can PR the change in the 0.71 release branch, I guess this should be listed in "breaking changes" ?

**Comment by melMass** [comment]
> also piping to a file (Nushell equivalent being `save`).

This sound like something I can handle! Can you open a dedicated issue ?

**Comment by sholderbach** [comment]
I like the change and being more defensive is definitely a good default. GNU coreutils `mv file fileexists` will allow overwriting regular files but they don't seem to document their rules publicly. (The comments in https://github.com/nushell/nushell/issues/6920 hint to me that after landing this change we might still want to provide the people who want to live dangerous with a config option to go silent in some common cases)

The only question for testing I would have, are we safely prohibiting overwriting non-empty directories after this change? Generally I think in this case for testing it is more important that we test, that we don't cause unintended data loss for the users. I think for files you got us covered.

**Comment by melMass** [comment]
Nice! 
I'll check this case and if it's needs an extra test later today!

**Comment by melMass** [comment]
After trying to come up with a new test I'm actually unsure what you meant Sholder?
mv to an existing folder moves it inside it, I'm not sure of the case you had in mind.

**Comment by sholderbach** [comment]
@melMass you are correct, all other cases I was wondering about (moving a folder on a file etc.) are covered by tests and protected.
So I am happy to merge it and get ready for user feedback.
Would you mind adding the breaking change to the release notes branch of our documentation/blog? 
https://github.com/nushell/nushell.github.io/blob/release-notes-0.71/blog/2022-11-08-nushell-0.71.md

**Comment by melMass** [comment]
>  Would you mind adding the breaking change to the release notes branch of our documentation/blog?

@sholderbach  I usually leave that out to better PR people 😅  as english is not my main language, but I drafted it here:
https://github.com/nushell/nushell.github.io/pull/653/files

**Comment by sholderbach** [comment]
Thanks! Looks perfectly understandable! and people on the internet will be happy to correct any mistakes :P

**Comment by dandavison** [comment]
> "saner" default
> This is not a "standard" expectation users that want this behavior

I'm a bit confused by this PR. UNIX and Linux behavior has always been for commands such as `mv` and `cp` to overwrite destination files with the same name.

**Comment by webbedspace** [comment]
Every zsh guide I've seen tells you to turn the NOCLOBBER setting on (which is the equivalent to this) so if that isn't demand, I don't know what is.

**Comment by dandavison** [comment]
For people who've been using Unix/Linux for a long time, this is very unexpected behavior. There is another argument against this default: for people whose jobs require them to use command-line interfaces in critical production contexts, it is important that they do NOT get accustomed to `NOCLOBBER` behavior.

As @sholderbach mentioned above, I think we really want a config option controlling this, since it's a bit awkward in Nushell currently to override a default while retaining control over the rest of the command, i.e. there's no way to do the equivalent of

```python
def mv(**kwargs):
    stdlib.mv(force=True, **kwargs)
```

**Comment by webbedspace** [comment]
Well, `rm` does have those two flags and one config setting that control trashing vs. erasing… so it's not unprecedented…

**Comment by dandavison** [comment]
Also we should bring `cp` into line with `mv` -- currently `cp` clobbers by default and lacks a `--force` option.

> Well, rm does have those two flags and one config setting that control trashing vs. erasing

I didn't quite follow what you were saying here.

**Comment by webbedspace** [comment]
Y'know, this:
```
  rm: {
    always_trash: true # always act as if -t was given. Can be overridden with -p
  }
```

**Pull request merged**
