### PR TITLE
Send LSP Completion Item Kind

### PR DESCRIPTION
**Pull request by schrieveslaach**
# Description

This commit fills in the completion item kind into the `textDocument/completion` response so that LSP client can present more information to the user.

It is an improvement in the context of #10794

# User-Facing Changes

Improved information display in editor's intelli-sense menu

output

### CODE REVIEW

**Comment by schrieveslaach** [comment]
@fdncred, do you mind to check out some TODO comments, e.g. [here](https://github.com/nushell/nushell/pull/11443/files#diff-8faa418ca3af7012f50b5e447bc7d1fe648e0c7afbb009ec1b191cb1bd22ea4cR484), in order to clarify what kind of [kind](https://docs.rs/lsp-types/latest/lsp_types/struct.CompletionItemKind.html) Nushell could send in these cases.

I'm not so familiar with the completion code deep down in Nushell.

**Comment by fdncred** [comment]
I'm not familiar with code completion either. Sorry. Here's my guess.

> // TODO: can we assume that this is kind VALUE?

x is definitely a nushell enum Value here and Value can be any nushell datatype. when it's calling as_string() it's this function, so it's a limited set of nushell values.
https://github.com/nushell/nushell/blob/21b3eeed99b3beb45b10a266ec05f4eabf897796/crates/nu-protocol/src/value/mod.rs#L312-L336

> / TODO: can we assume that this is kind RECORD or STRUCT?

the match for as_record is ensuring this is a nushell record. this is the function so I think we can be pretty sure it's a record.
https://github.com/nushell/nushell/blob/21b3eeed99b3beb45b10a266ec05f4eabf897796/crates/nu-protocol/src/value/mod.rs#L403-L413

I'm not exactly sure how we map to `CompletionItemKind` though. Some things seem obvious, like we have these:
TEXT would be Value::String
METHOD might be a subcommand?
FUNCTION is probably a custom command
FIELD might be an element of a Value::Record
VARIABLE would be a variable
MODULE might be a module like when you `use modulename.nu`
UNIT would maybe be like Value::Filesize such as KB or KiB and durations like sec, min
VALUE would be value?
KEYWORD we have keywords although they're not really called out like if, for, let
CONSTANT we have const's
OPERATOR we have operators
TYPE_PARAMETER I guess this could be the type annotation of custom command parameters?


Not supported I guess?
CLASS
INTERFACE
PROPERTY
ENUM
SNIPPET
COLOR - we have colors but not a color type
FILE - we have SyntaxShape::Filepath i think but not Value::Path
REFERENCE
FOLDER
ENUM_MEMBER
STRUCT
EVENT

Nushell Types
https://github.com/nushell/nushell/blob/21b3eeed99b3beb45b10a266ec05f4eabf897796/crates/nu-protocol/src/ty.rs#L11-L36

Nushell Values
https://github.com/nushell/nushell/blob/21b3eeed99b3beb45b10a266ec05f4eabf897796/crates/nu-protocol/src/value/mod.rs#L44-L155

**Comment by fdncred** [comment]
I worry about this PR because I'm not sure if we have 100% code coverage in tests and this PR is changing a lot of completion files. I'm not saying it's not right. I'm just saying it makes me nervous.

**Comment by schrieveslaach** [comment]
@fdncred, I share your worries and therefore, I made my changes the least invasive as possible. I also updated the code and added some LSP tests.

**Comment by fdncred** [comment]
@schrieveslaach would you mind fixing the conflicts? i'd love to get this in soon.

**Comment by Feel-ix-343** [comment]
Hey, I have been thinking about Kinds recently and closed a PR realizing you had already started one.

Correct me if I'm wrong, but do we want to couple all of nushell completions to LspTypes? My intuition is that LspTypes should be only used in the LSP crate. To do this, we could possibly implement a completer in the lsp crate, instead of reusing the cli completer. 

Beyond the scope of this PR, though, the nushell cli could benefit from giving completion kinds as well. If we were to do this, I feel it would be best to create our own kind type in the cli completer, then implement From for Lsptypes completion kind. 

Let me know what you all think

**Comment by fdncred** [comment]
It would be nice to isolate these changes to nu-lsp if possible. I worry, as stated above already, that negative things might happen as is. Maybe it's ok but I'd rather be as safe as possible. Thoughts?

**Comment by fdncred** [comment]
@schrieveslaach been missing your prs for nu-lsp lately. hope everything is ok.

do you think these changes can be somehow isolated to the nu-lsp crate?

**Comment by schrieveslaach** [comment]
> hope everything is ok.

A lot of stuff going on here, sorry for not responding earlier. I'll try to reach out to you in the next days.

**Comment by schrieveslaach** [comment]
I revisited the stuff I changed here and I see follow options

1. Add a new enum to the `nu-cli` crate that represents the kind of completions that is provided
2. Rewrite a new completer in `nu-lsp`
3. Let lsp-types sink into the rest of nushell (current approach of this PR)

After thinking for a while I prefer option 1 because it seems to me the option with the most clear boundaries among the crates.

I would abandon option 2 because that means there has to a whole rewrite [`completer.rs`](https://github.com/nushell/nushell/blob/c90640411d66515fa6422578d05f66a53ea5facd/crates/nu-cli/src/completions/completer.rs#L112-L413) in `nu-lsp` and then repl or lsp completions will be out of sync. Feels like a bad options to me. I would abandon option 3 for the reasons mentioned here.

But still, option 1 requires for me that `NuCompleter` in `nu-cli` has an additional method (like [`fetch_completions_at`](https://github.com/nushell/nushell/pull/11443/files#diff-8faa418ca3af7012f50b5e447bc7d1fe648e0c7afbb009ec1b191cb1bd22ea4cR32)) that returns then a type that contains the `reedline::Suggestion` and that new enum. 

@fdncred, is that a viable approach to you? Even if I won't be able to provide a whole test suite for the `NuCompleter` (like you mentioned [here](https://github.com/nushell/nushell/pull/11443#issuecomment-1875356906))

**Comment by fdncred** [comment]
@schrieveslaach I think option 1 sounds the safest compared to the other two. Although, at some point in the future, option 2 may be interesting.

**Comment by schrieveslaach** [comment]
@fdncred, here is a new preliminary version. Do you mind to have a rough look into it? There are still some TODO comments but I want to double check if it is going into the right direction.

**Comment by fdncred** [comment]
The only real thing that kind of rubs me the wrong way is the `kind: None` in several places. I wish there was a way to have some generic kind but maybe it doesn't work that way since nushell doesn't support certain language types. But I guess `kind: None` still completes but it just doesn't give the user more information.

**Comment by fdncred** [comment]
@schrieveslaach I think we may be able to land this if we can get the conflict(s) fixed.

**Comment by fdncred** [comment]
thanks

**Pull request merged**
