### PR TITLE
Correction bug multiple dots mkdir and touch

### PR DESCRIPTION
**Pull request by tcoratger**
# Description

As described in #8386, there was a problem in creating files and folders with more than two consecutive dots (`..`) in their name. This came from the specific management of nushell points in paths (for example, `...` is automatically transformed into `../..`). But this should not happen when the user wants to create a file/folder with several points (for example `test...`). In this case, the given file/folder should be created as requested by the user.

# Proposed change

To this end, I proposed to modify a little bit the `expand_ndots` function by checking if the character just before the dots is a separator/whitespace or not. If it is a separator or a whitespace, then the classic rule (`...` to `../..`) applies. Otherwise, the user must be free to do what he wants when handling paths.

This results in:

```rust
// find if we need to expand any >2 dot paths and early exit if not
let mut dots_count = 0u8;
let mut not_separator_before_dot = false;
let ndots_present = {
for chr in path_str.chars() {
    if chr == '.' {
        dots_count += 1;
    } else {
        if is_separator(chr) && (dots_count > 2) {
            // this path component had >2 dots
            break;
        }
        not_separator_before_dot = !(is_separator(chr) || chr.is_whitespace())
        dots_count = 0;
    }
}

dots_count > 2
};

if !ndots_present || not_separator_before_dot {
    return path.as_ref().into();
}
```

# Tests

The corresponding tests are added in the `mkdir.rs` and `touch.rs` test files.

### CODE REVIEW

**Comment by ahkrr** [comment]
While submitting my PR for the same issue as this one, I noticed that you had already made one. 
Though, I think the way this PR wants to fix the problem doesn't work correctly in all cases. 
Paths like those in your test cases will indeed no longer be incorrectly expanded, but other paths will create problems.
For example, `.../folder.../file.txt`  would no longer be correctly expanded, I think.

**Comment by ahkrr** [comment]
While submitting my PR for the same issue as this one, I noticed that you had already made one. 
Though, I think the way this PR wants to fix the problem doesn't work correctly in all cases. 
Paths like those in your test cases will indeed no longer be incorrectly expanded, but other paths will create problems.
For example, `.../folder.../file.txt`  would no longer be correctly expanded, I think.

**Comment by tcoratger** [comment]
@ahkrr Yes you're right because if you have multiple times `...`, my condition will just take into account the first one and not the remaining ones, right? Giving `../../folder../../file.txt` in the case you mentioned right? because `!ndots_present || not_separator_before_dot` is false due to the first `...` of `.../folder.../file.txt`, correct?

**Comment by ahkrr** [comment]
I don't fully understand the implementation of your solution I just noticed that some cases are incorrectly handled.
`folder.../.../file.txt` should become `folder.../../../file.txt`, I think.

**Comment by kubouch** [comment]
I think it's good . If there is a need to improve it further, you can always open another PR.

**Pull request merged**
