### PR TITLE
Treat empty pipelines as pass-through

### LINKED ISSUE #8393: Variable assignment fails due to piping no values in an empty directory
### Question

How do I assign variables when I'm in an empty directory?

```nushell
let x = (ls | where size >= 2kB)
```
```nushell
Error: nu::shell::only_supports_this_input_type (link)

  × Input type not supported.
   ╭─[entry #12:1:1]
 1 │ let x = (ls | where size >= 2kB)
   ·          ─┬   ──┬──
   ·           │     ╰── only list, binary, raw data or range input data is supported
   ·           ╰── input type: nothing
   ╰────
```

I guess, returning an empty list may still be okay?

### Additional context and details

_No response_

### PR DESCRIPTION
**Pull request by jntrnr**
# Description

This allows empty pipelines to pass their emptiness through a filter. This helps fix issues like trying to run a filter on an `ls` in an empty directory. It also feels a bit more reasonable that a filter filters what is *there* but doesn't require something to be there.

fixes #8393

# User-Facing Changes

No breaking changes (that I know of). Should allow filtering to be a little less surprising with emptiness.

# Tests + Formatting

Don't forget to add tests that cover your changes.

Make sure you've run and fixed any issues with these commands:

- `cargo fmt --all -- --check` to check standard code formatting (`cargo fmt --all` applies these changes)
- `cargo clippy --workspace -- -D warnings -D clippy::unwrap_used -A clippy::needless_collect` to check that you're using the standard code style
- `cargo test --workspace` to check that all tests pass

# After Submitting

If your PR had any user-facing changes, update [the documentation](https://github.com/nushell/nushell.github.io) after the PR is merged, if necessary. This will help us keep the docs up to date.

### CODE REVIEW

**Comment by jntrnr** [comment]
I want to also land some corresponding fixes to some of the filter commands, so we have a consistent way filtering works with empty pipelines

**Comment by fdncred** [comment]
@jntrnr Thoughts on this one? We have time before the next release if we land soon.

**Comment by fdncred** [comment]
pinging you again @jntrnr so that, if we want this, we can land it shortly after the next release in a few days.

**Comment by amtoine** [comment]
:bulb: https://github.com/nushell/nushell/issues/8393 has been fixed around the same time independently in https://github.com/nushell/nushell/pull/8439 :ok_hand: 

i think the two approaches are complementary and should be kept :sparkles:

**Comment by sholderbach** [comment]
Marking as a breaking changes as this could be a potential change to the semantics of erroneous usage of filtering commands after "void" commands that return `PipelineData::Empty`

**Comment by amtoine** [comment]
@sholderbach 
you're absolutely right, this is a breaking change, mainly on error handling

```bash
> cd . | where blah
Error: nu::shell::only_supports_this_input_type

  × Input type not supported.
   ╭─[entry #13:1:1]
 1 │ cd . | where blah
   ·        ──┬──┬
   ·          │  ╰── input type: null
   ·          ╰── only list, binary, raw data or range input data is supported
   ╰────
```
now becomes silent... :confused: 
```bash
> cd . | where blah
╭────────────╮
│ empty list │
╰────────────╯
```

**Comment by amtoine** [comment]
if we want things like `cd . | where blah` to return an error (i think it should), we should probably revert that and add a test for this :thinking:

**Pull request merged**
