### PR TITLE
Prepend directory to the binary tarball

### LINKED ISSUE #6676: tar archive should contain a directory
### Describe the bug

Normally (by convention/usual practice), tar archives for Linux packages have a directory.

The nushell tar archive lacks such a directory.

### How to reproduce

1. Download the latest Linux archive.

    wget https://github.com/nushell/nushell/releases/download/0.69.1/nu-0.69.1-x86_64-unknown-linux-gnu.tar.gz

2. Look at the table of contents of the archive.

    tar tzf nu-0.69.1-x86_64-unknown-linux-gnu.tar.gz

### Expected behavior

The expected output is something like this:
```
nu-0.69.1/LICENSE
nu-0.69.1/README.txt
nu-0.69.1/nu
nu-0.69.1/nu_plugin_custom_values
nu-0.69.1/nu_plugin_example
nu-0.69.1/nu_plugin_gstat
nu-0.69.1/nu_plugin_inc
nu-0.69.1/nu_plugin_query
```

The actual output is:
```
LICENSE
README.txt
nu
nu_plugin_custom_values
nu_plugin_example
nu_plugin_gstat
nu_plugin_inc
nu_plugin_query
```

### Screenshots

_No response_

### Configuration

Version: file https://github.com/nushell/nushell/releases/download/0.69.1/nu-0.69.1-x86_64-unknown-linux-gnu.tar.gz

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by nibon7**
# Description

~~According to https://www.gnu.org/software/tar/manual/html_section/transform.html, use `--transform` parameter to prepend directory to each file name.~~

GNU tar is not available on Mac by default, use a common way.

Closes #6676

Screenshot from 2022-10-11 17-24-53

# Tests

Make sure you've done the following:

- [ ] Add tests that cover your changes, either in the command examples, the crate/tests folder, or in the /tests folder.
- [ ] Try to think about corner cases and various ways how your changes could break. Cover them with tests.
- [ ] If adding tests is not possible, please document in the PR body a minimal example with steps on how to reproduce so one can verify your change works.

Make sure you've run and fixed any issues with these commands:

- [ ] `cargo fmt --all -- --check` to check standard code formatting (`cargo fmt --all` applies these changes)
- [ ] `cargo clippy --workspace --features=extra -- -D warnings -D clippy::unwrap_used -A clippy::needless_collect` to check that you're using the standard code style
- [ ] `cargo test --workspace --features=extra` to check that all the tests pass

### CODE REVIEW

**Comment by sholderbach** [comment]
Do we have any consumers of our tarballs that might need adjustment with this change?

**Comment by sholderbach** [comment]
I am wondering if we need to change things for downstream tools or package distributors that download the nu binaries from the GitHub release.
We would have to make sure they can deal with this change correctly (and if they support version pinning to older versions, things don't break with a change to the recipe)

Examples:
https://github.com/Yethal/ansible-role-nushell
https://github.com/marketplace/actions/setup-nu

Dragging in @Yethal and @hustcer for comment

**Comment by hustcer** [comment]
`Setup-nu` Action may not work well with the new release workflow, I will test and fix it recently

**Comment by Yethal** [comment]
No change from my perspective. Ansible role already searches recursively to find the files. With that said, the only reason I'm doing it in the first place is because tarball does not have the directory prepended to it.

**Comment by fdncred** [comment]
I'm nervous about this one because all downstream consumers might need to change something.

**Comment by hustcer** [comment]
Feel free to merge this PR, I will fix `setup-nu` action if it fails for the new release tarball

**Comment by Yethal** [comment]
@fdncred maybe post about this change on discord/twitter/etc to reach other consumers, other than me and hustcer there are probably people maintaining packages in third party repos such as aur or pacstall

**Comment by rgwood** [comment]
This seems like a good idea to me.

In general, Linux package managers are going to be building Nu from source and won't be affected by this. Homebrew builds from source too.

**Comment by Yethal** [comment]
Package managers yes, but places such as pacstall, aur, homebrew etc that automate the process of downloading the release from github might be affected

**Comment by rgwood** [comment]
Homebrew builds Nu from scratch. I believe AUR does too. I understand that some tools might use our binaries but I suspect the number of such tools is quite small.

**Comment by fdncred** [comment]
let's move forward with this. I just hope it doesn't come back to bite us on Nov 8th release. Thanks!

**Comment by hustcer** [comment]
[`setup-nu@v3`](https://github.com/hustcer/setup-nu) supports latest `nu` v0.71.0

**Comment by rgwood** [comment]
Looks like this ended up breaking virtualenv. Hopefully they can work around it. https://github.com/pypa/virtualenv/pull/2442#issuecomment-1310562695

**Pull request merged**
