### PR TITLE
nu-cli/completions: fix file completions with quotes

### PR DESCRIPTION
**Pull request by herlon214**
# Description

This fixes the issue https://github.com/nushell/nushell/issues/5223 . I'm just checking if the path has single/double quotes, and wrapping the path with quotes.

- single quotes -> wrap with double quotes
- double quotes -> wrap with single quotes

To be honest I'm not 100% sure that this is the correct way of doing it, perhaps there are more special characters we need to check. Any suggestion is welcome.

# Tests

Make sure you've run and fixed any issues with these commands:

- [X] `cargo fmt --all -- --check` to check standard code formatting (`cargo fmt --all` applies these changes)
- [X] `cargo clippy --all --all-features -- -D warnings -D clippy::unwrap_used -A clippy::needless_collect` to check that you're using the standard code style
- [x] `cargo build; cargo test --all --all-features` to check that all the tests pass

### CODE REVIEW

**Comment by jntrnr** [comment]
@herlon214 - if the quote or single-quote is in the middle of the path, I think wrapping it with the same might not be what you want. We do some automatic quoting in the other completions, though I'm trying to remember how they work. Maybe you can dig them up as part of it?

I want to say the logic is something like "take the quotes off the end, and if there's a space in the path, re-quote it"

**Comment by herlon214** [comment]
@jntrnr I'm not wrapping with the same, it's the inverse:
" => '
' => "

The things I found related were:

- When reading the dir entries, add the quotes if it contains space:
```
if path.contains(' ') {
    path = format!("\'{}\'", path);
}
```

- Remove single quotes when checking partial:
```
let partial = input.replace('\'', "");
```

**Comment by jntrnr** [comment]
Hmm, I don't think we want to wrap with double quotes though, now that I think about it. In Windows, that would break the backslashes used for Windows path.

We could wrap with backticks instead of double quotes. That's currently another option

**Comment by herlon214** [comment]
@jntrnr wrapping with backticks seems to work fine 👍

**Comment by jntrnr** [comment]
cool

**Comment by uasi** [comment]
We've fallen into the same trap as https://github.com/nushell/nushell/issues/5185 . `` `...` `` can't be used to quote an arbitrary string; we need to provide a proper escape function, for example, `nu_parser::escape_string()`.

**Comment by herlon214** [comment]
@uasi that sounds like a good idea. I'm wondering what we can do if the path has sinlge+double quotes + backticks :thinking:

**Comment by uasi** [comment]
@herlon214 Only `"` and `\` need to be escaped. For example, `` C:\foo'bar\baz`qux\my"file".txt `` would be escaped as ``  "C:\\foo'bar\\baz`qux\\my\"file\".txt" ``

**Comment by herlon214** [comment]
Shall we continue the discussion on https://github.com/nushell/nushell/pull/5254?

**Pull request merged**
