### PR TITLE
allow `return` to return any nushell value

### PR DESCRIPTION
**Pull request by fdncred**
# Description

This PR allows the `return` command to return any nushell value.

### Before
image

### After
image

# User-Facing Changes

# Tests + Formatting

# After Submitting

### CODE REVIEW

**Comment by sholderbach** [comment]
The type error you see in the first case is due to the `int -> int` input output types of `f`. But the body doesn't actually do anything with `int ->` input. This is separate from the `x: int` argument.

Interesting that the type check collapses through `any` for the output type. This to me seems like the actual bug.

**Comment by sholderbach** [comment]
For reference @amtoine and I in the following discussion ran into a similar fallacy around how `return`'s signature should look like 
https://github.com/nushell/nushell/pull/9701

Issue around that #9697

**Comment by amtoine** [comment]
@sholderbach
do you think this very PR should be reverted?

**Comment by sholderbach** [comment]
Not sure if the problem you laid out in #9697 still persists? If this change would allow valid code to pass I would let it stand for now even if it is more permissive or not perfect in theory.

**Comment by amtoine** [comment]
> Not sure if the problem you laid out in #9697 still persists? If this change would allow valid code to pass I would let it stand for now even if it is more permissive or not perfect in theory.
>
just installed Nushell with these changes and it's fixed :ok_hand:

**Comment by fdncred** [comment]
This seems to work.
```nushell
> def f [x: int]: int -> int { let y = $in; return (2 * $x + $y) }
> 6 | f 5
16
```

This error should be different like "You're not using an `int` input in this body".
```nushell
❯ def f [x: int]: int -> int { return (2 * $x) }
Error: nu::parser::input_type_mismatch

  × Command does not support int input.
   ╭─[entry #14:1:1]
 1 │ def f [x: int]: int -> int { return (2 * $x) }
   ·                              ───┬──
   ·                                 ╰── command doesn't support int input
   ╰────
```

That error message is probably a separate issue. I think my PR is good because `return` should be allowed to return nushell values and not just nothing. This is why this code exists, if i'm reading it right.
```rust
        let return_value: Option<Value> = call.opt(engine_state, stack, 0)?;
        if let Some(value) = return_value {
            Err(ShellError::Return(call.head, Box::new(value)))
        } else {
            Err(ShellError::Return(
                call.head,
                Box::new(Value::nothing(call.head)),
            ))
        }
```

**Pull request merged**
