### PR TITLE
More descriptive errors when registering plugins

### PR DESCRIPTION
**Pull request by biesnecker**
# Description

Previously, when errors occurred during the plugin registration process, the only feedback given to the user was `Plugin failed to load: <system error message>`, which wasn't particularly helpful in diagnosing errors. This PR adds somewhat more descriptive error messages, especially for two cases (file not found and permission denied) that might be encountered when running Nushell commands from another shell when the configuration directory is either missing or inaccessible (the motivating example of this was an error running plugin registration from Bash in a Docker file). 

Examples:

```
6:48:30 ~/projects/nushell better-plugin-registration-errors $ chmod a-wrx ~/Library/Application\ Support/nushell
6:48:33 ~/projects/nushell better-plugin-registration-errors $ ./target/debug/nu -c 'register /Users/jbiesnecker/.cargo/bin/nu_plugin_formats'
Error: nu::shell::plugin_failed_to_load

  × Plugin failed to load: Permission denied when trying to create the plugin file: /Users/jbiesnecker/Library/Application Support/nushell/plugin.nu

6:48:37 ~/projects/nushell better-plugin-registration-errors $ chmod +wrx ~/Library/Application\ Support/nushell
6:48:47 ~/projects/nushell better-plugin-registration-errors $ rm -rf ~/Library/Application\ Support/nushell
6:48:59 ~/projects/nushell better-plugin-registration-errors $ ./target/debug/nu -c 'register /Users/jbiesnecker/.cargo/bin/nu_plugin_formats'
Error: nu::shell::plugin_failed_to_load

  × Plugin failed to load: Plugin file not found: /Users/jbiesnecker/Library/Application Support/nushell/plugin.nu. If you're running this command from outside of Nushell, you may need to create the configuration
  │ directory.
```

This PR fixes https://github.com/nushell/nushell/issues/10754

# User-Facing Changes

Error messages generated by failure to register plugins.

# Tests + Formatting

- [x] `cargo fmt --all -- --check` to check standard code formatting (`cargo fmt --all` applies these changes)
- [x] `cargo clippy --workspace -- -D warnings -D clippy::unwrap_used` to check that you're using the standard code style
- [x] `cargo test --workspace` to check that all tests pass (on Windows make sure to [enable developer mode](https://learn.microsoft.com/en-us/windows/apps/get-started/developer-mode-features-and-debugging))
- [x] `cargo run -- -c "use std testing; testing run-tests --path crates/nu-std"` to run the tests for the standard library

### CODE REVIEW

**Review by fdncred — APPROVED** [review]
Oh, nice! Thanks for improving the plugin ecosystem. It needs love and doesn't get much.

**Comment by fdncred** [comment]
Was looking at this again and was wondering if you'd be up to adding some tests? Some of these things you can test for but others not so much.

**Comment by biesnecker** [comment]
Sure, I can add tests.

**Review by amtoine — CHANGES_REQUESTED** [review]
just making the request for tests more *official* :wink: 

@fdncred 
feel free to dismiss this when tests got pushed :relieved:

**Comment by fdncred** [comment]
@biesnecker Were you going to add some tests?

**Comment by biesnecker** [comment]
@fdncred I was / am planning to, but I was a little lost on how to test it, and then work got crazy so I haven't had a chance to come back to it.

**Comment by fdncred** [comment]
ok, thanks for the update. I guess you need to try to register a bogus plugin and check that the error message is what is expected. not sure you can register a valid plugin in a test.

**Comment by fdncred** [comment]
I guess one way to test this would be to try and register a file that is not a plugin and check that the error message is correct.

**Comment by biesnecker** [comment]
Sorry I don't think I'm going to have time to learn how to write tests for this. I manually tested this PR, so someone else who already knows how the testing framework works can probably pick it up and finish it.

**Pull request closed without merging**
