### PR TITLE
Update release script to nu v0.71 and use ubuntu-20.04 to build nu binary

### LINKED ISSUE #7282: `glibc` version too damn high?
### Describe the bug

```
nu: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by nu)
nu: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found (required by nu)
nu: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found (required by nu)
```

The `glibc` version on current Debian 11 Bullseye (stable) is [2.31](https://packages.debian.org/bullseye/libc6).

Which means, the most recent version of `nu` cannot be installed through the officially recommended ways without unrecommended & potentially risky hacks to the system.

I've seen other issues like this before.

https://github.com/nushell/nushell/issues/3825
https://github.com/nushell/nushell/issues/3737

Usually, they could be fixed by upgrading the system's packages.
In this case, it does not seem possible, without issues.

### How to reproduce

1. Run Debian 11 Bullseye (stable, as of now).
2. `apt update && apt upgrade -y`
3. Still, `nu` won't run.

### Expected behavior

Continues to run on popular GNU/Linux distribution, even after an upgrade.

### Screenshots

_No response_

### Configuration

| key                | value                                           |
| ------------------ | ----------------------------------------------- |
| version            | 0.71.0                                          |
| branch             |                                                 |
| commit_hash        | 6cc4ef6c706ebbdc5b995013e0b00f77f7a4dba7        |
| build_os           | linux-x86_64                                    |
| build_target       | x86_64-unknown-linux-gnu                        |
| rust_version       | rustc 1.65.0 (897e37553 2022-11-02)             |
| rust_channel       | stable-x86_64-unknown-linux-gnu                 |
| cargo_version      | cargo 1.65.0 (4bc8f24d3 2022-10-20)             |
| pkg_version        | 0.71.0                                          |
| build_time         | 2022-11-08 18:00:26 +00:00                      |
| build_rust_channel | release                                         |
| features           | database, dataframe, default, trash, which, zip |
| installed_plugins  | partial                                         |

### Additional context

**Platform**
Debian GNU/Linux 11 (bullseye) in WSL2 on Windows 10

**Terminal software**
Windows Terminal

Nushell is running "natively" as a login shell.

____

I don't know, whether this is acceptable or not. Though, I had the impression that support for major operating systems in their currently most popular/recent edition is significant to this project's goals.

### PR DESCRIPTION
**Pull request by hustcer**
# Description

1. Update nu to v0.71 for release script
2. Remove the usage of `set-output` see: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
3. Use `ubuntu-20.04` instead of `ubuntu-latest` to fix #7282 

To check the workflow running result see: https://github.com/hustcer/nu-release/actions/runs/3588720720/jobs/6040412953

# User-Facing Changes

_(List of all changes that impact the user experience here. This helps us keep track of breaking changes.)_

# Tests + Formatting

Don't forget to add tests that cover your changes.

Make sure you've run and fixed any issues with these commands:

- `cargo fmt --all -- --check` to check standard code formatting (`cargo fmt --all` applies these changes)
- `cargo clippy --workspace -- -D warnings -D clippy::unwrap_used -A clippy::needless_collect` to check that you're using the standard code style
- `cargo test --workspace` to check that all tests pass

# After Submitting

If your PR had any user-facing changes, update [the documentation](https://github.com/nushell/nushell.github.io) after the PR is merged, if necessary. This will help us keep the docs up to date.

### CODE REVIEW

**Comment by fdncred** [comment]
Thanks for your help with this.

It would also be helpful to print out the variables in the first ~20 lines. It was difficult for me to debug without really knowing what these were supposed to be. I'd also like to land this PR https://github.com/nushell/nushell/pull/7277 before this one because it has some comments on running it manually.

**Comment by hustcer** [comment]
@fdncred That's fine with me, I will wait until #7277 merged.

**Comment by fdncred** [comment]
@hustcer Would you mind changing this to 20.04 vs 22.04? We think moving to the older version would help with the glibc issues.

**Comment by hustcer** [comment]
> @hustcer Would you mind changing this to 20.04 vs 22.04? We think moving to the older version would help with the glibc issues.

I agree with you, will change it to ubuntu-20.04 later

**Pull request merged**
