### PR TITLE
Initial SQLite functionality

### PR DESCRIPTION
**Pull request by rgwood**
# Description

This PR adds basic support for SQLite databases to the `open` command, using [the `rusqlite` crate](https://lib.rs/crates/rusqlite):
```
> open sample.db
╭─────────┬────────────────╮
│ strings │ [table 6 rows] │
│ ints    │ [table 5 rows] │
│ floats  │ [table 4 rows] │
╰─────────┴────────────────╯
> open sample.db | get floats
╭───┬──────────────────────────────────────────────────────────────────────╮
│ # │                                  f                                   │
├───┼──────────────────────────────────────────────────────────────────────┤
│ 0 │                                                                 3.40 │
│ 1 │                                                                 3.14 │
│ 2 │                                                                23.00 │
│ 3 │ this string that doesn't really belong here but sqlite is what it is │
╰───┴──────────────────────────────────────────────────────────────────────╯
```

# Notes

- Thanks to @stormasm for help with this! He wrote some of the code to convert SQLite rows to Nu values.
- Databases are detected by looking for [a known header](https://sqlite.org/fileformat.html) in the file contents; this is necessary because there is no standard SQLite file extension. I think the "read, then rewind" approach I took makes sense but I might be missing a better way to do this
- This is a little different from how the existing `from *` commands work, because `rusqlite` doesn't have a way to load databases from bytes in memory. If consistency is important here, maybe we could add a `from sqlite` command that does the hacky "write to disk then read again" thing but ensure that `open foo.db` can shortcut that
- The reedline folks plan to add SQLite-backed history using `rusqlite`; we'll need to ensure that Nu and reedline use the same `rusqlite` version for build time+size efficiency

# Future work

This PR is a very simple approach, it loads the entire database into memory as Nu values. I'd like to add a way to write SQL instead, perhaps something like this:
```bash
open foo.db --query "select * from cool_table"
# or
open foo.db --sql "select * from cool_table"
```

This would help in situations where SQL is a more natural way to express a query than Nu syntax, and it would allow for performance optimization when necessary (maybe you have a really big DB and you don't want to load the whole thing into memory).

# Tests

Make sure you've run and fixed any issues with these commands:

- [x] `cargo fmt --all -- --check` to check standard code formatting (`cargo fmt --all` applies these changes)
- [x] `cargo clippy --all --all-features -- -D warnings -D clippy::unwrap_used -A clippy::needless_collect` to check that you're using the standard code style
- [x] `cargo build; cargo test --all --all-features` to check that all the tests pass

### CODE REVIEW

**Comment by stormasm** [comment]
@rgwood so far so good, code looks nice !
however, I am running your code and it does not seem to work correctly.
might be on my end --- so lets try and clarify...

https://github.com/stormasm/rust-examples/blob/main/sqlite/examples/writedb04.rs

If you run the above code it will create a sqlite db for you...
The db it creates I then try and open with your code...
and this is what I am seeing...

```rust
?p?;tablepersonpersonCREATE TABLE person (
                  id              INTEGER PRIMARY KEY,
                  name            TEXT,
                  data            BLOB,
                  grade           REAL
@ ffffffBill@??????Petea@ffffffSteven@
                                      333333
```
so that does not appear to be correct....

**Comment by rgwood** [comment]
@stormasm I've run your code to generate a database ([person04.zip](https://github.com/nushell/nushell/files/8485369/person04.zip)) and it works for me on Windows:

```
> open C:\Users\reill\source\rust-examples\sqlite\person04.db
╭────────┬────────────────╮
│ person │ [table 4 rows] │
╰────────┴────────────────╯
```

What OS+architecture are you on? I wonder if something's going wrong with the header detection.

**Comment by stormasm** [comment]
@rgwood ok 
[here are all of my dbs](https://github.com/stormasm/tmp100/blob/main/rgwood-db.tar.gz)
For some reason none of them work :)
I am on a macbook pro....

**Comment by rgwood** [comment]
@stormasm Thanks! Is your MBP x86 or ARM? Those databases work for me; I have an x86 Mac that I can test with but it will take a while to get it set up.

The macOS tests succeeded so I wonder if this might be an issue with your machine, hmm.

**Comment by stormasm** [comment]
so I have a 2.7 Gig Hz intel core i5...
does that answer your question / so I guess its X86 ?
this is strange then ---- not sure why its not working...
the sqlite3 client opens them with no problem.

**Comment by stormasm** [comment]
the mac tests are passing on my machine...

**Comment by rgwood** [comment]
Yup, that would be x86. I'll dig out my Mac. 

Just to rule out any other issues: you're opening the databases using `open` without any other arguments, right? 

```
open person04.db
```

**Comment by stormasm** [comment]
Its working !!

**Comment by stormasm** [comment]
@rgwood let me know you got this message !! its working...

**Comment by stormasm** [comment]
I had two nushell binaries installed / and I built your code but it was pulling the other binary 👍 So it was a pilot error on my part...

**Pull request merged**
