### PR TITLE
Add `from-eml` command

### PR DESCRIPTION
**Pull request by aeshirey**
For #136, this PR adds a `from-eml` command using my new [`eml-parser` crate](https://crates.io/crates/eml-parser) ([git here](https://github.com/aeshirey/EmlParser/)).

### CODE REVIEW

**Comment by jonathandturner** [comment]
Oh nice, looking forward to playing with this.

Can you also add a test case?  We've got some for other format converters here you can base a test or two off of: https://github.com/nushell/nushell/tree/master/crates/nu-cli/tests/format_conversions

**Comment by jonathandturner** [comment]
There's one test that needs to get updated when you add new file formats, `prepares_and_decorates_filesystem_source_files`.

I'm debating whether we should remove it, since I forget to update it (and it's unrelated to the formats)

**Comment by jonathandturner** [comment]
Heh :) 

Thanks for the PR!

**Comment by aeshirey** [comment]
Thanks! Looking forward to the next issue I can tackle!

**Pull request merged**
