### PR TITLE
Use built-in is_terminal instead of is_terminal::is_terminal

### PR DESCRIPTION
**Pull request by nibon7**
# Description
This PR tries to remove ~atty~ is-terminal from the entire code base, since ~[atty is unmaintained](https://rustsec.org/advisories/RUSTSEC-2021-0145) and~ [`is_terminal` has been stabilized](https://blog.rust-lang.org/2023/06/01/Rust-1.70.0.html#isterminal) in rust 1.70.0.

cc @fdncred 

# User-Facing Changes

# Tests + Formatting

# After Submitting

### CODE REVIEW

**Comment by nibon7** [comment]
Yes, they perform exactly the same function in *nix.

https://github.com/softprops/atty/blob/7b5df17888997d57c2c1c8f91da1db5691f49953/src/lib.rs#L39-L49
https://github.com/rust-lang/rust/blob/8882507bc7dbad0cc0548204eb8777e51ac92332/library/std/src/sys/unix/io.rs#L79-L82

**Comment by ChrisDenton** [comment]
Also worth noting that atty hasn't been maintained in a long while. The std version includes bug fixes (at least for Windows). There's also the `is-terminal` crate that aims to be an interim solution for pre-1.70 but some people don't like it because of the heavier dependencies.

**Comment by sholderbach** [comment]
Thanks for rebasing on it!

**Review by sholderbach — APPROVED** [review]
Thanks for following up!

**Pull request merged**
