### PR TITLE
Replace dirs and directories with maintained

### LINKED ISSUE #1817: Explore using the new `dirs` crates
**Is your feature request related to a problem? Please describe.**
Recently announced are new crates for doing `dirs` functionality (the original crate was abandoned)

https://www.reddit.com/r/rust/comments/gli4pc/directoriesnext_dirsnext_the_new_home_for/

**Describe the solution you'd like**
We should take a look at them and see if they fit the needs Nu has. If so, it may make sense to go ahead and move to them.

**Describe alternatives you've considered**
We can keep what we have, as it seems to work well enough.

### PR DESCRIPTION
**Pull request by brightly-salty**
Replaces dirs with dirs-next
Replaces directories with directories-next

Fixes #1817

### CODE REVIEW

**Comment by jonathandturner** [comment]
Thanks for the PR!

What we might do is move this functionality into Nushell itself rather than using crates for them. The reason is that we've switched to different crates a few different times, and each time we switch we break anyone who was using the previous version of Nu as sometimes the new crate would use a different directory than the old one.

**Comment by fdncred** [comment]
Hey @brightly-salty , Jonathan and I discussed this. He's right when he talks about not wanting to break users configuration settings, i.e. where the `config.toml` is stored on Linux, Mac, and Windows. With that in mind, could I ask you to do one more thing?  Could you please check the existing `dirs` and `directories` crates to understand where the `config.toml` file is currently located, on all three platforms, and help assure us that moving to `dirs-next` and `directories-next` won't cause a breaking change? If you can do that, I'll accept this PR and land it.

**Comment by brightly-salty** [comment]
Sure @fdncred 

`dirs::home_dirs()` [source](https://github.com/dirs-dev/dirs-rs#feature) = `dirs_next::home_dirs()` [source](https://github.com/xdg-rs/dirs#features)
`directories::ProjectDirs::config_dir` [source](https://github.com/dirs-dev/directories-rs#projectdirs) = `directories-next::ProjectDirs::config_dir` [source](https://github.com/xdg-rs/dirs/tree/master/directories#projectdirs)
`directories:::ProjectDirs::data_local_dir` [source](https://github.com/dirs-dev/directories-rs#projectdirs) = `directories-next::ProjectDirs::data_local_dir` [source](https://github.com/xdg-rs/dirs/tree/master/directories#projectdirs)

**Comment by fdncred** [comment]
So, if I'm reading this right. For `config_dir` this is what's happening.
```
OLD - https://github.com/dirs-dev/directories-rs#projectdirs
config_dir
    Linux
        $XDG_CONFIG_HOME/<project_path> or
        $HOME/.config/<project_path>
    Windows
        {FOLDERID_RoamingAppData}/<project_path>/config
    Mac
        $HOME/Library/Application Support/<project_path>

NEW - https://github.com/xdg-rs/dirs/tree/master/directories#projectdirs
config_dir
    Linux
        $XDG_CONFIG_HOME/<project_path> or
        $HOME/.config/<project_path>
    Windows
        {FOLDERID_RoamingAppData}/<project_path>/config
    Mac
        $HOME/Library/Application Support/<project_path>
```
So, at least for `config_dir` those values look identical to me. Right?

In fact, I checked all the `Base Dirs`, `User Dirs` and `Project Dirs` and the only thing I see different is there is no `preference_dir`, which I don't think is a show stopper. 

@brightly-salty is this how you read it?

**Comment by brightly-salty** [comment]
@fdncred Yes, that's how I read it. I don't think too much have been changed with the "next" version, but they are maintained actively.

**Comment by fdncred** [comment]
Thanks! Landing this.

**Pull request merged**
