### PR TITLE
relocate default config in sample_config folder

### PR DESCRIPTION
**Pull request by fdncred**
# Description

This PR relocates the `default_config.nu` file to `docs/sample_config/default_config.nu`. I'm making this a draft because I'm not sure of the ramifications, if any, to using the env var `CARGO_MANIFEST_DIR` to locate the default config and how that relates to publishing.

@jntrnr do you think this will work?

# Tests

Make sure you've run and fixed any issues with these commands:

- [x] `cargo fmt --all -- --check` to check standard code formatting (`cargo fmt --all` applies these changes)
- [x] `cargo clippy --all --all-features -- -D warnings -D clippy::unwrap_used -A clippy::needless_collect` to check that you're using the standard code style
- [ ] `cargo build; cargo test --all --all-features` to check that all the tests pass

### CODE REVIEW

**Comment by jmoore34** [comment]
I wonder if
```rust
include_str!("../docs/default_config")
```
might work

**Comment by fdncred** [comment]
> I wonder if
> 
> ```rust
> include_str!("../docs/default_config")
> ```
> 
> might work

I tried that first but couldn't get a relative path to work. did you get that to work?

**Comment by jmoore34** [comment]
Huh, it worked

Here's the line I used

```rust
let config_file = include_str!("../docs/sample_config/default_config.nu");
```

**Comment by fdncred** [comment]
Nice work, @jmoore34! I must of been just using the wrong path. I updated this PR.

**Pull request merged**
