### PR TITLE
fix removing symlinks on windows

### LINKED ISSUE #9624: rm: delete symlinks on windows
### Describe the bug

`rm` throws an OS error when trying to delete a symlink. I dunno if the same happens on Linux, I'd assume not since it would've been found earlier as they're far more common there.

The command does work when using the -t flag, which means this isn't a problem of capability, just a bug. The error says "The directory name is invalid". Probably has something to do with [this](https://github.com/nushell/nushell/blob/f38657e6f352d8bacfdb984bc4d4dcf6307d99f3/crates/nu-command/src/filesystem/rm.rs#L399) fallback to remove_dir_all, as an earlier if checks for is_symlink but it's not checked in the if let..else chain.

### How to reproduce
0. `touch somefile.txt` (this doesn't need admin)
1. `mklink link.txt somefile.txt` (you need admin for this)
2. `rm link.txt` (you don't need admin for this one)

### Expected behavior

I expect the symlink to be deleted. I also expect the original file to not be deleted oh god no please not that, I prefer it to throw an error. You can add a --follow-symlinks flag, but never let it be the default

### Screenshots

_No response_

### Configuration

| key                | value                                    |
| ------------------ | ---------------------------------------- |
| version            | 0.81.0                                   |
| branch             |                                          |
| commit_hash        | 5c81bcef1a3c1667468c81ef8c06cf56a0962133 |
| build_os           | windows-x86_64                           |
| build_target       | x86_64-pc-windows-msvc                   |
| rust_version       | rustc 1.68.2 (9eb3afe9e 2023-03-27)      |
| rust_channel       | 1.68.2-x86_64-pc-windows-msvc            |
| cargo_version      | cargo 1.68.2 (6feb7c9cf 2023-03-26)      |
| build_time         | 2023-06-06 22:55:37 +00:00               |
| build_rust_channel | release                                  |
| features           | default, sqlite, trash, which, zip       |
| installed_plugins  |                                          |

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by cramt**
this PR should close #9624

# Description

Fixes the `rm` command assuming that a symlink is a directory and trying to delete the directory as opposed to unlinking the symlink.

Should probably be tested on linux before merge.

Added tests for deleting symlinks

# User-Facing Changes

# Tests + Formatting

- :green_circle: `toolkit fmt`
- :green_circle: `toolkit clippy`
- :green_circle: `toolkit test`
- :green_circle: `toolkit test stdlib`

# After Submitting

### CODE REVIEW

**Comment by amtoine** [comment]
@cramt 
as i've just posted in https://github.com/nushell/nushell/issues/9624, i personally do not see any issue with the latest revision of Nushell on linux :ok_hand:

**Review by amtoine — CHANGES_REQUESTED** [review]
i do not see any change in behaviour on linux with this PR :ok_hand: 

maybe we should have a little test that makes sure that this bug stays fixed in the future :yum:

**Comment by cramt** [comment]
added filesystem tests for creating and removing files, dirs and symbols, since i didnt find any integration tests related to filesystem things, might just have not noticed it

**Comment by sholderbach** [comment]
Our existing filesystem integration tests can be found associated to each of the commands in https://github.com/nushell/nushell/tree/main/crates/nu-command/tests/commands. I think if there is not an explicit category of things we should test together for better understanding. your tests should be with the relevant commands to avoid fragmentation of the tests.

**Review by sholderbach — APPROVED** [review]
Thanks for iterating on the test and the fix!

**Pull request merged**
