### PR TITLE
Cargo Release CI Profile: enable LTO + reduce codegen-units

### PR DESCRIPTION
**Pull request by aminya**
Although I prefer optimizing for speed, if the least size is the desired behaviour, these are the settings that should be used.

Related to #3896

### CODE REVIEW

**Comment by jntrnr** [comment]
We've had a setting like this before and unfortunately had to change it because of the compile time cost.

I just ran it again on your branch to see if it has a similar issue, and it does seem to. Full build times for `cargo build --all --features=extra --release`

Before: 5 min 45 sec
With these settings: 20 mins 57 sec

I'm not sure if there is a way get back a build time closer to what we have today, but we'd need to before we could change the settings.

**Comment by aminya** [comment]
This is a release build though. It is built once in the CI, and it is used by thousands of people thousands times.

**Comment by jntrnr** [comment]
@aminya - developers who work on Nu build it in release mode regularly to compare performance benchmarks for data processing systems, to dogfood looking for issues, and by testers who update regularly. Asking everyone for that build to be 4x slower is too much.

**Comment by aminya** [comment]
In my opinion, this setting should be only used for "release" as the name suggests. If people want more optimization during dev, we should change the dev settings.

**Comment by jntrnr** [comment]
@aminya - what folks are testing is the performance of what the users will feel by using the release build. They are the same. In Rust, release builds are meant as those builds with optimisations turned on.

**Comment by aminya** [comment]
To me that is like "dev-optimized" and not releasing to the end users (what "release" means). This is a niche situation, and probably that is why Cargo doesn't have a "dev-optimized".

At least, "z" should be changed to "s". People pay for those fancy instruction sets, but "z" throws them all away

**Comment by jntrnr** [comment]
Yeah, switching to "s" is fine if you want to change to that. Looks like that has fairly similar compile times to "z".

**Comment by aminya** [comment]
@jntrnr It turns out that Cargo has an upcoming feature that allows us to make named profiles! I added a "release_ci" profile that is only used inside CI for the maximum optimizations

**Comment by aminya** [comment]
This needs cargo nightly. That's why the CI failed.

**Comment by jntrnr** [comment]
1.57 just released with custom profiles

**Comment by jntrnr** [comment]
With tomorrow's merge of the new engine, we're closing previous PRs for Nushell (as they won't merge cleanly against the new engine).

If you still see the same issue in the new engine, please file an issue (or even a PR).

**Pull request closed without merging**
