### PR TITLE
Move Value to helpers, separate span call

### PR DESCRIPTION
**Pull request by jntrnr**
# Description

As part of the refactor to split spans off of Value, this moves to using helper functions to create values, and using `.span()` instead of matching span out of Value directly.

Hoping to get a few more helping hands to finish this, as there are a lot of commands to update :)

# User-Facing Changes

# Tests + Formatting

# After Submitting

### CODE REVIEW

**Comment by fdncred** [comment]
I was going to chip in a bit, but I don't want to duplicate other's work. Was thinking maybe we should make a checklist to allow assigning work out so we don't stomp on each other.

|first_letter_of_cmd|cmd_count|assigned|
|-|-|-|
|a|8||
|b|22||
|c|15||
|d|127||
|e|14||
|f|23||
|g|5||
|h|22||
|i|22||
|j|1||
|k|5||
|l|8||
|m|39||
|n|2||
|o|2||
|p|17||
|q|1||
|r|20||
|s|52||
|t|21||
|u|10||
|v|6||
|w|7||
|z|1||

Here's a one-liner to see the commands by letter.
```nushell
help commands | where command_type == builtin | sort-by name | select name | group-by { get name | split chars | first } | transpose first_letter cmd_count | update cmd_count {|c| $c | get cmd_count.name | str join ', '}
```

**Comment by WindSoilder** [comment]
Oh, that's a good idea
Sorry that for catching up later, I've just finished some commands in the pr: https://github.com/jntrnr/nushell/pull/3/files

**Comment by fnordpig** [comment]
Just dropping a note that I'll take some. Maybe the "f" commands

**Comment by WindSoilder** [comment]
Here is also one-linear to get commands which starts with specific character(take 'b' as example):
```nushell
 help commands | where command_type == builtin | sort-by name | select name | filter {|x| $x | get name | str starts-with 'b'}
```

**Comment by jntrnr** [comment]
Thanks folks (and big shout-out to @WindSoilder for all the hard work)

I think this is ready to land. It needs a review, but otherwise I think we're good.

**Comment by amtoine** [comment]
has the table from @fdncred above been completed?

**Review by amtoine — COMMENTED** [review]
i traversed the changes without looking at every details and it looks ok.

just to be sure i understand the PR:
- it's purely refactoring, right?
- we use `Value::string("foo", some_span)` instead of `Value::String { val: "foo", span: some_span }`, same with other values
- we use `let span = value.span(); match value { ... }` instead of unpacking `Value::Foo { val, span }`

**Comment by WindSoilder** [comment]
> it's purely refactoring, right?

Yup, it's just a purely refactoring.

> we use Value::string("foo", some_span) instead of Value::String { val: "foo", span: some_span }, same with other values

Yeah, we construct these enum from functions rather than using relative syntax directly

> we use let span = value.span(); match value { ... } instead of unpacking Value::Foo { val, span }

Yeah, we make sure that there is no `internal_span` in the matched value.  Instead, we use `value.span()` to get the span from value.

**Comment by fdncred** [comment]
I've gone through a bunch of these from the bottom up and the only thing that jumps out to me as not understanding if it's right, is where we have `Box::new(error)` before and now just have `error`. I thought Stefan went through a bunch of ShellErrors and boxed them because the enum was too large and clippy was giving us warnings. I'm sure the compiler would complain if it weren't right, but I thought I'd bring this up.

The other thing is, I anticipate having some spans that are incorrect. Meaning, myself and everyone else who made changes has the opportunity to make mistakes refactoring this code. It's just so hard to tell in a PR this large.

My vote is to land it and deal with the potential ramifications when/if they come up.

**Comment by WindSoilder** [comment]
> I've gone through a bunch of these from the bottom up and the only thing that jumps out to me as not understanding if it's right, is where we have Box::new(error) before and now just have error

Actually we still bave `Box::new(error)`, it's created inside `error` function

**Comment by fdncred** [comment]
> Actually we still have Box::new(error), it's created inside error function

Thanks @WindSoilder. I hadn't noticed that. I appreciate you pointing it out.

**Pull request merged**
