### PR TITLE
Fix some issues with table wrapping of lists

### LINKED ISSUE #7591: `list<string>` values are not shown if a string is too wide
### Describe the bug

If a `list<string>` contains a string that is too long, the string is replaced with `...` instead of being truncated for display purposes

```bash
〉term size
╭─────────┬─────╮
│ columns │ 103 │
│ rows    │ 54  │
╰─────────┴─────╯
〉["foobarbaz foobarbaz foobarbaz foobarbaz foobarbaz foobarbaz foobarbaz foobarbaz foobarbaz foobar"]
╭───┬─────╮
│ 0 │ ... │
╰───┴─────╯
〉["foobarbaz foobarbaz foobarbaz foobarbaz foobarbaz foobarbaz foobarbaz foobarbaz foobarbaz fooba"]
╭───┬─────────────────────────────────────────────────────────────────────────────────────────────────╮
│ 0 │ foobarbaz foobarbaz foobarbaz foobarbaz foobarbaz foobarbaz foobarbaz foobarbaz foobarbaz fooba │
╰───┴─────────────────────────────────────────────────────────────────────────────────────────────────╯
```

### How to reproduce

1. Figure out your terminal width with `term size`
2. Display a list with a string that is around the same width as your terminal

### Expected behavior

I expected at least part of each string to be shown somehow, perhaps truncated if necessary. And `table -e` should definitely expand each field, but it does not.

### Screenshots

I appreciate that it's not always obvious when to hide information and when to show it, but let's use horizontal space better than this:

image

### Configuration

| key                | value                                    |
| ------------------ | ---------------------------------------- |
| version            | 0.73.1                                   |
| branch             | main                                     |
| commit_hash        | a43e66ef9273a0047fcc61184bf82e06152353e3 |
| build_os           | linux-x86_64                             |
| build_target       | aarch64-unknown-linux-musl               |
| rust_version       | rustc 1.65.0 (897e37553 2022-11-02)      |
| cargo_version      | cargo 1.65.0 (4bc8f24d3 2022-10-20)      |
| pkg_version        | 0.73.1                                   |
| build_time         | 2022-12-24 00:07:25 +00:00               |
| build_rust_channel | release                                  |
| features           | database, default, trash, which, zip     |
| installed_plugins  |                                          |

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by zhiburt**
close #7591 

I tend to think it must be addressed.
But I'd verify it @rgwood.

PS: I've noticed how `table -e` and `table` with the same width wraps a bit differently sometimes. (I guess it also must be addressed......)

### CODE REVIEW

**Comment by rgwood** [comment]
Thanks for the speedy fix!

Before:
image

After:
image

Much better but that 4th row seems to be wrapping incorrectly (it should not split `2022` into `2\n022`) 🤔

**Comment by fdncred** [comment]
Looks good to me too. All the previous ways that I could break it seem to be fixed now. Thanks!

**Comment by rgwood** [comment]
Still think we need to address the wrapping issue in my screenshot, but maybe that's a separate issue.

**Comment by fdncred** [comment]
Oh, I missed your last comment Reilly. Sorry.

**Pull request merged**
