### PR TITLE
allow use of $in in if-statement

### PR DESCRIPTION
**Pull request by NiklasJonsson**
* use enum to customize behaviour of has_var_usage for $in

### CODE REVIEW

**Comment by NiklasJonsson** [comment]
Fixes #3826 and #3873

**Comment by jntrnr** [comment]
Thanks for working on a fix! Much appreciated.

Looking through this, I'm not clear on `HasVarUsageSearchScope` and why it was incorporated. Is it not possible to reason about when to treat the first part of the pipeline as something receiving the `$in`?

**Comment by NiklasJonsson** [comment]
My idea was that I wanted to keep the current behaviour for `$it` and get the new behaviour for `$in` so I introduced `ExcludeExprBlocks` and `IncludeExprBlocks`. Further, after we've entered a block (e.g. the condition/body of an if) we only want to match on the first command of a pipeline, as any others will be expanded later, so I added OnlyFirstPipelineCommand. I could remove Include/Exclude in favor of check for `if var_name == "$in"`, is this what you'd prefer? I'm not sure how you could reason about the behaviour and not introduce the enum, but I might not be understanding enough of the IR.

**Comment by jntrnr** [comment]
@NiklasJonsson sorry for the slow response - 

I think we might want different functions for the types of walks. This could help with readability a bit, at the expense of a bit of code duplication.

**Comment by NiklasJonsson** [comment]
@jt No worries! I'll have a look at splitting them. But I still think I need to differentiate between OnlyFirstPipelineCommand or Any of them, right? Or am I misunderstanding?

**Comment by jntrnr** [comment]
@NiklasJonsson - I'm not sure what "Any" means here exactly, though yeah, listing the rules for the different types of walks will help us make sure everything is getting covered

**Comment by NiklasJonsson** [comment]
Hello again @jntrnr , I've been busy with work and moving so I haven't had time for this until now.

By "Any" I meant that in some cases, we would want to search through all the commands in a pipeline for a use of `$in`. As I was writing out my response as to why we need that, I realized that we probably don't 😄 and I was misunderstanding the syntax tree. I think it should be enough to always look in the first command in a pipeline when looking for $in. I updated the PR to have a separate function for this.

**Comment by jntrnr** [comment]
With tomorrow's merge of the new engine, we're closing previous PRs for Nushell (as they won't merge cleanly against the new engine).

If you still see the same issue in the new engine, please file an issue (or even a PR).

**Pull request closed without merging**
