### PR TITLE
add `into record` command

### PR DESCRIPTION
**Pull request by fdncred**
# Description

This command converts things into records.
Screenshot 2022-11-24 at 2 10 54 PM

Screenshot 2022-11-24 at 5 04 11 PM

It also converts dates into record but I couldn't get the test harness to accept an example.

Thanks to @WindSoilder for writing the "hard" parts of this. :)

_(Thank you for improving Nushell. Please, check our [contributing guide](../CONTRIBUTING.md) and talk to the core team before making major changes.)_

_(Description of your pull request goes here. **Provide examples and/or screenshots** if your changes affect the user experience.)_

# User-Facing Changes

_(List of all changes that impact the user experience here. This helps us keep track of breaking changes.)_

# Tests + Formatting

Don't forget to add tests that cover your changes.

Make sure you've run and fixed any issues with these commands:

- `cargo fmt --all -- --check` to check standard code formatting (`cargo fmt --all` applies these changes)
- `cargo clippy --workspace -- -D warnings -D clippy::unwrap_used -A clippy::needless_collect` to check that you're using the standard code style
- `cargo test --workspace` to check that all tests pass

# After Submitting

If your PR had any user-facing changes, update [the documentation](https://github.com/nushell/nushell.github.io) after the PR is merged, if necessary. This will help us keep the docs up to date.

### CODE REVIEW

**Comment by sholderbach** [comment]
I struggle a bit to see the `"value"` of the conversions from scalar values. What is the advantage over using `... | {my_name: $in}`?

**Comment by fdncred** [comment]
> I struggle a bit to see the "value" ...

Ya, my thoughts were/are really that any `into` command should support all types that can be sent into it. It kind of bothers my OCD to see `into` commands where certain types just aren't supported.

I chose the word `value` because I thought it fit, but I'd be open to other terms that are a better fit.

> What's the advantage ...

It's a command where you don't have to think in records, it does it for you. That's really it.


The conception of this command was really to take the place of `transpose -ird` since that is not really discoverable. We may not have this command 100% where it needs to be yet, but I think we can land it an iterate on it until we get it the shape where we want it to be. I personally think it's close but may still need some work in some areas. Like, I'm not sure I like `ls | into record` but I want to live with it a bit and let others do the same. Hopefully that will spur on some contributions to make it nicer.

**Comment by sholderbach** [comment]
True.

`transpose -r -d` currently can deal with a table with a `key` and a `value` column (naming is ignored.). The current `into record` on table on the other hand effectively strips the list around the single record.

**Comment by fdncred** [comment]
Feel free to tweak it how you think is best. You won't hurt my feelings. I just wanted something easier.

**Comment by jntrnr** [comment]
`into record` I think only makes sense for a few value types. Things like dates being split into their components, and possibly also duration and filesize being split into s/ms/us/ns and mib/kib/b etc.

Things like `4` or `0.5` don't make sense to have a `into record` for as they don't have any structural components. They're instead atomic units that can't be split.

**Comment by fdncred** [comment]
> into record I think only makes sense for a few value types. 

That may be true, I just wasn't willing to assume I knew every use case and erred on the conservative side of accepting nearly all values as input.

**Comment by jntrnr** [comment]
> > into record I think only makes sense for a few value types.
> 
> That may be true, I just wasn't willing to assume I knew every use case and erred on the conservative side of accepting nearly all values as input.

I'd vote for being conservative and only adding support for things you for-sure know we should have `into record` on, and then if folks find other places, we can take them as a case-by-case basis.

**Pull request merged**
