### PR TITLE
add tests to `polars unique`

### PR DESCRIPTION
**Pull request by maxim-uvarov**
# Description

I would like to help with `polars` plugin development and add tests to all the `polars` command's existing params.

Since I have never written any lines of Rust, even though the task of creating tests is relatively simple, I would like to ask for feedback to ensure I did everything correctly here.

### CODE REVIEW

**Comment by fdncred** [comment]
I think this looks good as far as layout and code. The questions I have are 1) are examples tested in plugins and 2) did the tests pass when you ran cargo text or cargo nextest? Maybe @ayax79 could look at this first one and you can continue in this fashion if he approves it.

**Comment by maxim-uvarov** [comment]
> 1) are examples tested in plugins 

@fdncred, I'm not sure if I understood correctly, but maybe the second answer will be enough.

> 2) did the tests pass when you ran cargo text or cargo nextest?

I ran `cargo test` inside the folder with changes, and it went well. I also intentionally spoiled the results to check if the tests worked, and they failed as expected. I did not try `nextest`. If it is useful in this case, please let me know where I can find more information about it.

**Comment by fdncred** [comment]
ok, you answered my questions. thanks! cargo nextest is not required. i just use it because it's faster.

**Review by ayax79 — APPROVED** [review]
Everything looks great to me, Thanks!

**Pull request merged**
