### PR TITLE
Implement histogram command

### PR DESCRIPTION
**Pull request by WindSoilder**
# Description

Implement `histogram` to push #4314. Relative: #3215, #3343

Sorry that I'm failed to create a relative small pr, the biggest addition is introducing `HashableValue` struct.

## Histogram Part: pipeline input checking
1. if `pipeline input` itself is not a list, just throw out error.
2. if `<column-name>` is not provided, expect `pipeline input` is a list of single value.
3. if `<column-name>` is provided, more invalid input scenario needs to handle:
 * item in `input` is not a `record`, just skip it.
 * a record **doesn't** contain specific column, just skip it.
 * **all records** don't contain specific column, throw out error, indicate at least one row should contains specific column.
 * a record contain a value which can't be hashed, skip it.

## HashableValue Part: Why HashableValue is needed?
Because `Value` is not hashable, in `histogram`, we need to count the frequency of each value.  ~Here is another command [math mode](https://github.com/nushell/nushell/blob/main/crates/nu-command/src/math/mode.rs) which shares the same requirement too.  And it also defines a similar [HashableType](https://github.com/nushell/nushell/blob/main/crates/nu-command/src/math/mode.rs#L19)~.

~To handle this, we can introduce a more general `HashableValue` struct in `nu-protocol`(Or define it in the top level of `nu-command` crate? I'm not sure), so we have chance to make `math mode` and `histogram` share the same code~.

To handle this, we introduct `HashableValue` inside `chart` package, but it may be used in other commands in the future (like math mode).

## Test code Part: Why tests code changed?
* refer to #3215, we need to change percentage calc method in default
* `get column` in a table not return a single value anymore, it will return a list, to we need to attach a more `get 0` to retrieve proper result
* `to json` output changed, after checking the behavior, I think it's ok to adjust code to match proper output.

## What can be done if the code is ok
If the code is ok, the following tasks in https://github.com/nushell/nushell/issues/4314 can be done
* commands::histogram::count - (histogram command doesn't exist yet)
* commands::histogram::summarizes_by_column_given - (histogram command doesn't exist yet)
* commands::histogram::summarizes_by_values - (histogram command doesn't exist yet)

# Tests

Make sure you've run and fixed any issues with these commands:

- [x] `cargo fmt --all -- --check` to check standard code formatting (`cargo fmt --all` applies these changes)
- [x] `cargo clippy --all --all-features -- -D warnings -D clippy::unwrap_used -A clippy::needless_collect` to check that you're using the standard code style
- [x] `cargo build; cargo test --all --all-features` to check that all the tests pass

### CODE REVIEW

**Comment by fdncred** [comment]
oh, wow! I'm going to have to try this out and play a bit.

**Comment by fdncred** [comment]
oh wow, this is very nice. Good work!
```
> ls **/* | where type == file | get name | path parse | get extension | histogram | sort-by percentage | reverse
╭────────────────────┬───────┬────────────┬────────────────────────────────────────────────────────────────────────────────╮
│       value        │ count │ percentage │                                   frequency                                    │
├────────────────────┼───────┼────────────┼────────────────────────────────────────────────────────────────────────────────┤
│ o                  │ 32443 │ 78.80%     │ ****************************************************************************** │
│ d                  │  1933 │ 4.70%      │ ****                                                                           │
│ rmeta              │  1573 │ 3.82%      │ ***                                                                            │
│ rlib               │  1187 │ 2.88%      │ **                                                                             │
│                    │  1109 │ 2.69%      │ **                                                                             │
│ rs                 │   899 │ 2.18%      │ **                                                                             │
│ bin                │   696 │ 1.69%      │ *                                                                              │
│ h                  │   489 │ 1.19%      │ *                                                                              │
│ lock               │   235 │ 0.57%      │                                                                                │
│ timestamp          │   206 │ 0.50%      │                                                                                │
│ dylib              │    87 │ 0.21%      │                                                                                │
│ ll                 │    62 │ 0.15%      │                                                                                │
│ hjson              │    59 │ 0.14%      │                                                                                │
│ json               │    54 │ 0.13%      │                                                                                │
│ toml               │    34 │ 0.08%      │                                                                                │
│ md                 │    19 │ 0.05%      │                                                                                │
│ a                  │    17 │ 0.04%      │                                                                                │
│ nu                 │    15 │ 0.04%      │                                                                                │
│ png                │    14 │ 0.03%      │                                                                                │
│ gif                │     5 │ 0.01%      │                                                                                │

```

**Comment by elferherrera** [comment]
I like it. Could it be done by using the custom value trait?

**Comment by stormasm** [comment]
I reviewed the code and it looks good to me, nice job !
@WindSoilder your implementation is clean with minimal code changes to the underlying nu-protocol as well...
👍

**Comment by elferherrera** [comment]
After checking the code again, the Hashable Struct doesn't need to be in protocol. It can live happily in nu-command next to the chart command

**Comment by stormasm** [comment]
@elferherrera great catch ! perfect...
then it should definitely be moved over to nu-command if that is the case...

in the future if we find other places in our code where we would need
this functionality then we can address the proper place for it ?

@fdncred curios to know your thoughts on this point...

**Comment by elferherrera** [comment]
If we want to create more commands that use Hashable, it can implement custom value

**Comment by stormasm** [comment]
So I went back and reviewed the code again too...
After @elferherrera last comment...

And yes, its literally a simple cut / paste from

nu-protocol/src/value/hashtable_value.rs
into
historgram.rs

and everything should work 😄

**Comment by fdncred** [comment]
> @fdncred curios to know your thoughts on this point...

@stormasm I like to leave this stuff to you guys who work on the internals. I prefer to focus on the ui/ux.

@jntrnr what's your take on this?

**Comment by WindSoilder** [comment]
> If we want to create more commands that use Hashable, it can implement custom value.

@elferherrera Sorry, I've looked into custom value trait, and don't get the idea...  I think it plays an important role in nu core, `DataFrame` and `Db` feature make more use of it.

But when will a struct need to implement `custom value` trait?
(Here is my guess: it's needed when a struct need to interactive with other commands through pipeline, or output directly to user, but I'm not sure...)

And yeah, I'm happy to move this into `nu-command`. 

I'll move back inside `chart` first, if we can share the same code, then put it elsewhere inside `nu-command`.

**Comment by stormasm** [comment]
@WindSoilder yes, sounds like a great idea ! go for it...

**Comment by elferherrera** [comment]
@WindSoilder as you said, the custom value trait is for values that will interact with more functions. I could forsee a case where other function converts normal values to Hashable ones and then we can do more operations with them. But we can start with just moving them to the histogram command and move forward from there

**Comment by fdncred** [comment]
very nice @WindSoilder. thanks for working with us on this. let's land it!

**Comment by stormasm** [comment]
@WindSoilder great job on this PR !  Thank you so much, looking forward to working with you more on Nushell....

**Comment by kubouch** [comment]
@WindSoilder This is awesome! I hacked my own `histogram` using Nushell commands but it's 100x slower than this one :-D. 

I have one suggestion: Instead of the percentages being a string with the `%` attached, having them as decimal numbers would make them easier to work with. And my personal preference: I'd also remove the 100x scaling and report them as a raw ratios (e.g., 0.701 instead of 70.1%) because when displayed in a column, raw ratios will have uniform width as they can be max. 1.0.

**Comment by fdncred** [comment]
i like `%` too and agree it's easier to read. i'd support the `quantile` column as decimal.

**Comment by kubouch** [comment]
We can have a "quantile" column (should it be called "percentile?) with the decimal ratio if you prefer having the `%`. For me, the important thing is to have a way to easily process the data further without string pasing.

**Pull request merged**
