### PR TITLE
get rid of reading file during parse

### LINKED ISSUE #3822: A hang occurs when typing `source /dev/stdin`
**Describe the bug**
Nushel hangs when trying to type `source /dev/stdin`.

**To Reproduce**
1. Open Nushell
2. Try to type `source /dev/stdin`
3. It hangs when pressing the last <kbd>N</kbd> key and the letter `n` is not displayed

**Expected behavior**
It should not hang.

**Screenshots**
image

**Configuration (please complete the following information):**

Run `version | pivot` and paste the output to show OS, features, etc.

```
> version | pivot
  #        Column0                                               Column1
────────────────────────────────────────────────────────────────────────────────────────────────────────────────
  0   version              0.33.0
  1   build_os             linux-x86_64
  2   rust_version         rustc 1.53.0
  3   cargo_version        cargo 1.53.0
  4   pkg_version          0.33.0
  5   build_time           2021-07-20 18:48:12
  6   build_rust_channel   release
  7   features             clipboard-cli, ctrlc, default, ptree, rustyline, term, trash, uuid, which, zip
  8   installed_plugins    binaryview, chart bar, chart line, fetch, from bson, from sqlite, inc, match, post,
                           ps, query json, s3, selector, start, sys, textview, to bson, to sqlite, tree, xpath
```

**Add any other context about the problem here.**

### PR DESCRIPTION
**Pull request by flappyBug**
This should close #3822 and #3785

### CODE REVIEW

**Comment by jntrnr** [comment]
@flappyBug - if we remove reading the source file, how will the `source` command work? We're reading the file contents during parse because we'll need those definitions during parse time.

We may want to make the file reading more robust so if it runs into issues, we can handle those errors better.

**Comment by flappyBug** [comment]
@jntrnr Sorry, I didn't get why we need the definition in file during parse time. I have tested if we have defs in source script, we can get those defs after execution.

The actual execution is in Success arm of match bellow:
https://github.com/nushell/nushell/blob/1e15f26e98ffaeccd7bb4ca6e3377ff484ef0744/crates/nu-cli/src/cli.rs#L334-L343

**Comment by jntrnr** [comment]
@flappyBug - Nushell uses the definitions at parse time because the definitions tell nushell how to parse other commands. Parse time lets us do both parsing and type checking, and the types tell the parser how to handle the commands.

**Comment by fdncred** [comment]
so, if i'm reading these comments right, what needs to happen is it needs to read the file, as it did before, but only if, it's not one of the exceptions mentioned in the issues for windows/mac/linux.

**Comment by jntrnr** [comment]
@fdncred - yup, that sounds right to me, too

**Comment by flappyBug** [comment]
@jntrnr Thanks for your explanation. But I still think that reading files during parse time is not a reasonable behavior. At least we have something more to optimize other than exclude specific file name.
1. As mentioned in above issues, if we try to source files like `CON`, `stdin`, there will be a halt.
2. If we happened to source a large file, there will be a lag.
3. The reading file behavior happened every key stroke when typing interactively in terminal, even the command is ended with a comment, or in another pipeline.

I'm new to system programming, let me know if I make things wrong. Thanks for your patience.

**Comment by jntrnr** [comment]
@flappyBug - one way to think of it is to think about how an IDE works. When you're typing in the IDE, and add a line of source that imports from a file, then in the IDE it will find that file for you so that you can get completions for the definitions from the file.

Nushell is similar to an IDE in that way. If you import something, we want to make those definitions available to the user so that they can get completions, errors, etc.

To your specific points:

1. Yes, we should definitely exclude reading from files that are reserved in that OS
2. If it's a large source file, hopefully you'll feel very little lag if we do a good job of loading and parsing. This is a case though where we can improve our techniques as well. Some IDEs, for example, will quickly parse a file looking only for definitions, and only later finish parsing if it needs to.
3. I think this might be a limitation of the current nushell system. We're working on a new system to replace the current parser that should be able to cache a file it's loaded before, so that the file is only loaded once

**Comment by flappyBug** [comment]
Thanks for your further explanation. I think I should close the pr for now.

**Comment by fdncred** [comment]
Sorry to see this close. It was close, we just needed to put some checks in for specific file names. Thanks anyway.

**Pull request closed without merging**
