### PR TITLE
Ansi as const

### PR DESCRIPTION
**Pull request by amtoine**
related to
- #10239

# Description
this PR makes `ansi` a parse-time constant command.

this mostly
- moves the `run` method of the command to a `run` function
- adds a `run_const` method to `Command`
- uses `call.req` and `call.req_const` to get the color `code`

# User-Facing Changes
this will allow things like
```nushell
const FOO = (ansi red)
```
or
```nushell
const BAR = $"(ansi blue)bar(ansi reset)"
```

# Tests + Formatting

# After Submitting

### CODE REVIEW

**Comment by amtoine** [comment]
@kubouch 
i think i got it working because the following is now possible and is not on `0.87.0`
```nushell
const FOO = (ansi red)
```
however the following still does not work on this PR
```nushell
const FOO = $"(ansi cyan)foo(ansi reset)"
```

i think this does not have anything to do with this PR and that just Nushell does not support string interpolation as being constant :smirk: 

on `0.87.0`:
```nushell
const BAZ = (1 + 2)
```
does work but the following does not and is not a parse-time constant :open_mouth: 
```nushell
const BAZ = $"(1 + 2)"
```

**Comment by amtoine** [comment]
i don't have time to work on this right now...
so i'll go ahead and close this, it will still be available in the list of my closed PRs :relieved:

**Comment by sholderbach** [comment]
Just to make sure did you intend to delete the branch on your fork as well?

**Comment by amtoine** [comment]
> Just to make sure did you intend to delete the branch on your fork as well?
>
yes i did :wink:

**Comment by kubouch** [comment]
Ah, that's a pity, I somehow missed this! We can totally make `ansi` const.

The examples you shared above that are not working are not working because string interpolation doesn't seem to be const currently (it can probably be made so, though).

**Pull request closed without merging**
