### PR TITLE
Feature/open ndjson

### LINKED ISSUE #8574: JSON Lines support
### Related problem

_No response_

### Describe the solution you'd like

[JSON Lines](https://jsonlines.org/) is becoming a pretty popular format in the data world, and it might be helpful to introduce support for it as an input format (or perhaps input and output).

### Describe alternatives you've considered

It is possible to handle JSON Lines files by splitting the file contents and parsing each line as JSON, so it isn't strictly necessary to have language-level support for this. However, there would be some benefits of having it directly supported (e.g., integration with the feature that recognizes a file's structure from its extension).

### Additional context and details

_No response_

### PR DESCRIPTION
**Pull request by utouto97**
close #8574

# Description

`open` command can open `.ndjson` files directly.
(Previously, we needed to do something like `open abc.ndjson --raw | from json -o`)

# User-Facing Changes

We can open `.ndjson` files with `open` now.

# Tests + Formatting

`toolkit check pr`
- :green_circle: `toolkit fmt`
- :green_circle: `toolkit clippy`
- :green_circle: `toolkit test`
- :green_circle: `toolkit test stdlib`
# After Submitting

### CODE REVIEW

**Comment by fdncred** [comment]
hmmm, I'm wondering if we should add `.jsonl` to this too. I _think_ `.ndjson` and `.jsonl` both represent complete and valid json on each line.

https://jsonlines.org/
http://ndjson.org/

Please correct me if I'm wrong.

**Review by amtoine — COMMENTED** [review]
mm shouldn't we add `from ndjson` / `from jsonl` and let `open` handle the opening by itself?

for instance, i have this in my config
```nushell
def "from ndjson" []: string -> any {
    from json --objects
}
```
and `open` is now able to open `.ndjson` files without doing any extra work :smirk:

**Comment by sholderbach** [comment]
Wouldn't this be a great candidate for the standard library prelude. So we don't need hardcoded special casing in the `open` impl and every advanced nu user can quickly see what's going on?

**Comment by amtoine** [comment]
@sholderbach 
agree that would be great :ok_hand:

**Comment by jntrnr** [comment]
:+1:  on adding to the standard library

**Comment by amtoine** [comment]
@utouto97 
can you have a look into this? :innocent:

**Comment by amtoine** [comment]
- closing in favor of https://github.com/nushell/nushell/pull/10283

**Pull request closed without merging**
