### PR TITLE
adding changes for all-trim option

### PR DESCRIPTION
**Pull request by palashahuja**
This PR resolves [#3482](https://github.com/nushell/nushell/issues/3482)

This commit allows trimming all the whitespace characters from the column. 

Something like 
`echo ' Hello    World  ' | str trim --all` should give `Hello World`

### CODE REVIEW

**Comment by fdncred** [comment]
If I really wanted to trim _all_ how would I do it?

**Comment by palashahuja** [comment]
Do you mean something like trimming `' Hello      World '  -> 'HelloWorld'`? 
If so, we could add another flag `-f`  that would trim the whitespaces in a pretty format way. 
I was also thinking of an implementation like this. Let me know if this is a good idea and I can proceed with it. 
```
str trim -h
trims text

Usage:
  > str trim ...args {flags} 

Parameters:
  ...args: optionally trim text by column paths

Flags:
  -h, --help: Display this help message
  -c, --char <string>: character to trim (default: whitespace)
  -l, --left: optionally trim character or whitespace from the beginning of text (default: whitespace)
  -r, --right: optionally trim text from the end by column paths (default: whitespace)
  -f, --format: trims characters from the string in a pretty formatted way (default: whitespace)
  -a, --all: trims all characters (default: whitespace)
```

**Comment by jonathandturner** [comment]
Can we keep `trim` to mean trimming the whitespace on the left and right? We could use a flag like `--both` to mean trimming both left and right.

**Comment by nathom** [comment]
Shouldn't trimming all whitespace be left to some sort of find and replace function? `trim` colloquially means trimming whitespace from the ends. I think it would be confusing if nu changes the definition needlessly.

**Comment by fdncred** [comment]
> Do you mean something like trimming ' Hello World ' -> 'HelloWorld'?

Yes, that is what I meant.

I like the idea of combining all these things into one command. Perhaps something like this:
```
str trim -h
trims text

Usage:
  > str trim ...args {flags}

Parameters:
  ...args: optionally trim text by column paths

Flags:
  -h, --help: Display this help message
  -c, --char <string>: character to trim (default: whitespace)
  -l, --left: trims characters only from the beginning of the string (default: whitespace)
  -r, --right: trim characters only from the end of the string (default: whitespace)
  -a, --all: trims all characters from both sides of the string *and* in the middle (default: whitespace)
  -b, --both: trims all characters from left and right side of the string (default: whitespace)
```

**Comment by palashahuja** [comment]
According to PR - #3482, we want to trim spaces in such a way that there is a single character left in the middle in terms of all the spaces. I was planning to add that as a `-f` flag as well.

**Comment by fdncred** [comment]
@palashahuja - marking as a draft until you're finished with the `-f` parameter.

**Pull request closed without merging**
