### PR TITLE
feature: flakify nushell

### PR DESCRIPTION
**Pull request by MangoIV**
# Description

This adds nix compatibility to nu-shell for easy use with the nix package manager. 

# User-Facing Changes

- no changes for the user, except for the option to optionally install and use `nu` via nix flakes. 
- if you have nix and direnv installed, you will now be slapped by `pre-commit-hooks` to please run formatting and linting, before commiting. 
- I can, perhaps, remove the `.envrc` as a user of `direnv` with something other than `nix` might be upset by it being specified 

# Tests + Formatting

I've added a github action that builds nu, nu docs, nu tests and formatting and linting checks via nix. 

- [x] `cargo fmt --all -- --check` to check standard code formatting (`cargo fmt --all` applies these changes)
- [x] `cargo clippy --workspace -- -D warnings -D clippy::unwrap_used -A clippy::needless_collect` to check that you're using the standard code style
- [x] `cargo test --workspace` to check that all tests pass
- [x] `nix -Lv flake check` 
- [x] `pre-commit run --all`

# After Submitting

I have not added documentation because I'm unsure how this should be documented. A nix user will not have issues to use this as it doesn't use anything non-standard and the available outputs can be easily introspected by using `nix flake show github:mangoiv/nushell/mangoiv/flakify-nushell`

### CODE REVIEW

**Comment by MangoIV** [comment]
ah, damn, I made a mistake in the legacy gh action.

**Comment by fdncred** [comment]
Thanks for thinking of us enough to add a PR!

I'm not a big fan of adding more to our already slow ci. Also, not a fan of adding ci and scripts for a specific flavor of linux or linux package manager. Maybe others will disagree with me?

**Comment by kubouch** [comment]
I have nothing against supporting nix but this PR adds a significant amount of code and new files. AFAIK, none of the core team members use Nix, at least not on the regular basis and we'd have to maintain all of it. Could the solution be to have this collection somewhere else than the Nushell's main repo?

Also, as Darren said, our CI is already quite overloaded and we'd rather not add more stuff to it if possible.

**Comment by kubouch** [comment]
Adding all the crates to the workspace sounds like a good idea to me, not sure why it wasn't the case before. Maybe someone else knows.

**Comment by MangoIV** [comment]
>  have nothing against supporting nix but this PR adds a significant amount of code and new files. AFAIK, none of the core team members use Nix, at least not on the regular basis and we'd have to maintain all of it. Could the solution be to have this collection somewhere else than the Nushell's main repo?

> Also, as Darren said, our CI is already quite overloaded and we'd rather not add more stuff to it if possible.

Thank you, that makes sense. So does that mean that I should just immediately close this PR or should I perhaps just remove the github workflows? 

> Also, not a fan of adding ci and scripts for a specific flavor of linux or linux package manager

This is quite the common argument against adding `nix` code and it's quite understandable, too, but consider this: many repositories do have a dockerfile, nix kinda solves the same problems and perhaps it will lead to more adaptation in the nix community, too. Using a devenv with nix is *trivial*, it's literally `nix develop` and you will have all the dependencies.

**Comment by MangoIV** [comment]
> Could the solution be to have this collection somewhere else than the Nushell's main repo?

yes, this is certainly possible.

**Comment by MangoIV** [comment]
okay, I will close this and have a repo that adds this flake, I will open a new PR for the changes to the `Cargo.*`

**Comment by kubouch** [comment]
@MangoIV  OK, I see you added the nix config to https://git.sr.ht/~mangoiv/nu-shell.nix. If you find a place where we could link to it in our README / documentation, feel free to open a PR, we can add the link somewhere. It could be also linked in https://github.com/nushell/awesome-nu under Integrations maybe.

**Comment by MrFoxPro** [comment]
@fdncred @MangoIV What about adding flake.nix to root of repo, so people could easily install Nushell from source via `nix profile install github:nushell/nushell`? It doesn't necessary to add CI checks.

**Comment by MangoIV** [comment]
- It is necessary to add ci checks 
- this has been rejected independently of the ci checks. 
- see https://git.sr.ht/~mangoiv/nu-shell.nix

**Comment by MangoIV** [comment]
nix run sourcehut:~mangoiv/nu-shell.nix

**Comment by MangoIV** [comment]
It's listed on the awesome nu integrations but yeah, you would have to check (as you always have to) 

But you can check once, then pin the nix code and just update nu (with inputs.nu.follows = "myNuInput";

**Comment by MangoIV** [comment]
That's how I do it (but also it's my repo and I trust myself)

**Comment by kubouch** [comment]
Btw @MangoIV we now have https://github.com/nushell/integrations, feel free to add your flake.nix there.

**Comment by Abdillah** [comment]
@kubouch How does the integrations repo work? There seemingly `src` branch there.

---

Nix flake is not just for installation. It is also a tool to prepare dev environment and runtime dependency.
Hence, anyone can get start the dev faster (without figuring out dependencies to install).

Btw, I think this PR should only adds `flake.lock` and `flake.nix`, other changes can be negotiated.

**Comment by kubouch** [comment]
The format is relatively open as there is not much content For adding flakes, I guess there could be a nix subdirectory, for example. PRs can be submitted freely. I don't know what the src branch is about.

**Comment by Abdillah** [comment]
Okay thanks. 

But, that's a bit unusual for a flake to be separate from the source. AFAIK, the existence of flake files enable the repo to be identified as package or development shell.

Is there a way we can at least add two files to Nushell repo? (flake.nix, flake.lock)

**Comment by kubouch** [comment]
For now, we're trying to avoid package manager--specific files in our repository, we can't maintain every possible package manager. For example, the [Zig language](https://github.com/ziglang/zig) follows the same strategy and doesn't have flake files, yet the community maintains separate [flake](https://github.com/mitchellh/zig-overlay) [repositories](https://github.com/erikarvstedt/nix-zig-build), so 3rd party flakes seem to be possible. We're willing to host them in the community-maintained integrations repository.

**Comment by Abdillah** [comment]
Okay, that's understandable..
I'll try to explore on that option. It is also possible to make a script that download the flakes into this repository locally for development.

**Pull request closed without merging**
