### PR TITLE
Add "regex" search term to commands with regex functionality

### PR DESCRIPTION
**Pull request by ja-cop**
Just makes it easier to find these commands when using the `help` system - the `find` command already has the "regex" search term.

### CODE REVIEW

**Comment by fdncred** [comment]
Could you maybe add the other commands too that have `--regex(-r)` parameters?

**Review by amtoine — CHANGES_REQUESTED** [review]
@ja-cop 
i think you're just missing the `split column` command :yum: 

according to `rg '"regex"'`, we have the following files to modify :smirk: 
- [x] `crates/nu-command/src/strings/parse.rs`
- [x] `crates/nu-command/src/strings/split/column.rs`
- [x] `crates/nu-command/src/strings/split/list.rs`
- [x] `crates/nu-command/src/strings/split/row.rs`
- [x] `crates/nu-command/src/filters/find.rs`

**Review by sholderbach — APPROVED** [review]
Thank you very much for improving the consistency and discoverability here!

**Comment by amtoine** [comment]
thanks @ja-cop for adding the `split column` command :blush:

**Pull request merged**
