### PR TITLE
feat: Add sensitive flag to get, fix #4295

### LINKED ISSUE #4295: Add cross-platform shorthand for getting Path/PATH
On Windows, environment variable names are case-insensitive and sometimes you can end up having PATH, other times Path in Nushell's env. A cross-platform code that detects it would need to look like this:
```
let path = if (sys).host.name == "Windows" {
    if ("Path" in (env).name) {
        $env.Path
    } else {
        $env.PATH
    }            
} else {
    $env.PATH
}
```

We could have `env path` command that would basically run the above snippet and fail if not Path/PATH was found.

Another way would be to have a way to do case-insensitive env var lookup, something like `env get -i path`. This one would be wordier but has the advantage that it would work on all env vars, not just Path/PATH.

### PR DESCRIPTION
**Pull request by hustcer**
# Description

feat: Add sensitive flag to get, fix #4295

# Tests

Make sure you've run and fixed any issues with these commands:

- [x] `cargo fmt --all -- --check` to check standard code formatting (`cargo fmt --all` applies these changes)
- [x] `cargo clippy --workspace --features=extra -- -D warnings -D clippy::unwrap_used -A clippy::needless_collect` to check that you're using the standard code style
- [x] `cargo test --workspace --features=extra` to check that all the tests pass

### CODE REVIEW

**Comment by fdncred** [comment]
hmmmm, quite a change here. if we're going to make --ignore-errors --quite, we should also do it for `do` I think.

**Comment by hustcer** [comment]
I guess `do -i` may be widely used, I'm not quite sure we should do that or not

> hmmmm, quite a change here. if we're going to make --ignore-errors --quite, we should also do it for `do` I think.
>

**Comment by fdncred** [comment]
Ya, I don't really like breaking changes. Maybe we should leave --ignore-errors and make insensitive something else.

**Comment by hustcer** [comment]
> make insensitive something else

Any suggestions? how about no short flag and only a long flag: `get --insensitive`, just like `save` has `--append` but no `-a` (I don't know why save don't have `-a`)

**Comment by fdncred** [comment]
or you could make it `-s` for `--sensitive`.

**Comment by fdncred** [comment]
ya, I meant to make the default insensitive when I changed completions recently. I still think we should all things default to insensitive.

**Comment by hustcer** [comment]
> ya, I meant to make the default insensitive when I changed completions recently. I still think we should all things default to insensitive.

I think it's ready now

**Comment by fdncred** [comment]
ok, let's try it.

**Pull request merged**
