### PR TITLE
Add support to render right prompt on last line of the prompt

### PR DESCRIPTION
**Pull request by nibon7**
# Description

Depends on nushell/reedline#492

* `new_line` `line_break`
Screenshot from 2022-10-18 15-56-15

* `new_line`  ~~`line_break`~~
Screenshot from 2022-10-18 16-00-28

* ~~`new_line`~~  `line_break`
Screenshot from 2022-10-18 15-55-51

* ~~`new_line`~~ ~~`line_break`~~
Screenshot from 2022-10-18 15-55-27

# Tests

Make sure you've done the following:

- [ ] Add tests that cover your changes, either in the command examples, the crate/tests folder, or in the /tests folder.
- [ ] Try to think about corner cases and various ways how your changes could break. Cover them with tests.
- [ ] If adding tests is not possible, please document in the PR body a minimal example with steps on how to reproduce so one can verify your change works.

Make sure you've run and fixed any issues with these commands:

- [x] `cargo fmt --all -- --check` to check standard code formatting (`cargo fmt --all` applies these changes)
- [x] `cargo clippy --workspace --features=extra -- -D warnings -D clippy::unwrap_used -A clippy::needless_collect` to check that you're using the standard code style
- [x] `cargo test --workspace --features=extra` to check that all the tests pass

# Documentation

- [x] If your PR touches a user-facing nushell feature then make sure that there is an entry in the documentation (https://github.com/nushell/nushell.github.io) for the feature, and update it if necessary.

### CODE REVIEW

**Comment by nibon7** [comment]
> It seems like there are 3 modes, is that right?

Indeed, there are two, above and below. :joy: Because I changed the settings, you might mistakenly think there are 3 modes

**Comment by fdncred** [comment]
I guess my question is, should we support these 3 modes natively (with or without starship) or should we just have it as true/false, like you have it now?

**Comment by nibon7** [comment]
sorry to misunderstood. I think it's hard to determine which is `left_prompt` that you said, e.g. `let-env PROMPT_COMMAND = { "PROMPT1\nPROMPT2\nPROMPT3\nPROMPT4" }`. Maybe we can use 'top', 'center' or 'bottom'. :)

**Comment by fdncred** [comment]
it seems like we could have `above`, `same_line`, `below` or something like those.

**Comment by sholderbach** [comment]
As this is cosmetic and you are discussing the best way forward to configure that, I would suggest waiting on this one for the next release cycle?

**Comment by nibon7** [comment]
> it seems like we could have above, same_line, below or something like those.

I don't know how `same_line` works if left prompt has multiple lines :(

**Comment by fdncred** [comment]
@sholderbach I agree.

@nibon7 I see what you're saying. Let me draw a quick picture of a 2 line prompt to maybe help. In these examples the left prompt is 2 lines with prompt text on the first line and the prompt indicator on the second line.

mode 1 - the right_prompt text is `above` left_prompt text
```
                  01:57:03 PM
~/src/nushell
>
```
mode 2 - the right_prompt text is on the `same_line` as the left_prompt text
```
~/src/nushell       01:57:03 PM
>
```
mode 3 - the right_prompt is `below` left_prompt text
```
~/src/nushell
>                  01:57:03 PM
```
so really the terms are referring to where the right_prompt text is in relation to the left_prompt text (not the prompt indicator). honestly, i really have no idea why anyone would want mode 1 but who knows?

Does this help you understand what I'm suggesting?

**Comment by nibon7** [comment]
Thanks for your explanation. In your example,  I think left prompt is something like `let-env PROMPT_COMMAND = { $"($env.PWD) \n> " }`, but how we show right prompt when `let-env PROMPT_COMMAND = { "PROMPT1\nPROMPT2\nPROMPT3\nPROMPT4\n > " }`? :joy:

**Comment by fdncred** [comment]
This is how I'd do `same_line` in your example.

mode 2 `same_line`
```
PROMPT1             
PROMPT2
PROMPT3
PROMPT4             RIGHT_PROMPT
>
```
maybe it should be called `last_line` which means the right prompt shows up on the last line of the left_prompt, which isn't the prompt_indicator line.

**Comment by nibon7** [comment]
> mode 1 - above all left_prompt
> mode 2 - on the last_line of the left_prompt
> mode 3 - on the prompt_indicator line

Shall we implement this?  Considering the left prompt and prompt indicator may contain multiple newlines, I think these three modes are too complicated and confused, and the current implementation is clear and straightforward. :)

**Comment by fdncred** [comment]
if you want to land some interim version for us to try out, that's fine too. I just hoping whatever lands will include this use case.
```
~/src/nushell       01:57:03 PM
>
```
was thinking of switching my prompt to something like that recently.

**Comment by nibon7** [comment]
>I just hoping whatever lands will include this use case.
> 
> ```
> ~/src/nushell       01:57:03 PM
> >
> ```


It covers this use case if there are no multiple newlines before `~/src/nushell`.
And the leading newlines could be skipped if you want.

**Comment by nibon7** [comment]
This feature depends on nushell/reedline#492, so the CI could be fixed by waitting nushell/reedline#492 or patching crates.io.

**Comment by fdncred** [comment]
@nibon7 nushell/reedline#492. if you can get the ci green, we can land this. thanks.

**Comment by nibon7** [comment]
@fdncred reedline has been pointed to @dandavison's personal repo, and this change has not been merged by reedline, shoud we wait the tab inline completion feature to be merged? :joy:

**Comment by sholderbach** [comment]
I landed the PR nushell/reedline#498 so you can repoint to main and run `cargo update --package reedline`

**Comment by nibon7** [comment]
Thanks @sholderbach

**Comment by nibon7** [comment]
I think there is a fix should be included, see nushell/reedline#501.

**Comment by sholderbach** [comment]
Would you mind adding your improvements to the upcoming [release notes](https://github.com/nushell/nushell.github.io/pull/647) and the [prompt config documentation](https://github.com/nushell/nushell.github.io/blob/main/book/coloring_and_theming.md#prompt-configuration-and-coloring)?

**Comment by nibon7** [comment]
ok

**Comment by fdncred** [comment]
@nibon7 what am i doing wrong here? No matter what I do, I always get the right prompt on the last line.
image
no matter if `render_right_prompt_on_last_line` is `true` or `false`
I thought making it false would put it on the same line that has username path branch and setting it to true would put it on the same line as the indicator. did i misunderstand?

**Comment by fdncred** [comment]
ok, nevermind. I can get your changes to work with simplistic prompts. I'm working on someone else's prompt and it's not working right. I'll have to dig in and see what's going on with their prompt. It's weird that the left prompt is breaking the right prompt.

**Pull request merged**
