### PR TITLE
Remove duplicate dependencies

### PR DESCRIPTION
**Pull request by Marwes**
The huge number of dependencies when doing `cargo install` were bugging me so a quick inspection showed `surf` to pull in an old version of hyper/tokio etc. Replacing it with `reqwest` which is already in use removes around 90 dependencies.

Also removed a barely used derive which removed an old syn version.

### CODE REVIEW

**Comment by fdncred** [comment]
oh my! i've been dreaming of someone doing this for a long time. I have a few questions. thank you so much!!!! ❤️ 

1. does it follow redirects?
2. does it still work with [this script](https://github.com/fdncred/nu_scripts/blob/main/make_release/this_week_in_nu_release.nu) from our nu_script repo? same question about [this web scraping script](https://github.com/fdncred/nu_scripts/blob/main/webscraping/scraping.nu).
3. any thoughts on making post use reqwest as well?
4. is there any quirkiness that you've observed?

**Comment by Marwes** [comment]
> does it follow redirects?
yes, 10 by default in reqwest

> does it still work with this script from our nu_script repo? same question about this web scraping script.
No idea, hoping tests would catch any discrepancies. The requests done seem to be very simple though, so I doubt this changes anything.

> any thoughts on making post use reqwest as well?
I did update the post plugin, what else do you mean by post?

**Comment by fdncred** [comment]
> I did update the post plugin, what else do you mean by post?

aaaaaaaaaaaaaaarg!!! i didn't even see that. so sorry. 

I'll try to checkout this PR and see if it still works.  Thanks again!

**Comment by jntrnr** [comment]
Thanks!

**Pull request merged**
