### PR TITLE
fix: Alias crash

### PR DESCRIPTION
**Pull request by ahkrr**
I looked into the Issues around aliases crashing nushell #3138 #3194
This problem occurs if an alias contains Items that aren't `Spanned<String>` or similary "easy" types.
An alias like this
``` sh
 alias push = git push origin $( echo amazing_branch )
```
needs additional parsing down the line for the `$(...) `which leads to the crashes.
This result from the fact that only the `Spans` in the initial substitution of the `alias` get adjusted to point to the `alias` but not the `Items` that get recursively parsed further down the line.
I have an initial approach to solve this by recursively adjusting the spans at the right points.
This won't change the actual parsing logic and should only add 1 mandatory check in the logic where aliases aren't used.
This is still a draft and only covers some of the types that need their Spans adjusted, but it already works for some examples given in the linked issues.
This draft will also see some refactoring to make it more maintainable.

### CODE REVIEW

**Comment by jonathandturner** [comment]
@ahkrr - What are the next steps for this PR?

If you'd like to review it for possible inclusion, you can mark it as "Ready for review".

**Comment by ahkrr** [comment]
Is this approach that I am taking to fix the alias crashes a desired one?
If yes, where should these functions, that modify the spans live? 
Should they stay for themselves, or should they become methods of the different types they are operating on?
Are the function names good enough or are there ones that fit better?

**Comment by jonathandturner** [comment]
I was thinking through this, and it feels like we may want to do the expansion earlier. If we do that, we won't have to re-do a lot of the work that the lexer would have done.

In the lexer, we'll know if we're looking at the command position since it's the first thing on the line, the first thing after a semicolon, or the first thing after a pipe. If we know what the aliases are (or, maybe we just saw one and make note of it), we could then use that knowledge to see and expand into the stream of input we're looking at (as the lexer) and then continue lexing from there.

There are some details to work out but I think this would, hopefully, be both simpler and more future-proof.

**Comment by ahkrr** [comment]
An implementation of aliases that is better integrated into nushell sounds better than patching the bugs in the current approach.
One problem that I was noticing while trying to fix the span problem was, that recursive alias usage would overflow the stack (I hope I am not misremembering something). If aliases get rethought, a form of protection against this, leading to nushell crashing would probably also be good.

**Comment by fdncred** [comment]
Is this still happening? Should we close this?

**Pull request closed without merging**
