### PR TITLE
Autoenv rewrite, security and scripting

### PR DESCRIPTION
**Pull request by samhedin**
# Autoenv
You no longer have to restart nushell after using `autoenv trust`. On startup, nushell reads `nu-env.toml` and stores the trusted files and their hashes. It uses the `sha2` crate to allow for predictable hash values, since `DefaultHasher` can change between versions. This was by request, and if it would be better to avoid adding the dependency, it is simple to revert back to `DefaultHasher`.
## Autoenv trust/untrust
You mark a `.nu-env` file as trusted or untrusted by running `autoenv trust` or `autoenv untrust` in the directory it is in, or by giving the commands the dir path.
If you enter a directory with a `.nu-env` file which was either not trusted on startup, or has a different hash than it had on startup, `nu-env.toml` is read again and the `.nu-env` hash is checked against it.
You still need to restart after using `autoenv untrust`, as I could not come up with a good way to reload this. Just re-reading `nu-env.toml` all the time would work, but it also feels wrong to read a file all the time like that.

## Scripting
In addition to  `env`, each `.nu-env` file may now contain the lines `entryscripts`, `exitscripts` and the section `scriptvars`.
The keys in `scriptvars` must point to a valid command which resolves to a value. After that, the key and value are tracked and removed by nushell like regular environment variables listed under `env`.
Commands in `entryscripts` and `exitscripts` are run when you enter and after you exit a directory. Nushell takes no responsibility for these and does not even show their output. Note that `exitscripts` are not run inside the directory they are declared in.
[edit: new toml format]
``` toml
[env]
k = "v"

[scriptvars]
myscript = "echo 'myval'"

[scripts]
entryscripts = ["touch hello.txt"]
exitscripts = ["touch bye.txt]
```

All comments appreciated! Please do test it if you can.

### CODE REVIEW

**Comment by samhedin** [comment]
The build fails on windows during the test stage without any particular info. All tests pass when I run them locally on win 10. Is there a way to get more information? https://dev.azure.com/nushell/nushell/_build/results?buildId=3291&view=logs&j=3df22538-2a64-5d6a-ccd1-435dcd87d567

**Comment by tionis** [comment]
Hm, I'm getting a Build error:
```
error: linking with `cc` failed: exit code: 1
```

**Comment by samhedin** [comment]
huh... It builds just fine on arch. Something's clearly messed up here - all tests pass when I run them locally on win 10 and arch, but clearly I am being lucky. I have no idea what could be causing this. Need to think

**Comment by tionis** [comment]
Latest Commit is building now (on Arch) for me.

**Comment by samhedin** [comment]
The latest commit basically commented out all code I added just to see if the tests passed. Are you available for some debugging on the nushell discord right now? Try to track down what's messing it up. My name is JustSam there.

**Comment by tionis** [comment]
Sadly not, maybe another time. But I will watch the changes here.

**Comment by samhedin** [comment]
Sounds good!

**Comment by samhedin** [comment]
At last, windows issues fixed! For now...

**Comment by jonathandturner** [comment]
@samhedin - oh wow, this looks impressive. Let me know when you're ready and we'll review

**Comment by samhedin** [comment]
It's all ready to review :)

**Comment by jonathandturner** [comment]
@samhedin - just gave it a try. Do I need to do something different when trusting a directory?

Screenshot from 2020-07-02 15-47-02

**Comment by jonathandturner** [comment]
I'm also still using the previous .nu-env, so I might have to update a few things on my end.

**Comment by tionis** [comment]
I tried it with 35fded94d6e595f5b74a229a33c695e3e74adcac and can report that everything seems to be working as stated above.  
Looks good :+1:, but I think the entry and exit script should be optional and ignored silently.   
I can also confirm that ~/.nu-env seems to behave differently and even environment variables stay between restarts.

**Comment by samhedin** [comment]
> @samhedin - just gave it a try. Do I need to do something different when trusting a directory?
> 
> Screenshot from 2020-07-02 15-47-02

You found an issue! The Autoenv trust command created the path wrong when you gave it `.`: `/home/sam/testme/./.nu-env` instead of `/home/sam/testme/./.nu-env`. That's fixed now.

> but I think the entry and exit script should be optional and ignored silently.
Hmm, I thought about this. I guess it should be that way, and it should be easy to fix.

**Comment by samhedin** [comment]
Alright! Another commit, another try. The format has now changed. The script section and all valid keys (entryscripts and exitscripts) are optional.
``` toml
[env]
k = "v"

[scriptvars]
myscript = "echo 'myval'"

[scripts]
entryscripts = ["touch hello.txt"]
exitscripts = ["touch bye.txt"]
```

**Comment by samhedin** [comment]
Question: Should autoenv give an error message if any section is missing (i.e `env`, `scriptvars`, `scripts`) or just be quiet and happy about it?

**Comment by rrichardson** [comment]
@samhedin  - I'd say it should be quiet and only work with what it is given.

**Comment by jonathandturner** [comment]
@samhedin - gave it a go. If I do:

```
> autoenv trust .
```

I'm able to trust the current .nu-env, and it looks like it works great without a restart.

I ran into an issue if I try to untrust in the same session:

```
> autoenv untrust .
```

If I `cd` into and out of the directory, I still see environment variables come and go as if the file was trusted, even though it should now be untrusted.

**Comment by samhedin** [comment]
As I said in the original post, I didn't want to hot-reload after `autoenv untrust` since this would require re-reading from `nu-env.toml` every time you enter a command and I was afraid of how that would impact people who are running scripts inside nushell.
But things changed - now there are checks to make sure autoenv is only run once per directory change, so maybe it is fine to do IO each time. So have a look at this commit, it should hot-reload both `trust` and `untrust`, hopefully without slowing any scripts down!

**Comment by jonathandturner** [comment]
@samhedin Cool, will keep an eye open for performance issues.

I was just trying the same test again, and getting the same result.

If you're in a trusted directory, and you untrust it, do you still see the same environment variables? 

Feels like we're close.

**Comment by jonathandturner** [comment]
Just noticed I had some stale things in my build cache and a few other things weren't working I think as a result. I'll try cleaning it out and trying again.

**Comment by samhedin** [comment]
Did it work out alright? Untrusting a directory will not immediately unset the variables - you need to leave the directory as usual. Untrust only prevents any new variables and scripts from running. Is this alright behavior?

**Comment by rrichardson** [comment]
I think the behavior of Direnv is that it actively strips any env vars that it controls when you "un-allow" a .envrc (directory) 
That is the behavior I would have expected, but we should decide if that's actually the behavior we want.

**Comment by samhedin** [comment]
Huh, interesting. I would have expected the current behavior to be the norm. I don't believe that this would be a trivial change, but if it's requested I will of course give it a proper go.

**Comment by jonathandturner** [comment]
@samhedin - I think it's worth giving it a try, and seeing if it's doable.

**Comment by samhedin** [comment]
If you run `autoenv untrust` in a directory, do you think that it should
a) remove all vars set by the directory *and* run its exitscripts
b) remove all vars set by the directory *and not* run its exitscripts

**Comment by thegedge** [comment]
I'd lean towards (b). I know that could leave things in a weird state, but I think when we trust a directory, we trust it to run the scripts. When we untrust, we take back that trust and probably shouldn't run the scripts. I'd start there, at least.

**Comment by samhedin** [comment]
I agree completely. I want to add that for a while I didn't even consider adding `autoenv untrust`. How common will it be to untrust a file you trusted previously? Not very common, I expect, since any changes would invalidate it anyway, and if you don't want it you could just delete the file itself.

**Comment by jonathandturner** [comment]
@samhedin - is it possible that it's going up into a parent directory and finding something?

**Comment by samhedin** [comment]
This was my initial thought too, but nope. Very strange.

**Comment by jonathandturner** [comment]
Did some testing with the trust/untrust, scriptvars, and scripts. Things look good enough we should land this so we can use it and continue improving it based on how it feels in practice.

Thanks again for putting all this together!

@samhedin - I did notice that the paths in my nu-env.toml weren't canonical at one point but then couldn't reproduce it. Maybe you fixed something along the way?

**Comment by samhedin** [comment]
> Did some testing with the trust/untrust, scriptvars, and scripts. Things look good enough we should land this so we can use it and continue improving it based on how it feels in practice.
> 

Super exciting! I am very ready for a stream of bug reports.

> @samhedin - I did notice that the paths in my nu-env.toml weren't canonical at one point but then couldn't reproduce it. Maybe you fixed something along the way?

Yes! At some point I started using `std::fs::canonicalize` instead of... whatever I was using before.

**Pull request merged**
