### PR TITLE
Attempt to guess the content type of a file when opening with --raw

### PR DESCRIPTION
**Pull request by ayax79**
# Description
Attempt to guess the content type of a file when opening with --raw and set it in the pipeline metadata. 

Screenshot 2024-08-02 at 11 30 10

# User-Facing Changes
- Content of files can be directly piped into commands like `http post` with the content type set appropriately when using `--raw`.

### CODE REVIEW

**Review by sholderbach — COMMENTED** [review]
Can we craft some tests (maybe skipping the complexity of a full `http post`) to see where that would break down?

**Comment by ayax79** [comment]
@sholderbach, I added tests for all the `to *` commands for checking metadata. As long as we don't mind adding some more temp files for the tests, I can add some for `open`. There aren't currently any tests for `open`.

**Comment by sholderbach** [comment]
Can we use the existing demo files for their content types?

**Comment by ayax79** [comment]
@sholderbach, I added a test using the existing test files. I also made sure that the content types are consistent with what is returns with the `to *` commands.

**Review by sholderbach — APPROVED** [review]
Thanks for the tests, let's see how this plays out using the pipeline metadata in earnest

**Pull request merged**
