### PR TITLE
nu-table: Check perf improvements

### PR DESCRIPTION
**Pull request by zhiburt**
I've made a small patch to `tabled` to switch parsing to `vte` lib (actually to @dandavison usage of it).

I believe it must be faster.
But the benchmarks I've ran didn't showed it.
`1..100000` got a bit faster but it may not show real picture.

So if someone would have time it could be great to see if it's any faster.

### CODE REVIEW

**Comment by dandavison** [comment]
@zhiburt can you post some instructions showing how you do benchmarking? I know you showed some nice graphs, etc.

**Comment by fdncred** [comment]
with casual usage it doesn't seem slower.

**Comment by zhiburt** [comment]
> with casual usage it doesn't seem slower.

I hope so,

It's just my believe it must get better (at least a bit) because we remove 1 `String` call.
But surprisingly I see small downgrades sometimes.

So yes just pondering if it's any better as I haven't found any clear case where it is.

> @zhiburt can you post some instructions showing how you do benchmarking? I know you showed some nice graphs, etc.

Generally I run these https://github.com/zhiburt/tabled/tree/comparision-libs-bench `cargo bench`.
The only thing is that you're interested in a new branch and released one so you would need to make a small changes.

Comment these out https://github.com/zhiburt/tabled/blob/c8691ae71cbc66a1652fd83c5edc8a7bf6613a75/benches/benchmark.rs#L35-L37

Change this https://github.com/zhiburt/tabled/blob/comparision-libs-bench/tabled_color/Cargo.toml#L9 to `tabled = { git = "https://github.com/zhiburt/tabled", rev = "883eeda030e8a822a8d5fcbee2d416b69ac4e42d", features = ["color"], default-features = false }`

**Comment by zhiburt** [comment]
OK it seems like someone made a few mistakes when doing benchmarks (me.....).

I've benchmark local function.

#### string width

```
string_width/tabled-1048576                     168.8±12.19ms
string_width/tabled-256                         35.9±2.06µs
string_width/tabled-262144                      39.7±1.83ms
string_width/tabled-32768                       5.1±0.17ms
string_width/tabled-4194304                     675.0±8.96ms
string_width/tabled_master-1048576              192.8±7.14ms
string_width/tabled_master-256                  34.0±1.53µs
string_width/tabled_master-262144               46.4±2.23ms
string_width/tabled_master-32768                5.1±0.22ms
string_width/tabled_master-4194304              884.8±19.76ms
```

#### string width multiline

```
string_width_multiline/tabled-1048576           168.0±6.15ms
string_width_multiline/tabled-256               37.8±2.62µs
string_width_multiline/tabled-262144            40.0±0.82ms
string_width_multiline/tabled-32768             5.0±0.20ms
string_width_multiline/tabled-4194304           700.7±15.13ms
string_width_multiline/tabled_master-1048576    219.9±11.28ms
string_width_multiline/tabled_master-256        39.3±2.25µs
string_width_multiline/tabled_master-262144     53.8±3.93ms
string_width_multiline/tabled_master-32768      6.5±0.80ms
string_width_multiline/tabled_master-4194304    971.6±27.79ms
```

#### wrapping

```
wrap/tabled-256              109.8±1.77µs
wrap/tabled-262144           117.0±2.23ms
wrap/tabled-32768            15.2±0.98ms
wrap/tabled-4194304          2.1±0.04s
wrap/tabled_master-256       249.5±17.91µs
wrap/tabled_master-262144    254.5±3.19ms
wrap/tabled_master-32768     33.5±2.59ms
wrap/tabled_master-4194304   4.6±0.09s
```

Though it would be interesting to see a 'real' improvements.

**Comment by fdncred** [comment]
if we're comparing `tabled-blah` as the new implementation to `tabled-master-blah` as the old implementation, then it seems faster all around, which is great!

**Comment by fdncred** [comment]
we can land these changes once you publish to crates.io because we're getting close to a release. if you can't publish a couple days before the release on Oct 18th, then we'll land it in the next release. thanks for working on performance so much. it makes a big difference to have a fast table renderer.

**Comment by fdncred** [comment]
Hey @zhiburt, what's the outlook on publishing the crates nushell depends on? I'm assuming they haven't been published yet. We have a release tomorrow and was just checking on this. It's cool to wait until after the release, if you haven't published already.

**Comment by zhiburt** [comment]
> We have a release tomorrow and was just checking on this. It's cool to wait until after the release, if you haven't published already.

I could release it.
But I have in mind a few small things I'd like to merge before.
I hope to have it done by tomorrow.
But not sure whether I'll get it done before you will release nushell.
So it may be better included in the next?

**Comment by fdncred** [comment]
ok @zhiburt, no biggy. Let's just wait until you're comfortable with your fixes. Then we can land this.

**Comment by zhiburt** [comment]
I think it's done.

**Comment by fdncred** [comment]
Thanks @zhiburt. Let's land this now.

**Pull request merged**
