### PR TITLE
Implement bareword interpolation

### PR DESCRIPTION
**Pull request by WindSoilder**
# Description
Close: #12330

After this pr, we can use bareword interpolation to do something like this:
```nushell
let base = "/usr/bin"
let result = $`($base)/ls`  # run ls command and save it to result
```
And something like this:
```nushell
ls $`($nu.default-config-dir)/*.nu`
```
Because backtick quoted is treated as a bareword, so it will list all files under `$nu.default-config-dir`. 

## Warning
To be honest, I'm hesitate to add this feature.

After this pr, we have one more way to expand glob if user want to expand variable, to summarize:
1. **this pr provides**, bareword interpolation:
```nushell
ls $`($nu.default-config-dir)/*.nu`
```
It's useful when user doesn't want to interactive with a variable.  But user can do someting like this as a workaround:
```nushell
ls ($"($nu.default-config-dir)/*.nu" | into glob)
```
Though it looks a little bit verbosely

2. define a variable as glob type:
```nushell
let x: glob = $"($nu.default-config-dir)/*.nu"
ls $x
```
It's useful when writing custom command:
```nushell
def my_list [p: glob] { ls $p }
```

3. use `into glob`:
```nushell
let x = $"($nu.default-config-dir)/*.nu"
ls ($x | into glob)
```
It's more explicitly, and it's a workaround for bareword interpolation:
```nushell
def my_list [p] { ls ($p | into glob) }
```

4. use spreading operator with `glob` command:
```nushell
let x = $"($nu.default-config-dir)/*.nu"
ls ...(glob $x)
```
It makes use of current nushell feature we have.

To be honest I'm a little worried to have too much way to done one job.  If user wants to run a command lays inside dynamic path, we also have a workaround:
```
$`($env.HOME)/nvim`
# it's the same to
^$"($env.HOME)/nvim"
```

But on the other side, it provides a simpler way to expand glob, if user doesn't want to use a variable.

# User-Facing Changes
NaN

# Tests + Formatting
Done

# After Submitting
NaN

### CODE REVIEW

**Comment by fdncred** [comment]
My only real concern with adding this functionality is if there will be unwanted behavior or unintended consequences with paths or files with spaces in them, since the only way to work with them now is with backtick quotes. For instance, can you have a path with a space in it and not have globbing? Is there a way to make a literal path with a path with a space?

**Comment by WindSoilder** [comment]
> For instance, can you have a path with a space in it and not have globbing? Is there a way to make a literal path with a path with a space

I think double quote or single quote works for this scenario.  Backtick quotes is not the only way

**Comment by fdncred** [comment]
> I think double quote or single quote works for this scenario. Backtick quotes is not the only way

I'm pretty sure it is the only way on windows.

double quotes - tries to escape the backslashes
image

single quotes - thinks it's a literal
image

backtick quotes - works
image

Also, something to consider is that backtick quotes are what the completions use.
image

**Comment by WindSoilder** [comment]
Ok, I think I get what you mean.
I have added a test to ensure that bareword interpolation works the same to backtick quoted path: `bareword_interpolation_dont_escape`

**Comment by sholderbach** [comment]
I really think we shouldn't continue naming the special backtick quoted strings "bare words", they can behave *like* bare words  (bare as in no quotes/escaping) can in certain circumstances but now they get more and more special meaning.

**Comment by WindSoilder** [comment]
> I really think we shouldn't continue naming the special backtick quoted strings "bare words"

Hmm...I'm not sure, I remember the position of `backtick quoted` is a "bare words" with a space...So what's the proper name here, maybe "BacktickInterpolation"?

**Comment by IanManske** [comment]
Hmmm, I'm not convinced that this is something we should add. Backticks currently define bare words, which are literal values. Adding runtime interpolation makes backticks more like strings. 

> I really think we shouldn't continue naming the special backtick quoted strings "bare words", they can behave like bare words (bare as in no quotes/escaping) can in certain circumstances but now they get more and more special meaning.

In which circumstances @sholderbach? My understanding is that backticks create, or are the same as, bare words.

**Comment by WindSoilder** [comment]
Yeah, that's a good point to concern.  I will close the pr and relative issue.

**Pull request closed without merging**
