### PR TITLE
Refactor and fix `Config`<->`Value` mechanism

### PR DESCRIPTION
**Pull request by sholderbach**
# Description
Our config exists both as a `Config` struct for internal consumption and as a `Value`. The latter is exposed through `$env.config` and can be both set and read.
Thus we have a complex bug-prone mechanism, that reads a `Value` and then tries to plug anything where the value is unrepresentable in `Config` with the correct state from `Config`.

The parsing involves therefore mutation of the `Value` in a nested `Record` structure. Previously this was wholy done manually, with indices.
To enable deletion for example, things had to be iterated over from the back. Also things were indexed in a bunch of places. This was hard to read and an invitation for bugs.

With #10876 we can now use `Record::retain_mut` to traverse the records, modify anything that needs fixing, and drop invalid fields.

# Parts:

- Error messages now consistently use the correct spans pointing to the problematic value and the paths displayed in some messages are also aligned with the keys used for lookup.
- Reconstruction of values has been fixed for:
	- `table.padding`
	- `buffer_editor`
	- `hooks.command_not_found`
	- `datetime_format` (partial solution)
- Fix validation of `table.padding` input so value is not set (and underflows `usize` causing `table` to run forever with negative values)
- New proper types for settings. Fully validated enums instead of strings:
  - `config.edit_mode` -> `EditMode` 
  	- Don't fall back to vi-mode on invalid string
  - `config.table.mode` -> `TableMode`
    - there is still a fall back to `rounded` if given an invalid `TableMode` as argument to the `nu` binary
  - `config.completions.algorithm` -> `CompletionAlgorithm`
  - `config.error_style` -> `ErrorStyle`
    - don't implicitly fall back to `fancy` when given an invalid value.
  - This should also shrink the size of `Config` as instead of 4x24 bytes those fields now need only 4x1 bytes in `Config`
- Completely removed macros relying on the scope of `Value::into_config` so we can break it up into smaller parts in the future.
- Factored everything into smaller files with the types and helpers for particular topics.
- `NuCursorShape` now explicitly expresses the `Inherit` setting. conversion to option only happens at the interface to `reedline`

### CODE REVIEW

**Comment by fdncred** [comment]
Thanks for taking this on. It's been needed for a while. I'm excited to see your PRs.

**Comment by kubouch** [comment]
One problem with config is also that there is one global Config struct, but there would need to be one config per overlay to work correctly, see also https://github.com/nushell/nushell/issues/7760. I'm thinking, do we need the Config struct at all, or could we just use the `$env.config` record and pull values from it as necessary?

**Comment by kubouch** [comment]
Always using a Value from the environment would also solve the problem encountered in https://github.com/nushell/nushell/pull/10483: No need to clone the entire Config just to get one value from it.

With the new ergonomic Record API, I'm becoming increasingly in favor of ditching the Config struct as it would allow us to sidestep many bugs, e.g., https://github.com/nushell/nushell/issues/7760 https://github.com/nushell/nushell/issues/10175.

**Comment by sholderbach** [comment]
> One problem with config is also that there is one global Config struct, but there would need to be one config per overlay to work correctly, see also #7760. I'm thinking, do we need the Config struct at all, or could we just use the `$env.config` record and pull values from it as necessary?

Yes and no. 

As long as we don't have a mechanism to store and materialize diffs of nested values or another elegant copy-on-write mechanism that allows us to cheaply keep track of the different `$env.config` settings for each overlay or scope we would be still cloning the whole nested record. And that is certainly more expensive than the `Config` struct where the information is more compressed (and `Span`-less) 

In general duplicating the information sucks.

At the same time having explicit types is much better than matching on `Value`s as necessary as it encourages reuse and rules out a bunch of undefined state.

In my view we should go ahead with this PR and then in a follow up we can break up the big processing method into smaller processing functions that take care of the subrecords for better readability.

Then we can do a survey of which config options are read in a hot-loop or which are cold enough that the `Value` overhead would be neglible.

**Comment by fdncred** [comment]
I'd vote to land this sooner rather than later. We're getting close to release date.

**Comment by kubouch** [comment]
Agreed, I'd land it, I just wanted to share some thoughts I had on this topic.

**Pull request merged**
