### PR TITLE
refactor parser: rename method pub fn block to parse_block

### PR DESCRIPTION
**Pull request by stormasm**
This will make it clearer and more precise in the code exactly what this method is doing.  Previously discussed name re-change of this method is happening now that @wycats and @LhKipp first round of lexer and parser refactor work is completed.  This will also make it cleaner and clearer in the code as we move forward on a solution for issue #2972

### CODE REVIEW

**Comment by stormasm** [comment]
@jonathandturner this PR is failing due to this error in 

[hir.rs line 212](https://github.com/nushell/nushell/blame/main/crates/nu-protocol/src/hir.rs#L212)

I am pretty sure this is not a relic of my code changes....

I am not comfortable making any code changes to the hir.rs code as I am not familiar with it...

Any help would be greatly appreciated.

Thanks,
Michael


Checking hyper v0.11.27
2021-02-11T17:52:07.6481130Z error: Unnecessary nested match
2021-02-11T17:52:07.6483410Z    --> crates/nu-protocol/src/hir.rs:213:21
2021-02-11T17:52:07.6487880Z     |
2021-02-11T17:52:07.6585050Z 213 | /                     if let ClassifiedCommand::Internal(internal) = command {
2021-02-11T17:52:07.6589290Z 214 | |                         internal.args.external_redirection = external_redirection;
2021-02-11T17:52:07.6688360Z 215 | |                     }
2021-02-11T17:52:07.6689410Z     | |_____________________^
2021-02-11T17:52:07.6693070Z     |
2021-02-11T17:52:07.6789920Z     = note: `-D clippy::collapsible-match` implied by `-D warnings`
2021-02-11T17:52:07.6794270Z help: The outer pattern can be modified to include the inner pattern.
2021-02-11T17:52:07.6892090Z    --> crates/nu-protocol/src/hir.rs:212:29
2021-02-11T17:52:07.6892950Z     |
2021-02-11T17:52:07.6993210Z 212 |                 if let Some(command) = pipeline.list.last_mut() {
2021-02-11T17:52:07.7093630Z     |                             ^^^^^^^ Replace this binding
2021-02-11T17:52:07.7195560Z 213 |                     if let ClassifiedCommand::Internal(internal) = command {
2021-02-11T17:52:07.7296040Z     |                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ with this pattern
2021-02-11T17:52:07.7397750Z     = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#collapsible_match
2021-02-11T17:52:07.7398630Z 
2021-02-11T17:52:09.3171790Z error: aborting due to previous error
2021-02-11T17:52:09.3194990Z 
2021-02-11T17:52:09.3265290Z error: could not compile `nu-protocol`
2021-02-11T17:52:09.3266940Z

**Comment by jonathandturner** [comment]
I just landed https://github.com/nushell/nushell/pull/3049 to fix the clippy issues. Can you merge main and try again?

**Comment by stormasm** [comment]
@jonathandturner Thanks for fixing the clippy issues, now everything is green.  enjoy your weekend !

**Comment by jonathandturner** [comment]
Looks good!

**Pull request merged**
