### PR TITLE
cleanup version command and add in database feature

### PR DESCRIPTION
**Pull request by stormasm**
Remove all of the old code / old features / old plugins
that were still there from version 0.44...

Add in the new feature **database**

### CODE REVIEW

**Comment by fdncred** [comment]
@stormasm should we also add the new openssl static feature?

**Comment by stormasm** [comment]
@fdncred thanks yes, let me give that a whirl prior to landing this PR...

**Comment by stormasm** [comment]
@fdncred ok its in there...

**Comment by fdncred** [comment]
looks good to me. let's take it for a whirl.

**Comment by stormasm** [comment]
@fdncred thanks for the heads up on the ssl feature...
I am actually not sure how to trigger it though...
I added it in there...
But was not able to see it when I typed the version command.
I am actually not sure the way the Reilly's code (with the feature flag) is now implemented how
to get it to "kick off"

**Comment by fdncred** [comment]
i believe you have to build with something like `--features=extra,static-link-openssl`

**Comment by stormasm** [comment]
@fdncred ok thanks I will check that out later...

**Comment by stormasm** [comment]
@fdncred that is it ! 😄 
I didn't get the release part...  cool !

**Pull request merged**
