### PR TITLE
add signature information when get help on one command

### PR DESCRIPTION
**Pull request by WindSoilder**
# Description

Closes: #7090 
Closes: https://github.com/nushell/nushell/issues/6754
As title, we have signature information for commands, I think it's ok to show that signature when you want to get help message on one command.

Before:
```
﻿❯ help str join
Concatenate multiple strings into a single string, with an optional separator between each

Search terms: collect, concatenate

Usage:
  > str join (separator)

Flags:
  -h, --help - Display the help message for this command

Parameters:
  (optional) separator <String>: optional separator to use when creating string

Examples:
  Create a string from input
  > ['nu', 'shell'] | str join

  Create a string from input with a separator
  > ['nu', 'shell'] | str join '-'
```

After:
```
❯ help str join
Concatenate multiple strings into a single string, with an optional separator between each

Search terms: collect, concatenate

Usage:
  > str join (separator)

Flags:
  -h, --help - Display the help message for this command

Signatures(Cell paths are supported):
  <list<string>> | str join <string?> -> <string>

Parameters:
  (optional) separator <String>: optional separator to use when creating string

Examples:
  Create a string from input
  > ['nu', 'shell'] | str join

  Create a string from input with a separator
  > ['nu', 'shell'] | str join '-'
```

After this pr, we have one more information about signatures.

## Signature format description
In general, a commands signature should looks like this:
```
<string> | command name <string>, <int?> -> <string>
```
More detail explaination:
the first one is the input from previous command, aka, pipeline input
then positional arguments type
then optional arguments type, which ends with `?`
Then followed by `->`
Finally output type.

If a command contains multiple input/output types, separate them in different lines

# Major Changes

If you're considering making any major change to nushell, before starting work on it, seek feedback from regular contributors and get approval for the idea from the core team either on [Discord](https://discordapp.com/invite/NtAbbGn) or [GitHub issue](https://github.com/nushell/nushell/issues/new/choose).
Making sure we're all on board with the change saves everybody's time.
Thanks!

# Tests + Formatting

Make sure you've done the following, if applicable:

- Add tests that cover your changes (either in the command examples, the crate/tests folder, or in the /tests folder)
  - Try to think about corner cases and various ways how your changes could break. Cover those in the tests

Make sure you've run and fixed any issues with these commands:

- `cargo fmt --all -- --check` to check standard code formatting (`cargo fmt --all` applies these changes)
- `cargo clippy --workspace --features=extra -- -D warnings -D clippy::unwrap_used -A clippy::needless_collect` to check that you're using the standard code style
- `cargo test --workspace --features=extra` to check that all tests pass

# After Submitting

* Help us keep the docs up to date: If your PR affects the user experience of Nushell (adding/removing a command, changing an input/output type, etc.), make sure the changes are reflected in the documentation (https://github.com/nushell/nushell.github.io) after the PR is merged.

### CODE REVIEW

**Comment by webbedspace** [comment]
Consider writing `List(String) => String` using the `describe` format: `list<string> => string`

**Comment by WindSoilder** [comment]
Currently I'd like to make it behaves the same to `help commands` bahabior on signature.   @dandavison mentioned about the reason to use `SyntaxShape` rather than `Type`:

https://discord.com/channels/601130461678272522/615329862395101194/1036416055234547782

**Comment by dandavison** [comment]
@WindSoilder let's not assume that what I did in the `help commands` table is perfect - I just did something quick so that we had a way of seeing the types.

@webbedspace @WindSoilder How do you think we should incorporate the positional arguments with the input types? Would you agree that it doesn't make much sense showing the input type only? E.g. consider a function like `str distance `. It's type is clearly "takes in 2 strings and returns an int". But one string is what nushell calls the "input" and the other string is an "argument".

I agree with @webbedspace that we should use the same format everywhere: in the table, in the help text, and in describe. Let's create a shared utility function and use the same function everywhere.

**Comment by dandavison** [comment]
@WindSoilder let's not assume that what I did in the `help commands` table is perfect - I just did something quick so that we had a way of seeing the types.

@webbedspace @WindSoilder How do you think we should incorporate the positional arguments with the input types? Would you agree that it doesn't make much sense showing the input type only? E.g. consider a function like `str distance `. It's type is clearly "takes in 2 strings and returns an int". But one string is what nushell calls the "input" and the other string is an "argument".

I agree with @webbedspace that we should use the same format everywhere: in the table, in the help text, and in describe. Let's create a shared utility function and use the same function everywhere.

Oh, but @WindSoilder is right that they have to be slightly different since `describe` shows the fields on Record and Table, but we can't do that for input types since the fields are typically unknown

@WindSoilder for the input types, how about doing the same as `describe` but using

```
record<any>
table<any>
```

I'm not sure whether people really want lower case types or not. But it's ok to do an initial version here and keep iterating.

**Comment by webbedspace** [comment]
>I'm not sure whether people really want lower case types or not. But it's ok to do an initial version here and keep iterating.

Aren't lowercase types already used by `def`?
```
〉def foo [f:closure, g:string] { [a $g c] | each $f }
```

**Comment by fdncred** [comment]
There's also some discussion about this formatting here https://github.com/nushell/nushell/issues/6754, and this PR should probably close that issue I think.

**Comment by dandavison** [comment]
> Aren't lowercase types already used by def?

Yes, they are, I just meant to start a discussion about whether that was what the project wanted and when exactly we'd use lower- vs uppercase. But I agree we can separate that discussion from this work.

@WindSoilder in this PR would you be able to refactor things so that `describe`, `help commands` and `$command --help` all use the same code to create the formatted representation of their types? I think for now that should be similar to what `describe` does: so you can change the code I added which makes camel case type names. But you'll need to find a way to handle records and tables in input and output types that don't specify fields/columns.

**Comment by WindSoilder** [comment]
> would you be able to refactor things so that describe, help commands and $command --help all use the same code to create the formatted representation of their types? 

That's a good idea, it also solve something @webbedspace mentioned(all help and describe represents the same thing).

> I'm not sure whether people really want lower case types or not. But it's ok to do an initial version here and keep iterating.

In initial version, I think lowercase is ok.

**Comment by WindSoilder** [comment]
Mark as draft for now for further investigation.

**Comment by fdncred** [comment]
I'd be interested in what folks this about the name "Signatures". I really think of signature as more than just this i/o part.
Is this any more intuitive?
```
Input => Output:
  List(String) => String
```
vs
```
Signatures:
  List(String) => String
```

**Comment by sholderbach** [comment]
I think from a tacit convention perspective it would make sense to use `<>` for the datastructure inner types and reserve the `()` for the argument list. 

e.g.
```
str distance
Signature: 

string | (string) => int
list<string> | (string) => int
```

**Comment by webbedspace** [comment]
I was going to suggest using `|` for the separator, actually, but on both sides, so that it can be easier to split them off using string splitting.
By the way, everyone seems to be forgetting one last wrinkle in `str distance`'s signature:
```
str distance
string | string | int
list<string> | string | int
structure | string ...cellpath | structure
```
(N.B: `structure` is a hypothetical shape name for "record or list". Note that the strings inside the `structure` can be arbitrarily deep.)

This is an off-topic aside but I also think there should be a `type` command which functions similarly to `path` in decomposing or performing quick operations on things. Stuff like `a | type is 'string'` or `[a b 'c'] | type domain` (produces `'string'`) or `a | type matches $b`.

**Comment by dandavison** [comment]
@WindSoilder I think that the signature should contain the positional arguments, and maybe rest params and flags, in addition to the input and output types. What do you think about using the information in `$nu.scope.commands` for this?  Have you seen it? E.g.

```
$nu.scope.commands | where name == 'str distance' | get signatures.0 | table -e
```

image


image

As for the exact design of how to present this information in `help foo`, I'm not sure. But if you get the information in there, we can all discuss the exact design. @webbedspace what are you current thoughts on what might be a nice way to present the information in `help foo`? I guess we want it to be accurate, and ideally helpful to less experienced as well as more experienced programmers.

**Comment by WindSoilder** [comment]
> I think that the signature should contain the positional arguments, and maybe rest params and flags, in addition to the input and output types.

I agree with you :-D

----------

For the signature for a specific command.,   I'd propose a signature like this, some of the idea is borrowed from typescript.
```
string => arg1: string, option_arg2?: string, {flags}, ...(rest) => string
```

If a function doesn't need to accept pipeline, the relative signature will be:
```
arg1: string, option_arg2?: string, {flags}, ...(rest) => string
```

If the type is union type, we can use `|` to mark it.
```
string | list<string> => arg1: string, option_arg2?: string, {flags}, ...(rest) => string
```

We may have many flags, so I'd make it a simple `{flags}`, and user can check more information from other part of help message

**Comment by dandavison** [comment]
@WindSoilder. This makes a lot of sense to me.

> If the type is union type

Here, do you mean a command like `into bool` that has multiple input types but only one output type?

What would you do with commands that have multiple input types and multiple output types? Would those each get a separate signature?

> `string => arg1: string, option_arg2?: string, {flags}, ...(rest) => string`

I do like this: it "looks" like a Nushell pipeline.

I just want to mention a few thoughts:

1. Do we need the names? Or could it be

```
string => string, string?, {flags}, ...(rest) => string
```


2. If you are used to something like Haskell type signatures then it might seem normal, but other people might be confused to see two arrows in one function signature.

  An alternative would be to put the input in the first arg position, and put `Nothing` there if the command does not accept input

```
input: string,  arg1: string, option_arg2?: string, {flags}, ...(rest) => string

input: Nothing, arg1: string, option_arg2?: string, {flags}, ...(rest) => string
```

or

```
string,  string, string?, {flags}, ...(rest) => string

Nothing, string, string?, {flags}, ...(rest) => string
```

**Comment by WindSoilder** [comment]
> Here, do you mean a command like into bool that has multiple input types but only one output type?

Yeah, and we may have multiple output types.

> An alternative would be to put the input in the first arg position, and put Nothing there if the command does not accept input

I think that's a good idea, no names can make our signature simpler, and just **one** `=>` is more natural.

---

For multiple input types and output types, combined with your input, I come up with 2 options(take `into bool` as example)

Option 1:
```
int => boolean
number => boolean
string => boolean
boolean => boolean
list<any> => table
```

Option 2(It seems that typescript and python goes with this way):
```
input | number | string | boolean | list<any> => boolean | table
```

BTW: we have 53 commands match for the case

**Comment by dandavison** [comment]
> I think that's a good idea, no names can make our signature simpler, and just one => is more natural.

OK great, I like this. I think you can go ahead and implement it and then we'll see whether the others like that choice of string formatting or want to suggest modifications.

> For multiple input types and output types, combined with your input, I come up with 2 options(take into bool as example)

I think we should do Option 1 because it does not lose any information.

**Comment by dandavison** [comment]
If the rest positionals are cell paths, then I think it would be helpful to format that as

```
string,  string, string?, {flags}, ...cell_paths => string
```

I have removed the `()` do we need it to be `...(rest)` and `...(cell_paths)`, or can it be `...rest` and `...cell_paths`?

**Comment by dandavison** [comment]
I had two more thoughts:

- I don't think we need `{flags}` in the signature. Flags should never affect the output type (those that do are bugs in Nushell that will be fixed) and the user can just look further down in the help entry to see if there are flags.

- I don't think `...cell_paths` should be in the signature. The reason is the following. Consider

```
string,  string ...cell_paths => string  
```

That signature is not accurate: it's not true that `string` input can be used with `cell_paths`. In fact, that signature should really be:

```
string,  string => string
table,  string, ...cell_paths => string  
record,  string, ...cell_paths => string  
list,  string, ...cell_paths => string  
```

But rather than adding the 3 extra ones, it's sufficient just to say "Supports cell paths" in the text.

So the end result of what I'm suggesting is that our signatures can be very simple, e.g.

```
string,  string => string
```

or

```
Nothing,  string => string
```

**Comment by sholderbach** [comment]
>     * I don't think we need `{flags}` in the signature. Flags should never affect the output type (those that do are bugs in Nushell that will be fixed) and the user can just look further down in the help entry to see if there are flags.

I don't know if we can uphold this absolutism for user defined commands. At least with the current language evolution users are not yet used to enforced output types and take nushell more dynamic than your goal.


>     * I don't think `...cell_paths` should be in the signature.

Mhh I think at least for the users it is helpful to know if the cellpath broadcasting is available (and  `...rest` params can make it impossible to implement that unambiguously)

**Comment by dandavison** [comment]
> I don't know if we can uphold this absolutism for user defined commands

Ah good point! I was thinking about builtins only. So to be clear, when I said "Flags should never affect the output type". That was incorrect. But what about the question of whether it is helpful to display `{flags}` in the formatted signature? I'm not sure it is -- it's sufficient to look down the page for documentation of flags isn't it?

For user-defined commands, the signature will come from the type annotations that they add in source code I believe. I'm not sure how a user will type a command for which the output type varies according to flags.

>  I think at least for the users it is helpful to know if the cellpath broadcasting is available

Yes, my suggestion is simply to say that "Cell paths are supported". What do you think of the argument above, starting where it says "That signature is not accurate..."?

**Comment by WindSoilder** [comment]
@dandavison I think that's a good idea, which makes our signature much simpler again.

One thing to concern is: can we assume that if `rest_positional` parameter is `SyntaxShape::CellPath`, we can say it "Supports cell paths" ?  That'll be a new convention in nushell.

**Comment by dandavison** [comment]
> can we assume that if rest_positional parameter is SyntaxShape::CellPath, we say the command "Supports cell paths" ?

Yes I think so. You can use the method `Signature::operates_on_cell_paths`

https://github.com/nushell/nushell/blob/336df6c65e36472c06381fd0e18f767f7d44ea90/crates/nu-protocol/src/signature.rs#L264:L278

**Comment by WindSoilder** [comment]
Ok, since something is unclear in https://github.com/nushell/nushell/issues/7131, I still keep help message to be displayed as text.

Here are some changes:
1. implement signature format through `impl std::fmt::Display for Signature`
2. Don't show signature for parser keyword, because it's likely to have special syntax(alias as example), the signature for `alias` is really hard to read
3. Change string representation for `Type::Record` and `Type::Table` when there is no elements, so we can output `record => table` rather than `record<> => table<>`
4. change signature representation in `help commands` and `help -f`

**Review by fdncred — APPROVED** [review]
I've tested this by looking at a few `help blah` commands and by using `help commands`. I like what you've done here @WindSoilder. 

I think it's generally more helpful when looking at the help.

Good work. I'm ready to land.

**Comment by rgwood** [comment]
Nice change, thanks @WindSoilder!

I've been trying this out and I don't fully understand the usage of `<>` for "simple types":

> /// if argument type is a simple type(like string), we'll wrapped with `<>`, the result will be `<string>`
/// if argument type is already contains `<>`, like `list<any>`, the result will be `list<any>`.

For example: 

```
// str distance has:
<string> | str distance <string> -> <int>
// str join:
list<string> | str join <string?> -> <string>
```

Do people prefer `<string> | str distance <string> -> <int>` to `string | str distance string -> int`?

**Comment by WindSoilder** [comment]
I think <string> says that we need to type a custom value which has a type string, If you type string without <>, user might thought you need to type bare word string

**Comment by rgwood** [comment]
I see how that could be confusing for command parameters. Brainstorming a few different options:

1. Always use `<>` (the current approach):

image

I don't really like this, I think it's confusing how `string` changes to `<string>` but `list<string>` does not change.

2. Only use `<>` for parameters:

image

3. Use colours to identify types:

image

**Comment by fdncred** [comment]
I'm confused, we had this conversation on Discord already. I'm pretty sure @WindSoilder coded what we decided. 

I've been kind of out of the loop for a couple days. Maybe those decisions were reversed?

**Comment by rgwood** [comment]
I don’t think I saw that conversation. Happy to go with the current approach if that’s what people agreed on.

**Comment by fdncred** [comment]
Here's the conversation id https://discord.com/channels/601130461678272522/615329862395101194/1041999531153297418 where it starts. I'm fine with waiting. I thought you were part of the conversation but I guess not.

**Comment by rgwood** [comment]
Thanks. I think the `<>` inconsistency is going to be confusing but that's fine for now, happy to land this as is and iterate.

**Comment by fdncred** [comment]
ok, let's do that then. thanks for all the input here.

**Pull request merged**
