### PR TITLE
Feature: custom commands to generate random lists

### PR DESCRIPTION
**Pull request by EmilySeville7cfg**
# Description
- Custom commands to generate random lists.
- Tests (I don't know how to fix them 🤔).

# User-Facing Changes
- Custom commands to generate random lists.

# Tests + Formatting

# After Submitting

### CODE REVIEW

**Comment by EmilySeville7cfg** [comment]
I am confused by this problem:
image

Why it happens? I've tried to do the same thing as in my previous PR with loggers.

**Comment by EmilySeville7cfg** [comment]
Tests still fail. 🤔

**Comment by EmilySeville7cfg** [comment]
> Cloning into 'virtualenv'...
remote: Internal Server Error
fatal: unable to access 'https://github.com/pypa/virtualenv.git/': The requested URL returned error: 500

Lol. 😸

**Comment by fdncred** [comment]
seen that before, i just reran failed jobs

**Comment by fdncred** [comment]
@EmilySeville7cfg I'm kind of on-the-fence about landing this in the stdlib. I see it more as a nu_scripts coolscript thing that people can choose to include if so inclined. I'm just not sure this fits with what we want the stdlib to be. I'm curious how others feel about this.

**Comment by amtoine** [comment]
i kinda agree with you @fdncred :thinking: 

this definitely is a cool module but maybe the `nu_scripts` are more appropriate :relieved:

**Comment by EmilySeville7cfg** [comment]
What we want to see in standard library then? 🌚

**Comment by fdncred** [comment]
@EmilySeville7cfg We've been discussing that. Here's one take on it. `nu-std should focus on adding foundational basic blocks and avoid adding commands that can be easily built from the basic blocks`. The reality is we're still trying to figure it out.

We think what you've written is cool and should be in nu_scripts. Sorry for our undecidedness, we're still learning what we want to do.

**Comment by fdncred** [comment]
Thanks for understanding @EmilySeville7cfg

**Pull request closed without merging**
