### PR TITLE
remove `def-env` and `export def-env`

### PR DESCRIPTION
**Pull request by amtoine**
follow-up to
- https://github.com/nushell/nushell/pull/10715

> **Important**
> wait for between 0.87 and 0.88 to land this

# Description
it's time for removal again :yum: 
this PR removes `def-env` and `export def-env` in favor of `def --env`

# User-Facing Changes
`def-env` and `export def-env` will not be found anymore.

# Tests + Formatting

# After Submitting

### CODE REVIEW

**Comment by WindSoilder** [comment]
Hi @amtoine , would you please fix the conflicts?  I believe it's conflict with `extern-wrapped` changed, because they change the same line..

**Comment by amtoine** [comment]
yup, should be better now @WindSoilder :wink:

**Comment by WindSoilder** [comment]
I'm sorry that I didn't review it yesterday, it seems that we still have comflicts...Can you please resolve it again?

**Comment by amtoine** [comment]
no worries @WindSoilder, should be good to go again :wink:

**Review by WindSoilder — APPROVED** [review]
Sure!  Let's go, thanks for your work through this

**Pull request merged**
