### PR TITLE
Add ulimit command

### LINKED ISSUE #3976: Configure maximum number of file descriptors
### Related problem

`bash` provides `ulimit` as a built-in utility to tune the limits for the currently running shell. In particular, `ulimit -n X` can be used to configure the maximum number of open file descriptors.

`nu` does not provide `ulimit` nor an alternative, at least from what I can see checking the command reference / grepping for `limit` there. 

### Describe the solution you'd like

If the feature already exists, it'd be great to add it in the migration table for bash.
If not, then an equivalent command should be provided.

### Describe alternatives you've considered

_No response_

### Additional context and details

_No response_

### LINKED ISSUE #9563: Add ulimit
### Related problem

Posix shells all have to have something like `ulimit` built in somehow in order to change their limits from the shell in a way that persists. It does me no good to use the system ulimit (typicall at /usr/bin/ulimit) from nushell as that does not change nushell's limits nor any of its child process limits.

### Describe the solution you'd like

On posix systems there should be a built in for getrlimit and setrlimit libc functions. This would allow me to at least write my own ulimit

### Describe alternatives you've considered

Ideally, nushell would maintain its own ulimit implementation that worked something like bash's ulimit rather than just providing raw primitives.

### Additional context and details

Right now if I have to change my ulimits I have to go into bash first, and then change it, and then if I still want to use nushell I have to invoke nushell form there.

### PR DESCRIPTION
**Pull request by nibon7**
# Description
Add `ulimit` command to Nushell.

Closes #9563
Closes #3976

Related pr #11246

Reference:  https://github.com/fish-shell/fish-shell/blob/master/fish-rust/src/builtins/ulimit.rs
https://github.com/mirror/busybox/blob/master/shell/shell_common.c#L529

# User-Facing Changes
```
nushell on  ulimit is 📦 v0.88.2 via 🦀 v1.72.1                                                                                                [3/246]
❯ ulimit -a
╭────┬──────────────────────────────────────────────────────────────────────────┬───────────┬───────────╮
│  # │                               description                                │   soft    │   hard    │
├────┼──────────────────────────────────────────────────────────────────────────┼───────────┼───────────┤
│  0 │ Maximum size of core files created                              (kB, -c) │ unlimited │ unlimited │
│  1 │ Maximum size of a process's data segment                        (kB, -d) │ unlimited │ unlimited │
│  2 │ Controls of maximum nice priority                                   (-e) │         0 │         0 │
│  3 │ Maximum size of files created by the shell                      (kB, -f) │ unlimited │ unlimited │
│  4 │ Maximum number of pending signals                                   (-i) │     55273 │     55273 │
│  5 │ Maximum size that may be locked into memory                     (kB, -l) │      8192 │      8192 │
│  6 │ Maximum resident set size                                       (kB, -m) │ unlimited │ unlimited │
│  7 │ Maximum number of open file descriptors                             (-n) │      1024 │    524288 │
│  8 │ Maximum bytes in POSIX message queues                           (kB, -q) │       800 │       800 │
│  9 │ Maximum realtime scheduling priority                                (-r) │         0 │         0 │
│ 10 │ Maximum stack size                                              (kB, -s) │      8192 │ unlimited │
│ 11 │ Maximum amount of CPU time in seconds                      (seconds, -t) │ unlimited │ unlimited │
│ 12 │ Maximum number of processes available to the current user           (-u) │     55273 │     55273 │
│ 13 │ Maximum amount of virtual memory available to each process      (kB, -v) │ unlimited │ unlimited │
│ 14 │ Maximum number of file locks                                        (-x) │ unlimited │ unlimited │
│ 15 │ Maximum contiguous realtime CPU time                                (-y) │ unlimited │ unlimited │
╰────┴──────────────────────────────────────────────────────────────────────────┴───────────┴───────────╯
nushell on  ulimit is 📦 v0.88.2 via 🦀 v1.72.1
❯ ulimit -s
╭───┬─────────────────────────────┬──────┬───────────╮
│ # │         description         │ soft │   hard    │
├───┼─────────────────────────────┼──────┼───────────┤
│ 0 │ Maximum stack size (kB, -s) │ 8192 │ unlimited │
╰───┴─────────────────────────────┴──────┴───────────╯
nushell on  ulimit is 📦 v0.88.2 via 🦀 v1.72.1
❯ ulimit -s 100
nushell on  ulimit is 📦 v0.88.2 via 🦀 v1.72.1
❯ ulimit -s
╭───┬─────────────────────────────┬──────┬──────╮
│ # │         description         │ soft │ hard │
├───┼─────────────────────────────┼──────┼──────┤
│ 0 │ Maximum stack size (kB, -s) │  100 │  100 │
╰───┴─────────────────────────────┴──────┴──────╯
nushell on  ulimit is 📦 v0.88.2 via 🦀 v1.72.1
```

# Tests + Formatting
- [x] add commands::ulimit::limit_set_soft1
- [x] add commands::ulimit::limit_set_soft2
- [x] add commands::ulimit::limit_set_hard1
- [x] add commands::ulimit::limit_set_hard2
- [x] add commands::ulimit::limit_set_invalid1
- [x] add commands::ulimit::limit_set_invalid2
- [x] `cargo fmt --all -- --check` to check standard code formatting (`cargo fmt --all` applies these changes)
- [x] `cargo clippy --workspace -- -D warnings -D clippy::unwrap_used` to check that you're using the standard code style
- [x] `cargo test --workspace` to check that all tests pass (on Windows make sure to [enable developer mode](https://learn.microsoft.com/en-us/windows/apps/get-started/developer-mode-features-and-debugging))
- [x] `cargo run -- -c "use std testing; testing run-tests --path crates/nu-std"` to run the tests for the standard library

### CODE REVIEW

**Comment by fdncred** [comment]
We want to do a hotfix today so let's wait until that lands to put this in. Thanks again!

**Comment by stormasm** [comment]
Thanks for getting this done so quickly, we appreciate your effort...

**Comment by stormasm** [comment]
@nibon7 After the nushell HOTFIX release happens can you update your code to the latest code...

Right now your code base is still on 87.2

Then I will go ahead and test out the *ulimit* command...

Thanks...

**Comment by fdncred** [comment]
@nibon7 still working on this, is that why you made it draft?

**Comment by nibon7** [comment]
add support to print soft and hard limits, and improve the tests

**Comment by fdncred** [comment]
Looks like some of our new parameter formatting CI checks are working, yay.

**Comment by nibon7** [comment]
I think it's ready now :smiley_cat:

**Comment by fdncred** [comment]
Thanks

**Comment by ArmoredPony** [comment]
may be you should mention in the docs or on the help page that this command is unix-only... spent a good chunk looking for this command on my windows machine before finding this [changelog entry](https://www.nushell.sh/blog/2024-01-09-nushell_0_89_0.html#ulimit-for-unix-based-systems)

**Pull request merged**
