### PR TITLE
Suggest a new motto

### PR DESCRIPTION
**Pull request by BatmanAoD**
We don't have to go with the specific motto I've suggested here (though I do personally quite like it), but this is probably a better place to discuss possible mottos than the Discord #general channel is.

### CODE REVIEW

**Comment by jonathandturner** [comment]
@BatmanAoD before changing mottos, we should agree that the current motto should be changed.

Are there a number of folks feel it needs to be changed?

**Comment by wycats** [comment]
@jonathandturner personally, I'm comfortable with the current motto. Honestly, I'd rather spend my time on improving nushell at the moment.

**Comment by BatmanAoD** [comment]
It's kind of impossible to know who thinks the motto "needs" to change, since presumably they'd be turned off by the current motto and wouldn't have bothered to investigate the shell in the first place! I just think a different motto could better indicate what's interesting about nushell.

**Comment by sharksforarms** [comment]
As someone who just found out about nushell, I'm not sure I understand what is meant by "GitHub era"... How does this relate to a shell?

**Comment by AndresMPR** [comment]
Okay, so I’m old enough and got into PC early enough that I remember my first computer was a PCjr. I loved that little machine, but spent more time with my little basic cartridge than any game. 

Fast forward to today, I got comfortable with bash in university since that was what came pre installed on our shiny new Redhat PC machines that everyone used in the lab. Verisioning we talked about CVS and SVN and there was no Git even on the horizon when I graduated.

So I come from the pre-Git generation and I dove right into Git from day one, and I love it!

I have Git GUI installed on my main systems, but I still like to do most of my own Git dev workflows from the command line.

I think that’s where the motto is coming from, and for me, it made me want to get involved.

So Git == Newer stuff (15 years so it’s a more mature package, but still a teenager, not like bash OR vi) Nushell == fresh as daisies, but inspired by Git, and taking Git workflow into a shell. Can’t wait for version control on my scripts as a default option in my shell.

Also feature suggestion: version control (using Git) on any “script” folders. (Command mechanic for marking such folders?)

Hope that helps with the reasons, and a feature suggest presented itself while writing this story. So you can put inspired open source development with my post on your resume.

Nice! I’m calling this a win win and logging off and hitting send!

**Comment by twe4ked** [comment]
Including GitHub in the name is definitely going to turn some people off, but you can't please everyone. Nothing about it is GitHub specific though, so I'd lean towards making it a more generic motto.

**Comment by wycats** [comment]
I don't object to considering a new motto at some point, but right now I'm going to close this because I don't intend to spend time thinking about it right now, and I don't think the current motto is a major problem.

I don't have any problem with people continuing to discuss in the thread.

**Comment by jonathandturner** [comment]
To circle back to this: we did get a lot more feedback since this PR that the motto is confusing. We're currently working on improving it, just starting to gather ideas here: https://twitter.com/jntrnr/status/1207900915979583488?s=20

**Pull request closed without merging**
