### PR TITLE
nu-table: Fix expand table unnessary color in trail head config when wrap is used

### PR DESCRIPTION
**Pull request by zhiburt**
So it must address it,
But please check.

PS: I don't like the patch... but it is what it is

fix: #10359
cc: @amtoine

### CODE REVIEW

**Comment by zhiburt** [comment]
> 🟠 

It's actually supposed to be so.

The string contains white spaces, so they just there.
Or your point is to remove them?

**Comment by fdncred** [comment]
ya, this looks right to me. we decided not to color the header when there's white space with this type of header. It's fine for now I think. We can address that later if it's critical.

**Comment by amtoine** [comment]
ooh wow, my bad :pray: 

i did not notice there was whitespaces in the header name too :scream: 
then it's all green for me, thanks again for the quick fix :relieved:

**Comment by fdncred** [comment]
Thanks again @zhiburt!

**Pull request merged**
