### PR TITLE
:bug: Fixes markdown formatting on LSP hover

### PR DESCRIPTION
**Pull request by AucaCoyan**
# Description
Hi! I was playing around and I fixed the formatting in the LSP hover. 
I _only tested in VS Code using Windows_, if anyone is capable, can you test it on nvim or linux if it works properly? I think markdown shouldn't have any problem

The link of the LSP meta issue just for reference #10941 

# User-Facing Changes
Now the LSP hovers markdown properly
image

# Tests + Formatting

# After Submitting

### CODE REVIEW

**Comment by fdncred** [comment]
Love it!

**Comment by p00f** [comment]
the signature doesn't seem to have the backslash https://github.com/AucaCoyan/nushell/blob/9ba178a7794d9e6a1b380c1303460d881e6968ba/crates/nu-cmd-lang/src/core_commands/let_.rs#L18-L29

**Comment by AucaCoyan** [comment]
Thanks! I will pay extra attention to those details 👍🏼

**Comment by AucaCoyan** [comment]
`let` Fixed! It was again some treacherous `/` miss-escaped char
I also fix the tests I didn't ran before 😋

**Comment by AucaCoyan** [comment]
> thanks, there are three more instances of `\\\n` in crates/nu-lsp/src/lib.rs, I think they are unneeded too - can you take a look to make sure?

Will do!
I was just testing the LSP on my machine and it crashes on VS Code. The test go right, but I believe I have broke it.
I'm still brand new to LSPs. Please don't merge yet!

**Comment by p00f** [comment]
seems unlikely, you only changed strings

**Comment by AucaCoyan** [comment]
> I was just testing the LSP on my machine and it crashes on VS Code. The test go right, but I believe I have broke it.

I realized that checking out a previous version that works still have issues, so probably is my VS Code misbehaving than the code going wrong

**Comment by AucaCoyan** [comment]
Yeee! Ship it 🛥️

**Comment by fdncred** [comment]
Thanks!

**Pull request merged**
