### PR TITLE
enable the ability to use fancy-regex with -f instead of regex

### PR DESCRIPTION
**Pull request by fdncred**
# Description

This PR is kind of a prototype to allow `str replace` to use the generally accepted `regex` crate for regular expressions *OR* now to be able to use the `fancy-regex` crate for regular expressions. You can read more about the `fancy-regex` crate [here](https://docs.rs/fancy-regex/0.10.0/fancy_regex/). There are some things that the regex crate just cannot do such as backreferences and lookaround. One of the interesting things about `fancy-regex` is that if you don't use the "advanced" features, it falls back itself to using the `regex` crate, according to the documentation. So, perhaps, we can just remove `regex` altogether? The two examples I added were straight from their documentation website and aren't really very good. We should augment those in the future.

# Tests

Make sure you've done the following:

- [x] Add tests that cover your changes, either in the command examples, the crate/tests folder, or in the /tests folder.
- [ ] Try to think about corner cases and various ways how your changes could break. Cover them with tests.
- [ ] If adding tests is not possible, please document in the PR body a minimal example with steps on how to reproduce so one can verify your change works.

Make sure you've run and fixed any issues with these commands:

- [x] `cargo fmt --all -- --check` to check standard code formatting (`cargo fmt --all` applies these changes)
- [x] `cargo clippy --workspace --features=extra -- -D warnings -D clippy::unwrap_used -A clippy::needless_collect` to check that you're using the standard code style
- [x] `cargo test --workspace --features=extra` to check that all the tests pass

### CODE REVIEW

**Comment by WindSoilder** [comment]
Maybe we can use fancy-regex directly?  I think user doesn't care about the difference between `fancy-regex` and `regex`.

**Comment by fdncred** [comment]
I think it's probably best to remove regex altogether. I didn't realize fancy-regex fell back to regex until reading comments in fancy-regex and then seeing the documentation, ugh. My main goal of adding both was not to surprise the user with a different regex syntax. I should've read through the docs first, LOL.

**Comment by fdncred** [comment]
I converted this to draft to prevent accidental merging. I may just close this one eventually because it's probably easier to just make a new PR.

**Comment by fdncred** [comment]
closing in favor of #6227

**Pull request closed without merging**
