### PR TITLE
add `start_time` to `ps -l` on macos

### PR DESCRIPTION
**Pull request by fdncred**
# Description

This PR adds `start_time` to the MacOS `ps -l` command. Was requested in discord. `start_time` is displayed in `Local` time.

image

# User-Facing Changes

# Tests + Formatting

# After Submitting

/cc @cablehead

### CODE REVIEW

**Comment by cablehead** [comment]
Context from discord:

image

and then thread: https://discord.com/channels/601130461678272522/615253963645911060/1297203869717237844

**Comment by cablehead** [comment]
Just checking, will this only add the column on macOS? One consideration: do we want to ensure the columns are consistent between platforms, for cross scripting reliability?

**Comment by fdncred** [comment]
> Just checking, will this only add the column on macOS? One consideration: do we want to ensure the columns are consistent between platforms, for cross scripting reliability?

yes, it's only for macos on. there are already differences between operating system. It would be nice to make it consistent, but not at the expense of removing columns from certain operating systems.

**Comment by sholderbach** [comment]
A brief google search showed that the info should internally be provided by all the major platforms. So someone has their work cut out for replicating this on the other platforms.

**Comment by fdncred** [comment]
I can look into adding start_time on all platforms where it's missing. It's just very difficult to do it in 1 PR because you typically write a PR on one operating system, not 3 or more. 😄 I don't even have a BSD system or vm to check.

**Comment by sholderbach** [comment]
We can land this with a tracking issue so we get the rest of the platforms complete till the release :D

**Comment by fdncred** [comment]
macos, linux, windows all have start_time now.

**Pull request merged**
