### PR TITLE
Lazy dataframes

### PR DESCRIPTION
**Pull request by elferherrera**
# Description

Adds new lazy frames commands to work with dataframes

# Tests

Make sure you've run and fixed any issues with these commands:

- [ ] `cargo fmt --all -- --check` to check standard code formatting (`cargo fmt --all` applies these changes)
- [ ] `cargo clippy --all --all-features -- -D warnings -D clippy::unwrap_used -A clippy::needless_collect` to check that you're using the standard code style
- [ ] `cargo build; cargo test --all --all-features` to check that all the tests pass

### CODE REVIEW

**Comment by stormasm** [comment]
@elferherrera great job on this PR, we are making very nice progress on moving along dataframes...  I have been spendning a lot more time getting to know your code better along with the underlying arrow and polars code base...
Hopefully we can land ASAP...  Also glad to see the upgrade to polars 0.21.1 which will fix the current parquet bug in version 0.20.0 of polars...

**Comment by stormasm** [comment]
https://github.com/jorgecarleitao/parquet2/tree/main/parquet-tools
@elferherrera I have been trying to run this code which you wrote (looks like about a year ago). it does not seem to be working now --- just curious does this code need to be updated ?

**Comment by fdncred** [comment]
@elferherrera my vote is to just land this if we're sure it's the rust-cache running out of space issue.

**Comment by elferherrera** [comment]
@stormasm what error do you get?

**Comment by stormasm** [comment]
@elferherrera 

I am able to
cargo build
https://github.com/jorgecarleitao/parquet2

but when I
cd to 
https://github.com/jorgecarleitao/parquet2/tree/main/parquet-tools

and 
cargo build

I get this error
```
parquet-tools$ cb
    Updating crates.io index
error: failed to select a version for the requirement `parquet2 = "^0.1"`
candidate versions found which didn't match: 0.12.0
location searched: /Users/ma/j/tmp06/parquet2
required by package `parquet-tools v0.1.0 (/Users/ma/j/tmp06/parquet2/parquet-tools)`
```

**Comment by elferherrera** [comment]
@stormasm Jorge hasn't updated those tools. That means that they need to use whatever version of the parquet crate they have. He told me they are going to be removed because nobody is maintain them

**Pull request merged**
