### PR TITLE
Add interleave command for reading multiple streams in parallel

### PR DESCRIPTION
**Pull request by devyn**
# Description

This command mixes input from multiple sources and sends items to the final stream as soon as they're available. It can be called as part of a pipeline with input, or it can take multiple closures and mix them that way.

See `crates/nu-command/tests/commands/interleave.rs` for a practical example. I imagine this will be most often used to run multiple commands in parallel and print their outputs line-by-line. A stdlib command could potentially use `interleave` to make this particular use case easier.

It's quite common to wish that nushell had a command for running things in the background, and instead of providing job control, this provides an alternative to some use cases for that by just allowing multiple commands to run simultaneously and direct their output to the same place.

This enables certain things that are not possible with `par-each` - for example, you may wish to run `make` across several projects in parallel:

```nushell
(ls projects).name | par-each { |project| cd $project; make }
```

This works well enough, but the output will only be available after each `make` command finishes. `interleave` allows you to get each line:

```nushell
interleave ...(
  (ls projects).name | each { |project|
    {
      cd $project
      make | lines | each { |line| {project: $project, out: $line} }
    }
  }
)
```

The result of this is a stream that you could process further - for example, by saving to a text file.

Note that the closures themselves are not run in parallel. The initial execution happens serially, and then the streams are consumed in parallel.

# User-Facing Changes

Adds a new command.

# Tests + Formatting

- :green_circle: `toolkit fmt`
- :green_circle: `toolkit clippy`
- :green_circle: `toolkit test`
- :green_circle: `toolkit test stdlib`

# After Submitting

### CODE REVIEW

**Comment by fdncred** [comment]
@devyn is on 🔥

**Comment by fdncred** [comment]
@devyn if you can get the ci green again, we can try and land this before our release.

**Review by IanManske — APPROVED** [review]
Thanks for this PR and for the demo in the meeting @devyn ! I've looked it over, and I don't see anything that needs changing.

**Comment by kubouch** [comment]
One thing is the `.expect()` on failed thread creation (same for the tee command). We try to avoid panics, if possible, although now it has become less of an issue due to the new panic catching we just landed. Could the thread failure be handled with ShellError instead?

Another thing is that, as we go towards 1.0, we try to compact our set of commands/flags/features to only those that we really need, ideally offloading the rest to the stdlib or plugins. I think both `tee` and `interleave` are good additions, I won't block landing them, but just to keep in mind that apart from adding commands, we also need to look where we can cut and make things more consistent.

**Comment by IanManske** [comment]
I forgot that `spawn` returns an `io::Errror`, yeah this should be handled if possible (`From<io::Error> for ShellError` exists). Later, I will probably go around and fix the other areas where we spawn threads.

**Comment by kubouch** [comment]
The `From<io::Error> for ShellError` should be probably removed because it produces errors without spans, which are extremely unhelpful when they happen. Nushell errors should always have some span (`call.head` is fine), unless it's some testing code where you don't have spans.

**Comment by devyn** [comment]
I should be able to change the thread spawn `expect` to an error, yeah.

I kind of just looked at what other thread spawning code in the codebase does, and at this point it seems like almost all of them just `expect`. I think I'll submit a PR at some point trying to clean all of those up as much as possible, especially since I think it is an error that could actually reasonably happen

**Comment by fdncred** [comment]
We try our best not to have a ton of expects and use ShellError everywhere we can, although sometimes we miss some.

**Comment by devyn** [comment]
Looks like it all works, the `expect` is now an `IOErrorSpanned` as advised

**Comment by fdncred** [comment]
thanks

**Pull request merged**
