### PR TITLE
Use async-stream crate to replace most async_stream_block invocations

### PR DESCRIPTION
**Pull request by est31**
Targets some lower hanging fruit. cc #362

### CODE REVIEW

**Comment by jonathandturner** [comment]
Looks good to me. Tagging @wycats to also take a look.

So, if we do this, does that mean we can move off of using generators, or is there still more work for that?

**Comment by est31** [comment]
`async_stream_block` is still being used in some places in the code base, in fact in very similar ones to the ones this PR is touching. E.g. see the second commit which touches some of those files (but there are more). However, simply replacing them in the style of this PR led to weird errors and I'm not familiar enough with async to be able to come up with a solution.

**Comment by est31** [comment]
Maybe with more time I'll be able to, idk.

**Comment by jonathandturner** [comment]
Got it, sounds good.

**Pull request merged**
