### PR TITLE
use constant instead of <0 for ls fix

### PR DESCRIPTION
**Pull request by davehorner**
https://github.com/nushell/nushell/pull/10558#issuecomment-1911076784

more correct than <0.  safer check.

### CODE REVIEW

**Comment by kubouch** [comment]
Thanks!

1. It's better to define the number as a constant with a comment on what the value means and why it is this exact number. Now it's not understandable for someone reading the code later.
2. Can you remove the commented out lines introduced in the previous PR? https://github.com/nushell/nushell/pull/10558/files#diff-52d84ef0558fd4948723cbae739ecea22351dba0965d24ab3d6862181f309f44R684

**Comment by davehorner** [comment]
```
    const NEG_UNIX_EPOCH: u64 = -11644473600i64;
    if sec == NEG_UNIX_EPOCH { // {
        return None;
    }
```
the i64 suffix is unneeded; as is the const.  I agree about constants though, loose numbers are magic numbers.  I don't know the value of pulling out the const for 
```
        /// January 1, 1970 as Windows file time
        const EPOCH_AS_FILETIME: u64 = 116444736000000000;
        const HUNDREDS_OF_NANOSECONDS: u64 = 10000000;
```
the epoch number is there above but in nanoseconds I guess.  to each their own.

**Comment by davehorner** [comment]
keep it open and I'll toy with it.  lmk if you'd like a change.

**Comment by davehorner** [comment]
if anyone knows of a better way to test SystemTime for 0 above the match we could not define another const.
`t.duration_since(0)==0` might work

**Comment by kubouch** [comment]
So should this be merged, or do you intend to still do something with it? If so, please convert to draft.

The comments now are good.

One last thing would be having a test for this. It could be a unit-test for `try_convert_to_local_date_time()` and `unix_time_from_filetime()` to not cause a panic if given some weird time stamp. Just to make sure we won't regress in the future.

**Comment by davehorner** [comment]
I converted to draft.  Maybe I should not have done that...
This is ready, no intention for additional change.

I didn't plan to add tests but will integrate a test if given one.  If you provide details on where its possible I could do it.  this should not hinder this PR.  the code committed is incorrect.

**Comment by kubouch** [comment]
The tests could test that
* `unix_time_from_filetime(ft: &FILETIME)` doesn't produce a negative timestamps
* `try_convert_to_local_date_time(t: SystemTime)` doesn't panic anymore

using input values those that caused panic before.

The tests could be directly in the ls.rs file, or in `nu-command/tests/commands/ls.rs` but then you'd need to make those functions public. You might need to experiment a bit to see where the tests could fit.

**Comment by davehorner** [comment]
Please accept this PR in its current state.  I do not intend to spend more time on this.

**Comment by davehorner** [comment]
@fdncred first it's a panic, now its a logical error I'm chasing.  please merge to fix the bug.

**Comment by fdncred** [comment]
Landing since this is an improvement over what we had but can you please spend a little more time and add the tests Kubouch suggests?

**Pull request merged**
