### PR TITLE
Aliases

### PR DESCRIPTION
**Pull request by jonathandturner**
With this PR, we'll have aliases (yay!)

Aliases have the form:

```
> alias alias_name [arg1 arg2] {block | of | commands}
```

Example:

```
> alias double_echo [a b] { echo $a $b }
```

Aliases are currently added to the command list, making them work similarly to internal commands. This means they'll also show up in the list when you do `help commands`. We may want to change that behavior in the future.

Aliases, being internal commands, also read in and output structure values, so -- at least in theory -- you should be able to use them anywhere you would use an internal command today.

This PR also adds a new `config` setting called "startup".  The "startup" setting now holds a table of strings. Each string is run, similar to a script, as Nu starts up.  This is a good place to put aliases you want to keep around.

_Note: The arguments are required, so if you have zero arguments we still currently require `[]` in that position._

### CODE REVIEW

**Comment by casidiablo** [comment]
Is there a way to define an alias that can receive any number of parameters?

e.g. let's say I want to alias `ll` to '^ls -lah'.

```
alias ll [] { ^ls -lha }
```

But what if I also want to call this like this: `ll ~/.some/path`?

**Comment by casidiablo** [comment]
This is definitely a very good feature. I was hoping to port all of my aliases from fish and bash, and doing so automatically (by transforming all my `alias foo="bar baz"` into the appropriate nu shell alias syntax).

It worked for some of my aliases, but it breaks for aliases that use other aliases.

e.g.:

```
alias arb [] { something_here } # this works fine, but then:

alias arbc [] { arb && arc diff } # this produces:

- shell:1:33
1 | alias arbc [] { arb && arc diff }
  |                     ^^ unexpected argument (try arb -h)
```

**Comment by casidiablo** [comment]
Also, can't get this to work:

```
❯ alias ga [a] { git add $a }
❯ ga fii
Nothing specified, nothing added.
Maybe you wanted to say 'git add .'?
```

**Comment by jonathandturner** [comment]
@casidiablo - we're currently fixing this issue. The problem is that external commands like ^ls and git need a little more support to handle the new variables we're sending. Once that's done, you should be able to call them in aliases like you're doing.

**Comment by casidiablo** [comment]
I'm sorry I commented three times instead of bundling all my questions in a single block. Did you see my first question?

**Comment by jonathandturner** [comment]
@casidiablo - I missed it. A few things we still need to add:

* Optional and rest style arguments
* We don't support `&&` between pipelines but hope to support something like it soon

**Pull request merged**
