### PR TITLE
Revert "Only run $env.PROMPT_COMMAND once per prompt"

### PR DESCRIPTION
**Pull request by fdncred**
Reverts nushell/nushell#10986

@CAD97 This isn't working right. I have a 2 line prompt with a transient prompt. on enter, you see the transient prompt drawn and then the normal prompt overwrites it.

### CODE REVIEW

**Comment by ysthakur** [comment]
I just checked out CAD97's fork's main branch and it seems to be working fine for me:
image

**Comment by fdncred** [comment]
The problem was that with my prompt, which happens to be a 2 line prompt,
image
you could have the prompt on the bottom of the terminal, hit enter, then the transient prompt would appear, and the normal prompt would overwrite it and nothing would advance upward. So, it was like you were hitting enter, screen flashes, nothing happens.

**Comment by ysthakur** [comment]
@fdncred Odd, it's working for me (`edit_mode = emacs`, but I assume you're using emacs mode too):

image

Those two empty lines are just because I hit enter too fast for the prompt to render before then.

Could you try out the changes on [this branch](https://github.com/ysthakur/nushell/tree/cad-transient-prompt-fix) on my fork and see if that works for you? The changes there are essentially the same as CAD97's but more conservative (`prompt.rs` has been left untouched)

**Comment by fdncred** [comment]
That branch works well. I think better than your PR that I landed. I recently discovered problems with yours as well.

**Comment by fdncred** [comment]
@ysthakur Just to be clear, this is the problem I just discovered in the latest main. This is how CAD's PR was working for me too. Your new branch DOES NOT do this.
prompt-issues

**Comment by ysthakur** [comment]
@fdncred That's wacky, any idea why it's happening? I made a [PR](https://github.com/nushell/nushell/pull/11366) with that new branch

**Comment by fdncred** [comment]
> That's wacky, any idea why it's happening?

It looks like it has something to do with the transient prompt because it's being drawn and then overwritten with the regular prompt. So, I'm not really sure but it's wacky indeed. I'll take a look at your PR.

**Pull request merged**
