### PR TITLE
Adapt for improved history isolation in reedline

### PR DESCRIPTION
**Pull request by Hofer-Julian**
Depends on https://github.com/nushell/reedline/pull/634

### CODE REVIEW

**Comment by Hofer-Julian** [comment]
Thanks @WindSoilder for updating the PR. It is ready to be reviewed now.

**Review by WindSoilder — APPROVED** [review]
Thanks!  It looks good to me!

**Comment by maxim-uvarov** [comment]
@Hofer-Julian such a huge usability improvement for me! Thank you so much!

**Comment by fdncred** [comment]
I hope we don't regret this. Landing PRs 1 day from release doesn't give much time for testing.

**Comment by WindSoilder** [comment]
Sorry it's my fault, I'll follow up and keep our release schedule in mind

**Comment by fdncred** [comment]
I'm not super worried about it @WindSoilder. No hard feelings. We just need to keep an eye out for odd behaviors related to this and hope it doesn't cause us to have to make a point release. I wasn't planning on landing this until after the release but, I guess maybe we had to land it since the `SqliteBackedHistory::with_file` API changed in reedline, unless we were going to stay on an older version of reedline, which I doubt we would.

I'm trying to figure out how to get rid of these warnings now. I think this is related to the change but vscode/rust-analyzer aren't picking it up right. The good news is that it's not preventing me from compiling.
image

**Comment by ofek** [comment]
Do this require a new option or is it now the default behavior?

**Comment by Hofer-Julian** [comment]
> Do this require a new option or is it now the default behavior?

You have to set the backend to sqlite and enable history isolation.
I hope that it can become the default in one of the future releases.

**Pull request merged**
