### PR TITLE
nu-explore/ Fix configuration issues

### LINKED ISSUE #7518: `explore` config deserialization may not be working
### Describe the bug

@zhiburt something is broken somewhere maybe not even with this PR, but I don't see any highlights anymore when in cursor mode, nor do I see the config.cursor_color being respected. I'm using the default config and I'm not sure it's being processed.

If i do `:config-show` I can see that things don't look right and don't match my config.nu explore section. Some of the color records are being treated as strings. This is with the default config in my config.nu.
Screenshot 2022-12-18 at 7 23 47 AM
This is with no config at all for explore in my config.nu
Screenshot 2022-12-18 at 7 31 37 AM

I'm convinced the config either isn't being read correctly or it is being overwritten somewhere. I put this as my config for explore and it's being ignored. The colors don't show up when using explore and when i do config-show, there are no colors that show up for these two settings.
```
  explore: {
    config: {
        cursor_color: 'red'
    }
    table: {
        selected_cell: { bg: 'blue' }
    }
  }
```

Another thing I noticed while looking at the code is we need to change all `Rgb` colors to named colors. There are a bunch of named colors now as I added another 256 yesterday. Rgb assumes that you have a terminal that supports 24-bit color and we cannot assume that.

`:tweak config.cursor_color red` definitely works.

I'm guessing that this function isn't working right but I could be wrong.
```rust
fn insert_style(map: &mut HashMap<String, Value>, key: &str, value: Style) {
```

### How to reproduce

see above

### Expected behavior

deserialize into nushell colors/styles properly

### Screenshots

_No response_

### Configuration

|key|value|
|-|-|
|version|0.72.2|
|branch|get_ignore_error|
|commit_hash|864e42e290ae4b97c49ea3d35b3388d40b2da275|
|build_os|macos-aarch64|
|build_target|aarch64-apple-darwin|
|rust_version|rustc 1.65.0 (897e37553 2022-11-02)|
|rust_channel|1.65.0-aarch64-apple-darwin|
|cargo_version|cargo 1.65.0 (4bc8f24d3 2022-10-20)|
|pkg_version|0.72.2|
|build_time|2022-12-10 07:07:39 -06:00|
|build_rust_channel|debug|
|features|database, default, trash, which, zip|
|installed_plugins|custom-value generate, custom-value generate2, custom-value update, from parquet, gstat, inc, nu-example-1, nu-example-2, nu-example-3, pnet, query, query json, query web, query xml, regex|

### Additional context

/cc @zhiburt

### PR DESCRIPTION
**Pull request by zhiburt**
close #7518

### CODE REVIEW

**Comment by fdncred** [comment]
It seems like this is parsing the config much better, however I'm not sure it's using the values. I have this in my config.nu.
```
  explore: {
    config: {
        cursor_color: 'red'
    }
    table: {
        selected_cell: { bg: 'blue'}
    }
  }
```
and `:config-show` shows that values. However, when in tables the background is not blue.
Screenshot 2022-12-18 at 2 01 55 PM

Also, the settings we had from the previous PR, as it relates to border/line colors is now gone. The ls_colors part is there as well as filesize color and datetime color but the lines are not right any longer.
Screenshot 2022-12-18 at 2 02 34 PM
I was expecting something closer to regular `ls` with my purple lines. The previous PR had the purple lines.
Screenshot 2022-12-18 at 2 03 28 PM

The `cursor_color: red` looks good. I believe that's only used in the config menus. At least that's the only place i see it like this.
Screenshot 2022-12-18 at 2 05 36 PM
Note that surprisingly these lines are purple here but not in the other screens.

**Comment by zhiburt** [comment]
> It seems like this is parsing the config much better, however I'm not sure it's using the values. I have this in my config.nu.

It was actually related to this. I was wrong.

> > As far as I understand nushell doesn't support records nested more then 2 levels and treats it as strings.
(I might be wrong here).

> The menus in the config file serialize pretty deeply. I've never really counted how many levels but here's an example of one that works just fine that's pretty deep.

Good catch.
Must be adrressed.

**Comment by fdncred** [comment]
This most recent changes are looking better but still the initial `ls | explore` is not keeping the line colors configured.
Screenshot 2022-12-18 at 10 45 07 PM
I think all the other config settings for values are working though.

**Comment by zhiburt** [comment]
Must be fixed.

PS: and sorry for this ping pong comment/fix cycle...

**Comment by fdncred** [comment]
much better, thanks!

**Pull request merged**
