### PR TITLE
Fetch content from S3

### PR DESCRIPTION
**Pull request by yanganto**
- fetch content of s3 object and try convert into table

### CODE REVIEW

**Comment by jonathandturner** [comment]
@yanganto we just published a release, and looks like it caused some conflicts.

The code looks good. Once the conflicts are fixed, we should be able to land.

Thanks for putting it together!

**Comment by yanganto** [comment]
@jonathandturner conflicts are fixed. :smile:

**Comment by jonathandturner** [comment]
Looks good!

**Comment by fdncred** [comment]
Hey @yanganto, are you interested in helping us fix the nu_s3_plugin? It's currently breaking the build process and our only resort is to disable it. I think you wrote the s3handler it's using? There looks to be an outdated dependency.

**Pull request merged**
