### PR TITLE
Add `tee` command for operating on copies of streams

### PR DESCRIPTION
**Pull request by devyn**
[Related conversation on Discord](https://discord.com/channels/601130461678272522/615329862395101194/1209951539901366292)

# Description

This is inspired by the Unix tee command, but significantly more powerful. Rather than just writing to a file, you can do any kind of stream operation that Nushell supports within the closure.

The equivalent of Unix `tee -a file.txt` would be, for example, `command | tee { save -a file.txt }` - but of course this is Nushell, and you can do the same with structured data to JSON objects, or even just run any other command on the system with it.

A `--stderr` flag is provided for operating on the stderr stream from external programs. This may produce unexpected results if the stderr stream is not then also printed by something else - nushell currently doesn't. See #11929 for the fix for that.

# User-Facing Changes

If someone was using the system `tee` command, they might be surprised to find that it's different.

# Tests + Formatting

- :green_circle: `toolkit fmt`
- :green_circle: `toolkit clippy`
- :green_circle: `toolkit test`
- :green_circle: `toolkit test stdlib`

# After Submitting

### CODE REVIEW

**Comment by fdncred** [comment]
I haven't looked at the code too closely but what is `tee` doing in a pipeline like this? I see the names printed, but are they nushell values or dumb strings? They look like just strings. 
```nushell
ls | tee { each { echo $in.name }}
```

I noticed that I can't do either of these pipelines.

This each block would typically return nushell values.
```nushell
ls | tee { each { $in.name }}
```
This each block would typically show me the type
```nushell
ls | tee { each { $in.name | describe }}
```

**Comment by IanManske** [comment]
It looks output from the closure is not printed (not sure if it should or not). This will work @fdncred:
```nushell
ls | tee { get name | print }  
```

**Comment by devyn** [comment]
@fdncred @IanManske 

Exactly, it doesn't print the output of the closure, it just drains it. That's a good question whether or not it should print it... I'm not sure. I guess a user might expect it to be printed. Easy enough to just call `print()` instead.

It sets both `redirect_stdout` and `redirect_stderr` to false, so `echo` does work.

**Comment by fdncred** [comment]
let's move forward with this and adjust if we need to.

**Pull request merged**
