### PR TITLE
Add `ListItem` type for `Expr::List`

### PR DESCRIPTION
**Pull request by IanManske**
# Description
This PR adds a `ListItem` enum to our set of AST types. It encodes the two possible expressions inside of list expression: a singular item or a spread. This is similar to the existing `RecordItem` enum. Adding `ListItem` allows us to remove the existing `Expr::Spread` case which was previously used for list spreads. As a consequence, this guarantees (via the type system) that spreads can only ever occur inside lists, records, or as command args.

This PR also does a little bit of cleanup in relevant parser code.

### CODE REVIEW

**Review by sholderbach — COMMENTED** [review]
How does that play with the spread operator in command calls? cc @ysthakur 

I am on board with trying to make things more explicit if it allows us to diagnose problems better. The code for nuon seems to grow a bit Is there a change to the behavior in a table literal/expression?

**Comment by IanManske** [comment]
> How does that play with the spread operator in command calls?

It looks like that's handled by `Argument::Spread` and `Call::add_spread`.

> The code for nuon seems to grow a bit Is there a change to the behavior in a table literal/expression?

There might be a few extra lines because of the match statement, but the total change isn't that big since there's a section of code (re)moved below.

**Comment by ysthakur** [comment]
Making spreading inside lists type safe is a great idea, I'm not sure why I didn't do it this way originally. I think I mistakenly assumed the refactor was bigger than it's actually turned out to be here.

> How does that play with the spread operator in command calls?

As Ian said, `Expr::Spread` isn't used to represent spread arguments, there's `Argument::Spread` and `ExternalArgument::Spread` for that.

I haven't tested this out on my computer or looked too closely at the changes to the parser yet, but the rest looks good to me.

**Comment by sholderbach** [comment]
Let's go with this

**Pull request merged**
