### PR TITLE
Fix external command name parsing with backslashes, and add tests

### LINKED ISSUE #13016: nushell 0.94.1 breaks Windows path handling
### Describe the bug

```
Error:   × Invalid literal
     ╭─[C:\Users\zhang\AppData\Roaming\nushell\config.nu:792:17]
 791 │ #use ~/.starship.nu
 792 │ alias curl = c:\msys64\clangarm64\bin\curl.exe
     ·                 ───────────────┬──────────────
     ·                                ╰── unrecognized escape after '\' in string
 793 │ alias vim = nvim
     ╰────
```

### How to reproduce

Windows style paths in config file result in error `unrecognized escape after '\' in string`

### Expected behavior

Don't error

### Screenshots

N/A

### Configuration

N/A

### Additional context

Regression in 0.94.1. It worked in 0.94.0

### PR DESCRIPTION
**Pull request by devyn**
# Description

Fixes #13016 and adds tests for many variations of external call parsing.

I just realized @kubouch took a crack at this too (#13022) so really whichever is better, but I think the
tests are a good addition.

### CODE REVIEW

**Comment by kubouch** [comment]
That's fine, I just quickly tested one thing, let's go with your version.

**Comment by fdncred** [comment]
@devyn @kubouch This just hangs now. I'm not convinced #13016 is fixed yet.
```nushell
❯ let b = c:\Users\username\.cargo\bin\bat.exe
```

**Comment by kubouch** [comment]
@fdncred 
```nushell
let b = c:\Users\username\.cargo\bin\bat.exe
```
tries to run `c:\Users\username\.cargo\bin\bat.exe` and store the result to `b`. So, I think it makes sense that it hangs. `alias b = c:\Users\username\.cargo\bin\bat.exe` should be working, though.

The caret is required for running an external from a string, that seems to work as intended.

**Comment by fdncred** [comment]
I don't understand what you're saying because you used 2 identical examples and said one should work and the other shouldn't. LOL.

I'm not sure #13016 is fixed unless we say it has to be in quotes.

**Comment by kubouch** [comment]
Look at the first word: `let` vs. `alias`.

**Comment by fdncred** [comment]
ROTFL! I'm so stupid. You're right. In this situation let = bad, alias = good. I feel better now.

**Pull request merged**
