### PR TITLE
Add utouch command from uutils/coreutils

### PR DESCRIPTION
**Pull request by ysthakur**
Part of https://github.com/nushell/nushell/issues/11549

# Description

This PR adds a `utouch` command that uses the `touch` command from https://github.com/uutils/coreutils. Eventually, `utouch` may be able to replace `touch`.

The conflicts in Cargo.lock and Cargo.toml are because I'm using the uutils/coreutils main rather than the latest release, since the changes that expose `uu_touch`'s internal functionality aren't available in the latest release.

# User-Facing Changes

Users will have access to a new `utouch` command with the following flags:
todo

# Tests + Formatting

# After Submitting

### CODE REVIEW

**Comment by ysthakur** [comment]
@fdncred Sorry, I've been really busy and haven't touched this for a week. The uutils side is currently not ready but I think I know what to do, and I'll be updating that today or tomorrow. Hopefully we can get that one merged by the end of the week

**Comment by fdncred** [comment]
Thanks for the heads-up @ysthakur. I appreciate your efforts here.

**Comment by fdncred** [comment]
How's this going? Are we waiting for changes to land at coreutils?

**Comment by fdncred** [comment]
@ysthakur Is there any hope to getting the coreutils PR landed?

**Comment by ysthakur** [comment]
@fdncred Yes, sorry I've left it alone for a while. I wasn't quite sure how to interpret Terts's suggestions, but I just pushed a commit and will be bothering him about it :)

**Comment by fdncred** [comment]
ok, thanks for the update. appreciate your help.

**Comment by ysthakur** [comment]
@fdncred Currently waiting on a review for the PR I made in uutils/coreutils.

**Comment by fdncred** [comment]
@ysthakur wow! the uutils pr landed. we can finally progress on this one. yipee!

**Comment by ysthakur** [comment]
I think `touch` is accidentally added to the default shell context twice, once with the filesystem commands and once with the [format commands](https://github.com/nushell/nushell/blob/main/crates/nu-command/src/default_context.rs#L293). I only added UTouch once there, with the filesystem commands.

**Comment by fdncred** [comment]
good catch. I don't think it should be the formats section.

**Comment by ysthakur** [comment]
By the way, this PR isn't dead, it's just that there's a bug in the way uutils parses dates (https://github.com/uutils/coreutils/issues/6629). I think I've found the cause, more or less, and am working on a fix there.

**Comment by fdncred** [comment]
Thanks for the update yash. Sorry this is such a hassle.

**Comment by fdncred** [comment]
just noticed there's a new release of coreutils. maybe your changes are in there?

**Comment by ysthakur** [comment]
@fdncred Thanks for letting me know, yes, my changes were in there! Should be ready to go now.

**Comment by fdncred** [comment]
ok, let's land this then. especially since it's named `utouch`. we can test for a while and deprecate `touch` in another pr as is the process. Thanks for pushing on this steadily.

**Pull request merged**
