### PR TITLE
add a multi-set cartesian product to the standard library

### PR DESCRIPTION
**Pull request by amtoine**
# Description
i wrote this for my job and thought it could be a nice fit in `std iter` :yum: 

# User-Facing Changes
adds the `std iter cartesian product` command which takes a *rest* number of lists as arguments and produces the list of lists of all the possible element combinations of the input lists.

# Tests + Formatting
adds a new `iter_cartesian_product` test to `test_iter.nu`

# After Submitting

### CODE REVIEW

**Comment by jntrnr** [comment]
Sorry - but I'm not sure this fits in the standard library. We should try to keep it focused to things that'll have pretty wide usage for now.

**Comment by amtoine** [comment]
> Sorry - but I'm not sure this fits in the standard library. We should try to keep it focused to things that'll have pretty wide usage for now.
>
i can move that to the `nu_scripts` :wink:

**Comment by fdncred** [comment]
let's close this for now since you're moving it to nu_scripts.

**Comment by amtoine** [comment]
yup, PR is up :relieved:

**Pull request closed without merging**
