### PR TITLE
Fix trailing slash issue with autocd

### PR DESCRIPTION
**Pull request by woosaaahh**
# Description

Issues have been fixed for trailing slashes when using `cd ../` (https://github.com/nushell/nushell/pull/12760) or `cd /` (https://github.com/nushell/nushell/pull/12761).
This fixes trailing slash issues with `autocd` e.g. `../` (https://github.com/nushell/nushell/pull/12760#issuecomment-2094961496).

# User-Facing Changes

No more `$env.PWD contains trailing slash` error when using `autocd`.

# Tests + Formatting

# After Submitting

### CODE REVIEW

**Comment by YizhePKU** [comment]
I think we should add automated tests for auto-cd.

**Comment by YizhePKU** [comment]
Could you also add a test for this?

**Comment by YizhePKU** [comment]
Let's put this on hold. We're considering adding a dedicated `set_pwd()` API that also fixes the issue. See https://github.com/nushell/nushell/pull/12760#issuecomment-2095393012

**Comment by woosaaahh** [comment]
> Let's put this on hold. We're considering adding a dedicated `set_pwd()` API that also fixes the issue. See [#12760 (comment)](https://github.com/nushell/nushell/pull/12760#issuecomment-2095393012)

OK, no problem !

I'll let you decide if this should be closed or not.

**Comment by sholderbach** [comment]
Thanks for immediately starting on this @woosaaahh 

Superseded by #12779

**Pull request closed without merging**
