### PR TITLE
nu-explore: Try to fix a truncation issue in expand view

### LINKED ISSUE #10560: explore misaligns columns/lines when hitting right arrow sometimes
### Describe the bug

When testing the `explore` command I like to do `$env | explore` because it can be complex. While doing this, I noticed that sometimes the alignment of lines can get off. Here is an example.

### How to reproduce

1. `$env | explore`
2. hit `t` (for table/transpose)
3. hit `e` (for expand)
4. Down-Arrow until you get to menus - alignment looks good (or page down/fn page down on mac)
image
5. Hit right arrow - alignment looks good
image
6. Hit right arrow again - alignment is messed up now
7. Notice how the lines of type, style, and source are now misaligned.
image

### Expected behavior

lines stay aligned

### Screenshots

_No response_

### Configuration

|key|value|
|-|-|
|version|0.85.1|
|branch|main|
|commit_hash|fa2e6e5d5340ce0d12dca8218aae3561fb1d6231|
|build_os|macos-aarch64|
|build_target|aarch64-apple-darwin|
|rust_version|rustc 1.70.0 (90c541806 2023-05-31)|
|rust_channel|1.70.0-aarch64-apple-darwin|
|cargo_version|cargo 1.70.0 (ec8a8a0ca 2023-04-25)|
|build_time|2023-09-30 09:49:00 -05:00|
|build_rust_channel|release|
|allocator|mimalloc|
|features|dataframe, default, extra, sqlite, trash, which, zip|
|installed_plugins|emoji, file, from eml, from ics, from ini, from parquet, from plist, from vcf, gstat, highlight, hist, inc, json path, periodic-table, plot, pnet, query, query json, query web, query xml, regex, str bexpand, str similarity, xyplot|

### Additional context

/cc @zhiburt @rgwood

### PR DESCRIPTION
**Pull request by zhiburt**
I haven't tested cause can't reproduce, but the issue very likely was related to a emojies. (I mean I probably could but ....)

Could you try it @fdncred?
 
fix #10560

### CODE REVIEW

**Comment by fdncred** [comment]
Yup, this fixes the problem but creates another problem. This fix removes all the colors.
image

**Comment by sholderbach** [comment]
To bisect things can you recheckout the `Cargo.lock` from `main` as there seems to be an unrelated `cargo update` of all deps in this PR

**Comment by fdncred** [comment]
I checked it out and re-compiled with the main branches cargo.lock file and the non-coloring issue still exists.

**Comment by fdncred** [comment]
Latest commit fixes the coloring issues. Thanks!
image

**Comment by fdncred** [comment]
Thanks!

**Pull request merged**
