### PR TITLE
nu-table/ Fix footer truncation in case of head_on_border

### LINKED ISSUE #13966: heads and footers don't always match
### Describe the bug

@zhiburt a while back you fixed some bugs with headers getting truncated. That is working great but now the footers are truncated. When you have a minute, it would be great if you could look into this.

## Header
image

## Footer
image

Notice how the headers don't match the footers. It seems that whatever you did to the headers, needs to be done to the footers.

### How to reproduce

See above

### Expected behavior

See above

### Configuration

|key|value|
|-|-|
|version|0.98.1|
|major|0|
|minor|98|
|patch|1|
|branch|main|
|commit_hash|166d5fa4ffa3c5514b2d7597f3238e6828c986f9|
|build_os|macos-aarch64|
|build_target|aarch64-apple-darwin|
|rust_version|rustc 1.79.0 (129f3b996 2024-06-10)|
|rust_channel|1.79.0-aarch64-apple-darwin|
|cargo_version|cargo 1.79.0 (ffa9cf99a 2024-06-03)|
|build_time|2024-09-30 16:55:41 -05:00|
|build_rust_channel|release|
|allocator|mimalloc|
|features|default, sqlite, trash|
|installed_plugins|bexpand 1.3.5, bg 0.5.0, compress 0.1.0, dt 0.1.0, emoji 0.6.0, explore_ir 0.2.0, file 0.8.0, formats 0.98.1, gitql 0.1.0, gstat 0.98.1, image 0.4.2, inc 0.98.1, json_path 0.7.0, jwalk 0.8.0, md 0.5.0, parquet 0.8.0, pnet 1.7.0, polars 0.98.1, qr_maker 1.1.0, query 0.98.1, query_git 0.7.0, regex 0.7.0, strutils 0.5.0|

### PR DESCRIPTION
**Pull request by zhiburt**
Hi there;

I do think it must be fixed.

I also did improve performance for a fraction in case of header on border.
I want to believe :) I didn't bench it.
But we didn't cached the width in this code branch before.
Which was causing all data reestimation.

close #13966
cc: @fdncred

### CODE REVIEW

**Comment by fdncred** [comment]
Doesn't seem like it fixed it. It's broken on top now too.
image
image
```nushell
❯ term size
╭─────────┬─────╮
│ columns │ 135 │
│ rows    │ 44  │
╰─────────┴─────╯
```

**Comment by zhiburt** [comment]
But where it's broken now?
I guess it's alright?

I mean I did change the behavior in a minor way so it's sort of expected.
But what was supposed to be there?

**Comment by fdncred** [comment]
You can get the column names like this
```nushell
❯ ls -l | columns
╭────┬───────────╮
│  0 │ name      │
│  1 │ type      │
│  2 │ target    │
│  3 │ readonly  │
│  4 │ mode      │
│  5 │ num_links │
│  6 │ inode     │
│  7 │ user      │
│  8 │ group     │
│  9 │ size      │
│ 10 │ created   │
│ 11 │ accessed  │
│ 12 │ modified  │
╰────┴───────────╯
```
ta should be target
readonl should be readonly

This is the columns labels on top *before* this PR
image

**Comment by zhiburt** [comment]
fixed?

**Comment by fdncred** [comment]
Yup, this works great!

**Pull request merged**
