### PR TITLE
remove output, append, bin flag from fetch command

### PR DESCRIPTION
**Pull request by WindSoilder**
# Description

Closes: #7439

I love to see so much code are removed :-)

# User-Facing Changes

_(List of all changes that impact the user experience here. This helps us keep track of breaking changes.)_

# Tests + Formatting

Don't forget to add tests that cover your changes.

Make sure you've run and fixed any issues with these commands:

- `cargo fmt --all -- --check` to check standard code formatting (`cargo fmt --all` applies these changes)
- `cargo clippy --workspace -- -D warnings -D clippy::unwrap_used -A clippy::needless_collect` to check that you're using the standard code style
- `cargo test --workspace` to check that all tests pass

# After Submitting

If your PR had any user-facing changes, update [the documentation](https://github.com/nushell/nushell.github.io) after the PR is merged, if necessary. This will help us keep the docs up to date.

### CODE REVIEW

**Comment by fdncred** [comment]
@WindSoilder Would you mind documenting in this issue what the work-around to removing this code is please? I assume it's `| save` and such but it would be a good reference for someone looking to figure out what has changed and how to make it work again.

**Comment by WindSoilder** [comment]
@fdncred , sure!  If the pr is ok, here are workaround(the first two are already mentioned in the original issue):

```
fetch --output test.html https://www.example.com ---> fetch https://www.example.com | save test.html 
fetch --append test.html https://www.example.com ---> fetch https://www.example.com | save --append test.html
fetch --output test.html --bin https://www.example.com ---> fetch https://www.eaxmple.com | save --raw test.html
```

**Comment by fdncred** [comment]
What I'm curious about is when downloading a binary, which I thought was what `--bin` was for. Here you're saving a text file in binary mode. I'm not sure if that's a good example. Perhaps a link to a zip or something like that should be tested. Some binary file.

**Comment by WindSoilder** [comment]
图片
Here is my testing result, `--bin` is actually the same to `--raw` in `safe`

**Comment by fdncred** [comment]
Thanks for the extra testing @WindSoilder. I appreciate all your support. I tried it too and it's working for me too.

**Pull request merged**
