### PR TITLE
Allow custom value operations to work on eager and lazy dataframes interchangeably. 

### PR DESCRIPTION
**Pull request by ayax79**
Fixes Bug #12809 

The example that @maxim-uvarov posted now works as expected:

Screenshot 2024-05-09 at 16 21 01

### CODE REVIEW

**Comment by IanManske** [comment]
Thanks! This looks good.

**Comment by maxim-uvarov** [comment]
> Although, maybe https://github.com/nushell/nushell/issues/12821 needs fixing as well?
yep, ayax79 is for sure aware of it.

**Comment by fdncred** [comment]
Is this ready to land?

**Comment by ayax79** [comment]
@fdncred, yes it is good to go.

**Comment by ayax79** [comment]
> Although, maybe #12821 needs fixing as well?
I will fix that seperately, it's not really related.

**Comment by fdncred** [comment]
Thanks!

**Pull request merged**
