### PR TITLE
Add -n option for echo

### PR DESCRIPTION
**Pull request by nibon7**
# Description
Related #5724

# Tests

Make sure you've done the following:

- [x] Add tests that cover your changes, either in the command examples, the crate/tests folder, or in the /tests folder.
- [ ] Try to think about corner cases and various ways how your changes could break. Cover them with tests.
- [ ] If adding tests is not possible, please document in the PR body a minimal example with steps on how to reproduce so one can verify your change works.

Make sure you've run and fixed any issues with these commands:

- [ ] `cargo fmt --all -- --check` to check standard code formatting (`cargo fmt --all` applies these changes)
- [ ] `cargo clippy --workspace --features=extra -- -D warnings -D clippy::unwrap_used -A clippy::needless_collect` to check that you're using the standard code style
- [ ] `cargo test --workspace --features=extra` to check that all the tests pass

### CODE REVIEW

**Comment by jntrnr** [comment]
@nibon7 - in Nushell, we're currently using `echo` to send values into a pipeline. You may want to add this flag to `print`, which hands printing to the screen.

**Comment by hustcer** [comment]
@jntrnr We have this flag for `print` already: https://github.com/nushell/nushell/pull/5935

**Comment by nibon7** [comment]
> @nibon7 - in Nushell, we're currently using `echo` to send values into a pipeline. You may want to add this flag to `print` instead, which hands printing to the screen.

I see. It seems when using internal and external command, an extra newline added.

```sh
 ls *.txt | each { |x| echo (sha512sum --tag $x.name) } | save sha512.txt
```

**Comment by nibon7** [comment]
Hmm,  `str trim` may be helpful. #5898. Close it.

**Pull request closed without merging**
