### PR TITLE
create Palette trait

### PR DESCRIPTION
**Pull request by klnusbaum**
As stated in #1798, we'd like to be able to support user defined color schemes. The first step in this process seems to be abstracting out the ability to style spans. In this PR, we introduce the `Pallet` trait. The only implementor at the moment is the `DefaultPallet`, however, as stated in #1798 we aim to eventually be able to define our own base16 file format and then create a Pallet that can use those files.

I'd like to actually put the Pallet code in it's own file, but I kept getting compile errors like
```
103 |     pub fn paint_string<'l, P: Pallet>(
    |                                ^^^^^^ not found in this scope
```

I think this is due to my lack of knowledge on the Rust module system. Any guidance here would be much appreciated.

Also, we should probably discuss whether or not `paint_string` should remain a static function. It's starting to take in several parameters now and it might just be worth making it a method.

### CODE REVIEW

**Comment by jonathandturner** [comment]
@klnusbaum - looks good. One nit: can we call it "Palette" instead of "Pallet"?

**Comment by jonathandturner** [comment]
Oh and you can put it in a separate file if that file is referenced by one of the `mod.rs` files.  It's a tiny bit tricky, but happy to chat about how to do it. Might be easier on discord.

**Comment by klnusbaum** [comment]
> call it "Palette" instead of "Pallet"?
Woops. Absolutely. That's an embarrassing misspell.

> It's a tiny bit tricky, but happy to chat about how to do it. Might be easier on discord.
Sure thing, I'll shoot you a message

**Comment by jonathandturner** [comment]
Looks good!

**Pull request merged**
