### PR TITLE
Add commands to scope variable

### PR DESCRIPTION
**Pull request by stevenbarragan**
Following `$scope.aliases` this adds `$scope.commands` to the `$scope` variable

Usage:

```shell
echo $scope.commands | pivot
```

It display the command along with the allowed parameters. Let me know what do you think.

Almost fixes issue https://github.com/nushell/nushell/issues/2821. The only thing missing would be displaying only custom commands. I can work on that after I get feedback form this PR.

### CODE REVIEW

**Comment by stormasm** [comment]
@stevenbarragan Hi !, thanks for working on this...  There is one issue that has to be resolved along with this PR...  Here is what is going on...

This commit introduced a regression into the code....
https://github.com/nushell/nushell/commit/e737222a5ddb5f24edbc317c513828fb13e14d9e

Currently @andrasio have been discussing on discord the following issue...

https://discord.com/channels/601130461678272522/615962413203718156/828284924255272971

This is the problem....

```rust
    pub fn get_command_names(&self) -> Vec<String> {
        let mut names = vec![];

        for frame in self.frames.lock().iter() {
            let mut frame_command_names = frame.get_command_names();
            frame_command_names.extend(frame.get_alias_names());
            //frame_command_names.extend(frame.get_custom_command_names());
            names.append(&mut frame_command_names);
        }

        names.dedup();
        names.sort();
        println!("{:?}",names);
        names
    }

```

So it appears that get_command_names already has the custom commands in them...
So then you are layering another layer of custom commands on top of that and the deduping
is not working for some reason....

You will see that if you test by adding a few of your own custom commands they will show
up twice in your list....
Which is what @andrasio and I were discussing on discord (see above link)

I believe the best way forward is to have the ability to see ONLY
regular commands
customer commands independently...
Mixing them all together in a big soup is too confusing...
Especially if you have lots of custom commands.
People will have lots of custom commands going forward.
So I recommend splitting it out now...
Let me know how this approach sounds to you and if you want to discuss further either here or on discord.
Thanks,
storm

**Comment by jonathandturner** [comment]
Cool :)

**Comment by fdncred** [comment]
I know this comment is late, but the `-h --help` on every command is kind of annoying. It's a cool idea to show the parameters, but my preference would be to hide the help ones.

**Comment by stormasm** [comment]
@fdncred @jonathandturner so I took I took the commit for a spin and noticed one thing that I don't like either...  

It would be great to see the commands sorted by name ---- right now its just a big jumbled list with no order.  
So therefore with a long list of commands you can not find the command you are looking for easily.

Curious to know what others think on whether they think it should be sorted ?

**Comment by fdncred** [comment]
I would support sorting.

**Pull request merged**
