### PR TITLE
Add system, user and idle times to benchmark command

### PR DESCRIPTION
**Pull request by radekvit**
This adds more information to the benchmark command, using the `heim` crate.

Extending the `benchmark` command was mentioned in #2568.

### CODE REVIEW

**Comment by radekvit** [comment]
@jonathandturner 
The wasm job fails on building `socket2`, which should not be affected by my changes.

**Comment by jonathandturner** [comment]
@radekvit - It looks like it's coming from some of the dependencies you added. One path to it is from `heim` -> `heim-common` -> `smol` -> `socket2`

**Comment by radekvit** [comment]
> @radekvit - It looks like it's coming from some of the dependencies you added. One path to it is from `heim` -> `heim-common` -> `smol` -> `socket2`

I can see `socket2` in Cargo.lock on main, so it already was a dependency. Both dependencies I added were, just not in nu-cli.

**Comment by jonathandturner** [comment]
@radekvit The lock file might have them if it was built using the default features. For wasm, we don't include any features by default since many of them aren't wasm-compatible, and use features to turn off the sections of the code (or simplify them)

**Comment by radekvit** [comment]
> @radekvit The lock file might have them if it was built using the default features. For wasm, we don't include any features by default since many of them aren't wasm-compatible, and use features to turn off the sections of the code (or simplify them)

@jonathandturner That must be it. I will feature-gate the advanced stats to fix this. Is it ok to add it to the "default" features in the top-level Cargo.toml

**Comment by jonathandturner** [comment]
@radekvit yeah that should be okay

**Comment by jonathandturner** [comment]
Thanks!

**Pull request merged**
