### PR TITLE
`query web --query` should return `list<list<string>>` like the scraper crate's `ElementRef::text()`

### PR DESCRIPTION
**Pull request by kik4444**
# Description

## Problem
I tried converting one of my Rust web scrapers to Nushell just to see how it would be done, but quickly ran into an issue that proved annoying to fix without diving into the source.

For instance, let's say we have the following HTML
```html
<p>Hello there, <span style="color: red;">World</span></p>
```
and we want to extract only the text within the `p` element, but not the `span`. With the current version of nu_plugin_query, if we run this code
```nushell
echo `<p>Hello there, <span style="color: red;">World</span></p>` | query web -q "p" | get 0
# returns "Hello there, World"

# but we want only "Hello there, "
```
we will get back a `list<string>` that contains 1 string `Hello there, World`.
To avoid scraping the span, we would have to do something like this
```nushell
const html = `<p>Hello there, <span style="color: red;">World</span></p>`
$html
| query web -q "p"
| get 0
| str replace ($html | query web -q "p > span" | get 0) ""
# returns "Hello there, "
```
In other words, we would have to make a sub scrape of the text we *don't* want in order to subtract it from the text we *do* want.

## Solution
I didn't like this behavior, so I decided to change it. I modified the `execute_selector_query` function to collect all text nodes in the HTML element matching the query. Now `query web --query` will return a `list<list<string>>`
```nushell
echo `<p>Hello there, <span style="color: red;">World</span></p>` | query web -q "p" | get 0 | to json --raw
# returns ["Hello there, ","World"]
```
This also brings `query web --query`'s behavior more in line with [scraper's ElementRef::text()](https://docs.rs/scraper/latest/scraper/element_ref/struct.ElementRef.html#method.text) which "Returns an iterator over descendent text nodes", allowing you to choose how much of an element's text you want to scrape without resorting to string substitutions.

## Consequences
As this is a user-facing change, the usage examples will produce different results than before. For example
```nushell
http get https://phoronix.com | query web --query 'header'
```
will return a list of lists of 1 string each, whereas before it was just a list of strings.

I only modified the 3rd example
```nushell
# old
http get https://www.nushell.sh | query web --query 'h2, h2 + p' | group 2 | each {rotate --ccw tagline description} | flatten
# new
http get https://www.nushell.sh | query web --query 'h2, h2 + p' | each {str join} | group 2 | each {rotate --ccw tagline description} | flatten
```
to make it behave like before because I thought this one ought to show the same results as before.
However, the second reason I changed the 3rd example is because it otherwise panics! If we run the original 3rd example with my modifications, we get a panic
```
thread 'main' panicked at crates/nu-protocol/src/value/record.rs:34:9:
assertion `left == right` failed
  left: 2
 right: 17
```
This happens because `rotate` receives a list of lists where the inner lists have a different number of elements.

However this panic is unrelated to the changes I've made, because it can be triggered easily without using the plugin. For instance
```nushell
# this is fine
[[[one] [two]] [[three] [four]]] | each {rotate --ccw tagline description}

# this panics!
[[[one] [two]] [[three] [four five]]] | each {rotate --ccw tagline description}
```
Though beyond the scope of this PR, I thought I'd mention this bug since I found it while testing the usage examples. However, I intend to make a proper issue about it tomorrow.

# User-Facing Changes

`query web --query "css selector"` now returns a `list<list<string>>` instead of a `list<string>` to make it more in line with [scraper's ElementRef::text()](https://docs.rs/scraper/latest/scraper/element_ref/struct.ElementRef.html#method.text).

# Tests + Formatting

I ran `cargo fmt --all -- --check`, `cargo clippy --workspace -- -D warnings -D clippy::unwrap_used` and the tests in the plugin.

# After Submitting

PR that updates the documentation to match the new 3rd example: https://github.com/nushell/nushell.github.io/pull/1235

### CODE REVIEW

**Comment by fdncred** [comment]
I'm generally for any updates to `query web`. I wrote it and several people have contributed to it to make it nicer but it's kind of a beast, especially the table finding stuff.

I'm fine with these changes in general but I'd like to make sure that the other examples still work, or at least are not broken due to this PR.

**Comment by fdncred** [comment]
I tested this and this test
```
http get https://phoronix.com | query web --query 'header'
```
needs to be updated to include `| flatten` because it doesn't work the same anymore.

I also noticed the second example doesn't work anymore but I'm not sure if that has anything to do with your changes.

**Comment by fdncred** [comment]
it would also be good to fix the rotate bug you've mentioned but in another pr, of course. we'd appreciate the help.

**Comment by fdncred** [comment]
@kik4444 if you can merge the latest main and change that one test I mentioned, we can land this.

**Comment by kik4444** [comment]
I made an issue about the `rotate` thing https://github.com/nushell/nushell/issues/11716

**Comment by kik4444** [comment]
> @kik4444 if you can merge the latest main and change that one test I mentioned, we can land this.

Do you mean just adding `flatten` to the first example?

**Comment by fdncred** [comment]
> > @kik4444 if you can merge the latest main and change that one test I mentioned, we can land this.
> 
> Do you mean just adding `flatten` to the first example?

yes

**Comment by kik4444** [comment]
Ok that should be everything then.

**Comment by fdncred** [comment]
Thanks!

**Pull request merged**
