### PR TITLE
Refactor `lines` command

### PR DESCRIPTION
**Pull request by IanManske**
# Description
This PR uses `str::lines` to simplify the `lines` command (and one other section of code). This has two main benefits:
1. We no longer need to use regex to split on lines, as `str::lines` splits on `\r\n` or `\n`.
2. We no longer need to handle blank empty lines at the end. E.g., `str::lines` results in `["text"]` for both `"test\n"` and `"text"`.

These changes give a slight boost to performance for the following benchmarks:
1. lines of `Value::String`:
    ```nushell
    let data = open Cargo.lock
    1..10000 | each { $data | timeit { lines } } | math avg 
    ```
    current main: 392µs
    this PR: 270µs
2. lines of external stream:
    ```nushell
    1..10000 | each { open Cargo.lock | timeit { lines } } | math avg 
    ```
    current main: 794µs
    this PR: 489µs

### CODE REVIEW

**Comment by fdncred** [comment]
This really seems like a great simplification. The only thing I can't see really is if there have been any changes in regard to streaming. We definitely don't want to change how lines streams data if possible.

**Comment by IanManske** [comment]
> We definitely don't want to change how lines streams data if possible.

Yep, that's for sure. I made sure to prove to myself that the streaming behavior should be the same. Correct me if anything looks wrong:
- for `Value::String`: this already had a `.collect::<Vec<String>>();`, so the whole result is already available and there is no point in streaming.
- for `PipelineData::ListStream`: still streams, just changed how the lines are split for each item.
- for `PipelineData::ExternalStream`: this one might be a little harder to see, but all the logic is still the same. (One small difference is that the incomplete line is removed from the queue instead of the current batch of lines, but this gives the same result.)

**Comment by fdncred** [comment]
Great, thanks for confirming!

**Comment by rgwood** [comment]
Nice PR, thanks!

**Pull request merged**
