### PR TITLE
Set current working directory at startup

### PR DESCRIPTION
**Pull request by YizhePKU**
This PR sets the current working directory to the location of the Nushell executable at startup, using `std::env::set_current_dir()`. This is desirable because after PR https://github.com/nushell/nushell/pull/12922, we no longer change our current working directory even after `cd` is executed, and some OS might lock the directory where Nushell started.

The location of the Nushell executable is chosen because it cannot be removed while Nushell is running anyways, so we don't have to worry about OS locking it.

This PR has the side effect that it breaks buggy command even harder. I'll keep this PR as a draft until these commands are fixed, but it might be helpful to pull this PR if you're working on fixing one of those bugs.

### CODE REVIEW

**Comment by fdncred** [comment]
We have 4 days until the next release which means there are 2 days to either revert #12922 or fix all the issues caused by it. I'm guessing we should probably revert it.

**Comment by fdncred** [comment]
Revert is here if/when we need it https://github.com/nushell/nushell/pull/12954

**Comment by fdncred** [comment]
I landed the revert. We can revert the revert after the release. We prefer not to have an unknown number of bugs right before the release since there is no time to find and fix them.

**Comment by YizhePKU** [comment]
I've incorporated https://github.com/nushell/nushell/pull/12922 into this PR, so we can merge this when we're ready to undo the revert. With https://github.com/nushell/nushell/pull/12975 and https://github.com/nushell/nushell/pull/12976, this should pass our current test suite, but there might be more issues (such as https://github.com/nushell/nushell/issues/12951 that aren't caught by the test suite).

**Comment by kubouch** [comment]
So before landing this PR, we need to patch reedline as per @sholderbach 's [comment](https://github.com/nushell/nushell/issues/12951#issuecomment-2131284556) to ensure that it reads the correct cwd. I guess it could get a separate cwd parameter.

**Comment by fdncred** [comment]
I believe we still want to land this but there are conflicts now. @YizhePKU do you have time to fix the conflicts?

**Comment by fdncred** [comment]
@YizhePKU do you have time to clean up the conflicts?

**Comment by devyn** [comment]
Reminding myself to clean this up so we can merge it

**Comment by fdncred** [comment]
This one has been a long time coming. We've discussed it in the past and we agreed to land it as soon as it could have a green ci. Devyn worked on it today, and got it mostly green, so let's land it and see how it goes.

**Comment by fdncred** [comment]
This has somehow broken LS_COLORS. Folders used to be blue, now they're white. 

## Before
image

## After
image

**Comment by NotTheDr01ds** [comment]
From reading through the history on this, #12922, and #12749, I can't tell if the behavior I mention in #14000 is an intentional or unintentional side-effect of this change.  Any thoughts from those that worked on it regarding that and how we can fix?

**Pull request merged**
