### PR TITLE
Keep until and while as subcommands of keep

### LINKED ISSUE #2180: Make keep a command and move keep-while and keep-until as sub commands.
With the move of `skip` as a command holding `skip-while` and `skip-until` as sub commands (`skip until` and `skip while`) [in this Pull Request](https://github.com/nushell/nushell/pull/2179) we need to do the same for `keep` and having `keep-while` turned to `keep while` and `keep-until` to `keep until` respectively.

The changes required are almost exactly the same steps as the linked Pull Request above.

### PR DESCRIPTION
**Pull request by k-brk**
Fixes #2180

### CODE REVIEW

**Comment by jonathandturner** [comment]
Hopefully https://github.com/nushell/nushell/pull/2196 helps with the warnings.

**Comment by jonathandturner** [comment]
@k-brk - can you add a trivial change to this so that CI will pick up the latest clippy fixes?

**Comment by k-brk** [comment]
@jonathandturner Done, I have added and removed new line with git amend and in the end pushed no new changes to trigger CI

**Comment by jonathandturner** [comment]
Looks good!

**Pull request merged**
