### PR TITLE
Linear Regression 

### PR DESCRIPTION
**Pull request by TrifanBogdan24**
Solved issue: https://github.com/nushell/nushell/issues/11392
Added Linear Regression Algorithm that will return the line that goes the best through a set of points in @d.
My method will either return `d : y = a * x + b` or `d : x = a`.

Please checkout the **README.md** at the location `crates/nu-command/src/math/nushell-liniar-regression/README.md`, where I explained my method.

https://github.com/TrifanBogdan24/nushell-linear-regression.git

### CODE REVIEW

**Review by fdncred — CHANGES_REQUESTED** [review]
Thanks for this. We appreciate you trying to make nushell better.

I'm not sure how popular linear regression calculation is but I think we'd want to put this in the extra crate with the other not frequently used match commands.

Also, linear is spelled liniar in some places.

We probably shouldn't have a path that uses nushell in the name like nushell-liniar-regression since it's a crate in nushell there's no need for nushell.

I wonder if this should be in a plugin rather than in the extra crate too. I'll let others chime in on that.

**Comment by amtoine** [comment]
the last status in #11392 was to implement a plugin first and see if people use it.
not sure having that built-into Nushell makes that much sense as a first step

**Comment by fdncred** [comment]
Converting to a draft until we find a way forward. I'd support a plugin and also put it in awesome-nu as well.

**Comment by alexandruradovici** [comment]
@TrifanBogdan24 can you try converting this into a plugin?

**Comment by fdncred** [comment]
If someone wants to take this code and put in a plugin, have at it. I'll list it on awesome-nu if you ping me with it. Closing this for now.

**Pull request closed without merging**
