### PR TITLE
fix: reduce command have not redirected block's evaluation output

### PR DESCRIPTION
**Pull request by ZetaNumbers**
# Description

fixes https://github.com/nushell/nushell/issues/5190

# Tests

Make sure you've run and fixed any issues with these commands:

- [x] `cargo fmt --all -- --check` to check standard code formatting (`cargo fmt --all` applies these changes)
- [x] `cargo clippy --all --all-features -- -D warnings -D clippy::unwrap_used -A clippy::needless_collect` to check that you're using the standard code style
- [x] `cargo build; cargo test --all --all-features` to check that all the tests pass

### CODE REVIEW

**Comment by ZetaNumbers** [comment]
I would like to add a test, but i don't know how to not require ripgrep for it. If there was some way to know if it's tty mode.

**Comment by fdncred** [comment]
are you sure this is right? i wrote how i did this in your issue but i just tested it in your pr.
image

**Comment by ZetaNumbers** [comment]
> are you sure this is right? i wrote how i did this in your issue but i just tested it in your pr. it appears that it's just showing the last search. image

Last replacement actually, and it disappears if you pipe the whole thing.

**Comment by ZetaNumbers** [comment]
> I don't think we want to call externals like `rg` from within our ci.

Can we, perhaps, add a new `debug-call` command, that would output `Command::run`'s arguments, including `redirect_stdout` (`Call`'s field)?

**Comment by jntrnr** [comment]
There are commands you can use that are built into nu. Check out `nu --testbin`. Something like `nu --testbin cococo` is like a crossplatform external echo that works the same across OSes and is good for tests.

**Comment by ZetaNumbers** [comment]
I wrote a testbin to detect tty on stdout, but `nu!` macro used in tests always pipes the output. I don't know what to do.

**Comment by ZetaNumbers** [comment]
There's https://github.com/dtolnay/faketty, but i am sure it's not allowed, unless it is included it in the nushell.

**Comment by ZetaNumbers** [comment]
After some research, i haven't found any good cross-platform way to fake tty. So the only way to write a test for this, is to directly use `Command::run`. However, i believe this would introduce much more complexity compared to the fix itself, so the comment i left should be enough.

**Comment by fdncred** [comment]
I'm not sure if this is a good "fix" or not but let's run with it and see if anything else breaks.

**Pull request merged**
