### PR TITLE
Update winget submission workflow include only default msi files

### PR DESCRIPTION
**Pull request by hustcer**
### Update winget submission workflow include only default msi files:
---
The new release workflow after https://github.com/nushell/nushell/pull/10457 will add full featured packages like: `nu-*-x86_64-windows-msvc-full.msi` and `nu-*-aarch64-windows-msvc-full.msi` (A release preview could be found here: https://github.com/nushell/nightly/releases/tag/nightly-6a2fd91 ) and this change will make sure only the default packages will be included just the same as before to make sure that nothing will be broken.

BTW: Due to lots of changes made recently about the release workflow, I will stand-by for the next release.

### CODE REVIEW

**Comment by fdncred** [comment]
ugh, i hate winget but we probably need to do this. thanks for your offer to stand-by.

**Comment by fdncred** [comment]
Winget failed. No clue why. https://github.com/microsoft/winget-pkgs/pull/122956

**Comment by fdncred** [comment]
This is the entry from the failed installer log.
```
CAQuietExec:  Error 0xc0000135: Command line returned an error.
CAQuietExec:  Error 0xc0000135: QuietExec Failed
CAQuietExec:  Error 0xc0000135: Failed in ExecCommon method
CustomAction ReplacePathsInWindowsTerminalProfile returned actual error code 1603 (note this may not be 100% accurate if translation happened inside sandbox)
Action ended 14:27:07: InstallFinalize. Return value 3.
Action ended 14:27:07: INSTALL. Return value 3.
```
Not sure what it means exactly although ReplacePathsInWindowsTerminalProfile is in our wix file.

**Comment by hustcer** [comment]
Sorry that it fails again, I have no idea why it fails currently, as my change works as expected. So weird

**Comment by fdncred** [comment]
I think the reason it's failing is because of trying to update the nu.json windows terminal fragment.

**Pull request merged**
