### PR TITLE
Fix completion on `$nu` to show correct menus

### LINKED ISSUE #8863: completion on `$nu` uses `$nu | columns` at all depth
### Describe the bug

could not find a similar in the issue tracker so here i go :smirk: 

when we try to auto-complete on the `$nu` variable, no matter the depth in the data, we get results from `$nu | columns` :open_mouth: 

### How to reproduce

see [this recording](https://asciinema.org/a/577132), which has the commands and the wrong completion menus :yum: 

### Expected behavior

the completion
- on `$nu` should use `config-path env-path history-path loginshell-path plugin-path scope home-path temp-path pid os-info startup-time is-interactive is-login current-exe`, i.e. `$nu | columns`
- on `$nu.scope` should use `vars commands aliases modules engine_state`, i.e. `$nu.scope | columns`
- etc, etc, ...

### Screenshots

_No response_

### Configuration

`version` is broken, i'm on latest `main` (8ee52b6ee1cebfbb265d68efcffed97254a7c252) :wink: 

| key                | value                                    |
| ------------------ | ---------------------------------------- |
| version            | 0.78.1                                   |
| branch             | main                                     |
| commit_hash        | f2b977b9c59931ad2b5e55174e63ebbec50b8cbe |
| build_os           | linux-x86_64                             |
| build_target       | x86_64-unknown-linux-gnu                 |
| rust_version       | rustc 1.66.1 (90743e729 2023-01-10)      |
| rust_channel       | 1.66.1-x86_64-unknown-linux-gnu          |
| cargo_version      | cargo 1.66.1 (ad779e08b 2023-01-10)      |
| build_time         | 2023-04-08 12:34:28 +02:00               |
| build_rust_channel | release                                  |
| features           | default, zip                             |
| installed_plugins  | len                                      |

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by ito-hiroki**
I'm still new to nushell and Rust, so please let me know if there are any omissions and/or mistakes.

# Description

fixed #8863
`$nu` completion shows wrong completion menus at this time.
This PR fixes the problem to show the correct ones.

# User-Facing Changes

Users can use the correct menus on `$nu` completion like this [recording](https://asciinema.org/a/KCwfpdAoMFsQODFBnb3NwmufC).

# Tests + Formatting

```
$ use toolkit.nu
$ toolkit check pr

- :green_circle: `toolkit fmt`
- :green_circle: `toolkit clippy`
- :green_circle: `toolkit test`
- :green_circle: `toolkit test stdlib`
```

# After Submitting

nothing

### CODE REVIEW

**Review by amtoine — COMMENTED** [review]
i could test it and it works like a charm :ok_hand: 

i'm just wondering if we could add tests to cover that behaviour :thinking: 
i think i've seen "completions" tests for such a thing but i'm not sure where they are in the tests...

**Comment by ito-hiroki** [comment]
The completion tests may be this one.
https://github.com/nushell/nushell/blob/main/crates/nu-cli/tests/completions.rs/#L525

I will prepare additional $nu tests.
Thank you for your comments.

**Review by amtoine — APPROVED** [review]
that's what i'm talking about, nice job @ito-hiroki :muscle: 

maybe another reviewer will want this to go in a separate test function, but i'm fine with the tests :ok_hand:

**Comment by ito-hiroki** [comment]
Sure! Thank you👍

**Comment by fdncred** [comment]
Thanks @ito-hiroki! We appreciate your help.

**Pull request merged**
