### PR TITLE
Deliver a few fixes for `explore` command

### PR DESCRIPTION
**Pull request by zhiburt**
ref #6984

### CODE REVIEW

**Comment by zhiburt** [comment]
Now look, I've found one more 'glitch' (quite big).

Type `:nu ls;ls` or `:try ls;ls <enter>`

it's related to a `eval_source`.
So you don't return a value from such an expression.

I am not sure what is the best fix would be here.

**Comment by zhiburt** [comment]
Yes I am not sure what is the right logic here.
As it involves nu 'language/syntax' logic.

**Comment by zhiburt** [comment]
But I've followed 1st approach.

**Comment by fdncred** [comment]
oh, I see what you mean with `ls;ls` that's weird. Ya, let's try the first approach, like you said, and see if that works.

It looks like the `:try` `clear` issue is resolved here though.

**Comment by fdncred** [comment]
ok, let's try it. thanks for the quick fix, as usual!

**Pull request merged**
