### PR TITLE
[WIP] table: Change Record view in expand-mode

### PR DESCRIPTION
**Pull request by zhiburt**
ref #6851

Maybe it's worth to change a `Record` view as we do the top table in an `expand` mode?

So inner records will be also represented as key-value

image

### Now:

image

### Was:

image

### CODE REVIEW

**Comment by fdncred** [comment]
@zhiburt are you ready to land this? looks like we may have some conflicts. I like your screenshots!

**Comment by zhiburt** [comment]
I'd like to point out that it's better to be tested by someone else. (As I've done not many runs)

One more screenshot.

image

**Comment by rgwood** [comment]
That's looking really nice!

**Comment by fdncred** [comment]
wow, I'm loving this new change!!!
Screenshot 2022-10-31 at 7 55 32 PM

@zhiburt The only thing I still don't understand is why 1/3 of my screen to the right isn't being used with `$nu | table -e`. I understand it truncates with `...` but surely either the `vars` or `commands` tables can show more.
Screenshot 2022-10-31 at 8 02 43 PM


Here's another example with `$nu.scope.vars`
Screenshot 2022-10-31 at 8 06 00 PM

versus `$nu.scope.vars | table -e`
Screenshot 2022-10-31 at 8 06 23 PM

**Comment by zhiburt** [comment]
Patched it.

Must be better; though certainly not ideal...

image

**Comment by fdncred** [comment]
@zhiburt yours looks great! but it doesn't appear to be doing exactly the same thing on Windows.
image

image

image

**Comment by zhiburt** [comment]
> @zhiburt yours looks great! but it doesn't appear to be doing exactly the same thing on Windows.

Could you try it now?

**Comment by fdncred** [comment]
It's not perfect but better.

Non maximized
image

Maximized
image

There's still a 1 inch to 1.5 inch gap on the right but we can live with that for now. 

I'd like to get this CI green so we can land it soon and play more.

**Comment by zhiburt** [comment]
> There's still a 1 inch to 1.5 inch gap on the right but we can live with that for now.

You mean this gap?

image

**Comment by zhiburt** [comment]
> There's still a 1 inch to 1.5 inch gap on the right but we can live with that for now.

Do you mean this gap?

image

**Comment by fdncred** [comment]
Sorry. I meant the top picture. This one. But like I said, we can live with it for now if we can get the CI green we'll land it.
image

**Comment by zhiburt** [comment]
So do you mean we shall spread the table to the whole width?
At least that's what I did you can check it.

PS: Or do it when by some metric like when have like 80% of a screen used already then we use the rest otherwise don't do anything

**Comment by fdncred** [comment]
> So do you mean we shall spread the table to the whole width?

Yes, that was what i've been confused about is why doesn't it take the whole width. It seems like it should take nearly the whole width of your terminal when drawing the table.

Your latest change fixes this now. Thanks! Now, if we can just get the CI green we can land it. Thanks for your excellent work!

**Comment by fdncred** [comment]
@zhiburt is it possible to get this CI green so we can land it. I'd like to have this in before our next release in a couple weeks.

**Comment by fdncred** [comment]
@zhiburt thanks for all this great work! On last check with you, are you ready to land this?

**Comment by fdncred** [comment]
@zhiburt one thing I'd like to mention, that isn't a deal breaker right now, but we're noticing that records don't seem to be highlighted properly. For instance, if you do `(sys).mem` you get I get green keys and white values. But if i do `(sys).mem | table -e -w 30` all keys and values are white.

We can always "fix" this in the next PR, if you want.

**Comment by zhiburt** [comment]
> @zhiburt one thing I'd like to mention, that isn't a deal breaker right now, but we're noticing that records don't seem to be highlighted properly. For instance, if you do `(sys).mem` you get I get green keys and white values. But if i do `(sys).mem | table -e -w 30` all keys and values are white.
> 
> There are some changes in tables too. You can see this with things like `sys | get disks` and `sys | get net`. In my perfect world, the highlighting would be the same both ways.

Must be addressed.
(also fixed an accidental issue where we were expanding all tables)

> As another item for a new PR, I wonder if we could/should reverse the way `-w` works. By that I mean, do an auto-width determination like you used to, but then when things are being truncated, we give it `--max-width` or some such flag to tell tabled to use the full width of the terminal. Thoughts?

But how it would work?
I mean we to truncate first and then expand the rest, correct?
Or do you mean to expand only when we do truncate/wrap stuff?

**Comment by fdncred** [comment]
> I've not pictured this proposal?
> Do you mean truncate first and then expand the rest, correct?
> Or to expand only when we do truncate/wrap stuff?

This is what I mean. Sometimes, there is no reason to expand to take the entire width of the terminal. One way of thinking is that both these commands should return identical tables, unless I specify something like `--max-width` or `--term-width` or something that means to take up the entire width of the terminal.
Screenshot 2022-11-15 at 6 22 35 AM

Then there are other times when you definitely want to take up the entire terminal window, like the screenshot below.
Screenshot 2022-11-15 at 6 25 40 AM

I'm wondering if it's possible to know these two times, when one is big and you want it as wide as you can get it, and when one is small and you don't need it super wide, unless you tell it?

**Comment by zhiburt** [comment]
> This is what I mean

Could you check it out?

> I'm wondering if it's possible to know these two times

Made it the most inefficient way possible.... :disappointed_relieved: : 
(I think it could be improved but currently it would just bring a little bit more mess to the code which is already not idea.... :disappointed:  ).

**Comment by fdncred** [comment]
> Could you check it out?

This looks good.
image

The coloring looks good too i think.

Did I miss this before or do we have a slight regression with `[list 0 items]`? maybe not? i'm not sure
image

Also `$nu | table -e` looks a little different now too... I think. Maybe this is right now and I'm confused because there have been other PRs landed that change the command signatures. What do you think?
image

Some seem to expand now and others do not expand
image

**Comment by zhiburt** [comment]
> Did I miss this before or do we have a slight regression with [list 0 items]? maybe not? i'm not sure

I believe it has been always the case.
Do you think we shall show it differently?

> Also $nu | table -e looks a little different now too... I think. Maybe this is right now and I'm confused because there have been other PRs landed that change the command signatures. What do you think?
> Some seem to expand now and others do not expand

Well it was explicitly set so when there's enough space for a cell to be expanded we do even if it will be the single expanded cell in a column.
I could change it so if we can't fully expand column we don't.

**Comment by fdncred** [comment]
but why in my images doesn't row 291 str camel-case expand like row 286 split-by does? what i'd prefer it to do is if there wasn't enough room it would fill in all the columns it could, within the width, and put ... in the last column. i think this is really the last item we need to deal with on this pr.

if `[list 0 items]` and `{ record 0 fields }` are normal, then let's leave that for now.

**Comment by zhiburt** [comment]
Changed it once again to a bit different logic.
Also fixed 1 issue (not sure if you noticed it but wrapping was sometimes applied to tables which is cool).

**Comment by fdncred** [comment]
let's go! thanks for this

**Pull request merged**
