### PR TITLE
Rename dataframe `describe` to `summary` so that the normal `describe` isn't overloaded

### LINKED ISSUE #6770: `describe`'s separate behaviour for dataframes and databases should be separate commands
### Related problem

_No response_

### Describe the solution you'd like

In my opinion, there is **no** reason why something as fundamental to the language as `describe` (which at the moment seems to be the *only* reliable type-checking facility in the entire language) should have a completely different type signature and functionality when its input is dataframe-type or database-type. This greatly harms the utility of `describe` and makes it much more difficult to think about or use in scripts. I strongly recommend making the dataframe and database variants into separate commands.

### Describe alternatives you've considered

_No response_

### Additional context and details

_No response_

### PR DESCRIPTION
**Pull request by webbedspace**
# Description

This closes #6770.

First of all, **yes,** I understand that the df `describe` is supposed to map to [Pandas.DataFrame.describe()](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.describe.html)! However, I strongly feel that `describe` is fundamental to the Nushell language as the (current) only real type-checking facility, and must *NOT* be overridden by anything else. A user command which uses `describe` to check input data, and which assumes `describe` outputs a string, will break if `describe` is overridden to output some other data type, and said type is used with that command. I also think the need to make Nushell's dataframe API map one-to-one to Pandas's API is kind of a fool's errand anyway given how different Nushell's language is to Python.

~~I have chosen the name `descriptives` because:~~
* ~~"Descriptive statistics" (the very specific set of stats output by df `describe`) are sometimes shortened to "descriptives" in casual speech.~~
* ~~Name is close enough in root to "describe", the Pandas name.~~
* ~~Being plural, it suggests to the user that it outputs multiple values (i.e. a table).~~
* ~~While significantly longer, this command is not the sort that necessarily requires succinctness (compared to something like `get`).~~

# User-Facing Changes

Renames `describe` (the dataframe version only) to `summary`. Since dataframes are possibly going to be moved out of the default install entirely, this is a relatively minor change in comparison.

# Tests + Formatting

Don't forget to add tests that cover your changes.

Make sure you've run and fixed any issues with these commands:

- `cargo fmt --all -- --check` to check standard code formatting (`cargo fmt --all` applies these changes)
- `cargo clippy --workspace --features=extra -- -D warnings -D clippy::unwrap_used -A clippy::needless_collect` to check that you're using the standard code style
- `cargo test --workspace --features=extra` to check that all tests pass

# After Submitting

If your PR had any user-facing changes, update [the documentation](https://github.com/nushell/nushell.github.io) after the PR is merged, if necessary. This will help us keep the docs up to date.

### CODE REVIEW

**Comment by webbedspace** [comment]
@elferherrera I request your thoughts on this proposal.

**Comment by sholderbach** [comment]
To me that sounds like a good idea, breaking the type info is more than unfortunate.
Just putting `summary` as an alternative slightly shorter name/alternative verb out there (would be the `R` function that comes closest to `df.describe()`).

**Comment by jntrnr** [comment]
`descriptives` isn't a word in English. Something like `descriptions` would work a bit better. Or maybe `identify`, if we want to use a verb that isn't `describe`

**Comment by webbedspace** [comment]
I guess I'll go with `summary` if it has a pedigree in the wild. The important thing is that the name describes the domain. Descriptive statistics are a kind of summary statistic, so I guess it tracks.

**Comment by rgwood** [comment]
Good change. `summary` sounds good to me.

**Pull request merged**
