### PR TITLE
fix: fixed typo and improved Value TypeMismatch exceptions

### PR DESCRIPTION
**Pull request by Sygmei**
# Description

This PR aims to improve `TypeMismatch` exception that occurs when comparing two values with `<`, `>`, `<=` or `>=` operators.

*Before*
image

*After*
image

This PR also bundles a small refactor for histogram forbidden column names exception, previous implementation forgot a column name in the message, to avoid this, I'm re-using the same array for checking and error display

# User-Facing Changes

Not much changes except a better and more readable exception for the user

# Tests + Formatting

Does not break any tests, formatting passes as well :)

### CODE REVIEW

**Comment by sholderbach** [comment]
Thank you very much for helping out with our rough error messages.

I think for type mismatches on operators we can also use the special variant `OperatorMismatch`

`TypeMismatch` at the moment is currently in a questionable state. I think some non-type errors got accidentally moved over to it. Furthermore there are some additional problems and duplication that I am currently working on (see #8229). But I haven't fully drawn up my battle plan to reign in the sprawl of variants.

**Comment by fdncred** [comment]
@Sygmei Are we going to be able to move forward on this or should we close this PR at this time?

**Comment by Sygmei** [comment]
@sholderbach would it be fine if I just use the proper variant, could this PR be merged without duplicating your work ?

**Comment by sholderbach** [comment]
Yeah I think improving this just based on the current state of the `ShellError` is fine. When refactoring that, we will notice the collisions anyways.

**Comment by Sygmei** [comment]
Should be ready to merge :)

**Comment by sholderbach** [comment]
Awesome, thanks!

**Pull request merged**
