### PR TITLE
Move completion code into its own crate.

### PR DESCRIPTION
**Pull request by thegedge**
This allows the completions crate to be completely decoupled from nu-cli, allowing it to be developed independently from most other nu crates.

The major change in this commit is making the completion context be a trait. Currently limited to returning a signature registry, we'll likely have to expand this as time goes on.

## Other approaches

Another approach would be to eliminate the context completely, and have the concrete `Completer` implementations receive shared (e.g., `Arc<RwLock<...>>`) instances of the things they need. This would require the caller to instantiate them though, which was outside of the scope of this PR. We can perhaps return to this idea later, once we have a dynamic registry of completers.

### CODE REVIEW

**Comment by thegedge** [comment]
@jonathandturner what do you think of this approach to decoupling?

I could also do a `dyn CompletionContext`. The context isn't really used on any hot path, so I wouldn't be worried about performance issues.

**Review by jonathandturner — APPROVED** [review]
Looks good.

As we work at this more, I think we should continue to separate rustyline from the completion engine. Maybe we only implement those traits if rustyline is detected (is that possible? not sure)

But yeah, this is good

**Comment by thegedge** [comment]
> As we work at this more, I think we should continue to separate rustyline from the completion engine. Maybe we only implement those traits if rustyline is detected (is that possible? not sure)

Agreed! There's actually only one use of rustyline in the completion engine right now, and that's for `unescape`. Honestly, I'd rather just drop that behaviour because it's weird that the completion engine can understand something that the rest of nushell cannot.

**Comment by jonathandturner** [comment]
@thegedge +1 for trait object. We can also make our own trait, so there's a trait between ours and rustyline's. Either way sounds good to me.

**Comment by gerred** [comment]
Seems like #2241 is affected by this potentially, @jonathandturner should I base my code off of this branch?

**Comment by thegedge** [comment]
This one is pretty old, @gerred . For the most part, it didn't introduce anything new, just moved the completion code into a separate crate. Since it's out of date, I think it would be best to start fresh instead of trying to rebase.

**Pull request closed without merging**
