### PR TITLE
`uniq-by` command

### PR DESCRIPTION
**Pull request by raccmonteiro**
# Description
New command `uniq-by` to get uniq results by column.

Closes https://github.com/nushell/nushell/issues/7109

# User-Facing Changes

The command `uniq-by` is new.

# Tests + Formatting
```
〉[[fruit day]; [apple monday] [apple friday] [Apple friday] [apple monday] [pear monday] [orange tuesday]] | uniq-by fruit
╭───┬────────┬─────────╮
│ # │ fruit  │   day   │
├───┼────────┼─────────┤
│ 0 │ apple  │ monday  │
│ 1 │ Apple  │ friday  │
│ 2 │ pear   │ monday  │
│ 3 │ orange │ tuesday │
╰───┴────────┴─────────╯
```

```
〉[[fruit day]; [apple monday] [apple friday] [Apple friday] [apple monday] [pear monday] [orange tuesday]] | uniq-by fruit day
╭───┬────────┬─────────╮
│ # │ fruit  │   day   │
├───┼────────┼─────────┤
│ 0 │ apple  │ monday  │
│ 1 │ apple  │ friday  │
│ 2 │ Apple  │ friday  │
│ 3 │ pear   │ monday  │
│ 4 │ orange │ tuesday │
╰───┴────────┴─────────╯
```

```
〉[[fruit day]; [apple monday] [apple friday] [Apple friday] [apple monday] [pear monday] [orange tuesday]] | uniq-by fruit -i
╭───┬────────┬─────────╮
│ # │ fruit  │   day   │
├───┼────────┼─────────┤
│ 0 │ apple  │ monday  │
│ 1 │ pear   │ monday  │
│ 2 │ orange │ tuesday │
╰───┴────────┴─────────╯
```

```
〉[[fruit day]; [apple monday] [apple friday] [Apple friday] [apple monday] [pear monday] [orange tuesday]] | uniq-by fruit -c | flatten
╭───┬────────┬─────────┬───────╮
│ # │ fruit  │   day   │ count │
├───┼────────┼─────────┼───────┤
│ 0 │ apple  │ monday  │     3 │
│ 1 │ Apple  │ friday  │     1 │
│ 2 │ pear   │ monday  │     1 │
│ 3 │ orange │ tuesday │     1 │
╰───┴────────┴─────────┴───────╯
```

```
〉[[fruit day]; [apple monday] [apple friday] [Apple friday] [apple monday] [pear monday] [orange tuesday]] | uniq-by fruit -u
╭───┬────────┬─────────╮
│ # │ fruit  │   day   │
├───┼────────┼─────────┤
│ 0 │ Apple  │ friday  │
│ 1 │ pear   │ monday  │
│ 2 │ orange │ tuesday │
╰───┴────────┴─────────╯
```

### CODE REVIEW

**Comment by webbedspace** [comment]
Does this do anything when given a plain record? Error? Return it?

**Comment by sholderbach** [comment]
Thanks for including the examples and great code reuse!
I think if you can address @webbedspace 's concern we can land this one for now.

#### Tangential rant
I think looking at both `uniq` and `uniq-by`, finally brought out what is rubbing me the wrong way with `uniq`:

`uniq` tries to follow in the footstep of the UNIX uniq and fails at that as it does not do sequential deduplication (only following duplicates are ignored vs. global uniqueness)

With the flags it does like three distinct operations:

- only letting uniques through (no flag or `-u`)
- collecting the duplicates (`-d`)
- counting the occurences of a particular value (`-c`)

For reference in `pandas` that would be three or four methods:

- [`pd.Series.unique()`](https://pandas.pydata.org/docs/reference/api/pandas.Series.unique.html#pandas.Series.unique) which does the same as our `uniq` without flag. *global* uniqueness
- [`pd.Series.value_counts()`](https://pandas.pydata.org/docs/reference/api/pandas.Series.value_counts.html) Associating all unique values with a count (in our case this flag can change the output type from list to table on `uniq`
- [`pd.Series.duplicated()`](https://pandas.pydata.org/docs/reference/api/pandas.Series.duplicated.html) Identify the entries that are duplicated (`-d`). In their case it just generates a mask. The equivalent to our option would be to filter with that `s[s.duplicated()].unique()` (and dedup again)
- [`pd.Series.drop_duplicates()`](https://pandas.pydata.org/docs/reference/api/pandas.Series.drop_duplicates.html#pandas.Series.drop_duplicates) Does the unix `uniq` style *local* deduplication. Drop consecutive duplicates.

**Comment by webbedspace** [comment]
I give my initial support for splitting off `uniq` into `duplicates` or `dups` (for `-d`) and another thing for `-u`. (I don't actually like `drop duplicates` because I don't really like `drop` subcommand naming due to `drop` itself being paired with both `skip` and `last`…)

**Comment by raccmonteiro** [comment]
I added some validations for missing columns in command parameters, and invalid columns.
image

**Comment by rgwood** [comment]
Thanks @raccmonteiro! This looks like a great PR.

I think that behaviour for single records is acceptable. I think it would also be OK to return an error.

I would support merging this now, and we can look into addressing Stefan and Leon's points separately.

**Review by sholderbach — APPROVED** [review]
Agreed!

Thanks for the good work!

**Pull request merged**
