### PR TITLE
Complete Dataframe MVP

### PR DESCRIPTION
**Pull request by elferherrera**
This PR presents a new variable for Nushell; a Dataframe. Unlike a Table or a Row (which are `Vec<Values>` and `Row<Dictionary>`), the dataframe stores all its the values in one single structure. The dataframe structure is based on a `Polars` dataframe which uses `Arrow` as the memory layout for the data.

With this new variable type, Nushell could load a very large parquet or csv file in order to do queries on the data (joins, group by, filter, etc). It could open the door for new commands that manipulate these large files.

At the moment there are two ways to create a dataframe: 

The first one using an input stream

```
echo [[a b];[1 2] [3 4] [5 6]] | dataframe
```

The second one reading a file

```
dataframe -f test.csv
```

The dataframe has a converter that converts a section of the data to a Stream of Rows that can be used for pretty printing to the terminal.

### CODE REVIEW

**Comment by fdncred** [comment]
Wow! This is some very nice work indeed. I can't wait to try it. some checks were not successful. Would you mind running these commands and cleaning up the warnings? If you do, then the PR will 'go green' and we'll be able to commit it.

Clippy
`RUSTFLAGS="-D warnings" cargo clippy --all -- -D clippy::unwrap_used`

Tests
`RUSTFLAGS="-D warnings" cargo test --all`

There's slightly different syntax if you're on Windows.

**Comment by elferherrera** [comment]
@fdncred I've tried to run both commands but I keep getting this error

```
error: failed to run custom build command for `x11 v2.18.2`
```

I've run the commands in two computers, a mac and a linux machine and in both fails. I don't know if I need something special in my configuration

**Comment by fdncred** [comment]
@elferherrera I've never seen that error. Do you have all the [pre-reqs installed](https://www.nushell.sh/book/installation.html#dependencies)? One would think you do since you're already compiling nushell.

**Comment by elferherrera** [comment]
@fdncred I managed to run the clippy and test commands using a docker image. There is a test that keeps failing (fails_with_ls_to_dir_without_permission) but I didn't touch that function. Is that normal?

**Comment by stormasm** [comment]
@elferherrera looks like your branch is "3 commits behind nushell main"; so you may want to update your branch prior to running the tests again.

**Comment by elferherrera** [comment]
@stormasm I merged this branch with master to get all commits. Let me know if this works for you

**Comment by stormasm** [comment]
@elferherrera it all works...  all tests are passing on my local machine and my dataframe command is working with local test csv files...

the reason your tests are now failing is probably because jt did a commit prior to you pulling your code and so your branch is now 1 commit behind the main branch.

I will continue to test your code as you publish new commits to the branch....

**Comment by elferherrera** [comment]
@stormasm I see what you mean. Since my lock is different to main's because I have different dependencies this will fail all the time. Now I need to see if JT is interested in this implementation

**Comment by jonathandturner** [comment]
@elferherrera - yes, I'm interested. I think to start out, this should be behind a feature flag that's not on by default, as we'll need to migrate commands over to use it. We'll also want to experiment with it a bit generally.

Can you put it behind a `dataframe` feature flag that's off by default? Once enabled, it'll enable the work you're doing.

I also need to make some time to chat with the polars creators. I've filed this issue on their repo to try to set up some time to chat with them: https://github.com/ritchie46/polars/issues/601

**Comment by elferherrera** [comment]
@jonathandturner Sure thing, let me add the feature flag to this development. 

I was also thinking of making some of the native commands to be a bit versatile. For example, the command `to csv` when it finds that the UntaggedValue is a `DatafFrame` can use the polars encoder to save to csv. 

Btw, do you think it is possible to join your chat with Ritchie? I would like to know what are his plans for `polars` as well.

**Comment by stormasm** [comment]
@jonathandturner @elferherrera After you speak with Ritchie I would (also) be curious to know what you find out... If you have some free time to communicate what you learned from the conversation that would be great ! Thanks....

**Comment by elferherrera** [comment]
@jonathandturner I tried putting the dataframe behind a feature flag and there is an issue that I don't know how to tackle. Since the variable Dataframe is in the nu-protocol, any command that does a match on Untaggedvalue always asks for the missing arm, which is Dataframe. I tried putting a feature flag as well on the missing arm, but it doesnt work. 

What would you suggest doing?

**Comment by jonathandturner** [comment]
@elferherrera - looking at the errors on CI (if you click into details in the failing tests you should be able to see them), it seems like you need to merge in the latest main with your changes.

**Comment by jonathandturner** [comment]
Had a good chat with Ritchie last night. I'll put the notes here but we might want to find a more permanent place to put them:

I wanted to chat about a few possible futures:
* DataFrame as a case of UntaggedValue (like @elferherrera is working on here)
* DataFrame as the "transport container" meaning its what holds all the values in the system. Effectively it would make the iterators between commands speak DataFrame instead

I showed Ritchie our Primitive data types and we agreed that they're a bit different than what Polars uses, including bigint, bigdecimal, and the ability to embed one table inside of another. After chatting about the limitations, it seemed to me that second possibility above seemed the more difficult by far.

I explained how the current nushell system worked to Ritchie. We agreed there's definitely performance we're not getting by not taking advantage of homogeneous data when we know that's what it is. Also true for columnar data, if the data can be made columnar.

We left it at that basically. They're willing to help us if we want to go in the Polars direction officially. I told him we wanted to experiment first before we have a good idea of what we want to do.

**Comment by elferherrera** [comment]
@jonathandturner I also think that the best option is to have a Dataframe as another UntaggedValue type. After playing around with the code I can tell the `Untagged::Row`, `Untagged::Table`, and `Untagged::Dataframe` will serve different purposes. 

I see that the first two will be very useful to print data in the terminal. Among other things, it is very easy with those types to show what number or element is wrong. The `Untagged::Dataframe` should be the main type for all type of group calculations, specially columnar operations. The other types will be very good for doing row operations, like `each`, that requires a string to be passed to the block that is going to be repeated. This will also mean that it will have to be decided if a Dataframe is a default or optional feature in nushell. 

Let us know what you decide so I can start playing with other commands and implement polars operations.

**Comment by jonathandturner** [comment]
@elferherrera - for the experiment, let's definitely go with "part of UntaggedValue, enabled with a feature flag". With that we can land it, and then start experimenting with allowing some commands to handle DataFrames as part of their functionality (`math sum` as one example)

**Comment by elferherrera** [comment]
@jonathandturner yesterday I tried to add that feature to both `nu-protocol` and `nu-commands` and I couldn't compile nushell. For example, with the crate `nu-value-ext`, in this [line](https://github.com/nushell/nushell/blob/cfee151d4e03aea6e133e0ec2b4658ac3275d283/crates/nu-value-ext/src/lib.rs#L721) it requires that all match arms are defined. However, when I compile the whole project with the `dataframe` feature enabled I get a compilation error because there is now a new UntaggedValue that Im not considering. 

I tried creating a feature for that command in its [toml](https://github.com/nushell/nushell/blob/main/crates/nu-value-ext/Cargo.toml) file, but I was having the same issue. I tried using this as well:

```
nu-protocol = { path = "../nu-protocol", version = "0.30.1" , feature=["dataframe']}
```

But this doesn't make that feature optional for the `nu-value-ext` crate.

What do you suggest I could do?

**Comment by jonathandturner** [comment]
@elferherrera if you make it a top-level feature, I think you can use the same trick we do for trash support: https://github.com/nushell/nushell/blob/main/Cargo.toml#L149-L153

**Comment by elferherrera** [comment]
@jonathandturner when you say top-level feature do you mean something like this

Added to Cargo.toml in `nu-protocol`
```
[features]
default = []
dataframe = ["polars"]
```

btw, what github actions are run when doing a PR? I cannot find them in the github actions folder

**Comment by jonathandturner** [comment]
@elferherrera - there are a few parts. What I link to is the top Cargo.toml that drives all the other sub-crates. We create a feature there for the trash, and then from there we enable the features in the subcrates. I think you can do a similar technique for dataframe support in subcrates.

**Comment by elferherrera** [comment]
@jonathandturner yeap, that did the trick. I didn't know you could nest crates this way. It has been a revelation 😄 

Let me know what you think about the dataframe

**Comment by jonathandturner** [comment]
@elferherrera - we're taking a look at the PR now.

We may wait until after the next release, which happens next week, before we land it. We haven't decided yet, but I didn't want you to worry about it if it doesn't land this week.

**Comment by elferherrera** [comment]
@jonathandturner No problem. Actually this was an MVP for the dataframe idea. I wanted to see if it was possible to have a dataframe as a new variable and how we could interact with it. If you think this PR needs to change more or add functionally for the next release, let me know.

**Comment by jonathandturner** [comment]
Thanks for the PR!

**Pull request merged**
