### PR TITLE
Removed the polars dtypes command

### PR DESCRIPTION
**Pull request by ayax79**
# Description
The polars dtype command is largerly redundant since the introduction of the schema command. The schema command also has the added benefit that it's output can be used as a parameter to other schema commands:

```nushell
[[a b]; [5 6] [5 7]] | polars into-df -s ($df | polars schema
```

# User-Facing Changes
`polars dtypes` has been removed. Users should use `polars schema` instead.

### CODE REVIEW

**Comment by sholderbach** [comment]
Breaking change label with the caveat that the plugin has not been officially released yet.

**Comment by fdncred** [comment]
I think this is fine but it's something that we'll need to point out in the release notes for anyone trying to port dfr to polars.

**Comment by ayax79** [comment]
What's the process for making sure things are in the release notes?

**Comment by fdncred** [comment]
> What's the process for making sure things are in the release notes?

No process really, just update the release notes. I think there's already one for 0.93 that some have been adding items to. I also added the pr:release-note-mention label to remind us.

**Pull request merged**
