### PR TITLE
let `to nuon` convert column names with spaces

### LINKED ISSUE #6283: `from nuon` cannot parse a table in nuon format
### Describe the bug

A table in nuon format cannot be parse by `from nuon` command. The nuon parser complains about missing columns.
```
/home/user〉docker images | from ssv | to nuon | from nuon
Error: 
  × error when parsing nuon text
   ╭─[entry #38:1:1]
 1 │ docker images | from ssv | to nuon | from nuon
   ·                                      ────┬────
   ·                                          ╰── could not parse nuon text
   ╰────

Error: 
  × error when parsing
   ╭────
 1 │ [[REPOSITORY, TAG, IMAGE ID, CREATED, SIZE]; ["bitnami/kafka", "latest", "691acc2203ec", "11 months ago", "585MB"], ["bitnami/zookeeper", "latest", "d91e539be199", "11 months ago", "468MB"], ["neo4j", "latest", "539db0bbdf5e", "12 months ago", "571MB"]]
   ·                                              ──────────────────────────────────┬──────────────────────────────────
   ·                                                                                ╰── Missing columns.
   ╰────

```

### How to reproduce

1. Runt he following command
```nu
docker images | from ssv | to nuon | from nuon  
```

### Expected behavior

The same result as in
```nu
docker images | from ssv 
```

### Screenshots

_No response_

### Configuration

〉version | transpose key value | to md --pretty                                                                                                                                                                                                  08/10/2022 10:28:13 AM
| key                | value                                       |
| ------------------ | ------------------------------------------- |
| version            | 0.66.3                                      |
| branch             |                                             |
| commit_hash        |                                             |
| build_os           | linux-x86_64                                |
| build_target       | x86_64-unknown-linux-gnu                    |
| rust_version       | rustc 1.64.0-nightly (1b57946a4 2022-08-03) |
| rust_channel       | nightly-x86_64-unknown-linux-gnu            |
| cargo_version      | cargo 1.64.0-nightly (85b500cca 2022-07-24) |
| pkg_version        | 0.66.3                                      |
| build_time         | 2022-08-04 17:07:04 +02:00                  |
| build_rust_channel | release                                     |
| features           | default, trash, which, zip                  |
| installed_plugins  |                                             |

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by merelymyself**
# Description

Fixes #6283.

# Tests

Make sure you've done the following:

- [ ] Add tests that cover your changes, either in the command examples, the crate/tests folder, or in the /tests folder.
- [ ] Try to think about corner cases and various ways how your changes could break. Cover them with tests.
- [ ] If adding tests is not possible, please document in the PR body a minimal example with steps on how to reproduce so one can verify your change works.

Make sure you've run and fixed any issues with these commands:

- [ ] `cargo fmt --all -- --check` to check standard code formatting (`cargo fmt --all` applies these changes)
- [ ] `cargo clippy --workspace --features=extra -- -D warnings -D clippy::unwrap_used -A clippy::needless_collect` to check that you're using the standard code style
- [ ] `cargo test --workspace --features=extra` to check that all the tests pass

### CODE REVIEW

**Comment by kubouch** [comment]
Does it wrap _all_ column names in quotes? I'm thinking maybe we want to wrap them only if they have a space in them (to keep the file size down).

**Comment by kubouch** [comment]
Actually, looking at the record case, it adds the quotes to everything so I think we're good to merge. Thanks!

We might keep the optional quotes in mind and do it later, if necessary. I suspect the file size impact of the additional quotes shouldn't be too big but might be significant in deeply nested data.

**Comment by fdncred** [comment]
ya, i'd prefer to only use quotes where needed. the great thing about Nuon is that it doesn't have to be compliant with json, otherwise it would just be json. I'd use bare words wherever we can.

**Comment by kubouch** [comment]
Yeah, I agree. But since we already automatically quote in records, I thought we could merge it.

We would accept a PR that doesn't quote if not necessary and it should include both tables and records.

**Pull request merged**
