### PR TITLE
nu-explore/ Add handlers for HOME/END keys

### LINKED ISSUE #9665: Add Home & End key functionality to `explore`
### Related problem

It would be nice to be able to go to the first and last row of a large dataset in explore using the KeyCode::Home and KeyCode::End key functionality.

### Describe the solution you'd like

Home goes to start of data
End goes to end of data

### Describe alternatives you've considered

I tried adding this but it didn't work
```rust
    pub fn end_row(&mut self) -> bool {
        self.y.set_window_at(self.y.end())
    }

    pub fn home_row(&mut self) -> bool {
        self.y.set_window_at(0)
    }
```
and
```rust
            KeyCode::End => {
                self.cursor.end_row();

                info.status = Some(Report::info("END"));

                Some(Transition::Ok)
            }
            KeyCode::Home => {
                self.cursor.home_row();

                info.status = Some(Report::info("TOP"));

                Some(Transition::Ok)
            }
```

### Additional context and details

@zhiburt Would you mind looking into this please?

### PR DESCRIPTION
**Pull request by zhiburt**
close #9665

It could be good to run it though and see if it does what indented.
(I did but cause there's  no test coverage for it it's better to recheck)

PS: Surely... this cursor logic much more complex then it shall be ... the method names .... 

cc: @fdncred

### CODE REVIEW

**Comment by fdncred** [comment]
No wonder I couldn't figure it out. Thanks!

Here's a simple test that I could not get it to work with. Not sure why. Even in release it was super painfully slow to do anything with only 1336 files.
``
ls crates/**/* | explore
```

Both `input listen` and `keybindings listen` "hear" home and end properly so I'm not sure what's going on. I'm on Windows testing.

**Comment by zhiburt** [comment]
> Here's a simple test that I could not get it to work with.

Hmmm; works for me instantly.
I'll try it on windows a bit later.

**Comment by zhiburt** [comment]
But maybe you in `<edit>` mode?
These keys are not supported there. (not sure if they shall)

**Comment by fdncred** [comment]
works great now! thanks, appreciate your help!

**Pull request merged**
