### PR TITLE
Use match_indices: None for all suggestions

### PR DESCRIPTION
**Pull request by ysthakur**
# Description

This PR accompanies https://github.com/nushell/reedline/pull/798, by adding `match_indices: None` to every created `Suggestion`. I didn't bother actually computing the right match indices for now, since that would require bigger changes. This just keeps Nushell from breaking.

If you want to review this, you can add the following to the `[patch.crates.io]` section in Cargo.toml:
```
reedline = { git = "https://github.com/ysthakur/reedline", branch = "fuzzy-select-underline" }
```

# User-Facing Changes

None, if all goes well. User-facing changes would come in a later PR.

# Tests + Formatting

# After Submitting

### CODE REVIEW

**Comment by sholderbach** [comment]
@ysthakur  what is the status on this pair of PRs? Do you want to ship this with the upcoming release?

**Comment by ysthakur** [comment]
@sholderbach I was going to say we could merge them right now, but I just realized that they don't properly handle Unicode. I'd like to make the suggestion highlighting thing iterate over grapheme clusters instead of bytes. Since this isn't a change visible to users, I'd prefer to push it to the next release.

**Comment by sholderbach** [comment]
OK, no problem.
For the library users using grapheme clusters may be a bit unexpected compared to byte indices that most of the standard library functions provide, but I know we operate on them for most of our internal work.

**Comment by ysthakur** [comment]
@sholderbach Oh yeah, I meant that users would still be able to pass in byte indices, but when actually highlighting, we can iterate over the graphemes, and if even one of the bytes inside that grapheme was matched, we highlight the entire grapheme. That approach actually fixes https://github.com/nushell/nushell/issues/11916:

image

(just noticed a minor bug while taking that screenshot: the typed text is technically empty, but the first character of those suggestions is highlighted because the user's typed in `"`, even though it should be stripped. I'll make an issue for it later, could be a good first issue)

**Comment by ysthakur** [comment]
> what is the status on this pair of PRs? Do you want to ship this with the upcoming release?

@sholderbach I think they're ready to go now!

**Comment by ysthakur** [comment]
Closing because https://github.com/nushell/nushell/pull/13409 should make this unnecessary

**Pull request closed without merging**
