### PR TITLE
Added tests for non-utf8 paths.

### PR DESCRIPTION
**Pull request by merelymyself**
# Description

Title. I also removed an unnecessary space from nu-path's cargo.toml that was bugging me.

# Tests

Make sure you've run and fixed any issues with these commands:

- [x] `cargo fmt --all -- --check` to check standard code formatting (`cargo fmt --all` applies these changes)
- [x] `cargo clippy --all --all-features -- -D warnings -D clippy::unwrap_used -A clippy::needless_collect` to check that you're using the standard code style
- [x] `cargo build; cargo test --all --all-features` to check that all the tests pass

### CODE REVIEW

**Comment by kubouch** [comment]
I think what you're testing are non-ASCII UTF-8 paths? Non-utf8 paths would contain bytes not decodable as unicode but the paths in your tests seem to be decodable.

I think it's valuable to add tests for paths with weird characters but maybe they shouldn't be called non-utf-8 paths. I think that's a different category.

**Comment by merelymyself** [comment]
@kubouch - whoops, you were right. 

Is this new commit correct? It uses `from_wide` from `std::os::windows::ffi::OsStrExt` to get a non-UTF8 OsString, or at least I believe that's how it works.

**Comment by kubouch** [comment]
@merelymyself I'm not sure. I think you just created UTF-16 Windows paths which are still convertible to a valid string. The purpose of the tests is to test the case when the path cannot be represented by a valid UTF-8 string (that is, [`path_buf.to_str()`](https://doc.rust-lang.org/std/path/struct.PathBuf.html#method.to_str) would yield `None`).

In Nushell, we assume all paths are valid UTF-8 strings and fail silently if not, so we don't really support paths not representable by UTF-8 strings. That's why we didn't finish testing it. So for now, we're fine skipping the tests, but if you still want to dig deeper, go ahead! We can also keep the tests for weird non-ASCII characters you added earlier.

**Comment by merelymyself** [comment]
@kubouch I see, thanks for the explanation! I'll definitely try to dig deeper.

**Pull request closed without merging**
