### PR TITLE
New xml format

### PR DESCRIPTION
**Pull request by NotLebedev**
# Description

Changes old `from xml` `to xml` data formats. See #7682 for reasoning behind this change.
Output is now a series of records with `tag`, `attributes` and `content` fields.

Old:
image
New:
image

# User-Facing Changes

New output/input format, better error handling for `from xml` and `to xml` commands.

# Tests + Formatting

Don't forget to add tests that cover your changes.

Make sure you've run and fixed any issues with these commands:

- `cargo fmt --all -- --check` to check standard code formatting (`cargo fmt --all` applies these changes)
- `cargo clippy --workspace -- -D warnings -D clippy::unwrap_used -A clippy::needless_collect` to check that you're using the standard code style
- `cargo test --workspace` to check that all tests pass

# After Submitting

If your PR had any user-facing changes, update [the documentation](https://github.com/nushell/nushell.github.io) after the PR is merged, if necessary. This will help us keep the docs up to date.

### CODE REVIEW

**Comment by rgwood** [comment]
I'm excited for this PR. XML has been a weak spot for a long time.

**Comment by fdncred** [comment]
I'd still vote to re-run the CI and land this when it's green. It's better than what we have now.

**Comment by jntrnr** [comment]
Seconding @fdncred. I vote we should land this, too.

**Comment by rgwood** [comment]
This should get mentioned as a breaking change/new feature in the 0.77 blog post. @NotLebedev do you have time to write that up today or would you like someone else to? https://github.com/nushell/nushell.github.io/pull/800

**Comment by NotLebedev** [comment]
> This should get mentioned as a breaking change/new feature in the 0.77 blog post. @NotLebedev do you have time to write that up today or would you like someone else to? [nushell/nushell.github.io#800](https://github.com/nushell/nushell.github.io/pull/800)

Yes I have time. Will do shortly.

**Pull request merged**
