### PR TITLE
Dependency update: update reqwest, csv version

### PR DESCRIPTION
**Pull request by WindSoilder**
# Description

Relative: https://github.com/nushell/nushell/issues/8060

So atoi, base64 won't be duplicated

# User-Facing Changes

_(List of all changes that impact the user experience here. This helps us keep track of breaking changes.)_

# Tests + Formatting

Don't forget to add tests that cover your changes.

Make sure you've run and fixed any issues with these commands:

- `cargo fmt --all -- --check` to check standard code formatting (`cargo fmt --all` applies these changes)
- `cargo clippy --workspace -- -D warnings -D clippy::unwrap_used -A clippy::needless_collect` to check that you're using the standard code style
- `cargo test --workspace` to check that all tests pass

# After Submitting

If your PR had any user-facing changes, update [the documentation](https://github.com/nushell/nushell.github.io) after the PR is merged, if necessary. This will help us keep the docs up to date.

### CODE REVIEW

**Comment by sholderbach** [comment]
Based on the diff in the `Cargo.lock` they still specify their version so there is still a duplicate somewhere. It might be that this duplication doesn't affect the base `cargo build` anymore which already would be a slight improvement but for the CI slog it doesn't save us yet.

**Comment by WindSoilder** [comment]
Oh, you're right, I'll try to look into it more

**Comment by WindSoilder** [comment]
It seems that the atoi duplicate comes from nu_plugin_query(the [scraper](https://github.com/causal-agent/scraper/blob/master/Cargo.toml#L18) repo) and dataframe feature([arrow2](https://github.com/jorgecarleitao/arrow2/blob/main/Cargo.toml#L72) repo)

**Comment by WindSoilder** [comment]
Will close the pr for now, it may takes a long time to update these(maybe)

**Pull request closed without merging**
