### PR TITLE
Add 'number' command for enumeration

### PR DESCRIPTION
**Pull request by jntrnr**
# Description

This adds a `number` command that will enumerate the input, and add an `index` and `item` record for each item. The `index` is the number of the item in the input stream, and `item` is the original value of the item.

```
> ls | number | get 14
╭───────┬────────────────────────────╮
│ index │ 14                         │
│       │ ╭──────────┬─────────────╮ │
│ item  │ │ name     │ crates      │ │
│       │ │ type     │ dir         │ │
│       │ │ size     │ 832 B       │ │
│       │ │ modified │ 2 weeks ago │ │
│       │ ╰──────────┴─────────────╯ │
╰───────┴────────────────────────────╯
```

# User-Facing Changes

This adds a `number` command.

# Tests + Formatting

Don't forget to add tests that cover your changes.

Make sure you've run and fixed any issues with these commands:

- `cargo fmt --all -- --check` to check standard code formatting (`cargo fmt --all` applies these changes)
- `cargo clippy --workspace -- -D warnings -D clippy::unwrap_used -A clippy::needless_collect` to check that you're using the standard code style
- `cargo test --workspace` to check that all tests pass

# After Submitting

If your PR had any user-facing changes, update [the documentation](https://github.com/nushell/nushell.github.io) after the PR is merged, if necessary. This will help us keep the docs up to date.

### CODE REVIEW

**Comment by fdncred** [comment]
This is an interesting take on the `--numbered` parameter we have in commands. It's more nushell-y to me.

With this:
```
> ls | number | each {|r| {idx: $r.index item: $r.item.name}}
╭────┬─────┬───────────────────────╮
│  # │ idx │         item          │
├────┼─────┼───────────────────────┤
│  0 │   0 │ CODE_OF_CONDUCT.md    │
│  1 │   1 │ CONTRIBUTING.md       │
│  2 │   2 │ Cargo.lock            │
│  3 │   3 │ Cargo.toml            │
│  4 │   4 │ Cross.toml            │
│  5 │   5 │ LICENSE               │
│  6 │   6 │ README.md             │
│  7 │   7 │ README.release.txt    │
│  8 │   8 │ assets                │
│  9 │   9 │ benches               │
│ 10 │  10 │ build-all-maclin.sh   │
```
vs this:
```
> ls | each --numbered {|r| {idx: $r.index item: $r.item.name}}
╭────┬─────┬───────────────────────╮
│  # │ idx │         item          │
├────┼─────┼───────────────────────┤
│  0 │   0 │ CODE_OF_CONDUCT.md    │
│  1 │   1 │ CONTRIBUTING.md       │
│  2 │   2 │ Cargo.lock            │
│  3 │   3 │ Cargo.toml            │
│  4 │   4 │ Cross.toml            │
│  5 │   5 │ LICENSE               │
│  6 │   6 │ README.md             │
│  7 │   7 │ README.release.txt    │
│  8 │   8 │ assets                │
│  9 │   9 │ benches               │
│ 10 │  10 │ build-all-maclin.sh   │
```

**Review by sholderbach — APPROVED** [review]
Don't see any gotchas with the code. Also more in the `enumerate` camp, but happy either way.

**Comment by hustcer** [comment]
I like the name `enumerate`, It's quite familiar for coders, and `number` was typically used as a noun, especially for non-native English speakers.

**Comment by jntrnr** [comment]
I'll switch to `enumerate` and land.

**Comment by rgwood** [comment]
Is it just me or is the `index` column a bit magical? It's surprising that it shows up as `#` here:

```
〉[a, b, c] | enumerate
╭───┬──────╮
│ # │ item │
├───┼──────┤
│ 0 │ a    │
│ 1 │ b    │
│ 2 │ c    │
╰───┴──────╯
```

**Comment by fdncred** [comment]
Yes, it is a bit magical. It's in the design of tables. If you have a column named `index` it puts that in the `#` column. Which enables you to do things like this. But I think there's a hole in the logic for when you have the table indexes turned off. I can't remember what it does in that situation.
```
[[index item]; [zan 1] [jayna 2] [wonder-twins activate]] 
╭──────────────┬──────────╮
│            # │   item   │
├──────────────┼──────────┤
│          zan │        1 │
│        jayna │        2 │
│ wonder-twins │ activate │
╰──────────────┴──────────╯
```

**Comment by sholderbach** [comment]
The whole index column thing was a TIL feature well into my core team career, and I have to say I so far never felt the need to rely on it and only noticed it in gotchas of issues...

**Comment by fdncred** [comment]
It's a little half-baked. You can't use the "row headers" as indexes. Like you can't do this.
```
[[index item]; [zan 1] [jayna 2] [wonder-twins activate]] | get zan
```
You'd think you should be able to do that but you have to do a `| get 0`.

I'm not an avid user of the magical-index-value but I think it's a cool feature. I don't think there's another way to create row headers other than this. I mean, you can transpose, but that doesn't count because it'll still have the `#` column.

If we did get rid of it, I'd like there to be a substitute for making row headers. Even if it's `| update '#' {|r| $r ... }`. Right now I don't think you can update the `#` column.

**Comment by rgwood** [comment]
Am I correct in thinking that the magical-index-column feature is purely for providing more control over how tables are displayed? If so, maybe adding a flag to `table` that controls whether to show the `#` column would be an adequate replacement.

I think I would vote to remove the feature even without a replacement, though.

**Comment by fdncred** [comment]
We have a config point that already disables index display in tables.

**Comment by rgwood** [comment]
OK. In that case, I guess it would be possible to set `index_mode: never` and then add a column explicitly named `#` to put whatever you want in that column.

I suspect I don't fully understand the motivation for the magical-index-column behaviour. I guess it lets users make ad-hoc tweaks to row indexes but that doesn't seem like an especially compelling use case to me.

**Comment by fdncred** [comment]
Technically, you can do this:
```
$env.config.table.index_mode = "never"
ls | enumerate | flatten | upsert '#' {|r| $r.index} | roll right
```
However, you lose the LS_COLORS coloring. With that in mind, I'd rather just make the # column editable versus this hack. There'd probably have to be some other changes too because we allow that column to be colored with a configured color with `row_index` and I think the header alignment is different. I'm not sure it's worth messing with.

**Pull request merged**
