### PR TITLE
Attempts to add a command that checks if nushell is running with admin priveleges

### LINKED ISSUE #5689: Add ability to check if nushell is running with administrator privileges
### Related problem

I'm currently working on improving my custom nushell prompt but I realized there is no way to check if nushell is running with administrator privileges.

### Describe the solution you'd like

An an environment variable (in `$env`) that tells you if nushell is running with administrator privileges.

### Describe alternatives you've considered

_No response_

### Additional context and details

_No response_

### PR DESCRIPTION
**Pull request by merelymyself**
# Description

Title. Fixes #5689.

# Tests

Make sure you've run and fixed any issues with these commands:

- [x] `cargo fmt --all -- --check` to check standard code formatting (`cargo fmt --all` applies these changes)
- [x] `cargo clippy --workspace --features=extra -- -D warnings -D clippy::unwrap_used -A clippy::needless_collect` to check that you're using the standard code style
- [x] `cargo test --workspace --features=extra` to check that all the tests pass

### CODE REVIEW

**Comment by rgwood** [comment]
Thanks for the PR!

We're trying to be a little more cautious about bringing new dependencies into Nushell. A few questions:
- What kind of research did you do for the `is-root` crate? How confident are you that it's secure, well-supported, and lean?
- Devil's advocate: Would this make more sense as a plugin, or do you think it needs to be built in to Nu?

**Comment by fdncred** [comment]
My vote would be to build it in but taking a quick look from my phone, it doesn't seem well supported. On the plus side, the crate may be small enough to just be absorbed. It does call the windows api for the windows part too. Not exactly sure how to proceed. 

IMO, I do think we need something to let users know when they're in admin/root mode though.

**Comment by rgwood** [comment]
I looked through the is_root source and it seems OK. I’d be OK merging this with a few small tweaks:

- priveleges->  privileges spelling fix
- might be good to clarify how this works on *nix in the description (“administrator” isn’t commonly used on *nix, “root” is)

**Comment by merelymyself** [comment]
Thanks for the suggestions @rgwood !

**Comment by fdncred** [comment]
@merelymyself it would be nice to have some documentation in the book about this functionality too. let's try it out. thanks!

**Pull request merged**
