### PR TITLE
Revert 8cadc5a4

### PR DESCRIPTION
**Pull request by thegedge**
Fixes https://github.com/nushell/nushell/issues/1177

Not sure the specifics, but `popen.wait()` doesn't behave nicely with a terminal resize, whereas `popen.poll()` is fine.

### CODE REVIEW

**Comment by thegedge** [comment]
Looking for others to verify this PR fixes the issue /cc @coolshaurya @jonathandturner

**Comment by coolshaurya** [comment]
Yep, this PR fixes #1177. 
 
But doing cargo test on my machine gives - 

```sh
failures:

---- commands::classified::external::tests::identifies_command_failed stdout ----
Error: ShellError { error: Diagnostic(ShellDiagnostic { diagnostic: Diagnostic { severity: Error, code: None, message: "Command not found", labels: [Label { span: Span { start: 0, end: 0 }, message: Some("command not found"), style: Primary }] } }), cause: None }
thread 'commands::classified::external::tests::identifies_command_failed' panicked at 'assertion failed: `(left == right)`
  left: `1`,
 right: `0`: the test returned a termination value with a non-zero status code (1) which indicates a failure', src/libtest/lib.rs:196:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace.


failures:
    commands::classified::external::tests::identifies_command_failed

test result: FAILED. 41 passed; 1 failed; 0 ignored; 0 measured; 0 filtered out

error: test failed, to rerun pass '--lib'
```
the relevant code in `src/commands/classified/external.rs` is - 

```
 385   │     async fn failure_run() -> Result<(), ShellError> {
 386   │         let cmd = external("fail");
 387   │ 
 388   │         let mut ctx = Context::basic().expect("There was a problem creating a basic context.");
 389   │         let stream = run_external_command(cmd, &mut ctx, None, false)
 390   │             .await?
 391   │             .expect("There was a problem running the external command.");
 392   │ 
 393   │         match read(stream.into()).await {
 394   │             Some(Value {
 395   │                 value: UntaggedValue::Error(_),
 396   │                 ..
 397   │             }) => {}
 398   │             None | _ => panic!("Command didn't fail."),
 399   │         }
 400   │ 
 401   │         Ok(())
 402   │     }
 403   │ 
 404   │     #[test]
 405   │     fn identifies_command_failed() -> Result<(), ShellError> {
 406   │         block_on(failure_run())
 407   │     }
```

**Comment by thegedge** [comment]
@coolshaurya yeah, I had to build/test with `--workspace`. We've added some custom commands so that our tests don't depend on potentially non-existent external commands :)

**Comment by andrasio** [comment]
@coolshaurya @thegedge Sorry about that. You'd need to run as `cargo test --all --features stable,nu-dummies` now. (Notice the nu-dummies feature)

/ref @jonathandturner @wycats

**Comment by coolshaurya** [comment]
doing `cargo test --all --features "stable,nu-dummies"` passes all tests :smiley:

**Comment by andrasio** [comment]
> doing `cargo test --all --features "stable,nu-dummies"` passes all tests 😃

From latest master, you can now just keep running tests like before. `nu-dummies` in there is no longer necessary.

**Comment by jonathandturner** [comment]
Great, thanks all!

**Pull request merged**
