### PR TITLE
remove panic from `lpad` and `rpad`, change truncation behaviour for `lpad`

### PR DESCRIPTION
**Pull request by merelymyself**
# Description

Related: #6488. At the same time, I changed how truncation works (allowing for truncation from both ends now) and also added in a check against negative numbers (previously, nushell would just crash if one specified a negative length).

# Tests

Make sure you've done the following:

- [ ] Add tests that cover your changes, either in the command examples, the crate/tests folder, or in the /tests folder.
- [ ] Try to think about corner cases and various ways how your changes could break. Cover them with tests.
- [ ] If adding tests is not possible, please document in the PR body a minimal example with steps on how to reproduce so one can verify your change works.

Make sure you've run and fixed any issues with these commands:

- [ ] `cargo fmt --all -- --check` to check standard code formatting (`cargo fmt --all` applies these changes)
- [ ] `cargo clippy --workspace --features=extra -- -D warnings -D clippy::unwrap_used -A clippy::needless_collect` to check that you're using the standard code style
- [ ] `cargo test --workspace --features=extra` to check that all the tests pass

### CODE REVIEW

**Comment by sholderbach** [comment]
I am honenstly not sure if the symmetry to `trim` really helps in the real world. Before the direction was explicit with `lpad` or `rpad`. With `trim` the default usecase has its meaning and is probably also the most common (i.e. remove whitespace to get just useful text) 
Now I would have to remember that this is implicit a left pad and else I need to use a separate flag I have to remember.

But catching the panic is definitely great!

**Comment by merelymyself** [comment]
@fdncred , thoughts? Personally, I'm ambivalent about condensing it or not.

**Comment by fdncred** [comment]
I'm kind of on the fence about this. I'm not sure if it's a good idea now that i see it and think about it more. I could be convinced in either direction.

**Comment by jntrnr** [comment]
I kinda think `pad left` and `pad right` would read a bit better. I don't think I'd assume left padding by default as a reader, without looking up in the docs.

**Comment by fdncred** [comment]
@merelymyself following jt's suggestion, i think something like this makes me feel better about the command. `blah | str pad left -c '0' -l 5` and `str pad right -c '0' -l 5`. I think jt is hitting on what makes me a bit ambivalent, which is it's not super intuitive to have a bunch of params like -a -b -c -d -e -f, etc. what do you think?

**Comment by merelymyself** [comment]
Do you mean having them as subcommands, but more readable? Sounds good to me!

**Comment by merelymyself** [comment]
Testing it out, that seems to be causing problems for the completer. Maybe I'll just put in the check and change truncation in this PR, and do the renaming in a different one when I work it out how to make it work nicely with the completer.

**Comment by sholderbach** [comment]
Thanks @merelymyself, sad that the completer has a problem there. I also agree with JT's suggestion. But lets land this first.

**Pull request merged**
