### PR TITLE
Uniformize usage() and extra_usage() message ending for commands helper.

### PR DESCRIPTION
**Pull request by jaudiger**
# Description

Working on uniformizing the ending messages regarding methods usage() and extra_usage(). This is related to the issue https://github.com/nushell/nushell/issues/5066 after discussing it with @jntrnr 

# User-Facing Changes

None.

# Tests + Formatting

Don't forget to add tests that cover your changes.

Make sure you've run and fixed any issues with these commands:

- `cargo fmt --all -- --check` to check standard code formatting (`cargo fmt --all` applies these changes)
- `cargo clippy --workspace -- -D warnings -D clippy::unwrap_used -A clippy::needless_collect` to check that you're using the standard code style
- `cargo test --workspace` to check that all tests pass

# After Submitting

If your PR had any user-facing changes, update [the documentation](https://github.com/nushell/nushell.github.io) after the PR is merged, if necessary. This will help us keep the docs up to date.

### CODE REVIEW

**Review by sholderbach — COMMENTED** [review]
Thanks for doing the tedious work! Much nicer for the written documentation on the website and in the help. Only downside would be that it requires an additional character column in the completion menu when showing the description.

**Comment by jaudiger** [comment]
I’m opened to any suggestions. If you have something in mind that could help to uniformize the descriptions while also resolving the issue you mentioned with the column, please let me know.

**Comment by fdncred** [comment]
wow! what a pain to do all this. thanks so much!

**Review by rgwood — APPROVED** [review]
Thanks! It's nice to be consistent about this kind of thing.

I don't think the extra character in the completion menu is a deal-breaker.

**Pull request merged**
