### PR TITLE
Exclude ./... from expansion

### PR DESCRIPTION
**Pull request by elferherrera**
# Description

There is peculiar case with golang and the path `./...` which shouldn't be expanded. The proposed solution is to create a list of excluded cases where dot expansion shouldnt happen. 

Im wondering if this list should be configurable, meaning that it should be in the config file

# Tests

Make sure you've done the following:

- [ ] Add tests that cover your changes, either in the command examples, the crate/tests folder, or in the /tests folder.
- [ ] Try to think about corner cases and various ways how your changes could break. Cover them with tests.
- [ ] If adding tests is not possible, please document in the PR body a minimal example with steps on how to reproduce so one can verify your change works.

Make sure you've run and fixed any issues with these commands:

- [ ] `cargo fmt --all -- --check` to check standard code formatting (`cargo fmt --all` applies these changes)
- [ ] `cargo clippy --workspace --features=extra -- -D warnings -D clippy::unwrap_used -A clippy::needless_collect` to check that you're using the standard code style
- [ ] `cargo test --workspace --features=extra` to check that all the tests pass

### CODE REVIEW

**Comment by kubouch** [comment]
Shouldn't we disable all path expansion for externals? I'm not much in favor of hard-coding some special cases like this (e.g., `...` and `././...` would still expand).

**Comment by elferherrera** [comment]
Should it be optional? I want to remove dot expansion, but I don't know why it was added. Maybe someone is using it

**Comment by elferherrera** [comment]
@jntrnr do you remember why you added dot expansion for externals?

**Comment by elferherrera** [comment]
@kubouch @fdncred let's test externals without dot expansion to see how they feel

**Comment by kubouch** [comment]
I think originally, there was a full expansion (like also `..` etc.) but it broke some externals. So we reduced it only to Nushell-specific expansions: `...` and `~`. I'd propose we remove the `...` expansion but still keep the `~` expansion.

**Pull request merged**
