### PR TITLE
Implement netrc support for `http get`

### LINKED ISSUE #12181: .netrc support for http auth
### Related problem

I am trying to use `http get` to work with an API. I have credentials stored in my `.netrc` file, as that is supported by a wide variety of tools including `curl` and `xh`. I want to use `http get` instead of these tools both to keep everything nushell-native and to benefit from automatic content type detection, but it can't read my `.netrc` file.

### Describe the solution you'd like

`http get` should parse the `~/.netrc` file for authentication, either automatically as `xh` does, or upon request with a `-n`/`--netrc` flag as `curl` does. It should also support using the `NETRC` env var to override the location of the netrc file as `xh` does. If netrc support is opt-in, then it may want to parse the `.netrc` file when authorization is required as `wget` does (the manpage is not clear on the exact conditions here, I assume this means when the initial request gets a 401 Unauthorized response). If it parses automatically it should support a `--no-netrc` flag as `curl` and `wget` do.

### Describe alternatives you've considered

_No response_

### Additional context and details

This was previously requested in #8874. That issue was closed as not planned after reading https://daniel.haxx.se/blog/2022/05/31/netrc-pains/, a blog post about how the netrc format is unspecified. However, that blog post says that curl would be changing its implementation starting in version 7.84.0 to match wget, where if you double-quote the password then you can backslash-escape spaces and quotes. This seems like reasonable behavior to match, especially since spaces in passwords is sufficiently rare that most users won't run into this. And I don't think anyone is really going to complain about a new netrc parser matching curl's current behavior.

`xh` has [their own implementation of a netrc parser](https://github.com/ducaale/xh/blob/f50f10c87c1c92c487a57561a8a1ed64eb5ed5ab/src/netrc.rs) which references curl's implementation from v7.78.0. It has a comment which says it's too specialized to publish as a crate but could be copy&pasted into another project. This could be used as the basis for a parser in nushell, modified to support wget's quoted passwords, and perhaps even contributed back as an improvement to `xh`.

### PR DESCRIPTION
**Pull request by nils-degroot**
- closes #12181

# Description

This PR allows nushell's `http get` command to use credentials stored in the [netrc file](https://www.gnu.org/software/inetutils/manual/html_node/The-_002enetrc-file.html). The implementation for the parser is taken from [xh](https://github.com/ducaale/xh/blob/f50f10c87c1c92c487a57561a8a1ed64eb5ed5ab/src/netrc.rs), this could be replaced at a later stage with a purpose made crate.

Currently I only implemented it for the `get` command, once the structure is approved I'll add it to the other http methods as well.

# User-Facing Changes

# Tests + Formatting

# After Submitting

### CODE REVIEW

**Comment by fdncred** [comment]
Is netrc a valid thing for Windows? I've never heard of it there.

**Comment by fdncred** [comment]
We talked about this in our meeting on Wednesday. IIRC, the consensus was that we'd probably support this functionality if the netrc parsing was moved to a crate. Parsing this file is not something we want to maintain.

**Comment by nils-degroot** [comment]
That fair, so lets close this for now?

**Comment by fdncred** [comment]
> That fair, so lets close this for now?

We can close it, or you can find a netrc parsing crate to change this PR. The choice is yours.

**Comment by nils-degroot** [comment]
I recently made a crate for this because I tough the existing crates weren't that well put together, but I don't feel comfortable adding it here yet. I might open another PR for it at a later point.

**Comment by fdncred** [comment]
Sounds good. Thanks for trying to make nushell better. Sorry we couldn't make it happen this time. Maybe next time. :-)

**Pull request closed without merging**
