### PR TITLE
Add `rm_always_trash` option to config

### LINKED ISSUE #941: Should `rm` recycle by default?
from reddit:

"Wouldn't it be prudent to invert the behavior, rm sends to the trash by default and rm --no-backsies does a non-recoverable delete?"

### PR DESCRIPTION
**Pull request by filalex77**
Close #941.

Also:
- add `--permanent` flag to `rm`
  So users can override the behavior of `rm_always_trash` option.

### CODE REVIEW

**Comment by Kelli314** [comment]
It looks like `-p` and `-t` can be specified in tandem which could lead to confusing results. We should make them mutually exclusive.

**Comment by filalex77** [comment]
@Kelli314 Great idea! Is there a way to do this with the `Signature`, or should we just `return` an `Error`?

**Comment by Kelli314** [comment]
https://github.com/nushell/nushell/blob/master/crates/nu-protocol/src/signature.rs#L172

It doesn't look like there's currently an option to set mutually exclusive switches.

**Comment by jonathandturner** [comment]
@Kelli314 - for now, you could workaround the limitation of not having mutually exclusive switches. You could check for the existence of both switches, and if both are there return an error message.

**Comment by filalex77** [comment]
@jonathandturner What kind of `ShellError` constructor should be used for this? Is something like `ShellError::syntax_error("--permanent and --trash are mutually exclusive")` fine? How can spans be added to it? I'm not really familiar with error construction in Nu.

**Comment by thegedge** [comment]
I think syntax errors are more for errors during parse.

Most of the times you can't go wrong with just a simple `ShellError::labeled_error` 🙂

```rust
ShellError::labeled_error(
  "only one of --permanent and --trash can be used",
  "conflicting flags",  // not sure a nice, short way to describe this label
  name_tag
)
```

Note the difference in my message too. I've recently taken some tech writing lessons and generally it's best to opt for simpler words. "only one of" is far simpler to understand than "mutually exclusive" 🙂

**Comment by jonathandturner** [comment]
Looks good!

**Pull request merged**
