### PR TITLE
add `like` and `not-like` operators as synonyms for the regex operators `=~` and `!~`

### LINKED ISSUE #13261: Add 'like' operator (clone of =~)
### Related problem

The `~` character is awkward to write on certain keyboards (I need to hit three keys to insert it). Also, I often confuse the order and write `~=` instead of `=~`, but maybe that's just my brain that's wired wrong.

### Describe the solution you'd like

In SQL languages the `like` operator is used. I propose that `like` could be used on top of `=~`. The operators should work exactly the same, it's just another way to write it. An operator-alias if you like. The syntax would be very SQL-like.

Example: `ls | where name like .bash` could be used instead of `ls | where name =~ .bash`

### Describe alternatives you've considered

_No response_

### Additional context and details

_No response_

### PR DESCRIPTION
**Pull request by fdncred**
# Description

This PR adds `like` as a synonym for `=~` and `not-like` as a synonym for `!~`. This is mainly a quality-of-life change to help those people who think in sql.

image

closes #13261

# User-Facing Changes

# Tests + Formatting

# After Submitting

### CODE REVIEW

**Comment by NotTheDr01ds** [comment]
I notice you updated the completions.  Also will be needed in `help operators`:

* `crates/nu-command/src/help/help_operators.rs`
* `crates/nu-std/std/help/mod.nu`

**Comment by fdncred** [comment]
Thanks for pointing those out.

**Comment by NotTheDr01ds** [comment]
The more I think about this one, the more I like it.  I think I'd probably switch to this syntax for readability.

**Comment by sholderbach** [comment]
Inclined to say we should remove the squiggly `!~` / `=~` if we land this after some grace period. I don't think having aliased syntax is really a good thing for teaching Nushell. And I always forget the order of `=~` vs `~=`... 

There is certainly a readability and special case burden for having simple words as operators with our bare words, but we already went there for the booleans and the rare bitwise ones. As those operations are expression context dependent it shouldn't mess with basic list expressions but just to tap the sign once #12767

**Comment by hustcer** [comment]
I vote to keep `=~` and `!~` 😭

**Comment by fdncred** [comment]
> I vote to keep `=~` and `!~` 😭

I'd vote to keep both too for now.

**Comment by rgwood** [comment]
I like this change. I also would not object to replacing the shorter operators.

**Comment by sam701** [comment]
I’d prefer to have only one way to do something (either `=~` or `like`). Otherwise, it gets messy.

**Comment by NotTheDr01ds** [comment]
Poll added, perhaps more for my own curiosity than anything.

**Comment by adamkpickering** [comment]
> I’d prefer to have only one way to do something (either =~ or like). Otherwise, it gets messy.

Agreed. Whenever there are two ways to do something, we end up having to remember both ways in order to understand code. It might seem like a small thing, but many such duplications make a language significantly more difficult to use.

Also, as a native english speaker the term "like" can mean a lot more to me than "is a regex match". For example, 1.2 is "like" 1.3... under some contexts. `a` is "like" `A`... but also not. And `{asdf: 4, qwer: 5}` is "like" `{asdf: 7, qwer: 8}`... again, under a certain context. AFAIK `=~` and `!~` are used only for matching regular expressions, and I think nushell should have only them, and not `like` and `not-like`.

**Pull request merged**
