### PR TITLE
Add an option to move header on borders

### PR DESCRIPTION
**Pull request by zhiburt**
A patch to play with.
Need to make a few tests after all.

The question is what shall be done with `table.mode = none`, as it has no borders.

```nu
$env.config.table.move_header = true
```

image

cc: @fdncred

### CODE REVIEW

**Comment by fdncred** [comment]
I'll try it out, but I think `$env.config.table.mode = none` should be drawn like it is now.

**Comment by fdncred** [comment]
Loving this, although there's something going on with the top row. size and modified values are the wrong colors.
image

**Review by amtoine — CHANGES_REQUESTED** [review]
i like this change, this is a nice compact idea :blush: 

i'll just backup @fdncred on some of the points with this new config :thinking: 

in the root of Nushell, i've run the same `ls | first 5` command with different value of `table.mode` and `table.move_header`:

### `$env.config.table.mode = rounded; $env.config.table.move_header = false`
round

### `$env.config.table.mode = rounded; $env.config.table.move_header = true`
round-move

### `$env.config.table.mode = compact; $env.config.table.move_header = false`
compact

### `$env.config.table.mode = compact; $env.config.table.move_header = true`
compact

### `$env.config.table.mode = none; $env.config.table.move_header = false`
none

### `$env.config.table.mode = none; $env.config.table.move_header = true`
none-move


we can see that some of the column names are not perfectly centered, that the color of the first line sometimes disappears and that the moved none layout does not show the columns :wink:

**Comment by fdncred** [comment]
yup, i can see in my screenshots that `compact`, `compact_double`, and `with_love` have the last 3 columns moved over to the right a little bit.

**Comment by zhiburt** [comment]
Must be addressed.
Though the fix is yet not released (likely will take a few days).

Let me know if it helps.

____________

Thinking maybe having the same alignment for cases where all column have the same alignment could be also a good option?

Basically if size is aligned to the right the header will be also.
Precisely can be added as a configuration.

**Comment by fdncred** [comment]
> Let me know if it helps.

Just tested it. Looks much better.
 
> Thinking maybe having the same alignment for cases where all column have the same alignment could be also a good option?
> 
> Basically if size is aligned to the right the header will be also. Precisely can be added as a configuration.

I'd have to see what this acts like. It's hard to tell from the description.

Regarding `light` and `none` table themes. I think `light` should look like it does now with the exception of the header and footer text being drawn on the lines. And `none` should just probably look exactly the same as it does now.
image

**Comment by zhiburt** [comment]
The themes must be fixed.
Though I've left `light` also unchanged cause if you think about it the line is not on the top.
I mean logically we could leave top row empty and put the headers on the line but .... I think maybe just leave it as a default is good enough?

____________

Something like this (Yee maybe not as good)

image

**Comment by fdncred** [comment]
This is what it looks like for me on Windows, which is unchanged, as you said. I kind of lean to this, if there's a line shown, put the column names centered on the line.
image

Also, I'd like to change the name of the option from `move_header` to `header_on_separator`. I'm up for other names too. I'm just looking for something a little more intuitive for people. Something easy to understand what it does.

**Comment by fdncred** [comment]
@zhiburt what do you think about putting the header names on the separator line for the `light` theme? I'd like to do it I think, just to be consistent.

**Comment by fdncred** [comment]
@zhiburt I think we're finally close to landing this after our latest release. What are your thoughts on my last request to put the header text on the separator line for the light theme?

**Comment by zhiburt** [comment]
> What are your thoughts on my last request to put the header text on the separator line for the light theme?

mixed; personally I'd not do that.

______________

Sorry it took longer then it shall.
I hope add a few tests in the nearest and switch to crates.io dependency.

**Comment by fdncred** [comment]
> mixed; personally I'd not do that.

I just think people will complain that all of them have the header text on the separator line except one.

> Sorry it took longer then it shall.

No problem.

> I hope I'll add a few tests in the nearest and switch to crates.io dependency.

Sounds good.

**Comment by jntrnr** [comment]
@zhiburt great work! Let's go ahead and land this so we have time to play with and tune it ahead of the next release. Thanks much!

**Comment by fdncred** [comment]
@zhiburt Seems like some changes somewhere have this PR broken now. It looks like the header row is the first data row?
image

**Comment by fdncred** [comment]
Also notice the last row, row 27.
image

**Comment by rgwood** [comment]
Wow I love this new compact layout! Thanks Maxim.

**Comment by rben01** [comment]
This is awesome. Is there any way to leave a space on either side of each header? I think it'd help readability a tad.

```
> $env.config.table.mode = compact; $env.config.table.move_header = true; ls | first 5
─ # ┬─────── name ───────┬─ type ─┬─── size ──┬────── modified ─────
  0 │ CODE_OF_CONDUCT.md │  file  │   3.4 KiB │ 2023-04-20 19:41:30
  1 │ CONTRIBUTING.md    │  file  │  10.4 KiB │ 2023-07-01 11:41:16
  2 │ Cargo.lock         │  file  │ 139.1 KiB │ 2023-07-25 18:27:54
  3 │ Cargo.toml         │  file  │   5.6 KiB │ 2023-07-25 18:27:54
  4 │ Cross.toml         │  file  │     363 B │ 2023-03-11 12:38:37
────┴────────────────────┴────────┴───────────┴─────────────────────
```

(Not sure if the `type` column should be made narrower by removing the extraneous `─`; they help with aesthetics but take up valuable space.)

**Comment by fdncred** [comment]
What does that table look like with `$env.config.table.padding = 0`? seems like it would still not be quite right.

**Pull request merged**
