### PR TITLE
Update internal use of `decimal` to `float`

### PR DESCRIPTION
**Pull request by sholderbach**
# Description
We made the decision that our floating point type should be referred to as `float` over `decimal`.
Commands were updated by #9979 and #10320

Now make the internal codebase consistent in referring to this data type as `float`.

Work for #10332

# User-Facing Changes

`decimal` has been removed as a type name/symbol. 

Instead of 
```nushell
def foo [bar: decimal] decimal -> decimal {}
```
use 
```nushell
def foo [bar: float] float -> float {}
```

Potential effect of `SyntaxShape`'s `Display` implementation now also referring to `float` instead of `decimal`

# Details
- Rename `SyntaxShape::Decimal` to `Float`
- Update `Display for SyntaxShape` to `float`
- Update error message + fn name in dataframe code
- Fix docs in command examples
- Rename tests that are float specific
- Update doccomment on `SyntaxShape`
- Update comment in script

# Tests + Formatting
Updates the names of some tests

### CODE REVIEW

**Comment by sholderbach** [comment]
Update on the impact of changing the display name of `SyntaxShape::Float`: The IDE flags use `FlatShape` which already refers to it as float. (So no need for tooling release synchronization)

Affected would be the `help` and `scope` output. If some one depends on a particular signature this will be a breaking change.

**Comment by jntrnr** [comment]
@sholderbach - is the type/shape name the user types now `float` also?

**Comment by sholderbach** [comment]
@jntrnr 
> is the type/shape name the user types now `float` also?

It already supported both `float` and `decimal`

this PR does not yet remove the latter.

**Comment by amtoine** [comment]
> this PR does not yet remove the latter.
>
soon :smirk:

**Comment by sholderbach** [comment]
@jntrnr and @amtoine 

Now no more `decimal` around :P

**Comment by amtoine** [comment]
> Now no more `decimal` around :P
>
loving it :muscle:

**Pull request merged**
