### PR TITLE
IR: Don't generate instructions for `def` and `export def`.

### PR DESCRIPTION
**Pull request by WindSoilder**
# Description
Fixes: #14110
Fixes: #14087

I think it's ok to not generating instruction to `def` and `export def` call.  Because they just return `PipelineData::Empty` without doing anything.

If nushell generates instructions for `def` and `export def`, nushell will try to capture variables for these block.  It's not the  time to do this.

# User-Facing Changes
```
nu -c "
def bar [] {
    let x = 1
    ($x | foo)
}
def foo [] {
    foo
}
" 
```
Will no longer raise error.

# Tests + Formatting
Added 4 tests

### CODE REVIEW

**Review by sholderbach — COMMENTED** [review]
Wow that's subtle! Thanks for identifying this. Makes sense to me that the definitions themselves don't need to evaluate at runtime and only should happen at parse time.

Giving the last word to @devyn

**Comment by devyn** [comment]
I think they need to clear the output register at least (equivalent of return empty)

**Comment by WindSoilder** [comment]
> I think they need to clear the output register at least (equivalent of return empty)

Thank you for your input!  I think I get the idea.  Although I'm not sure why `load_empty` works but `drop_reg` doesn't.

**Comment by sholderbach** [comment]
What are the remaining questions here that need clarification? @devyn / @WindSoilder

**Comment by WindSoilder** [comment]
I don't think so, I checked the generated IR, it seems fine to me

**Comment by fdncred** [comment]
Can we land this?

**Comment by devyn** [comment]
Hey @WindSoilder - `load_empty()` leaves the register as allocated, while `drop_reg()` marks it as free for use by something else, inside the compiler. The compiler tries to reuse registers by giving out ones that it knows aren't going to be used again before it increases the number of registers needed by the program.

I think your change should work fine.

**Pull request merged**
