### PR TITLE
fix: lose `ls_colors` in some filters commands

### PR DESCRIPTION
**Pull request by jaeheonji**
This PR related to #4444, #4306, #4309

# Description

Currently,`Ls_colors` is not applied due to missing `metadata` from some commands related to `filters`.
This bug appears not only in `first` and `skip` filters, but also in `reverse`, `get`, etc.

Therefore, for `Ls_colors`, each filter will have to return `PipelineData` including `metadata`.

**Expected Behavior:**
스크린샷 2022-02-18 오후 8 41 36

**Task:**
- [x] first
- [x] skip
- [x] last
- [x] reverse

# Tests

Make sure you've run and fixed any issues with these commands:

- [x] `cargo fmt --all -- --check` to check standard code formatting (`cargo fmt --all` applies these changes)
- [x] `cargo clippy --all --all-features -- -D warnings -D clippy::unwrap_used -A clippy::needless_collect` to check that you're using the standard code style
- [x] `cargo build; cargo test --all --all-features` to check that all the tests pass

### CODE REVIEW

**Comment by fdncred** [comment]
It makes me so happy to see this PR. Hopefully you don't run into any issues.

Note that we mention this issue in the `Checks` section of this tracking issue as well. https://github.com/nushell/nushell/issues/4356

**Comment by jaeheonji** [comment]
@fdncred

First of all, I applied `LS_COLORS` to 4 commands.
Actually, it seems that quite a few commands have not been applied yet. 

So, I think it's good to make a list of these and manage them as a one issues.

**Comment by fdncred** [comment]
@jaeheonji thank you so much for this. The current list that i know about is here https://github.com/nushell/nushell/issues/4356. If you want to make a new tracking issue, that's cool. It kind of hard to keep up with everything sometimes.

I know these are still missing
- [ ] roll
- [ ] ls | sort-by

i'll land this one and we can work on the others. thanks again!

**Comment by jaeheonji** [comment]
@fdncred thank you! The missing part will be made into another PR.
And, I will try to organize the parts which ls_colors is not applied and update to that issue 👍

**Pull request merged**
