### PR TITLE
Fix `touch` to allow changing timestamps on directories

### PR DESCRIPTION
**Pull request by kik4444**
# Description

Fix for #11757.
The main issue in #11757 is I tried to copy the timestamp from one directory to another only to realize that did not work whereas the coreutils `^touch` had no problems. I thought `--reference` just did not work, but apparently the whole `touch` command could not work on directories because `OpenOptions::new().write(true).create(true).open(&item)` tries to create `touch`'s target in advance and then modify its timestamps. But if the target is a directory that already exists then this would fail even though the crate used for working with timestamps, `filetime`, already seems to work for directories without just fine. 

# User-Facing Changes

I don't believe this should change any existing valid behaviors. It just changes a non-working behavior.

# Tests + Formatting

~~I only could not run `cargo test` because I get compilation errors on the latest main branch~~
All tests pass with `cargo test --features=sqlite`

# After Submitting

**P.S.** I recommend resetting back to `62272975f` at the latest to test this change. From `1867bb1a8` onwards there's a bug with flag arguments trying to convert strings to booleans for some reason.

### CODE REVIEW

**Comment by fdncred** [comment]
if you add `--features=sqlite` you can do cargo test. We need to fix that but it hasn't been tracked down yet.

**Comment by kik4444** [comment]
Speaking of tests I think I should make some a test or two for changing timestamps of directories, but tomorrow at the earliest cause I need to get to sleep soon.

**Comment by fdncred** [comment]
> Speaking of tests I think I should make a test or two for changing timestamps of directories, but tomorrow at the earliest cause I need to get to sleep soon.

yes, please. more tests helps ensure that features don't break in the future.

**Comment by kik4444** [comment]
> > Speaking of tests I think I should make a test or two for changing timestamps of directories, but tomorrow at the earliest cause I need to get to sleep soon.
> 
> yes, please. more tests helps ensure that features don't break in the future.

Ok that should cover everything. Though `commands::touch::change_dir_times_to_reference_dir` likely won't succeed because of the aforementioned issue with Nu trying to convert some of its `touch`'s flag args to booleans for some reason.

**Comment by fdncred** [comment]
> P.S. I recommend resetting back to 62272975f at the latest to test this change. From 1867bb1a8 onwards there's a bug with flag arguments trying to convert strings to booleans for some reason.

Is this a separate issue already? It probably needs to be fixed first because I doubt this will land unless the ci is green.

**Comment by kik4444** [comment]
I was hoping I'd get an answer from comment I made on the PR that introduced the regression, but perhaps that's enough waiting. I'll make an issue about it soon.

**Comment by kik4444** [comment]
Actually upon taking a closer look, I think I could fix this myself. I'm not sure anymore if this is a regression per-se, maybe @NotLebedev can shed some light, but I noticed other builtin commands that take an argument from a flag don't have this issue as far as I've looked. There may be others but I haven't noticed. The reason why `touch -r ref_dir` errors but something like `glob -e [ref_dir]` doesn't is because `glob` directly gets the flag value
```rust
let paths_to_exclude: Option<Value> = call.get_flag(engine_state, stack, "exclude")?;
```
while `touch` first checks if the flag is used
```rust
let use_reference: bool = call.has_flag(engine_state, stack, "reference")?;
```

`has_flag` treats the flag as a switch which is either provided by itself (i.e. `-f` or `--flag`) or whether it's given a boolean value (eg `--flag=false`). This is the relevant section
```rust
// crates/nu-engine/src/call_ext.rs

// Check --flag=false
let result = eval_expression(engine_state, stack, expr)?;
match result {
    Value::Bool { val, .. } => Ok(val),
    _ => Err(ShellError::CantConvert {
        to_type: "bool".into(),
        from_type: result.get_type().to_string(),
        span: result.span(),
        help: Some("".into()),
    }),
}
```
I can't think of many commands that accept an argument from a flag off the top of my head, but given that `touch` is the only command I've seen with this issue I imagine that when this change was made `touch` was not ported to use `get_flag` directly instead of first using `has_flag`.

Anyways, I can fix this myself, but it's possible there are other commands with the same bug, though I can't seen any others yet.

**Comment by fdncred** [comment]
There are some use cases for `--flag=true` but most of what I've seen are for forwarding flags to other programs and doing flag parsing inside of a custom command.

**Comment by kik4444** [comment]
Turns out there were quite a few things I wanted to improve/refactor after all. I hope that's okay

**Comment by kik4444** [comment]
Well that's weird. All tests pass on my system.

**Comment by fdncred** [comment]
Weird indeed.
```
thread 'commands::touch::change_dir_times_to_reference_dir' panicked at crates\nu-command\tests\commands\touch.rs:322:9:
assertion `left != right` failed
  left: SystemTime { intervals: 133519057186339154 }
 right: SystemTime { intervals: 133519057186339154 }
```

**Comment by kik4444** [comment]
> Weird indeed.
> 
> ```
> thread 'commands::touch::change_dir_times_to_reference_dir' panicked at crates\nu-command\tests\commands\touch.rs:322:9:
> assertion `left != right` failed
>   left: SystemTime { intervals: 133519057186339154 }
>  right: SystemTime { intervals: 133519057186339154 }
> ```

Minor correction. I didn't realize this when looking at the test, but that part of that test is supposed not to equal. Those 2 systemtimes are *supposed* to be different. But on that Windows system they're not...

**Comment by kik4444** [comment]
Ok interesting. This time the most important tests were canceled for some reason and one ubuntu test failed outside my changes.

**Comment by NotLebedev** [comment]
> Actually upon taking a closer look, I think I could fix this myself. I'm not sure anymore if this is a regression per-se, maybe @NotLebedev can shed some light, but I noticed other builtin commands that take an argument from a flag don't have this issue as far as I've looked. There may be others but I haven't noticed. The reason why `touch -r ref_dir` errors but something like `glob -e [ref_dir]` doesn't is because `glob` directly gets the flag value
> 
> while `touch` first checks if the flag is used
>
> I can't think of many commands that accept an argument from a flag off the top of my head, but given that `touch` is the only command I've seen with this issue I imagine that when this change was made `touch` was not ported to use `get_flag` directly instead of first using `has_flag`.

You are correct in your assessment. This change was intentional on my part. Get flag already returns `Optional<T>` so there is no need for additional check. If this was not the case then basically two versions of `has_flag` would need to exist and as pointed out [in original PR](https://github.com/nushell/nushell/pull/11492#issuecomment-1879849718) there is no need for this.

Because that PR was large I mostly did it automatically (no way I edit almost 150 files by hand) and then went through test failures and some commands where I knew for a fact issues like you mentioned existed. Unfortunately I underestimated extend of this problem, it seems. It is strange that no test caught this. 

For anybody referring here in future. As @kik4444 said fix is easy, just remove this double check and just check the variant of `Optional` that `get_flag` returns, which, in my opinion, is a better rust code anyways.

Also sorry for long reply time.

**Comment by kik4444** [comment]
Ok more problems with Windows. Has anyone tested if `touch` actually works as it's supposed to on Windows before? Is github workflows experiencing problems? Or is it that the tests were not strict enough before? To be fair I did modify the existing tests to set the timestamps to 0, or `1970-01-01_00:00:00`, before running the test to make sure `touch` changed the mtime or atime to today properly whilst preserving the other...

**Comment by fdncred** [comment]
I thought this would be a quick and easy change, but unfortunately it looks like we're having lots of issues. With that in mind, we've planned on moving to uutils/coreutils uu_touch as documented here https://github.com/nushell/nushell/issues/11549. I'd hate to see you continue to put in lots of time only to have this code eventually removed. Sorry I didn't bring this up earlier.

@ysthakur may have started on replacing touch but you may be able to work with him too.

**Comment by kik4444** [comment]
Oh well, at least I hope it brings attention to why Windows tests are failing

**Comment by fdncred** [comment]
I'm running the tests in Windows now just to see if I get the same error

**Comment by ChrisDenton** [comment]
> To be fair I did modify the existing tests to set the timestamps to 0,
Wait, literally zero or UNIX zero? A literal zero won't work because it has a special meaning (see [SetFileTime](https://learn.microsoft.com/en-us/windows/win32/api/fileapi/nf-fileapi-setfiletime)).

**Comment by fdncred** [comment]
I just changed the test to this and the first part passes.
```rust
        // Change the times for reference
        filetime::set_file_times(
            &reference,
            filetime::FileTime::from_unix_time(1337, 1337),
            filetime::FileTime::now(),
        )
        .unwrap();
```
I decided to not use 
```rust
const TIME_ZERO: filetime::FileTime = filetime::FileTime::zero();
```

But now I get this
image

**Comment by ysthakur** [comment]
@kik4444 As fdncred said, I'm working on integrating uu_touch into Nushell. Here's [the PR](https://github.com/nushell/nushell/pull/11817) if you want to also collaborate there. It doesn't look like uutils/coreutils tests setting the time to 0 either, so I'll copy the tests over.

> Wait, literally zero or UNIX zero? A literal zero won't work because it has a special meaning (see [SetFileTime](https://learn.microsoft.com/en-us/windows/win32/api/fileapi/nf-fileapi-setfiletime)).

@ChrisDenton Nice catch, it looks like the `filetime::FileTime::zero` method ([source](https://docs.rs/filetime/latest/src/filetime/lib.rs.html#74-79)) literally uses 0 and as far as I can tell, that's not added to later, so you might be right. [`from_unix_time(0, 0)`](https://docs.rs/filetime/latest/filetime/struct.FileTime.html#method.from_unix_time) would avoid that, but it wouldn't test setting the time to Windows 0.

**Comment by kik4444** [comment]
> But now I get this image

That can't be right. I reworked most of `touch` precisely to avoid that. I don't get that error anymore and neither do the tests.



> > To be fair I did modify the existing tests to set the timestamps to 0,
> 
> Wait, literally zero or UNIX zero? A literal zero won't work because it has a special meaning (see [SetFileTime](https://learn.microsoft.com/en-us/windows/win32/api/fileapi/nf-fileapi-setfiletime)).

I think so, since FileTime defines zero like so
```rust
FileTime { seconds: 0, nanos: 0 }
```
Wouldn't unix zero and literal 0 be the same thing though?

**Comment by ChrisDenton** [comment]
A Windows [FILETIME](https://learn.microsoft.com/en-us/windows/win32/api/minwinbase/ns-minwinbase-filetime) starts from 1601-01-01 whereas a Unix time is 1979-01-01. So no.

**Comment by kik4444** [comment]
Anyways this should fix the Windows issue with 0 being special and I also thought of 2 more tests to make sure `--reference` combined with `-m` or `-a` preserves the other timestamp. I hope this doesn't seem like *too many* tests...

**Comment by kik4444** [comment]
Or should we retain tests for 0 specifically on Windows? I feel like it could be a source of confusion if the future `touch` command accepts integers directly. What should the correct behavior be if a user passes in `touch -d 0` on Windows?

**Comment by fdncred** [comment]
I'm fine with having tests that only run on windows and others that run on unix.

> That can't be right.

I could be doing something wrong but I have your touch-dir PR checked out and run the `change_dir_times_to_reference_dir` test and get the `can't convert string to bool` error on Windows.

**Comment by kik4444** [comment]
You have synced the latest changes from the branch though, haven't you?

**Comment by fdncred** [comment]
@kik4444 can you fix the conflicts? I'm thinking we can probably land this if we can get the ci green.

**Comment by kik4444** [comment]
To be honest I don't understand why this still conflicts

**Comment by fdncred** [comment]
Does this one need to be closed?

**Pull request closed without merging**
