### PR TITLE
Check for WRAP_PROMPT_XXX in environment

### PR DESCRIPTION
**Pull request by PerBothner**
These can provide a wrapper around the corresponding user-specified variable (such as PROMPT_COMMAND) allowing for things like customised or [enhanced shell integration protocols](https://gitlab.freedesktop.org/Per_Bothner/specifications/blob/master/proposals/semantic-prompts.md).

This provides the same functionality as withdrawn PR #7077 but as a much simpler (and more flexible) change.

# Description

The idea is that when evaluating `PROMPT_XXX` we first check if `WRAP_PROMPT_XXX` is defined.  If so we evaluate it instead.  While `WRAP_PROMPT_XXX` can in principle return any string it wants, the intended use-case is for `WRAP_PROMPT_XXX` to call the user-preference `PROMPT_XXX` and then modify or wrap the result. This is useful for shell-integration and might have other uses.

Using `WRAP_PROMPT_XXX` functions allows users to customize the prompts and indicators in the documented way, without getting in the way of shell-integration or other UI protocols.

The iTerm2-style shell-integration `PRE_PROMPT_MARKER` and `POST_PROMPT_MARKER` strings are ignored if `WRAP_PROMPT_COMMAND` is defined.

This is how these variables can be used for Domterm:
```
let-env WRAP_PROMPT_COMMAND = if "DOMTERM" in (env).name {
    { $"\u001b]133;P;k=i\u0007(do $env.PROMPT_COMMAND)\u001b]133;B\u0007" }
  } else $env.PROMPT_COMMAND
let-env WRAP_PROMPT_COMMAND_RIGHT = if "DOMTERM" in (env).name {
    { $"\u001b]133;P;k=r\u0007(do $env.PROMPT_COMMAND_RIGHT)\u001b]133;B\u0007" }
  } else $env.PROMPT_COMMAND_RIGHT
let-env WRAP_PROMPT_INDICATOR = if "DOMTERM" in (env).name {
    { $"\u001b]133;P\u0007(do $env.PROMPT_INDICATOR)\u001b]133;B\u0007" }
  } else $env.PROMPT_INDICATOR
let-env WRAP_PROMPT_INDICATOR_VI_INSERT = if "DOMTERM" in (env).name {
    { $"\u001b]133;P\u0007(do $env.PROMPT_INDICATOR_VI_INSERT)\u001b]133;B\u0007" }
  } else $env.PROMPT_INDICATOR_VI_INSERT
let-env WRAP_PROMPT_INDICATOR_VI_NORMAL = if "DOMTERM" in (env).name {
    { $"\u001b]133;P\u0007(do $env.PROMPT_INDICATOR_VI_NORMAL)\u001b]133;B\u0007" }
  } else $env.PROMPT_INDICATOR_VI_NORMAL
let-env WRAP_PROMPT_MULTILINE_INDICATOR = if "DOMTERM" in (env).name {
    { $"\u001b]133;P;k=c\u0007(do $env.PROMPT_MULTILINE_INDICATOR)\u001b]133;B\u0007" }
  } else $env.PROMPT_MULTILINE_INDICATOR
```
The above enables the following features on DomTerm:
* Move cursor by clicking mouse.  This is simulated by the terminal sending Left/Right arrow keys.
* Command errors are indicated with a small red circle.  Hovering over it displays the error code.
* If you change the window width, it automatically adjusts the position of right prompts in the scroll-back buffer.  The prompt is hidden if there isn't enough space on the line. _Note_: While reedline adjusts the right-prompt position in the _current_ command, for previous commends this had to be handled by the terminal.
* "Folding": Little triangles that when clicked show or hide the output of a command.
* Right prompt and indicators are distinguished internally and visibly.

See [this old blog article](http://per.bothner.com/blog/2019/shell-integration-proposal/) for more about these features, with (non-Nu) screenshots.`

# Tests + Formatting

Make sure you've run and fixed any issues with these commands:

[X] `cargo fmt --all -- --check` to check standard code formatting (`cargo fmt --all` applies these changes)
[X] `cargo clippy --workspace --features=extra -- -D warnings -D clippy::unwrap_used -A clippy::needless_collect` to check that you're using the standard code style. (There are a bunch of errors, bit they predate my changes and are in different areas of the code.)
[X] `cargo test --workspace --features=extra` to check that all tests pass

### CODE REVIEW

**Comment by fdncred** [comment]
My tendency is to land this because it's not very intrusive and just provides a way to wrap our PROMPT_ blocks. Of course, if we do land that we'd want some documentation on this functionality. But before we do that, let's see what others think of this.

**Comment by PerBothner** [comment]
Some tentative documentation, for [this part of the book](https://www.nushell.sh/book/coloring_and_theming.html#prompt-configuration-and-coloring):

If any of `WRAP_PROMPT_COMMAND`, `WRAP_PROMPT_COMMAND_RIGHT`, `WRAP_PROMPT_INDICATOR`, `WRAP_PROMPT_INDICATOR_VI_INSERT`, `WRAP_PROMPT_INDICATOR_VI_NORMAL`, or `WRAP_PROMPT_MULTILINE_INDICATOR` is defined, NuShell uses that variable instead of the corresponding plain `PROMPT_XXX` variable. Typically, a `WRAP_PROMPT_XXX` block would invoke the corresponding `PROMPT_XXX` and do some modification or wrapping of the result. Normally, you would change `PROMPT_XXX` if you want to set the text or style of the prompt or indicator, while you set `WRAP_PROMPT_XXX` for a terminal-specific or UI-specific protocol.

Here are two examples. The first actually has no effect if `config.shell_integration` is set, since it mimics part of the effect of setting `shell_integration`. The second example is how to handle "right prompt" if you want to do [enhanced shell integration](https://gitlab.freedesktop.org/Per_Bothner/specifications/blob/master/proposals/semantic-prompts.md):
```
let-env WRAP_PROMPT_COMMAND = {
    $"\u001b]133;A\u0007(do $env.PROMPT_COMMAND)\u001b]133;B\u0007" }
let-env WRAP_PROMPT_COMMAND_RIGHT = {
    $"\u001b]133;P;k=r\u0007(do $env.PROMPT_COMMAND_RIGHT)\u001b]133;B\u0007" }
```

**Comment by sholderbach** [comment]
From the internals it looks straight forward, but I don't find it particularly aesthetically pleasing to have to solve it that way. Having text based env vars that silently shadow each other feels not fully nushell-y. 
I am not up to speed on how the slightly different shell/terminal integration protocols work. What locations do they expect their signals? How do they handle the error/output signals differently? How do they treat segmented prompts (what your wrapping of my prompt archenemy `PROMPT_INDICATOR*` effectively does)? Would it be feasible to define clear config variables for the components and let nushell handle that or ist that not truly compatible with 3rd party prompts that might do part of the work already?

Question would be is the complexity to do it properly more annoying to us and the users than to leave this solution.

From a perspective of `reedline` as a library it would be pleasing to provide the logic to wrap prompts in those signals based on a config, so that other users could benefit from that as well.

**Comment by PerBothner** [comment]
The "traditional" separation between terminal, input edtor, and shell (or other REPL-based application) is functional but limited. Something as obvious as being unable to move the input cursor with a mouse click is only acceptable because we're so used to it. There have been a number of efforts to come up something richer: Emacs eshell, [cat-9](https://github.com/letoram/cat9), and many more. A goal of "shell integration" is to provide semantic meaning for different parts of the terminal display: Prompts, user input, and output. This is very much in the spirit of NuShell: Working with structure instead of raw text. Once you have that, you can do some interesting things.

Some terminals (most notably iTerm2) support a simple "shell integration" protocol, which I believe was invented for FinalTerm. This protocol (which Nu has builtin support for) is quite limited. It makes no provision for a "right prompt", or multiline input with prompts beyond the first line. It is also extremely fragile when dealing with redisplay due to window resize.

As a minimum, once needs to distinguish prompts (including indicators) from user input. You can't reliably do click-moves-mouse without that. Also, having an indicator for the right prompt is needed if the terminal is to handle window resize properly.

You could certainly use config variables for escape sequences to indicate start and end of the various segments. My previous withdrawn solution PR #7077 did that. However, it was  a much bigger change.  This current PR is also more flexible. For example a `WRAP_PROMPT_XX` function would for example upper-case the user prompt string.  (Not sure why you'd ever want to do that, though ...) 

*About error vs output:* DomTerm does have an escape sequences to indicate  that the following text comes from standard error rather than standard error. Following text will be placed inside a special segment (`<span std="error">error seen!</span>`), which by default is styled with red as the text color. Unfortunately this has to be done by each application. It would be nice if we could automatically detect that some text was written to stderr, but by the time it has made to through the pty layer, that information is lost. Changing that would seem to require terminal driver changes - perhaps an extension of `EXTPROC` mode. Not likely to happen any time soon.

**Comment by fdncred** [comment]
Kind of off topic, but related.

> Also, having an indicator for the right prompt is needed if the terminal is to handle window resize properly.

I'm wondering if any of this is good for reedline. Reedline doesn't handle resize of the terminals as well as we'd like. Is there something we could build in there that would help resize redrawing?

**Comment by fdncred** [comment]
@PerBothner I keep looking at this and keep missing the point. I apologize for not fully understanding. I can easily see by your thorough description how you would use this in DomTerm. I've also read the links you've referenced. What I'm not clear about is are there a few use cases you can provide that will aid the user in modern terminals?

Here's a list of some of the terminals we test with.
Gnome-Terminal
Windows Terminal
Tabby
iTerm2
Alacritty
Kitty
Warp
terminal.app
WezTerm
kgx/Console

**Comment by PerBothner** [comment]
@fdncred I'm not sure what you're saying. It sounds like "we only care about functionality that can be used on the most popular modern terminals". Of course a terminal author might just as well say "we only care about functionality that is used by the more popular shells" - which would not currently include NuShell. My goal is to improve the state-of-the-art of repl/terminal interfaces - and I think NuShell has a similar goal. Specifically, I think DomTerm is an especially good match for NuShell because NuShell works with richer data types, and DomTerm can provide richer display of those data types. One possibility: image thumbnails in `ls` output.

Most "modern terminal" do not support any shell-integration at all (unless you consider `OSC 7` and `OSC 2`). Then the question is whether you see the value of iTerm2-style shell integration - and whether support should be built in to NuShell. I do know there is a small number of terminals that implement this kind of shell integration (Kitty is one of them), but it is rare and I don't know of any among the most popular terminals.

Now it is a fact that the FinalTerm/iTerm2 shell-integration protocol is a poor match for NuShell (or Fish). It doesn't handle right prompts and it doesn't handle continuation lines. This allows you to distinguish input lines from output lines - but not much else. You can't distinguish prompts from input - in which case what is the point of having an "end-of-prompt" escape sequence?

Note also that this PR gives you the option of removing existing shell-integration from the NuShell core, because it makes it very easy to re-implement it using the `WRAP_PROMPT_XXX` variables plus execution hooks. (You'd want to replace `get_command_finished_marker` with a hook.) That shows the use and flexibility of this change.

For what it is worth: It is _possible_ to implement shell-integration (basic or enhanced) just by modifying the `PROMPT_XXX` variables in a pre-input hook and restoring them in a pre-execution hook. That is basically how the shell-integration scripts for Bash, Fish, and Zsh do it. If you think that is the way to go, I think we should remove the existing `shell_integration` support from the Rust code, and re-implement it in `config.nu`. However, that way is more complicated and fragile. Much simpler and more robust to use the `WRAP_` mechanism in my patch.

**Comment by PerBothner** [comment]
_"It seems the need for the WRAP_PROMPT_COMMAND family env vars stems from the need to define new PROMPT_COMMAND using the old one. But once you re-define it, the old one is gone so you need to keep some OLD_PROMPT_COMMAND or something internally."_

Right. What seems the tricky part is that the new `PROMPT_COMMAND` needs to be reverted ("popped") once Reedline is done and commands start executing. That command may redefine `PROMPT_COMMAND` - which in turn becomes the new `OLD_PROMPT_COMMAND` while Reedline is active.

I don't understand your example - but I think I understand the idea you're suggesting. The `pre_prompt` hook could do either `overlay new` or `overlay use` while the `pre_execution` hook can do `overlay hide`. (Of course we need to not mess things up if the command is invalid or otherwise cancelled.)

So how does the new `PROMPT_COMMAND` get hold of the old one? One mechanism is to define `OLD_PROMPT_COMMAND`; do the `overlay use`; and then define `PROMPT_COMMAND` in terms of `OLD_PROMPT_COMMAND`. However, that seems rather clumsy.  Is there a way for an overlay to access an otherwise-hidden definition? Perhaps something like `$old_env.PROMPT_COMMAND` or `$env.outer.PROMPT_COMMAND` ?

**Comment by kubouch** [comment]
Overlays are layers that are stacked on top of each other. You could make a new overlay and define `PROMPT_COMMAND` there but the old `PROMPT_COMMAND` is still in the previous overlay, it is not deleted. You could have a command that says "give me the `PROMPT_COMMAND` env var but from the previous overlay, not from the current one". 

> Is there a way for an overlay to access an otherwise-hidden definition?

Currently, no, but it should be quite easy to add this mechanism for env vars shadowed by overlays.

So, the `pre_prompt` hook could look like
```
overlay new spam
let-env PROMPT_COMMAND = give-me-old-prompt-command-and-wrap-it
```
and `pre_execution` hook would be just
```
overlay hide spam
```

**Comment by kubouch** [comment]
And thinking about it, this solution should already work just fine:
```
# pre_prompt hook
overlay new spam
let-env OLD_PROMPT_COMMAND = $env.PROMPT_COMMAND
let-env PROMPT_COMMAND = ...do something with $env.OLD_PROMPT_COMMAND
```
and
```
# pre_execution hook
overlay hide spam
```

The system I described earlier is still viable, but I think this is already good enough.

**Comment by kubouch** [comment]
Actually, if we added a way to either delete an overlay permanently, or make the `export-env` block be executed _before_ the overlay's environment is activated (or both), you should be able to do this:
```
# pre_prompt hook
module spam {
  export-env {
    let old_prompt_command = $env.PROMPT_COMMAND
    let-env PROMPT_COMMAND = ... do something with $old_prompt_hook
  }
}

overlay use spam
```
```
# pre_execution hook
overlay hide spam  # or `overlay delete spam`
```
I think that's not too bad, we just need to extend the overlays system a little bit.

We don't even need the mechanism I described above. This is more robust solution.

**Comment by PerBothner** [comment]
@kubouch The example code you wrote fails if `read_line(prompt)` returns anything other than `Ok`.

One solution is to check in the `pre_prompt` hook if the wrapped definitions are still active (because the `pre_exeuction` hook didn't get called). If so, do nothing. A simple way to check is if `OLD_PROMPT-COMMAND` is defined,

However, I think a cleaner solution would be to add a `post_input` hook:

        let input = line_editor.read_line(prompt);
        let shell_integration = config.shell_integration;

        if let Some(hook) = config.hooks.post_input.clone() {
            if let Err(err) = eval_hook(engine_state, stack, None, vec![], &hook) {
                report_error_new(engine_state, &err);
            }
        }

        match input {
            Ok(Signal::Success(s)) => {

The `overlay hide` should be in the `post_input` hook (instead of the `pre-execution` hook).

If probably makes sense to pass an argument to the `post_input` hook that encodes the Ok/Ctrl-C/Ctrl-D/Err result.

**Comment by PerBothner** [comment]
@kubouch I tried a variant of  what you suggested:
```
let-env config = if "DOMTERM" in (env).name { $env.config
  | upsert hooks {
    pre_prompt: {
       print --no-newline "\u001b]133;A;cl=m\u0007"
       overlay new integration
       module integration {
         export-env {
           let old_prompt_right = $env.PROMPT_COMMAND_RIGHT
           let-env PROMPT_COMMAND_RIGHT =  { $"\u001b]133;P;k=r\u0007(do $old_prompt_right)\u001b]133;B\u0007" }
           }
        }
        overlay use integration
      }
    # pre_execution: { overlay hide integration }
    display_output: { to html --partial --no-color | domterm hcat } }
  } else { $env.config }
```
That seemed to work. But when I uncommented the `pre_execution` line I get:
```
Error: nu::shell::external_command (link)

  × External command failed
     ╭─[/home/bothner/.config/nushell/config.nu:424:1]
 424 │   | upsert hooks {
 425 │     pre_prompt: {
     ·     ─────┬─────
     ·          ╰── executable was not found
 426 │        print --no-newline "\u001b]133;A;cl=m\u0007"
     ╰────
  help: No such file or directory (os error 2)
```
Hopefully someone with more Nu experience will find that less puzzling than I do ...

**Comment by kubouch** [comment]
It won't work for two reasons
1. The `export-env` block will run after the overlay is active which means that if you activated the overlay before, it won't see the original environment. I'm looking into ways how to address this.
2. Overlays are scoped which means you probably need to define them as strings.

The error you're getting stems from the fact that if Nushell can't parse `{ ... }` as a record (because there is an error, in your case, in `overlay hide integration` the "integration" overlay is not available, see point 2.), it tries to parse it as a closure.

**Comment by kubouch** [comment]
@PerBothner Have you tried using the updated overlays in the latest version? From my limited testing, it seems like it should cover your use case.

**Comment by kubouch** [comment]
Adding a `post_input` could also be something we could add, you can make a feature request. I'm not super keen on adding too many hooks because it would get confusing. But you could indeed end up in some dangling state if `read_line()` fails like you mentioned, that's something that should be thought about. Maybe the `pre_execution` hook could be changed to `post_prompt` and executed regardless of the `read_line()` outcome?

**Comment by PerBothner** [comment]
Thanks - I'll take a look at the new features in 0.72.

I've been busy with  other things, but I have realized that it is possible to make do with the existing hooks, as long as I can mutate and test the environment as needed.  Using pseudo-code:

    let _prompt_wrapped = false;
    pre_prompt: {
      if ! $_prompt_wrapped {
         _prompt_wrapped = true
         SAVE_PROMPT_COMMAND_RIGHT = $PROMPT_COMMAND_RIGHT
         PROMPT_COMMAND_RIGHT = $"...(do $env.SAVE_PROMPT_INDICATOR)...."
      }
    }
    pre_execution: {
      if $_prompt_wrapped {
         _prompt_wrapped = false
         PROMPT_COMMAND_RIGHT = $SAVE_PROMPT_COMMAND_RIGHT
      }
    }

The idea is if we get to `pre_prompt` without an intervening `pre_execution` we don't need to do anything, we can just continue using the existing wrapper.

A similar logic could probably be used with "updated overlays" (which I have to read up on).

It's a bit clunky, but it can probably work well enough. It probably requires a modest change to DomTerm to distinguish an initial `OSC 133 A` with extra parameters (emitted by `pre_prompt`) vs a secondary `OSC 133 A` (emitted by the builtin shell-integration each time the prompt is rendered).

**Comment by PerBothner** [comment]
This seems to work:
```
let-env _PROMPT_WRAPPED = false
if "DOMTERM" in (env).name {
  let-env config = ($env.config | upsert hooks {
    display_output: { to html --partial --no-color | domterm hcat }
    pre_prompt: {
      print --no-newline "\u001b]133;A;cl=m\u0007"
      if not $env._PROMPT_WRAPPED {
        let-env _PROMPT_WRAPPED = true
        let-env _SAVED_PROMPT_RIGHT = $env.PROMPT_COMMAND_RIGHT
        let-env PROMPT_COMMAND_RIGHT = { $"\u001b]133;P;k=r\u0007(do $env._SAVED_PROMPT_RIGHT)\u001b]133;B\u0007" }
      }
    }
    pre_execution: {
      if not $env._PROMPT_WRAPPED {
        let-env _PROMPT_WRAPPED = false
        let-env PROMPT_COMMAND_RIGHT = $env._SAVED_PROMPT_RIGHT
      }
    }
  })
}
```
It only "wraps" the `PROMPT_COMMAND_RIGHT`, but the same logic should be easy to add for the various `PROMPT_INDICATOR_XXX`, which should be wrapped in the same way.
I assume overlays might simplify the `pre_execution` hook, but otherwise this seems pretty workable.

**Comment by kubouch** [comment]
OK cool, then I'll close this PR as the WRAP_xxx approach would introduce an additional complexity.

You should be able to utilize overlays by defining the hook as a source code string: https://www.nushell.sh/book/hooks.html#automatically-activating-an-environment-when-entering-a-directory. Feel free to raise an issue or ask on Discord if you have any issues with this.

**Comment by PerBothner** [comment]
For the record, I'm using this now:
```
if "DOMTERM" in (env).name {
  let-env _SAVED_PROMPTS = null
  let-env config = ($env.config | upsert hooks {
    display_output: { to html --partial --no-color | domterm hcat }
    pre_prompt: {
      print --no-newline "\u001b]133;A;cl=m\u0007"
      if $env._SAVED_PROMPTS == null {
        let SP = {
          right: $env.PROMPT_COMMAND_RIGHT
          indicator: $env.PROMPT_INDICATOR
          vi_insert: $env.PROMPT_INDICATOR_VI_INSERT
          vi_normal: $env.PROMPT_INDICATOR_VI_NORMAL
          multiline: $env.PROMPT_MULTILINE_INDICATOR
        }
        let-env _SAVED_PROMPTS = $SP
        let-env PROMPT_COMMAND_RIGHT = { $"\u001b]133;P;k=r\u0007(do $SP.right)\u001b]133;B\u0007" }
        let-env PROMPT_INDICATOR = { $"\u001b]133;P\u0007(do $SP.indicator)\u001b]133;B\u0007" }
        let-env PROMPT_INDICATOR_VI_INSERT = { $"\u001b]133;P\u0007(do $SP.vi_insert)\u001b]133;B\u0007" }
        let-env PROMPT_INDICATOR_VI_NORMAL = { $"\u001b]133;P\u0007(do $SP.vi_normal)\u001b]133;B\u0007" }
        let-env PROMPT_MULTILINE_INDICATOR = { $"\u001b]133;P;k=c\u0007(do $SP.multiline)\u001b]i8k133;B\u0007" }
      }
    }
    pre_execution: {
      if $env._SAVED_PROMPTS != null {
        let $SP = $env._SAVED_PROMPTS
        let-env PROMPT_COMMAND_RIGHT = $SP.right
        let-env PROMPT_INDICATOR = $SP.indicator
        let-env PROMPT_INDICATOR_VI_INSERT = $SP.vi_insert
        let-env PROMPT_INDICATOR_VI_NORMAL = $SP.vi_normal
        let-env PROMPT_MULTILINE_INDICATOR = $SP.multiline
        let-env _SAVED_PROMPTS = null
      }
    }
  })
}
```
It uses structure to avoi cluttering up the environment - it only adds `_SAVED_PROMPTS`.

**Comment by PerBothner** [comment]
There are some issues with the above solution, compared to the `_WRAP_XXX` approach. The following come to mind:

* Hooks are not modular: I see no clean way for two independent libraries to independently use hooks without at least one knowing about the other - or using some (new) hook-management library.

* A bunch of new closures are created and destroyed on each command.  This seems inefficient. Since it happens on user input, it is unlikely to matter, but it seems inelegant.

A separate but related issue:

*  The variable `shell_integration` controls a hodge-podge of unrelated features, some of which (like window titles) date back to xterm (and have been near-universal for 2 decades); some of which are newer but beoming common (OSC 8); some of which are true "shell integration" supported by only a few (and except for iTerm2 reltively less common) terminals.

**Comment by fdncred** [comment]
> The variable shell_integration controls a hodge-podge ...

Ya, it would be great to start separating some of these shell_integration features as different settings like:
```
shell_integration.title = true
shell_integration.osc8 = true
shell_integration.reset_application = true
etc, etc
```

**Pull request closed without merging**
