### PR TITLE
String values should pass their content-type correctly on http requests with a body (e.g. http post)

### PR DESCRIPTION
**Pull request by ayax79**
# Description
The content-type was not being handled appropriately when sending requests with a string value.

# User-Facing Changes
- Passing a string value through a pipeline with a content-type set as metadata is handled correctly
- Passing a string value as a parameter with a content-type set as a flag is handled correctly.

### CODE REVIEW

**Comment by sholderbach** [comment]
This probably should rebase onto the changes from #13701 or vice versa

**Comment by ayax79** [comment]
It's probably much easier to pull this into #13701. Alternately, I could reimplement once it is in.

**Comment by ayax79** [comment]
@sholderbach - I updated with the changes from #13701.

**Comment by sholderbach** [comment]
Kind of tricky to have this ambiguity if a string is already prepared json or a string to be quotes.

**Comment by ayax79** [comment]
> Kind of tricky to have this ambiguity if a string is already prepared json or a string to be quotes.

Personally, I would expect that if application/json is passed in that the string is always well formed json. This seemed to break a lot of tests were passing in "1" with application/json and expecting it not to break. The fallback is basically to allow this... I personally, would change all the tests and considered it a breaking change as I feel like if you are going to pass application/json it should actually be json.

**Comment by ayax79** [comment]
I spoke with @sholderbach, we will land this as is. If we want to restrict the conversions more we can add it.

**Pull request merged**
