### PR TITLE
polars: add binary type support

### PR DESCRIPTION
**Pull request by dead10ck**
# Description
This adds support for reading and writing binary types in the polars
commands.

The `BinaryOffset` type can be read into a Nushell native `Value` type
no problem, but unfortunately this is a lossy conversion, as there's
no Nushell-native semantic equivalent to the fixed size binary type
in Arrow.

# User-Facing Changes

`polars open` and `polars save` now work with binary types.

### CODE REVIEW

**Comment by fdncred** [comment]
This is interesting. What's the use case? Or can we have a test and/or example that demonstrates it?

**Comment by dead10ck** [comment]
The use case is working with binary data. Are you looking for something more specific? There are a plethora of use cases for working with raw binary data. One might ask what the use case is for having a binary data type in nushell. Where does one even begin?

Currently if you have any binary data in a dataframe and try to serialize it, it just errors.

```
{ foo: 'hello', bar: 0x[00 01 02] } | polars into-df | polars save test.parquet
Error:   × Error saving file
   ╭─[source:1:68]
 1 │ { foo: 'hello', bar: 0x[00 01 02] } | polars into-df | polars save test.parquet
   ·                                                                    ──────┬─────
   ·                                                                          ╰── cannot write 'Object' datatype to parquet
   ╰────
```

After the change, it can work with binary.

```
nushell on  polars/add-binary [?] is 📦 v0.97.1 via 🦀 v1.80.0 on ☁  personal
❯ : { foo: 'hello', bar: 0x[00 01 02] } | polars into-df | polars save test.parquet
╭───┬───────────────────────────────────────────────────────────────────╮
│ 0 │ saved "/data/data/com.termux/files/home/src/nushell/test.parquet" │
╰───┴───────────────────────────────────────────────────────────────────╯

nushell on  polars/add-binary [?] is 📦 v0.97.1 via 🦀 v1.80.0 on ☁  personal
❯ : polars open test.parquet --eager
╭─#─┬──foo──┬────bar────╮
│ 0 │ hello │ [0, 1, 2] │
╰───┴───────┴───────────╯
```

**Comment by fdncred** [comment]
Ah, i see. thanks

**Comment by fdncred** [comment]
@ayax79 any objections here?

**Comment by dead10ck** [comment]
Anything I can do for this PR?

**Comment by fdncred** [comment]
Thanks

**Pull request merged**
