### PR TITLE
[WIP] table: Show truncated record differently

### LINKED ISSUE #6851: `table -e`: A subvalue, {record 5 fields}, is displayed as completely truncated in `-e` view
### Describe the bug

The new `table -e` view has a rather strange phenomenon where, if a record can't fully fit into view, all of the record's columns are truncated to nothing rather than showing them.

### How to reproduce

image

### Expected behavior
Here's what `scope` looks like, by the way:
```
〉$nu | get scope
╭──────────────┬───────────────────╮
│ vars         │ [table 4 rows]    │
│ commands     │ [table 482 rows]  │
│ aliases      │ [table 66 rows]   │
│ modules      │ [list 2 items]    │
│ engine_state │ {record 7 fields} │
╰──────────────┴───────────────────╯
```
I understand that this is rather a dense structure, but I would at least expect that the scope table's relatively short column names are displayed, and then their *values* are truncated to nothing, rather than just hiding the entire table.

Actually, I don't suppose there's any code for truncating _just_ the values of a column yet, is there…?

### Screenshots

_No response_

### Configuration

| key                | value                                           |
| ------------------ | ----------------------------------------------- |
| version            | 0.70.0                                          |
| branch             |                                                 |
| commit_hash        | 9ef65dcd692b502d7476b1787247fae8638c2f0c        |
| build_os           | windows-x86_64                                  |
| build_target       | x86_64-pc-windows-msvc                          |
| rust_version       | rustc 1.64.0 (a55dd71d5 2022-09-19)             |
| rust_channel       | stable-x86_64-pc-windows-msvc                   |
| cargo_version      | cargo 1.64.0 (387270bc7 2022-09-16)             |
| pkg_version        | 0.70.0                                          |
| build_time         | 2022-10-18 18:55:02 +00:00                      |
| build_rust_channel | release                                         |
| features           | database, dataframe, default, trash, which, zip |
| installed_plugins  |                                                 |

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by zhiburt**
fix #6851

### CODE REVIEW

**Comment by sholderbach** [comment]
Will there be a conflict with #6885?

**Comment by zhiburt** [comment]
> Will there be a conflict with https://github.com/nushell/nushell/pull/6885?

likely

**Comment by jntrnr** [comment]
Do you have a screenshot for what the new version will look like?

**Comment by zhiburt** [comment]
Hi @jntrnr 

You can take a look at #6851, for ongoing discussion (as I have still a question).

> Do you have a screenshot for what the new version will look like?

### main

image

### PR

image

**Comment by sholderbach** [comment]
I like the change and vote for landing it, should make browsing json, yaml etc. much more pleasant. 
I think a separate issue we should address is that bare strings get treated as single entry lists through the expansion.

**Comment by fdncred** [comment]
I vote to land this as well. I'd like to get some good testing in before our next release.

**Pull request merged**
