### PR TITLE
Tab inline completion

### PR DESCRIPTION
**Pull request by dandavison**
This PR makes nushell tab completion behave more like zsh/bash. See https://github.com/nushell/reedline/pull/498

### CODE REVIEW

**Comment by jntrnr** [comment]
We chatted about this during today's design meeting and we'd like to land this since we just put out a release. That gives us time to try it out and tweak the new approach.

**Comment by rgwood** [comment]
This might have broken history search. If I open history with `ctrl+r` and then type some text, the history menu is not filtered by that text.

image

dbuch on Discord reports that reverting this PR fixes the issue.

**Comment by dandavison** [comment]
> This might have broken history search.

Thanks @rgwood. #6835 fixes it.

**Comment by rgwood** [comment]
Thank you for the quick fix!

**Pull request merged**
