### PR TITLE
std lib: extend test runner capabilities

### PR DESCRIPTION
**Pull request by presidento**
I am implementing a nu plugin, and want to unit test that it works well.

# Basic usage (unchanged)

image

# Select the folder to run tests within (subfolders included)

image

# Select module to run tests within

image

# Select test command to run

image

# Complex usage

image

### CODE REVIEW

**Comment by amtoine** [comment]
the tests of the existing library are broken, let me fix them and i'll come back to this PR right after the changes have been applied :wink:

**Comment by amtoine** [comment]
- see #8504 for the fix :+1:

**Comment by amtoine** [comment]
in the meantime, to help the developer trying to run the new tests runner, i think a `--list` option to list all the modules and their respective available commands would be very nice :open_mouth:

and also allowing to pass multiple modules and commands maybe?
not sure how easy that would be though :thinking:

**Comment by presidento** [comment]
I was thinking about `--dry-run` or `--dry`. I think it describes better what it does. And as I remember, other thest suites uses something similar. Do you prefer `--list` instead?

At first step I do not want implement support for multiple modules & commands. I _can_ be useful, but until somebody really needs it for me it seems to me L'art pour L'art work. (Also can be workarounded easily with chained commands.)

**Comment by amtoine** [comment]
> I was thinking about `--dry-run` or `--dry`. I think it describes better what it does. And as I remember, other thest suites uses something similar. Do you prefer `--list` instead?
> 
i would say `--list` is more `nushell`y :yum: 
and to me, it represents more what it does, i.e. listing available options :+1: 

> At first step I do not want implement support for multiple modules & commands. I _can_ be useful, but until somebody really needs it for me it seems to me L'art pour L'art work. (Also can be workarounded easily with chained commands.)
>
yeah you got a point, never mind about that one :wink: 

something like this, right? :smirk: 
```rust
def "multi-test" [] {
    let tests = $in

    let runner = (
        git rev-parse --show-toplevel
        | str trim
        | path join "crates" "nu-utils" "standard_library" "tests.nu"
    )

    $tests
    | transpose module command
    | flatten
    | each {|test|
        nu $runner --module $test.module --command $test.command
    }
}

{foo: [f1 f2 f3], bar: [b1 b4]} | multi-test
```

**Comment by presidento** [comment]
That can be an example. The other one is just `nu tests.nu --module test_a; nu tests.nu --module test_b`. I think it is rarely needed. The typical use case is to run just a given command for TDD, or run the tests for my currently developed module.

I added `--list` option.

**Review by amtoine — APPROVED** [review]
thanks for the `--list` option and the extended documentation :ok_hand:

**Comment by presidento** [comment]
Conflict with main branch is resolved.

**Comment by presidento** [comment]
Master is merged to get rid of CI errors.

**Review by amtoine — APPROVED** [review]
looks good to me :ok_hand:

**Comment by sholderbach** [comment]
Then let's give this a shot! Thanks!

**Pull request merged**
