### PR TITLE
Add support for optional list stream output formatting

### PR DESCRIPTION
**Pull request by panicbit**
# Description

Some commands like `ls` or `find` have the desire to show or highlight data in a certain way if shown to the user.
Currently there are two strategies to implement this:

- the `ls` way: metadata is set to signal to the `table` command to format the data a specific way. The logic for how to format the `ls` output is hardcoded into `table`. Adding other commands would require further polluting `table` with more code that is not relevant to `table`s core functionality.
- the `find` way: the data in the stream is modified to contain ansi escapes. This is flexible in that formatting logic stays encapsulated in the original command, but has the downside of making the data stream unusable for further processing.

This PR enables a third approach:
`ListStream` elements can now have an optional `ValueFormatter`. A `ValueFormatter` is at it's core just a glorified function `fn (Value) -> Value`. Its purpose is to be produced by commands like `ls`, `find`, or any other command that wishes a value to be presented to the user in a custom way. The intended consumer of `ValueFormatter`s is the `table` command and possibly other future commands that are intended to present data to the user. A command is always free to discard / ignore a `ValueFormatter` if it has no use for it, which applies to most commands.

This PR does **not** change any command to make use of `ValueFormatter` yet.

In the future this design could be naturally extendend to also work with `PipelineData` other than `ListStream`.

# Tests

Make sure you've done the following:

- [x] Add tests that cover your changes, either in the command examples, the crate/tests folder, or in the /tests folder.
- [ ] Try to think about corner cases and various ways how your changes could break. Cover them with tests.
- [ ] If adding tests is not possible, please document in the PR body a minimal example with steps on how to reproduce so one can verify your change works.

Make sure you've run and fixed any issues with these commands:

- [x] `cargo fmt --all -- --check` to check standard code formatting (`cargo fmt --all` applies these changes)
- [x] `cargo clippy --workspace --features=extra -- -D warnings -D clippy::unwrap_used -A clippy::needless_collect` to check that you're using the standard code style
- [x] `cargo test --workspace --features=extra` to check that all the tests pass (1 test already failed without changes)

### CODE REVIEW

**Comment by panicbit** [comment]
Ideally I'd like to add an example command that demonstrates this new mechanism, but I'm not sure what the best way to do it would be. I could implement it as test, but I think due to the way the new mechanism works I'd have to compare against the exact rendered output of `table`, which doesn't sound exactly stable / reliable to me.
Any suggestions?

**Comment by fdncred** [comment]
This sounds interesting to me, although it's kind of hard to test as is. 

To me it also sounds like test would be the best place for that. The only other thing I can think of is having a base command called `test` and some subcommands called `valueformatter`, `find`, `ls`, `sqlite`, `whatever` that do something different. i'm just not sure how this would be different than unit tests and integration tests.

**Comment by panicbit** [comment]
I've added [a test](https://github.com/nushell/nushell/pull/6325/files#diff-f0c41f4756a0932c64ca33dac24f72d921b45ce29fe2312c7097753a51c6e0cdR584-R643) that exercises the new code path in the table viewer.

**Comment by panicbit** [comment]
> One last thought. I wonder what this does to performance. Faster? Slower? The same?

Is there any way I can conveniently bench the performance?

At any rate, performance changes *should* be within a negligible range, since this change only adds a second tuple field in the list stream and most commands completely ignore it.
For ValueFormatter consumers (viewers like table) the performance should be most affected if there is actually a formatter set.
For ValueFormatter producers (like ls/find), the performance should be most affected if they need to recreate the formatter all the time (instead of just cheaply cloning existing `ValueFormatter`, which uses `Arc` under the hood). Luckily neither `ls` nor `find` require this.

**Comment by fdncred** [comment]
> Is there any way I can conveniently bench the performance?

We really need something like the `1..100000` benchmark but that uses the valueformatter somehow.

I'm also wondering how this would/could/should affect theming because theming is mostly done now by coloring datatypes and shapes, each datatype is obviously a value. You can see the light and dark themes in the default_config.nu.

**Comment by panicbit** [comment]
Theming should be unaffected unless the formatter adds colors via ansi escape codes, in which case the formatter is responsible for respecting relevant color settings.

**Comment by fdncred** [comment]
ok @panicbit let's try it. thanks.

**Comment by panicbit** [comment]
Thank's, I'll follow up with the ports of `ls` and `find` (am I missing some other commands here?) soon-ish!

**Comment by fdncred** [comment]
There are other commands that should color the output with ls colors that don't work like I believe things like `ls | upset {}` but I'm not sure exactly if that falls into this category. tbh, you'll probably have to tell me which commands fit.

**Pull request merged**
