### PR TITLE
Rename `count` to `length`

### PR DESCRIPTION
**Pull request by John-Goff**
I was discussing with @jonathandturner on discord, and I mentioned that I kept looking for a `length` function and not knowing that in nu it is `count`. I think the reason `length` to me feels more natural is that this is how it is called in most other programming languages, at least ones that I am familiar with. Some examples:

In Elixir, the equivalent function is `length`: `length(list)`
In Ruby, there is a `length` attribute: `list.length`, as well as `count`: `list.count`
In JavaScript, there is a `length` attribute: `list.length`
In Rust, there is a `len` method: `list.len()`, as well as `count`: `list.count()`
In Python, there is a `len` function: `len(list)`
In Go, there is a `len` function: `len(list)`

Ruby and Rust seem to be the only ones which use `count`, and in both of them the `count` method works slightly differently to `length` which is why there is both methods.

### CODE REVIEW

**Comment by jonathandturner** [comment]
Looks great!

**Comment by alok** [comment]
bikeshedding, but maybe 'len' would've been better, since it's a commonly typed command, especially in pipelines.

**Comment by sunfishcode** [comment]
> In Elixir, the equivalent function is length: length(list)
In Ruby, there is a length attribute: list.length, as well as count: list.count
In JavaScript, there is a length attribute: list.length
In Rust, there is a len method: list.len(), as well as count: list.count()
In Python, there is a len function: len(list)
In Go, there is a len function: len(list)

In all those languages except Elixir, `len`/`length` is for a constant-time operation on a collection that knows its length. In languages which have a `count`, Rust and Ruby, `count` is a linear-time operation on an iterator/enumerable. Another relevant language here is Unix shell scripting, where this is `wc -l`, where the `c` is for "count" (`l` is for "lines").

Because of my familiarity with those languages, it subjectively feels to me like `| length` is encouraging me to think in terms of passing in an eagerly-collected list, while `| count` is encouraging me to think in terms of streaming data in.

**Comment by shado23** [comment]
> I was discussing with @jonathandturner on discord, and I mentioned that I kept looking for a length function and not knowing that in nu it is count. 

Funny that. I just starting using nu and was thoroughly confused there wasn't a 'count' function, then I tried 'size' and ultimately had to look up that it was 'length', which seemed to be unlikely to me because it's too long for a frequently used shell command. I agree with @sunfishcode that 'length' would be good name if we were dealing with lists here, but since we're dealing with tables 'count' is much more appropriate, especially to people familiar with SQL. I expected 'count' because you already have 'where'. If you want to keep 'length' and be consistent you should rename 'where' to 'filter' (and probably 'select' to 'get', or something like that).

**Pull request merged**
