### PR TITLE
Support kitty key modifiers in keybindings

### PR DESCRIPTION
**Pull request by replcat**
# Description
hi hi, this makes the parsing of modifier key combos in config more general, and adds support for additional kitty keyboard protocol modifiers. It seems that support for [kitty keys](https://sw.kovidgoyal.net/kitty/keyboard-protocol) had already been added to nushell in https://github.com/nushell/nushell/pull/10540, and this was the only missing piece to making them available in keybindings.

# User-Facing Changes
- keybindings in config can include the super, hyper and meta modifiers (e.g. `modifier: super`, `modifier: shift_super`, etc.), and these modifiers will work in supporting terminals (kitty, foot, wezterm, alacritty...)
- all permutations of snake_cased modifier combinations now behave equivalently for the purpose of describing keybindings in config (e.g. `control_alt_shift` was previously supported where `shift_control_alt` was a config error — now they're the same)

# Tests
None of this looks to be tested at the moment. I only found a smoke test under the nu-cli crate, and I couldn't break tests elsewhere by stuffing around with modifier handling. Works on my machine, though! ✨🌈

### CODE REVIEW

**Comment by fdncred** [comment]
Thanks for jumping in to complete this. I would be nice if you added whatever other modifiers are in the kitty protocol so we could finish this once and for all.

**Review by sholderbach — COMMENTED** [review]
I like the simplification of the code, we should make sure that our `keybindings` commands also support `super` or the other modifiers up for discussion. As they are only supported to be passed to the terminal on a subset of platforms and terminals, it is paramount that users can check them properly with `keybindings listen` before they wonder "why isn't this binding working on my terminal"

(EDIT:) Another thing to sanity check would be if there are some accidental filters for modifier keys in reedline. I don't think in emacs mode but there could be limitations for vi mode.

**Comment by replcat** [comment]
@fdncred I've added the remaining hyper and meta modifiers which are explicitly supported by crossterm.

@sholderbach Yep, I came to the particular change in this PR via looking at reedline and nu's `keybindings listen` — both seemed to support kitty modifiers already.

I've pushed the reedline test which I'd used check support over there (see https://github.com/nushell/reedline/pull/831) if there's worries about vi mode possibly complicating things in the future.

**Comment by replcat** [comment]
Just a thought: at the cost of making the config API a bit sprawling, there's an opportunity here to include aliases like `ctrl`, `cmd`, `win`, `command`, `windows` as aliases in the modifier strings, so that someone entering e.g. `cmd_shift` won't have to find out from an error that they needed to specially use `super`, for example.

**Comment by fdncred** [comment]
Thanks for your help @replcat!

**Comment by fdncred** [comment]
It just occured to me that super, hyper, and meta are not represented in `keybindings list` as modifiers and should be. It would be cool if someone updates that command to add them.

**Pull request merged**
