### PR TITLE
DRAFT: Logical operators on commands

### PR DESCRIPTION
**Pull request by dheater**
# Description

Add handling for joining commands with logical && and ||.
ex. sudo apt update && sudo apt list --upgradable
ex. tmux attach || tmux

# Tests

Make sure you've done the following:

- [ ] Add tests that cover your changes, either in the command examples, the crate/tests folder, or in the /tests folder.
- [ ] Try to think about corner cases and various ways how your changes could break. Cover them with tests.
- [ ] If adding tests is not possible, please document in the PR body a minimal example with steps on how to reproduce so one can verify your change works.

Make sure you've run and fixed any issues with these commands:

- [ ] `cargo fmt --all -- --check` to check standard code formatting (`cargo fmt --all` applies these changes)
- [ ] `cargo clippy --workspace --features=extra -- -D warnings -D clippy::unwrap_used -A clippy::needless_collect` to check that you're using the standard code style
- [ ] `cargo test --workspace --features=extra` to check that all the tests pass

### CODE REVIEW

**Comment by jntrnr** [comment]
Nice - it's good to see someone working on this one

**Comment by dheater** [comment]
Looks like you've already done part of this on #4668 @jntrnr 

Simple commands like `false || true` work, but a command like `pwd && echo done` yeilds => `pwd: ignoring non-option arguments`

Do you have recommendations on how to approach this?

**Comment by jntrnr** [comment]
@dheater - you'll need to figure out if you're in "math mode" parsing or "command mode" parsing. The parser already does this, but you'll need to change lexing/lite-parsing to work a bit differently so the parser can use it

You can look at `is_math_expression_like` to see how to know if you're beginning to parse a math expression or a command.

**Comment by jntrnr** [comment]
Another idea would be to make `and` and `or` the boolean operators and `&&` and `||` the command connectors

**Comment by dheater** [comment]
> Another idea would be to make `and` and `or` the boolean operators and `&&` and `||` the command connectors

I like `and` and `or` for readability, but I think `&&` and `||` should also be accepted (aliases) since they're usage is common (principle of least surprise)

**Comment by dheater** [comment]
> @dheater - you'll need to figure out if you're in "math mode" parsing or "command mode" parsing. The parser already does this, but you'll need to change lexing/lite-parsing to work a bit differently so the parser can use it

Maybe I'm missing something. It seems to me that "math mode" and "command mode" shouldn't need different logic. If we parse an expression to be broken into sub expressions (as is done with the `;` operator) and evaluate the sub-expressions in left to right order with continued sub-expression evaluation dependent on the "truthiness" of the preceding sub-expression, then I don't think it should matter ff the sub-expressions are mathematical or commands.

Is there something I'm missing there?

**Comment by ite-klass** [comment]
Was this discarded?

**Pull request closed without merging**
