### PR TITLE
Enforce nightly toolchain

### PR DESCRIPTION
**Pull request by vthriller**

### CODE REVIEW

**Comment by jonathandturner** [comment]
Can it be set to a specific nightly? If so, we could set it to be the same version we're using for the CI

**Comment by vthriller** [comment]
> Can it be set to a specific nightly?

It sure can; [here's how servo does that](https://github.com/servo/servo/blob/master/rust-toolchain).

**Comment by jonathandturner** [comment]
Cool. If that works, you might want to point to the same compiler version the CI server is using: https://github.com/nushell/nushell/blob/master/.azure/azure-pipelines.yml (at the top of the file)

Maybe there's a slick way to keep these in sync, but it's probably not too bad to just edit two files instead of just one

**Comment by est31** [comment]
see also #377

**Comment by vthriller** [comment]
> Maybe there's a slick way to keep these in sync

I also pushed a commit that replaced variables in `azure-pipelines.yml` with read from a file on a `rustup` step.

**Comment by jonathandturner** [comment]
Thanks!

**Pull request merged**
