### PR TITLE
Update SHLVL (only when interactive) on startup

### PR DESCRIPTION
**Pull request by rikukiix**
# Description

Make NuShell correctly inherit and update `SHLVL` from other shells (obviously including itself) in Unix environment.

See issue #14384

# User-Facing Changes

None

# Tests + Formatting

New code formatted.

New feature works well in interactive usage.

# After Submitting

### CODE REVIEW

**Comment by sholderbach** [comment]
We shouldn't need an update on exit as the parent process has its own environment which we received as a copy on startup, right?

**Comment by rikukiix** [comment]
> What's the harm of having this on Windows? I really don't like platform specific code if it's not absolutely required.

There's no harm. I limit the platform just because no shell on Windows uses `SHLVL` as far as I know.

**Comment by rikukiix** [comment]
> We shouldn't need an update on exit as the parent process has its own environment which we received as a copy on startup, right?

Yes, that makes sense.

**Comment by rikukiix** [comment]
> What's the harm of having this on Windows? I really don't like platform specific code if it's not absolutely required.

Of course this platform limit can be removed if needed.

**Comment by sholderbach** [comment]
According to https://learn.microsoft.com/en-us/windows/win32/procthread/environment-variables the number of environment variables was last limited on XP which we don't support so that should not directly harm (and the startup cost for a few extra bytes should be minimal)

**Comment by fdncred** [comment]
Also, is SHLVL supposed to be based on `is_interactive()`? So, `nu -c blah.nu` isn't supposed to increment it, run blah.nu, then it's decremented after that shell exits?

This is what the bash manpage says, `SHLVL  Incremented by one each time an instance of bash is started.` The zsh help says, `SHLVL <S> Incremented by one each time a new shell is started.`.

However, `zsh -c "print $SHLVL"` prints 1, even from inside of zsh. I don't see any docs that say "interactive sessions only" but zsh seems to work that way.

**Comment by fdncred** [comment]
I'd definitely enable SHLVL on Windows. One reason is that it may make some scripts more portable.

**Comment by rikukiix** [comment]
> How does this work with an `exec nu`? It shouldn't increment in the case of a process replacement, right? I don't see any special handling for that here, though.

It works properly.

**Comment by fdncred** [comment]
ok, let's try it. Thanks

**Comment by NotTheDr01ds** [comment]
> > How does this work with an `exec nu`? It shouldn't increment in the case of a process replacement, right? I don't see any special handling for that here, though.
> 
> It works properly.

I should have tested this earlier, but it doesn't seem to be working properly.  See #14567.

**Pull request merged**
