### PR TITLE
Don't redraw prompt when transient prompt disabled

### PR DESCRIPTION
**Pull request by ysthakur**
# Description

moonlander pointed out in Discord that the transient prompt feature added in release 0.86 (implemented in #10391) is causing the normal prompt to be redrawn when the transient prompt variables are unset or set to null. This PR is for fixing that, although it's more of a bandaid fix. Maybe the transient prompt feature should be taken out entirely for now so more thought can be given to its implementation.

Previously, I'd thought that when reedline redraws the prompt after a command is entered, it's a whole new prompt, but apparently it's actually the same prompt as the current line (?). So now, `nu_prompt` in `repl.rs` is an `Arc<RwLock<NushellPrompt>>` (rather than just a `NushellPrompt`), and this `Arc` is shared with the `TransientPrompt` object so that if it can't find one of the `TRANSIENT_PROMPT_*` variables, it uses a segment from `NushellPrompt` rather than re-evaluate `PROMPT_COMMAND`, `PROMPT_COMMAND_RIGHT`, etc. Using an `RwLock` means that there's a bunch of `.expect()`s all over the place, which is not nice. It could perhaps be avoided with some changes on the reedline side.

# User-Facing Changes

`$env.PROMPT_COMMAND` (and other such variables) should no longer be executed twice if the corresponding `$env.TRANSIENT_PROMPT_*` variable is not set.

# Steps to reproduce

Described by moonlander in Discord [here](https://discord.com/channels/601130461678272522/614593951969574961/1164928022126792844).

Adding this to `env.nu` will result in `11` being added to `/tmp/run_count` every time any command is run. The expected behavior is a single `1` being added to `/tmp/run_count` instead of two. The prompt command should not be executed again when the prompt is redrawn after a command is executed.

```nu
$env.PROMPT_COMMAND = {||
  touch /tmp/run_count
  '1' | save /tmp/run_count --append
  '>'
}

# $env.TRANSIENT_PROMPT_COMMAND not set
```

If the following is added to `env.nu`, then `12` will be added to `/tmp/run_count` every time any command is run, which is expected behavior because the normal prompt command must be displayed the first time the prompt is shown, then the transient prompt command is run when the prompt is redrawn.
```nu
$env.TRANSIENT_PROMPT_COMMAND = {||
  touch /tmp/run_count
  '2' | save /tmp/run_count --append
  '>'
}
```

Here's a screenshot of what adding that first snippet looks like (`cargo run` in the `main` branch):
image

Here's a screenshot of what it looks like with this PR (only one `1` is added to `/tmp/run_count` each time):
image

### CODE REVIEW

**Comment by fdncred** [comment]
Converting to draft as I think we were deferring to @CAD97's PR.

**Comment by ysthakur** [comment]
I'd be fine with closing it, since it can be reopened at any time

**Comment by fdncred** [comment]
closing in favor of https://github.com/nushell/nushell/pull/10986

**Comment by fdncred** [comment]
Well darn, #10986 didn't work. Now what?

**Comment by fdncred** [comment]
@ysthakur I'm wondering if you can update this to the latest main and let us try again since @CAD97's didn't work?

**Comment by ysthakur** [comment]
> Well darn, https://github.com/nushell/nushell/pull/10986 didn't work. Now what?

Welp, that was a really nice approach. Maybe there's just a minor bug somewhere, I can try to make it work later

**Comment by fdncred** [comment]
I tried yours out and it didn't seem to have the same problem with cad's. i'm good with whatever works.

**Comment by ysthakur** [comment]
@fdncred We can merge this now and I (or CAD97 themselves) can try to adapt their fix later

**Comment by fdncred** [comment]
let's try it

**Pull request merged**
