### PR TITLE
Include subcommands in `help commands`

### LINKED ISSUE #2561: `help commands` include subcommands
**Is your feature request related to a problem? Please describe.**
`help commands` only shows the toplevel commands. There's no easy way to also enumerate the subcommands.

**Describe the solution you'd like**
Some ideas:

**Idea 1**
`help commands` would also show subcommands, all under the existing `name` column.

**Idea 2**
`help commands` would also show subcommands, but in another column:

| command | subcommand | description |
|-|-|-|
| ... | ... | ... |
| str | | description |
| str | camel-case | description |
| str | capitalize | description |
| ... | ... | ... |
|-|-|-|

**Idea 3**
`help commands` shows the root commands, but also includes a column stating whether or not a command has subcommands. `help commands --with-subcommands` would show all commands.

### PR DESCRIPTION
**Pull request by coolshaurya**
resolves #2561

### CODE REVIEW

**Comment by jonathandturner** [comment]
@coolshaurya - can you show a "before" and "after" so we can wee how the output changes?

**Comment by coolshaurya** [comment]
# Before -

### `help commands | last 15`

|name|description|
|-|-|
|table|View the contents of the pipeline as a table.|
|tags|Read the tags (metadata) for values.|
|textview|Autoview of text data.|
|to|Convert table into an output format (based on subcommand, like csv, html, json, yaml).|
|touch|creates one or more files|
|tree||
|uniq|Return the unique rows|
|update|Update an existing column to have a new value.|
|update-nu||
|url|Apply url function|
|version|Display Nu version|
|where|Filter table to match the condition.|
|which|Finds a program file.|
|with-env|Runs a block with an environment set. Eg) with-env [NAME 'foo'] { echo $nu.env.NAME }|
|wrap|Wraps the given data in a table.|

# After - 

### `help commands | last 15`

|name|description|subcommands|
|-|-|-|
|table|View the contents of the pipeline as a table.||
|tags|Read the tags (metadata) for values.||
|textview|Autoview of text data.||
|to|Convert table into an output format (based on subcommand, like csv, html, json, yaml).|[table 9 rows]|
|touch|creates one or more files||
|tree|||
|uniq|Return the unique rows||
|update|Update an existing column to have a new value.||
|update-nu|||
|url|Apply url function|[table 4 rows]|
|version|Display Nu version||
|where|Filter table to match the condition.||
|which|Finds a program file.||
|with-env|Runs a block with an environment set. Eg) with-env [NAME 'foo'] { echo $nu.env.NAME }||
|wrap|Wraps the given data in a table.||

### `help commands | where name == url | get subcommands`

|name|description|
|-|-|
|url host|gets the host of a url|
|url path|gets the path of a url|
|url query|gets the query of a url|
|url scheme|gets the scheme (eg http, file) of a url|

**Comment by jonathandturner** [comment]
Cool. thanks!

**Comment by fdncred** [comment]
@coolshaurya When I do `help commnads` I get a command name `s`. When I do `help commands | where name == "s"` I get this
```
═══╦══════╦═════════════╦═════════════════
 # ║ name ║ description ║ subcommands
═══╬══════╬═════════════╬═════════════════
 0 ║ s    ║             ║ [table 30 rows]
═══╩══════╩═════════════╩═════════════════
```

if I do this
`help commands | where name == "s" | get subcommands`

I get this
```
════╦══════════════════════════╦══════════════════════════════════════════════════════════════════════════════════════════════════════════
 #  ║ name                     ║ description
════╬══════════════════════════╬══════════════════════════════════════════════════════════════════════════════════════════════════════════
  0 ║ skip until               ║ Skips rows until the condition matches.
  1 ║ skip while               ║ Skips rows while the condition matches.
  2 ║ split chars              ║ splits a string's characters into separate rows
  3 ║ split column             ║ splits contents across multiple columns via the separator.
  4 ║ split row                ║ splits contents over multiple rows via the separator.
  5 ║ str camel-case           ║ converts a string to camelCase
  6 ║ str capitalize           ║ capitalizes text
  7 ║ str collect              ║ collects a list of strings into a string
  8 ║ str contains             ║ Checks if string contains pattern
  9 ║ str downcase             ║ downcases text
 10 ║ str ends-with            ║ checks if string ends with pattern
 11 ║ str find-replace         ║ finds and replaces text
 12 ║ str from                 ║ Converts numeric types to strings. Trims trailing zeros unless decimals parameter is specified.
 13 ║ str index-of             ║ Returns starting index of given pattern in string counting from 0. Returns -1 when there are no results.
 14 ║ str kebab-case           ║ converts a string to kebab-case
 15 ║ str length               ║ outputs the lengths of the strings in the pipeline
 16 ║ str ltrim                ║ trims whitespace or character from the beginning of text
 17 ║ str pascal-case          ║ converts a string to PascalCase
 18 ║ str reverse              ║ outputs the reversals of the strings in the pipeline
 19 ║ str rtrim                ║ trims whitespace or character from the end of text
 20 ║ str screaming-snake-case ║ converts a string to SCREAMING_SNAKE_CASE
 21 ║ str set                  ║ sets text
 22 ║ str snake-case           ║ converts a string to snake_case
 23 ║ str starts-with          ║ checks if string starts with pattern
 24 ║ str substring            ║ substrings text
 25 ║ str to-datetime          ║ converts text into datetime
 26 ║ str to-decimal           ║ converts text into decimal
 27 ║ str to-int               ║ converts text into integer
 28 ║ str trim                 ║ trims text
 29 ║ str upcase               ║ upcases text
════╩══════════════════════════╩══════════════════════════════════════════════════════════════════════════════════════════════════════════
```

was this the intent?  Why am I getting `s` as a command?

**Comment by fdncred** [comment]
ok, i know why i'm getting `s` as a command thanks to @jonathandturner. I have an `s` alias, but it doesn't explain the rest.

**Pull request merged**
