### PR TITLE
Move dataframes support to a plugin

### PR DESCRIPTION
**Pull request by ayax79**
WIP

This PR covers migration crates/nu-cmd-dataframes to a new plugin ./crates/nu_plugin_polars

## TODO List

Other:
- [X] Fix examples
- [x] Fix Plugin Test Harness
- [X] Move Cache to Mutex<BTreeMap>
- [X] Logic for disabling/enabling plugin GC based off whether items are cached.
- [x] NuExpression custom values
- [X] Optimize caching (don't cache every object creation). 
- [x] Fix dataframe operations (in NuDataFrameCustomValue::operations)
- [x] Added plugin_debug! macro that for checking an env variable POLARS_PLUGIN_DEBUG 

Fix duplicated commands:
- [x] There are two polars median commands, one for lazy and one for expr.. there should only be one that works for both. I temporarily called on polars expr-median (inside expressions_macros.rs)
- [x] polars quantile (lazy, and expr). the expr one is temporarily expr-median
- [x] polars is-in (renamed one series-is-in)

Commands:
- [x] AppendDF
- [x] CastDF
- [X] ColumnsDF
- [x] DataTypes
- [x] Summary
- [x] DropDF
- [x] DropDuplicates
- [x] DropNulls
- [x] Dummies
- [x] FilterWith
- [X] FirstDF
- [x] GetDF
- [x] LastDF
- [X] ListDF
- [x] MeltDF
- [X] OpenDataFrame
- [x] QueryDf
- [x] RenameDF
- [x] SampleDF
- [x] SchemaDF
- [x] ShapeDF
- [x] SliceDF
- [x] TakeDF
- [X] ToArrow
- [x] ToAvro
- [X] ToCSV
- [X] ToDataFrame
- [X] ToNu
- [x] ToParquet
- [x] ToJsonLines
- [x] WithColumn
- [x] ExprAlias
- [x] ExprArgWhere
- [x] ExprCol
- [x] ExprConcatStr
- [x] ExprCount
- [x] ExprLit
- [x] ExprWhen
- [x] ExprOtherwise
- [x] ExprQuantile
- [x] ExprList
- [x] ExprAggGroups
- [x] ExprCount
- [x] ExprIsIn
- [x] ExprNot
- [x] ExprMax
- [x] ExprMin
- [x] ExprSum
- [x] ExprMean
- [x] ExprMedian
- [x] ExprStd
- [x] ExprVar
- [x] ExprDatePart
- [X] LazyAggregate
- [x] LazyCache
- [X] LazyCollect
- [x] LazyFetch
- [x] LazyFillNA
- [x] LazyFillNull
- [x] LazyFilter
- [x] LazyJoin
- [x] LazyQuantile
- [x] LazyMedian
- [x] LazyReverse
- [x] LazySelect
- [x] LazySortBy
- [x] ToLazyFrame
- [x] ToLazyGroupBy
- [x] LazyExplode
- [x] LazyFlatten
- [x] AllFalse
- [x] AllTrue
- [x] ArgMax
- [x] ArgMin
- [x] ArgSort
- [x] ArgTrue
- [x] ArgUnique
- [x] AsDate
- [x] AsDateTime
- [x] Concatenate
- [x] Contains
- [x] Cumulative
- [x] GetDay
- [x] GetHour
- [x] GetMinute
- [x] GetMonth
- [x] GetNanosecond
- [x] GetOrdinal
- [x] GetSecond
- [x] GetWeek
- [x] GetWeekDay
- [x] GetYear
- [x] IsDuplicated
- [x] IsIn
- [x] IsNotNull
- [x] IsNull
- [x] IsUnique
- [x] NNull
- [x] NUnique
- [x] NotSeries
- [x] Replace
- [x] ReplaceAll
- [x] Rolling
- [x] SetSeries
- [x] SetWithIndex
- [x] Shift
- [x] StrLengths
- [x] StrSlice
- [x] StrFTime
- [x] ToLowerCase
- [x] ToUpperCase
- [x] Unique
- [x] ValueCount

### CODE REVIEW

**Comment by devyn** [comment]
I'm so excited about this!

**Comment by fdncred** [comment]
wow, this already is and will be amazing! it's hard for me to believe we could have dataframes in a plugin. we've literally talked about this for years.

**Comment by fdncred** [comment]
@elferherrera as the original author of our dataframes (and lots of other stuff), I wanted to tag you here so you can see this work happening because we've discussed dfrs as plugins before. It appears that we're getting close.

**Comment by devyn** [comment]
I got a chance to try this out and see your progress - it's really cool to see this working!

I have a few ideas:

- You should probably try to set up the examples to return a custom value that won't get registered, and modify your test harness to treat it the same way. This could be a custom value that contains `NuDataFrame` / `NuLazyFrame` that always causes an error on serialize/deserialize - if you want to cheat you could do an enum with only one variant that is `#[serde(skip)]`
- Suggest using just a single `BTreeMap` behind a `Mutex` for the cache as long as your operations on it are fast (you just clone an arc or something) - it will likely be faster, and you can make more solid atomic guarantees
- When creating a dataframe, you can do `engine.set_gc_disabled(true)` to ensure the plugin doesn't exit. I would do this inside the mutex lock somehow
- When dropping a dataframe, you can do `engine.set_gc_disabled(false)` to enable the GC again, as long as you can guarantee there isn't a race condition. Again, inside the mutex lock preferably
- For `to_base_value()`, if you want the old behavior of showing the types under the column name, I can confirm that creating a table with column names that have newlines in them does show up properly, e.g. `[["foo\n---\nint"]; [0] [1]]`. Since you have `polars into-nu` anyway, it shouldn't matter that much if `to_base_value()` does something special

**Comment by fdncred** [comment]
> For to_base_value(), if you want the old behavior of showing the types under the column name, I can confirm that creating a table with column names that have newlines in them does show up properly, e.g. [["foo\n---\nint"]; [0] [1]]. Since you have polars into-nu anyway, it shouldn't matter that much if to_base_value() does something special

While having type in the column name could be a cool debug feature. I wouldn't want it to be the default since filtering by it would be a pain with `where` or `filter` or whatever the dfr equivalent is.

This only works if header_on_separator is false.
```nushell
❯ [["foo\n---\nint"]; [0] [1]]
╭─#─┬foo╮
│ 0 │ 0 │
│ 1 │ 1 │
╰───┴───╯
❯ $env.config.table.header_on_separator = false
❯ [["foo\n---\nint"]; [0] [1]] 
╭───┬─────╮
│ # │ foo │
│   │ --- │
│   │ int │
├───┼─────┤
│ 0 │   0 │
│ 1 │   1 │
╰───┴─────╯
```

**Comment by devyn** [comment]
> While having type in the column name could be a cool debug feature. I wouldn't want it to be the default since filtering by it would be a pain with `where` or `filter` or whatever the dfr equivalent is.

Since `to_base_value()` is really only for display purposes, I think it's fine - all of the `dfr` commands work on the internal stuff which just has the column names as is, and `dfr into-nu` would also not format them like that

**Comment by ayax79** [comment]
> * You should probably try to set up the examples to return a custom value that won't get registered, and modify your test harness to treat it the same way. This could be a custom value that contains `NuDataFrame` / `NuLazyFrame` that always causes an error on serialize/deserialize - if you want to cheat you could do an enum with only one variant that is `#[serde(skip)]`
I independently came to the same conclusion... it's in the latest push. I also changed all the cache inserts to be explicit, versus on every object creation as they only need to be cached part of the time. I also changed the implementation of the examples to render the output without caching the dataframes as they didn't seem to get cleared from cache. 

> * Suggest using just a single `BTreeMap` (no need to hash uuids) behind a `Mutex` for the cache as long as your operations on it are fast (you just clone an arc or something) - it will likely be faster, and you can make more solid atomic guarantees
I'll take a look.. I used [DashMap](https://docs.rs/dashmap/latest/dashmap/struct.DashMap.html) out of convenience. 

> * When creating a dataframe, you can do `engine.set_gc_disabled(true)` to ensure the plugin doesn't exit. I would do this inside the mutex lock somehow
> * When dropping a dataframe, you can do `engine.set_gc_disabled(false)` to enable the GC again, as long as you can guarantee there isn't a race condition. Again, inside the mutex lock preferably
Can you explain this a little more.. I would do this on every map insert and remove?

**Comment by devyn** [comment]
> > * When creating a dataframe, you can do `engine.set_gc_disabled(true)` to ensure the plugin doesn't exit. I would do this inside the mutex lock somehow
> > * When dropping a dataframe, you can do `engine.set_gc_disabled(false)` to enable the GC again, as long as you can guarantee there isn't a race condition. Again, inside the mutex lock preferably
> 
> Can you explain this a little more.. I would do this on every map insert and remove? 

You really only have to trigger it if it transitions between empty and non-empty. So you can check if it was empty before and do the call if that changes. 

This is just flipping a bool in the GC, so it stays that way while your plugin is alive. It starts enabled.

It's just to keep your plugin alive while you're storing data, so users don't accidentally lose it and don't have to manually start and stop the plugin.

**Comment by ayax79** [comment]
> > > * When creating a dataframe, you can do `engine.set_gc_disabled(true)` to ensure the plugin doesn't exit. I would do this inside the mutex lock somehow
> > > * When dropping a dataframe, you can do `engine.set_gc_disabled(false)` to enable the GC again, as long as you can guarantee there isn't a race condition. Again, inside the mutex lock preferably
> > 
> > 
> > Can you explain this a little more.. I would do this on every map insert and remove?
> 
> You really only have to trigger it if it transitions between empty and non-empty. So you can check if it was empty before and do the call if that changes.
> 
> This is just flipping a bool in the GC, so it stays that way while your plugin is alive. It starts enabled.
> 
> It's just to keep your plugin alive while you're storing data, so users don't accidentally lose it and don't have to manually start and stop the plugin.

So, it seems like the correct behavior would be: 
1. set gc to false upon first insert
2. set gc to true on the last remove

**Comment by devyn** [comment]
GC stuff seems to work exactly as it should. Nice.

**Comment by ayax79** [comment]
Throwing in a quick update. 

All the core dataframe types (NuDataFrame,NuLazyFrame,etc) are now cached on completion of a command and CustomValues (e.g. NuDataFrameCustomValue) containing just the UUID cache key are returned to the pipeline. The cached values are looked up whenever a CustomValue is passed back to the plugin, either passed through a pipeline call or when a method like Plugin::custom_value_to_base_value is called. 

I have been spending a lot of time cleaning up the various dataframe objects types access patterns to make creation and caching consistent. This will probably break some behaviors in cases like when a NuLazyFrame reference is passed to a NuDataFrame and is just works (the behavior of try_from_value). I think it will be better to handle these more explicitly anyways, rather than creating an object five layers down and trying to determine whether or not it should be cached.

Right now I am waiting on #12279 to land before porting the rest of the commands over. Once it is in, I should be able to port the commands pretty quickly. 

There are also a couple of tweaks that @devyn will be adding to the test support so that I can compare base_value outputs versus the custom value returned from the plugin.

**Comment by fdncred** [comment]
Thanks for your tough and continued work here @ayax79. If devyn can get the conflicts fixed we'll land 12279.

**Comment by fdncred** [comment]
By the time you're finished, you'll either know polars very well, never want to work with polars again, or both. 🤣

**Comment by ayax79** [comment]
I'm definitely learning the ends and outs of **ALL** the dataframe code.

**Comment by devyn** [comment]
You are a machine!

**Comment by ayax79** [comment]
Thanks!

**Comment by ayax79** [comment]
Currently waiting on the following to make it in:
#12418 
#12409

**Comment by fdncred** [comment]
i landed those just now. thanks!

**Comment by fdncred** [comment]
Let's go! Let's give a round of applause to @ayax79 for all the effort put into this PR! 👏🏻👏🏻👏🏻👏🏻👏🏻

**Comment by WindSoilder** [comment]
@ayax79 Thank you for your excellent work!

**Comment by stormasm** [comment]
@ayax79 incredible !!  this is going to be a HUGE STEP forward for the whole data frame concept in concert with Nushell...

super fantastic work.... 😄

**Pull request merged**
