### PR TITLE
Replace `winapi` with `windows`

### PR DESCRIPTION
**Pull request by nibon7**
# Description
`winapi` is not actively maintained, use the Microsoft blessed `windows` crate instead.

# User-Facing Changes
N/A

### CODE REVIEW

**Comment by fdncred** [comment]
The only thing I see not working is `sys`'s `cpu` `load_average` is always 0's. Maybe it was like that before too?

**Comment by fdncred** [comment]
yup, it was like that before. we need to fix that if we can but it's not related to this pr. let's land it. thanks!

**Comment by nibon7** [comment]
Seems `load_average`  does not work on Windows.

https://github.com/GuillaumeGomez/sysinfo/blob/71eb1d6a668e2a7d38d907d7c9b4d72882ed1d4f/src/common.rs#L575

**Comment by fdncred** [comment]
Thanks for looking into it.

**Pull request merged**
