### PR TITLE
rename "nothing" type to `null`

### PR DESCRIPTION
**Pull request by amtoine**
related to
- https://github.com/nushell/nushell/pull/9918

# Description
this PR renames the `nothing` type to `null`.

# User-Facing Changes
`nothing` should be replaced by `null` in type annotations, e.g.
```nushell
def foo []: null -> null {}
```
instead of
```nushell
def foo []: nothing -> nothing {}
```

# Tests + Formatting
should not change anything.

# After Submitting

### CODE REVIEW

**Comment by jntrnr** [comment]
@amtoine -

A couple things:

- this PR is doing more than changing the name of the type to `null`
- I made this draft because we haven't decided on the name of the type, yet

**Comment by amtoine** [comment]
> * this PR is doing more than changing the name of the type to `null`
>
i'm not sure i see what it does more :confused: 
if the type is renamed from `nothing` to `null`, i thought having things like `Value::Nothing` wouldn't make sense anymore and thus renamed them to things like `Value::Null` :yum: 

> * I made this draft because we haven't decided on the name of the type, yet
>
makes sense, it's just the same PR as #9918 :ok_hand:

**Comment by jntrnr** [comment]
@amtoine - the value is different from the type, so the PR should only touch the type.

**Comment by amtoine** [comment]
i see :+1: 

let's close this and rework it once we decide what we do with the `nothing` type :yum:

**Pull request closed without merging**
