### PR TITLE
Fix a crash when moving the cursor after accepting a suggestion from the help menu

### LINKED ISSUE #9627: Panic when trying to do anything after inserting something from the help menu on a non-empty line
### Describe the bug

When you insert some text from the help menu (F1) with a non-empty line or buffer, Nu panics if you try to modify the buffer in any way. For example deleting a char, moving with the arrow keys or inserting something else from a menu. But if the buffer is empty there's no problem.

### How to reproduce

1. Start with an empty line.
2. Type anything such that the buffer is not empty. For example a single char `a` or space ` `
3. Open the help menu with F1 and insert anything
4. Press backspace or any of the arrow keys.
5. Nu panics with `thread 'main' panicked at 'byte index N is out of bounds ...`

Alternatively press tab or F1 again to open another menu after step 3. Then you get `thread 'main' panicked at 'assertion failed: self.is_char_boundary(idx)'`

### Expected behavior

Nu should take into account the existing buffer when you insert something from the help menu and not panic.

### Screenshots

_No response_

### Configuration

| key                | value                                                            |
| ------------------ | ---------------------------------------------------------------- |
| version            | 0.82.0                                                           |
| branch             | makepkg                                                          |
| commit_hash        | ecdb023e2f6cb17445ae799206e464b2daef3d71                         |
| build_os           | linux-x86_64                                                     |
| build_target       | x86_64-unknown-linux-gnu                                         |
| rust_version       | rustc 1.70.0 (90c541806 2023-05-31) (Arch Linux rust 1:1.70.0-1) |
| cargo_version      | cargo 1.70.0                                                     |
| build_time         | 2023-06-28 05:27:55 +00:00                                       |
| build_rust_channel | release                                                          |
| allocator          | standard                                                         |
| features           | dataframe, default, extra, sqlite, trash, which, zip             |
| installed_plugins  |                                                                  |

### Additional context

This happens even without my config if I launch Nu with `nu --no-config-file`

### PR DESCRIPTION
**Pull request by nibon7**
# Description

Fixes #9627 
Related nushell/reedline#602 nushell/reedline#612

# User-Facing Changes

# Tests + Formatting

# After Submitting

### CODE REVIEW

**Review by amtoine — COMMENTED** [review]
@nibon7 
as i said in https://github.com/nushell/nushell/issues/9627, i'm not able to reproduce this on linux, so i'm not able to confirm that these changes, even though quite simple :yum:, fix the issue.

i'll let the decision to someone having access to MacOS and seeing the fix in action :relieved:

**Comment by fdncred** [comment]
I'm wondering if this is already fixed. I cannot reproduce it any longer on MacOS.

**Comment by nibon7** [comment]
I can still reproduce it on linux with the latest main `f61503893835f777c1ade71ec76a6b07fcf818f2`.

Screenshot from 2023-08-05 10-48-24

reproduce steps:
1. enter `a` or anything else
2. press <kbd>F1</kbd> to activate the help menu
3. accept a suggestion(e.g. `echo`)
4. press the arrow keys

**Comment by amtoine** [comment]
thanks @nibon7, i can reproduce the panic now with that precise sequence of keys :+1: 
let me see if this PR fixes it :wink:

**Review by amtoine — COMMENTED** [review]
it fixes https://github.com/nushell/nushell/issues/9627 indeed :ok_hand: 
well done :muscle: 

### newbie question :wink: 
just curious to undestand what `.saturating_sub(start)` adds here :yum: 
it looks like it's just computing `lb.len - (end - start) - start`, with this "*saturation*" thing?

**Comment by fdncred** [comment]
thanks @nibon7

**Pull request merged**
