### PR TITLE
remove nu_cli crate dependency from nu_std

### PR DESCRIPTION
**Pull request by stormasm**
now nu_std only depends on nu_parser, nu_protocol and miette
and removes the nu_cli dependency

this enables developers moving forward to come along and implement their own CLI's without having to pull in a redundant nu-cli which will not be needed for them.

I did this by moving report_error into nu_protocol
which nu_std already has a dependency on anyway....

- `cargo fmt --all -- --check` to check standard code formatting (`cargo fmt --all` applies these changes)
- `cargo clippy --workspace -- -D warnings -D clippy::unwrap_used -A clippy::needless_collect` to check that you're using the standard code style
- `cargo test --workspace` to check that all tests pass
- `cargo run -- crates/nu-std/tests.nu` to run the tests for the standard library

> **Note**
> from `nushell` you can also use the `toolkit` as follows
> ```bash
> use toolkit.nu  # or use an `env_change` hook to activate it automatically
> toolkit check pr
> ```

### CODE REVIEW

**Comment by stormasm** [comment]
@amtoine 

FYI this error is showing up on the main branch prior to my changes

```rust
Error: 
  × error when parsing nuon text
    ╭─[/Users/ma/j/tmp17/nushell/crates/nu-std/tests.nu:83:1]
 83 │             nu -c $'use ($module.file) *; $nu.scope.commands | select name module_name | to nuon'
 84 │             | from nuon
    ·               ────┬────
    ·                   ╰── could not parse nuon text
 85 │             | where module_name == $module.name
    ╰────

Error: 
  × error when parsing
```

**Comment by amtoine** [comment]
thanks for the refactoring, that sounds cleaner to have these error reporting functions in `nu_protocol` right? :yum:

**Comment by amtoine** [comment]
@stormasm 
i cannot reproduce the error your having...
i works on
- latest `main` f2b977b9c59931ad2b5e55174e63ebbec50b8cbe
- the tip of `report_error` 9fbb330e502b368d59893cbd6339b9a4468597ac

:open_mouth:

**Review by amtoine — APPROVED** [review]
looks great and sensible to me :ok_hand:

**Review by sholderbach — APPROVED** [review]
Good call @stormasm

**Pull request merged**
