### PR TITLE
feat: added multiple options to http commands

### PR DESCRIPTION
**Pull request by Sygmei**
# Description

All `http` commands now have a `-f` flag which for now contains the `headers`, `body` and `status` fields (we can later add stuff like `is-redirect` or `cookies`).

image

*Try it yourself*
```
http get http://mockbin.org/bin/630069dc-2c09-483a-a484-672561b7de14
http get -f http://mockbin.org/bin/630069dc-2c09-483a-a484-672561b7de14
```

The `http` commands can also now use the `-e` flag, which stands for `--allow-errors`. When the status code is `>= 400`, it will still allow you to interpret it like a normal response.

image

*Try it yourself*
```
http get http://mockbin.org/bin/2ebd3d27-bdc2-4ee8-b042-0bc2c0d1ad2a # should fail like usual
http get -e http://mockbin.org/bin/2ebd3d27-bdc2-4ee8-b042-0bc2c0d1ad2a # will return the body
http get -e -f http://mockbin.org/bin/2ebd3d27-bdc2-4ee8-b042-0bc2c0d1ad2a # will let you see the full response
```

# User-Facing Changes

- Adds `-f` (`--full`) to all `http` commands
- Adds `-e` (--allow-errors) to all `http` commands

### CODE REVIEW

**Review by rgwood — COMMENTED** [review]
Cool, thanks! It looks good to me from a user-facing perspective. Might be good to get @jaudiger's opinion too, he's been working in this area recently.

Would you be able to add some tests that exercise the new error handling functionality? We can use a mock HTTP server for tests now; see `crates/nu-command/tests/commands/network/http/get.rs` etc. for examples.

**Comment by Sygmei** [comment]
Ah yes sure, I'll add the unit tests :)

**Comment by jaudiger** [comment]
I'll have a look at the PR today, or tomorrow, depending on my spare time.

Anyway, it looks very promising :heart:

**Comment by Sygmei** [comment]
@rgwood @jaudiger added the units tests for `http get` :)

**Comment by rgwood** [comment]
@Sygmei  I haven't figure out why yet, but it seems like this PR broke some uses of `http post`.

I've been playing around with the OpenAI API, and this worked before the PR:

```
let key = "my private API key"

let body = {model: "gpt-3.5-turbo", 
    messages: [{"role": "user", content: "What is the current population of Canada?"}]
}

http post -t 'application/json' -H ["Authorization" $"Bearer ($key)"] https://api.openai.com/v1/chat/completions $body
```

After the PR it fails with a 400. Still looking into it, not sure what broke exactly - maybe something to do with the record-to-JSON conversion?

**Pull request merged**
