### PR TITLE
nu-table: Wrap last column in `table -e`

### LINKED ISSUE #7763: `table -e` should show all columns
### Describe the bug

I noticed when using `help -f` that sometimes `table -e` is producing unhelpful results:

image

1. There's a lot of wasted horizontal space
2. We're not showing all columns (even though there aren't that many columns)

cc: @zhiburt 

### How to reproduce

Run `help -f arg | table -e` in a terminal around 130 columns wide.

### Expected behavior

I expect Nu to show all columns in the result.

### Screenshots

_No response_

### Configuration

| key                | value                                    |
| ------------------ | ---------------------------------------- |
| version            | 0.74.1                                   |
| branch             | main                                     |
| commit_hash        | 5419e8ae9d1ca3b4e22fc4016012eb80ef8f01ff |
| build_os           | linux-x86_64                             |
| build_target       | x86_64-unknown-linux-gnu                 |
| rust_version       | rustc 1.65.0 (897e37553 2022-11-02)      |
| rust_channel       | 1.65.0-x86_64-unknown-linux-gnu          |
| cargo_version      | cargo 1.65.0 (4bc8f24d3 2022-10-20)      |
| pkg_version        | 0.74.1                                   |
| build_time         | 2023-01-11 23:19:39 -08:00               |
| build_rust_channel | release                                  |
| features           | database, default, trash, which, zip     |
| installed_plugins  |                                          |

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by zhiburt**
Hi  @rgwood thank you for report.

So this PR must fix it but I'd make a few runs.

close #7763

### CODE REVIEW

**Comment by fdncred** [comment]
For me:

Before this PR:
image

After this PR:
image

I like the Before better but I'm not sure @rgwood's looks so bad?

**Comment by zhiburt** [comment]
> After this PR:

Tried to mitigate this.
I'd make a few more runs.

@rgwood

**Comment by zhiburt** [comment]
> After this PR:

Tried a few solutions for this.
1. Wrap when there's for example at least 25 chars available
2. Wrap when wrapping amount of chars will be max 2
3. Wrap when the available width is at least equal a width of a column name

Everyone has it's flaws.

Picked a 3rd

**Comment by fdncred** [comment]
I guess this looks a little better than before (171x42 terminal size)
image

It's also interesting that it wraps differently in 80x20 terminal
image

and 111x37 terminal
image

**Comment by zhiburt** [comment]
> It's also interesting that it wraps differently in 80x20 terminal

Good catch.

It's unrelated to original issue but,
Must be better now.

**Comment by zhiburt** [comment]
> I'm wondering if it's possible to detect when the input is going to be nested like $nu | table -e and when it's going to be flat. If that were possible,

It's possible to do, but to guarantee that it's flat we would need to iterate over the dataset which I don't like.

Personally, I like the fact that the `-e` logic is a bit different.

**Comment by fdncred** [comment]
@rgwood, you're the tie breaker. If you're satisfied with these changes, I'd vote with you to land them.

**Review by rgwood — APPROVED** [review]

**Pull request merged**
