### PR TITLE
deprecate `std clip`

### PR DESCRIPTION
**Pull request by amtoine**
related to 
- https://github.com/nushell/nushell/issues/11041
- https://github.com/nushell/nu_scripts/pull/674

cc/ @FMotalleb 

# Description
reading the [frontpage of the standard library](https://github.com/nushell/nushell/blob/main/crates/nu-std/README.md#--welcome-to-the-standard-library-of-nushell--) and according to the last Nushell meeting, i has been agreed that `std clip` does not belong to the standard library :open_mouth: 
- it is not written in pure Nushell and requires external dependencies which might not even work properly as in https://github.com/nushell/nushell/issues/11041
- it is not a building block to build more complex applications

this PR deprecates the `std clip` command in favor of [`modules/system clip`](https://github.com/nushell/nu_scripts/pull/674) for now.

the `std clip` command will be removed in Nushell 0.89.

# User-Facing Changes
the deprecation warning:
std-clip-deprecation
> **Note**
> the link has been changed to the `nu_scripts` in fa6c17da0 according to the review comments

# Tests + Formatting

# After Submitting
this will have to be mentionned in the next release note, namely the slight differences between the two commands.

### CODE REVIEW

**Comment by fdncred** [comment]
I'm not sure recommending a non-nushell supported plugin is the best course of action. I mean, I like the plugin and it works great, but it's not within our control. So, it may be better just to take the code from std clip and put it in a module in nu_scripts. At least then, it's in our control. We could even check for the plugin in the script if we wanted to and use it, otherwise fall back to the more traditional clip functionality.

**Comment by FMotalleb** [comment]
Well, I have to agree with @fdncred 

> I'm not sure recommending a non-nushell supported plugin is the best course of action.

Currently, I maintain the clip plugin although it’s not certain whether I’ll continue to do so over the next years.

+ It’s noteworthy that the `clipboard` is not a common feature in other shells:
    1. It's not a default functionality of OS or any programming language
    2. Even though its behavior is predictable, but unknown in every single environment
 
Considering these points, I would recommend adding this functionality as a `cool script` or a replaceable `plugin`.

In the meantime, don’t hesitate to use this plugin in your script, until the day comes when I decide to retire it, which isn’t in the immediate future as far as I can see.

**Comment by amtoine** [comment]
these are very valid points :pray: 
i'll go ahead and apply the change :relieved:

**Comment by amtoine** [comment]
@fdncred @FMotalleb 
so i've created a very simple https://github.com/nushell/nu_scripts/pull/674 to move the command to the `nu_scripts`.

this should probably land first, and i've modified the deprecation warning accordingly in fa6c17da0 :yum:

**Comment by amtoine** [comment]
i've landed the other PR that moves the command to `nu_scripts`, let's start by deprecating `std clip` :relieved:

**Pull request merged**
