### PR TITLE
Handle relative paths correctly on polars to-(parquet|jsonl|arrow|etc) commands

### PR DESCRIPTION
**Pull request by ayax79**
# Description

All polars commands that output a file were not handling relative paths correctly. 

A command like
``` [[a b]; [6 2] [1 4] [4 1]] | polars into-df | polars to-parquet foo.json``` 
was outputting the foo.json to the directory of the plugin executable. 

This pull request pulls in nu-path and using it for resolving the file paths.

Related discussion
https://discord.com/channels/601130461678272522/1227612017171501136/1227889870358183966

# User-Facing Changes
None

# Tests + Formatting
Done, added tests for each of the polars to-* commands.

### CODE REVIEW

**Comment by fdncred** [comment]
I think a rebase may fix this since the ci is working now. oops, there's conflicts too now.

**Comment by ayax79** [comment]
hmm.. It looks like I need to test the new tests I added on windows.

**Comment by fdncred** [comment]
that's how i've fixed windows paths in tests before too.

**Comment by fdncred** [comment]
Thanks

**Pull request merged**
