### PR TITLE
Adding more math constants (and a small correction to the description of an existing one)

### PR DESCRIPTION
**Pull request by simdimdim**
Adding more float constants for when https://github.com/rust-lang/rust/issues/103883 is accepted and merged. And fixing a small conflation in the description of the Euler number. Please take a look and let me know if I've missed or screwed up anything.

### CODE REVIEW

**Review by simdimdim — COMMENTED** [review]
typo fix, missed an 'e'

**Comment by amtoine** [comment]
@simdimdim 
looks like you should run
```
cargo fmt --all
```
or
```
use toolkit.nu
toolkit fmt
```
:wink:

**Review by amtoine — COMMENTED** [review]
when the CI will be happy, this looks good to me :ok_hand: 

we have `pi` and `e` why not `gamma` and `phi` :yum: 

> **Note**
> i'm just wondering if we should keep adding constants to `math` in the long run :thinking: 
> maybe `nu_scripts` or the standard library might be a better fit later :+1:

**Comment by simdimdim** [comment]
Well, ultimately we still have to wait for https://github.com/rust-lang/rust/issues/103883 and I have no clue how to make the pull request conditionally depend on it.

for the record 
```
use toolkit.nu
toolkit fmt
```
where can I do that?

**Comment by amtoine** [comment]
> ```
> use toolkit.nu
> toolkit fmt
> ```
> 
> where can I do that?
>
from inside a Nushell instance, from the root of the `nushell/nushell` repo on your local machine :ok_hand:

**Comment by WindSoilder** [comment]
Hi @simdimdim thanks for your contribution.  Since the pr is adding some math consts, I'd suggest to make it to be `nu-std`'s module

**Comment by simdimdim** [comment]
> Hi @simdimdim thanks for your contribution. Since the pr is adding some math consts, I'd suggest to make it to be `nu-std`'s module

Hey o/,
I just added them where the other math constants were. If they get moved, I'll submit a new commit with the appropriate changes, since I'm very unfamiliar with the codebase and pretty much just copied `pi.rs` and `euler.rs` and edit their contents.

**Comment by fdncred** [comment]
I'm fine with landing this if the ci gets green. We can figure out what to move to stdlib after this.

**Comment by simdimdim** [comment]
well, that's it on my end I think. Now we just wait for the rust std to add PHI and EGAMMA to `std::f64::consts::`

**Comment by fdncred** [comment]
> well, that's it on my end I think. Now we just wait for the rust std to add PHI and EGAMMA to `std::f64::consts::`

I don't get this. If PHI and EGAMMA aren't in std::f64::consts, why do we have this PR?

**Comment by WindSoilder** [comment]
> well, that's it on my end I think. Now we just wait for the rust std to add PHI and EGAMMA to std::f64::consts::

I've checked these consts in both stable and nightly doc, but it don't exists in both place, and I don't think they'll be added in forseen future.  Are there any rfc or pr in rustc to add these constants?

**Comment by WindSoilder** [comment]
> well, that's it on my end I think. Now we just wait for the rust std to add PHI and EGAMMA to std::f64::consts::

I've checked these consts in both stable and nightly doc, but it don't exists in both place, and I don't think they'll be added in forseen future.  Are there any rfc or pr in rustc to add these constants?

**Comment by simdimdim** [comment]
> > well, that's it on my end I think. Now we just wait for the rust std to add PHI and EGAMMA to std::f64::consts::
> 
> I've checked these consts in both stable and nightly doc, but it don't exists in both place, and I don't think they'll be added in forseen future. Are there any rfc or pr in rustc to add these constants?

I've mentioned the related issue on the rust side in the first message already: https://github.com/rust-lang/rust/issues/103883
(and mentioned I dunno how to make this issue/pr depend on the status of the other one so it can automatically become mergeable when they're ready with the changes on the rust side of things)

**Comment by WindSoilder** [comment]
Oh, sorry for missing that message...Then I'll mark it as a draft.

**Comment by fdncred** [comment]
Just add these and be done with it, right?
```
/// The golden ratio (φ)
pub const PHI: f64 = 1.618033988749894848204586834365638118_f64;

/// The Euler-Mascheroni constant (γ)
pub const EGAMMA: f64 = 0.577215664901532860606512090082402431_f64;
```

**Comment by simdimdim** [comment]
> Just add these and be done with it, right?
> 
> ```
> /// The golden ratio (φ)
> pub const PHI: f64 = 1.618033988749894848204586834365638118_f64;
> 
> /// The Euler-Mascheroni constant (γ)
> pub const EGAMMA: f64 = 0.577215664901532860606512090082402431_f64;
> ```

That works too, should I do that instead?

**Comment by fdncred** [comment]
if you want to land this PR, i think it's the only way to move forward right now.

**Comment by fdncred** [comment]
@simdimdim Do you have time to update this PR with what is discussed above?

**Comment by simdimdim** [comment]
clippy appears to be unhappy with the too many decimal places, should I also do as it suggests?

**Comment by fdncred** [comment]
I'm not sure of the ramifications but my first reaction is to do what you did and add an `allow`.

**Comment by simdimdim** [comment]
well, since it's meant to be only a temporary patch it shouldn't really matter (once the constants could be used directly from std)
I think the actual values would get truncated anyway (to something that fits in a f64).
But for the time being I think this is all.

**Comment by fdncred** [comment]
Thanks. It's fine for now. It's likely that some of these basic type math commands will be moved to our std lib anyway.

**Pull request merged**
