### PR TITLE
Fix missing file names from rm errors

### PR DESCRIPTION
**Pull request by michaeljohnalbers**
# Description
Fixes a small bug with `rm` where names of files which couldn't be deleted due to error were not printed.

Fixes https://github.com/nushell/nushell/issues/9004

# User-Facing Changes
Slightly different error message than previously. Nothing significant, though.

The new error message looks like this
```
~/Projects/rust/nushell> rm /proc/1/mem                                                                                                                                                            05/06/2023 01:13:23 PM
Error: nu::shell::remove_not_possible

  × Remove not possible
   ╭─[entry #3:1:1]
 1 │ rm /proc/1/mem
   ·    ─────┬─────
   ·         ╰── Could not delete /proc/1/mem: Operation not permitted (os error 1)
   ╰────

```

or when using a glob (only showing a single entry for brevity)

```
Error: nu::shell::remove_not_possible

  × Remove not possible
   ╭─[entry #2:1:1]
 1 │ rm --recursive --force --verbose /proc/1/*
   ·                                  ────┬────
   ·                                      ╰── Could not delete /proc/1/comm: Operation not permitted (os error 1)
   ╰────
```

# Tests + Formatting
No new unit tests were added for this change as it is pretty difficult to test this particular case. However, manual testing was run with the following commands

```
rm /proc/1/mem
rm --recursive --force --verbose /proc/1/*
```

# After Submitting
N/A

### CODE REVIEW

**Comment by amtoine** [comment]
i propose safer tests that do not require touching `/`
```bash
sudo mkdir -p /tmp/nushell/nushell#9120/foo
sudo touch /tmp/nushell/nushell#9120/foo/bar.txt
```
then
```
rm /tmp/nushell/nushell#9120/foo/bar.txt
rm --recursive --force --verbose /tmp/nushell/nushell#9120/foo/*
```
:relieved:

**Review by amtoine — APPROVED** [review]
that looks good to me :muscle: 

i could reproduce the same kind of errors with the `/tmp/` tests above :relieved:

**Comment by juanPabloMiceli** [comment]
Can't we test this using something like [this](https://github.com/nushell/nushell/blob/main/crates/nu-command/tests/commands/cp.rs#L566)?

**Comment by amtoine** [comment]
> Can't we test this using something like [this](https://github.com/nushell/nushell/blob/main/crates/nu-command/tests/commands/cp.rs#L566)?
>
oooh maybe!

@michaeljohnalbers
could you give this a try, that'd be great :sparkles: 

just to have your simple test in the source base :relieved:

**Review by amtoine — CHANGES_REQUESTED** [review]
> Can't we test this using something like [this](https://github.com/nushell/nushell/blob/main/crates/nu-command/tests/commands/cp.rs#L566)?
>
oooh maybe!

@michaeljohnalbers
could you give this a try, that'd be great :sparkles: 

just to have your simple test in the source base :relieved:

**Comment by amtoine** [comment]
@michaeljohnalbers 
that looks promising :innocent: 

you might have to run `cargo fmt --all` or
```
use toolkit.nu
toolkit fmt
```
to fix the CI :relieved: 

also you can directly run
```
use toolkit.nu
toolkit check pr
```
to make sure everything is ok at once :smirk: 
(be careful the tests require some RAM :eyes:)

**Comment by michaeljohnalbers** [comment]
@amtoine Sorry about that. I thought I had my git hooks set up, but it seems I didn't. I ran the formatter as well as `toolkit check pr` everything appeared to pass.

**Review by amtoine — COMMENTED** [review]
amazing, that looks better :ok_hand: 

let's run the CI and see if it passes :innocent:

**Comment by amtoine** [comment]
@michaeljohnalbers 
so why do we have to skip the tests on windows? :open_mouth:

**Comment by amtoine** [comment]
could we still try them in the CI, to see if it works on all OSes? 
or do you mean it *can **not*** run on windows at all? :open_mouth:

i do not have windows available too, so i dunnot either :eyes:

**Comment by michaeljohnalbers** [comment]
One of the earlier CI runs did attempt to run the new test on Windows and it did fail. The assertion verifying the files were not deleted failed. This was despite making the containing folder/directory read-only.

**Comment by amtoine** [comment]
@michaeljohnalbers 
oh yeah my bad :+1: 

i'm not a windows chad so i'd rather leave the final word to a more familiar member of the core-team :relieved:

**Pull request merged**
