### PR TITLE
make `++` append lists

### PR DESCRIPTION
**Pull request by merelymyself**
# Description

Related: #6746. `++` now works with adding lists to lists, values to lists and lists to values.

`[1 3] ++ [5 6]` -> `[1 3 5 6]`

`[1 3] ++ 5` -> `[1 3 5]`

`1 ++ [3 5]` -> `[1 3 5]`

# Tests

Make sure you've done the following:

- [x] Add tests that cover your changes, either in the command examples, the crate/tests folder, or in the /tests folder.
- [ ] Try to think about corner cases and various ways how your changes could break. Cover them with tests.
- [ ] If adding tests is not possible, please document in the PR body a minimal example with steps on how to reproduce so one can verify your change works.

Make sure you've run and fixed any issues with these commands:

- [x] `cargo fmt --all -- --check` to check standard code formatting (`cargo fmt --all` applies these changes)
- [ ] `cargo clippy --workspace --features=extra -- -D warnings -D clippy::unwrap_used -A clippy::needless_collect` to check that you're using the standard code style
- [ ] `cargo test --workspace --features=extra` to check that all the tests pass

### CODE REVIEW

**Comment by kubouch** [comment]
I'm not sure this is desired because `[1 3] + [5 6]` can be also interpreted as `[6 9]`.

**Comment by sholderbach** [comment]
While the `list + list` case is ambiguous as we are not typed on the dimension of the list but we could declare an internal logic there, I think the dissimilar type case is even more open ended when it comes to proper semantics.

**Comment by fdncred** [comment]
I like it but I can see both sides. I'll vote with the majority.  I wonder if there is a better append symbology we could use other than `+`. What do other languages use like javascript and python for combining lists?

**Comment by kubouch** [comment]
Python uses `+`.

**Comment by WindSoilder** [comment]
I think `list + list`'s append behavior is find, but `list + other type` should raise out error.  That can raise ambiououly, because in dataframe/series, `number + df` will add number to the whole dataframe's values.

**Comment by merelymyself** [comment]
Any thoughts on `++` instead of `+`? It was suggested in the original issue and seems like a good way to sidestep all the confusion.

**Comment by fdncred** [comment]
Yes, please update this pr with ++ and we can land it.

**Comment by WindSoilder** [comment]
Sorry, I'd put one vote against `++`, what if `3 ++ 4` should be interpreted to? 

Or once we remove spaces from operators mentioned here: https://kubouch.notion.site/4db276462ba24704919edb4cc4b86be7?v=10506505557f4f7b9a65155128c04250&p=adb5f3c631aa40dba7eb8d5b1c794acf&pm=s

Then for the cases of `3++4` and `[3]++[4]`, we still have one operator `++` to do addition and concatenation

**Comment by merelymyself** [comment]
I don't think that will be that big of a problem; `++` can just be a generic `append` operator. so [3] ++ [4] and 3 ++ 4 both result in the list `[3 4]`.

**Comment by jntrnr** [comment]
@WindSoilder yes, some languages use `++` for array concatenation.

I think it wouldn't have any meaning for simpler values, so `3 ++ 4` would be an error.

**Comment by jntrnr** [comment]
We chatted about this in today's Nushell meeting and people like it. Thanks!

**Pull request merged**
