### PR TITLE
Fix bug #2921

### PR DESCRIPTION
**Pull request by LhKipp**
Moving whether a range should be parsed further back, giving e.G. parsing of invocations precedence fixes the bug.

### CODE REVIEW

**Comment by jonathandturner** [comment]
Nice!

**Comment by jonathandturner** [comment]
Can you add a few tests for this, too?

**Comment by LhKipp** [comment]
Testing the bug from #2921 requires to check for the correct span. I tried to implement a test, but I can't figure out how to create an `EvaluationContext` to call the function `run_block`. Testing with the test macro `nu!` doesn't allow for checking of the correct amount of whitespace before the `^^^^` marker.

**Comment by jonathandturner** [comment]
@LhKipp - we have a few tests that just check to make sure there isn't a parse error, so that's one option.

Another approach would be to run an example that would have failed before, but now will succeed. And then check that the output is what you expect.

**Comment by LhKipp** [comment]
@jonathandturner Great. I have Implemented an example (Not the same as described in the Issue) which failed before for the same reason.

**Comment by jonathandturner** [comment]
Looks good!

**Pull request merged**
