### PR TITLE
fix: Implicit coercion of boolean false and empty value #4094

### PR DESCRIPTION
**Pull request by closetool**
Signed-off-by: closetool <c299999999@qq.com>

Fix: #4094

### CODE REVIEW

**Comment by kubouch** [comment]
Thanks for the PR! Sorry for the lack of update, we're currently working hard towards merging engine-q into Nushell.

Seems like you're effectively turning Nothing into -1, so you'll get an ordering that in Nushell would result in `$nothing < $false < $true`. Not sure whether ordering booleans and nothings makes sense like that but I guess we can keep it.

Could you please add tests to cover the examples shown in the linked issue, just to make sure it keeps working in the future?

**Comment by closetool** [comment]
@kubouch Sure, I'll add it later. By the way could you offer me a link to describe what is engine-q, thanks.

**Comment by kubouch** [comment]
@closetool Sure! We're rewriting core components of Nushell in a separate repository. When we merge it in, basically, the nu-parser, nu-engine and nu-engine will be brand new. 

Here is the link: https://github.com/nushell/engine-q. Some parts of it are documented so you can clone the repo and use `cargo doc` to build the docs for the sub-crates.

**Comment by kubouch** [comment]
We were chatting about not allowing the `>` and `<` operations on booleans and nothing, but I think we can merge this and fix that in another PR. In engine-q comparing booleans like that is already disallowed.

So you can just replace the Cargo.lock with the new one and we can merge this.

**Comment by andrasio** [comment]
Attempting to use nothing values in boolean logic should error and not assume it's false.

If you'd like to remove nothing values you can pipe the table using the compact command and then proceed to use boolean logic with, say, where command.

**Comment by closetool** [comment]
ping @kubouch, fixed, please review.

**Comment by kubouch** [comment]
OK, thanks! Let's merge it but we should keep an eye on this when we merge engine-q to ensure comparing booleans and nothings is not allowed at all.

**Pull request merged**
