### PR TITLE
Preserve empty columns if separator isn't whitespace

### PR DESCRIPTION
**Pull request by oskarskog**
Changes the behavior of ```split-colum``` according to what is discussed in #394.

### CODE REVIEW

**Comment by jonathandturner** [comment]
Thanks for the PR! Can we also add a flag that will let people manually collapse empty columns, or keep them, if they want?

**Comment by oskarskog** [comment]
This project is a cool idea, happy to help! 

Can I make it the default behavior to keep empty columns and then add a flag for collapsing e.g. ```--collapse-empty```? If so, I think it's best to remove the special treatment of white space separators I added earlier, otherwise the shell works differently whenever white space is used as a separator; and I don't think we want that? @jonathandturner

**Comment by jonathandturner** [comment]
@oskarskog - yeah you can make the default not to collapse and have a flag to collapse. Sounds good

**Comment by oskarskog** [comment]
Flag added.

**Comment by jonathandturner** [comment]
Looks good, thanks!

**Pull request merged**
