### PR TITLE
Redirection: Avoid blocking when err+out> redirects too much stderr message

### PR DESCRIPTION
**Pull request by WindSoilder**
# Description

After reading into code, I found that `err+out>` will always redirect stdout message first, then stderr message.  

Then when we have a script which want to redirect too much error message too make nushell hangs.

Here is a python script example:
```python
# test.py
import sys

print('aa'*300, flush=True)
print('bb'*999999, file=sys.stderr, flush=True)
print('cc'*300, flush=True)
```

And running script:
`python test.py err+out> 1.txt`
~~I think it's better to make them interleaved like #6658 mentioned.~~

And BTW, fix `--raw` flag passing into external save command.

# User-Facing Changes

_(List of all changes that impact the user experience here. This helps us keep track of breaking changes.)_

# Tests + Formatting

Don't forget to add tests that cover your changes.

Make sure you've run and fixed any issues with these commands:

- `cargo fmt --all -- --check` to check standard code formatting (`cargo fmt --all` applies these changes)
- `cargo clippy --workspace -- -D warnings -D clippy::unwrap_used -A clippy::needless_collect` to check that you're using the standard code style
- `cargo test --workspace` to check that all tests pass

# After Submitting

If your PR had any user-facing changes, update [the documentation](https://github.com/nushell/nushell.github.io) after the PR is merged, if necessary. This will help us keep the docs up to date.

### CODE REVIEW

**Comment by sholderbach** [comment]
I only looked at the diff so far. How is this enabling interleaved reading? And how do we ensure that there is no blocking with potentially buffered reading?

**Comment by WindSoilder** [comment]
> How is this enabling interleaved reading?

Actually the key lays in the `save` command, when `save` command receive `--stderr` parameter, it consumes `stdout` and `stderr` in different thread.

> And how do we ensure that there is no blocking with potentially buffered reading?

The key here is still multi-threading in `save` command.  And, yeah, current implementation can lead to blocking.

consider the following python script:

```python
# test.py
import sys
import time

print('aa'*300, flush=True)
time.sleep(3)
print('bb'*999999, file=sys.stderr, flush=True)
time.sleep(3)
print('cc'*300, flush=True)
```

And run the script with `python test.py err+out> 1.txt` will block nushell.  This pr also solves the issue

**Comment by jntrnr** [comment]
I tested this against:

```rust
fn main() {
    eprintln!("Hello1, world!");
    println!("Hello2, world!");
    eprintln!("Hello3, world!");
    println!("Hello4, world!");
    eprintln!("Hello5, world!");
    println!("Hello6, world!");
}
```

then did:
```
> errout err+out> ../bar.txt
> cat ../bar.txt
Hello2, world!
Hello4, world!
Hello6, world!
Hello1, world!
Hello3, world!
Hello5, world!
```

The bash equivalent keeps them in the same order:
```
jt@pop-os:~/Source/nushell$ errout > ../foo.txt 2>&1
jt@pop-os:~/Source/nushell$ cat ../foo.txt 
Hello1, world!
Hello2, world!
Hello3, world!
Hello4, world!
Hello5, world!
Hello6, world!
```

**Comment by WindSoilder** [comment]
Ok, I've checked bash, the bash way to implement redirect is using `dup` system call, I should change the title.

**Comment by rgwood** [comment]
I spent some time looking into interleaving stderr and stdout. [This blog post](https://www.rozmichelle.com/pipes-forks-dups/) was quite helpful, as was section 5.5 in [The Linux Programming Interface](https://man7.org/tlpi/).

## How Bash Does It

As WindSoilder says, Bash uses [`dup()`/`dup2()`](https://man7.org/linux/man-pages/man2/dup.2.html). For example `dup2(1, 2)` will close the current process's stderr (`2`) and replace it with a copy of stdout (`1`) so that writes to stderr go to the same place as stdout. I believe the semantics of concurrent writes are then handled by [POSIX's guarantees for pipes](https://unix.stackexchange.com/a/68157/395923):

> Write requests of {PIPE_BUF} bytes or less shall not be interleaved with data from other processes doing writes on the same pipe. Writes of greater than {PIPE_BUF} bytes may have data interleaved

## How Nu Can Do It

I don't think using `dup()` is very practical for Nu. `dup()` needs to be called _from the child process_, which means we'd need to give up on using Rust's nice cross-platform `Command`/`spawn()`/`Child` abstractions and drop down to `fork`+`dup`+`exec` on *nix. I guess this is technically possible but I'm scared that it will have a long tail of bugs and cross-platform inconsistencies (I have no idea how we'd accomplish this on Windows).

Another option would be to use a Rust channel and spin up threads that just pump data from the external's stderr+stdout into the channel as it arrives. Some hacky prototype code that seems to work:

```rust
let mut process = Command::new("some-external")
.stderr(Stdio::piped())
.stdout(Stdio::piped())
.spawn()?;

let mut child_stderr = process.stderr.take().unwrap();
let mut child_stdout = process.stdout.take().unwrap();

let (tx, rx): (Sender<Vec<u8>>, Receiver<Vec<u8>>) = mpsc::channel();

// pump stderr into the channel
let thread_tx = tx.clone();
thread::spawn(move || {
    let mut buf = [0; 10];
    loop {
        let bytes_read = child_stderr.read(&mut buf).unwrap();
        if bytes_read == 0 {
            break;
        }

        let v = Vec::from(&buf[..bytes_read]);
        thread_tx.send(v).unwrap();
    }
});

// pump stdout into the channel
let thread_tx = tx.clone();
thread::spawn(move || {
    let mut buf = [0; 10];
    loop {
        let bytes_read = child_stdout.read(&mut buf).unwrap();
        if bytes_read == 0 {
            break;
        }

        let v = Vec::from(&buf[..bytes_read]);
        thread_tx.send(v).unwrap();
    }
});

// read from the channel
while let Ok(bytes) = rx.recv() {
    print!("{}", String::from_utf8_lossy(&bytes));
}
```

**Comment by rgwood** [comment]
Running the first Python script like `python3 test.py err+out> 1.txt` gives me unexpected, nondeterministic results; 

```
... (lots of bbbb chars)
bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb
... (lots more bbbb chars)
```

I'm a little surprised that the `print('aa'*300, flush=True)` call doesn't show up first in the output. I don't have a good understanding of why this PR works the way it does, will try to fix that.

**Comment by WindSoilder** [comment]
>  don't have a good understanding of why this PR works the way it does

After checking my code a bit, I think this PR is not always work like it does, it uses multi-threading, so there is no guarantee about the order it printed out...

It can only guarantee that all message to stdout will consume in order, and all message to stderr will consume in order.  But message between stdout and stderr can have different order.....  And it even can't guatantee that `print('aa' * 300, flush=True)` is atomic :-(  That's bad

**Comment by WindSoilder** [comment]
Have a look into this again, the external result handling should be done at the beginning of process creation:

https://rust-lang-nursery.github.io/rust-cookbook/os/external.html#redirect-both-stdout-and-stderr-of-child-process-to-the-same-file

I don't think it's an easy task, and it requires a lot of change.

Close the pr for now, it's a corner case of redirection, I think it's ok to leave current behavior for now

**Comment by rgwood** [comment]
That example is a great find, thanks.

**Pull request closed without merging**
