### PR TITLE
Update the command 'version'.

### PR DESCRIPTION
**Pull request by jaudiger**
# Description

No real changes, just some cleanup while I was looking at the code of the command.

# User-Facing Changes

Remove the attribute 'pkg_version', since it's already exposed through 'version'.

# Tests + Formatting

Don't forget to add tests that cover your changes.

Make sure you've run and fixed any issues with these commands:

- `cargo fmt --all -- --check` to check standard code formatting (`cargo fmt --all` applies these changes)
- `cargo clippy --workspace -- -D warnings -D clippy::unwrap_used -A clippy::needless_collect` to check that you're using the standard code style
- `cargo test --workspace` to check that all tests pass

# After Submitting

If your PR had any user-facing changes, update [the documentation](https://github.com/nushell/nushell.github.io) after the PR is merged, if necessary. This will help us keep the docs up to date.

### CODE REVIEW

**Comment by jaudiger** [comment]
Not sure why the MacOS tests failed. It seems unrelated to this PR.

**Comment by fdncred** [comment]
I think these changes are fine. One thing that I always want to do is dynamically figure out which features are in use. Do you know if shadow-rs supports that yet or if there's another way to do this?

**Comment by jaudiger** [comment]
shadow-rs does not support it yet. I saw that you wrote about this possible improvement inside the issue https://github.com/baoyachi/shadow-rs/issues/53, but it has not been resolved. I looked at the variables exposed by the library, and there is no such variable exposing the features (unless I missed something in their documentation).

Anyway, I also looked at the documentation of cargo which talks about that: https://doc.rust-lang.org/cargo/reference/features.html#build-scripts. There is maybe a possibility to implement a dynamic check based on environment variables exposed by Cargo. But I didn’t test what they said yet. I’ll experiment  in a few days, but I can’t promise about the results.
I understand that it can be cumbersome to maintain it manually.


Can we merge as for now this PR?

**Comment by fdncred** [comment]
Sure. Thanks!

**Pull request merged**
