### PR TITLE
Allow NU_LIBS_DIR and friends to be const

### PR DESCRIPTION
**Pull request by StevenDoesStuffs**
See #8310

### CODE REVIEW

**Comment by fdncred** [comment]
I've checked out and ran nushell with this PR. However, I'm struggling to figure out a good way to test it. Everything starts up right but what can I do to test that NU_LIB_DIRS & friends are consts?

**Comment by StevenDoesStuffs** [comment]
The whole point of having those values be const is so that changes to those values can be reflected in the same parse (which will allow us to remove the dual config system we have now). 

One way to test that everything works is to create a file where you declare a const NU_LIB_DIRS and check that source searches in those directories.

**Comment by fdncred** [comment]
Let me try to work through this out loud.

I have this in my env.nu
```
let-env NU_LIB_DIRS = [
    ($nu.config-path | path dirname | path join 'scripts')
    'C:\Users\username\source\repos\forks\nu_scripts'
]
```
NU_LIB_DIRS looks like this
```
> $env.NU_LIB_DIRS
╭───┬───────────────────────────────────────────────────╮
│ 0 │ C:\Users\username\AppData\Roaming\nushell\scripts │
│ 1 │ C:\Users\username\source\repos\forks\nu_scripts   │
╰───┴───────────────────────────────────────────────────╯
```
I have a file called defs.nu in `C:\Users\username\AppData\Roaming\nushell\scripts` and `nu_defs.nu` in `C:\Users\username\source\repos\forks\nu_scripts\misc`.
on launch I can do `source defs.nu` and `source misc\nu_defs.nu` without any problems.

Now, I create a folder at `C:\Users\username\AppData\Roaming\nushell\scripts2` and put `defs2.nu` in it. Then I do
```
const NU_LIB_DIRS = [ 'C:\Users\username\AppData\Roaming\nushell\scripts2' ]
```
Now, `source defs2.nu` works but when I do `$env.NU_LIB_DIRS` I still see the original folders and I can still do `source defs.nu` which is not in the const NU_LIB_DIRS definition. So, it seems like both `$env.NU_LIB_DIRS` and the const NU_LIB_DIRS are both working, but it's kind of confusing. I can also see the const definition in `$nu.scope.vars | table -e`.

I guess I was just expecting any changes to be reflected in `$env.NU_LIB_DIRS` even though I also added a const version of it (which doesn't really sound logical now that I type it out). I also didn't expect both of them to be working at the same time (but I guess that was the problem with the last PR, both weren't working at the same time. LOL.).

I'm anxious to see whatever Phase2 of this looks like, as you refer to in the previous PR. It seems to me like this is working as designed now. Let me know if you disagree with any of my rambling.

**Comment by StevenDoesStuffs** [comment]
Ah that's not quite right. I think I accidentally made it search in the env-var whenever it couldn't find the file in the const directories rather than checking whether the const exists. I'll fix that. It should be the case that once the const is declared, it takes over fully.

**Comment by StevenDoesStuffs** [comment]
I... forgot to actually add my changes before I pushed :facepalm:.

**Comment by fdncred** [comment]
i can't check this out anymore to test it. it might need a rebase?

**Comment by StevenDoesStuffs** [comment]
Not sure what you mean by that, but just did the rebase, so hopefully it works now.

**Comment by fdncred** [comment]
I just tested on Windows and for the first time it worked!!!

**Comment by fdncred** [comment]
I can't get this to work in WSL now. Does it look like I'm doing something wrong?
image

**Comment by fdncred** [comment]
Ok, @StevenDoesStuffs pointed out the error of my ways, mainly still being on the `main` branch for this latest test - LOL 🤣 

After moving to the proper branch. Everything works in WSL too.
image

**Comment by kubouch** [comment]
I have `let-env NU_LIB_DIRS = ...` inside `env.nu`. When I use `const NU_LIB_DIRS = ...` inside `config.nu`, suddenly, sourcing a file from the NU_LIB_DIRS env var inside `config.nu` does not work. Seems like it's not quite working yet.

**Comment by StevenDoesStuffs** [comment]
If I'm understanding what you're saying correctly, this is intended behavior. The const version of NU_LIB_DIRS will will take priority over the env-var if defined.

**Comment by fdncred** [comment]
@kubouch The way this is working for me now is:

1. if env.nu has `let-env NU_LIB_DIRS ...` - this works as normal
2. if env.nu has `let-env NU_LIB_DIRS ...` and from the repl you use `const NU_LIB_DIRS ...`, then the `const` list of folder overrides the `let-env` list of folders. so, none of the `let-env` list will be available unless they're the same as the `const`.
3. if env.nu has `const NU_LIB_DIRS ...` - then these work as you'd expect. I can't figure out how to append to NU_LIB_DIRS once it's a const. Maybe that's by design.

Is this the way you expect it to work?

**Comment by kubouch** [comment]
So, the main motivation for making NU_LIB_DIRS const is to merge env.nu and config.nu into a single file. Before that can happen, however, we need to investigate parse-time evaluation a bit further to see if we can make it work more like the current `let-env NU_LIB_DIRS` (e.g. using `$nu.config-path` and `path` commands to create it instead of hard literals).

What I imagined was that we would have both `let-env NU_LIB_DIRS` and `const NU_LIB_DIRS` working side by side. If you define `const`, the `let-env` would still keep working. Later, when/if we're ready, we'd delete the `let-env` support (or the `const` support if we deem it impossible, hopefully not). The reason is that if you're just trying it out, adding a few paths (like I did), if you rely a lot on `let-env NU_LIB_DIRS`, you'll get a lot of errors when it stops working, you'd have to re-create it completely using `const NU_LIB_DIRS` which is too tedious.

Also @fdncred you can't append to a const because it's immutable but you should be able to redefine it, like you'd do before we had `mut`.

**Comment by StevenDoesStuffs** [comment]
>  If you define `const`, the `let-env` would still keep working. 

Thoughts on how this should be done? One way is that we could check the env-var if the const dirs don't contain the item we're looking for if both are defined.

**Comment by kubouch** [comment]
Yeah, that's what I was thinking. First, check const. If not found in const, check env var.

**Comment by StevenDoesStuffs** [comment]
Just made the changes. 

2023-04-04-035447_hyprshot

**Comment by mon-jai** [comment]
> merge env.nu and config.nu into a single file

That would make both files hard to edit (via command line).

Currently the default config.nu contains ~524 lines, which is hard to navigate enough with vim.

**Comment by kubouch** [comment]
OK, it seems to work for me, let's try it out. Thanks for the patience!

**Comment by kubouch** [comment]
@mon-jai We plan to further refactor the config to make it more manageable. We haven't yet decided 100% how but stay tuned!

**Pull request merged**
