### PR TITLE
Change PluginCommand API to be more like Command

### PR DESCRIPTION
**Pull request by devyn**
# Description

This is something that was discussed in the core team meeting last Wednesday. @ayax79 is building `nu-plugin-polars` with all of the dataframe commands into a plugin, and there are a lot of them, so it would help to make the API more similar. At the same time, I think the `Command` API is just better anyway. I don't think the difference is justified, and the types for core commands have the benefit of requiring less `.into()` because they often don't own their data

- Broke `signature()` up into `name()`, `usage()`, `extra_usage()`, `search_terms()`, `examples()`
- `signature()` returns `nu_protocol::Signature`
- `examples()` returns `Vec<nu_protocol::Example>`
- `PluginSignature` and `PluginExample` no longer need to be used by plugin developers

# User-Facing Changes
Breaking API for plugins yet again :smile:

# Tests + Formatting
- :green_circle: `toolkit fmt`
- :green_circle: `toolkit clippy`
- :green_circle: `toolkit test`
- :green_circle: `toolkit test stdlib`

# After Submitting
- [ ] Change book documentation to reflect
- [ ] Make announcement on Discord

### CODE REVIEW

**Comment by ayax79** [comment]
Looks great!

**Comment by fdncred** [comment]
This makes the plugins look pretty familiar. Thanks!

**Comment by devyn** [comment]
I'm always creating my own conflicts, aren't I :rofl:

**Review by sholderbach — APPROVED** [review]
Let's land this to save @ayax79 some pain

**Pull request merged**
