### PR TITLE
Update `sys users` signature

### LINKED ISSUE #13171: Wrong signature for `sys users`
It returns a list of records (table):

https://github.com/nushell/nushell/blob/28ed0fe700167e09633ebf49c495d168cd9a7561/crates/nu-command/src/system/sys/users.rs#L57-L61

But the signature says it returns a record:

https://github.com/nushell/nushell/blob/28ed0fe700167e09633ebf49c495d168cd9a7561/crates/nu-command/src/system/sys/users.rs#L16

The result is that `sys users | where name == root` doesn't work, but it should.

### PR DESCRIPTION
**Pull request by weirdan**
Fixes #13171 

# Description
Corrects the `sys users` signature to match the returned type.

Before this change `sys users | where name == root` would result in a type error.
 

# User-Facing Changes

# Tests + Formatting

# After Submitting

### CODE REVIEW

**Comment by fdncred** [comment]
I just tested it with this and it works too
```rust
    fn signature(&self) -> Signature {
        Signature::build("sys users")
            .category(Category::System)
            .input_output_types(vec![
                (Type::Nothing, Type::record()),
                (Type::Nothing, Type::table()),
            ])
    }
```

**Comment by weirdan** [comment]
> should have both record and table in the signature because if there's just 1 item, but maybe that gets turned into a 1 item table?

The implementation always returns a list of records: 

https://github.com/nushell/nushell/blob/28ed0fe700167e09633ebf49c495d168cd9a7561/crates/nu-command/src/system/sys/users.rs#L57-L61

Doesn't this mean it's always a table?

**Comment by fdncred** [comment]
> Doesn't this mean it's always a table?

Ya, I think so. A list of 1 is still a list I think.

**Comment by fdncred** [comment]
I tried the other sys commands and they all work with where. I wasn't able to try sys temp because it returns nothing in Windows and Linux. Not sure what's going on with it.

**Comment by fdncred** [comment]
Let's move ahead with this. Thanks!

**Comment by weirdan** [comment]
`sys temp` returns a table for me on (bare metal) linux:
```
sys temp
╭────┬─────────────────────────────────────────────────┬───────┬───────┬──────────╮
│  # │                      unit                       │ temp  │ high  │ critical │
├────┼─────────────────────────────────────────────────┼───────┼───────┼──────────┤
│  0 │ thinkpad CPU                                    │ 58.00 │ 58.00 │    ❎    │
│  1 │ thinkpad temp7                                  │ 58.00 │ 58.00 │    ❎    │
│  2 │ thinkpad temp8                                  │   NaN │   NaN │    ❎    │
│  3 │ thinkpad temp6                                  │ 58.00 │ 58.00 │    ❎    │
│  4 │ thinkpad temp4                                  │  0.00 │  0.00 │    ❎    │
│  5 │ thinkpad temp5                                  │ 49.00 │ 49.00 │    ❎    │
│  6 │ thinkpad GPU                                    │   NaN │   NaN │    ❎    │
│  7 │ thinkpad temp3                                  │ 45.00 │ 45.00 │    ❎    │
│  8 │ pch_cannonlake temp1                            │ 58.00 │ 58.00 │    ❎    │
│  9 │ nvme Sensor 2 SAMSUNG MZVLB1T0HBLR-000L7 temp3  │ 42.85 │ 42.85 │    ❎    │
│ 10 │ nvme Sensor 1 SAMSUNG MZVLB1T0HBLR-000L7 temp2  │ 45.85 │ 45.85 │    ❎    │
│ 11 │ nvme Composite SAMSUNG MZVLB1T0HBLR-000L7 temp1 │ 45.85 │ 45.85 │    84.85 │
│ 12 │ acpitz temp1                                    │ 58.00 │ 58.00 │    ❎    │
│ 13 │ coretemp Core 1                                 │ 59.00 │ 59.00 │   100.00 │
│ 14 │ coretemp Package id 0                           │ 61.00 │ 61.00 │   100.00 │
│ 15 │ coretemp Core 0                                 │ 58.00 │ 58.00 │   100.00 │
│ 16 │ coretemp Core 2                                 │ 57.00 │ 57.00 │   100.00 │
│ 17 │ coretemp Core 3                                 │ 58.00 │ 58.00 │   100.00 │
│ 18 │ iwlwifi_1 temp1                                 │ 49.00 │ 49.00 │    ❎    │
╰────┴─────────────────────────────────────────────────┴───────┴───────┴──────────╯
```

**Comment by fdncred** [comment]
oh, it's temperature. I thought it was some temp folder thingy. lol. ya, that wouldn't work in wsl and probably not on windows.

**Pull request merged**
