### PR TITLE
Add `unlet_env` command

### LINKED ISSUE #3625: Feature request: "unlet" environment variables
**Is your feature request related to a problem? Please describe.**
I would like to set `$VIRTUAL_ENV` when entering a virtual environment and remove the variable when I leave it.

**Describe the solution you'd like**
A function like
```
unlet-env VIRTUAL_ENV
```
that removes `VIRTUAL_ENV` from `nu.env` altogether.

**Describe alternatives you've considered**
I have tried `let-env VIRTUAL_ENV = ''` but this doesn't work for programs that only check whether the environment variable exists.

### PR DESCRIPTION
**Pull request by nathom**
Resolves #3625.

I added a command named `unlet-env` that deletes an environment variable. It's the complement of `let-env` and an analogue of the bash `unset` command. Here's a demonstration:

```nushell
/Users/nathan/nushell(main)> let-env FOO = bar
/Users/nathan/nushell(main)> $nu.env.FOO
bar
/Users/nathan/nushell(main)> unlet-env FOO
/Users/nathan/nushell(main)> $nu.env.FOO
error: Unknown column
  ┌─ shell:6:9
  │
6 │ $nu.env.FOO
  │         ^^^ did you mean 'HOME'?

/Users/nathan/nushell(main)> unlet-env --help
Delete an environment variable.

Usage:
  > unlet-env <name> {flags}

Parameters:
  <name> the name of the environment variable

Flags:
  -h, --help: Display this help message

Examples:
  Remove the environment variable named FOO.
  > unlet-env FOO
```

### CODE REVIEW

**Comment by jonathandturner** [comment]
This looks good. Can you add a test, too? There are some tests that check for errors, you might be able to follow a similar pattern

**Comment by jonathandturner** [comment]
Just a heads up - we recently moved the commands around a bit so that they are no longer all in one directory. You'll need to merge main into your branch to get the updates.

**Comment by nathom** [comment]
Ok, I just updated the branch with the tests. Let me know if there's anything else to do.

**Comment by jonathandturner** [comment]
Looks good!

**Pull request merged**
