### PR TITLE
Short-hand flags

### PR DESCRIPTION
**Pull request by Amanita-muscaria**
Add support for short-hand flags

### CODE REVIEW

**Comment by jonathandturner** [comment]
Seems like the failures are clippy-related?

**Comment by jonathandturner** [comment]
@Amanita-muscaria this PR looks really good. My one nit is that I think we need a few tests that use the shorthand flags to just to be sure they continue to work in the future.

**Comment by Amanita-muscaria** [comment]
Should I modify any more tests than that or do you think it will be sufficient?

**Comment by jonathandturner** [comment]
Looks good!

**Pull request merged**
