### PR TITLE
add range command

### PR DESCRIPTION
**Pull request by sebastian-xyz**

### CODE REVIEW

**Comment by jonathandturner** [comment]
Cool. This one will be a good command to build from.

Can you add some tests and run it through `rustfmt`?

**Comment by jonathandturner** [comment]
@sebastian-xyz - hmm, looks like there are a few errors/warnings to be fixed. If you click on "Details" in the red x lines, then click on "View more details on Azure Pipelines" on the next page, you'll see the errors that are happening when the code is being tested.

You can run the tests locally by running `cargo test --all-features`. That should show you the same errors and warnings.

**Comment by sebastian-xyz** [comment]
I ran the tests before I commited and ran them again a few minutes ago. I didn't get any errors on my machine. Not sure whats causing those errors.

**Comment by jonathandturner** [comment]
@sebastian-xyz - it might be from the latest code in master. We landed a few big changes last night that you might need to adapt your code to work with. If you merge the latest master into your branch, I wonder if that will show you the errors.

**Comment by sebastian-xyz** [comment]
@jonathandturner yes I did that just now. It showed errors so I tried to compile master and I got the same errors.

**Comment by jonathandturner** [comment]
@sebastian-xyz - there's currently an issue with nightly, so you may also want to check with the stable Rust compiler. Once we can get stable passing without warnings/errors I think we can land it.

**Comment by jonathandturner** [comment]
@sebastian-xyz - looking at the results, it looks like you'll need to get rid of the warnings when building and running the tests also. The checks are setup so that there are no warnings when code lands, and it checks warnings when building tests also.

**Comment by jonathandturner** [comment]
Looks good! thanks :+1:

**Pull request merged**
