### PR TITLE
Update mimalloc to 0.1.42

### PR DESCRIPTION
**Pull request by devyn**
# Description

This update fixes mimalloc for NetBSD

# Tests + Formatting

Tests are passing just fine

### CODE REVIEW

**Comment by devyn** [comment]
@0323pin just a heads up - this will most likely work in 0.94, as it was fixed upstream :slightly_smiling_face:

**Comment by 0323pin** [comment]
@devyn I've tried to build `mimalloc`-0.1.42 stand alone today and failed, I can post the error later/tomorrow but, I remember it fails to find `static.c`

**Comment by devyn** [comment]
@0323pin okay, do let me know. We are building with `--no-default-features` I think. Also note that the rust package versions don't reflect the actual mimalloc versions at all

**Comment by 0323pin** [comment]
@devyn All good, git-HEAD builds natively with **default features** on NetBSD current. Thank you!

Bear in mind, my system is on Rust-1.78.0 while, default Rust on NetBSD is currently stuck on 1.76.0 due to [this](https://github.com/rust-lang/rust/issues/123551).

2024-05-23-132109_1366x768_scrot

Although, I must say, this is weird ...
```
~> pin/Downloads: ls
.rw-r--r-- pin wheel 16 KB Thu May 23 13:14:04 2024  mimalloc_rust-0.1.42.tar.gz
~> pin/Downloads: tar -xf mimalloc_rust-0.1.42.tar.gz
~> pin/Downloads: cd mimalloc_rust-0.1.42
~> pin/Downloads/mimalloc_rust-0.1.42: cargo build --release
    Updating crates.io index
  Downloaded cc v1.0.98
  Downloaded libc v0.2.155
  Downloaded 2 crates (820.3 KB) in 0.59s
   Compiling libc v0.2.155
   Compiling cc v1.0.98
   Compiling libmimalloc-sys v0.1.38 (/home/pin/Downloads/mimalloc_rust-0.1.42/libmimalloc-sys)
The following warnings were emitted during compilation:

warning: libmimalloc-sys@0.1.38: cc: error: c_src/mimalloc/src/static.c: No such file or directory
warning: libmimalloc-sys@0.1.38: cc: fatal error: no input files
warning: libmimalloc-sys@0.1.38: compilation terminated.

error: failed to run custom build command for `libmimalloc-sys v0.1.38 (/home/pin/Downloads/mimalloc_rust-0.1.42/libmimalloc-sys)`

Caused by:
  process didn't exit successfully: `/home/pin/Downloads/mimalloc_rust-0.1.42/target/release/build/libmimalloc-sys-16279b23cc448111/build-script-build` (exit status: 1)
  --- stdout
  OPT_LEVEL = Some("3")
  TARGET = Some("x86_64-unknown-netbsd")
  HOST = Some("x86_64-unknown-netbsd")
  cargo:rerun-if-env-changed=CC_x86_64-unknown-netbsd
  CC_x86_64-unknown-netbsd = None
  cargo:rerun-if-env-changed=CC_x86_64_unknown_netbsd
  CC_x86_64_unknown_netbsd = None
  cargo:rerun-if-env-changed=HOST_CC
  HOST_CC = None
  cargo:rerun-if-env-changed=CC
  CC = None
  cargo:rerun-if-env-changed=CC_ENABLE_DEBUG_OUTPUT
  cargo:rerun-if-env-changed=CRATE_CC_NO_DEFAULTS
  CRATE_CC_NO_DEFAULTS = None
  DEBUG = Some("false")
  CARGO_CFG_TARGET_FEATURE = Some("fxsr,sse,sse2")
  cargo:rerun-if-env-changed=CFLAGS_x86_64-unknown-netbsd
  CFLAGS_x86_64-unknown-netbsd = None
  cargo:rerun-if-env-changed=CFLAGS_x86_64_unknown_netbsd
  CFLAGS_x86_64_unknown_netbsd = None
  cargo:rerun-if-env-changed=HOST_CFLAGS
  HOST_CFLAGS = None
  cargo:rerun-if-env-changed=CFLAGS
  CFLAGS = None
  cargo:rerun-if-env-changed=CC_ENABLE_DEBUG_OUTPUT
  cargo:rerun-if-env-changed=CRATE_CC_NO_DEFAULTS
  CRATE_CC_NO_DEFAULTS = None
  CARGO_CFG_TARGET_FEATURE = Some("fxsr,sse,sse2")
  cargo:rerun-if-env-changed=CFLAGS_x86_64-unknown-netbsd
  CFLAGS_x86_64-unknown-netbsd = None
  cargo:rerun-if-env-changed=CFLAGS_x86_64_unknown_netbsd
  CFLAGS_x86_64_unknown_netbsd = None
  cargo:rerun-if-env-changed=HOST_CFLAGS
  HOST_CFLAGS = None
  cargo:rerun-if-env-changed=CFLAGS
  CFLAGS = None
  cargo:warning=cc: error: c_src/mimalloc/src/static.c: No such file or directory
  cargo:warning=cc: fatal error: no input files
  cargo:warning=compilation terminated.

  --- stderr


  error occurred: Command "cc" "-O3" "-ffunction-sections" "-fdata-sections" "-fPIC" "-m64" "-I" "c_src/mimalloc/include" "-I" "c_src/mimalloc/src" "-Wall" "-Wextra" "-ftls-model=initial-exec" "-DMI_DEBUG=0" "-o" "/home/pin/Downloads/mimalloc_rust-0.1.42/target/release/build/libmimalloc-sys-8f501235df9081f0/out/98cfcaec7182b1d8-static.o" "-c" "c_src/mimalloc/src/static.c" with args cc did not execute successfully (status code exit status: 1).
```

**Comment by devyn** [comment]
@0323pin glad to hear it! So that's why NetBSD is on 1.76. I just used rustup which seemed to work fine. That's a weird issue, I hope it gets resolved somehow soon...

As for rust-mimalloc, that kind of looks to me like it might be missing the git submodule that contains the actual mimalloc source code. If you grab it from a `git clone` and then `git submodule init --update`, does that still happen?

**Comment by 0323pin** [comment]
> As for rust-mimalloc, that kind of looks to me like it might be missing the git submodule that contains the actual mimalloc source code.

🤦‍♂️ Didn't even think about this. I hate git submodules.

**Comment by 0323pin** [comment]
@devyn The important thing is that it's working inside `nushell` build. As for using git-submodules ...
```
~> git clone https://github.com/purpleprotocol/mimalloc_rust
~> git submodule init
Submodule 'libmimalloc-sys/c_src/mimalloc' (https://github.com/microsoft/mimalloc) registered for path 'libmimalloc-sys/c_src/mimalloc'
~> cargo build --release
[...]
error occurred: Command "cc" "-O3" "-ffunction-sections" "-fdata-sections" "-fPIC" "-m64" "-I" "c_src/mimalloc/include" "-I" "c_src/mimalloc/src" "-Wall" "-Wextra" "-ftls-model=initial-exec" "-DMI_DEBUG=0" "-o" "/home/pin/Downloads/mimalloc_rust/target/release/build/libmimalloc-sys-8f501235df9081f0/out/98cfcaec7182b1d8-static.o" "-c" "c_src/mimalloc/src/static.c" with args cc did not execute successfully (status code exit status: 1).
~> set-env CC "clang"
~> cargo build --release
[...]
error occurred: Command "clang" "-O3" "-ffunction-sections" "-fdata-sections" "-fPIC" "-m64" "--target=x86_64-unknown-netbsd" "-I" "c_src/mimalloc/include" "-I" "c_src/mimalloc/src" "-Wall" "-Wextra" "-ftls-model=initial-exec" "-DMI_DEBUG=0" "-o" "/home/pin/Downloads/mimalloc_rust/target/release/build/libmimalloc-sys-8f501235df9081f0/out/98cfcaec7182b1d8-static.o" "-c" "c_src/mimalloc/src/static.c" with args clang did not execute successfully (status code exit status: 1).
~> git submodule update
Cloning into '/home/pin/Downloads/mimalloc_rust/libmimalloc-sys/c_src/mimalloc'...
Submodule path 'libmimalloc-sys/c_src/mimalloc': checked out '6141843614220c4d85f55774c131a68ba778e413'
~> cargo build --release
   Compiling libc v0.2.155
   Compiling cc v1.0.98
   Compiling libmimalloc-sys v0.1.38 (/home/pin/Downloads/mimalloc_rust/libmimalloc-sys)
warning: libmimalloc-sys@0.1.38: In file included from c_src/mimalloc/src/static.c:38:
warning: libmimalloc-sys@0.1.38: In file included from c_src/mimalloc/src/prim/prim.c:25:
warning: libmimalloc-sys@0.1.38: c_src/mimalloc/src/prim/unix/prim.c:75:12: warning: unused function 'mi_prim_open' [-Wunused-function]
warning: libmimalloc-sys@0.1.38:    75 | static int mi_prim_open(const char* fpath, int open_flags) {
warning: libmimalloc-sys@0.1.38:       |            ^~~~~~~~~~~~
warning: libmimalloc-sys@0.1.38: c_src/mimalloc/src/prim/unix/prim.c:78:16: warning: unused function 'mi_prim_read' [-Wunused-function]
warning: libmimalloc-sys@0.1.38:    78 | static ssize_t mi_prim_read(int fd, void* buf, size_t bufsize) {
warning: libmimalloc-sys@0.1.38:       |                ^~~~~~~~~~~~
warning: libmimalloc-sys@0.1.38: c_src/mimalloc/src/prim/unix/prim.c:81:12: warning: unused function 'mi_prim_close' [-Wunused-function]
warning: libmimalloc-sys@0.1.38:    81 | static int mi_prim_close(int fd) {
warning: libmimalloc-sys@0.1.38:       |            ^~~~~~~~~~~~~
warning: libmimalloc-sys@0.1.38: c_src/mimalloc/src/prim/unix/prim.c:84:12: warning: unused function 'mi_prim_access' [-Wunused-function]
warning: libmimalloc-sys@0.1.38:    84 | static int mi_prim_access(const char *fpath, int mode) {
warning: libmimalloc-sys@0.1.38:       |            ^~~~~~~~~~~~~~
warning: libmimalloc-sys@0.1.38: 4 warnings generated.
   Compiling mimalloc v0.1.42 (/home/pin/Downloads/mimalloc_rust)
    Finished `release` profile [optimized] target(s) in 20.89s
```

**Pull request merged**
