### PR TITLE
Support redirect stderr and stdout+stderr with a pipe

### PR DESCRIPTION
**Pull request by WindSoilder**
# Description
Close: #9673
Close: #8277
Close: #10944

This pr introduces the following syntax:
1. `e>|`, pipe stderr to next command.  Example: `$env.FOO=bar nu --testbin echo_env_stderr FOO e>| str length`
2. `o+e>|` and `e+o>|`, pipe both stdout and stderr to next command, example: `$env.FOO=bar nu --testbin echo_env_mixed out-err FOO FOO e+o>| str length`

Note: it only works for external commands.  ~There is no different for internal commands, that is, the following three commands do the same things:~  Edit: it raises errors if we want to pipes for internal commands
``` 
❯ ls e>| str length
Error:   × `e>|` only works with external streams
   ╭─[entry #1:1:1]
 1 │ ls e>| str length
   ·    ─┬─
   ·     ╰── `e>|` only works on external streams
   ╰────

❯ ls e+o>| str length
Error:   × `o+e>|` only works with external streams
   ╭─[entry #2:1:1]
 1 │ ls e+o>| str length
   ·    ──┬──
   ·      ╰── `o+e>|` only works on external streams
   ╰────
```

This can help us to avoid some strange issues like the following:

`$env.FOO=bar (nu --testbin echo_env_stderr FOO) e>| str length`

Which is hard to understand and hard to explain to users.

# User-Facing Changes
Nan

# Tests + Formatting
To be done

# After Submitting
Maybe update documentation about these syntax.

### CODE REVIEW

**Comment by kubouch** [comment]
I'm OK with it because it fills in missing functionality. The redirection syntax is becoming quite complex at this point. It would be good to have an overview of _all_ possible ways you can redirect stdout/stderr to file/pipe in some table and put it to our [Reference](https://www.nushell.sh/lang-guide).

**Comment by WindSoilder** [comment]
Thanks for feedback! there is one more thing which is unclear to me.

Currently `do -i { ls } | complete` raises an error:
```
Error:   × Complete only works with external streams
   ╭─[entry #35:1:1]
 1 │ do -i { ls } | complete
   ·                ────┬───
   ·                    ╰── complete only works on external streams
   ╰────
```

Do we want to raise error while using `e>|`(`o+e>|`) with internal commands?  e.g `ls e>| str length name` and `ls o+e>| str length name`

**Comment by kubouch** [comment]
> Do we want to raise error while using `e>|`(`o+e>|`) with internal commands? e.g `ls e>| str length name` and `ls o+e>| str length name`

Maybe we should, to make it consistent with `complete`.

**Comment by IanManske** [comment]
Great, it'll be nice to be able to redirect stderr.

Correct me if I'm wrong, but isn't `o>|` and `o+e>|` unnecessary, since stdout is always piped for external commands (if it's followed by a pipe)? Maybe we could add something like `e>o` which redirects stderr to stdout.

**Comment by WindSoilder** [comment]
@IanManske Yup, `o>|` is unnecessary, this pr doesn't support the syntax :) 

> Maybe we could add something like e>o which redirects stderr to stdout.

I think it's `2>&1` in bash.  I don't think it's necessary either.  Currently we use `o+e> file` to redirect both stdout and stderr to a file, so I think it's good to keep consistency to use the similar syntax like `o+e>| nextcmd` to pipe both stdout and stderr to next command.

So they would be idential:

| bash | fish | nu |
| ---- | -- | ---- |
|cmd 1>result.log 2>&1  |  cmd  &> result.log | cmd o+e> result.log
|cmd 2>&1 \| next_cmd  |   cmd &\| next_cmd |  cmd o+e>\| next_cmd

**Comment by IanManske** [comment]
> Yup, o>| is unnecessary, this pr doesn't support the syntax :)

Sorry, I misread the PR :sweat_smile:

I also wrongly thought that ```command1 e>| command2``` had the same result as ```command1 o+e>| command2```. But it looks like stdout is ignored for ```command1 e>| command2```? If so, this makes sense, and the consistent syntax is nice!

**Comment by WindSoilder** [comment]
> But it looks like stdout is ignored for command1 e>| command2?

Yeah, it's ignored :)

**Comment by WindSoilder** [comment]
Let's go and try it

**Comment by rgwood** [comment]
Thank you for continuing to work on redirection!

**Pull request merged**
