### PR TITLE
allow users to access `$env.path` in a case-insensitive manner

### PR DESCRIPTION
**Pull request by fdncred**
# Description

Nushell has never been able to handle `PATH` on Windows or `Path` on *nix, because in those two use cases, they do not exist and it's actually reversed. Windows (most) always wants to see `$env.Path` and MacOS and Linux want to see `$env.PATH`. This lead to a bunch of scripts checking the OS to determine if they should look at `PATH` or `Path`. This change allows you to `$env.Path`, `$env.PATH`, `$env.path`, `$env.PaTh` on any OS, effectively making this access case-insensitive.

image

I'm not sure this change is in the right place, but it works. I'm looking for reviewers to point out what's wrong with this or a better way to do it. It seems a little hack-ish to me.

I initially tried to hard code anything to `PATH` but that ended up breaking things an giving me two `PATH` env variables on Windows. It was very weird to have 2 of the same name env var. To top it off, they had slightly different data as well. So, I took the path of least resistance, which means Windows is always really stored as `Path` and MacOS/Linux is always stored as `PATH`.

# User-Facing Changes

# Tests + Formatting

# After Submitting

### CODE REVIEW

**Comment by fdncred** [comment]
Not sure how I'm doing this but on linux `PATH` is getting added twice. One has the right values, one has the wrong ones and the tests are failing because of this (I think).
image

**Comment by fdncred** [comment]
I think I finally cracked this nut. More of a root-canal than I expected but it seems to work.

**Comment by raggi** [comment]
I think fixing #11154 is a much better idea, otherwise the project could end up maintaining not only two odd system behaviors, but also the interpolation of historical choices such as this as well. If #11154 is fixed, all users could use `$env.PATH`, as they do in all other shells, including other shells on Windows.

**Comment by raggi** [comment]
For consideration: https://github.com/nushell/nushell/pull/11432

**Comment by fdncred** [comment]
This is not a windows-only change. It makes `$env.PATH` case insensitive across platforms.

**Comment by amtoine** [comment]
case-insensitive env in other systems still sounds strange to me :thinking: 
making that windows only maybe?

**Comment by fdncred** [comment]
@amtoine I think it sounds strange to you because you only live in Linux.

> If https://github.com/nushell/nushell/issues/11154 is fixed, all users could use $env.PATH, as they do in all other shells, including other shells on Windows.

This is true but it's basically saying, let's do everything the Linux way. It also means that you can't have `$env.path` on Windows *and* Linux or MacOS. With your PR, it would work on Windows but not anywhere else. So, therefore, scripts would not be cross-platform because you'd have to be very conscious about how you deal with path. My PR doesn't care. I'm not saying all my changes are 100% right, but I'm saying I like the concept of being able to ignore the case everywhere better.

**Comment by amtoine** [comment]
> @amtoine I think it sounds strange to you because you only live in Linux.
> 
yup, completely :yum: 
i was not talking for Windows :wink: 

a [related comment](https://github.com/nushell/nushell/issues/11432#issuecomment-1871173228) i think

**Comment by YizhePKU** [comment]
I don't like the idea of making only `$env.path` case-insensitive. It feels unintuitive. Either all environment variables should be case-insensitive, or none at all. I like @raggi's proposal better.

> It also means that you can't have `$env.path` on Windows and Linux or MacOS. With your PR, it would work on Windows but not anywhere else.

What if instead of trying to make `$env.path` work on Linux, we make it *break* on Windows? We can guard against any attempt to write to `$env.path` or `$env.Path` and throw an error, telling the user to write to `$env.PATH` instead.

**Comment by fdncred** [comment]
I'm also fine with the other PR like this one. Someone has to finish it though.

**Pull request closed without merging**
