### PR TITLE
nu-cli: directory syntax shape + completions

### PR DESCRIPTION
**Pull request by herlon214**
# Description

This PR creates the syntax shape for directories, changes the command `cd` , `mkdir` to use the directory shape and create the DirectoryCompletion.

It's mostly reusing things we had for `FilePath`, but filtering directories only.

There are a couple of things we need to decide:
1) Which color should we highlight the directories?
2) Is there any other command we should change the syntax shape?

Also, added tests for file completions and directory completions.

[asciicast](https://asciinema.org/a/QX7J1kw5wtJsgM1ztlwRSnklO)

# Tests

Make sure you've run and fixed any issues with these commands:

- [X] `cargo fmt --all -- --check` to check standard code formatting (`cargo fmt --all` applies these changes)
- [X] `cargo clippy --all --all-features -- -D warnings -D clippy::unwrap_used -A clippy::needless_collect` to check that you're using the standard code style
- [X] `cargo build; cargo test --all --all-features` to check that all the tests pass

### CODE REVIEW

**Comment by herlon214** [comment]
I'm wondering if we should change the file completions to filter directories out, probably yes but I'm afraid of breaking something. Should we change it?

**Comment by fdncred** [comment]
> I'm wondering if we should change the file completions to filter directories out, probably yes but I'm afraid of breaking something. Should we change it?

maybe? which commands would use that?

**Comment by herlon214** [comment]
@fdncred i'm not sure, previously every completion related to file was using the Filepath

**Comment by herlon214** [comment]
Also, would be nice to have directories with different color.

**Comment by fdncred** [comment]
> Also, would be nice to have directories with different color.

it would be nice to have `LS_COLORS` working there in completions

**Pull request merged**
