### PR TITLE
update crate chrono-tz to its latest version

### PR DESCRIPTION
**Pull request by stormasm**
This updates chrono-tz to the latest version which is 0.6.1

### CODE REVIEW

**Comment by fdncred** [comment]
have you tried playing with `cargo update`, it seems to update all crates that are outdated but only in the cargo.lock file, which seems a bit weird to me.

Try running it, it updates a bunch of stuff.

**Comment by stormasm** [comment]
@fdncred so I noticed you ran the command cargo update...
And obviously it works...

What about the associated Cargo.toml files ?

I don't understand exactly what is going on....

Does this mean that the Cargo.toml files we have now our not
synced up with the Cargo.lock file...

If we delete Cargo.lock from nushell and re-build will it regress
back to the old versions ?

**Comment by fdncred** [comment]
> What about the associated Cargo.toml files ?

Good question. I have no clue. :)

Maybe there's a way to do that too. I haven't read all these docs yet https://doc.rust-lang.org/cargo/commands/cargo-update.html.
 
> If we delete Cargo.lock from nushell and re-build will it regress back to the old versions ?

That's my guess.

**Comment by stormasm** [comment]
@fdncred We have more work to then on understanding how this works... 

As I believe there will be times when you just want to start over,
and build from scratch and not have a hard-coded lock file...

I believe you never want to have your lock file contain the truth...

**Pull request merged**
