### PR TITLE
Adds progressbar for 'for' using '-b'.

### PR DESCRIPTION
**Pull request by FilipAndersson245**
# Description

Adds support to run `for` with `-b` or `--bar` to add a progress bar tracking the elapsed progress.
This is initial work and I hope to test this out on other commands, eg `rm`, `fetch` `mv` etc.
This is my first major commit to Nushell, so please be nice 🙏.
This currently only works for Lists & Ranges as i am unsure how the third option in `for` works.

https://user-images.githubusercontent.com/17986183/197404072-6c743a43-357c-4f8d-ae31-5e7dbd441b8b.mp4

to test it out run:  
`for x in 1..100 -b { sleep 10ms }`
`for x in [1 2 3 4 5] -b { sleep 150ms }`

This is initial work on #5542
# Tests

Make sure you've done the following:

- [ ] Add tests that cover your changes, either in the command examples, the crate/tests folder, or in the /tests folder.
- [ ] Try to think about corner cases and various ways how your changes could break. Cover them with tests.
- [ ] If adding tests is not possible, please document in the PR body a minimal example with steps on how to reproduce so one can verify your change works.

Make sure you've run and fixed any issues with these commands:

- [x] `cargo fmt --all -- --check` to check standard code formatting (`cargo fmt --all` applies these changes)
- [x] `cargo clippy --workspace --features=extra -- -D warnings -D clippy::unwrap_used -A clippy::needless_collect` to check that you're using the standard code style
- [x] `cargo test --workspace --features=extra` to check that all the tests pass

# Documentation

- [ ] If your PR touches a user-facing nushell feature then make sure that there is an entry in the documentation (https://github.com/nushell/nushell.github.io) for the feature, and update it if necessary.

### CODE REVIEW

**Comment by fdncred** [comment]
1. This looks so cool!!!!
2. What happens if your for loop is outputting data? Is it hidden by the progress bar or does all the output show with the progress bar somehow?

**Comment by FilipAndersson245** [comment]
https://user-images.githubusercontent.com/17986183/197411467-7a8b7df6-6460-44e4-b272-f8801f38e6e2.mp4

could be better, but this is a general problem with cli progress bars

**Comment by FilipAndersson245** [comment]
Also if you nest progress bars it becomes quite a mess, but that should be solvable in the mid to long term.

**Comment by fdncred** [comment]
It seems like multiple progress bars should be like the multi.rs and yarnish.rs samples on idicatif examples. I'm wondering if a progress bar is enabled if somehow it should collect all output into an array, show the progress bar, and when it's done, output the array. But that sounds tricky.

**Comment by FilipAndersson245** [comment]
that sounds like a possible solution, but think this works, for now, I will try to see if this logic can be utilized for other long-running commands.

**Comment by fdncred** [comment]
What is a real-world use case example?

**Comment by FilipAndersson245** [comment]
I dont have anything right now, but if you want to run some command or program repetedly with some data, you can now use `-b` to know where in the loop you currently are.

**Comment by fdncred** [comment]
But it doesn't work if there's any output of data. so, i'm trying to figure out if there are commands that we use, that don't output data, where this would be handy. As cool as this feature is, i don't want to add it if there is no real use case we can apply this to.  What about coping files?

**Comment by FilipAndersson245** [comment]
I still believe we can put data with this approach?, Just that intermediary we display the progress?

**Comment by webbedspace** [comment]
I'm just passing by, but my opinion about progress bar vs. incidental `print` output is that the bar shouldn't actually be rendered in the same buffer that `print` data goes to, but to some separate display area at the bottom of the terminal, similar to that used by the Ctrl-R history search panel and its "NO RECORDS" message. If Nushell had something like that (not familiar enough with the bare-metal particulars to know if this is feasible) then this would be excellent.

**Comment by fdncred** [comment]
I tend to agree with you @webbedspace. I'm a bit antsy with script output interleaved with progress bars. It's just not a good user experience to show both.

**Comment by FilipAndersson245** [comment]
I can only speak from my experience with similar tools in other languages, an example is tqdm in python, and there if you print anything intermediary you will break the current progress bar into a new one, so I think this is an acceptable solution. Otherwise, do we think this may be better to print the progress of other commands such as fetch etc?

**Comment by webbedspace** [comment]
>Otherwise, do we think this may be better to print the progress of other commands such as fetch etc?

I do think the current `fetch` has a lot to be desired on the UX front compared to command-line `curl`, in things like this.

**Comment by webbedspace** [comment]
By the way, as a compromise for the intermediate `print` issue, maybe just cause the first intermediate `print` to disable the bar entirely? It's gotta be better than the alternative (letting a bunch of clashing noise appear onscreen).

**Comment by FilipAndersson245** [comment]
> By the way, as a compromise for the intermediate `print` issue, maybe just cause the first intermediate `print` to disable the bar entirely? It's gotta be better than the alternative (letting a bunch of clashing noise appear onscreen).

im unsure how this should be done,  if anyone could point me in the right how that could be implementented?

**Comment by rgwood** [comment]
This is very cool, thank you for putting it together!

We discussed the PR yesterday and I think the general feeling is that this is cool but we're not entirely comfortable with the approach. In addition to the edge cases already discussed, we're a bit uncomfortable adding new flags to `for` which is arguably more like a keyword than a regular command.

I think it makes sense to close this PR (apologies), but progress UI is definitely something we could push forward in other ways.

**Comment by FilipAndersson245** [comment]
Okay, glad I at least could bring the idea to the table 😊.

**Comment by fdncred** [comment]
@FilipAndersson245 one more thought to put out there. i'm wondering, if it would be possible to make a 'progress-bar' command that could somehow piped into our other commands. I really don't think it's possible with our current architecture but it's worth thinking a little about maybe.

Another idea for future people that see this, it might be interesting to do something like this pseudo-code:
```
import progress-bar
do some thing
do some longer running thing
call progress-bar functions/exports/methods to display a progress bar
```
Maybe that's more of a tui type thing, which would also be cool to have scriptable in nushell.

thanks again for showing off the cool progress bar and we appreciate the effort.

**Pull request closed without merging**
