### PR TITLE
Add encoding auto-detection for `decode`

### PR DESCRIPTION
**Pull request by horasal**
# Description
Allow `decode` command to guess the encoding of input if no encoding name is given.

# User-Facing Changes

* `decode` now has an optional parameter instead of required one. User can just run `decode` to let the command automatically detect encoding and convert it to utf-8.
    Example

* Based on the detect result, user may have to give a encoding name
     Error Sample1 
     or get informed that the input is not supported by `decode`
    Error Sample2

# Tests + Formatting

* `cargo fmt --all -- --check` : OK
* `cargo clippy --workspace -- -D warnings -D clippy::unwrap_used -A clippy::needless_collect -A clippy::result_large_err`: OK
* `cargo test --workspace` : OK
* `cargo run -- -c "use std testing; testing run-tests --path crates/nu-std"`: OK

# After Submitting

[Command document](https://www.nushell.sh/commands/docs/decode.html) is auto-generated and requires no action.

### CODE REVIEW

**Comment by fdncred** [comment]
I think this is a great add, even though it adds one more dependency. The use experience gets a great boost. 

However, having a 6-year-old crate may not be the best choice for us. Is there perhaps a better supported crate for this?  I noticed https://github.com/hsivonen/chardetng has been updated in the last year, not sure it does the same thing though. Thoughts?

**Comment by horasal** [comment]
I tried `chardetng` but it does not work really well. It fails at some cases on [chardet's testset](https://github.com/thuleqaid/rust-chardet/tree/master/tests/data)   (see attached log)

As charset is lagacy from old time and almost hasn't changed in these years, I think `chardet` is also good to use.

But as chardet is written in rust-2018 style and have some bugs,  so how about to use [my fork](https://github.com/horasal/rust-chardet) for now and replace it with better crates in future?

```
encoding different, chardetng: UTF-8, groundtruth: ISO-2022-KR, chardetng reports success: true, document: tests/data/iso-2022-kr/_ude_iso1.txt
encoding different, chardetng: UTF-8, groundtruth: ISO-2022-KR, chardetng reports success: true, document: tests/data/iso-2022-kr/_ude_iso2.txt
encoding different, chardetng: windows-1250, groundtruth: ISO-8859-1, chardetng reports success: true, document: tests/data/iso-8859-2-hungarian/cigartower.hu.xml
encoding different, chardetng: windows-1250, groundtruth: ISO-8859-1, chardetng reports success: true, document: tests/data/iso-8859-2-hungarian/escience.hu.xml
encoding different, chardetng: windows-1250, groundtruth: ISO-8859-1, chardetng reports success: true, document: tests/data/iso-8859-2-hungarian/hirtv.hu.xml
encoding different, chardetng: windows-1250, groundtruth: ISO-8859-1, chardetng reports success: true, document: tests/data/iso-8859-2-hungarian/saraspatak.hu.xml
encoding different, chardetng: windows-1250, groundtruth: ISO-8859-1, chardetng reports success: true, document: tests/data/iso-8859-2-hungarian/shamalt.uw.hu.mk.xml
encoding different, chardetng: windows-1250, groundtruth: ISO-8859-1, chardetng reports success: true, document: tests/data/iso-8859-2-hungarian/shamalt.uw.hu.mr.xml
encoding different, chardetng: windows-1250, groundtruth: ISO-8859-1, chardetng reports success: true, document: tests/data/iso-8859-2-hungarian/shamalt.uw.hu.mv.xml
encoding different, chardetng: windows-1250, groundtruth: ISO-8859-1, chardetng reports success: true, document: tests/data/iso-8859-2-hungarian/shamalt.uw.hu.xml
encoding different, chardetng: windows-1250, groundtruth: ISO-8859-1, chardetng reports success: true, document: tests/data/iso-8859-2-hungarian/ugyanmar.blogspot.com.xml
encoding different, chardetng: ISO-8859-6, groundtruth: MacCyrillic, chardetng reports success: true, document: tests/data/iso-8859-6-arabic/_chromium_ISO-8859-6_with_no_encoding_specified.html
encoding different, chardetng: ISO-8859-7, groundtruth: windows-1253, chardetng reports success: true, document: tests/data/iso-8859-7-greek/disabled.gr.xml
encoding different, chardetng: windows-1253, groundtruth: ISO-8859-7, chardetng reports success: true, document: tests/data/iso-8859-7-greek/hotstation.gr.xml
encoding different, chardetng: windows-1253, groundtruth: ISO-8859-7, chardetng reports success: true, document: tests/data/iso-8859-7-greek/naftemporiki.gr.bus.xml
encoding different, chardetng: windows-1253, groundtruth: ISO-8859-7, chardetng reports success: true, document: tests/data/iso-8859-7-greek/naftemporiki.gr.cmm.xml
encoding different, chardetng: windows-1253, groundtruth: ISO-8859-7, chardetng reports success: true, document: tests/data/iso-8859-7-greek/naftemporiki.gr.fin.xml
encoding different, chardetng: windows-1253, groundtruth: ISO-8859-7, chardetng reports success: true, document: tests/data/iso-8859-7-greek/naftemporiki.gr.mrk.xml
encoding different, chardetng: windows-1253, groundtruth: ISO-8859-7, chardetng reports success: true, document: tests/data/iso-8859-7-greek/naftemporiki.gr.mrt.xml
encoding different, chardetng: windows-1253, groundtruth: ISO-8859-7, chardetng reports success: true, document: tests/data/iso-8859-7-greek/naftemporiki.gr.spo.xml
encoding different, chardetng: windows-1253, groundtruth: ISO-8859-7, chardetng reports success: true, document: tests/data/iso-8859-7-greek/naftemporiki.gr.wld.xml
encoding different, chardetng: windows-1253, groundtruth: ISO-8859-7, chardetng reports success: true, document: tests/data/iso-8859-7-greek/_chromium_ISO-8859-7_with_no_encoding_specified.html
encoding different, chardetng: windows-1253, groundtruth: ISO-8859-7, chardetng reports success: true, document: tests/data/iso-8859-7-greek/_ude_greek.txt
encoding different, chardetng: windows-1254, groundtruth: ISO-8859-1, chardetng reports success: true, document: tests/data/iso-8859-9-turkish/divxplanet.com.xml
encoding different, chardetng: windows-1254, groundtruth: ISO-8859-1, chardetng reports success: true, document: tests/data/iso-8859-9-turkish/subtitle.srt
encoding different, chardetng: windows-1254, groundtruth: ISO-8859-1, chardetng reports success: true, document: tests/data/iso-8859-9-turkish/wikitop_tr_ISO-8859-9.txt
encoding different, chardetng: KOI8-U, groundtruth: KOI8-R, chardetng reports success: true, document: tests/data/KOI8-R/aif.ru.health.xml
encoding different, chardetng: KOI8-U, groundtruth: KOI8-R, chardetng reports success: true, document: tests/data/KOI8-R/aug32.hole.ru.xml
encoding different, chardetng: KOI8-U, groundtruth: KOI8-R, chardetng reports success: true, document: tests/data/KOI8-R/aviaport.ru.xml
encoding different, chardetng: KOI8-U, groundtruth: KOI8-R, chardetng reports success: true, document: tests/data/KOI8-R/blog.mlmaster.com.xml
encoding different, chardetng: KOI8-U, groundtruth: KOI8-R, chardetng reports success: true, document: tests/data/KOI8-R/forum.template-toolkit.ru.1.xml
encoding different, chardetng: KOI8-U, groundtruth: KOI8-R, chardetng reports success: true, document: tests/data/KOI8-R/forum.template-toolkit.ru.4.xml
encoding different, chardetng: KOI8-U, groundtruth: KOI8-R, chardetng reports success: true, document: tests/data/KOI8-R/forum.template-toolkit.ru.6.xml
encoding different, chardetng: KOI8-U, groundtruth: KOI8-R, chardetng reports success: true, document: tests/data/KOI8-R/forum.template-toolkit.ru.8.xml
encoding different, chardetng: KOI8-U, groundtruth: KOI8-R, chardetng reports success: true, document: tests/data/KOI8-R/forum.template-toolkit.ru.9.xml
encoding different, chardetng: KOI8-U, groundtruth: KOI8-R, chardetng reports success: true, document: tests/data/KOI8-R/greek.ru.xml
encoding different, chardetng: KOI8-U, groundtruth: KOI8-R, chardetng reports success: true, document: tests/data/KOI8-R/intertat.ru.xml
encoding different, chardetng: KOI8-U, groundtruth: KOI8-R, chardetng reports success: true, document: tests/data/KOI8-R/janulalife.blogspot.com.xml
encoding different, chardetng: KOI8-U, groundtruth: KOI8-R, chardetng reports success: true, document: tests/data/KOI8-R/kapranoff.ru.xml
encoding different, chardetng: KOI8-U, groundtruth: KOI8-R, chardetng reports success: true, document: tests/data/KOI8-R/koi.kinder.ru.xml
encoding different, chardetng: KOI8-U, groundtruth: KOI8-R, chardetng reports success: true, document: tests/data/KOI8-R/money.rin.ru.xml
encoding different, chardetng: KOI8-U, groundtruth: KOI8-R, chardetng reports success: true, document: tests/data/KOI8-R/music.peeps.ru.xml
encoding different, chardetng: KOI8-U, groundtruth: KOI8-R, chardetng reports success: true, document: tests/data/KOI8-R/newsru.com.xml
encoding different, chardetng: KOI8-U, groundtruth: KOI8-R, chardetng reports success: true, document: tests/data/KOI8-R/susu.ac.ru.xml
encoding different, chardetng: KOI8-U, groundtruth: KOI8-R, chardetng reports success: true, document: tests/data/KOI8-R/_chromium_KOI8-R_with_no_encoding_specified.html
encoding different, chardetng: KOI8-U, groundtruth: KOI8-R, chardetng reports success: true, document: tests/data/KOI8-R/_ude_1.txt
encoding different, chardetng: windows-1251, groundtruth: MacCyrillic, chardetng reports success: true, document: tests/data/MacCyrillic/aif.ru.health.xml
encoding different, chardetng: windows-1251, groundtruth: MacCyrillic, chardetng reports success: true, document: tests/data/MacCyrillic/aug32.hole.ru.xml
encoding different, chardetng: windows-1252, groundtruth: MacCyrillic, chardetng reports success: true, document: tests/data/MacCyrillic/aviaport.ru.xml
encoding different, chardetng: windows-1251, groundtruth: MacCyrillic, chardetng reports success: true, document: tests/data/MacCyrillic/blog.mlmaster.com.xml
encoding different, chardetng: windows-1251, groundtruth: MacCyrillic, chardetng reports success: true, document: tests/data/MacCyrillic/forum.template-toolkit.ru.4.xml
encoding different, chardetng: windows-1252, groundtruth: MacCyrillic, chardetng reports success: true, document: tests/data/MacCyrillic/forum.template-toolkit.ru.6.xml
encoding different, chardetng: KOI8-U, groundtruth: MacCyrillic, chardetng reports success: true, document: tests/data/MacCyrillic/forum.template-toolkit.ru.8.xml
encoding different, chardetng: windows-1251, groundtruth: MacCyrillic, chardetng reports success: true, document: tests/data/MacCyrillic/forum.template-toolkit.ru.9.xml
encoding different, chardetng: windows-1251, groundtruth: MacCyrillic, chardetng reports success: true, document: tests/data/MacCyrillic/greek.ru.xml
encoding different, chardetng: windows-1251, groundtruth: MacCyrillic, chardetng reports success: true, document: tests/data/MacCyrillic/intertat.ru.xml
encoding different, chardetng: windows-1251, groundtruth: MacCyrillic, chardetng reports success: true, document: tests/data/MacCyrillic/kapranoff.ru.xml
encoding different, chardetng: windows-1251, groundtruth: MacCyrillic, chardetng reports success: true, document: tests/data/MacCyrillic/koi.kinder.ru.xml
encoding different, chardetng: windows-1251, groundtruth: MacCyrillic, chardetng reports success: true, document: tests/data/MacCyrillic/money.rin.ru.xml
encoding different, chardetng: windows-1252, groundtruth: MacCyrillic, chardetng reports success: true, document: tests/data/MacCyrillic/music.peeps.ru.xml
encoding different, chardetng: windows-1252, groundtruth: MacCyrillic, chardetng reports success: true, document: tests/data/MacCyrillic/newsru.com.xml
encoding different, chardetng: windows-1251, groundtruth: MacCyrillic, chardetng reports success: true, document: tests/data/MacCyrillic/susu.ac.ru.xml
encoding different, chardetng: windows-1252, groundtruth: MacCyrillic, chardetng reports success: true, document: tests/data/MacCyrillic/_ude_1.txt
encoding different, chardetng: windows-1252, groundtruth: UTF-16BE, chardetng reports success: true, document: tests/data/UTF-16/bom-utf-16-be.srt
encoding different, chardetng: windows-1251, groundtruth: UTF-16LE, chardetng reports success: true, document: tests/data/UTF-16/bom-utf-16-le.srt
unsupported encoding UTF-32BE (encoding_rs) but detect as windows-1252
unsupported encoding UTF-32LE (encoding_rs) but detect as windows-1254
encoding different, chardetng: windows-1250, groundtruth: ISO-8859-1, chardetng reports success: true, document: tests/data/windows-1250-hungarian/bbc.co.uk.hu.learningenglish.xml
encoding different, chardetng: windows-1250, groundtruth: ISO-8859-1, chardetng reports success: true, document: tests/data/windows-1250-hungarian/bbc.co.uk.hu.xml
encoding different, chardetng: windows-1250, groundtruth: ISO-8859-1, chardetng reports success: true, document: tests/data/windows-1250-hungarian/objektivhir.hu.xml
encoding different, chardetng: windows-1250, groundtruth: ISO-8859-1, chardetng reports success: true, document: tests/data/windows-1252/_mozilla_bug421271_text.html
encoding different, chardetng: windows-1254, groundtruth: ISO-8859-1, chardetng reports success: true, document: tests/data/windows-1254-turkish/_chromium_windows-1254_with_no_encoding_specified.html
encoding different, chardetng: ISO-8859-8, groundtruth: windows-1255, chardetng reports success: true, document: tests/data/windows-1255-hebrew/maakav.org.xml
encoding different, chardetng: ISO-8859-8, groundtruth: windows-1255, chardetng reports success: true, document: tests/data/windows-1255-hebrew/notes.co.il.50.xml

**Comment by fdncred** [comment]
There's no problem using your fork if you plan to maintain it, but it also has to be published to crates.io. We cannot make releases without all crates being published.

**Comment by fdncred** [comment]
Where are we at on this @horasal ?

**Comment by horasal** [comment]
I noticed that [chardet uses LPGL](https://github.com/thuleqaid/rust-chardet/blob/master/LICENSE) so I changed the dependency to [chardetng which uses MIT/Apache](https://github.com/hsivonen/chardetng/blob/master/LICENSE-MIT), and now it's ready for review.

(maybe there will be a better crate in future)

**Comment by fdncred** [comment]
> I noticed that [chardet uses LPGL](https://github.com/thuleqaid/rust-chardet/blob/master/LICENSE)

oh, ya, that's a big deal. good catch!

**Comment by horasal** [comment]
rebased to main

**Comment by fdncred** [comment]
Thanks for this! Let's give it a try.

**Pull request merged**
