### PR TITLE
Include exit code and command duration in left prompt

### PR DESCRIPTION
**Pull request by SUPERCILEX**
My old shell used to do this and I found it super valuable to quickly know if the last command failed.

Closes https://github.com/nushell/nushell/issues/6906

### CODE REVIEW

**Comment by fdncred** [comment]
I do something similar with `nu_scripts/prompt/oh-my.nu` and like it in my prompt, but not everyone will.

**Comment by SUPERCILEX** [comment]
This will only show up for new installs. But yeah, if we don't want this to be the default, then it'd be nice to have this documented somewhere or maybe even just commented out.

**Comment by rgwood** [comment]
Can you please attach a screenshot showing how this change will look?

**Comment by SUPERCILEX** [comment]
Sure, here you go:
image

**Comment by merelymyself** [comment]
I’ll admit it looks snazzy, but I’m wondering if this is better fitted to be in nu_scripts instead of the default config, which I feel should be as minimal as possible.

**Comment by fdncred** [comment]
my vote is the same as @merelymyself, this would be a nice add to the prompt folder of nu_scripts.

**Comment by SUPERCILEX** [comment]
Can someone point me to where that folder is? Can't find it.

**Comment by sholderbach** [comment]
It's in this community repo:

https://github.com/nushell/nu_scripts/tree/main/prompt

**Comment by SUPERCILEX** [comment]
Oh wow, I had no idea that repo existed. I can move this change there, though I do wonder if it's simple enough for everyone. I would draw the line at something like a git integration because that requires external dependencies to the shell, but surfacing exit codes/time is relevant to everyone and built into the shell.

**Comment by fdncred** [comment]
thanks for working with us @SUPERCILEX. it think you present a good form of a "simple" prompt that others may like and that would fit perfectly in prompt folder of nu_scripts. thanks for understanding, closing this now.

**Comment by SUPERCILEX** [comment]
Sounds good, created https://github.com/nushell/nu_scripts/pull/309

**Pull request closed without merging**
