### PR TITLE
Conditionally disable expansion for external command

### LINKED ISSUE #5978: git branch -vl '*/*' returns nothing
### Describe the bug

When using the command `git branch -vl '*/*'` in a folder of a git repository. the command returns nothing.

When using PowerShell to execute the same command, it returns a list of git branches. 

### How to reproduce

1. open nushell in a folder a of git repository
2. execute the command `git branch -vl '*/*'`

### Expected behavior

The command returns the list of branches of the git repository with "/" in them like : `feature/1234-myaweomefeature`

### Screenshots

_No response_

### Configuration

| key                | value                                           |
| ------------------ | ----------------------------------------------- |
| version            | 0.65.0                                          |
| branch             |                                                 |
| commit_hash        | 390d06d4e7383d9fee814713bda8d1aaca858c5a        |
| build_os           | windows-x86_64                                  |
| build_target       | x86_64-pc-windows-msvc                          |
| rust_version       | rustc 1.62.0 (a8314ef7d 2022-06-27)             |
| rust_channel       | stable-x86_64-pc-windows-msvc                   |
| cargo_version      | cargo 1.62.0 (a748cf5a3 2022-06-08)             |
| pkg_version        | 0.65.0                                          |
| build_time         | 2022-07-05 17:33:16 +00:00                      |
| build_rust_channel | release                                         |
| features           | database, dataframe, default, trash, which, zip |
| installed_plugins  |                                                 |

### Additional context

It seems to me that the '*/*' is interpreted by nushell instead of being executed by the git command.

### PR DESCRIPTION
**Pull request by Kangaxx-0**
# Description

Fix #5978, with this change, external command will do expansion based on 
- Bare word(`^ls *.nu`): will expand glob for external
- Backticks(`^ls `*.nu``): will also expand glob
- (Single and double) Quotes: prevent glob expansion, like `^ls '*.nu'` won't do the path expansion

# Tests

Make sure you've done the following:

- [x] Add tests that cover your changes, either in the command examples, the crate/tests folder, or in the /tests folder.
- [x] Try to think about corner cases and various ways how your changes could break. Cover them with tests.
- [x] If adding tests is not possible, please document in the PR body a minimal example with steps on how to reproduce so one can verify your change works.

Make sure you've run and fixed any issues with these commands:

- [x] `cargo fmt --all -- --check` to check standard code formatting (`cargo fmt --all` applies these changes)
- [x] `cargo clippy --workspace --features=extra -- -D warnings -D clippy::unwrap_used -A clippy::needless_collect` to check that you're using the standard code style
- [x] `cargo test --workspace --features=extra` to check that all the tests pass

### CODE REVIEW

**Comment by jntrnr** [comment]
With this, will we still expand globs if there aren't quotes?

Some externals will expand the shell to do the expansion of globs for them.

**Comment by Kangaxx-0** [comment]
> With this, will we still expand globs if there aren't quotes?
> 
> Some externals will expand the shell to do the expansion of globs for them.

No, external(`arg` contains `*`)will not expand after this change, the alternative i was told is to pipe `glob`

**Comment by Kangaxx-0** [comment]
@jntrnr  If you could point me out what external might need expansion, that would be helpful to understand this. I tried to ask the same question in our implementation chat.

Regards to the opt-out, my first thought is to create an opt-out list that could prevent the expansion

**Comment by jntrnr** [comment]
@Kangaxx-0 - any external that takes in a glob likely will break.

```
❯ ^ls *.md
ls: cannot access '*.md': No such file or directory

❯ ^cat *.md
cat: '*.md': No such file or directory

❯ ls *.md
╭───┬────────────────────┬──────┬──────────┬──────────────╮
│ # │        name        │ type │   size   │   modified   │
├───┼────────────────────┼──────┼──────────┼──────────────┤
│ 0 │ CODE_OF_CONDUCT.md │ file │  3.4 KiB │ 2 months ago │
│ 1 │ CONTRIBUTING.md    │ file │  1.6 KiB │ 2 weeks ago  │
│ 2 │ README.md          │ file │ 12.8 KiB │ 2 weeks ago  │
╰───┴────────────────────┴──────┴──────────┴──────────────╯
```
```

**Comment by Kangaxx-0** [comment]
> @Kangaxx-0 - any external that takes in a glob likely will break.
> 
> ```
> ❯ ^ls *.md
> ls: cannot access '*.md': No such file or directory
> 
> ❯ ^cat *.md
> cat: '*.md': No such file or directory
> 
> ❯ ls *.md
> ╭───┬────────────────────┬──────┬──────────┬──────────────╮
> │ # │        name        │ type │   size   │   modified   │
> ├───┼────────────────────┼──────┼──────────┼──────────────┤
> │ 0 │ CODE_OF_CONDUCT.md │ file │  3.4 KiB │ 2 months ago │
> │ 1 │ CONTRIBUTING.md    │ file │  1.6 KiB │ 2 weeks ago  │
> │ 2 │ README.md          │ file │ 12.8 KiB │ 2 weeks ago  │
> ╰───┴────────────────────┴──────┴──────────┴──────────────╯
> ```

Ok, this was the same thing I worried. I am going to start a new thread(Discord) for further discussion on this :)

**Comment by fdncred** [comment]
did we decide anything on this?

**Comment by fdncred** [comment]
I'll try to bring this up later today with the team.

**Comment by fdncred** [comment]
@Kangaxx-0 The core team discussed this today and we decided on this approach. Would you be willing to update this PR to support this below? Also, how do you feel about this decision? Do you think it's a good way to go?

- Bare word: will expand glob for external
- Backticks: will also expand glob
- (Single and double) Quotes: prevent glob expansion

**Comment by Kangaxx-0** [comment]
> 



> @Kangaxx-0 The core team discussed this today and we decided on this approach. Would you be willing to update this PR to support this below? Also, how do you feel about this decision? Do you think it's a good way to go?
> 
> * Bare word: will expand glob for external
> * Backticks: will also expand glob
> * (Single and double) Quotes: prevent glob expansion

One quick question,  double quotes usually do the expansion, e.g  - run this in zsh ` echo '$HOME' is "$HOME"`  gives us ` $HOME is /home/abc', do we want to prevent that in Nushell?

**Comment by jntrnr** [comment]
> > 
> 
> > @Kangaxx-0 The core team discussed this today and we decided on this approach. Would you be willing to update this PR to support this below? Also, how do you feel about this decision? Do you think it's a good way to go?
> > 
> > * Bare word: will expand glob for external
> > * Backticks: will also expand glob
> > * (Single and double) Quotes: prevent glob expansion
> 
> One quick question, double quotes usually do the expansion, e.g - run this in zsh ` echo '$HOME' is "$HOME"` gives us ` $HOME is /home/abc', do we want to prevent that in Nushell?

Hmm, interesting - can we think through variable expansion separate from glob expansion? I think we might want to do some design work specifically for that case so that we can see the trade-offs more clearly.

I noticed that Bash also treats these differently:

```
$ echo "*.md" is '*.md' is *.md
*.md is *.md is CODE_OF_CONDUCT.md CONTRIBUTING.md README.md
$ echo "$SHLVL" is '$SHLVL' is $SHLVL
1 is $SHLVL is 1
```

So maybe yeah we can focus on just the path glob expansion first and then we'll do some work to figure out variable expansion.

**Comment by b333z** [comment]
In regards to the decision above, what about variables, if we have `ls $something` is there a way in run_external for it to know that `$something` should not be expanded (does it come in quoted?).

It this a case of losing context, I wonder if to avoid opt-in/opt-out we need to make bare words a more first-class concept or be able to attach/wrap it in something so the consumer knows it was declared without quotes and should be treated as a bare word and glob expanded,

Can we have a `Value::BareWord` that in general is treated just like a string for most commands, but commands like run_external can run any BareWord values through glob expansion?

**Comment by Kangaxx-0** [comment]
Can someone change my pr to draft please, I will be working on the changes:

- Bare word: will expand glob for external
- Backticks: will also expand glob
- (Single and double) Quotes: prevent glob expansion

**Comment by Kangaxx-0** [comment]
Please do not merge the latest iteration, I will come up with some test scenarios, and also add more tests :)

**Comment by fdncred** [comment]
@Kangaxx-0 how's it going on this PR? Looks like CI is green, are we ready to merge?

**Comment by Kangaxx-0** [comment]
> @Kangaxx-0 how's it going on this PR? Looks like CI is green, are we ready to merge?

Yes, I did  a few tests, and also add some unit tests. Now, single and double quotes will prevent expansion, backtick and bare word does path expand

**Comment by Kangaxx-0** [comment]
CI and my local, windows gave me different error message. Nonetheless, it did work fine

**Comment by fdncred** [comment]
@Kangaxx-0 If you're done, I guess we can probably merge but it looks like there's some tests missing from the Windows side, if I'm reading things right, like backticks quoting. I can understand if you're just fed up with working on this.

**Comment by Kangaxx-0** [comment]
> @Kangaxx-0 If you're done, I guess we can probably merge but it looks like there's some tests missing from the Windows side, if I'm reading things right, like backticks quoting. I can understand if you're just fed up with working on this.

 My local windows was running super slow. I have switched to another issue, I will add some unit tests after i am done with that issue

**Comment by Kangaxx-0** [comment]
Interesting.... The failed two unit tests, they worked as expected in my local(Win 11), I did not see any error whatsoever, the image CI use is win server 2022.

**Comment by fdncred** [comment]
are we ready to land this? appreciate all your hard work.

**Comment by Kangaxx-0** [comment]
> are we ready to land this? appreciate all your hard work.

I am going to add some comment, will ping you when it is ready

**Comment by Kangaxx-0** [comment]
> are we ready to land this? appreciate all your hard work.

I think it is ready now

**Comment by fdncred** [comment]
ok, let's land this and see if it makes things better. thanks for sticking with it @Kangaxx-0!

**Pull request merged**
