### PR TITLE
Bracketed paste refactor

### PR DESCRIPTION
**Pull request by WindSoilder**
# Description
This pr is a completion of https://github.com/nushell/reedline/pull/598

After that pr is merged, we no longer need to disable bracketed mode in nushell

# User-Facing Changes

# Tests + Formatting

# After Submitting

### CODE REVIEW

**Comment by sholderbach** [comment]
Just a `cargo update -p reedline` and we should be good here.

**Comment by WindSoilder** [comment]
Wow, that's cool!

**Comment by fdncred** [comment]
Don't we need to change the cargo.toml for this? like
```toml
[patch.crates-io]
reedline = { git = "https://github.com/nushell/reedline.git", branch = "main"}
nu-ansi-term = {git = "https://github.com/nushell/nu-ansi-term.git", branch = "main"}
```
(nu-ansi-term isn't related here but I think we need to enable it too since i landed a pr there)

**Comment by sholderbach** [comment]
Yeah you need to run it with the patch section active.

**Comment by fdncred** [comment]
@WindSoilder if you can change the cargo.toml as shown above, we can probably land this and move forward.

**Comment by WindSoilder** [comment]
Yeah ok :-)  Just updated

**Comment by sholderbach** [comment]
> Yeah ok :-) Just updated

Thanks! You just need to add the `Cargo.lock` after the change as well. 

Sorry for the confusion

**Comment by WindSoilder** [comment]
Hi, sorry for a bit delay.
I found that I can't update and patch `nu-ansi-term` for now, because currently latest `nu-ansi-term` version is `0.48`, but nushell is using `0.47`.

And I've tried to update it, but currently it's blocked by https://github.com/sharkdp/lscolors/pull/66

**Comment by fdncred** [comment]
> And I've tried to update it, but currently it's blocked by https://github.com/sharkdp/lscolors/pull/66

Oh ya, I think `lscolors` is gated by the non-published 0.49 release of nu-ansi-term. You're right that we probably won't be able to update until nu-ansi-term is published and lscolors is published. Darn.

**Comment by fdncred** [comment]
but let's move forward with the other changes. Thanks @WindSoilder!

**Pull request merged**
