### PR TITLE
Fix #11047

### LINKED ISSUE #11047: `table` nested list indices are off after 1 "chunk"
### Describe the bug

when `table` displays a long list in multiple "chunk"s, the nested list indices in later chunks don't start from 0, but start from that chunk's first index, which is wrong

### How to reproduce

`0..1000 | each {[0]}`

### Expected behavior

the nested list indices should always start from 0

### Screenshots

maim-2023 11 13 20 32 04

### Configuration

| key                | value                                    |
| ------------------ | ---------------------------------------- |
| version            | 0.86.1                                   |
| branch             |                                          |
| commit_hash        | 51d5d0eac84ab883123eb0e621c8d71c396eb115 |
| build_os           | linux-x86_64                             |
| build_target       | x86_64-unknown-linux-gnu                 |
| rust_version       | rustc 1.71.1 (eb26296b5 2023-08-03)      |
| rust_channel       | 1.71.1-x86_64-unknown-linux-gnu          |
| cargo_version      | cargo 1.71.1 (7f1d04c00 2023-07-29)      |
| build_time         | 2023-11-05 11:29:30 -08:00               |
| build_rust_channel | release                                  |
| allocator          | mimalloc                                 |
| features           | default, sqlite, trash, which, zip       |
| installed_plugins  |                                          |

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by zhiburt**
close #11047

### CODE REVIEW

**Comment by zhiburt** [comment]
Out of topic

```nu
~/bin/nushell> [[a b, c]; [1 [2 3 3] 3] [4 5 [1 2 [1 2 3]]]] | table --collapse                                                                                                  
╭───┬───┬───╮
│ a │ b │ c │
├───┼───┼───┤
│ 1 │ 2 │ 3 │
├───┼───┼───┤
│ 4 │ 3 │ 1 │
│   ├───┼───┤
│   │ 3 │ 2 │
│   ├───┼───┤
│   │ 5 │ 1 │
│   │   ├───┤
│   │   │ 2 │
│   │   ├───┤
│   │   │ 3 │
╰───┴───┴───╯
```

*I think at first it was hard to do but as I recall it's got to be achievable for a while
I wonder maybe we shall add index?

**Comment by zhiburt** [comment]
By the way; I maybe forgot but @fdncred can we turn off index?
Cause it seems like a valuable option.

**Comment by fdncred** [comment]
@zhiburt Yes, `$env.config.table.index_mode`. I think that's it.
```
        index_mode: always # "always" show indexes, "never" show indexes, "auto" = show indexes when a table has "index" column
```

**Review by fdncred — APPROVED** [review]
Thanks for the quick fix @zhiburt. This indeed fixed the issue.

**Comment by zhiburt** [comment]
> `$env.config.table.index_mode`

Wouldn't it be useful to also have a `--argument` (e.g. `-i`, `--index`) to a `table` duplicating the behavior?
So it could be easier to do per table bases rather then changing a config per interested call.

Could be made as `GOOD FIRST ISSUE`

**Comment by fdncred** [comment]
I could see that. Really, the most requested parameter to table is --theme, to change the table theme for  one draw of the table.

**Comment by fdncred** [comment]
@zhiburt Can you fix the merge conflicts so we can land this please?

**Comment by fdncred** [comment]
Thanks!

**Pull request merged**
