### PR TITLE
refactor `std help` into a multi-file directory module

### PR DESCRIPTION
**Pull request by amtoine**
# Description
`std help` was a single monolithic module, quite hard to work with...

this PR splits the old `help.nu` file into a `help/` directory module
- `mod.nu` is the main entry point and defines `std help`
- `error.nu` defines all the error tool commands
- `common.nu` holds `build-help-header`
- `<cmd>.nu`, where `<cmd>` is one of the `std help` subcommand, defines `std help <cmd>`

> **Warning**
> one thing i'm not happy about is that i had to add all the submodules manually to `lib.rs` and they appear now in `help modules` :thinking: 
>
> cc/ @kubouch ? :grimacing: 

# User-Facing Changes
```
$nothing
```

# Tests + Formatting

# After Submitting
```
$nothing
```

# Notes for reviewers
to test this, i think the easiest is to run the following command, from inside `cargo run -- -n`, before and after `use std help` and observe the nature of the commands change :+1: 
```bash
def pr [] {
    ["" "commands" "externs" "operators" "modules" "aliases"] | reduce --fold [] {|it, acc|
        let command = (["help" $it] | str join " " | str trim)
        $acc | append (which $command)
    }
}
```

### CODE REVIEW

**Comment by kubouch** [comment]
Maybe you could move the files that you don't want public under `help` under a private directory, e.g., `help/utils/error.nu` etc. You'd need to add the directory as a virtual directory in `lib.rs` but it should solve the issue.

**Comment by amtoine** [comment]
> Maybe you could move the files that you don't want public under `help` under a private directory, e.g., `help/utils/error.nu` etc. You'd need to add the directory as a virtual directory in `lib.rs` but it should solve the issue.
>
mm i'll try that :ok_hand:

**Comment by amtoine** [comment]
ok so to be clear, i'd need to
- move the `error.nu` and `common.nu` files to another subdirectory
- move the "error.nu" and "common.nu" lines out from the `std_files` in `lib.rs` and redo the whole `working_set.add_file` + `working_set.add_virtual_path(..., File)` loop and finally a `working_set.add_virtual_path(..., Dir)`

?

**Comment by amtoine** [comment]
maybe we can just land this?
it's not perfect but at least the big `std help` has been split and will be much easier to work with :relieved:

**Comment by fdncred** [comment]
as long as this is still used as `std help blah`, i'm fine with getting the ci green and landing it.

**Comment by amtoine** [comment]
i do not have much time to work on this now, so i'll make this a draft :relieved:

**Comment by amtoine** [comment]
closing as it's been stale for a while now...

**Pull request closed without merging**
