### PR TITLE
Bump version to `0.92.3`

### PR DESCRIPTION
**Pull request by sholderbach**

### CODE REVIEW

**Comment by fdncred** [comment]
dang, i reset the cache again and it still didn't go green. not sure how to proceed here.

**Comment by fdncred** [comment]
Should we maybe turn off the caching temporarily until we've had time to test dfr vs polars?

**Comment by sholderbach** [comment]
It failed even when no cache was found so I don't think disabling the cache will get us much (apart from whatever has to get installed for the github actions tools)

**Comment by fdncred** [comment]
yay!

**Pull request merged**
