### PR TITLE
Fix release workflows

### PR DESCRIPTION
**Pull request by nibon7**
# Description
This PR tries to fix the release workflows of armv7 and riscv64gc. The ci workflows failed after commit c55b5c0a5 which pulled `simd-json` and it has known issues on armv7 and riscv64gc.

related to https://github.com/simd-lite/simd-json/issues/263

# User-Facing Changes

# Tests + Formatting

# After Submitting
See https://github.com/nibon7/nushell/actions/runs/5392226551/jobs/9790279348 and https://github.com/nibon7/nushell/actions/runs/5392226551/jobs/9790279472

### CODE REVIEW

**Comment by hustcer** [comment]
@nibon7 Thanks for the workaround, do you think we should create a upstream tracking issue in polars or value-trait?

**Comment by fdncred** [comment]
Doesn't this just exclude dataframes from those particular builds? If so, it's a work-around but probably not the ideal one. If I'm understanding right, we probably need to find a fix that allows `"allow-non-simd"` to be used. Unfortunately, I think this may have to be an upstream fix.

**Comment by hustcer** [comment]
Yes, it's not the ideal one. We will include the dataframes if only they have fixed the related issue.

**Comment by nibon7** [comment]
There is another workaround: remove the `json` feature from `polars` :)

**Pull request merged**
