### PR TITLE
feat: spawn the executables directly if possible

### LINKED ISSUE #3898: Multiline strings are not passed correctly to external programs
### Describe the bug

Multiline strings are not passed correctly to external programs.

### How to reproduce

```
> node -e 'console.log("sss")
console.log("aaaa")'

sss
```

### Expected behavior

I expected
```
sss
aaa
```

### Screenshots

image

### Configuration

Installed using winget.

```
────┬────────────────────┬─────────────────────────────────────────────────────────────────────────────────────────
 #  │      Column0       │                                         Column1
────┼────────────────────┼─────────────────────────────────────────────────────────────────────────────────────────
  0 │ version            │ 0.35.0
  1 │ short_commit       │ bc682066
  2 │ commit_hash        │ bc682066d8eb756727c38d98ae58a34dd9cb3b38
  3 │ commit_date        │ 2021-08-03 08:01:09
  4 │ build_os           │ windows-x86_64
  5 │ rust_version       │ rustc 1.54.0 (a178d0322 2021-07-26)
  6 │ rust_channel       │ stable-x86_64-pc-windows-msvc (default)
  7 │ cargo_version      │ cargo 1.54.0 (5ae8d74b3 2021-06-22)
  8 │ pkg_version        │ 0.35.0
  9 │ build_time         │ 2021-08-03 08:46:53
 10 │ build_rust_channel │ release
 11 │ features           │ clipboard-cli, ctrlc, dataframe, default, rustyline, term, trash, uuid, which, zip
 12 │ installed_plugins  │ binaryview, chart bar, chart line, fetch, from bson, from sqlite, inc, match, post, ps,
    │                    │ query json, s3, selector, start, sys, textview, to bson, to sqlite, tree, xpath
────
```

### Additional context

Might be related to #3765

### PR DESCRIPTION
**Pull request by aminya**
This pull request changes nu-command so that it spawns the process directly if:
- They are a `.exe` on Windows
- They are not a `.sh` or `.bash` on not windows.

Benefits:
- As I explained in [this comment](https://github.com/nushell/nushell/issues/3898#issuecomment-894000812), this is another step towards making Nushell a standalone shell that doesn't need to shell out unless it is running a script for a particular shell (cmd, sh, ps1, etc.).
- Fixes the bug with multiline strings. Fixes #3898 
- Better performance due to direct spawning.

For example, this script shows ~30 ms less latency.
After:
```nu
C:\> benchmark { node -e 'console.log("sssss")' }
───┬──────────────────
 # │    real time
───┼──────────────────
 0 │ 54ms 875us 700ns
───┴──────────────────
```
Before
```nu
C:\> benchmark { node -e 'console.log("sssss")' }
───┬──────────────────
 # │    real time
───┼──────────────────
 0 │ 79ms 136us 800ns  
───┴──────────────────
```

### CODE REVIEW

**Review by aminya — COMMENTED** [review]
Fixed

**Comment by fdncred** [comment]
I'm a little concerned that we're not covering all the executables, at least on Windows.  On Windows the `PATHEXT` holds the extensions that are executable. On my Windows system it says this `PATHEXT=.COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH;.MSC`.

**Comment by aminya** [comment]
Yes, this pull request currently changes the behaviour for `.exe` files on Windows. That means there is no middle man for spawning exe files. For the rest of the extensions, it shells out to cmd like before, until we implement special care for them too. For example, we can add a function to spawn PowerShell scripts, CMD scripts, etc.

**Comment by fdncred** [comment]
We also handle ps1 a special way in plugins too here https://github.com/nushell/nushell/blob/66cedf0b3aa4ff4e9b37313ac7a629f4069acf0a/crates/nu-engine/src/plugin/build_plugin.rs#L16-L41

**Comment by aminya** [comment]
> It also may be worth noting that nu-engine considers these extensions as executable.
> https://github.com/nushell/nushell/blob/66cedf0b3aa4ff4e9b37313ac7a629f4069acf0a/crates/nu-engine/src/plugin/build_plugin.rs#L135-L158

Because only the native executables are spawned directly, this one isn't used yet. But as I said we can implement special code for each of these executables.

**Comment by aminya** [comment]
> We also handle ps1 a special way in plugins too here
> 

Great! I don't know the relation of this code to `nu-command`. But these two should come together at some point. For now, let's focus on the native executables.

**Comment by fdncred** [comment]
I'm fine with taking baby-steps toward a goal. @jntrnr, what are your thoughts?

**Comment by jntrnr** [comment]
@fdncred 👍 for baby steps

**Comment by aminya** [comment]
This is ready to go on my end. I have been actually using my branch instead of the official release, which is broken for multiline strings.

**Comment by fdncred** [comment]
ok, let's land this then and see how it goes. thanks!

**Comment by aminya** [comment]
You're welcome!

**Pull request merged**
