### PR TITLE
align help

### PR DESCRIPTION
**Pull request by amtoine**
related to 
- https://github.com/nushell/nushell/issues/5066#issuecomment-1421528910
- https://github.com/nushell/nushell/issues/5066#issuecomment-1685018756

# Description
TODO

## TODO
- [x] align subcommands
- [ ] align flags
- [ ] align parameters
- [ ] make it work with scripts

# User-Facing Changes
## before: not aligned
```nushell
> help path
...

Subcommands:
  path basename - Get the final component of a path.
  path dirname - Get the parent directory of a path.
  path exists - Check whether a path exists.
  path expand - Try to expand a path to its absolute form.
  path join - Join a structured path or a list of path parts.
  path parse - Convert a path into structured data.
  path relative-to - Express a path as relative to another path.
  path split - Split a path into a list based on the system's path separator.
  path type - Get the type of the object a path refers to (e.g., file, dir, symlink).

...
```
```nushell
> def "foo" [] {}; def "foo bar" [] {}; def "foo baaaaaaaaaaaaaaaz" [] {}
> help foo
...

Subcommands:
  foo baaaaaaaaaaaaaaaz -
  foo bar -

...
```
```nushell
> module spam {
    export def "foo" [] {}
    export def "foo bar" [] {}
    export def "foo baaaaaaaaaaaaaaaz" [] {}
}
> use spam *
> help foo
...

Subcommands:
  foo baaaaaaaaaaaaaaaz -
  foo bar -

...
```

## after: aligned
```nushell
> help path
...

Subcommands:
  path basename    - Get the final component of a path.
  path dirname     - Get the parent directory of a path.
  path exists      - Check whether a path exists.
  path expand      - Try to expand a path to its absolute form.
  path join        - Join a structured path or a list of path parts.
  path parse       - Convert a path into structured data.
  path relative-to - Express a path as relative to another path.
  path split       - Split a path into a list based on the system's path separator.
  path type        - Get the type of the object a path refers to (e.g., file, dir, symlink).

...
```
```nushell
> def "foo" [] {}; def "foo bar" [] {}; def "foo baaaaaaaaaaaaaaaz" [] {}
> help foo
...

Subcommands:
  foo baaaaaaaaaaaaaaaz -
  foo bar               -

...
```
```nushell
> module spam {
    export def "foo" [] {}
    export def "foo bar" [] {}
    export def "foo baaaaaaaaaaaaaaaz" [] {}
}
> use spam *
> help foo
...

Subcommands:
  foo baaaaaaaaaaaaaaaz -
  foo bar               -

...
```

# Tests + Formatting

# After Submitting

### CODE REVIEW

**Comment by amtoine** [comment]
i think ab7bfdcc6 should align the flags as well, but it does not...
it appears to be due to the ANSI escape sequences in the left hand side :thinking: 

applying the following, i.e. removing the ANSI formatting from the output,
```diff
diff --git a/crates/nu-engine/src/documentation.rs b/crates/nu-engine/src/documentation.rs
index d5de78820..f24e90b71 100644
--- a/crates/nu-engine/src/documentation.rs
+++ b/crates/nu-engine/src/documentation.rs
@@ -354,16 +354,14 @@ where
 {
     //todo make these configurable -- pull from enginestate.config
     const G: &str = "\x1b[32m"; // green
-    const C: &str = "\x1b[36m"; // cyan
                                 // was const BB: &str = "\x1b[1;34m"; // bold blue
     const BB: &str = "\x1b[94m"; // light blue (nobold, should be bolding the *names*)
     const RESET: &str = "\x1b[0m"; // reset
-    const D: &str = "\x1b[39m"; // default
 
     let mut long_desc = String::new();
     let _ = write!(long_desc, "\n{G}Flags{RESET}:\n");
 
-    let mut lines: Vec<(String, String, usize)> = Vec::new();
+    let mut lines: Vec<(String, String)> = Vec::new();
     for flag in &signature.named {
         let no_ansi_left = if let Some(arg) = &flag.arg {
             if let Some(short) = flag.short {
@@ -394,35 +392,6 @@ where
             format!("--{}", flag.long)
         };
 
-        let left = if let Some(arg) = &flag.arg {
-            if let Some(short) = flag.short {
-                format!(
-                    "{C}-{}{}{RESET} <{BB}{:?}{RESET}>",
-                    short,
-                    if !flag.long.is_empty() {
-                        format!("{D},{RESET} {C}--{}", flag.long)
-                    } else {
-                        "".into()
-                    },
-                    arg,
-                )
-            } else {
-                format!("{C}--{}{RESET} <{BB}{:?}{RESET}>", flag.long, arg)
-            }
-        } else if let Some(short) = flag.short {
-            format!(
-                "{C}-{}{}{RESET}",
-                short,
-                if !flag.long.is_empty() {
-                    format!("{D},{RESET} {C}--{}", flag.long)
-                } else {
-                    "".into()
-                },
-            )
-        } else {
-            format!("{C}--{}{RESET}", flag.long)
-        };
-
         let default_str = if let Some(value) = &flag.default_value {
             format!(" (default: {BB}{}{RESET})", &value_formatter(value))
         } else {
@@ -436,12 +405,12 @@ where
         };
 
         let right = format!("{}{}{}", flag.desc, default_str, required);
-        lines.push((left, right, no_ansi_left.len()));
+        lines.push((no_ansi_left.clone(), right));
     }
 
-    let max_width = lines.iter().map(|(_, _, w)| *w).max().unwrap_or(0);
+    let max_width = lines.iter().map(|(l, _)| l.len()).max().unwrap_or(0);
 
-    for (left, right, _) in lines {
+    for (left, right) in lines {
         long_desc.push_str(&format!(
             "  {:<width$} - {}\n",
             left,
```
solves this issue, but it's a no-go because the output is ugly lol :eyes: 

this gives things like
```
Flags:
  -a          -
  --long      -
  -d <String> -  (default: 'foo')
  -b, --both  -
  -h, --help  - Display the help message for this command
```
but it's all white :confused:

**Comment by fdncred** [comment]
ya, let's keep color. 

in these type of situations, i usually setup a variable for width that measures the string after the ansi escapes are stripped using this function.

https://github.com/nushell/nushell/blob/028a327ce82279e760037e268d0cfbf233b21d6a/crates/nu-utils/src/deansi.rs#L67-L84

but then still use the ansi escaped string for printing.

**Comment by amtoine** [comment]
> ya, let's keep color.
>
ooh yeah, 100% agree :+1: 
 
> in these type of situations, i usually setup a variable for width that measures the string after the ansi escapes are stripped using this function.
> 
> https://github.com/fdncred/nushell/blob/main/crates/nu-utils/src/deansi.rs#L67-L84
> 
> but then still use the ansi escaped string for printing.
>
i was able to grealty simplify all this in 38ef82e57 by using `strip_ansi_string_likely` :ok_hand: 
colors are there, but the `-` does not align for some reason :sweat_smile:

**Comment by fdncred** [comment]
I'm not sure what you mean 
image

**Comment by amtoine** [comment]
i'm talking about the flags, not the subcommands :wink: 
try with
```nushell
def foo [-a, --long, -d = "foo", --both (-b)] {}; def "foo bar" [] {}; def "foo baaaaaaaz" [] {}; help foo
```

**Comment by fdncred** [comment]
oh, i see. it looks like the flags part isn't being aligned. haven't looked that close at the code to know why.

**Comment by amtoine** [comment]
i think, because there are ANSI escape sequence INSIDE the `left` part of the flag lines, it messes up the alignment with `{:<width$}`...

**Comment by amtoine** [comment]
i don't have time to work on this right now...
so i'll go ahead and close this, it will still be available in the list of my closed PRs :relieved:

**Pull request closed without merging**
