### PR TITLE
Added attributes to from-xml command

### PR DESCRIPTION
**Pull request by Borimino**
Attempt at solving issue #196. I am not sure, if this is the best way of showing attributes, but it is the simplest way I could think of.

### CODE REVIEW

**Comment by jonathandturner** [comment]
@Borimino - I've been thinking about this a bit.  This solution keeps things small, but it has the risk of overwriting a value (if they have an attribute and a child that conflict, for example)

I think what we want to do is to more explicit.  We could make a field `attributes` and put the attributes in there, `children` and put children in there, and so on.

This makes the table a bit bigger, but I think that's okay to do. It's more precise, and more closely matches what the xml has.

**Comment by Borimino** [comment]
@jonathandturner - I am not quite sure that I understand, how you would want this to look.

Could you perhaps give a mock-up of what you would expect this xml to result in?

```
<nu version="2.0" age="25">
  <version date="20190124">2.0</version>
  <age precision="precise">25</age>
</nu>
```

**Comment by jonathandturner** [comment]
For this:
```xml
<nu version="2.0" age="25">
  <version date="20190124">2.0</version>
  <age precision="precise">25</age>
</nu>
```

I think we would create a table that matches this json:
```json
{
	"nu": {
		"attributes": {
			"version": "2.0",
			"age": "25"
		},
		"children": [
			{
				"version": {
					"attributes": {
						"date": "20190124"
					},
					"children": [
						2.0
					]
				}
			},
			{
				"age": {
					"attributes": {
						"precision": "precise"
					},
					"children": [
						25
					]
				}
			}
		]
	}
}
```

Each node would have two columns: `attributes` and `children`, and that's where the attribute data and children data would go. Basically, we'd separate them into to tables rather than putting them together in the same table.

**Comment by jonathandturner** [comment]
Looks good!

**Pull request merged**
