### PR TITLE
Use sqlite as default history format

### PR DESCRIPTION
**Pull request by azzamsa**
# Description

Use `sqilte` as default history format. It gives the ability to filter the history based on exit status or current working directory.

# Tests

Make sure you've done the following:

- [-] Add tests that cover your changes, either in the command examples, the crate/tests folder, or in the /tests folder.
- [ -] Try to think about corner cases and various ways how your changes could break. Cover them with tests.
- [-] If adding tests is not possible, please document in the PR body a minimal example with steps on how to reproduce so one can verify your change works.

Make sure you've run and fixed any issues with these commands:

- [X] `cargo fmt --all -- --check` to check standard code formatting (`cargo fmt --all` applies these changes)
- [X] `cargo clippy --workspace --features=extra -- -D warnings -D clippy::unwrap_used -A clippy::needless_collect` to check that you're using the standard code style
- [-] `cargo test --workspace --features=extra` to check that all the tests pass

# More context

- `cargo test --workspace --features=extra` always crash both my wezterm and gnome terminal. So I have no clue for the final result.

### CODE REVIEW

**Comment by fdncred** [comment]
I'm not sure we want to make sqlite the default. I'm not sure how the user population would feel about that.

**Comment by azzamsa** [comment]
Yes. I just want the team aware of the filter I use in my workflow. Because I see some appreciation from it.

**Comment by Kangaxx-0** [comment]
> I'm not sure we want to make sqlite the default. I'm not sure how the user population would feel about that.

I am not a big fan of setting SQLite as default, even it is a super lightweight database :)

**Comment by fdncred** [comment]
based on #6520 this can go into nu_scripts as well please.

**Pull request closed without merging**
