### PR TITLE
fix: remove path expand for PATH

### PR DESCRIPTION
**Pull request by yuuyins**
# Description

Fixes: #6239
Co-authored-by: Vivian Wang <dramforever@live.com>

In default environment configuration, nushell expands paths in PATH.
This in an issue for operating systems that implement
transaction/atomicity through symlinks such as NixOS
(probably same issue arises when using Nix or home-manager standalone),
since the older expanded paths from older "system generations"
might not exist after creating or using newer "system generation".
So system is neither able to find some paths in PATH
and, thus, nor the PATHs' binaries.

This reverts #5692.

(i'm unable to run the tests, if someone can do so that would be nice)

# Tests

Make sure you've done the following:

- [ ] Add tests that cover your changes, either in the command examples, the crate/tests folder, or in the /tests folder.
- [ ] Try to think about corner cases and various ways how your changes could break. Cover them with tests.
- [ ] If adding tests is not possible, please document in the PR body a minimal example with steps on how to reproduce so one can verify your change works.

Make sure you've run and fixed any issues with these commands:

- [ ] `cargo fmt --all -- --check` to check standard code formatting (`cargo fmt --all` applies these changes)
- [ ] `cargo clippy --workspace --features=extra -- -D warnings -D clippy::unwrap_used -A clippy::needless_collect` to check that you're using the standard code style
- [ ] `cargo test --workspace --features=extra` to check that all the tests pass

### CODE REVIEW

**Comment by fdncred** [comment]
I'm not a big fan of this PR when all you have to do is change the config.nu. That's why it's configurable in the first place, so each person can configure it the way they want it.

If we had some overwhelming demand to revert this, then that's one thing but to revert it for one particular flavor of Linux doesn't seem to be worth it to me.

**Comment by rgwood** [comment]
Agreed with fdncred; #5692 was implemented for a reason and I think it would be unfortunate to revert that change just for Nix.

Perhaps it would be better to document how to get Nix set up (either as a comment in this file, or on the Nushell website)?

**Comment by yuuyins** [comment]
what about @kubouch suggestion?

> What we could do is add a flag to path expand to not resolve the symlinks. It would still expand ~ and .. and such but not the symlinks.

**Comment by yuuyins** [comment]
@fdncred @rgwood 

btw, this is not only an issue with nix in specific. whenever someone has a symlink that is dynamically changed, this issue will arise. i just don't think it's a good idea to assume paths are for some reason static, will exist forever

**Comment by kubouch** [comment]
I think the main problem in that issue was that it was somehow expanding PATH entries even when `path expand` was removed from the config. We need to reproduce this and figure out why PATH entries were auto-expanded when they shouldn't.

I'd prefer to keep the expansion in, which can be enhanced by implementing a flag to `path expand` which would prevent expanding symlinks. But I think we need to find the root cause instead of going back and forth with the config.

**Comment by fdncred** [comment]
I'd support @kubouch's suggestion but we should probably close this one.

**Comment by kubouch** [comment]
Yeah, turns out you can fix it by modifying the config. Thanks for the effort, though!

**Pull request closed without merging**
