### PR TITLE
Added `help externs` command

### PR DESCRIPTION
**Pull request by klementievdmitry**
# Description

`help externs` - command, which list external commands

Closes https://github.com/nushell/nushell/issues/8301

# User-Facing Changes

```nu
$ help externs
╭───┬──────────────┬─────────────┬───────────────────────────────────────────────────╮
│ # │     name     │ module_name │                       usage                       │
├───┼──────────────┼─────────────┼───────────────────────────────────────────────────┤
│ 0 │ git push     │ completions │ Push changes                                      │
│   │              │             │                                                   │
│ 1 │ git fetch    │ completions │ Download objects and refs from another repository │
│   │              │             │                                                   │
│ 2 │ git checkout │ completions │ Check out git branches and files                  │
│   │              │             │                                                   │
╰───┴──────────────┴─────────────┴───────────────────────────────────────────────────╯
```

# Tests + Formatting

Don't forget to add tests that cover your changes.

Make sure you've run and fixed any issues with these commands:

- `cargo fmt --all -- --check` to check standard code formatting (`cargo fmt --all` applies these changes)
- `cargo clippy --workspace -- -D warnings -D clippy::unwrap_used -A clippy::needless_collect` to check that you're using the standard code style
- `cargo test --workspace` to check that all tests pass

# After Submitting

If your PR had any user-facing changes, update [the documentation](https://github.com/nushell/nushell.github.io) after the PR is merged, if necessary. This will help us keep the docs up to date.

### CODE REVIEW

**Comment by amtoine** [comment]
This should close #8301 :ok_hand:

**Comment by fdncred** [comment]
If we're going to have this command, I'd rather call it `help extern` since it shows up here `$nu.scope.commands | where is_extern == true` as `is_extern`. 

I also think that it would be good to have the `module_name` column. 

The `category`, `signatures`, and `search_terms` don't seem particularly useful.

Just my two cents.

**Comment by fdncred** [comment]
@klementievdmitry oops, I made a mistake. Sorry, but we can't use `help extern` because we already have an `extern` command and `help extern` shows that help. Maybe making it plural is ok like `help externs`, unless you have a better suggestion.

**Comment by klementievdmitry** [comment]
Well, I didn't even think about it, I just did :smile:, and I have no other ideas.

**Comment by kubouch** [comment]
I'm thinking `help externals` is clearer and even more distinct. Otherwise, I'm ok with this PR.

**Comment by kubouch** [comment]
One thing we might do is to remove aliases and externals from `help commands`, and make better customized individual help messages for them. The externals discovery should also be added here https://github.com/nushell/nushell/blob/a52386e837bc4cb74d93379f02facc932b4acde3/crates/nu-cmd-lang/src/core_commands/help.rs#L88-L115. `help name` should be different based on whether `name` is a command, alias or known external. I think known externals might have one already, not sure, but the aliases should show a more customized message in addition to showing the wrapped command's help message. But these changes can be done in a future PR.

Ultimately, the `help` commands could be re-implemented in Nu code as a part of the standard library so that's also something to consider in the future.

**Comment by amtoine** [comment]
(@kubouch added to the task list :wink:)

**Comment by fdncred** [comment]
> I'm thinking `help externals` is clearer and even more distinct. Otherwise, I'm ok with this PR.

I think `help externals` is confusing because your file system is filled with externals that are not nushell built-ins. Is `help externals` supposed to list everything on your file system that isn't a built-in?  Also, if we're going to be consistent, then it should match `is_extern` but we can't have `help extern` because `extern` is a built-in. Which is why it's plural now. So, I'm voting against `help externals` since it's so confusing.

**Comment by kubouch** [comment]
OK, let's keep it `help externs` then. Alternative is `help known-externals` but that seems too verbose...

**Comment by fdncred** [comment]
I agree that `help known-externals` is too verbose but it is descriptive. I'm up for something else too, as long as it's less confusing. overloaded terms like extern are confusing. maybe the nushell code should call them something else too.

**Comment by sholderbach** [comment]
I would like to move ahead with this even though I can understand the arguments for and against certain naming decisions.

**Pull request merged**
