### PR TITLE
`fetch` -> `http get` and `post` -> `http post`

### PR DESCRIPTION
**Pull request by Kazuki-Ya**
# Updated description by @rgwood

This PR changes `fetch` to `http get` and `post` to `http post`. `fetch` and `post` are now deprecated. [I surveyed people on Discord](https://discord.com/channels/601130461678272522/601130461678272524/1065706282566307910) and users strongly approved of this change.

# Original Description
This PR is related to #2741 and my first pull request in rust :)

Implemented a new http mod to better http support and alias `fetch` and `post` commands to `http get` and `http post` respectively.

# User-Facing Changes

Users will be able to use HTTP method via http command, for example
``` shell
> http get "https://www.example.com"
<!doctype html>
<html>
...
```

### CODE REVIEW

**Comment by rgwood** [comment]
Thanks for the PR!

When you say "alias fetch and post commands", what exactly do you mean? I'm running your branch but `fetch` does not work for me:

```
〉fetch
Error: nu::shell::external_command (link)

  × External command failed
   ╭─[entry #5:1:1]
 1 │ fetch
   · ──┬──
   ·   ╰── did you mean 'http'?
   ╰────
  help: No such file or directory (os error 2)
  ```


FWIW, when we deprecate commands we usually do so by adding to [this file](https://github.com/nushell/nushell/blob/main/crates/nu-command/src/deprecated/deprecated_commands.rs). I'm not 100% sure if we should deprecate it, I'll ask around on Discord.

**Comment by fdncred** [comment]
I had the same question as @rgwood about "aliasing" but it also occurred to me that if we're renaming commands the files should be renamed and put in the http folder too, for organization. so `fetch.rs` would be `network/http/http_get.rs` or maybe just `network/http/get.rs`. the same is true for `post.rs`.

**Comment by Kazuki-Ya** [comment]
I think it is better just replacing fetch to httpget in [mod.rs](crates/nu-command/src/network/mod.rs) because fetch.rs and post.rs have many histroies. but if  it is ok to write entire http_get.rs, I'll do that.

**Comment by fdncred** [comment]
It's looking like we're going to land this soon. In preparation, there are some scripts in nu_scripts that will need to be updated in parallel, specifically the ones in make_release. We don't want to get around to making a release and have it puke.

cc @hustcer because there may be some `fetch` commands in the CI script as well. I can't remember.

**Comment by fdncred** [comment]
Scratch that, no `fetch` in the CI that I can see. It's using aria2c.exe.

However, there is another change in nu-command/src/strings/split/words.rs Example that needs to be updated.

**Review by rgwood — APPROVED** [review]
This looks good to me. Thanks for the nice first PR!

**Comment by hustcer** [comment]
@fdncred we are always using a fixed version of nushell，so wont be affected

**Pull request merged**
