### PR TITLE
Implement `De`-/`Serialize` for `Record` manually

### PR DESCRIPTION
**Pull request by sholderbach**
# Description
This decouples the serialized representation of `Record` from its internal implementation. It now gets treated as a map type in `serde`.

This has several benefits:
- more efficient representation (not showing inner fields)
- human readable e.g. as a JSON record
- no breaking changes when refactoring the `Record` internals in the future (see #12326, or potential introduction of `indexmap::IndexMap` for large N)
- we now deny the creation of invalid records a non-cooperating plugin could produce
  - guaranteed key-value correspondence
  - checking for unique keys

# Breaking change to the plugin protocol:
Now expects a record/map directly as the `Record.val` field instead of a serialization of it.

### CODE REVIEW

**Comment by devyn** [comment]
Are we waiting on anything for this? I want to document the serialized format of all `Value` types, and it would be nice to have this landed first so I don't have to change it later.

**Comment by WindSoilder** [comment]
> Are we waiting on anything for this? I want to document the serialized format of all Value types, and it would be nice to have this landed first so I don't have to change it later.

I don't think so, it's just because no one has looked into it yet.

**Review by WindSoilder — APPROVED** [review]
Thank!  Let's land and try it out

**Comment by devyn** [comment]
Thanks @WindSoilder :heart:

**Pull request merged**
