### PR TITLE
 fix #9462 the command do with flag -i, --ignore-errors doesn't work;

### LINKED ISSUE #9462: Cannot ignore errors related to permissions
### Describe the bug

I'm trying to delete file from the user that doesn't have permission to file. To ignore errors I'm trying to use `do` command with different options but none of them are show errors in any case and I see the error 

```
Error:   × Could not delete because: Operation not permitted (os error 1)
 1 │ do -i { rm /tmp/test }
   ·            ────┬────
   ·                ╰── Operation not permitted (os error 1)
   ╰────
```

### How to reproduce

1. Create tmp file from the root `sudo touch /tmp/test`
2. Run `do -i { rm /tmp/test }`

### Expected behavior

`do -i` or `do -s` should ignore all possible shell errors

### Screenshots

_No response_

### Configuration

| key                | value                                                   |
| ------------------ | ------------------------------------------------------- |
| version            | 0.81.0                                                  |
| branch             |                                                         |
| commit_hash        | 5c81bcef1a3c1667468c81ef8c06cf56a0962133                |
| build_os           | linux-x86_64                                            |
| build_target       | x86_64-unknown-linux-gnu                                |
| rust_version       | rustc 1.68.2 (9eb3afe9e 2023-03-27)                     |
| rust_channel       | 1.68.2-x86_64-unknown-linux-gnu                         |
| cargo_version      | cargo 1.68.2 (6feb7c9cf 2023-03-26)                     |
| build_time         | 2023-06-06 22:55:22 +00:00                              |
| build_rust_channel | release                                                 |
| features           | default, sqlite, static-link-openssl, trash, which, zip |
| installed_plugins  |                                                         |

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by mengsuenyan**
- fixes #9462

### CODE REVIEW

**Comment by sholderbach** [comment]
I know figuring out reliable tests around permissions is always a bit tricky but we should shield this here as it seems subtle to get right.

**Review by amtoine — CHANGES_REQUESTED** [review]
(just adding a bit of red to backup the request from @sholderbach to add a test :relieved:)

**Comment by fdncred** [comment]
@mengsuenyan are you going to be able to add a test to this pr?

**Comment by mengsuenyan** [comment]
> @mengsuenyan are you going to be able to add a test to this pr?

```rust
    all_targets
        .into_iter()
        .map(move |(f, span)| {
            let is_empty = || match f.read_dir() {
                Ok(mut p) => p.next().is_none(),
                Err(_) => false,
            };

            if let Ok(metadata) = f.symlink_metadata() {
                #[cfg(unix)]
                let is_socket = metadata.file_type().is_socket();
                #[cfg(unix)]
                let is_fifo = metadata.file_type().is_fifo();

                #[cfg(not(unix))]
                let is_socket = false;
                #[cfg(not(unix))]
                let is_fifo = false;

                if metadata.is_file()
                    || metadata.file_type().is_symlink()
                    || recursive
                    || is_socket
                    || is_fifo
                    || is_empty()
                {
                    let (interaction, confirmed) = try_interaction(
                        interactive,
                        format!("rm: remove '{}'? ", f.to_string_lossy()),
                    );

                    let result;
                    #[cfg(all(
                        feature = "trash-support",
                        not(target_os = "android"),
                        not(target_os = "ios")
                    ))]
                    {
                        use std::io::Error;
                        result = if let Err(e) = interaction {
                            let e = Error::new(ErrorKind::Other, &*e.to_string());
                            Err(e)
                        } else if interactive && !confirmed {
                            Ok(())
                        } else if trash || (rm_always_trash && !permanent) {
                            trash::delete(&f).map_err(|e: trash::Error| {
                                Error::new(ErrorKind::Other, format!("{e:?}\nTry '--trash' flag"))
                            })
                        } else if metadata.is_file()
                            || is_socket
                            || is_fifo
                            || metadata.file_type().is_symlink()
                        {
                            std::fs::remove_file(&f)
                        } else {
                            std::fs::remove_dir_all(&f)
                        };
                    }
                    #[cfg(any(
                        not(feature = "trash-support"),
                        target_os = "android",
                        target_os = "ios"
                    ))]
                    {
                        use std::io::{Error, ErrorKind};
                        result = if let Err(e) = interaction {
                            let e = Error::new(ErrorKind::Other, &*e.to_string());
                            Err(e)
                        } else if interactive && !confirmed {
                            Ok(())
                        } else if metadata.is_file()
                            || is_socket
                            || is_fifo
                            || metadata.file_type().is_symlink()
                        {
                            std::fs::remove_file(&f)
                        } else {
                            std::fs::remove_dir_all(&f)
                        };
                    }

                    if let Err(e) = result {
                        let msg = format!("Could not delete {:}: {e:}", f.to_string_lossy());
                        Value::Error {
                            error: Box::new(ShellError::RemoveNotPossible(msg, span)),
                        }
                    } else if verbose {
                        let msg = if interactive && !confirmed {
                            "not deleted"
                        } else {
                            "deleted"
                        };
                        let val = format!("{} {:}", msg, f.to_string_lossy());
                        Value::String { val, span }
                    } else {
                        Value::Nothing { span }
                    }
                } else {
                    let msg = format!("Cannot remove {:}. try --recursive", f.to_string_lossy());
                    Value::Error {
                        error: Box::new(ShellError::GenericError(
                            msg,
                            "cannot remove non-empty directory".into(),
                            Some(span),
                            None,
                            Vec::new(),
                        )),
                    }
                }
            } else {
                let msg = format!("no such file or directory: {:}", f.to_string_lossy());
                Value::Error {
                    error: Box::new(ShellError::GenericError(
                        msg,
                        "no such file or directory".into(),
                        Some(span),
                        None,
                        Vec::new(),
                    )),
                }
            }
        })
        .filter(|x| !matches!(x.get_type(), Type::Nothing))
        .into_pipeline_data(ctrlc)
        .print_not_formatted(engine_state, false, true)?;
```

After getting a little familiar with the code of nushell, I realized that when the command similar to the `rm` failed to execute, why not directly return `ShellError`, but print the error directly.

For Example:

```rust
ShellError {
....
      BundleError(String, Vec<ShellError>),
...
}
```

```rust
.filter(|x| !matches!(x.get_type(), Type::Nothing))
.into_shell_bundle_error("rm failed", ctrlc)
```

**Comment by mengsuenyan** [comment]
This [pull request](https://github.com/nushell/nushell/pull/9952) may be the better method to fixed the bug.

**Comment by amtoine** [comment]
## :exclamation: might be superseded by https://github.com/nushell/nushell/pull/9952

**Pull request closed without merging**
