### PR TITLE
New "display_output" hook.

### PR DESCRIPTION
**Pull request by PerBothner**
# Description

This adds a new `display_output` hook. If defined, non-stream output in the REPL (specifically calls to `eval_source`) are filtered through the hook.

This is a solution for issues #5368 and #1570.

It might be desirable to refactor a bit more, so only the `eval_source` calls in `repl.rs` checks for the `display_output` hook. Not sure if that's necessary/desirable, or the best way to do it. A simple and clean way is to add a `check_display_hook` argument to `display_hook`.

# Tests

I have not added tests - I haven't looked into how tests are written.

I've been testing it by adding this at the end of `config.nu`:

    let-env config = ($env.config | upsert hooks {
        if "DOMTERM" in (env).name {{ display_output: { to html --partial | domterm hcat  }}} else {} })

Make sure you've run and fixed any issues with these commands:

- [X] `cargo fmt --all -- --check` to check standard code formatting (`cargo fmt --all` applies these changes)
- [X] `cargo clippy --workspace --features=extra -- -D warnings -D clippy::unwrap_used -A clippy::needless_collect` to check that you're using the standard code style
- [X] `cargo test --workspace --features=extra` to check that all the tests pass

# Documentation

Once this is approved, an update to the "hooks" page is needed.  If someone has a simple example it will be appreciated.

### CODE REVIEW

**Comment by fdncred** [comment]
@PerBothner would it be possible for you to put some other examples of things we can test. I tried this one below and while it's a bit weird, it seems to work, and, for me, gives better insight as to what this change is supposed to do. I'm just thinking of other ways to use this other than DomTerm specific things.

adding this hook to my config.nu
```
hooks: {
  #... other hooks above here
  display_output: {
    to json
  }
}
```

I also wonder if it's applicable to add a list of display_output hooks and if that's supported like the other hooks. For instance I could make a list in pre_prompt:
```
pre_prompt: [
  {
    print -n ((char -u "02501") | str lpad -c (char -u "02501") -l ((term size).columns))
  }
  {
    print -n $"(ansi osc)133;A(ansi st)"
  }
]
```

**Comment by PerBothner** [comment]
Here is a cute example that uses a pdf viewer for the output. It's highly impractical, but it hints at things you might do with a IDE or notebook interface such as Jupyter.

* Install [weasyprint](https://weasyprint.org/)

    `pip install weasyprint`

* Add to your `config.nu` in the appropriate place:

  `display_output: { to html | ~/.local/bin/weasyprint - /tmp/nu-output.pdf }`

  (Adjust depending on where `weasyprint` is installed.)

* Start nu, and type a command that creates a table, such as `ls`.

* Open `/tmp/nu-output.pdf` in a pdf viewer, preferably one that auto-reloads when the file changes. On my fedora Linux system, either `evince` or `okular` do that. For example, in a separate non-nu window:

    `evince /tmp/nu-output.pdf &`

As you type commands into the nu repl, the output is displayed by the pdf viewer. It takes a second or more to update (`weasyprint` is a Python application) so it's way too slow for for real use. But it demos one way you could have an interface where the output is redirected to a separate window. Of course for a real application you'd presumably use the html output directly, rather than deal with pdf - using weasyprint and a pdf viewer is just a quick-and-easy demo.

**Comment by PerBothner** [comment]
> I also wonder if it's applicable to add a list of display_output hooks and if that's supported like the other hooks.

I can't think of a use for that. What would it mean? It could chain multiple hooks in a pipeline, I suppose. Or it could redirect the output to multiple places, like the venerable `tee` program. (You have to first convert stream output to value, of ocurse.) Neither of these seem to offser enough extra benefit to be worth supporting.

**Comment by PerBothner** [comment]
An even easier demo: Add this to the `hooks` in `config.nu`:

    display_output: { to html | save /tmp/nu-output.html --raw }

and then just open `file:/tmp/nu-output.html` in any browser.

Downside: you have to explicitly reload the page after each command. Of course, this is unacceptable for real use, but for any given "notebook-style" interface it should be easy to fix so it updates automatically, .

**Comment by PerBothner** [comment]
Thanks! I wrote some documentation - see https://github.com/nushell/nushell.github.io/pull/662

**Comment by fdncred** [comment]
I just noticed that there is no entry for this in our default_config.nu file. Shouldn't there be one with `$nothing` in there like the others so there is some level of discoverability?

**Comment by PerBothner** [comment]
I expressed my recommendation in issue #6787.  Having a "default config.nu" is a bug (an "anti-pattern"). Very few applications do this - for good reason. Nothing should be in the default config.nu. Much better is a web-page of "suggested configuation options" that can be kept up to date, and that can have links to detailed information. The start-up banner could print a link to this web-page if there is no config.nu.

**Comment by rgwood** [comment]
@PerBothner Unfortunately, it looks like this PR broke a few things: #7431 and #7342.

**Comment by fdncred** [comment]
@rgwood Do you mean it's the `display_output` functionality itself or perhaps it's the `--expand` mode of `table -e` that is used in it by default? I know `table -e` works very differently than `table`.

**Comment by rgwood** [comment]
@fdncred The former. No matter what the hook is, it collects the whole pipeline here:

https://github.com/nushell/nushell/blob/2bacc29d30fc6bb4798c9ef99801267492feb80d/crates/nu-cli/src/repl.rs#L958

**Comment by PerBothner** [comment]
_"No matter what the hook is, it collects the whole pipeline here:"_

To clarify: If there is *no* display hook set, does it still wait for the whole pipeline?  That would be weird and unfortunate. I don't think that should happen (though it's been 5-6 weeks since I looked at this).

I haven't looked into what it would take to write a `display_output` hook that pipes output incrementally. It seems like it should be possible using the simple `display_output` mechanism (with a more complicated hook implementation). Perhaps it might require a more complicated prototocol.

You linked to a line in `eval_block_with_early_return`. As far as I can tell, this line was added *after* the `display_output` changes.  Specifically:
```
commit 62e34b69b34ff2f9f39b8c75a9789d9d35da8fe7
Author: JT <547158+jntrnr@users.noreply.github.com>
Date:   Fri Nov 25 09:39:16 2022 +1300

    New commands: `break`, `continue`, `return`, and `loop` (#7230)
```
Couild the above change be involved in the issue?

**Comment by rgwood** [comment]
> To clarify: If there is no display hook set, does it still wait for the whole pipeline?

No. If there is no display hook set, results stream as expected.

> I haven't looked into what it would take to write a `display_output` hook that pipes output incrementally.

I think `run_hook_block` might need to be rewritten to return a `PipelineData` instead of a `Value`.

> You linked to a line in `eval_block_with_early_return`. As far as I can tell, this line was added after the display_output changes. 

That line is in the `run_hook_block` function and a blame suggests that it was added in #5480:

image

**Comment by PerBothner** [comment]
> I think `run_hook_block` might need to be rewritten to return a `PipelineData` instead of a `Value`.

I don't think that would help in the use-case of displaying a table using HTML. For that, for the first chunk of output you'd want to generate an HTML table. Then for each subsequent chunk of output you'd want to update the existing table by adding new rows. This might be doable without changing the `display_output` hook protocol, but the actual hook might have to be written in Rust so it can handle the `PipelineData`.

**Pull request merged**
