### PR TITLE
Remove usage of in_band_lifetimes feature

### PR DESCRIPTION
**Pull request by taiki-e**
cc #362

### CODE REVIEW

**Comment by wycats** [comment]
I don't really want to remove in-band lifetimes 😢 😭

**Comment by taiki-e** [comment]
Okay, #362 is blocked by specialization, so we won't need to merge it immediately.

However, half of this PR change is a lifetime omission, so I would like to split it into another PR. Then, when the specialization is stable we can redo this and resolve #362.

**Comment by jonathandturner** [comment]
@taiki-e - would it make sense to merge what we have now rather than re-do it?

**Comment by jonathandturner** [comment]
@wycats - I wonder how close it is to becoming stable in rustc

**Comment by wycats** [comment]
I'm ok with removing in-band lifetimes, as sad as it makes me. Stable Rust is important.

**Comment by taiki-e** [comment]
I'm fine with either one (this is a small work).

**Comment by jonathandturner** [comment]
@taiki-e - if you want to resolve the conflict, I'll go ahead and land this

**Comment by taiki-e** [comment]
Resolved the conflict.

**Comment by jonathandturner** [comment]
Thanks!

**Pull request merged**
