### PR TITLE
making changes in README file

### PR DESCRIPTION
**Pull request by topaja**

### CODE REVIEW

**Comment by kubouch** [comment]
I don't think we need to make headers extra bold?

**Comment by topaja** [comment]
Yup, maybe it's just that this is my first open-source contribution.
But we can keep the shell in bold & italics if you like.

**Comment by jntrnr** [comment]
The headers will be rendered by the website software. We shouldn't make them bold.

**Comment by kubouch** [comment]
@topaja Thanks for the initiative but I think even highlighting the "shell" word is not necessary. However, if you're eager to help, the README could use a bit of polish. For example, the [Configuration](https://github.com/nushell/nushell#configuration) section is outdated and could be updated to have just a short description and point at [the documentation](https://www.nushell.sh/book/configuration.html).

**Comment by topaja** [comment]
Ok
I will definitely try to do that & thanks for guiding.

**Comment by jntrnr** [comment]
Converting to draft until you have the new direction you want to go.

**Comment by jntrnr** [comment]
Seems like there isn't progress here. We don't want to bold something that is already a header, and adding bold doesn't help the readability.

I'll go ahead and close.

**Pull request closed without merging**
