### PR TITLE
Ls symlink fix

### LINKED ISSUE #6706: `ls` resolves a symlink which pointed to a file
### Describe the bug

E.g. there are a file and a symlink which pointed to the file, `ls *` or just `ls`, the type of the symlink is `symlink`, but  `ls <NAME_OF_THE_SYMLINK>`, the type of the symlink is `file`.

### How to reproduce

1. mkdir test
2. cd test
3. touch a_file
4. ln -s a_file a_symlink
5. ls | where name == a_symlink | get type
6. ls a_symlink | get type

### Expected behavior

ls does not resolve a symlink which pointed to a file

### Screenshots

Screenshot from 2022-10-12 08-28-12

### Configuration

| key                | value                                    |
| ------------------ | ---------------------------------------- |
| version            | 0.69.2                                   |
| branch             | main                                     |
| commit_hash        | 118033e4a58a415bb5e01820bf50f3b27bf1cb21 |
| build_os           | linux-x86_64                             |
| build_target       | x86_64-unknown-linux-gnu                 |
| rust_version       | rustc 1.64.0 (gentoo)                    |
| cargo_version      | cargo 1.64.0                             |
| pkg_version        | 0.69.2                                   |
| build_time         | 2022-10-10 08:43:05 +08:00               |
| build_rust_channel | release                                  |
| features           | default, trash, which, zip               |
| installed_plugins  |                                          |

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by alesito85**
# Description

Fixes #6706.

I took a look at this issue and it seems that the issue is because the path is canonicalized and thus derives to the target. I've tested it locally by checking if the path is a symlink and acting accordingly to not canonicalize it and it seems fine.

In current release if the target is deleted but the symlink remains and one `ls`'s it, it throws a `directory not found` error. But with the fix it still shows the symlink (with red background, indicating missing target).

The change I've applied only triggers when `ls` is done on a symlink, on all other counts it should basically do the same as before.

# User-Facing Changes

_(List of all changes that impact the user experience here. This helps us keep track of breaking changes.)_

# Tests + Formatting

Don't forget to add tests that cover your changes.

Make sure you've run and fixed any issues with these commands:

- `cargo fmt --all -- --check` to check standard code formatting (`cargo fmt --all` applies these changes)
- `cargo clippy --workspace -- -D warnings -D clippy::unwrap_used -A clippy::needless_collect` to check that you're using the standard code style
- `cargo test --workspace` to check that all tests pass

## List existing symlink and target

Current
```
ls a_symlink                                                                                                                                                                                ╭───┬────────┬──────┬──────┬──────────────╮
│ # │  name  │ type │ size │   modified   │
├───┼────────┼──────┼──────┼──────────────┤
│ 0 │ a_file │ file │  0 B │ 20 hours ago │
╰───┴────────┴──────┴──────┴──────────────╯
```
With fix
```
ls a_symlink                                                                                                                                                                                ╭───┬───────────┬─────────┬──────┬──────────────╮
│ # │   name    │  type   │ size │   modified   │
├───┼───────────┼─────────┼──────┼──────────────┤
│ 0 │ a_symlink │ symlink │  6 B │ 20 hours ago │
╰───┴───────────┴─────────┴──────┴──────────────╯
```

## List existing symlink with missing target

Current
```
ls symfile_x                                                                                                                                                                          
Error: nu::shell::directory_not_found (link)

  × Directory not found
   ╭─[entry #13:1:1]
 1 │ ls symfile_x
   ·    ────┬────
   ·        ╰── directory not found
   ╰────
```

With fix
```
ls symfile_x                                                                                                                                                                          ╭───┬───────────┬─────────┬──────┬─────────────╮
│ # │   name    │  type   │ size │  modified   │
├───┼───────────┼─────────┼──────┼─────────────┤
│ 0 │ symfile_x │ symlink │  6 B │ 2 hours ago │
╰───┴───────────┴─────────┴──────┴─────────────╯
```

### CODE REVIEW

**Comment by fdncred** [comment]
After your PR, is there a way to tell what the symlink is pointing to? Like I've seen some system says `a_simlink -> a_file`. I was thinking that's what our `target` column was for but maybe I'm wrong?

**Comment by alesito85** [comment]
This hasn't changed actually and is still display when used in conjunction with a switch `ls -l {file}`.

image

**Comment by fdncred** [comment]
Thanks for confirming @alesito85

**Comment by alesito85** [comment]
No problem, let me know if you'd like me to check anything else.

**Comment by fdncred** [comment]
Thanks

**Pull request merged**
