### PR TITLE
Support automated tests that need a terminal emulator

### PR DESCRIPTION
**Pull request by YizhePKU**
This PR adds support for tests that need a terminal emulator. It adds the `alacritty_terminal` crate as a dev-dependency. The terminal state is kept in memory (no actual rendering takes place) and connected to a Nushell process via a PTY.

Two test cases are added as a demonstration, one for auto-cd and one for PWD-aware command hints.

### CODE REVIEW

**Comment by fdncred** [comment]
Thanks for this. If we can get this green, it has the potential to significantly help with testing things we cannot test today. I'm excited about this PR!

**Comment by YizhePKU** [comment]
Turns out the CI failure had nothing to do with MacOS. The problem was that there is no `config.nu` in the CI environment, so Nushell was asking if I want to create one with default, expecting me to type Y/N in the terminal. The solution is to always use `--no-config-file` (or specify both `--config` and `--env-config` explicitly).

**Comment by YizhePKU** [comment]
> Seems like there should be a --ci that loads the default configs or something.

Isn't `--no-config-file` doing just that?

**Comment by fdncred** [comment]
It doesn't technically load a default config. That's why when you run `nu -n` there is no `$env.config` entry.

**Comment by YizhePKU** [comment]
In any case, `--no-config-file` works for most tests, so it shouldn't affact this PR.

**Comment by rgwood** [comment]
This is very cool!

The `std::thread::sleep(Duration::from_millis(500));` is a little unfortunate; I wonder if it would make sense to handle waiting inside `pty_with_nushell()`. Could do something like poll the pty output until it generates the default Nushell prompt (and time out if it's not seen within a few seconds)?

**Comment by YizhePKU** [comment]
> I wonder if it would make sense to handle waiting inside pty_with_nushell().

That sounds good.

> Could do something like poll the pty output until it generates the default Nushell prompt (and time out if it's not seen within a few seconds)?

I tried a number of approaches (including polling), and sleeping for 500ms seemed to be the most reliable option. I don't really understand what is causing the issue, though, so take it with a grain of salt. In any case, sleeping for 500ms should have little impact on debugging and CI.

**Comment by rgwood** [comment]
> In any case, sleeping for 500ms should have little impact on debugging and CI.

I'm not sure I agree. We have a _lot_ of tests and parallelism is limited. Waiting for 500ms is not a huge deal in 1 or 2 tests but if we start adding more terminal emulator tests this kind of `sleep()` call will impact overall test times.

**Comment by YizhePKU** [comment]
> We have a lot of tests and parallelism is limited. Waiting for 500ms is not a huge deal in 1 or 2 tests but if we start adding more terminal emulator tests this kind of sleep() call will impact overall test times.

Really? When I test locally, my CPU usage is saturated at 100% a lot, so I was not expecting `sleep()` to cause trouble.

Shouldn't parallelism solve the problem?

**Comment by rgwood** [comment]
Tools like `cargo nextest` (which run tests in parallel) generally limit the numbers of tests that can be running at once (to limit memory consumption, I think).

I often run `cargo nextest` and notice that a batch of relatively slow tests (usually the plugin ones IIRC) block other tests from starting for a long time.

**Comment by sholderbach** [comment]
What is needed to make progress on this endeavour? Would love to see those added tests, as long as we do not grind our CI to a halt.

**Comment by rgwood** [comment]
> What is needed to make progress on this endeavour?

Possibly nothing. I think the `sleep(500ms)` is icky and we can+should do better, but it's not necessarily a blocker if @YizhePKU doesn't have time for that.

**Comment by YizhePKU** [comment]
Closing in favor of https://github.com/nushell/reedline/pull/847.

**Comment by sholderbach** [comment]
There may be some rare other places where we want to mock the user interactions like the `input` command or `explore` but if you get this going for `reedline` we are already a big step ahead.

**Pull request closed without merging**
