### PR TITLE
Remove feat `extra` and include in default

### PR DESCRIPTION
**Pull request by sholderbach**
# Description
The intended effect of the `extra` feature has been undermined by introducing the full builds on our release pages and having more activity on some of the extra commands.

To simplify the feature matrix let's get rid of it and focus our effort on truly either refining a command to well-specified behavior or discarding it entirely from the `nu` binary and moving it into plugins.

## Details
- Remove `--features extra` from CI
- Don't explicitly name `extra` in full build wf
- Remove feature extra from build-help scripts
- Update README in `nu-cmd-extra`
- Remove feature `extra`
- Fix previously dead `format pattern` tests
- Relax signature of `to html`
- Fix/ignore `html::test_no_color_flag`
- Remove dead features from `version`
- Refine `to html` type signature

# User-Facing Changes
The commands that were previously only available when building with `--features extra` will now be available to everyone. This increases the number of dependencies slightly but has a limited impact on the overall binary size.

# Tests + Formatting
Some tests that were left in `nu-command` during cratification were dead because the feature was not passed to `nu-command` and only to `nu-cmd-lang` for feature-flag mention in `version`.
Those tests have now been either fixed or ignored in one case.

# After Submitting
There may be places in the documentation where we point to `--features extra` that will now be moot (apart from the generated command help)

### CODE REVIEW

**Comment by kubouch** [comment]
Does it mean that the "full" builds still exist, but compared to normal builds, they have only dataframe support? I'm wondering that maybe we should rename them to "dataframe" to make it clearer (and also make a clear cut from the previous full builds, which were extra+dataframe).

**Comment by sholderbach** [comment]
Yes I kept the `full-` ... builds under the same name for now (don't know who depends on the name. But yes `dataframe` would probably be more honest now.

**Comment by sholderbach** [comment]
> Yes I kept the `full-` ... builds under the same name for now (don't know who depends on the name on top of https://github.com/hustcer/setup-nu/blob/main/src/setup.ts). But yes `dataframe` would probably be more honest now.

**Comment by kubouch** [comment]
I'd personally vote for the "dataframe" name. Not sure if it's better to do in this PR, I'm OK also landing this and renaming it later, we still have time until the next release.

**Comment by hustcer** [comment]
I think It's not a bad idea to keep the current name unchanged:
1. Users who want to use `dataframe` feature may already download it by grep `*-full`, not only [`setup-nu`](https://github.com/hustcer/setup-nu/blob/main/src/setup.ts), it's unwise to break their scripts.
2. Renaming it to `*-dataframe` is a good choice in the short term, but what if we need to put some other features outside of `default` later? Do we rename `dataframe` to `full` again?

That's why I think it's better to adapt to changes with no changes 🤣

**Comment by stormasm** [comment]
I am fine with removing *--features extra*  

and just having those commands located in the crate *nu-cmd-extra*

be part of the main binary...

**Review by stormasm — APPROVED** [review]
See my other comment in the PR.

**Comment by sholderbach** [comment]
> Not sure if it's better to do in this PR, I'm OK also landing this and renaming it later, we still have time until the next release.

Agree, let's refine the name / messaging around the "full" build elsewhere. I am probably sharing the concern with @hustcer that there is some breakage risk/confusion when doing a rename.

 
> 2\. what if we need to put some other features outside of `default` later? Do we rename `dataframe` to `full` again?

We simply shouldn't do it. If it doesn't warrant inclusion with the main Nushell build it should probably be removed entirely or never added before exhausting the options using plugins. We have some remaining features (that are enabled by default) which may matter for building on limited platforms.

**Comment by fdncred** [comment]
I labeled this breaking change because people who build this for package managers may try to build with --features=extra and get an error.

**Pull request merged**
