### PR TITLE
Add pipeline support for start command

### PR DESCRIPTION
**Pull request by horasal**
This pr adds pipeline data support for `start` command.

# Description

Currently, `start` can only be used with a positional parameter, and if user tries to run 

```
$nu.current-exe | path dirname  | start
```

There will be a error message:

This pr makes this work.

# User-Facing Changes

Users can either pipeline a string to `start` or use a positional parameter.

```bash
start path_to_start

# both external and internal command work
$nu.current-exe | path dirname | start
ls | first | get name | ^echo $in | start
```

there will be an error if 

* pipelined data is not a string or external stream
    
* pipeline data and positional parameter exist at the same time
    

# Tests + Formatting

- :green_circle: `toolkit fmt`
- :green_circle: `toolkit clippy`
- :green_circle: `toolkit test`
- :green_circle: `toolkit test stdlib`

# After Submitting

None

### CODE REVIEW

**Comment by WindSoilder** [comment]
Hi, thanks for your pr.
But I'm not sure why do you want this?  What's the matter if we use it as positional parameter?

**Comment by horasal** [comment]
one of the concepts of nushell is that piping data between commands and so it's natural for every command to accept pipelined data. 

```
from https://www.nushell.sh/book/thinking_in_nu.html#nushell-isn-t-bash

Thinking in Nushell: The way Nushell views data is that data flows through the pipeline until it reaches the user or is handled by a final command. You can simply type data, from strings to JSON-style lists and records, and follow it with | to send it through the pipeline. Nushell uses commands to do work and produce more data. Learning these commands and when to use them helps you compose many kinds of pipelines
```

considering the example in this pr, with current `start`, if want to open the folder containing `nu`, user usually starts from finding its path:

```bash
$nu.current-exe | path dirname
```

and now if you want to start it, you have to insert a command BEFORE everything:

```
start ($nu.current-exe | path dirname)
```

it behaves differently from other commands like `table` , `describe`, `print`, `save` and requires user to move the cursor around.

**Review by sholderbach — CHANGES_REQUESTED** [review]
I currently don't want to take on this implementation of having to include all that boilerplate for switching between the input sources and handling the errors gracefullly in the particular command.

Could we survey all the commands that provide this input duplication and if we consider it worthwhile to add to `start`, factor out this logic into a command common helper?

**Comment by fdncred** [comment]
Thanks for working on this and trying to make nushell better.

We discussed this in our team meeting last week and decided not to accept this at this point. We really want to live with the spread operator (...$var) for a while and see if that helps this situation.

**Pull request closed without merging**
