### PR TITLE
Update removed "MDI" icons to current MD icons

### PR DESCRIPTION
**Pull request by SED4906**
# Description

This PR updates now-removed (since NF 3.0.0) file icons shown in e.g. `grid` to their updated codepoints.

# User-Facing Changes

File icons changed were for:
`cs`, `csproj`, `csx`, `license`, `node`, `rtf`, `vue`, `xml`, and `xul`

# Tests + Formatting

# After Submitting

### CODE REVIEW

**Comment by fdncred** [comment]
@SED4906 I'm not opposed to this PR if you can get the CI green.

**Comment by SED4906** [comment]
hm, I'm still not sure why it's not green. the warnings just said "Warning: Diff in /home/runner/work/nushell/nushell/crates/nu-command/src/viewers/icons.rs at line (number)" and I have no clue what it is trying to bring attention to.

**Comment by SED4906** [comment]
oh, the comments showing the actual icons got pushed forward a column and this made cargo fmt unhappy

**Comment by amtoine** [comment]
let's land this and see how it goes, thanks @SED4906 :blush:

**Pull request merged**
