### PR TITLE
Reimplement parsers with nu-serde

### PR DESCRIPTION
**Pull request by lily-mara**
The nu-serde crate allows us to become much more generic with respect to how we
convert output to `nu-protocol::Value`s. This allows us to remove a lot of the
special-case code that we wrote for deserializing JSON values.

Additionally, it appears that the previous JSON parser was noncompliant.
Unquoted strings and optional commas between items in lists were previously
supported. I'm not sure if it's acceptable to lose this flexibility in favor of
adhesion to the JSON spec.

I did not redo the yaml parser, because the code was less clear when I tried to filter out the unquoted yaml template values like `{{ string }}`.

### CODE REVIEW

**Comment by fdncred** [comment]
wow - super pumped to see this.

hmmm... good questions about nu-json. IIRC, we kept nu-json because, we liked it's predecessor, hjson but hjson was no longer maintained and we needed to make changes. We also liked how hjson maintained ordering (i think), allowed comments in json, and other things. I'd suspect @jntrnr would want to chime in because I'm not sure if I'm remembering all the reasons we forked it exaclty.

i also was wondering if nu-serde would/could work with yaml & toml files. you mentioned yaml, so i follow there. we do a bit of io with the config.toml and it would be nice to streamline that too. i while back i wanted to use toml-edit because it preserved toml comments but i never got around to implementing it correctly.

**Comment by jntrnr** [comment]
This is one of those "it's unfortunate" kinds of things. We've tried moving onto the more standard json serde a few times, but unfortunately it's so strict that it seems to break many people's json files. For example, at least last time I tried it, it wouldn't let you put comments in your json. While technically correct, comments are in lots of files.

I wonder if there's a way to do a similar fix but to use the hjson package (or something like it) instead of the serde-json one. I think the main thing is the comments, but the quotes around keys may also be important.

Let me tag @andrasio also. If I'm remember correctly, he's the one that hit the snag last time to we tried to move away from hjson.

**Comment by lily-mara** [comment]
Good news; the thing that we need exists - [serde_hjson::Value](https://docs.rs/serde-hjson/0.9.1/serde_hjson/value/enum.Value.html). Bad news; serde-hjson appears to be unmaintained and has not been updated to support serde 1.0, so we cannot use it.

**Comment by jntrnr** [comment]
@lily-mara - I was trying to remember where `nu-json` came from. Would you believe it's a fork of serde_hjson, updated for serde 1.0? One of us must have done it after seeing that serde-hjson was unmaintained.

**Comment by fdncred** [comment]
lolz - this is in our config.toml for nu-json
```toml
[package]
authors = ["The Nu Project Contributors", "Christian Zangl <laktak@cdak.net>"]
description = "Fork of serde-hjson"
edition = "2018"
license = "MIT"
name = "nu-json"
version = "0.34.1"
```
I was thinking we just brought over hjson but apparently not. Along with comments, there was something about maintaining order of things in the json file or sorting or something like that as well. I distinctly remember JT, Andres and I discussing it somewhere.

**Comment by fdncred** [comment]
@lily-mara with all these comments in mind, when you get a sec, could you please update this pr to use our nu-json, which under the hood, is serde-hjson but updated?

**Comment by lily-mara** [comment]
Yes, I've been a bit busy but let me look into that tonight

**Comment by lily-mara** [comment]
The line diff count is not nearly as impressive as it was previously, but I have re-added the nu-json crate and reverted the changes that I made to the non-conforming JSON tests

**Comment by fdncred** [comment]
Thanks!

**Pull request merged**
