### PR TITLE
Tango migration

### PR DESCRIPTION
**Pull request by FilipAndersson245**
# Description

This PR migrates the benchmark suit to Tango. Its different compared to other framework because it require 2 binaries, to run to do A/B benchmarking, this is currently limited to Linux, Max, (Windows require rustc nightly flag), by switching between two suits it can reduce noise and run the code "almost" concurrently. I have have been in contact with the maintainer, and bases this on the dev branch, as it had a newer API simular to criterion. This framework compared to Divan also have a simple file dump system if we want to generate graphs, do other analysis on later. I think overall this crate is very nice, a lot faster to compile and run then criterion, that's for sure. 

# User-Facing Changes

# Tests + Formatting

# After Submitting

### CODE REVIEW

**Comment by kubouch** [comment]
Sorry for being late, I meant to reply to the other PR. I'd personally go back to criterion, just to be able to do single-point benchmarks with JSON output that can be processed later. It is also more actively developed than Tango, just judging from the number of contributors and overall activity. I guess Tango could run in the CI after each PR to check for regressions? Can it also run a single benchmark? If so, we could potentially use it, but we can't have git dependencies because of publishing. So I'd vote for moving back to criterion and experimenting more later.

**Comment by FilipAndersson245** [comment]
> Is there a way to set up the benchmarks to use multiple benchmarking frameworks? E.g., criterion for spot benchmarks and tango for A/B benchmarking in the CI.
> 
Tango supports running pointwise aswell, it will just run against itself, but the result should be equivalent. The main point is that pointwise measurement are bad in CI, cause the allocated CPU time have high variety, A/B are run  together so the relative difference should be roughly equal even on different hardware.

> Also, one point I wanted to bring up is to focus on actually doing something useful with the benchmarks. We could e.g. polish https://github.com/amtoine/nu-criterion-tracker , have it running on a server and add some plotting backend to it. Another option is https://github.com/iai-callgrind/iai-callgrind to reduce the noise. Tango also can be used, but again, we should first come up with a use case, e.g., run in the CI after each PR to check for regressions, and see if it's feasible (e.g., if it doesn't add too much time to the CI run).

I think it would be nice to use something like callgrid, but I cannot run it as it requires some hardware flags that don`t exist thanks to that I run most of my dev stuff through WSL, and it seems impossible to run on Windows.

I am in talks with the author of Tango, and he recommended testing out the updated API. I can try to ping and see when he will update crates.io so that would be a non-issue.

Also I see no specific problem with having two suits, live parallel at least for some time, I believe you can specify what bench suit you want to run quite easily.

**Comment by FilipAndersson245** [comment]
> Sorry for being late, I meant to reply to the other PR. I'd personally go back to criterion, just to be able to do single-point benchmarks with JSON output that can be processed later. It is also more actively developed than Tango, just judging from the number of contributors and overall activity. I guess Tango could run in the CI after each PR to check for regressions? Can it also run a single benchmark? If so, we could potentially use it, but we can't have git dependencies because of publishing. So I'd vote for moving back to criterion and experimenting more later.

Yee tango is younger, and I guess did not blow up as much as Divan did on reddit with its initial blog. I was its first fork 😎, Atleast there I have been able to have communication with the maintainer, in the other repos the main author seems to be quite infrequent looking over it, Criterion maintainer hasn't committed in over a year. and the rework of the internals seem to not have been touched for over two years now.

**Comment by kubouch** [comment]
The point-wise benchmarks are important for long-term performance tracking and be able to build something similar to https://perf.rust-lang.org. In a default CI, the variance will be high, but that can be improved by running on a dedicated machine (e.g., someone's old leftover laptop). iai-callgrind on Linux could complement the results, we'd need to experiment.

A/B benchmarking is more useful when comparing two revisions. To me, that seems ideal as a CI step checking for performance regressions after each PR (if it doesn't take too long; it could run only a smaller set of the benchmarks).

If we could do both with Tango, that would be ideal, but IMO we should still wait until the new API is merged so that we don't have a git dependency.

**Comment by FilipAndersson245** [comment]
> The point-wise benchmarks are important for long-term performance tracking and be able to build something similar to https://perf.rust-lang.org. In a default CI, the variance will be high, but that can be improved by running on a dedicated machine (e.g., someone's old leftover laptop). iai-callgrind on Linux could complement the results, we'd need to experiment.
> 
> A/B benchmarking is more useful when comparing two revisions. To me, that seems ideal as a CI step checking for performance regressions after each PR (if it doesn't take too long; it could run only a smaller set of the benchmarks).
> 
> If we could do both with Tango, that would be ideal, but IMO we should still wait until the new API is merged so that we don't have a git dependency.

Agree, Nothing would stop us from having the benchmarks be separate except the possible extra dependency and code. I will try to update the criterion so we can move that back, and rename this to tang-benchmarks.

iai-callgrind looks interesting, I will try to look over it this weekend, think that would possible be more interesting in pointwise measurment.

**Comment by FilipAndersson245** [comment]
@kubouch I think this is ready for a review, now

**Comment by kubouch** [comment]
Just a few comments about the toolkit commands:
* The scripts do not seem to account for CARGO_TARGET_DIR environment variable. I have it set to a global destination. Perhaps this should be taken into account instead of assuming the build artifacts are in `./target/`.
* Perhaps the commands could have a shorter name and be merged into one? E.g. `benchmark` would run the current benchmark, and `benchmark --compare xyz` would compare the current branch against `xyz`. Just to make it more concise and also more powerful than hardcoding the main branch.
* The double quotes in command names are unnecessary :-)

Anyway, I'm also fine with merging as-is. But we are also pausing PR merging until after the release, so you can still tweak it until about Wednesday or so.

**Comment by WindSoilder** [comment]
Hi, @FilipAndersson245 Thanks for your migration!  Would you resolve conflicts?  So we can land it

**Comment by FilipAndersson245** [comment]
I do not understand why the tests break, as far as know I have not changed tests that would break existing texts?

**Comment by kubouch** [comment]
Maybe the test inputs were somehow changed by switching to Tango? Does it fail on your machine as well, or only in the CI?

**Comment by FilipAndersson245** [comment]
It does on my linux machine aswell, but i don't understand why it would.

**Comment by IanManske** [comment]
It looks like the `base64` crate was patch bumped from 0.22.0 to 0.22.1 in this PR. The newer version fixes an issue/bug with binhex encoding which breaks some of the "expected" output in our tests.

**Comment by IanManske** [comment]
Thanks for working on this! (It looks like a bunch of unrelated crates were updated in the `Cargo.lock`, but the CI is green.) Merging :rocket:

**Pull request merged**
