### PR TITLE
to-html: replace baby-poop yellow with reddish

### PR DESCRIPTION
**Pull request by jzaefferer**
Follow-up to #2200
See also https://github.com/nushell/wasm-nu/issues/5#issuecomment-660298534

Before:
Screenshot 2020-07-18 at 10 27 00

After:
Screenshot 2020-07-18 at 10 26 52

cc @fdncred

### CODE REVIEW

**Comment by fdncred** [comment]
@jzaefferer Can we keep it somewhere in the yellow family? I'd prefer for the colors to match the terminals as close as we can. Perhaps we could change the background from brilliant white to more of an off-white which will help text like yellow. Another way through this is to look at one of those windows terminal themes and see what their "yellow" color is.

**Comment by jonathandturner** [comment]
Would it make sense to have `to html` optionally take in the colors to use, or would that be too inconvenient?

**Comment by fdncred** [comment]
I'm finishing up some test settings in `to html` right now #2219 that kind of make way for themes. Right now there is a hard coded theme named `default` and a theme named `campbell` which is microsoft's windows terminal default theme. So, i added `--campbell` as a way to change the theme from `default` to `campbell`. I see `--campbell`  as a temporary parameter for testing  and vetting out what we should really do.

What I'm not sure about is how to store themes. We could easily copy Microsoft's dozen themes in a json format or write something that takes iterm2 color themes. But at this point they'd only be useful for `to html` and we'd need to distribute them in the config location.

if we want to test with some other theme, all i need is the 16 colors and name in the format that is in the code now. i can add new parameters to test other things. But I'm not sure how much further we can go at this point.  If we don't like the colors we can change them. If we want a new them, we can add it.

**Comment by jzaefferer** [comment]
> Can we keep it somewhere in the yellow family? I'd prefer for the colors to match the terminals as close as we can.

I tried that again, but it all looks pretty bad, both with the base yellow hue and a more orange hue. To get decent contrast it always looks shitty.

> Perhaps we could change the background from brilliant white to more of an off-white which will help text like yellow. 

I tried that, too, but it didn't help. A background color like #eee (lightish gray) already looks quite different from pure white, but barely helps with the contrast (at least according to the Firefox DevTools).

> Another way through this is to look at one of those windows terminal themes and see what their "yellow" color is.

I found these for iTerm 2: https://github.com/mbadolato/iTerm2-Color-Schemes/tree/master/screenshots#screenshots I have no idea what those codes mean - maybe you can make sense of them?

**Comment by fdncred** [comment]
Pick one of those from the iterm2 site and i'll see if i can get it integrated somehow. Just remember that we generally we can do a light background with whatever foreground colors or a dark background with whatever color. I don't think we can easily cover all those columns of background colors. Or for that matter, pick a light theme and a dark theme but we can really only do the column to the left of the 40m column.

Just for your information, the columns are background colors, the rows are the foreground colors `1;` means bold or bright for the row colors.

Technically nu could do all the background colors too but it would take some work.

**Comment by jzaefferer** [comment]
I think of the light ones this `github.png` looks pretty solid: https://github.com/mbadolato/iTerm2-Color-Schemes/blob/master/screenshots/github.png

I don't feel particularly qualified for that kind of choice, but hopefully this gets as a little further.

**Comment by fdncred** [comment]
Here's the github theme as rendered by `to html` on the left and `windows terminal` on the right. It's close. Thoughts on it? I'll look at some other `light` themes and see what I can find. [This site](https://atomcorp.github.io/themes/) is pretty cool for theme hunting.
image

**Comment by fdncred** [comment]
This one called `blulocolight` isn't too bad.
image

**Comment by jzaefferer** [comment]
Of those three, `blulocolight` makes the best overall impression.

> Updated with same font hard-coded in the html.

What did you set? Should that be set by the demo code? (or wherever `to html` gets used)

**Comment by jzaefferer** [comment]
With `to html --html_color --theme 'blulocolight'`:

Screenshot 2020-07-25 at 18 57 32

Looks good to me!

**Pull request closed without merging**
