### PR TITLE
`++=` appendAssign operator (#7346)

### PR DESCRIPTION
**Pull request by raccmonteiro**
# Description

Closes  https://github.com/nushell/nushell/issues/7346

# Tests + Formatting
```
> mut a = [1 2 3]
> $a ++= [4 5 6]
> $a
[1 2 3 4 5 6]
```

### CODE REVIEW

**Comment by webbedspace** [comment]
Please write tests. Just copy-paste the `++` tests and tweak them if you must. \*someone comes in and informs me that `++` has no tests either\* Ah! Well. Nevertheless,

**Comment by raccmonteiro** [comment]
Added some tests.
But, I noticed this does not work
```
> mut a = [1 2 3]
> $a ++= [a]
```
results in this error:
image

This should be a valid case, right? I did not understood yet where this error is being thrown. 
If someone wants to help please be free to make the changes :)

**Review by sholderbach — APPROVED** [review]
Your code and tests look good to me!

**Comment by sholderbach** [comment]
I think constraining the type of a mutable variable to the one at assignment time sounds less surprising, but the question is if for this the list should be opaque with the inner type erased (`list<any>`).

> Added some tests. But, I noticed this does not work
> 
> ```
> > mut a = [1 2 3]
> > $a ++= [a]
> ```
> 
> results in this error: image
> 
> This should be a valid case, right? I did not understood yet where this error is being thrown. If someone wants to help please be free to make the changes :)

**Comment by rgwood** [comment]
> I think constraining the type of a mutable variable to the one at assignment time sounds less surprising

I agree, this seems like the right behaviour to me.

> the question is if for this the list should be opaque with the inner type erased (list<any>).

I think `a` should be as specific as possible by default (`list<int>`), but we should allow the user to opt into `list<any>`. Beyond the scope of this PR but it would be nice to be able to do something like `mut a: list<any> = [1 2 3]`

**Review by rgwood — APPROVED** [review]

**Comment by rgwood** [comment]
I think this could use another test checking that the case above (`mut a = [1 2 3]; $a ++= [a]`) returns an error. But it's not 100% necessary and this could be merged as is. Thanks @raccmonteiro!

**Comment by rgwood** [comment]
btw, this is interesting (but not something that needs to be fixed in this PR IMO):

image

I haven't taken a look at the implementation but it looks like we are not handling covariance correctly.

**Comment by raccmonteiro** [comment]
> I think this could use another test checking that the case above (`mut a = [1 2 3]; $a ++= [a]`) returns an error. But it's not 100% necessary and this could be merged as is. Thanks @raccmonteiro!

I added this case, I didn't do it before because I thought this should not result in error.


Thank you both for explaining your thoughts

**Pull request merged**
