### PR TITLE
Highlight matching brackets / parentheses

### LINKED ISSUE #4325: Highlighting matching brackets / parentheses
This might be more a reedline feature request. A cool thing would be to highlight a matching paren / brace / bracket when the cursor is on one.

### PR DESCRIPTION
**Pull request by paper-lark**
# Description

In this PR I propose a solution for matching bracket highlighting based on the AST. Thus, given the current cursor position we find the token to which it belongs and if the cursor is at the start/end of a specific token (a record, a list, a block, etc.) the other end of the token will be highlighted.

I decided it was a not a good idea to simply find a matching bracket without using ATS. The reason is, in some cases, like in case of `[\[]]` (where the `\[]` is a string), this would contradict the ATS.

This approach has some downsides:
1. Currently in tables only the outer brackets are matched.
2. If an expression is isolated with brackets in order for matching to work, the expression should be processed correctly in the `find_matching_bracket_in_expr` function.

Please, provide me the feedback on this solution. I will adjust the logic if necessary and cover the functionality with tests.

Fixes #4325.

# Tests

Make sure you've done the following:

- [ ] Add tests that cover your changes, either in the command examples, the crate/tests folder, or in the /tests folder.
- [ ] Try to think about corner cases and various ways how your changes could break. Cover them with tests.
- [ ] If adding tests is not possible, please document in the PR body a minimal example with steps on how to reproduce so one can verify your change works.

Make sure you've run and fixed any issues with these commands:

- [x] `cargo fmt --all -- --check` to check standard code formatting (`cargo fmt --all` applies these changes)
- [x] `cargo clippy --workspace --features=extra -- -D warnings -D clippy::unwrap_used -A clippy::needless_collect` to check that you're using the standard code style
- [x] `cargo test --workspace --features=extra` to check that all the tests pass

### CODE REVIEW

**Comment by fdncred** [comment]
I'm trying to figure out what this does. I mean, I figure it is highlighting matching brackets and parens but I can't seem to get it to work on Windows. Do you have some examples I can try with screenshots please?

**Comment by paper-lark** [comment]
> I'm trying to figure out what this does. I mean, I figure it is highlighting matching brackets and parens but I can't seem to get it to work on Windows. Do you have some examples I can try with screenshots please?

Strange it did not work on Windows. Perhaps, it has something to do with `reverse()` style.
Here is a little demo

https://user-images.githubusercontent.com/23142244/193612696-070b439b-ba39-40d7-a441-b14f8ab71bf1.mov

**Comment by fdncred** [comment]
ok, that helps a bunch. I can see it working now on Windows. It doesn't work while typing at all, not sure if it's supposed to or not but it does work if you arrow left or right through the string. See windows below. It would be cool if it highlighted when typing too. Also, I missed the point that the highlight was supposed to be reverse() ansi. I was looking for rainbow where first paren is red, the next is orange, the next is yellow, etc. reverse is fine though.

highlight_parens

**Comment by dandavison** [comment]
@paper-lark this looks exciting. I think that there's a bug exhibited here:

image

image

**Comment by paper-lark** [comment]
> ok, that helps a bunch. I can see it working now on Windows. It doesn't work while typing at all, not sure if it's supposed to or not but it does work if you arrow left or right through the string. See windows below. It would be cool if it highlighted when typing too. Also, I missed the point that the highlight was supposed to be reverse() ansi. I was looking for rainbow where first paren is red, the next is orange, the next is yellow, etc. reverse is fine though.
> 
> highlight_parens [ highlight_parens ](https://user-images.githubusercontent.com/343840/193620589-35331398-0a37-4086-b07b-dee77fc27dba.gif) [ ](https://user-images.githubusercontent.com/343840/193620589-35331398-0a37-4086-b07b-dee77fc27dba.gif)

We could do matching while typing too. I'll have a look at how it is implemented in different text editors

**Comment by sholderbach** [comment]
Excited for this, let me know if the syntax higlighting API of `reedline` has to be improved to make the highlighting while typing easier.

**Comment by fdncred** [comment]
@paper-lark Just checking in. This is a cool feature. Wondering if it'll make it in by our next release or if we should plan on it landing after that. The next release is Oct 18th.

**Comment by paper-lark** [comment]
> @paper-lark Just checking in. This is a cool feature. Wondering if it'll make it in by our next release or if we should plan on it landing after that. The next release is Oct 18th.

Sorry, I don't think I'll have time to complete it by the release date :c

**Comment by fdncred** [comment]
Since it's not ready to land yet I removed the wait-until-after-nushell-release label and just changed it to a draft until we can move forward. Thanks.

**Comment by paper-lark** [comment]
@fdncred I fixed matching while typing.
@dandavison However, I didn't come up with a solution for the bug you'd found. It is related to spans that the parser returns.  In particular, in your case parser treats the closing bracket as the end of the outer list. Hence the strange highlight. I'm a bit hesitant about changing it.

https://user-images.githubusercontent.com/23142244/196045465-a9b34a72-9f97-479b-8704-e617304367a0.mov

**Comment by fdncred** [comment]
I still think this is totally rad. However, We can probably land this but I'm really wanting to have a different highlighting other than reverse in another PR. Only because reverse doesn't look that great in all terminals/themes like this one.

hilite

**Comment by paper-lark** [comment]
> I still think this is totally rad. However, We can probably land this but I'm really wanting to have a different highlighting other than reverse in another PR. Only because reverse doesn't look that great in all terminals/themes like this one. Or maybe it's just changed since last time I try it - it doesn't look this dark in my previous gif.

Maybe we should change the highlight style to underline instead or make it configurable?

**Comment by fdncred** [comment]
I would love to have it configurable somehow, but if you'd rather land this first, then make it configurable that's fine. Or if you just want to add it to this, I'm cool with that too.

Just thinking out loud here, but I think we'd want the color highlighting configuration to work like the other color configuration in the config.nu where it supports:
- hex colors like `#ffb000`
- named colors like `red`
- foreground, background, attribute colors like `{ fg: "#0c0c0c" bg: "#33ff00" attr: b}`

Just to be consistent.

**Comment by paper-lark** [comment]
@fdncred Let's merge this version first because it seems quite big as it is. But I'll start working on the configuration in the meantime.

**Comment by fdncred** [comment]
whoop whoop! let's go! thanks for this cool feature!

**Pull request merged**
