### PR TITLE
Attempts to add `skip if` command

### LINKED ISSUE #5738: skip if command
### Related problem

I am trying to delete lines containing any of a few keywords from a large file. I found out about `skip while`/`skip until` but they cannot do this job. But they inspired me to request something like `skip if`. It would be really useful in such cases.

More info in [this PR](https://github.com/nushell/nu_scripts/pull/249)

### Describe the solution you'd like

Basically the skipping shouldn't end after the first time condition gets True/False (like in `skip while`/`skip until`), so:

`echo [-1 0 -2 1 -3 2] | skip if $it < 0`

should return

`0 1 2`

### Describe alternatives you've considered

_No response_

### Additional context and details

_No response_

### PR DESCRIPTION
**Pull request by merelymyself**
# Description

Hopefully fixes #5738. @skelly37, do let me know if I misunderstood your request.

# Tests

Make sure you've run and fixed any issues with these commands:

- [x] `cargo fmt --all -- --check` to check standard code formatting (`cargo fmt --all` applies these changes)
- [x] `cargo clippy --workspace --features=extra -- -D warnings -D clippy::unwrap_used -A clippy::needless_collect` to check that you're using the standard code style
- [x] `cargo test --workspace --features=extra` to check that all the tests pass

### CODE REVIEW

**Comment by merelymyself** [comment]
@kubouch , I’ll admit I felt the same, but the linked issue got tagged instead of closed, so I was wondering if there was some use case where this would be valid.

**Comment by skelly37** [comment]
@merelymyself yeah, that's what I was talking about, thanks!

**Comment by fdncred** [comment]
@skelly37 can you help us understand with an example of how `where` doesn't solve this same problem please? i'd like to know before we make the decision on whether to land this or not.

**Comment by skelly37** [comment]
@fdncred Actually, I can't. I've been thinking about it but you all are right — `where` can do. Sorry for the mess...

**Comment by fdncred** [comment]
@merelymyself i think it was my prompting that someone make a `skip if` - sorry to waste your work here, but i think we should close this now. if you disagree, let's chat more.

@skelly37 no worries.

**Pull request closed without merging**
