### PR TITLE
Strict JSON parsing

### PR DESCRIPTION
**Pull request by IanManske**
# Description
Adds the `--strict` flag for `from json` which will try to parse text while following the exact JSON specification (e.g., no comments or trailing commas allowed). Fixes issue #11548.

### CODE REVIEW

**Comment by IanManske** [comment]
I opted to use `serde_json` instead of modifying `nu_json`, since this should be more futureproof and less error prone.
`serde_json` was already one of our dependencies, so it looks like the PR only adds ~45KiB to the binary size.

**Comment by fdncred** [comment]
I looked through this @IanManske. Are we ready to land it?

**Comment by IanManske** [comment]
Yep, I think this is ready!

**Comment by fdncred** [comment]
Thanks

**Pull request merged**
