### PR TITLE
deprecate `size` to `str size`

### PR DESCRIPTION
**Pull request by amtoine**
related to
- https://discord.com/channels/601130461678272522/614613939334152217/1164530991931605062

# Description
it appears `size` is a command that operates on `string`s only and gives the user information about the chars, graphemes and bytes of a string.
this looks like a command that should be a subcommand to `str` :smirk: 

this PR
- adds `str size`
- deprecates `size`

`size` is planned to be removed in 0.88

# User-Facing Changes
`str size` can be used for the same result as `size`.

# Tests + Formatting

# After Submitting
write a removal PR for `size`

### CODE REVIEW

**Comment by amtoine** [comment]
cc/ @fdncred

**Review by fdncred — APPROVED** [review]
Seems appropriate. 

This has nothing to do with your work here but it's still an odd command. Maybe it's supposed to be nushell's version of `wc`?

```nushell
❯ wc Cargo.toml 
 176  759 6094 Cargo.toml
❯ open Cargo.toml -r | size
╭─────────┬────╮
│lines    │176 │
│words    │743 │
│bytes    │6094│
│chars    │6094│
│graphemes│5918│
╰─────────┴────╯
```

**Comment by amtoine** [comment]
@fdncred 
yeah sounds like some kind of Nushell version to `wc` :thinking:

**Comment by fdncred** [comment]
I was wondering if `str info` might be better? It just seems like `str size` will be confused with `str length`.

**Comment by amtoine** [comment]
> I was wondering if `str info` might be better? It just seems like `str size` will be confused with `str length`.
>
it's the size in memory i'd say? :thinking:

**Comment by fdncred** [comment]
I'm not sure "size in memory" is correct either. Not really sure what the correct name is.
```
❯ "👨‍👨‍👧‍👦" | str size
╭───────────┬────╮
│ lines     │ 1  │
│ words     │ 0  │
│ bytes     │ 25 │
│ chars     │ 7  │
│ graphemes │ 1  │
╰───────────┴────╯
```

**Comment by hustcer** [comment]
`str stats`？

**Comment by fdncred** [comment]
ya, i could support `str stats`.

**Comment by amtoine** [comment]
feel free to overwrite this PR with a new name, we're inbetween two releases, so that's more than fine :wink: 
just remember that https://github.com/nushell/nushell/pull/10784 will have to be replaced as well :yum:

**Comment by fdncred** [comment]
@hustcer Do you feel like updating the name and #10784? If not, I can try to remember to do it.

**Pull request merged**
