### PR TITLE
Fuzzy completion matching

### PR DESCRIPTION
**Pull request by Tropid**
# Description

This adds a new `MatchAlgorithm::Fuzzy` which uses the `fuzzy-completer` crate from skim (https://github.com/lotabout/fuzzy-matcher) to complete suggestions with a "fuzzy" search.

This is opt-in and can be enabled in the `config.nu` by setting the new `completion_algorithm` setting to `fuzzy` instead of the `prefix` default:

```
let-env config = {
  ...
  completion_algorithm: "fuzzy"
  ...
}
```

I developed and tested it on Windows so the fuzzy-matcher crate seems to support Windows even if skim itself does not.

Custom completions can still override completion options, although the `positional` and `case_sensitive` option has no effect at the moment if the `completion_algorithm` for this custom completion is `fuzzy`.

# Examples

```
> git out<tab>
> git checkout

> git checkout featcompl<tab>
> git checkout feature/new-completions

> echo $env.chome<tab>
> echo $env.CARGO_HOME
```

# Known Issues

* Completion may be slower than "prefix" completion
* `case_sensitive` option for custom commands does not work with fuzzy completion algorithm

# Future ideas

* Highlight matching chars
* Sort completions by matching score

### CODE REVIEW

**Comment by fdncred** [comment]
oooooh, this is nice!

**Comment by fdncred** [comment]
anxious to try this.

**Comment by fdncred** [comment]
I like your future ideas too

**Comment by fdncred** [comment]
@Tropid - I see this fuzzy functionality work and not work. Is there tweaking that can be done or am I just not understanding how this is supposed to work.

* `vim iaps<tab>` completes to `vim ./install-all.ps1`
* `vim bui<tab>` <-- bad results `vim buil<tab>` <-- good results
* `vim sr<tab>` fails but `vim src<tab>` works

so, we're just trying to understand what is supposed to work or if we're testing it wrong, or what.

/cc @jntrnr

**Comment by Tropid** [comment]
@fdncred there is no tweaking. I would expect every single failing example you posted to work. I will look into it. I might not have any spare time today, though. So I will probably get to it tomorrow.

**Comment by Tropid** [comment]
Status update:

The problem seems to be the partial completions in the `ColumnarMenu` in reedline. The `can_partially_complete()` function tries to find the shortest common string in the suggestions. When using fuzzy matching there are multiple suggestions in the nushell repository for `vim bui`:

* ./build.rs
* **./CONTRIBUTING.md**
* ...

So the shortest common string is `.\` because `.\CONTRIBUTING.md` and the other `.\build*` suggestions only share this part. When typing `vim buil<tab>` the `.\CONTRIBUTING.md` suggestion is not present anymore so all suggestions share the `.\build` part and the completions look fine.

I'm not sure about `vim sr<tab>` because this completes just fine for me. I would guess you have another file which contains `s` and `r` in its name but does not start with `sr`.

**Comment by fdncred** [comment]
that all makes sense to me. the `vim sr<tab>` i think were @jntrnr's so i can't speak to what was in the folder but i figured it was the nushell folder.

so, is there a way around this to make fuzzy more reliable? i really like the functionality when it works.

**Comment by Tropid** [comment]
In my opinion the partial completion should never remove already entered input. In the example I would just expect it to not complete anything because there is no obvious partial completion. I have a lot of work tomorrow so I guess I'll get to propose a change on Thursday at the earliest.

**Comment by fdncred** [comment]
Thanks for the input. No rush. We can recommend leaving the config at prefix for now.

**Comment by fdncred** [comment]
We love having this type of fuzzy functionality but we may need to roll it back for the release we have coming up May 3rd. So, if you see us roll it back, it just means that it may need a little more work before releasing.

**Comment by fdncred** [comment]
@Tropid we're reverting #5254. can you take another look at fuzzy-things after it's laned?

**Comment by Tropid** [comment]
@fdncred After it's reverted or after it is applied again?

**Comment by fdncred** [comment]
@Tropid just reverted. it's landed now.

**Pull request merged**
