### PR TITLE
[WIP] Refactor commands to seperate crates

### PR DESCRIPTION
**Pull request by FilipAndersson245**
# Description

Im trying to split commands into multiple crates to improve the compile time of nushell.

# Tests + Formatting

Make sure you've done the following, if applicable:

- Add tests that cover your changes (either in the command examples, the crate/tests folder, or in the /tests folder)
  - Try to think about corner cases and various ways how your changes could break. Cover those in the tests

Make sure you've run and fixed any issues with these commands:

- `cargo fmt --all -- --check` to check standard code formatting (`cargo fmt --all` applies these changes)
- `cargo clippy --workspace --features=extra -- -D warnings -D clippy::unwrap_used -A clippy::needless_collect` to check that you're using the standard code style
- `cargo test --workspace --features=extra` to check that all tests pass

# User-Facing Changes

If you're making changes that will affect the user experience of Nushell (ex: adding/removing a command, changing an input/output type, adding a new flag):

- Get another regular contributor to review the PR before merging
- Make sure that there is an entry in the documentation (https://github.com/nushell/nushell.github.io) for the feature, and update it if necessary

### CODE REVIEW

**Comment by sholderbach** [comment]
Thanks for experimenting in that direction! Did you notice a particular blocker or is it just overwhelming work at the moment to get this into a clean state?

**Comment by FilipAndersson245** [comment]
Its quite alot of works, to transfer it into multiple crates, currently there are some items that cannot be seperated or they cause cylindrical dependencies, I will try to continue this work when i have time, i fell we can get some nice compile speedups from doing this.

**Comment by FilipAndersson245** [comment]
Its quite alot of works, to transfer it into multiple crates, currently there are some items that cannot be seperated or they cause cylindrical dependencies, I will try to continue this work when i have time, i fell we can get some nice compile speedups from doing this.

**Comment by sholderbach** [comment]
I think @stormasm also tried to break up `nu-command` once to have a minimal nu to embed into other projects. I think it was not trivial.
For the compile time heavy data-frames the future might possibly be that they are separately compiled as a core plugin/extension as we discussed in the meeting today.
With that evolving also as part of improving command consistency we might reach better primitives to base all the commands on.
If we can place that in a base crate, it would make this possibly a bit more cycles free.

**Comment by stormasm** [comment]
@sholderbach I did get a core command crate working / up and running with my iox work I did earlier in the summer...

However, since I only needed the core commands for Iox I didn't have to implement the other crate where all of the remaining commands lived...

https://github.com/stormasm/nu-command-core

Here was the other crate with the remaining commands...

https://github.com/stormasm/nu-command-iox/tree/main/src

Since this work happened back in June I can't really remember exactly
how all of this worked.

**Comment by stormasm** [comment]
@sholderbach this is an example of what we were discussing today in the meeting.

Prior to someone doing this work we should have a process in place where it is discussed with other people on the design team first.

Then we can decide whether or not this is something we would like to move forward on doing...

**Pull request closed without merging**
