### PR TITLE
Update rust-toolchain.toml to 1.67.1

### PR DESCRIPTION
**Pull request by fdncred**
# Description
This PR bumps the rust toolchain from 1.66.1 to 1.67.1

# User-Facing Changes

# Tests + Formatting

# After Submitting

### CODE REVIEW

**Review by amtoine — APPROVED** [review]
lgtm

**Comment by amtoine** [comment]
@fdncred
we can not just remove the lifetime there?
or add `-A clippy::needless-lifetimes` to suppress the *clippy* complaint?

**Comment by fdncred** [comment]
> @fdncred we can not just remove the lifetime there? or add `-A clippy::needless-lifetimes` to suppress the _clippy_ complaint?

I think it's in the tabled crate, not our code. I couldn't find it in our code. We could allow that lint but I'd prefer to not have a bunch of allows if possible.

**Comment by amtoine** [comment]
> I think it's in the tabled crate, not our code. I couldn't find it in our code.
>
mm that's more complex then :thinking: 

> We could allow that lint but I'd prefer to not have a bunch of allows if possible.
>
i agree :+1: 

maybe we should wait for this PR then? :confused:

**Comment by fdncred** [comment]
Yup, @sholderbach was right. It's in our code now. I just hadn't merged main. My fault @zhiburt, et. al. sorry.

**Pull request merged**
