### PR TITLE
update `reject` to be able to recive arg list

### PR DESCRIPTION
**Pull request by Tiggax**
This PR is in relation to #10215 

# Description

This PR introduces `reject` to receive list of columns or rows as argument.
This change is similar to change of `select` and the code used is similar.

# User-Facing Changes
The user will be able to pass a list as rejection arguments.
```nushell
let arg = [ type size ]
[[name type size]; [ cargo.toml file 20mb ] [ Cargo.lock file 20mb] [src dir 100mb]] | reject $arg
```

### CODE REVIEW

**Comment by fdncred** [comment]
@Tiggax I think I'm ready to land this. Is there a reason why it's still draft?

**Comment by Tiggax** [comment]
@fdncred I'm waiting for #10216 to land, since it might need some diff conflicts to resolve, since its the same file.

**Comment by fdncred** [comment]
> @fdncred I'm waiting for #10163 to land, since it might need some diff conflicts to resolve, since its the same file.

LOL, just landed that, and you're right. conflicts.

**Comment by Tiggax** [comment]
This looks like it should be ready to merge now @fdncred :innocent:

**Comment by fdncred** [comment]
Thanks!

**Pull request merged**
