### PR TITLE
Add virtual path abstraction layer

### PR DESCRIPTION
**Pull request by kubouch**
# Description

Adds the possibility to embed "virtual" files and directories into Nushell so that loading them does not require real physical paths on the file system.

The primary use case is loading the standard library. First, all the stdlib files are loaded as virtual files in a made-up `NU_STDLIB_VIRTUAL_DIR` directory: `NU_STDLIB_VIRTUAL_DIR/std/mod.nu`, `NU_STDLIB_VIRTUAL_DIR/std/dirs.nu`, etc. Then, when loading the stdlib, the parser's current working directory is set to the virtual directory. When parsing statements such as `use dirs.nu`, the parser looks into the virtual directories and finds the path there without it being present in the file system.

The virtual paths can be used in the future for other Nu code we might want to ship with Nushell, such as package manager.

One future use case for this could be "compiling" Nushell projects so that they can run on other machines without having to install their dependencies and requiring all source files to be on the file system. You could think of it as static linking.

Seems like loading stdlib from virtual paths improves the startup times by ~50 ms, too.

### Limitations

`source` and `source-env` currently load the virtual paths in the parser but they fail during evaluation. We'd need to add the support for virtual files to the engine in https://github.com/nushell/nushell/blob/db4b26c1acdb62e51d3f8615f8bb23b5045a79a4/crates/nu-engine/src/env.rs#L247

# User-Facing Changes

Faster stdlib loading

# Tests + Formatting

# After Submitting

### CODE REVIEW

**Comment by amtoine** [comment]
i have a drastic improvement with the startup time :scream: :eyes: 

`cargo run -- -n` gives me around
- `850ms` on latest `main`
- `280ms` with this PR

**Comment by kubouch** [comment]
Wow, that's a lot. I'll try to finish it so we can merge it.

**Comment by kubouch** [comment]
Startup times on my machine (Linux):
* `cargo run --release -- -n`: ~15 ms
* `nu -n`: 42-44 ms

**Comment by amtoine** [comment]
after more attempts
- `nu`: ~260ms
- `nu -n`: ~85ms
- `cargo run --release` on `nushell:main@db4b26c`: ~265ms
- `cargo run --release -- -n` on `nushell:main@db4b26c`: ~85ms

and now the real meat :smirk: 
- `cargo run --release` on `kubouch:stdlib-loading`: ~180ms
- `cargo run --release -- -n` on `kubouch:stdlib-loading`: ~30ms

very nice :ok_hand:

**Comment by cablehead** [comment]
I've just added the ability to cross.stream to [append Nushell modules](https://cablehead.github.io/xs/reference/topics/#module-topics) to the stream. As you do, the modules are registered in the base Nushell engine's vfs. Then any handler etc running on cross.stream can `use` these modules!

Thanks @kubouch for adding this feature, which made that possible 🙏

**Pull request merged**
