### PR TITLE
Starship prompt

### PR DESCRIPTION
**Pull request by jonathandturner**
Make starship prompt an optional feature for Nu. Builds on work by @Southclaws 

Screenshot from 2019-11-17 06-17-27

Closes #804

### CODE REVIEW

**Comment by jonathandturner** [comment]
@Southclaws - I know you had some additional things you wanted to add to make the experience even better from Nu, and I'm definitely :+1: for that. I just wanted to see if I could get your baseline working, and then we could grow from there.

**Comment by waldyrious** [comment]
I'm having trouble figuring out how to enable the starship. The [documentation](https://book.nushell.sh/en/configuration#prompt-configuration) only explains how to configure the starship prompt once it's enabled, not how to enable it. I'm using 0.6.0 installed via Homebrew.

**Comment by fdcds** [comment]
The Fedora build appears to have the same issue.

**Comment by Southclaws** [comment]
It's behind a feature-flag `starship-prompt`, not sure if any builds ship with it enabled but if you build from source and enable that flag it should be present in the prompt.

**Comment by waldyrious** [comment]
> if you build from source and enable that flag 

Would you be so kind as to show how that would look like, i.e. what commands or CLI options I would have to use to do so? As someone who is aware of Rust, but never worked directly with it, I'd greatly appreciate the extra guidance. 😄

**Comment by jonathandturner** [comment]
@waldyrious - I'll update the blog post with installation steps

**Comment by devurandom** [comment]
The Fedora package is built with `cargo build --release --all-features`: https://copr-dist-git.fedorainfracloud.org/cgit/atim/nushell/nushell.git/tree/nushell.spec?id=65be21c7d49cd67d9495d177125c76a4fd70e8c5

Shouldn't this include `starship-prompt`? I.e. shouldn't `nu` from the Fedora package always start with a Starship prompt?

**Comment by waldyrious** [comment]
> @waldyrious - I'll update the blog post with installation steps

I appreciate the update to the blog post, but the command seems to be slighly off. I sent a PR to fix it: https://github.com/nushell/blog/pull/16

I've also created a [PR to Homebrew](https://github.com/Homebrew/homebrew-core/pull/48041) to enable the starship prompt there as well.

**Pull request merged**
