### PR TITLE
keep raw for variable inputed argument

### PR DESCRIPTION
**Pull request by WindSoilder**
# Description

It's a further and user friendly improvement after #6420
Reiative issue: #6399

With this pr, users no longer need to quote variable as arguments which passed to external string.

Before:
```
let dump_command = "PGPASSWORD='db_secret' pg_dump -Fc -h 'db.host' -p '$db.port' -U postgres -d 'db_name' > '/tmp/dump_name'"
^echo $""($dump_command)""
```

After:
```
let dump_command = "PGPASSWORD='db_secret' pg_dump -Fc -h 'db.host' -p '$db.port' -U postgres -d 'db_name' > '/tmp/dump_name'"
# no need any quotes, if we pass variable as echo's argument, the inner quote will keep the same.
^echo $dump_command
```

# Tests

Make sure you've done the following:

- [X] Add tests that cover your changes, either in the command examples, the crate/tests folder, or in the /tests folder.
- [X] Try to think about corner cases and various ways how your changes could break. Cover them with tests.
- [X] If adding tests is not possible, please document in the PR body a minimal example with steps on how to reproduce so one can verify your change works.

Make sure you've run and fixed any issues with these commands:

- [X] `cargo fmt --all -- --check` to check standard code formatting (`cargo fmt --all` applies these changes)
- [X] `cargo clippy --workspace --features=extra -- -D warnings -D clippy::unwrap_used -A clippy::needless_collect` to check that you're using the standard code style
- [X] `cargo test --workspace --features=extra` to check that all the tests pass

### CODE REVIEW

**Comment by fdncred** [comment]
nice - how does this affect the other scenarios that we documented on that hackmd document? i.e. is this going to break some existing functionality?

**Comment by WindSoilder** [comment]
Sorry, I have only one mac, and did some manual tests for MacOS relative commands, all work fine for me.

And I believe it doesn't affect any existing functionality

**Comment by kubouch** [comment]
When I try to run the "before" example on Windows, I get "The system cannot find the path specified." Can you provide a simpler example? It is hard to understand what problem this PR is trying to solve.

**Comment by kubouch** [comment]
I'm having the following output without this PR on Windows:
```
> let cmd = "PGPASSWORD='db_secret' pg_dump -Fc -h 'db.host'"

> ^echo $cmd
"PGPASSWORD='db_secret' pg_dump -Fc -h 'db.host'"

> ^echo $""($cmd)""
"\"PGPASSWORD='db_secret' pg_dump -Fc -h 'db.host'\""

> $cmd
PGPASSWORD='db_secret' pg_dump -Fc -h 'db.host'
```

**Comment by kubouch** [comment]
So, trying out the testbin:

without this PR:
```
i let cmd = "PGPASSWORD='db_secret' pg_dump -Fc -h 'db.host'"

i nu --testbin nonu $cmd
PGPASSWORD=db_secret' pg_dump -Fc -h 'db.host

i nu --testbin nonu $""($cmd)""
PGPASSWORD='db_secret' pg_dump -Fc -h 'db.host'
```

with this PR:
```
> let cmd = "PGPASSWORD='db_secret' pg_dump -Fc -h 'db.host'"

> nu --testbin nonu $cmd
PGPASSWORD='db_secret' pg_dump -Fc -h 'db.host'

i nu --testbin nonu $""($cmd)""
PGPASSWORD='db_secret' pg_dump -Fc -h 'db.host'
```

So yeah, seems like it's fixed even on Windows as well. I'd suggest changing the test to use the testbin and remove the OS guard.

**Comment by WindSoilder** [comment]
@kubouch Thanks for testing these on Windows, and `nu --testbin nonu $cmd` looks really interesting.

I just changed test code

**Comment by fdncred** [comment]
thanks. let's move forward with this.

**Pull request merged**
