### PR TITLE
Added support for multiple attributes to `query web -a`

### PR DESCRIPTION
**Pull request by weirdan**
# Description

Allows specifying multiple attributes to retrieve from the selected nodes. E.g. you may want to select both hrefs and targets from the list of links:

```nushell
.... | query web --query a --attribute [href target]
```
# User-Facing Changes

`query web --attribute` previously accepted a string. Now it accepts either a string or a list of strings.

The shape definition for this flag was relaxed temporarily, until nushell/nushell#13253 is fixed.

### CODE REVIEW

**Comment by weirdan** [comment]
Fair warning: I don't know what I'm doing. Rust is like French to me.

**Comment by fdncred** [comment]
Thanks. This looks cool. Is there a better example we can use that people can test with? I get this.
```nushell
❯ http get https://example.org | query web --query a --attribute [ href target ]
╭─#─┬─────────────────href─────────────────┬target╮
│ 0 │ https://www.iana.org/domains/example │      │
╰───┴──────────────────────────────────────┴──────╯
```
which either means there's a bug in the code or there's no target.

**Comment by fdncred** [comment]
I also wonder if we should not add empty rows? What do you think?
```nushell
❯ http get https://phoronix.com | query web --query div --attribute [ align id ]
╭──#──┬─align──┬─────────────────id──────────────────╮
│ 0   │        │                                     │
│ 1   │ center │ phoronix_desktop_leaderboard_header │
│ 2   │        │ headerwrap                          │
│ 3   │        │                                     │
│ 4   │        │ headerright                         │
│ 5   │        │ social                              │
│ 6   │        │ litemenu                            │
│ 7   │        │ menuwrap                            │
│ 8   │        │                                     │
│ 9   │        │ categories-list                     │
│ 10  │        │ categories-content                  │
│ 11  │        │ search                              │
│ 12  │        │                                     │
│ 13  │        │ content-bg                          │
│ 14  │        │ content                             │
│ 15  │        │ main-wrap                           │
│ 16  │        │ main                                │
│ 17  │        │                                     │
│ 18  │ center │ phoronix_desktop_leaderboard_atf    │
│ 19  │        │                                     │
│ 20  │        │                                     │
│ 21  │        │                                     │
│ 22  │        │                                     │
│ 23  │ center │ phoronix_leaderboard_incontent_1    │
│ 24  │        │                                     │
│ 25  │        │                                     │
│ 26  │        │                                     │
...
```

**Comment by weirdan** [comment]
For empty rows, it didn't change compared to what the command did with a single attribute:

This is nushell 0.95.0
```nushell
: http get https://www.rust-lang.org/
-> | query web --query 'meta[property^="og:"]' --attribute content
╭───┬──────────────────────────────────────────────────────────────────────────╮
│ 0 │                                                                          │
│ 1 │ A language empowering everyone to build reliable and efficient software. │
│ 2 │ https://www.rust-lang.org/static/images/rust-social-wide.jpg             │
│ 3 │ website                                                                  │
│ 4 │ en_US                                                                    │
╰───┴──────────────────────────────────────────────────────────────────────────╯
: http get https://www.rust-lang.org/
-> | query web --query 'a' --attribute some_unknown_attribute
╭────┬──╮
│  0 │  │
│  1 │  │
│  2 │  │
│  3 │  │
│  4 │  │
│  5 │  │
│  6 │  │
....
```
A nice example could be the one we discussed over discord:
```nushell
http get https://www.rust-lang.org/
-> | query web --query 'meta[property^="og:"]' --attribute [property content]
╭───┬────────────────┬──────────────────────────────────────────────────────────────────────────╮
│ # │    property    │                                 content                                  │
├───┼────────────────┼──────────────────────────────────────────────────────────────────────────┤
│ 0 │ og:title       │                                                                          │
│ 1 │ og:description │ A language empowering everyone to build reliable and efficient software. │
│ 2 │ og:image       │ https://www.rust-lang.org/static/images/rust-social-wide.jpg             │
│ 3 │ og:type        │ website                                                                  │
│ 4 │ og:locale      │ en_US                                                                    │
╰───┴────────────────┴──────────────────────────────────────────────────────────────────────────╯
```

**Comment by fdncred** [comment]
I'm good with the rust-lang example. I think it looks better.

Regarding empties, even though it hasn't changed, I still wonder if it's the right thing to do. Maybe it's something for another PR?

**Comment by weirdan** [comment]
I think ideally we'd want to represent absent attributes as `null` and empty attributes as empty strings. This is something for a separate PR. However keeping the number of rows equal to the number of selected nodes can be useful, even if none of them has the requested attribute(s).

I'll update the example.

**Comment by weirdan** [comment]
Updated.

**Comment by cablehead** [comment]
Thanks for this!

**Comment by fdncred** [comment]
Thanks for this.

**Pull request merged**
