### PR TITLE
Use Hash Set to compute columns

### PR DESCRIPTION
**Pull request by gaetschwartz**
# Description

Previously, the columns implementation would use a simple nested for loop to compute the columns of a list of records, which would lead to O(N^2) performance. This can become problematic for big lists.

This changes that behavior by using a Hash Set (actually used an IndexSet by the `indexmap` crate, which allows us to keep the original ordering).

# User-Facing Changes
None AFAIK.

# Benchmarks
As we can see in the following benchmarks it can get up to 50 times faster when a large amount of columns are used.
Screenshot 2023-10-16 at 14 47 57

### CODE REVIEW

**Review by sholderbach — APPROVED** [review]
Good call! Thanks for the thorough benchmark. Do you have numbers for different row counts? Really surprised that there is even a benefit for a single column.

Let's wait for after the release but sounds convincing to land.

**Comment by gaetschwartz** [comment]
I would guess there is an overhead when building the set for a small amount of items ?

**Comment by sholderbach** [comment]
Yeah my intuition was that for really small n of columns a linear search over a `Vec` would be faster to go through a hash function and "random" lookup. But that could potentially get less notable for larger number of rows?

**Comment by sholderbach** [comment]
With [commit-bencher.nu](https://gist.github.com/sholderbach/280a04e80e57948a6d94670dacbd2e6e)

`nu commit-bencher.nu --depth 3 columns-bench.nu`

```nu
def createdata [rows, cols] {
  let row = 1..$cols | into record
  1..$rows | each {$row}
}

def inner_bench [data] {
# print $data
1..10 | each { timeit { $data | columns } } | math avg
}

let rows = [1 10 100 1000]
let cols = [1 10 100 1000]

let matrix = $rows | each { |row| $cols | each { |col| {rows: $row, cols: $col}} } | flatten
let matrix = $matrix | insert data { createdata $in.rows $in.cols }

$matrix | insert timing { inner_bench $in.data } | reject data
```

```
=== 76ee00e01 ===
╭────┬──────┬──────┬────────────────────────╮
│  # │ rows │ cols │         timing         │
├────┼──────┼──────┼────────────────────────┤
│  0 │    1 │    1 │              1µs 798ns │
│  1 │    1 │   10 │              1µs 320ns │
│  2 │    1 │  100 │             17µs 352ns │
│  3 │    1 │ 1000 │        1ms 130µs 575ns │
│  4 │   10 │    1 │              1µs 175ns │
│  5 │   10 │   10 │               5µs 36ns │
│  6 │   10 │  100 │            140µs 668ns │
│  7 │   10 │ 1000 │        11ms 61µs 601ns │
│  8 │  100 │    1 │              5µs 753ns │
│  9 │  100 │   10 │             44µs 893ns │
│ 10 │  100 │  100 │        1ms 371µs 452ns │
│ 11 │  100 │ 1000 │      110ms 876µs 450ns │
│ 12 │ 1000 │    1 │             53µs 297ns │
│ 13 │ 1000 │   10 │            427µs 669ns │
│ 14 │ 1000 │  100 │       14ms 239µs 330ns │
│ 15 │ 1000 │ 1000 │ 1sec 104ms 242µs 561ns │
╰────┴──────┴──────┴────────────────────────╯
=== 89ccdc2b0 ===
╭────┬──────┬──────┬────────────────────────╮
│  # │ rows │ cols │         timing         │
├────┼──────┼──────┼────────────────────────┤
│  0 │    1 │    1 │              1µs 697ns │
│  1 │    1 │   10 │              1µs 477ns │
│  2 │    1 │  100 │             17µs 444ns │
│  3 │    1 │ 1000 │         1ms 131µs 33ns │
│  4 │   10 │    1 │              1µs 179ns │
│  5 │   10 │   10 │              4µs 956ns │
│  6 │   10 │  100 │            139µs 719ns │
│  7 │   10 │ 1000 │        11ms 43µs 275ns │
│  8 │  100 │    1 │              5µs 835ns │
│  9 │  100 │   10 │              42µs 23ns │
│ 10 │  100 │  100 │        1ms 373µs 876ns │
│ 11 │  100 │ 1000 │      110ms 911µs 243ns │
│ 12 │ 1000 │    1 │             53µs 972ns │
│ 13 │ 1000 │   10 │            418µs 573ns │
│ 14 │ 1000 │  100 │       14ms 238µs 443ns │
│ 15 │ 1000 │ 1000 │ 1sec 108ms 691µs 713ns │
╰────┴──────┴──────┴────────────────────────╯
=== d59bda3dd ===
╭────┬──────┬──────┬──────────────────╮
│  # │ rows │ cols │      timing      │
├────┼──────┼──────┼──────────────────┤
│  0 │    1 │    1 │        1µs 378ns │
│  1 │    1 │   10 │        1µs 778ns │
│  2 │    1 │  100 │       11µs 106ns │
│  3 │    1 │ 1000 │      101µs 624ns │
│  4 │   10 │    1 │        1µs 234ns │
│  5 │   10 │   10 │        5µs 262ns │
│  6 │   10 │  100 │       46µs 219ns │
│  7 │   10 │ 1000 │      440µs 447ns │
│  8 │  100 │    1 │        6µs 901ns │
│  9 │  100 │   10 │       40µs 696ns │
│ 10 │  100 │  100 │      390µs 691ns │
│ 11 │  100 │ 1000 │  4ms 282µs 123ns │
│ 12 │ 1000 │    1 │       66µs 434ns │
│ 13 │ 1000 │   10 │       432µs 32ns │
│ 14 │ 1000 │  100 │  4ms 300µs 390ns │
│ 15 │ 1000 │ 1000 │ 45ms 124µs 899ns │
╰────┴──────┴──────┴──────────────────╯
=== adde32791 ===
╭────┬──────┬──────┬──────────────────╮
│  # │ rows │ cols │      timing      │
├────┼──────┼──────┼──────────────────┤
│  0 │    1 │    1 │         2µs 59ns │
│  1 │    1 │   10 │        1µs 523ns │
│  2 │    1 │  100 │        8µs 728ns │
│  3 │    1 │ 1000 │       77µs 159ns │
│  4 │   10 │    1 │        1µs 299ns │
│  5 │   10 │   10 │        5µs 400ns │
│  6 │   10 │  100 │        45µs 92ns │
│  7 │   10 │ 1000 │      449µs 449ns │
│  8 │  100 │    1 │        7µs 846ns │
│  9 │  100 │   10 │       51µs 749ns │
│ 10 │  100 │  100 │      419µs 707ns │
│ 11 │  100 │ 1000 │  4ms 385µs 576ns │
│ 12 │ 1000 │    1 │       77µs 904ns │
│ 13 │ 1000 │   10 │      464µs 104ns │
│ 14 │ 1000 │  100 │  4ms 424µs 468ns │
│ 15 │ 1000 │ 1000 │ 46ms 721µs 331ns │
╰────┴──────┴──────┴──────────────────╯
```

**Comment by gaetschwartz** [comment]
Thank you for the benchmark, so it seems to introduce a clear speedup when more columns and an (imo) acceptable overhead for lower amount of columns.

**Comment by sholderbach** [comment]
Looking at the numbers I think I have to retract my full endorsement. We have a lot of data that has few columns in the single or double-digit column count with a lot of rows. Here the change introduces a measurable negative impact. Here we probably need some additional "real-world" benchmarks to argue what is acceptable for the users.

Yes we do the users of the large records a disfavor at the moment. This is generally problematic if you reasonably assume that they have `O(1)` insert times of a hashmap or want to use them for caching etc.

**Comment by gaetschwartz** [comment]
I agree, I will investigate and see if I can improve perf for small amounts of columns.

**Comment by gaetschwartz** [comment]
The thing is,  as you said, we don't really have a proper way of investigating what the real impact. Maybe we should consider building some benchmarking infrastructure ?

**Comment by amtoine** [comment]
there has been an unfortunate merge here, right? :open_mouth:

**Comment by fdncred** [comment]
This doesn't seem to be going anywhere recently. Although maybe a good idea. It would be nice to discuss more in #design-discussion. Closing this due to age and inactivity.

**Pull request closed without merging**
