### PR TITLE
Make insert take in a block

### PR DESCRIPTION
**Pull request by coolshaurya**

### CODE REVIEW

**Comment by jonathandturner** [comment]
If we update `insert`, I wonder if we should also update `update`.

The more I think about this, the more I like the idea that these commands take a block, since it lets  you have more control over how to update/insert into that row.

cc @andrasio - who has also been thinking a lot about this.

**Comment by andrasio** [comment]
@jonathandturner We are updating `insert` to allow it as block form too. This came up in the `#general` discord chat. We're good.

**Comment by andrasio** [comment]
@coolshaurya Could you add some tests?

**Comment by jonathandturner** [comment]
Just chatted with @andrasio, and he says this is good to go. Merging.

Thanks @coolshaurya!

**Pull request merged**
