### PR TITLE
Deprecate `hash base64`, extend `decode` and add `encode` commands

### LINKED ISSUE #5861: Deprecate `hash base64` in favor of a more accurate command name
### Related problem

Nushell is generally good when it comes to naming, however, `hash base64` is not optimal in that aspect.

Indeed, base64 is a lossless binary-to-text encoding strictly representing a binary payload, not a hash digest, it is improper for any (cryptographic) hash application such as signatures and authentication codes.
Furthermore, while hash functions are one-way, an efficient reverse operation is available when it comes to base64 (and other similar encodings such as hexadecimal).
While technically not an issue (code can be, and actually is fully separated from the other hash functions as if it was an unrelated command), putting this command under the `hash` family harms discoverability (I believe most people don’t expect to find base64 there) and might lead some users to misunderstandings.

I believe this issue can inform naming for a future hexadecimal conversion command as well.

### Describe the solution you'd like

The encoding part could be moved to `into base64` and the decoding part to `from base64`. Any better suggestion is welcomed!

#### New `decode` and `encode` families

I actually like this alternative, but the number of command families is increased.

We could have commands such as:
- `encode base64`
- `decode base64`
- `encode hex`
- `decode hex`

One other issue is that the `decode` command already exists.

#### `str base64`

I don’t think it’s the best, especially since all `str to-datetime`, `str to-decimal`, `str to-int` got deprecated recently in favor of `into` alternatives.

#### `to base64`

`to` family is used to translate structured data into an equivalent structured format such as json or xml. base64 is not a structured format, so I don’t think it belongs to this family.

### Additional context and details

This is something I already mentioned [back when we were porting the commands to engine-q](https://github.com/nushell/engine-q/issues/242#issuecomment-989339902). The deprecation didn’t happen at that time in an effort to limit the number of breaking changes at a time. I think now is a good time to revisit the idea.

### PR DESCRIPTION
**Pull request by CBenoit**
Closes #5861

I separated changes in two independents commits in case you prefer rebasing.

# Description

This PR:
- deprecates `hash base64` command
- Adds `encode` command family
- Backports `hash base64` features to `encode base64` and `decode base64` sub-commands.
- Refactors code a bit and extends tests for encodings
- `decode base64` returns a binary value `Value::Binary` (that may be decoded into a string using `decode` command)

image

# Tests

Make sure you've done the following:

- [x] Add tests that cover your changes, either in the command examples, the crate/tests folder, or in the /tests folder.
- [x] Try to think about corner cases and various ways how your changes could break. Cover them with tests.
- [x] If adding tests is not possible, please document in the PR body a minimal example with steps on how to reproduce so one can verify your change works.

Make sure you've run and fixed any issues with these commands:

- [x] `cargo fmt --all -- --check` to check standard code formatting (`cargo fmt --all` applies these changes)
- [x] `cargo clippy --workspace --features=extra -- -D warnings -D clippy::unwrap_used -A clippy::needless_collect` to check that you're using the standard code style
- [x] `cargo test --workspace --features=extra` to check that all the tests pass

### CODE REVIEW

**Comment by fdncred** [comment]
This looks great. Thanks!  The one part I'm struggling with is that decode returns a binary. I'm wondering if we can default to returning a string but if we are decoding something binary we switch to output binary, either that or we do `| into binary` somewhere in the pipeline? My fear is that switch to bin output will be a breaking change for some.

Just playing around with the macOS base64 command you can do `"foo" | base64` and `"Zm9v" | base64 -d` and it outputs a string.

**Comment by kubouch** [comment]
I like the changes, though it seems a bit inconsistent that the other `md5` and `sha256` are still under the `hash` command. Maybe we can move them to `encode` as well?

**Comment by zer0x64** [comment]
As for binary vs string:

Base64 (and a lot of other encoding) are meant to encode binary data as a string, and that's what you'll do in most use case. The input of the encoding function should be binary, while the output should be string, or it'll severely limit the usefulness of the function. As for the decoding, it's the opposite.

I think the encoding input can be implicitly converted from a string to binary for useability. As for the output of the decoding function, that's a design decision if it should output a string when possible(which won't be every case) or if the user should do an explicit conversion. I think that, in that case, implicit conversion could randomly break scripts when the data is accidentally ascii and isn't a great idea. But, the `unencoded` data should support binary or else the command would be close to useless

**Comment by CBenoit** [comment]
> i'd vote for string but interested in other opinions

Yes, let’s wait a bit to gather some more. I will ask on discord :slightly_smiling_face: 

@WindSoilder do you have any preference here?

**Comment by CBenoit** [comment]
Thank you!

I also posted in the Discord #feedback channel for more opinions.
Just so that it’s visible in the PR as well: I want to point out that nushell show binary values using a beautiful hexadecimal viewer along the ASCII representation when appropriate and thus is already good at showing ASCII strings out of the box (see screenshot).

image

So it’s not a bad default behavior when user just want to decode a string and see the result immediately (somewhat limited because it only shows ASCII, not UTF-8 characters).

**Comment by CBenoit** [comment]
Following discussion on discord, I updated the decode command to returns a string by default, but binary can be requested using `--binary(-b)`.
I'll open follow up PRs so that `--binary(-b)` can be omitted when the next command requires binary explicitly using overloading.

**Comment by kubouch** [comment]
OK, thank you! It seems good to me so let's land it.

For the overloading, note that we moved the type information from Command to Signature in the last PR so make sure you're on the latest main.

**Comment by fdncred** [comment]
this doesn't compile on the latest main.

**Comment by CBenoit** [comment]
I see you fixed it, thank you!

**Pull request merged**
