### PR TITLE
Add path separator to `char`; Update char to engine-p; List all names of all possible chars

### PR DESCRIPTION
**Pull request by kubouch**
`char sep` or `char separator` outputs either `/` or `\`, based on the host OS.

### CODE REVIEW

**Comment by kubouch** [comment]
Oh, wait a sec, I'll convert it to engine-p while I'm at it.

**Comment by fdncred** [comment]
Good catch. I'd eventually like a `char --list` so show which characters `char` can use.

**Comment by kubouch** [comment]
Yeah, I was wondering the same thing looking at the char command. We have the `extra_usage()` but I think it's a bit too verbose to put the full list in the help message.

I can include the list as well.

**Comment by fdncred** [comment]
That would be cool if you could include it. I was thinking about making the list of chars an indexmap at one point so we could print them out but I'm up for however is easiest to print the list. I also agree, i don't think extra_usage() is the right place.

**Comment by kubouch** [comment]
I actually started doing that with HashMap but IndexMap is better since it preserves the order.

**Comment by fdncred** [comment]
ya, i was just thinking of indexmap because it's easier to turn into a nushell table. i think ... :) do it however you think is best.

**Comment by kubouch** [comment]
@fdncred Currently it looks like this:
```shell
> char --list
  #                name                character    unicode
───────────────────────────────────────────────────────────────
   0   newline                                     a
   1   enter                                       a
   2   nl                                          a
   3   tab                             	           9
   4   sp                                          20
   5   space                                       20
   6   pipe                            |           7c
   7   left_brace                      {           7b
   8   lbrace                          {           7b
   9   right_brace                     }           7d
  10   rbrace                          }           7d
  11   left_paren                      (           28
  12   lparen                          (           28
  13   right_paren                     )           29
  14   rparen                          )           29
  15   left_bracket                    [           5b
  16   lbracket                        [           5b
  17   right_bracket                   ]           5d
  18   rbracket                        ]           5d
  19   sep                             /           2f
  20   separator                       /           2f
  21   branch                                     e0a0
  22   segment                                    e0b0
  23   identical_to                    ≡           2261
  24   hamburger                       ≡           2261
  25   not_identical_to                ≢           2262
  26   branch_untracked                ≢           2262
  27   strictly_equivalent_to          ≣           2263
  28   branch_identical                ≣           2263
  29   upwards_arrow                   ↑           2191
  30   branch_ahead                    ↑           2191
  31   downwards_arrow                 ↓           2193
  32   branch_behind                   ↓           2193
  33   up_down_arrow                   ↕           2195
  34   branch_ahead_behind             ↕           2195
  35   black_right_pointing_triangle   ▶           25b6
  36   prompt                          ▶           25b6
  37   vector_or_cross_product         ⨯           2a2f
  38   failed                          ⨯           2a2f
  39   high_voltage_sign               ⚡          26a1
  40   elevated                        ⚡          26a1
  41   tilde                           ~           7e
  42   twiddle                         ~           7e
  43   squiggly                        ~           7e
  44   home                            ~           7e
  45   hash                            #           23
  46   hashtag                         #           23
  47   pound_sign                      #           23
  48   sharp                           #           23
  49   root                            #           23
  50   sun                             ☀️          2600 fe0f
  51   sunny                           ☀️          2600 fe0f
  52   sunrise                         ☀️          2600 fe0f
  53   moon                            🌛          1f31b
  54   cloudy                          ☁️          2601 fe0f
  55   cloud                           ☁️          2601 fe0f
  56   clouds                          ☁️          2601 fe0f
  57   rainy                           🌦️          1f326 fe0f
  58   rain                            🌦️          1f326 fe0f
  59   foggy                           🌫️          1f32b fe0f
  60   fog                             🌫️          1f32b fe0f
  61   mist                            ░           2591
  62   haze                            ░           2591
  63   snowy                           ❄️          2744 fe0f
  64   snow                            ❄️          2744 fe0f
  65   thunderstorm                    🌩️          1f329 fe0f
  66   thunder                         🌩️          1f329 fe0f
  67   bel                                        7
  68   backspace                                 8
```
The indentation is somehow messed up due to some of the whitespace characters and some of the longer unicode symbols.

**Comment by fdncred** [comment]
looks very cool. good job!

**Comment by fdncred** [comment]
Thanks!

**Pull request merged**
