### PR TITLE
improve error message for CoerceError

### PR DESCRIPTION
**Pull request by peterthejohnston**

### CODE REVIEW

**Comment by jonathandturner** [comment]
@peterthejohnston - if you're interested in continuing on this PR, I think it's a good direction that will help improve the errors

**Comment by peterthejohnston** [comment]
ok! i'm happy to get this in a good state for review, it might be a couple days until i have the time.

**Comment by peterthejohnston** [comment]
sorry for the lack of progress on this. i haven't had the time to work on it. anyone is welcome to take over this PR if they're interested

**Comment by jonathandturner** [comment]
Going ahead and closing as this is now out of date with the current codebase.

**Pull request closed without merging**
