### PR TITLE
Fix handling of spaces in executable names

### PR DESCRIPTION
**Pull request by qfel**
# Description
The original code assumed a full single-string command line could be split by space to get the original argv.

# User-Facing Changes
Fixes an issue where `ps` would display incomplete process name if it contained space(s).

# Tests + Formatting
Fixes existing code, no new coverage. Existing code doesn't seem to be covered, we could be it would be somewhat involved and the fix was simple, so didn't bother..

### CODE REVIEW

**Comment by sholderbach** [comment]
Are there asssociated issue numbers or a before and after for `ps`? Not sure if we use the `nu-system` logic for other things as well?
That command escaping seems to be something somewhat tricky depending on the use.

**Comment by fdncred** [comment]
It would be nice if this were a little bit consistent across platforms. On Windows "name" is just the name, not the entire path. That is reserved for command. I'm not saying they need to have identical columns, but it seems like "name" should just be the name of the executable and command should be the full path with arguments.
image

On Linux, it looks like command and name columns are the same
image

**Comment by qfel** [comment]
> Are there associated issue numbers or a before and after for ps?

Not that I know of.  Can add something once we agree on comm below.

> That command escaping seems to be something somewhat tricky depending on the use.

I don't really want to tackle it here, just wanted to leave a comment for future maintainers to not parse it in any way.

> It would be nice if this were a little bit consistent across platforms.

You mean, swap the branches so the linux version prefers comm?

**Comment by fdncred** [comment]
> You mean, swap the branches so the linux version prefers comm?

Just my opinion, but I think all platforms should work like Windows here where "name" is just the name and not the full path. If you want the full path, you can combine `cwd` and `name`.

**Comment by qfel** [comment]
> If you want the full path

IIUC on linux the name may not be the executable name, so I wouldn't say you can always combine `cwd` and `name`. But then, `command` seems to have it.

Anyway, I was simply preserving existing behavior. If you want the change in the same PR, I can update it (though then it's a bug fix + behavior change).

**Comment by fdncred** [comment]
It's fine for now but it would be nice to unify the output a bit. Thanks.

**Pull request merged**
