### PR TITLE
parser/refactor def

### PR DESCRIPTION
**Pull request by LhKipp**
This PR splits the huge param_flag_list.rs module into pieces to make it easier understandable.
It simply:
- Move tests into own file
- Move data structs to own file
- Move functions parsing 1 Token (primitives) into own file
- Rename param_flag_list to signature
- Add tests
- Fix clippy lint

### CODE REVIEW

**Comment by jonathandturner** [comment]
I want to look at this, but I want to see if we can land #2956 first. It seems to be at risk of bitrotting.

**Comment by jonathandturner** [comment]
@LhKipp - now that #2956 is in, can you fix the conflicts (and make any other changes you need to)?  I can look at it when you're ready

**Comment by wycats** [comment]
@jonathandturner thanks for helping land #2956. Now that it's done, I opened up an issue for follow-on work (#3010).

**Comment by LhKipp** [comment]
@jonathandturner It's ready for review and hopefully merging :)

**Comment by jonathandturner** [comment]
Looks good!

**Pull request merged**
