### PR TITLE
Run a round of clippy --fix to fix a ton of lints

### PR DESCRIPTION
**Pull request by SUPERCILEX**
It's pretty annoying to have erroneous lints that aren't related to your code changes. This PR gets rid of good chunk of them.

### CODE REVIEW

**Comment by fdncred** [comment]
i ran clippy a few hours ago and didn't get these lints. are you overriding the version of rust used to compile nushell?  just curious. i'm not sure these changes hurt anything. our currently rustc version is pinned to 1.64.

**Comment by SUPERCILEX** [comment]
Oh interesting, yeah I'm on nightly. I guess the clippy team has just been on a roll. :) Glad to know stable is clean.

**Comment by fdncred** [comment]
thanks. ci is green, let's roll! :)

**Comment by SUPERCILEX** [comment]
:tada:

**Pull request merged**
