### PR TITLE
Add cursor shape configuration for each edit mode

### PR DESCRIPTION
**Pull request by fdncred**
# Description

This PR allows the configuration of cursor shapes in nushell for each edit mode. This is the change that is in the default_config.nu file.
```
  cursor_shape: {
    emacs: line # block, underscore, line (line is the default)
    vi_insert: block # block, underscore, line (block is the default)
    vi_normal: underscore # block, underscore, line  (underscore is the default)
  }
```

# User-Facing Changes

See above. If you'd prefer a different default, please speak up and let us know.

# Tests + Formatting

Don't forget to add tests that cover your changes.

Make sure you've run and fixed any issues with these commands:

- `cargo fmt --all -- --check` to check standard code formatting (`cargo fmt --all` applies these changes)
- `cargo clippy --workspace -- -D warnings -D clippy::unwrap_used -A clippy::needless_collect` to check that you're using the standard code style
- `cargo test --workspace` to check that all tests pass

# After Submitting

If your PR had any user-facing changes, update [the documentation](https://github.com/nushell/nushell.github.io) after the PR is merged, if necessary. This will help us keep the docs up to date.

### CODE REVIEW

**Comment by stormasm** [comment]
@fdncred it seems to me that having reedline and crossterm be a dependency inside nu-protocol is not the correct approach...

Don't we want nu-protocol to be pure and simple as possible ?

Why do we need reedline and crossterm as a dependency ?

**Comment by fdncred** [comment]
Good point @stormasm. Those were left overs from prior work trying to get this stupid thing to work. I just removed them and it all seems to still work. Thanks for noticing.

**Comment by rgwood** [comment]
Do we need this setting to vary by edit mode? Would be nice if we could get by with 1 cursor setting instead of 3.

I never touch the edit modes so I might be missing something important.

**Comment by fdncred** [comment]
> Do we need this setting to vary by edit mode?

I don't thnk so. The whole point to the reedline PR was to allow vi_insert cursor to be different from vi_normal cursor. I just wanted a friggin line/bar/beam everywehre myself.

**Comment by fdncred** [comment]
Let's move forward with this. We need to redesign this config system because, IMO, it was a huge pain adding these new configuration points.

**Comment by sholderbach** [comment]
Thanks for dealing with this configuration complexity!

**Comment by fdncred** [comment]
We might want to tweak this to make these cursor settings optional by adding another option to `line`, `block`, `underscore`, and that is `terminal` so if `terminal` were set, it would set these options to None and therefore use the terminal's settings for the cursor shape. I'm not sure that will programmatically work but we may need to think about it in the future.

**Comment by dead10ck** [comment]
@fdncred thanks so much for this! Your work, as well as that of the reviewers, is appreciated :)

**Pull request merged**
