### PR TITLE
echo $scope.aliases | pivot to see all of your aliases

### PR DESCRIPTION
**Pull request by stormasm**
https://github.com/nushell/nushell/issues/2858#issuecomment-754641823

From a discussion with @fdncred on knocking off one of the items in the 

[The Big Todo List](https://github.com/nushell/nushell/issues/2858)

### CODE REVIEW

**Comment by fdncred** [comment]
@stormasm I'm kind of wondering if this should be `$scope.aliases` so we can later have `$scope.custom_commands` and `$scope.whatever else lives in the scope`. Thoughts?

**Comment by stormasm** [comment]
@fdncred yes fully agreed.  that is the way I have it set up...  I will add other things later once this PR lands and we agree that $scope.XXX is the way to go... $scope.aliases is just the first one...

**Comment by fdncred** [comment]
Ok. Good. I missed that in the diff. Thanks.

**Comment by jonathandturner** [comment]
@stormasm - can you add a few tests as well?

**Comment by stormasm** [comment]
@jonathandturner yes ! happy to add the tests... thanks for reviewing

**Comment by stormasm** [comment]
@jonathandturner the tests for this PR are now in there...   all tests are passing on my machine...  looks like clippy is unhappy ---- probably because the new release today of rust ?

**Comment by stormasm** [comment]
@jonathandturner Thanks kindly for fixing all of those clippy issues !!

**Comment by stormasm** [comment]
@jonathandturner I merged in changes from PR https://github.com/nushell/nushell/pull/3217
failures do not appear to be from my changes...
thanks for taking a look...

**Comment by fdncred** [comment]
I restarted the CI and it went green. Sometimes the CI is just flaky and doesn't work.

**Comment by stormasm** [comment]
@fdncred thanks for doing that... have a good weekend.

**Comment by jonathandturner** [comment]
Looks good!

**Pull request merged**
