### PR TITLE
Changes HashMap to use aHash instead, giving a performance boost.

### PR DESCRIPTION
**Pull request by FilipAndersson245**
# Description

see https://github.com/nushell/nushell/issues/9390
using `ahash` instead of the default hasher. this will not affect compile time as we where already building `ahash`.

# User-Facing Changes

# Tests + Formatting

# After Submitting

### CODE REVIEW

**Comment by fdncred** [comment]
I'm good with going this direction but I wonder how you arrived at aHash? I mean, how do we know it's the fastest? Could there perhaps be faster ones?

**Comment by FilipAndersson245** [comment]
> I'm good with going this direction but I wonder how you arrived at aHash? I mean, how do we know it's the fastest? Could there perhaps be faster ones?

I had used it previously so i wanted to test if it improved performance, as far as iknow ahash does not lock itself to a specific algorithm so it always uses the fastest one available, it is possible faster ones, but ahash had drop in replacments for the standard library making it easy drop and replace.

**Comment by fdncred** [comment]
it tells you how it's a typo and how to rename it

**Comment by stormasm** [comment]
> Don't get why the typos gets triggered by this?

Warning: "reuseable" should be "reusable".

Just send in another commit with this change and it should pass...

**Comment by stormasm** [comment]
@FilipAndersson245 

Thank you kindly for investigating this !  Great work 👍 

We are going to need to analyze further...

For starters I downloaded your branch and built nushell...

And I am seeing no difference in startup times between the main branch and your branch...

_Which tells me possibly that the benchmarking code is not giving us a true picture of what is going on..._

I would be curious to know what you are seeing on your computer as far as startup times
between your branch and the main branch...

Thanks --- lets investigate further and see what we come up with...

**Comment by fdncred** [comment]
Just to jump in. Here's me running cargo bench on my m1mac

| function | main | ahash
| - | - | - |
| parse_default_env_file | 383.47 µs | 360.60 µs |
| parse_default_config_file | 1.4435 ms | 1.3889 ms |
| eval default_env.nu  | 747.83 µs | 707.41 µs |
| eval default_config.nu  | 1.9011 ms | 1.8596 ms |
| eval default_env.nu 2 | 750.61 µs | 714.26 µs |
| eval default_config 2 | 1.8857 ms | 1.8774 ms |

**Comment by FilipAndersson245** [comment]
| function| main | ahash |
|--------|--------|--------|
|parse_default_env_file          |315.38 µs |300.96 µs|
|parse_default_config_file       |1.3181 ms |1.1080 ms|
|eval default_env.nu             |664.07 µs |681.50 µs|
|eval default_config.nu          |1.6868 ms |1.6020 ms|
|eval default_env.nu 2          |705.73 µs |648.34 µs|
|eval default_config.nu 2       |1.6323 ms |1.7428 ms|

**Comment by amtoine** [comment]
## :postal_horn: :postal_horn: little annoucement
the *Typos* CI job is failing in this PR.
this has been fixed in https://github.com/nushell/nushell/pull/9393 :+1: 

in this PR, you can either
- merge the new `main` branch into the PR branch to explicitely have a :heavy_check_mark: here
- wait for the PR to land and the CI should be :heavy_check_mark: once landed on the `main` branch :relieved:

**Comment by fdncred** [comment]
I'm about ready to land this to see how it goes, but I'd like to have it tested on Windows first. Windows is weird and may behave badly. If someone gets a chance to try it, please post your timings.

**Comment by stormasm** [comment]
@fdncred I am not sure why we are landing this...
I am still seeing a slowdown with ahash instead of a speed up...

I wish we could get a few other folks to test prior to landing this...
Running the comparison tests above that you and @FilipAndersson245 ran...

**Comment by stormasm** [comment]
> I'm about ready to land this to see how it goes, but I'd like to have it tested on Windows first. Windows is weird and may behave badly. If someone gets a chance to try it, please post your timings.

@fdncred I am not sure why we are landing this now...

@FilipAndersson245 in two of his ahash tests is causing a slowdown...

And my benchmark tests show a slowdown...

I would feel more comfortable landing this if we had a few other folks run the same tests
we did just for comparison...

**Comment by fdncred** [comment]
@stormasm it would be good if you could post all 6 of your timings here so we can gather results consistently.

I have 6 of 6 improvements on my mac m1
@FilipAndersson245  has 4 of 6 improvements on linux i assume
@storm has 2 of 4 improvements on mac x86 i assume (i'll update this if you show your 6)

**Comment by stormasm** [comment]
> @stormasm it would be good if you could post all 6 of your timings here so we can gather results consistently.
> 
> I have 6 of 6 improvements on my mac m1 @FilipAndersson245 has 4 of 6 improvements on linux i assume @storm has 2 of 4 improvements on mac x86 i assume (i'll update this if you show your 6)

I will run them now and post...
Should take a few minutes...
stay tuned.

**Comment by stormasm** [comment]
Apple M1 Pro with 16G of memory

| function | main | ahash
| - | - | - |
| parse_default_env_file | 411.49 µs | 401.16 µs |
| parse_default_config_file | 1.4912 ms | 1.4415 ms |
| eval default_env.nu  | 823.05 µs | 770.71 µs |
| eval default_config.nu  | 2.0569 ms | 1.9858 ms |
| eval default_env.nu #2 | 812.52 µs | 767.01 µs |
| eval default_config.nu #2 | 2.0333 ms | 1.9896 ms |

Lets land it ! 😄

**Comment by fdncred** [comment]
i'm building in windows now to see what it does.

**Comment by fdncred** [comment]
Windows

| function | main | ahash
| - | - | - |
| parse_default_env_file | 958.95 µs | 855.95 µs |
| parse_default_config_file | 3.2623 ms | 3.2155 ms |
| eval default_env.nu  | 2.4146 ms | 2.4098 ms |
| eval default_config.nu  | 5.5520 ms | 5.4936 ms |
| eval default_env.nu 2 | 2.6904 ms | 2.5983 ms |
| eval default_config 2 | 5.0630 ms | 5.4408 ms |

**Comment by amtoine** [comment]
the *revert* button creating a commit right away without confirmation is an interesting feature :sweat_smile: 

nothing changed here, no worries :eyes:

**Pull request merged**
