### PR TITLE
Try adding an interpolation shorthand

### PR DESCRIPTION
**Pull request by jntrnr**
# Description

This adds a string interpolation shorthand that's a bit simpler than full string interpolation.

Currently, this is only enabled for the following SyntaxShapes:
* ExternalArg
* FilePath
* GlobPattern
* Directory

Example of the shorthand:

```
> cd ($env.PWD)/crates
```

In effect, it treats the whole argument as if it were a string interpolation, without requiring adding the explicit `$"` and `"` around it.

# User-Facing Changes

This will change some of the existing syntax. For example, this used to work:

```
cat (["foo"]).0
```

It would now be required to be wrapped in parens, as we would string interpolate the above:

```
cat (["foo"].0)
```

# Tests + Formatting

# After Submitting

### CODE REVIEW

**Comment by WindSoilder** [comment]
Is there any way to opt-out this behavior?  Especially for `ExternalArg`

I'm worry that for `ExternalArg`, users always have a way to opt-out some feature.

**Comment by jntrnr** [comment]
@WindSoilder - for external args, put quotes around it

**Comment by fdncred** [comment]
I love this change. I think the positives will outweigh the negatives. However, I am wondering how big of a hangup the cell-path issue will be. I'm trying to think of real-world scenarios but not coming up with any yet.

As seen in the test, this
`nu --testbin cococo (ls | sort-by name | get name).1`
vs this
`nu --testbin cococo ((ls | sort-by name | get name).1)`

Because of the cell-path change, this should probably be a "breaking-change" too, I think.

**Review by amtoine — CHANGES_REQUESTED** [review]
i like the change :blush: 

could we just add some tests?
e.g. to make sure the following works as you mention it in the PR description :yum: 
```nushell
cd ($env.PWD)/crates
```

**Comment by amtoine** [comment]
closing this for now then, feel free to reopen at anytime by pushing to the PR branch :relieved:

**Pull request closed without merging**
