### PR TITLE
Re-enable some good tests, remove some bad tests

### PR DESCRIPTION
**Pull request by rgwood**
I tackled some of the disabled `FIXME`/`#[ignore]` tests. Most were straightforward to re-enable, and a few of them did not deserve to be re-enabled.

### CODE REVIEW

**Review by sholderbach — APPROVED** [review]
Awesome! Thanks!

**Comment by rgwood** [comment]
Ugh, those plugin failures are getting annoyingly frequent.

**Comment by fdncred** [comment]
I'm confused why this test would give give a `directory not found` only on Windows. The only thing I found weird is that the directory is in `D:` drive. `cd "D:\a\nushell\nushell\tests\fixtures\formats"`.

Now that I think of it, I'm wondering if nushell doesn't allow changing drives and directories at the same time on Windows maybe?

**Comment by ChrisDenton** [comment]
The OS error is:

```
IO Error: Os { code: 123, kind: InvalidFilename, message: "The
        filename, directory name, or volume label syntax is incorrect." }
```

Hm, this usually means there was a syntax error in the given path (e.g. an invalid character is in the path, like `"` or `\t`, etc). It might be useful to dbg what path is actually being passed to the API that's erroring, if possible.

**Comment by fdncred** [comment]
Here's another idea. Since the path `cd "D:\a\nushell\nushell\tests\fixtures\formats"` is in double quotes, i wonder if nushell is interpreting all the `\` as escapes. So, if we changed that on windows to `cd "D:\\a\\nushell\\nushell\\tests\\fixtures\\formats"`, i wonder if that would fix it?

**Comment by rgwood** [comment]
Thanks for looking into this. I might not be able to fix that until I get back in ~10 days, will take a closer look then.

Side note: omg Windows Nu is so slow to compile on my laptop 😭

**Comment by fdncred** [comment]
I just changed the `cd "{}"` to `cd '{}'` to see if it makes any difference and rule out nushell interpreting double quoting back slashes as escapes.

**Comment by ChrisDenton** [comment]
Yep, it looks like you're right:
```
Z:\test\nu〉cd Z:\test\nu
Z:\test\nu〉cd "Z:\test\nu"
Error: nu::shell::directory_not_found (link)

  × Directory not found
   ╭─[entry #11:1:1]
 1 │ cd "Z:\test\nu"
   ·    ──────┬─────
   ·          ╰── directory not found
   ╰────
  help: IO Error: Os { code: 123, kind: InvalidFilename, message: "The filename, directory name, or volume label
        syntax is incorrect." }

Z:\test\nu〉cd "Z:\\test\\nu"
Z:\test\nu〉cd 'Z:\test\nu'
Z:\test\nu〉

```

**Comment by fdncred** [comment]
whoop whoop! it worked! thanks @ChrisDenton for the inspiration. let's land this.

**Pull request merged**
