### PR TITLE
Try to fix #7380

### LINKED ISSUE #7380: `table` sometimes gives `...` columns when it shouldn't
### Describe the bug

I see this from time to time. Just documenting here with the latest run in. I have a full width terminal and halfway through the width of the terminal `tabled` must think that it's near the end because it makes that last N columns `...`.

image

Here's my table configuration
```
    table: {
        mode: rounded # basic, compact, compact_double, light, thin, with_love, rounded, reinforced, heavy, none, other
        index_mode: always #  "always" show indexes, "never" show indexes, "auto" = show indexes when a table has "index" column
        trim: {     # A strategy of managing table view in case of limited space.
            methodology: wrapping # truncating or wrapping
            wrapping_try_keep_words: true
            # A suffix which will be used with 'truncating' methodology
            truncating_suffix: "…" # "⋯" "︙"
        }
    }
```

### How to reproduce

1. With this example, download https://github.com/JosephTLyons/nu_plugin_periodic_table. I updated the cargo.toml to use the 0.72.0 build.
2. cargo install --path .
3. nu
4. register ~/.cargo/bin/nu_plugin_periodic_table (with .exe if on windows)
5. maximize terminal
6. run periodic-table -c

### Expected behavior

No `...`'s unless we're at the end of the terminal

### Screenshots

_No response_

### Configuration

|key|value|
|-|-|
|version|0.72.2|
|branch|main|
|commit_hash|017a13fa3f465a6a62082fd3da1a373b39055cd8|
|build_os|windows-x86_64|
|build_target|x86_64-pc-windows-msvc|
|rust_version|rustc 1.65.0 (897e37553 2022-11-02)|
|rust_channel|1.65.0-x86_64-pc-windows-msvc|
|cargo_version|cargo 1.65.0 (4bc8f24d3 2022-10-20)|
|pkg_version|0.72.2|
|build_time|2022-12-05 14:24:44 -06:00|
|build_rust_channel|release|
|features|database, dataframe, default, trash, which, zip|
|installed_plugins|custom-value generate, custom-value generate2, custom-value update, from parquet, gstat, inc, nu-example-1, nu-example-2, nu-example-3, periodic-table, pnet, query, query json, query web, query xml|

### Additional context

/cc @zhiburt

### PR DESCRIPTION
**Pull request by zhiburt**
fix #7380 

As the PR changes a little bit the behavior 
I'd make a few runs on other data to see if it's good enough.

### CODE REVIEW

**Comment by fdncred** [comment]
Yup, this PR seems to fix this use case. Thanks!
image

**Comment by fdncred** [comment]
@zhiburt if you can get the ci green we can land this.

**Comment by zhiburt** [comment]
So after looking at the CI.
I found out that the original fix was error prone.

Must work now.

But it underwent A SMALL refactoring.
So I am not sure maybe some manual runs would be a  benefit. (I ran it a few time seems OK).

**Comment by fdncred** [comment]
I haven't been able to break it. let's land.

**Comment by fdncred** [comment]
@zhiburt I broke it again on the latest main. the `history` command doesn't appear to be wrapping the table columns appropriately.
image
There should be plenty of room these columns if the command column would wrap better `start_timestamp command cwd duration exit_status`

**Comment by zhiburt** [comment]
> I broke it again on the latest main. the history command doesn't appear to be wrapping the table columns appropriately.

How you can this multi column history?
I mean I have only 1 column.

> There should be plenty of room these columns start_timestamp command cwd duration exit_status if the command column would wrap better.
> Also, setting the table methodology to truncating produces the same result as above.

So as I've mentioned I've changed the algorithm a bit.
So now it prioritizes the left most content.

Meaning there must be only 2 AT MAXIMUM columns being truncated/wrapped, is the last and the prev to last.
But in most cases it's the last column only. (the column before `...` column).

But it though might be a bug not sure.
I've run it seems ok.

**Comment by fdncred** [comment]
> How did you get this multi column history?

You have to have your history set to sqlite.
```
    history: {
        max_size: 100000 # Session has to be reloaded for this to take effect
        sync_on_enter: true # Enable to share the history between multiple sessions, else you have to close the session to persist history to file
        file_format: sqlite # "sqlite" or "plaintext"
    }
```

I'm not sure how you want me to check the length of the command, but here's the last few. I have a max of 975.
image

> Meaning if we can show the full content of a column we do, and then if we have no space left we will not show any more columns to not truncate/wrap the content.

I'm not sure how i feel about that. I mean if there are a lot of columns, it should probably have a max width so 1 column doesn't take the entire width of your screen. Ideally it would work closely like table worked before we migrated to tabled, as far as how column widths were allocated.

**Pull request merged**
