### PR TITLE
fix #7145

### LINKED ISSUE #7145: `table -e` doesn't always list all entries in nested tables, and sometimes collapses them even if there's some room
### Describe the bug

Assuming you have something like this `default_theme` in your config.nu file
image
Assuming you have this hook (I'm assuming the hook isn't to blame, but I'm also not ruling that out)
```
      display_output: {
        if (term size).columns > 100 { table -e } else { table }
      }
```
Now if your terminal is maximized and I type `$nu`, I get this.
image
Notice that there are more items in the default_theme than are rendered in the table.

Now, in Windows Terminal I hit ctrl+- to make my font smaller, to see what happens. Even though I now have more room, I noticed that this entire table is:
1. entirely collapsed
2. has a different row number (this is not a big issue, I just point it out because it surprised me)
image

I do ctrl+- again and the font gets smaller, there's more room, but $default_theme isn't expanded
image

I can also see something similar with `commands` (at normal zoom level)
image

Now zoomed out with ctrl+- twice and type `$nu` again. Now there are tables but there are more columns than are being shown.
image
For comparison, here's just the alias command
image

I believe this is related to #6885

### How to reproduce

See above

### Expected behavior

I definitely understand that parsing and representing all this data in a coherent way is not trivial. However, when I discovered this, my initial thought was that tables should be drawn in such a way that when there is not enough room for columns, the truncation column `...` should be shown.

### Screenshots

_No response_

### Configuration

|key|value|
|-|-|
|version|0.71.1|
|branch|main|
|commit_hash|ef32e1ce1ac68eb99cdbaef49e381d2e9b179f2e|
|build_os|windows-x86_64|
|build_target|x86_64-pc-windows-msvc|
|rust_version|rustc 1.63.0 (4b91a6ea7 2022-08-08)|
|rust_channel|1.63.0-x86_64-pc-windows-msvc|
|cargo_version|cargo 1.63.0 (fd9c4297c 2022-07-01)|
|pkg_version|0.71.1|
|build_time|2022-11-11 15:25:04 -06:00|
|build_rust_channel|release|
|features|database, dataframe, default, trash, which, zip|
|installed_plugins|custom-value generate, custom-value generate2, custom-value update, gstat, inc, nu-example-1, nu-example-2, nu-example-3, query, query json, query web, query xml|

### Additional context

/cc @zhiburt

### PR DESCRIPTION
**Pull request by zhiburt**
fix #7145

### CODE REVIEW

**Comment by fdncred** [comment]
wow, that was quick, and only 1 line! :)

What about this. Why aren't these record fields ($my_theme, $default_theme, $base16_theme) expanding when there seems to be apparent room?
image

**Comment by zhiburt** [comment]
also found this WIP;

**Comment by zhiburt** [comment]
Could you check it?

**Comment by fdncred** [comment]
wow, this looks much much better! I'm on my Mac now. I'll test tomorrow on my Windows machine and see if it looks good there too. If so, I'll land this fix. Thanks for the quick turn-around time @zhiburt!!

**Comment by fdncred** [comment]
I think this looks better now so I'm going to land it. I do have one question though.

This is the end of the $nu.scope.commands section
image
I notice there are signatures and examples that *could* be expanded but we've chosen not to do that and put the `...` at the end. I'm totally good with this behavior. But my question is, what are the expansion rules. I mean, how does it know not to expand signatures and examples here?

**Comment by rgwood** [comment]
I'm playing around with `explore` now and it's really cool, thanks zhiburt!

**Pull request merged**
