### PR TITLE
Filesystem commands print --verbose to stderr

### PR DESCRIPTION
**Pull request by NotLebedev**
# Description

Makes `mkdir`, `cp`, `mv` and `rm` return nothing and print info to stderr:
image
See https://github.com/nushell/nushell/pull/7925#issuecomment-1420861638 and [discord](https://discord.com/channels/601130461678272522/615329862395101194/1072523941865857055).

# User-Facing Changes

`mkdir`, `cp`, `mv` and `rm` will return nothing and print info to stderr with `--verbose` flag.

# Tests + Formatting

Don't forget to add tests that cover your changes.

Make sure you've run and fixed any issues with these commands:

- `cargo fmt --all -- --check` to check standard code formatting (`cargo fmt --all` applies these changes)
- `cargo clippy --workspace -- -D warnings -D clippy::unwrap_used -A clippy::needless_collect` to check that you're using the standard code style
- `cargo test --workspace` to check that all tests pass

# After Submitting

If your PR had any user-facing changes, update [the documentation](https://github.com/nushell/nushell.github.io) after the PR is merged, if necessary. This will help us keep the docs up to date.

### CODE REVIEW

**Comment by NotLebedev** [comment]
So I am not 100% sure here. Currently a pretty table is printed to stderr. Should it be like this or should I print just plain text instead?

**Comment by rgwood** [comment]
> IMO, I think it would be better, as a general rule, to reserve pretty tables for stdout and text for stderr.

Agreed.

**Comment by NotLebedev** [comment]
Done. Now this looks like plain text:
image

**Review by rgwood — APPROVED** [review]
This looks good to me. Thank you for the PR!

**Comment by fdncred** [comment]
I can kind of see where this may become annoying. How do I get rid of this "empty list"?
image

**Comment by rgwood** [comment]
Interesting. `each` returns an empty list if the closure returns nothing... I'm not sure if it should.
image

**Comment by NotLebedev** [comment]
One could always add `ignore`:
image

What @rgwood is correct, I think that closure that returns nothing should maybe not produce empty list. However look at this examples:
image

In first example closure can return nothing or an `int`. I would say that in this case there should be an `empty list` placeholder. Another input and this list would not be empty.

In second and third cases closure returns nothing at all but in slightly different ways. First closure does not return anything, and second returns what `print` returns, but `print` returns nothing. But  in both cases it is clear that nothing could ever be returned.

However I do not see any way to know return type of closure in `each`. In my opinion `each` can return nothing iff closure has return type of `nothing`. But again, I don't see a way to get return type of closure. If it is possible I would like to know.

**Comment by NotLebedev** [comment]
> The output looks weird

In my opinion this does not look any worse than output if something is printed and returned at the same type:
image
This just follows existing design that stdout is indistinguishable from value returned by command:
image

However I agree that in this example it is uninformative and redundant, because it is clear from closure that the result will be empty.

**Comment by fdncred** [comment]
I'm leaning toward a revert atm. These bogus [empty list]'s are pretty annoying.

**Comment by rgwood** [comment]
We’re super early in the release cycle; I don’t think we should revert yet, perhaps we can find another way to clean up the output of `each`.

**Comment by fdncred** [comment]
We need some suggestions to make this better.

Options.
1. Revert
2. Leave it as is
3. Add an config point to disable it
4. Fix each or whatever else is broken (need help figuring this out)

I think part of the problem is people think `print` is just a normal everyday command, when actually it was written to support debugging by immediately writing out whatever you tell it versus being caught up in the pipeline and printing oddly like `echo` does sometimes. This is why `print` doesn't return nushell values.

I'm not saying that `print` shouldn't be used in other ways, but that's the history of it. I complained about `echo` and then jt wrote `print`.

**Comment by rgwood** [comment]
@fdncred Just to confirm, are you talking about reverting this PR or https://github.com/nushell/nushell/pull/7925? I think we started discussing this on the wrong PR.

**Comment by fdncred** [comment]
@rgwood good point. I think I am talking about that PR. I like the file system commands printing with `-v`. I think that's the one printing `[empty list]` like in this screenshot.
image

**Comment by webbedspace** [comment]
My personal opinion is that having [empty list] printed when you don't expect it isn't really a problem. My motivation for #6765 comes from experience using the browser console REPL, which prints *every* return value, including `null` and `undefined`, even if it would be "inconvenient". Open it now and check out this:
image
That `undefined` is `console.log()`'s return value. You might notice that it's denoted with a ← glyph to signify it's the command's return value, compared to `log()`'s side-effect output. The addition of that glyph might be an addition to Nushell that'd help matters.

**Comment by hustcer** [comment]
To me I don't like the `[empty list]` output in my running scripts, It's annoying, unless I can turn it off in my scripts which is not quite convenient either.
In a JS script `console.log(foo)` will display only `foo` and nothing else.

**Comment by rgwood** [comment]
> It would be better if `[empty list]` display in REPL mode and hide in script mode.

I think this is worth trying if it's not too hacky to implement.

**Comment by fdncred** [comment]
I don't even want to see it in repl mode the way `each` displays it

**Comment by webbedspace** [comment]
A `--verbose` flag for what? Every single command that might output an empty list or empty record? Nushell itself? (In the latter case it'd be better served as a config flag.)

**Comment by NotLebedev** [comment]
Ok the discussion is getting a little heated. I want to clarify something. 
First, there already is a config option to disable this. Please look in related PR https://github.com/nushell/nushell/pull/7925
Second, the problem with scripts printing `[empty list]` is not because of this PR. Look at this:
image

**Comment by rgwood** [comment]
We discussed this in today's team meeting. JT noted that people can use `for` instead of `each` to avoid outputting an empty list; @fdncred would that meet your needs?

**Comment by fdncred** [comment]
I'll just turn off the setting. `for` != `each` since one returns values and the other does not.

**Comment by hustcer** [comment]
>  I'm not sure why we want to output `[empty list]` for this each loop use case.

Agreed

> JT noted that people can use for instead of each to avoid outputting an empty list

@rgwood That's not good enough, IMO, I use `each` commonly as it can be piped, whereas `for` can't be piped, I have to break the pipe to use `for`.

**Comment by rgwood** [comment]
> I use `each` commonly as it can be piped, whereas `for` can't be piped, I have to break the pipe to use `for`.

That's a good point. Maybe we should try hiding `[empty list]` in scripts.

**Comment by NotLebedev** [comment]
> That's a good point. Maybe we should try hiding `[empty list]` in scripts.

Actually what is the point of printing output of anything but last pipeline?
image
The result in this example is highly unexpected IMO. For me it seems natural that last value is treated as return value and everything else is ignored (like it happens in rust)

**Comment by rgwood** [comment]
Continuing the discussion in the actual PR: https://github.com/nushell/nushell/pull/7925#issuecomment-1455138278

I'm wondering if we should temporarily disable this so we have more time to polish it.

**Comment by mksinicus** [comment]
This broke one of my scripts that batch-renames files and parses the output of `mv -v` into a pretty table... (Though there are other ways to do this, using the `--verbose` flag would seem most concise to me)

Can we currently redirect stderr of internal commands somehow, since `complete` only works on external streams? <https://github.com/nushell/nushell/issues/8277> suggests the answer is no. Just my personal opinion, maybe we shouldn't have done this change before redirection of internal stderr would be possible.

**Comment by rgwood** [comment]
This should get mentioned as a breaking change/new feature in the 0.77 blog post. @NotLebedev do you have time to write that up today or would you like someone else to? https://github.com/nushell/nushell.github.io/pull/800

@mksinicus Can you help us understand your use case a little better? What do you use that script for?

**Comment by mksinicus** [comment]
@rgwood Sure! It looks like

```nu
def batch-rename [pattern new_pat] {
   ls | get name | find $pattern | each {
     |e| mv -v $e ($e | str replace -sa $pattern $new_pat)
   } | flatten | str substring '6,' | split column ' to ' | rename 'moved' 'to'
 }
```

It batch renames files in the current directory, and the info printed with `--verbose` ("moved A to B") is collected into a list (as the return value of `each`) and parsed into a table with two columns. So it would work like such in the former version:

```sh
> touch foo.bar foo.baz
> batch-rename foo baz
╭───┬─────────┬─────────╮
│ # │  moved  │   to    │
├───┼─────────┼─────────┤
│ 0 │ foo.bar │ baz.bar │
│ 1 │ foo.baz │ baz.baz │
╰───┴─────────┴─────────╯
```

I agree that it's proper to print verbose info into stderr, just that it'd be nicer if we could have something that captures, redirects stderr, like `2>&1` in bash.

**Pull request merged**
