### PR TITLE
Simplify string interpolation

### PR DESCRIPTION
**Pull request by jonathandturner**
This is a draft proposal to simplify string interpolation.

Currently, string interpolation looks like this:

```
echo `This is my name {{$name}}`
```

It also can handle columns passed to it:

```
echo [[name]; [foo]] | each { echo `{{name}}` }
```

This proposal uses a different syntax and aligns the block with Nushell blocks, removing some of the surprises and streamlining the experience of using it.

Without #3389, this PR will look like:

```
echo $"this is my name {= $name}"
```

With #3389, this PR will look like:

```
echo $"this is my name {$name}"
```
The block is assume to be a full Nushell block, and I suspect this will mean the column shorthand behavior will be removed. Instead, you'll need to use the `format` command.

### CODE REVIEW

**Comment by fdncred** [comment]
is this supposed to work? 

```
echo [[name]; [foo]] | each { echo {= $name} }
```
i get this 
```
───┬───────
 0 │ block
───┴───────
```

**Comment by fdncred** [comment]
I was trying to mimic what you listed in the PR description:

> It also can handle columns passed to it:
```
echo [[name]; [foo]] | each { echo `{{name}}` }
```

**Comment by jmoore34** [comment]
What about

```bash
echo "this is my $name"
```

and for chained variable accesses
```bash
echo "this is my os ${nu.env.OS}"
```

and for command calls
```bash
echo "hello $(echo world)"
```

I feel like interpolation would be a more common use case than literal dollar signs, and for that, perhaps backticks could be repurposed to signify string literals. This would also allow users to use both single and double quotes in a string, e.g.

```
echo `<button onclick="alert('hello')" />` > index.html
```
Command substitution could be used in cases where the user wants both string literals and interpolation, e.g. ```echo "Your balance is $(echo `$`)$balance"```. And of course, things like a dollar sign followed by whitespace or numbers could automatically be treated as literals.

I feel like this would be a bit more natural for users coming from other shells, but I'm happy to hear your thoughts.

**Comment by fdncred** [comment]
I'd really prefer to be consistent with how we handle this. I would push back on, "when it looks like `x` you need to do `y`", that's just too confusing. I'd rather have, "always do `x` with string interpolation, no matter what", although I don't know if these changes work in all circumstances. I'd really like to land this the way it is and adjust if needed.

**Comment by jmoore34** [comment]
That's a good point. I was thinking of revising my comment to:

```
echo "this is my os $($nu.env.OS)"
```

for consistency, but looking at it, I think JT's syntax looks cleaner. 😁

**Comment by jonathandturner** [comment]
@jmoore34 - ah good. and thanks for investigating :slightly_smiling_face: 

Looking forward to using this!

**Pull request merged**
