### PR TITLE
Make opening a directory list its contents

### LINKED ISSUE #3117: Opening a directory hangs nushell indefinitely with high CPU
**Describe the bug**
If you open a directory with a relative path, the application hangs indefinitely with high CPU

**To Reproduce**
Steps to reproduce the behavior, run the following command
 - `open foo` (where foo is a directory)

**Expected behavior**
The command fails with an error (or maybe it's an alias for enter?)

**Configuration:**

Run `version | pivot` and paste the output to show OS, features, etc.

```
> version | pivot
────┬────────────────────┬────────────────────────────────────────────────────────────────────────────────────
 #  │      Column0       │                                      Column1
────┼────────────────────┼────────────────────────────────────────────────────────────────────────────────────
  0 │ version            │ 0.27.1
  1 │ branch             │ FilterCurDir
  2 │ short_commit       │ dd0f7bf7
  3 │ commit_hash        │ dd0f7bf778dae623deeb601521c91038cf9b2dc1
  4 │ commit_date        │ 2021-02-22 11:00:48
  5 │ build_os           │ macos-x86_64
  6 │ rust_version       │ rustc 1.50.0 (cb75ad5db 2021-02-10)
  7 │ rust_channel       │ stable-x86_64-apple-darwin (default)
  8 │ cargo_version      │ cargo 1.50.0 (f04e7fab7 2021-02-04)
  9 │ pkg_version        │ 0.27.1
 10 │ build_time         │ 2021-02-22 11:06:54
 11 │ build_rust_channel │ release
 12 │ features           │ ctrlc, default, directories, dirs, ichwh, ptree, rustyline, term, uuid, which, zip
────┴────────────────────┴────────────────────────────────────────────────────────────────────────────────────
```

### PR DESCRIPTION
**Pull request by iCodeSometime**
Hi. I'm not sure this is a change that you guys would like, or more generally where you find yourself on the spectrum between "there should be only one way to do everything" and "if it seems like it should work, it should work" - but this is one potential solution to close #3117.

I assume the existing error handling should be modified a bit also to prevent related issues, but I am not yet familiar enough with rust to figure out what's needed there.

### CODE REVIEW

**Comment by iCodeSometime** [comment]
WIP - will add test in addition to example.

**Comment by jonathandturner** [comment]
I was thinking through some of the things `open <directory>` could potentially do (like what would someone expect it to do).

`enter` I *think* might be a little too surprising, if they've never used the `shells` feature before.

That said, `open <directory>` could do something like give back a simple directory list of that directory.

Any other ideas for things people might expect it to do?

**Comment by iCodeSometime** [comment]
Every time I have accidentally tried to open a directory, I'd meant to enter it, but making it behave like `ls` does seem more consistent with how it normally behaves, now that you mention it.

Opening a file displays the contents, so opening a directory should display it's contents.

I'll get it changed and get a test added in the next day or so

**Comment by jonathandturner** [comment]
Sounds good

**Pull request merged**
