### PR TITLE
:sparkles: Make `hover` equal to `help` command

### PR DESCRIPTION
**Pull request by AucaCoyan**
# Description
Hi! A few days ago I changed the hover from `--ide-lsp` to match `help` #11284, now this PR is doing the same but for the new `--lsp` server

I also did some tiny fixes to syntax, with some clippy `pedantic` lints

# User-Facing Changes
image

# Tests + Formatting
✅ ran `toolkit check pr`

### CODE REVIEW

**Comment by fdncred** [comment]
@AucaCoyan if you can fix the conflict, we can probably move forward with this.

**Comment by AucaCoyan** [comment]
Sure! Thanks

**Comment by fdncred** [comment]
now if we can get the ci green, we'll be good to go.

**Comment by AucaCoyan** [comment]
Now it's green! I had a fight with git and the with cargo test. You can see I lost a few times 🤣

**Comment by fdncred** [comment]
Thanks!

**Pull request merged**
