### PR TITLE
Use the directories crate instead of app_dirs

### PR DESCRIPTION
**Pull request by AdminXVII**
The app_dirs crate is abandonned since quite a bit of time. Use the directories
crate instead, which is maintained and have more OS support.

### CODE REVIEW

**Comment by AdminXVII** [comment]
I don't think the CI failure is due to this PR. If it is, please let me know if you have a clue about the problem.

**Comment by jonathandturner** [comment]
@AdminXVII - agreed. I've filed a bug for that failing test. https://github.com/nushell/nushell/issues/1783

After re-running everything is green

**Comment by jonathandturner** [comment]
Looks good!

**Comment by aeosynth** [comment]
> Use the directories crate instead, which is maintained

actually [directories-rs](https://github.com/soc/directories-rs) is also abandoned (archived), along with its dependencies of [dirs-rs](https://github.com/soc/dirs-rs) and [dirs-sys-rs](https://github.com/soc/dirs-sys-rs). maybe nu could take ownership of them?

**Pull request merged**
