### PR TITLE
Improve "Did you mean?" suggestions

### PR DESCRIPTION
**Pull request by dandavison**
# Description
Fixes https://github.com/nushell/nushell/issues/6578

This PR improves the "did you mean suggestions". See #6578 but the biggest problem is that there was no upper limit on how dissimilar a suggestion could be. I've gone back and forth on implementations but would like to suggest that, for now, a simple, reliable step that goes a reasonable way in a good direction is just to copy what the rust compiler does. So that's what this PR does (it involves vendoring one file from https://github.com/rust-lang/rust).

I have made one change to Rust's behavior: if the user input is a single character, and the suggestion is a different character (not merely an upper/lower case difference) then this PR does _not_  make such a suggestion. Rust does make the suggestion, but it doesn't seem likely to be helpful to me.

# Tests

Make sure you've done the following:

- [x] Add tests that cover your changes, either in the command examples, the crate/tests folder, or in the /tests folder.
- [x] Try to think about corner cases and various ways how your changes could break. Cover them with tests.
- [x] If adding tests is not possible, please document in the PR body a minimal example with steps on how to reproduce so one can verify your change works.

Make sure you've run and fixed any issues with these commands:

- [x] `cargo fmt --all -- --check` to check standard code formatting (`cargo fmt --all` applies these changes)
- [x] `cargo clippy --workspace --features=extra -- -D warnings -D clippy::unwrap_used -A clippy::needless_collect` to check that you're using the standard code style
- [x] `cargo test --workspace --features=extra` to check that all the tests pass

### CODE REVIEW

**Comment by fdncred** [comment]
This PR looks interesting to me. The only unsubstantiated concern I have is performance. Previously we had a "slow" Levenshtein function. Then we added the one here that was just removed. I wonder if the rust one is equal or better performance or if there's a trade off in performance to have more accurate error reporting.

**Comment by dandavison** [comment]
Hey @fdncred, thanks for thinking about this.

So the first thing I'd say is that we _were_ until a week ago doing Levenshtein calculations in various non-error code paths (e.g. when a user runs an executable), so performance would indeed have been a concern until recently. But we stopped doing that in https://github.com/nushell/nushell/pull/6540. So now, we only do Levenshtein calculations when showing an error to a user, making performance much less of a worry.

Can you link me to discussion of the slow Levenshtein function? Was the concern there slowness when showing errors to the user, or slowness in internal nushell code paths (that maybe should never have been doing Levenshtein in the first place?).

Secondly, while I have't benchmarked, this code is from Rust, and it's what they use to display errors. So if there's a performance problem with it then we should open an issue against Rust, but it seems very unlikely.

**Comment by dandavison** [comment]
@fdncred related to your point, it probably does make sense to refuse to calculate edit distance above a certain string size or for more than N strings.

**Comment by fdncred** [comment]
> Can you link me to discussion of the slow Levenshtein function? 

#3358
#3361
#3366

**Comment by dandavison** [comment]
@fdncred, thanks! Yes, confirmed, the Rust compiler version doesn't do any allocations in the loops over characters. But, for example, if a user makes a typo in a field name in a record with a large number `N` of fields, then it could get slow, because we'll be calling `lev_distance` `N` times, and hence allocating `N` times, and I think it does actually make sense to check for that. (But probably shouldn't block this MR because that issue is present currently.)

**Comment by dandavison** [comment]
There's a genuine-looking test failure on ubuntu. Not immediately clear to me why it fails on ubuntu only, will look into it.

**Comment by dandavison** [comment]
All tests are passing on this branch now.

**Comment by fdncred** [comment]
let's try it. thanks dan.

**Pull request merged**
