### PR TITLE
Improve md5 and sha256 code

### PR DESCRIPTION
**Pull request by realcundo**
- md5 and Sha256 (and other future digests) require less boilerplate code  now
- error reporting includues the name of the hash again
- added missing hash sha256 test

@fdncred this is what I came up with so far. To support dynamic `name()` and `usage()` I'd need to change the signature from `&str` to `String` or `Cow<str>` -- it turns out there are 300 structs that I'd have to touch so for now I'm storing name/usage as `String`. If you think `Cow` is better I'll be happy to make this or any other change. :smile:

### CODE REVIEW

**Comment by fdncred** [comment]
Thanks @realcundo! 

@jntrnr can you chime in here please? I'd hate for someone to go down the path of changing the signature in ~300 places for something we don't need or want to do.

**Comment by jntrnr** [comment]
@realcundo - there's some value to it, though my feeling is that we should start an issue and collect together the changes we want to do across all the commands. Because it will break folks building things from nushell, I'd like to batch up these kinds of changes where possible

**Comment by realcundo** [comment]
@jntrnr thanks, that makes sense. In that case I won't touch the public interface to support dynamic usage/name fields and the PR doesn't need any change, unless there's something related to the hashing impl.

**Comment by fdncred** [comment]
i was thinking that was the case @realcundo. let's land this and see what happens. we can always revert if we need to. thanks!

**Pull request merged**
