### PR TITLE
`from-ssv` logic updated

### PR DESCRIPTION
**Pull request by t-hart**
Hey! So a pull request with no prior discussion may be bad form, but I was tinkering around with this problem I had and managed to solve it, and due to how we're seemingly in very different time zones, I just wanted to get it out there without too much delay. Hope you don't mind.

# What and why

Anyway: **I'd like to change the table creation algorithm for `from-ssv`**. Previously, the table would be created based only on an entries index in a row as decided by the separators in the row. This meant that two values, though vertically misaligned, could still belong together:
```
col1                col2
a        b
```
So in the above snippet, assuming a separator of two spaces, `a` belongs to `col1`, and `b` to `col2`. This makes a lot of sense to me, but it has one pretty big hole: **what about empty values**?

Given this table:
```
col1   col2   col3
a             c
```
It seems quite intuitive that `c` would go in `col3` and that `col2` just doesn't have a value in this case, but with the old (current) algorithm, `c` would belong to `col2` and `col3` would have an empty value.

With the new algorithm, the first table would give `col1` the value of `a        b` and `col2` and empty string. The second table would pair `col1` with `a`, `col3` with `c` and `col2` with an empty string again.

Thus, given that the only real world examples I have seen of space-separated values being used  are output from `kubectl` (Kubernetes) or `oc` (OpenShift), and that these output values sometimes _do_ have holes in them, I think this approach, **basing an entry's column on its horizontal alignment**, is more correct and intuitive. 

-----

Discussion on this is very welcome, and please do not feel any pressure to merge this if you disagree with the sentiment. I should have opened an issue for clarification but got a bit to absorbed by trying to solve the problem, so let this act as both a potential solution and a general discussion for the issue.
Cheers!

### CODE REVIEW

**Comment by jonathandturner** [comment]
I think you're right it's going to often be columns.  We have a way now to split on just the whitespace, and this gives you something closer to what you would want: being able to understand the columns more visually.

Do you think this is going to be the major way people use it? Is it worth having two modes or just this one?

**Comment by t-hart** [comment]
Hmm, that's a good question. I don't really have a clear idea about how people use text in this format outside of the kubernetes ecosystem, but I think that it's generally going to be presented in a columnar fashion.

If you want to store text in a file format that uses a separator, you're more than likely going to use one of the more traditional formats such as csv or tsv. This makes it easier for humans to scan and for machines to work with. Having a separator be a single character instead of a combination of characters--especially when they're all spaces, which is a character that might appear frequently anyway--makes it clearer where the separation occurs, and easier to parse. 

I think the main use case for space-separated tables like this is for output from command line interfaces and the like where the source of the data can't guarantee tab width, and where aligning values is more important than having a clear separator between them. This strikes me as being chiefly concerned with readability, and as such, very likely to align data with column headers.

Side note: I was playing around with it a bit and noticed that when piping it through `from-ssv` and into `to-yaml` (or any other format) still renders columns with empty values. This is expected, as I register them as empty spaces, if I instead didn't register them, would the keys be absent from the yaml output, or would they still appear? I'll have a look.

**Comment by jonathandturner** [comment]
Yeah that sounds good.  I think we still need to work out exactly what happens in tables where the columns are different, both visually and in terms of how they serialize, but for now I think we can land this and keep iterating.

**Comment by t-hart** [comment]
Yeah, I agree. I'm happy with where it's at right now, but wouldn't mind expanding on it (or for anyone else to) if there are other suggestions. 

You sound like you have some thoughts, so I'd be very interested to hear them.

**Pull request merged**
