### PR TITLE
nu-explore: Refactorings

### PR DESCRIPTION
**Pull request by zhiburt**
1. Added mode to the status bar right most corner
2. Added a command name with a status when run

ref #8582 
cc: @fdncred

### CODE REVIEW

**Comment by fdncred** [comment]
So fun to play with this again. I like the changes. It makes it a little more useful and intuitive.

**Comment by rgwood** [comment]
Nice, thanks @zhiburt!

I noticed the mode (bottom right), looks good:
image

I'm not sure what "Added a command name with a status when run" is, do you or @fdncred have a screenshot handy?

**Comment by zhiburt** [comment]
> I'm not sure what "Added a command name with a status when run" is, do you or @fdncred have a screenshot handy?

When you run a command you see it's title;

image

image

**Comment by fdncred** [comment]
Mine looks like this when I launch `explore` and do `:nu sys`. Using `:nu` will run any pipeline from within `explore`.
image

**Comment by amtoine** [comment]
just to be sure, does this PR fixes part or all of #8582 ? :yum:

**Comment by rgwood** [comment]
@amtoine just part of it (showing the current mode). I think this PR is a good incremental improvement, thanks Maxim!

I've been reading through the `explore` code, it looks good and I think I'll be able to make some contributions to it soon.

**Review by rgwood — APPROVED** [review]

**Comment by amtoine** [comment]
definitely thanks @zhiburt for working on built-in `explore` :pray:

**Comment by fdncred** [comment]
Thanks @zhiburt! as always.

**Pull request merged**
