### PR TITLE
Remove `math eval` command

### LINKED ISSUE #7073: Remove `math eval` and fully replace it with pure nushell implementation
### Related problem

We currently have `math eval` that takes a string and parses and executes math in it through the `meval` crate. 
This creates two sources of truth how math behaves in nushell. 

Further more the crate carries some out of date dependencies, causing dependency duplication.

### Describe the solution you'd like

For nu to be a fully useable scripting language there should be a library of math functions that are implemented with proper care (may be part of the core or a plugin).
`math eval` shouldn't be necessary or trivially implementable in nu code.

### Describe alternatives you've considered

Hot take: If you need string math `bc` is still around, but `math eval` is only slightly more compatible with nushell/ 

## List of missing math commands:

Compare to https://docs.rs/meval/latest/meval/#supported-expressions

#### Exponentiation

- [x] `pow`/ general exponentiation
- [ ] `exp`, 
- [x] `ln`
- [x] logs in other bases for convenience/numerical stability reasons

#### Trigonometry
- [x] `sin`
- [x]  `cos`
- [x]  `tan`
- [x]  `asin`
- [x]  `acos`
- [x]  `atan`
- [ ]  `atan2`
- [x] `sinh`
- [x] `cosh`
- [x] `tanh`
- [x] `asinh`
- [x] `acosh`
- [x] `atanh`

#### Utilities
- [ ] `signum` (get the sign cheaply)
- [x] `modulo` 

#### constants:
- [x] `pi`
- [x] `e`

### PR DESCRIPTION
**Pull request by sholderbach**
# Description

- [x] #7258 and potential further math commands need to land
- [x] Requires sign off from the team

## Reasoning:

Most missing math commands are implemented with #7258.
The `meval` crate itself declares that it doesn't strive to stringent
standards (https://docs.rs/meval/latest/meval/#related-projects).
For example no particular special casing or transformations are
performed to ensure numerical stability. It uses the same rust `std`
library functions we use or have access to (and `f64`).
While the command call syntax in nushell may be a bit more verbose,
having a single source of truth and common commands is beneficial.
Furthermore the `math` commands can themselves implement broadcasting
over lists (or table columns).

Closes #7073

Removed dependencies:
- `meval`
- `nom 1.2.4` (duplicate)

# User-Facing Changes

Scripts using `math eval` will break. 
We remove a further `eval` like behavior to get results through runtime evaluation (albeit limited in scope)

# Tests

- Updated tests that internally used `math eval`.
- Removed one test that primarily used `math eval` to obtain a result from `str join`

### CODE REVIEW

**Comment by rgwood** [comment]
Sounds good to me. Better to evaluate these kinds of expressions in native Nu code.

**Comment by sholderbach** [comment]
Making a deprecation note for a subcommand currently kind of sucks:
https://github.com/sholderbach/nushell/blob/29fdfeee433c3bbf31667971cc4f3166faa3ac92/crates/nu-command/src/deprecated/deprecated_commands.rs#L3 
We would need to carry the command around returning an error as long as the `math` base help command exists. (Same applies for `url parse` where we only have it left)

**Comment by sholderbach** [comment]
Not happy with the state of deprecation yet #7530 
Else the removal could go ahead as soon as we are happy. Will have to update a few scripts that still rely on `math eval`

**Comment by rgwood** [comment]
Nice, thanks for getting this over the line.

**Pull request merged**
