### PR TITLE
an experiment to make `glob` output `const`

### PR DESCRIPTION
**Pull request by fdncred**
# Description

Just some stray thoughts here. I was thinking that the return of `glob` could be `const`. Maybe that's a bad idea, but I coded it up anyway. With this PR you can do the following.
```nushell
const files = (glob *.nu)
source $files.0
```
What you cannot do is `for` or `each` loop through them sourcing them. So, I'm not sure what good this change does but I wanted to put it up for discussion.

@kubouch any thoughts on this?

# User-Facing Changes

# Tests + Formatting

# After Submitting

### CODE REVIEW

**Comment by AucaCoyan** [comment]
Thanks for the PR!
I am the culprit here 🤣 

I was trying to do
```nu
let files  = glob **/*.nu

for file in $files {
    source $file
}
```

but we couldn't make the for loop work. [This is the discord discussion](https://discord.com/channels/601130461678272522/614593951969574961/1200087531346206721)

**Comment by fdncred** [comment]
Thanks @AucaCoyan. The question here is, "Is there any value to glob returning const"? I'm not really sure. As we discussed on discord, if we has something like this:
```nushell
for (const file) in $files {
  source $file
}
```
Then it would probably work but since it's being captured in the block, it seems like it's const-ness is being removed.

**Comment by kubouch** [comment]
I think in principle, it shouldn't be that bad to have glob as const, but we must be careful about the implicit `$env.PWD` dependency. One other issue is ordering: Is the glob output guaranteed to be ordered in some way? I think some glob implementations iterate in random order (maybe Python, not sure). Lastly, I'm not sure about the use case.

I'm not hard against this, if there is a good use case for it, but it introduces some unclarity because when calling `source $files.0`, you don't really know what you're sourcing.

**Comment by fdncred** [comment]
closing this for now. I'm just not sure there's value having glob results as a const. if you disagree, let's talk and reopen this.

**Pull request closed without merging**
