### PR TITLE
Optional members in cell paths: Attempt 2

### PR DESCRIPTION
**Pull request by rgwood**
This is a follow up from https://github.com/nushell/nushell/pull/7540. Please provide feedback if you have the time!

## Summary

This PR lets you use `?` to indicate that a member in a cell path is optional and Nushell should return `null` if that member cannot be accessed. 

Unlike the previous PR, `?` is now a _postfix_ modifier for cell path members. A cell path of `.foo?.bar` means that `foo` is optional and `bar` is not.

`?` does _not_ suppress all errors; it is intended to help in situations where data has "holes", i.e. the data types are correct but something is missing. Type mismatches (like trying to do a string path access on a date) will still fail.

### Record Examples

```bash

{ foo: 123 }.foo # returns 123

{ foo: 123 }.bar # errors
{ foo: 123 }.bar? # returns null

{ foo: 123 } | get bar # errors
{ foo: 123 } | get bar? # returns null

{ foo: 123 }.bar.baz # errors
{ foo: 123 }.bar?.baz # errors because `baz` is not present on the result from `bar?`
{ foo: 123 }.bar.baz? # errors
{ foo: 123 }.bar?.baz? # returns null
```

### List Examples
```
〉[{foo: 1} {foo: 2} {}].foo
Error: nu::shell::column_not_found

  × Cannot find column
   ╭─[entry #30:1:1]
 1 │ [{foo: 1} {foo: 2} {}].foo
   ·                    ─┬  ─┬─
   ·                     │   ╰── cannot find column 'foo'
   ·                     ╰── value originates here
   ╰────
〉[{foo: 1} {foo: 2} {}].foo?
╭───┬───╮
│ 0 │ 1 │
│ 1 │ 2 │
│ 2 │   │
╰───┴───╯
〉[{foo: 1} {foo: 2} {}].foo?.2 | describe
nothing

〉[a b c].4? | describe
nothing

〉[{foo: 1} {foo: 2} {}] | where foo? == 1
╭───┬─────╮
│ # │ foo │
├───┼─────┤
│ 0 │   1 │
╰───┴─────╯
```

# Breaking changes

1. Column names with `?` in them now need to be quoted.
2. The `-i`/`--ignore-errors` flag has been removed from `get` and `select`
    1. After this PR, most `get` error handling can be done with `?` and/or `try`/`catch`.
4. Cell path accesses like this no longer work without a `?`:
```bash
〉[{a:1 b:2} {a:3}].b.0
2
```
We had some clever code that was able to recognize that since we only want row `0`, it's OK if other rows are missing column `b`. I removed that because it's tricky to maintain, and now that query needs to be written like:

```bash
〉[{a:1 b:2} {a:3}].b?.0
2
```

I think the regression is acceptable for now. I plan to do more work in the future to enable streaming of cell path accesses, and when that happens I'll be able to make `.b.0` work again.

### CODE REVIEW

**Comment by fdncred** [comment]
Just to be clear, the reason you're suggesting we remove `--ignore-errors/-i` is because:

These produce identical results
```
{ foo: 123 } | get bar?
{ foo: 123 } | get -i bar
```

and these produce identical results

```
[{a:1 b:2} {a:3}] | select b?
[{a:1 b:2} {a:3}] | select -i b
```

If that is correct, then I'd propose dropping the `-i` in this PR, and maybe have a deprecate message on `-i`?

**Comment by rgwood** [comment]
Right, `?` can replace `-i` in most situations. For others, try/catch can be used. I’ll remove `-i`

**Comment by rgwood** [comment]
On second thought... removing `-i` is going to be hard, it's used in `default_env.nu` 😞 

```
let home = ($env | get -i (if $nu.os-info.name == "windows" { "USERPROFILE" } else { "HOME" }) | into string)
```

Removing the flag will break people's `env.nu`. Maybe we should leave it around for now.

**Comment by rgwood** [comment]
I've removed the `-i` flag from `get` and `select`. Hopefully that won't make too many people angry.

**Comment by webbedspace** [comment]
Thanks for revisiting this feature!

**Comment by rgwood** [comment]
I asked in Discord and several people voted to merge this. Let's give it a try!

**Pull request merged**
