### PR TITLE
Deprecate `size` to `str stats`

### PR DESCRIPTION
**Pull request by hustcer**
# Description

Rename `str size` to `str stats`, for more detail see: https://github.com/nushell/nushell/pull/10772

# User-Facing Changes

# Tests + Formatting

# After Submitting

### CODE REVIEW

**Comment by fdncred** [comment]
Looks good. Just so we don't forget, this PR also needs to be updated https://github.com/nushell/nushell/pull/10784 so it suggests the right command.

**Comment by hustcer** [comment]
> Looks good. Just so we don't forget, this PR also needs to be updated #10784 so it suggests the right command.

I think we should land it before the next release and update https://github.com/nushell/nushell/pull/10784 after the next release, right?

**Comment by fdncred** [comment]
ya, i think so. i'm not saying it's time to land #10784, but as it sits now, it's wrong. so, we should update 10784 so when we're ready to land it, it's right.

**Comment by amtoine** [comment]
yeah the idea behind removal PRs is for them to be ready as soon as the deprecation lands, in a DRAFT, so that we do not forget about them :relieved:

**Pull request merged**
