### PR TITLE
fix embedded whitespace breaking nu-highlight parse

### PR DESCRIPTION
**Pull request by bobhy**
# Description

There are a couple of places where Nu tries to parse and colorize representations of Nu objects, e.g `view source`  and help displaying example results which are records or lists.  See #8928 and #9027.

In these cases, the common issue is unquoted whitespace introduced by stringifying a Value::String but also Value::Date via method `.into_string()` and friends. The user-visible result is output from `nu-highlight` that is mostly colored red.

This PR aims to fix both scenarios, though exactly how is not yet determined.  

* The first step is to provide an alternate implementation for stringification of `Value::` which avoids the embedded whitespace: by quoting strings (but only when embedded in a record or list) and by using a different date time format (e.g RFC3339).  That much is covered by the first commit here.
* Next step is to provide a way to stringify arbitrary nu `Value::` for use in contexts that require parsability, such as help and view source.  Approach currently TBD
* Possible 3rd piece of the puzzle is to address `view source` as a special case, since the logic for generating the source string is embedded in this builtin.

# User-Facing Changes

# Tests + Formatting

# After Submitting

### CODE REVIEW

**Comment by bobhy** [comment]
Ready for review.  This will also resolve #8928.
The new command `to parsable` sounds arcane, though the function does the right thing (as used in `std help`).  
It could better be called `view pipeline` (or `view pipeline object`, which would be more correct but also unnecessarily pedantic), or other names you might suggest.

**Review by amtoine — COMMENTED** [review]
i did not look at all the code but i have a few questions already
- you seem to mention to problems in the PR body, could this PR be split up into smaller and easier-to-review ones?
- do we need the new `rstest` dependency?
- you say https://github.com/nushell/nushell/issues/8928 will be fixed here but it's already been fixed, right? (i can see the default values of something like `def foo [x = "foo"] {}` with both `help foo` and `std help foo` on latest `main` :open_mouth:)

**Comment by fdncred** [comment]
should this be folded into `to text`?

**Comment by amtoine** [comment]
also @bobhy, i'm still not sure what to expect before / after this PR :confused: 
**is there some `nu-highlight` command that we can run to see the changes in action?** :yum:

**Pull request closed without merging**
