### PR TITLE
Fix find puts extra cols into record

### LINKED ISSUE #9394: Regression in find command
### Describe the bug

With nushell 0.81 the find command seems to generate puzzling results - please see "How to reproduce" for a simple example.

### How to reproduce

Setup:

```
$ mkdir test
$ cd test
$ touch file_a
$ touch file_b
$ touch file_c
```

This works as expected:

```
$ ls | find file_a

╭───┬────────┬──────┬──────┬──────────────╮
│ # │  name  │ type │ size │   modified   │
├───┼────────┼──────┼──────┼──────────────┤
│ 0 │ file_a │ file │  0 B │ a minute ago │
╰───┴────────┴──────┴──────┴──────────────╯
```

This messes up columns, and highlights file_a in column name, and file_b in column type:

```
$ ls | find file_a file_b

╭───┬────────┬────────┬──────┬──────────╮
│ # │  name  │  type  │ size │ modified │
├───┼────────┼────────┼──────┼──────────┤
│ 0 │ file_a │ file_a │ file │ file     │
│ 1 │ file_b │ file_b │ file │ file     │
╰───┴────────┴────────┴──────┴──────────╯
```

Same here, only the highlights are switched:

```
$ ls | find file_b file_a                                                                                                         
╭───┬────────┬────────┬──────┬──────────╮
│ # │  name  │  type  │ size │ modified │
├───┼────────┼────────┼──────┼──────────┤
│ 0 │ file_a │ file_a │ file │ file     │
│ 1 │ file_b │ file_b │ file │ file     │
╰───┴────────┴────────┴──────┴──────────╯
```

This messes up columns even more, and does not even highlight file_f:

```
$ touch file_d file_f
$ ls | find file_b file_a file_c file_d file_f                                                                                    
╭───┬────────┬────────┬────────┬──────────╮
│ # │  name  │  type  │  size  │ modified │
├───┼────────┼────────┼────────┼──────────┤
│ 0 │ file_a │ file_a │ file_a │ file_a   │
│ 1 │ file_b │ file_b │ file_b │ file_b   │
│ 2 │ file_c │ file_c │ file_c │ file_c   │
│ 3 │ file_d │ file_d │ file_d │ file_d   │
│ 4 │ file_f │ file_f │ file_f │ file_f   │
╰───┴────────┴────────┴────────┴──────────╯
```

### Expected behavior

Same example run in nushell 0.76.0:

```
$ ls | find file_b file_a file_c file_d file_f                                                                                    
╭───┬────────┬──────┬──────┬────────────────╮
│ # │  name  │ type │ size │    modified    │
├───┼────────┼──────┼──────┼────────────────┤
│ 0 │ file_a │ file │  0 B │ 10 minutes ago │
│ 1 │ file_b │ file │  0 B │ 10 minutes ago │
│ 2 │ file_c │ file │  0 B │ 10 minutes ago │
│ 3 │ file_d │ file │  0 B │ 4 minutes ago  │
│ 4 │ file_f │ file │  0 B │ 4 minutes ago  │
╰───┴────────┴──────┴──────┴────────────────╯
```

### Screenshots

_No response_

### Configuration

| key                | value                                                             |
| ------------------ | ----------------------------------------------------------------- |
| version            | 0.81.0                                                            |
| branch             |                                                                   |
| commit_hash        |                                                                   |
| build_os           | openbsd-x86_64                                                    |
| build_target       | x86_64-unknown-openbsd                                            |
| rust_version       | rustc 1.69.0 (84c898d65 2023-04-16) (built from a source tarball) |
| cargo_version      | cargo 1.69.0                                                      |
| build_time         | 2023-06-09 11:36:29 +00:00                                        |
| build_rust_channel | release                                                           |
| features           | default, sqlite, trash, which, zip                                |
| installed_plugins  |                                                                   |

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by AstrickHarren**
# Description

Trying to fix #9394. 

The problem with PR #9159 seems to be when searching for multiple terms, each term is checked against the original values. It outputs a new value for each such check, thus introducing replication for each search term. As a result, it works fine with num of search term = 1.

### CODE REVIEW

**Review by amtoine — CHANGES_REQUESTED** [review]
@AstrickHarren 
thanks for tackling this issue :relieved: 

could you add some tests to make sure the issue is fixed with these changes? :yum:

**Comment by fdncred** [comment]
This was hard to get right the first time I wrote this highlighting code. Look at this example. The LS_COLORS highlighting is gone. It should be there with the find hit colored differently.
image

**Comment by amtoine** [comment]
@fdncred 
does this mean that this PR broke something? :open_mouth:

**Comment by AstrickHarren** [comment]
Looks like the red-white color is introduced in PR #9326. As far as I understand, the color from a ls command seems to be handled at the end of the command. (Looks like `ls = ls | table` to me, and `table` is responsible to color the output if it thinks a certain string is path). 

Now if `ls | find | table` is called, and `find` try to color strings before `table`, table will have hard time understanding the colored string as a path and will do nothing about it. Prior to #9326, this seems to be done manually with find taking on the responsibility of producing both lscolors and highlighted colors.

**Comment by AstrickHarren** [comment]
I have added test cases for the PR

**Comment by fdncred** [comment]
ok, this is wrong but better. The LS_COLORS highlighting needs to happen like it did before and then highlighting on top of that.

**Pull request merged**
