### PR TITLE
WIP: Path utility commands

### PR DESCRIPTION
**Pull request by mattyhall**
For #2145 . Probably not ready and I realise nu isn't set on using std::path::Path. I had fun giving this a go and thought I would submit a PR in case it is useful, but no worries at all if not! It includes:

* basename
* extension
* expand (expands to a full path, including fixing up ~/, ../ etc)

My main question is what is nu's philosophy on error handling. Commands like expand and extension could fail. Should it cause an error or should it give some other value (eg empty string, original path)?

### CODE REVIEW

**Comment by jonathandturner** [comment]
@mattyhall - this looks good. I think how you have it looks right, to me. If there isn't an extension, but the path is valid, returning an empty string seems good. You are returning ShellError when there are errors, and that part also looks good.

If you're comfortable with it, I'd be happy to land it.

**Comment by mattyhall** [comment]
That’s fine by me then 🙂

**Comment by jonathandturner** [comment]
Sounds good. Thanks for working on this

**Comment by jonathandturner** [comment]
@mattyhall - btw, any interest in the `url` commands? I was thinking we could do a similar treatment for parsing URLs

**Comment by mattyhall** [comment]
As in getting the hostname, path, protocol and so on out of a url? If so, yes :smile:

**Comment by jonathandturner** [comment]
@mattyhall - yup, exactly that 👍

**Pull request merged**
