### PR TITLE
[draft] start working on removing unwraps!!!

### PR DESCRIPTION
**Pull request by ubsan**
bitmoji

(sorry, this should be a draft PR, I just screwed up when creating it)

### CODE REVIEW

**Comment by jonathandturner** [comment]
@ubsan - interested in working on this?

**Comment by ubsan** [comment]
@jonathandturner yeah, I'm just having a really stressful quarter

**Comment by jonathandturner** [comment]
@ubsan - no worries, I'll keep it open for ya :)

**Comment by jonathandturner** [comment]
@ubsan - okay, since this has probably bit-rotted quite a bit now, I'm going to go ahead and close it.

If you want to have another go at removing unwraps, please do. We can put together a checklist and see if we can get other volunteers too, if you like.

**Pull request closed without merging**
