### PR TITLE
add multiple grouper support to `group-by`

### LINKED ISSUE #14330: `group-by` should support multiple grouper arguments
### Related problem

Related:
- #2607 
- #14019
- #14316 

### Describe the solution you'd like

Similar to `sort-by`, `group-by` should support multiple grouper arguments, as the rest parameter.
```nushell
group-by ...(grouper)
```

Examples will be demonstrated on this sample data, taken from split-by's examples

```nushell
let data = [
    [name, lang, year];
    [andres, rb, "2019"],
    [jt, rs, "2019"],
    [storm, rs, "2021"]
]
```

---

Without `--to-table`, the output would be in the form of nested records, which would also make `split-by` obsolete.

Output of the split-by command, and the suggested group-by should be the same.
```nushell
> $data | group-by year | split-by lang
> $data | group-by lang year
╭────┬─────────────────────────────────────────╮
│    │ ╭──────┬──────────────────────────────╮ │
│ rb │ │      │ ╭─#─┬──name──┬─lang─┬─year─╮ │ │
│    │ │ 2019 │ │ 0 │ andres │ rb   │ 2019 │ │ │
│    │ │      │ ╰─#─┴──name──┴─lang─┴─year─╯ │ │
│    │ ╰──────┴──────────────────────────────╯ │
│    │ ╭──────┬─────────────────────────────╮  │
│ rs │ │      │ ╭─#─┬─name─┬─lang─┬─year─╮  │  │
│    │ │ 2019 │ │ 0 │ jt   │ rs   │ 2019 │  │  │
│    │ │      │ ╰─#─┴─name─┴─lang─┴─year─╯  │  │
│    │ │      │ ╭─#─┬─name──┬─lang─┬─year─╮ │  │
│    │ │ 2021 │ │ 0 │ storm │ rs   │ 2021 │ │  │
│    │ │      │ ╰─#─┴─name──┴─lang─┴─year─╯ │  │
│    │ ╰──────┴─────────────────────────────╯  │
╰────┴─────────────────────────────────────────╯
```

---

With `--to-table`, the output should be a flat table (excluding items column) regardless of how many grouper arguments are used.

```nushell
> $data | group-by lang year --to-table
╭─#─┬─group_1─┬─group_2─┬────────────items─────────────╮
│ 0 │ rb      │ 2019    │ ╭─#─┬──name──┬─lang─┬─year─╮ │
│   │         │         │ │ 0 │ andres │ rb   │ 2019 │ │
│   │         │         │ ╰─#─┴──name──┴─lang─┴─year─╯ │
│ 1 │ rs      │ 2019    │ ╭─#─┬─name─┬─lang─┬─year─╮   │
│   │         │         │ │ 0 │ jt   │ rs   │ 2019 │   │
│   │         │         │ ╰─#─┴─name─┴─lang─┴─year─╯   │
│ 2 │ rs      │ 2021    │ ╭─#─┬─name──┬─lang─┬─year─╮  │
│   │         │         │ │ 0 │ storm │ rs   │ 2021 │  │
│   │         │         │ ╰─#─┴─name──┴─lang─┴─year─╯  │
╰─#─┴──lang───┴──year───┴────────────items─────────────╯
```

*Note:* The columns will be named after the groupers' string form, and `group{i}` will be used for groupers that can't be stringified (closures).

### Describe alternatives you've considered

_No response_

### Additional context and details

_No response_

### PR DESCRIPTION
**Pull request by Bahex**
- closes #14330 

Related:
- #2607 
- #14019
- #14316 

# Description
This PR changes `group-by` to support grouping by multiple `grouper` arguments.

# Changes

- No grouper: no change in behavior 
- Single grouper
  - `--to-table=false`: no change in behavior
  - `--to-table=true`:
    - closure grouper: named group0
    - cell-path grouper: named after the cell-path
- Multiple groupers:
  - `--to-table=false`: nested groups
  - `--to-table=true`: one column for each grouper argument, followed by the `items` column
    - columns corresponding to cell-paths are named after them
    - columns corresponding to closure groupers are named `group{i}` where `i` is the index of the grouper argument

# Examples
```nushell
> [1 3 1 3 2 1 1] | group-by
╭───┬───────────╮
│   │ ╭───┬───╮ │
│ 1 │ │ 0 │ 1 │ │
│   │ │ 1 │ 1 │ │
│   │ │ 2 │ 1 │ │
│   │ │ 3 │ 1 │ │
│   │ ╰───┴───╯ │
│   │ ╭───┬───╮ │
│ 3 │ │ 0 │ 3 │ │
│   │ │ 1 │ 3 │ │
│   │ ╰───┴───╯ │
│   │ ╭───┬───╮ │
│ 2 │ │ 0 │ 2 │ │
│   │ ╰───┴───╯ │
╰───┴───────────╯

> [1 3 1 3 2 1 1] | group-by --to-table
╭─#─┬─group─┬───items───╮
│ 0 │ 1     │ ╭───┬───╮ │
│   │       │ │ 0 │ 1 │ │
│   │       │ │ 1 │ 1 │ │
│   │       │ │ 2 │ 1 │ │
│   │       │ │ 3 │ 1 │ │
│   │       │ ╰───┴───╯ │
│ 1 │ 3     │ ╭───┬───╮ │
│   │       │ │ 0 │ 3 │ │
│   │       │ │ 1 │ 3 │ │
│   │       │ ╰───┴───╯ │
│ 2 │ 2     │ ╭───┬───╮ │
│   │       │ │ 0 │ 2 │ │
│   │       │ ╰───┴───╯ │
╰─#─┴─group─┴───items───╯

> [1 3 1 3 2 1 1] | group-by { $in >= 2 }
╭───────┬───────────╮
│       │ ╭───┬───╮ │
│ false │ │ 0 │ 1 │ │
│       │ │ 1 │ 1 │ │
│       │ │ 2 │ 1 │ │
│       │ │ 3 │ 1 │ │
│       │ ╰───┴───╯ │
│       │ ╭───┬───╮ │
│ true  │ │ 0 │ 3 │ │
│       │ │ 1 │ 3 │ │
│       │ │ 2 │ 2 │ │
│       │ ╰───┴───╯ │
╰───────┴───────────╯

> [1 3 1 3 2 1 1] | group-by { $in >= 2 } --to-table
╭─#─┬─group0─┬───items───╮
│ 0 │ false  │ ╭───┬───╮ │
│   │        │ │ 0 │ 1 │ │
│   │        │ │ 1 │ 1 │ │
│   │        │ │ 2 │ 1 │ │
│   │        │ │ 3 │ 1 │ │
│   │        │ ╰───┴───╯ │
│ 1 │ true   │ ╭───┬───╮ │
│   │        │ │ 0 │ 3 │ │
│   │        │ │ 1 │ 3 │ │
│   │        │ │ 2 │ 2 │ │
│   │        │ ╰───┴───╯ │
╰─#─┴─group0─┴───items───╯
```

```nushell
let data = [
    [name, lang, year];
    [andres, rb, "2019"],
    [jt, rs, "2019"],
    [storm, rs, "2021"]
]

> $data
╭─#─┬──name──┬─lang─┬─year─╮
│ 0 │ andres │ rb   │ 2019 │
│ 1 │ jt     │ rs   │ 2019 │
│ 2 │ storm  │ rs   │ 2021 │
╰─#─┴──name──┴─lang─┴─year─╯
```

```nushell
> $data | group-by lang
╭────┬──────────────────────────────╮
│    │ ╭─#─┬──name──┬─lang─┬─year─╮ │
│ rb │ │ 0 │ andres │ rb   │ 2019 │ │
│    │ ╰─#─┴──name──┴─lang─┴─year─╯ │
│    │ ╭─#─┬─name──┬─lang─┬─year─╮  │
│ rs │ │ 0 │ jt    │ rs   │ 2019 │  │
│    │ │ 1 │ storm │ rs   │ 2021 │  │
│    │ ╰─#─┴─name──┴─lang─┴─year─╯  │
╰────┴──────────────────────────────╯
```

Group column is now named after the grouper, to allow multiple groupers.
```nushell
> $data | group-by lang --to-table  # column names changed!
╭─#─┬─lang─┬────────────items─────────────╮
│ 0 │ rb   │ ╭─#─┬──name──┬─lang─┬─year─╮ │
│   │      │ │ 0 │ andres │ rb   │ 2019 │ │
│   │      │ ╰─#─┴──name──┴─lang─┴─year─╯ │
│ 1 │ rs   │ ╭─#─┬─name──┬─lang─┬─year─╮  │
│   │      │ │ 0 │ jt    │ rs   │ 2019 │  │
│   │      │ │ 1 │ storm │ rs   │ 2021 │  │
│   │      │ ╰─#─┴─name──┴─lang─┴─year─╯  │
╰─#─┴─lang─┴────────────items─────────────╯
```

Grouping by multiple columns makes finer grained aggregations possible.
```nushell
> $data | group-by lang year --to-table
╭─#─┬─lang─┬─year─┬────────────items─────────────╮
│ 0 │ rb   │ 2019 │ ╭─#─┬──name──┬─lang─┬─year─╮ │
│   │      │      │ │ 0 │ andres │ rb   │ 2019 │ │
│   │      │      │ ╰─#─┴──name──┴─lang─┴─year─╯ │
│ 1 │ rs   │ 2019 │ ╭─#─┬─name─┬─lang─┬─year─╮   │
│   │      │      │ │ 0 │ jt   │ rs   │ 2019 │   │
│   │      │      │ ╰─#─┴─name─┴─lang─┴─year─╯   │
│ 2 │ rs   │ 2021 │ ╭─#─┬─name──┬─lang─┬─year─╮  │
│   │      │      │ │ 0 │ storm │ rs   │ 2021 │  │
│   │      │      │ ╰─#─┴─name──┴─lang─┴─year─╯  │
╰─#─┴─lang─┴─year─┴────────────items─────────────╯
```

Grouping by multiple columns, without `--to-table` returns a nested structure.
This is equivalent to `$data | group-by year | split-by lang`, making `split-by` obsolete.
```nushell
> $data | group-by lang year
╭────┬─────────────────────────────────────────╮
│    │ ╭──────┬──────────────────────────────╮ │
│ rb │ │      │ ╭─#─┬──name──┬─lang─┬─year─╮ │ │
│    │ │ 2019 │ │ 0 │ andres │ rb   │ 2019 │ │ │
│    │ │      │ ╰─#─┴──name──┴─lang─┴─year─╯ │ │
│    │ ╰──────┴──────────────────────────────╯ │
│    │ ╭──────┬─────────────────────────────╮  │
│ rs │ │      │ ╭─#─┬─name─┬─lang─┬─year─╮  │  │
│    │ │ 2019 │ │ 0 │ jt   │ rs   │ 2019 │  │  │
│    │ │      │ ╰─#─┴─name─┴─lang─┴─year─╯  │  │
│    │ │      │ ╭─#─┬─name──┬─lang─┬─year─╮ │  │
│    │ │ 2021 │ │ 0 │ storm │ rs   │ 2021 │ │  │
│    │ │      │ ╰─#─┴─name──┴─lang─┴─year─╯ │  │
│    │ ╰──────┴─────────────────────────────╯  │
╰────┴─────────────────────────────────────────╯
```

From #2607:
> Here's a couple more examples without much explanation. This one shows adding two grouping keys. I'm always wanting to add more columns when using group-by and it just-work:tm: `gb.exe -f movies-2.csv -k 3,2 -s 7 --skip_header`
> 
> ```
>  k:3                   | k:2       | count | sum:7
> -----------------------+-----------+-------+--------------------
>  20th Century Fox      | Drama     | 1     | 117.09
>  20th Century Fox      | Romance   | 1     | 39.66
>  CBS                   | Comedy    | 1     | 77.09
>  Disney                | Animation | 4     | 1264.23
>  Disney                | Comedy    | 4     | 950.27
>  Fox                   | Comedy    | 5     | 661.85
>  Independent           | Comedy    | 7     | 399.07
>  Independent           | Drama     | 4     | 69.75
>  Independent           | Romance   | 7     | 1048.75
>  Independent           | romance   | 1     | 29.37
> ...
> ```

This example can be achieved like this:
```nushell
> open movies-2.csv
  | group-by "Lead Studio" Genre --to-table
  | insert count {get items | length}
  | insert sum { get items."Worldwide Gross" | math sum}
  | reject items
  | sort-by "Lead Studio" Genre
╭─#──┬──────Lead Studio──────┬───Genre───┬─count─┬───sum───╮
│ 0  │ 20th Century Fox      │ Drama     │     1 │  117.09 │
│ 1  │ 20th Century Fox      │ Romance   │     1 │   39.66 │
│ 2  │ CBS                   │ Comedy    │     1 │   77.09 │
│ 3  │ Disney                │ Animation │     4 │ 1264.23 │
│ 4  │ Disney                │ Comedy    │     4 │  950.27 │
│ 5  │ Fox                   │ Comedy    │     5 │  661.85 │
│ 6  │ Fox                   │ comedy    │     1 │   60.72 │
│ 7  │ Independent           │ Comedy    │     7 │  399.07 │
│ 8  │ Independent           │ Drama     │     4 │   69.75 │
│ 9  │ Independent           │ Romance   │     7 │ 1048.75 │
│ 10 │ Independent           │ romance   │     1 │   29.37 │
...
```

### CODE REVIEW

**Comment by fdncred** [comment]
Could you write something up in the release notes for 0.101 to go with this PR when you have time? (i'm not even sure if someone has created the 101 release notes yet)

**Comment by IanManske** [comment]
With the `--to-table` flag, `group-by` should probably return two colums: `group` and `items`. Because currently, the columns can conflict:
```nu
ls | rename items | group-by --to-table items
╭────┬─────────────────────╮
│  # │        items        │
├────┼─────────────────────┤
│  0 │ CITATION.cff        │
│  1 │ CODE_OF_CONDUCT.md  │
│  2 │ CONTRIBUTING.md     │
│  3 │ Cargo.lock          │
│  4 │ Cargo.toml          │
│  5 │ Cross.toml          │
│  6 │ LICENSE             │
│  7 │ README.md           │
│  8 │ SECURITY.md         │
│  9 │ assets              │
│ 10 │ benches             │
│ 11 │ crates              │
│ 12 │ devdocs             │
│ 13 │ docker              │
│ 14 │ rust-toolchain.toml │
│ 15 │ scripts             │
│ 16 │ src                 │
│ 17 │ target              │
│ 18 │ tests               │
│ 19 │ toolkit.nu          │
│ 20 │ typos.toml          │
│ 21 │ wix                 │
╰────┴─────────────────────╯
```

**Comment by Bahex** [comment]
> With the `--to-table` flag, `group-by` should probably return two colums: `group` and `items`. Because currently, the columns can conflict:
> 
> ```nu
> ls | rename items | group-by --to-table items
> ╭────┬─────────────────────╮
> │  # │        items        │
> ├────┼─────────────────────┤
> │  0 │ CITATION.cff        │
> │  1 │ CODE_OF_CONDUCT.md  │
> ...
> ```

@IanManske, thanks for bringing this up, that specific name conflict didn't come to my mind while implementing this, and now I can think of some other (though less likely) cases that can happen when using closures as groupers as well.

I thought of a few ways to solve this, but the most predictable behavior would be to *not use groupers for any kind of column naming*, and just name group columns `group{i}`, same as when using closures to group.

With that change output would be like this.
```nushell
> $data | group-by lang year --to-table
╭─#─┬─group0─┬─group1─┬────────────items─────────────╮
│ 0 │ rb     │ 2019   │ ╭─#─┬──name──┬─lang─┬─year─╮ │
│   │        │        │ │ 0 │ andres │ rb   │ 2019 │ │
│   │        │        │ ╰─#─┴──name──┴─lang─┴─year─╯ │
│ 1 │ rs     │ 2019   │ ╭─#─┬─name─┬─lang─┬─year─╮   │
│   │        │        │ │ 0 │ jt   │ rs   │ 2019 │   │
│   │        │        │ ╰─#─┴─name─┴─lang─┴─year─╯   │
│ 2 │ rs     │ 2021   │ ╭─#─┬─name──┬─lang─┬─year─╮  │
│   │        │        │ │ 0 │ storm │ rs   │ 2021 │  │
│   │        │        │ ╰─#─┴─name──┴─lang─┴─year─╯  │
╰─#─┴─group0─┴─group1─┴────────────items─────────────╯
```

While I find naming the columns after the grouper arguments to be more intuitive, this is the more consistent and predictable way. I'll make a new PR when I'm free.

**Comment by fdncred** [comment]
boo! i'd rather be more intuitive with column names.

**Comment by IanManske** [comment]
Just realized I should have worded my previous comment more clearly. I was thinking that `group-by` should always return two columns. This would get rid of the potential conflict with `items`.
```nu
ls | group-by --to-table { get name | path parse | get extension } { get type }
╭───┬───────────────────┬─────────────────────────────────────────────────────────────╮
│ # │       group       │                            items                            │
├───┼───────────────────┼─────────────────────────────────────────────────────────────┤
│ 0 │ ╭────────┬──────╮ │ ╭───┬─────────────────────┬──────┬─────────┬──────────────╮ │
│   │ │ group0 │ toml │ │ │ # │        name         │ type │  size   │   modified   │ │
│   │ │ group1 │ file │ │ ├───┼─────────────────────┼──────┼─────────┼──────────────┤ │
│   │ ╰────────┴──────╯ │ │ 0 │ Cargo.toml          │ file │ 9.0 KiB │ 4 hours ago  │ │
│   │                   │ │ 1 │ Cross.toml          │ file │   666 B │ 6 months ago │ │
│   │                   │ │ 2 │ rust-toolchain.toml │ file │ 1.1 KiB │ a day ago    │ │
│   │                   │ │ 3 │ typos.toml          │ file │   513 B │ 2 months ago │ │
│   │                   │ ╰───┴─────────────────────┴──────┴─────────┴──────────────╯ │
│ 1 │ ╭────────┬──────╮ │ ╭───┬─────────┬──────┬─────────┬────────────╮               │
│   │ │ group0 │      │ │ │ # │  name   │ type │  size   │  modified  │               │
│   │ │ group1 │ file │ │ ├───┼─────────┼──────┼─────────┼────────────┤               │
│   │ ╰────────┴──────╯ │ │ 0 │ LICENSE │ file │ 1.1 KiB │ a year ago │               │
│   │                   │ ╰───┴─────────┴──────┴─────────┴────────────╯               │
│ 2 │ ╭────────┬─────╮  │ ╭────┬───────────┬──────┬─────────┬──────────────╮          │
│   │ │ group0 │     │  │ │  # │   name    │ type │  size   │   modified   │          │
│   │ │ group1 │ dir │  │ ├────┼───────────┼──────┼─────────┼──────────────┤          │
│   │ ╰────────┴─────╯  │ │  0 │ assets    │ dir  │ 4.0 KiB │ 6 months ago │          │
│   │                   │ │  1 │ benches   │ dir  │ 4.0 KiB │ a day ago    │          │
│   │                   │ │  2 │ crates    │ dir  │ 4.0 KiB │ 3 weeks ago  │          │
│   │                   │ │  3 │ devdocs   │ dir  │ 4.0 KiB │ 2 months ago │          │
│   │                   │ │  4 │ docker    │ dir  │ 4.0 KiB │ a day ago    │          │
│   │                   │ │  5 │ empty_dir │ dir  │ 4.0 KiB │ 3 months ago │          │
│   │                   │ │  6 │ scripts   │ dir  │ 4.0 KiB │ 2 months ago │          │
│   │                   │ │  7 │ src       │ dir  │ 4.0 KiB │ a day ago    │          │
│   │                   │ │  8 │ target    │ dir  │ 4.0 KiB │ 2 months ago │          │
│   │                   │ │  9 │ tests     │ dir  │ 4.0 KiB │ 5 months ago │          │
│   │                   │ │ 10 │ wix       │ dir  │ 4.0 KiB │ 5 months ago │          │
│   │                   │ ╰────┴───────────┴──────┴─────────┴──────────────╯          │
╰───┴───────────────────┴─────────────────────────────────────────────────────────────╯
```

However, this doesn't solve the issue where the column names generated for the closures can conflict with a cell path. Not sure what the best solution is. Some ideas:
- If any closure is provided, change the groups to be lists instead of a records. E.g, `[toml, file]` instead of `{group0: toml, group1: file}`.
- The above might be slightly confusing though (the return structure/type is changed based on arguments). Alternatively, we disallow mixing cell paths and closures, returning record group keys for cell paths and list group keys for closures.
-  When provided a single closure, both of the above create groups keys that are lists of length 1. This seems annoying -- if I provide a single closure, I would expect the group key to be the same as the return value of the closure instead of it being wrapped in a list. So, perhaps we should only allow providing one closure to compute the group key.

So, right now I'm leaning towards only allowing two ways of providing arguments to `group-by`:
```nu
# any number of cell paths
$data | group-by path1 path2 path3.nested
# returns a table with a `group` column and an `items` column. `group` will contain records like:
# { path1: _, path2: _, path3: { nested: _ } }

# one closure
$data | group-by { path parse | get extension }
# returns a table with a `group` and an `items` column. `group` will contain the closure return value,
# in this case, a file extension string.
```

This is nice and simple, but closures and cell paths cannot be mixed. IMO this is fine, since you can use `select` in the closure to choose additional keys using cell paths. I.e., `group-by path1 path2` is shorthand for / equivalent to `group-by { select path1 path2 }`

**Comment by fdncred** [comment]
I'm not a fan of only two columns. It makes it much harder to understand.

**Pull request merged**
