### PR TITLE
REFACTOR: clean the root of the repo

### PR DESCRIPTION
**Pull request by amtoine**
# Description
i've almost always wanted to clean up the root of the repo, so here is my take at it, with some important advice given by @fdncred :relieved: 

- `README.release.txt` is now gone and directly inline in the `release-pkg` script used in the `release` *workflow*
- `build.rs` has been moved to `scripts/` and its path has been changed in [`Cargo.toml`](https://github.com/amtoine/nushell/blob/refactor/clean-root/Cargo.toml#L3) according to the [*Build Scripts* section](https://doc.rust-lang.org/cargo/reference/build-scripts.html#build-scripts) of *The Cargo Book*
- i've merged `images/` into `assets/` and fix the only mention to the GIF in the README
- i've moved the `docs/README.md` inside the main `README.md` as a new [*Configuration* section](https://github.com/amtoine/nushell/tree/refactor/clean-root#configuration)
- the very deprecated `pkg_mgrs/` has been removed
- all the `.nu`, `.sh`, `.ps1` and `.cmd` scripts have been moved to `scripts/`

### things i've left as-is
- all the other `.md` documents
- the configuration files
- all the Rust and core stuff
- `docker/`
- `toolkit.nu`
- the `wix/` diretory which appears to be important for `winget`

# User-Facing Changes
scripts that used to rely on the paths to some of the scripts should now call the scripts inside `scripts/` => i think this for the greater good, it was not pretty nor scalable to have a bunch of scripts in the root of our main `nushell` :scream: 

*i even think we might want to move these scripts outside the main `nushell` repo*
maybe to `nu_scripts` or some other tool :+1: 

# Tests + Formatting
- :green_circle: `toolkit fmt`
- :green_circle: `toolkit clippy`
- :black_circle: `toolkit test`
- :black_circle: `toolkit test stdlib`

# After Submitting
```
$nothing
```

### CODE REVIEW

**Comment by fdncred** [comment]
I see a couple of potential issues.
1. I think the scripts assume you're in the root of the repo when they're executed. So, if you `cd scripts` and run one of them, it'll fail. `register-plugins.nu` works great because it doesn't depend on being in a particular folder. I think the rest will fail from that folder. Of course, if you run them like `.\scripts\install-all.ps1` it works - maybe the others will work like this too?
2. I'm worried with any tampering to release-pkg.nu. What you've done seems good but this CI does not test it. It needs testing somehow. I'm not up for that right now because it's a pain.

I'm generally good with this PR. We just need a story or some instructions about how to run the scripts. Maybe a readme in that folder?

**Comment by amtoine** [comment]
very legit concerns @fdncred 

1. i'll double check the scripts :ok_hand: 
2. `cp -v <file> <dest>` and `<file-content> | save <dest>` should be completely equivalent :thinking: maybe i can try running the CI on my fork and see how it goes?
3. i'll add a little `README` to `scripts/` :+1:

**Comment by amtoine** [comment]
@fdncred 
i've just run the release workflow and it [did work](https://github.com/amtoine/nushell/actions/runs/5022130129) fine :+1: 

i think it's ok to use the inline `README.release.txt` :ok_hand:

**Comment by amtoine** [comment]
i've also fixed the `.sh` and `.nu` scripts and added a little README :yum:

**Review by fdncred — APPROVED** [review]
I can make due with whatever work-around is needed in any other script but my main concern was for release-pkg.nu. So, since that is working. I'm good with this.

**Comment by amtoine** [comment]
let's try this then :relieved: 
we can always revert the CI part if it does not work in the end :muscle:

**Comment by amtoine** [comment]
forgot to merge with the CI tests and the coverage :scream: 
thanks Darren :relieved:

**Pull request merged**
