### PR TITLE
📜 docs(env.nu): add pyenv basic setup for default env.nu

### LINKED ISSUE #5423: How to make pyenv work withnushell?
Hi, thanks for nushell :)

I'm trying to get [pyenv](https://github.com/pyenv/pyenv)1 to work with nushell but no luck so far, I'm having troubles translating the fish / bash to nushell because of the reliance on things like `command` and `eval` for which I found no equivalent in nushell.

Any of you already made it work? If not I'm willing to invest some time on this in the near future.

### PR DESCRIPTION
**Pull request by JackTheMico**
This PR should fix #5423 

# Description

I added two lines at the bottom of the `default_env.nu` file to show how people can make pyenv work by adding the pyenv shims to the `$env.PATH`.
Here's a asciinema recording to show how it work.
[asciicast](https://asciinema.org/a/636181)

# User-Facing Changes

Nothing.

# Tests + Formatting

I have run the `cargo test --workspace` and all tests were passed.

# After Submitting

### CODE REVIEW

**Comment by fdncred** [comment]
Seems to me like this would be better in our documentation repo that in our default_config.nu

**Comment by WindSoilder** [comment]
Yeah I agree, not everyone uses python although I'm happy with the information.

@JackTheMico Would you please add it to documentation repo?

**Comment by JackTheMico** [comment]
@WindSoilder Can you give me a target URL to show me where I should put the information?

**Comment by WindSoilder** [comment]
Sure, I believe this is where you want to put: https://github.com/nushell/nushell.github.io/blob/main/book/configuration.md

And it's relative to this page: https://www.nushell.sh/book/configuration.html

**Pull request closed without merging**
