### PR TITLE
add raw-string literal support

### PR DESCRIPTION
**Pull request by fdncred**
# Description

This PR adds raw string support by using `r#` at the beginning of single quoted strings and `#` at the end.

Notice that escapes do not process, even within single quotes, parentheses don't mean anything, $variables don't mean anything. It's just a string.
```nushell
❯ echo r#'one\ntwo (blah) ($var)'#
one\ntwo (blah) ($var)
```
Notice how they work without `echo` or `print` and how they work without carriage returns.
```nushell
❯ r#'adsfa'#
adsfa
❯ r##"asdfa'@qpejq'##
asdfa'@qpejq
❯ r#'asdfasdfasf
∙ foqwejfqo@'23rfjqf'#
```
They also have a special configurable color in the repl. (use single quotes though)
image

They should work like rust raw literals and allow `r##`, `r###`, `r####`, etc, to help with having one or many `#`'s in the middle of your raw-string.

They should work with `let` as well.

```nushell
r#'some\nraw\nstring'# | str upcase
```

closes https://github.com/nushell/nushell/issues/5091
# User-Facing Changes

# Tests + Formatting

# After Submitting

### CODE REVIEW

**Comment by amtoine** [comment]
> Again, I'm not sure this is helpful because this is kind of what single quotes do now anyway.
>
i vote :+1: because, if you want to single and double quotes in a strings, you are currently forced to escape some of them right now :open_mouth:

**Comment by fdncred** [comment]
@amtoine Good point. This works too.
```nushell
❯ echo r'"""``""dafssa""``"""'
"""``""dafssa""``"""
❯ echo r"'''''''```one\ntwo''' (blah)``` ($var)'"
'''''''```one\ntwo''' (blah)``` ($var)'
```
Right now the requirement is that the raw string start and end with the same single or double quote mark. Backtick quotes aren't part of it.

**Comment by jntrnr** [comment]
Feels like we get a lot of what you're looking for with:
```
`one\ntwo (blah) ($var)`
```

**Comment by fdncred** [comment]
> Feels like we get a lot of what you're looking for with:

@jntrnr agreed. the same with single quotes. it's just more verbose, plus using backticks always makes me thing of bash as "evaluate this". backticks should just be banned altogether, imo. like I said above, I'm not sure if it's helpful or not.

**Comment by fdncred** [comment]
After talking about this, we've decided to close this PR. The best thing about this PR (IMO), that we're going to continue working on, is adding the ability to highlight different types of strings in separate colors. We think this would be a nice QOL repl improvement.

**Comment by hustcer** [comment]
echo a raw string works, however:
```nushel
$> let raw = `one\ntwo (blah) ($var)`
Error: nu::shell::external_command

  × External command failed
   ╭─[entry #12:1:1]
 1 │ let raw = `one\ntwo (blah) ($var)`
   ·           ────────────┬───────────
   ·                       ╰── executable was not found
   ╰────
  help: 系统找不到指定的路径。 (os error 3)
```

> Feels like we get a lot of what you're looking for with:
> 
> ```
> echo `one\ntwo (blah) ($var)`
> ```

**Comment by fdncred** [comment]
Apparently we never did anything with "the best thing about the PR" nor did we answer hustcer's point. I'd still like to see this added as a QOL improvement.

**Comment by hustcer** [comment]
Agreed, we need this feature.

**Comment by fdncred** [comment]
@hustcer I just learned that this works now
```nushell
> let raw = echo `one\ntwo (blah) ($var)`
> $raw
one\ntwo (blah) ($var)
```

**Comment by hustcer** [comment]
> @hustcer I just learned that this works now
> 
> ```nushell
> > let raw = echo `one\ntwo (blah) ($var)`
> > $raw
> one\ntwo (blah) ($var)
> ```

Thanks, still not perfect enough, as:
```nu
# This one works
let raw = echo `one\ntwo (blah) ($var)`
# However, this one doesn't
let raw = `one\ntwo (blah) ($var)`
Error: nu::shell::external_command

  × External command failed
   ╭─[entry #2:1:1]
 1 │ let raw = `one\ntwo (blah) ($var)`
   ·           ────────────┬───────────
   ·                       ╰── executable was not found
   ╰────
  help: 系统找不到指定的路径。 (os error 3)
```

**Comment by blueberrycarrot** [comment]
Raw strings are much needed, would love to see this in the language. Except, can we go all the way and add Rust's `r#` syntax? Reasoning being, the arbitrary amount of `#`s can help with escaping problems in edge cases, and after all, raw strings's primary goal is to avoid escaping problems.

**Comment by fdncred** [comment]
> Raw strings are much needed, would love to see this in the language. Except, can we go all the way and add Rust's `r#` syntax? Reasoning being, the arbitrary amount of `#`s can help with escaping problems in edge cases, and after all, raw strings's primary goal is to avoid escaping problems.

I'd initially be against `#` since it means comment in nushell plus all the nixos crap with `#` scattered throughout. Seems like it would just make it more difficult.

**Comment by blueberrycarrot** [comment]
What about the essence of `#`, which is to make "begin" and "end" markers configurable at the declaration site? Could be something else, for example:

    let rawstring = rFOO"Look, I can use "double quotes"!"FOO

Or, if the user writing the script doesn't care about a custom marker, it can be omitted:

    let rawstring = r"Look, I can use "double quotes"!"

This also intuitively resonates with Bash people that use arbitrary heredoc markers like

    cat <<EOF
    See one coronation and you've seen them all.
    EOF

where `EOF` can be anything. It's certainly more meaningful than Rust's repetition of `#`s.

**Comment by fdncred** [comment]
I tried to update this old PR to the latest main. May have missed some things. One thing that doesn't work is:
```nushell
let a = r"one\ntwo\n (blah) ($var)"
```
I'm not sure `let` ever worked. I can't remember.

**Comment by andrasio** [comment]
> What about the essence of `#`, which is to make "begin" and "end" markers configurable at the declaration site? Could be something else, for example:
> 
> ```
> let rawstring = rFOO"Look, I can use "double quotes"!"FOO
> ```
> 
> Or, if the user writing the script doesn't care about a custom marker, it can be omitted:
> 
> ```
> let rawstring = r"Look, I can use "double quotes"!"
> ```
> 
> This also intuitively resonates with Bash people that use arbitrary heredoc markers like
> 
> ```
> cat <<EOF
> See one coronation and you've seen them all.
> EOF
> ```
> 
> where `EOF` can be anything. It's certainly more meaningful than Rust's repetition of `#`s.

+1 to this and it'd be great if it can support interpolation in it as well.

**Comment by blueberrycarrot** [comment]
> it'd be great if it can support interpolation in it as well.

That's a murky area, as it kind of defeats the purpose of it being a raw string. I know what you mean, and I've been at the receiving end of this: it's both a blessing and annoying at the same time that in Bash, you can use variables in heredoc:

    ssh user@remotehost <<EOF
    echo $myvar # myvar taken from outer script scope
    echo \$myvar # myvar taken from the inner Bash scope (assuming remote host runs Bash)
    EOF

And this `$myvar` and `\$myvar` escaping can be hard to debug and do right. I love-hate it.

What if raw strings were pure raw with no embellishments whatsoever? You could still insert computed values by concatenating raw strings using `+`.

**Comment by fdncred** [comment]
Ugh, this is going to take some surgery. parse_value is not passing the right span to parse_raw_string.

If anyone wants to pick this up and take it over, please volunteer. I doubt I'll work on it.

**Comment by andrasio** [comment]
> > it'd be great if it can support interpolation in it as well.
> 
> That's a murky area, as it kind of defeats the purpose of it being a raw string. I know what you mean, and I've been at the receiving end of this: it's both a blessing and annoying at the same time that in Bash, you can use variables in heredoc:
> 
> ```
> ssh user@remotehost <<EOF
> echo $myvar # myvar taken from outer script scope
> echo \$myvar # myvar taken from the inner Bash scope (assuming remote host runs Bash)
> EOF
> ```
> 
> And this `$myvar` and `\$myvar` escaping can be hard to debug and do right. I love-hate it.
> 
> What if raw strings were pure raw with no embellishments whatsoever? You could still insert computed values by concatenating raw strings using `+`.

The primary reason I'd be interested in having interpolation is heredocs is exactly what I'm looking for! 😅 

Generally for the nu language most of the time I think about them in the sense of modern programming/scripting languages and not syntax or following how things work in things like bash. In programs I've written, heredocs, both with optional delimiter for multiline strings and optionally disable/enable interpolation can be really useful and code easy to read.

So it would be a really welcomed addition IMO. Big fan of [Ruby's heredocs](https://www.rubyguides.com/2018/11/ruby-heredoc/) and I use them a lot and is helpful for other folks reading my code.

**Comment by blueberrycarrot** [comment]
By the way, in Bash you have control over interpolation, where
```
cat <<EOF
echo $PATH
EOF
```
will expand `$PATH` to its value, but
```
cat <<'EOF'
echo $PATH
EOF
```
will not, due to single quotes around `EOF`.

**Comment by sholderbach** [comment]
I like the robustness of the rust like syntax you picked. Makes sense on the parsing side to me. 
Unsure if we really need the separate `Value::RawString` especially now that we have Glob in its own Value

**Comment by fdncred** [comment]
> I like the robustness of the rust like syntax you picked. Makes sense on the parsing side to me. Unsure if we really need the separate `Value::RawString` especially now that we have Glob in its own Value

Thanks. That's encouraging. I think my reasoning behind `Value::RawString` was so that it could be highlighted differently with `SyntaxShape::RawString` but the Value part may not be needed. I'm not really sure how it all works; still waking up and it's been a bit considering I wrote most of this in August. LOL.

@sholderbach Do you happen to know how I can fix `let` to allow `let a = raw_string_syntax`? It's trying to run whatever I assign. I can't seem to figure out where `let a = "normal string"` is, so I can copy/tweak it to make raw-string work.

**Comment by fdncred** [comment]
@WindSoilder I looked through the latest changes and it's looking good!!! I'm still voting to keep `Value::RawString`, `Expr:RawString`, `Type::RawString`, and `SyntaxShape::RawString` for now. What I'd like to see is we continue to move forward and land this shortly after the next release. Then work with it and continue making it better, which I assume that could include removing the raw-string value, expr, and type. My one requirement, other than the base functionality, is to have raw-strings colored distinctly in the repl, which I think means we need to keep the syntax shape.

**Comment by WindSoilder** [comment]
>  I'm still voting to keep Value::RawString, Expr:RawString, Type::RawString, and SyntaxShape::RawString for now

Sure!  I'm ok with it, I can try to look into it and remove these `RawString` things, and still make it colored distinctly in the repl.

**Comment by IanManske** [comment]
If I understand correctly,
- backticked strings can't contain backticks and also cannot be used with `let` without `echo`.
- single quoted strings can't contain single quotes.

Meaning that these string types aren't fully raw strings. So, this PR adds raw strings (`r##`) with variable number of `#` to be able to enclose any string.

But I'm totally convinced about this approach. My two objections:
- The syntax is a little inconsistent:
  - Normal double quoted strings allow c-style backslash escapes. The proposed raw string syntax also uses double quotes but does not respect backslash escapes. This is potentially confusing, so I think it would be better to use single quotes (i.e., `r#''#`).
  - Like @fdncred mentioned, `#` are already used for comments, so it's a little weird to also use them for the raw string syntax. This makes sense in Rust, since backlashes are used for comments, so there's no existing conflict.
- Single quoted strings are already 90% of the way to being raw strings. Rather than adding yet another new string syntax, I think it makes sense to extend single quoted strings in some way. For example, like how this PR allows any number of `#`, we could allow single quotes strings to start with any number of single quotes: `'''This can contain 'single quoted strings' or ''doubly single quoted strings'''''`.

**Comment by fdncred** [comment]
> Meaning that these string types aren't fully raw strings. So, this PR adds raw strings (r##) with variable number of # to be able to enclose any string.

Slight correction here. It should work like rust used to with `r#` and `#`. If there are one or more `#`'s in the raw string, you have to do `r##` and `##` depending on the number of `#`s in the raw-string literal.

> Normal double quoted strings allow c-style backslash escapes.

When I originally wrote it, I allowed single quotes, double quotes, and backtick quotes. I simplified to double quote. I chose double because it's what most people are familiar with. I could be talked into only supporting single quotes without processing escapes, essentially the same way it works now but with single quotes instead of double quotes.

> Like @fdncred mentioned, # are already used for comments, so it's a little weird to also use them for the raw string syntax. This makes sense in Rust, since backlashes are used for comments, so there's no existing conflict.

I picked a char. I originally had `@`. I'm not going to lose sleep over whatever character is used. In the end I chose `#` because of Rust.

> Single quoted strings are already 90% of the way to being raw strings.

Agree to Disagree. They're maybe 50% there. Same with backticks. I still vote for having something separate that is less like Python and more like Rust.

**Comment by fdncred** [comment]
@IanManske what about this compromise? 
- Begin `r@`
- End `@`
- Increase `@` to escape at signs in the string 
- Only works on single quotes

**Comment by IanManske** [comment]
@fdncred Yeah, that sounds good. Although, I think the `r` might be unnecessary. Languages like Rust and Python always process escape sequences in strings, so the `r` indicates that escape sequences should be ignored in these languages. Our single quoted strings already have this behavior, so I think it's best to not have the `r` in our raw string syntax.

I wouldn't mind making the necessary changes to implement this.

**Comment by IanManske** [comment]
> I kind of always considered the `r` as meaning, "this is going to be a raw-string". So, my preference would be to keep it. 

Right, my point is that single quotes already mean "raw string", so there's no need to have double the indication. The `@`'s also mean "raw string", so it's actually triple indication XD

> Plus, I think `@'string'@` is weirder looking that `r@'string'@`.

Not sure I follow, it's a single character difference :sweat_smile: . If anything, the extra `r` at the start makes it look unbalanced. I think it's a matter of getting used to it. This is similar to how Swift does raw strings `#"raw 'text' here"#`, but just with the `#` with replaced `@`.

> If you want to make these changes in my compromise note above, please feel free.

Will do :smile:

**Comment by WindSoilder** [comment]
It should closes:  #5091

**Comment by sholderbach** [comment]
A small concern I have with the `r@""@` syntax is that it has an overlap with the custom completer passing syntax. Might not manifest right now but worth checking or considering if overloading the `@` sigil is worth it for the raw strings.

`def test [my_arg: number@"my func"]` is a valid way to specify a custom completer, as we strip quotes for quoted function names. This shares the `r@"` prefix.

**Comment by fdncred** [comment]
We can always pick another symbol like `!`. @IanManske @WindSoilder what are your thoughts on Stefan's comment?

```nushell
echo r!'one\ntwo (blah) ($var)'!
```

**Comment by IanManske** [comment]
Since we don't allow spaces in the customer completer sytnax, e.g.,
```nushell
def cmd [arg: string @ options] {} # this is a command with three positional parameters
```
So, there shouldn't be any issues distinguishing between the two.

Then again, it could look confusing/inconsistent:
```nushell
def cmd [arg: string@'options'] {} # almost looks like `r@''@`
```
So, I would also be fine with changing the symbol/syntax.

**Comment by sholderbach** [comment]
As we should be parsimonous with the available special sauce characters, and have something as identifiable as possible for the users, among the options I prefer the Rust-like raw strings
- `r#"raw like rust"#`, familiar to Rust users. `#` already associated with quoting as a comment, comments already enforce that you have a space before the `#` so no conflict when provided with `r#` and `"#` (or was there a deeper problem you identified during torture testing), (small partial conflict with unquoted `nix` `#` specs may need to be ruled out.)
- `r@"raw but Anders"@` I think the `@` read as `at` may be useful to preserve for the completers or general future evolution as a type operator.
- `@"is this C# verbatim?"@` - character soup to me
- `r!"..."!` uses up a so far unused special char that we don't have available for future endeavours into syntax (even though I would advise against using more sigils for strings and only use special prefix chars or names with a mnemonic like `r(aw)-string` for future string additons)

**Comment by WindSoilder** [comment]
To be honest, I don't think it's a big issue, because we only use raw string outside of function signature, and custom completer only exists inside function signature.  They don't have overlap inside the same space.

C# using @ in various places: https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/tokens/verbatim

**Comment by fdncred** [comment]
My personal favorite is still prefix: `r#` suffix: `#`. I was trying to compromise with Ian.

I think the point about double quotes vs single quotes is probably a good one, so I'm good with single quotes.

I spent 20+ years writing C# but I still like `r#'raw-string'#` best. Maybe we should talk about it Wednesday.

**Comment by IanManske** [comment]
> Maybe we should talk about it Wednesday.

Yeah, sounds good.

Just to reiterate my point, I sympathize with the fact that `r#"raw like rust"#` is familiar to Rust users, but  I'm not sure if this syntax fits in language. IMO it looks too much like a comment.
```nushell
let a = dir #"this is a comment"
let b = r#"this is a raw string"#
```
Had I not know that comments required a preceding space (I just learned that now lol), then I would have assumed that `let b = ...` had a comment. I'm trying to look at this from the perspective of a new user where they may have seen many examples of comments in action and learned that `#` means ignore the rest of the line. The `r#""#` syntax breaks this assumption and may come as a surprise to some.

The `r@''@` syntax has a similar problem, since it's similar to our completion syntax. As @WindSoilder said, they aren't used in the same context, so it's slightly better. Then again, Stefan makes a good point that we may want to reserve or extend the `@` sign for other uses in the future.

So now I'm leaning towards `r!'...'!` of all things :sweat_smile: (or some other symbol).

**Comment by fdncred** [comment]
@WindSoilder can we change this one more time to `r#'raw-string'#`?  so `r#` prefix, `#` suffix, and single quotes only.

**Comment by YizhePKU** [comment]
I noticed that even though we've added `Expr::RawString`, I'm still getting `Expr::String` from `run_external`. Is this normal?

Here's the output of `dbg!(call)` from `run_external`. I typed `^ls r#'foo bar'#` into the shell.
```
[crates\nu-command\src\system\run_external.rs:50:9] call = Call {
    decl_id: 0,
    head: Span {
        start: 123381,
        end: 123383,
    },
    arguments: [
        Positional(
            Expression {
                expr: String(
                    "ls",
                ),
                span: Span {
                    start: 123381,
                    end: 123383,
                },
                ty: String,
                custom_completion: None,
            },
        ),
        Positional(
            Expression {
                expr: String(
                    "r#'foo bar'#",
                ),
                span: Span {
                    start: 123384,
                    end: 123396,
                },
                ty: String,
                custom_completion: None,
            },
        ),
    ],
    parser_info: {},
}
```

**Comment by rgwood** [comment]
This is a great feature. Thanks all!

**Pull request merged**
