### PR TITLE
Patch after fix after fix 7380

### PR DESCRIPTION
**Pull request by zhiburt**
> I'm not sure how i feel about that. I mean if there are a lot of columns, it should probably have a max width so 1 column doesn't take the entire width of your screen. Ideally it would work closely like table worked before we migrated to tabled, as far as how column widths were allocated.

I believe it still not completely matched.
*To be honest I am not against the #7446 approach.

The PR makes a switch between logics on a premise of `termwidth`.
So if `termwidth > 120` we start prioritizing amount of columns we can show (We try to show as many columns as we can).
Otherwise we do what I've described in #7446 (We show the least columns but with least truncation involvement).

In case it's OK,
I guess we could make the value configurable.

cc @fdncred 
ref #7446

### CODE REVIEW

**Comment by zhiburt** [comment]
(Just in case) You can see the differens here

https://github.com/nushell/nushell/blob/57719fd7baa685b577448aa5e82f64c7c5b43f94/crates/nu-table/tests/constrains.rs#L196-L197

**Comment by fdncred** [comment]
I think this looks much better.

Short mode
Screenshot 2022-12-17 at 12 06 28 PM

Long mode
Screenshot 2022-12-17 at 12 07 02 PM

@zhiburt if you can fix the conflicts we can land this one too.

**Comment by fdncred** [comment]
thank you very much!

**Comment by rgwood** [comment]
A very small bug report: after this change, interrupting a `ListStream` with `ctrl+c` now incorrectly reports "Couldn't fit table into X columns!":

```bash
〉ls | each {|f| sleep 1000ms; $f}
^CCouldn't fit table into 133 columns!
```

We might want to check `ctrl+c` like this: https://github.com/nushell/nushell/blob/28123841baf30124feb41c44c471ce74e6963d57/crates/nu-command/src/viewers/table.rs#L315-L321

**Pull request merged**
