### PR TITLE
Add custom datetime format through `strftime` strings

### PR DESCRIPTION
**Pull request by fnordpig**
- improves usability of datetime's in displayed text
- 
# Description
Creates a config point for specifying long / short date time formats.  Defaults to humanized as we have today.

Provides for adding strftime formats into config.nu such as:
```nu
  datetime_format: {
    normal: "%Y-%m-%d %H:%M:%S"
    table: "%Y-%m-%d"
  }
```

Example:
```bash
> $env.config.datetime_format                                                                                                                         
┏━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━┓
┃ normal ┃ %a, %d %b %Y %H:%M:%S %z ┃
┃ table  ┃ %m/%d/%y %I:%M:%S%p      ┃
┗━━━━━━━━┻━━━━━━━━━━━━━━━━━━━━━━━━━━┛
> let a = (date now)                                                                                                                                  
> echo $a                                                                                                                                             
Thu, 22 Jun 2023 10:21:23 -0700
> echo [$a]                                                                                                                                           
┏━━━┳━━━━━━━━━━━━━━━━━━━━━┓
┃ 0 ┃ 06/22/23 10:21:23AM ┃
┗━━━┻━━━━━━━━━━━━━━━━━━━━━┛
```

# User-Facing Changes
Any place converting a datetime to a user displayed value should be impacted.

# Tests + Formatting

- `cargo fmt --all -- --check` Done
- `cargo clippy --workspace -- -D warnings -D clippy::unwrap_used -A clippy::needless_collect -A clippy::result_large_err` Done
- `cargo test --workspace` Done 
- `cargo run -- crates/nu-std/tests/run.nu` Not done - doesn't seem to work 

```bash
> use toolkit.nu  # or use an `env_change` hook to activate it automatically
> toolkit check pr
``` - Done

### CODE REVIEW

**Comment by fnordpig** [comment]
I don't really understand what test is failing above - looks like some sort of virtualenv test?

**Comment by fdncred** [comment]
> I don't really understand what test is failing above - looks like some sort of virtualenv test?

The venv issue is not related to your PR. It's crashing everyone's PR. We're trying to look into it.

**Comment by fdncred** [comment]
If we move forward with this PR we'll need the config point in the default_config.nu file with comments that help explain how to set the values.

**Comment by fnordpig** [comment]
> If we move forward with this PR we'll need the config point in the default_config.nu file with comments that help explain how to set the values.
> 
> I put this in my config. Is this appropriate?
> 
> ```
>   datetime_format: {
>     normal: "%Y-%m-%d %H:%M:%S"
>     abbreviated: "%Y-%m-%d"
>   }
> ```
> 

Yep that's precisely right!  I'll add the default_config.nu changes to this PR

> I'm not sure where `normal` and `abbreviated` show up in nushell. Any ideas?

Normal shows up wherever value.into_string/nonerror_into_string are called - it's a bit of a nest, because value::record/lazyrecord/list also defer to these types so it's tough for me to understand everywhere it shows up.  I wish I had a better answer than that...

**Comment by fnordpig** [comment]
> > I'm not sure where `normal` and `abbreviated` show up in nushell. Any ideas?
> 
> Normal shows up wherever value.into_string/nonerror_into_string are called - it's a bit of a nest, because value::record/lazyrecord/list also defer to these types so it's tough for me to understand everywhere it shows up. I wish I had a better answer than that...

So, normal shows up if you do something like:
```bash
let a = (date now)
echo $a
```

Abbreviated appears to be generally when rendering a table that tries to fit on the screen.

**Comment by fnordpig** [comment]
Added default_config.nu

**Comment by sholderbach** [comment]
I am gonna be the pedantic party pooper for just a moment:

Can you update your PR description and title to make clear what changes and how one can use it, as soon as your design is ready for review. Both to help folks that want to play with it before it gets merged and also to have a good record in the commit history. Furthermore good examples in the PR descriptions make the life so much easier when we have to compile the release notes.

**Comment by fdncred** [comment]
I have one more request, instead of "normal" and "abbreviated" can we have "normal" and "ls" (or maybe "table")? I understand where abbreviated came from but I think it would be more intuitive for future users to intuitively understand which one shows up in `ls`.

**Comment by amtoine** [comment]
i think this should solve #8549, can you confirm that @fnordpig? :yum:

**Review by amtoine — CHANGES_REQUESTED** [review]
to wrap this up by a review :relieved: 

i love the feature, it looks great thanks @fnordpig :partying_face: 

i agree with the remarks of @fdncred and @sholderbach, and i'll approve this with great pleasure once
- [x] the `default_config.nu` has been upated
- [ ] the PR description has been completed with what the changes do and examples
- [ ] change the name of the config items

**Comment by fnordpig** [comment]
>     * [x]  the `default_config.nu` has been upated
> 
>     * [x]  the PR description has been completed with what the changes do and examples
> 
>     * [x]  change the name of the config items
> 
>     * [x]  the linked issue ([into datetime  only gets last part of date in output when on list/table #8549](https://github.com/nushell/nushell/issues/8549)) has been confirmed to be solved by this PR

I can confirm, it does resolve this.  Obviously you have to do something like this:

```bash
> let-env config = ($env.config | upsert datetime_format.table '%m/%d/%y')                                                                             > [1649203200000000000,1649289600000000000] | into datetime                                                                                            ┏━━━┳━━━━━━━━━━┓
┃ 0 ┃ 04/06/22 ┃
┃ 1 ┃ 04/07/22 ┃
┗━━━┻━━━━━━━━━━┛
```

But assuming that's sufficient, it does indeed work.

**Review by fdncred — APPROVED** [review]
Thanks for making the changes I requested. I'm ready.

**Comment by fdncred** [comment]
I went ahead and made one change to the default_config.nu. Since this is the config file that most people start nushell with, I thought it was appropriate to leave our default human readable datetime in place. So, I left the `table:` setting in there but commented it out for people to experiment. Hope that's ok.

This is what I changed.
```
  datetime_format: {
    normal: '%a, %d %b %Y %H:%M:%S %z'  # shows up in displays of variables or other datetime's outside of tables
    # table: '%m/%d/%y %I:%M:%S%p'        # generally shows up in tabular outputs such as ls
  }
```

Also, I'm not sure the default is appropriate for locales that use day/month/year vs month/day/year.

**Comment by fdncred** [comment]
sorry, i broke your PR by landing another PR. would you mind fixing the merge conflicts?

**Comment by fnordpig** [comment]
Gah I've gotten into some sort of git hell

**Comment by fdncred** [comment]
been there, done that. don't worry too much about the amount of commits as they are all squashed anyway.

**Comment by fnordpig** [comment]
Ok I seem to have navigated git hell successfully

**Comment by fdncred** [comment]
nice work, just some small fmt-clippy items to deal with and it should be good.

**Comment by fnordpig** [comment]
Doh, merge artifacts.  Fixed.

**Comment by fdncred** [comment]
Thanks!

**Comment by amtoine** [comment]
this is really quite cool, thanks @fnordpig :ok_hand:

**Pull request merged**
