### PR TITLE
Custom canonicalize method on Filesystem Shell. 

### LINKED ISSUE #1484: Bug on moving to previous directory after deleting current directory
So I am in a directory called `bar` inside another directory called `foo` and the pwd is `~/home/foo/bar`

If I delete `bar` while in the same directory I cannot change the directory to `foo` using `cd ..`

### PR DESCRIPTION
**Pull request by quebin31**
Added a new canonicalize custom method for Filesystem Shell, this method prepares path for dunce::canonicalize. Fixes #1484

### CODE REVIEW

**Comment by jonathandturner** [comment]
This looks good. Would you also be able to create a test to make sure this keeps working in the future?

**Comment by quebin31** [comment]
> This looks good. Would you also be able to create a test to make sure this keeps working in the future?

Sure, placed on `filesystem_shell.rs`?

**Comment by jonathandturner** [comment]
@quebin31 - that sounds good

**Comment by quebin31** [comment]
@jonathandturner I have created the test, I guess it should be enough?

**Comment by jonathandturner** [comment]
Looks good!

**Pull request merged**
