### PR TITLE
Replace all instances of 'column path' in `help` messages with 'cell path'

### PR DESCRIPTION
**Pull request by webbedspace**
# Description

Replaces all instances of 'column path' in `help` messages with 'cell path'

Reasons why:
* Cell path is already accepted terminology for this feature in [the Nushell docs](https://www.nushell.sh/book/types_of_data.html#cell-paths)
* Cell paths can also take row indexes (among complex paths like `a.0.b`)
* Cell paths can work on lists (by simply beginning with row indexes)
* "Column path" suggests it only works on tables and not records

This also (in passing) fixes a shocking number of help strings which until now were just flat-out incorrect. For example, `path` subcommands say they accept cell paths, but actually only operate on column names with no extra qualification.

# Major Changes

If you're considering making any major change to nushell, before starting work on it, seek feedback from regular contributors and get approval for the idea from the core team either on [Discord](https://discordapp.com/invite/NtAbbGn) or [GitHub issue](https://github.com/nushell/nushell/issues/new/choose).
Making sure we're all on board with the change saves everybody's time.
Thanks!

# Tests + Formatting

Make sure you've done the following, if applicable:

- Add tests that cover your changes (either in the command examples, the crate/tests folder, or in the /tests folder)
  - Try to think about corner cases and various ways how your changes could break. Cover those in the tests

Make sure you've run and fixed any issues with these commands:

- `cargo fmt --all -- --check` to check standard code formatting (`cargo fmt --all` applies these changes)
- `cargo clippy --workspace --features=extra -- -D warnings -D clippy::unwrap_used -A clippy::needless_collect` to check that you're using the standard code style
- `cargo test --workspace --features=extra` to check that all tests pass

# After Submitting

* Help us keep the docs up to date: If your PR affects the user experience of Nushell (adding/removing a command, changing an input/output type, etc.), make sure the changes are reflected in the documentation (https://github.com/nushell/nushell.github.io) after the PR is merged.

### CODE REVIEW

**Comment by fdncred** [comment]
Good catch. Apparently we didn't notice all this when we renamed column path to cell path.

**Comment by dandavison** [comment]
Hi @webbedspace just a heads-up -- #6796 also makes lots of changes to command files. It looks like they don't conflict _too_ badly, but I just wanted to point it out in case you were making others.

**Comment by webbedspace** [comment]
Thanks.

**Comment by dandavison** [comment]
Thanks for doing this -- I'd noticed it too and this is a big improvement.

**Comment by jntrnr** [comment]
This is a good change. We'll land this when conflicts are resolved and the tests are green.

**Comment by rgwood** [comment]
Nice, thanks. Really appreciate the effort you’re putting in to make Nu more consistent and well-documented.

**Pull request merged**
