### PR TITLE
Initial attempt at prompt customization

### PR DESCRIPTION
**Pull request by djc**
This implements most of the design outlined in #356. I realized that we might to somehow add something like control flow so that for example if you have the `{vcs_branch}` you can add a space before or after it only if a `vcs_branch` is actually being rendered. Not sure what the syntax for that should look like, any suggestions?

Some issues I'm having:

* Colors aren't being rendered correctly, which seems weird
* Even before I started working, the prompt shows up green, but not sure where that's from
* Somehow the last characters of the prompt are being eaten

If someone knows more about how these bits fit together, that would be great.

### CODE REVIEW

**Comment by djc** [comment]
Not right now -- was hoping someone might have some insight on how those pieces fit together so I have some clues before I start digging.

**Comment by jonathandturner** [comment]
I'll take a look

**Comment by jonathandturner** [comment]
Some thoughts on the approach:

In looking at this, we're going to need a more full-featured parsing story.  One example I tripped over was just setting my prompt to ">", but that caused the parser to have issues. We may want to integrate with something like `nom`, which Nu already uses, and build up the prompt grammar as something nom will parse for us.

Parsing should give us a tree and then we should render the tree as a colored prompt. Right now, there is coloring going on inside of the parse, which makes it difficult to debug (and would make it difficult to later extend)

**Comment by djc** [comment]
Thanks for the review!

I agree about the need for a full-fledged parser. I wasn't aware nu already depended on nom, or I would have used it. Will rewrite the parser based on nom.

I disagree with your characterization that there's coloring going on inside the parse -- it just uses types from `cross-term` as part of the AST which is convenient. IMO an invalid color name should probably result in an error at parse time.

Did you manage to reproduce/find out anything about the issues with eating the final characters?

**Comment by jonathandturner** [comment]
@djc - I only got far enough in to see this approach would need a rewrite around the parse, sorry.

**Comment by jonathandturner** [comment]
For your other point, my rule of thumb with validation is that you parse first, then validate, then transform. If you try to do too much at once, the code becomes really difficult to understand.

**Comment by jonathandturner** [comment]
@djc still interested in working on customizing prompts?

**Comment by ubsan** [comment]
I think this is a really odd way of implementing prompts -- imo, requiring prompt parsing is an issue. Powershell does this with a function which returns a string, and I think that's the best solution. If you want colorization, you could do an array of

```
let type base =
  | string
  | { color: string, text: string }
in
let type prompt =
  | base
  | base[]
in
let type t =
  | prompt
  | { left: prompt, right: prompt }
```

(or you could simplify by removing left-prompt and right-prompt, but the point is it's extensible backwards compatibly)

**Comment by jonathandturner** [comment]
@ubsan - Since we don't have functions, yet, we could opt to evolve the prompt customization. The first version could be more like what @djc shows, with a string bit that's parsed. As we grow more support in Nu, we could look at moving it to being more structured, like a block that's executed.

**Comment by djc** [comment]
@jonathandturner let's say I'm still interested in getting a customized prompt for myself (I consider this blocking for myself to actually start using nushell in earnest), I would certainly not mind if someone else wants to pick up the work. Unfortunately the response to this PR so far has somewhat deflated my motivation to continue on it.

**Comment by ubsan** [comment]
@jonathandturner I really dislike adding any parsing to the shell for purposes of prompt customization, because it seems like a back-compat minefield

**Comment by jonathandturner** [comment]
@djc - it may make sense to close this PR and wait for string interpolation to land (which hopefully is in the next couple weeks).  Once that's in, the logic you were planning with config should be able to work with the feature in nu to build the prompts.

**Comment by djc** [comment]
Is there some tracking issue and/or documentation for what string interpolation?

**Comment by jonathandturner** [comment]
@djc sorry for the slow reply - not sure why I didn't see this pop up.

We don't have string interpolation support yet, but it's something we'd like to add as we add features to Nu.  It would be something like "${user}:${path}" and then Nu would be able to fill in those spots for you.

How exactly that was going to work I think we need to experiment.

**Comment by jonathandturner** [comment]
For now, we'll close this in favor of https://github.com/nushell/nushell/pull/970

We may want a simpler configurable prompt too, which can build off the string interpolation that we started for `format`. If you're interested, let's create a new PR for that.

**Pull request closed without merging**
