### PR TITLE
Add `exec` command for Windows

### PR DESCRIPTION
**Pull request by IanManske**
# Description
Based of the work and discussion in #10844, this PR adds the `exec` command for Windows. This is done by simply spawning a `std::process::Command` and then immediately exiting via `std::process::exit` once the child process is finished. The child process's exit code is passed to `exit`.

# User-Facing Changes
The `exec` command is now available on Windows, and there should be no change in behaviour for Unix systems.

### CODE REVIEW

**Comment by fdncred** [comment]
Seems to be working great! I closed my PR after testing this.

**Comment by IanManske** [comment]
I think it's good to go. The only thing left is that I'm not sure how we want to word the `exec` command `usage` and `extra_usage`.

**Comment by fdncred** [comment]
Oh, ya. How about....
```
Execute a command, replacing or spawning the current process, depending on architecture.
```

```
On Unix-based systems exec will replace the current process. On Windows based systems exec will spawn a new process.
```

Something like that. Feel free to reword.

**Comment by fdncred** [comment]
Wording is good. I plan on landing this when the CI is green. Thanks for your help!

**Comment by IanManske** [comment]
You're welcome, glad to help!

**Pull request merged**
