### PR TITLE
Initial implementation of the random decimal subcommand.

### PR DESCRIPTION
**Pull request by smaydew**
Initial implementation of the random decimal sub-command.

### CODE REVIEW

**Comment by jonathandturner** [comment]
@smaydew - you'll need to merge main into your branch and try again. I had to fix a few things that came up with the new Rust 1.48 release

**Comment by kubouch** [comment]
Random decimals are cool! However, have you considered having default range 0..1 instead of unrestricted? That would make the subcommand without argument more useful.

**Comment by smaydew** [comment]
> Random decimals are cool! However, have you considered having default range 0..1 instead of unrestricted? That would make the subcommand without argument more useful. Just a suggestion.

That's a good idea. The unrestricted values are coming out pretty useless. I'll put that into another PR.

**Comment by smaydew** [comment]
Going to close this PR in favor of the next one which will have a change to make the default value more useful.

**Comment by kubouch** [comment]
I think you could just push another commit into this PR instead of making a new one.

**Comment by smaydew** [comment]
I just submitted the new one. I'm kind of a newbie when it comes to the github flow and wasn't sure if I could modify a commit after the PR had been created.

**Comment by kubouch** [comment]
Yes, you can, thee commits will appear here, it's quite common to do so.

**Comment by smaydew** [comment]
So if I would have committed the changes to the branch in this PR, this pipeline would re-run and pickup the new commit and comment(s)?

**Comment by kubouch** [comment]
Exactly. You can check other PRs, they usually have a bunch of commits there. Also, in case main branch gets updated after you create the PR, you can rebase on the updated main and force push into the PR branch -- that way you ensure your changes are built on top of the newest main branch commit.

**Pull request closed without merging**
