### PR TITLE
Respect `use_ansi_coloring` setting in `banner`

### PR DESCRIPTION
**Pull request by NotTheDr01ds**
# Description

Partial fix for #14043 - If `$env.config.use_ansi_coloring` is `false`, strip the ansi coloring before displaying.

# User-Facing Changes

Bug fix

# Tests + Formatting

- :green_circle: `toolkit fmt`
- :green_circle: `toolkit clippy`
- :green_circle: `toolkit test`
- :green_circle: `toolkit test stdlib`

# After Submitting

N/A

### CODE REVIEW

**Comment by fdncred** [comment]
Thanks for working on this!

**Comment by NotTheDr01ds** [comment]
Thanks - It would have been a 5 minute fix if not for the failing tests, which makes no sense given the minimal change.

**Comment by NotTheDr01ds** [comment]
Updating tests next - Local test failed for a completely unrelated reason.

**Comment by NotTheDr01ds** [comment]
Would have been a 5 minute fix had I just got remembered the *second* `?` ;-)

**Comment by fdncred** [comment]
Thanks again.

**Pull request merged**
