### PR TITLE
added documentation for no_auto_pivot

### PR DESCRIPTION
**Pull request by Samboy218**
completes #1826

### CODE REVIEW

**Comment by Samboy218** [comment]
associated PR for the book: https://github.com/nushell/book/pull/96

**Comment by thegedge** [comment]
@Samboy218 looks like you'll need to rebase on master to fix the errors 🙂

**Comment by thegedge** [comment]
Looks like you lost all of the changes, @Samboy218. Try this:

```
git co issue-1826
git reset --hard 8026cd9
git rebase master
```

**Comment by Samboy218** [comment]
I'm not great with git, thanks for bearing with me.
this was my process, maybe you can see where i went wrong
```
git checkout master
git remote add upstream https://github.com/nushell/nushell.git
git fetch upstream
git rebase upstream/master
git checkout issue-1826
git rebase origin/master
```
I also pushed master and issue-1628 after this

after `git rebase upstream master` I got `Successfully rebased and updated refs/heads/master`, which sounds good. Then after `git rebase origin master` on issue-1628 I got `Current branch issue-1826 is up to date.`

**Comment by thegedge** [comment]
Ahh, I'm guessing your `origin` remote is actually pointing at your fork.

Perhaps you want to `git rebase upstream/master`?

**Comment by thegedge** [comment]
There's another approach to this if you're not able to get a `git rebase` working:

Since it's a one commit kind of change, you could `git reset --hard upstream/master` on your current branch and then `git cherry-pick 8026cd9` (the commit with your changes in it).

If you're having trouble with it, I don't mind doing the rebase for you 🙂

**Comment by Samboy218** [comment]
you're a wizard @thegedge 
thank you so much!

**Comment by thegedge** [comment]
🙌 let's get this one in 🙂

**Pull request merged**
