### PR TITLE
Plugin: Add benchmark for different encoding protocol

### PR DESCRIPTION
**Pull request by WindSoilder**
# Description

The benchmark can help us make decision on plugin protocol decision

Currently, my benchmark(just estimate by runtime) result is:
1. msgpack is better for data with larger size, capnp is better for smaller size.
2. they are both better than json

# Tests

Make sure you've done the following:

- [X] Add tests that cover your changes, either in the command examples, the crate/tests folder, or in the /tests folder.
- [X] Try to think about corner cases and various ways how your changes could break. Cover them with tests.
- [X] If adding tests is not possible, please document in the PR body a minimal example with steps on how to reproduce so one can verify your change works.

Make sure you've run and fixed any issues with these commands:

- [X] `cargo fmt --all -- --check` to check standard code formatting (`cargo fmt --all` applies these changes)
- [X] `cargo clippy --workspace --features=extra -- -D warnings -D clippy::unwrap_used -A clippy::needless_collect` to check that you're using the standard code style
- [X] `cargo test --workspace --features=extra` to check that all the tests pass

### CODE REVIEW

**Comment by fdncred** [comment]
@WindSoilder What I was going for was a chart that has all 3 graphed together per test like this example shows https://bheisler.github.io/criterion.rs/book/user_guide/comparing_functions.html. Do you think that's possible? I was trying to do that myself and just couldn't get it to work right. I'm not sure what I'm doing wrong.

**Comment by fdncred** [comment]
for what it's worth, this was my latest attempt that still doesn't do exactly what I wanted.
```rust
use criterion::{criterion_group, criterion_main, BenchmarkId, Criterion};
use nu_plugin::{protocol::PluginResponse, EncodingType};
use nu_protocol::{Span, Value};
use std::time::Duration;

// generate a new table data with `row_cnt` rows, `col_cnt` columns.
fn new_test_data(row_cnt: usize, col_cnt: usize) -> Value {
    let columns: Vec<String> = (0..col_cnt).map(|x| format!("col_{x}")).collect();
    let vals: Vec<Value> = (0..col_cnt as i64).map(|i| Value::test_int(i)).collect();

    Value::List {
        vals: (0..row_cnt)
            .map(|_| Value::test_record(columns.clone(), vals.clone()))
            .collect(),
        span: Span::test_data(),
    }
}

fn run_encode_benchmark(fmt: &str, row_cnt: usize, col_cnt: usize) {
    let encoder = EncodingType::try_from_bytes(fmt.as_bytes()).unwrap();
    let mut res = vec![];
    let test_data = PluginResponse::Value(Box::new(new_test_data(row_cnt, col_cnt)));
    let _ = encoder.encode_response(&test_data, &mut res);
}

fn run_decode_benchmark(fmt: &str, row_cnt: usize, col_cnt: usize) {
    let encoder = EncodingType::try_from_bytes(fmt.as_bytes()).unwrap();
    let mut res = vec![];
    let test_data = PluginResponse::Value(Box::new(new_test_data(row_cnt, col_cnt)));
    encoder.encode_response(&test_data, &mut res).unwrap();
    let mut binary_data = std::io::Cursor::new(res);
    binary_data.set_position(0);
    let _ = encoder.decode_response(&mut binary_data);
}

fn encode_with_param(fmt: &str, row_cnt: usize, col_cnt: usize) {
    run_encode_benchmark(fmt, row_cnt, col_cnt);
}

fn decode_with_param(fmt: &str, row_cnt: usize, col_cnt: usize) {
    run_decode_benchmark(fmt, row_cnt, col_cnt);
}

fn bench_plugin_protocols(c: &mut Criterion) {
    let test_cnt_pairs = [
        (100, 5),
        (100, 10),
        (100, 15),
        (1000, 5),
        (1000, 10),
        (1000, 15),
        (10000, 5),
        (10000, 10),
        (10000, 15),
    ];

    let mut group = c.benchmark_group("Protocols");
    for fmt in ["json", "capnp", "msgpack"].iter() {
        for (row_cnt, col_cnt) in test_cnt_pairs {
            group.bench_with_input(
                BenchmarkId::new(format!("{fmt}_encode_for_{row_cnt}_X_{col_cnt}"), fmt),
                fmt,
                |b, i| b.iter(|| encode_with_param(*i, row_cnt, col_cnt)),
            );
            group.bench_with_input(
                BenchmarkId::new(format!("{fmt}_decode_for_{row_cnt}_X_{col_cnt}"), fmt),
                fmt,
                |b, i| b.iter(|| decode_with_param(*i, row_cnt, col_cnt)),
            );
        }
    }
    group.finish();
}

criterion_group!(
    name = benches;
    config = Criterion::default().measurement_time(Duration::from_secs(5));
    targets = bench_plugin_protocols
);
criterion_main!(benches);
```

**Comment by WindSoilder** [comment]
Unfortunately I don't think so, the line chart has been changed somehow...

Refer to the example provided by the doc: https://bheisler.github.io/criterion.rs/book/user_guide/html_report.html
And the example line chart is also changed

**Comment by fdncred** [comment]
Let's land this for now and if https://github.com/bheisler/criterion.rs/issues/609 responds we can update it.

**Pull request merged**
