### PR TITLE
Fix `try` not working with `let`, etc.

### PR DESCRIPTION
**Pull request by IanManske**
# Description
Partialy addresses #13868. `try` does not catch non-zero exit code errors from the last command in a pipeline if the result is assigned to a variable using `let` (or `mut`).

This was fixed by adding a new `OutDest::Value` case. This is used when the pipeline is in a "value" position. I.e., it will be collected into a value. This ended up replacing most of the usages of `OutDest::Capture`. So, this PR also renames `OutDest::Capture` to `OutDest::PipeSeparate` to better fit the few remaining use cases for it.

# User-Facing Changes
Bug fix.

# Tests + Formatting
Added two tests.

### CODE REVIEW

**Comment by fdncred** [comment]
I'm trying to figure out what this is supposed to do with this. Is it supposed to capture the error when not inside of a git repo folder?
```nushell
let status = try {
  git status
} catch {|e| print -n ""}
```

## new
```nushell
❯ $env.config.display_errors.exit_code = false
❯ let status = try {
❯❯❯   git status
❯❯❯ } catch {|e| print -n ""}
fatal: not a git repository (or any of the parent directories): .git
❯ $env.LAST_EXIT_CODE
0
❯ $status
```
## old
```nushell
❯ $env.config.display_errors.exit_code = false
❯ let status = try {
❯❯❯   git status
❯❯❯ } catch {|e| print -n ""}
fatal: not a git repository (or any of the parent directories): .git
❯ $env.LAST_EXIT_CODE
128
❯ $status
Error: nu::shell::variable_not_found

  × Variable not found
   ╭─[entry #22:1:1]
 1 │ $status
   · ───┬───
   ·    ╰── variable not found
   ╰────
```

**Comment by WindSoilder** [comment]
Thanks for the pr!  I love the idea, but I don't think it fixes #13868 .  Because the command still raises error:
```
"1\n2" | grep -E "[[:alpha:]]" | detect columns
```

**Comment by WindSoilder** [comment]
> Is it supposed to capture the error when not inside of a git repo folder?

I think so, when there is an error in try, the return value will be the result of `catch` block.  But `try` doesn't eat the error message.

**Comment by IanManske** [comment]
> Thanks for the pr! I love the idea, but I don't think it fixes #13868 . Because the command still raises error:
> 
> ```
> "1\n2" | grep -E "[[:alpha:]]" | detect columns
> ```

Oh yeah, I was confused. This PR fixes the issue with `try` but not #13868 in general. But, #13868 should be easy to fix after this PR when combined with #13881.

**Comment by fdncred** [comment]
Thanks

**Pull request merged**
