### PR TITLE
set the type of default NU_LIB_DIRS and NU_PLUGIN_DIRS to list<string>

### PR DESCRIPTION
**Pull request by WindSoilder**
# Description
Fix: #12489

I believe the issue it's because the default value of `NU_LIB_DIRS` and `NU_PLUGIN_DIRS` is a string, but it should be a list.

So if users don't set up these values in `env.nu`, we will get a problem.

### CODE REVIEW

**Comment by kubouch** [comment]
Thanks for the fix! Looks good, but I'm wondering, is there a good way to test this?

**Comment by WindSoilder** [comment]
Firstly I don't think it's easy to add tests to test `use` behavior under default `NU_LIB_DIRS` value.

But I think we can just take an easy way: just test the type of `NU_LIB_DIRS` and `NU_PLUGIN_DIRS`..

**Comment by fdncred** [comment]
Thanks!

**Comment by NotTheDr01ds** [comment]
Thank you! This will simplify at least one aspect of my config ;-)

**Pull request merged**
