### PR TITLE
git completion: 'git fetch' for remotes

### PR DESCRIPTION
**Pull request by raboof**
# Description

Add completion for 'git fetch' to the default config

# Tests

Make sure you've run and fixed any issues with these commands:

- [x] `cargo fmt --all -- --check` to check standard code formatting (`cargo fmt --all` applies these changes)
- [ ] `cargo clippy --all --all-features -- -D warnings -D clippy::unwrap_used -A clippy::needless_collect` to check that you're using the standard code style
- [ ] `cargo build; cargo test --all --all-features` to check that all the tests pass

### CODE REVIEW

**Comment by sholderbach** [comment]
Thank you very much for the PR!

Would you mind adding comments as a short flag description? They automatically get turned into the description during tab completion 
image

On a more general note we probably have to decide at which point we stop putting the custom completions in the `default_config.nu` to not bloat it with completion modules. 

We started collecting some of the completions in the `nu_scripts` repo, but may want to have an easier to access source of completions.
https://github.com/nushell/nu_scripts/blob/main/custom-completions/git/git-completions.nu

**Comment by raboof** [comment]
> Would you mind adding comments as a short flag description? They automatically get turned into the description during tab completion

Ah cool, I should definitely upgrade to a version of nushell that actually shows those :D 

> On a more general note we probably have to decide at which point we stop putting the custom completions in the `default_config.nu` to not bloat it with completion modules.

I can definitely imagine that's a tricky balance: having git completions in the default install is a great initial experience, but indeed copying them to the user config (also making updates to newer versions potentially more tricky) might not be great long-term. I'll leave that up to you though :)

**Comment by raboof** [comment]
> I think we need to move all git completions out of the config and to nu_scripts and just have a minimal completion example.

I don't disagree :) - otoh I also think having git completions in the default install is very helpful.

Perhaps it would be possible to provide a way for packagers to include nu_scripts when shipping nushell, and somehow load the completions from there in the default config? I'm a nushell newbie so I'm not sure how much of what would be needed for that is already in place ;)

**Comment by fdncred** [comment]
we have some git-completions in our nu_scripts repo like sholderbach said. we need a `nu_get` to get and install scripts and plugins

**Comment by raboof** [comment]
Is there a way to check if a script is present on the `NU_LIB_DIRS` search path?

If so, perhaps the default config could check if `custom-completions/git/git-completions.nu` is available on that path, and if it is, load it, otherwise show a message to the user telling it to either add the nu_scripts to `NU_LIB_DIRS` or remove that fragment from their config?

**Comment by jntrnr** [comment]
@fdncred - what if the default install also offered to install a default set of completions when we ask about configurations? That way we could move them out but still bundle them with the install.

**Comment by fdncred** [comment]
> @fdncred - what if the default install also offered to install a default set of completions when we ask about configurations? That way we could move them out but still bundle them with the install.

@jntrnr yup, I'd support that. I just want to accomplish two things.
1. get them out of config.nu/env.nu so it's smaller (maybe put a comment in the config.nu pointing to nu_scripts/custom-completions)
2. avoid collisions with the git-completions in nu_scripts

**Comment by fdncred** [comment]
> Is there a way to check if a script is present on the NU_LIB_DIRS search path?

@raboof hmmmm, the `which` command can see if commands are loaded.

example:
```
> which "git checkout" 
╭───┬──────────────┬──────────────────────────┬──────────╮
│ # │     arg      │           path           │ built-in │
├───┼──────────────┼──────────────────────────┼──────────┤
│ 0 │ git checkout │ Nushell built-in command │ true     │
├───┼──────────────┼──────────────────────────┼──────────┤
│ # │     arg      │           path           │ built-in │
╰───┴──────────────┴──────────────────────────┴──────────╯
```

**Comment by jntrnr** [comment]
@fdncred can we land this into config.nu when it's ready, and then do a follow-up PR to refactor the completions into their own file(s)?

**Comment by fdncred** [comment]
> @fdncred can we land this into config.nu when it's ready, and then do a follow-up PR to refactor the completions into their own file(s)?

that's fine by me

**Comment by jntrnr** [comment]
Great, let's do it.

Thanks @raboof!

**Pull request merged**
