### PR TITLE
Rename `IoStream` to `OutDest`

### PR DESCRIPTION
**Pull request by IanManske**
# Description
I spent a while trying to come up with a good name for what is currently `IoStream`. Looking back, this name is not the best, because it:
1. Implies that it is a stream, when it all it really does is specify the output destination for a stream/pipeline.
2. Implies that it handles input and output, when it really only handles output.

So, this PR renames `IoStream` to `OutDest` instead, which should be more clear.

### CODE REVIEW

**Comment by devyn** [comment]
This is a clever name and I like the reasoning, but I'll be honest, I think that's one of the Rust standard library's poorer naming choices. How about something just very plain and descriptive like `PipeMode` or `OutDest`?

**Comment by IanManske** [comment]
Yeah, `OutDest` is also a good name. I'm fine with that or `Stdoe`. Wonder if anyone else has other suggestions or prefers one of the existing ones (so that I don't have to change it again lol).

**Comment by WindSoilder** [comment]
Personally I'd vote for `OutDest`, it's a little hard for me to connect `oe` with `out+err`.

**Comment by IanManske** [comment]
Ok, I think I found all the places that needed renaming :crossed_fingers:

**Pull request merged**
