### PR TITLE
Fix `select` on empty lists

### PR DESCRIPTION
**Pull request by rgwood**
This PR fixes `select` when given an empty list; it used to return `null` when given an empty list. I also cleaned up other `select` tests while I was in the area.

### Before:

```
> [] | select a | to nuon
null
```

### After:

```
> [] | select a | to nuon
[]
```

It looks like the previous behaviour was accidentally introduced by [this PR](https://github.com/nushell/nushell/pull/7639).

### CODE REVIEW

**Comment by fdncred** [comment]
We still have 7 days. I'd vote to land it too.

**Comment by rgwood** [comment]
> We still have 7 days.

Whoops, I lost track of time; thought it was less for some reason. Thanks!

**Comment by sholderbach** [comment]
> It looks like the previous behaviour was accidentally introduced by [this PR](https://github.com/nushell/nushell/pull/7639).

So we can skip marking this as a breaking change? 


Thanks should reduce type confusion!

**Comment by rgwood** [comment]
Yeah, it could break scripts in theory but I doubt anyone was depending on this behaviour.

**Comment by rgwood** [comment]
For context, this came up [on Discord](https://discord.com/channels/601130461678272522/614593951969574961/1090323027872465087); a user was having trouble with web APIs that sometimes return an empty list.

**Pull request merged**
