### PR TITLE
Add nullglob functionality to nu-glob

### PR DESCRIPTION
**Pull request by casually-blue**
# Description
This pull request fixes an issue where files with square brackets in their names would be treated as a glob pattern rather than the filename, even if there were no matches to the glob pattern. This is similar to bash nullglob.

# User-Facing Changes
Glob would now use the literal glob pattern as a result if there were no other results from matching

### CODE REVIEW

**Comment by WindSoilder** [comment]
Hi, Thanks for your contribution.  So I think it fixes: https://github.com/nushell/nushell/issues/9232

Would you please run `cargo fmt` to format the code first, and add a relative test case for `ls`?

**Comment by WindSoilder** [comment]
Hi, thanks for your contribution, I wonder is `ls` command also meet the same issue like this? https://github.com/nushell/nushell/issues/9232

Would you please add a relative test case for relative commands you changed?

**Comment by casually-blue** [comment]
> Hi, thanks for your contribution, I wonder is `ls` command also meet the same issue like this? #9232
I think that is likely the issue that is causing that, and I've found that I need to fix my pull request because its acting on the pattern as a whole and it should be working by path segment instead.

> Would you please add a relative test case for relative commands you changed?
I'm not quite sure on how to do test cases since this patch works on the results from actually running the glob patterns against a filesystem. Do you have any pointers on how I could do this from a test environment?

**Comment by fdncred** [comment]
Cool! Thanks for working on this!

To answer your question about tests, you can search for glob in our tests and find hits like this for `ls` 
https://github.com/nushell/nushell/blob/3005fe10e54a247de843e01f68c98c4b53a17148/crates/nu-command/tests/commands/ls.rs#L174-L206
and `glob`
https://github.com/nushell/nushell/blob/3005fe10e54a247de843e01f68c98c4b53a17148/crates/nu-command/tests/commands/glob.rs#L6-L22
Just note that the `glob` command does not use the `nu-glob` crate, it uses `wax` just to give some different functionality (although we'd like to integrate them back together someday)

**Comment by fdncred** [comment]
@casually-blue are you going to be able to have time for this?

**Comment by casually-blue** [comment]
Initially I was thinking that it would be possible to just check if there were no matches for the pattern as a whole but I've realized that nullglob needs to actually be implemented so it gets checked for each path segment which requires a bit more understanding of how the glob library is actually working internally. I should have something soon but if anyone who knows a bit more about it has any pointers that would be greatly appreciated.

**Comment by fdncred** [comment]
Thanks for your help, we appreciate the dedication to making nushell better!

**Comment by fdncred** [comment]
The tricky part is supporting both cases. Sometimes you want `[blah]` to work like a range/glob and other times it's literal. I'm not sure there's a way to fix it automatically, but we should allow escaping like `ls \[blah\]`, at least that's an opt-in approach.

Our previous approach was to totally remove `[]` from nu-glob entirely. We'd still love to have some type of fix so that we don't have to remove it again.

**Comment by casually-blue** [comment]
> The tricky part is supporting both cases. Sometimes you want `[blah]` to work like a range/glob and other times it's literal. I'm not sure there's a way to fix it automatically, but we should allow escaping like `ls \[blah\]`, at least that's an opt-in approach.

Yeah, I'm talking about the relative path that ls is putting in when it canonicalizes the path. The current version will treat characters in that as part of the glob when they are meant to be read literally.

**Comment by fdncred** [comment]
any ideas for a fix?

**Comment by casually-blue** [comment]
Looking at the code I got it somewhat working by just escaping the filename and then converting back to a PathBuf for pushing the rest of the glob, but that both breaks the prefix calculation for removing the relative parts of the path and isn't really a good idea because then the PathBufs that ls uses in its code aren't valid paths anymore since escaping is its own thing.

**Comment by fdncred** [comment]
I may be close with https://github.com/nushell/nushell/pull/9416, if you're interested in testing, please let me know how it goes.

**Comment by fdncred** [comment]
closing in favor of #9416 (which is pretty hacky. would love to have a better fix still)

**Pull request closed without merging**
