### PR TITLE
Refactor/usage of test support

### PR DESCRIPTION
**Pull request by LhKipp**
I wanted to write some tests for #3242, but I it was really hard to get a context in a test case. This PR solves this problem by adding a `get_test_context` to nu-test-support.

Therefore nu test now depends on nu-commands. This lead to some cyclic dependencies, as nu-test-support is included in some crates as a dependency and not as a dev-dependency.

So I moved some shortcut functions to create `Value`s into nu-protocol (it already contains macro row!...) and split nu-plugin into nu-plugin and nu-plugin-support (so that nu-plugin-test-support can use nu-test-support)

### CODE REVIEW

**Comment by andrasio** [comment]
The examples tests in `nu-command` (where contexts are created and commands added to) are different than what's in `nu-test-support` crate. If you need to test code that involves context, please add a helper to create a context with the commands and/or options that you need instead.

`nu-test-support` is not ready for a refactor at this stage.

**Comment by LhKipp** [comment]
Hey Andres @andrasio, this PR doesn't change any code inside of nu-test-support. It only changes how nu-test-support is used.
 
I can't create a test in nu-engine (where run_script resides logically and I want to write the test, where the code lives) if it needs to have a context with commands.

Before nu-test-support was included under dependencies (which is wrong IMO, as nu-test-support is for tests, not for normal code) so that some helper funcs like `fn string(str) -> Value` could be used. Now these helper funcs are moved outside of nu-test-support (as there are very few legitimate reasons to use them in non test code), and the includes got fixed up.

**Comment by stormasm** [comment]
"Therefore nu test now depends on nu-commands..."

@LhKipp I am pretty sure nu test should not depend on nu-commands...
nu-commands should be able to go away for folks doing lower level testing...
who do not want to have nu-commands in their setup

**Comment by LhKipp** [comment]
> who do not want to have nu-commands in their setup and do not want to pull
> in a large crate like nu-command...

Does a user of `nu-test-support` statically link modules from `nu-commands`, if he uses `nu-test-support`, but not the context module? (With the context module being the only module which includes some modules from `nu-commands`)

**Comment by andrasio** [comment]
@LhKipp Hi! Here is the issue.

We have examples tests under `nu-command`. These tests are still WIP fwiw and they are no different than what you need to do for tests in `nu-engine` (You can just `use` a basic evaluation, pass that to your test and continue working). Most importantly is the fact that one of them will be removed and not the other one. This is expected and the reason one might contain N commands and the other different commands (or perhaps at some point the same, we don't know and this is important).

This is on purpose because once there is full coverage of commands, the other will be removed. For this case you are refactoring something we are still working on and we need the duplication as it is right now to finish that pending work.

The helpers under `nu-test-support` for creating full-fledged `Value`s with unknown tags is fine the way it is (unless there is a really good reason it isn't). The create itself makes it clear `value` is another module and it's ok having the separation of concerns at that level.

Unless you are testing right now Nu plugins I could say something about them. Can you think of the top of your head a good reason of why the test helpers for plugins need to be moved to an independent sub crate? Why not as a `plugin` module under `nu-test-support` ?

**Comment by LhKipp** [comment]
Thanks for taking the time to respond. Then I will duplicate the code once more.

> Unless you are testing right now Nu plugins I could say something about them. Can you think of the top of your head a good reason of why the test helpers for plugins need to be moved to an independent sub crate? Why not as a `plugin` module under `nu-test-support` ?

I had to separate there, because of cyclic dependencies. I don't have a opinion where they should go.

**Pull request closed without merging**
