### PR TITLE
Loops return external stream when external command failed.

### PR DESCRIPTION
**Pull request by WindSoilder**
# Description

Fixes: #8644

# User-Facing Changes

For the following code:
```
for i in 1..2 {
    nu --testbin fail
}
print 3
```
Before this change, nu will print 3.  After this change, 3 won't be printed

# Tests + Formatting

Don't forget to add tests that cover your changes.

Make sure you've run and fixed any issues with these commands:

- `cargo fmt --all -- --check` to check standard code formatting (`cargo fmt --all` applies these changes)
- `cargo clippy --workspace -- -D warnings -D clippy::unwrap_used -A clippy::needless_collect` to check that you're using the standard code style
- `cargo test --workspace` to check that all tests pass

> **Note**
> from `nushell` you can also use the `toolkit` as follows
> ```bash
> use toolkit.nu  # or use an `env_change` hook to activate it automatically
> toolkit check pr
> ```

# After Submitting

If your PR had any user-facing changes, update [the documentation](https://github.com/nushell/nushell.github.io) after the PR is merged, if necessary. This will help us keep the docs up to date.

### CODE REVIEW

**Comment by fdncred** [comment]
Nice work!

**Comment by colemickens** [comment]
Strangely this DOES resolve my limited repro shown in #8644 , but doesn't for my real-world script. I'm still trying to track down what the difference is. Not a reason to block this, but I thought I'd mention it.

**Comment by colemickens** [comment]
Actually, I had modified my repro case locally. @WindSoilder if I run the exact repro from my issue, I am still seeing it fallthrough and return success.

**Comment by colemickens** [comment]
Is it possible that the use of a function is also swallowing the pipeline error?

**Comment by WindSoilder** [comment]
You can wrap the command call with `do -i`, like `do -i { custom cmd}`.

> but doesn't for my real-world script

Would you please provide another minimum code to reproduce?  Or is the code in  #8654?

**Comment by colemickens** [comment]
@WindSoilder Sorry for the confustion -- to clarify, I pulled your PR, put it on top of tip, and ran the precise repro code I posted in #8654 and it still displays the unfortunate behavior. When I initially said it worked, I had another `^false` in the function body.

```
╭ zeph  ~/code/nixcfg 0s
╰─▶ nix develop -i -c nu ./posted.nu
warning: Git tree '/home/cole/code/nixcfg' is dirty
warning: Git tree '/home/cole/code/nixcfg' is dirty
[inputup] attempting good
[inputup] success for [good]
[inputup] attempting bad
[inputup] intentionally calling ^false for [bad]
[inputup] finished
[main] surived after inputup

╭ zeph  ~/code/nixcfg 2.19s
╰─▶ echo $env.LAST_EXIT_CODE
0

╭ zeph  ~/code/nixcfg 0.82s
╰─▶ cat ./pkgs/pkgs/nushell/metadata.nix | rg rev
  rev = "7e47651b77cd68b1fdf3cb3a6a09513d8f01dd30";
```

And that is https://github.com/colemickens/nushell/commits/7e47651b77cd68b1fdf3cb3a6a09513d8f01dd30 just in case you want to sanity check.

**Comment by WindSoilder** [comment]
Somehow I'm not sure what's going on(I remember it works yesterday)...Mark as draft for more investigation

**Comment by colemickens** [comment]
FANTASTIC! It works for my repro, the posted repro, and my "real world" script. Thank you very much @WindSoilder!

**Comment by kubouch** [comment]
This seems good to me. It makes it consistent with the behavior without the loop:
```
nu --testbin fail
print 3
```

**Pull request merged**
