### PR TITLE
Update libproc

### PR DESCRIPTION
**Pull request by ZetaNumbers**
# Description
Update libproc from 0.12.0 to 0.13.0 to fix https://github.com/nushell/nushell/pull/8062#issuecomment-1564193217

# User-Facing Changes
None

### CODE REVIEW

**Comment by fdncred** [comment]
I have no problems building on MacOS with Ventura 13.4 with this PR or without this PR. I don't see the problem that this fixes. Maybe it's just on older versions of MacOS?

**Comment by ZetaNumbers** [comment]
> I just have xcode's tools installed, nothing special.

me too

**Comment by fdncred** [comment]
Just to be clear, this is what I do
1. git clone https://github.com/nushell/nushell.git (i don't do this much since i already have it locally)
2. cd nushell
3. if my repo isn't updated to the latest, i update it with git commands
4. cargo install --path . --features=dataframe

Are those the same steps you use?

**Comment by ZetaNumbers** [comment]
I see bindgen is updated from 0.59.2 to 0.64.0, perhaps this is what solves the issue?

**Comment by ZetaNumbers** [comment]
> Are those the same steps you use?

Yep

**Comment by ZetaNumbers** [comment]
But it wouldn't harm anyone if we bump libproc version right?

**Comment by fdncred** [comment]
I'm working on a PR to update a lot of crate versions. Let me try to put it in there.

**Comment by fdncred** [comment]
closed by #9296

**Pull request closed without merging**
