### PR TITLE
nu-table/ table --collapse style fix

### LINKED ISSUE #8033: `table --collapse` is a bit hard to read
### Related problem

i like using `table --collapse` to explore structured data in some other form :yum: 

however, i find that `table --collapse` is a bit too "pointy" and thus hard to read :thinking: 
let me explain with an example :wink: 

the normal `ls` gives
```bash
╭────┬───────────────────────┬──────┬──────────┬──────────────╮
│  # │         name          │ type │   size   │   modified   │
├────┼───────────────────────┼──────┼──────────┼──────────────┤
│  0 │ CODE_OF_CONDUCT.md    │ file │   3.4 KB │ 3 weeks ago  │
│  1 │ CONTRIBUTING.md       │ file │   3.6 KB │ 3 weeks ago  │
│  2 │ Cargo.lock            │ file │ 145.5 KB │ 15 hours ago │
│  3 │ Cargo.toml            │ file │   4.8 KB │ 5 days ago   │
│  4 │ Cross.toml            │ file │    363 B │ 3 weeks ago  │
│  5 │ LICENSE               │ file │   1.1 KB │ 3 weeks ago  │
│  6 │ README.md             │ file │  13.2 KB │ 3 weeks ago  │
│  7 │ README.release.txt    │ file │    124 B │ 3 weeks ago  │
│  8 │ assets                │ dir  │   4.1 KB │ 3 weeks ago  │
│  9 │ benches               │ dir  │   4.1 KB │ 5 days ago   │
│ 10 │ build-all-maclin.sh   │ file │    622 B │ 3 weeks ago  │
│ 11 │ build-all-windows.cmd │ file │    755 B │ 3 weeks ago  │
│ 12 │ build-all.nu          │ file │    603 B │ 3 weeks ago  │
│ 13 │ build.rs              │ file │    381 B │ 3 weeks ago  │
│ 14 │ crates                │ dir  │   4.1 KB │ 3 weeks ago  │
│ 15 │ docker                │ dir  │   4.1 KB │ 3 weeks ago  │
│ 16 │ docs                  │ dir  │   4.1 KB │ 3 weeks ago  │
│ 17 │ images                │ dir  │   4.1 KB │ 3 weeks ago  │
│ 18 │ install-all.ps1       │ file │    953 B │ 3 weeks ago  │
│ 19 │ install-all.sh        │ file │    874 B │ 3 weeks ago  │
│ 20 │ pkg_mgrs              │ dir  │   4.1 KB │ 3 weeks ago  │
│ 21 │ register-plugins.nu   │ file │   2.0 KB │ 3 weeks ago  │
│ 22 │ rust-toolchain.toml   │ file │   1.1 KB │ a week ago   │
│ 23 │ src                   │ dir  │   4.1 KB │ 4 days ago   │
│ 24 │ target                │ dir  │   4.1 KB │ 3 weeks ago  │
│ 25 │ tests                 │ dir  │   4.1 KB │ 3 weeks ago  │
│ 26 │ uninstall-all.sh      │ file │    405 B │ 3 weeks ago  │
│ 27 │ wix                   │ dir  │   4.1 KB │ 2 weeks ago  │
├────┼───────────────────────┼──────┼──────────┼──────────────┤
│  # │         name          │ type │   size   │   modified   │
╰────┴───────────────────────┴──────┴──────────┴──────────────╯
```
which is normal to read :ok_hand: 

now, let's pass this into `table --collapse`, i get
```bash
╭──────┬──────┬──────┬───────────────────────────────╮
│ name │ type │ size │           modified            │
 ──────┴──────┴────── ──────┬─────────┬────────────── 
│ CODE_OF_CONDUCT.md │ file │ 3.4 KiB │ 3 weeks ago  │
 ─────────────────┬──┴───┬──┴──────┬──┴────────────── 
│ CONTRIBUTING.md │ file │ 3.5 KiB │   3 weeks ago   │
 ────────────┬────┴─┬────┴──────┬──┴───────────────── 
│ Cargo.lock │ file │ 142.1 KiB │    15 hours ago    │
 ──────────── ────── ─────────┬─┴──────────────────── 
│ Cargo.toml │ file │ 4.7 KiB │      5 days ago      │
 ──────────── ────── ───────┬─┴────────────────────── 
│ Cross.toml │ file │ 363 B │      3 weeks ago       │
 ─────────┬──┴───┬──┴──────┬┴──────────────────────── 
│ LICENSE │ file │ 1.1 KiB │       3 weeks ago       │
 ─────────┴─┬────┴─┬───────┴──┬────────────────────── 
│ README.md │ file │ 12.9 KiB │     3 weeks ago      │
 ───────────┴──────┴─┬──────┬─┴─────┬──────────────── 
│ README.release.txt │ file │ 124 B │  3 weeks ago   │
 ────────┬─────┬─────┴───┬──┴───────┴──────────────── 
│ assets │ dir │ 4.0 KiB │        3 weeks ago        │
 ────────┴┬────┴┬────────┴┬────────────────────────── 
│ benches │ dir │ 4.0 KiB │        5 days ago        │
 ─────────┴─────┴─────┬───┴──┬───────┬─────────────── 
│ build-all-maclin.sh │ file │ 622 B │  3 weeks ago  │
 ─────────────────────┴─┬────┴─┬─────┴─┬───────────── 
│ build-all-windows.cmd │ file │ 755 B │ 3 weeks ago │
 ──────────────┬──────┬─┴─────┬┴───────┴───────────── 
│ build-all.nu │ file │ 603 B │     3 weeks ago      │
 ──────────┬───┴──┬───┴───┬───┴────────────────────── 
│ build.rs │ file │ 381 B │       3 weeks ago        │
 ────────┬─┴───┬──┴──────┬┴────────────────────────── 
│ crates │ dir │ 4.0 KiB │        3 weeks ago        │
 ──────── ───── ───────── ─────────────────────────── 
│ docker │ dir │ 4.0 KiB │        3 weeks ago        │
 ──────┬─┴───┬─┴───────┬─┴─────────────────────────── 
│ docs │ dir │ 4.0 KiB │         3 weeks ago         │
 ──────┴─┬───┴─┬───────┴─┬─────────────────────────── 
│ images │ dir │ 4.0 KiB │        3 weeks ago        │
 ────────┴─────┴──┬────── ───────┬─────────────────── 
│ install-all.ps1 │ file │ 953 B │    3 weeks ago    │
 ────────────────┬┴─────┬┴──────┬┴─────────────────── 
│ install-all.sh │ file │ 874 B │    3 weeks ago     │
 ──────────┬───── ──────┴──┬────┴──────────────────── 
│ pkg_mgrs │ dir │ 4.0 KiB │       3 weeks ago       │
 ──────────┴─────┴────┬────┴─┬─────────┬───────────── 
│ register-plugins.nu │ file │ 2.0 KiB │ 3 weeks ago │
 ───────────────────── ────── ───────── ───────────── 
│ rust-toolchain.toml │ file │ 1.1 KiB │ a week ago  │
 ─────┬─────┬───────── ──────┴─────────┴───────────── 
│ src │ dir │ 4.0 KiB │          4 days ago          │
 ─────┴──┬──┴──┬──────┴──┬─────────────────────────── 
│ target │ dir │ 4.0 KiB │        3 weeks ago        │
 ───────┬┴────┬┴────────┬┴─────────────────────────── 
│ tests │ dir │ 4.0 KiB │        3 weeks ago         │
 ───────┴─────┴────┬────┴─┬───────┬────────────────── 
│ uninstall-all.sh │ file │ 405 B │   3 weeks ago    │
 ─────┬─────┬──────┴──┬───┴───────┴────────────────── 
│ wix │ dir │ 4.0 KiB │         2 weeks ago          │
 ─────┴┬────┴─┬──────┬┴────────────────────────────── 
│ name │ type │ size │           modified            │
╰──────┴──────┴──────┴───────────────────────────────╯
```

to me it looks "pointy" => there are holes all over the output, e.g. around the `rust-toolchain.toml` line
```
...
│ register-plugins.nu │ file │ 2.0 KiB │ 3 weeks ago │
 ───────────────────── ────── ───────── ───────────── 
│ rust-toolchain.toml │ file │ 1.1 KiB │ a week ago  │
 ─────┬─────┬───────── ──────┴─────────┴───────────── 
│ src │ dir │ 4.0 KiB │          4 days ago          │
...
```
see? there are holes at almost all intersection :open_mouth: 

## some observations
- as can be seen in the example above, the behaviour of these "holes" is not very consistent in the output of `table --collapse` => sometimes there is a hole, some other times no hole
- i think it makes it quite hard to read compared to the normal `ls`...
see the output below, where i've removed all the intersections and replaced them with holes systematically, i think it's the extreme and it's very hard to read and capture the structure of the data :thinking: 
```
╭──────┬──────┬──────┬───────────────────────────────╮
│ name │ type │ size │           modified            │
 ────── ────── ────── ────── ───────── ────────────── 
│ CODE_OF_CONDUCT.md │ file │ 3.4 KiB │ 3 weeks ago  │
 ───────────────── ── ─── ── ────── ── ────────────── 
│ CONTRIBUTING.md │ file │ 3.5 KiB │   3 weeks ago   │
 ──────────── ──── ─ ──── ────── ── ───────────────── 
│ Cargo.lock │ file │ 142.1 KiB │    16 hours ago    │
 ──────────── ────── ───────── ─ ──────────────────── 
│ Cargo.toml │ file │ 4.7 KiB │      5 days ago      │
 ──────────── ────── ─────── ─ ────────────────────── 
│ Cross.toml │ file │ 363 B │      3 weeks ago       │
 ───────── ── ─── ── ──────  ──────────────────────── 
│ LICENSE │ file │ 1.1 KiB │       3 weeks ago       │
 ───────── ─ ──── ─ ─────── ── ────────────────────── 
│ README.md │ file │ 12.9 KiB │     3 weeks ago      │
 ─────────── ────── ─ ────── ─ ───── ──────────────── 
│ README.release.txt │ file │ 124 B │  3 weeks ago   │
 ──────── ───── ───── ─── ── ─────── ──────────────── 
│ assets │ dir │ 4.0 KiB │        3 weeks ago        │
 ────────  ────  ────────  ────────────────────────── 
│ benches │ dir │ 4.0 KiB │        5 days ago        │
 ───────── ───── ───── ─── ── ─────── ─────────────── 
│ build-all-maclin.sh │ file │ 622 B │  3 weeks ago  │
 ───────────────────── ─ ──── ─ ───── ─ ───────────── 
│ build-all-windows.cmd │ file │ 755 B │ 3 weeks ago │
 ────────────── ────── ─ ─────  ─────── ───────────── 
│ build-all.nu │ file │ 603 B │     3 weeks ago      │
 ────────── ─── ── ─── ─── ─── ────────────────────── 
│ build.rs │ file │ 381 B │       3 weeks ago        │
 ──────── ─ ─── ── ──────  ────────────────────────── 
│ crates │ dir │ 4.0 KiB │        3 weeks ago        │
 ──────── ───── ───────── ─────────────────────────── 
│ docker │ dir │ 4.0 KiB │        3 weeks ago        │
 ────── ─ ─── ─ ─────── ─ ─────────────────────────── 
│ docs │ dir │ 4.0 KiB │         3 weeks ago         │
 ────── ─ ─── ─ ─────── ─ ─────────────────────────── 
│ images │ dir │ 4.0 KiB │        3 weeks ago        │
 ──────── ───── ── ────── ─────── ─────────────────── 
│ install-all.ps1 │ file │ 953 B │    3 weeks ago    │
 ────────────────  ─────  ──────  ─────────────────── 
│ install-all.sh │ file │ 874 B │    3 weeks ago     │
 ────────── ───── ────── ── ──── ──────────────────── 
│ pkg_mgrs │ dir │ 4.0 KiB │       3 weeks ago       │
 ────────── ───── ──── ──── ─ ───────── ───────────── 
│ register-plugins.nu │ file │ 2.0 KiB │ 3 weeks ago │
 ───────────────────── ────── ───────── ───────────── 
│ rust-toolchain.toml │ file │ 1.1 KiB │ a week ago  │
 ───── ───── ───────── ────── ───────── ───────────── 
│ src │ dir │ 4.0 KiB │          4 days ago          │
 ───── ── ── ── ────── ── ─────────────────────────── 
│ target │ dir │ 4.0 KiB │        3 weeks ago        │
 ───────  ────  ────────  ─────────────────────────── 
│ tests │ dir │ 4.0 KiB │        3 weeks ago         │
 ─────── ───── ──── ──── ─ ─────── ────────────────── 
│ uninstall-all.sh │ file │ 405 B │   3 weeks ago    │
 ───── ───── ────── ── ─── ─────── ────────────────── 
│ wix │ dir │ 4.0 KiB │         2 weeks ago          │
 ─────  ──── ─ ──────  ────────────────────────────── 
│ name │ type │ size │           modified            │
╰──────┴──────┴──────┴───────────────────────────────╯
```

### Describe the solution you'd like

the ideal for me, and i think it would just be normal given the inconsistent output of `table --collapse`, would be to fill all the holes :yum: 

below is the same example as above, but with all the holes filled :relieved: 
```
╭──────┬──────┬──────┬───────────────────────────────╮
│ name │ type │ size │           modified            │
├──────┴──────┴──────┼──────┬─────────┬──────────────┤
│ CODE_OF_CONDUCT.md │ file │ 3.4 KiB │ 3 weeks ago  │
├─────────────────┬──┴───┬──┴──────┬──┴──────────────┤
│ CONTRIBUTING.md │ file │ 3.5 KiB │   3 weeks ago   │
├────────────┬────┴─┬────┴──────┬──┴─────────────────┤
│ Cargo.lock │ file │ 142.1 KiB │    16 hours ago    │
├────────────┼──────┼─────────┬─┴────────────────────┤
│ Cargo.toml │ file │ 4.7 KiB │      5 days ago      │
├────────────┼──────┼───────┬─┴──────────────────────┤
│ Cross.toml │ file │ 363 B │      3 weeks ago       │
├─────────┬──┴───┬──┴──────┬┴────────────────────────┤
│ LICENSE │ file │ 1.1 KiB │       3 weeks ago       │
├─────────┴─┬────┴─┬───────┴──┬──────────────────────┤
│ README.md │ file │ 12.9 KiB │     3 weeks ago      │
├───────────┴──────┴─┬──────┬─┴─────┬────────────────┤
│ README.release.txt │ file │ 124 B │  3 weeks ago   │
├────────┬─────┬─────┴───┬──┴───────┴────────────────┤
│ assets │ dir │ 4.0 KiB │        3 weeks ago        │
├────────┴┬────┴┬────────┴┬──────────────────────────┤
│ benches │ dir │ 4.0 KiB │        5 days ago        │
├─────────┴─────┴─────┬───┴──┬───────┬───────────────┤
│ build-all-maclin.sh │ file │ 622 B │  3 weeks ago  │
├─────────────────────┴─┬────┴─┬─────┴─┬─────────────┤
│ build-all-windows.cmd │ file │ 755 B │ 3 weeks ago │
├──────────────┬──────┬─┴─────┬┴───────┴─────────────┤
│ build-all.nu │ file │ 603 B │     3 weeks ago      │
├──────────┬───┴──┬───┴───┬───┴──────────────────────┤
│ build.rs │ file │ 381 B │       3 weeks ago        │
├────────┬─┴───┬──┴──────┬┴──────────────────────────┤
│ crates │ dir │ 4.0 KiB │        3 weeks ago        │
├────────┼─────┼─────────┼───────────────────────────┤
│ docker │ dir │ 4.0 KiB │        3 weeks ago        │
├──────┬─┴───┬─┴───────┬─┴───────────────────────────┤
│ docs │ dir │ 4.0 KiB │         3 weeks ago         │
├──────┴─┬───┴─┬───────┴─┬───────────────────────────┤
│ images │ dir │ 4.0 KiB │        3 weeks ago        │
├────────┴─────┴──┬──────┼───────┬───────────────────┤
│ install-all.ps1 │ file │ 953 B │    3 weeks ago    │
├────────────────┬┴─────┬┴──────┬┴───────────────────┤
│ install-all.sh │ file │ 874 B │    3 weeks ago     │
├──────────┬─────┼──────┴──┬────┴────────────────────┤
│ pkg_mgrs │ dir │ 4.0 KiB │       3 weeks ago       │
├──────────┴─────┴────┬────┴─┬─────────┬─────────────┤
│ register-plugins.nu │ file │ 2.0 KiB │ 3 weeks ago │
├─────────────────────┼──────┼─────────┼─────────────┤
│ rust-toolchain.toml │ file │ 1.1 KiB │ a week ago  │
├─────┬─────┬─────────┼──────┴─────────┴─────────────┤
│ src │ dir │ 4.0 KiB │          4 days ago          │
├─────┴──┬──┴──┬──────┴──┬───────────────────────────┤
│ target │ dir │ 4.0 KiB │        3 weeks ago        │
├───────┬┴────┬┴────────┬┴───────────────────────────┤
│ tests │ dir │ 4.0 KiB │        3 weeks ago         │
├───────┴─────┴────┬────┴─┬───────┬──────────────────┤
│ uninstall-all.sh │ file │ 405 B │   3 weeks ago    │
├─────┬─────┬──────┴──┬───┴───────┴──────────────────┤
│ wix │ dir │ 4.0 KiB │         2 weeks ago          │
├─────┴┬────┴─┬──────┬┴──────────────────────────────┤
│ name │ type │ size │           modified            │
╰──────┴──────┴──────┴───────────────────────────────╯
```

### Describe alternatives you've considered

_No response_

### Additional context and details

_No response_

### PR DESCRIPTION
**Pull request by zhiburt**
close #8033

So as I said they suppose to be there;

I've basically added a change of style if --collapse is used.

PS: I guess it's worth to add tests so hold on if you'll plan to merge it.

### CODE REVIEW

**Comment by fdncred** [comment]
@zhiburt if you can find time to fix these tests, we'll merge this. thanks!

**Comment by zhiburt** [comment]
So do you think we shall not `remove` --collapse?

**Comment by fdncred** [comment]
For now, I'd like to keep it. We may eventually remove it if we don't find a use for it.

**Comment by fdncred** [comment]
@zhiburt can you fix up these tests please?

**Comment by fdncred** [comment]
Thanks

**Pull request merged**
