### PR TITLE
`pstr` command to handle indexing by rendered "screen positions"

### PR DESCRIPTION
**Pull request by bobhy**
Provides a variant of `str` command (called `pstr`) where indexes and lengths match what you see on the screen, so-called "screen positions", rather than counting `char`s.   

`psrr` accounts for multi-byte UTF-8 extended graphemes (which can render as a single glyph) and ANSI control sequences (which change the styling but don't take up a screen position).

This logic was added to `fill` a while ago, but this PR adds a compatible calculation for string length and  substring, so it made sense to combine them all into one command.

The claim is this is handy when you're constructing a prompt string or other fixed-format text layout.

<aside>The name `pstr` arose when I was thinking about "print positions" (mainframe terminology). 
 A more correct name for the concept is "screen positions", but the name stuck.</aside>

# Description

```
> "こんにちは世界" | str length
21
> "こんにちは世界" | str length -g
7
> "こんにちは世界" | pstr length 
7
```
So `pstr length` is an alias for `str length --grapheme-clusters?

```
> $"plain(ansi cyan)cyan(ansi red)red(ansi reset)" | str length
26
> $"plain(ansi cyan)cyan(ansi red)red(ansi reset)" | str length -g
26
```
Oops, `str length -g` doesn't handle ANSI styling.
```
 $"plain(ansi cyan)cyan(ansi red)red(ansi reset)"
plaincyanred
> $"plain(ansi cyan)cyan(ansi red)red(ansi reset)" | pstr length
12
```

### Substring indexing
The length as seen by `pstr` is compatible with substring indexing.
```
> "こんにちは世界" | pstr substring 5..7
世界

> $"plain(ansi cyan)cyan(ansi red)red(ansi reset)" | pstr substring 0..5
plain
> $"plain(ansi cyan)cyan(ansi red)red(ansi reset)" | pstr substring 5..9
cyan
> $"plain(ansi cyan)cyan(ansi red)red(ansi reset)" | pstr substring 9..12
red
```

### Padding
Width field is a number of screen positions.
```
> 'nushell' | pstr fill --alignment m --character '─' --width 15
────nushell────
$"(ansi cyan)cyan(ansi reset)" | pstr fill --alignment m --character '─' --width 15
─────cyan──────
'こんにちは世界' | pstr fill --alignment m --character '─' --width 15
────こんにちは世界────
```
(last example may render wider than previous 2, because characters themselves are wider in  japanese font -- but still one screen position)

# User-Facing Changes
n/a

# Tests + Formatting
- :green_circle: `toolkit fmt`
- :green_circle: `toolkit clippy`
- :green_circle: `toolkit test`
- :green_circle: `toolkit test stdlib`

# Future directions
* `pstr` might need to copy  `str index-of` (and other?) subcommands to be functionally complete for screen layout calculations. (`str` command remains available for use when you're indexing bytes or chars.)
* Fill has a few things that might be fixed. 
  *  `'nushell' | pstr fill --width 4` should produce a 4 character result, not 6.
  * *decimal* alignment: right align, but with fixed number of decimal places
* I'd say the standalone `fill` command could then be deprecated.
* `pstr` could also expose the   `str` subcommands that don't imply index numbering,  (like `upcase`, `trim`, `join` ...) , then user wouldn't have to mix and match `str` and `pstr`

# After Submitting

### CODE REVIEW

**Comment by fdncred** [comment]
I'm kind of confused here as to why we need another set of commands. It seems like most of our string commands already support graphemes and we could add a --ansi/-a parameter to string the ansi and have all the functionality you're writing here. What am I missing?

**Comment by bobhy** [comment]
Basically, I'm angling to provide a total clone of the `str` command where all the string iteration is done by "screen positions" rather than chars -- we have all the well-known caveats about string indexing in UTF-8 and the additional variable of ANSI styling.  I'm thinking it would be nice to get back to the good old days when you could think of strings as an array of char, full stop.  Considering that Nushell is all about fixed-width text layout, that feels like a big ease of use win.
Functionally, the existing `fill` command and `str length -g` do cover some use cases, and `table` has a lot of the layout smarts, but some important functions are missing if you're rolling your own layout:  there's currently no `str substring -g` or `str index-of`  or a way to iterate through grapheme clusters either.  I'd like to add all of these under one umbrella command.

**Comment by fdncred** [comment]
I'm not sure any of the coreteam is going to be a fan of a separate set of string commands, but I'll let them speak for themselves. 

To me, it seems like we should just enhance what we have instead of rolling a completely new set of commands that do nearly the exact same thing.

**Comment by amtoine** [comment]
@bobhy 
i'll back up @fdncred on this one: we would like to
1. understand what the issue really is
2. see if it would be possible to improve existing commands
3. write new commands if it's proven to be impossible / too complex

also, for such a big change, i.e. it's quite a wall of green new lines, it would be great to have discussed the design together a bit in a prelimiray issue :relieved: 

i would recommend closing this PR for now and switch to an issue to better understand the situation and the direction we can take together :yum: 
of course, we can always go back to the present PR and reopen if in the end it was the way to go :wink:

**Comment by bobhy** [comment]
Closing per team request.

**Pull request closed without merging**
