### PR TITLE
type checking friendly to list<any>

### PR DESCRIPTION
**Pull request by WindSoilder**
# Description
Fixes:  #11259

This pr is aimed to make type_checking for list<any> happier.

## About the change:
When execute the following command:
```
[['a', 'b']; ["1", "2"]] | flatten | str trim
```

The data type flow will be something like this:
```nushell
  table             list<any>             list<string>
--------->  flatten ------------> str trim ------------>
```
But it's not really correct because when accessing `list<any>` input, `str trim` can output `table` too.

After the pr, `str trim` will generate `<any>` output for `list<any>` input, so the data type flow will be the following:
```nushell
  table             list<any>                 any
--------->  flatten ------------> str trim ------------>
```

So it'll make remaining commands happier

# User-Facing Changes

# Tests + Formatting
Done

### CODE REVIEW

**Comment by fdncred** [comment]
If I'm understanding this correctly, this seems like the wrong way to go. It looks like for hard coding a type to `any` when certain conditions are met. It seems like this could cause other problems that will be really difficult to find if we start changing types like this.

It seems like the right thing to do is to make it work without changing the type somehow by properly matching the input and output types instead of just picking the first one that's close to a match.

**Comment by WindSoilder** [comment]
Thanks for your opinion!

> It looks like for hard coding a type to any when certain conditions are met.

Yeah you're right, actually we are already doing this for `<any>` input type. 
I can explain more about the current behavior for `<any>` input type, which is current behavior in current main.  Let's take `str trim` and `echo` as example:
Here is `str trim`'s input output types:
```shell
string -> string
list<string> -> list<string>
table -> table
record -> record
```
Here is `echo`'s input type types:
```shell
nothing -> any
```
Then when we `echo "1234" | str trim`, the data type flow will be the following:
```
               <any>              <any>
---------> echo --------> str trim -------->
```
It's because can generate `<any>` type, and str trim have different output types, there is no right to **chose one** input/output type, so we have to give it `<any>`.

I think the same rule should apply to `list<any>`.  Still take str trim as example, if we give it `list<any>`, it matches:
1. list<string> -> list<string>
2. table -> table
There is also no right to **chose one** input/output type, so we also have to give it `<any>`.  This is what is pr is aimed for.  If we give it `list<string>` type, the output will also be `list<string>`

**Comment by sophiajt** [comment]
@WindSoilder - can you describe what the fix is that you're doing? I looked through the code, but it's not really clear what the fix is.

**Comment by WindSoilder** [comment]
@sophiajt It want to fix some parse error, which can be run in runtime:

Take the following as example:
```nushell
[['a', 'b']; ["1", "2"], ["3", "4"]] | flatten | str trim | transpose -ird
```
Currently it failed on latest main.  This pr can fix it.

**Comment by WindSoilder** [comment]
I will close this because it lasts for too long time.  And it may causes other problems by this pr.

**Pull request closed without merging**
