### PR TITLE
Change range semantic to behaves more like rust.

### PR DESCRIPTION
**Pull request by WindSoilder**
# Description
We have decided to make range to behave like rust, that is:
```
> 1..3
╭───┬───╮
│ 0 │ 1 │
│ 1 │ 2 │
╰───┴───╯
> 1..=3
╭───┬───╮
│ 0 │ 1 │
│ 1 │ 2 │
│ 2 │ 3 │
╰───┴───╯
> 1..<3
Error: nu::shell::external_command

  × External command failed
   ╭─[entry #2:1:1]
 1 │ 1..<3
   · ──┬──
   ·   ╰── executable was not found
   ╰────
  help: No such file or directory (os error 2)
```

This pr also:
1. removes `1..<3` syntax.  The main change is happened in `crates/nu-parser/src/parser.rs:parse_range` 
2. change range semantic in these commands due to changes in `crates/nu-cmd-base/src/util.rs`
* `detect_columns` (for `-c` flag)
* `str substring`
* `str index-of` (for `-r` flag)
* `bytes at`
Take `str substring` as example:
### Before
```
❯ "abcd" | str substring 1..=3
bc
```
### After
```
❯ "abcd" | str substring 1..=3
bcd
```
The result of `"abcd" | str substring 1..3` remains unchanged because the semantic of `1..3` is changed from `[1,2,3]` to `[1,2]`, so it returns "bc".

Apart from changes in `crates/nu-parser/src/parser.rs:parse_range` and `crates/nu-cmd-base/src/util.rs`, remaining changes are most about adjusting test code to follow new semantic

Fixes:  #7761
# User-Facing Changes
It's a big breaking change, because the semantic of `1..3` is changed from `[1,2,3]` to `[1,2]`

# Tests + Formatting
Adjusted all tests

# After Submitting
Need to update documentation about ranges

### CODE REVIEW

**Comment by WindSoilder** [comment]
Make as draft because the decision is not finally made

**Comment by NotTheDr01ds** [comment]
Coming to this based on #13077  - As a user, I think the existing semantic is much more logical.  I know that various languages and libraries are split on this:

* In PHP (not necessarily a language I want to mimic, but ...) `range(1,3)` results in 1, 2, and 3.
* In JavaScript, the `d3` library does the same, but Lodash results in 1 and 2 only.
* Python `range(1, 3)` results in 1 and 2 only

Personally, I see `1..3` as more logically `1..=3`, with `1..<3` being available if you need the alternative semantic.

On the flip side, I fully understand that splicing operations should (and must) be based on the rule "0 is the position *before* the first element, count up from there", which means that `length + 1` is the position *after* the last character.  E.g.:

```Nushell
> [ 1 2 3 4 ] | range 0..4
[ 1 2 3 ]
```

**Comment by WindSoilder** [comment]
@NotTheDr01ds Thanks for your input!  Happy to see there are some languages return inclusive pair on something like `1..3`(PHP in your example)
I'm ok with keeping current semantic.

**Comment by stevenxxiu** [comment]
I support this PR. *Rust* and *Python* are very popular languages, with *Nushell* being written in *Rust* too. It'll be more familiar for people coming from those, especially when manipulating strings.

**Pull request closed without merging**
