### PR TITLE
feat(nu-cli): use `cwd` to filter Hinter suggestions where available

### LINKED ISSUE #5799: Current working directory complete in addition to history complete
### Related problem

I have read the Reedline documentation but either the feature isn't there or how to accomplish it isn't clicking in my head.

In Fish, the default configuration suggests the contents of the current working directory in addition to history.

Is this an existing option and I'm just wooshing on it hard? If it is, can it be made default?

### Describe the solution you'd like

Use both history and the CWD to make autocomplete suggestions

### Describe alternatives you've considered

_No response_

### Additional context and details

image

https://asciinema.org/a/8g9NWwULdsus6xyIjF5ztmMMs

### PR DESCRIPTION
**Pull request by rrcwang**
# Description

Resolves #5799. Implements a `reedline::Hinter` to suggest completions based on `cwd` (the current working directory), when where the `cwd` of command history is available. This matches the default `fish` shell behaviour. 

When it is not available, returns to the existing behaviour.

## TODOs
- [ ] basic tests (desired behavior)
- [ ] resiliency testing if there are no failures if the history is not supporting storing the cwd, errors from either reading the history or the current working directory should not crash the hinter.

## Example
Consider the following directory structure, where | is the current caret position:
```
foo/
bar/
├─ bacon.txt
├─ eggs.txt
├─ spam.txt
```

**Not filtered by `cwd`**
```
$ cd bar
$ cat bacon.txt
Lorem Ipsum
$ cd ..
$ cd bar
$ c|d bar
```

**Filtered by `cwd`**
```
$ cd bar
$ cat bacon.txt
Lorem Ipsum
$ cd ..
$ cd bar
$ c|at bacon.txt
```

### Some notes:
* Mostly ripped from the current reedline release's DefaultHinter implementation ([v0.11.0](https://github.com/nushell/reedline/releases/tag/v0.11.0))
* Next steps should involve colouring the output based on whether a file exists in the working directory or not. I will open a ticket and describe more fully

# Tests

Make sure you've done the following:

- [ ] Add tests that cover your changes, either in the command examples, the crate/tests folder, or in the /tests folder.
- [ ] Try to think about corner cases and various ways how your changes could break. Cover them with tests.
- [ ] If adding tests is not possible, please document in the PR body a minimal example with steps on how to reproduce so one can verify your change works.

Make sure you've run and fixed any issues with these commands:

- [ ] `cargo fmt --all -- --check` to check standard code formatting (`cargo fmt --all` applies these changes)
- [ ] `cargo clippy --workspace --features=extra -- -D warnings -D clippy::unwrap_used -A clippy::needless_collect` to check that you're using the standard code style
- [ ] `cargo test --workspace --features=extra` to check that all the tests pass

### CODE REVIEW

**Comment by fdncred** [comment]
Question: I'm wondering if both DefaultHinter and CWDHinter are useful to people such that we need to make it configurable which one to use?

**Comment by fdncred** [comment]
Also, doesn't this menu do the same thing?
```
{
        # List all unique successful commands in the current directory
        name: pwd_history_menu
        only_buffer_difference: true
        marker: "? "
        type: {
            layout: list
            page_size: 10
        }
        style: {
            text: green
            selected_text: green_reverse
        }
        source: { |buffer, position|
            history
            | select command exit_status cwd
            | where exit_status != 1
            | where cwd == $env.PWD
            | where command =~ $buffer
            | each { |it| {value: $it.command } }
            | reverse
            | uniq
        }
    }
```
and keybinding
```
    {
      name: "pwd history"
      modifier: control
      keycode: char_h
      mode: emacs
      event: { send: menu name: pwd_history_menu }
    }
```

**Comment by sholderbach** [comment]
> Also, doesn't this menu do the same thing?

This tries to concern it self with the hints/autosuggesiton (no tab necessary) while the menu requires pressing tab to either display or the enabled quick completion to directly complete on keypress.

---

To add tests you can look at how the [tests for the file/path completions](https://github.com/nushell/nushell/blob/main/crates/nu-cli/tests/completions.rs) are implemented and reuse the dummy directories we have in the [`fixtures` folder](https://github.com/nushell/nushell/tree/main/tests/fixtures/completions).

--- 

My criteria for landing this would be:

- [ ] basic tests (desired behavior)
- [ ] resiliency testing if there are no failures if the history is not supporting storing the `cwd`, errors from either reading the history or the current working directory should not crash the hinter.

config option would be nice to have but this seems to be a bit smarter than defualt hinter

**Comment by rrcwang** [comment]
> This tries to concern it self with the hints/autosuggesiton (no tab necessary) while the menu requires pressing tab to either display or the enabled quick completion to directly complete on keypress.

Yes! This exactly.

@sholderbach Thank you for the info about test structure. I'll re-request review on this PR when I've completed them.

**Comment by sholderbach** [comment]
Awesome, thanks! Let me know if you need help or have questions around the tests.

**Comment by fdncred** [comment]
@rrcwang any updates on this PR?

**Comment by fdncred** [comment]
seems like there's no activity. let's close this for now. @rrcwang let us know if/when you want to work on this again and we can reopen/start a new PR.

**Pull request closed without merging**
