### PR TITLE
Move history into their own module

### PR DESCRIPTION
**Pull request by Hofer-Julian**
# Description

Since there are plans to add more history commands, it seems sensible to put them into their own module and category

https://github.com/nushell/nushell/pull/10440#issuecomment-1731408785

# User-Facing Changes

The history commands are in the category "History" rather than "Misc"

### CODE REVIEW

**Comment by sholderbach** [comment]
Sounds good to have a category for them. 

I think we could keep them in `nu-cli` as they are tightly linked to having a `reedline` repl. Not moving them to `nu-command` could be slightly beneficial for parallel compilation as `nu-command` is already a large monolith and we already depend on `reedline` for `nu-cli`

**Comment by Hofer-Julian** [comment]
> Sounds good to have a category for them.
> 
> I think we could keep them in `nu-cli` as they are tightly linked to having a `reedline` repl. Not moving them to `nu-command` could be slightly beneficial for parallel compilation as `nu-command` is already a large monolith and we already depend on `reedline` for `nu-cli`

Sure, I will adapt the PR tomorrow

**Comment by Hofer-Julian** [comment]
@sholderbach done!

**Review by sholderbach — APPROVED** [review]
Awesome! Thanks

**Pull request merged**
