### PR TITLE
Remove CI and releases for `dataframe` feature

### PR DESCRIPTION
**Pull request by IanManske**
# Description
Removes the CI for the `dataframe` feature. Also removes the nightly builds for the `dataframe` feature as well as the "Full" releases.

### CODE REVIEW

**Comment by fdncred** [comment]
Shouldn't this be done when dfrs are removed? I'm not sure we're quite ready to remove them yet. I think @maxim-uvarov and @ayax79 are still testing, please correct me if I'm wrong.

**Comment by maxim-uvarov** [comment]
I'm really incompetent here.

Yet I would like to mention:
- IMO the current release version of the `polars` plugin is functioning better than `dfr`.
- But it needs additional steps for installation for final users (which I guess is not a problem at all). I will send pr into the book `dataframe` chapter with info on how to install `polars` soon.

It would be cool if it were possible to install nushell plugins, including polars, with package managers (like it is already done with nushell itself).

**Comment by fdncred** [comment]
One last point, I'm good with removing dataframes from nushell, in favor of nu_plugin_polars, whenever @ayax79 and @maxim-uvarov are ready. I'd like to do it sooner rather than later but I also don't want to rush any testing that may be happening.

**Comment by maxim-uvarov** [comment]
@ayax79 is a decision-maker here; let's wait for him.

**Comment by sholderbach** [comment]
Can't wait for the full migration!

Conceptually I think that the CI part should only go with the code itself being removed. I don't want some baggage in the repo that may not compile anymore.
Sunsetting the release part itself can happen independently.

**Comment by IanManske** [comment]
> Conceptually I think that the CI part should only go with the code itself being removed. I don't want some baggage in the repo that may not compile anymore.

Yeah, that makes sense. I'll close for whoever wants to handle removing the old dataframe crate.

**Comment by maxim-uvarov** [comment]
Just for tracking purposes:
I submitted a PR that uses `polars` instead of `dfr` and added installation instructions.
https://github.com/nushell/nushell.github.io/pull/1391

**Comment by devyn** [comment]
Why not just build on this and remove `nu-cmd-dataframe` and the `dataframe` feature entirely? I think that is the plan for this release anyway

**Comment by IanManske** [comment]
If @ayax79 is fine with that, and he thinks it's ready, then sure. (Or, if he would like to do the honors :smile:)

**Pull request closed without merging**
