### PR TITLE
Make example binaries proper cargo examples

### PR DESCRIPTION
**Pull request by sholderbach**
# Description

Should not be built by default with `cargo build`
Instead are compiled with `cargo test` to avoid bitrot
Run with `cargo run -p ... --example ...`

# Tests + Formatting

Make sure you've done the following, if applicable:

- Add tests that cover your changes (either in the command examples, the crate/tests folder, or in the /tests folder)
  - Try to think about corner cases and various ways how your changes could break. Cover those in the tests

Make sure you've run and fixed any issues with these commands:

- `cargo fmt --all -- --check` to check standard code formatting (`cargo fmt --all` applies these changes)
- `cargo clippy --workspace --features=extra -- -D warnings -D clippy::unwrap_used -A clippy::needless_collect` to check that you're using the standard code style
- `cargo test --workspace --features=extra` to check that all tests pass

# User-Facing Changes

If you're making changes that will affect the user experience of Nushell (ex: adding/removing a command, changing an input/output type, adding a new flag):

- Get another regular contributor to review the PR before merging
- Make sure that there is an entry in the documentation (https://github.com/nushell/nushell.github.io) for the feature, and update it if necessary

### CODE REVIEW

**Comment by rgwood** [comment]
LGTM - thanks!

**Comment by rgwood** [comment]
Seeing a new warning after this PR:

```
/home/reilly/source/nushell〉cargo nextest run --all --features=database                                       11/06/2022 03:42:25 PM
warning: output filename collision.
The example target `demo` in package `nu-system v0.70.1 (/home/reilly/source/nushell/crates/nu-system)` has the same output filename as the example target `demo` in package `nu-pretty-hex v0.70.1 (/home/reilly/source/nushell/crates/nu-pretty-hex)`.
Colliding filename is: /home/reilly/source/nushell/target/debug/examples/demo
The targets should have unique names.
Consider changing their names to be unique or compiling them separately.
This may become a hard error in the future; see <https://github.com/rust-lang/cargo/issues/6313>.
warning: output filename collision.
The example target `demo` in package `nu-table v0.70.1 (/home/reilly/source/nushell/crates/nu-table)` has the same output filename as the example target `demo` in package `nu-system v0.70.1 (/home/reilly/source/nushell/crates/nu-system)`.
Colliding filename is: /home/reilly/source/nushell/target/debug/examples/demo
The targets should have unique names.
Consider changing their names to be unique or compiling them separately.
This may become a hard error in the future; see <https://github.com/rust-lang/cargo/issues/6313>.
```

**Comment by sholderbach** [comment]
> Seeing a new warning after this PR:
> 
> ```
> /home/reilly/source/nushell〉cargo nextest run --all --features=database                                       11/06/2022 03:42:25 PM
> warning: output filename collision.
> The example target `demo` in package `nu-system v0.70.1 (/home/reilly/source/nushell/crates/nu-system)` has the same output filename as the example target `demo` in package `nu-pretty-hex v0.70.1 (/home/reilly/source/nushell/crates/nu-pretty-hex)`.
> Colliding filename is: /home/reilly/source/nushell/target/debug/examples/demo
> The targets should have unique names.
> Consider changing their names to be unique or compiling them separately.
> This may become a hard error in the future; see <https://github.com/rust-lang/cargo/issues/6313>.
> warning: output filename collision.
> The example target `demo` in package `nu-table v0.70.1 (/home/reilly/source/nushell/crates/nu-table)` has the same output filename as the example target `demo` in package `nu-system v0.70.1 (/home/reilly/source/nushell/crates/nu-system)`.
> Colliding filename is: /home/reilly/source/nushell/target/debug/examples/demo
> The targets should have unique names.
> Consider changing their names to be unique or compiling them separately.
> This may become a hard error in the future; see <https://github.com/rust-lang/cargo/issues/6313>.
> ```

*Shakes fist at the cargo workspace cloud* dang was only testing that with our toolchain at the time

**Comment by sholderbach** [comment]
Fixed in #7046

**Pull request merged**
