### PR TITLE
Fix silent failure of parsing input output types

### LINKED ISSUE #13736: Incorrect pipeline signature should not be ignored
### Describe the bug

When pipeline types are specified incorrectly in function signature, they are silently ignored. This is an error, and it should be treated accordingly.

### How to reproduce

```nushell
# incorrect, there should be a colon after argument specs
def test1 [] nothing -> nothing {}

# correct
def test2 []: nothing -> nothing {}
```

Above are 2 function definitions, the latter is the correct version of the former.

And yet both are accepted by nu shell. The former just gets the pipe spec quietly ignored and treated like `def test1 [] {}`.

### Expected behavior

Nu shell should raise exception when processing the definition of `test1`

### Configuration

| key                | value                                                         |
| ------------------ | ------------------------------------------------------------- |
| version            | 0.97.1                                                        |
| major              | 0                                                             |
| minor              | 97                                                            |
| patch              | 1                                                             |
| branch             |                                                               |
| commit_hash        | 60769ac1ba3ea036d889f140095d855e5597840c                      |
| build_os           | linux-x86_64                                                  |
| build_target       | x86_64-unknown-linux-musl                                     |
| rust_version       | rustc 1.78.0 (9b00956e5 2024-04-29)                           |
| rust_channel       | 1.78.0-x86_64-unknown-linux-gnu                               |
| cargo_version      | cargo 1.78.0 (54d8815d0 2024-03-26)                           |
| build_time         | 2024-08-21 03:29:44 +00:00                                    |
| build_rust_channel | release                                                       |
| allocator          | mimalloc                                                      |
| features           | default, sqlite, static-link-openssl, system-clipboard, trash |
| installed_plugins  | polars 0.97.1, query 0.97.1                                   |

### PR DESCRIPTION
**Pull request by ratherforky**
- This PR should fix/close:
  - #11266
  - #12893 
  - #13736 
  - #13748
  - #14170
- It doesn't fix #13736 though unfortunately. The issue there is at a different level to this fix (I think probably in the lexing somewhere, which I haven't touched).

# The Problem

The linked issues have many examples of the problem and the related confusion it causes, but I'll give some more examples here for illustration. It boils down to the following:

This doesn't type check (good):
```nu
def foo []: string -> int { false }
```

This does (bad):
```nu
def foo [] : string -> int { false }
```

Because the parser is completely ignoring all the characters. This also compiles in 0.100.0:
```nu
def blue [] Da ba Dee da Ba da { false }
```

And this also means commands which have a completely fine type, but an extra space before `:`, lose that type information and end up as `any -> any`, e.g.
```nu
def foo [] : int -> int {$in + 3}
```
```bash
$ foo --help
Input/output types:
  ╭───┬───────┬────────╮
  │ # │ input │ output │
  ├───┼───────┼────────┤
  │ 0 │ any   │ any    │
  ╰───┴───────┴────────╯
```

# The Fix

Special thank you to @texastoland whose draft PR (#12358) I referenced heavily while making this fix.

That PR seeks to fix the invalid parsing by disallowing whitespace between `[]` and `:` in declarations, e.g. `def foo [] : int -> any {}`

This PR instead allows the whitespace while properly parsing the type signature. I think this is the better choice for a few reasons:
- The parsing is still straightforward and the information is all there anyway,
- It's more consistent with type annotations in other places, e.g. `do {|nums : list<int>| $nums | describe} [ 1 2 3 ]` from the [Type Signatures doc page](https://www.nushell.sh/lang-guide/chapters/types/type_signatures.html)
- It's more consistent with the new nu parser, which allows `let x : bool = false` (current nu doesn't, but this PR doesn't change that)
- It will be less disruptive and should only break code where the types are actually wrong (if your types were correct, but you had a space before the `:`, those declarations will still compile and now have more type information vs. throwing an error in all cases and requiring spaces to be deleted)
- It's the more intuitive syntax for most functional programmers like myself (haskell/lean/coq/agda and many more either allow or require whitespace for type annotations)

I don't use Rust a lot, so I tried to keep most things the same and the rest I wrote as if it was Haskell (if you squint a bit). Code review/suggestions very welcome. I added all the tests I could think of and `toolkit check pr` gives it the all-clear.

# User-Facing Changes

This PR meets part of the goal of #13849, but doesn't do anything about parsing signatures twice and doesn't do much to improve error messages, it just enforces the existing errors and error messages.

This will no doubt be a breaking change, mostly because the code is already broken and users don't realise yet (one of my personal scripts stopped compiling after this fix because I thought `def foo [] -> string {}` was valid syntax). It shouldn't break any type-correct code though.

### CODE REVIEW

**Comment by fdncred** [comment]
Happy to see this. Thanks!

I'd personally rather see no space between `[]` and `:` but let's see what others think. I can live with it either way and it's definitely an improvement over what we have now.

**Comment by 132ikl** [comment]
> I'd personally rather see no space between [] and : but let's see what others think.

Style-wise, I agree. But in my opinion this should just be a style rule, not something actually enforced by the parser. The space could be removed by e.g., nufmt or topiary-nushell, but I think the parser should be lenient and accept either.

**Comment by ratherforky** [comment]
I'd be happy (or rather, only slightly sad) to go with strictly no space if that's what people ultimately want, though I'm curious where that preference comes from. The only language I know of that favours no space is Rust, but even Rust allows spaces before `:` (including in let bindings) and so does nu in the parameters e.g. `def foo [y : string] {}`

**Comment by fdncred** [comment]
We just need to be consistent. So, if this PR allows the space, we need to allow it in assignment like `let a : bool = false` (not allowed) and custom command parameter like `def foo [value? : number = 5]` (allowed), records `{a : 1 b : 2}` (allowed). There may be other places that I'm not remembering right now.

**Comment by vyadh** [comment]
Much appreciate this change as some of my code had little type checking without me realising because I didn't specify the signature properly.

FWIW, I agree with the point of this being more of a convention and style and that I think is normally the case in other languages in terms of allowing it but have conventions. Languages that by convention do not have a space in similar context, I think it's probably the majority of the more well known languages? For example, Rust, Python, Scala, Kotlin, TypeScript, Swift - all have something of the form `let variable: type` or `def function: type`. Then there are data formats like YAML, JSON, etc obviously having similar convention for `key: value`. In term of those languages that use a space, I can think of C++, Haskel and Ocaml. I guess a space before a colon was more prevalent style in early languages too (e.g. Ada, Algol, Fortran).

**Comment by ratherforky** [comment]
Yeah I definitely agree the convention should stay as no space since it's well established and seems to be favoured by the imperative-gone-functional languages/most nu contributors. I was more wondering about the preference for _enforcing_ no space, which none of those languages do (I checked). Even JSON allows spaces and that's not even a type annotation.

I get the sense we're more or less in agreement about this though and I'd like `let` to be consistent too. I've had a quick look and I think it's definitely doable, just a bit annoying (it's stateful and a bit obtuse), otherwise I'd get it out of the way right now. The code which would need changing is `parse_let` in parse_keywords.rs, starting from `let mut idx = 0`, and `parse_var_with_opt_type` in parser.rs.

**Comment by fdncred** [comment]
Nice work. Just tried this out and it fixed several errors in the files I source at startup!

**Comment by fdncred** [comment]
Thanks

**Pull request merged**
