### PR TITLE
switch from reqwest to surf

### PR DESCRIPTION
**Pull request by jonathandturner**
Fixes https://github.com/nushell/nushell/issues/342

The moves us from reqwest to surf, which removes some unnecessary dependencies as well

### CODE REVIEW

**Comment by jonathandturner** [comment]
Not sure what is causing the macOS failure. It might be related to how the 'surf' dependency is being used or imported.

**Comment by jbcden** [comment]
@jonathandturner It looks like some weird linking issue. Every time I setup a mac from scratch there are lots of weird linking things that need to be setup so it could be that. On my mac, it seems to build fine -- which is what makes me think it might be something to do with the setup. I will try to investigate a bit.

**Comment by jbcden** [comment]
@jonathandturner On a separate note, I also found the issues with the `hyper-client` feature and opened a PR to address those on `surf`: https://github.com/rustasync/surf/pull/58.

**Comment by jbcden** [comment]
@jonathandturner I don't know much about Azure but I found https://github.com/ddnet/ddnet/commit/e8bd8459a6f556594f48f33f4d145033bc89d46f which references issues with certain flags not existing on older versions of Xcode. I believe that macos 10.13 shipped with Xcode 9 which may not have that flag based on https://github.com/ddnet/ddnet/issues/1325#issuecomment-426937386. Perhaps updating the version of macos that is specified in the piplelines file would fix this?

**Comment by jbcden** [comment]
Looks like the latest macos should be available as per https://devblogs.microsoft.com/devops/azure-pipelines-now-supports-additional-hosted-macos-versions/

**Comment by jbcden** [comment]
@jonathandturner It looks like upgrading fixes the issue! See https://github.com/nushell/nushell/pull/405!

**Comment by jonathandturner** [comment]
@jbcden - awesome work! Thanks for tracking that down. I'll make the change and land this.

**Pull request merged**
