### PR TITLE
remove old deprecated commands

### PR DESCRIPTION
**Pull request by amtoine**
# Description
in this PR i propose to remove the following old deprecated commands
- `hash base64` -> `encode base64`
- `math eval` -> `math <sub>`
- `str to-datetime` -> `into datetime`
- `str to-decimal` -> `into decimal`
- `str find-replace` -> `str replace`
- `str to-int` -> `into int`
- `keep` -> `take`
- `match` -> `find`
- `nth` -> `select`
- `pivot` -> `transpose`
- `unalias` -> `hide`
- `all?` -> `all`
- `any?` -> `any`
- `empty?` -> `is-empty`
- `build-string` -> `str join` / string concatenation with `+`
- `str lpad` -> `fill`
- `str rpad` -> `fill`
- `str collect` -> `str join`
- `old-alias` -> `alias`

so old i do not remember them at all :open_mouth:

i left the following four commands because they have been moved much more recently i think!
- `fetch` -> `http get`
- `post` -> `http post`
- `benchmark` -> `timeit`
- `let-env`
- `date format` -> `format date`

# User-Facing Changes

# Tests + Formatting
- :green_circle: `toolkit fmt`
- :green_circle: `toolkit clippy`
- :black_circle: `toolkit test`
- :black_circle: `toolkit test stdlib`

# After Submitting

### CODE REVIEW

**Comment by jntrnr** [comment]
@fdncred maybe we need one called `turn` or `rotate` :D

**Review by sholderbach — APPROVED** [review]
Let's go ahead with this! In my view this is not a breaking change as it doesn't affect behavior we advertise as working.

**Comment by amtoine** [comment]
after the merge with the `date format` change i've just
- removed the `old-alias` command which i forgot
- left the `date format` -> `format date` deprecation as it's so recent
- renamed `LetEnvDeprecated` to `LetEnv`
- moved `LetEnv` and `DateFormat` to the "deprecated" section of `default_context.rs`

**Comment by fdncred** [comment]
Thanks

**Pull request merged**
