### PR TITLE
cp: expand target path before checking

### PR DESCRIPTION
**Pull request by WindSoilder**
# Description
Fixes: #11683

# User-Facing Changes
NaN

# Tests + Formatting
~~I don't think we need to add a test, or else it'll copy some file to user's directory, it seems bad.~~
Done.

# After Submitting
NaN

### CODE REVIEW

**Comment by bew** [comment]
> I don't think we need to add a test, or else it'll copy some file to user's directory, it seems bad.

To write a test you could set `$env.HOME` to a test folder so actual user home isn't targeted?

**Comment by WindSoilder** [comment]
Thanks for your suggestion!  Sadly I don't think it works.   Because `expand_path_with` reads home dir from `dirs_next::home_dir()`, it doesn't know anything about `$env.HOME`

**Comment by bew** [comment]
Well in the end getting the home dir will look for the HOME env var (at least on Linux), so it should be possible to to set that env var before running the tests to ensure it doesn't leak into the test environment 

https://doc.rust-lang.org/std/env/fn.home_dir.html

**Comment by WindSoilder** [comment]
Thanks!  I've add a test on unix like system

**Pull request merged**
