### PR TITLE
Fix `describe -d` for lazy records

### PR DESCRIPTION
**Pull request by gaetschwartz**
# Description

This PR fixes an overlook from a previous PR. It now correctly returns the details on lazy records.

# User-Facing Changes

Describe detailed now returns the expected result.

### CODE REVIEW

**Comment by gaetschwartz** [comment]
This PR fixes an overlook from a previous PR. It now correctly returns the details on lazy records.

**Comment by fdncred** [comment]
This is definitely better than failing silently but I kind of expected something in the vein of `ls | describe -d | table -e` and just got this. Is this what you were aiming for
```nushell
❯ sys | describe -d 
╭──────┬──────╮
│type  │record│
│lazy  │true  │
│length│6     │
╰──────┴──────╯
```

**Comment by gaetschwartz** [comment]
Lazy are not collected by default ;) `describe -d -l`

**Comment by fdncred** [comment]
We don't have to decide here but I'm not sure why there is even a parameter for `--collect-lazyrecords`. Seems like describe should maybe always do that to me. Is there some advantage to having it?

**Comment by gaetschwartz** [comment]
I figured as collecting can be potentially really slow, it could lead to surprises. Should I remove the flag ?

**Comment by fdncred** [comment]
Thanks for the update. Let's leave it for now and see if anything breaks in the future.

**Pull request merged**
