### PR TITLE
create `nuon` crate from `from nuon` and `to nuon`

### PR DESCRIPTION
**Pull request by amtoine**
# Description
playing with the NUON format in Rust code in some plugins, we agreed with the team it was a great time to create a standalone NUON format to allow Rust devs to use this Nushell file format.

> **Note**
> this PR almost copy-pastes the code from `nu_commands/src/formats/from/nuon.rs` and `nu_commands/src/formats/to/nuon.rs` to `nuon/src/from.rs` and `nuon/src/to.rs`, with minor tweaks to make then standalone functions, e.g. remove the rest of the command implementations

### TODO
- [x] add tests
- [x] add documentation

# User-Facing Changes
devs will have access to a new crate, `nuon`, and two functions, `from_nuon` and `to_nuon`
```rust
from_nuon(
    input: &str,
    span: Option<Span>,
) -> Result<Value, ShellError>
```
```rust
to_nuon(
    input: &Value,
    raw: bool,
    tabs: Option<usize>,
    indent: Option<usize>,
    span: Option<Span>,
) -> Result<String, ShellError>
```

# Tests + Formatting
i've basically taken all the tests from `crates/nu-command/tests/format_conversions/nuon.rs` and converted them to use `from_nuon` and `to_nuon` instead of Nushell commands
- i've created a `nuon_end_to_end` to run both conversions with an optional middle value to check that all is fine

> **Note** 
> the `nuon::tests::read_code_should_fail_rather_than_panic` test does give different results locally and in the CI...
> i've left it ignored with comments to help future us :)

# After Submitting
mention that in the release notes for sure!!

### CODE REVIEW

**Comment by amtoine** [comment]
the last test fails in the CI, i dunno why... i just ignored it for now :eyes:

**Comment by devyn** [comment]
I think this probably shouldn't take an `EngineState`, it should always just create a new one. Nuon input should never be affected by anything in the user's environment

**Comment by amtoine** [comment]
> I think `from_nuon()` probably shouldn't take an `EngineState`, it should always just create a new one. Nuon input should never be affected by anything in the user's environment
>
that would be changing the way the implementation of `from nuon` was before this PR, you sure that's ok? :scream:

**Comment by amtoine** [comment]
@devyn 
appears to not harm anyone, so i'll push the commit at least, to have it hanging here :wink: 
could be reverted if need be.

**Comment by devyn** [comment]
> that would be changing the way the implementation of `from nuon` was before this PR, you sure that's ok? 😱

Yeah, I mean... good point, but I really don't think it should be affected.

If you want to keep it I would make it take a `Option<&EngineState>` so you don't have to clone it. you can then use `Cow` within the function to give you an either borrowed or owned engine state

**Comment by amtoine** [comment]
@devyn i think you are right, NUON should not care about the state of the engine, e.g. the PWD does not have anything to do with parsing / serializing NUON

@kubouch might have found why the CI fails, `engine_state` needs to have PWD set
i'll fix it right now

**Comment by amtoine** [comment]
ok lol, `from nuon` appears to be fixed but now, even the tests pass locally, the CI of `nu-nuon` fails :rofl:

**Comment by kubouch** [comment]
I'm fine with landing this, but we can still look into the failing test a bit. The UknnownState error comes from the parser being in some impossible situation. It would be good to at least narrow down from where the error originates.

**Comment by amtoine** [comment]
we talked about this in private with the core team, let's land and we have 10 days before the release to tweak this new crate :wink:

**Pull request merged**
