### PR TITLE
Bump `tabled` dependency to 0.11

### PR DESCRIPTION
**Pull request by zhiburt**
close? #8060

Quite a bit of refactoring took place.
I believe a few improvements to collapse/expand were made.

I've tried to track any performance regressions and seems like it is fine.

I've noticed something different now with default configuration path or something in this regard?
So I might missed something while testing because of this.

Requires some oversight.

### CODE REVIEW

**Comment by fdncred** [comment]
Wow, that is a bunch of changes. Thanks for working on this!

The first thing I've noticed that doesn't seem right is this commnad.
```
$nu | table -e --expand-deep 2
```
It's leaving some table drawing artifacts like this
image

**Comment by zhiburt** [comment]
Could you provide a `term size`? (cause I can't catch right away)

**Comment by fdncred** [comment]
> Could you provide a term size? (cause I can't catch it right away)

```
term size 
╭─────────┬─────╮
│ columns │ 171 │
│ rows    │ 42  │
╰─────────┴─────╯
```

**Comment by zhiburt** [comment]
Must be addressed.
Good catch.

I am thinking maybe it's worth to remove `expand-deep` and expect an optional argument to `--expand`?
```nu
ls | table -e 2
ls | table -e
ls | table --expand=2
ls | table --expand
```

**Comment by fdncred** [comment]
> It's not like this at the moment.
> Nowadats it's expected to set an expand-deep instead.
> I am just saying we could provide the argument right to expand instead, and remove expand-deep (maybe it more intuitive).

Right. I understood what you were saying. What I'm saying is that I'm not sure nushell understands what `--expand=2` means. It would understand `--expand 2` and `-e 2`, of course, but I'm not sure about the `=` sign between the flag and value.

**Comment by zhiburt** [comment]
Added a truncation logic for `table --collapse` (not very well tested).

**Comment by zhiburt** [comment]
It would be interesting to compare performance to the old version.
I bet it must be better (expand/collapse mode included), but not sure.

**Comment by zhiburt** [comment]
cc: @fdncred

**Comment by fdncred** [comment]
@zhiburt I've tested a little and things seem to be fine. are you ready to land?

**Comment by zhiburt** [comment]
I do not see any obstacles.

I just wonder if it's not worth to do something similar to (including wrap/collapse) https://github.com/nushell/nushell/issues/5972#issuecomment-1184646537?

**Comment by zhiburt** [comment]
### `table`

|terminal|main| PR |
|----|----|----|
| alacritty | 250 | 200 |
| wezterm | 300 | 300 |
| xterm-256color | 390 | 310 ||
| xterm | 2200 | 2220 |

### `table -c`

Checked for `$nu` on the same term size (the same output);

|terminal|main| PR |
|----|----|----|
| alacritty | 2305 | 1069 |

### `table -e`

Checked for `$nu` on the same term size (the same output);

|terminal|main| PR |
|----|----|----|
| alacritty | 420 | 220 |

**Comment by fdncred** [comment]
> I just wonder if it's worth to do something similar to (including wrap/collapse) https://github.com/nushell/nushell/issues/5972#issuecomment-1184646537?

It would be nice to have an automated way to do that, but I'm covered up right now.

I'm voting to land this and if we find some regression, we can get your help to fix it or revert. Thanks for upgrading us here @zhiburt. We sincerely appreciate all you do for nushell!

**Comment by fdncred** [comment]
@zhiburt I just noticed that this PR is blocking us from upgrading our rust toolchain to 1.67.1, specifically clippy. Do you think you could support 1.67.1 in tabled?
```
    Checking nu-table v0.79.1 (/home/fdncred/src/forks/nushell/crates/nu-table)
error: the following explicit lifetimes could be elided: 'a
   --> crates/nu-table/src/types/expanded.rs:567:1
    |
567 | fn dive_options<'a, 'b>(opts: &'a Options<'b>, span: Span) -> Options<'b> {
    | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |
    = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#needless_lifetimes
    = note: `-D clippy::needless-lifetimes` implied by `-D warnings`

error: could not compile `nu-table` due to previous error
```

**Pull request merged**
