### PR TITLE
Allow multiple patterns in ls command

### PR DESCRIPTION
**Pull request by PlasmaIntec**
# Description

Related to #6045.

Taking @jntrnr 's advice to read glob patterns as rest arg, then iterating over the rest arg using `.flat_map()` to collect `Value`s.

Currently dealing with `ShellError`s by collecting them in a `vec!` and returning the last one using `.pop()` if there are any. This is suboptimal since it means a command with some successful results fails if there is one failure. I'm open to suggestions here.

# Tests

Make sure you've done the following:

- [x] Add tests that cover your changes, either in the command examples, the crate/tests folder, or in the /tests folder.
- [x] Try to think about corner cases and various ways how your changes could break. Cover them with tests.
- [x] If adding tests is not possible, please document in the PR body a minimal example with steps on how to reproduce so one can verify your change works.

Make sure you've run and fixed any issues with these commands:

- [x] `cargo fmt --all -- --check` to check standard code formatting (`cargo fmt --all` applies these changes)
- [x] `cargo clippy --workspace --features=extra -- -D warnings -D clippy::unwrap_used -A clippy::needless_collect` to check that you're using the standard code style
- [ ] `cargo test --workspace --features=extra` to check that all the tests pass

I have four tests failing but they are failing on the `main` branch as well:
```
failures:
    path::canonicalize::canonicalize_nested_symlink_relative_to
    path::canonicalize::canonicalize_nested_symlink_within_symlink_dir_relative_to
    path::canonicalize::canonicalize_symlink
    path::canonicalize::canonicalize_symlink_relative_to
```

### CODE REVIEW

**Comment by fdncred** [comment]
Doesn't vec.pop() just show us the last error? It would be nice to see all the errors that occurred.

**Comment by PlasmaIntec** [comment]
Are there examples of other commands which display all errors?

For example, the following command seems to quit at the first instance of an error:

```
[1, 2, 3] | each { |it| $it | from json }
```

**Comment by fdncred** [comment]
If you're saying it quits after the first error, then that's fine. I must of read the code wrong. I thought it was completing everything, perhaps having a dozen errors and listing 20 files and then just showing 1 error.

**Comment by PlasmaIntec** [comment]
Is there anything else I should complete to finish addressing this issue?

**Comment by fdncred** [comment]
> Is there anything else I should complete to finish addressing this issue?

Please explain to me how the error reporting works. Does `ls` stop after the first error? Does it keep going and report all errors at the end? Does it do something in between these two options?

**Comment by PlasmaIntec** [comment]
Currently, if any errors are encountered, the first error is reported and the pipeline is broken

**Comment by fdncred** [comment]
thanks for answering my questions. let's land this.

**Pull request merged**
