### PR TITLE
add the ability to time commands

### LINKED ISSUE #3080: Expose duration of the last command that was run
**Is your feature request related to a problem? Please describe.**

I believe currently there is no way to get the duration of the last command that was run. This is useful information for a prompt to have for a prompt (#2733) and I imagine there could be uses for this.

Here's an overview of how some approaches other shells have taken:

**Ion/Fish:**
Expose duration of the last command as an environment variable (for example `$CMD_DURATION`).

**Powershell:**
Expose duration information with the history command.

Powershell sample:

```powershell
if ($lastCmd = Get-History -Count 1) {
    $duration = [math]::Round(($lastCmd.EndExecutionTime - $lastCmd.StartExecutionTime).TotalMilliseconds)
}

```

**Most other shells:**
Calculate duration with pre- and post-command hooks.

Elvish sample:
```
local:cmd-start-time = 0
local:cmd-end-time = 0

fn starship-after-readline-hook [line]{
    cmd-start-time = (starship time)
}

fn starship-before-readline-hook {
    cmd-end-time = (starship time)
}

edit:after-readline = [ $@edit:after-readline $starship-after-readline-hook~ ]
edit:before-readline = [ $@edit:before-readline $starship-before-readline-hook~ ]

edit:prompt = {
   if (!= $cmd-start-time 0) {
    $duration = (- $cmd-end-time $cmd-start-time)
  }
}
```

**Describe the solution you'd like**
I think exposing it as an environment variable is the best solution because all the other solutions come with quite a bit of boilerplate which will likely need updating in the future and it looks like it would be hard to update this at runtime in nu.

**Additional context**
This is not yet possible in nu:

```
~
❯ sleep 3

~ took 3s
❯
```

### PR DESCRIPTION
**Pull request by fdncred**
This closes #3080 

This PR should allow nushell to time all commands and store the results in the `$nu.env.CMD_DURATION` environment variable. 

image

@andrasio @jonathandturner can you please look at this. I know you've been working on env var things and I just want to make sure this is compliant with how you want to handle env vars going forward.

### CODE REVIEW

**Comment by fdncred** [comment]
I don't get the test failures when running locally. Not sure what's going on.

**Comment by fdncred** [comment]
First failure in CI was because of `syncs_env_if_new_env_entry_is_added_to_an_existing_configuration` so I restarted the tests and `quickcheck_parse` is failing but the sync test is passing. Something wiggy is going on.

image

**Comment by fdncred** [comment]
Third time's a charm. I wonder why all the failures?

**Comment by jonathandturner** [comment]
There's a parsing bug this is catching. We should file it so we can fix it later.

**Pull request merged**
