### PR TITLE
Upgrade to interprocess 2.0.0

### LINKED ISSUE #12724: 0.93.0 compilation failure on NetBSD current
### Describe the bug

0.93.0 fails to compile on NetBSD x86_64 with:
```
error[E0432]: unresolved import `libc::xucred`
  --> /usr/pkgsrc/wip/nushell/work/vendor/interprocess-1.2.1/src/os/unix/imports.rs:45:24
   |
45 |         pub(super) use libc::xucred;
   |                        ^^^^^^------
   |                        |     |
   |                        |     help: a similar name exists in the module: `uucred`
   |                        no `xucred` in the root

   Compiling parking_lot_core v0.9.9
For more information about this error, try `rustc --explain E0432`.
error: could not compile `interprocess` (lib) due to 1 previous error
warning: build failed, waiting for other jobs to finish...
```

### How to reproduce

Source build of the new 0.93.0 release. v0.92.2 compiles without issues.

### Expected behavior

Successful build.

### Screenshots

NA

### Configuration

NA

### Additional context

```
~> name -rsv
NetBSD 10.99.10 NetBSD 10.99.10 (GENERIC) #0: Thu Apr 25 22:39:14 CEST 2024  pin@mybox:/home/pin/obj/sys/arch/amd64/compile/GENERIC
~> pkg_info | grep rust
rust-1.77.2         Safe, concurrent, practical language
```

### PR DESCRIPTION
**Pull request by devyn**
# Description

This fixes #12724. NetBSD confirmed to work with this change.

The update also behaves a bit better in some ways - it automatically unlinks and reclaims sockets on Unix, and doesn't try to flush/sync the socket on Windows, so I was able to remove that platform-specific logic.

They also have a way to split the socket so I could just use one socket now, but I haven't tried to do that yet. That would be more of a breaking change but I think it's more straightforward.

# User-Facing Changes

- Hopefully more platforms work

# Tests + Formatting
- :green_circle: `toolkit fmt`
- :green_circle: `toolkit clippy`
- :green_circle: `toolkit test`
- :green_circle: `toolkit test stdlib`

# After Submitting

### CODE REVIEW

**Review by sholderbach — COMMENTED** [review]
Sounds good to me, appreciate the simplification on the dependency side.

We have to keep in mind that the [`interprocess` crate also has limited testing](https://docs.rs/interprocess/latest/interprocess/#platform-support) for our [non-explicit targets](https://github.com/nushell/nushell/blob/main/devdocs/PLATFORM_SUPPORT.md#passively-supported-platforms) like the BSDs or android

**Comment by devyn** [comment]
That's good to know. I think I'm going to make a note of trying to do a bit more second-tier platform testing before releases, since I've got the VMs now anyway. Just need to set something up for Termux because I don't want to compile it on my phone every time :wink:

**Comment by 0323pin** [comment]
I could do weekly builds on NetBSD and perfom a minimal tests, if this is helpful. Although, I'd have additional interest if https://github.com/nushell/nushell/issues/8461 got fixed 😉

**Comment by 0323pin** [comment]
Thanks!

**Pull request merged**
