### PR TITLE
Patch restore lead trail space bg color

### PR DESCRIPTION
**Pull request by zhiburt**
```nu
 $env.config.color_config.leading_trailing_space_bg = { bg: 'white' }; [[a b, 'c   ']; ['  1  ' '    2' '3    '] ['  4  ' "hello   \n  world  " ['  1  ' 2 [1 '  2  ' 3]]]] | table --expand
```

image

ref: #2794
close: #10317

note: test are not actually make scenes cause `nu!` strips colors. (Ideally it would need a flag to not do so)
note: It does does does ... slower down quite a bit rendering... (

PS: Maybe it's better being a flag to `table` rather then a configuration option?
PS: I am not sure why the logic was removed in a first place

### CODE REVIEW

**Comment by fdncred** [comment]
Thanks @zhiburt! Thanks for the research and digging up my old code. The reason I made this a config option was to specify the color. I made the original change a long time ago and things have changed since then. 

Do you think having it as a table flag would make it faster? If so, I'd be willing to do that, as long as we can pass the 3 types of colors we use in config with the flag. e.g named colors like `red`, hex colors like `'#00ff00'`, and record colors like `{fg: red, bg: '#0000ff', attr: u}`.

**Comment by fdncred** [comment]
I think the strange table behavior is only with `$env.config.table.header_on_separator = true`.

Let's land this for now and we can address the header_on_separator thing separately. Also, we can investigate whether moving this to the `table` command helps speed.

**Comment by zhiburt** [comment]
> I think the strange table behavior is only with $env.config.table.header_on_separator = true.

Ahhhh;

So it's caused by expectation that header on border does not contain any colors, and be set afterwards only to a single one.

Primarily the reason is to not check color per symbol.

I don't know which way it's better be fixed.
The easiest is to disallow custom colors in header.

**Comment by hustcer** [comment]
Any way to set `$env.config.color_config.leading_trailing_space_bg` to transparent? Thanks

**Comment by fdncred** [comment]
We can disallow for now and come back to it later if needed.

**Pull request merged**
