### PR TITLE
Changes to allow plugins to be loaded in a multi-threaded manner

### PR DESCRIPTION
**Pull request by fdncred**
Changes to allow plugins to be loaded in a multi-threaded manner in order to decrease startup time.

Pay particular attention to `cli.rs` `load_plugins()`. This is where the multi-threading takes place. I'm not sure if what I'm doing on line 150 with the map function is right, specifically the None and else returns.

I also have question about Arc Mutex I'm using and whether that is proper on line 133.

As well as how I'm calling `load_plugin()` on line 194.

I'm assuming more work is needed. I'm just not sure I can do it myself.

### CODE REVIEW

**Comment by jonathandturner** [comment]
Looking through the errors on the PR, you may want to run a few tools to help go green.

* installing `rustup component add rustfmt` and then `cargo fmt` should get rid of the formatting errors
* after that you probably also want to do `rustup component add clippy` followed by `cargo clippy --all --features=stable` and then fix the warnings that clippy gives

**Comment by fdncred** [comment]
Finally figured out how to use clippy and fmt. No failures at least however that doesn't mean the code is correct. :)

**Comment by jonathandturner** [comment]
This looks like the right idea to me. A couple thoughts:

* Context is already protected with Arc on the inside, so in theory you should be able to copy between threads.  Did you have issues with it that required you to create a new lock outside?
* For locking, I think we might want to run the plugin, get its information back, and only then lock the context and update it with what we found out.  If we lock it from outside load_plugin, this will effectively serialize each plugin being loaded and we won't get the wins from being parallel that we probably want. Luckily, this is already done for us by `load_plugin`, which calls the helper methods when we insert a command, and those do their own locking.

**Comment by fdncred** [comment]
* Regarding Context & the new Arc - Yes, I had issues. Those issues being that I couldn't compile without it.
* For locking, again, this is all I could come up with which is why I wrote in the original PR that someone know has a clue about this should modify it. I'm not arguing that what you're saying isn't the right thing to do. I'm saying, I'd like to make it work the way you want it to, I'm just not sure what to change. Perhaps if we discuss some on discord I will understand.
* Regarding the IDE files, I have to have them for vscode so I added a .gitignore change so I can keep them and they don't make it into the repo.

Regarding the speed of load with this change - we're down from 3 seconds originally before is_file() was removed to 0.5 - 0.8 with this change.

**Comment by jonathandturner** [comment]
Looks like the tests all pass, landing.

**Comment by jonathandturner** [comment]
Thanks!

**Pull request merged**
