### PR TITLE
Added document for tree command

### PR DESCRIPTION
**Pull request by akramkazmi71**
For the issue [711](https://github.com/nushell/nushell/issues/711), added a new document for tree command.

### CODE REVIEW

**Comment by akramkazmi71** [comment]
@andrasio can you please help me, how can I resolve these errors?

**Comment by jonathandturner** [comment]
You can ignore the CI error. I just fixed that this morning.

For your example, can you use a small example?  This one is quite big.

**Comment by jonathandturner** [comment]
Also, it looks like you're documenting the `tree` command from outside of Nushell?  Nushell has its own tree command that will display the table as a tree.  

If you build with `cargo build --all-features` you'll see the tree command when you run `help tree` inside of Nushell.

**Comment by andrasio** [comment]
@akramkazmi71 Please read again the instructions for writing documentation carefully. This is no the `tree` Nu command. Closing this for now, feel free to make changes required and reopen!

Thanks!

**Pull request closed without merging**
