### PR TITLE
Add storing and setting metadata

### PR DESCRIPTION
**Pull request by KoviRobi**
Hi!

# Description
Sorry I didn't do the chat on discourse thing, I just saw #7368 and I had an idea on how to improve it without adding metadata everywhere, which would be a big refactor.

The biggest change is probably in adding `let-with-metadata` to the parser -- I'm not sure if there is a more elegant way of doing this, seems a bit code duplication-y -- but the same problem also exists with `mut` and `let`/`const`.

I've also currently not made `metadata` into a value, just use the record representation of metadata, which does allow users to create metadata including bad metadata. This is currently just ignored:

```console
❯ echo | set-metadata {source: ls} | metadata
╭────────┬────╮
│ source │ ls │
╰────────┴────╯

❯ echo | set-metadata {source: foo} | metadata


❯ echo | set-metadata {source: foo} | metadata | describe
record
```

I've also used [`strum`](https://docs.rs/strum/latest/strum/index.html) for convenience, but it wouldn't be difficult to replace it and implement the to/from string myself.

Also the stringification of the `HtmlThemes` was incorrectly `into html --list` not `to html --list`.

# User-Facing Changes

- Add a builtin `let-with-metadata <var name> <metadata-var-name> = <expression>` to capture the metadata *and* the value
   - This is because you can currently capture one or the other, but not both, e.g. if you do
      ```
      let data = $in
      let metadata = ($in | metadata)
      ```
      then the input stream gets consumed so you can't get it's metadata -- and vice versa

- Add `set-metadata` to be able to assign metadata to pipelines

# Tests + Formatting

Don't forget to add tests that cover your changes.

Make sure you've run and fixed any issues with these commands:

- [x] `cargo fmt --all -- --check` to check standard code formatting (`cargo fmt --all` applies these changes)
- [x] `cargo clippy --workspace -- -D warnings -D clippy::unwrap_used -A clippy::needless_collect` to check that you're using the standard code style
- [ ] `cargo test --workspace` to check that all tests pass
   - The two failing tests are https://github.com/nushell/nushell/issues/4100#issuecomment-1414332678 and related to me having a terminal emulator called `st`.
   - I've rebased and switched computers, and on this computer there are other test failures in the `all`/`any` examples tests -- investigating

# After Submitting

If your PR had any user-facing changes, update [the documentation](https://github.com/nushell/nushell.github.io) after the PR is merged, if necessary. This will help us keep the docs up to date.

### CODE REVIEW

**Comment by KoviRobi** [comment]
I was going to suggest
```
def lsi [] {
  let-with-metadata data md = ls;
  $data | sort-by type name -i | set-metadata $md
}
```
but seems like even the following works
```
def lsi [] { ls | sort-by type name -i }
```
so it seems this is to do with the parentheses (as just `(ls | sort-by type name -i)` loses the metadata too)

**Comment by kubouch** [comment]
To me, extending the language seems too heavyweight for something that is intended as more like an implementation detail. Ideally, the metadata should stay hidden from the programmer.

There is some discussion about it in the [previous attempt](https://github.com/nushell/nushell/pull/7689). We plan to refactor the engine and change how spans are stored and a similar system might be used for metadata as well.

**Comment by fdncred** [comment]
I tend to agree with kubouch. I think this is an innovative idea and really "thinking outside the box" but I'm not sure I want to require people to mess with metadata this way. It should just be invisible to end users. This type of stuff should "just work" without having to think about it.

I appreciate you changing the `lsi` alias into a custom command for demonstration purposes. However, we can't just ignore aliases. (I also never considered that `(` and `)` were the cause of losing the color in aliases. Good find.) Our future fix, whatever that looks like, for this needs to include aliases and custom commands.

**Comment by KoviRobi** [comment]
That's fair! In the meanwhile I also realised there is a much more elegant solution to this, get rid of `let-with-metadata` and modify `metadata` so that it has a flag to also return the data (and keep `set-metadata`). This would get rid of all the parser changes, just adding a flag to `metadata` and adding the `set-metadata` command. Would this be lightweight enough?

**Comment by fdncred** [comment]
I'm still on the fence about this. Let's see what others think.

**Comment by kubouch** [comment]
Yeah, I'm not too much into it either. Nushell is already complicated and if we added manual handling of metadata, that would introduce another level of complexity for users to track. If we add it just as a temporary solution, then removing it later would create a breaking change, and we'd need to maintain it until then. So, I'd lean towards not merging this and rather concentrating on how it could be done without requiring user's attention.

**Comment by KoviRobi** [comment]
Sure well I can always maintain this on my fork, it's not a huge set of changes

**Pull request closed without merging**
