### PR TITLE
IDE style completion

### PR DESCRIPTION
**Pull request by maxomatic458**
# Description

Adds an IDE-Style completion menu
grafik

# User-Facing Changes

# Tests + Formatting

# After Submitting

### CODE REVIEW

**Comment by fdncred** [comment]
nice work. do you think you could add a menu in the default_config.nu file so people know how to use this. maybe put the menu on some other keybinding?

**Comment by maxomatic458** [comment]
i tried using shift+tab as keybind but that doesnt seem to work for some reason, i think ill use ctrl+w

**Comment by fdncred** [comment]
> i tried using shift+tab as keybind but that doesnt seem to work for some reason, i think ill use ctrl+w

ya, shift+tab maps to backtab i think so you can tab through a list and shift+tab to go backwards through it. i'm fine with ctrl+w as long as it doesn't conflict with anything.

**Comment by fdncred** [comment]
looks like control char_w is already for twice with
```
        {
            name: delete_one_word_backward
            modifier: control
            keycode: char_w
            mode: [emacs, vi_insert]
            event: {edit: backspaceword}
        }
```
and this for emacs
```
        {
            name: cut_word_left
            modifier: control
            keycode: char_w
            mode: emacs
            event: {edit: cutwordleft}
        }
```

**Comment by maxomatic458** [comment]
i changed it to crtl+n now (which isnt used by anything else)
probably not the most convinient, but i guess if people want to use the ide menu, they will just map it to tab

**Comment by fdncred** [comment]
ya, it's not about convenience in the default_config.nu. It's just to show people how to use it. Thanks!

**Pull request merged**
