### PR TITLE
Ensures that non-strings are not unnecessarily quoted

### PR DESCRIPTION
**Pull request by merelymyself**
# Description

Intended to resolve issue #5472. By performing rigorous check that a string needs to be escaped. 

The primary issue comes with negative numbers.

# Tests

Make sure you've run and fixed any issues with these commands:

- [x] `cargo fmt --all -- --check` to check standard code formatting (`cargo fmt --all` applies these changes)
- [x] `cargo clippy --all --all-features -- -D warnings -D clippy::unwrap_used -A clippy::needless_collect` to check that you're using the standard code style
- [x] `cargo build; cargo test --all --all-features` to check that all the tests pass

### CODE REVIEW

**Comment by merelymyself** [comment]
@uasi , I think this should fix it - could you take a look? It collects the types and if it is 'math', 'number' or 'int' it sends the negative number on with quotes.

**Comment by uasi** [comment]
@merelymyself Thank you for the hard work, but I've come to think that simply making quoting smarter does not solve the overall problem (see https://github.com/nushell/nushell/issues/5472#issuecomment-1122051663 ). It appears it requires the argument evaluation semantics need to be redesigned at a deeper level of the language. Please contact one of the core devs, as I'm just a new-ish contributor.

**Comment by merelymyself** [comment]
@uasi I honestly think you might be right, it may be better in the long-run to redesign the argument evaluation semantics. The whole of `deparse.rs` feels like a band-aid. That said, I think it may be better to keep the bandaid on for the moment. I suggest you open an issue on this.

**Comment by jntrnr** [comment]
I also think I agree with uasi. The problem with the argument parsing we do now is that it feels very much "solve one case but unfortunately break another case". With a rewrite, we can start by making sure we have all the cases we want to cover first, and then make sure the parser and the parts that deal with args all understand it.

**Comment by fdncred** [comment]
how do we move forward on this? should we close this PR and talk about it in design-discussion or land this and continue to try and make it better?

**Comment by merelymyself** [comment]
closing this for the moment.

**Pull request closed without merging**
