### PR TITLE
Tweak auto-rotate for single row output

### PR DESCRIPTION
**Pull request by fdncred**
added helper to convert value data to strings
added ability to auto-rotate single row output
if row will be greater than terminal width

### CODE REVIEW

**Comment by jonathandturner** [comment]
cc @wycats 

I had mentioned building heuristics around this, but I think someone (@wycats maybe?) explained to me that rotating sometimes and not others was a bad experience for some people with various cognitive processing styles.  Yehuda - do you remember the line of reasoning there?

It'd make sense to have some some logic here as the space is constrained, if there's a way to do it that isn't too confusing for people.

**Comment by fdncred** [comment]
From my perspective, I'd like this to be configurable. I just wasn't sure how to do that. But if you think about it, `echo $nu.env` is always wider than my terminal so I want it to display pivoted but `date` always fits within my terminal so I want it to display 'normally'. 

I think the *real* fix to this is to have a pager like was mentioned in discord that allows you to page horizontally and vertically and freeze horizontal and vertical panes.

**Comment by jonathandturner** [comment]
@fdncred - that's a good idea. We could have "pivot-to-fit" or something as a setting.  If that's turned on, we can use the heuristic you have.

I agree the pager is the long-term solution here.

**Comment by fdncred** [comment]
@jonathandturner How about now? I added the pivot_to_fit config setting.

**Comment by fdncred** [comment]
@jonathandturner Not sure what the failure is about. I run `cargo fmt` and nothing appears to happen.

**Comment by jonathandturner** [comment]
Looks good!

**Pull request merged**
