### PR TITLE
Fix parser crashes on `..=..`

### PR DESCRIPTION
**Pull request by hanjunghyuk**
# Description

See also: #9417 

Range has the following syntax: `[<from>][<next_operator><next>]<range_operator>[<to>]`
Where <next_operator> only accepts `..`.

This PR takes care of `..=` in <next_operator> just like `..<` so it doesn't panic.

Before:
```
$ [0,1,2,3,4,5] | range ..=.
thread 'main' panicked at 'slice index starts at 28 but ends at 27', crates/nu-protocol/src/engine/engine_state.rs:1430:29
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
``` 

After:
```
$ [0,1,2,3,4,5] | range ..=..
Error: nu::parser::parse_mismatch

  × Parse mismatch during operation.
   ╭─[entry #5:1:1]
 1 │ [0,1,2,3,4,5] | range ..=..
   ·                       ──┬──
   ·                         ╰── expected inclusive operator preceding second range bound
   ╰────
``` 
# User-Facing Changes

# Tests + Formatting

# After Submitting

### CODE REVIEW

**Comment by hyiltiz** [comment]
Is it preferable to have a runtime crash rather than wrapping the parser with error capture to avoid crashing just because a dark spell (like this one) has been typed? I wonder if there is a systematic way to iron out all parser edge cases.

**Comment by hyiltiz** [comment]
Can replicate the runtime crash in `main` build.

**Comment by amtoine** [comment]
@hanjunghyuk 
i'm not sure i understand what `..=..` should mean :thinking: 

EDIT: oooh, you are giving an error now, because this does not mean anything, right?

**Review by amtoine — CHANGES_REQUESTED** [review]
one less panic is great i guess :yum: 

i'm not familiar with the parser of Nushell, so i wouldn't be able to comment on that really, but at least i think we need a test to make sure we always get the right error when using `..=..` with `range` :yum:

**Review by amtoine — COMMENTED** [review]
thanks for the new tests @hanjunghyuk :blush:

**Comment by anka-213** [comment]
why was this closed without merging?

**Comment by amtoine** [comment]
@anka-213 
i think the author's account was deleted :scream: 
this is what @ghost is all about :cry:

**Pull request closed without merging**
