### PR TITLE
create clickable links in ls output if configured

### LINKED ISSUE #6307: Hyperlink files/dirs in ls
### Related problem

lsd (and I believe exa) provides a config option to add hyperlinks to all `ls` results.

The user may then use whatever their terminal's hyperlink interaction process is to open those links. (Ctrl+Click for Windows Terminal, Cmd+Click for iTerm2, etc) From there you let the OS determine how it wants to handle things.

It's really convenient.

### Describe the solution you'd like

For each file, append `file:///` to the beginning of the file's/dir's full path, URL-encode any wayward characters, and then use that as the URL in the hyperlink.

image

### Describe alternatives you've considered

Just use lsd lol. The problem is that Nushell's tabling is so damn sexy that I don't want to give it up <3

### Additional context and details

_No response_

### PR DESCRIPTION
**Pull request by fdncred**
# Description

This PR introduces clickable links in the `ls` table output if your terminal supports it. I'm not really sure if we should have this or not, but there was a request for it (#6307) so I thought we could try it out.

image

closes #6307 

# Tests

Make sure you've done the following:

- [ ] Add tests that cover your changes, either in the command examples, the crate/tests folder, or in the /tests folder.
- [ ] Try to think about corner cases and various ways how your changes could break. Cover them with tests.
- [ ] If adding tests is not possible, please document in the PR body a minimal example with steps on how to reproduce so one can verify your change works.

Make sure you've run and fixed any issues with these commands:

- [x] `cargo fmt --all -- --check` to check standard code formatting (`cargo fmt --all` applies these changes)
- [x] `cargo clippy --workspace --features=extra -- -D warnings -D clippy::unwrap_used -A clippy::needless_collect` to check that you're using the standard code style
- [x] `cargo test --workspace --features=extra` to check that all the tests pass

### CODE REVIEW

**Comment by kubouch** [comment]
I like this feature. I'm just wondering: It seems to make use ansi sequences, right? I'm asking because we had some troubles with `find` spitting out ansi escapes that need to be stripped with commands like `rm`, etc. There is a PR that uses metadata for `find` which seems like a cleaner solution to me. Shouldn't this also use metadata instead of directly outputting ansi escapes? I'm worried we'd run into the same problem as with `find`.

**Comment by fdncred** [comment]
> It seems to make use ansi sequences, right?

@kubouch, yes, you are correct, it uses ansi escape sequences. 

>  Shouldn't this also use metadata instead

I figured I'd leave that to @panicbit 😆. 

Since that PR isn't in place yet, this is done "old-style". We also need to vet that solution and ensure it works as prescribed and there's little-to-no performance impact.

**Comment by panicbit** [comment]
@fdncred As the change seems to be confined to the table viewer, I have no objections against the ansi escape sequences here 😅

**Comment by kubouch** [comment]
Ah yeah, it seems to be done on the `table` output. That should be fine, then. I just wanted to avoid breaking `ls | each {|it| rm $it.name }`.

**Comment by ehawman** [comment]
@fdncred Thank you for your work on this! I really appreciate it.
❤️

**Pull request merged**
