### PR TITLE
Get rid of header bold option

### LINKED ISSUE #4072: Unnecessary "header_bold" config option
### Describe the bug

`header_bold` is an unnecessary configuration point. To make header a bold text it should follow the other config point styles i.e. use `header_color` and set with `red_bold`

### How to reproduce

1. [See documentation](https://www.nushell.sh/book/configuration.html#nushell-configuration-with-config-toml)

2. Go to the Color Config Section

3. Note: 

Name | Purpose | Value Type
-- | -- | --
header_bold | Enable/Disable bold for the header | string
header_color | Apply a color to the header | string

### Expected behavior

`header_bold` config point is obsolete and should be removed. It should be done the same way `index_color` or a `primitive_#` is done.

Example:
```
header_color = "cyan_bold"
```

### Screenshots

_No response_

### Configuration

_No response_

### Additional context

Also it is set as a `string` when it should be a `boolean`, though this does not matter.

### PR DESCRIPTION
**Pull request by oscard0m**
# Description
- Get rid of `header_bold` option (use `<color>_bold` instead)
- Update docs removing mentions to `header_bold`

# Context
Fix #4072 

# How has been this tested?
Run nushell: `cargo run --release --features=extra -- --loglevel trace` and run an `ls` as a test

### CODE REVIEW

**Comment by fdncred** [comment]
would you mind updating 'the book' too with this change? https://github.com/nushell/nushell.github.io/blob/master/book/configuration.md

**Comment by fdncred** [comment]
let's just make this a draft until you can get back to it. @oscard0m 
@jntrnr let's just leave the docs update for now. if we get questions we can point them here.

**Comment by oscard0m** [comment]
> let's just make this a draft until you can get back to it. @oscard0m @jntrnr let's just leave the docs update for now. if we get questions we can point them here.

After doing a bit of debugging it seems like the result when getting `head_color` and `head_bold` is `{}` but, in `main` branch, the logic applied when the color obtained is `{}`, is to apply `bold: true` by default: https://github.com/nushell/nushell/blob/75782f0f50e81c8a73ce6e6ccf6b7fd73dc0f7a4/crates/nu-command/src/commands/viewers/table/options.rs#L88

---

For my personal knowledge and understanding, I would like to ask if this is correct. In the end the value from default color is being overwritten with true.

@fdncred

**Comment by jntrnr** [comment]
Looks good!

**Pull request merged**
