### PR TITLE
Make $nothing | into string == ""

### PR DESCRIPTION
**Pull request by pejato**
# Description

Makes `$nothing | into string` yield empty string per discussion on [the original PR](https://github.com/nushell/nushell/pull/3969)

# Tests

Not sure about adding a test to cover this, I saw some tests in `crates/nu-command/tests/commands/str_/into_string.rs` but got test & compilation failures when I enabled the tests there..

### CODE REVIEW

**Comment by pejato** [comment]
cc @kubouch

**Comment by kubouch** [comment]
Thanks! Sorry it took so long :-D . 

What kind of failures did you get when enabling the tests?

**Comment by pejato** [comment]
I'll paste the output.

`from_range` fails due to whitespace differences:
```
cargo test --package nu-command --test main -- commands::str_::into_string::from_range --exact --nocapture <
...
thread 'commands::str_::into_string::from_range' panicked at 'assertion failed: `(left == right)`
  left: `"[  \"1\",  \"2\",  \"3\",  \"4\",  \"5\"]"`,
 right: `"[\"1\",\"2\",\"3\",\"4\",\"5\"]"`', crates/nu-command/tests/commands/str_/into_string.rs:15:5
```

The next two output tables instead of plain old strings.

`from_filename`:
```
cargo test --package nu-command --test main -- commands::str_::into_string::from_filename --exact --nocapture <
...
thread 'commands::str_::into_string::from_filename' panicked at 'assertion failed: `(left == right)`
  left: `"╭───┬─────────────╮│ 0 │ sample.toml │╰───┴─────────────╯"`,
 right: `"sample.toml"`', crates/nu-command/tests/commands/str_/into_string.rs:87:9
```

`from_filesize`:
```
cargo test --package nu-command --test main -- commands::str_::into_string::from_filesize --exact --nocapture <
...
thread 'commands::str_::into_string::from_filesize' panicked at 'assertion failed: `(left == right)`
  left: `"╭───┬──────╮│ 0 │ 25 B │╰───┴──────╯"`,
 right: `"25 B"`', crates/nu-command/tests/commands/str_/into_string.rs:107:9
```

These last 3 fail due to the leading `=`, I'm actually unsure why it's there.

`from_decimal_correct_trailing_zeros`:
```
cargo test --package nu-command --test main -- commands::str_::into_string::from_decimal_correct_trailing_zeros --exact --nocapture <
...
Error: nu::shell::external_command (https://docs.rs/nu-protocol/0.62.1/nu_protocol/enum.ShellError.html#variant.ExternalCommand)

  × External command
   ╭─[source:1:1]
 1 │ = 1.23000 | into string -d 3
   · ┬
   · ╰── can't run executable
   ╰────
  help: No such file or directory (os error 2)
```

`from_int_decimal_correct_trailing_zeros`:
```
cargo test --package nu-command --test main -- commands::str_::into_string::from_int_decimal_correct_trailing_zeros --exact --nocapture <
...
Error: nu::shell::external_command (https://docs.rs/nu-protocol/0.62.1/nu_protocol/enum.ShellError.html#variant.ExternalCommand)

  × External command
   ╭─[source:1:1]
 1 │ = 1.00000 | into string -d 3
   · ┬
   · ╰── can't run executable
   ╰────
  help: No such file or directory (os error 2)
```

`from_int_decimal_trim_trailing_zeros`:
```
cargo test --package nu-command --test main -- commands::str_::into_string::from_int_decimal_trim_trailing_zeros --exact --nocapture <
...
Error: nu::shell::external_command (https://docs.rs/nu-protocol/0.62.1/nu_protocol/enum.ShellError.html#variant.ExternalCommand)

  × External command
   ╭─[source:1:1]
 1 │ = 1.00000 | into string | format "{$it} flat"
   · ┬
   · ╰── can't run executable
   ╰────
  help: No such file or directory (os error 2)
```

**Comment by fdncred** [comment]
this test `from_range` should probably use raw json `to json -r`.
this test `from_filename` should probably be `ls Cargo.toml | get name | into string | get 0`
this test `from_filesize` should probably be `ls Cargo.toml | get size | into string | get 0`
this test `from_decimal_correct_trailing_zeros` should have the `=` removed
this test `from_int_decimal_correct_trailing_zeros` should have the `=` removed
same for the other one with `=`

**Comment by pejato** [comment]
Nice, thank you @fdncred , that fixes all but `from_int_decimal_trim_trailing_zeros` which complains further that `Input data is not supported by this command.` when trying to pipe the string into format:
```
1.00000 | into string | format "{$it} flat"
```

**Comment by fdncred** [comment]
how about this `1.0000 | into string | $"($in) flat"`? format apparently doesn't work the same as it used to. or you may be able to get this to work too `1.0000 | into string | wrap num | format '{num} flat'`

**Comment by pejato** [comment]
Sweet, thanks for the tips @fdncred ! These tests are enabled & fixed up and I also added another for the `$nothing | into string` case.

**Comment by pejato** [comment]
Looks like the filesize test failed here due to differing line endings between Windows & Linux/MacOS. I just updated that test to use a `cfg!(windows)` to make it pass, hopefully that's acceptable.

**Comment by kubouch** [comment]
OK, nice, thanks!

I think the starting `=` might be a relict from the past where we used it to denote math operations.

**Pull request merged**
