### PR TITLE
add 'int' command

### PR DESCRIPTION
**Pull request by ilius**
To convert any type/value that can be converted to integer.
(Like `int` built-in function in Python or similar function in other scripting languages)
Either in a table, or array or just a primitive (with `echo`)

### CODE REVIEW

**Comment by jonathandturner** [comment]
@ilius - I wonder if `into` would fit a bit better, so you could have `into int` for the int things here, or `into string`, `into bool` etc

**Comment by ilius** [comment]
It makes it harder to type.
What is the benefit?

Dynamically-typed languages like Python (and some statically-typed like Go) generally have functions like `int`, `float` etc.
Ruby has `to_i`, `to_f` which is not as clean, PHP has `intval` and `floatval`.
Python generally has the cleanest most-readable syntax and naming.

Maybe `str` is an exception because there are so many string operation (it's the equivalent of [Go's strings package](https://golang.org/pkg/strings/)).
But we already have `math` command for numeric operations, so there is nothing else to reserve `int` command for.

PS: I wrote an [`eval` plugin in Python](https://github.com/ilius/nu-addons/blob/main/plugins/nu_plugin_eval) that evaluates any Python expression.
We can write something similar in other languages including Rust, so that we can write much more extensive filters (compared to our `where` command), or formulas to create new columns, maybe even Excel formulas.
I don't see why we should have a super command `into` for a simple basic type conversion.

**Comment by jonathandturner** [comment]
@ilius - something that we'll be working on as Nushell grows is to be able to import from modules. This would let you potentially import something called `int` from a module that was used for doing type conversions.

We can also include aliases like this in the standard library.

For now, it's better to be a little larger with the idea that we could simplify it later. The larger name is easier to find and easier for people to use auto-completion to learn more (where as just calling it `int` doesn't give that to you).

**Comment by ilius** [comment]
We already have a `to` command.
And `into` sounds the same, and doesn't tell the user that it converts the type of cells, not the whole table.
But the name `int` makes it clear that it converts the type of primitives.
It makes more sense, so it's easier to find and remember (like Python and Go).

I don't see how auto-completion would be different.
You either type `int` and then column names.
Or type `into` press tab that (currently fills up `int`).
Either way we can have auto-completion for the column names later, which is implemented outside the command (arg types are ColumnPath).

We also have `into-int` which should be removed I think, for several reasons:
- It only converts filesize to int, and can be replaced with this PR.
- It only accepts the input as arguments like `into-int 10kb`, so you have to use `each` to use it for tables and arrays, which makes it harder and slower.

And we have `str to-int` which has the same problems as `into-int`.

For example how do you find `str to-int` without looking at the manual?
You have to guess it's done with `str` command and run `str -h` (there is no auto-completion for sub-commands of `str`).
Using same command name as the type (int) just makes sense and makes it easy to find.
We don't have so many primitives that can be converted from several data types (I can only think of `int` and `decimal`)

**Comment by jonathandturner** [comment]
Yes, we should be able to remove some of the old commands as improved commands are added. `str` is a good example of a command that needs to be reworked. It's not in the final state.

That said, we'd still like to put commands that are related together so that as we find a good home for them they're easy to discover.

Happy to chat more about this on discord to fill you in more on some of the plans going on.

**Comment by fdncred** [comment]
my vote would be to merge `int` and `into-int` into `into int` (`into` command, `int` subcommand). i'd like to have `into all_the_primitives` to try and standardize things a bit more this way.

@ilius it's interesting that you say this

> But the name int makes it clear that it converts the type of primitives.

because i had to look at the code to figure out what `int` would do - lol. 

i'm still learning that: 
1. not everyone agrees with what I think is intuitive 
2. just because something is intuitive to a certain mindset and background, doesn't mean it's good for nushell

for instance, i still wish `first` was named `top` like in sql, but now that we have aliases, it's easy for me to have `top` and everyone else have `first`.

**Comment by fdncred** [comment]
@ilius side note - i love what you're doing here https://github.com/ilius/nu-addons/blob/main/functions.nu and the other nu files in that folder. very cool! makes me think about having stdlib functionality.  do you `source` those in your nushell config.toml?

**Comment by ilius** [comment]
>  do you source those in your nushell config.toml?
Yes.

**Comment by ilius** [comment]
How about `math int`?

**Comment by andrasio** [comment]
@ilius We've had discussions related to conversions since the beginning of Nu. I originally wrote `str` even before sub command support existed. Imagine the reasons I had to give for it :P 

Things have turned out fine regarding that. Since we didn't have a definite decision on how exactly to deal with types and type conversions in general (because we wanted to be strict with types). So, naturally when someone or any of us suggested things coming from dynamic languages were types go funny on runtime, it raises alarms.

Something also to consider is that Nu covers a lot of things and a classic mindset coming from just a programming language isn't enough. `from` and `to` is one example, one could think of it as converting "types" but in general, it is a higher level of abstraction in terms of conversions (file formats in and out of the universal Nu "table" representation).

We also want to stay away as much as possible from the `but in this other place, this is how it's done`. In terms of terminals, being POSIX compliant is not a priority nor goal for instance.

That said. Same goes for `math` command suite right now (again, `math` didn't even exist either, they were called `sum`, `avg` and that's it). You read `math sum`, `math avg`, these are mostly operations that work and processes the values from a table.

I reiterate again that Nu is different. We ended up with sub commands in this way instead of, say, stating the `sub commands` as `flags` and we are still growing it (we also want to stay away as much as possible from adding too many flags, options, and ending up with your classic old commands filled with them)

The consensus right now is that to deal with type conversions or even where a command should be placed, we isolate it under a command suite (`str`, `math`) so we know exactly where the logic is and refactor it out when there is a need (which we are starting to see for `str`). Same applies for your wonderful PR dealing with conversions.

Whether it is far longer to type or not, or uncomfortable. This is not a problem, priority 1, personally, is that when you read it, it must tell you pretty much what you should expect to do. We have a long way to go due to lack of time in terms of documentation and allow you to find usage in the quickest way possible, too. We are fine with this because we are not 1.0 yet (and this is on purpose).

Another big problem we have right now and we are hoping to deal with it very soon, is the growing number of commands. This is expected. You see table commands, row manipulation commands, value specific commands, commands that either work on individual values or work on a row and could or could not work on individual columns (column paths), you can see where this is going in complexity. For an example, take `str trim`, if used alone it does a `trim` operation on all the columns of a row BUT if you pass it column paths, it just affects the particular columns of a given row (and this is what I expect from your PR).

This is a good opportunity to start putting in a bucket all the related converting types. and `into int` is a good start for that, then for the others, and the main purpose for this is to allow testing each and every single one of them because we also care about what types can and can't be converted to.

So I ask you to do that. Rename it to `into int`, remove `into-int` command, and let's move forward. Time will tell us what we will end up doing later. if you still want to use it locally as `int`, alias it.

**Comment by ilius** [comment]
Thanks for taking the time to explain these.
My main problem is with the word `into`.

- A command's name should uniquely tell what it does (maybe not at first sight if it's an abbrevation). Why not `to int`? because `to` is already taken for something else! So we choose a similar word that does something different? It just adds more chaos.
- Commands are commands. Actions. They should be the keyword of the action they perform. What is `into` the keyword for? It can be `turn into`, `move into` or `insert into` etc. And in none of them `into` is the keyword. Prepositions are not generally good commands (`x in y` makes sense, but `in x y` does not for example). What's next? `onto`? `towards`? It doesn't make sense.

Feel free to modify and use my branch (I also have it in `dev` branch if I deleted this branch).
I'm closing this.

**Comment by andrasio** [comment]
@ilius For the same reasons I explained above.

`to int` not because right now (from the explanation of `from` and `to`) we do file format serializations. when you add a `from xxx` command, when you try to open a file that has the extension `xxx` Nu internally calls `from xxx` so we limit `from` and `to` for all possible extension types, it's automatic. (see `from json`, `to json`, `from xml`, etc).

Doing `open data.csv --raw | from csv` is the same as `open data.csv` basically, just like `... | to csv | save --raw data.csv` is the same as `... | save data.csv`

`open data.csv | save data.json` is equivalent to `open data.csv --raw | from csv | to json | save data.json --raw`

So when you raise the question, why not `to int`. This means `to` would have many responsibilities and since the beginning it was chosen as file conversion / opening reponsabilities. Integers are not files.

for your second point, try to think of the command as what will it do from what's coming in as input (by the way, `move` and `insert` exist and they are column operations on the table coming in as input).

`ls | insert len { get name | str length }`
`ls | move modified --after name`

when you want to do type conversions, you want to `convert` the table that's coming in `into` an `int`, whether you allow particular columns or all of them, that's what column paths are for.

Ok great! I still think you should re-open the PR and make the changes. Thanks for your time.

**Pull request closed without merging**
