### PR TITLE
early return for parsing closure and block with interchanged shape

### PR DESCRIPTION
**Pull request by Kangaxx-0**
# Description

- Try to add some constrains to early return parse error when parsing closure with block shape as input, and vice-versa 
- Update error message for closure

Make sure you've run and fixed any issues with these commands:

- [x] `cargo fmt --all -- --check` to check standard code formatting (`cargo fmt --all` applies these changes)
- [x] `cargo clippy --workspace -- -D warnings -D clippy::unwrap_used -A clippy::needless_collect` to check that you're using the standard code style
- [x] `cargo test --workspace` to check that all tests pass

# After Submitting

If your PR had any user-facing changes, update [the documentation](https://github.com/nushell/nushell.github.io) after the PR is merged, if necessary. This will help us keep the docs up to date.

### CODE REVIEW

**Comment by sholderbach** [comment]
Are there associated issues this fixes?

**Comment by Kangaxx-0** [comment]
> Are there associated issues this fixes?

No, this is something found out when I was investigating another issue, I feel like it would be great to set this explicit check since `Block` and `Closure` have been split up already

**Comment by kubouch** [comment]
Seems like it's already covered:
```
> if 5 < 3 { |x| $x }
Error: nu::parser::parse_mismatch (link)

  × Parse mismatch during operation.
   ╭─[entry #11:1:1]
 1 │ if 5 < 3 { |x| $x }
   ·            ┬
   ·            ╰── expected block but found closure
   ╰────
```

I'd prefer not to add additional checks unless they fix some existing problem.

We can still land the block/closure typo in the error message, though.

**Comment by Kangaxx-0** [comment]
> Seems like it's already covered:
> 
> ```
> > if 5 < 3 { |x| $x }
> Error: nu::parser::parse_mismatch (link)
> 
>   × Parse mismatch during operation.
>    ╭─[entry #11:1:1]
>  1 │ if 5 < 3 { |x| $x }
>    ·            ┬
>    ·            ╰── expected block but found closure
>    ╰────
> ```
> 
> I'd prefer not to add additional checks unless they fix some existing problem.
> 
> We can still land the block/closure typo in the error message, though.

Did some quick changes, should be good to go

**Comment by kubouch** [comment]
OK thanks!

**Pull request merged**
