### PR TITLE
[DRAFT] Adds `from-ssv` command.

### PR DESCRIPTION
**Pull request by t-hart**
(Continued from https://github.com/nushell/nushell/pull/828)

As discussed in #807, this pull request implements a `from-ssv` command that takes a whitespace-separated table and turns it into a nushell data structure. 

The implementation is based on the `from-tsv` command.

In addition to the implementation, I have also added some tests and updated the readme.

Any issues, thoughts, whatever, let me know.

# Of note
One issue which has not been completely resolved is the `--headerless` option, which throws away the first row. If this is the intended behavior (it's how it's implemented in `from-tsv` today), then all is good. If this is not how it should work, this requires a little more work to change the behavior.

# Further development
While this works as it is right now, and I'd hope to get this merged as a first version, one possible expansion would be to allow a user-defined number of spaces in an entry, thus not splitting on any space, but only on at least `n` spaces. 

The motivation for this is the `oc get events` (and likely also `kubectl get events`) command, which also returns a space-separated table structure, but which has entries with spaces defined. It seems that all OpenShift (Kubernetes?) output tables use at least three spaces between each column.

So, if that sounds like a good idea, I'd like to look into that as a possible further expansion of this command.

### CODE REVIEW

**Comment by t-hart** [comment]
So this has more commits listed, but I'm assuming you can squash them through an option, or at least that's what I found after a bit of quick googling. Apologies for the mess, I'm more of a GitLab user.

**Comment by t-hart** [comment]
Actually, I forgot that I put an `unwrap` in there while figuring things out. That's not nice. Let me go back and edit that. Is there a way to mark a pull request as draft again?

**Comment by jonathandturner** [comment]
No worries, I'll just update the title for now.

**Comment by t-hart** [comment]
Thanks! Third time's the charm, right?

**Comment by jonathandturner** [comment]
This looks good to me :)

If you're comfortable with it, I think it's ready to land.

**Comment by t-hart** [comment]
Absolutely! Lest get it in. 

Any thoughts on taking it further, by the way? Implementing a way to only split if there are at least a certain number of spaces? I’ll open an issue for it if it’s of interest. 

Also, thanks for being so responsive! It’s been a pleasure to work with you.

**Comment by jonathandturner** [comment]
I'll go ahead and land.

I like the idea to give it a couple more options for people who want to have a bit more control.

Something else that's a bit related you might look into also is a `to-ssv` command.

**Comment by jonathandturner** [comment]
And you're welcome :)

**Pull request merged**
