### PR TITLE
fix #5131

### LINKED ISSUE #5131: `..branchname` in `git log ..branchname` is expanded by nushell
### Describe the bug

Double dots (`..`) in arguments to external commands appear to be expanded by nushell:
```
❯ git log ..staging
fatal: ambiguous argument '[REDACTED ABSOLUTE PATH]/..staging': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'
```

Also quoting `..staging` (`git log "..staging"` or `git log '..staging'`) does not help: The error returned by `git` is exactly the same. Escaping the dots (`..staging` -> `\.\.staging`) makes nushell no longer expand them, but also passes them literally to `git`, which then cannot find the path. This is the same when quoting the argument (`'..staging'` -> `'\.\.staging'`, `"..staging"` -> `"\.\.staging"`).

### How to reproduce

1. Try to run `git log ..staging`
2. Observe an error printed by `git`

### Expected behavior

I would expect nushell to not expand arguments that are not valid paths. In fact as a bash and fish user, it comes unexpected that it expands regular paths at all, i.e. paths that do not contain `*` or `~`. At the very least I would expect there to be an obvious way to prevent this expansion and pass an argument literally, as I wrote it, to the command.

### Screenshots

_No response_

### Configuration

| key                | value                                 |
| ------------------ | ------------------------------------- |
| version            | 0.60.0                                |
| build_os           | linux-x86_64                          |
| rust_version       | rustc 1.59.0 (gentoo)                 |
| cargo_version      | cargo 1.59.0                          |
| pkg_version        | 0.60.0                                |
| build_time         | 2022-03-25 19:35:23 +01:00            |
| build_rust_channel | release                               |
| features           | dataframe, default, trash, which, zip |
| installed_plugins  |                                       |

### Additional context

See-also: https://github.com/nushell/nushell/issues/4205

### PR DESCRIPTION
**Pull request by strega-nil-ms**
I don't personally agree with this; I'd prefer less magic,
and going back to a simple `expand_path`.

# Description

Instead of checking for `arg.starts_with('~') || arg.starts_with("..")`, this instead checks for the first path element being either tilde, or only composed of dots. This doesn't fix the existing issue of `blah/.../foo`, though, which `expand_path` would fix.

cc @jntrnr 

# Tests

Make sure you've run and fixed any issues with these commands:

- [x] `cargo fmt --all -- --check` to check standard code formatting (`cargo fmt --all` applies these changes)
- [x] `cargo clippy --all --all-features -- -D warnings -D clippy::unwrap_used -A clippy::needless_collect` to check that you're using the standard code style
- [x] `cargo build; cargo test --all --all-features` to check that all the tests pass

### CODE REVIEW

**Comment by strega-nil** [comment]
My preferred fix is this, fwiw:

```patch
From a87d1b656baa7e00ad1af0a3f8b039e4f415bfc8 Mon Sep 17 00:00:00 2001
From: nicole mazzuca <mazzucan@outlook.com>
Date: Sun, 10 Apr 2022 21:21:43 -0700
Subject: [PATCH] fix #5131 the second

---
 crates/nu-command/src/system/run_external.rs | 20 ++++++--------------
 crates/nu-path/src/expansions.rs             |  8 ++++++--
 2 files changed, 12 insertions(+), 16 deletions(-)

diff --git a/crates/nu-command/src/system/run_external.rs b/crates/nu-command/src/system/run_external.rs
index d0ce1ab9..29390308 100644
--- a/crates/nu-command/src/system/run_external.rs
+++ b/crates/nu-command/src/system/run_external.rs
@@ -398,13 +398,9 @@ impl ExternalCommand {
     /// Spawn a command without shelling out to an external shell
     pub fn spawn_simple_command(&self, cwd: &str) -> Result<std::process::Command, ShellError> {
         let head = trim_enclosing_quotes(&self.name.item);
-        let head = if head.starts_with('~') || head.starts_with("..") {
-            nu_path::expand_path_with(head, cwd)
-                .to_string_lossy()
-                .to_string()
-        } else {
-            head
-        };
+        let head = nu_path::external_expand_path(head)
+            .to_string_lossy()
+            .to_string();
 
         let mut process = std::process::Command::new(&head);
 
@@ -413,13 +409,9 @@ impl ExternalCommand {
                 item: trim_enclosing_quotes(&arg.item),
                 span: arg.span,
             };
-            arg.item = if arg.item.starts_with('~') || arg.item.starts_with("..") {
-                nu_path::expand_path_with(&arg.item, cwd)
-                    .to_string_lossy()
-                    .to_string()
-            } else {
-                arg.item
-            };
+            arg.item = nu_path::expand_path_with(&arg.item, cwd)
+                .to_string_lossy()
+                .to_string();
 
             let cwd = PathBuf::from(cwd);
 
diff --git a/crates/nu-path/src/expansions.rs b/crates/nu-path/src/expansions.rs
index f23b6197..1a4d0d75 100644
--- a/crates/nu-path/src/expansions.rs
+++ b/crates/nu-path/src/expansions.rs
@@ -49,9 +49,13 @@ where
     canonicalize(path)
 }
 
-fn expand_path(path: impl AsRef<Path>) -> PathBuf {
+pub fn external_expand_path(path: impl AsRef<Path>) -> PathBuf {
     let path = expand_tilde(path);
-    let path = expand_ndots(path);
+    expand_ndots(path)
+}
+
+fn expand_path(path: impl AsRef<Path>) -> PathBuf {
+    let path = external_expand_path(path);
     expand_dots(path)
 }
 
-- 
2.32.0 (Apple Git-132)
```

**Comment by jntrnr** [comment]
@strega-nil-ms - we need `expand_path_with` because Nushell uses its own cwd. It'll pull from the environment at startup, but then after that follows its own value.

Thanks for putting the PR together. Once this goes green, I'll land it

**Comment by strega-nil** [comment]
@jntrnr mmh, I see what you're saying; however, I don't think that this is the best way to do that. I don't see why you can't pass it through unchanged, since the subprocess's CWD will be in the "right" CWD.

**Comment by strega-nil** [comment]
```
/Users/nimazzuc/projects〉./nushell/a.out                                                            04/11/2022 05:58:11 PM
/Users/nimazzuc/projects
/Users/nimazzuc/projects〉cd nushell                                                                 04/11/2022 05:58:13 PM
/Users/nimazzuc/projects/nushell〉./a.out                                                            04/11/2022 05:58:19 PM
/Users/nimazzuc/projects/nushell
/Users/nimazzuc/projects/nushell〉cat test.c                                                         04/11/2022 05:58:21 PM
char *getcwd(char *buf, unsigned long size);
int printf(char const*, ...);

int main()
{
        printf("%s\n", getcwd((char[128]){0}, 128));
}
```

**Pull request merged**
