### PR TITLE
Add Windows Terminal profile and icon in Windows control panel

### PR DESCRIPTION
**Pull request by wolimst**
# Description

Windows Installer generation script (`wix/main.wxs`) is updated to support following features:
- Add an installation option for Windows Terminal profile (#3994)
- Install icon file in `install_dir/nu.ico`, to show icon in Windows Terminal
- Show the product icon in Windows 'Add/Remove Programs' control panel

# Checks

Since the changes are only related to installation process in Windows, and do not contain source code changes, no test is added. Instead, I have checked following things.

- OS: Windows 11 (Version 21H2 OS Build 22000.675)
- Built the installer using `.github/workflows/release-pkg.nu` script
  - Environment variables used in the script are manually set (referred to `.github/workflows/release.yml`)

### Checks for Windows Terminal profile

- [x] Install (adding Windows Terminal profile feature enabled)
- [x] Install (WT profile enabled, installation directory is changed)
- [x] Install (WT profile disabled) -> Re-run the installer and Modify (WT profile enabled)
- [x] Install (WT profile enabled) -> Manually remove/modify the profile file -> Re-run the installer and Repair
  - Expected result for above 4 cases:
    - The profile file should be created (`%PROGRAMDATA%/Microsoft/Windows Terminal/Fragments/nu/nu.json`) and the file should contain correct path for the nushell executable and the icon
    - The profile should be shown in the Windows Terminal
- [x] Uninstall
- [x] Install (WT profile enabled) -> Re-run the installer and Modify (WT profile disabled)
  - Expected result for above 2 cases: The profile file should be removed

### Checks for icon in control panel

- [x] Icon is shown in Windows 'Add/Remove Programs' control panel after installation

# Tests

Make sure you've done the following:

- [x] Add tests that cover your changes, either in the command examples, the crate/tests folder, or in the /tests folder.
  -> Not applicable for the changes
- [x] Try to think about corner cases and various ways how your changes could break. Cover them with tests.
- [x] If adding tests is not possible, please document in the PR body a minimal example with steps on how to reproduce so one can verify your change works.
  -> See `Checks` section above

Make sure you've run and fixed any issues with these commands:

- [x] `cargo fmt --all -- --check` to check standard code formatting (`cargo fmt --all` applies these changes)
- [x] `cargo clippy --workspace --features=extra -- -D warnings -D clippy::unwrap_used -A clippy::needless_collect` to check that you're using the standard code style
- [x] `cargo test --workspace --features=extra` to check that all the tests pass

### CODE REVIEW

**Comment by rgwood** [comment]
Awesome, thank you for the contribution! It will be really nice to finally have this feature.

**Comment by rgwood** [comment]
> Maybe I can re-generate asset/nu_logo.ico from [asset/icons/nushell-original.png](https://github.com/nushell/nushell/blob/main/assets/icons/nushell-original.png) file, if that's ok.

Sounds good, that's worth a try.

**Comment by fdncred** [comment]
@wolimst I just wanted to jump in and say, nice work on this PR! it's a pleasure to read such detailed notes in the PR body. Good job!

**Comment by wolimst** [comment]
I used the original `asset/nu_logo.ico` because the `asset/icons/nushell-original.png` had lower resolution (200x200px) than the ico file (256x256px).

Simply opened and overwrited the file with GIMP.
And, Windows Terminal had no problem with the new icon file installed with the new installer!

Maybe the problem was related to metadata..?
image

Changed PR to ready for review, since the recreated icon solved the issue.

**Comment by wolimst** [comment]
The icon is shown somewhat not clearly though, because the high-res image is resized.
image

I think this might be resolved by including multiple images with various resolution (with larger nu letter in low-res image?) in the `ico` in the future.

**Comment by rgwood** [comment]
That's a good idea; we might also need to pick a logo that looks good even at small resolutions. We're not 100% set on the current one.

I think this is good to merge now and we can tweak the icon later; thanks again, this is a great first PR!

**Comment by wolimst** [comment]
> we might also need to pick a logo that looks good even at small resolutions. We're not 100% set on the current one.

Looking forward to it!

> I think this is good to merge now and we can tweak the icon later; thanks again, this is a great first PR!

Thanks for the merge, and thanks for having me to contribute!

**Comment by fdncred** [comment]
@wolimst This has been causing the winget ci to fail for months. The winget folks finally narrowed it down to this error.
```
Installation failed with exit code -1978335226
2023-05-16 17:48:21.070 [CLI ] ShellExecute installer failed: 1603
CAQuietExec: Error 0xc0000135: Command line returned an error.
CAQuietExec: Error 0xc0000135: QuietExec Failed
CAQuietExec: Error 0xc0000135: Failed in ExecCommon method CustomAction ReplacePathsInWindowsTerminalProfile returned actual error code 1603 (note this may not be 100% accurate if translation happened inside sandbox) Property(S): ErrorDialog = ErrorDlg
MSI (s) (74:6C) [17:48:20:955]: Product: nu -- Installation failed.
MSI (s) (74:6C) [17:48:20:955]: Windows Installer installed the product. Product Name: nu. Product Version: 0.80.0. Product Language: 1033. Manufacturer: The Nushell Project Developers. Installation success or error status: 1603.
```
Which seems to jive with these changes in the wsx file https://github.com/nushell/nushell/blob/057de0661315e0b4e6f38aafca13179a4d9e8369/wix/main.wxs#L375-L393

Any ideas how to keep this from failing?

**Comment by wolimst** [comment]
@fdncred 
At first, I thought the problem is caused by the nushell command that replaces paths failing, however, it seems that is not the case...

Running the msi installer built from the source / Installing nu with winget created the windows terminal profile without an error, and I couldn't reproduce the problem.

Here is the nushell command to replace the paths, ran by the installer. Notice single quotes are used inside the double quotes.

```
"C:\Program Files\nu\bin\nu.exe" -c "open 'C:\ProgramData\Microsoft\Windows Terminal\Fragments\nu\nu.json' | update profiles.commandline 'C:\Program Files\nu\bin\nu.exe' | update profiles.icon 'C:\Program Files\nu\nu.ico' | save -f 'C:\ProgramData\Microsoft\Windows Terminal\Fragments\nu\nu.json'"
```

Relevant part in the msi installer log, which includes the command (you might need to scroll to the right to see it)
```
Action 17:26:48: ReplacePathsInWindowsTerminalProfile. 
MSI (s) (8C:74) [17:26:48:148]: Executing op: CustomActionSchedule(Action=ReplacePathsInWindowsTerminalProfile,ActionType=3073,Source=BinaryData,Target=CAQuietExec,CustomActionData="C:\Program Files\nu\bin\nu.exe" -c "open 'C:\ProgramData\Microsoft\Windows Terminal\Fragments\nu\nu.json' | update profiles.commandline 'C:\Program Files\nu\bin\nu.exe' | update profiles.icon 'C:\Program Files\nu\nu.ico' | save -f 'C:\ProgramData\Microsoft\Windows Terminal\Fragments\nu\nu.json'")
MSI (s) (8C:78) [17:26:48:150]: Invoking remote custom action. DLL: C:\Windows\Installer\MSIB94F.tmp, Entrypoint: CAQuietExec
MSI (s) (8C:20) [17:26:48:150]: Generating random cookie.
MSI (s) (8C:20) [17:26:48:150]: System Environment : Client has accepted UAC prompt
MSI (s) (8C:20) [17:26:48:150]: System Environment : Client has accepted UAC prompt
MSI (s) (8C:20) [17:26:48:154]: Created Custom Action Server with PID 8808 (0x2268).
```

So, I think the problem is in the winget ci maybe?

---

> 2023-05-16 17:48:21.070 [CLI ] ShellExecute installer failed: 1603

Looking for the error code 1603 from the winget ci, I found following information about the causes.

> You may receive this error message if any one of the following conditions is true:
>
> - Windows Installer is attempting to install an app that is already installed on your PC.
> - The folder that you are trying to install the Windows Installer package to is encrypted.
> - The drive that contains the folder that you are trying to install the Windows Installer package to is accessed as a substitute drive.
> - The SYSTEM account does not have Full Control permissions on the folder that you are trying to install the Windows Installer package to. You notice the error message because the Windows Installer service uses the SYSTEM account to install software.
>
> From https://learn.microsoft.com/en-us/troubleshoot/windows-server/application-management/msi-installation-error-1603

Just guessing, but as described in the last item of the possible causes above, I think maybe it is a permission issue in the ci.

Currently, the path replacing command is ran with system privileges, but I think the ci system wouldn't expose full privileges for custom script for obvious reasons.

So, maybe we can change the installer to add windows terminal profile for the current user only, without elevated privileges, and see how it goes with the ci.

Do you know whether we can run the winget ci for testing purpose?

**Comment by fdncred** [comment]
thanks for the great research @wolimst. i appreciate all your work.

i installed the msi on my win 11 laptop and never saw that nu.json fragment, nor could i get windows terminal to recognize it. so, it's odd to me that it's working for you.

using a path that doesn't require full privileges sounds like something that should be tried.

i'm not sure about the winget ci, maybe if you fork the winget ci repo and run the ci locally?

**Comment by wolimst** [comment]
@fdncred 
> i installed the msi on my win 11 laptop and never saw that nu.json fragment, nor could i get windows terminal to recognize it. so, it's odd to me that it's working for you.

That is odd..
I am also using windows 11, and the fragment is installed in `C:\ProgramData\Microsoft\Windows Terminal\Fragments\nu\nu.json`. The profile appears in Windows Terminal as well. Maybe you can find out more details from the installer log. `msiexec /i <path/to/installer.msi> /l*v <path/to/output-log-file>` will give you the log file.

---

I have looked into winget ci repo, but I think the validation is done by calling azure functions (something like aws lambda I guess?), and I couldn't find any ci scripts or tools for us to run the validation ci locally.

Some references:
- [Report of the failed validation job](https://dev.azure.com/ms/winget-pkgs/_build/results?buildId=458979&view=logs&j=871b4eed-22de-5cb6-c1c8-82f190de633f&t=58bdf892-4e45-5ba7-4782-31912f95e167): the validation is done by calling POST request to azure function endpoint
- The ci configuration [[1]](https://github.com/microsoft/winget-pkgs/blob/b5f9494bde916aea9f4e3b463fb07eb194b9491a/DevOpsPipelineDefinitions/validation-pipeline.yaml#L197-L216), [[2]](https://github.com/microsoft/winget-pkgs/blob/b5f9494bde916aea9f4e3b463fb07eb194b9491a/DevOpsPipelineDefinitions/validation-pipeline.yaml#L62-L69) only contain the endpoint of the azure function; couldn't find any ci scripts

So, what is our next approach?

I think I can change the install script related to wt profile to use user context instaed of system context, and we can see how it goes with the ci on the next release.

- wt fragment installation path will be: `%LOCALAPPDATA%\Microsoft\Windows Terminal\Fragments\nu\nu.json`
  e.g. `C:\Users\<user>\AppData\Local\Microsoft\Windows Terminal\Fragments\nu\nu.json`
- the custom action to update executable path in the fragment file will be run without privilege elevation

But this will reduce some consistency on the context of the installation: executables and PATH env variable will be installed for all users, while the wt profile fragment will be installed for the current user only.

What are your thoughts?

**Comment by fdncred** [comment]
It's definitely not in this path on my windows 11 machine (C:\ProgramData\Microsoft\Windows Terminal\Fragments\nu\nu.json). I tried putting it there and there were permission issues that I had to override and even when I got everything in place with the correct paths in the json, windows terminal didn't recognize it. No clue what's going on.

TBH, I thought i was going where I have other fragments which is \users\<username>\appdata\local\microsoft\windows terminal\fragments\nu\nu.json. I tried putting it in there but i can't get that to be recognized by WT as well. I'm sure it's me. Is there some WT documentation that says where these fragment files can/should be located?

I think the next step should be putting the fragment in a path that the user has permissions to.

**Comment by wolimst** [comment]
> Is there some WT documentation that says where these fragment files can/should be located?

You can find it in [this document](https://learn.microsoft.com/en-us/windows/terminal/json-fragment-extensions#where-to-place-the-json-fragment-files), but it says only those two paths, `C:\ProgramData\...` and `C:\Users\<user>\AppData\Local\...`

> I think the next step should be putting the fragment in a path that the user has permissions to.

Sure, I'll try to create a PR for this soon.

**Comment by wolimst** [comment]
@fdncred Hello again!

> I'm guessing that the problem is that it's installing here "C:\ProgramData\Microsoft\Windows Terminal\Fragments\nu\nu.json" instead of a user level profile. It's just a guess though.
> 
> I think this is part of the problem. Looking in the sandbox, there is no c:\programdata\microsoft\windows terminal folder. Maybe we need to create that folder first?

Didn't have time to reproduce it on my end, but I don't think that the root cause is `ReplacePathsInWindowsTerminalProfile`, as we found in the last time in https://github.com/nushell/nushell/pull/9513.

---

Quote from https://github.com/nushell/nushell/pull/9513, brief summary of the cause:

> Nushell is using target.x86_64-pc-windows-msvc.rustflags to statically link MSVC runtime in windows platform, but this config is being ignored in ci workflows.

The error code is same as the last time `CAQuietExec:  Error 0xc0000135`, so I think the cause is also the same.

---

Seems like the changes made by https://github.com/nushell/nushell/pull/9513 to preserve `target.x86_64-pc-windows-msvc.rustflags` is removed by https://github.com/nushell/nushell/commit/a26a01c8d0bf6118ad5b17754e9bd36036d02ecb, in following lines.

https://github.com/nushell/nushell/blob/5d8763ed1d14048ac9fc09eb21be36e6e622f0d7/.github/workflows/release.yml#L81-L83

https://github.com/nushell/nushell/blob/5d8763ed1d14048ac9fc09eb21be36e6e622f0d7/.github/workflows/release.yml#L169-L171

Maybe re-add the removed option `with: rustflags: ''` on those lines again?

**Comment by fdncred** [comment]
dang it, i checked that yaml and thought i saw the rust flags there. i'll take a closer look. it's so good having a second set of eyes on this stuff. thanks @wolimst!!

**Comment by hustcer** [comment]
Oh, sorry, that's my bad, I have never notice that, We should Add some comments there to prevent recurrence

**Comment by wolimst** [comment]
Yes, I also think that we need some comments about it, because it is really easy to overlook, and also it is quite hard to find where the cause is, from the problems caused by it.

More detail for the `rustflags` option of the `setup-rust-toolchain` action: https://github.com/actions-rust-lang/setup-rust-toolchain/#rustflags

**Pull request merged**
