### PR TITLE
Flexibility updating table's cells.

### PR DESCRIPTION
**Pull request by andrasio**
Very often we need to work with tables (say extracted from unstructured data or some kind of final report, timeseries, and the like).

It's inevitable we will be having columns that we can't know beforehand what their names will be, how many, or even more unknowns during a transient step for further processing. Also, we may end up with certain cells having values we may want to remove as we explore.

Here, `update cells` fundamentally goes over every cell in the table coming in and updates the cell's contents with the output of the block passed. Basic example here:

```
> [

    [   ty1,       t2,       ty];

    [     1,        a, $nothing]
    [(wrap), (0..<10),      1Mb]
    [    1s,     ({}),  1000000]
    [ $true,   $false,   ([[]])]

] | update cells { describe }

───┬───────────────────────┬───────────────────────────┬──────────
 # │          ty1          │            t2             │    ty
───┼───────────────────────┼───────────────────────────┼──────────
 0 │ integer               │ string                    │ nothing
 1 │ row Column(table of ) │ range[[integer, integer)] │ filesize
 2 │ string                │ nothing                   │ integer
 3 │ boolean               │ boolean                   │ table of
───┴───────────────────────┴───────────────────────────┴──────────
```

and another one (in the examples) for cases, say we have a timeseries table generated and
we want to remove the zeros and have empty strings and save it out to something like CSV.

```
> [
    [2021-04-16, 2021-06-10, 2021-09-18, 2021-10-15, 2021-11-16, 2021-11-17, 2021-11-18];
    [        37,          0,          0,          0,         37,          0,          0]
] | update cells {|value| 
  if ($value | into int) == 0 {
    ""
  } {
    $value
  }
}

───┬────────────┬────────────┬────────────┬────────────┬────────────┬────────────┬────────────
 # │ 2021-04-16 │ 2021-06-10 │ 2021-09-18 │ 2021-10-15 │ 2021-11-16 │ 2021-11-17 │ 2021-11-18
───┼────────────┼────────────┼────────────┼────────────┼────────────┼────────────┼────────────
 0 │         37 │            │            │            │         37 │            │
───┴────────────┴────────────┴────────────┴────────────┴────────────┴────────────┴────────────
```

### CODE REVIEW

**Comment by kubouch** [comment]
Cool! I think it would be useful if we could (optionally) set which columns it applies to. Like `ls | update cells -c [name, size] { describe }`.

**Comment by kubouch** [comment]
Or it could be named `update columns`: `ls | update columns name size { describe }`.

**Comment by kubouch** [comment]
Maybe even `update rows`: `ls | update rows 2..10 { describe }`

**Comment by fdncred** [comment]
love it! of course, i love most anything that resembles mutation. haha :)

**Pull request merged**
