### PR TITLE
Add examples for env,let-env,rm,touch and date list-timezone

### PR DESCRIPTION
**Pull request by hustcer**
# Description

Add examples for env,let-env,rm,touch and date list-timezone
  
# Tests

Make sure you've run and fixed any issues with these commands:

- [x] `cargo fmt --all -- --check` to check standard code formatting (`cargo fmt --all` applies these changes)
- [x] `cargo clippy --all --all-features -- -D warnings -D clippy::unwrap_used -A clippy::needless_collect` to check that you're using the standard code style
- [x] `cargo build; cargo test --all --all-features` to check that all the tests pass

### CODE REVIEW

**Comment by hustcer** [comment]
@fdncred Updated

**Comment by kubouch** [comment]
@hustcer Another small thing: On Windows the PATH is called Path, so you could set up the example string on Windows to use Path and all the others to use PATH. But it's just a small thing, we can do that later.

**Comment by fdncred** [comment]
> @hustcer Another small thing: On Windows the PATH is called Path, so you could set up the example string on Windows to use Path and all the others to use PATH. But it's just a small thing, we can do that later.

I'm on windows right now. I'm seeing this:
```
> 'PATH' in (env).name
true
> 'Path' in (env).name
false
```
I'll be interested to see what the Windows CI says.

**Comment by hustcer** [comment]
> @kubouch I just figured part of it out.
> 
> 1. if your parent shell is cmd.exe, it's `Path`
> 2. if your parent shell is pwsh.exe or powershell.exe, it's `PATH`
> 
> ugh - windows, make up your mind!

Any need to fix the `Path` on windows later?

**Pull request merged**
