### PR TITLE
Parameter defaults to $nu.scope.commands

### PR DESCRIPTION
**Pull request by bobhy**
(second try at posting this PR, #9084 got all messed up, and so were my local repos...)

# Description

Show parameter defaults in scope command signature, where they're available for display by help.
per https://github.com/nushell/nushell/issues/8928.

I found unexpected ramifications in one completer (`NuHelpCompleter`) and plugins, which both use the flag-formatting routine from builtin help.  For the moment I made the minimum necessary changes to get the mainline scenario to pass tests and run.  But we should circle back on what to do with plugins and help completer..  

# User-Facing Changes

1. New `parameter_default` column to `signatures` table in `$nu.scope.commands`
It is populated with whatever parameters can be defaulted: currently positional args and named flags.
2. Built in help (both `help <command>` and `<command> --help` will display the defaults
3. Help completer will display defaults for flags, but not for positionals.  

Example:
A custom command with some default parameters:
```
〉cat ~/work/dflts.nu 
# sample function to show defaults in help
export def main [
    arg1: string        # mandatory positional
    arg2:string=abc     # optional positional
    --switch            # no default here
    --named:int         # named flag, no default
    --other:string=def  # flag 
    --hard:record<foo:int bar:string, bas:bool> # default can be compound type
            = {foo:22, bar:"other worlds", bas:false}
] { {arg1: $arg1,
    arg2: $arg2,
    switch: $switch,
    named: $named,
    other: $other,
    hard: $hard, }
}

〉use ~/work/dflts.nu

〉$nu.scope.commands | where name == 'dflts' | get signatures.0.any | reject short_flag description custom_completion
╭───┬────────────────┬────────────────┬──────────────────────────────────────────┬─────────────┬───────────────────────────╮
│ # │ parameter_name │ parameter_type │               syntax_shape               │ is_optional │     parameter_default     │
├───┼────────────────┼────────────────┼──────────────────────────────────────────┼─────────────┼───────────────────────────┤
│ 0 │                │ input          │ any                                      │ false       │                           │
│ 1 │ arg1           │ positional     │ string                                   │ false       │                           │
│ 2 │ arg2           │ positional     │ string                                   │ true        │ abc                       │
│ 3 │ switch         │ switch         │                                          │ true        │                           │
│ 4 │ named          │ named          │ int                                      │ true        │                           │
│ 5 │ other          │ named          │ string                                   │ true        │ def                       │
│ 6 │ hard           │ named          │ record<foo: int, bar: string, bas: bool> │ true        │ ╭───────┬───────────────╮ │
│   │                │                │                                          │             │ │ foo   │ 22            │ │
│   │                │                │                                          │             │ │ bar   │ other worlds  │ │
│   │                │                │                                          │             │ │ bas   │ false         │ │
│   │                │                │                                          │             │ ╰───────┴───────────────╯ │
│ 7 │                │ output         │ any                                      │ false       │                           │
╰───┴────────────────┴────────────────┴──────────────────────────────────────────┴─────────────┴───────────────────────────╯

〉help dflts
sample function to show defaults in help

Usage:
  > dflts {flags} <arg1> (arg2) 

Flags:
  --switch - switch -- no default here
  --named <Int> - named flag, typed, but no default
  --other <String> - flag with default (default: 'def')
  --hard <Record([("foo", Int), ("bar", String), ("bas", Boolean)])> - default can be compound type (default: {foo: 22, bar: 'other worlds', bas: false})
  -h, --help - Display the help message for this command

Parameters:
  arg1 <string>: mandatory positional
  arg2 <string>: optional positional (optional, default: 'abc')
```

Compared to (relevant bits of) help output previously:
```
Flags:
  -h, --help - Display the help message for this command
  -, --switch - no default here
  -, --named <int> - named flag, no default
  -, --other <string> - flag
  -, --hard <record<foo: int, bar: string, bas: bool>> - default can be compound type

Signatures:
  <any> | dflts <string> <string> -> <any>

Parameters:
  arg1 <string>: mandatory positional
  (optional) arg2 <string>: optional positional
```

# Tests + Formatting

# After Submitting

### CODE REVIEW

**Comment by fdncred** [comment]
Generally this PR looks very helpful and cool. But I'm not sure how I feel about changing BB to make it work for your background. It looks worse for me, but it's the same argument with making it work for my background. I know others don't like a lot of config, but I kind of wish this stuff was configurable by matching your theme.

The difference, for me and my background, is subtle but noticeable at low brightness.
Old:
image
New
image

**Comment by bobhy** [comment]
Agree.  But I couldn't have tested this code without making the color change, and this code, `get_flags_section`, ignores existing color configuration settings.  
I will take another look at finding a way to accomplish that much, but I guess this situation is one more data point for a much larger discussion about accessibility Nu should be having soonish ( ~~8% of Caucasian males have red-green color blindness [wikipedia](https://en.wikipedia.org/wiki/Color_blindness#Epidemiology))

**Comment by fdncred** [comment]
I agree about the accessibility in regards of colors. I commented on your other issue around this.

**Review by amtoine — CHANGES_REQUESTED** [review]
@bobhy 
could you implement the same UX for the `std help` commands?
that would be great :yum:

**Comment by fdncred** [comment]
@amtoine Can we land this and have another pass later to update std help? I think that's the only change you requested.

**Comment by bobhy** [comment]
I can make the corresponding changes in `std help` today.

**Comment by bobhy** [comment]
Goodness me oh my!  Whatever am I doing wrong that keeps picking up unrelated changes when I rebase on latest main?
It happened again: I've got several extraneous files mentioned in this PR that came from main when I rebased this AM.  However, the extra files didn't show in my `git diff origin/<feature branch>`!

I don't want to muck about trying to remove those files from this PR.  I believe the extraneous files were changed in other commits already merged to upstream main.  Will this cause you problems if you merge this PR into main later?

The requested fixes to the feature look good...

**Comment by bobhy** [comment]
I've gotten entirely too good at recovering from these unrelated commits creeping into the github pr feature branch.  If only I could avoid it in the first place!

In any case, a clean PR is available, including the requested changes to `std help`, at #9152

**Pull request closed without merging**
