### PR TITLE
Introduce new command - nu check

### PR DESCRIPTION
**Pull request by Kangaxx-0**
# Description

To address #5825 - The idea is to apply `nu-check` to pre-validate an input file, give user some appropriate messages if parsing failed

What is covered and what is not

- [x] - New command `nu-check` to pre-validate and parse content
- [x] - Support both `script` and `module`
- [x] - "Operate on a string or a raw output: open foo.nu | nu-check" 

---
### Update:
1. Change command from`nu check` to `nu-check`
2. Support pipe of `string`, `ListStream` and `ExternalStream` 
3.  Change the default output is either `true` or `false`
4.  New flag `-d` to show more error message
5.  Add more tests

- Pipe with ListStream
parse_liststream
---

### Test coverage
- [x] Successfully parse file as script
- [x] Successfully pipe with string as script
- [x] Successfully pipe with List Stream as script
- [x] Successfully pipe with external rawStream as script
- [x] Successfully parse file as module
- [x] Successfully parse file as module
- [x] Failed to parse file as script
- [x] Failed to parse file as module
- [x] File not found
- [x] Unsupported file extension

Demos

- Parse script success
parse_success

- Parse script failure
parse_failure

# Tests

Make sure you've done the following:

- [x] Add tests that cover your changes, either in the command examples, the crate/tests folder, or in the /tests folder.
- [x] Try to think about corner cases and various ways how your changes could break. Cover them with tests.
- [ ] If adding tests is not possible, please document in the PR body a minimal example with steps on how to reproduce so one can verify your change works.

Make sure you've run and fixed any issues with these commands:

- [x] `cargo fmt --all -- --check` to check standard code formatting (`cargo fmt --all` applies these changes)
- [x] `cargo clippy --workspace --features=extra -- -D warnings -D clippy::unwrap_used -A clippy::needless_collect` to check that you're using the standard code style
- [x] `cargo test --workspace --features=extra` to check that all the tests pass

### CODE REVIEW

**Comment by jntrnr** [comment]
This is cool! I wonder if we should build this into nu so that we can give the nice error for parsing errors.

Also, `nu check` feels like a good thing to include type checking also. Everything but actually running the file.

**Comment by hustcer** [comment]
Will it be better if we output nothing or a simple `true` if the check passed, this will be friendly for programmatic checking. Or add a flag ?

**Comment by Kangaxx-0** [comment]
> Also, `nu check` feels like a good thing to include type checking also. Everything but actually running the file.

Could you elaborate a bit how this might work with `nu check` please :)

**Comment by Kangaxx-0** [comment]
> Will it be better if we output nothing or a simple `true` if the check passed? Just like run `git rev-parse --is-inside-work-tree` in a git repo, this will be friendly for programmatic checking. Or add a flag ?

My first try was to output nothing, it looked less intuitive, so I added a parse success message. If you guys feel like nothing is better, I am totally ok with that :)

**Comment by kubouch** [comment]
Cool! A few points:

* I'd prefer if it worked on a string input instead of a file. It would make it more useful, you could, for example select just some lines from file: 
```
> open foo.nu | lines | range 10 | str collect (char nl) | nu-check
```
We don't need the command to open files. `nu-highlight` works the same way.
* Maybe a better name for the command would be `nu-check` instead of `nu check` to be consistent with `nu-highlight`

**Comment by fdncred** [comment]
wow, nice work!

1. I agree that I'd like to use it in scripts so I could check for a true/false return or either maybe last_exit_code = 1 if it returns that?
2. I do also like the error message too. Maybe that could be produced with a `--debug` parameter?
3. It also would be cool if the error message pointed you to the span where the first error was found. I'd actually like to see all errors but I'm not sure it can produce all errors atm.
4. feature for later, json output so it's easily consumed by external apps because this is kind of a start of a lsp-like tool.
5. agree nu-check is a more appropriate name.
6. I'd like it to work on a string or a file. A string you can just check the input and a file you can just check for that parameter.

we've been needing this for a while, so thank you very much. I'm excited to see this eventually land. :)

**Comment by rycee** [comment]
About emitting output. I would prefer no output whatsoever if the check succeeds and the exit code should be zero. If the check fails then the error message(s) should be printed (I have no strong opinion on whether they should be printed to stdout or stderr) and the exit code should be non-zero.

The idea to print "true" on success seems mainly useful if you make it symmetric by exiting with zero status and print "false" on check failure.

**Comment by Kangaxx-0** [comment]
Seems like folks have slight different opinions regarding the output,  can I just leave it as is for now which is - Send `true/false` with default, and support error information with flag `-d`, or something different.

**Comment by fdncred** [comment]
Yes. Let's get something landed and tweak on it more later.

**Comment by jntrnr** [comment]
I was thinking through this a bit this morning and wondering... it seems like it'd be really useful to be able to check nu scripts from outside nu too.

What if we offered this functionality as part of `nu`? Something like `nu --check myfile.nu` could check the file for errors, print errors if it sees them, return non-zero exit code on error, but not actually run the file.

**Comment by rycee** [comment]
@jntrnr Indeed, that's exactly what I'm looking for and what I tried to express in #5825.

My use-case is to run the nu check command from a script in a different language. Specifically, from a Bash script run as part of a [Nix](https://nixos.org/) build. The idea is that you can generate a Nu script as a Nix package. The final part of the build would be to check the generated script. The Nix build would fail (ideally with a helpful error message from Nu) if the generated script is invalid.

**Comment by kubouch** [comment]
I'd still like to be able to pipe a string to it without having a file.

**Comment by Kangaxx-0** [comment]
> I'd still like to be able to pipe a string to it without having a file.

You can do that without having a file, this is one of the unit test in PR .  File is totally optional now

```
#[test]
fn parse_string_as_script_success() {
    Playground::setup("nu_check_test_13", |dirs, _sandbox| {
        let actual = nu!(
            cwd: dirs.test(), pipeline(
            r#"
                echo $'two(char nl)lines' | nu-check
            "#
        ));

        assert!(actual.err.is_empty());
    })
}
```

**Comment by kubouch** [comment]
OK, cool, I was mostly reacting to the `nu --check` suggestion, I thought maybe JT meant not to have this command. I think the `nu --check` could be added as a separate PR.

**Comment by kubouch** [comment]
Is there still something blocking this PR or can it be merged? It seems good to me.

**Comment by Kangaxx-0** [comment]
> Is there still something blocking this PR or can it be merged? It seems good to me.

I spotted one corner case regarding the list stream, I am going out now and will be sending a new iteration tonight :)

**Comment by fdncred** [comment]
@Kangaxx-0 are we ready to land this now?

**Comment by fdncred** [comment]
I'm not sure how I feel about this.
```
> ls *.nu | each {|i| [[script result]; [$i.name (nu-check $i.name)]]} | flatten
╭──────────────────┬────────╮
│      script      │ result │
├──────────────────┼────────┤
│ oh-my-minimal.nu │ false  │
│ oh-my-v2.nu      │ true   │
│ oh-my.nu         │ false  │
│ panache-git.nu   │ true   │
│ zoxide-eq.nu     │ false  │
├──────────────────┼────────┤
│      script      │ result │
╰──────────────────┴────────╯
```
apparently, the reason some of these failed was because they're modules. I wonder how we can teach nu-check to detect that?

**Comment by Kangaxx-0** [comment]
> I'm not sure how I feel about this.
> 
> ```
> > ls *.nu | each {|i| [[script result]; [$i.name (nu-check $i.name)]]} | flatten
> ╭──────────────────┬────────╮
> │      script      │ result │
> ├──────────────────┼────────┤
> │ oh-my-minimal.nu │ false  │
> │ oh-my-v2.nu      │ true   │
> │ oh-my.nu         │ false  │
> │ panache-git.nu   │ true   │
> │ zoxide-eq.nu     │ false  │
> ├──────────────────┼────────┤
> │      script      │ result │
> ╰──────────────────┴────────╯
> ```
> 
> apparently, the reason some of these failed was because they're modules. I wonder how we can teach nu-check to detect that?
> 
> my original goal was to run nu-check on everything in the nu_scripts folder. I'll have to think harder about that now.

Since script and module are being parsed differently, for `module`, could you try please try `nu-check --as-module`.

**Comment by fdncred** [comment]
Ya, of course. I did that manually. I was just wondering if there was a way to auto detect this so one wouldn't have to manually tell it that it was a module.

**Comment by Kangaxx-0** [comment]
> Ya, of course. I did that manually. I was just wondering if there was a way to auto detect this so one wouldn't have to manually tell it that it was a module. 

It's totally doable, the only question I had was how user would know if the parse result is for script or module?

**Comment by fdncred** [comment]
maybe it matters that it's a module, maybe it doesn't. I'm not sure.

**Comment by hustcer** [comment]
How about add a `--all(-a)` flag to check it for both script and module, and output a record like: `{ script: false, module: true }`

**Comment by kubouch** [comment]
We could also have some simple heuristic, like "try to parse as a script, then as a module if it fails".

**Comment by Kangaxx-0** [comment]
I will be working on this tweak and send a PR for `--all` flag

**Pull request merged**
