### PR TITLE
fix: now sqlite insert handles column names as expected

### LINKED ISSUE #11429: `into sqlite` INSERT is based on column order rather than name
### Describe the bug

When inserting a table into a SQLite database, the column names are ignored.  Only the positional column values of the input are used.  This can lead to unexpected corruption of the table.

### How to reproduce

```Nu
> mkdir showme; cd showme; touch foo bar
> ls | select name modified size | into sqlite foo.sqlite
> ls | select name size modified | into sqlite foo.sqlite
> open foo.sqlite | get main
╭───┬────────────┬──────────────────────────────────────┬──────────────────────────────────────╮
│ # │    name    │               modified               │                 size                 │
├───┼────────────┼──────────────────────────────────────┼──────────────────────────────────────┤
│ 0 │ bar        │ 2023-12-27 10:32:40.227788746 -05:00 │                                    0 │
│ 1 │ foo        │ 2023-12-27 10:32:40.227788746 -05:00 │                                    0 │
│ 2 │ bar        │ 0                                    │ 2023-12-27 10:32:40.227788746 -05:00 │
│ 3 │ foo        │ 0                                    │ 2023-12-27 10:32:40.227788746 -05:00 │
│ 4 │ foo.sqlite │ 8192                                 │ 2023-12-27 10:32:49.408107839 -05:00 │
╰───┴────────────┴──────────────────────────────────────┴──────────────────────────────────────╯
```

While this particular example is simplified and contrived, this has happened to me in a real Nu script when the table structure changed.  Nu only seems to check the *number* of columns being inserted.

I see that this is because `into_sqlite.rs` parses the column names, but it only uses them for the `CREATE TABLE`.  When the `INSERT` is performed, only the positional values are used.

### Expected behavior

Use the column names of the Nushell records when performing the `INSERT`.  E.g.:

```SQL
INSERT INTO main (name, modified, size) VALUES
  ('foo', '2023-12-27 10:32:40.227788746 -05:00', 0),
  ('bar', '2023-12-27 10:32:40.227788746 -05:00', 0);
```

### Screenshots

_No response_

### Configuration

| key                | value                                                                           |
| ------------------ | ------------------------------------------------------------------------------- |
| version            | 0.88.1                                                                          |
| branch             |                                                                                 |
| commit_hash        |                                                                                 |
| build_os           | linux-x86_64                                                                    |
| build_target       | x86_64-unknown-linux-gnu                                                        |
| rust_version       | rustc 1.74.0 (79e9716c9 2023-11-13) (built from a source tarball)               |
| cargo_version      | cargo 1.74.0                                                                    |
| build_time         | 1980-01-01 00:00:00 +00:00                                                      |
| build_rust_channel | release                                                                         |
| allocator          | mimalloc                                                                        |
| features           | dataframe, default, extra, sqlite, trash, which, zip                            |
| installed_plugins  | from eml, from ics, from ini, from vcf, query, query json, query web, query xml |

### Additional context

_No response_

### LINKED ISSUE #12011: into sqlite expects column order to be the same thoughout the data
### Describe the bug

If I have data with named columns but in different order, they are messed up in the sqlite db.
Here is how that can be verified

```
~> [{"a":"a1","b":"b1"},{"b":"b2","a":"a2"}]                                                                                                                                                                  
╭───┬────┬────╮
│ # │ a  │ b  │
├───┼────┼────┤
│ 0 │ a1 │ b1 │
│ 1 │ a2 │ b2 │
╰───┴────┴────╯
~> [{"a":"a1","b":"b1"},{"b":"b2","a":"a2"}] | into sqlite test.db                                                                                                                                                        
~> open test.db | get main                                                                                                                                                                                                    
╭───┬────┬────╮
│ # │ a  │ b  │
├───┼────┼────┤
│ 0 │ a1 │ b1 │
│ 1 │ b2 │ a2 │
╰───┴────┴────╯ 

workaround: [{"a":"a1","b":"b1"},{"b":"b2","a":"a2"}] | select a b  | into sqlite test.db

```

### How to reproduce

See above

### Expected behavior

I expect the output from "open test.db | get main" to be the same table as the data before I put it in.

### Screenshots

_No response_

### Configuration

```
| key                | value                                                |
| ------------------ | ---------------------------------------------------- |
| version            | 0.90.1                                               |
| branch             |                                                      |
| commit_hash        |                                                      |
| build_os           | macos-x86_64                                         |
| build_target       | x86_64-apple-darwin                                  |
| rust_version       | rustc 1.75.0 (82e1608df 2023-12-21) (Homebrew)       |
| cargo_version      | cargo 1.75.0                                         |
| build_time         | 2024-02-06 22:28:49 +00:00                           |
| build_rust_channel | release                                              |
| allocator          | mimalloc                                             |
| features           | dataframe, default, extra, sqlite, trash, which, zip |
| installed_plugins  |                                                      |
```

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by NowackiPatryk**
- fixes #11429
- fixes #12011

### CODE REVIEW

**Comment by NowackiPatryk** [comment]
> This doesn't seem to fix #12011 but if I understand correctly, it should, I think.

Indeed, gonna dig deeper then

**Comment by NowackiPatryk** [comment]
@rgwood Now it seems to be working as expected. Problem: Insert statement was created once and all sets of data were processed through it. Now insert statement is being created for every set individually.

**Comment by fdncred** [comment]
> Now insert statement is being created for every set individually.

hmmmm, I wonder how that will affect performance?  Thanks for working on it!

**Comment by fdncred** [comment]
Seems to work. Thanks!

**Comment by rgwood** [comment]
@NowackiPatryk I have some concerns about the approach taken in this PR. It looks like you're doing all of the following for _every_ Value we attempt to insert:

1. Try to CREATE the database table
2. Create a new transaction
3. Create an INSERT statement
4. Attempt to run the statement
5. Commit the transaction

This is likely going to be very slow. I think steps 1,2 and 5 should only happen once even if we're inserting multiple Values.

**Comment by rgwood** [comment]
Confirmed the performance impact of this PR. Just measured on a 10,000 row table, it went from 19ms to 18,578ms - about 1000x slower. I am guessing the main culprit is the additional COMMIT calls, in my experience those are very slow.

**Comment by fdncred** [comment]
@rgwood of course, you're right. I started a revert for this pr https://github.com/nushell/nushell/pull/12112 in case @NowackiPatryk or someone else doesn't tweak this.

**Pull request merged**
