### PR TITLE
Switch from dirs_next 2.0 to dirs 5.0

### PR DESCRIPTION
**Pull request by jcgruenhage**
# Description

Replaces the `dirs_next` family of crates with `dirs`. `dirs_next` was born when the `dirs` crates were abandoned three years ago, but they're being maintained again and most projects depend on `dirs` nowadays. `dirs_next` has been abandoned since.

This came up while working on https://github.com/nushell/nushell/pull/13382.

# User-Facing Changes

None.

# Tests + Formatting

Tests and formatter have been run.

# After Submitting

### CODE REVIEW

**Comment by devyn** [comment]
Are there any changes in the directories returned by the two crates that would affect us?

**Comment by jcgruenhage** [comment]
From my comparison of https://github.com/xdg-rs/dirs/blob/master/dirs/CHANGELOG.md (dirs_next) and https://github.com/dirs-dev/dirs-rs?tab=readme-ov-file#changelog (dirs), I'd say there are no changes that affect us.

**Comment by devyn** [comment]
Sounds right to me.

**Comment by devyn** [comment]
@fdncred do you think we have enough time before the release to be ok with this, so we can catch anything across the supported platforms? It shouldn't change anything, but we do use the dirs to look up config locations a lot, so we should be sure we don't break something.

**Comment by fdncred** [comment]
I'm ok with switching crates if we land this today or tomorrow. We actually used to use dirs. Then it was unsupported and chose dirs-next. Seems like it's switched again.

**Comment by fdncred** [comment]
Thanks

**Pull request merged**
