### PR TITLE
Line buffer editor

### PR DESCRIPTION
**Pull request by elferherrera**
# Description

Introduces a new keybinding (ctr+e) that opens an editor to modify the current line buffer. The default line editor in the config file is `emacs`. It should be changed in the user's config file

# Tests

Make sure you've run and fixed any issues with these commands:

- [ ] `cargo fmt --all -- --check` to check standard code formatting (`cargo fmt --all` applies these changes)
- [ ] `cargo clippy --all --all-features -- -D warnings -D clippy::unwrap_used -A clippy::needless_collect` to check that you're using the standard code style
- [ ] `cargo build; cargo test --all --all-features` to check that all the tests pass

### CODE REVIEW

**Comment by jmoore34** [comment]
Very nice change. Does the ctrl-e binding conflict with the default `MoveToLineEnd` binding?

**Comment by yerlaser** [comment]
This is very cool. Thanks.

However, I just tried a custom keybinding to OpenEditor event and the parser refuses it.

```
event: {send: OpenEditor}
    ·                    ─────────┬────────
    ·                             ╰── expected Reedline event, got openeditor
```

**Comment by elferherrera** [comment]
I've changed the keybinding to ctrl+I
That shouldn't collide with the other keybindings

**Comment by NotTheDr01ds** [comment]
@elferherrera Isn't ctrl+i just the same as the Tab key for most terminals?  That triggers auto-completion for me.  Tested in Windows Terminal and xterm, along with `keybindings listen`, all with the same results.

**Comment by NotTheDr01ds** [comment]
Is now Ctrl+o for those searching

**Pull request merged**
