### PR TITLE
Fix CPU usage info in `sys`

### LINKED ISSUE #8264: CPU usage is always reported as 0 in sys
### Describe the bug

CPU usage is always reported as 0 on windows.

### How to reproduce

Run 

```nu
sys | get cpu | get cpu_usage
```

### Expected behavior

The output should reflect the actual CPU usage (as reported by task manager for instance).

### Screenshots

_No response_

### Configuration

| key                | value                                           |
| ------------------ | ----------------------------------------------- |
| version            | 0.76.0                                          |
| branch             |                                                 |
| commit_hash        |                                                 |
| build_os           | windows-x86_64                                  |
| build_target       | x86_64-pc-windows-msvc                          |
| rust_version       | rustc 1.67.1 (d5a82bbd2 2023-02-07)             |
| rust_channel       | stable-x86_64-pc-windows-msvc                   |
| cargo_version      | cargo 1.67.1 (8ecd4f20a 2023-01-10)             |
| pkg_version        | 0.76.0                                          |
| build_time         | 2023-02-24 17:17:11 +01:00                      |
| build_rust_channel | release                                         |
| features           | database, dataframe, default, trash, which, zip |
| installed_plugins  | gstat                                           |

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by rgwood**
Closes #8264. This PR does a few things to fix the `usage` column in `sys.cpu`:

1. Sleep a while (~400ms) between calls to `sys.refresh_cpu()`, [as required by `sysinfo`](https://docs.rs/sysinfo/latest/sysinfo/trait.SystemExt.html#method.refresh_cpu)
2. Change `sys` to return a `LazyRecord` (so you can do things like `sys | get host` instantly without waiting for CPU info)
3. Update our `sysinfo` dependency to [fix CPU usage calculations on Linux](https://github.com/GuillaumeGomez/sysinfo/pull/946)

CPU usage is no longer always reported as zero:

image

### CODE REVIEW

**Comment by rgwood** [comment]
FWIW, the CPU usage numbers we get from `sysinfo` still seem a little iffy. I'm not sure how accurate they are; perhaps within a couple percent?

There's a tradeoff between 2 extremes:
1. Wait a long time between refreshes for more accurate data
2. Wait a very short time so users get `sys` results quickly

Hard to say where exactly we want to land on that spectrum.

**Comment by fdncred** [comment]
I can't get this to print anything either. Weird that there's noting > 0 and < 2.4
```
mut counter = 0
while $counter < 25 { 
 sys | get cpu | where cpu_usage > 0.00 and cpu_usage < 2.40
 $counter += 1
 # sleep 500ms
}
```

**Comment by rgwood** [comment]
> Weird that there's noting > 0 and < 2.4

Agreed. I _suspect_ it's because the CPU performance counters used under the hood are fairly low-resolution; seems like we need to wait longer if we want more accuracy.

**Comment by fdncred** [comment]
I just changed it to 
- `* 3` and got mostly 1.60's between that range and one 1.70. 
- `* 4` and got mostly 1.20's and some 1.30
- `* 5` and got mostly 1.00 and some 2.00 but it was significantly slower

There's some black magic going on.

**Comment by jntrnr** [comment]
@rgwood would it be worth removing that column and not using the feature?

**Comment by rgwood** [comment]
@jntrnr I lean toward keeping it; could give it a try for now?

I believe that the sysinfo CPU numbers are inherently imprecise (error somewhere in the single-digit percentages) when measured over a few hundred milliseconds; the performance counters they're accessing aren't granular enough. After the recent sysinfo v28.2 bug fix I think that the numbers we're seeing now are _imprecise_ but not _inaccurate_.

I think we've landed at an okay place on the accuracy/time tradeoff curve, at least to start.

**Pull request merged**
