### PR TITLE
Remove unnecessary `cwd`, `pipeline()`, `r#` from various tests

### PR DESCRIPTION
**Pull request by hanjunghyuk**
# Description

This PR cleans up tests in the `tests/` directory by removing unnecessary code.
Part of #8670.

- [x]  const_/mod.rs
- [x]  eval/mod.rs
- [x]  hooks/mod.rs
- [x]  modules/mod.rs
- [x]  overlays/mod.rs
- [x]  parsing/mod.rs
- [x]  scope/mod.rs
- [x]  shell/environment/env.rs
- [x]  shell/environment/nu_env.rs
- [x]  shell/mod.rs
- [x]  shell/pipeline/commands/external.rs
- [x]  shell/pipeline/commands/internal.rs
- [x]  shell/pipeline/mod.rs

# User-Facing Changes

# Tests + Formatting

# After Submitting

### CODE REVIEW

**Review by amtoine — APPROVED** [review]
i think this is a step in the right direction, thanks @hanjunghyuk for taking the time :blush:

**Review by amtoine — APPROVED** [review]
wow, the tests went wild with time :laughing: 

still looks good to me :ok_hand:

**Comment by amtoine** [comment]
@hanjunghyuk 
do you want to work on even more tests or are we good to land here? :relieved:

**Comment by hanjunghyuk** [comment]
@amtoine I think I'm good here 👍

**Comment by amtoine** [comment]
great, let's land this then :partying_face: 
thanks again for tackling so many tests :blush:

**Pull request merged**
