### PR TITLE
use "search_result" style to colorize matching strings (fixes #9275)

### LINKED ISSUE #9275: change style of search results
### Question

There doesn't seem to be a way to change style of search results highlighting. It's always red background with the default foreground. 

Digging through the code I found find calls style computer with "search result" style name at https://github.com/nushell/nushell/blob/74724dee809c039440ce299db65ee5ad5aa321ea/crates/nu-command/src/filters/find.rs#L403, but attempts to add "search result" to color config did nothing. 

Is there a way to style search result?

### Additional context and details

_No response_

### PR DESCRIPTION
**Pull request by solodov**
This change introduces new `search_result` style supported in the color config. The change also removes obsolete check for `config.ls_colors` for computing the style. `config.ls_colors` has been removed last year, so this removes the reference to the obsolete flag, along with a cleanup that removes all the code that used to rely on ls_colors for highlighting search results.

# Description

# User-Facing Changes

# Tests + Formatting

# After Submitting

### CODE REVIEW

**Comment by fdncred** [comment]
Looking good. Thanks! I'm anxious to test it. 

I'd prefer the default to be what it is now, white on red, versus red_reverse.

**Comment by solodov** [comment]
updated default style

**Comment by fdncred** [comment]
For testing I made mine `red_reverse`, just so I could see if the color was working. I think some ansi sequences aren't getting reset somewhere (note the white lines)
image

Also, `help -f arg` doesn't highlight at all now. I'm not sure why. It's finding the right entries but not highlighting them properly.
image

**Comment by solodov** [comment]
I think it's fixed now. The find test case was testing for the right reset
escape sequence, that change is now undone and everything passes. I ran
your examples too, all looks good to me.

**Comment by fdncred** [comment]
@solodov I'm not sure I'd call this fixed. At least both commands have identical output now.
```
help commands | find arg
```
image

**Comment by fdncred** [comment]
@zhiburt Do you have any idea why having a smaller terminal window, which causes wrapping, would change the way the highlight rendering works?

@solodov I'm not sure but I think it has to be related to your PR since we don't have this problem before your PR? I just tested that. I kind of wonder if line endings are getting messed up somehow in the wrapping.

**Comment by solodov** [comment]
I think I know what's going on. The example I tested is with `search_result` set to `blue_reverse`. If I change it to `{fg: white bg: blue}' everything works correctly, even with wrapping. I don't think it's my change, it's likely a more general problem with how reverse bit is handled.

SCR-20230601-muuk

**Comment by solodov** [comment]
nice call on `debug -r`, I didn't know that. However, debug produces a string without wrapping. If you try to print that string it's shown as expected. 

However, here's something weird, in the latest unmodified release of nushell with `string` style set to `blue_reserve`:

SCR-20230601-nzaj

I think we can now conclude it's not my change :)

**Comment by fdncred** [comment]
ya, you're right. i saw that change earlier. we can probably land this if the ci is green.

**Comment by fdncred** [comment]
I created issue #9335 to pinpoint the issue we discovered here.

**Comment by fdncred** [comment]
ok, let's land this since the default is to work the same way it does now. this pr does allow us to demonstrate the error more easily. hopefully we don't get a ton of "why is this colored wrong" before we can get it fixed.

**Comment by fdncred** [comment]
It's looking like this PR may have broken some things too See #9397. This command
```
❯ ls | find toml md sh
```
needs to color using LS_COLORS and then highlight using the configured highlighting color.

**Comment by fdncred** [comment]
Thank you. It's always behaved the way I described. It would be wonderful to restore that behavior. Truly appreciate your help!

**Pull request merged**
