### PR TITLE
move git completions out of default_config.nu

### PR DESCRIPTION
**Pull request by raboof**
but leave a reference recommending people include them themselves

# Description

a first primitive step of what has been discussed in
https://github.com/nushell/nushell/pull/5253

# Tests

Make sure you've run and fixed any issues with these commands:

- [ ] `cargo fmt --all -- --check` to check standard code formatting (`cargo fmt --all` applies these changes)
- [ ] `cargo clippy --all --all-features -- -D warnings -D clippy::unwrap_used -A clippy::needless_collect` to check that you're using the standard code style
- [ ] `cargo build; cargo test --all --all-features` to check that all the tests pass

### CODE REVIEW

**Comment by jntrnr** [comment]
Hmmm :thinking: 

I *think* we want to bundle them in with the default installer like we do with env.nu and config.nu, but I'm not exactly sure how just yet. Might be a good thing to jump into the discord to talk through so other folks can jump in.

**Comment by fdncred** [comment]
I personally like this PR with the completions removed and the comment left in it pointing to where our completions live. I'd leave it like this and land it because the config is supposed to be the "truth" as far as defaults are concerned and there are no hard-coded custom-completions.

**Comment by jackos** [comment]
From an outsider's perspective, I was just trying it out after hearing about new features, I had a config already from trying it out a few months ago which meant that git completions didn't work. I then went to nu-scripts and got the git completion using the `source` keyword in `config.nu`, I had to remove the export keywords to get it to work.

My strong suggestion would be to have a folder with completion scripts in `~/.config/nushell/completions`, and have default widely used ones like `git.nu` and `cargo.nu` in there, make it so they are just automatically loaded if they're in that folder. This makes it clear for people to see how simple the completion scripts are so they can start writing there own, and avoids this problem of overwriting the popular git completions when they're a default.

**Comment by elferherrera** [comment]
I also like the idea of removing it from the config. We may also remove the example menus and leave them in the book

**Comment by fdncred** [comment]
If we rebase this PR onto the latest main branch, I think we could achieve a compromise by just commenting out the git completions but leaving them in the config.nu. Then they're there for people to learn from but they are "disabled" by default. Agree/Disagree?

**Comment by fdncred** [comment]
apparently, this isn't going to get done

**Pull request closed without merging**
