### PR TITLE
Remove `--encoding` argument during register plugin

### PR DESCRIPTION
**Pull request by WindSoilder**
# Description

## About the change
Currently, register command is something like this:
```
register -e msgpack ~/.cargo/bin/nu_plugin_example
```

This pr is going to make register command easier, so we can just type something like this:
```
register ~/.cargo/bin/nu_plugin_example
```

No need to provide protocol by hand
Closes: #5944

## WARN
And... yeah, it's a breaking change, we need to register these again to fit the new change.

## About the design
Currently, the communication between nushell and plugin is something like this:
```
  NUSHELL                PLUGIN
    │                     │
    ├────────────────────►│
    │    JSON CALL        │
    │                     │
    │◄────────────────────┤
    │    JSON RESPONSE    │
    │                     │
```
Nushell need to know how to encode/decode message and send to / response from plugin, so we tell Nushell by `-e` flag.

But the encoding format is predefined in plugin, NUSHELL can get encoding information from PLUGIN, `-e` seems unnecessary to user, after removing, the communication between nushell and plugin is something like this:
```

  NUSHELL               PLUGIN
    │                     │
    │◄────────────────────┤
    │ TELL ENCODING FORMAT│
    │                     │
    ├────────────────────►│
    │    JSON CALL        │
    │                     │
    │◄────────────────────┤
    │    JSON RESPONSE    │
    │                     │
```

Although plugin send one more message to NUSHELL, but the communication just happened on the same machine, I think that's ok.
One more thing we can get from the new design: if one plugin changed encoding format, we don't need to retype `register` again to refresh the plugin.

### TELL ENCODING FORMAT
The message contains 1 byte telling the body length, the rest is the body.

Like: `4json` or `7msgpack`.

# Tests

Make sure you've done the following:

- [X] Add tests that cover your changes, either in the command examples, the crate/tests folder, or in the /tests folder.
- [X] Try to think about corner cases and various ways how your changes could break. Cover them with tests.
- [X] If adding tests is not possible, please document in the PR body a minimal example with steps on how to reproduce so one can verify your change works.

Make sure you've run and fixed any issues with these commands:

- [X] `cargo fmt --all -- --check` to check standard code formatting (`cargo fmt --all` applies these changes)
- [X] `cargo clippy --workspace --features=extra -- -D warnings -D clippy::unwrap_used -A clippy::needless_collect` to check that you're using the standard code style
- [X] `cargo test --workspace --features=extra` to check that all the tests pass

### CODE REVIEW

**Comment by fdncred** [comment]
Nice! Good work. Since the release is tomorrow, I'd like to wait on this one until after the release.

**Comment by sholderbach** [comment]
Are we happy to land? Do we need to have PR's in other repos ready for the next release?

**Comment by WindSoilder** [comment]
> Do we need to have PR's in other repos ready for the next release?

I don't think so :-)

**Comment by fdncred** [comment]
ok, let's try it out. we'll have to eventually update the docs to match.

**Comment by fdncred** [comment]
@WindSoilder can you look at this. i can't get plugins to register and it's just hanging nushell.

**Comment by fdncred** [comment]
nevermind - i was trying to register the old plugins. once i compiled the plugins again with this new code it worked. sorry for the false alarm.

**Comment by sholderbach** [comment]
After merging an unrelated PR #6495 we got a CI failure on `main` for a plugin test for macOS.

https://github.com/nushell/nushell/runs/8249199634?check_suite_focus=true#step:5:733

**Comment by WindSoilder** [comment]
Sorry I can't reproduce it on my machine, I'll dig a little deeper and see if something can be done here

**Comment by sholderbach** [comment]
Rerunning the test also seems to resolve it.

**Pull request merged**
