### PR TITLE
Windows: only shell out to cmd for specific commands

### PR DESCRIPTION
**Pull request by rgwood**
# Description

Nu has behaviour on Windows where, when it can't find an executable on disk, it will "shell out" to cmd.exe. This is because [some common shell commands are implemented internally in cmd.exe and do not exist on disk](https://ss64.com/nt/syntax-internal.html). This PR changes the behaviour so we only shell out for a specific set of known internal commands: ASSOC, DIR, ECHO, FTYPE, MKLINK, START, VER, VOL

# Deets

This change is motivated by 2 considerations:
1. cmd.exe's error messages are not as nice as Nu/Miette errors
2. Shelling out to cmd.exe makes it difficult to programmatically determine when a command could not be found at all ([example](https://github.com/nushell/nushell/issues/4996))

I read through the full list of internal commands, and determined that those are the only ones likely to be useful in Nu. [Here's a spreadsheet with reasoning for each command](https://1drv.ms/x/s!ApnCVOIY9OCytk7MK8PmJoxngdxP?e=epjHF1).

Prior to this PR:
image

After this PR:
image

# Tests

Make sure you've done the following:

- [ ] Add tests that cover your changes, either in the command examples, the crate/tests folder, or in the /tests folder.
- [ ] Try to think about corner cases and various ways how your changes could break. Cover them with tests.
- [x] If adding tests is not possible, please document in the PR body a minimal example with steps on how to reproduce so one can verify your change works.

(no tests added - I think our existing tests cover this)

Make sure you've run and fixed any issues with these commands:

- [x] `cargo fmt --all -- --check` to check standard code formatting (`cargo fmt --all` applies these changes)
- [x] `cargo clippy --workspace --features=extra -- -D warnings -D clippy::unwrap_used -A clippy::needless_collect` to check that you're using the standard code style
- [x] `cargo test --workspace --features=extra` to check that all the tests pass

### CODE REVIEW

**Comment by fdncred** [comment]
The only other built in that I use for troubleshooting sometimes in windows is `type` but it's rare that I need it. I typical use cat, bat, or open. So, I wouldn't hold up this PR for that. Also, if people complain, it's easy enough to add later if needed.

**Comment by hustcer** [comment]
So can this issue: https://github.com/nushell/nushell/issues/4932 be closed?

**Comment by rgwood** [comment]
@hustcer Yes I think so

**Comment by CAD97** [comment]
Circling back: it seems `assoc`/`ftype` may be useless on Win8 and later: https://stackoverflow.com/a/51727990

I haven't tested, but this does merit investigation; if the builtins don't even function properly anymore, then exposing them through nushell doesn't make any sense.

**Comment by rgwood** [comment]
@CAD97 Good catch, agreed. Are you able to confirm that and submit a PR?

**Comment by CAD97** [comment]
I can confirm that `assoc`/`ftype` are shoing html associated to IE despite that not being the case on my machine. Opened https://github.com/nushell/nushell/pull/6441

**Pull request merged**
