### PR TITLE
To html with color

### PR DESCRIPTION
**Pull request by fdncred**
This PR adds flags to `to html` to:
* change ansi color to html color using `--html_color`
* remove ansi color altogether using `--no_color`

In order to test it you need something that produces ansi color. It's easy to test this with any nu command that has examples in the help because the examples are colored. I tested with `cd --help | to html --html_color`

### CODE REVIEW

**Comment by jonathandturner** [comment]
This looks good so far.

@fdncred can you throw in a few tests to ensure that we keep this working?

**Comment by fdncred** [comment]
Yes, I've added tests that don't pass. LOL - still more work to do. Spent 6 hours on this change today - sick of it - need a break. This has become much more of a pain that it originally was due to the complexity of changing colors from ansi to html. I may end up removing the `--html_color` flag since it's such a pain. It's more of a nice-to-have, than required.

**Comment by fdncred** [comment]
@jonathandturner Take another look whenever you get a chance please. I think I figured out where it was failing. Thanks for suggesting the tests. I'm terrible at remembering them. The test actually revealed several problems that are now all, hopefully, fixed.

**Comment by jonathandturner** [comment]
Oh good. Yeah looks okay

**Pull request merged**
