### PR TITLE
Allow duration defaults

### LINKED ISSUE #9217: Function input can't assign default closure/duration/filesize/range anymore
### Describe the bug

Function input can have default closure in version 0.79. But this becomes not available in 0.80.

### How to reproduce

```nu
def f [ g = { $in } ] {}
```

Also:

```nu
def f1 [ g = 1sec ] {}
def f2 [ g = 1mb ] {}
def f3 [ g = 1..2 ] {}
```

### Expected behavior

Should be able to define a closure as default.

### Screenshots

image

### Configuration

| key                | value                                                                                       |
| ------------------ | ------------------------------------------------------------------------------------------- |
| version            | 0.80.0                                                                                      |
| branch             | makepkg                                                                                     |
| commit_hash        | 8695b575848d5eb4d688087aa9e906b4d9e7c8d8                                                    |
| build_os           | linux-x86_64                                                                                |
| build_target       | x86_64-unknown-linux-gnu                                                                    |
| rust_version       | rustc 1.69.0 (84c898d65 2023-04-16) (Arch Linux rust 1:1.69.0-3)                            |
| cargo_version      | cargo 1.69.0                                                                                |
| build_time         | 2023-05-17 05:13:57 +00:00                                                                  |
| build_rust_channel | release                                                                                     |
| features           | default, zip                                                                                |
| installed_plugins  | from eml, from ics, from ini, from vcf, gstat, inc, query, query json, query web, query xml |

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by MariaSolOs**
# Description

Fixes #9217 (some cases, still can't accept all default expressions)

# User-Facing Changes

- Follow-up of #8940, expanding `eval_constant` so that it can also evaluate values with units.

# Tests + Formatting

- A unit test was added to verify that defaults like `1sec` are accepted.

### CODE REVIEW

**Comment by MariaSolOs** [comment]
Ehhh should I be concerned about the failed coverage check? 😅

**Review by amtoine — APPROVED** [review]
thanks maria :blush:

**Comment by MariaSolOs** [comment]
Always happy to help!

**Comment by 1Kinoti** [comment]
> i did notice, unrelated to this pr, that it's kind of weird how our file sizes reduce. 1mb says 1000.0kb, 1kb says 1,000 b, etc. i mean, i guess it's right, but it's kind of weird.

[this](https://github.com/nushell/nushell/blob/9b139330f834a6d5916190041fcb15b8e51efc66/crates/nu-parser/src/parser.rs#L2280) conversion is the one responsible for this reduction. the conversion values come from the third part of [this](https://github.com/nushell/nushell/blob/9b139330f834a6d5916190041fcb15b8e51efc66/crates/nu-parser/src/parser.rs#L2313) tuple.

**Comment by fdncred** [comment]
@1Kinoti has it always reduced this way, i can't remember?

**Comment by 1Kinoti** [comment]
i just copied [it](https://github.com/nushell/nushell/blob/6a0c88d516faf9fd1165fddbd7ef69ba47f97cc6/crates/nu-parser/src/parser.rs#LL2360C1-L2376C7) over in #9190, so yes

**Pull request merged**
