### PR TITLE
Into cell path

### LINKED ISSUE #6597: `get` should accept cellpath specified as string
### Describe the bug

`get` accepts symbols of form `a.b` now (from the REPL) but when defining custom functions, it is awkward to pass in a literal symbol (nu is not lisp, after all), and accidentally passing `'a.b'` as a cell path spec for `get` just surprises users.

### How to reproduce

```{nu}
{a: 1, b:{b1:21, b2:22}} | get $s
{a: 1, b:{b1:21, b2:22}} | get b.b1
let s = 'b.b1'
{a: 1, b:{b1:21, b2:22}} | get $s
let data = {a: 1, b:{b1:21, b2:22}}
$s | split row '.' | reduce --fold $data {|it,acc| $acc | get $it}
def my-get [cellpath: string] {let data = $in; $cellpath | split row '.' | reduce --fold $data {|it,acc| $acc | get $it}}
{a: 1, b:{b1:21, b2:22}} | my-get 'b.b1'
```

### Expected behavior

Same behavior as if the passed string literal is passed directly to `get` at the REPL level (recursively `get` until done, failing at the earliest non-existent field).

### Screenshots

image

Here is a simple workaround for `get` that works better:
image

### Configuration

| key                | value                                                                                                                                                             |
| ------------------ | ----------------------------------------------------------------------------------------------------------------------------------------------------------------- |
| version            | 0.68.1                                                                                                                                                            |
| branch             |                                                                                                                                                                   |
| commit_hash        |                                                                                                                                                                   |
| build_os           | macos-x86_64                                                                                                                                                      |
| build_target       | x86_64-apple-darwin                                                                                                                                               |
| rust_version       | rustc 1.63.0                                                                                                                                                      |
| cargo_version      | cargo 1.63.0 (fd9c4297c 2022-07-01)                                                                                                                               |
| pkg_version        | 0.68.1                                                                                                                                                            |
| build_time         | 2022-09-08 20:41:49 +00:00                                                                                                                                        |
| build_rust_channel | release                                                                                                                                                           |
| features           | database, dataframe, default, trash, which, zip                                                                                                                   |
| installed_plugins  | custom-value generate, custom-value generate2, custom-value update, gstat, inc, nu-example-1, nu-example-2, nu-example-3, query, query json, query web, query xml |

### Additional context

_No response_

### LINKED ISSUE #8466: allow accessing data with deep variable path
### Related problem

i have some data i would like to run a closure on top of, without knowing in advance what the exact path in the data is nor the exact value i work with.

this works with a single depth-path, e.g. `a`, but not with multiple levels, e.g. `a.b.c.1`

e.g.
- define some data
```nushell
let data = {a: {b: {c: [1 2 3]}}}
```
- :heavy_check_mark: this works
```nushell
>_ let target = "a"
>_ $data | get $target
╭───┬───────────────────╮
│   │ ╭───┬───────────╮ │
│ b │ │   │ ╭───┬───╮ │ │
│   │ │ c │ │ 0 │ 1 │ │ │
│   │ │   │ │ 1 │ 2 │ │ │
│   │ │   │ │ 2 │ 3 │ │ │
│   │ │   │ ╰───┴───╯ │ │
│   │ ╰───┴───────────╯ │
╰───┴───────────────────╯
>_ $data | update $target []
╭───┬────────────────╮
│ a │ [list 0 items] │
╰───┴────────────────╯
```
- :x: but this does not work
```nushell
>_ let target = "a.b.c.1"
>_ $data | get $target
Error: nu::shell::column_not_found

  × Cannot find column
   ╭─[entry #14:1:1]
 1 │ $data | get $target
   · ──┬──       ───┬───
   ·   │            ╰── cannot find column 'a.b.c.1'
   ·   ╰── value originates here
   ╰────

>_ $data | update $target 0
Error: nu::shell::column_not_found

  × Cannot find column
   ╭─[entry #16:1:1]
 1 │ $data | update $target 0
   · ──┬──          ───┬───
   ·   │               ╰── cannot find column 'a.b.c.1'

   ·   ╰── value originates here
   ╰────
```

### Describe the solution you'd like

- with the same data
```nushell
let data = {a: {b: {c: [1 2 3]}}}
```
- :heavy_check_mark: this would still work
```nushell
>_ let target = "a"
>_ $data | get $target
╭───┬───────────────────╮
│   │ ╭───┬───────────╮ │
│ b │ │   │ ╭───┬───╮ │ │
│   │ │ c │ │ 0 │ 1 │ │ │
│   │ │   │ │ 1 │ 2 │ │ │
│   │ │   │ │ 2 │ 3 │ │ │
│   │ │   │ ╰───┴───╯ │ │
│   │ ╰───┴───────────╯ │
╰───┴───────────────────╯
>_ $data | update $target []
╭───┬────────────────╮
│ a │ [list 0 items] │
╰───┴────────────────╯
```
- :heavy_check_mark: and this would work as well
```nushell
>_ let target = "a.b.c.1"
>_ $data | get $target
2
>_ $data | update $target 0
╭───┬───────────────────────────╮
│   │ ╭───┬───────────────────╮ │
│ a │ │   │ ╭───┬───────────╮ │ │
│   │ │ b │ │   │ ╭───┬───╮ │ │ │
│   │ │   │ │ c │ │ 0 │ 1 │ │ │ │
│   │ │   │ │   │ │ 1 │ 0 │ │ │ │
│   │ │   │ │   │ │ 2 │ 3 │ │ │ │
│   │ │   │ │   │ ╰───┴───╯ │ │ │
│   │ │   │ ╰───┴───────────╯ │ │
│   │ ╰───┴───────────────────╯ │
╰───┴───────────────────────────╯
```

### Describe alternatives you've considered

_No response_

### Additional context and details

_No response_

### PR DESCRIPTION
**Pull request by fdncred**
# Description

This PR is an attempt to allow you to specify cell-paths as strings and convert them for usage.

### Example 1 - Working now

```
> let a = {a: 1, b:{b1:21, b2:22}}
> let s = 'b.b1'
> $a | get b.b1
21
> $a | get $s 
Error: nu::shell::column_not_found

  × Cannot find column
   ╭─[entry #6:1:1]
 1 │ $a | get $s
   · ─┬       ─┬
   ·  │        ╰── cannot find column 'b.b1'
   ·  ╰── value originates here
   ╰────
> $a | get ($s | into cell-path)
21
```

### Example 2 - Working now

```
> let data = {a: {b: {c: [1 2 3]}}}
> let target = 'a'
> $data | get $target
╭───┬──────────────────╮
│ b │ {record 1 field} │
╰───┴──────────────────╯
> let target = "a.b.c"
> $data | get $target
Error: nu::shell::column_not_found

  × Cannot find column
   ╭─[entry #12:1:1]
 1 │ $data | get $target
   · ──┬──       ───┬───
   ·   │            ╰── cannot find column 'a.b.c'
   ·   ╰── value originates here
   ╰────
> $data | get ($target | into cell-path)
╭───┬───╮
│ 0 │ 1 │
│ 1 │ 2 │
│ 2 │ 3 │
╰───┴───╯
```

### Example 3 (still doesn't work - is '1' a cell-path in this example? The rest (a.b.c) are columns, but 1 is a row-index.)

```
> let target = "a.b.c.1"
> $data | get ($target | into cell-path)
Error: nu::shell::column_not_found

  × Cannot find column
   ╭─[entry #8:1:1]
 1 │ let data = {a: {b: {c: [1 2 3]}}}
   ·                         ┬
   ·                         ╰── value originates here
   ╰────
   ╭─[entry #19:1:1]
 1 │ $data | get ($target | into cell-path)
   ·                        ───────┬──────
   ·                               ╰── cannot find column '1'
   ╰────
```

closes #6597
closes #8466

# User-Facing Changes

I totally missed this PR https://github.com/nushell/nushell/pull/7417 which apparently got reverted here https://github.com/nushell/nushell/pull/7523. Interesting. Looks like I'm doing much of the same but perhaps not as nice. :)

# Tests + Formatting

Don't forget to add tests that cover your changes.

Make sure you've run and fixed any issues with these commands:

- `cargo fmt --all -- --check` to check standard code formatting (`cargo fmt --all` applies these changes)
- `cargo clippy --workspace -- -D warnings -D clippy::unwrap_used -A clippy::needless_collect` to check that you're using the standard code style
- `cargo test --workspace` to check that all tests pass

> **Note**
> from `nushell` you can also use the `toolkit` as follows
> ```bash
> use toolkit.nu  # or use an `env_change` hook to activate it automatically
> toolkit check pr
> ```

# After Submitting

If your PR had any user-facing changes, update [the documentation](https://github.com/nushell/nushell.github.io) after the PR is merged, if necessary. This will help us keep the docs up to date.

### CODE REVIEW

**Comment by jntrnr** [comment]
This feels a bit like `eval`-lite :) Something I was wondering about is if we support things like `$foo.$bar` in the future and use `$bar` as where we get the path from, would it break in this case? Same as we make paths more advanced, like being able to add searches to them `$foo.[name == 'bar*']` etc. Like it works fine for now, just thinking ahead a bit and wondering if future changes we do (like Riley's recent `?` syntax) might make this one tricky.

**Comment by fdncred** [comment]
I've been trying to get `lex` and `parse_cell_path` functions hooked up so the cell path can be parsed properly but I'm just running into dead ends everywhere.

**Comment by Dorumin** [comment]
Kubouch's comment [here](https://github.com/nushell/nushell/pull/7417#issuecomment-1345264955) is relevant if you try to incorporate the parser at runtime on the string, it is very much eval-lite given you'd have to be able to follow variables at a minimum for it to be useful, and it gets worse when you get subexpressions like jt mentioned, so something like `[name == $var]` if it ever does land. I'm not super knowledgeable on nushell's parser, but that's the impression it left on me. Maybe `into cellpath` will have to be restricted to "static" paths that have all of their context inside the source string.

**Comment by fdncred** [comment]
Looks like this won't be happening. IMO, it's helpful to users as was #7417. Others disagree. The best work-able solution I heard about it was somehow changing the parser to allow cell-path literals but I'm not sure that'll ever see the light of day either.

**Pull request closed without merging**
