### PR TITLE
Add top-level crate documentation/READMEs

### PR DESCRIPTION
**Pull request by sholderbach**
# Description
Add `README.md` files to each crate in our workspace (-plugins) and also include it in the `lib.rs` documentation for <docs.rs> (if there is no existing `lib.rs` crate documentation) 

In all new README I added the defensive comment that the crates are not considered stable for public consumption. If necessary we can adjust this if we deem a crate useful for plugin authors.

### CODE REVIEW

**Comment by sholderbach** [comment]
Something in `nu-json` (which is a fork of `serde-hjson` originally) is up that it won't parse the example copied over from the original crate in the README. As I moved the README into `lib.rs` this now gets doctested and fails.

- https://crates.io/crates/serde-hjson

**Comment by drmason13** [comment]
> Something in `nu-json` (which is a fork of `serde-hjson` originally) is up that it won't parse the example copied over from the original crate in the README. As I moved the README into `lib.rs` this now gets doctested and fails.
> 
>     * https://crates.io/crates/serde-hjson

This seems like a bug, for some reason swapping the `#` for `//` will make the test pass even though both are supposed to be valid comment characters in hjson!

Also, a hint to the bug: doubling the `#` -> `## specify rate in requests/second`  will also make the test pass.

**Comment by sholderbach** [comment]
Thanks so much for narrowing it down @drmason13 ! 
Wondering, is there an interaction with the `rustdoc` markdown handling or is that also present for a direct use and a regression from `hjson`

**Comment by drmason13** [comment]
Remarkably, I can reproduce this using `serde-hjson 0.8.2`, so not a regression.

I think it must be an "edge case" where `#` is placed where otherwise a keyname would be expected.

**Comment by drmason13** [comment]
Oh you were right after all about the interaction with rustdoc markdown, nice one!

I've got a reproduction that feels like a bug in rustdoc - I've raised https://github.com/rust-lang/rust/issues/127702

`##` or `//` fixes it not because of the length of the comment characters and any parsing bug, but because it escapes or doesn't include a `#` and avoids rustdoc _partially removing the line from the str literal_ (yikes!)

the hjson parser was being given `specify rate in requests/second\n    rate` and rightly complaining that this isn't a valid key due to containing whitespace 😄

**Comment by drmason13** [comment]
so after all that distraction, I'd just using `//` instead of `#` since `##` will look weird in the README.

**Comment by sholderbach** [comment]
Thanks for figuring this out for me!

**Pull request merged**
