### PR TITLE
REFACTOR: remove deprecated commands (`old-alias`)

### PR DESCRIPTION
**Pull request by amtoine**
# Description
as stated in the `0.79` release note, this PR removes the `old-alias` and `export old-alias` commands, which were deprecated before.

# User-Facing Changes
`old-alias` is gone for good :relieved: 

# Tests + Formatting
- :green_circle: `toolkit fmt`
- :green_circle: `toolkit clippy`
- :green_circle: `toolkit test`
- :green_circle: `toolkit test stdlib`

# After Submitting
already mentionned in the `0.79` release note.

### CODE REVIEW

**Comment by fdncred** [comment]
Do we need to add `old-alias` to deprecated_commands.rs to notify people it's gone and to use `alias` now?

**Comment by amtoine** [comment]
@fdncred i've added `old-alias` to the deprecated commands in 002bd95d61d0bb974669a45ad61565f3255b915b

**Comment by amtoine** [comment]
also, i could 
1. remove `match` from `deprecated_commands`
2. add `math eval` to the function

in this PR or in another? :smirk:

**Comment by sholderbach** [comment]
Let's land this one and follow up with moving the rest of the commands in the `deprecated` category to the function (even though it doesn't handle subcommands) just to be defensive for the future if it should work. 

And yes `match` should be removed as it is now a parser keyword.

**Pull request merged**
