### PR TITLE
Change group-by to accept cell paths

### LINKED ISSUE #9003: `group-by` should accept `?` for optional path members
`group-by` fails if the specified column is not present on any rows:

```
> [{'a': 1}, {'a': 2} {}] | group-by a
Error: nu::shell::column_not_found

  × Cannot find column
   ╭─[entry #6:1:1]
 1 │ [{'a': 1}, {'a': 2} {}] | group-by a
   ·                     ─┬    ────┬───
   ·                      │        ╰── cannot find column 'a'
   ·                      ╰── value originates here
   ╰────
```
   
Would be nice if `group-by` worked with `?` so you could do `group-by a?` and it would ignore any rows without an `a` column.
   
Context: this came up as a usability issue on Discord https://discord.com/channels/601130461678272522/614593951969574961/1100648770326233199

### PR DESCRIPTION
**Pull request by rgwood**
Closes #9003.

This PR changes `group-by` so that its optional argument is interpreted as a cell path. In turn, this lets users use `?` to ignore rows that are missing the column they wish to group on. For example:

```
> [{foo: 123}, {foo: 234}, {bar: 345}] | group-by foo
Error: nu::shell::column_not_found

  × Cannot find column
   ╭─[entry #3:1:1]
 1 │ [{foo: 123}, {foo: 234}, {bar: 345}] | group-by foo
   ·                          ─────┬────             ─┬─
   ·                               │                  ╰── cannot find column 'foo'
   ·                               ╰── value originates here
   ╰────

> [{foo: 123}, {foo: 234}, {bar: 345}] | group-by foo?
╭─────┬───────────────╮
│ 123 │ [table 1 row] │
│ 234 │ [table 1 row] │
╰─────┴───────────────╯
```

~~This removes the ability to pass `group-by` a closure or block (I wasn't able to figure out how to make the 2 features coexist), and so it is a breaking change. I think this is OK; I didn't even know `group-by` could accept a closure or block because there was no example for that functionality.~~

### CODE REVIEW

**Comment by fdncred** [comment]
I think this is a cool PR, thanks! 

I'm wondering if we can follow @Sygmei's suggestion in Discord and create a separate `group-by block` so we don't lose that powerful type of grouping? Here's an example of how to use it.

```
ls | group-by { get name | path parse | get extension } 
╭──────┬─────────────────╮
│ md   │ [table 3 rows]  │
│ lock │ [table 1 row]   │
│ toml │ [table 3 rows]  │
│      │ [table 12 rows] │
│ txt  │ [table 1 row]   │
│ sh   │ [table 4 rows]  │
│ cmd  │ [table 1 row]   │
│ nu   │ [table 4 rows]  │
│ rs   │ [table 1 row]   │
│ yml  │ [table 1 row]   │
│ json │ [table 1 row]   │
│ ps1  │ [table 1 row]   │
╰──────┴─────────────────╯
```

**Comment by Sygmei** [comment]
I think you can make the two features co-exist by using the following `SyntaxShape`
```rust
            .optional(
                "grouper",
                SyntaxShape::OneOf(vec![
                    SyntaxShape::CellPath,
                    SyntaxShape::Block,
                    SyntaxShape::Closure(None),
                    SyntaxShape::Closure(Some(vec![SyntaxShape::Any])),
                ]),
 ```

**Comment by rgwood** [comment]
Good points, thanks. I might not have time/energy to implement that for a couple weeks.

@Sygmei would you like to take this issue+code and run with it? If not no worries, I'll get back to this eventually.

**Comment by Sygmei** [comment]
Sure, I'll give it a try !

**Comment by rgwood** [comment]
@Sygmei Any luck? I may be able to pick this up again soon if you don't have time to work on it.

**Comment by Sygmei** [comment]
Go ahead ! In the end I had a pretty busy schedule as well :(

**Comment by rgwood** [comment]
OK, this is ready to go! I've re-added the block/closure functionality and added an example.

**Review by fdncred — APPROVED** [review]
I'm glad you figured out a way to keep the block type and also have the optional type. It seems more powerful now.

**Comment by fdncred** [comment]
let's go!

**Pull request merged**
