### PR TITLE
Add an option to set header on border (style)

### PR DESCRIPTION
**Pull request by zhiburt**
fix #9796

Sorry that you've had the issues.
I've actually encountered them yesterday too (seems like they have appeared after some refactoring in the middle) but was not able to fix that rapid.

Created a bunch of tests.

cc: @fdncred 

Note:

This option will be certainly slower then a default ones. (could be fixed but ... maybe later).
Maybe it shall be cited somewhere.

PS: Haven't tested on a wrapped/expanded tables.

### CODE REVIEW

**Comment by fdncred** [comment]
Thanks @zhiburt. I tested it out and it works better now.

**Comment by fdncred** [comment]
btw - doesn't look bad with `sys | table -e` either
image

**Comment by fdncred** [comment]
Thanks @zhiburt for putting up with us and adding cool new features to tables in nushell. We appreciate all your efforts and I'm excited to see what else you come up with.

**Comment by hustcer** [comment]
Amazing

**Pull request merged**
