### PR TITLE
Feature: Userland LazyRecords

### PR DESCRIPTION
**Pull request by Dorumin**
# Description
Despite the innocent-looking title, this PR involves quite a few backend changes as the existing LazyRecord trait was not at all friendly towards the idea of these values being generated on the fly from Nu code.

In particular, here are a few changes involved:
- The LazyRecord trait now involves a lifetime `'a`, and this lifetime is used in the return value of `get_column_names`. This means it no longer returns `'static str`s (but implementations still can return these). This is more stringent on the consumption side.
- The LazyRecord trait now must be able to clone itself via a new `clone_value` method (as requiring `Clone` is not object safe). This pattern is borrowed from `Value::CustomValue`.
- LazyRecord no longer requires being serde serializable and deserializable.

These, in hand, allow for the following:
- LazyRecord can now clone itself, which means that they don't have to be collected into a Record when being cloned.
  - This is especially useful in Stack, which is cloned on each repl line and in a few other cases. This would mean that _every_ LazyRecord instance stored in a variable would be collected in its entirety and cloned, which can be catastrophic for performance. See: `let nulol = $nu`.
- LazyRecord's columns don't have to be static, they can have the same lifetime of the struct itself, so different instances of the same LazyRecord type can have different columns and values (like the new `NuLazyRecord`)
- Serialization and deserialization are no longer meaningless, they are simply less.

I would consider this PR very "drafty", but everything works. It probably requires some cleanup and testing, though, but I'd like some eyes and pointers first.

# User-Facing Changes
New command. New restrictions are largely internal. Maybe there are some plugins affected?

Example of new command's usage:
```
lazy make --columns [a b c] --get-value { |name| print $"getting ($name)"; $name | str upcase }
```

You can also trivially implement something like `lazy make record` to take a record of closures and turn it into a getter-like lazy struct:
```
def "lazy make record" [
    record: record
] {
    let columns = ($record | columns)

    lazy make --columns $columns --get-value { |col| do ($record | get $col) }
}
```

Open to bikeshedding. `lazy make` is similar to `error make` which is also in the core commands. I didn't like `make lazy` since it sounded like some transformation was going on.

# Tour for reviewers
Take a look at LazyMake's examples. They have `None` as the results, as such they aren't _really_ correct and aren't being tested at all. I didn't do this because creating the Value::LazyRecord is a little tricky and didn't want to risk messing it up, especially as the necessary variables aren't available when creating the examples (like stack and engine state).

Also take a look at NuLazyRecord's get_value implementation, or in general. It uses an Arc<Mutex<_>> for the stack, which must be accessed mutably for eval_block but get_value only provides us with a `&self`. This is a sad state of affairs, but I don't know if there's a better way.

On the same code path, we also have pipeline handling, and any pipeline that isn't a Pipeline::Value will return Value::nothing. I believe returning a Value::Error is probably better, or maybe some other handling. Couldn't decide on which ShellError to settle with for that branch.

The "unfortunate casualty" in the columns.rs file. I'm not sure just how bad that is, though, I simply had to fight a little with the borrow checker.

A few leftover comments like derives, comments about the now non-existing serde requirements, and impls. I'll definitely get around to those eventually but they're in atm

Should NuLazyRecord implement caching? I'm leaning heavily towards **yes**, this was one of the main reasons not to use a record of closures (besides convenience), but maybe it could be opt-out. I'd wonder about its implementation too, but a simple way would be to move a HashMap into the mutex state and keep cached values there.

### CODE REVIEW

**Review by rgwood — COMMENTED** [review]
Very cool! Some questions and observations:

1. Removing the hacky typetag+serializable requirement is great👍 
2. I'm surprised that `let nulol = $nu` collects `$nu` on every REPL line. That feels like a bug; do you know why it does that?
3. Do you have any use cases in mind for `lazy make`?

**Comment by Dorumin** [comment]
1. It is! I hope it doesn't break anything!
2. It was surprising when I found out about it. I was testing that indeed the LazyRecord would only evaluate the value when I accessed the key. But when I did something like `let lz = (lazy make ...)`, _every_ key got evaluated every time I pressed the enter key. This wasn't something with my code, it's because on every repl line, `Stack` is cloned, and in Stack's clone implementation, it collect()ed LazyRecord values as LazyRecords were unable to clone themselves due to object safety. That's why clone_value was added, and Stack clone now uses that method.
3. Yeah! Maybe! It's non-essential, you don't _need_ it but it is quite convenient if you want to improve the end user experience. I see lazy make as letting you create getters with automatic caching of values. This is more ergonomic over returning a simple record of closures as when evaluating the record directly, it would be very ugly, simply displaying lots of <Closure 000>s for values.

Concrete examples are as such kind of hard to come up with for this kind of quality of life improvement (better than passing closures everywhere), but I guess I can try. Maybe some encapsulation when creating objects for how the values themselves are being computed, instead being displayed automatically when table'd or evaluated when accessing needed props:
```sh
def "breed person" [name: string = "john doe", birthyear: int = 1987, status: string = "maidenless"] {
    # static props
    let inner = {
        callsign: ($name | split words | each { split chars | first } | str join | str upcase)
    }

    # ... methods (?)
    let age = { (date now | date format "%Y" | into int) - $birthyear }

    # public interface/getters
    lazy make record {
        age: $age,
        presentation: { $"hi, I'm ($name), (do $age) years old and currently ($status)" },
        callsign: { $inner.callsign }
    }
}
```

Or a use case closer to `sys`, wrapping individual accessors' functionality so only the necessary ones are executed, while also letting you get the whole object if needed
```sh
def "profile-api" [token: string] {
    lazy make --columns [ account relationships settings ] --get-value { |endpoint|
        http get $"https://fromsnippetstolove.rs/api/profile/($endpoint)" -H [Authentication $token]
    }
}
```

I honestly think I could come up with a better example for "intensive, separate work that maybe involves some I/O or disk" but it's not coming out right now. Maybe something with hashing

**Comment by rgwood** [comment]
I'd be up for giving this a try. Let's wait until after the next release (March 14) so we have more time to test it.

**Comment by rgwood** [comment]
The implementation looks good to me! If this gets cleaned up a bit and the tests pass, I think we should try it out.

**Comment by sholderbach** [comment]
What needs to be done/decided to finish this after the release on Tuesday?

**Comment by fdncred** [comment]
@Dorumin Can you please fix the conflicts so we can give this a try after on next release in a few days?

**Comment by Dorumin** [comment]
@fdncred Sorry about the radio silence, just checked my inbox and found this was still here. Not great at keeping up with stuff, but I cleaned up what was left and fixed the conflicts

**Comment by fdncred** [comment]
Thanks - today is release day so we'll probably wait until some time after the release. Appreciate your help.

**Pull request merged**
