### PR TITLE
do not attempt to glob expand if the file path is wrapped in quotes

### PR DESCRIPTION
**Pull request by WindSoilder**
# Description
Fixes: #11455

### For arguments which is annotated with `:path/:directory/:glob`
To fix the issue, we need to have a way to know if a path is originally quoted during runtime.  So the information needed to be added at several levels:
* parse time (from user input to expression)
We need to add quoted information into `Expr::Filepath`, `Expr::Directory`, `Expr::GlobPattern`
* eval time
When convert from `Expr::Filepath`, `Expr::Directory`, `Expr::GlobPattern` to `Value::String` during runtime, we won't auto expanded the path if it's quoted

### For `ls`
It's really special, because it accepts a `String` as a pattern, and it generates `glob` expression inside the command itself.

So the idea behind the change is introducing a special SyntaxShape to ls: `SyntaxShape::LsGlobPattern`.  So we can track if the pattern is originally quoted easier, and we don't auto expand the path either.

Then when constructing a glob pattern inside ls, we check if input pattern is quoted, if so: we escape the input pattern, so we can run `ls a[123]b`, because it's already escaped.
Finally, to accomplish the checking process, we also need to introduce a new value type called `Value::QuotedString` to differ from `Value::String`, it's used to generate an enum called `NuPath`, which is finally used in `ls` function.  `ls` learned from `NuPath` to know if user input is quoted.

# User-Facing Changes
Actually it contains several changes
#### Before
```nushell
> def foo [p: path] { echo $p }; print (foo "~/a"); print (foo '~/a')
/home/windsoilder/a
/home/windsoilder/a
> def foo [p: directory] { echo $p }; print (foo "~/a"); print (foo '~/a')
/home/windsoilder/a
/home/windsoilder/a
> def foo [p: glob] { echo $p }; print (foo "~/a"); print (foo '~/a')
/home/windsoilder/a
/home/windsoilder/a
```
#### After
```nushell
> def foo [p: path] { echo $p }; print (foo "~/a"); print (foo '~/a')
~/a
~/a
> def foo [p: directory] { echo $p }; print (foo "~/a"); print (foo '~/a')
~/a
~/a
> def foo [p: glob] { echo $p }; print (foo "~/a"); print (foo '~/a')
~/a
~/a
```
### For ls command
`touch '[uwu]'`
#### Before
```
❯ ls -D "[uwu]"
Error:   × No matches found for [uwu]
   ╭─[entry #6:1:1]
 1 │ ls -D "[uwu]"
   ·       ───┬───
   ·          ╰── Pattern, file or folder not found
   ╰────
  help: no matches found
```

#### After
```
❯ ls -D "[uwu]"
╭───┬───────┬──────┬──────┬──────────╮
│ # │ name  │ type │ size │ modified │
├───┼───────┼──────┼──────┼──────────┤
│ 0 │ [uwu] │ file │  0 B │ now      │
╰───┴───────┴──────┴──────┴──────────╯
```

# Tests + Formatting
Done

# After Submitting
NaN

### CODE REVIEW

**Comment by fdncred** [comment]
I think this is a creative solution @WindSoilder. Nice work. I have a couple questions.

1. Does this work with any quotes (single, double, backtick)?
2. Does this (or should this) revert bob's [PR](https://github.com/nushell/nushell/pull/10694) that checks if the glob exists file first, then if not, checks for a file?
3. Related to 2, I'm curious how this works for `cp`, `mv, `umv`, `rm`, `touch` etc. (commands that may make use of globbing)

**Comment by WindSoilder** [comment]
1. Does this work with any quotes (single, double, backtick)?
Nope: it doesn't work with backtick, because a backtick wrapped string is a bare word.
2. Does this (or should this) revert bob's https://github.com/nushell/nushell/pull/10694 that checks if the glob exists file first, then if not, checks for a file?
I've tested examples under `10694`, and found it doesn't revert bob's pr.
3. Related to 2, I'm curious how this works for cp, mv, umv, rm, touch etc. (commands that may make use of globbing)
For cp, mv, rmv, rm, touch, the behavior is still the same, it checks if the file exists firstly, if not exists, apply glob operation.  This logic is handled by `arg_glob` function.

The changes on `SyntaxShape::GlobPattern` only affects custom command which annotated with `:glob`.

**Comment by WindSoilder** [comment]
I'm thinking that do we need to apply the same logic on *cp, mv, rm*.  Which is: if quoted, get rid of globbing.  If not quoted, apply the glob operation.  

If we do so, nushell will get better consistency on globbing rules across different fs commands.  But it belongs to another problem.

**Comment by WindSoilder** [comment]
Yeah, that's a good point.  Maybe I can try to handle it in another pr? 
Revert the logic and apply the logic in this pr to mv, cp, rv will require a larger change, I need to think how to achieve the bahavior

**Comment by fdncred** [comment]
ya, i'd be fine with a separate pr for that.

**Comment by WindSoilder** [comment]
I'll merge it if there is no objections, any thought?

**Comment by fdncred** [comment]
no objections from me. i think it's worth a try.

**Comment by WindSoilder** [comment]
OK, thanks for your input, you guide me to a good direction to improve some other commands

**Comment by crides** [comment]
After this PR, how are we supposed to deal with globs containing spaces? in POSIX shells one can just escape the space directly, but that's not the case in nushell

**Comment by fdncred** [comment]
@crides do backticks work? they seem to work for me
```
ls `/Library/Application Support/*`
```

**Comment by crides** [comment]
oh okay, backticks are not included. Thanks

**Pull request merged**
