### PR TITLE
FEATURE: add the first draft of the standard library

### PR DESCRIPTION
**Pull request by amtoine**
hello there :wave: :yum: 

as discussed over on the discord server, in `#standard-library`, there is this new project of putting together a bunch of "_standard_" scripts and functions and propose a `nushell` "_standard library_".
this PR is the first one in that direction :tada: 

> **Note**
> ~~this PR is still a draft to have some feedback :relieved:~~ 
> this PR is now **READY FOR REVIEW** :tada: 

# Description
this PR implements the following few commands:
- the `assert` familly with a private helper `_assert`
- a version of the `match` statement

i've also added some examples in the docstrings of the functions :+1: 

# User-Facing Changes
the standard library can now be used with
```bash
use crates/nu-utils/src/sample_config/std.nu
```
from the root of the `nushell` source

# Tests + Formatting
i've written a first draft of a [`tests.nu`](https://github.com/amtoine/nushell/blob/feature/first-draft-of-the-standard-library/crates/nu-utils/src/sample_config/tests.nu) module which
- tests the `assert` familly of function in `test_assert`
- tests the rest of the standard library in `tests`

the tests are run with
```bash
nu crates/nu-utils/src/sample_config/tests.nu
```
through the `main` function and should give no error :+1: 

> **Note**
> if you change one of the test line, there should be an error popping when running the tests :wink: 

# After Submitting
> **Warning**
> to be coming

### CODE REVIEW

**Comment by amtoine** [comment]
TODO:
- make sure the tests have a correct form
- make sure the tests cover the few first functions
- make sure the calling method, both for `use`ing the library and `run`ning the tests, are easy to use
- add documentation to the `std.nu` functions
- add better error messages (maybe for later?)
- probably some other things here :yum:

**Comment by fdncred** [comment]
Seems like a good start. It doesn't have to be perfect the first time. We'll continue to iterate.

**Comment by jmoore34** [comment]
Perhaps `assert_eq` and such could be subcommands, eg `assert eq` with a space, for better discoverability

**Comment by amtoine** [comment]
@fdncred @jmoore34 

> Perhaps `assert_eq` and such could be subcommands, eg `assert eq` with a space, for better discoverability
>
no problem, i've changed that in 839d7bf82 :+1: 


> Seems like a good start. It doesn't have to be perfect the first time. We'll continue to iterate.
>
gotcha :ok_hand: 
then we can mark that as "_ready for review_" and merge it if you want.
the TODO can be moved to some other place :yum:

**Comment by amtoine** [comment]
mm how can i fix https://github.com/nushell/nushell/actions/runs/4260734684/jobs/7414370252? :confused:

**Comment by sholderbach** [comment]
> mm how can i fix [nushell/nushell/actions/runs/4260734684/jobs/7414370252](https://github.com/nushell/nushell/actions/runs/4260734684/jobs/7414370252)? 😕

We removed the Windows coverage run for now as our setup was currently incompatible with the limited disk allocation on those workers. Should resolve by merging main.

**Comment by amtoine** [comment]
> We removed the Windows coverage run for now as our setup was currently incompatible with the limited disk allocation on those workers. Should resolve by merging main.
>
got it :ok_hand: 
i'll merge this branch into `main` and we'll see if that fixes the CI!

**Comment by amtoine** [comment]
there it is, merged on very latest `main` :crossed_fingers:

**Comment by amtoine** [comment]
@sholderbach
cool it worked :star_struck:

**Comment by sholderbach** [comment]
What is the general status? I would favour landing as soon as possible so potential bikeshedding can happen in their respective topical PRs.

**Comment by amtoine** [comment]
> What is the general status? I would favour landing as soon as possible so potential bikeshedding can happen in their respective topical PRs.
>
as been already said, that might be a good start, at least i've done what i had in mind for this very first PR :+1:

**Comment by fdncred** [comment]
Let's land this and keep building.

**Pull request merged**
