### PR TITLE
Revert "Add `format` meta command (#11334)"

### PR DESCRIPTION
**Pull request by fdncred**
This reverts commit fd77114d822d24658feea302eb2129a87aa97040.

@KAAtheWiseGit We can't just allow this `format` to stomp on extra `format`. Any other ideas how to accomplish this? What could an better name for the existing `format` command in extra be?

# Description

# User-Facing Changes

# Tests + Formatting

# After Submitting

### CODE REVIEW

**Comment by KAAtheWiseGit** [comment]
@fdncred, hmm, `format pattern`?

**Comment by fdncred** [comment]
sounds good to me. if you change that, we can just close this pr.

**Comment by KAAtheWiseGit** [comment]
Do I just file a separate PR for that?

**Comment by KAAtheWiseGit** [comment]
Made #11355

**Pull request closed without merging**
