### PR TITLE
Make `$in` work in `catch` closures

### PR DESCRIPTION
**Pull request by webbedspace**
# Description

This now works:
```
try { 'x' | math abs } catch { $in }
```

# User-Facing Changes

See above.

# Tests + Formatting

Don't forget to add tests that cover your changes.

Make sure you've run and fixed any issues with these commands:

- `cargo fmt --all -- --check` to check standard code formatting (`cargo fmt --all` applies these changes)
- `cargo clippy --workspace -- -D warnings -D clippy::unwrap_used -A clippy::needless_collect` to check that you're using the standard code style
- `cargo test --workspace` to check that all tests pass

# After Submitting

If your PR had any user-facing changes, update [the documentation](https://github.com/nushell/nushell.github.io) after the PR is merged, if necessary. This will help us keep the docs up to date.

### CODE REVIEW

**Comment by sholderbach** [comment]
I think it is a bit unclear what `$in` means in this context. The captured error, the pipeline that was piped into the whole construct which is now consumed, some pipeline stage of the try block?

**Comment by fdncred** [comment]
I'm leaning against making `$in` more magical than it already is. I'd really like to remove `$in` altogether because it's too confusing. There are always questions about it.

**Comment by webbedspace** [comment]
> I'm leaning against making `$in` more magical than it already is. I'd really like to remove `$in` altogether because it's too confusing. There are always questions about it.

The thing is that, from my usage half the language requires `$in` in order to be usable. `$in` implicitly solves so many problems: how concat operators are supposed to work with the pipeline without creating command versions, how to use pipeline input in arg position without needing some ugly `xargs`-type shim (or having to add special "pipe-or-arg" invocation cases for things like `save`), golfing down `where` and `each` closures to just `{ $in > 3 }` or `{ ls $in }`, and some other stuff I've probably overlooked.

Plus, this isn't particularly "magical". Most Nushell closures have things piped into them, and the `$in` rule I've just given work uniformly across most of them. I'd honestly consider `$it` to be much more "magical", in the sense that it can only be used in one or two very specific syntactic situations.

**Comment by rgwood** [comment]
> As I understand it, `$in` used in the first line of a closure that takes 1 positional argument always means "the value that would be in the first positional argument". Compare `each`: `[1 2 3 4] | each { $in * 2 }`

Oh, that's interesting. I think of `$in` as "a value that is being piped _in_ to the current block/closure" but I think your definition is easier to reason about.

I had the same reaction as @sholderbach to this PR, it wasn't clear to me what `$in` meant in this context. But after reading the explanation I think I like the change. 

Would like to hear from a few more people since this touches on the definition of `$in`, I've mentioned this issue on Discord to see if we can get some more opinions.

**Comment by kubouch** [comment]
I also see `$in` as the value being piped into the closure, rather than positional argument.

I mentally translate `[1 2 3 4] | each { $in * 2 }` to `1 | { $in * 2 }`, `2 | { $in * 2 }`, etc. and that's how `$in` actually works in Nushell today:
```
> let b = { $in + 7 }
> 7 | do $b
14
```

So, I would interpret the `catch` closure of
```
'spam' | try { 'x' | math abs } catch { $in }
```
as
```
'spam' | { $in }
```

Basically, for me, `$in` == input from the pipeline. But sometimes it's a bit weird because, for example, `each` seems to supply the iterated value to both the pipeline input and the positional argument to the closure.

**Comment by webbedspace** [comment]
I thought of some more things that only work because of $in:
* `print ($in | describe)` or any other thing where input must be given to the interior of ( )
* `def foo [a:any] { let $a = $in`
* `{ key: $in }` and `[$in]` where input is not a structure

One other thing to consider is that $in has different semantics to a positional after the first link in a pipeline in a closure: `{|e| $e.name | $in + $e.extension }` sees $in refer to `$e.name` while `$e` still refers to the original input.

> But sometimes it's a bit weird because, for example, `each` seems to supply the iterated value to both the pipeline input and the positional argument to the closure.

Not only `each`, but also: color_config closures, `update` and `insert` closures, `do` closures (try giving them a positional), `collect` closures, and even `reduce`.

**Comment by fdncred** [comment]
any more thoughts on this? i'm not objecting to landing this, i just don't like $in in general :)

**Comment by kubouch** [comment]
I don't object landing it. We might want to revisit `$in` in general because in many places we're supplying both implicit pipeline input (and therefore `$in`) and the first positional argument which I think is weird. We should either formalize it and make it a rule or decide where we pass a pipeline input and where a positional.

**Comment by fdncred** [comment]
ok, let's move forward with this and keep iterating somewhere else on `$in`. Thanks all.

**Pull request merged**
