### PR TITLE
Var args in alias

### PR DESCRIPTION
**Pull request by LhKipp**
This is work in progress.

This PR adds the ability to have var args in alias. (#1716) See `alias.md` for examples and restrictions on var arg usage. Let me know what you think about them :)
On the way of doing so, the type deduction has been partially reworked and extended for additional cases.

Therefore this fixes: #2416, #2346 (if not fixed already), #1835, #1632 (if not fixed already).

This is still WIP, because there are still dozens of TODO`s in the deduction module.

Anyone wanting to help is invited :)

### CODE REVIEW

**Comment by jonathandturner** [comment]
@LhKipp - this would be a good one to brainstorm about. The idea of using type inference to figure out how to handle it as it spreads is cool, not sure I would have thought of that until after trying a few different approaches.

Something I was wondering: would it make sense to add a kind of "spread" operations like other languages that use rest?  So we can tell a difference between treating all the parameters as a group or handling them separately.

Something else that I think people will want to do is pass flags. I missed if you supported that, but something else we could try to think through.

Excited to see this moving forward. It's been a *big* request.

**Comment by LhKipp** [comment]
> Something else that I think people will want to do is pass flags. I missed if you supported that, but something else we could try to think through.
This PR does not support passing of flags to keep it small.

My vision for passing of flags would be as followed:
The flags of the alias is a combination of all flags from every command used in the pipeline - excluding flags already used. When two (or more) commands in the pipeline have same flags, the user has to prefix the flags with the command name:
For example:
```shell
alias ll [paths...] {ls -a $paths} --> ll gets all flags
alias ll [paths...] {ls -a $paths | where type == Dir} --> ll gets all flags from ls and where
alias ls_rm [paths...] {ls $paths; rm $paths} --> ll gets all flags from ls and rm. (At least) conflict on -R
```
An invocation of ls_rm could be:
`ls_rm --rm::R $HOME`

When the same command (say where) is used more than once, the user has to prefix them with: 
`--where1::flag --where2::flag`
If the number is omitted, the flag gets passed to all cmds (here where)

Of course: The user is free to prefix flags even if it is not necessary.

One could pass the flags to the commands within the block by modifying the InternalCommand.args.named field, I think.  

From my point of view, passing of flags has nothing to do with var args or how positional arguments are handled. But I am always happy to hear different opinions and ideas :)


> @LhKipp - this would be a good one to brainstorm about. The idea of using type inference to figure out how to handle it as it spreads is cool, not sure I would have thought of that until after trying a few different approaches.
> 
Thanks. But type inference doesn't solve the problem if there are optional arguments.
Currently no signature has optional arguments. Therefore the text below shows, what would be needed as soon as commands (external ones ?) will come up. However the alias command should be written with that in mind, to lower the change of a rewrite later on.

 Let me elaborate. 
## Which problem?
Alias should be type safe. Meaning: During (or after?) parsing stage, it should be possible to judge whether the positional arguments fit the requirements of the alias. (Technical problem)
Optionally there should be a way to see, what one can pass to an alias. (UI / UX problem)

Currently the Signature of an Command solves both problems.
That doesn't work  (nicely) for Aliases. Let me give examples.

Lets take the example of git log: 
```shell
 git log signature:      git log [<options>] [<revision range>] [[--] <path>...]
alias gl [arg, args...] {git log $arg $args}
```
What is the correct inference for $arg1 here? Its `SyntaxShape::String` with the alternative of `SyntaxShape::FilePath`. What is the correct signature of gl? It is: `gl [<revision range>] [<path>...]` BUT pass at least 1 argument. (argument 'arg' can't be empty by design. Or should declared variables be allowed to be empty? How could one implement that?).
Note that type inference differs from the actual inference. And that you can't pass the requirement "At least 1 argument" within the current structure of the signature Struct / SyntaxShape enum.

Let me give a second (more arbitrary) example:
```shell
cmd signature: cmd [<FilePath>] [<FileSize>] [<Block>] [<Int>...]
alias c [a1, a2, a3] {cmd $a1 $a2 $a3}
```
Now there are even dependencies between the variables! If a1 is int, all of the others have to be int too.
Please also note that the above example doesn't include a var arg. The problem already arises for normal arguments.

## The solution for correct shape deduction
Please note, that the "signature language" is of type 3. Or in other words: The problem of detecting whether a stream of syntactical shapes / expressions given by the user is correct for a given signature is the same as asking: Does the regex (here signature) match the input (here input of shapes).

For normal commands, you can build the finite state machine from the signature. Aliases on the other hand need more fine grained control.

Therefore the signature should be used for UI / UX. The finite state machine should be used to verify user input.

Currently the parser does parsing and checking the user with the command signature at the same time.
(And while doing that it can't handle optional fields anyways.
Proof: 
https://github.com/LhKipp/nushell/tree/cmd_with_optional_pos
cargo build
cargo test --package nu-cli --test main works -- commands::alias (I don't know how I can make a new test package; Therefore I have put the test to the alias tests)
)


I personally think that the way forward for aliases (and nushell) would be to introduce a function: shape_deduction, of which one subfunction is variable type deduction. Whenever there is a variable used in place of a optional positional argument, type inference is not enough. The function shape_deduction has to copy (and modify?) parts of the signature in which the variable is used.
The parser on the other hand has to only parse the input. The parsed input will then be checked in a second step against the finite state machine (with coercion rules on)

With such a huge change a couple of questions arise:
How will nice errors still be provided. THAT IS THE MAJOR QUESTION IN THE ROOM.
Are there any regex / state machine libraries one could use?
Could the parser code be auto generated by handing a grammar to a parser generator?
Can the signature rules be relaxed? Do we want to give the whole power of L3 / regex to the user? e.G. would a signature like: 
```shell
cmd [<int> {3,4}] <path> <filePath>+ <int>*
cmd with optional 3 to 4 ints, followed by one path, followed by one or more file paths, followed by 0 or more ints
```
be legal? Could the user put more than one var arg to a function?



> Something I was wondering: would it make sense to add a kind of "spread" operations like other languages that use rest? So we can tell a difference between treating all the parameters as a group or handling them separately.
> 
I am not sure what you mean by this. Do you mean: We should introduce an operator to cast a variable of type Row (or other vector like types) to an var arg? Yeah sure. Casting is better than automatic coercion, from my point of view.

**Comment by jonathandturner** [comment]
@LhKipp - This is a well thought-through, and super thorough response. It's much appreciated. I feel like I need a little bit of time to digest the implications of the design choices you bring up.

One of the bits of feedback I'm hearing from other folks getting more ambitious with their aliases is that the error reporting is already a problem. If we get more complex there, we're going to have to redouble our effort to make sure what the report back to the user is actionable error feedback rather than a more complex set of things they need to understand.

The part that you call out I really need to chew on is the idea how what kind of deduction, and how deep to go. Like you mention, if you allow the same flag in multiple places, you need to be able to disambiguate.

We may need to start collecting use cases here to see how the deduction might work in practice, to see if it's feasible and if we could give good error messages from it.

In tandem, I've also been wondering about alternate approaches. Something like C++'s template expansion, so that you could pass anything in, and we just expand to be the full pipeline as the first step. Once expanded, it's then we do the parse and typecheck. This has the advantage of being able to trivially support things like flags, but the same disadvantage you point out, namely, how do we give good error messages here. As a user of an alias, you'd be exposed to the internal workings, which isn't ideal.

**Comment by LhKipp** [comment]
> In tandem, I've also been wondering about alternate approaches. Something like C++'s template expansion, so that you could pass anything in, and we just expand to be the full pipeline as the first step. Once expanded, it's then we do the parse and typecheck. This has the advantage of being able to trivially support things like flags, but the same disadvantage you point out, namely, how do we give good error messages here. As a user of an alias, you'd be exposed to the internal workings, which isn't ideal.

Do you mean templates in signatures?

I think a better aproach would be to just ask the command what type he will return, given the input.
Let me elaborate:

If the templatized signatures would be: 
```shell
ls | where size > 1kb | get date | math sum

ls -> Input: FilePath, Output: Table[name: FilePath,type: String, size: Unit, modified: Date]
where -> Input: <U> Block, Output: <U> (Good usage of templates)
get -> Input: Table[U...] ColumnName, Output: U ( !!! Problem arises here !!! )
math -> Input: <U>, Output: Number
```
By having the i/o templatized, e.G. the completion engine could have infered that it should have promoted the words: name, type, size and modified, when the user asked for completion on get, as the where command gives out what he gets in.
However as the table contains columns of different types, you cant be sure which type will be returned by get - by just doing static analysis. And so the static typechecking will fail. No completion or deduction based on templates will be possible after here.

The pipeline has to run, to see which types will be at every stage.

However: One could implement for every command a function lets say:
```rust
fn result_type(stdin: Expression, positionals: Positionals, flags: Flags) -> Expression
```
The above pipeline would have implementations as follows:
```shell
ls: return Table[name: FilePath,type: String, size: Unit, modified: Date]
where: return stdin
get: return stdin[positionals[0]] (Return table column with name positionals[0])
math: assert stdin == Vector of Number; return Number
```

Now one can infer the result type of get before running the pipeline.

I think adding such a function to the WholeStreamCommand interface fits better into a dynamic environment like the shell is, than templates.

**Comment by LhKipp** [comment]
Status update:
- Var args:
The current implementation only allows them as positional parameters. I think that makes the most sence.
There is type deduction for var args. 
- Deduction:
I resolved a lot of the todos. It works better than the old code (at least for me :}). There are some situations where the code is not able to infer, for example:
    - Deducing types between variables and $it: e.G. `$var + $it`
        See above discussion why this is currently not possible for a lot of use cases.
    - Deducing types between variables: e.G. `math eval $var1 + $var2; sleep $var1`.
        Currently these dependencies are safed while iterating over all expressions. But the dependencies are not resolved at the end. One has to implement the method: `solve_dependencies`.
    - Deducing types between variables and the result type of a binary expression: e.G. $var + 1kb / $var2.
        Same as for previous bullet point.
    - Some times a variable can be of different shapes (See above discussion for example with optional positional arguments), then the first of all alternatives is picked at the moment.
    - There is no correct handling of optional positional arguments. (See above discussion for problems with them)

I added tests. Some are commented out. These are failing for various reasons (parser giving strange ast, evaluator evaluating in expr possibly wrong...). But I have made sure, that the failures are not related to the type deduction. 

Please note: On the way to implement better type deduction it was necessary to:
- add itertools as a dependency
- implement Variables and Booleans as standalone Expressions (Booleans were parsed as variables, Variables were parsed as column paths)

**Comment by LhKipp** [comment]
Status update:
- Var args:
The current implementation only allows them as positional parameters. I think that makes the most sence.
There is type deduction for var args. 
- Deduction:
I resolved a lot of the todos. It works better than the old code (at least for me :}). There are some situations where the code is not able to infer, for example:
    - Deducing types between variables and $it: e.G. `$var + $it`
        See above discussion why this is currently not possible for a lot of use cases.
    - Deducing types between variables: e.G. `math eval $var1 + $var2; sleep $var1`.
        Currently these dependencies are safed while iterating over all expressions. But the dependencies are not resolved at the end. One has to implement the method: `solve_dependencies`.
    - Deducing types between variables and the result type of a binary expression: e.G. $var + 1kb / $var2.
        Same as for previous bullet point.
    - Some times a variable can be of different shapes (See above discussion for example with optional positional arguments), then the first of all alternatives is picked at the moment.
    - There is no correct handling of optional positional arguments. (See above discussion for problems with them)

I added tests. Some are commented out. These are failing for various reasons (parser giving strange ast, evaluator evaluating in expr possibly wrong...). But I have made sure, that the failures are not related to the type deduction. 

Please note: On the way to implement better type deduction it was necessary to:
- add itertools as a dependency
- implement Variables and Booleans as standalone Expressions (Booleans were parsed as variables, Variables were parsed as column paths)

**Comment by LhKipp** [comment]
> Something else that I think people will want to do is pass flags. I missed if you supported that, but something else we could try to think through.

I implemented passing of flags for the trivial case (The alias abbreviates exactly 1 command). I have opened another PR for that. This one is already more than big enough.

**Comment by jonathandturner** [comment]
After thinking through this, and reading through the kinds of changes you're doing to get to the point where you can support all the use cases, here's what I'm thinking:

We *definitely* want to extend aliases to be able to handle multiple arguments and even flags going forward. Tackling that is no small task, like you're showing.

A few ways forward from here:

* There's a lot of design work going on here. I read through your deduction code and wasn't able to keep it all in my head at one time. An easier way to understand the full algorithm and its implications would be to write up an RFC. I think you've largely done this above in your comment, so you've got a nice headstart there. The RFC allows more folks to jump in and understand what the feature will look like and feel like, and how the logic will work under the hood to make it all happen.

Here's an example RFC I'm working on: https://github.com/nushell/rfcs/pull/3

Once the RFC is up and people can comment on it, it will help put this PR (and also the other PR) into a well-understood design framing, making them easier to review.

* Since you've been able to touch so much of the system and understand how various parts work, it may make sense to break this PR up into incremental updates to the system. For example, you have different ways that types can coerce to each other during inference. This is could be put into a separate PR because we could use it for the normal type inference that's an optional part of `alias`. It also helps code reviewers because we can focus on the one topic of that PR, which in this case would be "are these a good set of type coercions during type inference?".

Either or both of the above will help move this PR into more byte-sized portions that are easier to review, and will give people more ability to discuss the design as it lands.

**Comment by LhKipp** [comment]
https://github.com/nushell/rfcs/pull/4

**Comment by LhKipp** [comment]
With the RFC getting good feedback (and me having a little more free time again :) ), I will now start to pick this way to huge PR into pieces. 
 #2679 Is the start.

**Pull request closed without merging**
