### PR TITLE
Restrict closure expression to be something like `{|| ...}`

### PR DESCRIPTION
**Pull request by WindSoilder**
# Description

As title, closes: #7921 closes: #8273

# User-Facing Changes

when define a closure without pipe, nushell will raise error for now:
```
❯ let x = {ss ss}
Error: nu::parser::closure_missing_pipe

  × Missing || inside closure
   ╭─[entry #2:1:1]
 1 │ let x = {ss ss}
   ·         ───┬───
   ·            ╰── Parsing as a closure, but || is missing
   ╰────
  help: Try add || to the beginning of closure
```

`any`, `each`, `all`, `where` command accepts closure, it forces user input closure like `{||`, or parse error will returned.
```
❯ {major:2, minor:1, patch:4} | values | each { into string }
Error: nu::parser::closure_missing_pipe

  × Missing || inside closure
   ╭─[entry #4:1:1]
 1 │ {major:2, minor:1, patch:4} | values | each { into string }
   ·                                             ───────┬───────
   ·                                                    ╰── Parsing as a closure, but || is missing
   ╰────
  help: Try add || to the beginning of closure
```

`with-env`, `do`, `def`, `try` are special, they still remain the same, although it says that it accepts a closure, but they don't need to be written like `{||`, it's more likely a block but can capture variable outside of scope:
```
❯ def test [input] { echo [0 1 2] | do { do { echo $input } } }; test aaa
aaa
```

Just realize that It's a big breaking change, we need to update config and scripts...

# Tests + Formatting

Don't forget to add tests that cover your changes.

Make sure you've run and fixed any issues with these commands:

- `cargo fmt --all -- --check` to check standard code formatting (`cargo fmt --all` applies these changes)
- `cargo clippy --workspace -- -D warnings -D clippy::unwrap_used -A clippy::needless_collect` to check that you're using the standard code style
- `cargo test --workspace` to check that all tests pass

# After Submitting

If your PR had any user-facing changes, update [the documentation](https://github.com/nushell/nushell.github.io) after the PR is merged, if necessary. This will help us keep the docs up to date.

### CODE REVIEW

**Comment by kubouch** [comment]
+1

Seems like we need to patch https://github.com/pypa/virtualenv/blob/main/src/virtualenv/activation/nushell/activate.nu again :-D

**Comment by jntrnr** [comment]
I've been thinking about this... for something like `each`, sometimes it's nice to not to have to put the `||`. For example, in this example:

`[1, 2, 3, 4] | each { $in + 100 }`

imho, I think this is a little nicer to write than: `[1, 2, 3, 4] | each {|x| $x + 100 }` or `[1, 2, 3, 4] | each {|| $in + 100 }`. Maybe it's harder to read, though?

**Comment by WindSoilder** [comment]
I agree that `[1, 2, 3, 4] | each { $in + 100 }` is nicer than `[1, 2, 3, 4] | each {|| $in + 100 }`.

But not really sure about `{[1, 2, 3, 4] | each {|x| $x + 100 }`, because here I know each is `$x`, it's a bit verbose, but clearly to me personally.

**Comment by fdncred** [comment]
I also think it clears up a problem with knowing what is a closure and what is a block. With this change, that is always answered correctly.

**Comment by kubouch** [comment]
I agree. While it is clearer to have `each { $in + 100 }`, it is not obvious that it is different than `for x in [1, 2, 3, 4] { $x + 100 }`. For example, closure scopes environment and does not allow mutation, unlike block, but this is not conveyed in the code in any way.

Also, it helps with https://github.com/nushell/nushell/issues/7921 which is one of the nastier footguns we have, it's super hard to debug. Although, that could also be solved by trying to sniff ahead for `:` inside a record.

**Comment by fdncred** [comment]
@WindSoilder if you can fix this merge conflicts i'm hoping we can merge this.

**Comment by fdncred** [comment]
let give this a try and see how people respond.

**Comment by hustcer** [comment]
Can we have a syntax sugar for closures that don't have any param, instead of `[1, 2, 3, 4] | each {|| $in + 100 }`, can we use `[1, 2, 3, 4] | each {@ $in + 100 }` or something the like ? It's more elegant than `{||` I think, and `|` was typically used as a pipe to connect two commands

**Comment by amtoine** [comment]
> Can we have a syntax sugar for closures that don't have any param, instead of `[1, 2, 3, 4] | each {|| $in + 100 }`, can we use `[1, 2, 3, 4] | each {@ $in + 100 }` or something the like ? It's more elegant than `{||` I think, and `|` was typically used as a pipe to connect two commands
>
i also imagined `{_| ... }` or `{|_| ... }` :yum: 

what would the syntax be with `@` when there is a param to a closure? still `{|x| ... }`?

**Comment by hustcer** [comment]
> 
> what would the syntax be with `@` when there is a param to a closure? still `{|x| ... }`?

Yeap. `{@` just a syntax sugar for `{||`, if the closure has any param, the param(s) will be put in `||` just as before

**Pull request merged**
