### PR TITLE
Commands to engine

### PR DESCRIPTION
**Pull request by elferherrera**
Batch of commands changed to engine p

- move
- parse
- roll/column up

List of remaining commands to port: #3390

### CODE REVIEW

**Comment by elferherrera** [comment]
@jonathandturner I was trying to print the error produced by Regex in this [line](https://github.com/nushell/nushell/blob/e2973d2176bec6a206c37892458ef3b09146d34b/crates/nu-command/src/commands/parse/command.rs#L58) while parsing the regex expression, but I wasn't passing the nushell tests. 

I was doing something like this to print more information about the parsing
```rust 
let regex_pattern = if let Tagged { item: true, tag } = regex {  
      Regex::new(&amp;pattern.item).map_err(|e| ShellError::labeled_error("Invalid regex", format!("{}", e), tag.span))?   
} else {
```

Is there a better way to format errors produced by other processes?

**Comment by jonathandturner** [comment]
@elferherrera I haven't used the regex crate much. It's possible it has more regex information you can share in a shell error

**Comment by jonathandturner** [comment]
@elferherrera - do you want to work on the regex stuff before I review this PR?

**Comment by elferherrera** [comment]
@jonathandturner let me see if I can format a bit better the error message for the regex parser

**Comment by elferherrera** [comment]
@jonathandturner I added the detail from the regex parsing error to the output of nushell. It looks like this
image

This gives a bit more information about the missing bits when parsing with regex. What do you think?

**Comment by jonathandturner** [comment]
@elferherrera - that's an improvement.

Looking at the error, I wonder if you could improve it further. There's an underline of where the group begins, we could make that what's underlined in the error message instead of the whole regex.

```
Error: Invalid regex - parse error
...
"(?P<a>\w+ (?P<b>\w+" -r
           ^ unclosed group
```

**Comment by elferherrera** [comment]
@jonathandturner I was looking for a way to do that, but I couldnt figure it out. The string Im printing comes from the error generated by Regex. How can I create a nushell error marking the character where the error is?

**Comment by jonathandturner** [comment]
@elferherrera you might have to parse the error that comes back from Regex if it's only text. It's possible there's more information in the error. I don't know the regex API to know if there's maybe an additional method you can call on the error

**Comment by elferherrera** [comment]
@jonathandturner Sorry. I thought there were some utilities in nushell that could parse those error messages. I pushed a better version of parse with regex
image

I hope this looks better

**Comment by andrasio** [comment]
@elferherrera I think it's great so far. Do you it's possible to use `ShellError::labeled_error_with_secondary` ? if not, I'm more than happy to merge this.

**Comment by elferherrera** [comment]
@andrasio sure, let me try. I haven't used that one

**Comment by elferherrera** [comment]
@andrasio with the secondary message looks like this
image

I like it better

**Comment by andrasio** [comment]
@elferherrera Yeah, the primary span (red) is sort of invading the secondary span (blue) though. @jonathandturner Ideas on what could we show as the secondary span and primary one? For an idea of both in practice and said underline colors not touching each other, try `ls | wrap x | get x.9.nam` (given there are more than 9 rows in the output of `ls`)

**Comment by andrasio** [comment]
@elferherrera Also, please have a look at `get` command for ideas on how to create spans too. Few utilities under `nu-source` in meta.rs on `Span` is helpful (like `since`, `span_for_span_list`, etc). Tags too.

**Comment by andrasio** [comment]
@elferherrera Here is another example: try something like `open Cargo.toml | get missing`

**Comment by elferherrera** [comment]
@andrasio thanks for the tips. Following the last example it could look like this

image

**Comment by elferherrera** [comment]
@andrasio I have been looking at the error message that we get from the regex parsing and I don't think we can get extra information from it. The other option could be like this:
image

**Comment by andrasio** [comment]
@elferherrera Let's go ahead with the [one before it](https://github.com/nushell/nushell/pull/3448#issuecomment-846417073) then.

**Comment by elferherrera** [comment]
@andrasio thanks for the hints. I submitted the changes with the suggested layout

**Comment by andrasio** [comment]
@elferherrera Thank you!

**Pull request merged**
