### PR TITLE
Path commands: Put column path args behid flag; Allow `path join` appending without flag

### PR DESCRIPTION
**Pull request by kubouch**
Some refactors to the path subcommands:
* `path join` now appends without the `-a` flag: `"foo/bar/baz" | path join spam.txt`
* as a consequence, the column path arguments for all path subcommands are behind a `-c` flag: `ls | path type -c [name]`

Also updated the examples of each subcommand to include a column path example end remove redundant "echo" keyword from the examples.

Improved an error when table is received without correct structured path columns.

### CODE REVIEW

**Comment by kubouch** [comment]
@andrasio  You might be interested in this.

**Comment by andrasio** [comment]
@kubouch Heh.

Good to see ways to figure out the column path/single value attempts.

it looks great the new change for `path join`.

For working with column paths to change tables coming in "in place" I may have new thoughts too (or not).

**Comment by kubouch** [comment]
@andrasio Do you think it's good enough for a merge? I'm thinking the `-c` flag is just temporary until we have a better design for changing the column paths in-place.

**Comment by andrasio** [comment]
@kubouch Of course! I think it's great.

**Pull request merged**
