### PR TITLE
Add the history import command (again)

### PR DESCRIPTION
**Pull request by qfel**
# Description

This is mainly https://github.com/nushell/nushell/pull/13450 (which got reverted). Additionally:
 - always clear IDs on import, disallow specifying IDs when piping
 - added extra tests
 - create backup of the history

# User-Facing Changes

New command: `history import`

# Tests + Formatting

Added mostly integration tests and a few smaller unit tests.

### CODE REVIEW

**Comment by 132ikl** [comment]
Maybe `--include-ids` should be renamed `--overwrite`, and do a clear before importing? I'm not sure in what case you would want to overwrite only the history entries with IDs that already exist in the history (but maybe there is some case?).

**Comment by qfel** [comment]
Because IDs are a part of history, I wanted to leave an option  to import them too.  Because right now IDs are continuous and start from 0/1, that has the weird effect you're describing - but I could imagine eg. random numbers.

So in terms of long-term, it's not obvious we should be always allocating new IDs. In the short term, `--include-ids` doesn't really make sense for "simple" imports, but may when piping records to `history import`.  You can selectively edit existing history items that way.

So, not really sure if it's leaking implementation details too much, or is a useful escape hatch for the user.

**Comment by NotTheDr01ds** [comment]
> Because IDs are a part of history

I'm not sure I understand this.  In a text-backed history, it's simply a flat-file with no indices. Deleting a history item changes the "index" of every item after it.

Conversely, as discussed in #13579, in a SQLite-backed history, the `id` column has no relation to the `!<index>` and really no value to the end-user if the earlier entries are overwritten.

> You can selectively edit existing history items that way.

I personally think we should leave that to other commands and let `history import` be a non-destructive append or insert.

Also note that appending means that later entries are weighted more heavily in suggestions, which is why I think an prepend might be more appropriate here.  That's not critical, though, but definitely has impact on the user experience (in my testing).

**Comment by qfel** [comment]
> I'm not sure I understand this. In a text-backed history, it's simply a flat-file with no indices. Deleting a history item changes the "index" of every item after it.

I meant in terms of the API exposed by reedline. The history still has a concept of an ID, even with plaintext - it just maps to the entry index (and save is arguably buggy by ignoring the provided ID). Perhaps it would be better if plaintext has no IDs, but reedline does return IDs when reading from plaintext. But yes, that's not really of concern to the user.

> I personally think we should leave that to other commands

Honoring IDs lets you import the same file twice, without creating duplicates. Which is probably a niche thing to care about, and likely not a great experience anyway unless we use UUIDs (which plaintext can't reasonably have; perhaps reedline should allow items with no ID?). Though I could imagine it being useful, especially in the pipe form (if somebody tries to import from some custom format).

Technically it fits (the ID is a part of the history item, regardless of how it's stored), less so practically (the users don't know/care about IDs, and the practical values aren't that useful either in current implementations).

Anyway, right now that's behind the `--include-ids` flag, so I think the main question is should we remove the flag or leave it be?

> Also note that appending means that later entries are weighted more heavily in suggestions, which is why I think an prepend might be more appropriate here.

That's not (reasonably) possible with the current reedline API, since all I have is save which is either append or replace. We could make changes to reedline, but that seems like some nebulous future.

**Comment by fdncred** [comment]
Where are we at on this? Ready to land and try again?

**Comment by 132ikl** [comment]
I'm leaning towards removing the option to avoid any ambiguity with usage. It can always be re-added if we think it would be useful, eg. because of an implementation change. Not a huge deal though, and I would be happy to see this land either way.

**Comment by fdncred** [comment]
When ran without any arguments/flags is it destructive? If so, I wouldn't want to accept it. Append mode should be the default and if you want to overwrite your entire history, you should supply a flag so that it's opt-in.

**Comment by qfel** [comment]
It's not destructive by default: unless `--include-ids`  is specified, we erase IDs from the input (perhaps we should fail on IDs being piped, not sure), which causes reedline to always append.

Perhaps let's flip it a bit: unless you think there is a good use case to allow including IDs (I mentioned potential reasons in https://github.com/nushell/nushell/pull/14083#issuecomment-2415384056, but I'm not sure how good of a reason those are) I'll remove the flag and make piping IDs an error (we have to still accept and erase them when importing from another reedline backend).

**Comment by fdncred** [comment]
> It's not destructive ...

I don't understand this really because the description of the PR says, "this adds --include-ids flag to avoid overwriting existing history when using sqlite" which seems to imply that the only way to avoid overwriting existing history is to use --include-ids. What am I missing?

> Perhaps let's flip it a bit: ...

I'm leaning towards this too. It's super important to never be destructive by default. I like errors on piping.

**Comment by 132ikl** [comment]
> What am I missing?

The "avoid overwriting existing history when using sqlite" bit could be more clearly phrased as "gates overwriting history behind the new `--include-ids` flag". The default behavior of `history import` in this PR is to NOT overwrite, and the `--include-ids` flag has this explanation on `help history import`: "WARNING: Setting this flag can cause existing history items to be overwritten."

> I'll remove the flag and make piping IDs an error

I think this is a great idea! I would also recommend adding a suggestion to the explanation for this error, like "use `reject id` to import history from this data source" or something like that

**Comment by qfel** [comment]
> I don't understand this really because the description of the PR says,

Sorry, poor phrasing. Updated to never allow overwriting IDs and updated the description.

**Comment by fdncred** [comment]
Thanks for continuing to work on this. Let's give this one a try.

**Pull request merged**
