### PR TITLE
consolidate shell integration behind config setting

### PR DESCRIPTION
**Pull request by fdncred**
# Description

This PR consolidates the shell_integration settings that nushell is passing with each prompt. They have to do with prompt marking and a work-around to ssh problems with arrow keys not working.

```rust
const PROMPT_MARKER_BEFORE_PS1: &str = "\x1b]133;A\x1b\\"; // OSC 133;A ST
const PROMPT_MARKER_BEFORE_PS2: &str = "\x1b]133;A;k=s\x1b\\"; // OSC 133;A;k=s ST
const PROMPT_MARKER_BEFORE_CMD: &str = "\x1b]133;C\x1b\\"; // OSC 133;C ST
const RESET_APPLICATION_MODE: &str = "\x1b[?1l"; // reset arrow keys
```

To use these features you need to set the new config flag `shell_integration` to `true` in your config.nu file.

# Tests

Make sure you've run and fixed any issues with these commands:

- [ ] `cargo fmt --all -- --check` to check standard code formatting (`cargo fmt --all` applies these changes)
- [ ] `cargo clippy --all --all-features -- -D warnings -D clippy::unwrap_used -A clippy::needless_collect` to check that you're using the standard code style
- [ ] `cargo build; cargo test --all --all-features` to check that all the tests pass

### CODE REVIEW

**Comment by rgwood** [comment]
Thank you! Unfortunately that does not fix the issue for me (Linux, GNOME Terminal).

Just curious, can you reproduce the issue by `cat`ing this file? [minimal-repro.txt](https://github.com/nushell/nushell/files/8544330/minimal-repro.txt)

**Comment by fdncred** [comment]
Thanks for testing it out. I'm wondering if the code around that block that I quoted ever worked. I need to investigate what a better way to do this is, so I'm converting to a draft.

I can use your minimal-repro.txt file on Mac and reproduce the issue. Thanks for that. I wrote this code on Windows, not sure the repro works on Windows.

**Comment by fdncred** [comment]
when you get a second @rgwood, could you please test again. one thing to note, you have to hit enter after the prompt is drawn the first time for the reset to happen. after that first time, it should happen each time. there may be a better place to put this code but I haven't found it yet.  also, note that this code should also change your window/tab title with the pwd.

**Comment by rgwood** [comment]
No luck, unfortunately; still seeing the same issue. Not seeing the window/tab title change either.

**Comment by rgwood** [comment]
Something's weird here.  I've set shell_integration to true in config.nu but the code in `update_prompt()` thinks it's set to false.

image


image

**Comment by fdncred** [comment]
@rgwood I wonder what is going on. I added a similar statement to mine and you can see that it's working by printing true and changing the tab title.
Screen Shot 2022-04-23 at 8 05 06 AM

wait a second, why are you able to do `$config` - that shouldn't work any longer? that should be `$env.config` unless you've aliases it or something. do you have `let-env config { ... }` in your config.nu or `let config { .. }`?

**Comment by rgwood** [comment]
I still have `$let config`. One sec.

**Comment by rgwood** [comment]
Updating my `config.nu` to use `let-env` solves the issue, awesome. Thanks!

**Comment by fdncred** [comment]
@rgwood does that mean this PR also works for you now? or you're still having problems but your config is fixed now?

**Comment by rgwood** [comment]
The PR works for me now.

**Comment by jntrnr** [comment]
let's do it

**Pull request merged**
