### PR TITLE
Display empty records and lists

### PR DESCRIPTION
**Pull request by NotLebedev**
# Description

Fix some issues related to #7444 
1. Empty lists and records are now displayed as a small notice in a box:
    image
    image
2. Empty records are now correctly displayed if inside of another record list or table:
    image
    image
3. Fixed inconsistent coloring of empty list placeholder inside of lists/tables:
    image
    image

# User-Facing Changes

`table` command now displays empty records and lists like a table with text and correctly displays empty records inside tables and lists.

New behavior of displaying empty lists and records can be disabled using `table.show_empty` config option.

# Tests + Formatting

Don't forget to add tests that cover your changes.

Make sure you've run and fixed any issues with these commands:

- `cargo fmt --all -- --check` to check standard code formatting (`cargo fmt --all` applies these changes)
- `cargo clippy --workspace -- -D warnings -D clippy::unwrap_used -A clippy::needless_collect` to check that you're using the standard code style
- `cargo test --workspace` to check that all tests pass

# After Submitting

If your PR had any user-facing changes, update [the documentation](https://github.com/nushell/nushell.github.io) after the PR is merged, if necessary. This will help us keep the docs up to date.

### CODE REVIEW

**Comment by NotLebedev** [comment]
Spotted an issue. Commands like `mkdir` and `rm` that have a `--verbose` option return empty list even when called without `--verbose`
image
image
Not sure what to do with this

**Comment by rgwood** [comment]
Thank you; this looks like a really good improvement!

For `mkdir` and `rm`... yeah, those commands are a bit of a mess, I don't like how they return info as a `list<string>` instead of printing to stderr.

It would be a breaking change, but maybe we should finally change those to return `nothing` and print to stderr?

**Comment by rgwood** [comment]
I asked on Discord and other people agree that we should change the filesystem commands to return `nothing` and print info to stderr: https://discord.com/channels/601130461678272522/615329862395101194/1072523941865857055

Would you be up for making that change (either as part of this PR or in another PR)? Sorry that this is turning into a bit of a yak shave 😭

**Comment by NotLebedev** [comment]
Yes, I can do this. I will make a separate PR. It will be easier to work for me that way

**Comment by NotLebedev** [comment]
I think a useful addition might be a config option to switch to old behavior of not displaying this box
image
I think adding `config.table.show_empty` option should be useful. This should only control this boxes. This  `[list 0 items] will be displayed always
image
Also, if this option is added, should it be on or off by default?

**Comment by rgwood** [comment]
> Also, if this option is added, should it be on or off by default?

I vote for on by default. I don't think it needs to be configurable, but I'm OK with a config option if you want one.

**Comment by rgwood** [comment]
Cool!

I haven't had time to do a full code review yet, but I'll try to get to it soon. We discussed this PR in the weekly team meeting, and we agreed that we like the change. It's probably going to break a few things, so the plan is to merge it shortly after the next release (which is on Feb 21) - that will give us more time to test it in `main`.

**Review by rgwood — APPROVED** [review]
LGTM. Thank you for the PR!

Looking forward to merging this after the upcoming release.

**Comment by fdncred** [comment]
@NotLebedev would you mind fixing these conflicts so we can merge this pr? Thanks!

**Comment by fdncred** [comment]
I'm wondering if this change is breaking our table tests or just if another merge main is needed since I just landed another table thing?

**Comment by NotLebedev** [comment]
It broke a test. There were missing `{record 0 fields}` in expected table output

**Comment by rgwood** [comment]
Following up on the discussion in https://github.com/nushell/nushell/pull/8014#issuecomment-1440733867

How are we feeling about this one? We're 9 days from the release and it seems like we're still running into related issues. I'm wondering if we should temporarily disable this feature to give us more time.

**Comment by NotLebedev** [comment]
> Following up on the discussion in [#8014 (comment)](https://github.com/nushell/nushell/pull/8014#issuecomment-1440733867)
> 
> How are we feeling about this one? We're 9 days from the release and it seems like we're still running into related issues. I'm wondering if we should temporarily disable this feature to give us more time to polish it.
> 
> It feels like this PR has led to several others like #8292 and I don't think we're in a place where we can confidently explain to users "here's what we changed, and here's why it's better" _yet_.

I agree. This and related changes are a bit raw currently.  https://github.com/nushell/nushell/pull/8292 is sure to cause some more trouble and may bring up some more changes. 

This one can be removed from release entirely or disabled by default for this release via `table.show_empty` config option.

**Comment by NotLebedev** [comment]
> @NotLebedev Do you have time to submit a PR to disable this? If not I'll get around to it later today or tomorrow.

Can do. Are we disabling it by default or what should I do?

**Comment by rgwood** [comment]
I don't know what the best thing to do is (haven't had time to think about this much).

**Comment by hustcer** [comment]
To me, the most important thing currently is to make sure `[1 2 3] | each {|e| print $e }` don't display `empty list`

**Pull request merged**
