### PR TITLE
Path expansion no longer removes trailing slashes

### LINKED ISSUE #12602: `nu_path::expand_ndots` and its tests are broken because `PathBuf` compares with normalization
`PathBuf` implements its `PartialEq` trait by comparing its components:

```rust
impl PartialEq for PathBuf {
    fn eq(&self, other: &PathBuf) -> bool {
        self.components() == other.components()
    }
}
```

Also, the documentation of `PathBuf::components()` mentions that:

> When parsing the path, there is a small amount of normalization:
> * Repeated separators are ignored, so a/b and a//b both have a and b as components.
> * Occurrences of . are normalized away, except if they are at the beginning of the path. For example, a/./b, a/b/, a/b/. and a/b all have a and b as components, but ./a/b starts with an additional CurDir component.
> * A trailing slash is normalized away, /a/b and /a/b/ are equivalent.

This means that `PathBuf` are compared in their normalized form. e.g. `PathBuf::from(".")` compares equal to `PathBuf::from("./.")`. This wrecks havoc on our tests for path normalization, which uses `assert_eq!` for comparision.

For example, this test looks correct, but is completely broken:

```rust
// From crates/nu_path/src/dots.rs, edited for readability
#[test]
fn expand_dots_with_curdir() {
    let path = Path::new("/foo/./bar/./baz");

    let expected = PathBuf::from("/foo/bar/baz");
    let actual = expand_dots(path); // evaluates to `Path::new("/foo/./bar/./baz")` because of a bug

    assert_eq!(expected, actual); // test passes
}
```

By the way, the bug that I mentioned is also related to `PathBuf::components()` normalization. There's this code inside `expand_dots()`:

```rust
// Early-exit if path does not contain '.' or '..'
if !path
    .components()
    .any(|c| std::matches!(c, Component::CurDir | Component::ParentDir))
{
    return path.into();
}
```

But `PathBuf::components()` normalizes `.` away, so `Path::new("/foo/./bar/./baz")` triggers the early-exit incorrectly.

### PR DESCRIPTION
**Pull request by YizhePKU**
This PR changes `nu_path::expand_path_with()` to no longer remove trailing slashes. It also fixes bugs in the current implementation due to ineffective tests (Fixes #12602).

### CODE REVIEW

**Comment by kubouch** [comment]
Thanks for working on all the path stuff, it's great that someone is taking a deep dive into it.

So this PR has two parts:
1. Disable trailing slash auto-removal
2. Fixes the `expand_ndots()` bug

I'm fine with merging 2. right away. I believe this part needs to land for https://github.com/nushell/nushell/pull/12603 to be able to land, right?

The 1. needs a bit of clarification, but otherwise also seems good: It appears that this PR removes the trailing slash removal for the internal `nu-path` API, but `path expand` still removes the trailing slash because it calls `canonicalize()`, right? Maybe a flag to `path expand` to preserve the trailing slash could be useful, but not required for this PR, just an idea.

We're releasing Nushell 0.93.0 on Tuesday, so we paused merging PRs until then, but I think we can land all your PRs for the next version.

**Comment by YizhePKU** [comment]
> It appears that this PR removes the trailing slash removal for the internal nu-path API, but path expand still removes the trailing slash because it calls canonicalize(), right?

It's complicated. By default, `path expand` calls `canonicalize()`, but if `canonicalize()` fails we fall back to `nu_path::expand_path_with()`. Additionally, `path expand` has an option `--no-symlink`, which makes it always call `nu_path::expand_path_with()`. This PR changes the behavior of `path expand` whenever `nu_path::expand_path_with()` is called.

Here's a demonstration:

```
# Assuming "/tmp" exists, but "/foo" doesn't

# Current (buggy) behavior
"/tmp/"        | path expand                # "/tmp"      (striping trailing slash)
"/foo/"        | path expand                # "/foo/"     (NOT striping trailing slash)
"/foo/../foo/" | path expand                # "/foo"      (striping trailing slash)
"/tmp/"        | path expand --no-symlink   # "/tmp/"     (NOT striping trailing slash)
"/tmp/../tmp/" | path expand --no-symlink   # "/tmp"      (striping trailing slash)

# Behavior after this PR
"/tmp/"        | path expand                # "/tmp"      (striping trailing slash)
"/foo/"        | path expand                # "/foo/"     (NOT striping trailing slash)
"/foo/../foo/" | path expand                # "/foo/"     (NOT striping trailing slash)
"/tmp/"        | path expand --no-symlink   # "/tmp/"     (NOT striping trailing slash)
"/tmp/../tmp/" | path expand --no-symlink   # "/tmp/"     (NOT striping trailing slash)
```

We should probably unify the behavior and/or introduce an option that controls this, but this PR is about fixing our internal API.

**Comment by kubouch** [comment]
Ok, that makes sense. We should probably unify it as you said, but this PR can be merged as-is.

**Comment by fdncred** [comment]
Thanks

**Comment by woosaaahh** [comment]
Hi everyone ! 

> ```
> # Behavior after this PR
> "/tmp/"        | path expand                # "/tmp"      (striping trailing slash)
> ```

I might be missing something but I don't understand the result above.
If the goal of this PR is to keep trailing slashes, why does the result has a stripped slash ?

I tried with Nushell `0.92.2` + the `nighlty` from today `2024-05-03`and I have the same result that I don't understand.
On both machines, `~/.config` exists but `~/foo` doesn't.

On Linux : 
```sh
> '~/.config/' | path expand               # Removes the trailing backslash
/home/<my-user-name>/.config

> '~/.config/' | path expand --no-symlink  # Keeps   the trailing backslash
/home/<my-user-name>/.config/

> '~/foo/' | path expand                   # Keeps   the trailing backslash
/home/<my-user-name>/foo/

> '~/foo/' | path expand --no-symlink      # Keeps   the trailing backslash
/home/<my-user-name>/foo/
```

On Windows : 
```sh
> "~/.config/" | path expand               # Removes the trailing backslash
C:\Users\<my-user-name>\.config

> "~/.config/" | path expand --no-symlink  # Keeps   the trailing backslash
C:\Users\<my-user-name>\.config\

> "~/foo/" | path expand                   # Keeps   the trailing backslash
C:\Users\<my-user-name>\foo\

> "~/foo/" | path expand --no-symlink      # Keeps   the trailing backslash
C:\Users\<my-user-name>\foo\
```

**Comment by YizhePKU** [comment]
@woosaaahh The PR was about fixing out internal API. Previously, our internal API will always strip trailing slashes, so we can't keep them with `path expand` even if we want to. Now that this is fixed, we can actually change the behavior of `path expand` now, but it's not part of this PR.

**Comment by woosaaahh** [comment]
@YizhePKU OOooohh ok !
I was misled by the title, my bad !

**Pull request merged**
