### PR TITLE
add `$nu.data-dir` for completions and `$nu.cache-dir` for other uses

### PR DESCRIPTION
**Pull request by fdncred**
# Description

This PR is an attempt to add a standard location for people to put completions in. I saw this topic come up again recently and IIRC we decided to create a standard location. I used the dirs-next crate to dictate where these locations are. I know some people won't like that but at least this gets the ball rolling in a direction that has a standard directory.

This is what the default NU_LIB_DIRS looks like now in the default_env.nu. It should also be like this when starting nushell with `nu -n`
```nushell
$env.NU_LIB_DIRS = [
    ($nu.default-config-dir | path join 'scripts') # add <nushell-config-dir>/scripts
    ($nu.data-dir | path join 'completions') # default home for nushell completions
]
```

I also added these default folders to the `$nu` variable so now there is `$nu.data-path` and `$nu.cache-path`.

## Data Dir Default
image

While I was in there, I also decided to add a cache dir

## Cache Dir Default
image

### This is what the default looks like in Ubuntu.
image

### This is what it looks like with XDG_CACHE_HOME and XDG_DATA_HOME overridden
```nushell
XDG_DATA_HOME=/tmp/data_home XDG_CACHE_HOME=/tmp/cache_home cargo r
```
image

### This is what the defaults look like in Windows (username scrubbed to protect the innocent)
image

How my NU_LIB_DIRS is set in the images above
```nushell
$env.NU_LIB_DIRS = [
    ($nu.default-config-dir | path join 'scripts') # add <nushell-config-dir>/scripts
    '/Users/fdncred/src/nu_scripts'
    ($nu.config-path | path dirname)
    ($nu.data-dir | path join 'completions') # default home for nushell completions
]
```

Let the debate begin.

# User-Facing Changes

# Tests + Formatting

# After Submitting

### CODE REVIEW

**Comment by NotTheDr01ds** [comment]
Just keep in mind that most software that is installed by package managers will need a *system* (not user/home) location in which to install completions.  Fish has a number of directories it searches for completions - See [here](https://fishshell.com/docs/current/completions.html#where-to-put-completions). I'm not sure you need *that* many locations, but at a minimum, I think you'll need a user-level location and a system-level one.

**Comment by IanManske** [comment]
This looks like a good first step. Some notes to start:
- Similar to what we do for the config path, we should probably use the XDG env vars if they exist before using the system-specific paths for the data and cache paths.
- +1 for the user/system separation. Note sure how useful this is / how this translates to Windows. We can add the system level one later in another PR, but we should pick record key names anticipating this future addition.
- I don't think we need the cache path in `NU_LIB_DIRS` by default.

**Comment by fdncred** [comment]
Updated:
1. Use XDG_CACHE_HOME if available.
2. Use XDG_DATA_HOME if available.
3. Removed cache path from NU_LIB_DIRS.
4. Updated screenshots
5. TBD new PR - make `/usr/share/nushell/completions` system-level auto-source folder for *nix and `HOMEDRIVE:\ProgramData\nushell\completions` for Windows

**Comment by Owen-sz** [comment]
> Updated:
> 
>     1. Use XDG_CACHE_HOME if available.
> 
>     2. Use XDG_DATA_HOME if available.
> 
>     3. Removed cache path from NU_LIB_DIRS config & default NU_LIB_DIRS.
> 
>     4. Updated screenshots
> 
>     5. TBD new PR - make `/usr/share/nushell/completions` system-level auto-source folder for *nix and `ALLUSERPROFILE\nushell\completions` for Windows which usually translates to C:\ProgramData\nushell\completions. See Kubouch's comment on auto-source + system-level [Enable system package manager to install modules such as completions in system managed paths #11337 (comment)](https://github.com/nushell/nushell/issues/11337#issuecomment-1880855112)

Hi, just wondering if the system-wide  `/usr/share/nushell/completions` has been implemented yet? I am not seeing a PR specifically adding this. I would like to be able to package [jujutsu](https://github.com/jj-vcs/jj)'s .nu completions file for [Terra](https://terra.fyralabs.com/). I would also like to add nushell completions to our custom [RPM macro](https://github.com/terrapkg/srpm-macros/blob/f417f0e7688f402984fefbea3f261f103c74d34b/macros.anda#L41) that packagers for future packages with nushell completions can easily use to bundle these completion files. Thanks!

**Comment by fdncred** [comment]
I believe `$nu.vendor-autoload-dirs` should help with that

**Comment by Owen-sz** [comment]
> I believe `$nu.vendor-autoload-dirs` should help with that

Ah I see, and that looks in `/usr/share/nushell/completions`?

**Comment by fdncred** [comment]
not if you want them autoloaded. all autoload dirs end with nushell/vendor/autoload. This is what mine looks like on my mac.
```
$nu.vendor-autoload-dirs | table -e
╭───┬─────────────────────────────────────────────────────────────────────────────────╮
│ 0 │ /Library/Application Support/nushell/vendor/autoload                            │
│ 1 │ /Applications/Ghostty.app/Contents/Resources/ghostty/../nushell/vendor/autoload │
│ 2 │ /usr/share/nushell/vendor/autoload                                              │
│ 3 │ /usr/local/share/nushell/vendor/autoload                                        │
│ 4 │ /Users/fdncred/Library/Application Support/nushell/vendor/autoload              │
╰───┴─────────────────────────────────────────────────────────────────────────────────╯
```

**Comment by Owen-sz** [comment]
> /usr/share/nushell/vendor/autoload

Sounds good, looks like `/usr/share/nushell/vendor/autoload` is the option here then. Thanks!

**Pull request merged**
