### PR TITLE
Move some `from xxx` commands to plugin

### PR DESCRIPTION
**Pull request by WindSoilder**
# Description

From nushell 0.8 philosophy: https://github.com/nushell/nushell.github.io/blob/main/contributor-book/philosophy_0_80.md#core-categories

> The following categories should be moved to plugins:
Uncommon format support

So this pr is trying to move following commands to plugin:
- [X] from eml
- [x] from ics
- [x] from ini
- [x] from vcf

And we can have a new plugin handles for these formatting, currently it's implemented here: 

https://github.com/WindSoilder/nu_plugin_format

The command usage should be the same to original command.

If it's ok, the plugin can support more formats like [parquet](https://github.com/fdncred/nu_plugin_from_parquet), or [EDN format](https://github.com/nushell/nushell/issues/6415), or something else.

Just create a draft pr to show what's the blueprint looks like, and is it a good direction to move forward?

# User-Facing Changes

_(List of all changes that impact the user experience here. This helps us keep track of breaking changes.)_

# Tests + Formatting

Don't forget to add tests that cover your changes.

Make sure you've run and fixed any issues with these commands:

- `cargo fmt --all -- --check` to check standard code formatting (`cargo fmt --all` applies these changes)
- `cargo clippy --workspace -- -D warnings -D clippy::unwrap_used -A clippy::needless_collect` to check that you're using the standard code style
- `cargo test --workspace` to check that all tests pass

# After Submitting

If your PR had any user-facing changes, update [the documentation](https://github.com/nushell/nushell.github.io) after the PR is merged, if necessary. This will help us keep the docs up to date.

### CODE REVIEW

**Comment by WindSoilder** [comment]
Sadly found that it's relative hard to add examples to plugin commands.  It causes a relatively big change.  I'd vote for leave them to separate pr to make them clear.

**Comment by fdncred** [comment]
I'd really like to have that plugin Examples PR landed before this one if possible. Examples are such an integral part of commands. 

If it were up to me, I'd like to see this done in 3 parts like.
1. Add Examples PR so all plugins can have examples.
2. Add nu_plugin_format to the nushell repo under the crates folder.
3. Remove existing built-in commands.
Ideally 2 and 3 would be in the same PR but 1 can be in another PR.

**Comment by WindSoilder** [comment]
Ok, mark as draft for now and try to get 1st one

**Comment by sholderbach** [comment]
Sorry for the merge from hell 🙏

**Comment by fdncred** [comment]
Should this fix be in here? https://github.com/nushell/nushell/pull/8009

**Comment by WindSoilder** [comment]
I think we can do these one by one, since these commands in plugin are just copy-paste implementation from nushell..

I can move code here once #8009 is ok.

**Comment by WindSoilder** [comment]
Not really sure what's going on, it seems that sometimes plugin registered failed because it doesn't exists, but when I re-run tests, it's ok to register

**Comment by fdncred** [comment]
> Not really sure what's going on, it seems that sometimes plugin registered failed because it doesn't exists, but when I re-run tests, it's ok to register

I see this all the time in the ci. There is indeed some problem with plugins and ci. I'm not sure what the fix is either.

**Comment by fdncred** [comment]
@WindSoilder, one last thing I was thinking of was we need to update all the "build-all/install-all" scripts in the root of the repo. We can do that in another PR if you want. I just wanted to mention it while I was thinking about this.

Otherwise, I think this PR looks good. Lots of work to get to this point. Good job!

**Comment by WindSoilder** [comment]
@fdncred Thanks for your reminding, I've updated relative scripts

**Comment by WindSoilder** [comment]
Is there anything I need to change?

**Pull request merged**
