### PR TITLE
Change command search key-binding

### PR DESCRIPTION
**Pull request by Kangaxx-0**
# Description

Command search keybinding in default `config nu` is `CTRL+u` which has a conflict with `kb.add_binding(KM::CONTROL, KC::Char('u'), edit_bind(EC::CutFromStart));` from default reedline, proposing a new key-binding 'CTRL+s' for searching command

# Tests

Make sure you've done the following:

- [ ] Add tests that cover your changes, either in the command examples, the crate/tests folder, or in the /tests folder.
- [x] Try to think about corner cases and various ways how your changes could break. Cover them with tests.
- [ ] If adding tests is not possible, please document in the PR body a minimal example with steps on how to reproduce so one can verify your change works.

Make sure you've run and fixed any issues with these commands:

- [x] `cargo fmt --all -- --check` to check standard code formatting (`cargo fmt --all` applies these changes)
- [x] `cargo clippy --workspace --features=extra -- -D warnings -D clippy::unwrap_used -A clippy::needless_collect` to check that you're using the standard code style
- [x] `cargo test --workspace --features=extra` to check that all the tests pass

### CODE REVIEW

**Comment by sholderbach** [comment]
`Ctrl-S` is a bad binding as it is used as the `XOFF` signal for teletype emulation, meaning the screen freezes as no printing is transmitted.

Quite frankly, the menu that is linked to it is somewhat redundant to the full help menu currently bound to `F1` (Which in itself can be an issue if it is intercepted by a hosting application like VS Code). I think the raison d'être for this menu in the default config is more that @elferherrera wanted to demonstrate how to build an interactive menu as an example. 

My personal take would be to completely remove it in favor of the full help menu, but I am open to other opinions

**Comment by fdncred** [comment]
I'd personally like to leave the menus in default config for instructional purposes. So, instead of removing one or more of them I'd suggest we could comment one or more out.

**Comment by elferherrera** [comment]
Yeap. Those menus are there only for educational purposes, as @sholderbach mention they are redundant to the original menus. Im not sure if we should leave them or not. I have noticed that people use the default config as a way to start experimenting and exploring with nushell. On the other hand it produces these confusions.

I think we can close this ticket and start a poll to see if people prefer them in the default config or in the book

**Comment by Kangaxx-0** [comment]
Abandoning for a further discussion, this keybinding can be annoying for someone who is new to nu :)

**Pull request closed without merging**
