### PR TITLE
Fixed du crash bug

### PR DESCRIPTION
**Pull request by gautamprikshit1**
A solution for #7953

### CODE REVIEW

**Comment by fdncred** [comment]
Is this better than #7962?

**Comment by gautamprikshit1** [comment]
No, it's a mere bug fix and #7962 is a complete solution. My solution prevents the error.

**Comment by fdncred** [comment]
Sorry, I wasn't trying to compare the two PRs. Was just trying to decide which fix we should accept since they both seem to fix the same problem but in different ways.

**Comment by gautamprikshit1** [comment]
No need for apologies. Learnt new things due to your mention of the other PR. Thanks

**Comment by sholderbach** [comment]
Closing this one in favour of #7962

**Pull request closed without merging**
