### PR TITLE
nu-table/ Fix table --expand issue when table with no header involved 

### LINKED ISSUE #8029: Table inside cell fails to draw correctly if cell isn't wide enough
### Describe the bug

I ran `$env` in nushell, on my mac with the terminal set to the full screen.

image

Notice how the `mode` column tries to draw the table, but it gets broken.

cc @zhiburt 

### How to reproduce

1. Set terminal to large enough size you can see the `mode` column. I set mine to full screen on the mac.
2. `$env`
3. Notice the column has broken drawing

### Expected behavior

If we can't correctly draw the table, we should shrink the cell down to `...` or similar

### Screenshots

_No response_

### Configuration

| key                | value                                    |
| ------------------ | ---------------------------------------- |
| version            | 0.75.1                                   |
| branch             | main                                     |
| commit_hash        | 6e6ef862c500345c8bca3c74775b56b8b15d1175 |
| build_os           | macos-aarch64                            |
| build_target       | aarch64-apple-darwin                     |
| rust_version       | rustc 1.66.1 (90743e729 2023-01-10)      |
| rust_channel       | 1.66.1-aarch64-apple-darwin              |
| cargo_version      | cargo 1.66.1 (ad779e08b 2023-01-10)      |
| pkg_version        | 0.75.1                                   |
| build_time         | 2023-02-08 15:08:12 +13:00               |
| build_rust_channel | release                                  |
| features           | database, default, trash, which, zip     |
| installed_plugins  |                                          |

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by zhiburt**
close #8029

### CODE REVIEW

**Comment by zhiburt** [comment]
https://github.com/nushell/nushell/blob/fed10b5e15b73fa008849e45b1ea241214a06b52/crates/nu-command/tests/commands/table.rs#L1309-L1367

**Comment by jntrnr** [comment]
@zhiburt - 

this fixes the test case, but unfortunately it doesn't fix the original issue. I'm not sure how best to create a repro for you other than to give you my `$env` output. :thinking: 

If you create a table where the a table with no header has to fit in a cell that is 8 columns wide, you might be able to repro.

**Comment by zhiburt** [comment]
Good catch;

Could you check it once again?

**Comment by jntrnr** [comment]
@zhiburt - yeah I think that fixed it

**Pull request merged**
