### PR TITLE
Adding ~user tilde recognition in file paths

### PR DESCRIPTION
**Pull request by merelymyself**
# Description

Attempts to add ~user recognition for linux only.
Apologies for the previous PR. I swear clippy threw no errors when I ran it on my own machine...

# Tests

Make sure you've run and fixed any issues with these commands:

- [x] `cargo fmt --all -- --check` to check standard code formatting (`cargo fmt --all` applies these changes)
- [x] `cargo clippy --all --all-features -- -D warnings -D clippy::unwrap_used -A clippy::needless_collect` to check that you're using the standard code style
- [x] `cargo build; cargo test --all --all-features` to check that all the tests pass

### CODE REVIEW

**Comment by fdncred** [comment]
Can you please explain what this is supposed to do? I don't understand from your description. Also, maybe it's just me but, I really have an aversion to things that only work on one platform. At a minimum, one would think things like this would work on MacOS.

**Comment by merelymyself** [comment]
I'm trying to make '~user' expand to the home path for the user in question... except it doesn't seem to be working at the moment. I'm not very experienced at this. 

It should be working for MacOS without many changes, and I also hope to get it working for Windows soon.

**Comment by kubouch** [comment]
The `~user` home completion is indeed missing and it would be a good addition, thanks for working on it!

Your code has a lot of `unwrap`s and `expect`s which are problematic in a shell which is supposed to never panic. It would be great if you could eliminate them. To me, it seems like in most cases you could work directly with Paths, or convert `path.to_str()` once beforehand and skip the `~user` expansion if it fails.

Also, ideally, it should be cross-platform since we do not want Nushell to behave differently on different OSes.

**Comment by jntrnr** [comment]
Yeah, I think this could be handy.

I was thinking - for crossplatform logic could we use the home path and then substitute the user's name for what is given after the `~`? It'd be crossplatform and wouldn't pull in the additional dependency.

**Comment by kubouch** [comment]
@jntrnr Yeah, I was thinking the same but on Linux the `root` user has a different home path than `/home/root`. But maybe it's good enough or at least good enough on Windows.

**Comment by fdncred** [comment]
How is this supposed to work?

I have 2 users on my Mac.
```
> ls /Users 
╭───┬────────────────┬──────┬───────┬────────────────╮
│ # │      name      │ type │ size  │    modified    │
├───┼────────────────┼──────┼───────┼────────────────┤
│ 0 │ /Users/Shared  │ dir  │   384 │ 3 days ago     │
│ 1 │ /Users/fdncred │ dir  │ 1,408 │ 35 minutes ago │
├───┼────────────────┼──────┼───────┼────────────────┤
│ # │      name      │ type │ size  │    modified    │
╰───┴────────────────┴──────┴───────┴────────────────╯
```
Am I supposed to be able to do `ls ~/Shared` or `ls ~Shared` or what? Also, is it supposed to work with tab completions? I'm so confused. LOL

**Comment by merelymyself** [comment]
`ls ~Shared` should be correct. Whenever ~user is used (say in a filepath such as ~user/foo/bar/txt.txt) it should automatically expand to the user's home dir. (In this case, /home/user/foo/bar/txt.txt or some equivalent)

**Comment by merelymyself** [comment]
@fdncred - previously the function wasn't being called at all because `~user` formats were being declined by the check `if !path.starts_with("~")`. `ls ~user` is working now for me.

**Comment by fdncred** [comment]
I still can't get this to work on Mac.
Screen Shot 2022-04-23 at 8 57 01 AM
It's probably true that there is no password for the `Shared` user. I'm just thinking that there's probably a better way to handle this than panicking and exiting nushell.

Changing this PR to draft until it's figured out.

**Comment by merelymyself** [comment]
Ahhhh, that is a problem I had not considered. I should probably match the error to just return `/Users/username` for MacOS.

**Comment by kubouch** [comment]
@merelymyself Instead of panicking, you can just return the un-expanded path.

**Comment by merelymyself** [comment]
@kubouch @fdncred thanks for the feedback! There's no chance of panicking now, I removed all .expect()s.

**Comment by fdncred** [comment]
Seems like this is working now. Let's see if anything breaks. Thanks!

**Pull request merged**
