### PR TITLE
ls, rm, cp, open, touch, mkdir: Don't expand tilde if input path is quoted string or a variable.

### PR DESCRIPTION
**Pull request by WindSoilder**
# Description
Fixes:  #11887
Fixes: #11626

This pr unify the tilde expand behavior over several filesystem relative commands.  It follows the same rule with glob expansion:
|  command  |  result |
| ----------- |  ------ |
| ls ~/aaa  | expand tilde
| ls "~/aaa"  | don't expand tilde
| let f = "~/aaa"; ls $f  | don't expand tilde, if you want to: use `ls ($f \| path expand)`
| let f: glob = "~/aaa"; ls $f | expand tilde, they don't expand on `mkdir`, `touch` comamnd.

Actually I'm not sure for 4th item, currently it's expanding is just because it followes the same rule with glob expansion.

### About the change
It changes `expand_path_with` to accept a new argument called `expand_tilde`, if it's true, expand it, if not, just keep it as `~` itself.

# User-Facing Changes
After this change, `ls "~/aaa"` won't expand tilde.

# Tests + Formatting
Done

### CODE REVIEW

**Comment by kubouch** [comment]
It seems good to me. One slightly weird thing about it is that `~` is now considered a "glob": `let f: glob = "~/aaa"; ls $f`. But I'm OK with it for consistency. The `mkdir` and `touch` not expanding makes sense because they don't accept a glob type. You can do `touch ($f | into string | path expand)` -- less ideal, but doable.

**Comment by WindSoilder** [comment]
Then let's merge it and see how it works :)

**Comment by alxpettit** [comment]
I know my issue is partially to blame for this, but I'd say this doesn't cover all use cases. :P

It should be possible to get path expansion while still having spaces in the path. Ideally we would have _one_ quote type for that, and another quote type with the new behavior. E.g., maybe `\``, unless we're planning something. Or we could adopt the Bash behavior and use the `"` vs `'` distinction, though I wouldn't blame people for not liking it from an intuitive standpoint.

**Comment by WindSoilder** [comment]
Thanks for your feedback!
I think currently backtick will expand home path, isn't it?  These two are different:
```nushell
ls `~/aa bb`
ls "~/aa bb"
```

**Comment by alxpettit** [comment]
Oh :S

You're totally, completely right. I think a backtick placement issue from my path tab completion must have confused me or something. Thank you for the response!

By the way, do you have any answer to a good implementation of tab completion to file paths with spaces? There have been a lot of changes in Nushell, and my code is barely functional at this point! :P

**Comment by WindSoilder** [comment]
> By the way, do you have any answer to a good implementation of tab completion to file paths with spaces?

Sorry I don't, I don't touch much of tab completion of nushell, but I think it needs to be changed to fit new rules.

**Comment by alxpettit** [comment]
No worries :)

**Comment by adrian5** [comment]
> Thanks for your feedback! I think currently backtick will expand home path, isn't it? These two are different:
> 
> ```nushell
> ls `~/aa bb`
> ls "~/aa bb"
> ```
Should the backtick difference be mentioned in [working with strings](https://www.nushell.sh/book/working_with_strings.html#backtick-quoted-strings)?

**Comment by WindSoilder** [comment]
They should be different, I think the documentation is outdated.

Currently backtick is simply a bare word, but it allows to have spaces.  So: 
```
`abc`
```
and
```
abc
```
are the same thing, but have some difference to `"abc"` and `'abc'`

**Pull request merged**
