### PR TITLE
fix: fixcd

### PR DESCRIPTION
**Pull request by Decodetalkers**
try to fix cd

Log: try to fix the bug with can enter a permisson error fold

I cannot findout a better way to realize that..Both on windows,mac and linux..emm

# Description

(description of your pull request here)

# Tests

Make sure you've done the following:

- [x] Add tests that cover your changes, either in the command examples, the crate/tests folder, or in the /tests folder.
- [x] Try to think about corner cases and various ways how your changes could break. Cover them with tests.
- [ ] If adding tests is not possible, please document in the PR body a minimal example with steps on how to reproduce so one can verify your change works.

Make sure you've run and fixed any issues with these commands:

- [x] `cargo fmt --all -- --check` to check standard code formatting (`cargo fmt --all` applies these changes)
- [x] `cargo clippy --workspace --features=extra -- -D warnings -D clippy::unwrap_used -A clippy::needless_collect` to check that you're using the standard code style
- [x] `cargo test --workspace --features=extra` to check that all the tests pass

# Documentation

- [ ] If your PR touches a user-facing nushell feature then make sure that there is an entry in the documentation (https://github.com/nushell/nushell.github.io) for the feature, and update it if necessary.

### CODE REVIEW

**Comment by jntrnr** [comment]
For this one - is part of the problem that we're not sure what the access restrictions are when we're looking at a symlink? I was hoping we could use the permissions stuff we have available now (for example on unix systems, things like `ls -la` will get the umask. Maybe we could use that?)

**Comment by Decodetalkers** [comment]
> 

The file read is a fake path, and on windows, CON will not be named as file, so if I can access the file, not permissiondenied, then we can enter the fold..

And permisson is a little complex and the permission on unix is not usable on windows.. Maybe there can be a better solution? I don't know..

**Comment by fdncred** [comment]
@Decodetalkers we need to use proper permission checking as jt suggested. we use some of it in the `ls` command so you might look there for hints on how to do it. for now, I'm changing this to draft.

**Comment by Decodetalkers** [comment]
Now I use mode again... just fix under unix.. zsh and bash also use such method to defined if they can enter a fold

**Comment by fdncred** [comment]
This seems to be a good start. Thanks for taking our advice and finding another way around. You could also look at `lsd` to understand how they do this because `lsd` is cross-platform (MacOS, Windows, Linux). https://github.com/Peltoche/lsd

**Comment by Decodetalkers** [comment]
> This seems to be a good start. Thanks for taking our advice and finding another way around. You could also look at `lsd` to understand how they do this because `lsd` is cross-platform (MacOS, Windows, Linux). https://github.com/Peltoche/lsd

Now the problem is that I do not use windows...

**Comment by Decodetalkers** [comment]
https://doc.rust-lang.org/std/os/windows/fs/trait.MetadataExt.html
seems windows need this one..

**Comment by Decodetalkers** [comment]
Now I have try to realize the logic on windows,
the Logic is in https://learn.microsoft.com/en-us/windows/win32/fileio/file-attribute-constants
readonly on the page is described as:
```
A file that is read-only. Applications can read the file, but cannot write to it or delete it. This attribute is not honored on directories. For more information, see [You cannot view or change the Read-only or the System attributes of folders in Windows Server 2003, in Windows XP, in Windows Vista or in Windows 7](https://support.microsoft.com/kb/326549).
```
and the example here is
image

**Comment by Decodetalkers** [comment]
@fdncred I have already add test, but it failed on windows, can you help me?

**Comment by Decodetalkers** [comment]
> i posted this somewhere that i thought was here. image
> 
> i'll try to checkout your pr and run the tests on windows to see what it says

So maybe origin logic already works well on windows?

**Comment by fdncred** [comment]
my test was no using your pr. it's "current state" without your pr.

**Comment by fdncred** [comment]
This is what i get when i run the tests.
```
FAIL [   0.192s]                   nu-command::main commands::cd::cd_permission_deined_fold

--- STDOUT:                                nu-command::main commands::cd::cd_permission_deined_fold ---

running 1 test
=== stderr
Error: nu::shell::directory_not_found (link)

  × Directory not found
   ╭─[source:1:1]
 1 │ ;                 icacls banned /deny BUILTIN\Administrators:F;                 cd banned;
   ·                                                                                    ───┬──
   ·                                                                                       ╰── directory not found
   ╰────
  help: IO Error: Os { code: 5, kind: PermissionDenied, message: "Access
        is denied." }


test commands::cd::cd_permission_deined_fold ... FAILED

failures:

failures:
    commands::cd::cd_permission_deined_fold

test result: FAILED. 0 passed; 1 failed; 0 ignored; 0 measured; 705 filtered out; finished in 0.17s


--- STDERR:                                nu-command::main commands::cd::cd_permission_deined_fold ---
thread 'commands::cd::cd_permission_deined_fold' panicked at 'assertion failed: actual.err.contains(\"Folder is not able to read\")', crates\nu-command\tests\commands\cd.rs:329:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```
i'm not sure if the ci allows things like this.

So, i just compiled and ran your code.
image

It allowed me to cd into the directory so there must be some other problem with how permissions are being handled in windows too.

**Comment by rgwood** [comment]
Not sure, sorry. I'm finding it difficult to follow what's going on with this PR.

**Comment by fdncred** [comment]
It seems like the last step is to add tests that can ensure this functionality works in the future. The functionality seems to work in Windows based on small testing but we need someone with CI experience to help with the test. I'm not sure why folders can't be created and permissions assigned.

**Comment by fdncred** [comment]
I changed some of the error messages.

The thing I'm still not sure about in this PR is this PR right in unix? e.g. Are we sure that +x/-x are the right permissions?  What about +r/-r and +w/-w?  If I'm reading this PR right, it only checks for execute permission but if the directory is -r and -w, it seems like we also should not be able to cd to those folders too. Right?  or am I missing some point?

**Comment by Decodetalkers** [comment]
> I changed some of the error messages.
> 
> The thing I'm still not sure about in this PR is this PR right in unix? e.g. Are we sure that +x/-x are the right permissions? What about +r/-r and +w/-w? If I'm reading this PR right, it only checks for execute permission but if the directory is -r and -w, it seems like we also should not be able to cd to those folders too. Right? or am I missing some point?

I test -w , and the file under the fold can be list by ls, and I try zsh and bash, all of them can change directory into the folder, they are the same action, and so is -r, and when is -r, except program like "ls" who need to read files under the file, all program work well.

X is allow program can work in the folder, and I have test zsh and bash, they behave the same.. 

And your change seems need to format :)

**Review by fdncred — APPROVED** [review]
I think this is good now. I approve. :)

**Pull request merged**
