### PR TITLE
Updating CircleCI

### PR DESCRIPTION
**Pull request by vsoch**
This is a work in progress to test building with CircleCI - I'll be rebasing to keep it down to one commit. Please don't merge / update the branch until WIP tag is removed, and I'll update others when it's ready for a look!

Signed-off-by: Vanessa Sochat <vsochat@stanford.edu>

### CODE REVIEW

**Comment by vsoch** [comment]
I'm going to test this on my repository until it's working, I can't see the CircleCI settings here so I want to be sure it's not the recipe first.

**Comment by vsoch** [comment]
okey doke, my [CI triggered](https://circleci.com/gh/vsoch/nushell/3) so I think there is just probably a bloop in the settings here! One more thing to check - the last bullet is about pipelines being enabled, make sure that is set to yes.

**Comment by vsoch** [comment]
Updated title to remove WIP, I think this is ready to merge. I'll open other PRs if there are any bugs - we have a connection to CircleCI with a successful first build, and the QUAY token is set to deploy on merge, so this is tiny progress!

**Comment by jonathandturner** [comment]
Thanks!

**Pull request merged**
