### PR TITLE
fix: complete paths surrounded by quotes or backticks

### LINKED ISSUE #10586: Completions from a quote don't show anything
### Describe the bug

Try typing `"<tab>` on any command that takes a directory for filepath.

I've seen folks do this in the first few seconds they use Nushell, so it's definitely muscle memory (I also find myself doing it from time to time). This shouldn't return zero results, we should just complete as normal.

### How to reproduce

1. See above

### Expected behavior

Hitting tab after typing a double quote should allow for completions as normal.

Unfortunately, currently you get no completions at all.

### Screenshots

_No response_

### Configuration

| key                | value                                    |
| ------------------ | ---------------------------------------- |
| version            | 0.85.1                                   |
| branch             | main                                     |
| commit_hash        | 5c15a4dd6e0c573ac7d902fe8af93e98f332f4ed |
| build_os           | linux-x86_64                             |
| build_target       | x86_64-unknown-linux-gnu                 |
| rust_version       | rustc 1.70.0 (90c541806 2023-05-31)      |
| rust_channel       | 1.70.0-x86_64-unknown-linux-gnu          |
| cargo_version      | cargo 1.70.0 (ec8a8a0ca 2023-04-25)      |
| build_time         | 1980-01-01 00:00:00 +00:00               |
| build_rust_channel | release                                  |
| allocator          | mimalloc                                 |
| features           | default, sqlite, trash, which, zip       |
| installed_plugins  |                                          |

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by lavafroth**
Fixes #10586

# Description

Any partial path that begins with or is surrounded by a quote or backtick will be tab completed. The completed result would be surrounded by backticks unconditionally.

output

# User-Facing Changes

See above.

# Tests + Formatting

Formatted and added test cases.

# After Submitting

### CODE REVIEW

**Comment by fdncred** [comment]
thanks @lavafroth for looking into this. we appreciate your help.

**Comment by lavafroth** [comment]
Should be ready for merging now. Thanks again for the opportunity!

**Comment by lavafroth** [comment]
The windows tests were complaining about the quotes in the filenames. Should be all green now.

**Comment by fdncred** [comment]
@lavafroth Thanks for working on this. I think this is very close. Here's one (hopefully) small change I'm requesting. I just tried this out on my Mac. Here's the use case
```
cd ~/Library<tab>
cd `~/Library/Application Support/`
```

So "Application Support" has a space in it so that means the entire path is surrounded with backticks, which is great. The problem is when I try to complete the next part of the path, we used to be able to do this and the completions could continue.
```
cd `~/Library/Application Support/`A<tab>
```
Notice the A is after the backtick. Now we have to backspace over the last backtick, type the letter, then tab.
```
cd `~/Library/Application Support/A<tab>
```
Is there a way to allow the completions to complete the original way, without having to backspace over the ending backtick?

**Comment by lavafroth** [comment]
Sure, if that is the consensus, I can implement the feature. I personally like it too. Just want to make sure others are onboard with the idea.

**Comment by fdncred** [comment]
> Sure, if that is the consensus, I can implement the feature. I personally like it too. Just want to make sure others are onboard with the idea.

That's the way it used to work before your PR, so I'm assuming everyone would be ok with that. I'm fine with waiting though if you'd like more opinions from the @nushell/core-team.

**Comment by jntrnr** [comment]
Yes, let's please keep how it used to work after the backticks are added.

**Comment by lavafroth** [comment]
@fdncred you're right, it used to work that way. I'll fix it very soon.

**Comment by lavafroth** [comment]
This commit should do the job. I really hope we have raw strings in the future though.

**Comment by fdncred** [comment]
> This commit should do the job. I really hope we have raw strings in the future though.

Agreed. I'm thinking about trying this one again https://github.com/nushell/nushell/pull/9956.


Thanks for the cleanup!

**Review by fdncred — APPROVED** [review]

**Comment by fdncred** [comment]
@lavafroth I'm just noticing now that I'm getting lots of paths with backticks around them. I'm not sure why but I'm wondering if it's related to this PR. Any guesses?
image
I expect file names/paths to have backticks around them but nothing else.

**Comment by sholderbach** [comment]
I think the problem are the numbers in there.

They would need to be escaped if the path is purely consisting of numbers (or starting in a way that the parse would be ambiguous).

Part of the code from #10543 escapes any path with numeric characters

https://github.com/nushell/nushell/blob/5c15a4dd6e0c573ac7d902fe8af93e98f332f4ed/crates/nu-cli/src/completions/completion_common.rs#L124-L130

**Comment by fdncred** [comment]
Ya, you're right. Now that I look at several directories, it's the numbers that are messing it up. 

My hot take: This is a bit annoying to me and I don't care for it. I don't like backticks at all anyway but if we have to have them, it'd be nice to only have them when necessary. If this is a compromise we have to live with, then that's fine. I also don't like how it messes up the sorting.
image
Maybe if the sorting was better it wouldn't be as noticable?

**Comment by lavafroth** [comment]
In that case, we might use backticks if the path components are purely numeric. That should only apply for path like `800/20` and `400.2/2.0`.

**Comment by lavafroth** [comment]
Another thing I noticed is that since we need spaces between mathematical operands and operators, the above examples would not need to be escaped. If there was a file named `400 / 2` or `400 - 2`, it would automatically be escaped because of the spaces in it.

`400/2` and `400-2` would still be considered paths due to the lack of spaces.

Seems to me that we should escape paths containing numerals only when they are entirely numeric.

Should I update the path escape function to behave this way?

**Comment by fdncred** [comment]
Thanks @lavafroth!

**Pull request merged**
