### PR TITLE
Fix ignore-errors for select

### PR DESCRIPTION
**Pull request by nibon7**
# Description
currently, the `ignore-errors` flag for `select` doesn't work well, hope this PR fixes this.

* before
Screenshot from 2022-10-25 22-38-18
Screenshot from 2022-10-25 22-38-49
Screenshot from 2022-10-25 22-38-38
Screenshot from 2022-10-25 23-15-38

* after
Screenshot from 2022-10-25 22-40-08
Screenshot from 2022-10-25 23-16-26

# Tests

Make sure you've done the following:

- [x] Add tests that cover your changes, either in the command examples, the crate/tests folder, or in the /tests folder.
- [x] Try to think about corner cases and various ways how your changes could break. Cover them with tests.
- [ ] If adding tests is not possible, please document in the PR body a minimal example with steps on how to reproduce so one can verify your change works.

Make sure you've run and fixed any issues with these commands:

- [x] `cargo fmt --all -- --check` to check standard code formatting (`cargo fmt --all` applies these changes)
- [x] `cargo clippy --workspace --features=extra -- -D warnings -D clippy::unwrap_used -A clippy::needless_collect` to check that you're using the standard code style
- [x] `cargo test --workspace --features=extra` to check that all the tests pass

# Documentation

- [ ] If your PR touches a user-facing nushell feature then make sure that there is an entry in the documentation (https://github.com/nushell/nushell.github.io) for the feature, and update it if necessary.

### CODE REVIEW

**Comment by sholderbach** [comment]
Can we put together a small test to not regress on that behavior?

**Comment by sholderbach** [comment]
Thanks for addressing that. Your code looks much more readable than before!

**Comment by nibon7** [comment]
I think the tests cover all the change :)

**Comment by fdncred** [comment]
So, if I understand this properly, the idea of `select -i` is to fail silently, correct?  If so, I think this is working better now and we should land it.

I tested this pr with this `ls | select -I created` as well as the other examples above and they all work as stated.

@nibon7 the last thing that I have a question about is the help text, as I think it is incorrect now. Please confirm.
```
-i, --ignore-errors - when a column has empty cells, instead of erroring out, replace them with nothing
```
I don't think "replace them with nothing" is right now.

**Comment by nibon7** [comment]
> So, if I understand this properly, the idea of `select -i` is to fail silently, correct?

exactly.

> I don't think "replace them with nothing" is right now.

I think the current implementation just ignores the errors, and "when a column has empty cells, instead of erroring out, replace them with nothing" is inaccurate.

**Comment by fdncred** [comment]
Right. We need to tweak that. After that change I'll vote to land this PR.

**Review by fdncred — APPROVED** [review]
I'm fine with these changes.

**Pull request merged**
