### PR TITLE
separate `commandline` into subcommands

### PR DESCRIPTION
**Pull request by kit494way**
# Description

Related issue and PR, #11825 #11864 
This improves the signature of `commandline`.

## Before

`commandline` returns different types depending on the flags and an aurgument.

| command                     | input   | output  | description                            |
|-----------------------------|---------|---------|----------------------------------------|
| `commandline`               | nothing | string  | get current cursor line                |
| `commandline arg`           | nothing | nothing | replace the cursor line with `arg`     |
| `commandline --append arg`  | nothing | nothing | append `arg` to the end of cursor line |
| `commandline --insert arg`  | nothing | nothing | insert `arg` to the position of cursor |
| `commandline --replace arg` | nothing | nothing | replace the cursor line with `arg`     |
| `commandline --cursor`      | nothing | int     | get current cursor position            |
| `commandline --cursor pos`  | nothing | nothing | set cursor position to pos             |
| `commandline --cursor-end`  | nothing | nothing | set cursor position to end             |

`help commandline` shows that `commandline` accepts string as pipeline input, but `commandline` ignores pipeline input.

```
Input/output types:
  ╭───┬─────────┬─────────╮
  │ # │  input  │ output  │
  ├───┼─────────┼─────────┤
  │ 0 │ nothing │ nothing │
  │ 1 │ string  │ string  │
  ╰───┴─────────┴─────────╯
```
https://github.com/nushell/nushell/blob/671bd08bcda06ab340a05f960a03dd691e59c51a/crates/nu-cli/src/commands/commandline.rs#L70

This is misleading.

Due to the change #11864 , typecheck does not work well. https://github.com/nushell/nushell/pull/11864#discussion_r1491814054

## After

Separate `commandline` into subcommands so that each subcommands returns the same type for the same input type.

| command                          | input   | output  | description                            |
|----------------------------------|---------|---------|----------------------------------------|
| `commandline`                    | nothing | string  | get current cursor line                |
| `commandline edit arg`           | nothing | nothing | replace the cursor line with `arg`     |
| `commandline edit --append arg`  | nothing | nothing | append `arg` to the end of cursor line |
| `commandline edit --insert arg`  | nothing | nothing | insert `arg` to the position of cursor |
| `commandline edit --replace arg` | nothing | nothing | replace the cursor line with `arg`     |
| `commandline get-cursor`         | nothing | int     | get current cursor position            |
| `commandline set-cursor pos`     | nothing | nothing | set cursor position to pos             |
| `commandline set-cursor --end`   | nothing | nothing | set cursor position to end             |

# User-Facing Changes

# Tests + Formatting

# After Submitting

### CODE REVIEW

**Comment by fdncred** [comment]
Nice work! This is definitely more nushell-y with sub commands. Plus, it fixes the problem @sholderbach mentioned.

**Comment by sholderbach** [comment]
Agree that the subcommand API is better to express the mutually exclusive parts.

As `atuin` uses `commandline` IIRC, we need to go the careful deprecation route

**Comment by fdncred** [comment]
@kit494way If you're not familiar with nushell deprecation, it's a way of having the original command work but with a "warning" message. Here's an example in an old PR. You may be able to dig up other PRs too. We've done this a hand-full of times now.

https://github.com/nushell/nushell/pull/11289/files#diff-0845dc2fd7fb9dbed776b0561cade84ae09f084410b3365681a9b9fd8adc7cabR142-R151

We also seem to have `ParseWarning` but I have no idea how that works plus it has an old version number.

https://github.com/nushell/nushell/blob/360ebeb0bc2762f27fadc78797e2877e047ee184/crates/nu-protocol/src/parse_warning.rs#L7-L24

**Comment by kit494way** [comment]
@fdncred Thanks. I will make changes to keep the original command and add deprecation messages.

**Comment by IanManske** [comment]
@kit494way Just FYI, PR #11851 makes a few [minor changes](https://github.com/nushell/nushell/pull/11851/files#diff-8ed0a93924cb1ecf49da4c70aae2aa4c143ea312ea281daf3d8c4300cd06ce4c) to `commandline`. I think you can ignore these changes for the most part -- sorry, I thought there wouldn't be any conflicts.

**Comment by kit494way** [comment]
Restored original command and added deprecation message.
The test seems to have failed due to a network error.

**Comment by fdncred** [comment]
We need to change that test somehow because it fails all too often. I restarted the failed ci.

**Comment by fdncred** [comment]
@stevenxxiu Just a friendly heads-up that this PR will break atiun's nushell functionality. I think you wrote the initial atuin nushell integration.

**Review by fdncred — APPROVED** [review]
I've tested this and it seems to work with deprecation. I'm ready to land it.

**Comment by fdncred** [comment]
Let's go! Thanks!

**Pull request merged**
