### PR TITLE
Add `history migrate` command

### PR DESCRIPTION
**Pull request by brunerm99**
# Description

Add `history migrate` command as requested in #10440. 

## TODO
- [ ] Make sure migration is run as a SQL transaction so if the operation is interrupted it will not partially migrate history
  - This seems like the current behavior of reedline's `save` method, but I don't see where it explicitly starts a transaction. Needs investigation.
- [ ] Add `--overwrite` flag for overwriting the current SQLite history
  - Defaults to appending history
  - Relies on getting a way to clear history without crashing
    - #9575 suggested a way to do it for `history --clear` but it hasn't been merged. 
    - There's also the `clear` method in reedline's `SQLiteBackedHistory` but this crashes as well
    - ~~Looking into how to fix these errors. Reedline's `clear` method seems better to me but then this feature would rely on a PR in reedline~~
- [ ] Benchmark to avoid issue presented in #9403 
- [x] `--keep-duplicates` flag for keeping duplicate entries
  - ~~Currently the `--keep-duplicates` flag only removes duplicates from the plaintext file. Need to check for duplicates in SQLite database as well. Because of this, currently running history migrate will still duplicate some items.~~
- [ ] Change default `start_timestamp` to nushell's first commit datetime: `2019-05-10T09:59:12-07:00`
- [ ] `--history-file` parameter for migrating from a custom file
  -  Probably another PR

### CODE REVIEW

**Comment by fdncred** [comment]
The dump macos CI sometimes gets hung up. It had taken over 2 hrs so I stopped it and restarted it.

**Comment by brunerm99** [comment]
@fdncred 

Would it be bad to restart the REPL after overwriting history? I'm having trouble getting commands to be saved to the SQLite history after clearing it (for the `--overwrite` flag).

Doing the following in this order works: 
1. Clear history by removing the sqlite database files 
2. Open a connection to the history database
3. Migrate all commands from the plaintext history using reedline's `save` method

After doing that, commands run from the REPL do not save to history until I open a new terminal, even though all the commands migrated to the new history database successfully. This leads me to believe that a new connection needs to be made to the SQLite history database following the clearing to save newly-run commands.

I don't see a good way to refresh this connection. I thought maybe creating a new REPL instance would work but I haven't found how to do this. Any suggestions?

**Comment by fdncred** [comment]
This deeper level of surgery may need to be performed in reedline vs nushell. I'm not sure. I'd want to avoid restarting if we can but you may need to figure out how reedline and nushell start using the sqlite db and call those functions if possible?

**Comment by brunerm99** [comment]
@fdncred It looks like with some slight modification to what functions reedline exposes there could possibly be a good solution. The `update_line_editor_history` function in [the repl](https://github.com/nushell/nushell/blob/main/crates/nu-cli/src/repl.rs) may be all that's needed, but I need to figure out how to get access to the line editor. I'll keep digging and slowly learning... :smile:

**Comment by fdncred** [comment]
Sounds good. I'm sure you'll come up with something.

**Comment by NotTheDr01ds** [comment]
I believe this is now mostly or completely superseded by #13450?  Can/should it be closed?

**Comment by fdncred** [comment]
ya, let's close tihs for now.

**Pull request closed without merging**
