### PR TITLE
Remove any durations over weeks

### LINKED ISSUE #9118: Weird date math
### Describe the bug

Originally reported on discord, I found this repro:

```sh
> 2023-05-07T04:08:45+12:00 - 2019-05-10T09:59:12+12:00

3yr 12month 2day 18hr 9min 33sec
```

How does one have 12 months + 2days (and more) and not roll over to the next year?

### How to reproduce

1. See above

### Expected behavior

We should properly roll to the next year when displaying the duration to the user.

### Screenshots

_No response_

### Configuration

| key                | value                                    |
| ------------------ | ---------------------------------------- |
| version            | 0.78.1                                   |
| branch             | main                                     |
| commit_hash        | d00038eb4b507ff258cbb8c8eef234b8f57b2b8c |
| build_os           | macos-aarch64                            |
| build_target       | aarch64-apple-darwin                     |
| rust_version       | rustc 1.66.1 (90743e729 2023-01-10)      |
| rust_channel       | 1.66.1-aarch64-apple-darwin              |
| cargo_version      | cargo 1.66.1 (ad779e08b 2023-01-10)      |
| build_time         | 2023-04-22 07:03:30 +12:00               |
| build_rust_channel | release                                  |
| features           | default, zip                             |
| installed_plugins  |                                          |

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by jntrnr**
# Description

A while back, we [removed durations over a week](https://github.com/nushell/nushell/pull/6613) because they became inaccurate to calculate. For example, what is the length of a month? (28 days? 30 days? 31 days?) or a year? (365 days? 366 days?)

This leads to issues like #9118 where we don't display a sensible duration.

This PR removes any notion of durations above weeks. This is certainly less visually pleasing, but should be more accurate.

Before:
```
It's been this long since Nushell's first commit:
3yr 12month 1day 23hr 4min 10sec 929ms 851µs
```

Now:
```
It's been this long since Nushell's first commit:
208wk 23hr 24min 26sec 705ms 244µs
```

Fixes #9118 

# User-Facing Changes

Durations will now only show up to weeks and not months or years.

# Tests + Formatting

# After Submitting

### CODE REVIEW

**Comment by fdncred** [comment]
Hopefully @bobhy's ideas in #9113 will fix this once and for all.

**Comment by bobhy** [comment]
Yes, I think I've got a fix for the long term.  
This PR can go in, so far as I'm concerned.  It doesn't make anything worse, but the only improvement it offers is visual: sometimes this humanized duration won't be obvious nonsense.  However, the value will still be just as inaccurate as before.

**Comment by fdncred** [comment]
I'd vote to land this if https://gist.github.com/jntrnr/567b06a3d8ce8088bcd6aa84a8f2088b can be tweaked to have millis and micros and it's put in the stdlib so that the banner is calculated properly until the point that Bob's PR lands.

**Comment by fdncred** [comment]
Since we fixed the banner with your datetime-diff script + enhancements in the stdlib, I'd vote to close this for now in the hopes that @bobhy finds time to implement his date math fixes.

**Comment by amtoine** [comment]
let's close this as we have the banner fix in the standard library :+1: 

we can always reopen this PR if we figure out we need to remove these durations after all :relieved:

**Pull request closed without merging**
