### PR TITLE
Simplify register-plugins.nu

### PR DESCRIPTION
**Pull request by Yethal**
There's no need for matching logic ever since register doesn't require passing encoding type, simple loop suffices and makes it easier to understand by new users

# Description

_(Thank you for improving Nushell. Please, check our [contributing guide](../CONTRIBUTING.md) and talk to the core team before making major changes.)_

_(Description of your pull request goes here. **Provide examples and/or screenshots** if your changes affect the user experience.)_

# User-Facing Changes

_(List of all changes that impact the user experience here. This helps us keep track of breaking changes.)_

# Tests + Formatting

Don't forget to add tests that cover your changes.

Make sure you've run and fixed any issues with these commands:

- `cargo fmt --all -- --check` to check standard code formatting (`cargo fmt --all` applies these changes)
- `cargo clippy --workspace -- -D warnings -D clippy::unwrap_used -A clippy::needless_collect` to check that you're using the standard code style
- `cargo test --workspace` to check that all tests pass

# After Submitting

If your PR had any user-facing changes, update [the documentation](https://github.com/nushell/nushell.github.io) after the PR is merged, if necessary. This will help us keep the docs up to date.

### CODE REVIEW

**Comment by fdncred** [comment]
I agree it's not necessary. However, I do like having this because it shows how to use a `match` command which is all we have until a real pattern matching command is created for nushell. I'm kind of on the fence about this.

**Comment by Yethal** [comment]
Yes but that goal might be better served by a docs page and/or a dedicated example in nu_scripts repo. Here, not so much considering all plugin names match to the exact same command which might be confusing (i.e why is there a match command involved when they all work the same)

**Comment by fdncred** [comment]
Ya, I agree. Let's just keep it simple here.

**Comment by fdncred** [comment]
I just got around to testing this on Windows and it doesn't work. I get pages of stuff like this.
```
registering C:\CarTar\debug\deps\nu_plugin_inc-6ddec9035bfa7b14.d, Error:
  × Signature deserialization error
   ╭─[C:\Users\dschroeder\AppData\Roaming\nushell\plugin.nu:1:1]
 1 │ register C:\Users\dschroeder\.cargo\bin\nu_plugin_custom_values.exe  {
   · ────┬───
   ·     ╰── unable to deserialize signature: missing field `allows_unknown_args` at line 28 column 1
 2 │   "name": "custom-value generate",
   ╰────

Error:
  × Error getting signatures
   ╭─[source:1:1]
 1 │ register 'C:\CarTar\debug\deps\nu_plugin_inc-6ddec9035bfa7b14.d'
   · ────┬───
   ·     ╰── Plugin failed to load: Error spawning child process: %1 is not a valid Win32 application. (os error 193)
   ╰────

registering C:\CarTar\debug\deps\nu_plugin_query-238267fe4239c1bf.d, Error:
  × Signature deserialization error
   ╭─[C:\Users\dschroeder\AppData\Roaming\nushell\plugin.nu:1:1]
 1 │ register C:\Users\dschroeder\.cargo\bin\nu_plugin_custom_values.exe  {
   · ────┬───
   ·     ╰── unable to deserialize signature: missing field `allows_unknown_args` at line 28 column 1
 2 │   "name": "custom-value generate",
   ╰────

Error:
  × Error getting signatures
   ╭─[source:1:1]
 1 │ register 'C:\CarTar\debug\deps\nu_plugin_query-238267fe4239c1bf.d'
   · ────┬───
   ·     ╰── Plugin failed to load: Error spawning child process: %1 is not a valid Win32 application. (os error 193)
   ╰────

registering C:\CarTar\debug\deps\nu_plugin_query-b14eb27cde8f585e.d, Error:
  × Signature deserialization error
   ╭─[C:\Users\dschroeder\AppData\Roaming\nushell\plugin.nu:1:1]
 1 │ register C:\Users\dschroeder\.cargo\bin\nu_plugin_custom_values.exe  {
   · ────┬───
   ·     ╰── unable to deserialize signature: missing field `allows_unknown_args` at line 28 column 1
 2 │   "name": "custom-value generate",
   ╰────

Error:
  × Error getting signatures
   ╭─[source:1:1]
 1 │ register 'C:\CarTar\debug\deps\nu_plugin_query-b14eb27cde8f585e.d'
   · ────┬───
   ·     ╰── Plugin failed to load: Error spawning child process: %1 is not a valid Win32 application. (os error 193)
```

**Comment by fdncred** [comment]
I ended up changing the script to avoid these issues I found. https://github.com/nushell/nushell/pull/7677

**Pull request merged**
