### PR TITLE
Dataframe with real index

### PR DESCRIPTION
**Pull request by elferherrera**
# Description

Adds real index when printing dataframe

Screenshot 2022-06-26 at 12 56 59

# Tests

Make sure you've done the following:

- [ ] Add tests that cover your changes, either in the command examples, the crate/tests folder, or in the /tests folder.
- [ ] Try to think about corner cases and various ways how your changes could break. Cover them with tests.
- [ ] If adding tests is not possible, please document in the PR body a minimal example with steps on how to reproduce so one can verify your change works.

Make sure you've run and fixed any issues with these commands:

- [ ] `cargo fmt --all -- --check` to check standard code formatting (`cargo fmt --all` applies these changes)
- [ ] `cargo clippy --workspace --features=extra -- -D warnings -D clippy::unwrap_used -A clippy::needless_collect` to check that you're using the standard code style
- [ ] `cargo test --workspace --features=extra` to check that all the tests pass

### CODE REVIEW

**Comment by fdncred** [comment]
Oh, nice! Very cool!

**Comment by elferherrera** [comment]
I think this one looks better

Screenshot 2022-06-26 at 13 56 53

**Comment by elferherrera** [comment]
Btw, with the modifications I did to the `table` command you can also do something like this

Screenshot 2022-06-26 at 14 00 57

**Comment by jntrnr** [comment]
I like the idea. I'd say go for it.

**Pull request merged**
