### PR TITLE
Publish various docker image on git-tag

### PR DESCRIPTION
**Pull request by DrSensor**
> [**Usage**][docs]

### About
This PR is about adding CI for publishing docker image on git-tag with various base image. Hopefully, this can make developing plugin a bit easier for certain scenario.

### Motivation
Personally I do this to evaluate the new format of github action, test out how to do cross compilation to put them inside docker image for quick manual test, and finally hoping to replace the legacy github action on [one of my project][ci scdlang] 😋

Actually I want to use nushell in SBC or MiniPC as a lightweight alternative of [osquery](https://osquery.io). I think nushell is a great project 👍

[ci scdlang]: https://github.com/DrSensor/scdlang/tree/master/.github

### Demo
I'm not yet fully check all the image tag but for now you can try it via:
```sh
docker run -it docker.pkg.github.com/drsensor/nushell/nu:0.2-<tag>
```
see the available tag in [this table][docs]

[docs]: https://github.com/DrSensor/nushell/blob/master/docs/docker.md

---
> I'm also available on discord in case you need to '@mention' or DM me 🙂

### CODE REVIEW

**Comment by DrSensor** [comment]
Status update
```console
$ docker run -it nu:glibc-busybox
/bin/nu: error while loading shared libraries: libdl.so.2: cannot open shared object file: No such file or directory
```
and
```console
$ docker run -it nu:glibc-distroless
/bin/nu: error while loading shared libraries: libdl.so.2: cannot open shared object file: No such file or directory
```
still not working when executed directly

**Comment by DrSensor** [comment]
`nu:glibc-distroless` now works fine :tada:
but `nu:glibc-busybox` still have a problem
```console
$ docker run -it --rm docker.pkg.github.com/drsensor/nushell/nu:glibc-busybox
/bin/nu: error while loading shared libraries: librt.so.1: cannot open shared object file: No such file or directory
```

**Comment by DrSensor** [comment]
status update: everything works now

**Comment by jonathandturner** [comment]
@DrSensor - great, is there anything I need to do to turn on support for the github action parts so that we can test the CI changes?

**Comment by DrSensor** [comment]
@jonathandturner - for quick testing, you can fork [my fork][https://github.com/drsensor/nushell] then try `git tag` on any commit and push the tag. Seems it's impossible to try the CI directly on the PR before it merged :thinking: 

<details>
<br>
<details><summary>if github package registry enabled</summary><br>

Just add `DOCKER_REGISTRY` token to [**Settings** > **Secrets**](https://help.github.com/en/articles/virtual-environments-for-github-actions#creating-and-using-secrets-encrypted-variables)
</details>

<details><summary>if using another docker registry</summary><br>

1. Add your preferred `DOCKER_REGISTRY` token to [**Settings** > **Secrets**](https://help.github.com/en/articles/virtual-environments-for-github-actions#creating-and-using-secrets-encrypted-variables)
2. Find and replace all `docker.pkg.github.com/${{ github.repository }}` in the [.github/workflows/docker-publish.yml](https://github.com/nushell/nushell/blob/9dc58247e59b2bf3c42386798f8c89a921dd8aa1/.github/workflows/docker-publish.yml) with your preferred `registry/repo`. For example:
```diff
-REGISTRY: docker.pkg.github.com/${{ github.repository }}
+REGISTRY: quay.io/nushell-test
...
-env: { REGISTRY: 'docker.pkg.github.com/${{ github.repository }}' }
+env: { REGISTRY: 'quay.io/nushell-test' }
```
</details>
</details>

**Comment by jonathandturner** [comment]
@DrSensor - might be easier to talk on here rather than discord :) 

I'm okay with landing this and testing it after it lands. If it doesn't do what you want, we can revert and try again.

**Comment by DrSensor** [comment]
@jonathandturner sounds good to me :+1: 
I will reopen this PR (or open another PR) if it doesn't work :slightly_smiling_face:

**Pull request merged**
