### PR TITLE
Move wrap responsibility on tabled

### PR DESCRIPTION
**Pull request by zhiburt**
I've tried to clean everything possible and left everything needed to keep a similar wrap behavior.

And I think I reached a middle ground.

But I want you @fdncred to check it out.

I'd like to note that `tabled` has a logic to keep words when do split for wrap.
It's different from `nu_table` certainly.
But I intentionally did not turned that on as it's a bit slower than without it I tend to believe.

So once again; Don't merge unless you're confident to do.

### CODE REVIEW

**Comment by zhiburt** [comment]
By the way, it seems like #5972 degraded quite massively with this change, from `~750` to `~1100` on my machine

**Comment by fdncred** [comment]
I expected to find some issues when moving over to tabled. Hopefully we can figure things out over the next week or so.

**Comment by zhiburt** [comment]
Interestingly ci failed with this stdout;

```
"\u{1b}[37m╭───┬─────────────────────────────────────────────────────────────────────────╮\u{1b}[39m\u{1b}[37m│\u{1b}[39m \u{1b}[1m\u{1b}[32m0\u{1b}[22m\u{1b}[39m \u{1b}[37m│\u{1b}[39m \u{1b}[37mTigre Ecuador    OMYA Andina    3824909999    Calcium carbonate    Colo\u{1b}[39m \u{1b}[37m│\u{1b}[39m\u{1b}[37m│\u{1b}[39m   \u{1b}[37m│\u{1b}[39m \u{1b}[37mmbia\u{1b}[39m                                                                    \u{1b}[37m│\u{1b}[39m\u{1b}[37m╰───┴─────────────────────────────────────────────────────────────────────────╯\u{1b}[39m"
```

Notice this Columbia part.

```
Colo\u{1b}[39m \u{1b}[37m│\u{1b}[39m\u{1b}[37m│\u{1b}[39m   \u{1b}[37m│\u{1b}[39m \u{1b}[37mmbia\u{1b}[39m                                                                    
```

It look very strange.

Do you limit width of terminal in tests?

**Comment by zhiburt** [comment]
It's caused by 2nd `lines` command seems like.

From this

```
"a\tb\tc\td\toriginTigre Ecuador\tOMYA Andina\t3824909999\tCalcium carbonate\tColombia"
```

Lines gets this

```
"\u{1b}[37m╭───┬─────────────────────────────────────────────────────────────────────────╮\u{1b}[39m\u{1b}[37m│\u{1b}[39m \u{1b}[1m\u{1b}[32m0\u{1b}[22m\u{1b}[39m \u{1b}[37m│\u{1b}[39m \u{1b}[37ma    b    c    d    origin\u{1b}[39m                                              \u{1b}[37m│\u{1b}[39m\u{1b}[37m│\u{1b}[39m \u{1b}[1m\u{1b}[32m1\u{1b}[22m\u{1b}[39m \u{1b}[37m│\u{1b}[39m \u{1b}[37mTigre Ecuador    OMYA Andina    3824909999    Calcium carbonate    Colo\u{1b}[39m \u{1b}[37m│\u{1b}[39m\u{1b}[37m│\u{1b}[39m   \u{1b}[37m│\u{1b}[39m \u{1b}[37mmbia\u{1b}[39m                                                                    \u{1b}[37m│\u{1b}[39m\u{1b}[37m╰───┴─────────────────────────────────────────────────────────────────────────╯\u{1b}[39m"
```

**Comment by fdncred** [comment]
The only way I could get Colombia to split exactly at "Colo" was to have my terminal width exactly at 80 columns wide.

Screen Shot 2022-07-09 at 8 02 40 PM

**Comment by zhiburt** [comment]
So you're right;

We use a default width `80` in tests.
And now there's no enough space for all the text.
So we need to do wrap.
So we do.

This PR

image

original logic.

image

> If I run only that test on my Mac, with this PR, it succeeds.

That's very interesting;
I would bet `terminal_width` works on mac while it doesn't on l`inux`, because of some magic with `fork/exec`.
Not an expert how it works on mac.

So we just get a bigger term_width value there and no wrap is called.

**Comment by fdncred** [comment]
1. It looks like our `terminal-size` crate is outdated, maybe they've fixed a bug?
2. You can see how it works on unix here https://github.com/eminence/terminal-size
3. I think that example should probably wrap since it's just a string of tab delimited characters that are too wide for the terminal, but I think it should wrap at the tab, not in the middle of a word.
4. This may be an opportunity to use your new string truncation functionality too so it's like "some long string...", meaning, we could have a config value named something like "wrap_methodology: truncate # truncate or wrap" and if truncate is selected we have another config value that says "truncate_at: 80". Not asking you to put this in right now, just thinking about it out loud.

**Comment by zhiburt** [comment]
> It looks like our terminal-size crate is outdated, maybe they've fixed a bug? We'll have to try the latest and see what happens.

Didn't helped.

> I think that example should probably wrap since it's just a string of tab delimited characters that are too wide for the terminal, but I think it should wrap at the tab, not in the middle of a word.

That's what `tabled` wrap does.

image

Though we still can't match because we have a finish of color in the middle.

```
\u{1b}[37mColo\u{1b}[39m\u{1b}[37mmbia\u{1b}[39m
```

> This may be an opportunity to use your new string truncation functionality too so it's like "some long string...", meaning, we could have a config value named something like "wrap_methodology: truncate # truncate or wrap" and if truncate is selected we have another config value that says "truncate_at: 80". Not asking you to put this in right now, just thinking about it out loud.

I think it's good approach.
Though I'd not use the above one as a default.
We could also have a wrap setting whether try to not split words if possible or not.
(this 'setting' is my change above)

**Comment by zhiburt** [comment]
Here it is;

```
let-env config = ($env.config | upsert table_trim { methodology: 'wrapping', wrapping_try_keep_words: false })
let-env config = ($env.config | upsert table_trim { methodology: 'truncating', truncatting_suffix: '...@@...' })
```

`"truncate_at: 80"` is not applicable is this case I think;
Because we have a necessity already to do a truncate/wrap with exact width already.

**Comment by fdncred** [comment]
Neither of these seem to work very well. I'm not sure why it's adding so much padding to the right side.
```
let-env config = ($env.config | upsert table_trim { methodology: 'wrapping', wrapping_try_keep_words: false })
```
Screen Shot 2022-07-10 at 5 31 56 PM

```
let-env config = ($env.config | upsert table_trim { methodology: 'truncating', truncating_suffix: '...' })
```
Screen Shot 2022-07-10 at 5 31 12 PM

**Comment by fdncred** [comment]
With this
```
\u{1b}[37mColo\u{1b}[39m\u{1b}[37mmbia\u{1b}[39m
```
I think the `\u{1b}[39m\u{1b}[37` is not even needed. `[39m` means use the default foreground and there is no foreground coloring change at all between Colo and mbia. So the string should be `\u{1b}[37mColommbia`. However, wrapping could change because there's the table border that could change colors.

**Comment by zhiburt** [comment]
> They work better now because it's as wide as my terminal but i still don't see ... truncating anything with this let-env config = ($env.config | upsert table_trim { methodology: 'truncating', truncating_suffix: '...' }). It truncates things but there's no ....

Must be fixed.

**Comment by fdncred** [comment]
@zhiburt how are you feeling about all these changes? are you getting mad at me for wanting to try this? are you tired of trying to fix things? do you think we should try and roll back to nu-table or keep pressing ahead with tabled?

**Comment by zhiburt** [comment]
Well I am as far :)

Question:
In case where suffix bigger then an available space, is it better to show empty space or a truncated suffix?
(I've gone with the second variant)

**Comment by zhiburt** [comment]
> @zhiburt how are you feeling about all these changes? are you getting mad at me for wanting to try this? are you tired of trying to fix things? do you think we should try and roll back to nu-table or keep pressing ahead with tabled?

But there's not a lot of things left?

As far as I remember only; try to improve the ansi in case of wrapping which we discussed above.

**Comment by fdncred** [comment]
regarding truncation, I think we want to reserve enough space to print ..., so if the text is `inode` and there's only room for 4 chars, maybe it should be `i...`.

On my Mac the speed is about 1200ms depending on which terminal I use. iterm2 is pretty slow compared to wezterm or kitty. what terminal do you use?

I'd say the most important thing is speed. we can tweak on other things/features/truncation over time, but speed is kind of a big deal.

**Comment by fdncred** [comment]
I'd also like to land this PR if we can get the tests working. Just so we get some time to test it good.

**Comment by zhiburt** [comment]
> regarding truncation, I think we want to reserve enough space to print ..., so if the text is inode and there's only room for 4 chars, maybe it should be i....

Yes but what you do when there's only room for 2 chars?
It could be

1. `in` - ignored suffix
2. `..` - trimmed suffix
3. `  ` - empty space instead.

> On my Mac the speed is about 1200ms depending on which terminal I use. iterm2 is pretty slow compared to wezterm or kitty. what terminal do you use?

:disappointed: 

> I'd say the most important thing is speed. we can tweak on other things/features/truncation over time, but speed is kind of a big deal.

:+1:

**Comment by zhiburt** [comment]
> I think i'd vote for number 2 in this instance

That's what I went with as well.

**Comment by fdncred** [comment]
@zhiburt Can you do one more thing with this PR before we land it?  Can you update the default_config.nu with the new config options and their possibilities commented out like the rest?

**Comment by fdncred** [comment]
Thanks. Let's move forward with this and see how it responds.

**Comment by zhiburt** [comment]
> Thanks. Let's move forward with this and see how it responds.

I hope you've run it a few times;
As we've seen you have a magnetic ability to catch issues :)

**Comment by fdncred** [comment]
> As we've seen you have a magnetic ability to catch issues :)

LOL. Yes, I have and I'm running it now. I'm going to try to get the core-team to do some more testing as well. Thanks for all your work here.

**Pull request merged**
