### PR TITLE
Deny wildcard dependencies

### PR DESCRIPTION
**Pull request by bobhy**
General fix to prevent pure wildcard dependencies (e.g `dependencies.rstest = "*"`).  
These are acceptable to  cargo but cannot be published to https://crates.io.
See #10095 for a case where this broke a release.

# Description
There is a `clippy::wildcard_dependencies` lint, but it is "allowed" by default (it's part of the `clippy::cargo` group, which are all allowed by default).

This PR activates the lint by passing a "-Dclippy::wildcard_dependencies" to each invocation of `rustc`, configured in `./cargo/config.toml`.  This will be used in builds at the root of the project but also in the build of child crates, like `./crates/nu-cli`.   Thus, `> cargo clippy` will flag the offending dependencies and catch the error before the PR is even posted.

Here's an example of the lint detecting a problem:
```
> cargo clippy
    Checking nu-utils v0.84.1 (/home/bobhy/src/rust/nushell/crates/nu-utils)
    Checking nu-path v0.84.1 (/home/bobhy/src/rust/nushell/crates/nu-path)
    Checking nu-glob v0.84.1 (/home/bobhy/src/rust/nushell/crates/nu-glob)
    Checking nu-json v0.84.1 (/home/bobhy/src/rust/nushell/crates/nu-json)
    Checking nu-system v0.84.1 (/home/bobhy/src/rust/nushell/crates/nu-system)
   Compiling nu-cmd-lang v0.84.1 (/home/bobhy/src/rust/nushell/crates/nu-cmd-lang)
    Checking nu-pretty-hex v0.84.1 (/home/bobhy/src/rust/nushell/crates/nu-pretty-hex)
   Compiling nu v0.84.1 (/home/bobhy/src/rust/nushell)
error: wildcard dependency for `fancy-regex`
  |
  = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#wildcard_dependencies
  = note: requested on the command line with `-D clippy::wildcard-dependencies`

error: could not compile `nu` (build script) due to previous error
warning: build failed, waiting for other jobs to finish...
error: could not compile `nu-cmd-lang` (build script) due to previous error
error: could not compile `nu-utils` (lib) due to previous error
error: could not compile `nu-path` (lib) due to previous error
```
# User-Facing Changes
none

# Tests + Formatting

- :green_circle: `toolkit fmt`
- :green_circle: `toolkit clippy`
- :green_circle: `toolkit test`
- :green_circle: `toolkit test stdlib`

# After Submitting

# After Submitting

### CODE REVIEW

**Comment by bobhy** [comment]
CAVEAT CAVEAT CAVEAT

This PR is not ready for prime time!  

1. This PR does *not* flag bad dependencies in `./Cargo.toml`, though it appears to work fine in child crates like `./crates/nu-cli/Cargo.toml`.  
2. Note that the lint error message doesn't point to the offending line of source.  And, if you invoke it as `cargo clippy -v`, you'll see that it's encountering the errors it does detect doing a preliminary build of the build scripts (`--crate build_script_build`, per the log), not the build of a source crate.

So this PR is not doing what it should be doing, may not be reliable enough for general use.

Suggestions from reviewers gratefully accepted!
You can play around with it yourself: you'll find sample wildcard dependencies you can uncomment in `./Cargo.toml` (where it doesn't work) and `./crates/nu-cli/Cargo.toml` (where it does).

**Comment by fdncred** [comment]
I'm not sure how to debug clippy. It is indeed weird that it doesn't work like we expect. Another option is to use nushell in the CI like the release.yml does.

**Comment by amtoine** [comment]
> I'm not sure how to debug clippy. It is indeed weird that it doesn't work like we expect. Another option is to use nushell in the CI like the release.yml does.
>
if i understand well, it's not only about the CI but also blocking the publishing to *crates.io* locally, am i correct @bobhy?

**Comment by bobhy** [comment]
I am mostly worried about avoiding the deferred error when some Nushell
team member tries to publish a release and gets this error, based on a PR
that some other contributor might have checked in some time previous.
The local publish case seems less of a problem, I'm involved at both ends.
I'd prefer a check that runs locally when I run `toolkit check pr` (though
it doesn't have to be clippy).
A check that only runs after I submit a PR (e.g, in CI), would be more
annoying, like the typo check that catches typos only *after* i submit the
PR.
I'll submit this to the cargo team and see what they say...  It feels like
clippy is doing the right thing, but isn't being invoked on all the right
files (due to cargo?).

**Comment by bobhy** [comment]
Opened issues with Cargo and Clippy team to see what they can offer:

https://github.com/rust-lang/cargo/issues/12561

https://github.com/rust-lang/rust-clippy/issues/11409

**Comment by bobhy** [comment]
All I've got out of this draft PR is repro scenario that I've used for a bug report to cargo and clippy teams.  Cargo took a look and said it was a clippy problem.  Clippy team hasn't engaged at all.

I'm at a dead end here, so I'm closing the PR.

**Comment by sholderbach** [comment]
Thanks for trying to address that! Sad that this got lost in translation.

Maybe we can throw something together with nu code reading the the tomls.

**Pull request closed without merging**
