### PR TITLE
Revert "hopefully the final fix for history (#2222)"

### PR DESCRIPTION
**Pull request by JosephTLyons**
Addresses https://github.com/nushell/nushell/issues/2234

### CODE REVIEW

**Comment by fdncred** [comment]
@JosephTLyons , @jonathandturner So, the fix is to limit people to only have 100 entries in their history. I'm not sure I'd call that a fix. The fix would be to change the history from defaulting to 100_000 entries [here](https://github.com/nushell/nushell/blob/a36d2a1586fda5f5f70c065e898455527d265512/crates/nu-cli/src/cli.rs#L646). An alternate fix is to change your personal `config.toml` entry named `history_size` to whatever you want it to be.

I think we should rollback this rollback and implement one of the fixes above. I'm not being protective of my crappy code, I just think it's the right thing to do.

**Comment by ryanpcmcquen** [comment]
I think this broke https://github.com/nushell/nushell/issues/2193.

**Comment by fdncred** [comment]
@ryanpcmcquen can you try the latest source from main. I put some fixes in today.

**Comment by ryanpcmcquen** [comment]
@fdncred, the latest from `main` does seem to be preserving history for me now.

**Comment by fdncred** [comment]
Yay for small victories! Thanks for the confirmation.

**Comment by ryanpcmcquen** [comment]
@fdncred, did these changes land in `0.18.1`?

**Comment by fdncred** [comment]
Yes, they were there midway between 17 and 18. There were also some other rustyline fixes that made it into 0.18.1. We defaulted everything to rustyline defaults. So, if you don't set config values under the `[line_editor]` section in your `config.toml` they get defaulted to whatever rustyline has for it's defaults.

**Pull request merged**
