### PR TITLE
Fix `datetime-diff` command throwing an error

### LINKED ISSUE #10455: `datetime-diff` doesn't work
`datetime-diff` from the `dt` standard library module always errors out with:

EDIT from maintainer:
this error appears to come when the two dates are the same, e.g. with
```nushell
datetime-diff (date now) (date now)
```
which gives
```nushell
Error: nu::shell::name_not_found

  × Name not found
    ╭─[NU_STDLIB_VIRTUAL_DIR/std/dt.nu:81:1]
 81 │     mut current = $current
 82 │     $current.millisecond = $current.millisecond + 1_000
    ·                                     ─────┬─────
    ·                                          ╰── did you mean 'second'?
 83 │     $current.second = $current.second - 1
    ╰────
```

I looked at the source code, the issue seems to be caused by `datetime-diff` still using milliseconds and microseconds.  Whereas `date to-record` doesn't have them.

### PR DESCRIPTION
**Pull request by KAAtheWiseGit**
This version of the fix involves removing `millisecond` and `microsecond` fields from the output record.

Also changed the doc comment, in a format matching the `assert` module.

Fixes #10455.

## User-Facing Changes

Output of `datetime-diff` no longer has `millisecond` and `microsecond` fields.

# Note

There are two ways to fix this issue.  This one, or by adding `millisecond` and `microsecond` fields to the record earlier on.  I am unsure which one should be taken, so I will just leave this pull request here for the discussion.

### CODE REVIEW

**Comment by sholderbach** [comment]
Thanks for giving this a shot! 

Would you mind adding a test for this command? Apparently we did not have an accompanying test file for the commands in `dt.nu` so this broke silently. This would make sure we won't regress on that in the future.

**Comment by fdncred** [comment]
I'm not up for removing these if it's going to change our welcome screen from
```
It's been this long since Nushell's first commit:
4yrs 4months 11days 1hr 28mins 20secs 403ms 809µ
```
to something without milliseconds and microseconds.

**Comment by KAAtheWiseGit** [comment]
I did not realize `pretty-print-duration` was taking the input of `datetime-diff`.  In this case, this change doesn't make much sense.

**Comment by KAAtheWiseGit** [comment]
#10466 fixes this issue and is closer to what the command's author meant, so I am closing this pull request.

**Pull request closed without merging**
