### PR TITLE
Update dependency rust-embed now that issue with its use of syn has been fixed.

### PR DESCRIPTION
**Pull request by TrevorAC99**
I brought the `syn` issue to the attention of the `rust-embed` folks who fixed the issue in `rust-embed-impl`. See https://github.com/pyros2097/rust-embed/commit/05b1f43cbb7d626f0c55d9531c33dd8078d218f6 for the changes that were made for `rust-embed` version 5.8.0 that mean that `nu` no longer needs to pin the version of syn.

### CODE REVIEW

**Comment by jonathandturner** [comment]
Why'd you close this? Seems like the right fix if they did fix the syn problem

**Comment by TrevorAC99** [comment]
I closed it because there were some tests that weren't passing and I wasn't sure what the policy was on that. I was going to look into it later but I can open it again for you to look at.

**Comment by jonathandturner** [comment]
@TrevorAC99 - I think it was pinned in one more place. One of the plugins (maybe chart?)

With that, and the fix to the conflicting files, this should pass in theory

**Comment by jonathandturner** [comment]
Thanks!

**Pull request merged**
