### PR TITLE
Revert "Return external file completions if not empty (#10898)"

### PR DESCRIPTION
**Pull request by rsteube**
# Description

This reverts #10898 which breaks external completion.
Not having file completion fallback on empty result is **intentional** as this indicates that there is nothing to complete at this position.
To have nushell fallback to file completion the external completer can simply return *nothing*.

`NO RECORDS FOUND`:
```nushell
let external_completer = {|spans|
    []
}
```

Fallback to file completion:
```nushell
let external_completer = {|spans|
}
```

# User-Facing Changes

# Tests + Formatting

# After Submitting

### CODE REVIEW

**Comment by rsteube** [comment]
fyi @lavafroth @fdncred

**Comment by lavafroth** [comment]
So we are allowing the external completer to take responsibility for completing file names too?

**Comment by rsteube** [comment]
@lavafroth 

Yes, there are positions where file completion
- is not appropriate (`pkill <pid>`)
- needs to be done for a different directory than the current workdir (`git -C otherdir ....`)
- is merged with subcommands or arguments (`glow <file/subcommand/repository>`)
- is prefixed (`http localhost jsonembed:=@<file>`)

The fallback is good for simple (or incomplete?) external completers.
But most of the time it is just wrong.
So it is important to discern between "having nothing to complete" and "not being able to".

Not relying on the shell for file completion in carapace gives it a clear interface which enables all the advanced features like caching and embedding.
Implementing file completion externally is **very** complex though and has it own issues.

**Comment by lavafroth** [comment]
Yeah, I think that makes sense.

**Comment by fdncred** [comment]
same, thanks y'all.

**Pull request merged**
