### PR TITLE
Ensure `currently_parsed_cwd` is set for config files

### LINKED ISSUE #7849: While starting nu the config.nu doesn't seem to be able to source any relative files.
### Describe the bug

I like keeping my config files a bit organized so I tried making a separate completions.nu file where I could source all my external completions. However there is a problem when starting nu fresh; the `config.nu` file cant seem to see it's neighboring files.

Screenshot from 2023-01-24 10-38-41

However when I source the full path name it seems to work fine with no errors.

Screenshot from 2023-01-24 10-43-05

This seems to only be a problem in the `config.nu` file as the completions.nu can seem to load the other completions files and even source a test file I created to get confirmation of nested sourcing.

```nu
# completions.nu
# Script for gathering all completion files.

export use cargo-completions.nu *
export use git-completions.nu *

source confirm-test-load.nu # Added as a test to see if nested sourcing works.

"Completions Loaded" # Added as a test to see confirmation.
```

### How to reproduce

1. create `config.nu` and `completions.nu` in `~/.config/nushell/`
2. add `source completions.nu` or `use completions.nu` to `config.nu`

### Expected behavior

I expect nu to load the relative files without having to use the full file path.

### Screenshots

_No response_

### Configuration

| key                | value                                           |
| ------------------ | ----------------------------------------------- |
| version            | 0.74.0                                          |
| branch             |                                                 |
| commit_hash        |                                                 |
| build_os           | linux-x86_64                                    |
| build_target       | x86_64-unknown-linux-gnu                        |
| rust_version       | rustc 1.66.0 (69f9c33d7 2022-12-12)             |
| rust_channel       | stable-x86_64-unknown-linux-gnu                 |
| cargo_version      | cargo 1.66.0 (d65d197ad 2022-11-15)             |
| pkg_version        | 0.74.0                                          |
| build_time         | 2023-01-23 13:06:35 +01:00                      |
| build_rust_channel | release                                         |
| features           | database, dataframe, default, trash, which, zip |
| installed_plugins  |                                                 |

### Additional context

I am using Fedora and I've tried this in semode permissive.

I've tried installing the bin to `/usr/local/bin/` but the problem persists.

Some relevant issues:
#6150
#7247

### PR DESCRIPTION
**Pull request by texastoland**
# Description

Fixes #7849, #11465 based on @kubouch's suggestion in https://github.com/nushell/nushell/issues/11465#issuecomment-1883847806.

# User-Facing Changes

Can source files relative to `env.nu` or `config.nu` like in #6150.

# Tests + Formatting

Adds test that previously failed.

# After Submitting

### CODE REVIEW

**Comment by kubouch** [comment]
I think after parsing the file, the directory should be restored back. The `start_in_file()` might have not been the best API choice when I implemented it… Probably the best way would be to use the same manual technique inside `eval_source` as in #6150 https://github.com/nushell/nushell/pull/6150/files#diff-9447a50446b532e347d2723b0e00c4388244964e6a0f57525fae2ec9ba52bab8R123

**Comment by texastoland** [comment]
Cool will emand 👍🏼

**Comment by texastoland** [comment]
> I think after parsing the file, the directory should be restored back

I added restoring the previous value.

> The `start_in_file()` might have not been the best API choice

I prefer any kind of abstraction vs repeating the same pattern in numerous places. 1 option could be `enter_script` and `exit_script` maintaining a stack similar to `enter_scope` and `exit_scope`. I'm partial to `process_script` (or other name) accepting a closure to save the CWD before and restore it afterward.



> the best way would be to use the same manual technique inside `eval_source`

That said I can remove `start_in_file` completely if you prefer.

**Comment by kubouch** [comment]
Looks good now.

There could be a nicer API for this, like
```rust
let previous_cwd = engine_state.enter_file(file);
...
engine_state.leave_file(previous_cwd);
```
plus removing `start_in_file()` as it's error-prone. These should also be mirrored for the StateWorkingSet and in the parser to keep things consistent.

I'm going to merge this as-is, but if you want to continue improving it, feel free to open a new PR. There is also https://github.com/nushell/nushell/pull/12262 which attempts to use a stack, but has a failing test right now.

**Comment by texastoland** [comment]
> just note that there is also #12262 which changes the API significantly,

It looks to implement part of this suggestion:

> > maintaining a stack similar to `enter_scope` and `exit_scope`.

> and hopefully, we'll manage to land it.

Yeah IFL it supersedes mine so converting to draft until I can rebase on it.

> If you want to continue improving the API, you can continue here

Any changes would be minimal so I'll lump it here 👌🏼

Thanks for the tips!

**Comment by fdncred** [comment]
Thanks!

**Comment by YizhePKU** [comment]
> I prefer any kind of abstraction vs repeating the same pattern in numerous places.

Interesting. My position is that a bad abstraction is worse than no abstraction, and repeating the same pattern a few times is OK. This is why I chose to get rid of `start_in_file()` completely in my PR, because I think the name is really confusing and it did not see consistent usage.

**Pull request merged**
