### PR TITLE
add Ellie to the standard library

### PR DESCRIPTION
**Pull request by amtoine**
the other day i heard the story of our friend Ellie the elephant and i couldn't resist adding it as a command to the standard library :blush:

### CODE REVIEW

**Comment by UliTroyo** [comment]
Uh-oh, now we need `ellie say`:
```nushell
ellie say "Cool as a cucumber"
```
```nushell
     __  ,  ╭────────────────────╮
 .--()°'.' <  Cool as a cucumber │
'|, . ,'    ╰────────────────────╯
 !_-(_\
```
I'm gonna write this as a script anyway, and have this be the way I print debug info from now on (because how could I not?), but it would be great if this could be in `std`!

**Comment by amtoine** [comment]
@UliTroyo loving this idea :pray:

**Comment by UliTroyo** [comment]
I tried to write it myself... but it's really hard to take grapheme width into account! There isn't anything in Nushell that can easily wrap text into a "bubble" of specific size, the way lists, tables, and records are rendered, right? Or any way to detect the "character width" of graphemes?

**Comment by UliTroyo** [comment]
@fdncred  Thank you! Yes, I had tried all of these (and yeah, I think `str size` would be less weird), but my problem is that because graphemes like emojis and Chinese characters sometimes get rendered as 2-space characters, and that doesn't correspond to their number of bytes which I can detect with `size` ( 4 and 3 respectively), I don't know how to style my speech bubble so that it fits the terminal width. So if I have some string that is 80 emojis in a line, and my terminal window is 80 characters, and I treat the 80 graphemes as occupying a single space each, then when I draw them to the terminal they will extend into a separate line, breaking my drawn speech bubble. And if instead I `split chars` and join until the total bytes are at least 80, I wind up with fewer characters on the screen than I'd need (and using `fill` doesn't work because I still would have to know by how many spaces I'm short of the total terminal width).

Basically, if I add any emoji to my strings, suddenly my speech bubbles are all jagged on the right, or overflowing. 😬

But character width is a terminal thing instead of a shell thing, right? If it's not too technical to ask, what does Nushell do to render such perfect tables without a jaggy edge on the right side? Or could `size` (`str size`?) potentially have a "spaces" entry with the number of spaces the characters in the strings visually take up?

(Technical stuff for the curious: I was trying to figure out the rendering of the tables by running Nushell output through `<some list or table> | table | ansi strip | into binary` and I can see there's a whole lot of non-ascii stuff going on around the visible bits, but I don't know what the code points correspond to... I'll probably eventually get curious and break up the code points and look them up individually.)

**Comment by UliTroyo** [comment]
Oh, there's no magic going on! There's no known end to terminal rendering/encoding esoterica, so I thought maybe there were some hidden control codes that the terminal could be interpreting as "fill this space" or something, but no it's just the code points for the actual visual bits, plus `\n\r` ([I found a nifty unicode inspector to check](https://apps.timwhitlock.info/unicode/inspect?s=%E2%95%AD%E2%94%80%E2%94%80%E2%94%80%E2%94%80%E2%94%80%E2%94%80%E2%94%80%E2%95%AE%0D%0A%E2%94%82+hello+%E2%94%82%0D%0A%E2%94%82+%E6%9D%B1%E4%BA%AC++%E2%94%82%0D%0A%E2%94%82+%F0%9F%92%9A%F0%9F%92%9A++%E2%94%82%0D%0A%E2%95%B0%E2%94%80%E2%94%80%E2%94%80%E2%94%80%E2%94%80%E2%94%80%E2%94%80%E2%95%AF)). If I had a way to limit the total width of tables, I could cheat by:
```nushell
["hello" "東京" "💚💚"] | table | ansi strip | lines
| each {|line| ($line | str substring -g 0..2) + ($line | str substring -g 6..) }
| str join (char newline)
```
```nushell
╭───────╮
│ hello │
│ 東京  │   <--It's funny because browsers do it incorrectly.
│ 💚💚  │      This looks fine in Nushell!
╰───────╯
```
I'll probably do this, since something in Nushell seems to internally know how wide the terminal draws certain characters, but unfortunately it also means there's no way I can handle line overflows in my speech bubbles. 😬

**Comment by fdncred** [comment]
This misalignment is something I've fought for years with nushell and what I've found is that it's not about measuring distance or characters or graphemes. You can always do multiple measurements and take the max, but even if you do that, they can still be misaligned. This is because different terminals render wide characters and emojis different. There is no unified way to do it apparently because you can try 5 different terminals and get 5 different results.

Altough, I'd be interested in understanding how `cowsay` and other `say` commands do it, to see if we can learn anything.

**Comment by UliTroyo** [comment]
I've got it! There seems to be a bug in the new `unfold` which had the script (and the whole terminal window) crashing if I specify the character width of the message as an argument. The width is just a heuristic anyway, because I can't  view specific grapheme widths. BUT! It works, and it's very cute. Whatever message you give it, it will wrap around to a width of about 80 characters, and you can even specify the colors, or whether Ellie is at the top or the bottom of the message! It's not succinct at all, but it works if you want to try it.
```nushell
use std ellie

const default_colors = {
  ellie: 'green_bold'
  bubble: 'white_bold'
  message: 'blue_bold'
}

def updown [] { ["up", "down"] }

# Have Ellie tell you something!
export def 'ellie say' [
  message: string   # What you want Ellie to say.
  --color(-c): record<ellie: string, bubble: string, message: string> = $default_colors   # You may specify the colors of the output components!
  --position(-p): string@updown = "up"   # Whether Ellie should be at the top or bottom.
  --omit-newlines(-o)   # Don't print trailing newlines above and below the message.

  # --width(-w): int = 80   # A heuristic value for the character width of the message.
] {
  # There appears to be a bug in `unfold` that crashes if operating on an outside $width
  let width = 80

  if $width < 16 {
    print "That's not enough space for Ellie to say something!"
    return
  }
  let 🧼 = (ansi reset)
  let 🐘 = (ansi $color.ellie)
  let ellie = ( ellie | ansi strip | lines | each {|| fill -w 11 | $"($🐘)($in)($🧼)" } )
  let msg = ( $message | ansi strip | lines | each {|line| line_wrap $line ( $width - 15 ) } | flatten )
  let bubble = ( bubble_wrap $msg $color $position )

  if $position == 'down' {
    if (( $bubble | length ) >= ( $ellie | length )) {
      1..((( $bubble | length ) + 1 ) - ( $ellie | length ))
      | each {|| '' | fill --width 11 }
      | append $ellie
      | wrap ellie
      | merge ( $bubble | append '' | wrap bubble )
    } else {
      $ellie
      | wrap ellie
      | merge ( $bubble | append '' | wrap bubble )
    }
  } else {
    if (( $ellie | length ) < ( $bubble | length )) {
      1..(( $bubble | length ) - ( $ellie | length ))
      | each {|| '' | fill --width 11 }
      | prepend $ellie
      | wrap ellie
      | merge ( $bubble | wrap bubble )
    } else {
      $ellie
      | wrap ellie
      | merge ( $bubble | append '' | wrap bubble )
    }
  }
  | flatten
  | format '{ellie}{bubble}'
  | str join (char newline)
  | if $omit_newlines { $in } else { $"\n($in)\n" }
}

# Create a speech bubble around a message.
def bubble_wrap [
  message: list<string>     # Each line must already be the same size.
  color: record<ellie: string, bubble: string, message: string>   # The colors of the parts.
  position: string@updown   # The position of the tail of the speech bubble.
] -> list<string> {
  let 🧼 = (ansi reset)
  let 💬 = (ansi $color.bubble)
  let 📮 = (ansi $color.message)

  $message
  | table   # Cheaty Mc.Cheat! Let's get Nushell to give us some bubble-like thingy.
  | ansi strip
  | lines
  | each {|line| ($line | str substring -g 0..2 ) + ($line | str substring -g 6..) }
  | upsert 0 ($in | $" ($💬)($in.0)($🧼)" )
  | reverse
  | upsert 0 ($in | $" ($💬)($in.0)($🧼)")
  | reverse
  | each {|line| str replace -a -r '│ (.+?) │' $" │ ($📮)${1}($🧼) │" }
  | each {|line|
    str replace -a -r '^ │(.+?)│$' $" ($💬)│($🧼)${1}($💬)│($🧼)"
  }
  | if $position == 'up' {
    upsert 1 ($in.1 | str replace $" ($💬)│($🧼)" $"($💬)<($🧼) " )
  } else {
    reverse | upsert 1 ($in.1 | str replace $" ($💬)│($🧼)" $"($💬)<($🧼) " ) | reverse
  }
}

# Wrap a single string to a heuristic character width.
def line_wrap [
  line: string   # The line of text to wrap.
  width: int     # The heuristing character width to target.
] -> list<string> {
  let width = $width
  unfold $line {|text|
    if ($text | str length -g) < $width {

      # If we're at the tail end of the string, return it.
      { out: $text }

    } else {
      let index = ( $text | str index-of ' ' -g -e -r 0..($width) )
      if $index > 0 {

        # If we can wrap at a space character, let's do so.
        {
          out: ($text | str substring -g 0..($index) )
          next: ($text | str substring -g $index.. | str trim --left )
        }

      } else {

        # Else, let's cut and hyphenate.
        {
          out: (($text | str substring -g 0..( $width - 1 )) + '-')
          next: ($text | str substring -g ( $width - 1 ).. )
        }

      }
    }
  }
}
```
Now if you:
```nushell
ellie say "Hello Nushell!"
```
you get:
```nushell

     __  ,  ╭────────────────╮
 .--()°'.' <  Hello Nushell! │
'|, . ,'    ╰────────────────╯
 !_-(_\    
```
and if you:
```nushell
ellie say --position down --color {ellie: mb, bubble: wb, message: ub} "🐘 こん
にちは！Nu draws inspiration from projects like PowerShell, functional programming languages, and modern CLI tools. Rather than thinking of files and data as raw streams of text, Nu looks at each input as something with structure. For example, when you list the contents of a directory what you get back is a table of rows, where each row represents an item in that directory. These values can be piped through a series of steps, in a series of commands called a 'pipeline'."
```
you get:
```nushell

            ╭─────────────────────────────────────────────────────────────────╮
            │ 🐘 こんにちは！Nu draws inspiration from projects like          │
            │ PowerShell, functional programming languages, and modern CLI    │
            │ tools. Rather than thinking of files and data as raw streams of │
            │ text, Nu looks at each input as something with structure. For   │
            │ example, when you list the contents of a directory what you get │
            │ back is a table of rows, where each row represents an item in   │
     __  ,  │ that directory. These values can be piped through a series of   │
 .--()°'.' <  steps, in a series of commands called a 'pipeline'.             │
'|, . ,'    ╰─────────────────────────────────────────────────────────────────╯
 !_-(_\    
```
...but you can't see the colors on the browser, so try it out!

**Comment by fdncred** [comment]
This is what I get
image

**Comment by hudclark** [comment]
> I've got it! There seems to be a bug in the new `unfold` which had the script (and the whole terminal window) crashing if I specify the character width of the message as an argument. The width is just a heuristic anyway, because I can't view specific grapheme widths. BUT! It works, and it's very cute. Whatever message you give it, it will wrap around to a width of about 80 characters, and you can even specify the colors, or whether Ellie is at the top or the bottom of the message! It's not succinct at all, but it works if you want to try it.

@UliTroyo Would you mind sharing how to recreate the bug you've encountered with `unfold`? I would like to fix it :)

**Comment by amtoine** [comment]
@UliTroyo 
this is really cool, can't wait to see a PR with that :pray:

**Comment by UliTroyo** [comment]
@hudclark it wasn't `unfold` after all! It was `str index-of` when using the `--range` flag with non-ascii characters in special circumstances. I've now reported it here: https://github.com/nushell/nushell/issues/10774

**Comment by hudclark** [comment]
> @hudclark it wasn't `unfold` after all! It was `str index-of` when using the `--range` flag with non-ascii characters in special circumstances. I've now reported it here: #10774

Thanks for the follow-up!

**Comment by hustcer** [comment]
Can we add `ellie say` to std lib? BTW: The code here in https://github.com/nushell/nushell/pull/10686#issuecomment-1769853223 may not work for Nu v0.88.1

**Pull request merged**
