### PR TITLE
`explore` tweaks Round 1

### PR DESCRIPTION
**Pull request by rgwood**
A few small tweaks to the new `explore` command:

1. Rewrote the help text a bit.
    1. I think it's important to mention `:try` up front.
    2. Removed the info about `:help foo` because it's currently supported by very few subcommands
2. Make `exit_esc` default to true. I want to avoid people getting stuck in `explore` like they get stuck in Vim
3. ~~Always show the help message ("For help type :help") on startup~~
    1. The message is small+unobtrusive and I don't this is worth a configuration item
4. Exit the information view when Escape is pressed
5. General typo+grammar cleanup
    
cc: @zhiburt @fdncred

### CODE REVIEW

**Comment by fdncred** [comment]
I think all this looks good to me but I do have one question about the `show_banner` changes. As I recall, we had that so that people would or would not see the banner page again when hitting `esc` repeatedly to quit. Is that still what it's for, or something else? I guess it's more of not objecting to the change but more of about what the functionality is that this PR is disabling. Maybe @zhiburt remembers.

**Comment by zhiburt** [comment]
> As I recall, we had that so that people would or would not see the banner page again when hitting esc repeatedly to quit

Correct.
I am not sure why it was removed.

https://github.com/nushell/nushell/pull/7511/files#diff-79de7debe9733841dd181dee558d84296b6f016fb8a890a689a6cef749aa7b81R48

**Comment by rgwood** [comment]
> As I recall, we had that so that people would or would not see the banner page again when hitting esc repeatedly to quit.

Hmm. I don't understand why that needs a user-facing configuration entry.

**Comment by zhiburt** [comment]
> Hmm. I don't understand why that needs a user-facing configuration entry.

It was originally proposed by @remmycat in #7332

> In response to a comment on the original PR about a "help splash screen" on first open: Please do not show the help message only on the very first time someone opens the tool, people cannot even scroll up in the terminal to read that again when they need it. I'd much rather have a config like show_banner to deactivate the help message if it get's too annoying after a while.

**Comment by fdncred** [comment]
unrelated to this PR - @zhiburt would you be willing to join discord to chat with us? it doesn't have to be today but some time in the future it would be nice. it's hard having Q&A over github issues. Here's our discord server https://discord.gg/NtAbbGn

**Comment by rgwood** [comment]
My understanding (maybe wrong) is that `help_banner` controls whether to show the "For help type :help" message. I don't think that needs to be user-configurable.

**Comment by rgwood** [comment]
ugh - this is extremely broken after trying to fix a bunch of merge conflicts

**Comment by rgwood** [comment]
I have removed the `show_banner` change for now because I think the configuration for `explore` is a big conversation and I don't want it to hold up the other changes.

**Comment by remmycat** [comment]
Oh, regarding the config for the help message you quoted me on:

My point was not that this _should_ be configurable. I meant only that _if_ there needs to be a way to hide it (i.e. because people find it annoying), it should be hidden via configuration or another conscious opt-out, not by some metric like "user has opened explore before".

I think it's great if it's just always shown 🙂

**Comment by rgwood** [comment]
Merging because I believe `help_banner` was the only contentious part of this PR.

**Pull request merged**
