### PR TITLE
Add MatchAlgorithm for completion suggestions

### PR DESCRIPTION
**Pull request by Tropid**
# Description

This PR tackles two topics:

1) Pass options to `Completer::fetch()` to allow customization of the completer
2) Move suggestion filtering to `MatchAlgorithm` so it is easy to add more advanced suggestion matching (e.g. fuzzy matching)

# Implementation

Pass `CompletionOptions` to each `fetch()` call for each `Completer` and add `MatchAlgorithm` to `CompletionOptions` which specifes how completers should match possible suggestions. The current default would be "prefix", ~this PR will add some kind of substring matching~ (Edit: this PR adds just the basic implementation with a prefix matcher). Future PRs can add more match algorithms, (e.g. fuzzy matching or substring matching). The check if a completion matches the input is also moved to the `MatchAlgorithm` so that the actual comparison happens only at one place and is not duplicated in every completer.

This PR is not intended to change the current completion behaviour (which is prefix based).

# TODOs
- [x] Pass `CompletionOptions` to every completer
- [x] Handle matching logic in `MatchAlgorithm` (instead of in every single completer)
- [x] Add basic unit test for `MatchAlgorithm::Prefix`

### CODE REVIEW

**Comment by fdncred** [comment]
We're at risk of bit-rot here. If we still want to move forward with this can you please resolve the conflicts that have appeared recently?

**Comment by fdncred** [comment]
thanks. let's see what happens.

**Comment by Tropid** [comment]
@fdncred what do you mean by "bit-rot"? If you have some some concerns with this PR I'd be open to discuss it/change things.

**Comment by fdncred** [comment]
@Tropid I just meant that the longer a PR sits uncommitted the further out of date it gets. So, when you updated it, I landed it so it could avoid that and others could start using/experimenting with your changes.

**Pull request merged**
