### PR TITLE
Make login.nu work when using nu as a login shell 

### LINKED ISSUE #6055: `login.nu` don't work.
### Describe the bug

I use `chsh -s /bin/nu` to change my login shell to `nu`. After reboot, `login.nu` just don't work whan I login...
But if I run `nu -l` in shell manually, `login.nu` work normally.
I search for a while and still not found solution...

Sorry for my bad English.
And I not familiar with github, if has better place to asking, please tell me!

### How to reproduce

1. `chsh -s /bin/nu`
2. logout and login
3. `login.nu` don't work

### Expected behavior

I expected nu will run `login.nu` when I login.

### Screenshots

_No response_

### Configuration

> version | transpose key value | to md --pretty

| key                | value                                           |
| ------------------ | ----------------------------------------------- |
| version            | 0.65.0                                          |
| branch             |                                                 |
| commit_hash        | 390d06d4e7383d9fee814713bda8d1aaca858c5a        |
| build_os           | linux-x86_64                                    |
| build_target       | x86_64-unknown-linux-gnu                        |
| rust_version       | rustc 1.62.0 (Arch Linux rust 1:1.62.0-1)       |
| cargo_version      | cargo 1.62.0                                    |
| pkg_version        | 0.65.0                                          |
| build_time         | 2022-07-06 10:00:06 +00:00                      |
| build_rust_channel | release                                         |
| features           | database, dataframe, default, trash, which, zip |
| installed_plugins  |                                                 |

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by nibon7**
# Description

Tested with `ssh`, `su -` and `sudo -i -u` on linux

detailed implementation for bash and zsh:

https://github.com/bminor/bash/blob/f3a35a2d601a55f337f8ca02a541f8c033682247/shell.c#L1759-L1772
https://github.com/zsh-users/zsh/blob/00d20ed15e18f5af682f0daec140d6b8383c479a/Src/init.c#L251-L258

Fixes #6055

# Tests

Make sure you've done the following:

- [ ] Add tests that cover your changes, either in the command examples, the crate/tests folder, or in the /tests folder.
- [ ] Try to think about corner cases and various ways how your changes could break. Cover them with tests.
- [ ] If adding tests is not possible, please document in the PR body a minimal example with steps on how to reproduce so one can verify your change works.

Make sure you've run and fixed any issues with these commands:

- [x] `cargo fmt --all -- --check` to check standard code formatting (`cargo fmt --all` applies these changes)
- [x] `cargo clippy --workspace --features=extra -- -D warnings -D clippy::unwrap_used -A clippy::needless_collect` to check that you're using the standard code style
- [x] `cargo test --workspace --features=extra` to check that all the tests pass

### CODE REVIEW

**Comment by fdncred** [comment]
I don't see how this fixed #6055. In that PR the person did `chsh`. This PR just checks for a `-` at the start of the first parameter. I also can't get this to work on my Mac. Maybe I just don't understand or am doing something wrong.

I changed the code just so it prints out what argv0 is and I get this.
```
> sudo -h fdncred ./target/debug/nu 
argv0: Some("./target/debug/nu")
```
```
> ./target/debug/nu -c "echo hi"
argv0: Some("./target/debug/nu")
```

**Comment by nibon7** [comment]
> I don't see how this fixed #6055.

I  used `chsh -s /bin/nu`  to change default shell, and `ssh user@localhost` to repo this issue, it's ok.

**Comment by nibon7** [comment]
> This PR just checks for a `-` at the start of the first parameter. I also can't get this to work on my Mac

Is nu your login shell?

**Comment by fdncred** [comment]
> Is nu your login shell?

Not on windows or mac. Let me spin up WSL and try it there. Maybe that't the entire point and i'm missing it. Will report back.

**Comment by nibon7** [comment]
I think you should not set `PATH` in login.nu while `zoxide` is executed in env.nu. Nu eval env.nu, then config.nu, and login.nu at last.

https://github.com/nushell/nushell/blob/6b4e57703223f3d3289ee56ba7db7474f1835aab/src/main.rs#L366-L371

**Comment by fdncred** [comment]
Of course, you are correct. The order of sourcing the files is very very important. Moving it to env.nu, where it should be, works great!

Thanks for taking the time to help me understand.

Let's land this!

**Pull request merged**
