### PR TITLE
Fixed json parsing

### PR DESCRIPTION
**Pull request by nanoqsh**
# Description

I noticed that some json values are not parsed at the top level, for example: `null`, `true`, `false`. Although this is a valid json.
```
> "null" | from json
Error:
  × Error while parsing JSON text
   ╭─[entry #12:1:1]
 1 │ "null" | from json
   ·          ────┬────
   ·              ╰── error parsing JSON text
   ╰────

Error:
  × Error while parsing JSON text
   ╭────
 1 │ null
   ╰────
```

I tried to fix it and it seems to work fine.

# User-Facing Changes

It should give fewer errors.

# Tests + Formatting

Don't forget to add tests that cover your changes.

Make sure you've run and fixed any issues with these commands:

- `cargo fmt --all -- --check` to check standard code formatting (`cargo fmt --all` applies these changes)
- `cargo clippy --workspace --features=extra -- -D warnings -D clippy::unwrap_used -A clippy::needless_collect` to check that you're using the standard code style
- `cargo test --workspace --features=extra` to check that all tests pass

# After Submitting

If your PR had any user-facing changes, update [the documentation](https://github.com/nushell/nushell.github.io) after the PR is merged, if necessary. This will help us keep the docs up to date.

### CODE REVIEW

**Comment by sholderbach** [comment]
Good catch!
Kind of surprising that this fixes it.
Would you mind adding appropriate tests to the [`from json` tests](https://github.com/nushell/nushell/blob/899383c30c03fb9274e7cd862d4ec5bd36af6590/crates/nu-command/tests/format_conversions/json.rs), so we don't accidentally regress on that?

Is an empty string a valid `null` object or an error?

**Comment by jntrnr** [comment]
@nanoqsh can you also add a test or two to make sure this works in the future?

**Comment by nanoqsh** [comment]
> Is an empty string a valid null object or an error?

@sholderbach it gives a null
```
> "" | from json | to json
null
```

@jntrnr added

**Comment by sholderbach** [comment]
OK according to the [JSON spec](https://www.ecma-international.org/wp-content/uploads/ECMA-404_2nd_edition_december_2017.pdf). an empty file  (`EOF`/`\x00` being the first token) is not valid json. It has to start with either the keywords, a number, or an (empty) record, string, or list.

https://stackoverflow.com/a/30621997/15171257

**Comment by sholderbach** [comment]
I added a test to ensure proper types. 

Not sure if we should error or let the empty string be `null`

**Comment by jntrnr** [comment]
I think it's okay for us to be a little more resilient, even if it steps outside of the json spec. I think nu-json is built from the hjson crate iirc, so there are some parts where we're a little more lenient.

**Pull request merged**
