### PR TITLE
refactor the `CONTRIBUTING.md` guidelines for `nu-std`

### PR DESCRIPTION
**Pull request by amtoine**
## Description
just a little refactor of `CONTRIBUTING.md` of the standard library in `nu-std`.
- see the new version [here](https://github.com/amtoine/nushell/blob/stblib/refactor/CONTRIBUTING-guidelines/crates/nu-std/CONTRIBUTING.md).

> **Note**
> actually, that one might be best reviewed commit by commit :yum: 
> i tried to be as explicit as possible :relieved: 

- i fixed the width to `80` columns
- cc/ @bobhy, if you want to jump in and find broken links / bad changes

### CODE REVIEW

**Review by bobhy — COMMENTED** [review]
I'm good with all these changes, will approve separately.
It's great that you have a technique for canonic formatting of markdown files.
I think it's bad for the project that you're the only one who can run it currently.  Erodes everybody's productivity!
There are several MD linter/formatter tools around, maybe we can agree to adopt one of them and use it as the gold standard? 
I would quibble with some of link changes, but they all work and I don't want to start a  flame war now   Let's have that discussion once and for all when we're evaluating candidate linter/formatting tools.

**Comment by presidento** [comment]
I miss the documentation part. It may be added later, but at this moment I see that new modules are coming to the standard library, and I am afraid that somebody else will have to document these contributions later. At least it would be good to state the minimum requirements of in-line documentation which can be a source of the official documentation later. (For example, explain the rationale at the module level and add the necessary comments to the commands.)

**Comment by amtoine** [comment]
@bobhy 
i do not have a particular `markdown` formatter :eyes: 
it's just practice and writing quite a lot of `README`, i kinda know how to format it, what works, what does not, what is optional, etc, etc, ... :yum: 

@presidento 
if you feel things are missing, we can discuss that in an appropriate place :relieved: 
this poor PR is just a refactoring of the work of @bobhy in #8894 :wink:

**Comment by presidento** [comment]
OK then

**Comment by bobhy** [comment]
Is there any reason to hold off merging this?  FWIW, I'm good with it.

**Pull request merged**
