### PR TITLE
Add interactive plots using plotly.

### PR DESCRIPTION
**Pull request by lambertsbennett**
# Description
I really like the ability to perform operations on dataframes within Nushell. This is a draft pull request with a small addition to add interactive plot generation from dataframes using plotly. There is a lot of work that needs to be done to this to bring it to a decently useable level. But I figured I would throw it up here to see if there is any interest before I go any further.  Currently you can pipe a dataframe to dfr scatter and then choose the column names as inputs for a simple scatter plot. This then opens a browser window with the plot. If there is interest here I would be happy to keep working on these features. Please note that the code at this point is definitely not ready for any kind of meaningful use other than generating an example scatter plot from integer values. The rust implementation of plotly doesn't work well with polars dataframes, so quite some work needs to be done there.

# User-Facing Changes
add the command ```dfr scatter```. However, it would be interesting to hear whether it could make sense to just add ```dfr plot``` and then take the plot type as an argument along with values needed to populate different plot types. This would definitely reduce a command explosion.

### CODE REVIEW

**Comment by fdncred** [comment]
I've always wanted a great plotting integration. I was thinking we'd eventually use this one https://github.com/yuankunzhang/charming, although I've never tried it.

One thing that I see in your PR is that it seems to only be for dataframes. I think we'd want a command to support any nushell command that provides the right outputs for plotting.

Having said that, I'd love to give this a try. Can you provide some mocked up sample data in a nushell command that demonstrates what you've done?

**Comment by lambertsbennett** [comment]
Oooh charming makes really sleek looking plots. Honestly, I'm not attached to plotly, I'm just familiar with it from Pandas/Python. The difficulties of using plotly in rust with polars though really doesn't make it an obvious choice for plotting dataframes.

I agree that it would be best if it was a general purpose plotting tool, definitely something I can work towards!

For now you can do something like this ```[[a b]; [1 2] [3 4] [5 6]] | dfr into-df | dfr scatter a b ``` to see it in action. 

Embarrassingly it's a pretty fragile implementation so this will only work with integer data for the moment.

**Comment by fdncred** [comment]
cool, that's fun.
image

**Comment by lambertsbennett** [comment]
Closing this an opening a new draft with a better plotting implementation that handles arbitrary Nu values.

**Pull request closed without merging**
