### PR TITLE
add match-text style + config setting for ide menu

### PR DESCRIPTION
**Pull request by maxomatic458**
the match-text style (https://github.com/nushell/reedline/pull/730) is now configurable via the config.nu file.
the option ``correct_cursor_pos`` can now also be set in the config.nu file.

### CODE REVIEW

**Comment by fdncred** [comment]
> the match-text style (https://github.com/nushell/reedline/pull/730) is no configurable via the config.nu file.

Since it's not configurable, what is the default and will that work with dark and light terminals?

> the option correct_cursor_pos can now also be set in the config.nu file.

I have no idea what `correct_cursor_pos` means. It would be good to have some comments by some (or all) of these configurable values.

**Comment by maxomatic458** [comment]
> Since it's not configurable, what is the default and will that work with dark and light terminals?
sorry made a typo there, it is NOW configurable. the default is just underlining the text (im not sure how to do it in the config.nu file as a style, so i didnt add it explicitally there)

> I have no idea what correct_cursor_pos means. It would be good to have some comments by some (or all) of these configurable values.

that means that it will match the position of the suggestion with the text by the user ill add a comment for what it does

**Comment by fdncred** [comment]
Thanks. This looks good with my testing.

**Comment by fdncred** [comment]
@maxomatic458 I've found some strangeness where the prompt goes up as you arrow or tab down in the completion_menu items. Any ideas about this?

go-up

This is what my completion menu looks like.
```
  {
    name: completion_menu
    only_buffer_difference: false
    marker: $" \n❯ (char -u '1f4ce') "
    type: {
      layout: columnar
      columns: 4
      col_width: 20   # Optional value. If missing all the screen width is used to calculate column width
      col_padding: 2
    }
    style: {
      text: { fg: "#33ff00" }
      selected_text: { fg: "#0c0c0c" bg: "#33ff00" attr: b}
      description_text: yellow
      match_text: {attr: u}
      selected_match_text: {attr: ur}
    }
  }
```

**Comment by maxomatic458** [comment]
@fdncred Not sure if thats something that would be caused by this PR.
I will have a look at it.

Are you able to replicate it on windows? Maybe something in the menu refactor broke stuff for unix systems

**Comment by maxomatic458** [comment]
@fdncred this seems to happen because the description "str substring" is to long to fit in a single line (the columnar menu doesnt truncate suggestions or descriptions if they are to long)
maybe the description got changed recently, and now its easier to notice

**Comment by maxomatic458** [comment]
i made a issue on it for here https://github.com/nushell/reedline/issues/738

**Pull request merged**
