### PR TITLE
nu-cli/completions: completion for use and source

### PR DESCRIPTION
**Pull request by herlon214**
# Description

Adds completion to the commands `use` and `source` listing the files that ends with `.nu` in the current folder and in all the `NU_LIB_DIRS`.

1) There's one current limitation: if you have two files with the same name but different folders, and those folders are in the `NU_LIB_DIRS` it will probably show both files and the user won't know which one is what.

[asciicast](https://asciinema.org/a/m894hJwRbhMydXDcQtcSHU2HI)

# Tests

Make sure you've run and fixed any issues with these commands:

- [x] `cargo fmt --all -- --check` to check standard code formatting (`cargo fmt --all` applies these changes)
- [x] `cargo clippy --all --all-features -- -D warnings -D clippy::unwrap_used -A clippy::needless_collect` to check that you're using the standard code style
- [x] `cargo build; cargo test --all --all-features` to check that all the tests pass

### CODE REVIEW

**Comment by fdncred** [comment]
Just a comment following some of the discussion on discord, if duplicate files are detected, it may be better to fail, listing the two (or more) files that are duplicated versus just closing one.

**Comment by herlon214** [comment]
@fdncred what do you mean by fail? do not show any suggestion at all?

**Comment by fdncred** [comment]
I mean that if it there are dupes it should. It source anything and give an error reporting that these are the two files or defs that are conflicting.

**Comment by herlon214** [comment]
@fdncred what's the current Nu's behavior when I have multiple files named `myfile.nu` if I do `source myfile.nu`?
I mean, which one Nu will choose?

I tried here, it didn't return any error and I'm also not sure which file nu decided to use. So I'd say that we shouldn't return error for that case, once doing `source myfile.nu` doesn't return error in that case

**Comment by fdncred** [comment]
I have no idea but you're right, maybe this isn't your problem to solve here. Maybe it's for another issue/pr and you just found it by accident. I'm happy for you to solve it if you want, but I think there should be some notification about dupes.

**Comment by jntrnr** [comment]
I just gave this a try. It's great we'll have `use`/`source` completions soon.  I wasn't able to get it working for `source` a file from `~/Source/` so maybe it doesn't respect home paths yet?

**Comment by herlon214** [comment]
@jntrnr The `~/Source/~` is in the lib_dirs env var,  or was your pwd `~/Source/`?

**Comment by herlon214** [comment]
I'm afraid doing `$ source ~/Source/<tab>` isn't working. I'm gonna check it soon.

**Comment by herlon214** [comment]
@fdncred What's the proper way to show to the user some `warning` message? Probably not using a `println!()` I suppose 🤔 
Do we have any function that deals with this kind of message (like a yellow-ish warning message)?
So I could dedupe and use it to warn the user about the duplication.

**Comment by fdncred** [comment]
I'd guess a custom shellerror?

**Comment by herlon214** [comment]
> I'd guess a custom shellerror?

Interesting, I didn't know about them. I will take a look.

**Comment by herlon214** [comment]
omg, fixing the `~/Source` was so tricky 😅 but I think now it's ready.
can you give it another try @jntrnr ?
---
@fdncred I removed the dedup, I will raise one issue related to that problem in order to add the error message and pick that in another PR. Does that work for you?

**Comment by fdncred** [comment]
wow @herlon214 , you're becoming and expert at these completion things. thanks so much. I look forward to your next PR, whatever/whenever that is. :)

**Comment by jntrnr** [comment]
@herlon214 - we're closer. I think when you do `source ~/<tab>` you also want to show the directories as the source file might be inside one of those directories. So maybe directories + *.nu files?

**Comment by herlon214** [comment]
@jntrnr hmmm, true, nice catch about the folders. I will implement that

**Comment by herlon214** [comment]
@jntrnr done ✅

**Comment by jntrnr** [comment]
Great! Let's give this one a go

**Pull request merged**
