### PR TITLE
Another shot at trying to setup codecov

### LINKED ISSUE #7944: Calculate test coverage in the CI
### Related problem

As described in https://github.com/nushell/nushell/issues/5720 there is interest to estimate the code coverage of Nushell.
Doing this locally takes quite some time and also doesn't help to estimate the coverage change of PRs.

### Describe the solution you'd like

The free service Codecov, and it's corresponding [Action](https://github.com/codecov/codecov-action) can help with that.
Here is an example of the UI with a project I maintain: https://app.codecov.io/gh/Deltares/xmipy
If wanted, a bot also comments on PRs to report the coverage change: https://github.com/Deltares/xmipy/pull/79
They also provide badges which can be added to the README: https://about.codecov.io/product/feature/badges/

### Additional context and details

A script like this one could be used on Github Actions to create `lcov.info` that Codecov expects: https://about.codecov.io/tool/lcov/

```bash
#!/bin/bash
set -euxo pipefail
source <(cargo llvm-cov show-env --export-prefix) # Set the environment variables needed to get coverage.
cargo llvm-cov clean --workspace # Remove artifacts that may affect the coverage results.
cargo build --workspace
cargo test --workspace
cargo llvm-cov report --lcov --output-path lcov.info 
```

### PR DESCRIPTION
**Pull request by sholderbach**
Trying to setup using https://github.com/taiki-e/cargo-llvm-cov#get-coverage-of-external-tests

https://docs.codecov.com/docs/github-2-getting-a-codecov-account-and-uploading-coverage

Closes #7944

### CODE REVIEW

**Comment by Hofer-Julian** [comment]
Nice, seems like it works 🎉
https://app.codecov.io/gh/nushell/nushell/tree/stefan-codecov

**Comment by sholderbach** [comment]
Somehow the llvm coverage tooling is not yet happy with our complex workspace (and maybe the doctests?)

**Comment by Hofer-Julian** [comment]
> Somehow the llvm coverage tooling is not yet happy with our complex workspace (and maybe the doctests?)

Isn't the macOS workflow of nushell flaky in general? Or is it consistently failing?

**Comment by sholderbach** [comment]
> Isn't the macOS workflow of nushell flaky in general? Or is it consistently failing?

While I think your observation is correct that the macOS runners are the worst offenders when it comes to the flaky plugin registration tests, this case seems to be down to some problem with processing the raw data into the `lcov.info` file. And that failure was apparently pretty fast on the mac runners even though they were typically pretty slow. (I saw that `cargo-llvm-cov` stated that doctests are not supported so my last hunch was that I need to disable them explicitly while collecting coverage)

(Another issue to tackle, it seems to try to rebuild most of the test stuff again when following up `cargo build` with `cargo test` even though the flags are pretty similar. And doing a proper rebuild seems required to get tests that depend on the `nu` binary to pass now. Very weird that this was fine before?)

**Comment by sholderbach** [comment]
Let's try it out, it seems to pass the tests and merge the report without an issue (as we observed for the mac runners). Let's have a look how it looks like when we have this on the base `main` branch. We will certainly expend a bit more time but I am curious about how the caching etc. behaves.

**Pull request merged**
