### PR TITLE
Add unit tests for HTTP commands.

### PR DESCRIPTION
**Pull request by jaudiger**
# Description

Following the comment from @fdncred: https://github.com/nushell/nushell/pull/8144#issuecomment-1442514338. I added some unit tests for HTTP commands. The tests are not exhaustive, but at least, this is a first good step IMO.

# User-Facing Changes

None.

# Tests + Formatting

Don't forget to add tests that cover your changes.

Make sure you've run and fixed any issues with these commands:

- `cargo fmt --all -- --check` to check standard code formatting (`cargo fmt --all` applies these changes)
- `cargo clippy --workspace -- -D warnings -D clippy::unwrap_used -A clippy::needless_collect` to check that you're using the standard code style
- `cargo test --workspace` to check that all tests pass

# After Submitting

If your PR had any user-facing changes, update [the documentation](https://github.com/nushell/nushell.github.io) after the PR is merged, if necessary. This will help us keep the docs up to date.

### CODE REVIEW

**Comment by fdncred** [comment]
Looks good to me but we're kind of wondering if there's a lighter weight crate that doesn't include tokio. I realize this is doing a lot here, but we've been trying to trim down our dependencies as much as possible.

**Comment by jaudiger** [comment]
I only know as of today three **maintained** crates to mock an HTTP Server:

- https://github.com/LukeMathWalker/wiremock-rs
- https://github.com/alexliesenfeld/httpmock
- https://github.com/lipanski/mockito

Unfortunately, all of them use tokio internally. I chose `mockito` since it provides a way to write unit tests without having to use async inside the tests. httpmock could also do the trick, here, but I was more familiar with `wiremock-rs` and `mockito`. Regarding not using tokio, does this concern apply for dev dependencies? Not using mocking dependencies is possible, but it'll require to create our stubbing library for HTTP requests. Plus, today those libraries take care to open a free port for the HTTP Server, which then permits to run tests in parallel.

**Comment by rgwood** [comment]
This is very cool, thank you for a big improvement to Nu's tests!

I'm also a little concerned about the size of the dependencies, but I'm not sure I have a better idea.

> Regarding not using tokio, does this concern apply for dev dependencies? 

Yes. My main concerns are 1) compile time 2) disk space. Some context:
1. We currently use `tokio` under the hood for the `http *` commands because it's a dependency of `reqwest`. But we're planning to switch to `ureq`, mostly to remove the `tokio` dependency and improve compile times.
2. Running a full `cargo test` takes up a lot of disk space, we sometimes run into the GitHub Actions disk space limits (especially on Windows)

Maybe we should put these tests behind a feature so we can turn them on/off easily. I'd be OK merging this as-is and adding the feature later (if we need it).

**Comment by rgwood** [comment]
Discussed this on Discord and JT said "imho, I'd prefer to go the route of removing tokio".

I appreciate that this might be an impractical amount of work, but I wonder how difficult it would be to use something like [`tiny-http`](https://github.com/tiny-http/tiny-http) to spin up our own server.

**Comment by jaudiger** [comment]
Writing our mocking HTTP Server is possible. In fact, nothing is impossible, it's just a matter of time.

Basically, if it has to happen, this HTTP Server will need to be spawned in another thread to not block the nu pipeline. Supporting of mocking headers, body, and response code will be required. Checking of client HTTP requests (here Nushell through reqwest) could be optional. In order to run the tests in parallel, a list of opened ports by the HTTP Server will also need to be maintained to open new mocked HTTP Server.

I think I'm missing a few additional things, but, most of the important works are logged. But I don't think I'll have the time to implement this HTTP Server...

IMO re-using an already existing mocking library could help us in the future to mock complex HTTP requests. I'm not sure that implementing our mocking library will provide any user-facing values to Nushell. I thoroughly understand your points to reduce the disk usage in the CI.

What I can propose as for now is just to pause this PR.

**Comment by fdncred** [comment]
@jaudiger Thanks for your work on nushell and this PR in particular. Also, thanks for explaining all this. Sounds like a royal mess to try to do on our own. My vote is to land this PR.

**Comment by rgwood** [comment]
Putting some numbers on this:

- This PR adds 13 crates to a `cargo nextest run --workspace` build (663 -> 676).
- Test execution time seems about the same as before.
- This makes the `target` directory after a `cargo nextest run --workspace` run about 200mb bigger (9.8GB -> 10.0GB).
  - If I drop the `reqwest` dependency and the `http` commands, it's 9.2GB... so ~600MB is a rough upper limit for the amount of disk space used by Tokio and friends
  
I think I'm OK with this PR as a first step. Hopefully it isn't the straw that breaks the camel's back; we're already bumping up against disk space limits sometimes.

**Comment by rgwood** [comment]
Let's try it out. Thanks @jaudiger!

**Comment by jaudiger** [comment]
You’re welcome! If it needs to be further discuss or if there is a problem with the CI due to the disk usage, please ping me ! A quick question : is there any issue for the migration to ureq? And is there a person in charge of the work?

**Comment by rgwood** [comment]
Don't think we have an issue for the `reqwest` -> `ureq` migration. @FilipAndersson245 gave it a try last year and we (probably prematurely) closed the PR: https://github.com/nushell/nushell/pull/6985

@FilipAndersson245 has said he's going to try to submit another PR for it but I don't think he's mentioned a timeline.

**Comment by FilipAndersson245** [comment]
> Don't think we have an issue for the `reqwest` -> `ureq` migration. @FilipAndersson245 gave it a try last year and we (probably prematurely) closed the PR: https://github.com/nushell/nushell/pull/6985
> 
> @FilipAndersson245 has said he's going to try to submit another PR for it but I don't think he's mentioned a timeline.

I have had alot of work recently but I hope to work on it this weekend.

**Comment by jaudiger** [comment]
Thanks @FilipAndersson245 if you can work on it! Let me know if you need any help on this task. I saw your previous PR, and was wondering if there was a way to keep the insecure flag. Anyway, don’t hesitate to ping me once you open the new PR. I would be happy to give you some feedbacks and see if we can overcome possible limitations !

**Pull request merged**
