### PR TITLE
Refactoring nu_table

### LINKED ISSUE #5972: `tabled` seems about 10x slower than before
### Describe the bug

After merging https://github.com/nushell/nushell/pull/5969 I'm seeing about 10x performance drop.

### How to reproduce

```
> 1..100000
...
 99997    99998
 99998    99999
 99999   100000

> $env.CMD_DURATION_MS
3795
```

On my machine, before the PR, it takes about 350 ms. After the PR it takes 3.7 s.

### Expected behavior

Ideally, the performance difference wouldn't be so big. Rendering this big data is not useful but it can happen by accident and then you need to wait.

### Screenshots

_No response_

### Configuration

| key                | value                                           |
| ------------------ | ----------------------------------------------- |
| version            | 0.65.1                                          |
| branch             |                                                 |
| commit_hash        | d1687df0678ec55241031860e6f7132dec3f2503        |
| build_os           | linux-x86_64                                    |
| build_target       | x86_64-unknown-linux-gnu                        |
| rust_version       | rustc 1.62.0 (a8314ef7d 2022-06-27)             |
| rust_channel       | stable-x86_64-unknown-linux-gnu                 |
| cargo_version      | cargo 1.62.0 (a748cf5a3 2022-06-08)             |
| pkg_version        | 0.65.1                                          |
| build_time         | 2022-07-06 23:11:48 +03:00                      |
| build_rust_channel | release                                         |
| features           | database, dataframe, default, trash, which, zip |
| installed_plugins  | gstat                                           |

### Additional context

I'm using the `light` table mode.

### PR DESCRIPTION
**Pull request by zhiburt**
close #5972

### CODE REVIEW

**Comment by zhiburt** [comment]
I see 1 thing; don't merge yet.

**Comment by fdncred** [comment]
ok, i'll mark as draft. let me know when you're ready.

**Comment by fdncred** [comment]
after testing this, i think i'll be ready to land whenever you're done making changes.

**Comment by fdncred** [comment]
@zhiburt looks like we're all green. ready to land it?

**Pull request merged**
