### PR TITLE
Add indent flag to `to json` (first draft)

### PR DESCRIPTION
**Pull request by JosephTLyons**
# Description

This is just a draft.  Things left to do:

- [X] Handle allocation crash when supplying a negative number - fixed via https://github.com/nushell/nushell/pull/4570
- [ ] Generate documentation
- [X] Add examples
- [X] Add a test or two
- [X] ~Discuss the best way to get the indentation value down into the generic functions that do the actual indentating of the json.  I had two options for passing it down: Altering all of the functions to take in an indent parameter, or duplicating them with `_with_indent` variations.  I chose the second, but I don't feel either of these are good solutions.  Let me know if there's a 3rd, better solution, that I missed.~ I'll now with this for now  
# Tests

Make sure you've run and fixed any issues with these commands:

- [X] `cargo fmt --all -- --check` to check standard code formatting (`cargo fmt --all` applies these changes)
- [X] `cargo clippy --all --all-features -- -D warnings -D clippy::unwrap_used -A clippy::needless_collect` to check that you're using the standard code style
- [X] `cargo build; cargo test --all --all-features` to check that all the tests pass

### CODE REVIEW

**Comment by fdncred** [comment]
it doesn't hurt my feelings to have a few `_with_indent` functions like these.

**Comment by JosephTLyons** [comment]
I'm not able to run the documentation generation command, so I haven't been able to complete that

**Comment by fdncred** [comment]
thanks!

**Comment by JosephTLyons** [comment]
> it's great having you back contributing again!

Thanks for the kind words :).  I've always liked this project; I'll see what I can do about shooting some PRs out on a more regular basis.

**Pull request merged**
