### PR TITLE
Echo RangeIterator can also go down

### PR DESCRIPTION
**Pull request by gillespiecd**
1. I was looking into this `TODO` and think it may be already handled, added some unit tests to confirm.
1. Also updated RangeIterator to go down if the range goes down

### CODE REVIEW

**Comment by jonathandturner** [comment]
Should we just iterate backwards in that case?

**Comment by fdncred** [comment]
We also talked about adding a range by similar to `seq` like `echo 1..10by2` so it could count to 10 by 2's starting at 1. That's not the syntax anyone agreed to. I just made it up. seq actually does the same thing with `seq 1 2 10`. Not saying we have to do this here - just throwing it out there. And i'd definitlely like `5..1` to count backwards.

**Comment by gillespiecd** [comment]
Counting backwards is a good idea for ranges like `5..2`, I can work on updating this PR to include that approach.

**Comment by gillespiecd** [comment]
Updated to go downwards if applicable:

```
> echo 5..1
───┬───
 0 │ 5
 1 │ 4
 2 │ 3
 3 │ 2
 4 │ 1
───┴───
> echo 5..<1
───┬───
 0 │ 5
 1 │ 4
 2 │ 3
 3 │ 2
 ```

**Comment by fdncred** [comment]
Cool! Thanks. Any ideas about syntax of how to make it count by X. Like, count by 2s or 5s or whatever?

I guess we could add a `--by` parameter. Not sure what is right.

**Comment by jonathandturner** [comment]
Looks good!

@fdncred not sure if strides fit in the syntax, but maybe? For folks who want to skip rows, there are commands like: `echo 1..10 | each group 2 { echo $it.0 }` (which we might alias or something for a standard library).

**Comment by fdncred** [comment]
@jonathandturner I still think we should do `echo 1..2..10` for `by X`. Just my opinion. I think `each group` is clumsy on more difficult. But not everyone thinks like me (thank the good Lord). :)

**Pull request merged**
