### PR TITLE
support bracketed paste

### PR DESCRIPTION
**Pull request by WindSoilder**
# Description

Relative: #8113, #7630
It works on non-windows system

This pr depends on https://github.com/nushell/reedline/pull/571

# User-Facing Changes

# Tests + Formatting

# After Submitting

### CODE REVIEW

**Comment by fdncred** [comment]
Do you think we should have a config point to use bracketed paste? Seems like most shells have an option to turn it on or off.

**Comment by fdncred** [comment]
When I copy and paste this:
```
def a [] {
	echo
	echo
}
```
I get this
image

Which is the same as before this PR

**Comment by WindSoilder** [comment]
It's strange...I can't reproduce it on Mac..
图片

**Comment by sholderbach** [comment]
> I get this: image
> 
> Which is the same as before this PR.

My hunch is that this is a `CRLF` issue as you are reporting on Windows

**Comment by fdncred** [comment]
That's really weird @WindSoilder. You'll notice in my prompt that I'm on Windows (the little logo). I'm beginning to wonder if this is a line ending problem since MacOS and Windows have different line endings?

**Comment by WindSoilder** [comment]
Oh, I found a relative issue in crossterm...https://github.com/crossterm-rs/crossterm/issues/737

**Comment by WindSoilder** [comment]
> Do you think we should have a config point to use bracketed paste? Seems like most shells have an option to turn it on or off.

Back to the question, I think it's a good default behavior, but yeah I agree that we can make it confirable

**Comment by fdncred** [comment]
@amtoine That's odd. I thought modern macos and linux had the same line endings? Sounds like we need to experiment a bit on win/mac(working)/linux.

**Comment by WindSoilder** [comment]
Hi, @amtoine Would you please test it again?

**Comment by amtoine** [comment]
@WindSoilder ...

it's ALL GONE :partying_face: 

and that now works with `|` at the start of lines :scream: 
e.g. with
```
ls
| find 4
| get name
```
this is truely amazing :heart:

**Review by amtoine — APPROVED** [review]
and such a simple change? really?

that's very cool :smirk: 

EDIT: and it breaks when setting `bracketed_paste` to `false` :ok_hand:

**Comment by sholderbach** [comment]
Let's give it a try!

Thanks for working on this @WindSoilder

**Pull request merged**
