### PR TITLE
fix panic caused by `ls \\.\pipe`

### PR DESCRIPTION
**Pull request by davehorner**
wrap chrono in panic hooks to handle panic'ing unwraps on Jan 1, 1601 00:00 UTC and other reasons unknown. An overflow if time_u64 is smaller than EPOCH_AS_FILETIME has been wrapped.

Further discussion
https://github.com/nushell/nushell/issues/10464

There are two issues that are associated with Chrono.  I did not test.  It may not relate, but it could.
thread 'main' panicked at 'SystemTimeToFileTime failed with: The parameter is incorrect.
https://github.com/nushell/nushell/issues/6574
https://github.com/nushell/nushell/issues/9470

# Description

I'm not a fan of this code that was pulled from chrono.  negative seconds and nano seconds? 
```rust
    // Adapted from https://github.com/chronotope/chrono/blob/v0.4.19/src/datetime.rs#L755-L767.
    let (sec, nsec, was_success) = match t.duration_since(UNIX_EPOCH) {
        Ok(dur) => {
            (dur.as_secs() as i64, dur.subsec_nanos(),true)
        },
        Err(e) => {
            // unlikely but should be handled
            let dur = e.duration();
            let (sec, nsec) = (dur.as_secs() as i64, dur.subsec_nanos());
            if nsec == 0 {
                (-sec, 0,false)
            } else {
                (-sec - 1, 1_000_000_000 - nsec,false)
            }
        }
    };
```

There's more on the #10464 ticket;

# User-Facing Changes

Use ls and it will not crash when listing windows pipes 
ls \\.\pipe.

# Tests + Formatting

- `cargo fmt --all -- --check` to check standard code formatting (`cargo fmt --all` applies these changes)
DONE

- `cargo clippy --workspace -- -D warnings -D clippy::unwrap_used` to check that you're using the standard code style
that command yields:

```rust
error: casting raw pointers to the same type and constness is unnecessary (`*mut u16` -> `*mut u16`)
   --> crates\nu-system\src\windows.rs:972:13
    |
972 |             name.as_mut_ptr() as *mut u16,
    |             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ help: try: `name.as_mut_ptr()`
    |
    = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#unnecessary_cast
    = note: `-D clippy::unnecessary-cast` implied by `-D warnings`
    = help: to override `-D warnings` add `#[allow(clippy::unnecessary_cast)]`

error: casting raw pointers to the same type and constness is unnecessary (`*mut u16` -> `*mut u16`)
   --> crates\nu-system\src\windows.rs:974:13
    |
974 |             domainname.as_mut_ptr() as *mut u16,
    |             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ help: try: `domainname.as_mut_ptr()`
    |
    = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#unnecessary_cast

error: could not compile `nu-system` (lib) due to 2 previous errors
```

TBD
- `cargo test --workspace` to check that all tests pass (on Windows make sure to [enable developer mode](https://learn.microsoft.com/en-us/windows/apps/get-started/developer-mode-features-and-debugging))
- `cargo run -- -c "use std testing; testing run-tests --path crates/nu-std"` to run the tests for the standard library

### CODE REVIEW

**Comment by davehorner** [comment]
I'd propose that we drop "It may have an illegal filename" from the error messages. If I had my preference I'd remove the entire "Failed to read metadata for" error message.

**Comment by amtoine** [comment]
@davehorner 
to link this to issues properly, should this PR solve https://github.com/nushell/nushell/issues/10464, https://github.com/nushell/nushell/issues/6574 and https://github.com/nushell/nushell/issues/9470? :yum:

**Comment by kubouch** [comment]
I'd say that even a non-ideal fix is better than panicking, so I'd support wrapping the panic hooks like this, but we should look for better solutions how to handle the panicking crate.

**Comment by davehorner** [comment]
@kubouch I opened a ticket upstream.  https://github.com/chronotope/chrono/issues/1364 there are 124 issues outstanding on that crate.

Seems the only way is to find and localize the unwraps and placing them in panic hooks.  if there is a better way aside a new try interface from the crates, I'm interested.

I'd like some support for removing the output error "Failed to read metadata for".  There's more to fix to make this right.

**Comment by WindSoilder** [comment]
Thanks for your contribution!
I found there is some progress on chrono issue, maybe we need to hold on, and wait to see how it goes?

**Comment by davehorner** [comment]
I think wrapping the library in panic hooks works well and I'm not sure why the project hasn't taken the contribution to reduce crashes today.  I will continue to work with the upstream project...

**Comment by WindSoilder** [comment]
Sorry that we only get limited time to do all things.

I think it's good to add a TODO comment about we won't need `was_success` variable, and we don't need to set hook under `unix_time_to_local_date_time` function once the issue is solved: https://github.com/chronotope/chrono/issues/1364 ?

**Comment by fdncred** [comment]
maybe we should rebase and land this as a not-ideal fix but better than a panic, like @kubouch said?

it reared it's ugly head again here https://github.com/nushell/nushell/issues/11563

**Comment by davehorner** [comment]
I haven't had time to provide a better solution.  I'd suggest it be merged to stop the additional panics for everyone.

**Comment by fdncred** [comment]
@davehorner would you main rebasing on main? I'm hesitant to land such an old pr for fears it could hork other things.

**Comment by kubouch** [comment]
I remember @sophiajt has strong objections.

I'm also a bit cautious because `ls` is one of the most used commands, and we'd be doing this panic hook thing for every path reported by the command, we don't want to ruin performance. It would be good to measure the performance impact, and not just `ls`-ing in the current directory, but trying to `ls **/*` in some deeper structure with thousands of files.

**Comment by fdncred** [comment]
This is a benchmark using std bench and my nushell folder which currently has 64550 files in it

nushell main
```nushell
❯ bench { ls **/* } -n 10 --pretty
274ms 365µs 820ns +/- 22ms 422µs 912ns
```

this pr
```nushell
❯ bench { ls **/* } -n 10 --pretty
261ms 308µs 876ns +/- 16ms 258µs 526ns
```

**Comment by davehorner** [comment]
Someone suggested a test be written.  I think that's a good idea and I'm willing to learn how to do that.
Isn't there a test someone can point to me for ls that could be modified to call the special path on windows?

it's slower by some measure.   it stops the panic'ing.

I'll work on getting a better fix; I stopped working on this because I felt it was being ignored.

**Comment by kubouch** [comment]
If I understand it correctly, there are three sources of panic:
1. timestamp pointing to the year 1601
2. panics on Windows for unknown reasons?
3. time less than UNIX_EPOCH

To address these, we can:
1. filter out nonsensical timestamps
2. If I read your message correctly, has been fixed but not yet released? Maybe we can just wait for a chrono release.
3. already fixed by `wrapping_sub()` (shouldn't it be saturating subtraction instead?)

Seems like the runtime penalty is not too bad, but measurable. I still have reservations because I fear that if we merge it in, we'd never get to fix it properly later. Hiding it behind a panic hook would also prevent us from diagnosing the problem properly.

**Comment by ChrisDenton** [comment]
The problem with 1600 is ultimately a chrono bug (well arguably an OS bug that chrono needs to avoid) and should be fixed there. A workaround in nushell may possibly make sense as a temporary measure but isn't really a solution.

**Comment by kubouch** [comment]
Agreed, it should ultimately be fixed in chrono. In the meanwhile, filtering out nonsensical timestamps seems to me like a less invasive solution than swapping a panic hook for every timestamp encountered.

**Comment by fdncred** [comment]
@davehorner do you have time to look at the code and see if we can intercept the call before chrono gets it and pass in a better date? We'd love to have this fixed but we really would rather not do it with a panic hook if possible.

**Comment by davehorner** [comment]
the biggest problem i have is that the fields of SystemTime are private and I haven't come up with a way to filter.
println line provides: "SystemTime Components: SystemTime { intervals: 0 }"

there is no intervals field.  this confuses me.
```
    if(t.0.dwLowDateTime==0 && t.0.dwHighDateTime==0) {
        println!("SystemTime Components: {:?}", t);
        return None;
    }
```
I can't do this or even compare the whole structure to zero.

@kubouch mentioned the wrapping/staturating sub.
```
+        if time_u64>0 {
+            let rel_to_linux_epoch = time_u64 - EPOCH_AS_FILETIME;
+            let seconds_since_unix_epoch = rel_to_linux_epoch / HUNDREDS_OF_NANOSECONDS;    
+            return seconds_since_unix_epoch as i64
+        }
+        return 0
```
saturating might be fine and better than wrapping, the above would also be a solution.

**Comment by fdncred** [comment]
> should I update the ls_pipes_nushell branch to include these two small checks or create another PR?

whatever is easiest for you is fine. thanks for digging in.

**Comment by davehorner** [comment]
test

**Comment by davehorner** [comment]
Ok, I think I have a clean merge for you.
The negative number check could be a <0 check, but the negative constant works.

the new use num_traits::ToPrimitive; maybe something that can be deleted.  that was added by my editor i think.

**Comment by davehorner** [comment]
should pass checks now, <0 instead of constant applied.

**Comment by fdncred** [comment]
No crashes (yay!) but I'm not sure what this `Filed to read metadata` is. It doesn't look like a nushell error.
image

**Comment by fdncred** [comment]
Ah, I see it round line 685 in ls.rs. Hmmmm, not sure what to do about that if anything. Maybe something for a separate PR?

**Comment by davehorner** [comment]
idk, i go back and forth on the constant.  i may have just introduced an issue with dropping the constant and using <0.  it might be nice to use UNIX_EPOCH constant somewhere.

yes, that is the output I was talking about that should also go away.  that line comes from nushell and i thought I had pointers to it somewhere.  I'd be very happy to see that go away.

**Comment by fdncred** [comment]
Quite a bit of data looks ok, even though type, size, and modified are null.
image

**Comment by davehorner** [comment]
```
                // Sometimes this happens when the file name is not allowed on Windows (ex: ends with a '.')
                // For now, we just log it and give up on returning metadata columns
                // TODO: find another way to get this data (like cmd.exe, pwsh, and MINGW bash can)
                eprintln!(
                    "Failed to read metadata for '{}'. It may have an illegal filename",
                    filename.to_string_lossy()
                );
                log::error!("{e}");
```
drop the eprintln! all together. log::error too?

**Comment by fdncred** [comment]
Can you just comment this line out?
```rust
                eprintln!(
                    "Failed to read metadata for '{}'. It may have an illegal filename",
                    filename.to_string_lossy()
                );
```
and let's leave the `log` because that at least has a way to show what's going on.

I looked up some of the odd things and they're in the table, just without metadata. So, I think that's fine.

**Comment by davehorner** [comment]
i might make a suggestion to prefix the error with ls: 

sometimes getting the error string in the log file isn't helpful without a string to search for...

**Comment by fdncred** [comment]
I'm fine with making the error for the log more verbose if you want.

**Comment by fdncred** [comment]
was looking into alternate solutions and eza prints some information but not a lot.
image

**Comment by fdncred** [comment]
For historical purposes, powershell has no issues.
```
powershell
PS D:\nushell> Get-ChildItem \\.\pipe\


    Directory: \\.\pipe


Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
------        12/31/1600   6:00 PM              3 InitShutdown
------        12/31/1600   6:00 PM              5 lsass
------        12/31/1600   6:00 PM              3 ntsvcs

    Directory: \\.\pipe\LOCAL


Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
------        12/31/1600   6:00 PM              1 LOCAL\mojo.11340.15444.4090602839680163276
------        12/31/1600   6:00 PM              1 LOCAL\mojo.11340.15444.14862362133246965441
------        12/31/1600   6:00 PM              1 LOCAL\mojo.11340.15444.11463863991970289318
------        12/31/1600   6:00 PM              1 LOCAL\mojo.11340.15444.15622337728438899958
------        12/31/1600   6:00 PM              1 LOCAL\mojo.11340.15444.11756385997212485992
------        12/31/1600   6:00 PM              1 LOCAL\mojo.11340.15444.12777297401725170811
------        12/31/1600   6:00 PM              1 LOCAL\mojo.11340.15444.4063517427843339707
------        12/31/1600   6:00 PM              1 LOCAL\mojo.11340.15444.16112101256037885828
------        12/31/1600   6:00 PM              1 LOCAL\mojo.11340.15364.12403398334436138072
------        12/31/1600   6:00 PM              1 LOCAL\mojo.11340.15364.13792981662838343295
------        12/31/1600   6:00 PM              1 LOCAL\mojo.11340.15364.11535807849936101644
------        12/31/1600   6:00 PM              1 LOCAL\mojo.11340.15364.11440703132112103960
------        12/31/1600   6:00 PM              1 LOCAL\mojo.11340.15364.1302607518981618574
------        12/31/1600   6:00 PM              1 LOCAL\mojo.11340.15364.4318871563243086101
------        12/31/1600   6:00 PM              1 LOCAL\mojo.11340.15364.8579818736073960470

... and many more
```

**Comment by davehorner** [comment]
I'm a fan of seeing a clean ls of pipes like that of powershell.  Path and error string like exa is ok too.

**Comment by fdncred** [comment]
I'm sure there's some microsoft magic in powershell & pwsh to show this information. i wonder what it looks like in their repo or if i could even find it in there?

**Comment by fdncred** [comment]
Let's move forward with this the way it is now. Thanks @davehorner!!

**Comment by davehorner** [comment]
If I had to do it over again, I'd use the constant and not <0.  I fear I might have affected dates that are prior to epoch which are negative and should not return 0;

**Comment by fdncred** [comment]
> @fdncred If I had to do it over again, I'd use the constant and not <0. I fear I might have affected dates that are prior to epoch which are negative and should not return 0;

if you think that's safer, submit a PR and i'll look at it.

**Comment by kubouch** [comment]
Wow, great job! Thanks a lot for the persistence, @davehorner !

There are some commented out eprintln lines that can be removed, not a big deal.

**Pull request merged**
