### PR TITLE
FEATURE: add the startup time to `$nu`

### PR DESCRIPTION
**Pull request by amtoine**
# Description
in https://github.com/nushell/nushell/issues/8311 and the discord server, the idea of moving the default banner from the `rust` source to the `nushell` standar library has emerged :yum: 

however, in order to do this, one need to have access to all the variables used in the default banner => all of them are accessible because known constants, except for the startup time of the shell, which is not anywhere in the shell...

## the changes
in order to achieve this, i had to
- add `startup_time` as an `i64` to the `EngineState` => this is, to the best of my knowledge, the easiest way to pass such an information around down to where the banner startup time is computed and where the `$nu` variable is evaluated
- add `startup-time` to the `$nu` variable and use the `EngineState` getter for `startup_time` to show it as a `Value::Duration`
- pass `engine_state` as a `&mut`able argument from `main.rs` down to `repl.rs` to allow the setter to change the value of `startup_time` => without this, the value would not change and would show `-1ns` as the default value...
- the value of the startup time is computed in `evaluate_repl` in `repl.rs`, only once at the beginning, and the same value is used in the default banner :ok_hand: 

# User-Facing Changes
one can now access to the same time as shown in the default banner with
```bash
$nu.startup-time
```

# Tests + Formatting
- :green_circle: `cargo fmt --all`
- :green_circle: `cargo clippy --workspace -- -D warnings -D clippy::unwrap_used -A clippy::needless_collect`
- :green_circle: `cargo test --workspace`

# After Submitting
```
$nothing
```

### CODE REVIEW

**Comment by amtoine** [comment]
this is the script i talk about :yum: 
and it needs the startup time to be an exact clone of the default banner of course :thinking: 
this is a very first pure-clone draft and it would have to be augmented, but that's the gist of it :relieved: 

```rust
def banner [] {
$"(ansi green)     __  ,(ansi reset)
(ansi green) .--\(\)°'.' (ansi reset)Welcome to (ansi green)Nushell(ansi reset),
(ansi green)'|, . ,'   (ansi reset)based on the (ansi green)nu(ansi reset) language,
(ansi green) !_-\(_\\    (ansi reset)where all data is structured!

Please join our (ansi purple)Discord(ansi reset) community at (ansi purple)https://discord.gg/NtAbbGn(ansi reset)
Our (ansi green_bold)GitHub(ansi reset) repository is at (ansi green_bold)https://github.com/nushell/nushell(ansi reset)
Our (ansi green)Documentation(ansi reset) is located at (ansi green)https://nushell.sh(ansi reset)
(ansi cyan)Tweet(ansi reset) us at (ansi cyan_bold)@nu_shell(ansi reset)
Learn how to remove this at: (ansi green)https://nushell.sh/book/configuration.html#remove-welcome-message(ansi reset)

It's been this long since (ansi green)Nushell(ansi reset)'s first commit:
((date now) - ('2019-05-10 09:59:12-0700' | into datetime))

Startup Time: ($nu.startup-time)"
}
```

**Comment by fdncred** [comment]
@amtoine There are some small fixes that need to happen so the CI goes green. Do you have time for those?

**Comment by amtoine** [comment]
> @amtoine There are some small fixes that need to happen so the CI goes green. Do you have time for those?
>
ooh i did not see the conflicts!
let me fix those :ok_hand:

**Comment by amtoine** [comment]
okey it finally did compile, i can have a look at the issue :+1:

**Comment by amtoine** [comment]
i think this might be solved with 09ebf47 :thinking:

**Comment by amtoine** [comment]
yeah :partying_face:

**Comment by fdncred** [comment]
Thanks!

**Comment by amtoine** [comment]
> Thanks!
>
:+1:

**Pull request merged**
