### PR TITLE
nu-table/ Add `table.indent` configuration

### PR DESCRIPTION
**Pull request by zhiburt**
Hi there.

Am I got it right?

ref: https://github.com/zhiburt/tabled/issues/358
cc: @fdncred

### CODE REVIEW

**Comment by jntrnr** [comment]
@zhiburt can you add a screenshot to make it easier for folks to take a look?

**Comment by fdncred** [comment]
@zhiburt Looking great!
image

**Comment by fdncred** [comment]
@zhiburt I can't seem to break it. I think it looks good but can you rename `indent` to `padding`?

**Comment by hustcer** [comment]
If we rename it to `padding` then can we padding top and bottom? If not I prefer `indent`

**Comment by fdncred** [comment]
I'm not sure about top and bottom padding. That would mean each row takes more than one row.

**Review by amtoine — DISMISSED** [review]
i think this is kinda cool, will allow people with small screen to have more useful info from Nushell :partying_face: 

can we just add this to `default_config.nu` once the name of the config has settled down? :yum: 
e.g. currently it would be
```nushell
$env.config.table.indent = {left: 1, right: 1}
```
or
```nushell
$env.config.table.indent = 1
```
as the default value

**Comment by zhiburt** [comment]
> can we just add this to `default_config.nu`

fixed

https://github.com/nushell/nushell/blob/7a69b840fbb38436550c594b92883ded985b6abe/crates/nu-utils/src/sample_config/default_config.nu#L161



> with `padding`

renamed

**Comment by fdncred** [comment]
Thanks @zhiburt. Appreciate all your support.

**Pull request merged**
