### PR TITLE
Fix ls panics when a file or directory not exists

### LINKED ISSUE #6146: ls panics when a file or directory not exists
### Describe the bug

list a file or directory which not exists, ls panics

### How to reproduce

1. ls /a_file_or_directory_not_exists

### Expected behavior

ls should not panic

### Screenshots

_No response_

### Configuration

| key                | val                                      |
| ------------------ | ---------------------------------------- |
| version            | 0.66.1                                   |
| branch             |                                          |
| commit_hash        | 4d6426beab6d57d75c7009c464695f78f49f9d71 |
| build_os           | linux-x86_64                             |
| build_target       | x86_64-unknown-linux-gnu                 |
| rust_version       | rustc 1.62.1 (gentoo)                    |
| cargo_version      | cargo 1.62.1                             |
| pkg_version        | 0.66.1                                   |
| build_time         | 2022-07-27 05:42:04 +00:00               |
| build_rust_channel | release                                  |
| features           | default, trash, which, zip               |
| installed_plugins  |                                          |

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by nibon7**
# Description

Fixes #6146

# Tests

Make sure you've done the following:

- [ ] Add tests that cover your changes, either in the command examples, the crate/tests folder, or in the /tests folder.
- [ ] Try to think about corner cases and various ways how your changes could break. Cover them with tests.
- [ ] If adding tests is not possible, please document in the PR body a minimal example with steps on how to reproduce so one can verify your change works.

Make sure you've run and fixed any issues with these commands:

- [x] `cargo fmt --all -- --check` to check standard code formatting (`cargo fmt --all` applies these changes)
- [x] `cargo clippy --workspace --features=extra -- -D warnings -D clippy::unwrap_used -A clippy::needless_collect` to check that you're using the standard code style
- [x] `cargo test --workspace --features=extra` to check that all the tests pass

### CODE REVIEW

**Comment by kubouch** [comment]
Thanks, this is an important fix. Could you please add a test for it to prevent this in the future?

**Comment by kubouch** [comment]
Also, I think we should throw an error if the path is not found. Seems like your solution would return an empty result. This should also be covered by a test.

**Comment by nibon7** [comment]
> Thanks, this is an important fix. Could you please add a test for it to prevent this in the future?

I'll add it later.

**Comment by nibon7** [comment]
> Also, I think we should return an error if the path is not found. Seems like your solution would return an empty result. This should also be covered by a test.

The error was pushed into shell_errors and it will be returned.

https://github.com/nushell/nushell/blob/b67fe31544483fcbbae1948fedebd22c311cc781/crates/nu-command/src/filesystem/ls.rs#L392-L394

**Comment by kubouch** [comment]
> > Also, I think we should return an error if the path is not found. Seems like your solution would return an empty result. This should also be covered by a test.
> 
> The error was pushed into shell_errors and it will be returned.
> 
> https://github.com/nushell/nushell/blob/b67fe31544483fcbbae1948fedebd22c311cc781/crates/nu-command/src/filesystem/ls.rs#L392-L394

On this line https://github.com/nushell/nushell/pull/6148/files#diff-52d84ef0558fd4948723cbae739ecea22351dba0965d24ab3d6862181f309f44R154 it seems you're returning early with an empty result.

**Comment by nibon7** [comment]
> On this line https://github.com/nushell/nushell/pull/6148/files#diff-52d84ef0558fd4948723cbae739ecea22351dba0965d24ab3d6862181f309f44R154 it seems you're returning early with an empty result.

It's in a closure and seems can't return error early. After returning Iterator, it checks `shell_errors` immediately and return error.

**Comment by kubouch** [comment]
OK, that makes sense, I didn't notice the closure. Can I merge it or do you plan to add more tests?

**Pull request merged**
