### PR TITLE
Initial implementation for uutils uname

### PR DESCRIPTION
**Pull request by dmatos2012**
Hi,
This PR aims at implementing the first iteration for `uname` using `uutils`. Couple of things:
* Currently my [PR](https://github.com/uutils/coreutils/pull/5921) to make the required changes is pending in `uutils` repo.
* I guess the number of flags has to be investigated. Still the tests cover all of them. 

# Description

# User-Facing Changes

# Tests + Formatting
Don't forget to add tests that cover your changes.

Make sure you've run and fixed any issues with these commands:

- [X] `cargo fmt --all -- --check` to check standard code formatting (`cargo fmt --all` applies these changes)
- [X] `cargo clippy --workspace -- -D warnings -D clippy::unwrap_used` to check that you're using the standard code style
- [X] `cargo test --workspace` to check that all tests pass (on Windows make sure to [enable developer mode](https://learn.microsoft.com/en-us/windows/apps/get-started/developer-mode-features-and-debugging))
- [X] `cargo run -- -c "use std testing; testing run-tests --path crates/nu-std"` to run the tests for the standard library

> **Note**
> from `nushell` you can also use the `toolkit` as follows
> ```bash
> use toolkit.nu  # or use an `env_change` hook to activate it automatically
> toolkit check pr
> ```
-->

# After Submitting

### CODE REVIEW

**Comment by fdncred** [comment]
I'm wondering if uuname can just return the data instead of printing it out? It would be great to have something closer to $nu.os-info.
```nushell

**Comment by dmatos2012** [comment]
> Thanks @dmatos2012 for another great PR!
> 
> I'm wondering if uuname can just return the data instead of printing it out? It would be great to have something closer to $nu.os-info.
> 
> ```nushell
> ❯ $nu.os-info
> ╭────────────────┬─────────╮
> │ name           │ windows │
> │ arch           │ x86_64  │
> │ family         │ windows │
> │ kernel_version │ 22631   │
> ╰────────────────┴─────────╯
> ```

Thought about something similar as well to the output of `ls` , but wasnt exactly sure if thats something we wanted it.

However, with your suggestion, it means there would be only one way of using it: namely `uname`, which will print out all the flags as record as you pointed out. i really like it, since it avoids the mess of all the `-n, -p,-i`. Will give it a try :)

**Comment by fdncred** [comment]
ya, i think it would be more nushell-y just to print out a record if we can get the information.

**Comment by fdncred** [comment]
Not quite right but looking better.
```
❯ uname 
╭──────────────────┬─────────────────────────╮
│ kernel-name      │ Windows_NT              │
│ nodename         │ MYHOSTNAME              │
│ kernel-release   │ 10.0                    │
│ kernel-version   │ 22631 x86_64 MS/Windows │
│ machine          │ (Windows                │
│ operating-system │ 11)                     │
╰──────────────────┴─────────────────────────╯
```

**Comment by dmatos2012** [comment]
Much better now :) 
image

Please check this and the `uutils` PR and let me know what you think. I realized that trying to parse the long string was no good because probably every system will output in a different way so we needed a more structured output from `uutils`. 

As far as testing goes, given that we have no flags now, I think we will have to rely on their test harness at least for now.

**Comment by fdncred** [comment]
Looks good on my windows box. I'll try to test it on mac later.
```
❯ uname
╭──────────────────┬─────────────────────────╮
│ kernel-name      │ Windows_NT              │
│ nodename         │ MYHOSTNAME              │
│ kernel-release   │ 10.0                    │
│ kernel-version   │ 22631                   │
│ machine          │ x86_64                  │
│ operating-system │ MS/Windows (Windows 11) │
╰──────────────────┴─────────────────────────╯
```

**Comment by fdncred** [comment]
This is what my mac says. Long kernel-version, not saying that's bad, was just surprised.
```
❯ uname
╭──────────────────┬───────────────────────────────────────────────────────────────────────────────────────────────────────╮
│ kernel-name      │ Darwin                                                                                                │
│ nodename         │ M1X.local                                                                                             │
│ kernel-release   │ 23.3.0                                                                                                │
│ kernel-version   │ Darwin Kernel Version 23.3.0: Wed Dec 20 21:30:44 PST 2023; root:xnu-10002.81.5~7/RELEASE_ARM64_T6000 │
│ machine          │ arm64                                                                                                 │
│ operating-system │ Darwin                                                                                                │
╰──────────────────┴───────────────────────────────────────────────────────────────────────────────────────────────────────╯
```

**Comment by fdncred** [comment]
I guess we're just waiting for the core-utils release. Is that correct?

**Comment by dmatos2012** [comment]
> I guess we're just waiting for the core-utils release. Is that correct?

Yes, technically we are waiting for it to be merged first, and then the release, but aside from that everything should be ready.

**Comment by fdncred** [comment]
yay! one step closer.

**Comment by dmatos2012** [comment]
yeah I think I somehow messed up the branch but should be fixed now @fdncred. So maybe time to take it for a ride and wait for the release of `uutils`. Looking forward for this getting released :)

**Comment by fdncred** [comment]
I guess we're still waiting for a coreutils release? @tertsdiepraam is there a coreutils release in our future? 🤣

**Comment by tertsdiepraam** [comment]
🔮👀

My cristal ball says.... yes, should be fairly soon

**Comment by AndreiSva** [comment]
Will this replace `$env.os-info`?

**Comment by fdncred** [comment]
> Will this replace `$env.os-info`?

no. $nu.os-info is a compile time variable that we plan on keeping. it's helpful because it's super fast.

**Comment by fdncred** [comment]
yay, looks like coreutils 0.25 has been released

**Comment by dmatos2012** [comment]
I think this should be ready to go now @fdncred ?  The diff probably looks weird as I noticed all of the `Cargo.toml` were changed lol, but think should be good now :)

**Comment by fdncred** [comment]
I'd like to keep all uu_* crates on the same version so I changed them all to 0.0.25. I think bad things may happen if we mix and match versions.

**Comment by fdncred** [comment]
No clue what this means
image

**Comment by sholderbach** [comment]
The `Cargo.lock` just needs to be commited as well after the version bump. This check is aimed to catch bad tests or out of date `Cargo.lock`

**Comment by fdncred** [comment]
Thanks again @dmatos2012!!

**Pull request merged**
