### PR TITLE
[DRAFT] Check fix for emojie, wrap issues

### LINKED ISSUE #12786: `table` produces subtraction overflow
### Describe the bug

@zhiburt While troubleshooting my `emoji` plugin, I noticed that it hangs if `skin_tones` column is shown.

## Alternate Repro
devyn just figured out we could reproduce the error with `emoji --list | select emoji name skin_tones | save emoji.json` and then try to `open emoji.json` and you get the same error.
[emoji.json](https://github.com/nushell/nushell/files/15227358/emoji.json)

## Original Repro (harder to do)
1. Build nushell
2. Build nu_plugin_emoji https://github.com/fdncred/nu_plugin_emoji
3. in nushell do `plugin add /path/to/nu_plugin_emoji
4. quit out of nushell and start it back up again
5. now you can do `emoji :smirk:` and see that it works
6. now try `emoji --list`, if your terminal window is small and not showing the `skin_tones` column, it should work.
7. To see it fail do `emoji --list | select emoji name skin_tones` to force `skin_tones` column to show. It should hang and not show anything.

Further testing
This works `emoji --list | where shortcodes =~ wave` so it's not just about the skin_tones column but some specific data.

@devyn has been helping me troubleshoot and produced this
```
#0  0x00005b1e18f535f1 in <alloc::string::String as core::fmt::Write>::write_char ()
#1  0x00005b1e1a4b28ff in papergrid::grid::peekable::print_indent ()
#2  0x00005b1e1a4b267d in papergrid::grid::peekable::print_line ()
#3  0x00005b1e1a4b3377 in papergrid::grid::peekable::print_cell_line ()
#4  0x00005b1e1a4b0e6e in papergrid::grid::peekable::build_grid ()
#5  0x00005b1e1a4b214e in papergrid::grid::peekable::print_grid ()
#6  0x00005b1e1a4b6f46 in papergrid::grid::peekable::PeekableGrid<R,G,D,C>::build ()
#7  0x00005b1e1a4c9ee9 in <tabled::tables::table::Table as core::fmt::Display>::fmt ()
#8  0x00005b1e18f54916 in nu_table::table::NuTable::draw ()
```
and this by building in debug mode
```
proj nushell/nushell: emoji --list | select name skin_tones                                                                                                                                                               [⎇  main] 2024-05-06 15:47:27
Error:   × Main thread panicked.
  ├─▶ at /home/devyn/.cargo/registry/src/index.crates.io-6f17d22bba15001f/papergrid-0.10.0/src/grid/peekable.rs:715:16
  ╰─▶ attempt to subtract with overflow
  help: set the `RUST_BACKTRACE=1` environment variable to display a backtrace.
```

### Expected behavior

Show all the columns

### Screenshots

_No response_

### Configuration

|key|value|
|-|-|
|version|0.93.1|
|major|0|
|minor|93|
|patch|1|
|branch|main|
|commit_hash|e879d4ecaf75cb5dff02fb9f19a39848a477b916|
|build_os|macos-aarch64|
|build_target|aarch64-apple-darwin|
|rust_version|rustc 1.77.2 (25ef9e3d8 2024-04-09)|
|rust_channel|1.77.2-aarch64-apple-darwin|
|cargo_version|cargo 1.77.2 (e52e36006 2024-03-26)|
|build_time|2024-05-05 13:28:43 -05:00|
|build_rust_channel|release|
|allocator|mimalloc|
|features|dataframe, default, sqlite, system-clipboard, trash, which|
|installed_plugins|bexpand, bg, emoji, explore, file, formats, from_parquet, gstat, highlight, image, inc, json_path, jwalk, md, plist, pnet, polars, port_list, port_scan, qr_maker, query, query_git, regex, str_similarity, stress_internals|

### Additional context

_No response_

### LINKED ISSUE #13405: couldn't fit table in 269 columns
### Describe the bug

@zhiburt Looks like more table rendering problems. This one comes from opening the sample.parquet file in my [nu_plugin_parquet](https://github.com/fdncred/nu_plugin_parquet) repo.
```nushell
❯ open sample.parquet
Couldn't fit table into 269 columns!
```
I think this also has to do with data because there are some strange characters in the last column of this parquet file. I can get it to fully display if I make my font small enough (so i have 314 columns).

### How to reproduce

1. clone the nu_plugin_parquet repo side-by-side with the cloned nushell folder
2. cargo install --path .
3. plugin add ~/.cargo/bin/nu_plugin_parquet
4. exit
5. start nushell again
6. make sure you're in the nu_plugin_parquet folder
7. open sample.parquet

### Expected behavior

open the parquet file, displaying the columns that fit on the screen.

### Screenshots

_No response_

### Configuration

|key|value|
|-|-|
|version|0.95.1|
|major|0|
|minor|95|
|patch|1|
|branch|main|
|commit_hash|22379c9846713c3905bc3e4ef5f9187113f5a689|
|build_os|windows-x86_64|
|build_target|x86_64-pc-windows-msvc|
|rust_version|rustc 1.77.2 (25ef9e3d8 2024-04-09)|
|rust_channel|1.77.2-x86_64-pc-windows-msvc|
|cargo_version|cargo 1.77.2 (e52e36006 2024-03-26)|
|build_time|2024-07-18 16:15:34 -05:00|
|build_rust_channel|release|
|allocator|mimalloc|
|features|default, sqlite, system-clipboard, trash|
|installed_plugins|bg 0.5.0, emoji 0.5.0, explore, file 0.5.0, formats 0.95.1, gstat 0.95.1, highlight 1.2.0+0.95.0, inc 0.95.1, json_path 0.5.0, jwalk 0.5.0, md 0.5.0, parquet 0.6.0, periodic_table, pnet 1.7.0, polars 0.95.1, query 0.95.1, query_git 0.5.0, regex 0.5.0, str_similarity 0.5.0, stress_internals 0.95.1|

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by zhiburt**
Hi there

Here I am using latest tabled.

My tests shows it does fixes panics, but I am wanna be sure.

@fdncred could you verify that it does fixes those panics/errors?

Closes #13405 
Closes #12786

### CODE REVIEW

**Comment by fdncred** [comment]
can you please merge main? i'm getting weird issues because it's not on the latest main branch.

**Comment by zhiburt** [comment]
done

**Comment by fdncred** [comment]
Thanks! I went through my issues and recent PRs and this new tabled seem like it's fixing the issues while not breaking older fixes.
- It fixes #13405 
- It fixes #12786
- Fix is still working #13365
- Fix is still working #13336
- Fix is still working #13319
- Fix is still working #13287

**Comment by fdncred** [comment]
@zhiburt We're ready to land this if you can get the CI passing please.

**Comment by zhiburt** [comment]
Missed the timeline a bit apparently.
Just released the update to `crates.io`.

cc: @fdncred

**Comment by fdncred** [comment]
no worries, just need to get the ci green.

**Comment by fdncred** [comment]
would like to get this in as soon as possible. these table changes usually take a few iterations.

**Comment by fdncred** [comment]
@zhiburt when you get a chance, can you fix the remaining CI issues?

**Comment by zhiburt** [comment]
Hey @fdncred sorry;

It was not actually forgotten,
... Kind of ... got laid off unwillingly....

Hopefully it's all right.
But I'd double check.

Have a great weekend.

**Comment by fdncred** [comment]
Thanks. Still working so far!

**Comment by fdncred** [comment]
Sorry to hear about your job. Wish we could hire you on nushell but we have no funding.

**Comment by zhiburt** [comment]
> Sorry to hear about your job.

Thanks for carrying.

But no, thankfully I am still kicking :)
I meant to use _lay off_ as _put off_ as _postpone_ :sweat_smile:
Apparently there's no such collocation.... :disappointed_relieved:

**Pull request merged**
