### PR TITLE
nu-table: Bump tabled to 0.12.1

### LINKED ISSUE #9335: colors change when wrapping text
### Describe the bug

Found here https://github.com/nushell/nushell/pull/9326#issuecomment-1572693766

In the linked issue, if you change the search_result color to blue_reverse or any color reverse, and your terminal is shrunk small enough, you can see that wrapping is causing issues with colors.

I did this on the main branch in help.rs and it shows the problem too.
```rust
    // let style = Style::new().fg(White).on(Red);
    let style = Style {
        foreground: Some(nu_ansi_term::Color::Blue),
        is_reverse: true,
        ..Default::default()
    };
```

No wrapping
image

Wrapping
image

## Here's more research form the linked issue

Nice research. Here's a different test with mine set to blue_reverse
image
Then you can do this
```
help -f arg | last 2 | debug -r
```
and scroll down a bit and find this
```
val: "\u{1b}[37mReturns the floor of a number (l\u{1b}[0m\u{1b}[7;34marg\u{1b}[0m\u{1b}[37mest integer less than or equal to that number).\u{1b}[0m",
```

\e37m = white
Returns the floor of a number (l
\e0m = reset
\e7;34m = reverse blue
arg
\e0m = reset
\e37m = white
est integer less than or equal to that number).
\e0m = reset

We have a reset right before changing to white, so, that should reset the reverse bit. I'm not sure what's going on.

When you get a chance @zhiburt, we'd really appreciate you looking at the coloring during wrapping.

### How to reproduce

See above

### Expected behavior

color correctly

### Screenshots

_No response_

### Configuration

|key|value|
|-|-|
|version|0.80.1|
|branch|main|
|commit_hash|6481bf272c8a407aacddf91c171ebf78c0531889|
|build_os|windows-x86_64|
|build_target|x86_64-pc-windows-msvc|
|rust_version|rustc 1.67.1 (d5a82bbd2 2023-02-07)|
|rust_channel|1.67.1-x86_64-pc-windows-msvc|
|cargo_version|cargo 1.67.1 (8ecd4f20a 2023-01-10)|
|build_time|2023-05-26 09:15:25 -05:00|
|build_rust_channel|debug|
|features|default, sqlite, trash, which, zip|
|installed_plugins|from eml, from ics, from ini, from parquet, from plist, from vcf, gstat, hist, inc, json path, periodic-table, plot, pnet, query, query json, query web, query xml, regex, xyplot|

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by zhiburt**
close #9335 

I am not sure whether the fix was better to be delived as a minor bump but it is what is is.

Could you @fdncred test it somehow?
I did it by checking out back the the original commit before the PR refered in the issue.

### CODE REVIEW

**Comment by fdncred** [comment]
@zhiburt It's much closer but seems to still have some artifcats. Note the black on white arg. That was the only one that looked out of place. I wonder if it's because it's at the beginning after a line wrap?
image

**Comment by fdncred** [comment]
converting to draft until we can iron out the last issue

**Comment by zhiburt** [comment]
I wonder if you @fdncred could test it once again.

**Comment by fdncred** [comment]
I won't be able to test it this week on Windows. I'm out of town and don't have my Windows laptop. I'll ping you when I do test it though. Thanks!!

**Comment by fdncred** [comment]
I can't seem to reproduce the problem on my mac. I still haven't tested it on Windows yet though. But, so far, so good!

**Comment by fdncred** [comment]
Looks good on Windows too. I'm ready to land it.
image

**Comment by fdncred** [comment]
@zhiburt when you get a moment, can you fix the conflicts?

**Comment by fdncred** [comment]
well, i tried to fix the conflicts myself, which i did i guess, but now there are other test issues. darn it. when you get time @zhiburt it would be great to land this.

**Comment by fdncred** [comment]
CI looks green now. Are we ready to land?

**Comment by zhiburt** [comment]
> CI looks green now. Are we ready to land?

I hope so;

**Comment by fdncred** [comment]
Thanks!

**Pull request merged**
