### PR TITLE
Remove unnecessary `replace_in_variable`

### PR DESCRIPTION
**Pull request by IanManske**
# Description
`Expression::replace_in_variable` is only called in one place, and it is called with `new_var_id` = `IN_VARIABLE_ID`. So, it ends up doing nothing. E.g., adding `debug_assert_eq!(new_var_id, IN_VARIABLE_ID)` in `replace_in_variable` does not trigger any panic.

# User-Facing Changes
Breaking change for `nu_protocol`.

### CODE REVIEW

**Review by amtoine — COMMENTED** [review]
this sounds legit for the Nushell source base itself, but i'm wondering if people could be using these outside of Nushell, e.g. when writting plugins :thinking:

**Comment by IanManske** [comment]
Good point, I added a breaking change note. I think these methods were added as a workaround for the quirks of the `$in` variable, so I would be surprised if any plugins were using these methods.

**Comment by sholderbach** [comment]
Plugins currently only provide commands that operate on passed `Value`s so they don't see `Expression`s or `VarId`s at all that are part of the parsing and engine logic. 

So this is not part of any plugin API.

**Review by sholderbach — APPROVED** [review]
The old `Expression::replace_in_variable` was some heavy reading to see if there are no secret side effects but together with all tests still passing, I think we are good to say goodbye to this chunk.

**Pull request merged**
