### PR TITLE
Display script as it runs

### PR DESCRIPTION
**Pull request by bobhy**
An attempt to implement tracing of statements as they are executed, see #10037.

# Description

Still something of an experiment, but getting better.
You can now enable / disable tracing with `debug --trace` and `debug --no_trace`, so you don't see any tracing till you turn it on.
These set a flag in the eval `Stack` and all `PipelineElement`s evaluated with that stack are traced.  This produces both gaps and overlaps in the tracing output.  I'm struggling to find the right places to insert tracing to eliminate them, advice eagerly solicited!

Overlaps, where the same code is traced multiple times:
```
> do { debug --trace ;  let t = 22; let r = 33; let s = 44; $t}
entry #1:0     let t = 22
entry #1:0     22
entry #1:0     let r = 33
entry #1:0     33
entry #1:0     let s = 44
entry #1:0     44
entry #1:0     $t
22
```

A (fairly common) scenario where it works pretty well:
```
> cat test1.nu
export def main [] {
    debug --trace
    try {
        rm foo.foo
    } catch {
        echo "caught"
    }
}

> use test1.nu
|> test1
/home/bobhy/src/rust/nushell/test1.nu:3    
 try {
        rm foo.foo
    } catch {
        echo "caught"
    }
/home/bobhy/src/rust/nushell/test1.nu:4     rm foo.foo
/home/bobhy/src/rust/nushell/test1.nu:6     echo "caught"
caught

> touch foo.foo
> test1
/home/bobhy/src/rust/nushell/test1.nu:3    
 try {
        rm foo.foo
    } catch {
        echo "caught"
    }
/home/bobhy/src/rust/nushell/test1.nu:4     rm foo.foo
> 
```
If you enable tracing at the top of a block (e.g function) then statements in the block and statements within, `if-then-else` and `try-catch` will be traced (if they are executed).  Still some redundancy, though: the whole `if-then-else' is shown and then the individual statements that were actually executed.
I leaned into that by formatting the display as follows: If the traced statement is a single line, it is shown to the right of the source file and number.  But if it's a multiline statement, it is  displayed on the next line(s) after the source file line.  The result looks almost intentional (but only for this limited scenario).

If you embed a closure in the body of a function (or script, or other block), statements in the closure are not logged.(unless you add another `debug --trace` statement in the closure).  

```
> cat test2.nu
export def main [] {
    debug --trace
    try {
        do {| x | if $x == "grunt" {
                echo $"I am the walrus, hear me ($x)"
            } else {
                echo "meow"
            }
        } "grunt"
    } catch {
        echo "caught"
    }
}

> use test2.nu
> test2
/home/bobhy/src/rust/nushell/test2.nu:3    
 try {
        do {| x | if $x == "grunt" {
                echo $"I am the walrus, hear me ($x)"
            } else {
                echo "meow"
            }
        } "grunt"
    } catch {
        echo "caught"
    }
/home/bobhy/src/rust/nushell/test2.nu:4    
 do {| x | if $x == "grunt" {
                echo $"I am the walrus, hear me ($x)"
            } else {
                echo "meow"
            }
        } "grunt"
I am the walrus, hear me grunt
```
These are all artifacts of the current, simple-minded placement of tracing.

# User-Facing Changes

User will have to modify source files to enable tracing, by adding `debug --trace` statements and later removing them (in production).

# Tests + Formatting

# Future directions
- [x] Must provide some way to select which block should be traced and suppress tracing for everything else, certainly blocks in called functions but also child blocks within the block you're interested in.   This could by setting a variable or invoking a command in the block to be traced.  Variable could be named, e.g, `nu_trace`, or statement could be a subcommand of the existing `debug` command, like `debug trace`.  

- [ ] Maybe provide an option to show evaluated value of input, output and arguments.  Currently, we're just showing source code.

- [] Maybe also provide some formatting options: make filename / line number optional, colorize output, redirect trace to a file.

All feedback is welcome!

# After Submitting

### CODE REVIEW

**Comment by fdncred** [comment]
I think this is a cool idea. However, I'd change the left side to include datetime with millis, micros, or nanos. This way, it could also be a type of a profiler so you can see which lines are taking the most time.

Another idea is to only use this when a custom command has an attribute allowing it. Such as `#[profile]`.
```nushell
#[profile]
def foo [] {
  print 5
}
```

Finally, it would be cool to have it in a command, like the other tools in the debug category. Maybe call it `trace` or `nu-trace` or something to that effect.

I do have a question though; does it follow script and modules that are sourced/used? For instance, if you have a 1-line script that calls `source something.nu`, will it trace the lines in something.nu too?

**Comment by bobhy** [comment]
Hmm, there is an existing `profile` command that already reports
performance metrics.  For the current PR, I'm more focused on simply
showing the script statements as they're executed.
Using a command to manage enabling it makes good sense.

**Comment by fdncred** [comment]
> there is an existing `profile` command that already reports performance metrics.

yes, I realize that is what it's supposed to do. i've never had good luck with it, which is why i was suggesting adding it.

**Comment by cypof** [comment]
I hope this is still ongoing!

**Pull request closed without merging**
