### PR TITLE
Nix flake

### LINKED ISSUE #10352: Add Nix flake
### Describe the solution you'd like

Would be useful (IMO) to add a Nix flake (see for example https://github.com/helix-editor/helix/blob/master/flake.nix [the nixpkgs configuration for Nushell is [here](https://github.com/NixOS/nixpkgs/blob/master/pkgs/shells/nushell/default.nix) and home-manager is [here](https://github.com/nix-community/home-manager/blob/master/modules/programs/nushell.nix)]) so Nix users (using flakes) can easily point to a "nightly" version of Nushell.

This would allow users to configure an input and overlay to use the GitHub `main` version of Nushell.

This would also allow Nix users to contribute more easily.

(with `helix`:)

```nix
   # inputs ...
    helix = {
      url = "github:helix-editor/helix";
    };
    # ...
```
```nix
   # ...
    overlays = [
      (self: super: {
        inherit (helix.packages.aarch64-darwin) helix helix-unwrapped;
      })
    ];
    # ...
```

### PR DESCRIPTION
**Pull request by ysthakur**
Closes #10352 

# Description

This PR adds a `flake.nix` file so that Nushell can be available as a Nix flake.

One problem with this is that because the rust toolchain is gotten from `rust-toolchain.toml`, its hash must be manually entered into `flake.nix` every time the toolchain is updated. However, the toolchain isn't updated super frequently, so that might be acceptable.

# User-Facing Changes

Nix users will be able to use the `github:nushell/nushell` flake.

# Tests + Formatting

I'm not sure how to test this but I'll get around to it.

# After Submitting

TODO update documentation

### CODE REVIEW

**Comment by fdncred** [comment]
This was tried before https://github.com/nushell/nushell/pull/8155. I personally don't have a problem with it but other maintainers may.

**Comment by ysthakur** [comment]
Whoops, I didn't see that PR. I guess the concerns about CI still apply and MangoIV's flake works already (and is much more comprehensive)

**Comment by poelzi** [comment]
I guess it will become the new normal for us nix users to create flake PRs just to find out, somebody already did it and it did not get commited.  So sad the world is stuck in the last century sometimes

**Comment by crabdancing** [comment]
@poelzi Yeah, that's a mood. I wanted to quickly have my nix toolchain build & run the latest master branch just so I could try to reproduce some issues I saw, only to realize I'd have to rely on overlaying nixpkgs or using some less robust build system -- and I decided to not bother. :P

I actually do really wonder how many Nushell users happen to also use Nix, as both are massive paradigm shifts in conventional ways of doing things and could be classed as 'weird ML things'.

**Comment by fdncred** [comment]
We are open to having a nix flake here https://github.com/nushell/integrations

**Comment by crabdancing** [comment]
Oh! Well, I'd be willing to PR it there, but because of the way Nix flakes work, you'd have to bump the lock file on the `integrations` repo as this repo updates -- otherwise it'll keep reproducing earlier versions of the `nushell` repo instead of current.

This is because Nix flakes put a lot of emphasis on reproducibility and purity (minimizing wherever possible the outside changes that can affect the output of computations). It's great for being confident that something that works today can be made to work in 6 months or 10 years, even on a different system -- but it's not great for splitting up the flake into a separate repo, since the `flake.lock` _must_ be in version tracking somewhere, and has to be updated if you actually want the latest version.


That said, it's totally possible to automate flake.lock bumping with CI, and it is pretty reliable in my experience. How do you feel about that?

**Comment by fdncred** [comment]
I doubt any core-team member would be willing to do this manually so if there's a fool-proof automated way to do it in the integrations repo, then we could try that.

**Comment by crabdancing** [comment]
Honstly I'm not sure if it's worth it, if it can't go in the main repo -- it would cause a lot of bloat to the commit history of this repo, and add an extra point of failure. (E.g., if the main repo's path changes, or if CI automation breaks, or if MR key environment changes somehow).

It also doesn't inherit some of the other advantages, such as easily building and running forks of the main repo to quickly test out features. That advantage comes from flakes being tightly coupled with VCS, and each fork inheriting a flake.nix that specifies a 'ground truth' for the nix build process of a given project.

I'm not sure why they're so resistant to putting it in the main repo, but putting it in an external official git repo is barely better than just using an [unofficial flake](https://github.com/JoaquinTrinanes/nushell-nightly-flake) TBH.

**Comment by fdncred** [comment]
The main issue has always been that it requires the files to be in the root of the repo cluttering up the root folder.

**Comment by crabdancing** [comment]
Hmmm. I wonder if I could talk to the people making the implementation standard and see if they're open to having an alternate path. Am I right in inferring that having a single directory is acceptable (e.g., `nix` in the git root) but having two is not? (`flake.lock`, `flake.nix`)

**Comment by fdncred** [comment]
if it could go in our scripts folder then no one would care because it's out of site.

**Comment by crabdancing** [comment]
It looks like they also wanted to add `shell.nix` and `default.nix`. These do not have to be in the root directory, and in fact, don't have to be present at all. They are legacy niceties in the Nix world, and you can embed all the logic surrounding the imperative development environment in `devShells`, in the flake itself to minimize clutter if desirable.

If there was a PR that _only_ added two files to root, and didn't touch anything else, and was confirmed to result in a perfect reproducible build of Nushell, would that be acceptable?

**Comment by fdncred** [comment]
sure. if you put it in the scripts folder with nothing extra in the root of the repo, i'll land it.

**Pull request closed without merging**
