### PR TITLE
use stdin instead of crossterm::event::read

### PR DESCRIPTION
**Pull request by utouto97**
https://github.com/nushell/nushell/pull/10150#issuecomment-1721238336

# Description

Previously, I unified the approach using crossterm, but you will receive key events and store corresponding characters in a buffer.
However, this approach comes with the following issues:

1. Receiving characters as string rather than byte sequences.
2. The need for separate implementation of control codes like `^[`.
3. Inability to process input strings (due to focusing on key events).

Therefore terminal-size (https://github.com/nushell/nushell/pull/10150#issuecomment-1721238336) doesn't work.

So, I rewrite input command with stdin instead of crossterm, and this fixes input command that it worked well with terminal-size.

# User-Facing Changes

`input` command returns `Binary` type now instead of `String`.

# Tests + Formatting

`toolkit check pr`

- :green_circle: `toolkit fmt`
- :green_circle: `toolkit clippy`
- :green_circle: `toolkit test`
- :green_circle: `toolkit test stdlib`

# After Submitting

### CODE REVIEW

**Comment by utouto97** [comment]
```sh
> # get the terminal size with ansi escape codes
::: def terminal-size [] {
:::   let sz = (input (ansi size) --bytes-until-any 'R' -s)
:::   # $sz should look like this
:::   # Length: 9 (0x9) bytes | printable whitespace ascii_other non_ascii
:::   # 00000000:   1b 5b 33 38  3b 31 35 30  52             •[38;150R
:::   # let sz_len = ($sz | size).bytes
:::   let sz_len = ($sz | bytes length)
::: 
:::   # so let's skip the esc[ and R
:::   let r = ($sz | bytes at 2..($sz_len - 2))
::: 
:::   # $r should look like 38;150
:::   let size = ($r | split row ';')
::: 
:::   # output in record syntax
:::   {
:::     rows: ($size | get 0)
:::     columns: ($size | get 1)
:::   }
::: }
> terminal-size
╭─────────┬────╮
│ rows    │ 56 │
│ columns │ 11 │
╰─────────┴────╯
```

FYI: 
a little change in `let sz = (input (ansi size) --bytes-until-any 'R' -s)`.
- `--bytes-until` → `--bytes-until-any`
- add `-s`

**Comment by jntrnr** [comment]
Wouldn't this break arrow navigation and keyboard shortcuts?

**Comment by utouto97** [comment]
exactly...

if input command can accept a control codes, it will break arrow navigation and keyboard shortcuts. (since arrow navigation and ecs, etc... are expressed by control code)

I think we need to discuss how to handle control codes.

**Comment by fdncred** [comment]
Thanks so much @utouto97. This one is working now too.
```nushell
def get-bg [] {
    # have to hit control+g in kitty to get value in $bg
    let bg = (input $"(ansi -o '11;?')(ansi st)" --bytes-until-any '\' -s)
    # $bg should look like this
    # Length: 26 (0x1a) bytes | printable whitespace ascii_other non_ascii
    # 00000000:   1b 5d 31 31  3b 72 67 62  3a 31 39 31  39 2f 31 33   •]11;rgb:1919/13
    # 00000010:   31 33 2f 32  33 32 33 1b  5c 07                      13/2323•\•

    # jt's output
    # Length: 24 (0x18) bytes | printable whitespace ascii_other non_ascii
    # 00000000:   1b 5d 31 31  3b 72 67 62  3a 33 66 33  66 2f 33 66   •]11;rgb:3f3f/3f
    # 00000010:   33 66 2f 33  66 33 66 07                             3f/3f3f•

    # TODO figure how other ways that string can start so we can programmatically
    # calculate the start_index better. It's probably not always \x1b]11;rgb:
    let start_index = 9
    let end_index = ($bg | bytes index-of 0x[1b 5c])
    let term_data = ($bg | bytes at $start_index..$end_index)
    let rgb_string = ($term_data | decode utf-8)

    # Let's now get the rgb values by splitting on /
    # 1919/1313/2323
    let rgb = ($rgb_string | split row '/')
    let r = ($rgb | get 0)
    let g = ($rgb | get 1)
    let b = ($rgb | get 2)

    # Let's get the hex values here. Note `fmt` requires --features=extra now
    let red = (($r | into int -r 16) / 256 | math round | fmt).lowerhex
    let green = (($g | into int -r 16) / 256 | math round | fmt).lowerhex
    let blue = (($b | into int -r 16) / 256 | math round | fmt).lowerhex

    # output in record syntax
    {
        red: $red
        green: $green
        blue: $blue
        hex: $"#($red | str substring 2..)($green | str substring 2..)($blue | str substring 2..)"
        rgb: $"RGB(char lp)(($red | into int | fmt).display), (($green | into int | fmt).display), (($blue | into int | fmt).display)(char rp)"
    }
}
```

**Comment by utouto97** [comment]
Arrow keys are also represented using escape sequences. 
For example, `^[A`, and so on. 
Text color and cursor position are, of course, represented using escape sequences as well. 
`(ansi size)` is also like that, right? `

Therefore, I think the following considerations are necessary
1. Whether to accept escape sequences (I think it's necessary to accept them to make terminal-size or get-bg work).
1. If accepted, whether to render them (for example, if you input `abc←←`, how should it be displayed in the line? `a|bc`? (`|` means cursor). Do you disable rendering for other escape sequence except left and right arrow?)

**Comment by fdncred** [comment]
I don't remember having these issues before your original PR. How did it work back then? Whatever that is, I'd go with. e.g. Did we eat them? Did they display? Did we substitute them for other chars?

Seems like the point of `input` is to capture whatever the user types. So, if they're typing left arrow/right arrow, those would have to be bytes I think... maybe?

**Comment by sholderbach** [comment]
I think we should separate the different `input` behavior, possibly even into two commands. 
1. There should be a convenient command to get user input. The user may want to backspace/edit the input. (I think here #10150 made things a bit better as it fixed cancellation problems)
2. For stuff like `ansi size` it also seems necessary to have an option to read the raw bytes. (with the only exception that we should default to supporting cancellation/finalization by also looking for `Ctrl-C`/`Ctrl-D`/`Enter`

**Comment by fdncred** [comment]
I support your position @sholderbach, but it seems like we could just have two different parameters like I originally proposed. One for bytes and one for chars.

**Comment by sholderbach** [comment]
Is there a relevant use for `--until-char` that should not be expressed by `--bytes-until`? 

Implementing 1.) correctly is easy with crossterm.

Implementing 2.) separately is also relatively straightforward. Trying to get all of it in one loops is asking for trouble.

But if we want to have `--bytes-until` to change the behavior of `input` we could do it with separate loops.

**Comment by fdncred** [comment]
I can live with whatever you think the best solution is. I have no problem deferring to your expertise. I just want it fixed to work with bytes and chars.

**Comment by fdncred** [comment]
@utouto97 Could you update this PR with a parameter that handles the input from the `terminal-size` and `get-bg` custom commands above? If so, I think we would be able to land this and restore original functionality albeit differently with a parameter.

**Comment by fdncred** [comment]
@utouto97 We had another request for this type of functionality again today, capturing cursor position. Would it be possible for you to update this PR and have it work how it does today but perhaps add a `--raw` parameter to be able to capture these escapes if someone wants them?

**Comment by fdncred** [comment]
closed in favor of https://github.com/nushell/nushell/pull/14427

**Pull request closed without merging**
