### PR TITLE
Move `typos` config to repo root

### PR DESCRIPTION
**Pull request by IanManske**
# Description
Moves the `typos` config to the repository root directory. This allows one to run `typos` locally and have the config used automatically. Currently, one has to instead run `typos -c .github/.typos.toml`. Not sure if there is a reason why the config has to be in the `.github` folder.

### CODE REVIEW

**Comment by sholderbach** [comment]
Moved it in https://github.com/nushell/nushell/pull/10267 to make the root less cluttered.

**Comment by IanManske** [comment]
Oh I see. In this case, I think the having the convenience / expected behavior of running `typos` is more desirable. For example, this would be less confusing for new contributors.

**Comment by sholderbach** [comment]
Don't have much skin in the game, as I never run `typos` locally or even the `toolkit` :P Raw `cargo` for me, the rest of the things the CI can do for me :D

**Comment by IanManske** [comment]
Ok :smile: , then I'll go ahead and merge this.

**Pull request merged**
