### PR TITLE
move create_default_context out of cli.rs and into its own mod

### PR DESCRIPTION
**Pull request by stormasm**
Continuing to work on refactoring nu-cli.  Every time a new command gets added, deleted, or the name gets changed cli.rs has to be modified.  Also cli.rs is a fairly large (unwieldy) file, ---- and one of the reasons is because the method create_default_context has continued to grow over time as more commands get added.  Also, it would be nice in the future to make it easy for developers to implement their own cli.rs file depending on the application they might be developing...  It would be nice if they could use cli.rs as a model cli.rs in which to work from.  So they can much more easily do this with their own create_default_context function if its not inside cli.rs

### CODE REVIEW

**Comment by jonathandturner** [comment]
I'm not sure why there are failures. Looks like the quickcheck (a test we made to do some random testing for us) is failing on mac canary, but I can't see how your change would have changed it.

```
---- cli::tests::quickcheck_parse stdout ----
thread 'cli::tests::quickcheck_parse' panicked at 'attempt to subtract with overflow', crates/nu-parser/src/parse.rs:388:15
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread 'cli::tests::quickcheck_parse' panicked at 'attempt to subtract with overflow', crates/nu-parser/src/parse.rs:388:15
thread 'cli::tests::quickcheck_parse' panicked at 'attempt to subtract with overflow', crates/nu-parser/src/parse.rs:388:15
thread 'cli::tests::quickcheck_parse' panicked at 'attempt to subtract with overflow', crates/nu-parser/src/parse.rs:388:15
thread 'cli::tests::quickcheck_parse' panicked at 'attempt to subtract with overflow', crates/nu-parser/src/parse.rs:388:15
thread 'cli::tests::quickcheck_parse' panicked at 'attempt to subtract with overflow', crates/nu-parser/src/parse.rs:388:15
thread 'cli::tests::quickcheck_parse' panicked at 'attempt to subtract with overflow', crates/nu-parser/src/parse.rs:388:15
thread 'cli::tests::quickcheck_parse' panicked at 'attempt to subtract with overflow', crates/nu-parser/src/parse.rs:388:15
thread 'cli::tests::quickcheck_parse' panicked at '[quickcheck] TEST FAILED (runtime error). Arguments: ("$)")
Error: "attempt to subtract with overflow"', /Users/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/quickcheck-0.9.2/src/tester.rs:178:28
```

Can you fix the conflicts and we'll just re-run the tests and keep an eye on it?

**Comment by stormasm** [comment]
Run tests again....

**Comment by stormasm** [comment]
Thanks, I resolved the merge conflicts.
Hope you have a Happy New Year !!

**Comment by jonathandturner** [comment]
Looks good! And happy new year to you, too!

**Pull request merged**
