### PR TITLE
Completer: Fix fetch for CommandCompletions

### PR DESCRIPTION
**Pull request by dbuch**
# Description

Nushell crashes with panic due to invalid slicing into span content when completing with a pipeline.

1. ls -la | sele<Tab>
2. delete N chars (backspace)
3. Panic

Somewhere down the line as current line characters shrinks towards zero we see a crash with invalid slice indexing.

Last commit in this MR can be removed and discussed further in another MR.

# Tests

Make sure you've done the following:

- [ ] Add tests that cover your changes, either in the command examples, the crate/tests folder, or in the /tests folder.
- [ ] Try to think about corner cases and various ways how your changes could break. Cover them with tests.
- [ ] If adding tests is not possible, please document in the PR body a minimal example with steps on how to reproduce so one can verify your change works.

Make sure you've run and fixed any issues with these commands:

- [X] `cargo fmt --all -- --check` to check standard code formatting (`cargo fmt --all` applies these changes)
- [X] `cargo clippy --workspace --features=extra -- -D warnings -D clippy::unwrap_used -A clippy::needless_collect` to check that you're using the standard code style
- [X] `cargo test --workspace --features=extra` to check that all the tests pass

### CODE REVIEW

**Comment by kubouch** [comment]
I couldn't reproduce it with your reproduction steps. I managed to trigger the panic once but I'm not sure how, exactly.

Also, it would be the best if you could come up with a test that triggers the panic to make sure we don't regress.

**Comment by fdncred** [comment]
@dbuch @kubouch are we ready to land this?

**Comment by kubouch** [comment]
I wanted to see a reproducible example or a test because I cannot reproduce the panic. Seems OK to land but I'd wait a bit if @dbuch replies and we can land tomorrow otherwise.

**Comment by dbuch** [comment]
> I wanted to see a reproducible example or a test because I cannot reproduce the panic. Seems OK to land but I'd wait a bit if @dbuch replies and we can land tomorrow otherwise.

Yeah, you requested a reproducible example. Unfortunately I didn't manage to get that done due to insufficient time. I suspect I wont be able to make it this week either.

**Comment by kubouch** [comment]
I noticed the completion behaves differently. Without the PR, `ls -la | sele<tab>` would pull up a menu with the available `select` overloads, with your PR, it just auto-completes the first one.

So, I'd wait with merging until after the release since there are some side effects.

**Comment by fdncred** [comment]
Then let's convert to draft until we resolve this known issue.

**Comment by dbuch** [comment]
I plan to put this commit bc9309e46f3dbc9a14c5a854210aa7e6119b5611 in this inplace. Reedline do this even with assert!() (Perhaps, this codebase should do the same? See: [reedline/base.rs](https://github.com/nushell/reedline/blob/265e59966cea8d66672ae178d68f68b55edd178b/src/completion/base.rs#L17)) this will certainly shred light on this problem going forward. But it requires pending patches i unfortunately currently have locally. I'm able to allocated time during the comming weekend.
Feel free to close this for now, but please leave a second opinion about Span assert approach?
Side note: I have not tested this on current main/master branch so potentially this issue could be solved.

**Comment by fdncred** [comment]
@dbuch it seems reasonable to me. @kubouch what do you think of @dbuch's plan stated just above?

**Comment by kubouch** [comment]
I guess the `debug_assert!` is fine, but `assert!` is definitely a no-go: Nushell should never panic. It would be great to have repro steps and ideally a test to cover the fix.

**Comment by fdncred** [comment]
@dbuch do you have repro steps? and can you add a test to this pr for this situation?

**Comment by dbuch** [comment]
> @dbuch do you have repro steps? and can you add a test to this pr for this situation?
No I'm currently not using the configuration i used back then. I'm closing this for now.

**Comment by fdncred** [comment]
ok, thanks @dbuch for the pr anyway. we appreciate your contributions.

**Pull request closed without merging**
