### PR TITLE
Fix of a fix of #8671

### PR DESCRIPTION
**Pull request by zhiburt**
Hi @fdncred,

I accidentally noticed that your fix tricks wrapping a bit.

image

It must address it.

PS: I believe the issue was originally caused by a false positive of clippy. (maybe we shall report it I am not sure)

### CODE REVIEW

**Comment by zhiburt** [comment]
Maybe we shall add a few tests for regressions.

**Comment by zhiburt** [comment]
According to the empty table output.

Maybe it's better be

```
~/bin/nushell> [] | inspect                                                                                                                                                                           03/30/2023 07:45:05 PM
╭─────────────┬───────────╮
│ description │ list<any> │
├─────────────┴───────────┤
│                         │
╰─────────────────────────╯

╭────────────╮
│ empty list │
╰────────────╯
```

instead of

```
~/bin/nushell> [] | inspect                                                                                                                                                                           03/30/2023 07:46:14 PM
╭─────────────┬───────────╮
│ description │ list<any> │
├─────────────┴───────────┤
│                         │
├─────────────────────────┤
│ <empty data>            │
╰─────────────────────────╯

╭────────────╮
│ empty list │
╰────────────╯
```

**Comment by fdncred** [comment]
Thanks @zhiburt. If you want to change it so that `[] | inspect` works like this
```
~/bin/nushell> [] | inspect                                                                                                                                                                           03/30/2023 07:45:05 PM
╭─────────────┬───────────╮
│ description │ list<any> │
├─────────────┴───────────┤
│                         │
╰─────────────────────────╯
```
I'd be fine with that.

**Comment by zhiburt** [comment]
OUT OF CONTEXT;

Maybe we shall trim trailing new line here;
It must be done in `complete` command I believe.

```nu
~/bin/nushell> do -i { cat unknown.txt } | complete                                               03/31/2023 02:37:59 AM
╭───────────┬─────────────────────────────────────────────╮
│ stdout    │                                             │
│ stderr    │ cat: unknown.txt: No such file or directory │
│           │                                             │
│ exit_code │ 1                                           │
╰───────────┴─────────────────────────────────────────────╯
```

**Comment by zhiburt** [comment]
So I've found one more issue with wrong intersection in some cases.
Must be fixed.

But according to tests I spend good amount of time to do them.
But I did not figured out how to redirect `stderr` to stdout or something in this regard.
Because somehow `nu!` doesn't return correct `err`.
Specifically somehow it's term size is set to `0,0`.
But `stdout` is ok.

So yes it might be some internal issue not sure.

### reproducible

```rust
use nu_test_support::{nu, pipeline};

#[test]
fn inspect_basic_0() {
    let actual = nu!(pipeline("[[a b c]; [1 2 3] [4 5 [1 2 3]]] | inspect"));
    assert_eq!(
        actual.err,
        "╭─────────────┬───────────╮\
         │ description │ list<any> │\
         ├──────┬──────┼───────────┤\
         │ a    │ b    │ c         │\
         ├──────┼──────┼───────────┤\
         │ 1    │ 2    │ 3         │\
         │ 4    │ 5    │ [1 2 3]   │\
         ╰──────┴──────┴───────────╯"
    );
}
```

**Comment by fdncred** [comment]
> Maybe it shall trim trailing new line here;

IIRC, we've changed the trailing trim a few times. I think I'd rather just leave it to the person to do `| str trim` for now.

**Comment by fdncred** [comment]
> But I did not figured out how to redirect stderr to stdout or something in this regard.

I tried a few things too and couldn't figure it out. I think we should move forward with this and try and get the test working later. It may take much longer to get that test working. Thanks for trying.

**Comment by zhiburt** [comment]
So I've tried it too;
It might be also not expected IDK.

image

**Comment by fdncred** [comment]
Right. It's failing due to the nu pipeline not the stderr table. The way I get around that is by piping to `table`. However that doesn't fix the problem of stderr not being captured.

```
[[a b c]; [1 2 3] [4 5 [1 2 3]]] | inspect | table err> foo.txt
```

**Comment by fdncred** [comment]
I've tested this PR and it seems to work well on the test cases with `[] | inspect` and `{some: 1 huge: 2 record: 3 ...} | inspect`. Let's go ahead and land these fixes and come back to the stderr problem later.

**Pull request merged**
