### PR TITLE
allow for arguments in EDITOR and VISUAL env vars

### LINKED ISSUE #8051: EDITOR cannot contain arguments
### Describe the bug

I would like to set my `$env.EDITOR` so that it will cause this command to be run: `code --wait`. That's one command where `argv` is `['code', '--wait']`. I tried these two things:

```
let-env EDITOR = [ "code", "--wait" ]
# and
let-env EDITOR = "code --wait"
```

The first one says it wants a string, and got a `list<string>`, which makes sense. The second one says there's no command called `code --wait`. So I think it's trying to find a binary literally named `code --wait` in the path. Is there some way to do this, that I'm missing?

### How to reproduce

1. Run `let-env EDITOR = [ "code", "--wait" ]` or `let-env EDITOR = "code --wait"`
2. Run `config nu`
3. See error

### Expected behavior

Open `code` and pass in an argument `--wait`. Lots of editors need some sort of switch (I used to use `emacsclient -t`, because `emacsclient` by itself would fail if the emacs daemon isn't running).

### Screenshots

_No response_

### Configuration

| key                | value                                                            |
| ------------------ | ---------------------------------------------------------------- |
| version            | 0.74.0                                                           |
| branch             | makepkg                                                          |
| commit_hash        | 9a56665c6beee31e365ce17898056f1ff2db4094                         |
| build_os           | linux-x86_64                                                     |
| build_target       | x86_64-unknown-linux-gnu                                         |
| rust_version       | rustc 1.66.0 (69f9c33d7 2022-12-12) (Arch Linux rust 1:1.66.0-1) |
| cargo_version      | cargo 1.66.0                                                     |
| pkg_version        | 0.74.0                                                           |
| build_time         | 2023-01-10 22:53:04 +00:00                                       |
| build_rust_channel | release                                                          |
| features           | database, dataframe, default, trash, which, zip                  |
| installed_plugins  |                                                                  |

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by merelymyself**
# Description

Fixes #8051.

# User-Facing Changes

You can now put command arguments into the EDITOR and VISUAL config / env variables.

# Tests + Formatting

I don't know how to write tests for this. However, I set $env.EDITOR to "nvim -R" and it seemed to work.

# After Submitting

If your PR had any user-facing changes, update [the documentation](https://github.com/nushell/nushell.github.io) after the PR is merged, if necessary. This will help us keep the docs up to date.

### CODE REVIEW

**Comment by sholderbach** [comment]
Thanks for tackling this! Fixing the invocations of the editors is definitely the right place. 

Kind of annoying that we have this copy-paste duplication in the code for `config nu` and `config env` already. I think especially as the code grows with this patch it should be refactored out into its own function.

We also should validate that the `Ctrl-O` keybinding that launches an editor from reedline is tolerant to arguments.

**Comment by merelymyself** [comment]
I've opened a PR for reedline to make Ctrl+O work: https://github.com/nushell/reedline/pull/544

**Comment by fdncred** [comment]
Thanks for this + the refactor!

**Comment by bminer** [comment]
Note to users: Please use a list of arguments instead of space-delimited command.

See https://github.com/nushell/nushell/pull/10210

**Pull request merged**
