### PR TITLE
fix std help

### PR DESCRIPTION
**Pull request by WindSoilder**
# Description
Fixes: #12941

~~The issue is cause by some columns(is_builtin, is_plugin, is_custom, is_keyword) are removed in #10023~~
Edit: I'm wrong

# Tests + Formatting
Added one test for `std help`

### CODE REVIEW

**Comment by fdncred** [comment]
I think this is from #12832 because it change the `scope commands` columns and combined a bunch of the `is_*` columns into the `type` column. I talk about it here https://github.com/nushell/nushell/pull/12832#issuecomment-2105324677, right? Isn't this the problem?

**Comment by WindSoilder** [comment]
Oh, I haven't look into too much in #12832, I wrongly think it's because some method are removed in #10023.

I adjust the command type checking behavior to fit new changes.

**Review by fdncred — APPROVED** [review]
I think this looks better now. Thanks!

**Comment by NotTheDr01ds** [comment]
Thanks for the quick turnaround.  You beat me to this one! :-)

**Comment by fdncred** [comment]
Thanks

**Pull request merged**
