### PR TITLE
remove --not flag for 'str contains'

### PR DESCRIPTION
**Pull request by Skyppex**
# Description

This PR resolves an inconsistency between different `str` subcommands, notably `str contains`, `str starts-with` and `str ends-with`. Only the `str contains` command has the `--not` flag and a desicion was made in this #12781 PR to remove the `--not` flag and use the `not` operator instead. 

Before:
`"blob" | str contains --not o`
After:
`not ("blob" | str contains o)` OR `"blob" | str contains o | not $in`

> Note, you can currently do all three, but the first will be broken after this PR is merged.

# User-Facing Changes

- remove `--not(-n)` flag from `str contains` command
  - This is a breaking change!

# Tests + Formatting

- [x] Added tests
- [x] Ran `cargo fmt --all`
- [x] Ran `cargo clippy --workspace -- -D warnings -D clippy::unwrap_used`
- [x] Ran `cargo test --workspace`
- [ ] Ran `cargo run -- -c "use std testing; testing run-tests --path crates/nu-std"`
    - I was unable to get this working.
```
Error: nu::parser::export_not_found

  × Export not found.
   ╭─[source:1:9]
 1 │ use std testing; testing run-tests --path crates/nu-std
   ·         ───┬───
   ·            ╰── could not find imports
   ╰────
```
^ I still can't figure out how to make this work 😂 

# After Submitting

Requires update of documentation

### CODE REVIEW

**Review by IanManske — CHANGES_REQUESTED** [review]
Where possible we like to first deprecate commands and flags before removing them. Would you mind changing this to add a deprecation warning only? You can use #10827 as an example, thanks!

**Comment by Skyppex** [comment]
> Where possible we like to first deprecate commands and flags before removing them. Would you mind changing this to add a deprecation warning only? You can use #10827 as an example, thanks!

For sure, wasn't aware of this, i'll get it fixed :)

**Comment by Skyppex** [comment]
> Where possible we like to first deprecate commands and flags before removing them. Would you mind changing this to add a deprecation warning only? You can use #10827 as an example, thanks!

Which version should i say it will be removed? Based on the `register` command i'll assume two version up?

**Comment by IanManske** [comment]
> Which version should i say it will be removed?

Oh right, sorry. The next version is `0.94.0` which will be deprecation. So, version `0.95.0` will be removal.

**Review by IanManske — APPROVED** [review]
Thanks! This looks good.

**Comment by IanManske** [comment]
Oops, actually there's a clippy/formatting issue left to fix and then this is good to go.

**Comment by Skyppex** [comment]
Might be wise to rerun checks before merging since it doesn't seem like it did after the last commit. And now its aparently mergable 👀

**Review by IanManske — APPROVED** [review]
Thanks, merging :tada:

**Pull request merged**
