### PR TITLE
Table paging release

### PR DESCRIPTION
**Pull request by rezural**
This contains the last changes required to run off minus without using a branch.

It is currently pointing to the main branch of minus, once the release of minus from @arijit79 is pushed, then we can update Cargo.toml.

It also has some changes to respond to 'Q', and ESC to quit the pager. This is kind of unrelated, but I'll bundle it here, unless you want me to pull it out into a separate PR.

Thanks

### CODE REVIEW

**Comment by arijit79** [comment]
I am going to release a minor version today ASAP containing all the new changes.

**Comment by rezural** [comment]
> I am going to release a minor version today ASAP containing all the new changes.

Many thanks for being so helpful Arijit!

**Comment by andrasio** [comment]
THANK YOU!!! @rezural @arijit79 @fdncred @jonathandturner

**Comment by jonathandturner** [comment]
Nice!

**Pull request merged**
