### PR TITLE
Change history menu keybinding from ctrl+x to ctrl+r

### PR DESCRIPTION
**Pull request by rgwood**
# Description

~This is a draft PR for now; let's discuss before merging it.~

This PR changes the default history menu keybinding to `ctrl+r` from `ctrl+x`. I think `ctrl+r` is a better, more discoverable keybinding for Nu's most polished history search feature; it's probably the first keybinding users of Bash, Powershell, and fzf will try. I might be missing good reasons to keep the current keybinding, let me know if I am!

This does hide the simple reverse-i-search functionality that Reedline binds to `ctrl+r` by default; I'm personally OK with that, I think reverse-i-search is quite limited compared to the history menu.

# Tests

I did some manual testing and confirmed that this works, both with a fresh install of Nu and with an old default config file. If using the old config file, you'll end up with history search bound to both `ctrl+r` and `ctrl+x`.

- [x] `cargo fmt --all -- --check` to check standard code formatting (`cargo fmt --all` applies these changes)
- [x] `cargo clippy --all --all-features -- -D warnings -D clippy::unwrap_used -A clippy::needless_collect` to check that you're using the standard code style
- [x] `cargo build; cargo test --all --all-features` to check that all the tests pass

### CODE REVIEW

**Comment by herlon214** [comment]
wow i didn't even know about the `ctrl-x`, I've always been using `ctrl-r`  :sweat_smile:

**Comment by fdncred** [comment]
I'm probably fine with it. However, I use ctrl-x and ctrl-z together. Do you have a proposal for moving ctrl-z also? If you hit ctrl-x again and again the menu grows backward in history, since the history is sorted reverse, but then if you hit ctrl-z it switches direction and allow you to page the other direction through the menu. I just bring this functionality up because ctrl-r is a tiny bit different that ctrl-x but it still wouldn't bother me personally to move it.

I have no idea if what I'm using is the default or not so here's my keybindings.
```
    {
       name: trigger-history-menu
       modifier: control
       keycode: char_x
       mode: emacs
       event: { 
         until: [
           { send: menu name: history_menu }
           { send: menupagenext }
         ]
       }
    }
    {
        name: trigger-history-previous
        modifier: control
        keycode: char_z
        mode: emacs
        event: { until: [
            { send: menupageprevious }
            { edit: undo }
            ]
        }
    }
```

**Comment by rgwood** [comment]
@fdncred Good question, I've never used `ctrl+z`/`menupageprevious` before.

Playing around with it now... I don't know if I *would* use it; I don't think I have a need for multiple history pages. Maybe someone who uses that feature has an opinion?

**Comment by rgwood** [comment]
Hmm. I tried `ctrl+shift+r` for `trigger-history-previous` but I couldn't get it to work; seems like Nu supports `control | shift` as a modifier but Crossterm (or my terminal?) only detects control when both shift+control are pressed.

**Comment by rgwood** [comment]
After playing with multiple history pages a bit more: I think left arrow and right arrow would be better keys for changing pages, but that would require Reedline changes.

**Comment by fdncred** [comment]
if `keybindings listen` can see the key combinations, then we should be able to map them unless there's a bug.

**Comment by rgwood** [comment]
`keybindings listen` can only see `ctrl+r` when I type `ctrl+shift+r`. Probably another one of those horrible terminal compatibility things...

**Comment by fdncred** [comment]
interesting. I wonder if we have a bug. Mine can't see ctrl+shift+r either in WezTerm on Mac.

**Comment by rgwood** [comment]
Just pushed a change to remove `menupagenext` and `menupageprevious` bindings. I don't know if they're important enough to include in the default Nu config, and I think Reedline could have some default keybindings for them. Will ask the Reedline folks to see if they agree.

**Comment by rgwood** [comment]
I think this is finally ready to go.

After some further discussion it seems like changing Reedline arrow navigation is a bit complicated right now. I'll leave `ctrl+x` and `ctrl+z` bound to page navigation. `ctrl+r` will just open the history menu but do nothing about page navigation.

I've also removed the hardcoded Rust config for `ctrl+x` and `ctrl+z`. The Rust configuration was redundant, intended for situations where users don't have a config file or they create their own. But in practice, this seems to cause more problems than it solves.

**Comment by fdncred** [comment]
> I've also removed the hardcoded Rust config for `ctrl+x` and `ctrl+z`. The Rust configuration was redundant, intended for situations where users don't have a config file or they create their own. But in practice, this seems to cause more problems than it solves.

I'm not sure if this part is the right thing to do. Technically our code defaults are supposed to match our default_config.nu. Our process is to try to make the config match the hard-coded defaults. We can't do that everywhere, for instance, the vi keybindings, but at least that's what we try to do.

**Comment by rgwood** [comment]
> Technically our code defaults are supposed to match our default_config.nu.

I don't quite understand the thinking behind this. Why specify the config twice? I think that's confusing for users; I'm remembering a situation where I removed a keybinding only to find that it was still in effect.

**Comment by fdncred** [comment]
The idea is that the default_config.nu is the "truth source" and it demonstrates how to set the default configurations. It's supposed to work the same way, with or without the default_config.nu. JT and I have had this discussion a couple times. If we want to change it, that's fine, but for now, the default_config shows what the defaults are set to.

**Comment by rgwood** [comment]
I see, thanks for the explanation. I'll ask around and see how people feel about changing that setup.

**Comment by rgwood** [comment]
Wasn't able to get much engagement on this point so I've re-hardcoded the new keybindings. I'll try to convince people that hardcoding the keybindings is bad another time :)

@fdncred I think this is good to go now; did you have any concerns other than the hardcoding?

**Comment by fdncred** [comment]
I think it's fine to land. It probably violates the 'Principle of least astonishment' but maybe that's ok since our history access can be different. Let's see what the people say.

**Pull request merged**
