### PR TITLE
Scraping multiple tables

### PR DESCRIPTION
**Pull request by luccasmmg**
Related to #4004 

In @fdncred PR he talked about in the cases where there are multiple tables the current code will only return the first one found, but that it would better if a list of tables were returned. This PR adds this possibility. 

New behaviour:

```
❯ fetch https://en.wikipedia.org/wiki/Microsoft_Excel | selector -t [Format Extension Description] 
───┬─────────────────
 0 │ [table 5 rows]  
 1 │ [table 12 rows] 
───┴─────────────────
```
You can then access the tables with "nth and flatten" the flatten is necessary because curerntly nth doesn't auto expand inner tables. Alternatively you can put everything in a parenthesis and add the number of the row.

Ex 1:

```
❯ fetch https://en.wikipedia.org/wiki/Microsoft_Excel | selector -t [Format Extension Description] | nth 1 | flatten
────┬──────────────┬───────────┬───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
 #  │    Format    │ Extension │                                                                                                  Description                                                                                                  
────┼──────────────┼───────────┼───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
  0 │ Spreadsheet  │ .xls      │ Main spreadsheet format which holds data in worksheets, charts, and macros                                                                                                                                    
  1 │ Add-in (VBA) │ .xla      │ Adds custom functionality; written in VBA                                                                                                                                                                     
  2 │ Toolbar      │ .xlb      │ The file extension where Microsoft Excel custom toolbar settings are stored.                                                                                                                                  
  3 │ Chart        │ .xlc      │ A chart created with data from a Microsoft Excel spreadsheet that only saves the chart. To save the chart and spreadsheet save as .XLS. XLC is not supported in Excel 2007 or in any newer versions of Excel. 
  4 │ Dialog       │ .xld      │ Used in older versions of Excel.                                                                                                                                                                              
  5 │ Archive      │ .xlk      │ A backup of an Excel Spreadsheet                                                                                                                                                                              
  6 │ Add-in (DLL) │ .xll      │ Adds custom functionality; written in C++/C, Visual Basic, Fortran, etc. and compiled in to a special dynamic-link library                                                                                    
  7 │ Macro        │ .xlm      │ A macro is created by the user or pre-installed with Excel.                                                                                                                                                   
  8 │ Template     │ .xlt      │ A pre-formatted spreadsheet created by the user or by Microsoft Excel.                                                                                                                                        
  9 │ Module       │ .xlv      │ A module is written in VBA (Visual Basic for Applications) for Microsoft Excel                                                                                                                                
 10 │ Library      │ .DLL      │ Code written in VBA may access functions in a DLL, typically this is used to access the Windows API                                                                                                           
 11 │ Workspace    │ .xlw      │ Arrangement of the windows of multiple Workbooks                                                                                                                                                              
────┴──────────────┴───────────┴───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
```
Ex 2:

```

❯ (fetch https://en.wikipedia.org/wiki/Microsoft_Excel | selector -t [Format Extension Description]).0
───┬──────────────────────────────┬───────────┬──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
 # │            Format            │ Extension │                                                                                                         Description                                                                                                          
───┼──────────────────────────────┼───────────┼──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
 0 │ Excel Workbook               │ .xlsx     │ The default Excel 2007 and later workbook format. In reality, a Zip compressed archive with a directory structure of XML text documents. Functions as the primary replacement for the former binary .xls format, although it 
   │                              │           │ does not support Excel macros for security reasons. Saving as .xlsx offers file size reduction over .xls[38]                                                                                                                 
 1 │ Excel Macro-enabled Workbook │ .xlsm     │ As Excel Workbook, but with macro support.                                                                                                                                                                                   
 2 │ Excel Binary Workbook        │ .xlsb     │ As Excel Macro-enabled Workbook, but storing information in binary form rather than XML documents for opening and saving documents more quickly and efficiently. Intended especially for very large documents with tens of   
   │                              │           │ thousands of rows, and/or several hundreds of columns. This format is very useful for shrinking large Excel files as is often the case when doing data analysis.                                                             
 3 │ Excel Macro-enabled Template │ .xltm     │ A template document that forms a basis for actual workbooks, with macro support. The replacement for the old .xlt format.                                                                                                    
 4 │ Excel Add-in                 │ .xlam     │ Excel add-in to add extra functionality and tools. Inherent macro support because of the file purpose.                                                                                                                       
───┴──────────────────────────────┴───────────┴──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
```

### CODE REVIEW

**Comment by fdncred** [comment]
looking good luccas - just a few more clippy warnings and we'll be able to land it. i'm so excited to try it out!!!

**Comment by fdncred** [comment]
boom! Thanks @luccasmmg !!!

**Comment by fdncred** [comment]
I'm loving this @luccasmmg. What are your thoughts on this?

```
fetch https://en.wikipedia.org/wiki/Microsoft_Excel | selector -t [Year Name Version Comments] | nth 0 | flatten
╭────┬──────┬────────────┬───────────────────────────────────────────┬───────────────────────────────────────────────────────────────────────────────────────────────────────────────╮
│ #  │ Year │ Name       │ Version                                   │ Comments                                                                                                      │
├────┼──────┼────────────┼───────────────────────────────────────────┼───────────────────────────────────────────────────────────────────────────────────────────────────────────────┤
│  0 │ 1987 │ Excel 2    │ Old version, no longer maintained: 2.0    │ Renumbered to 2 to correspond with contemporary Macintosh version. Supported macros (later known as Excel 4   │
│    │      │            │                                           │ macros).                                                                                                      │
│  1 │ 1990 │ Excel 3    │ Old version, no longer maintained: 3.0    │ Added 3D graphing capabilities                                                                                │
│  2 │ 1992 │ Excel 4    │ Old version, no longer maintained: 4.0    │ Introduced auto-fill feature                                                                                  │
│  3 │ 1993 │ Excel 5    │ Old version, no longer maintained: 5.0    │ Included Visual Basic for Applications (VBA) and various object-oriented options                              │
│  4 │ 1995 │ Excel 95   │ Old version, no longer maintained: 7.0    │ Renumbered for contemporary Word version. Both programs were packaged in Microsoft Office by this time.       │
│  5 │ 1997 │ Excel 97   │ Old version, no longer maintained: 8.0    │ Missing column: 'Comments'                                                                                    │
│  6 │ 2000 │ Excel 2000 │ Old version, no longer maintained: 9.0    │ Part of Microsoft Office 2000, which was itself part of Windows Millennium (also known as "Windows ME").      │
│  7 │ 2002 │ Excel 2002 │ Old version, no longer maintained: 10.0   │ Missing column: 'Comments'                                                                                    │
│  8 │ 2003 │ Excel 2003 │ Old version, no longer maintained: 11.0   │ Released only 1 year later to correspond better with the rest of Microsoft Office (Word, PowerPoint, etc.).   │
│  9 │ 2007 │ Excel 2007 │ Old version, no longer maintained: 12.0   │ Missing column: 'Comments'                                                                                    │
│ 10 │ 2010 │ Excel 2010 │ Older version, yet still maintained: 14.0 │ Due to superstitions surrounding the number 13, Excel 13 was skipped in version counting.                     │
│ 11 │ 2013 │ Excel 2013 │ Older version, yet still maintained: 15.0 │ Introduced 50 more mathematical functions (available as pre-packaged commands, rather than typing the formula │
│    │      │            │                                           │ manually).                                                                                                    │
│ 12 │ 2016 │ Excel 2016 │ Current stable version: 16.0              │ Part of Microsoft Office 2016                                                                                 │
╰────┴──────┴────────────┴───────────────────────────────────────────┴───────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
```
image

A couple things here that we might want to work on. I'm interested in your thoughts.
1. Note that the `Version` column only has 2.0, 3.0, etc in the screenshot but in the scrape, we include the tool tip text. I'm wondering if we should keep the tooltip text. btw - i have no idea how we'd remove it but it may be possible.
2. Notice in the `Comments` column next to Version 8.0, 10.0, & 12.0 it says, "Missing column: 'Comments'" - I wonder if it is helpfule to have this missing text information or if it would be better to just have it empty. This is even more noticable in `nth 1`.

**Comment by fdncred** [comment]
I've also noticed some bugs with `selector -t []`, not that i'm saying this is your bug. I'm sure it's all mine because that `[]` code was weird. But notice this,
```
fetch https://en.wikipedia.org/wiki/Microsoft_Excel | selector -t [] | nth 5 | flatten
╭───┬─────────────────────────────────────────────────────────┬───────────────────────────────────────────────────────────┬────────────────────────────────────────────────────────────╮
│ # │ Extension                                               │ Description                                               │ Format                                                     │
├───┼─────────────────────────────────────────────────────────┼───────────────────────────────────────────────────────────┼────────────────────────────────────────────────────────────┤
│ 0 │ Excel Macro-enabled Workbook, .xlsm, As Excel Workbook, │ Excel Binary Workbook, .xlsb, As Excel Macro-enabled      │ Excel Workbook, .xlsx, The default Excel 2007 and later    │
│   │ but with macro support.                                 │ Workbook, but storing information in binary form rather   │ workbook format. In reality, a Zip compressed archive with │
│   │                                                         │ than XML documents for opening and saving documents more  │ a directory structure of XML text documents. Functions as  │
│   │                                                         │ quickly and efficiently. Intended especially for very     │ the primary replacement for the former binary .xls format, │
│   │                                                         │ large documents with tens of thousands of rows, and/or    │ although it does not support Excel macros for security     │
│   │                                                         │ several hundreds of columns. This format is very useful   │ reasons. Saving as .xlsx offers file size reduction over   │
│   │                                                         │ for shrinking large Excel files as is often the case when │ .xls[38]                                                   │
│   │                                                         │ doing data analysis.                                      │                                                            │
╰───┴─────────────────────────────────────────────────────────┴───────────────────────────────────────────────────────────┴────────────────────────────────────────────────────────────╯
```
versus this
```
fetch https://en.wikipedia.org/wiki/Microsoft_Excel | selector -t [Format Extension Description] | nth 0 | flatten
╭───┬──────────────────────────────┬───────────┬───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╮
│ # │ Format                       │ Extension │ Description                                                                                                                               │
├───┼──────────────────────────────┼───────────┼───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┤
│ 0 │ Excel Workbook               │ .xlsx     │ The default Excel 2007 and later workbook format. In reality, a Zip compressed archive with a directory structure of XML text documents.  │
│   │                              │           │ Functions as the primary replacement for the former binary .xls format, although it does not support Excel macros for security reasons.   │
│   │                              │           │ Saving as .xlsx offers file size reduction over .xls[38]                                                                                  │
│ 1 │ Excel Macro-enabled Workbook │ .xlsm     │ As Excel Workbook, but with macro support.                                                                                                │
│ 2 │ Excel Binary Workbook        │ .xlsb     │ As Excel Macro-enabled Workbook, but storing information in binary form rather than XML documents for opening and saving documents more   │
│   │                              │           │ quickly and efficiently. Intended especially for very large documents with tens of thousands of rows, and/or several hundreds of columns. │
│   │                              │           │ This format is very useful for shrinking large Excel files as is often the case when doing data analysis.                                 │
│ 3 │ Excel Macro-enabled Template │ .xltm     │ A template document that forms a basis for actual workbooks, with macro support. The replacement for the old .xlt format.                 │
│ 4 │ Excel Add-in                 │ .xlam     │ Excel add-in to add extra functionality and tools. Inherent macro support because of the file purpose.                                    │
╰───┴──────────────────────────────┴───────────┴───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
```
something just isnt' detecting things right. I figure it has to do with me trying to determine row headers versus column headers. do you have any thoughts on this one too?

**Comment by luccasmmg** [comment]
Hello @fdncred in relation to your points, i think i kind of know a solution to the first two ones and i know what is causing the third one.

1. In relation to the "Old version, no longer maintained" stuff, i think we can add something like this `*:not([style*="display: none"])` by default somewhere probably in the cell_content function. This will at least remove the cases where the `display: none` is inline in the html(Which is the case in this wikipedia table that you refer).
image

2. I think that this is just a matter of changing the code here. to be a empty string, maybe have a uniform empty message would make for easier scripting, somethink like just "Missing column", that way we at least show the user that we tried to find but couldn't. 
image
3. Its actually because of this piece of code right here. I know because i had the same problem, basically when you use an empty [] as input it thinks that the tables are rotated, the problem is that if we remove that, the tables that are actually rotated will be broken. This wasn't a problem before because we almost never would use [] since we had no way of knowing the return table, since it would only return the first table found. I was actually going to ask you about this in a few days when i thought you would have more free time. 
image
4. The next thing that i wanted to do, was about this that you talked about "when the column headers are the same on multiple tables on the same page, maybe combine them all into one table?", i wanted to know your opinion on how to present this option to the user, i was thinking on having a flag like "-c --concat" or "-s --squash" that would get the list of tables and try to reduce then by matching the headers, i don't think that would be too hard, i just don't know if a flag is the best way to allow the user to do it.

**Comment by luccasmmg** [comment]
I think i was able to solve the problem with []. 
image
Without messing with the 90 degrees table 
image
Altough i think the solution is kind of ugly, when i remove that chunk of code that i talked about in the previous comment, the result was that the 90 degrees tables don't build properly, all the rows get empty.
image
 So what i did was check if there are any rows not missing, which would indicate that the table was not rotated 90 degrees, the problem i think would be in the situations where we have a huge table rotated 90 degrees, and the code would have to do a check value by value to see if everything is empty. The important piece of code is here. 
image

**Comment by fdncred** [comment]
> In relation to the "Old version, no longer maintained" stuff, i think we can add something like this *:not([style*="display: none"]) 

ya, that sounds like a good plan. I hadn't considered that.

> I think that this is just a matter of changing the code here.

right. I remembered that one. I'm just not sure if it's better to say **Missing Column** or name the missing column? I'm up for whatever you think is best.

> Its actually because of this piece of code right here. 

Maybe using `-t []` should be changed like have some other option to indicate you want all the tables `--all` and have another flag that indicates tables are rotated like `--rotated` so we don't have to guess if tables should be rotated or not and can just leave it up to the user.

> The next thing that i wanted to do, was about this that you talked about "when the column headers are the same on multiple tables...

I kind of like just returning it the way you do now. if there happens to be two tables with the same column headers, returning two tables, like you do now, is fine I think. maybe we should leave that up to the user to decide if they want them combined with some other command in the pipeline and just leave it the way it is.

>  think i was able to solve the problem with [].

this looks great! good job

> Without messing with the 90 degrees table

yipee!!!

> Altough i think the solution is kind of ugly, when i remove that chunk of code that i talked about in the previous comment, the result was that the 90 degrees tables don't build properly, all the rows get empty.

uh oh, this is no good. maybe my idea about letting the user decide if it needs to be rotated is a better way to handle this?

> So what i did was check if there are any rows not missing...

hmmm, if you think you have a good heuristic for this, then let's try it. otherwise, we may want to do something else.

as i get time, i'll check here but i may not be very reliable for the next few days for the reasons i already told you about in chat.  keep up the good work on this!!!

**Comment by luccasmmg** [comment]
@fdncred i decided to open a PR with my changes so that you can see it better, and when it comes to the "display: none" stuff i spend the entire night yesterday trying but couldn't sorry, i will try to pick it up this issue after the weekend, hope everything is well with you and that stuff you talked about.

**Comment by fdncred** [comment]
i saw it. thanks. i'm fine with taking small PRs continually tweaking this stuff until we get it the way we want it. no rush. the 'display: none' isn't a deal-breaker. if we have to leave it in there, that's fine for now.

**Pull request merged**
