### PR TITLE
Add --directory (-D) flag to ls, list the directory itself instead of its contents

### PR DESCRIPTION
**Pull request by moxuze**
# Description

Add --directory (-D) flag to ls, list the directory itself instead of its contents.
Now we can list a specified directory itself:
```shell
/home/moxuze〉['/usr/bin' '/usr/bin/nu'] | each { |it| ls -D $it } | flatten
╭───┬─────────────┬──────┬──────────┬────────────────╮
│ # │    name     │ type │   size   │    modified    │
├───┼─────────────┼──────┼──────────┼────────────────┤
│ 0 │ /usr/bin    │ dir  │ 56.0 KiB │ 32 minutes ago │
│ 1 │ /usr/bin/nu │ file │ 38.7 MiB │ 9 hours ago    │
╰───┴─────────────┴──────┴──────────┴────────────────╯
/home/moxuze〉['./.' '.' '..' './nushell' 'nushell/install-all.sh'] | each { |it| ls -D $it } | flatten
╭───┬────────────────────────┬──────┬─────────┬───────────────╮
│ # │          name          │ type │  size   │   modified    │
├───┼────────────────────────┼──────┼─────────┼───────────────┤
│ 0 │ .                      │ dir  │ 4.0 KiB │ 4 minutes ago │
│ 1 │ .                      │ dir  │ 4.0 KiB │ 4 minutes ago │
│ 2 │ ..                     │ dir  │ 4.0 KiB │ 3 months ago  │
│ 3 │ nushell                │ dir  │ 4.0 KiB │ 10 hours ago  │
│ 4 │ nushell/install-all.sh │ file │   826 B │ 10 hours ago  │
╰───┴────────────────────────┴──────┴─────────┴───────────────╯
```

# Tests

Make sure you've done the following:

- [x] Add tests that cover your changes, either in the command examples, the crate/tests folder, or in the /tests folder.
- [x] Try to think about corner cases and various ways how your changes could break. Cover them with tests.

Make sure you've run and fixed any issues with these commands:

- [x] `cargo fmt --all -- --check` to check standard code formatting (`cargo fmt --all` applies these changes)
- [x] `cargo clippy --workspace --features=extra -- -D warnings -D clippy::unwrap_used -A clippy::needless_collect` to check that you're using the standard code style
- [x] `cargo test --workspace --features=extra` to check that all the tests pass

### CODE REVIEW

**Comment by WindSoilder** [comment]
Hi, thanks for your pr.  

Would you please add tests to `crates/nu-command/tests/commands/ls.rs` to make sure it's working?

**Comment by moxuze** [comment]
> Hi, @moxuze thanks for your contribution :)
> 
> Would you please add tests to `crates/nu-command/tests/commands/ls.rs` to make sure it's working?

Thanks for your reminding. I added two tests to `crates/nu-command/tests/commands/ls.rs`.

**Comment by fdncred** [comment]
@moxuze if you can fix up these tests that are failing we can land this PR.

**Comment by moxuze** [comment]
> @moxuze if you can fix up these tests that are failing we can land this PR.

Done, my expected string contains `/` so that tests failed under windows system. XD

**Comment by fdncred** [comment]
Thanks

**Pull request merged**
