### PR TITLE
Factorize HTTP commands code

### PR DESCRIPTION
**Pull request by jaudiger**
# Description

In order to work on https://github.com/nushell/nushell/issues/2741, I'm preparing the code.

# User-Facing Changes

Both commands do support the timeout option.

**But the timeout argument `-t, --timeout` has been migrated to `-m, --max-time`**. I had to make a choice since there is another option using the short command `t` which is "content-type".

# Tests + Formatting

Don't forget to add tests that cover your changes.

Make sure you've run and fixed any issues with these commands:

- `cargo fmt --all -- --check` to check standard code formatting (`cargo fmt --all` applies these changes)
- `cargo clippy --workspace -- -D warnings -D clippy::unwrap_used -A clippy::needless_collect` to check that you're using the standard code style
- `cargo test --workspace` to check that all tests pass

# After Submitting

If your PR had any user-facing changes, update [the documentation](https://github.com/nushell/nushell.github.io) after the PR is merged, if necessary. This will help us keep the docs up to date.

### CODE REVIEW

**Comment by jaudiger** [comment]
Not ready for review yet, I'm still working a bit on it. I'm just opening it, in case someone else was already working on it to prevent to do twice the same work.

**Comment by fdncred** [comment]
nice. looking good so far.

**Comment by jaudiger** [comment]
The PR should be ready to be reviewed.

**Comment by fdncred** [comment]
I marked this as a breaking change because `-t` was removed from `http get`. After looking at the code, it seems that it can still remain because the `-t` for content-type is used on `http post`. `http get -tt` wouldn't interfere with `http post -t`, right?

**Comment by jaudiger** [comment]
That's what I meant, indeed. I wanted to have the same subset of options across the HTTP commands. What I have in  mind would be to also support setting a payload while using `http get`, since there are use cases where on a GET a payload can be provided (the same thing could apply for DELETE command).

Having said that, and after looking at the arguments from cURL:

```
➜ curl --help all | grep time
     --connect-timeout <fractional seconds> Maximum time allowed for connection
     --expect100-timeout <seconds> How long to wait for 100-continue
     --happy-eyeballs-timeout-ms <milliseconds> Time for IPv6 before trying IPv4
     --keepalive-time <seconds> Interval time for keepalive probes
 -m, --max-time <fractional seconds> Maximum time allowed for transfer
 -R, --remote-time        Set the remote file's time on the local output
     --retry-delay <seconds> Wait time between retries
     --retry-max-time <seconds> Retry only within this period
 -y, --speed-time <seconds> Trigger 'speed-limit' abort after this time
 -z, --time-cond <time>   Transfer based on a time condition
     --trace-time         Add time stamps to trace/verbose output
```

```
➜ curl --help all | grep content
 -F, --form <name=content> Specify multipart MIME data
     --ignore-content-length Ignore the size of the remote resource
```

```
➜ curl --help all | grep type
     --cert-type <type>   Certificate type (DER/PEM/ENG/P12)
     --key-type <type>    Private key file type (DER/PEM/ENG)
     --proxy-cert-type <type> Client certificate type for HTTPS proxy
     --proxy-key-type <type> Private key file type for proxy
     --proxy-tlsauthtype <type> TLS authentication type for HTTPS proxy
     --tlsauthtype <type> TLS authentication type
```

The cURL tool does rely on the user to set properly the Content-Type header. This header has to be set separately using: `-H "Content-Type: application/json"` where with `http post`, you have to use the argument `-t`. Also, another difference between the arguments is cURL calculates automatically the header Content-Length. On our side, it has to be set by the user through `-l`.

Finally, regarding the timeout initial problem, we rely on this method from reqwest to set the time to wait: https://docs.rs/reqwest/latest/reqwest/blocking/struct.ClientBuilder.html#method.timeout
The documentation states:
> Set a timeout for connect, read and write operations of a Client.

It appears to be equivalent to the cURL argument: `-m, --max-time` (https://curl.se/docs/manpage.html#-m). I also noticed that the time given to this argument can be a float where in nushell we only accept integer for `-t`.

There are so many things to continue to work on for the HTTP commands :laughing: 

So, what's your inputs on that? I can update at least the timeout argument to better match to the cURL CLI.

**Comment by fdncred** [comment]
From my perspective, I'd rather people find parameters that they're used to using in curl or wget. Although, I'm not sure everyone would agree with me. We're not trying to be curl or wget but it's nice if the parameters with the same long/short names do similar things.

**Comment by jaudiger** [comment]
I understand your point. So, this time the arguments from `wget`:

```
➜ wget --help | grep time
  -N,  --timestamping              don't re-retrieve files unless newer than
                                     requests in timestamping mode
       --no-use-server-timestamps  don't set the local file's timestamp by
  -T,  --timeout=SECONDS           set all timeout values to SECONDS
       --dns-timeout=SECS          set the DNS lookup timeout to SECS
       --connect-timeout=SECS      set the connect timeout to SECS
       --read-timeout=SECS         set the read timeout to SECS
```

Should I go for `-m, --max-time` or `-T, --timeout` ? I would eventually tend to go for the second solution, but curl is more used than wget IMO. So, the floor is yours!

**Comment by fdncred** [comment]
I'd go with whichever one is more popular, which I assume is curl.

**Comment by jaudiger** [comment]
@fdncred I just add a commit to do the modification.

**Comment by fdncred** [comment]
LGTM. Let's try it out.

**Pull request merged**
