### PR TITLE
Display aliases and custom commands in which; fix #2810

### LINKED ISSUE #2810: `which` for inspecting aliases and custom commands
**Is your feature request related to a problem? Please describe.**
I'd like to use `which` to inspect aliases and custom commands. Currently its pretending that custom commands are built-ins in aliases don't exist.

```
> alias d = gid pd
> which d
> def docker-ps [] { docker ps --format '{{json .}}' | from json -o }
> which docker-ps
───┬───────────┬──────────────────────────┬─────────
 # │    arg    │           path           │ builtin
───┼───────────┼──────────────────────────┼─────────
 0 │ docker-ps │ nushell built-in command │ Yes
───┴───────────┴──────────────────────────┴─────────
/Users/jzaefferer/dev/other/nushell(main)>
```

**Describe the solution you'd like**
```
> which d
───┬───────────┬──────────────────────────┬─────────
 # │    arg    │           path           │ builtin
───┼───────────┼──────────────────────────┼─────────
 0 │ d │ nushell alias │ No
───┴───────────┴──────────────────────────┴─────────
> which docker-ps
───┬───────────┬──────────────────────────┬─────────
 # │    arg    │           path           │ builtin
───┼───────────┼──────────────────────────┼─────────
 0 │ docker-ps │ nushell custom command │ No
───┴───────────┴──────────────────────────┴─────────
```
Maybe add another column for both that prints the definition of the alias or custom command?

**Describe alternatives you've considered**
bash/native `which` has the same behaviour for aliases - it pretends they don't exist. That is not something to follow!

### PR DESCRIPTION
**Pull request by LhKipp**
Example output of nu after the commit is applied:

```shell
/home/leo/repos/nushell(feature/which_inspect_alias)> def docker-ps [] { docker ps --format '{{json .}}' | from json -o }
/home/leo/repos/nushell(feature/which_inspect_alias)> which docker-ps
───┬───────────┬────────────────────────┬─────────
 # │    arg    │          path          │ builtin
───┼───────────┼────────────────────────┼─────────
 0 │ docker-ps │ Nushell custom command │ No
───┴───────────┴────────────────────────┴─────────
/home/leo/repos/nushell(feature/which_inspect_alias)> alias d = gid pd
/home/leo/repos/nushell(feature/which_inspect_alias)> which d
───┬─────┬───────────────┬─────────
 # │ arg │     path      │ builtin
───┼─────┼───────────────┼─────────
 0 │ d   │ Nushell alias │ No
───┴─────┴───────────────┴─────────
```

### CODE REVIEW

**Comment by fdncred** [comment]
@LhKipp oooo, nice! Thanks for this. Quesiton - Does it also show such details with `help commands`?

**Comment by LhKipp** [comment]
> Question - Does it also show such details with `help commands`?
I will update the documentation. :)

**Comment by LhKipp** [comment]
> @LhKipp oooo, nice! Thanks for this. Quesiton - Does it also show such details with `help commands`?

I updated the documentation. The usage is now:
```rust
    fn usage(&self) -> &str {
        "Finds a program file, alias or custom command."
    }
```
I hope that answers your question.

**Comment by LhKipp** [comment]
> @LhKipp oooo, nice! Thanks for this. Quesiton - Does it also show such details with `help commands`?

I updated the documentation. I am open for suggestions for better wording the usage :)

**Comment by LhKipp** [comment]
Currently the macos Jobs fail due to some errors in files I didn't touch.:

```shell
error: this pattern reimplements `Option::unwrap_or`
  --> crates/nu-table/src/table.rs:49:18
   |
49 |           let bv = match bool_value {
   |  __________________^
50 | |             Some(v) => v,
51 | |             None => false,
52 | |         };
   | |_________^ help: replace with: `bool_value.unwrap_or(false)`
   |
   = note: `-D clippy::manual-unwrap-or` implied by `-D warnings`
   = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#manual_unwrap_or

error: explicit lifetimes given in parameter types where they could be elided (or replaced with `'_` if needed by type declaration)
  --> crates/nu-table/src/wrap.rs:77:1
   |
77 | pub fn column_width<'a>(input: &[Vec<Subline<'a>>]) -> usize {
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   |
   = note: `-D clippy::needless-lifetimes` implied by `-D warnings`
   = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#needless_lifetimes

error: explicit lifetimes given in parameter types where they could be elided (or replaced with `'_` if needed by type declaration)
   --> crates/nu-table/src/wrap.rs:103:1
    |
103 | fn split_word<'a>(cell_width: usize, word: &'a str) -> Vec<Subline<'a>> {
    | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |
    = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#needless_lifetimes

error: aborting due to 3 previous errors

```

**Comment by JosephTLyons** [comment]
This is likely because of the new Clippy lints in Rust 1.49, which I've added here:

https://github.com/nushell/nushell/pull/2835

Hopefully, the PR I linked passes all tests.  If it does and gets merged in, then you can just merge master back into your PR to fix these lints.

**Comment by JosephTLyons** [comment]
I believe if you merge master into your branch, it should be good to go now.

**Comment by LhKipp** [comment]
> I believe if you merge master into your branch, it should be good to go now.

Thank you :) It works now.

**Comment by jonathandturner** [comment]
Nice!

**Pull request merged**
