### PR TITLE
support tab completion cycling

### PR DESCRIPTION
**Pull request by amtoine**
should close https://github.com/nushell/nushell/issues/7202

# Description
i have been annoyed enough by this missing feature, so let's add that to Nushell without requiring any user configuration :smirk: 

# User-Facing Changes
this PR should allow tab completion cycling everytime, without requiring the user to use the default config files or add the following keybindings to their config
```nushell
    {
        name: completion_menu
        modifier: none
        keycode: tab
        mode: [emacs vi_normal vi_insert]
        event: {
            until: [
                { send: menu name: completion_menu }
                { send: menunext }
                { edit: complete }
            ]
        }
    }
```

### :test_tube: try it out
from the root of the repo, one can try `<tab>` in each of the following cases:
- `cargo run -- -n` to load Nushell without any config
- `cargo run -- --config crates/nu-utils/src/sample_config/default_config.nu --env-config crates/nu-utils/src/sample_config/default_env.nu` to load the default configuration
- `cargo run` to load the user configuration

## before
- `<tab>`, `ls <tab>` and `str <tab>` only work with the second `cargo run`, i.e. when loading the default config files

## after
- `<tab>` should cycle through the available commands
- `ls <tab>` should cycle through the available files and directories
- `str <tab>` should cycle the subcommands of `str`

in all three cases

# Tests + Formatting

# After submitting

### CODE REVIEW

**Comment by amtoine** [comment]
just amending the commit message, it was not... professional :eyes: :laughing:

**Comment by fdncred** [comment]
If you're going to enable `tab`, you should probably also enable `shift-tab` to go backwards through the list.
```nushell
  {
    name: completion_menu_previous
    modifier: shift
    keycode: backtab
    mode: [emacs vi_normal vi_insert]
    event: { send: menuprevious }
  }
```

**Comment by amtoine** [comment]
@fdncred 
i think it's already there :yum: 

https://github.com/nushell/nushell/blob/af79eb294/crates/nu-utils/src/sample_config/default_config.nu#L340-L346

https://github.com/nushell/nushell/blob/af79eb294/crates/nu-cli/src/reedline_config.rs#L485-L489

**Comment by fdncred** [comment]
@amtoine ah, ok. thanks. seems odd that we'd have shift-tab and not tab. probably an oversight on our part. i'm good with landing this.

**Comment by fdncred** [comment]
Thanks!

**Comment by amtoine** [comment]
> ah, ok. thanks. seems odd that we'd have shift-tab and not tab. probably an oversight on our part. i'm good with landing this.
>
might have splitted through my config sync PR :eyes:

**Pull request merged**
