### PR TITLE
Remove list of cell path support for `select` and `reject`

### PR DESCRIPTION
**Pull request by IanManske**
# Description
Requires each of the rest args for `select` and `reject` to be a cell path instead of the current `oneof(cellpath, list<cellpath>`. This simplifies the command signatures and code for `select` and `reject`. Users can now spread lists into the rest arguments instead of providing them as is.

For example,
```nushell
ls | select [name size]
```
must now be
```nushell
ls | select ...[name size]
```

# User-Facing Changes
Breaking change for the `select` and `reject` command signatures.

### CODE REVIEW

**Comment by fdncred** [comment]
I imagine there are a few commands this technique could be used.

**Comment by IanManske** [comment]
> I imagine there are a few commands this technique could be used.

Already one step ahead :p
`select` and `reject` were the only commands that had this special handling, so I only fixed them.

> It would be good if there could be an example that demonstrates something like this `ls | select ...[name size]`

Yeah, I can add some list spread examples. The example in the PR is contrived, I should have made it `ls | select ...$cols`.

**Comment by sholderbach** [comment]
Great that this looks both nicer externally and internally!

**Comment by fdncred** [comment]
Thanks!

**Pull request merged**
